### ISSUE TITLE
Make node-oracledb installable via standard 'npm' install

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#1]
We are working on it...

**Comment by theothermattm** [comment]
I am not a C coder, but if you need help with anything in particular related to javascript code or documentation, let me know, I can try to contribute.  I'll keep it in mind as I try out the module.

**Comment by cjbj** [comment]
@theothermattm we'd love  to understand how you use the DB in your Node.js applications, how you scale (cluster?), deal with LOBs, deal with NLS, deal with DATEs etc.  Let us know what you find, either here as Issues or on the OTN forum https://community.oracle.com/community/database/developer-tools/node_js/content  Also checkout CONTRIBUTING.md

**Comment by theothermattm** [comment]
Will do, thank you!

**Comment by tbranyen** [comment]
I published this module to NPM.  If anyone from Oracle would like to take over publishing, I'd be happy to transfer.

**Comment by atiertant** [comment]
+1 it whould be great that oracle publish a corporate npm package

**Comment by jeffm13** [comment]
+1

**Comment by sagiegurari** [comment]
I did npm install oracledb without knowing its not officially published by oracle corp.
I think that is an issue that it is published by someone else.
how hard is it to add a line "npm publish ." at the end of the official oracle release build process?

**Comment by cjbj** [comment]
@sagiegurari we need Legal and management sign off.  We're working on it.

**Comment by tbranyen** [comment]
@sagiegurari what issue is that exactly? I publish the exact version'd tag that comes from this Git repository.  This is fairly standard practice with NPM and Node.  Keep in mind NPM does not sign packages so if you're worried about security, there's a lot more to worry about than who is publishing.  If you'd like to pull the official (in your mind) source, you could always add:

``` javascript
"oracledb": "oracle/node-oracledb"
```

in your package.json to fetch directly from GitHub.

**Comment by sagiegurari** [comment]
issue is that when you publish to npm, it does not validate that it is exactly what you have in your git.
it just packages what you have locally in your directory that you published.
it is not that i don't appreciate your efforts, but i think it is a security issue and we need to be careful about it.

putting github url in package.json means it is not versioned which is not a good solution as you can't reproduce a build.
you can't go forward and backward in versions as you always take a snapshot of the current git status.
thats only good for testing something new (like this package).

"Legal and management sign off" - Ya i'm familiar with those :)
hopefully this would be handled quickly.

**Comment by tbranyen** [comment]
I hear ya @sagiegurari, but for now you absolutely can version with that syntax.  Simply add the SHA that matches the version you're looking for.  For instance the latest version (0.3.1) could be versioned in your package.json with the following:

``` javascript
"oracledb": "oracle/node-oracledb#619e9a8fa6625a2c5ca3e1a2ba10dbdaab5ae900"
```

I completely agree that it would be better for all parties if Oracle could get approval for publishing rights.  Until then I will maintain a clean Git repository and only publish exact tags.  Have your security team do an audit of files coming from NPM will go a long way from assuming everything there is published under official sources.

**Comment by theothermattm** [comment]
Thank you, Tim!  And good tip on using the SHA in your package.json to verify things... Did not know that.

**Comment by cjbj** [comment]
@tbranyen Did you see node-oracledb 0.4.1 is out?

**Comment by cjbj** [comment]
@theothermattm you can also use a tag in package.json:

```
    "dependencies": {
	"oracledb": "oracle/node-oracledb#v0.4.1"
    },
```

**Comment by tbranyen** [comment]
All set!

**Comment by cjbj** [comment]
@tbranyen are you ready to do a handover to me?  See email from a few days ago.

**Comment by cjbj** [comment]
node-oracledb 0.4.2 is now officially on https://www.npmjs.com/package/oracledb. Thanks to @tbranyen for setting it up and doing a smooth handover.

INSTALL.md has been updated to recommend NPM in the base installation steps.

**Comment by sagiegurari** [comment]
thanks, this is good news.
