### ISSUE TITLE
require oracledb or node-oracledb?

### ISSUE THREAD

**Issue by rinie** [oracle/node-oracledb#10]
The module is called node-oracledb, but the examples use  require('oracledb').
To make this work under windows I had to rename the directory to oracledb.

With regards to how I would like to use the module is: maximum SQL, minimum Javascript or objects.
I would like to see select * from ... and calls of stored procedures work smoothly.
Like I use sqlplus but additional:
- control long running queries
- paging without explicit modification of queries 

LOBS/CLOBS etc is not what I use Oracle for. Stored procedures, Views and plain SQL suffices.
So more a script runner of SQL that can also be executed in SQLPLUS but with control over timeouts and paging would be my target.

A level of API with events instead of callbacks would be nice:
'data', 'error', 'timeout', ...

**Comment by cjbj** [comment]
If you install exactly as the INSTALL.md example with 'npm install -g' you need require('oracledb').  The intention is for this to also be true after installation from npmjs.com - once we are on the npmj.com registry, see issue #1 

Thanks for the other comments. Regarding paging, is the 12c OFFSET / FETCH NEXT syntax useful? https://docs.oracle.com/database/121/SQLRF/statements_10002.htm#BABEAACC
You might also be interested in how pagination is handled in Oracle Rest Data Services 3.0 Beta http://www.oracle.com/technetwork/developer-tools/rest-data-services/ords-30-downloads-2373781.html
https://docs.oracle.com/cd/E56351_01/doc.30/e56293/develop.htm#AELIG3000

**Comment by cjbj** [comment]
Update: I didn't see it in a quick scan of the Beta ORDS 3.0 doc, but the statement of direction mentions one cool paging feature: that pagination can be made consistent from the time of the initial query execution, so new/change records don't change the page boundaries.
http://www.oracle.com/technetwork/developer-tools/rest-data-services/overview/ordsv3sod-2186242.pdf

**Comment by rinie** [comment]
NPM recommends that typical install is local, so -g global ought to be optional?

12c Paging command is explicit in the SQL (although the paging layer could add that), at work still only 11.2 or even 10...
