### ISSUE TITLE
Troubles with encoded data

### ISSUE THREAD

**Issue by Darynh** [oracle/node-oracledb#100]
Hello everyone !

I'm running into an encoding issue.
The database I'm working on is in AMERICAN_AMERICA.WE8ISO8859P15 according to SELECT USERENV ('language') FROM DUAL.

However, the database contains french words, which contains accents (such as "é"). If I log onto the SQL server (via web manager) and query it, it returns without the accents (thus missing letters).

If I query through node-oracledb, I get a question mark instead of the letter.
I tried setting NLS_LANG (which wasn't set prior) into :
> AMERICAN_AMERICA.WE8ISO8859P15 or FRENCH_FRANCE.WE8ISO8859P15 => doesn't change anything ;
> AMERICAN_AMERICA.UTF8 or FRENCH_FRANCE.UTF8 => "[Error: ORA-01406: fetched column value was truncated]" and doesn't change anything.

The thing is : the company's main web app runs with this database, and can show accents.

Any ideas ?

Thank you in advance !

Windows 8.1
Node v0.10.28
NetBeans

Sample code :
oracledb.getConnection(
  {
    user          : "...",
    password      : "...",
    connectString : "..."
  },
             function(err, connection)
              {
                if (err) { console.error(err); return; }
                console.log("OK");
                var r;
                connection.execute("...",
                            function(err, result){
                                      if (err) { console.error(err); return; }
                                      //console.log(result.rows);
                                      r = result.rows;
                                      console.log(r);
    })
);

**Comment by cjbj** [comment]
Possibly related to https://github.com/oracle/node-oracledb/issues/62

**Comment by Darynh** [comment]
Hi !

Sorry for the long wait, had to urgent matters to handle.
I've gone through the topic but I don't seem to be able to find any help with my issue.

Interestingly, I cannot seem to reproduce the ORA-01406 error : setting NLS_LANG to
AMERICAN_AMERICA.WE8ISO8859P15
FRENCH_FRANCE.WE8ISO8859P15
AMERICAN_AMERICA.UTF8
FRENCH_FRANCE.UTF8
doesn't change anything, I will still get '?' instead of special characters, like 'é'.

Any ideas ?

**Comment by cjbj** [comment]
@Darynh can you post a complete script with data, NLS settings in the DB and client, and the  expected output?

**Comment by Darynh** [comment]
As requested :
**Code sample**
```javascript
var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "user",
    password      : "pwd",
    connectString : "192.168.1.1"
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
    sql, // basic select
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log(result.rows);
      });
  });
```
**Output :**
C:\>node test.js
[ [ 'Groupe Sanguin ABO Rh?sus' ] ]

**Expected output :** [ [ 'Groupe Sanguin ABO Rh**é**sus' ] ]

**NLS Client** 
Tried with the following NLS_LANG environment variables but no changes
* NLS_LANG not set 
* AMERICAN_AMERICA.WE8ISO8859P15
* FRENCH_FRANCE.WE8ISO8859P15
* AMERICAN_AMERICA.UTF8
* FRENCH_FRANCE.UTF8

**NLS Database**

*NLS_DATABASE_PARAMETERS*

PARAMETER |	VALUE
----------------- | --------
NLS_LANGUAGE |	AMERICAN
NLS_TERRITORY |	AMERICA
NLS_CURRENCY |	$
NLS_ISO_CURRENCY |	AMERICA
NLS_NUMERIC_CHARACTERS |	.,
NLS_CHARACTERSET |	WE8ISO8859P15
NLS_CALENDAR |	GREGORIAN
NLS_DATE_FORMAT |	DD-MON-RR
NLS_DATE_LANGUAGE |	AMERICAN
NLS_SORT |	BINARY
NLS_TIME_FORMAT |	HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT |	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT |	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT |	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY |	$
NLS_COMP |	BINARY
NLS_LENGTH_SEMANTICS |	BYTE
NLS_NCHAR_CONV_EXCP |	FALSE
NLS_NCHAR_CHARACTERSET |	AL16UTF16
NLS_RDBMS_VERSION |	11.2.0.3.0

**Comment by cjbj** [comment]
@Darynh thank you

**Comment by cjbj** [comment]
@Darynh try with node-oracledb 1.0.  We made some NLS changes.  See https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md and https://github.com/oracle/node-oracledb/blob/master/doc/api.md#nls

**Comment by brunodenis** [comment]
Tried the exact same scenario with latest node-oracledb (1.10) without success. any help would be appreciated.

documentation is saying that it is possible (https://github.com/oracle/node-oracledb/blob/master/doc/api.md#nls) but it does not saying how. 

Thanks in advance,

env : node 4.4.1
node-oracledb :  1.10
DB Server : windows server 2012, Oracle 12c
Node server : windows 7 x64

**Comment by cjbj** [comment]
@brunodenis this old issue is closed.  Please open a new one and give enough (i.e more) information including a testcase and data.  Thanks!
