### ISSUE TITLE
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 6.9.1 (darwin, x64) when debugging and using different nodejs versions 

### ISSUE THREAD

**Issue by rstor1** [oracle/node-oracledb#1000]
I have a question about using different nodejs versions and oracledb. When I use nvm use 10.11.0 and try degugging in vscode, I am getting the error in the screenshot below. It is telling me to install instant client in ~/lib or /usr/local/lib but I already have it installed in /opt/oracle folder. Do I also have to have it installed in a different place if I am going between nodejs versions? Will this be an issue if I have it installed in two different places?
#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  **10.11.0**

2. What is your node-oracledb version? **3.0.0**

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as? **Launch Program in vscode for debugging**

4. What error(s) you are seeing?

![npm rebuild and njs045](https://user-images.githubusercontent.com/43070937/47441765-dbe6fe80-d77e-11e8-8f4a-abe645562a32.png)

5. What OS (and version) is Node.js executing on? **MacOS 10.13.6**

6. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed? **12.2 installed in /opt/oracle path**

7. What is your Oracle Database version? **Not installed, using a remote DB**

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

![in lib folder](https://user-images.githubusercontent.com/43070937/47441888-308a7980-d77f-11e8-8d00-716262362d4a.png)

9. What Oracle environment variables did you set?  How *exactly* did you set them? 

10. Do you have a small, single Node.js script that immediately runs to show us the problem? No

**Comment by dmcghan** [comment]
I don't think the issue is the instant client, but rather with node-oracledb's binary. The pre-compiled binary is specific to a particular version of Node.js. So, when you swap the Node.js version in NVM, you'll need to reinstall the driver. A simple `npm uninstall oracledb` followed by a `npm install oracledb` should do.
