### ISSUE TITLE
Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="67")

### ISSUE THREAD

**Issue by macdoor** [oracle/node-oracledb#1001]
Can not install pre-built binary packages of node-oracledb version 3.0 under node 11.
<img width="897" alt="2018-10-27 12 28 37" src="https://user-images.githubusercontent.com/29733517/47599577-db9b6d00-d9e3-11e8-8ba6-c82577112041.png">

**Comment by anthony-tuininga** [comment]
Yes, this is expected. Node 11 binaries have not been created yet. Until they are you'll have to build yourself from source.

**Comment by cjbj** [comment]
We'll release a 3.0.1 with binaries for Node.js 11.  It's being tested right now.

**Comment by cjbj** [comment]
I've released node-oracledb 3.0.1 which has a pre-built binary for Node 11.
