### ISSUE TITLE
BLOB Support

### ISSUE THREAD

**Issue by kumarmugu** [oracle/node-oracledb#101]
Hi @cjbj and all,

I am using v0.4.1 for my NodeJS application. I want to save the image files in the oracle database.
Is this driver currently supporting to store/retrieve images (BLOB) ?

If can you please share the samples/Help.
Thanks for the help and support

K.Mugunthan

**Comment by cjbj** [comment]
@kumarmugu LOB support is being worked on.  I'll close this as a duplicate of https://github.com/oracle/node-oracledb/issues/19

**Comment by hola5456** [comment]
hello @cjbj ,
i need LOB Support please 
Thanks
