### ISSUE TITLE
Core dump when doing CQN on same connection when 50>records insert and commit

### ISSUE THREAD

**Issue by alpertandogan** [oracle/node-oracledb#1018]
Platform OEL x64 7.6 , 18cR3 se2 , Memory 128 gb (70gb sga)
Nodejs,oracledb (final version)

------------server.js
async function myCallback(message) {
 console.log(message); 
}
function dbopen
 try {
    await oracledb.createPool(dbConfig);
    conn = await oracledb.getConnection();
    await conn.subscribe('mysub', {
      callback: myCallback,
      sql:      "SELECT * FROM msgtable"  // the table to watch
    });
....
----------

On Oracle call from other clients   (works weel small number loop )
---------
for i in 1...50 loop
update msgtable ; commit; 
end loop;

------------------------
Nodejs Client site 

SQLNET.ora 
SQLNET.SEND_TIMEOUT=60000
DIAG_ADR_ENABLED=FALSE
DIAG_SIGHANDLER_EANABLED=FALSE
DIAG_DDE_ENABLED=FALSE

-------------------------------Trace  file generated---- Client area
ORA-24550: signal received: [si_signo=11] [si_errno=0] [si_code=1] [si_int=-343398671] [si_ptr=0x2f9ceb8826f1] [si_addr=(nil)]
kpedbg_dmp_stack()+374<-kpeDbgCrash()+210<-kpeDbgSignalHandler()+121<-skgesig_sigactionHandler()+272<-__sighandler()<-_ZN15njsSubscription13CreateMessageEP16dpiSubscrMessage()+73<-_ZN15njsSubscription19ProcessNotificationEP10uv_async_s()+101<-uv_version_string()+283<-uv_get_process_title()+3136<-uv_run()+405<-_ZN4node5StartEPN2v87IsolateEPNS_11IsolateDataERKSt6vectorISsSaISsEES9_()+933<-_ZN4node5StartEiPPc()+841<-__libc_start_main()+245
Segmentation fault (core dumped)

------------------------------trace file with SQLNET.ORA parameters..
@8|8|tmdLLns72"18435_140578045536128|host_2627812140_110||1|1|1|1|1|
02jx-+5%dbgexProcessError*diag_dde*dbgex.c*HIj1XzB2SRms72~
9Ljx++E3$a3incident_id`1g:dbgrimbid_begin_incdump*dbgrim.c*incident_file*1MG101vddvv"
C4j3++1$dbgrim.c*2n1P"
TKj3++$dbgrim.c*0109"
EKj3++E$dbgrim.c*Error Stack*1308"
C4j3++1$dbgrim.c*3023"
UKj3++$dbgrim.c*0306"

**Comment by alpertandogan** [comment]
node --log_all test.js   dump documents
[ora_18435_140578045536128_trm.txt](https://github.com/oracle/node-oracledb/files/2657602/ora_18435_140578045536128_trm.txt)
[ora_18435_140578045536128.txt](https://github.com/oracle/node-oracledb/files/2657603/ora_18435_140578045536128.txt)

[tracelog.txt](https://github.com/oracle/node-oracledb/files/2657592/tracelog.txt)

**Comment by anthony-tuininga** [comment]
Can you take a look at this [comment](https://github.com/oracle/node-oracledb/issues/1009#issuecomment-444326508)? This appears to be a duplicate.
