### ISSUE TITLE
NJS-040: connection request timeout

### ISSUE THREAD

**Issue by alpertandogan** [oracle/node-oracledb#1019]
(This server setup using standart settings OEL 7.6 and 18cR2  without any change of parameters and ISO downloaded 3 days before from Oracle )

DBSERVER:OEL 7.6 X64 Database 18C R2 (70GB SGA)   

APP SERVER:OEL 7.6 X64 Oracle instance X64 Client 18.3  Nodejs ,oracledb (final)

This is test enviroment so there is no load . And servers are powerfull with in same switch .

Basicly
socket.io and pollingTimer for realtime chat with using nodejs,

I gate error randomly. I correctly do procedure call and query but this error apired randomly. 

Error: NJS-040: connection request timeout
    at Pool.onRequestTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:125:38)
    at Timeout._onTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:188:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error getting connection Error: NJS-040: connection request timeout
    at Pool.onRequestTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:125:38)
    at Timeout._onTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:188:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: NJS-040: connection request timeout
    at Pool.onRequestTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:125:38)
    at Timeout._onTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:188:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: NJS-046: poolAlias "tw" already exists in the connection pool cache
    at Oracledb.createPool (/var/www/twnodejs/node_modules/oracledb/lib/oracledb.js:169:18)
    at /var/www/twnodejs/node_modules/oracledb/lib/util.js:118:16
    at new Promise (<anonymous>)
    at Oracledb.createPool (/var/www/twnodejs/node_modules/oracledb/lib/util.js:106:14)
    at startOracle (/var/www/twnodejs/twio.js:29:20)
    at Object.getConnectionCb (/var/www/twnodejs/twio.js:183:8)
    at Pool.onRequestTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:125:22)
    at Timeout._onTimeout (/var/www/twnodejs/node_modules/oracledb/lib/pool.js:188:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)

twDbconfig.js
=====================
module.exports = {
   //poolAlias: "tw",
   user          : "M5",
   password      : "M5",
   connectString : "xxxxxxxxxxx.xx:1521/xxx.xx.com",
   //events: false,
   //poolMax:          4,
   //poolMin:          1,
   //poolIncrement:    1,
   //poolTimeout:      120,
   //poolPingInterval: 120,
   //stmtCacheSize: 30,
   //queueTimeout:60    
    events: false, // whether to handle Oracle Database FAN and RLB events or support CQN
    externalAuth: false, // whether connections should be established using External Authentication
    homogeneous: true, // all connections in the pool have the same credentials
    poolAlias: 'tw', // set an alias to allow access to the pool via a name.
    poolIncrement: 1, // only grow the pool by one connection at a time
    poolMax: 1, // maximum size of the pool. Increase UV_THREADPOOL_SIZE if you increase poolMax
    poolMin: 1, // start with no connections; let the pool shrink completely
    poolPingInterval: 60, // check aliveness of connection if idle in the pool for 60 seconds
    poolTimeout: 60, // terminate connections that are idle in the pool for 60 seconds
    queueTimeout: 60000, // terminate getConnection() calls in the queue longer than 60000 milliseconds
    stmtCacheSize: 30 // number of statements that are cached in the statement cache of each connection
};
=====================
program.js
=====================
`process.env.UV_THREADPOOL_SIZE=64;
var http = require('http');
var fs = require('fs');
var cookie = require('cookie'); 
var oracledb = require('oracledb');
var TWU9S="";
var POLLING_INTERVAL = 90*5000;  ////I Change interval very long but sometimes get an error again
var pollingTimer;
   
var connectionsArray    = [];
let dbConfig = require('/var/www/twDbconfig.js');

process
.on('SIGTERM', function() {
  console.log("\nTerminating");
  process.exit(0);
})
.on('SIGINT', function() {
  console.log("\nTerminating");
  process.exit(0);
});

async function startOracle() {
  try {
    await oracledb.createPool(dbConfig);
   } catch (err) {
    console.error(err);
   }  
}

async function ws() {   
   var server = http.createServer(function(req, res) {
      var d = new Date();
      var n = d.toTimeString();
      res.writeHead(200, {'Content-Type': 'text/plain'});
      res.end('Wellcome tw.com World\n'+n);
   }).listen(8080);

   // Loading socket.io
   var io = require('socket.io').listen(server);
   // When a client connects, we note it in the console
   io.sockets.on('connection', function (socket) {
      var cookief =socket.handshake.headers.cookie; 
      var cookies = cookie.parse(socket.handshake.headers.cookie);
      console.log('Number of connections:' + connectionsArray.length);	
      TWU9S = cookies['TWU9S'];
      db_socio(TWU9S,socket.id); ////THIS PROCEDURE JUST ınsert TABLE AND COMMIT ONLY;
       pollingLoop();
      connectionsArray.push(socket);
      socket.on('msg', function (message) {
         console.log('A client is speaking to me! They’re saying: ' + message);
      });     
      socket.on('error', function (reason){
         console.error('Unable to connect Socket.IO', reason);
      });
      socket.on('disconnect', function(){
         console.log('user disconnected');
         db_socio(TWU9S,"");  ////THIS PROCEDURE JUST INSERT A RECORD A TABLE AND COMMIT ONLY; 
         var socketIndex = connectionsArray.indexOf( socket );
         console.log('socket = ' + socketIndex + ' disconnected');
         if (socketIndex >= 0) {
            connectionsArray.splice( socketIndex, 1 );
         }
      });
      // socket.emit('msg', 'TEST MESSAGE COME FROM SERVER');
   });
}
async function nowlog(t) {
var datetime = new Date();
    console.log(t+"--->"+datetime);
}
 
async function run() {
   await nowt('tw socket.io');
   await startOracle();
   console.log('Oracle Started');  
   await ws();
}
run();

////THIS PROCEDURE JUST INSERT A RECORD A TABLE AND COMMIT ONLY; 

async function db_socio(TWU9S,SOCID) {    
   let connection;
   var binds = [];
   var options = { bindDefs: []};
   
   var sql="BEGIN M.SOCIO('"+TWU9S+"','"+SOCID+"'); END;" ;
   try {
      // Get a connection from the default pool
      let connection = await oracledb.getConnection(dbConfig.poolAlias);
      //console.log("connection stat" )
      // console.log(connection);
      var binds = [];
      let options = { outFormat: oracledb.OBJECT };
      await nowlog("db ");
      let result =  connection.execute(sql, binds, options);
      await nowlog("db execute");
      console.log("user registered " + TWU9S+"->"+SOCID);
      //console.log(result);
   } catch (err) {
      console.error(err);
   } finally {
      if (connection) {
         try {
         // Put the connection back in the pool
         connection.close();
         } catch (err) {
         console.error(err);
         }
      }
   }
}

var pollingLoop = function () {
   get_u9();
    if(connectionsArray.length) {
      	pollingTimer = setTimeout( pollingLoop, POLLING_INTERVAL );	
      }
}

function get_u9(get_u9Callback) {
  oracledb.getConnection(dbConfig.poolAlias,function(err, conn) {
    if (err) {
      console.log('Error getting connection', err);
       startOracle();
      return;
    }
   var binds = [];
   var options = { bindDefs: []};   
    console.log('Connected to database');   
    conn.execute(
      `SELECT * FROM U9_ACTIVE_UJ`,          
 ////THIS QUERY RETURN MAX 10 RECORDS NOW BUT I RETURNS ACLTIVE USERS LIST IN CHAT ROOM
      binds,
      options,
      function(err, result) {
        if (err) {
          console.log('Error executing query', err); 
          conn.close(function(err) {
            if (err) {
              console.log('Error closing connection', err);
            } else {
              console.log('Connection closed');
            }
          }); 
          return;
        } 
       //console.log('Query executed'); 
       //console.log(result);
       
        conn.close(function(err) {
          if (err) {
            console.log('Error closing connection', err);
          } else {
            console.log('Connection closed');
          }
        });
      }
    );
  });
}
 
module.exports.get_u9 = get_u9;

=====================

**Comment by cjbj** [comment]
Pro tips:

- When creating an issue on GItHub, use Markdown syntax for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
- Debug your code and see why you are getting `Error: NJS-046: poolAlias "tw" already exists in the connection pool cache`.  Why is `startOracle()` being called twice?
- Debug all your `getConnection()` and `close()` calls to make sure there is a 1-to-1 relationship.
- Check the [_logStats](https://oracle.github.io/node-oracledb/doc/api.html#connpoolmonitor) to see how the pool queue is growing.
- Consistently use the async/await syntax
- Simplify your code and get small parts working before adding more features.

**Comment by alpertandogan** [comment]
> Pro tips:
> 
> * When creating an issue on GItHub, use Markdown syntax for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
> * Debug your code and see why you are getting `Error: NJS-046: poolAlias "tw" already exists in the connection pool cache`.  Why is `startOracle()` being called twice?
> * Debug all your `getConnection()` and `close()` calls to make sure there is a 1-to-1 relationship.
> * Check the [_logStats](https://oracle.github.io/node-oracledb/doc/api.html#connpoolmonitor) to see how the pool queue is growing.
> * Consistently use the async/await syntax
> * Simplify your code and get small parts working before adding more features.

Yes you are right totaly.  await  async problem (I came from PLSQL its difrrent methodlogy for me I have to read same about await async)

I see when i use pool._logStats() . My connection dont close after execute and exit from function 
and i also try to reopen pool when this error occured.


````
try {
      // Get a connection from the default pool
      let connection = await oracledb.getConnection(dbConfig.poolAlias);     
      let options = { outFormat: oracledb.OBJECT };
      let result =   await connection.execute(sql, binds, options);
//////////////////////////put this close after execute because  finally block  dont run
      await connection.close(); 
   } catch (err) {
      console.log("ORACLE ERROR connection not opened");
      connPool._logStats();      
      console.error(err);
   } finally {
      if (connection) {
         try {
         await connection.close();
         } catch (err) {
         console.error(err);
         }
      }
   }
````
