### ISSUE TITLE
ec2 install

### ISSUE THREAD

**Issue by alciakng** [oracle/node-oracledb#102]
currently, I use amazon web service. Can't this moudule install to EC2 Instance ?  I use linux platform..

I intalled gcc-c++ complier as this command :  sudo yum install gcc-c++

but there are compile error! what's wrong ?

![image](https://cloud.githubusercontent.com/assets/10395170/7767737/e1fbe9a6-00af-11e5-9668-9459fe2e0a80.png)

**Comment by cjbj** [comment]
The main problem is you are using Node 0.12.  Did you apply the patch in https://github.com/oracle/node-oracledb/pull/43 ?  Also see https://github.com/oracle/node-oracledb/issues/2

Also use the latest node-oracledb, which is 0.5.0
