### ISSUE TITLE
fetchAsString can return imprecise floating point representation

### ISSUE THREAD

**Issue by cemremengu** [oracle/node-oracledb#1023]
I am aware that JavaScript cannot represent decimals/floats correctly so a workaround is to use `fetchAsString` for `NUMBER` type. However, it can still return representations like `'19.420000000000002'` in some cases (actually I suspect this can be due to the definition of tables cause it does not always happen).

Any ideas?

EDIT: columns are regular `NUMBER` type

**Comment by cemremengu** [comment]
I am using `execute` with a simple `select * from table` query where `oracledb.fetchAsString = [oracledb.CLOB, oracledb.NUMBER]`

```sql
CREATE TABLE FLOAT_TEST
(
  CITY_NAME    VARCHAR2(50 BYTE),
  TOTAL  NUMBER
)
NOLOGGING 
COMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

SET DEFINE OFF;
Insert into FLOAT_TEST
   (CITY_NAME, TOTAL)
 Values
   ('DUZCE', 2.604);
COMMIT;
```

Though if I execute this script and create a different table (by changing name), it returns the correct values so I am unable to reproduce. I am assuming, the problem is at the insert side. We have a Java ETL service that fills these tables. I can ask for that code if it helps.

**Comment by cjbj** [comment]
@cemremengu try selecting from your table in SQL*Plus with a big `numwidth` e.g. similar to:
```
SQL> select 19.420000000000002 from dual;

19.420000000000002
------------------
	     19.42

SQL> set numwidth 20
SQL> select 19.420000000000002 from dual;

  19.420000000000002
--------------------
  19.420000000000002

```

**Comment by anthony-tuininga** [comment]
The Java ETL service code isn't going to be that helpful. What we really want is simply the data that causes the problem and the code snippet you are using so that we can attempt to replicate your situation. If you can't replicate it yourself, that's not going to be very helpful! :-) Let me know when you have something that you can replicate consistently.

**Comment by cemremengu** [comment]
@cjbj If I set the `numwidth` to the value you suggested SQL*Plus also returns the incorrect representation, otherwise (default) it will return the correct values. So:

```
select * from test` -> OK ( 3.216)
set numwidth 20
select * from test` -> NOT OK (3.2160000000000002)
```

**Comment by cjbj** [comment]
@cemremengu so it sounds like a data "issue".

**Comment by cemremengu** [comment]
@cjbj I think so. Closing this for investigation on my side
