### ISSUE TITLE
npm install oracle@3.0.1 - 404 during installation

### ISSUE THREAD

**Issue by Barathwaja** [oracle/node-oracledb#1025]
While installing oracledb version 3 and above the installation fails with error 404. Please check this ASAP. Below is the screenshot of the error.

![image](https://user-images.githubusercontent.com/5066436/50083184-f090c180-0218-11e9-8c7b-ce263e720c42.png)

**Comment by cjbj** [comment]
I answered this in your continuation issue https://github.com/oracle/node-oracledb/issues/1011#issuecomment-447805340
