### ISSUE TITLE
how can i handle DML returning value with INSERT ALL?

### ISSUE THREAD

**Issue by gabamaral** [oracle/node-oracledb#1027]
for a single insert we have

INSERT 
                INTO table_name (pk, column1) VALUES (1, 'string') 
                RETURNING pk INTO :ids

how can i handle DML returning inserted ids value with INSERT ALL statement?

**Comment by dmcghan** [comment]
You wouldn't use INSERT ALL, you would use connection.executeMany. See [Batch Statement Execution](https://oracle.github.io/node-oracledb/doc/api.html#batchexecution).

**Comment by gabamaral** [comment]
thanks,

I did it with the executemany
