### ISSUE TITLE
Query returning wrong time

### ISSUE THREAD

**Issue by GilVieira** [oracle/node-oracledb#1030]
1. Node.js version: **8.12.0**

2. node-oracledb version: **3.0.0**

3. What error(s) you are seeing?
Hello, I'm having a problem with time_zone, but only with some date (maybe it's a bug with daylight saving time), in a single query it returns me records with correct and other wrong times. The only pattern I found is that the time is returned one hour earlier on the last days of October. Before the query I set the time zone **America/Sao_Paulo**.

4. OS Node.js executing on: **Windows 7**

6. Oracle client (e.g. Instant Client) version:  **12.1.0.2.0**

**Comment by dmcghan** [comment]
@GilVieira Could you please create a reproducible test case? Also, we need to know what you are expecting vs what you are getting. Finally, what is the timezone of your Node.js operating system?

**Comment by GilVieira** [comment]
Hi @dmcghan,
I discovered the problem, is that the DST in the time zone 'america / sao_paulo' began on 2018-11-04 and not on the 2018-10-21 day as lib waits, so in this period the time is wrong. I have now tested using a docker [https://github.com/CollinEstes/docker-node-oracle](https://github.com/CollinEstes/docker-node-oracle) image, but the problem remains. I checked the DST on the OS and it looks okay.

```
await connection.execute("ALTER SESSION SET TIME_ZONE='America/Sao_Paulo'");

const res = await connection.execute(`select
     to_date(\'20/10/2018 12:07\',\'DD/MM/YYYY HH24:MI\') as dt 
     , to_date(\'21/10/2018 12:07\',\'DD/MM/YYYY HH24:MI\') as dt2
     , to_date(\'03/11/2018 12:07\',\'DD/MM/YYYY HH24:MI\') as dt3
     , to_date(\'04/11/2018 12:07\',\'DD/MM/YYYY HH24:MI\') as dt4
  from dual`);
```

Result:

DT  = 2018-10-20T15:07:00.000Z - _correct date_
DT2 = 2018-10-21**T14:07:00.000Z** - _wrong date_ (already changed to DST, but should only 2018-11-04)
DT3 = 2018-11-03T14:07:00.000Z - _wrong date_
DT4 = 2018-11-04T14:07:00.000Z - _correct date_ 

About DST:
[https://support.oracle.com/knowledge/Oracle%20Cloud/2331560_1.html](https://support.oracle.com/knowledge/Oracle%20Cloud/2331560_1.html)

I'm sorry if I did not explain it right.
Tks

**Comment by dmcghan** [comment]
Ah, the link you provided explains it...

What do you get when you run this?

```sql
select version
from v$timezone_file
```

If it's version 31 or less, then you (or your DBA) will need to upgrade the time zone data files for the database.

**Comment by GilVieira** [comment]
Sorry for my delay with feedback, the version query returned 4, but I still could not talk to the DBA. I did not imagine the problem was on the server as a .Net application consuming the same information backs up the correct dates, so talk to the DBA and have some news I update here.

To get around the problem, for now, I converted the date field to varchar.

**Comment by cjbj** [comment]
I'll close this out for the moment.  We can reopen it when you want to continue discussion.
