### ISSUE TITLE
connection.execute() function returns empty object

### ISSUE THREAD

**Issue by stepanho** [oracle/node-oracledb#1034]
Hello,

I've faced with problem, when I execute several same callable statements.
On 1 execution all is OK, but on the next executions (all) 'await connection.execute' returns {}.
There is no errors.
**How it's possible? In which ways 'await connection.execute' can return empty object?**
SQL of executions is same. Only 'binds' properties change.

Node.JS v10.13.0, 64bit.
Oracle DB 11.2.0.4

I can provide any additional info If you need.

Thank you.

**Comment by stepanho** [comment]
> @stepanho Did you resolve the issue on your own?

Yes, there was my bug: before execution, i'm unexpectedly set "type" and "dir" of out binds to "null". So after that execution was successful, but result was empty ("result == {}"), with "result.outBinds == undefined".

In my opinion, exception should be thrown.

**Comment by cjbj** [comment]
@stepanho We have an action item to be stricter.  PRs welcome, of course

**Comment by gaspan** [comment]
@stepanho did you solve the issue? i faced same problem. how you solve the issue?

**Comment by gaspan** [comment]
@stepanho could you share code ?

**Comment by cjbj** [comment]
@gaspan read the [manual](https://oracle.github.io/node-oracledb/doc/api.html).  If you still have issues, then please open a new issue and answer the issue template questions.

**Comment by gaspan** [comment]
i was solved the issue by changing async await code to callback code...

**Comment by cjbj** [comment]
@gaspan you should/could review the async/await code because generally that style is easier to get correct !
