### ISSUE TITLE
ORA-24338 when procedures get recompiled

### ISSUE THREAD

**Issue by vrsbrazil** [oracle/node-oracledb#1036]
Hello guys,

  As you requested on issue #886  I am opening a specific issue for this case.

   So first of all going through versions:
   Node version: 10.7.0
   Oracle Client version: instantclient-basic-linux.x64-12.2.0.1.0
   node-oracledbversion: 2.3.0

   The situation we are facing here is everytime we recompile a procedure, once we try to call it through our node oracledb client we get the ORA-24338 error. The error however goes away onxe we stop our node script and start it again, so it does look like is a connection issue.
   At first we thought the issue only ocurred onde we added/removed fields from the procedure signature but we did receive the same error by just recompiling it with no changes to the parameters. I am thinking maybe I should implement a logic to my connection pool that once this error occurs I just reset this specific connection and I should be fine at least for the next call, but it does sound like more a workaround than a real correction.
   I cannot publicly post the procedure but I will be happy to share with you in case you have a private e-mail i can forward it to.

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`? 64bit

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`? 2.3.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?  not an installation issue, except for this, the connector works fine

4. What error(s) you are seeing? ORA-24338

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
3.10.0-957.1.3.el7.x86_64

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed? instantclient-basic-linux.x64-12.2.0.1.0 
path: /opt/oracle/instantclient_12_2/

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`? 11.2.0.4.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`? 
echo $LD_LIBRARY_PATH
/opt/oracle/instantclient_12_2

9. What Oracle environment variables did you set?  How *exactly* did you set them? none but LD_LIBRARY_PATH

10. Do you have a small, single Node.js script that immediately runs to show us the problem? It can be done once I recompile the procedure

**Comment by vrsbrazil** [comment]
Hey there,

   We have updated the version and apparently after a few recompilation attempts on the procedure the error did not occur again.
    In case it does not happen in the next few hours I will close the issue,ok?

Thank you.

**Comment by cjbj** [comment]
What is your [stmtCacheSize](https://oracle.github.io/node-oracledb/doc/api.html#propdbstmtcachesize).

The bottom-line from #886 applies to all OUT binds: they must be initialized.  This is a problem in lower Oracle code that can't be fixed by node-oracledb.
