### ISSUE TITLE
Support for LDAP connections

### ISSUE THREAD

**Issue by w2kzzz** [oracle/node-oracledb#1044]
#### Answer the following questions:

1. What is your Node.js version: 8.11.1 64bits

2. What is your node-oracledb version: 3.1

3. What *exact* command caused the problem: trying to connect. oracledb.getConnection

4. What error(s) you are seeing? ORA-12154: TNS could not resolve the connect identifier specified

5. What OS (and version) is Node.js executing on: Windows 7 64bits

6. What is your Oracle client (e.g. Instant Client) version: 18.3

7. What is your Oracle Database version: 12c

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Node.js script that immediately runs to show us the problem: yes

**Comment by cjbj** [comment]
See #287.  If this doesn't help, then give more details.
