### ISSUE TITLE
node-oracledb case in stress (concurrency = 100) through CMAN TDM, would  occasionally get ORA-01017 errors

### ISSUE THREAD

**Issue by sg7671** [oracle/node-oracledb#1045]
The ORA-01017 occur occasionally in CMAN TDM as well as PRCP config, but not 
occur at all when connect directly to DB with same stress. Here we have used UV_THREADPOOL_SIZE=128,
concurrency = 100 and Requests = 10000. I have also observed that when I reduced concurrency to 10 and also reduced some requests then no error is seen. Here I have shown some stats from log file 
(listener_address=(DESCRIPTION=(address=(protocol=tcp)(host=slc07ihv.us.oracle.com)(port=1950))))
    (aso_authentication_filter=OFF)
    (connection_statistics=ON)
    (log_directory=/scratch/u01/app/oracle/diag/netcman/slc07ihv/cman_slc07ihv.us.oracle.com/alert)
    (log_level=user)
    (max_connections=300)
    (idle_timeout=0)
    (inbound_connect_timeout=0)
    (session_timeout=0)
    (outbound_connect_timeout=0)
    (max_gateway_processes=16)
    (min_gateway_processes=2)
    (password=OFF)
    (remote_admin=ON)

Can somebody please help in knowing the reason behind this uncertainity ?
Thanks

**Comment by cjbj** [comment]
Sounds like you are an Oracle employee.  If so, [email me](https://github.com/cjbj).

**Comment by cjbj** [comment]
Closing - no update
