### ISSUE TITLE
Injection SQL with Bind parameters

### ISSUE THREAD

**Issue by bradisson** [oracle/node-oracledb#1046]
DISCLAIMER: I am not a PL/SQL dev, I'm an okay-ish node.js dev

 
I'm working with a REST API (express) that call PL/SQL package.
I found that if I put in a bind param the string `"foo' or 'a'='a"`, I got some messy injection in WHERE case.

below an exemple of the structure of the process, I tried to keep it short and readable.

NodeJS
```
import * as oracledb from 'oracledb';
import { Request, Response, NextFunction } from 'express-openapi';


async function Get (req: Request, res: Response, next: NextFunction): Promise<void> {
  // Here req.params.item_id = "foo' or 'a'='a";
  await getItem(req.params.item_id);
 next();
}

async function getItem(itemId: string) {
  const block =
      'DECLARE ' +
      'v_result CLOB := null; ' +
      'BEGIN ' +
      'PACKAGE.GetItemById( ' +
      ':item_id, ' +
      ').Mjson.to_clob(v_result); ' +
      ':response := v_result; ' +
      'END; ';
  const bindVars = {
    item_id: itemId,
    reponse: {
      dir: oracledb.BIND_OUT,
      type: oracledb.STRING,
    }
  }
  // Assume we have a valid connection to oracle DB
  await connection.execute(block, bindVars);
}
```

PL/SQL
```
FUNCTION GetItemById(i_item_id IN VARCHAR2) return  clob
    AS
    TYPE rec_curseur IS RECORD(v_id VARCHAR2(64));
    TYPE values_t IS TABLE OF rec_curseur;
    v_Json json := json();
    v_Clob clob;
    v_Retour_Clob clob := clob;

    cursor C_Item (i_item_id VARCHAR2)is
         select  t.ITEM_id  from TABLE T
         where t.ITEM_id = i_item_id
BEGIN

v_Clob := GetMetada(I_ITEM_ID   => I_item_id);
v_Json.put('item'  ,json(v_Clob));
v_Retour_Clob.SetContent(v_Json) ;

RETURN v_Retour_Clob;

END;


FUNCTION GetMetada(I_item_id  VARCHAR2) return clob
  AS
  TYPE rec_curseur IS RECORD(v_id VARCHAR2(64));
  TYPE values_t               IS TABLE OF rec_curseur;
  l_values                    values_t;
  v_retour_clob               clob := null;
  v_Json                      

  cursor C_Stops (i_item_id VARCHAR2  )is
             select  t.STOP_id  from TABLE T
             where t.ITEM_ID = i_item_id

  v_query VARCHAR2(4000);

  BEGIN

  v_query := 'select distinct t.ITEM_ID FROM TABLE T';
  -- multiple conditionnal structure later
  v_query :=v_query || ' where t.ITEM_ID  = ' ||''''|| i_item_id ||'''';


  -- v_query => select distinct t.ITEM_ID FROM TABLE T where t.ITEM_ID = '' or 'a'='a';
  EXECUTE IMMEDIATE  v_query   BULK COLLECT INTO l_values;
  FOR indx IN 1..l_values.COUNT
    LOOP
    v_Json.put('res',l_values (indx).v_id);
    END LOOP;
    v_Json.to_clob(v_Retour_Clob);

  RETURN v_Retour_Clob;
  END;
```

In the real case, the parameter `i_item_id` is send through a lot of function call before being used at the end in a where clause.
When the stored query is executed, the `where` clause execute the `or 'a'='a'`

I don't know what's wrong, from the documentation I understand that binding parameters should prevent SQL injection, and we don't need to sanitize our input.

Should I sanitize my input before the bind (Node side) or after (PL/SQL side) ?

If you need more info, tell me. I'll provide what I can.

Node.js version: v7.10.0 x64

node-oracledb version: 1.13.1 (I know this is old, but it's legacy project and I can't touch it)

OS: centos7

 Instant Client version: 12.2.0.1.0 x64

Oracle Database version: 11.2.0.3

**Comment by dmcghan** [comment]
@bradisson In PL/SQL, in parameters can be used directly as bind variables. You can rewrite your function as follows to avoid any issues:

```sql
FUNCTION GetMetada(I_item_id  VARCHAR2) return clob
  AS
  type vc2_aat is table of varchar2(64)
    index by pls_integer;
  l_values                    vc2_aat;
  v_retour_clob               clob := null;
  v_Json                      

  BEGIN

  select distinct t.ITEM_ID FROM TABLE T
  BULK COLLECT INTO l_values
  where t.ITEM_ID = GetMetada.I_item_id;

  FOR indx IN 1..l_values.COUNT
    LOOP
    v_Json.put('res',l_values (indx).v_id);
    END LOOP;
    v_Json.to_clob(v_Retour_Clob);

  RETURN v_Retour_Clob;
  END;
```

**Comment by dmcghan** [comment]
By the way, what version of the database are you using?

**Comment by dmcghan** [comment]
> FYI the database version was in my first post

Sorry I missed that. Just so you know, Oracle 12.2+ has JSON generation functions built in, so you don't have to rely on PL/JSON. You can build complex, nested JSON right from the SQL engine (no PL/SQL needed even) and return that as a CLOB to Node.js. Here's an example of how to use the functions: https://jsao.io/2018/10/relational-to-json-with-sql/

**Comment by cjbj** [comment]
Quick notes:

(i) the BULK COLLECT and FROM clauses in @dmcghan's code need swapping

(ii) The node-oracledb doc on JSON is at https://oracle.github.io/node-oracledb/doc/api.html#jsondatatype

**Comment by bradisson** [comment]
Thanks for your reply both of you.

Upgrading to 12.2+ and using JSON Data type is too much work for us I think.

The real struggle here is the fact that they (the SQL team of my company) used a lot of unbind params with string concatenation like `'WHERE COL = ' || '''' || i_param || ''''`.

This is a nest of potentials (and real) SQL injection attack. 

I wish there was a way to sanitize input on node side using node-oracledb to avoid risk when the data is badly used in the PL/SQL package.

Honestly I'm lost.
Should I build a sanitize method myself and sanitize each and every params I send to SQL package ?
Should I blame the SQL team for poor security skills and tell them to fix it themself ?
Should I quit my job and make a world trip ?

**Comment by dmcghan** [comment]
> Should I build a sanitize method myself and sanitize each and every params I send to SQL package ?

You could help address the security issue doing this, but database performance will still suffer. Point the developers to this: https://docs.oracle.com/en/database/oracle/oracle-database/18/tgsql/improving-rwp-cursor-sharing.html#GUID-971F4652-3950-4662-82DE-713DDEED317C


> Should I blame the SQL team for poor security skills and tell them to fix it themself ?

Yes.


> Should I quit my job and make a world trip ?

Also yes. 😂

**Comment by dmcghan** [comment]
@cjbj Swapped, thanks. I still don't know if it would compile... :)

**Comment by bradisson** [comment]
>> Should I quit my job and make a world trip ?

> Also yes. 😂

Any recommendation ?

Thanks for your help and answers.
