### ISSUE TITLE
Windows install: Error: ORA-12154: TNS:could not resolve the connect identifier specified 

### ISSUE THREAD

**Issue by rstor1** [oracle/node-oracledb#1047]
### For installation issues:

- Review the install instructions https://oracle.github.io/node-oracledb/INSTALL.html

- Review the troubleshooting tips https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

#### Answer the following questions:

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`? **x64**

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`? **3.1.1**

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as? **npm run start**

4. What error(s) you are seeing? **Error: ORA-12154: TNS:could not resolve the connect identifier specified**

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`? **win32**

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed? **12.1.0.2.0, 64 bit, zip file, node_modules/oracledb/build/Release**

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`? PATH was set to C:\oracle\instantclient_12_1 but I used this option in the install instructions instead as it was working better: _Alternatively move the unzipped Instant Client files to node_modules\oracledb\build\Release so the DLLs and other files are in the same directory as the oracledb.node binary. If you do this, then PATH does not need to be set._

9. What Oracle environment variables did you set?  How *exactly* did you set them? Did not do or know how to do this.

10. Do you have a small, single Node.js script that immediately runs to show us the problem? No the app is quite complex but I figured if the exact same app works on a MacOS, it most likely is how instant client is installed on the Windows machine. It is not resolving the connect identifier but I have installed the instant client as per instructions and have the tnsnames.ora setup. I even added the connection string hardcoded in the app to try and help the connection but it still does not catch. Here is the format of the oracle connection.

    this.creds = {
      "user": "aslkdklasd",
      "password": "asdjkjfaklsdj",
      "connectString": "XXXXX = (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = lkd.lkdjk.com)(PORT = 1521))(CONNECT_DATA = (SERVICE_NAME = KKDJFI)))"
    };
Any help is much appreciated. I had this same question for MacOS and got it working but it is not working for the Windows install.

**Comment by dmcghan** [comment]
@rstor1 See this section on [Embedded Connection Strings](https://oracle.github.io/node-oracledb/doc/api.html#embedtns). I think the `XXXXX=(DESCRIPTION =` is wrong. It should start with just `(DESCRIPTION =`.

**Comment by rstor1** [comment]
@dmcghan omg that was it! Thanks a million man!

**Comment by cjbj** [comment]
@rstor1 with your example you would just use the equivalent [Easy Connect syntax](https://oracle.github.io/node-oracledb/doc/api.html#easyconnect):
```
"connectString": "lkd.lkdjk.com/KKDJFI"
```
and not bother with the full syntax unless you need other network parmeters.

**Comment by rstor1** [comment]
@cjbj awesome, works!
