### ISSUE TITLE
Restart the discussion in issue #400 - DPI_ORACLE_TYPE_CHAR vs VARCHAR

### ISSUE THREAD

**Issue by metafloor** [oracle/node-oracledb#1048]
Our applications work with existing schemas (some were initially created in oracle 8) and the schemas cannot be changed.  Because of this legacy, there are lots of CHAR columns that rely on space padding semantics e.g. a column contains mainly 2-char strings in a CHAR(3) definition.  So the issue raised in #400 is relevant as comparisons with bind variables on CHAR columns fail.

Would you be willing to accept a pull request that provides a new option to bind strings using SQLT_AFC/DPI_ORACLE_TYPE_CHAR rather than the default SQLT_CHR/DPI_ORACLE_TYPE_VARCHAR?  I have the code working on my local fork. 

The boolean flag `charSemantics` has been added to the `[DBCobject].execute()` and `[DBCobject].executeMany()` options.  By default, `charSemantics` is false and the enhancement should be backward compatible.  My only concern is the following change in `njsConnection::Execute()`:

    // Options first to allow charSemantics to affect the binds
    if (ok)
        ok = ProcessExecuteOptions(info[2].As<Object>(), baton);
    if (ok)
        ok = ProcessExecuteBinds(info[1].As<Object>(), baton);

The original code does the binds first, then parses the options.  Do you see any potential compatibility issues with that change in sequence?  My testing shows no effects and that sequence is how it is done `ExecuteMany()`.

Thanks,
-Mark

**Comment by cjbj** [comment]
@metafloor we've had ongoing discussions about the binding system and how much flexibility (aka complexity) to add.  I'd be interested in your thoughts about what the node-oracledb syntax would look like, keeping in mind this would be for more than just CHAR and would need to keep backward compatibility.

**Comment by metafloor** [comment]
You probably don't want to hear this, but I consider binding strings as SQLT_CHR to be a bug, not a feature ;-)  I do not have access to internal OCI performance guidelines, but our c++ apps have always used SQLT_AFC for string data.  Our application framework supports user-defined queries (reports) where we have essentially no control over the SQL used.  We just need string comparisons to work, regardless of database column type.  And have it be intuitive for overworked, site-local programmers.  That is why I prefer an `execute()` option that can always be set versus using syntax/markup in the SQL.

With that said, we also support markup in the SQL.  Our applications work with large buffers of utf-8 string data.  And since we use buffers for both binary and string data, we need a way to differentiate usage without requiring lots of javascript boilerplate.

So the bind markup looks like casts or function calls:

    UPDATE ...  SET a_clob_column = :utf8(myutf8buffer) ...

Internally, the app framework converts that into the correct bind variable and re-writes the SQL for the underlying dbms.

As another example, we often have binary data stored in javascript strings (high bytes zero).  Since that can look like utf-16 data, we use markup to differentiate:

    UPDATE ... SET a_raw_column = :binary(mybinstring) ...

I don't think this markup is anything special, but it does work very well for specifying how to treat the bind data.  And is easily expandable when new use-cases arise.  From an oracledb perspective, allowing these named functions to be attached to the `[DBCobject]` similar to jQuery's `fn` object, would be a nice enhancement.

**Comment by cjbj** [comment]
Allowing users to control bind types would help cases like https://github.com/oracle/node-oracledb/issues/745 and https://github.com/oracle/node-oracledb/issues/711, and may be a way to allow more complex JS objects to be created where there is no good/nice JS type to match the Oracle DB type.  The question is the flexibility and usability.

**Comment by cjbj** [comment]
@metafloor node-oracledb 4.2 now lets you bind JS String values as `oracledb.DB_TYPE_CHAR`, see https://oracle.github.io/node-oracledb/doc/api.html#executebindparamtype
