### ISSUE TITLE
oracledb to Oracle 11 XE

### ISSUE THREAD

**Issue by nishad1992** [oracle/node-oracledb#1049]
I would really like to know if its possible to Create a REST API using NodeJS for Oracle 11 XE. How ? Please suggest .

**Comment by dmcghan** [comment]
@nishad1992 You can create a REST API on any edition and version of Oracle Database that's supported by node-oracledb, which includes XE (by the way, [XE 18c is now available](https://www.oracle.com/database/technologies/appdev/xe.html)).

Have a look at this blog series to get started: https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/

**Comment by cjbj** [comment]
@nishad1992 or skip REST and try something newer - GraphQL, see https://blogs.oracle.com/opal/demo:-graphql-with-node-oracledb

**Comment by nishad1992** [comment]
@dmcghan Sure, That sounds good. I'm looking into it. Thanks for the info.

@cjbj Thnx will defintily explore on this.
