### ISSUE TITLE
[The specified procedure could not be found. ] error on node-oracle

### ISSUE THREAD

**Issue by CarlosRen** [oracle/node-oracledb#105]
hi
this is my code:
app-oracle.js
```
function oracledb(){
  var oracledb = require('oracledb');
  oracledb.getConnection(
  {
    user          : "fundsdev",
    password      : "fundsdev",
    connectString : "10.6.10.141/fundsdev"
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      "SELECT * from sys_middle sys_middleprice_num orderby middleprice_date desc",
      [0],
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log(result.rows);
        return result.rows;
      });
  });

}
exports.orcl = oracledb;
```
app.js
```
app.get('/orcl',function(req, res, next){
	var result = oracleop.orcl();
	res.send(result);
});
```

and this is the error when i calling function by url 

The specified procedure could not be found. D:\mircospider\node_modules\oracledb\build\Release\oracledb.node
```
The specified procedure could not be found. D:\mircospider\node_modules\oracledb\build\Release\oracledb.node

Error: The specified procedure could not be found.
D:\mircospider\node_modules\oracledb\build\Release\oracledb.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\mircospider\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

is the way i using node-oracle wrong? or it is a problem of node-oracle?
i can't fix it ,wish your help

**Comment by cjbj** [comment]
Quite possibly PATH is not set, or doesn't contain the same version of the Oracle libraries that were used to build node-oracledb.

In your code, don't forget to release() the connection, including if there is an error during execute()

**Comment by dmcghan** [comment]
@CarlosRen After you address the PATH and release() issues, you'll also need to address an async issue... Currently your app.js is calling oracleop.orcl as though it's synchronous, which it is not. You'll need to update your oracledb function in app-oracledb.js to accept a callback which is invoked at the right time. Then your app.js would look like this:

app.get('/orcl',function(req, res, next){
    oracleop.orcl(function(result) {
        res.send(result);
   });
});

**Comment by CarlosRen** [comment]
@cjbj First , thank you for remind me about release() the connection : )
Also,thank to @dmcghan , i will add async issue as your words after this question closed 

I still have some questions about PATH , my computer system is win2008 R2 server and the PATH shows that:
```
D:\mircospider>path
PATH=C:\Python27\;C:\Python27\Scripts;C:\oraclexe\app\oracle\product\11.2.0\serv
er\bin;;D:\app\Administrator\product\11.2.0\client_1\bin;D:\app\Administrator\pr
oduct\11.2.0\dbhome_1\bin;C:\Program Files (x86)\Java\jdk1.6.0_24\bin;C:\Windows
\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerSh
ell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\oracle\instan
tclient;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\atom\bin;C
:\Users\Administrator\AppData\Roaming\npm
```
There is 3 PATH of oracle in my computer :
1 C:\oraclexe\app\oracle\product\11.2.0\server\bin;
2 D:\app\Administrator\product\11.2.0\client_1\bin;
3 D:\app\Administrator\product\11.2.0\dbhome_1\bin;
4 C:\oracle\instantclient; // i set it

besides, as https://github.com/oracle/node-oracledb/blob/master/INSTALL.md said 
i execute this 
```
set OCI_LIB_DIR=C:\oracle\instantclient_12_1\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient_12_1\sdk\include
```
in cmd of windows 

I think the PATH is reason lead to the question , but i have no idea to solve it , can your give me some seggestions?

**Comment by cjbj** [comment]
Thanks for the detail.

You built node-oracledb with Oracle 12.1 but at runtime your PATH is causing it use the Oracle XE 11.2 libraries, which don't have the new symbols node-oracledb will look for.  (If you did the reverse - building with 11.2 and running with 12.1 - it would work because 12.1 client libraries are a superset of 11.2).

Since you have at least one set of database software installed you didn't really need Instant Client, unless you wanted some 12.1 features (generally you'd need a 12.1 DB).

You could rebuild node-oracledb setting the OCI_*DIR paths to the Oracle XE paths.  INSTALL.md mentions the general naming scheme to use for ORACLE_HOME installs.

You could change your PATH to have the Instant Client libs first.  Be careful to do this only for Node.js.

You could copy the Instant Client to node_modules/oracledb as done in https://github.com/oracle/node-oracledb/issues/88

**Comment by CarlosRen** [comment]
@cjbj
This environment is prepared for Nodejs ,so I changed the PATH ,make sure that the Instant Client libs at first, and the problem is solved . 
╰(*°▽°*)╯thank you !!!
English is my second language, Thank you for your patience .
Btw , node-oracledb is a usefull module, wish it better !

**Comment by jaipreet-chhatwal** [comment]
hi
can i have a windows 64 bit machine /node 32 bit , oracle client lib for win 32  bit and install oracleDB .

**Comment by bchr02** [comment]
>can i have a windows 64 bit machine /node 32 bit , oracle client lib for win 32 bit and install oracleDB .

@jaipreet-chhatwal yes you can. if you are still having problems I would create a new issue instead of using this one.

**Comment by nakranimohit0** [comment]
Thanks @CarlosRen, your solution worked

**Comment by LaxmiNarasimha530** [comment]
hi iam having the same isse it did not get solved.

i had 
C:\Users\mohaah8\Documents\MobileFirstChat_DEV_1\MobileFirstChat-App\MobileFirstChat-Core\src\main\websrc>set PATH
Path=C:\Oracle\product\11.2.0\client_64;C:\Oracle\product\11.2.0\client_64\bin;C:\Oracle\11.2GR2\bin;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPo
werShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Fi
les\Java\jre8\bin;c:\Program Files (x86)\1E\SMSNomad\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files (x86)\IBM\OnDemand32;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files (x86)\apache-maven-3.0.5\bin;C:\Program Files
 (x86)\AccuRev\bin;C:\Users\mohaah8\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Oracle\instantclient;C:\Program Files (x86)\Microsoft Visual Studio 12.0;C:\Program Files\nodejs\;C:\Program Files (x86)\Python27;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1;C:\Program Files (x86)\Windows Kit




and






set OCI_LIB_DIR=C:\Oracle\instantclient\sdk\lib\msvc

set OCI_INC_DIR=C:\Oracle\instantclient\sdk\include


node -v 
6.0.0

npm -v
3.8.6

python -v
2.7.8

visual studio community 2013

oracle instant client versions 11.2.0 had both basic and sdk for the 64 bit.
