### ISSUE TITLE
How to  insert name of table field into query string?

### ISSUE THREAD

**Issue by urzt** [oracle/node-oracledb#1052]
Guys, how can i insert name of table field into query string via binds?
The code below sends a string and does not work.

```
queryString = `
                SELECT :fieldname
                FROM table
                WHERE locality = :location
                `;
binds = {
            fieldname: fieldname
          , location: location
        };

```

**Comment by urzt** [comment]
Find [that](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-188-binding-column-and-table-names-in-queries) workaround

**Comment by cjbj** [comment]
I'd forgotten about that doc.  Thanks for finding it!
