### ISSUE TITLE
Node js and Oracle Db. 

### ISSUE THREAD

**Issue by chezdrz** [oracle/node-oracledb#1055]
I am trying to query data from an Oracle db by following the instructions in this vid
https://www.youtube.com/watch?v=zQtRwTOwisI
Quickstart for Node.js and Oracle Database.

Question : Are these instructions still valid , or do I need to change something ?
Trying it out on a Linux box 

$ node -v
v10.15.1

echo $LD_LIBRARY_PATH
/orpppmd1/ppmapp/11.2.0/lib

$ cat package.json
{
 "name" : "cemli-demo",
 "version" : "1.0.0",
 "private" : true,
 "description" : "CEMLI Test",
 "dependencies" : {
     "oracledb" : "^2.0.15"
},
 "author": "CD",
 "license" : "MIT"
}

when doing an npm install I am hitting upon the following 
(could be a dependent git hub issue , could you please help out here ? )

> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v64-linux-x64.gz
oracledb ERR! getaddrinfo ENOTFOUND github.com github.com:443
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.3.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by danilohgds** [comment]
@chezdrz you seem to be behind a proxy that is not letting the installation pull the binaries from GitHub, 
given the message here: 
`
getaddrinfo ENOTFOUND github.com github.com:443`

There are ways on the documentation on how to handle this scenario.

**Comment by cjbj** [comment]
Even if you sorted out the proxy issue, you would find that 2.0.15 is very old and there are no pre-built binaries for [NODE_MODULE_VERSION ABI "64"](https://nodejs.org/en/download/releases/) (aka Node.js 10 ) as shown in the "v64" of the file name the installer looked for: "oracledb-v2.3.0-node-v64-linux-x64.gz".  You can see which node-oracledb 2.0.15 binaries were/are available at https://github.com/oracle/node-oracledb/releases/tag/v2.0.15.

However, the solution is to use the latest node-oracledb 3.1.2 which (a) doesn't need to pull from GitHub (b) has a pre-built binary for Node.js 10 (c) is better and has more features than 2.0.15

**Comment by chezdrz** [comment]
> Even if you sorted out the proxy issue, you would find that 2.0.15 is very old and there are no pre-built binaries for [NODE_MODULE_VERSION ABI "64"](https://nodejs.org/en/download/releases/) (aka Node.js 10 ) as shown in the "v64" of the file name the installer looked for: "oracledb-v2.3.0-node-v64-linux-x64.gz". You can see which node-oracledb 2.0.15 binaries were/are available at https://github.com/oracle/node-oracledb/releases/tag/v2.0.15.
> 
> However, the solution is to use the latest node-oracledb 3.1.2 which (a) doesn't need to pull from GitHub (b) has a pre-built binary for Node.js 10 (c) is better and has more features than 2.0.15

@cjbj,
Thanks a lot for your reply. Based on what you said I am now trying to install node-oracledb 3.1.2 for Linux 64bit .
So I went here https://github.com/oracle/node-oracledb/releases/tag/v3.1.2
But I am not able to find the downloadable installable for 3.1.2 - Linux 64bit.

I only see the file oracledb-src-3.1.2.tgz on this page.

**Comment by chezdrz** [comment]
> > Even if you sorted out the proxy issue, you would find that 2.0.15 is very old and there are no pre-built binaries for [NODE_MODULE_VERSION ABI "64"](https://nodejs.org/en/download/releases/) (aka Node.js 10 ) as shown in the "v64" of the file name the installer looked for: "oracledb-v2.3.0-node-v64-linux-x64.gz". You can see which node-oracledb 2.0.15 binaries were/are available at https://github.com/oracle/node-oracledb/releases/tag/v2.0.15.
> > However, the solution is to use the latest node-oracledb 3.1.2 which (a) doesn't need to pull from GitHub (b) has a pre-built binary for Node.js 10 (c) is better and has more features than 2.0.15
> 
> @cjbj,
> Thanks a lot for your reply. Based on what you said I am now trying to install node-oracledb 3.1.2 for Linux 64bit .
> So I went here https://github.com/oracle/node-oracledb/releases/tag/v3.1.2
> But I am not able to find the downloadable installable for 3.1.2 - Linux 64bit.
> 
> I only see the file oracledb-src-3.1.2.tgz on this page.

Further to his I downloaded the tar file and extracted the same 
Then ran a 

$ npm install oracledb
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "oracledb" under a package
npm ERR! also called "oracledb". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>


Note: This linux box already has an oracle database setup and running. 
Given this , should I follow some other route ?

**Comment by anthony-tuininga** [comment]
You should be able to simply run the command "npm install oracledb" and it will download and install binaries if the platform you are on is supported. But you do have to it outside of the directory where you downloaded the source. If you want to build from source, then in that directory you should only run the command "npm install".

**Comment by chezdrz** [comment]
> You should be able to simply run the command `npm install oracledb` and it will download and install binaries if the platform you are on is supported. But you do have to do it outside of the directory where you downloaded the source. If you want to build from source, then in that directory you should only run the command `npm install`.

Thank you. will try this

**Comment by chezdrz** [comment]
Finally got it to work.
@cjbj & anthony-tuininga Appreciate the help

**Comment by cjbj** [comment]
@chezdrz the installation instructions are [here](https://oracle.github.io/node-oracledb/INSTALL.html) if you ever need them.
