### ISSUE TITLE
batchInsert failing when I have null values.

### ISSUE THREAD

**Issue by ilynyeh** [oracle/node-oracledb#1056]
I'm trying to do a batchInsert, that has some values as null.  This is causing the insert to fail with 
TypeError: Cannot read property 'getDate' of null

oconn.batchInsert(insertSQL, batchInserts, { autoCommit: autoCommitFlag }, function onResults(error, output) {....}

The piece of code that is causing this issue is in simple-oracledb(i know not the right place, but you'll see why I am posting here below).

Connection.prototype.generateBindDefinitionEntry = function (bindDefinitions, key, item) {
    if (typeof item === 'object') {
			if (item) {
        if (typeof item.getDate === 'function') {
            bindDefinitions[key] = {
                type: constants.dateType
            };
        } 

typeof null returns object, which causes this to fail with the above message.  Prior to today, this was working fine with the old node-oracledb v 1.1.13 installed.  We upgraded node from v6 to v10 today, and rebuilt our modules. 

The code itself has not changed, but the versions of our packages have changed.  Anyone seen this error before or how to get around it?  I can't imagine we are the only ones batchloading into tables with possible null values.

Thanks much in advance!
Ilyn

#### Answer the following questions:

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?
v10.15.1
x64

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?
3.1.2

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
oconn.batchInsert(insertSQL, batchInserts, { autoCommit: autoCommitFlag }, function onResults(error, output) {....}

4. What error(s) you are seeing?
TypeError: Cannot read property 'getDate' of null

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?
linux

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
12.1.0.2.0

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?
11.2.0.4.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Node.js script that immediately runs to show us the problem?
No

**Comment by cjbj** [comment]
simple-oracledb recently started using node-oracledb's `executeMany()`.  If you can construct a pure node-oracledb testcase using `executeMany()` we can look at it.

**Comment by ilynyeh** [comment]
Thanks cjbj, with this information, i was able to add the option for useExecuteMany to false, and it ran fine.  Not sure why it's failing when using ExecuteMany.  Looks like it's trying to set the field type, but having issues when it's null.  This worked:

oconn.batchInsert(insertSQL, batchInserts, { autoCommit: autoCommitFlag, useExecuteMany: false }, function onResults(error, output) {....}

Thanks again!

**Comment by cjbj** [comment]
@ilynyeh using `executeMany()` will be **so much** faster that you should investigate the cause more.  If you share some data we may be able to help guess.

**Comment by ilynyeh** [comment]
@cjbj when I run this code
console.log(insertSQL);
console.log(batchInserts);
oconn.batchInsert(insertSQL, batchInserts, { autoCommit: autoCommitFlag, useExecuteMany: true }, function onResults(error, output) {...}

I get the following output. seems like if anything is null it errors on the getDate, since item is null.

INSERT INTO fact_rscr_store_data (callid,cache_type,cache_key,start_date,start_time,start_date_time,directions_prompt_id,language_primary,language_secondary,market_id,regular_hours_key,store_id,store_name,store_tn,store_type,time_zone,transfer_protocol,transfer_timeout,transfer_to_tn,record_load_time) VALUES (:callid, :cache_type, :cache_key, :start_date, :start_time, :start_date_time, :directions_prompt_id, :language_primary, :language_secondary, :market_id, :regular_hours_key, :store_id, :store_name, :store_tn, :store_type, :time_zone, :transfer_protocol, :transfer_timeout, :transfer_to_tn, :record_load_time)
[ { callid: 'wp0265ajcd190222141721',
    cache_type: 'retailstoreinfo',
    cache_key: '9402677',
    start_date: '20190222',
    start_time: '141747',
    start_date_time: 2019-02-22T14:17:47.238Z,
    directions_prompt_id: '164577_directions',
    language_primary: null,
    language_secondary: null,
    market_id: 68,
    regular_hours_key: 'Su10.20MoSa10.21',
    store_id: 164577,
    store_name: 'CAMARILLO PREMIUM OU',
    store_tn: 8053843595,
    store_type: 'OFP',
    time_zone: 'US/Pacific',
    transfer_protocol: 'CONSULT_CONNECT',
    transfer_timeout: 45000,
    transfer_to_tn: 8448235610,
    record_load_time: 2019-02-26T02:01:44.609Z },
  { callid: 'wp0265ajcd190222141721',
    cache_type: 'retailstorehours',
    cache_key: 'Su10.20MoSa10.21',
    start_date: '20190222',
    start_time: '141747',
    start_date_time: 2019-02-22T14:17:47.242Z,
    directions_prompt_id: null,
    language_primary: null,
    language_secondary: null,
    market_id: null,
    regular_hours_key: null,
    store_id: null,
    store_name: null,
    store_tn: null,
    store_type: null,
    time_zone: null,
    transfer_protocol: null,
    transfer_timeout: null,
    transfer_to_tn: null,
    record_load_time: 2019-02-26T02:01:44.609Z },
  { callid: 'wp0265ajcd190222141721',
    cache_type: 'retailstoreholidayhours',
    cache_key: '164577',
    start_date: '20190222',
    start_time: '141747',
    start_date_time: 2019-02-22T14:17:47.244Z,
    directions_prompt_id: null,
    language_primary: null,
    language_secondary: null,
    market_id: null,
    regular_hours_key: null,
    store_id: null,
    store_name: null,
    store_tn: null,
    store_type: null,
    time_zone: null,
    transfer_protocol: null,
    transfer_timeout: null,
    transfer_to_tn: null,
    record_load_time: 2019-02-26T02:01:44.609Z } ]
TypeError: Cannot read property 'getDate' of null
    at Connection.generateBindDefinitionEntry (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1698:25)
    at Connection.generateBindDefinitions (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1750:18)
    at Connection.insertOrUpdate (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:583:14)
    at Connection.promiseWrapper [as insertOrUpdate] (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/promise-helper.js:185:27)
    at Connection.insert (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:451:17)
    at Connection.batchInsertOrUpdate (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1117:24)
    at Connection.promiseWrapper [as batchInsertOrUpdate] (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/promise-helper.js:185:27)
    at Connection.batchInsert (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1030:17)
    at oconn.run.sequence (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/workers/rscrstoredata.js:115:13)
    at PromiseHelper.runAsync (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/promise-helper.js:63:19)
    at asyncAction (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1290:31)
    at /opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:3880:24
    at replenish (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:1011:17)
    at /opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:1016:9
    at _parallel (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit$1 [as parallelLimit] (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:3985:5)

Think simple-oracledb is not handling null values

Connection.prototype.generateBindDefinitionEntry = function (bindDefinitions, key, item) {
    if (typeof item === 'object') {
        if (typeof item.getDate === 'function') {
            bindDefinitions[key] = {
                type: constants.dateType
            };
        } 

Thank you!

**Comment by cjbj** [comment]
Can you share the SQL to create the table, and some data - I don't want to waste time guessing?  I don't need real table or values - just create a smaller testcase that has the same problem.

Also I edited your post to format the code - that's the "<>" button in the issue editor.

**Comment by ilynyeh** [comment]
Here is the DDL for the table.

```
CREATE TABLE RPT_AEP_ST_ENV1.FACT_RSCR_STORE_DATA (
	CALLID VARCHAR2,
	CACHE_TYPE VARCHAR2,
	CACHE_KEY VARCHAR2,
	START_DATE VARCHAR2,
	START_TIME VARCHAR2,
	START_DATE_TIME TIMESTAMP,
	DIRECTIONS_PROMPT_ID VARCHAR2,
	LANGUAGE_PRIMARY VARCHAR2,
	LANGUAGE_SECONDARY VARCHAR2,
	MARKET_ID NUMBER(22,0),
	REGULAR_HOURS_KEY VARCHAR2,
	STORE_ID NUMBER(22,0),
	STORE_NAME VARCHAR2,
	STORE_TN NUMBER(22,0),
	STORE_TYPE VARCHAR2,
	TIME_ZONE VARCHAR2,
	TRANSFER_PROTOCOL VARCHAR2,
	TRANSFER_TIMEOUT NUMBER(22,0),
	TRANSFER_TO_TN NUMBER(22,0),
	RECORD_LOAD_TIME DATE
) ;
```

Here is a sample insert SQL:

`INSERT INTO fact_rscr_store_data (callid,cache_type,cache_key,start_date,start_time,start_date_time,directions_prompt_id,language_primary,language_secondary,market_id,regular_hours_key,store_id,store_name,store_tn,store_type,time_zone,transfer_protocol,transfer_timeout,transfer_to_tn,record_load_time) VALUES (:callid, :cache_type, :cache_key, :start_date, :start_time, :start_date_time, :directions_prompt_id, :language_primary, :language_secondary, :market_id, :regular_hours_key, :store_id, :store_name, :store_tn, :store_type, :time_zone, :transfer_protocol, :transfer_timeout, :transfer_to_tn, :record_load_time)`

```
And here is an example insert object:
[ { record_load_time: 2019-02-26T04:33:54.723Z,
    callid: 'wp0265ajcd190222141721',
    cache_type: 'retailstoreinfo',
    cache_key: '9402677',
    start_date: '20190222',
    start_time: '141747',
    start_date_time: 2019-02-22T14:17:47.238Z,
    directions_prompt_id: '164577_directions',
    market_id: 68,
    regular_hours_key: 'Su10.20MoSa10.21',
    store_id: 164577,
    store_name: 'CAMARILLO PREMIUM OU',
    store_tn: 8053843595,
    store_type: 'OFP',
    time_zone: 'US/Pacific',
    transfer_protocol: 'CONSULT_CONNECT',
    transfer_timeout: 45000,
    transfer_to_tn: 8448235610,
    language_primary: null,
    language_secondary: null } ]
```
This command:
`
oconn.batchInsert(insertSQL, batchInserts, { autoCommit: autoCommitFlag }, function onResults(error, output) {...}`

 fails with:

TypeError: Cannot read property 'getDate' of null
    at Connection.generateBindDefinitionEntry (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1698:25)
    at Connection.generateBindDefinitions (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1750:18)
    at Connection.insertOrUpdate (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:583:14)
    at Connection.promiseWrapper [as insertOrUpdate] (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/promise-helper.js:185:27)
    at Connection.insert (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:451:17)
    at Connection.batchInsertOrUpdate (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1117:24)
    at Connection.promiseWrapper [as batchInsertOrUpdate] (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/promise-helper.js:185:27)
    at Connection.batchInsert (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1030:17)
    at oconn.run.sequence (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/workers/rscrstoredata.js:115:13)
    at PromiseHelper.runAsync (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/promise-helper.js:63:19)
    at asyncAction (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/simple-oracledb/lib/connection.js:1290:31)
    at /opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:3880:24
    at replenish (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:1011:17)
    at /opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:1016:9
    at _parallel (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit$1 [as parallelLimit] (/opt/app/ivrerp/chiscan2/iy4956/aep_api_1902/node_modules/async/dist/async.js:3985:5)
 

I hope this is what you are looking for.  Thanks again!

**Comment by dmcghan** [comment]
@ilynyeh 

> i know not the right place, but you'll see why I am posting here below

Why are you posting this here? The code you referenced is in simple-oracledb? Try opening an issue there.

Also, have you considered just using the driver directly?

**Comment by cjbj** [comment]
@ilynyeh it was what I was looking for but it didn't uncover any issues with node-oracledb.
To reiterate: you really, really want to be using `executeMany()` for batch uploads.

The following script runs fine in node-oracledb, even without `[bindDefs`](https://oracle.github.io/node-oracledb/doc/api.html#executemanyoptbinddefs) in the `options`.  We would recommend you use `bindDefs`, see some [examples](https://github.com/oracle/node-oracledb/blob/master/examples/em_batcherrors_aa.js).

```
/*

CREATE TABLE FACT_RSCR_STORE_DATA (
        CALLID VARCHAR2(100),
        CACHE_TYPE VARCHAR2(100),
        CACHE_KEY VARCHAR2(100),
        START_DATE VARCHAR2(100),
        START_TIME VARCHAR2(100),
        START_DATE_TIME TIMESTAMP,
        DIRECTIONS_PROMPT_ID VARCHAR2(100),
        LANGUAGE_PRIMARY VARCHAR2(100),
        LANGUAGE_SECONDARY VARCHAR2(100),
        MARKET_ID NUMBER(22,0),
        REGULAR_HOURS_KEY VARCHAR2(100),
        STORE_ID NUMBER(22,0),
        STORE_NAME VARCHAR2(100),
        STORE_TN NUMBER(22,0),
        STORE_TYPE VARCHAR2(100),
        TIME_ZONE VARCHAR2(100),
        TRANSFER_PROTOCOL VARCHAR2(100),
        TRANSFER_TIMEOUT NUMBER(22,0),
        TRANSFER_TO_TN NUMBER(22,0),
        RECORD_LOAD_TIME DATE
);

*/

'use strict';

process.env.ORA_SDTZ = 'UTC';

const oracledb = require('oracledb');
let config;
try {
  config = require('./dbconfig.js');
} catch (err) {
  if (err.code === 'MODULE_NOT_FOUND')
    config = { user: 'cj', password: 'cj', connectString: 'localhost/orclpdb' };
  else
    throw err;
}

let insertSql = `INSERT INTO fact_rscr_store_data
                      (callid, cache_type, cache_key, start_date, start_time, start_date_time, directions_prompt_id,
                       language_primary, language_secondary, market_id, regular_hours_key, store_id, store_name,
                       store_tn, store_type, time_zone, transfer_protocol, transfer_timeout, transfer_to_tn, record_load_time)
                VALUES (:callid, :cache_type, :cache_key, :start_date, :start_time, :start_date_time, :directions_prompt_id,
                        :language_primary, :language_secondary, :market_id, :regular_hours_key, :store_id, :store_name,
                        :store_tn, :store_type, :time_zone, :transfer_protocol, :transfer_timeout, :transfer_to_tn, :record_load_time)`;

let myDate = new Date();

let binds = [ { record_load_time: myDate,
            callid: 'wp0265ajcd190222141721',
            cache_type: 'retailstoreinfo',
            cache_key: '9402677',
            start_date: '20190222',
            start_time: '141747',
            start_date_time: myDate,
            directions_prompt_id: '164577_directions',
            market_id: 68,
            regular_hours_key: 'Su10.20MoSa10.21',
            store_id: 164577,
            store_name: 'CAMARILLO PREMIUM OU',
            store_tn: 8053843595,
            store_type: 'OFP',
            time_zone: 'US/Pacific',
            transfer_protocol: 'CONSULT_CONNECT',
            transfer_timeout: 45000,
            transfer_to_tn: 8448235610,
            language_primary: null,
            language_secondary: null } ];

let options = { autoCommit: true, batchErrors: true };

async function run() {
  let connection;

  try {
    connection = await oracledb.getConnection(config);
    let result;
    result = await connection.executeMany(insertSql, binds, options);
    console.log(result);
  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

run();

```

**Comment by ilynyeh** [comment]
@cjbj

Thank you so much for taking some time to help me.  I was able to implement this using your code as a guide.  You're the best! Take care!
