### ISSUE TITLE
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "/usr/src/app/oracle/instantclient_18_3/libclntsh.so: file too short".

### ISSUE THREAD

**Issue by KaustubhYK** [oracle/node-oracledb#1059]
This is my Dockerfile 
FROM node:carbon

USER root

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod -R 777 /usr/src/app

ENV LD_LIBRARY_PATH="/usr/src/app/oracle/instantclient_18_3"

I am using oracledb@3.1.2  node module to connect with oracle database.
And I am getting above error while calling **getConnection** function of oracledb.

**Comment by cjbj** [comment]
`file too short` sounds like an OS error reporting you have a corrupted Oracle Instant Client installation.

**Comment by KaustubhYK** [comment]
Thanks @cjbj  for responding,
There is only single  line in libclntsh.so , i.e.
** libclntsh.so.18.1 **

**Comment by cjbj** [comment]
That would be the expected symbolic link to libclntsh.so.18.1, which obviously must exist.  Make sure you copy all the files.

Here are some resources that you may be interested in:
- http://yum.oracle.com/oracle-linux-nodejs.html  You could use these packages to install Node.js
- https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/18.3.0/Dockerfile  You could use this as the basis for a container

**Comment by KaustubhYK** [comment]
Thanks @cjbj ,
libclntsh.so file was getting corrupt on windows machine while extracting.
Now I am extracting it directly on my remote environment before setting environment variables.

**Comment by rlunaro** [comment]
I found a cause for this error: this happens if you download the zip files of the instant client from oracle and you **uncompress them on windows instead of on linux**: this causes the symbolic links to be changed into a file with a text content holding only the filename. 

**Instead of decompressing the files on windows and then moving to linux, decompress on linux**. This will eliminate the problem.

**Comment by bmabir17** [comment]
@KaustubhYK can you please share your fixed dockerfile here? it would help a lot.

**Comment by cjbj** [comment]
@KaustubhYK try the new node-oracledb 6 default Thin mode: this doesn't need Instant Client, so installing will be a lot smoother. See the [release announcement](https://medium.com/@sharad-chandran/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2).

**Comment by yooman00** [comment]
@KaustubhYK and @bmabir17 can you share your solution?
DPI-1047: Cannot locate a 64-bit Oracle Client library: "/opt/oracle/instantclient_23_6/libclntsh.so: file too short".

I have the same issue. I checked the client installation it seems ok.
# ldconfig -p | grep libclntsh.so
        libclntsh.so.23.1 (libc6,x86-64) => /opt/oracle/instantclient_23_6/libclntsh.so.23.1
