### ISSUE TITLE
Instrument oracle db : Cannot redefine property: getConnection

### ISSUE THREAD

**Issue by devarajchidambaram** [oracle/node-oracledb#1063]
Im wrapping oracledb  module like this

```
var oracledb = require('oracledb');
var shimmer = require('shimmer')

  shimmer.wrap(oracledb , 'getConnection', function(orig){
    return function(){
      var returned = orig.apply(this, arguments)
      console.log('arguments==',arguments)
      return returned
    }
  })

```

throwing  error like this 

```
D:\Instrument\wrap_oracle\node_modules\shimmer\index.js:14
  Object.defineProperty(obj, name, {
         ^
TypeError: Cannot redefine property: getConnection
    at Function.defineProperty (<anonymous>)
    at defineProperty (D:\Instrument\wrap_oracle\node_modules\shimmer\index.js:14:10)
    at Function.wrap (D:\Instrument\wrap_oracle\node_modules\shimmer\index.js:56:3)
    at Object.<anonymous> (D:\Instrument\wrap_oracle\oracle_db.js:8:11)
```

is there any other options is available for  wrap the oracle db ?

**Comment by cjbj** [comment]
The (unreleased) refactoring of node-oracledb for [N-API](https://nodejs.org/api/n-api.html) resolves this specific case; I didn't try others.  But see https://github.com/oracle/node-oracledb/issues/1053#issuecomment-469908577.  The Node.js performance issue was fixed a few days ago in Node.js master. We still are waiting to see if it lands in Node 8 & 10 before committing to using N-API for node-oracledb 4.0.  And then we have to add some user features to make it worth releasing node-oracledb 4.0 - which will take time, not only because of upcoming conferences and vacations etc.

With the new node-oracledb version, this:

```
const oracledb = require('oracledb');
console.log('node-oracledb version: ' + oracledb.versionString);
let config = require('./dbconfig.js');

const shimmer = require('shimmer');

shimmer.wrap(oracledb , 'getConnection', function(orig){
  return function() {
    var returned = orig.apply(this, arguments);
    console.log('arguments==',arguments);
    return returned;
  };
});

async function run() {
  let connection;
  try {
    connection = await oracledb.getConnection(config);
    console.log('Connected successfully');
  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
	await connection.close();
      } catch (err) {
	console.error(err);
      }
    }
  }
}

run();
```

Gives:

```
node-oracledb version: 4.0.0-dev
arguments== [Arguments] {
  '0':
   { user: 'cj',
     password: 'cj',
     connectString: 'localhost/orclpdb',
     externalAuth: false } }
Connected successfully
```

At some stage soon I'll push a development code branch to GitHub so you can build and play with it yourself.

**Comment by cjbj** [comment]
I pushed a development branch https://github.com/oracle/node-oracledb/tree/dev-4.0 that you can [try](https://oracle.github.io/node-oracledb/INSTALL.html#githubtags) with `npm install oracle/node-oracledb#dev-4.0`.  Let us know how it goes.

**Comment by cjbj** [comment]
@devarajchidambaram If you need to work with node-oracledb 3.1 you could modify the lib/*.js files and make changes like:

```
diff --git a/lib/oracledb.js b/lib/oracledb.js
index 3196f0ec..fc2829e1 100644
--- a/lib/oracledb.js
+++ b/lib/oracledb.js
@@ -632,6 +632,7 @@ function extend(oracledb) {
       },
       getConnection: {
         value: getConnectionPromisified,
+        configurable: true,
         enumerable: true,
         writable: true
       }
```

This comes from https://github.com/oracle/node-oracledb/issues/505#issuecomment-252679780

**Comment by devarajchidambaram** [comment]
Thanks @cjbj

**Comment by cjbj** [comment]
@devarajchidambaram Node-oracledb 4.0 has been released with a fix for this.  The release announcement is at https://blogs.oracle.com/opal/oracle-db-named-objects-and-advanced-queuing-support-new-in-node-oracledb-40
