### ISSUE TITLE
ORA-00903: invalid table name

### ISSUE THREAD

**Issue by eunier14** [oracle/node-oracledb#1065]
I'm getting this error:
`ORA-00903: invalid table name`

This is the code:
```
var dotevn = require('dotenv');
var oracledb = require('oracledb');

dotevn.config({
  path: './.env'
});

var user = process.env.BD_TEST_USER;
var pw = process.env.BD_TEST_PASS;
var connectString = process.env.DB_CONNECT_STRING;

oracledb.getConnection(
  {
    user: user,
    password: pw,
    connectString: connectString
  },
  function(err, connection) {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      'SELECT * FROM :TABLE_NAME_HERE',
      [103], // bind value for :id
      function(err, result) {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
        console.log(result.rows);
        doRelease(connection);
      }
    );
  }
);

function doRelease(connection) {
  connection.close(function(err) {
    if (err) console.error(err.message);
  });
}
```

If I run the SQL string as below:

`SELECT * FROM TABLE_NAME_HERE`

I get:

`ORA-01036: illegal variable name/number`

I'm able to run the SQL string from the "Oracle SQL Developer" interface just fine, which is:

`SELECT * FROM TABLE_NAME_HERE`

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?
x64
undefined

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?
3.1.2

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?
ORA-00903: invalid table name

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?
win32

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
18.3.0.0.0

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?
11.2.0.4.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
C:\oracle\instantclient_18_3

**Comment by anthony-tuininga** [comment]
Unfortunately, you cannot use bind variables to replace the name of a table. It can only be used for providing data that will be stored in the database, not for any part of the SQL statement itself. You'll need to use string manipulation to create a valid SQL statement -- while at the same time sanitising the input and avoiding SQL injection. Sorry to be the bearer of bad news!

**Comment by dmcghan** [comment]
@eunier14 See section 18.8 of the doc, [Binding Column and Table Names in Queries](https://oracle.github.io/node-oracledb/doc/api.html#-188-binding-column-and-table-names-in-queries), for some tips.

**Comment by eunier14** [comment]
> @eunier14 See section 18.8 of the doc, [Binding Column and Table Names in Queries](https://oracle.github.io/node-oracledb/doc/api.html#-188-binding-column-and-table-names-in-queries), for some tips.

I got to

**Comment by eunier14** [comment]
Thanks for the quick relay. What if I don't want to use binding for table names. I'm trying to query:
`SELECT * FROM TEST_TABLE`
and I'm getting a 
`ORA-01036: illegal variable name/number`
I section 1.1.1 fo the doc, they use:
```
`SELECT manager_id, department_id, department_name
       FROM departments
       WHERE manager_id = :id`
```
The table name is "hard-coded" yet mine won't work. TEST_TABLE is an actual table on the database.

**Comment by anthony-tuininga** [comment]
If the code you are using is similar to what you had before, you have a bind value specified, but no bind variables. That will cause ORA-01036: illegal variable name/number to occur.

**Comment by eunier14** [comment]
> If the code you are using is similar to what you had before, you have a bind value specified, but no bind variables. That will cause ORA-01036: illegal variable name/number to occur.

You're right.  It worked. I remove the bind value. Silly me. Thanks.
