### ISSUE TITLE
Install issue on Windows7 64bit

### ISSUE THREAD

**Issue by nsuneel** [oracle/node-oracledb#1066]
*Delete unnecessary parts of this template.*

I downloaded hr_app from GitHub which uses oracledb and when I try to install oracledb I am getting an error.

NPM Version 6.1.0
Node Version v10.3.0
Windows 7 64bit
Visual Studio Code 1.32.2
Oracle Client: 11.1.0.7.0

Visual Studio Code Proxy:
// Place your settings in this file to overwrite the default settings
{
    "http.proxy": "http://something.domain.com:9090",
    "http.proxyStrictSSL": false
}

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?

Node Version v10.3.0

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?

oracledb@2.3.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

npm install oracledb

As Admin

4. What error(s) you are seeing?

C:\hr_app>npm install oracledb

> oracledb@2.3.0 install C:\hr_app\node_modules\oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v64-win32-x64.gz
oracledb ERR! connect ETIMEDOUT 192.30.253.113:443
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN hr_app@0.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.3.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Node.js script that immediately runs to show us the problem?

**Comment by cjbj** [comment]
> oracledb ERR! connect ETIMEDOUT 192.30.253.113:443

This is your problem.  You are unable to access GitHub, which was needed for installation in 2.3.

Instead of digging into the reasons, I suggest you simply upgrade to 3.1.2 which doesn't try to contact GitHub.

> Oracle Client: 11.1.0.7.0

This will be a problem because you need 11.2 or higher.

**Comment by dmcghan** [comment]
@nsuneel Just a quick followup. I updated all of the dependencies in that part of the repo so others will not have to do that manually. Thanks for the heads up.
