### ISSUE TITLE
returning id into .. NOT working with insert after select

### ISSUE THREAD

**Issue by orkhi** [oracle/node-oracledb#1067]
The below code works if I remove  **RETURNING id INTO :tempID**. Otherwise it gives 
ORA-00933: SQL command not properly ended. 

let **tempSql2** = "**INSERT** INTO intent (name,faq,response,description,json_id, category_id)                         **SELECT** intent.NAME, intent.FAQ, intent.RESPONSE, intent.DESCRIPTION, intent.JSON_ID, :a from intent where intent.id = :b **RETURNING id INTO :tempID"** 

connection.execute(tempSql2, 
  {      a:76,       b:7,      tempID:{type: oracledb.NUMBER, dir: oracledb.BIND_OUT}   }, {autoCommit: true},  
  function (err, result) {
      if (err) {
         console.log(err.message);
         connection.close();
         cb('error',err.message) ;
       }else {
            console.log("Result "+JSON.stringify(result));   
            connection.close();
            cb("done","Success!");
        }
});

**Comment by cjbj** [comment]
To expand on my previous comment, I have a feeling this is a limitation of SQL, and it not a node-oracledb implementation issue.  Some googling shows similar questions and various solutions.

**Comment by orkhi** [comment]
@cjbj Many Thanks
