### ISSUE TITLE
Can we force to use Oracle Client 11.1?

### ISSUE THREAD

**Issue by nsuneel** [oracle/node-oracledb#1068]
Creating new one because other ticket closed. I have Oracle Client: 11.1.0.7.0 installed. 

I guess we need 11.2 or higher, but is there a way to force to use 11.1?

**Comment by anthony-tuininga** [comment]
May I ask why you want to use such an old version of the Oracle Client libraries? They are no longer supported and free upgrades to supported versions of the Oracle Client libraries are available.

**Comment by nsuneel** [comment]
We have a standard and all servers are configured to use 11.1 and it take long time to get everything upgraded! That’s why and I am trying to see if I can bypass that step.

**Comment by anthony-tuininga** [comment]
Unfortunately, no. You might be able to rip out the constraints and have portions work -- but I wouldn't recommend that. I'd recommend upgrading at least the client.

**Comment by nsuneel** [comment]
Thanks
