### ISSUE TITLE
Cannot find module 'oracledb' on Windows installation of oracledb driver

### ISSUE THREAD

**Issue by RogelioGaytan** [oracle/node-oracledb#107]
Hi
   I'm having troubles with the installation on windows.

   At this point i've done every step in the installation instructions, so far

 I installed the whole stack in 64 bits:
 -   node-v0.12.4-x64.msi
 -   python-2.7.10.amd64.msi
 -    instantclient-basic-windows.x64-12.1.0.2.0.zip
 -   instantclient-sdk-windows.x64-12.1.0.2.0.zip

Unzip into one folder the install client 
  C:\oracle\instantclient_12_1

Set de system variables:

OCI_INC_DIR  C:\oracle\instantclient_12_1\sdk\include
OCI_LIB_DIR  C:\oracle\instantclient_12_1\sdk\lib\msvc

Added them to de PATH  = %OCI_INC_DIR%;%OCI_LIB_DIR%

Then I run de command prompt as administrator and install de driver

   npm install oracledb

It ends with ok so i assume it is installed correctly

Then I try to run the examples and it throws me this error:

C:\GitHub\node-oracledb\examples>node connect.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\GitHub\node-oracledb\examples\connect.js:27:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Any help would be appreciated.

**Comment by BlackMatrix971** [comment]
Use NodeJS v0.10.39, it will be ok.

**Comment by RogelioGaytan** [comment]
Ok, i unistalled node12 and installed node-v0.10.38-x64 ( i couldn't find 0.10.39 :S ). But keeps me telling the same thing

C:\GitHub\node-oracledb\examples>node connect.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\GitHub\node-oracledb\examples\connect.js:27:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by BlackMatrix971** [comment]
Sorry, I mean 10.38

delete oracledb from node_module, reinstall oracledb and then run !

**Comment by RogelioGaytan** [comment]
I did that, and still got the same message.

Perhasps this would help to have a view of what i'm doing.

The node installer puts it in C:\Program Files\nodejs

Then in the command prompt i locate in C:\Program Files\nodejs\node_modules
from ther is where i run:   "npm install oracledb"

and that is where the folder with the driver is installed and compiled.

Then i position the prompt where the examples are, in 

C:\GitHub\node-oracledb\examples

then i run the command:  node connect.js

And that's where the error oracledb not found is thrown

Should i change the location folder of de examples ?.

**Comment by cjbj** [comment]
I'm sure either 0.12 or 0.10 are fine.

It just sounds like PATH is not set correctly at runtime.  For a start there is no need to add the include files OCI_INC_DIR to it.   In the command window you are running node, do a echo %PATH% and sh

**Comment by RogelioGaytan** [comment]
@cjbj I deleted the variables from the path, and i still  get the same error message.

    :S   :(

**Comment by RogelioGaytan** [comment]
Any other advice?

I've installed it in linux and mac succesfully but in windows has been too much trouble

**Comment by BlackMatrix971** [comment]
node_modules should be in the js path.

**Comment by RogelioGaytan** [comment]
@BlackMatrix971 Could you show me how you have it configured?

The path, variables and stuff?

**Comment by cjbj** [comment]
@RogelioGaytan can you show us your settings? The info about 'echo %PATH%' that I asked for earlier would be useful.

**Comment by RogelioGaytan** [comment]
Sure.

![echo path](https://cloud.githubusercontent.com/assets/4450400/7969762/bc7ca3de-09fe-11e5-91b9-3ec9053713ca.png)

**Comment by RogelioGaytan** [comment]
![variables entorno](https://cloud.githubusercontent.com/assets/4450400/7969803/0ad23cb0-09ff-11e5-9567-9d363a1be2a5.png)

**Comment by cjbj** [comment]
OCI_INC_DIR and OCI_LIB_DIR are not needed once you have built the driver, so unset those.

I forget Windows subtleties about whether that %ORACLE_CLIENT12% will get expanded or whether it needs to be a full path.  I notice you have some 11g directories earlier in the path but you compiled node-oracledb with 12c libraries.  For node-oracledb, the first Oracle libraries in PATH need to be the ones that you built with (or a newer version). There's no magic to this requirement - the same is true of Linux and OS X library search paths.

**Comment by RogelioGaytan** [comment]
Ok, I just did a clean install in a windows just installed (this time 32 bits version) so there are no paths pointing to previous versions of oracle.

But It keeps telling me the same message, Cannot find oracle DB.

First I installed Node, Python, VisualStudio2012, and the zip with de oracle instantclient and sdk.

![0](https://cloud.githubusercontent.com/assets/4450400/8011957/1f7639de-0b83-11e5-973f-1a55e94767fe.png)

Then I run de VisualStudio prompt as an administrator

![1](https://cloud.githubusercontent.com/assets/4450400/8011976/43e7fa64-0b83-11e5-9b0e-0658b91abd72.png)

Then set de variables and install oracledb

![2](https://cloud.githubusercontent.com/assets/4450400/8011989/62cfdbae-0b83-11e5-80d5-5fc8e92a3a08.png)

But keeps telling that it can not find de oracledb when i try tu execute an example

![3](https://cloud.githubusercontent.com/assets/4450400/8012000/826213ce-0b83-11e5-95fc-9625ee3eb743.png)


Any other pointers to succesfully install the driver would be appreciated.  Thanks

**Comment by cjbj** [comment]
I'd check that oracledb got installed in a location in the node search path. You are installing in one directory but running node from another. 
- Maybe you need to edit the example and give the path to oracledb in the require() call, or set NODE_PATH
- I'd check that the 32 bit Instant Client was the architecture installed, since you are trying to do a 32bit build.
- it's not ideal for me to visually scan a screen shot, so you should triple check PATH has no other Oracle software before the instant client directory.

**Comment by cjbj** [comment]
If PATH is an issue, you could try copying the Instant Client libs like done in https://github.com/oracle/node-oracledb/issues/88

**Comment by RogelioGaytan** [comment]
@cjbj 
>"I'd check that oracledb got installed in a location in the node search path. You are installing in one directory but running node from another."

I'm new to Node, this is my first time i'm gonna use it so i'm not sure where is the node search path but the msi installer puts everything in C:\Program Files\nodejs

![node installation](https://cloud.githubusercontent.com/assets/4450400/8013846/8ac593ca-0b91-11e5-9d97-ec27985ddbb0.png)

When I locate the command prompt to install oracledb, it's in : C:\Program Files\nodejs\node_modules

And as seen in the previous screenshot it creates its respective folder with all the stuff.

The folder with the examples of using oracledb i have it somewhere else.


>"Maybe you need to edit the example and give the path to oracledb in the require() call, or set NODE_PATH

The path of the oracle.js file or another one?

>I'd check that the 32 bit Instant Client was the architecture installed, since you are trying to do a 32bit build.

Yes, they are 32 bit instant client

>it's not ideal for me to visually scan a screen shot, so you should triple check PATH has no other Oracle software before the instant client directory.

I'm absolutly sure theree is no ohter instant client because this is a fresh install of windows in a virtual machine, so there are nothing more installed.


I'm going to try putting the client directly. Thanks and I'll keep informed if it worked

**Comment by RogelioGaytan** [comment]
Didnt work :(.

I made NODE_PATH, didnt work,

Put the instant client directly like #88  in the release folder and still didn't work.

Oficially I'm giving up, I'll wait 'till a video tutorial showing the installation on windows comes out.

In the meantime i'll sell ice cream instead of programming :P XD

I'm very grateful for all your help @cjbj @BlackMatrix971 thanks for your time.

**Comment by BlackMatrix971** [comment]
Hi @RogelioGaytan.
Really sorry. I could not be for greater help. I use node on ubuntu running in a VM.
I have faced some problem when I tried to make oracle run on MacOSX.

OracleDB 0.6.0 is quite new, the last thing you could try is to install 0.4.3 for node 10.38 mixed with InstantClient 11_2.

This is the winner triplet, more stable.

If you need private advice : 
jeff_dom77 at yahoo dot fr

**Comment by cjbj** [comment]
@BlackMatrix971 why do you think the old versions are more stable?

**Comment by BlackMatrix971** [comment]
@cjbj 
I have tested that combination.
When I try to mix with new stuff, I get trouble.
I should say easier to build instead of more stable.
Sorry, I hope you have noticed that I'm not english ;-)

**Comment by RogelioGaytan** [comment]
Well, just yesterday tried once again to run the examples, just move out the examples folder, did an npm install oracledb inside the examples folder and it worked !!.

I don't know what thing in the path of all things i did, worked, i don't know if moving the instantclient files inside de node_modules of the node path, or what happened, but now it works, i don't know why but it does :)

Thank you all.

@BlackMatrix971  By any chance, do you speak spanish? i'm not an english folk either as maybe you have noticed :p

**Comment by RogelioGaytan** [comment]
I think one of the things that prevented me to install it and i just did a test is that you MUST put the instant client in the c:\oracle\instantclient folder instead of c:\oracle\instantclient_12_1 so you don't have to set the OCI_LIB_DIR=C:\oracle\instantclient_12_1\sdk\lib\msvc OCI_INC_DIR=C:\oracle\instantclient_12_1\sdk\include  variables because the installer got confused .

Weird :S

**Comment by cjbj** [comment]
@RogelioGaytan it sounds like your problem is fixed. The requirement about the instant client path doesn't seem right, but it works - use it.

**Comment by cjbj** [comment]
@BlackMatrix971 regarding older versions, do you remember the errors & problems building the new version?

**Comment by BlackMatrix971** [comment]
Yes !
All where concerning compiling oracle module with npm install.
I can try back in the same condition if it can help you.
I'll be back in 15 days.

I'm in vacation for now.
