### ISSUE TITLE
how can I know the encoding of buffer when using "oracledb.fetchAsBuffer = [oracledb.BLOB]"

### ISSUE THREAD

**Issue by blackmatch** [oracle/node-oracledb#1070]
I want to get the `BLOB` data from oracle database, and then convert it to string, and then save the string value to MYSQL database.

* The encoding of oracle database is `SIMPLIFIED CHINESE_CHINA.ZHS16GBK`.
* I use `oracledb.fetchAsBuffer = [oracledb.BLOB]` to get buffer data.

When I got the buffer data, I tried to convert it to string with Node.js. But I always got wrong string with some unknown codes.

I use [iconv-lite](https://github.com/ashtuchkin/iconv-lite) to convert buffer to string, I tried many encodings.

Who can tell me some ideas?

**Comment by cjbj** [comment]
What encoding is the data actually in?  Show us some sample code (and data would help).

**Comment by blackmatch** [comment]
@cjbj 

Here is the code:

```js
const iconv = require('iconv-lite')
const oracledb = require('oracledb')

oracledb.fetchAsBuffer = [oracledb.BLOB]

oracledb.getConnection(hisdb.connection, (err, con) => {
  if (err) {
    throw err
  }
  const sql = 'xxxx'
  con.execute(sql, (err, result) => {
    if (err) {
      throw err
    }
    console.log(result.rows)
    
    for (const item of result.rows) { 
      for (const data of item) {
        if (Buffer.isBuffer(data)) {
          const str = iconv.decode(data, 'utf-16le') // decode buffer to string
          console.log(str)
        }
      }                                                                                                                                         
    }                                                                                                                                                        
  })                                                                                                                                                                                                                                                                                                                               
})
```

And I log the buffer value, like [this](https://gist.github.com/blackmatch/0fa9b43791857ec290bf1471833e7bd6)

**Comment by cjbj** [comment]
What encoding is the data actually in?

**Comment by blackmatch** [comment]
@cjbj This is what I want to know. how `oracledb` convert `BLOB` data to `Buffer` when I use  `oracledb.fetchAsBuffer = [oracledb.BLOB]` ? Dose it use a default encoding ?

**Comment by cjbj** [comment]
Your data must have been inserted into the DB by some tool as some byte stream.  Those bytes must have some encoding so other tools know how to decode them.  What exactly is that encoding?  (And why are you using BLOBs for text???)

**Comment by blackmatch** [comment]
@cjbj 
Our clients support data to us by oracle database, they save some very long text as BLOBs(maybe oracle database limit text type length 4kb?). They have some data more than 100kb 😭 . I try to know what the encoding they use when they save data to oracle database. Thanks you very much.
