### ISSUE TITLE
Formatting JSON output 

### ISSUE THREAD

**Issue by chezdrz** [oracle/node-oracledb#1071]
Taking a simple Emp/Dept example 
currently a  console.log(result.rows); will return data in the following format.

[ 
  [ '1001','Marketing' ],
  [ '1002','Sales' ]
 ]
 
Is there any example on how to format the data such I get it in this format ?

 [ 
{ "empid":"1001","dept":"Marketing"},
{ "empid":"1002","dept":"Sales"}
]

Note: Am on Oracle db 12.1.x currently

**Comment by anthony-tuininga** [comment]
Sure. See the value of ``oracledb.outFormat`` to ``oracledb.OBJECT`` as shown in the [documentation](https://oracle.github.io/node-oracledb/doc/api.html#-3214-oracledboutformat).

**Comment by chezdrz** [comment]
Thank you, this resolved it.
