### ISSUE TITLE
How to connect remote Oracle databases at version 11.2 and 10.2 from one server？

### ISSUE THREAD

**Issue by exialym** [oracle/node-oracledb#1072]
Your Doc says：
Oracle Client libraries 18 and 12.2 can connect to Oracle Database 11.2 or greater. Version 12.1 client libraries can connect to Oracle Database 10.2 or greater. Version 11.2 client libraries can connect to Oracle Database 9.2 or greater.

but Our application need to connect Oracle databases at version 11.2 and 10.2 at the same time.

Which  library should I use？

**Comment by cjbj** [comment]
Use 12.1 as mentioned in "Version 12.1 client libraries can connect to Oracle Database 10.2 or greater".  If that sentence isn't clear, let us know what to change it to to help future readers.

**Comment by exialym** [comment]
Thank you @cjbj

**Comment by exialym** [comment]
Thank you @cjbj

**Comment by exialym** [comment]
Thank you @cjbj ! But when I trying to use Version 12.1 client libraries. I got this error: `DPI-1050: Oracle Client library is at version 12.1 but version 18.1 or higher is needed`

**Comment by exialym** [comment]
@cjbj Thank you.
