### ISSUE TITLE
TypeError: Cannot read property 'getRow' of undefined

### ISSUE THREAD

**Issue by dysonjm** [oracle/node-oracledb#1073]
Hi 

I am using oracle db with node js for retrieving data from oracle procedure as ref cursor .
I am getting the below error when I am using the function getRow or gerRows .

TypeError: Cannot read property 'getRow' of undefined

Any one please help me to resolve this .

Here is my code spinet . 
   connection.execute(
        `BEGIN duflip.duflip_menu(:main_menu); END;`,
        {
          // bind variables
          main_menu: { dir: oracledb.BIND_OUT, type: oracledb.CURSOR }
        },
        function(err, results) {
          if (err) {
            console.error(err.message);
            return;
          }
          console.log(results.outBinds);
          **results.outBinds.resultSet.getRow(function(err,row){**
              console.log('rows');
          });           
          console.log(results.outBinds);
          res.status(200).json({
            mainmenu: results.outBinds
          });
        }
      );

**Comment by cjbj** [comment]
Try it in a simple script without the web interaction and get that working.

Check the examples, such as [refcursor.js](https://github.com/oracle/node-oracledb/blob/master/examples/refcursor.js) and [refcursortoquerystream.js](https://github.com/oracle/node-oracledb/blob/master/examples/refcursortoquerystream.js).  You may find the async/await versions easier to work with, see the [dev-4.0 branch](https://github.com/oracle/node-oracledb/tree/dev-4.0/examples).

**Comment by dysonjm** [comment]
hi cjbj ,
Thank you for your input . 
It worked ..
