### ISSUE TITLE
can be done connection.subscribe() return regid?

### ISSUE THREAD

**Issue by Leon-Alexey** [oracle/node-oracledb#1075]

**Comment by Leon-Alexey** [comment]
the name does not match the name in USER_SUBSCR_REGISTRATIONS.SUBSCRIPTION_NAME

**Comment by anthony-tuininga** [comment]
Currently the registration id is only known by PL/SQL and is not available with the Oracle Client libraries. I'll ask internally if this can be changed at some point.

**Comment by cjbj** [comment]
This will be in node-oracledb 4.  See the dev-4.0 branch.  Documentation is at https://github.com/oracle/node-oracledb/blob/dev-4.0/doc/api.md#consubscribecallback

**Comment by cjbj** [comment]
Node-oracledb 4.0 has been released with an enhancement for this, see https://oracle.github.io/node-oracledb/doc/api.html#consubscribecallback.  The release announcement is at https://blogs.oracle.com/opal/oracle-db-named-objects-and-advanced-queuing-support-new-in-node-oracledb-40
