### ISSUE TITLE
TNSPING functionality in node-oracledb

### ISSUE THREAD

**Issue by ChrisHAdams** [oracle/node-oracledb#1077]
### General Question - Not Issue

Using node-oracledb, is it possible to make a tnsping like call to see if a database is listening without having first made a connection?

#### Background
I've built a healthcheck monitor using Node.  This monitor calls websites, web-services and pings servers to check they are up and running.

I've used node-oracledb to connect to databases to establish they are up and running, but we have some concerns around this as this means establishing a connection to the database and the db credentials are in clear-text in a config file.

We could encrypt the credentials, but our DBA suggested that a tnsping might be more useful as it doesn't require a log in.  I don't have a oracle client installed on the Node server, just node-oracledb.  Reading through the docs, there is a conn.ping() method that can be called, but the docs show this can only be used to check whether a previously opened connection can still be used, and therefore requires an initial login and we're back at the credentials in clear-text territory.

**Comment by cjbj** [comment]
From experience, if you really want to make sure that a DB is useable, then create a real connection to the DB.  You should/could use external authentication.  Or at least use an env variable.

There is no tnsping functionality in node-oracledb  - or in Instant Client, but that's another, known, story.
