### ISSUE TITLE
Getting error Error: "DPI-1047: Cannot locate a 64-bit Oracle Client library

### ISSUE THREAD

**Issue by johnysv** [oracle/node-oracledb#1078]
I am trying to connect Oracle DB (linux) from node.js(some other machine). but getting the below error.

Telnet for the db port works fine.
Able to query through sqldeveloper.

"Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found" node js"

**Comment by johnysv** [comment]
Do you mean that I need to install Oracle client lnstant client in my machine where I have node.js? My actual db is in some other linux remote server .

**Comment by anthony-tuininga** [comment]
Yes, you need to install the Oracle Client libraries (such as Instant Client) in the machine where you are running Node.js.

**Comment by johnysv** [comment]
I installed Instant client 18_5 (added to PATH). I also found vs redistributable is already installed (which u can see in screen shot). But now I get the below error

"{ Error: ORA-12154: TNS:could not resolve the connect identifier specified errorNum: 12154, offset: 0 }"

Please help me resolve this.

![image](https://user-images.githubusercontent.com/41629868/55962653-dadc5780-5c60-11e9-9bbf-1f17caf20523.png)

**Comment by anthony-tuininga** [comment]
That error means that your installation is working. What connect string are you using? There are two general formats:

1) a simple string which is looked up in ``$TNS_ADMIN/tnsnames.ora`` (or a specific location if the environment variable is not specified)

2) an EZ connect string in the format ``host[:port]/service`` such as ``localhost/DB18``

Of the two, I'd suggest the latter as it is easier to use, but if your environment has tnsnames set up that will work as well.

If you can provide the code you are using and the full connect string we might be able to help further. Just mask the user name and password with ``<user>`` and ``<password>`` or some such.

**Comment by johnysv** [comment]
Here is my code

var mypw = "*****"

var oracledb = require('oracledb');
oracledb.getConnection(
  {
    user          : "u_name",
     password      : mypw,
     connectString : "jdbc:oracle:thin:@10.90.103.4:1521:cita"
  },
  function(err, connection)
  {
    if (err) { console.error(err); return; }
    connection.execute(
      `select name from CLE_EXCEPTIONRECORD where CORRELATIONID='983b2f58-e0eb-49cb-b76c-9b8107de3edc'`,
      function(err, result)
      {
        if (err) { console.error(err); return; }
        console.log(result.rows);
      });
  });

Also see the below screen shot taken from sqldeveloper
![image](https://user-images.githubusercontent.com/41629868/56018427-a2388e80-5cf1-11e9-8667-
b0cfd45fba3c.png)

Below is the screen shot from developer tool TIBCO

![image](https://user-images.githubusercontent.com/41629868/56018559-fa6f9080-5cf1-11e9-8e49-d1b0a864e6cd.png)

**Comment by anthony-tuininga** [comment]
That's helpful. You can't use the JDBC thin driver with node-oracledb. So instead of this connect string:

``jdbc:oracle:thin:@10.90.103.4:1521:cita``

use this connect string

``10.90.103.4:1521/cita``

**Comment by johnysv** [comment]
Hi,

Thanks, I guess I get some output. But the Output is not understandable. Please see the below output.

 [ Lob {
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      iLob: [Object],
      close: [Function] } ],


But when I query the same in putty, I get the correct column value.

**Comment by anthony-tuininga** [comment]
The default behaviour when fetching a CLOB or BLOB value is to return a LOB object, which allows for streaming. If you know the size of the CLOB and BLOB are reasonably small (a few megabytes) it is far easier to return them as plain strings and buffers. You can do that by adding the following code:

```
oracledb.fetchAsString = [oracledb.CLOB];
```

You can see a full example [here](https://github.com/oracle/node-oracledb/blob/master/examples/lobselect.js).

**Comment by cjbj** [comment]
@johnysv you seem to have missed our [installation documentation](https://oracle.github.io/node-oracledb/INSTALL.html) and our [userguide](https://oracle.github.io/node-oracledb/doc/api.html).  Have a scan through those.
