### ISSUE TITLE
Provide ORA error numbers as constants

### ISSUE THREAD

**Issue by terohuomo** [oracle/node-oracledb#1080]
When executing an sql query with `oracledb` library, an error can be thrown by the module. The module will insert a `errorNum` variable to the thrown error. This includes the underlying ORA error number. For example if execute throws `ORA-00904`, `errorNum` will be 904.

It is my understanding that these error numbers are standard, and do not change between Oracle database versions. I would want these error numbers to be included as constants/enumeration straight in `node-oracledb` module.

Providing the error numbers helps with for example handling the errors or providing correct error messages for frontend.

Example usage for case where error number constants were provided:
```js
const oracledb = require('oracledb')

// omitted irrelevant code for setting up connections, queries etc.

try {
  const result = await connection.execute(query, parameters, options);
  // do something with result
} catch (error) {
  const { errorNum } = error;
  if (errorNum === oracledb.errors.UNIQUE_CONSTRAINT_VIOLATED) {
     // do something
   } else if (errorNum === oracledb.errors.PARENT_KEY_VIOLATED) {
     // do something else
   } else {
     // etc.
   }
}

```

Currently I have similarly defined my own js-file containing constant for error numbers I want to handle separately, but I need to duplicate it to new projects, manually update it and search for the relevant oracle error numbers.

**Comment by anthony-tuininga** [comment]
Thanks for the suggestion. We'll consider it and get back to you.

**Comment by cjbj** [comment]
There are [too many Oracle error numbers](https://docs.oracle.com/en/database/oracle/oracle-database/19/errmg/index.html). It isn't feasible for node-oracledb to have constants for them.  And everyone's use of node-oracledb is different, so identifying a subset of error numbers wouldn't satisfy everyone.

**Comment by dmcghan** [comment]
@terohuomo Just throwing this out there to you or anyone that may stumble on this in the future. If you think there's real value in having the errors in such a format, you could always create a new, separate module. I imagine it would look something like https://www.npmjs.com/package/http-errors or https://www.npmjs.com/package/http-status-codes.
