### ISSUE TITLE
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library

### ISSUE THREAD

**Issue by victorgianvechio** [oracle/node-oracledb#1081]
I'm developing an application node that connects to oracle database. The following error appears when you try to connect:

Error:  Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "C:\oracle\app\Desenv\product\11.1.0\db_1\bin\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

Can someone help me?

**Comment by anthony-tuininga** [comment]
You need to have a 64-bit Oracle Client installed and you currently have a 32-bit Oracle Client installed. Take a look at the links provided in the help message for further help.

**Comment by victorgianvechio** [comment]
I checked the links but did not find anything that would help me ... Does not work with 32 bits?

**Comment by anthony-tuininga** [comment]
You can use a 32-bit Oracle Client, but only if you have a 32-bit Node.js installation as well. We don't provide 32-bit binaries so you'll need to compile it yourself. I'd recommend using 64-bit, though. You simply have to download a 64-bit Oracle Instant Client from the link that was provided in the error message (http://www.oracle.com/technetwork/topics/winx64soft-089540.html).

**Comment by victorgianvechio** [comment]
I installed version 64 in parallel to 32. I changed the system variable to client 64 and it worked.

Thanks for the help!

**Comment by sdamte0428** [comment]
Hi , 
Please help , I am having the same issue for last couple of days . I have set the paths and checked all the versions seems 64bit . But I couldn't connect python 3.8.3 with oracle 19c using the 19.3 oracle instant client version .
attached my error message .
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    con = cx_Oracle.connect("hr/oracle@localhost/orcl")
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1)
I am connected to Oracle VM .

Thanks

**Comment by masterull** [comment]
try 
sudo sh -c "echo /usr/lib/oracle/18.3/client64/lib > /etc/ld.so.conf.d/oracle-instantclient.conf"
and 
sudo ldconfig

**Comment by hamzatariq9396** [comment]
I installed 64 bit node with 64 bit Oracle but it is not working
