### ISSUE TITLE
Run two connections with dependencies 

### ISSUE THREAD

**Issue by martaRodri** [oracle/node-oracledb#1082]
It is possible to execute with SYS the creation of a user. And continue using the new user afterwards, to make queries. Using that connection or creating a new one

**Comment by Sushanth2693** [comment]
Yes, it is possible. From existing connection give 

SQL> conn newuser/password

For new connection you can give

$ sqlplus newuser/password@TNSNAME

Make sure to give all the necessary privileges and permissions to the new user while connected with SYS user.

**Comment by albertoMarquez** [comment]
I ´m sorry. I think I have not explained myself well. I'll give you an example of what I want to do to see if you can help me with it.

Here I call the two fiunctions that have dependencies between:

```
oracleProfesor.connect(filas,request.body,(sol)=>{
                console.log(sol);
                oracleAlumno.connect(filas,request.body,(alumno)=>{
                    console.log(alumno);
                    daoE.subirProcedimientoAlumno(request.body, (err, filas)=>{
                        if(err){
                            response.status(400);
                            response.end();
                        }else{
                            response.json(filas);
                            response.status(201);
                            response.end();
                        }
                    })
                });
            });

```
### oracleAlumno.js:
```
`var oracledb = require('oracledb');
//var async = require('async');
var dbConfig = require('./dbconfig.js');
var fs = require("fs");
oracledb.autoCommit= true;

function connect(sql,datos,callback){
  try {
    let user = datos.nombre + datos.idAlumno.toString();
    callback("oracleAlumno");
   corregirProcedimiento(user,datos.solucion,sql);
  } catch (err) {
    console.error('init() error: ' + err.message);
  } 
}
async function corregirProcedimiento(user,solucion,scripts){//sql tiene la cracion de las tablas, el porcedimiento y los scripts
    let connection;
    console.log("scripts:"+scripts);
    console.log("user:"+user);
    console.log("solucion:"+solucion);
    try {
      connection = await oracledb.getConnection({
          user: "'" + user + "'",
          password: "'" + user + "'",
          connectString: 'localhost',
        },
        async function(err, connection) {
          if (err)
            console.error("conection :"+err);
          else{
            almacenarProcedimineto(user,solucion,scripts,connection);
            await connection.close();
          }
      });      
    } catch (err) {
      console.error("run :"+err);
    } finally {
      if (connection) {
        try {
          // Put the connection back in the pool
          await onnection.close();
        } catch (err) {
          console.error(" finally run :"+err);
        }
      }
    }
}

function almacenarProcedimineto(user,solucion,sql,connection){
  console.log("Hola, estas dentro de almacenar Procedimiento");
}
module.exports = {
  connect:connect
 
}`
```
### oracleProfesor.js :
```
 oracledb = require('oracledb');
//var async = require('async');
var dbConfig = require('./dbconfig.js');
var fs = require("fs");
oracledb.autoCommit= true;

function connect(sql,datos,callback){
  try {
    
    if(datos.usuario == 'alumno'){
      let user = datos.nombre + datos.idAlumno.toString();
      console.log(user);
      callback("Hola");
      altaUsuario(user);//sql son los scripts de prueba
    }/*else{
      await run(sql,(resultado) =>{
        //console.log("connect)");
        callback(resultado);
      });//la funcion que le pasamos(oracle.run)
    }*/
  } catch (err) {
    console.error('init() error: ' + err.message);
  }
}
async function run(sql,callback){//sql tiene la cracion de las tablas, el porcedimiento y los scripts
  let connection;
    try {
      /*connection = await oracledb.getConnection();
      await createTables(connection,sql[0]);
      await createProcedure(connection,sql[1]);*/
      connection = await oracledb.getConnection(
        {
          user: 'alberto',
          password: 'alberto',
          connectString: 'localhost',
          privilege: oracledb.SYSDBA
        },
        async function(err, connection) {
          if (err)
            console.error("conection :"+err);
          else{
            await createTables(connection,sql[0]);
            await createProcedure(connection,sql[1]);
            await callProcedures(connection,sql,(sol)=>{
              callback(sol);
            });
          }
        }
      );      
    } catch (err) {
      console.error("run :"+err);
    } finally {
      if (connection) {
        try {
          // Put the connection back in the pool
          await connection.close();
        } catch (err) {
          console.error(" finally run :"+err);
        }
      }
    }
}
async function createTables(connection,sql) {
  sql = sql.replace(/\r|\n|\t|#|COMMIT;|/g, '');
  sql=sql.split(";");
  var i, aux;

  for( i=0; i<sql.length-1;i++){
    aux = sql[i];
    if(aux.indexOf("drop") > -1){
      aux=  "BEGIN EXECUTE IMMEDIATE '"+sql[i]+"'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-00942) THEN RAISE; END IF; END;";
    }
    //console.log(aux);
    //else if(aux.indexOf("insert") > -1 || aux.indexOf("INSERT") > -1){
    await connection.execute(aux);
  }
}
async function createProcedure(connection,sql){
  //var sq = sql.replace(/\r|\n|\t|#|COMMIT;|/g, '');
  //console.log(sql);
  try {
    // Put the connection back in the pool
    await connection.execute(sql);
  } catch (err) {
    console.error("createProcedure : "+err);
  }
}
async function callProcedures(connection, sql,callback){
  let resultado =[];
  let sq;
  for(let i = 2; i < sql.length; i++){
    //console.log(sql[i].toString());
    sq = sql[i].toString();
    await connection.execute(sq);
    resultado[i-2] = fs.readFileSync('C:/tmp/resultado.log');
    //console.log(resultado[i-2].toString());
  }
  callback(resultado);
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

async function altaUsuario(user){
   
  let connection;
  try {
    /*connection = await oracledb.getConnection();
    await createTables(connection,sql[0]);
    await createProcedure(connection,sql[1]);*/
    connection = await oracledb.getConnection(
      {
        user: 'SYS',
        password: 'SYS',
        connectString: 'localhost',
        privilege: oracledb.SYSDBA
      },
      async function(err, connection) {
        if (err)
          console.error("conection :"+err);
        else{
          var sql = "begin ALTA_USUARIO('"+user+"'); end;";
          await connection.execute(sql);
          await connection.close();
        }
    });  
  } catch (err) {
    console.error("altaUsuario :"+err);
  } finally {
    if (connection) {
      try {
        // Put the connection back in the pool
        await connection.close();
      } catch (err) {
        console.error("altaUsuario connection close"+err);
      }
    }
  }
}
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


/*async function closePoolAndExit() {
  console.log('\nTerminating');
  try {
    // get the pool from the pool cache and close it when no
    // connections are in use, or force it closed after 10 seconds
    let pool = oracledb.getPool();
    await pool.close(10);
    console.log('Pool closed');
    //process.exit(0);
  } catch(err) {
    // Ignore getPool() error, which may occur if multiple signals
    // sent and the pool has already been removed from the cache.
    process.exit(0);
  }
}*/
 /*CREATE OR REPLACE PROCEDURE ALTA_USUARIO(user_id VARCHAR2) AS
  BEGIN
    EXECUTE IMMEDIATE 'DROP USER '||user_id||' CASCADE';
    EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-01918) THEN RAISE; END IF;
    EXECUTE IMMEDIATE 'CREATE USER '||user_id||' IDENTIFIED BY '||user_id;
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT CONNECT TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT debug any procedure, debug connect session TO '||user_id;
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON sys.write_log TO '||user_id;
  END;
  ;*/
/*process
  .on('SIGTERM', closePoolAndExit)
  .on('SIGINT',  closePoolAndExit)*/

module.exports = {
  connect:connect,
  run:run
}
```

**Comment by anthony-tuininga** [comment]
If you use SYS to create a user, you can then establish a new connection with the newly created user. You could continue working with the new user's tables, procedures, etc. using the SYS connection as well. It depends on what you want to do. There is a lot of code above. It would be helpful if you could summarise or explain further what your difficulty is.

**Comment by dmcghan** [comment]
@martaRodri I agree with @anthony-tuininga, we need more information. You supplied an example of what you're trying to do. Is it not working? Are you getting any errors?

I see a problem with your calls to `getConnection`:

```javascript
    connection = await oracledb.getConnection(
      {
        user: 'SYS',
        password: 'SYS',
        connectString: 'localhost',
        privilege: oracledb.SYSDBA
      },
      async function(err, connection) {
        if (err)
          console.error("conection :"+err);
        else{
          var sql = "begin ALTA_USUARIO('"+user+"'); end;";
          await connection.execute(sql);
          await connection.close();
        }
    });  
```

Note that you are awaiting the result of the call to `oracledb.getConnection` but you're also passing a callback function. This will not run as expected and could lead to hard to track down bugs. That should be written like this:

```javascript
    connection = await oracledb.getConnection({
      user: 'SYS',
      password: 'SYS',
      connectString: 'localhost',
      privilege: oracledb.SYSDBA
    }); 
    
    var sql = "begin ALTA_USUARIO('"+user+"'); end;";
    await connection.execute(sql);
```

You don't need the `close` call because that's already in the `finally` block. 

Also, you should avoid one-off connections and use connection pools instead. The driver supports heterogeneous connection pools which allows you to reuse connections as different users. This may help for what you're trying to do: https://oracle.github.io/node-oracledb/doc/api.html#connpoolproxy

**Comment by albertoMarquez** [comment]
Thank you, I changed the code, but I still have the same problem as before:
Connection pool started
conection :Error: ORA-01017: invalid username/password; logon denied

And this new problem:
Error: ORA-28009: connection as SYS should be as SYSDBA or SYSOPER

Now I´m using the use connection pools:
```
async function altaUsuario(user){
   
  let connection;
  try {
    // Create a connection pool which will later be accessed via the
    // pool cache as the 'default' pool.
    await oracledb.createPool({
      user: dbConfig.user,
      password: dbConfig.password,
      connectString: dbConfig.connectString
      // edition: 'ORA$BASE', // used for Edition Based Redefintion
      // events: false, // whether to handle Oracle Database FAN and RLB events or support CQN
      // externalAuth: false, // whether connections should be established using External Authentication
      // homogeneous: true, // all connections in the pool have the same credentials
      // poolAlias: 'default', // set an alias to allow access to the pool via a name.
      // poolIncrement: 1, // only grow the pool by one connection at a time
      // poolMax: 4, // maximum size of the pool. Increase UV_THREADPOOL_SIZE if you increase poolMax
      // poolMin: 0, // start with no connections; let the pool shrink completely
      // poolPingInterval: 60, // check aliveness of connection if idle in the pool for 60 seconds
      // poolTimeout: 60, // terminate connections that are idle in the pool for 60 seconds
      // queueTimeout: 60000, // terminate getConnection() calls in the queue longer than 60000 milliseconds
      // sessionCallback: myFunction, // function invoked for brand new connections or by a connection tag mismatch
      // stmtCacheSize: 30 // number of statements that are cached in the statement cache of each connection
    });
    console.log('Connection pool started');
    connection = await oracledb.getConnection();
    var sql = "begin ALTA_USUARIO('"+user+"'); end;";
    let result = await connection.execute(sql);
    console.log(result);
  } catch (err) {
    console.error("altaUsuario :"+err);
  } finally {
    await closePoolAndExit();
  }
}
```

**Comment by dmcghan** [comment]
Generally speaking, you should only be connecting as SYS for database maintenance. Why are you trying to connect as SYS from Node.js?

I see another problem in the code here:

```
var sql = "begin ALTA_USUARIO('"+user+"'); end;";
```

You're using string concatenation with what I assume could be a value from a user. This could lead to a SQL injection vulnerability. Even if `user` isn't directly from an end user, string concatenation can still lead to performance issues. Use bind variables instead: https://oracle.github.io/node-oracledb/doc/api.html#bind

**Comment by martaRodri** [comment]
Thanks for the security recommendation against the SQL injection, however I need to use SYS privileges  to create students.
How can I create a pool with SYSDBA privileges?

I'm going to explain better what I want to do because I don't know if my way is the easiest one or not.

I create student by taking an existing one from another DB, the procedure ALTA_USUARIO is stored in my oracle database with SYS privileges. Moreover creates the user, also gives the following privilege on this procedure `EXECUTE IMMEDIATE 'GRANT EXECUTE ON sys.write_log TO '|| user_id;`
This makes the students that I create before can use the procedure write_log .

```
create or replace PROCEDURE write_log (nombreFic VARCHAR2) AS
    l_line VARCHAR2 (255);
    l_done NUMBER;
    l_file utl_file.file_type;
BEGIN
    l_file: = utl_file.fopen ('TMP', nombreFic, 'W');
    LOOP
        EXIT WHEN l_done = 1;
       dbms_output.get_line (l_line, l_done);
       utl_file.put_line (l_file, l_line);
    END LOOP;
    utl_file.fflush (l_file);
    utl_file.fclose (l_file);
END write_log;

```

**Comment by dmcghan** [comment]
It looks like you're creating custom code in the SYS schema. You should not be doing this. Do you know why ALTA_USUARIO or WRITE_LOG are defined in the SYS schema?

**Comment by martaRodri** [comment]
ALTA_USUARIO is not accessible by students and we want to store WRITE_LOG in SYS schema.
But anyway, is it possible to create a pool as SYSDBA?

**Comment by martaRodri** [comment]
ALTA_USUARIO is not accessible by students and we want to store WRITE_LOG in SYS schema.
But anyway, is it possible to create a pool as SYSDBA?

```
await oracledb.createPool({
      user: dbConfig.user,
      password: dbConfig.password,
      connectString: dbConfig.connectString
    });
```
    oracledb.SYSDBA = 2;
   ```
 console.log('Connection pool started');
    connection = await oracledb.getConnection();
    connection.execute(
      `begin ALTA_USUARIO(:u); END;`,
      {
        u:  user
      },
      function (err, result) {
        if (err) { console.error(err.message); return; }
        console.log(result.outBinds);
    });
```

**Comment by dmcghan** [comment]
Why do you think you want to create WRITE_LOG in the SYS schema? Can you give me any real reason for this?

**Comment by dmcghan** [comment]
See this for more information on why you shouldn't be doing this: https://geraldonit.com/2017/08/28/why-you-should-never-put-objects-into-the-system-or-sysaux-tablespace/

**Comment by martaRodri** [comment]
Because we need to do this first `ALTER SYSTEM SET "_system_trig_enabled" = FALSE scope=both;` and store WRITE_LOG each time a student execute a procedure. At the end we want to create a user, execute some procedures (as student with a few privileges) and delete the student. To execute procedures as a student its necessary to execute write_log as SYS.

**Comment by dmcghan** [comment]
Thanks. I'm going to keep digging here to better understand your situation...

1. Why do you need to call this: `ALTER SYSTEM SET "_system_trig_enabled" = FALSE scope=both;`?
2. What does creating a user involve? Is it an insert into one or more tables? Is it creating a database user? Or something else?
3. What do you mean by, "To execute procedures as a student its necessary to execute write_log as SYS?"

**Comment by martaRodri** [comment]
thanks for your help, 
1. we need to call `alter system...` because we want to save log into a file, this is the functionallity of WRITE_LOG.
2. the idea is: 1 create a user, as that user, create tables and execute some procedures, save log and then delete the user.
3. WRITE_LOG is a procedure that is storage in SYS so, to save logs into a file as student user we have to execute it like this: sys.write_log("log.txt")

**Comment by dmcghan** [comment]
1. What does the `alter system` call have to do with WRITE_LOG? In other words, what would happen if you just invoked WRITE_LOG without the `alter system`?
2. To be clear, you're saying you need to do the following (where does ALTA_USUARIO fit into the sequence?):
   * Create a database user (which represents a student)
   * Within the new database user's schema, create some tables
   * Call some procedures owned by SYS
   * Call SYS.WRITE_LOG
   * Drop the database user
3. Yes, because WRITE_LOG is owned by SYS and not the student user (and there's no public synonym for WRITE_LOG) then you need to qualify the name of the procedure with its owner. However,  I still don't understand why the owner would be SYS and not something like MY_APP.

**Comment by martaRodri** [comment]
1 we have to use `alter system` because is a Windows OS without it doesn't work.
2. yes, this is exactly what we want to do, and ALTA_USUARIO is a store procedure that teacher (is the same as SYS because have the same privileges) runs to create users (students in this case). the sequence is the following one:

         1.  teacher creates a connection as SYS.
         2.  teacher execute ALTA_USUARIO to create a new user.
         3.  the new user creates tables and call procedures creates by himself
         4.  Save logs using WRITE_LOG.
         5.  Drop the database user.

We though storing WRITE_LOG inside SYS session it would be easier to execute, but anyway this is not the problem.
Is it possible to execute that 5 steps using oracledb and a connection pool, if not, how we can do it?

The code that we provide do that, but when we execute 

```
function connect(sql,datos,callback){
  try {
    let user = datos.nombre + datos.idAlumno.toString();
   corregirProcedimiento(user,datos.solucion,sql);
  } catch (err) {
    console.error('init() error: ' + err.message);
  } 
}
```

//user is the new student created by teacher
//scripts are procedures student has to execute
//solucion are scripts to create tables

```
async function corregirProcedimiento(user,solucion,scripts){
    let connection;
    console.log("scripts:"+scripts);
    console.log("user:"+user);
    console.log("solucion:"+solucion);
    try {
      connection = await oracledb.getConnection({
          user: "'" + user + "'",
          password: "'" + user + "'",
          connectString: 'localhost',
        },
        async function(err, connection) {
          if (err)
            console.error("conection :"+err);
          else{
            almacenarProcedimineto(user,solucion,scripts,connection);
            await connection.close();
          }
      });      
    } catch (err) {
      console.error("run :"+err);
    } finally {
      if (connection) {
        try {
          // Put the connection back in the pool
          await onnection.close();
        } catch (err) {
          console.error(" finally run :"+err);
        }
      }
    }
}
```
In corregirProcedimiento Oracle said that couldn't logging.

**Comment by dmcghan** [comment]
> we have to use alter system because is a Windows OS without it doesn't work.

What doesn't work? If you don't call `alter system`, when do you get an error and what is the error?

> Is it possible to execute that 5 steps using oracledb and a connection pool, if not, how we can do it?

I'm confident we can do what you need, but I still need a better understanding... It seems like this sequence of steps is all done at once, as a single unit of work done by the teacher, right? It's not like a teacher does something, then a student does something, and then the teacher again.

> In corregirProcedimiento Oracle said that couldn't logging.

What does this mean? Did you get an error? If so, which one?

***

Looking at your code, in your `connect` function, you are calling `corregirProcedimiento` but you're not awaiting the result. This means your try/catch block can't catch any async errors.

Additionally, in your `corregirProcedimiento` function, you're passing a callback to `getConnection` and you're awaiting the result - you should be doing one or the other. Finally, I think you want to await the result of `almacenarProcedimineto`, but you're not. It should probably look like this:

```javascript
async function corregirProcedimiento(user,solucion,scripts){
    let connection;
    console.log("scripts:"+scripts);
    console.log("user:"+user);
    console.log("solucion:"+solucion);
    try {
      connection = await oracledb.getConnection({
          user: "'" + user + "'",
          password: "'" + user + "'",
          connectString: 'localhost',
        });
        
      await almacenarProcedimineto(user,solucion,scripts,connection);
      // do not close here, that will happen in the finally block
    } catch (err) {
      console.error("run :"+err);
    } finally {
      if (connection) {
        try {
          // Put the connection back in the pool
          await connection.close();
        } catch (err) {
          console.error(" finally run :"+err);
        }
      }
    }
}
```

**Comment by martaRodri** [comment]
Hello,
Is not an error, if we don't use it, WRITE_LOG doesn't work.

> I'm confident we can do what you need, but I still need a better understanding... It seems like this sequence of steps is all done at once, as a single unit of work done by the teacher, right? It's not like a teacher does something, then a student does something, and then the teacher again.

No, teacher does something (ALTA_USUARIO, witch creates students) and then, our idea is students log in and execute "corregirProcedimiento".

```

async function corregirProcedimiento(user,solucion,scripts, conection, callback){
    console.log("scripts:"+scripts);
    console.log("user:"+user);
    console.log("solucion:"+solucion);

    try {
      conection = await oracledb.getConnection({
          user: "'" + user + "'",
          password: "'" + user + "'",
          connectString: 'localhost',
        },
        async function(err, conection) {
          if (err)
            console.error("conection :"+err);
          else{
            await almacenarProcedimineto(user,solucion,scripts,conection);
          }
      });      
    } catch (err) {
      console.error("run :"+err);
    } finally {
      if (conection) {
        try {
          // Put the connection back in the pool
          await conection.close();
        } catch (err) {
          console.error(" finally run :"+err);
        }
      }
    }
}
```

The result of execute it is: 
Error: ORA-01017: invalid username/password; logon denied

**Comment by dmcghan** [comment]
> Is not an error, if we don't use it, WRITE_LOG doesn't work.

What does "doesn't work" mean? You call the procedure, it completes successfully, but the file isn't modified? I find this hard to believe...

> No, teacher does something (ALTA_USUARIO, witch creates students) and then, our idea is students log in and execute "corregirProcedimiento".

Okay... Why are you creating database users for the students? I'm just curious about what functionality this is providing. As an alternative, you could just have a single MY_APP schema with a set of tables that are shared by all teachers and students. That would allow you to just do DML and not a lot of tricky DDL at run time. Is that not possible for some reason?

> The result of execute it is: Error: ORA-01017: invalid username/password; logon denied

Please stop writing calls to `oracledb.getConnection` with both `await` and callbacks. If you need a better understanding of the difference, see my series here: https://jsao.io/2017/06/how-to-get-use-and-close-a-db-connection-using-various-async-patterns/

As to the error your getting, why are you quoting the username and password as you are? Try this:

```javascript
async function corregirProcedimiento(user,solucion,scripts){
    let connection;
    console.log("scripts:"+scripts);
    console.log("user:"+user);
    console.log("solucion:"+solucion);
    try {
      connection = await oracledb.getConnection({
          user: user,
          password: user,
          connectString: 'localhost',
        });
        
      await almacenarProcedimineto(user,solucion,scripts,connection);
      // do not close here, that will happen in the finally block
    } catch (err) {
      console.error("run :"+err);
    } finally {
      if (connection) {
        try {
          // Put the connection back in the pool
          await connection.close();
        } catch (err) {
          console.error(" finally run :"+err);
        }
      }
    }
}
```

**Comment by albertoMarquez** [comment]
Thank you, we change this and other things and now It's working. 

We really apreciate your help.
