### ISSUE TITLE
Proposition - Node 12 support

### ISSUE THREAD

**Issue by sosoba** [oracle/node-oracledb#1085]
It's time for Node 12.

**Comment by danilohgds** [comment]
Node 12 is not in LTS until October 22nd, there are dozen of features and other things that would be just as beneficial if not more. 

I'd say let's wait until Node12 has matured a bit, and yes I am excited about the performance changes that it has promised.

**Comment by anthony-tuininga** [comment]
The work with N-API referenced in issue #1053 will work with Node.js 12 without any changes. Take a look there if you are eager!

**Comment by cjbj** [comment]
I (currently) have no plans to release node-oracledb 3 binaries for Node 12. Convince me otherwise. Early adopters can build the module binary easily enough, and/or build the [dev-4.0](https://github.com/oracle/node-oracledb/tree/dev-4.0) branch.

**Comment by cjbj** [comment]
Heh, a new NAN would be needed for v3.

**Comment by sosoba** [comment]
> 
> 
> I (currently) have no plans to release node-oracledb 3 binaries for Node 12. Convince me otherwise. 

Node 12 has one amazing feature. Error stacktrace containing the trace of asynchronous calls.

**Comment by cjbj** [comment]
Now would be a good time for you to build the amazing-and-will-be-more-amazing node-oracledb 4 dev code and give us some feedback.

**Comment by riyadshauk** [comment]
What about support for ECMAScript Modules so we can `import` this library?

**Comment by dmcghan** [comment]
@riyadshauk See this: https://github.com/oracle/node-oracledb/issues/501#issuecomment-267460619

**Comment by dmcghan** [comment]
@riyadshauk I just ran a test and I was able to get it working. Here are the steps:

1. In your module, use this:
   ```js
   import oracledb from 'oracledb';
   ```
2. Make sure your module file has the extension `.mjs`.
3. Run your module with the `experimental-modules` flag:
   ```js
   node --experimental-modules main.mjs
   ```

**Comment by cjbj** [comment]
Perhaps this should be documented... if someone submits a PR :)
