### ISSUE TITLE
undfined result

### ISSUE THREAD

**Issue by eunier14** [oracle/node-oracledb#1086]
I trying to run a query but I get an undefined result back. This is the code of file named 'oracledb.js' :
```
function runQuery(callback) {
  const dotevn = require('dotenv');
  const oracledb = require('oracledb');
  const log = require('../util/consoleLogger');

  dotevn.config({
    path: './.env'
  });

  const user = process.env.DB_TEST_USER;
  const pw = process.env.DB_TEST_PASS;
  const connectString = process.env.DB_CONNECT_STRING;

  let result = oracledb.getConnection(
    {
      user: user,
      password: pw,
      connectString: connectString
    },
    function(err, connection) {
      if (err) {
        log('error', `'getConnection error:\n\t ${err.message}`);
        return;
      } else {
        log('success', 'getConnection success');
      }

      connection.execute(
        `select * from table_test`,
        [],
        function(err, result) {
          if (err) {
            log('error', `execute error:\n\t${err.message}`);

            connection.close(function(err) {
              if (err) {
                log('error', `'doRelease error: ${err.message}`);
              }
            });

            return;
          } else {
            log('success', 'execute success');
            log('success', `result: \n${result.rows}`);
          }

          connection.close(function(err) {
            if (err) {
              log('error', `'doRelease error: ${err.message}`);
            }
          });

          return result;
        }
      );
    }
  );

  callback(result);
}

module.exports = runQuery;
```

This is how I call the above code:
```
const runQuery = require('./oracledb');

runQuery(function(result) {
    console.log(result);
});
```

The problem is that I can see on the console data from the database printed but when calling `runQuery` and try to `console.log(result)` in the above code I'm getting `undefined`. I'm sure this has to do with the async nature of node.js that I may not handling properly.

Thanks.

    What is your Node.js version: use console.log(process.version)? Is it 64-bit or 32-bit: use console.log(process.arch)?
    x64
    undefined

    What is your node-oracledb version: use console.log(oracledb.versionString)?
    3.1.2

    What error(s) you are seeing?
    undefined

    What OS (and version) is Node.js executing on: use console.log(process.platform)?
    win32

    What is your Oracle client (e.g. Instant Client) version: use console.log(oracledb.oracleClientVersionString)? Is it 64-bit or 32-bit? How was it installed? Where is it installed?
    18.3.0.0.0

    What is your Oracle Database version: use console.log(connection.oracleServerVersionString)?
    11.2.0.4.0

    What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On macOS, what is in ~/lib?
    C:\oracle\instantclient_18_3

**Comment by dmcghan** [comment]
@eunier14 At the end of your `runQuery` function, you have `return result;`. Change that to `callback(result)`.

Also, learn about other async patterns and try to move to async/await: https://jsao.io/2017/06/how-to-get-use-and-close-a-db-connection-using-various-async-patterns/

**Comment by eunier14** [comment]
Thanks @dmcghan ! I will definitively give that a read. I appreciate your help!
