### ISSUE TITLE
Segmentation fault (core dumped) on pool.getConnection()

### ISSUE THREAD

**Issue by git-di-marko** [oracle/node-oracledb#1087]
Hi!
During the stability test of my application i faced some troubles with getConnection from the pool. Details: i run my app in docker container then i kill all the sessions in Oracle associated with my oracledb pool, and try to send the request again. As a result i see "Segmentation fault (core dumped)". I tried to run the test on another OS Ubuntu, without docker and i faced the same problem.

Error in getOraConnection(ii) function, on pool.getConnection...
I tried to simplify the code also, but main reason is Error on pool.getConnection
after i killed the sessions in Oracle.

**My Env:**
Node version: v10.15.3
process.arch: x64
oracledb version: 3.1.2
Platform: 
  Virtualization: vmware
  Operating System: Ubuntu 16.04.6 LTS
  Kernel: Linux 4.4.0-143-generic
  Architecture: x86-64

ORA client: 12.1.0.2.0
ORA server: 12.1.0.2.0

[Code example:](https://gist.github.com/git-di-marko/d984afdd082786f7663ac3d19fd6232d)

**Comment by dmcghan** [comment]
@git-di-marko There seems to be some confusion around promises and async functions. For example, in `createOraGlobalPool`, you are combining promise chains and `await`. While this could be useful at times, I don't think this is one of them. Here's how that function probably should be written:

```javascript
async function createOraGlobalPool() {
  let localError;
  try {
    console.log('Creating ORA connection pool...');

    if (pool) {
      await pool.close(5);
    }

    pool = await oracledb.createPool(DB_ORA_INI.connectionAttr);

    console.log('ORA connection pool created.');

    pool._logStats();

    return pool; // I'm not sure why this is needed, we have a pool cache
  } catch(err) {
    console.log('ORA connection pool creation failed: ' + err);

    throw err; // This will be swallowed up as a rejection automatically
  }
}
```

The same goes for the `getOraConnection` function, you don't need to resolve or reject explicitly, it's done for you implicitly. 

What is the point of `getOraConnection`? It reads like: try to get a connection from the pool up to 4 times. If you can't get a connection then return an error. But what error are you anticipating on `pool.getConnection()` that caused you to write this?

Also, I see you're not actually testing the connection with a call to `connection.ping()`, was that intentional?

Have you seen the [Connection Pool Pinging](https://oracle.github.io/node-oracledb/doc/api.html#-1246-connection-pool-pinging) section of the doc? There is some built-in logic that should be doing this for you, but it doesn't work when you kill the sessions. Note this part:

> When node-oracledb is using the Oracle client library version 12.2 or later, then a lightweight connection check always occurs in the client library. While this check prevents some unusable connections from being returned by getConnection(), it does not identify errors such as session termination from the database resource manager or user resource profile IDLE_TIME, or from an ALTER SYSTEM KILL SESSION command. The explicit ping initiated by poolPingInterval will detect these problems.

**Comment by git-di-marko** [comment]
Dear @dmcghan,

Thank you for your very detailed comment! 

Yes I read about  Connection Pool Pinging. 
"The explicit ping initiated by poolPingInterval will detect these problems." - means to me that if i set poolPingInterval = 0 then i get  an explicit ping for every connection to be able to soleve the problem with killed session.

I tested a variety of connection modes and different types of connection checking with oracledb module. I tried single connection with manual ping and some reconnect logic, i also tested connection pool with manual connection pinging. 
Single connection mode works fine for me, with all that mix of async and promises. Only performance was not so brilliant. Manual reconnect logic works fine too :) 

But I've decided to have some extra power and tried connection pooling. In the documentation we can read about some stuff like auto ping every connection before it will be returned by getConnection method. But it doesn't matter, how it's made, with manual connection check or with auto check. The main reason is the pool usage and just calls to getCOnnection method. 

I've tried to leave only several instruction in connection logic (e.g. only pool.getConnection() ) and if all sessions is killed than we see Segmentation fault immediately :( Just with one instruction "on board" -  pool.getConnection()

**Comment by git-di-marko** [comment]
And some words about several attempts to connect to ORA with extra attempt of new pool creation :)

What if there is some troll in the sessions in ORACLE, e.g. while my app is trying to process about 1000-2000 rps with a little help of bulky internal oracle procedure? :) 
Many requests is queued already and i can't safely reboot an instance with pm2 for example.
I think will be better to try all i can to reconnect to ORA and to finish all the queued requests befor soft reboot of the app instance

**Comment by git-di-marko** [comment]
i did the code "castration" :) again.

async function getOraConnection() {
          console.log('Connecting to ORA...');
	  return await pool.getConnection();
}
i killed all ORA sessions in the pool and ...
and the first call to getOraConnection() crashes all app with Segmentation fault error...
:( 
I also tries to comment string with poolPingInterval = 0. The same result...

**Comment by cjbj** [comment]
> killed all ORA sessions in the pool

What does this mean?  What commands were run and where (DB or client)?

Please 
- tell us your goals and scaling requirements.
- tell us what you are trying to prove by this particular scenario of 'killing' sessions.
- fill in the [issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) you skipped so we know the OS and DB versions (and don't have to read your code to find the node & client versions...)

Thanks!

**Comment by git-di-marko** [comment]
Dear @cjbj ,

It's good question (about "killing" mechanics)! I use custom procedure from our DBA. I am going to figure out this, soon.

1) My goal is to be able to process requests with 1000-2000 rps, when some of them is very bulky inside the Oracle (5-11 secs). I've got another issue about this case :)
2) Sessions are suddenly gone sometimes. I have to understand the app behavior in this case
3) Ok, @cjbj, i used to work with my own local git and i am new to the online github. I'll try to fill all necessary information.

**Comment by cjbj** [comment]
Clean up your Node code.

Make sure you know how to increase the node-oracledb connection pool size and UV_THREADPOOL_SIZE (check the doc).

Review other architectures e.g. Advanced Queueing (which we don't have quite yet) to see if a notification mechanism is better than waiting for complex statements to complete.

Review potential scale-out mechanisms, e.g. multiple containers, to spread the mid-tier load.

**Comment by git-di-marko** [comment]
@cjbj, of course, i think about different architectures, especially about using microservice style with noSQL db and queues (e.g. Mongo/Redis). But anyway some worker threads will be send some load to the Oracle DB and i have to know how to work with this and what its limits and its behavior. KILLING MECHANICS details:

create or replace noneditionable procedure sys.kill_session
 (pn_sid    number
 ,pn_serial number)
as
 lv_user varchar2(30);
begin
 select username into lv_user from v$session where sid = pn_sid and serial# = pn_serial;
 if lv_user is not null and lv_user not in ('SYS','SYSTEM') then
  execute immediate 'alter system kill session '''||pn_sid||','||pn_serial||'''';
 else
  raise_application_error(-20000,'Attempt to kill protected system session has been blocked.');
 end if;
end;

**Comment by git-di-marko** [comment]
No "segmentation fault" error, after fully synthetic test has been finished. There is no extra logic at all, and only strict style when using async/await and Promises. 
I'll try to figure out what exactly is the main cause of the error above, simplifying the original app code as i can.

**Comment by git-di-marko** [comment]
Dear @dmcghan, @cjbj,
Thank you very much for your recommendations.
Now, i can say, that using async/await strictly and without Promise chains at the "same place" - its a good practice :) I didn't know that it could be so important thing. **Now it's ok**
