### ISSUE TITLE
Error: NJS-045: cannot load a node-oracledb binary for Node.js 12.0.0 (win32 x64) 

### ISSUE THREAD

**Issue by victorgianvechio** [oracle/node-oracledb#1091]
I am developing an academic project with electron and oracle. My dbConnection.js file connects to the database and returns a success or error message.

When I run 'node dbConnection.js' the success message appears.

When I try to call the connection method in the electron application I get the following error: Error: NJS-045: Can not load a node-oracledb binary for Node.js 12.0.0 (win32 x64).

Windows 10 x64
Node v10.15.3
Oracle 11G
Phyton 3.7.3
VC Redist 2005/2013/2015/2019 (all these versions installed)

Any ideas how to solve the problem?

**Comment by cjbj** [comment]
Since you're on Windows, my recommendation is to use Node 10 or 11.  The alternative is to compile the module yourself.  It's likely only the 4.0-dev version will compile, see https://github.com/oracle/node-oracledb/issues/1085

**Comment by cjbj** [comment]
If the message says you're using Node.js 12, then you're using Node.js 12.

**Comment by max-pub** [comment]
When will you offer a pre-compiled binary for node 12?

**Comment by victorgianvechio** [comment]
I Solved the problem using

```
"dependencies": {
        "oracledb": "github:oracle/node-oracledb#v3.1.2",
        "electron-rebuild": "^1.8.5",
 }
```

after installing the dependencies run `./node_modules/.bin/electron-rebuild`

**Comment by cjbj** [comment]
@max-pub precompile binaries will be available when node-oracledb 4 is released and 12 has bedded down a bit. Please help speed up the node-oracledb release process by testing v4, see https://github.com/oracle/node-oracledb/issues/1053 

@victorgianvechio that's great.

**Comment by tonydiep** [comment]
I'm experiencing this on a Windows and Linux machine
```
Uncaught Error: NJS-045: cannot load a node-oracledb binary for Node.js 12.0.0
```
I've double-checked and Node.js 12.0.0 is **NOT** installed on the Windows machine or Linux machine.
```
[tonydiep@tdlap15 vehicle-lookup]$  node --version
v10.16.0
```
I've tried rebuilding from source with electron-rebuild. Same results. 

It's as if some dependency is specifying Node.js 12.0.0

**Comment by cjbj** [comment]
@tonydiep If NJS-045 is saying you have Node 12, then that is what your Node is identifying itself as.  I know Electron is 'special'.  I'm surprised electron-rebuild isn't helping.  Here is what I'd suggest: (i) trying the dev-4.0 branch, see #1053. There is even a binary available (ii) installing Node 12 and compiling.

**Comment by victorgianvechio** [comment]
@tonydiep try deleting the node_modules folder and package-lock.json, then install the dependencies again and run the rebuild.

I have a simple [app](https://github.com/victorgianvechio/connection-generator) with oracle-db and electron.

**Comment by cjbj** [comment]
@victorgianvechio thanks for sharing the tip and the app.

Have you tried it with the dev-4.0 code? 
```

--- package.json.old	2019-07-16 10:16:16.000000000 +1000
+++ package.json	2019-07-16 10:16:48.000000000 +1000
@@ -21,7 +21,7 @@
     "dependencies": {
         "electron-progressbar": "^1.2.0",
         "jquery": "^3.4.1",
-        "oracledb": "github:oracle/node-oracledb#v3.1.2"
+        "oracledb": "github:oracle/node-oracledb#dev-4.0"
     },
     "devDependencies": {
         "babel-eslint": "^10.0.1",

```

**Comment by tonydiep** [comment]
@victorgianvechio Thanks for advice. Unfortunately I still get the same error after deleting node_modules and reinstalling fresh dependencies and dev-4.0.

**Comment by cjbj** [comment]
@tonydiep do some debugging and see what exactly is being loaded by what.

**Comment by victorgianvechio** [comment]
@cjbj i tried it now and worked without using electron-rebuild, great!!! see [package.json](https://github.com/victorgianvechio/connection-generator/commit/3cc7ce4b7256dba0c56d7c61faf6f6b3d724cce1)

@tonydiep have you deleted package-lock.json before running npm install? 

iam using

> $ node -v
> v10.15.3

> $ npm -v
> 6.4.1

I updated my [app](https://github.com/victorgianvechio/connection-generator) with node-oracledb#dev-4.0, test and see if the error still continues. Electron version 5.0.1

After clone just run:

```
npm i 
npm start
```

**Comment by victorgianvechio** [comment]
@tonydiep be sure if you have  node-gyp installed globally
´´´
npm i -G node-gyp
´´´
iam using node-gyp@4.0.0

> $ npm list -g --depth 0
> +-- node-gyp@4.0.0

**Comment by ceyhunkerti** [comment]
in 
`node_modules/oracledb/lib/oracledb.js`

locate the line with
```js
oracledbCLib = require(binaryLocations[i]);
```

and replace it with

```
oracledbCLib = require('../build/Release/oracledb-4.0.1-linux-x64.node')
```
`oracledb-4.0.1-linux-x64.node` this may be different according to your platform and `oracledb`
module version so check 
`node_modules/oracledb/build/Release` folder first

**Comment by Raks25** [comment]
> I am developing an academic project with electron and oracle. My dbConnection.js file connects to the database and returns a success or error message.
> 
> When I run 'node dbConnection.js' the success message appears.
> 
> When I try to call the connection method in the electron application I get the following error: Error: NJS-045: Can not load a node-oracledb binary for Node.js 12.0.0 (win32 x64).
> 
> Windows 10 x64
> Node v10.15.3
> Oracle 11G
> Phyton 3.7.3
> VC Redist 2005/2013/2015/2019 (all these versions installed)
> 
> Any ideas how to solve the problem?

**Comment by cjbj** [comment]
@Raks25 this is a closed issue.  Search for previous questions on Electron and look at things like [electron-rebuild](https://github.com/oracle/node-oracledb/issues/1141#issuecomment-523011669).  If you still have problems, please open a new issue.

**Comment by ywang67** [comment]
Try to use ES module, change the file .js to .mjs, and using require instead of import. It works for me, I think node-oracledb is ESM now.

**Comment by pramod9254** [comment]
thanks @cjbj. It worked for me. 👍
