### ISSUE TITLE
Building node-oracledb 3.1 (from source) for Node.js 12 fails to compile

### ISSUE THREAD

**Issue by aprknight** [oracle/node-oracledb#1092]
I have followed these instructions with great care https://oracle.github.io/node-oracledb/INSTALL.html

1. node v12.1.0
2. gcc v5.5.0
3. npm v6.9.0
4. python v2.7.16
5. npm install oracle/node-oracledb#v3.1.2
6. This leads to a compiler error as follows:-
>>>>>>>>>>>>>>>>>>>>>>>>>>>
CXX(target) Release/obj.target/oracledb/src/njsOracle.o
../src/njsOracle.cpp: In static member function 'static void njsOracledb::Init(v8::Local<v8::Object>)':
../src/njsOracle.cpp:194:31: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
             temp->GetFunction());
                               ^
In file included from /home/oracle/.node-gyp/12.1.0/include/node/node.h:63:0,
                 from ../src/njsOracle.cpp:51:
>>>>>>>>>>>>>>>>>>>>>>>>>>>

I have no idea what I might have done wrong so any help would be appreciated

**Comment by cjbj** [comment]
There's a patch from @anthony-tuininga now pushed to the master branch that allows it (node-oracledb 3.1) to compile with Node.js 12.
