### ISSUE TITLE
It would really help if pre-build binaries for Node.js 12.2 would be available

### ISSUE THREAD

**Issue by doberkofler** [oracle/node-oracledb#1094]
Currently when installaing on 12.2 the pre-built node-oracledb binary cannot not found: `oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for Node.js v12.2.0 (NODE_MODULE_VERSION=72) on win32 x64`.

**Comment by cjbj** [comment]
node-oracledb 3.1 also doesn't compile with Node.js 12, see #1085 and  #1092.

If someone wants to dig in and submit a PR to us or NAN, I'd appreciate it.  Otherwise we'll keep working on node-oracledb 4.0-dev, which does compile with Node.js 12, and make sure we have binaries by the time Node 12 goes LTS.

**Comment by doberkofler** [comment]
Thank you!

**Comment by cjbj** [comment]
I just pushed a commit from @anthony-tuininga to the master branch that allows it (node-oracledb 3.1) to compile with Node.js 12.  You may still prefer to use the dev-4.0 branch though.  The patch hasn't had full testing.

**Comment by bruce-solar** [comment]
is there a plan for testing and releasing the patch from @anthony-tuininga as a prebuilt binary?

is the intention for dev-4.0 to be backward compatible? any place i can go to find the dev-4.0 api changes?

**Comment by anthony-tuininga** [comment]
You can go [here](https://github.com/oracle/node-oracledb/blob/dev-4.0/doc/api.md) for the development branch documentation. The intent is for 4.0 to be backwards compatible as much as possible. There are a few changes that will work differently with 4.0 -- but these are out-of-the-ordinary and unlikely-to-be-used scenarios, we think. Take a look at the [change log](https://github.com/oracle/node-oracledb/blob/dev-4.0/CHANGELOG.md) and let us know if anything there looks troublesome. Thanks!

**Comment by cjbj** [comment]
@bruce-solar if you want to build the 4.0-dev code, see https://github.com/oracle/node-oracledb/issues/1053

**Comment by bruce-solar** [comment]
Thanks for the quick response. The links were helpful. And N-API is definitely good news.
