### ISSUE TITLE
NJS-011 encountered bind value and type mismatch

### ISSUE THREAD

**Issue by michel5element** [oracle/node-oracledb#1096]
Hello everyone,

I am running a kafka consumer service which sends .JSON messages which I then parse and write to my Oracle database. 

Most of the time it works fine, but sometimes get the following error `NJS-011 encountered bind value and type mismatch`. The string is inserted into a `oracledb.STRING, maxSize: 4000` defined column and when looking at the data and catching the messages that could not be inserted, size of the insert is not the issue. 

In summary I would like to write ALL my  JSON parsed strings into the Oracle database without the NJS-011 errors and missing data in my Oracle tables.

#### My system info:

1. What is your Node.js version: `v10.15.3`

2. What is your node-oracledb version: `3.1.2`

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  
Logged in as admin, running the command `let result = await connection.executeMany(sql, binds, options);`

4. What error(s) you are seeing?
`NJS-011 encountered bind value and type mismatch`

5. What OS (and version) is Node.js executing on: `win32`, windows server 2016, version 1607, (OS build 14393.0)

6. What is your Oracle client (e.g. Instant Client) version: `18.3.0.0.0`
Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
Built in client inside the oracledb node package, installed with npm

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
`C:\Program Files (x86)\Common Files\Oracle\Java\javapath`
`C:\oracle\WINDOWS.X64_180000_db_home\bin`
`C:\Program Files\nodejs\`

**Comment by cjbj** [comment]
We need a runnable example.  And the SQL to create the tables etc.
