### ISSUE TITLE
OracleDB 3.1.4 Install issues on Mac Mojave 10.14.4

### ISSUE THREAD

**Issue by kliebhart** [oracle/node-oracledb#1097]
### For general questions:

When trying to install oracledb using `npm install oracledb` it fails on my Mac Mojave. 

#### Answer the following questions:

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?
Darwin 18.5.0
node v12.1.0
npm  v6.9.0

` gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?
`3.1.2`

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`as an active directory user, permitted to install programms`

4. What error(s) you are seeing?

` npm install --verbose oracledb
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/12.1.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'oracledb'
npm verb cli ]
npm info using npm@6.9.0
npm info using node@v12.1.0
npm verb npm-session 3cd90f56df36463c
npm http fetch GET 200 https://registry.npmjs.org/oracledb 12ms (from cache)
npm timing stage:loadCurrentTree Completed in 55ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6ms
npm timing stage:loadIdealTree Completed in 9ms
npm timing stage:generateActionsToTake Completed in 3ms
npm verb correctMkdir /Users/k.liebhart/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/k.liebhart/.npm/_locks/staging-5efdd6e3fa20f4fa.lock for /private/var/oracle/node_modules/.staging
npm timing action:extract Completed in 118ms
npm timing action:finalize Completed in 4ms
npm timing action:refresh-package-json Completed in 10ms
npm info lifecycle oracledb@3.1.2~preinstall: oracledb@3.1.2
npm timing action:preinstall Completed in 1ms
npm info linkStuff oracledb@3.1.2
npm timing action:build Completed in 1ms
npm info lifecycle oracledb@3.1.2~install: oracledb@3.1.2

> oracledb@3.1.2 install /private/var/oracle/node_modules/oracledb
> node package/install.js

oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for Node.js v12.1.0 (NODE_MODULE_VERSION=72) on darwin x64
oracledb ERR! Try compiling node-oracledb source code using https://oracle.github.io/node-oracledb/INSTALL.html#github
npm verb lifecycle oracledb@3.1.2~install: unsafe-perm in lifecycle true
npm verb lifecycle oracledb@3.1.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/private/var/oracle/node_modules/oracledb/node_modules/.bin:/private/var/oracle/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
npm verb lifecycle oracledb@3.1.2~install: CWD: /private/var/oracle/node_modules/oracledb
npm info lifecycle oracledb@3.1.2~install: Failed to exec install script
npm timing action:install Completed in 69ms
npm verb unlock done using /Users/k.liebhart/.npm/_locks/staging-5efdd6e3fa20f4fa.lock for /private/var/oracle/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 14ms
npm timing stage:runTopLevelLifecycles Completed in 321ms
npm WARN oracle No description
npm WARN oracle No repository field.
npm WARN oracle No license field.

npm verb stack Error: oracledb@3.1.2 install: `node package/install.js`
npm verb stack Exit status 87
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:196:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:196:13)
npm verb stack     at maybeClose (internal/child_process.js:1000:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
npm verb pkgid oracledb@3.1.2
npm verb cwd /private/var/oracle
npm verb Darwin 18.5.0
npm verb argv "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/bin/npm" "install" "--verbose" "oracledb"
npm verb node v12.1.0
npm verb npm  v6.9.0
npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@3.1.2 install: `node package/install.js`
npm ERR! Exit status 87
npm ERR! 
npm ERR! Failed at the oracledb@3.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 87, true ]
npm timing audit submit Completed in 1143ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1144ms
npm timing audit body Completed in 1ms
npm timing npm Completed in 1436ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/k.liebhart/.npm/_logs/2019-05-16T20_27_53_915Z-debug.log`

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?
`Mac Mojave 10.14.4`

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
`Oracle Insta Client 18.1 / 64bit installed according Oracle instructions`

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
`$ ls -la ~/lib
total 280904
drwxr-xr-x   6 k.liebhart  staff        192 16 May 21:44 .
drwxr-xr-x+ 36 k.liebhart  staff       1152 16 May 16:38 ..
lrwxr-xr-x   1 k.liebhart  staff         34 16 May 16:17 libclntsh.dylib -> instantclient_18_1/libclntsh.dylib
lrwxr-xr-x   1 k.liebhart  staff         39 16 May 16:18 libclntsh.dylib.18.1 -> instantclient_18_1/libclntsh.dylib.18.1
-r-xr-xr-x@  1 k.liebhart  staff    8554544 16 May 21:44 libnnz18.dylib
-rwxr-xr-x@  1 k.liebhart  staff  126944172 16 May 21:46 libociei.dylib`

9. What Oracle environment variables did you set?  How *exactly* did you set them?
`nothing`

10. Do you have a small, single Node.js script that immediately runs to show us the problem?
`no`

**Comment by cjbj** [comment]
Thanks for the detail.  See https://github.com/oracle/node-oracledb/issues/1094
