### ISSUE TITLE
problem with queue

### ISSUE THREAD

**Issue by DOVER123** [oracle/node-oracledb#1101]
I have a problem with this moudle. I use ajax in font-end post something to nodejs server,it's works at the begining,but when i wait for a little time,then reflash webpage,it will wait a long time to get de result ,and some requests don't work anymore.
this is my code
server
    
    var http = require('http');
    var oracledb = require("oracledb");
    var fs = require("fs");
    var readline = require("readline");
    var path = require('path')
    var querystring = require('querystring')
    var pool = {};
    var initPool = async function (test_pool) {
        try {
            await oracledb.createPool({
                _enableStats: true,
                user: "",
                password: '',  // mypw contains the hr schema password
                connectString: "",
                poolAlias: 'test1_sgs'
            });
        } catch (err) {
            console.log(err);
        }
        pool['test1_sgs'] = true;
    }
    var executeSql = async function (dataSource, sql) {
        var pool_flag = pool[dataSource];
        if (!pool_flag) {
            console.log('error:' + dataSource + "!");
        }

        var pool_name = oracledb.getPool(dataSource);
        try {

            var connection = await pool_name.getConnection();
            let result = await connection.execute(sql);
            await connection.close();
            return Promise.resolve(result);
        } catch (err) {
            await connection.close();
            console.log(err.message)
        }

    };

    (async () => {
        var i = 1;
        await initPool();
        var server = http.createServer((req, res) => {
            console.log(i++);
            if (req.url === "/getfpdJson") {
                res.setHeader('Access-Control-Allow-Origin', 'null');

                var params = '';
                req.setEncoding('utf8');
               
                req.on('data', function (chunk) {
                    params += chunk;
                });
                req.on('end', () => {
                    params = decodeURIComponent(unescape(params));
                    var { sql, dataSource } = JSON.parse(params);
                    (async () => {
                        try {
                            var a = await executeSql(dataSource, sql);
                            var dataReturn = { flag: 1, data: a.metaData }
                            res.end(JSON.stringify(dataReturn));
                        } catch (err) {
                            res.end(JSON.stringify({ flag: 0, data: err.message }));
                        }
                    })();
                })

            } else if (req.url === "/getlog") {
                oracledb.getPool('test1_sgs')._logStats();
                res.end();
            }
        })
        await server.listen(8124)
    })();

this is my ajax

        var getfpdJson = function (sql, dataSource) {
        var params = {'sql':sql,'dataSource':dataSource};
        params = escape(encodeURIComponent(JSON.stringify(params)));
        $.ajax({
            'url': 'http://127.0.0.1:8124/getfpdJson',
            'method': 'POST',
            'data': params,
            'async':true,
            'dataType':"json",
            'success': function (data) {
                if(data.flag == 1){
                    console.log(data.data);
                }else{
                    alert(data.err);
                }
            }, error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert('error：' + XMLHttpRequest.status + '/' + XMLHttpRequest.readyState + "/" + textStatus)
            }
        });
    }
    for(var i=0;i<40;i++){
        console.log(1);
        getfpdJson("select '1' from dual",'test1_sgs'); 
    }
` 
this is log
Pool statistics:
...total up time (milliseconds): 108651
...total connection requests: 3200
...total requests enqueued: 732
...total requests dequeued: 732
...total requests failed: 0
...total request timeouts: 0
...max queue length: 2
...sum of time in queue (milliseconds): 1497
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 115
...avg time in queue (milliseconds): 2
...pool connections in use: 0
...pool connections open: 4
Related pool attributes:
...poolAlias: test1_sgs
...queueTimeout (milliseconds): 60000
...poolMin: 0
...poolMax: 4
...poolIncrement: 1
...poolTimeout (seconds): 60
...poolPingInterval: 60
...sessionCallback: undefined
...stmtCacheSize: 30
Pool status:
...status: 6000
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: undefined

is my code wrong ? what shoud i do ,thank you.

**Comment by dmcghan** [comment]
This looks like another one of those "SQL injection as a service" programs. You're allowing clients (the browser in this case) to send arbitrary SQL that you then execute in the database. This is potentially very dangerous. Is it intentional?

> but when i wait for a little time,then reflash webpage

If you refresh the webpage then the HTTP request is essentially lost - you don't have access to it in the new page context. So if you refresh the page, then you'll never get the response from the previous call. Whether you see the update from the initial request is just a matter of timing (did the Ajax call finish prior to the page refresh).

Also, if you want to handle this situation programmatically, there should be an `aborted` event that's triggered on the `request` object when something like a page refresh happens during an Ajax request.

> it will wait a long time to get de result ,and some requests don't work anymore.

What does this mean? Do you get errors? If so, which ones? If not, what is the behavior?

Finally, see this series for tips on setting up a REST API: https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/

**Comment by DOVER123** [comment]
@dmcghan thank you for answer.I have already get the results from server at the first 30 ajax posts，its very fast . Then，if i wait for two or three minutes，refresh the page to make other new 30 ajax posts，it will wait for a long time to get the  
result（only 3or4 of the 30posts），and some connections return the error message like“time out”.  if i use sync ajax  it dont have this problem. so i think my pool config has some problems， maybe poolmax:4 a little smile?

**Comment by cjbj** [comment]
@DOVER123 regarding the poolsize, read https://oracle.github.io/node-oracledb/doc/api.html#numberofthreads and https://oracle.github.io/node-oracledb/doc/api.html#connpooling

**Comment by dmcghan** [comment]
@DOVER123 You didn't answer my question about SQL injection. Do you understand the risk associated with the code you have?

> I have already get the results from server at the first 30 ajax posts，its very fast

You haven't shown us the code you're clients are executing. When you say you execute 30 Ajax posts, what kind of SQL statements are being executed?

> if i use sync ajax it dont have this problem.

Node.js doesn't care if you use Ajax or not. To it, an HTTP request is an HTTP request. But tell us more about this. If you're not using Ajax, what are you using? Do you mean when you toggle the `'async':true` flag?

Are you firing off these Ajax requests in some kind of loop?

> error message like“time out”

Please be more specific. What is the _exact_ error message you're seeing? Note that the details you showed us about your queue indicate that the problem isn't timeouts occurring while waiting for a connection, so they must be coming from somewhere else.

**Comment by DOVER123** [comment]
@dmcghan my english is not good . we dont have a problem with sql injection its not for public web . 

the sql "select 1 from dual" just to test wether i can use the moudle to get a result from Oracle 。

my all code is this.

<html>
<head>
....
</head>
<body>
<script>
    var getfpdJson = function (sql, dataSource) {
    var params = {'sql':sql,'dataSource':dataSource};
    params = escape(encodeURIComponent(JSON.stringify(params)));
    $.ajax({
        'url': 'http://127.0.0.1:8124/getfpdJson',
        'method': 'POST',
        'data': params,
        'async':true,
        'dataType':"json",
        'success': function (data) {
            if(data.flag == 1){
                console.log(data.data);
            }else{
                alert(data.err);
            }
        }, error: function (XMLHttpRequest, textStatus, errorThrown) {
            alert('error：' + XMLHttpRequest.status + '/' + XMLHttpRequest.readyState + "/" + textStatus)
        }
    });
}
for(var i=0;i<40;i++){
    console.log(1);
    getfpdJson("select '1' from dual",'test1_sgs'); 
}
</body>
</script>
</html>

yes i mean async:false.

its dont have a erorr message，but the client just wait for the answer for a long time and get {},when i start my server code ,and first time open html ,the right result is like name:[1],rows[1]。

**Comment by dmcghan** [comment]
@DOVER123 

> we dont have a problem with sql injection its not for public web .

Okay, thanks.

I just ran a test of your code. I found it worked fine for me. Even after waiting a few minutes, I was able to refresh the page and all of the requests finished without issues.

If you're getting errors, we need to know exactly which ones. It's possible that the database is set up to kill idle connections. What happens if you just keep refreshing the page without the long gaps?

**Comment by DOVER123** [comment]
@dmcghan if i just keep refreshing the page without the long gaps, it works fine,i can get the right results ervery time.
i will check what you said about database kill idle connections .
thankyou for answer.

**Comment by cjbj** [comment]
@DOVER123 please answer the [issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) questions that you skipped - there may be different behaviors with different versions of the various layers comprising node-oracledb.  Give us information to make it easy for us to help you.

**Comment by DOVER123** [comment]
@dmcghan I set oracledb.poolTimeout = '3600' or other long time,then i can get all the result , i think it's just like you said  ;

> It's possible that the database is set up to kill idle connections.

**Comment by cjbj** [comment]
Did you mean poolTimeout or queueTimeout?

**Comment by DOVER123** [comment]
@cjbj pooltimeout ，i try to set pooltimeout ，and it works well now.

**Comment by cjbj** [comment]
That's strange.
