### ISSUE TITLE
Super-Low Prio: Fix typo in documentation

### ISSUE THREAD

**Issue by area1211** [oracle/node-oracledb#1103]
Take a look at [https://oracle.github.io/node-oracledb/doc/api.html#-4261-executemany-sql-statement](url)

You define the number of section to be 4.2.7.1 instead of 4.2.6.1.

**Comment by cjbj** [comment]
Thanks. Every improvement helps.  I'll update the doc on the dev-4.0 branch with a fix.

**Comment by cjbj** [comment]
This was fixed last week.  Thanks!
