### ISSUE TITLE
multiple oracledb.getconnection() issue

### ISSUE THREAD

**Issue by haripriya12345mhp** [oracle/node-oracledb#1105]

**Comment by dmcghan** [comment]
@haripriya12345mhp 

> The issue is i want combine both the files as a single file with 3 oracle db queries producing 2 different outputs.

Why are you trying to combine all of your code files? I would recommend moving in the other direction. You need to organize your project better, which will require more files, not less.

Have a look at this series on creating a REST API:
https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/

Once you've separated database and controller logic, you can have a controller that uses one or more database APIs to generate and return a result.
