### ISSUE TITLE
createPool,can't get error message

### ISSUE THREAD

**Issue by DOVER123** [oracle/node-oracledb#1106]
i create a pool like this。

    var oracledb = require('oracledb');
      
    async function run() {
      let connection;
      try {
        oracledb.createPool({
          _enableStats: true,
          user: '',
          password: '',  // mypw contains the hr schema password
          connectString: '',
          poolAlias: 'J1'
      });
      } catch (err) {
        console.log(err.message);
      } 
    }
    
    run();

and i give it a wrong password ,why it con't console  a error message?
instantclient_11_2  and node-oracle 3.0.1

**Comment by cjbj** [comment]
Don't forget to use `await oracledb.createPool()`.  This is a common problem - it hit me today too.

**Comment by DOVER123** [comment]
@cjbj oh yes,i my trying to adapt await....thank you very match.

**Comment by DOVER123** [comment]
@cjbj no it still dont have the error message,
    var oracledb = require('oracledb');

    async function run() {
      let connection;
      try {
        await oracledb.createPool({
          _enableStats: true,
          user: '',
          password: '',  // mypw contains the hr schema password
          connectString: '',
          poolAlias: 'J1'
      });
      } catch (err) {
        console.error(err);
      } 
    }

    run();

**Comment by cjbj** [comment]
Try either (i) setting `poolMin` > 0 so that a connection is established when the pool is created (ii) or getting a connection from the pool (which will cause a connection to be created - and which will fail if the pw is wrong).

**Comment by DOVER123** [comment]
@cjbj ok，it works .thank you very much sir.
