### ISSUE TITLE
ARCGIS Versioning 'invalid SQL statement'

### ISSUE THREAD

**Issue by als9xd** [oracle/node-oracledb#1107]
1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?

node:10.15.1

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?

^3.1.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?

```Unhandled rejection Error: ORA-00900: invalid SQL statement```

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?

debian 9

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

instantclient-basic-linux.x64-18.3.0.0.0

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?

12.1.0.2.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Node.js script that immediately runs to show us the problem?

### Doesn't work
```javascript
  const db = knex({
    client: 'oracledb',
    debug: true,
    connection: {
      user,
      password,
      connectString: "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=" + host + ")(PORT=" + port + "))(CONNECT_DATA=(SID = " + sid + ")))"
    },
    pool: { 
      afterCreate: (conn:any, done:Function) => { 
        conn.execute('execute VECTORS.version_util.set_current_version(:tableName)',{
          tableName: 'VECTORS.Test'
        },(err:Error) => {
          done(err,conn);
        });
      } 
    },
    // @ts-ignore
    fetchAsString: ['clob']
  });

  db('STATES').first()
  .then((data:any) => (console.log(data)));
```
### Works 
```javascript
  const db = knex({
    client: 'oracledb',
    debug: true,
    connection: {
      user,
      password,
      connectString: "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=" + host + ")(PORT=" + port + "))(CONNECT_DATA=(SID = " + sid + ")))"
    },
    pool: { 
      afterCreate: (conn:any, done:Function) => { 
        conn.execute('SELECT * FROM COLUMN_REGISTRY WHERE ROWNUM = 1',(err:Error) => {
          done(err,conn);
        });
      } 
    },
    // @ts-ignore
    fetchAsString: ['clob']
  });

  db('STATES').first()
  .then((data:any) => (console.log(data)));
```

### Also Works

From within Oracle SQL developer

```sql
execute vectors.version_util.set_current_version('VECTORS.Test');
SELECT * FROM STATES WHERE rownum = 1;
```
This is the versioning system I am using:

http://desktop.arcgis.com/en/arcmap/10.3/manage-data/using-sql-with-gdbs/read-oracle-versioned-data-using-sql.htm

**Comment by cjbj** [comment]
Are you hitting https://github.com/oracle/node-oracledb/issues/147 ?

If you rephrase your question using node-oracledb calls (instead of Knex) and referring to the actual Oracle datatypes I could give a more confident answer.

**Comment by als9xd** [comment]
I'm not getting any data type errors.

```javascript
createPool({
    user,
    password,
    connectString: "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=" + host + ")(PORT=" + port + "))(CONNECT_DATA=(SID = " + sid + ")))"  
  })
  .then((pool) => pool.getConnection())
  .then(async (conn) => {
    try {
      await conn.execute('execute VECTORS.version_util.set_current_version(:tableName)',{
        tableName: 'VECTORS.Test'
      });
    } catch(err){
      console.error('Could not set version:\n',err);
      throw err;
    }
    return conn; 
  })
  .then(async (conn) => {
    try {
      await conn.execute('SELECT * FROM STATES WHERE ROWNUM = 1')
    } catch(err) {
      console.error('Could not get states:\n',err);
      throw err;
    }
    return conn;  
  });
```

**Error:**

```Could not set version { [Error: ORA-00900: invalid SQL statement] errorNum: 900, offset: 0 }```

**Comment by anthony-tuininga** [comment]
Set the environment variable DPI_DEBUG_LEVEL to the value 16. That will tell you the SQL that is being executed.

**Comment by als9xd** [comment]
That gives

```ODPI [00056] 2019-05-28 22:18:48.017: SQL execute VECTORS.version_util.set_current_version(:tableName)```

**Comment by cjbj** [comment]
`EXECUTE` is a SQL*Plus command.  Try the SQL `CALL` command or use `BEGIN . . . END`

**Comment by als9xd** [comment]
Ah. That fixed it thanks.
