### ISSUE TITLE
Is it mandatory to have the version oracle client 64-bit installed

### ISSUE THREAD

**Issue by maikosantos** [oracle/node-oracledb#1110]
Is it mandatory to have the version oracle cliente 64-bit installed?

**Comment by dmcghan** [comment]
Are you running 64-bit or 32-bit Node.js? It needs to match... What bit is your OS?

**Comment by maikosantos** [comment]
My OS and node are 64bits. However, o oracle cliente is 32. I need 32 to run apps vb6!

**Comment by dmcghan** [comment]
Well, you could run 32-bit Node.js (but I wouldn't do that). Alternatively, you could use both the 32-bit and 64-bit Instant Client libraries on the same machine. For this, you could probably leave the 32-bit install as is for VB6 and then just download the 64-bit zip for Node.js. Unzip the files and point `PATH` to the correct location. See the [install docs on Windows](https://oracle.github.io/node-oracledb/INSTALL.html#364-install-the-free-oracle-instant-client-zip) for more details.

**Comment by maikosantos** [comment]
Ohhh my friend! Very good!
It's worked perfect! 
Thank you so much!
