### ISSUE TITLE
dpi.h missing

### ISSUE THREAD

**Issue by max-pub** [oracle/node-oracledb#1111]
Hi,
I'm trying to build oracledb 4.0dev with node12 on windows.
Keep getting the following errors:
Any ideas?

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsCommon.cpp
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsCommon.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsConnection.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsOracle.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsPool.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]
  njsResultSet.cpp
  njsSubscription.cpp
  njsMessages.cpp
  njsIntLob.cpp
  njsSodaDatabase.cpp
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsSubscription.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]
  njsSodaDocument.cpp
  njsSodaOperation.cpp
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsSodaDatabase.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]
  njsSodaDocCursor.cpp
XXX\node_modules\oracledb\src\njscommon.h(65): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dpi.h": No such file or
directory (Quelldatei wird kompiliert ..\src\njsUtils.cpp) [XXX\node_modules\oracledb\build\oracledb.vcxproj]

**Comment by max-pub** [comment]
it's the same for 3.x and 4.x

**Comment by anthony-tuininga** [comment]
Can you show how you are trying to do the build? If you are building from a GitHub clone, then you'll need to make sure you run these commands after cloning node-oracledb:

**Comment by cjbj** [comment]
See https://oracle.github.io/node-oracledb/INSTALL.html#githubclone

**Comment by cjbj** [comment]
Closing - I presume this is fix.

**Comment by max-pub** [comment]
OK, thanks, I went with downgrading node to 10.x to be able to use the binaries...

**Comment by cjbj** [comment]
@max-pub if you're keen, you can try the node-oracledb 4.0-dev drop.  There is a binary for Windows that will work with Node.js 12.  See https://github.com/oracle/node-oracledb/releases/tag/v4.0.0-dev-20190623 for how to install.
