### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by max-pub** [oracle/node-oracledb#1113]
Hello,
I'm getting the following error:

      Segmentation fault (core dumped)

for result-set-lengths over about 500 rows.
I set the LD_LIBRARY_PATH as suggested in one of the issues here but to no avail.

Any ideas?

**Comment by anthony-tuininga** [comment]
Please fill in the issue template so we know more about what is going on in your situation! The reference to LD_LIBRARY_PATH suggests you are using Linux but there are other platforms out there that use that variable as well. We definitely need Oracle Client library version, Oracle Database version, platform, Node.js version. And it would also be helpful to provide the code that you are using! One frequent issue is the lack of an "await" in front of an asynchronous operation.

**Comment by max-pub** [comment]
ubuntu 18.04
node 10.16
instantclient 19.3
oracle 11.2

using "await" as in:
      return (await this.connection.execute('SELECT ...', {a:1}  )).rows

does that help in problem-solving?

**Comment by anthony-tuininga** [comment]
It helps a little. You're still missing the node-oracledb version. It would be even more helpful if you can try retrieving from something that I will have as well -- like ``all_tab_columns``. On my database that contains 24,186 rows. Please provide the complete script that you use. Thanks!

**Comment by max-pub** [comment]
It seems to have sth to do with ROWIDs... 
When I remove them from my Select-Statement I can query "any" amount of rows...
Any ideas why that is?

(node-oracledb 3.1.2)

**Comment by cjbj** [comment]
Try https://github.com/oracle/python-cx_Oracle/issues/315#issuecomment-498710438
and let us know.

**Comment by max-pub** [comment]
yes, applying "rowidtochar()" to the rowid solves the problem!
thanks!

**Comment by cjbj** [comment]
What a pain.  This bug is on my hotlist of things I would like fixed; we'll continue to hassle the responsible group.

**Comment by anthony-tuininga** [comment]
> yes, applying "rowidtochar()" to the rowid solves the problem!

You can also set the environment variable ``ORA_OCI_NO_OPTIMIZED_FETCH`` which should have the same effect without having to change your query.
