### ISSUE TITLE
'Ask us anything' Office Hours is July 2, 2019 21:00 - 21:30 UTC 

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#1116]
Our next ask-us-anything 'Office Hours' is  July 2, 2019 21:00 - 21:30 UTC 

Hop on the webcast at https://devgym.oracle.com/pls/apex/dg/office_hours/727

@dmcghan what have you got planned this month?

**Comment by dmcghan** [comment]
Today's session will provide a high-level intro to GraphQL and then demonstrate an implementation based on Node.js (node-oracledb and Join Monster) and Oracle Database. 😎
