### ISSUE TITLE
connection oracle mode and php

### ISSUE THREAD

**Issue by DarkNeku** [oracle/node-oracledb#1120]
Hello, my English is not very good ...
in my new work they use a database of oracle 9i and they asked me to connect through node.js, by doing it by cmd I managed to break the connection, but when I deploy it in my php project I get the following load. page 'Uncaught ReferenceError: require is not defined' and in the console the error marks it in "var oracledb = require ('oracledb');"
I need your help!!!!!!

**Comment by cjbj** [comment]
@DarkNeku This is a node-oracledb forum.  You don't use 'require' in PHP code.  Please give more detail about what you are trying to do.

The node-oracledb installation instructions are here: https://oracle.github.io/node-oracledb/INSTALL.html

The node-oracledb user documentation is https://oracle.github.io/node-oracledb/doc/api.html

From the node-oracled installation documentation you can see that you need node-oracledb linked with Oracle 11.2 (or later) client libraries.  The 11.2 libraries  should be able to connect to Oracle Database 9.2 or later.

**Comment by DarkNeku** [comment]
The connection is in a file called server.js where the "var oracledb = require ('oracledb');", I call it from a php page using the function "<script src =" server.js "> </ script> "and when loading this php page in the browser, I throw the error in the line var oracledb = require ('oracledb'); 'Uncaught ReferenceError: require is not defined'

**Comment by cjbj** [comment]
Node.js is a "mid-tier" application programming environment, like PHP.  You don't include in your HTML pages.  It can generate HTML pages.  Do some reading on Node.js.  If you then have specific node-oracledb questions, come and ask us.  We'd be glad to help.

I'll close this issue.

**Comment by DarkNeku** [comment]
friend, so I understood the connection I'm trying to make is not valid since php and node are not compatible?

**Comment by cjbj** [comment]
Your usage is wrong.  Read some documentation and try some examples.
