### ISSUE TITLE
"[Error: NJS-011: encountered bind value and type mismatch]" with executeMany and insert

### ISSUE THREAD

**Issue by markddrake** [oracle/node-oracledb#1122]
1. What is your Node.js version:

version: v11.9.0
arch: x64

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?
oracledb: 3.1.2

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
system/oracle [dba]

4. What error(s) you are seeing?
[Error: NJS-011: encountered bind value and type mismatch]

5. What OS (and version) is Node.js executing on:

platform win32

6. What is your Oracle client (e.g. Instant Client) version: 
client 12.2.0.1.0
64 Bit
C:\Program Files\Oracle\InstantClient\12.2

7. What is your Oracle Database version: use `console.log(connection.oracleServerVersionString)`?
server 19.0.0.0.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Mark D Drake\AppData\Local\Microsoft\WindowsApps;C:\Users\Mark D Drake\AppData\Local\GitHubDesktop\bin;C:\Program Files\Python;C:\Users\Mark D Drake\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Oracle\InstantClient\12.2\bin;C:\Program Files\MySQL\MySQL Workbench 8.0 CE;C:\Program Files\PostgreSQL\11\bin;C:\Program Files\Ruby25-x64\bin;C:\Users\Mark D Drake\AppData\Roaming\npm;

9. What Oracle environment variables did you set?  How *exactly* did you set them?

-None-

10. Do you have a small, single Node.js script that immediately runs to show us the problem?
```Javascript
"use strict"
const oracledb = require('oracledb');

async function main() {

  const connectionDetails = {
    user          : "system",
    password      : "oracle",
    connectString : "ORCL19C"
  };
    
  const SCHEMA = "TEST"  
  const PASSWORD = 'oracle';
    
  const DROP_USER = `DROP USER ${SCHEMA} CASCADE`;
  const CREATE_USER = `GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO ${SCHEMA} identified by ${PASSWORD}`

  const DDL = `declare
  TABLE_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( TABLE_EXISTS , -00955 );
  V_STATEMENT CLOB := 'create table "TEST"."test" (
 "ColdRoomTemperatureID" NUMBER(19,0)
,"ColdRoomSensorNumber" NUMBER(10,0)
,"RecordedWhen" TIMESTAMP(7)
,"Temperature" NUMBER(10,2)
,"ValidFrom" TIMESTAMP(7)
,"ValidTo" TIMESTAMP(7)
)
';
begin
  execute immediate V_STATEMENT;
exception
  when TABLE_EXISTS then
    null;
  when others then
    RAISE;
end;`
  
  const BINDS = [{"type":2002},{"type":2002},{"type":2001,"maxSize":33},{"type":2002},{"type":2001,"maxSize":33},{"type":2001,"maxSize":33}]
  
  const DML = `insert into "TEST"."test" ("ColdRoomTemperatureID","ColdRoomSensorNumber","RecordedWhen","Temperature","ValidFrom","ValidTo") values (:1,:2,:3,:4,:5,:6)`
  
  const DATA = [
    ["3654737",1,"2016-05-31T23:59:24Z",3.72,"2016-05-31T23:59:24Z","9999-12-31T23:59:59.9999999Z"],
    ["3654738",2,"2016-05-31T23:59:24Z",4.7,"2016-05-31T23:59:24Z","9999-12-31T23:59:59.9999999Z"],
    ["3654739",3,"2016-05-31T23:59:24Z",3,"2016-05-31T23:59:24Z","9999-12-31T23:59:59.9999999Z"],
    ["3654740",4,"2016-05-31T23:59:24Z",3.58,"2016-05-31T23:59:24Z","9999-12-31T23:59:59.9999999Z"]
  ]
 
  let results;
  let conn;  
  let i;

 
  console.log('version:',process.version)     
  console.log('arch:',process.arch)
  console.log('oracledb:',oracledb.versionString)
  
  try {
      
    conn = await oracledb.getConnection(connectionDetails);
    
    try {
      results = await conn.execute(DROP_USER);    
      console.log('DROP_USER',results)
    } catch (e) {
      console.log(e);
    }

    results = await conn.execute(CREATE_USER);
    console.log('CREATE_USER',results)
    results = await conn.execute(DDL);
    console.log('DDL',results)
    results = await conn.executeMany(DML,DATA,{bindDefs : BINDS});
    console.log('DML',results)
  } 
    catch (e) {
    console.log(e);
  }
}

main();

```

Results in

```
C:\Development\YADAMU>node wip\oracle\genericTest.js
version: v11.9.0
arch: x64
oracledb: 3.1.2
DROP_USER { rowsAffected: 0 }
CREATE_USER { rowsAffected: 0 }
DDL {}
[Error: NJS-011: encountered bind value and type mismatch]

C:\Development\YADAMU>
```

**Comment by markddrake** [comment]
FYI I I use a loop to insert each row, using the same insert but avoiding executeMany() there is no problem, other than performance when processing 1,000,000's of documents

**Comment by cjbj** [comment]
It will fail with the same error with `execute()` if you specify the bind types:

```
  BIND = [
    {val: "3654737", type: oracledb.NUMBER},  // give NJS-011 since val is a string
    {val:1, type: oracledb.NUMBER},
    {val:"2016-05-31T23:59:24Z", type:oracledb.STRING},
    {val: 3.72, type: oracledb.NUMBER},
    {val:"2016-05-31T23:59:24Z", type:oracledb.STRING},
    {val:"9999-12-31T23:59:59.9999999Z", type:oracledb.STRING}
  ];

 results = await conn.execute(DML, BIND);
```

This is because "3654737" is a string but you have said you are giving a NUMBER.

So the first stage is to remove the quotes from the first bind values (or change the type to `oracledb.STRING` and let the DB do the conversion)

But then the sample data produces `ORA-01843: not a valid month`. This also happens in SQL*Plus:

```
SQL> insert into test ("ColdRoomTemperatureID","ColdRoomSensorNumber","RecordedWhen","Temperature","ValidFrom","ValidTo") 
values (3654737, 1, '2016-05-31T23:59:24Z', 3.72, '2016-05-31T23:59:24Z', '9999-12-31T23:59:59.9999999Z');

  2  values (3654737, 1, '2016-05-31T23:59:24Z', 3.72, '2016-05-31T23:59:24Z', '9999-12-31T23:59:59.9999999Z')
                    *
ERROR at line 2:
ORA-01843: not a valid month
```

I'll leave that with you to look at.

BTW: the type numbers have changed in Node-oracledb 4.0, so make sure to use the `oracledb.XXX` constants in production, see https://github.com/oracle/node-oracledb/blob/dev-4.0/doc/api.md#migratev31v40

**Comment by markddrake** [comment]
Thanks Chris.. That was it.. Didn't notice that node MsSQL was generating strings for BIGINT.. (I had set my environment to deal with the Date Format issue).  And yes, the real code does using your constants..

**Comment by markddrake** [comment]
performance for  3,654,736 rows in row/row mode 539 rows, per second, 
performance with executeMany() and batches of 10K rows, 30578 rows per second.

**Comment by cjbj** [comment]
@markddrake just a bit faster then :)
