### ISSUE TITLE
Runnings sql scripts with set statements

### ISSUE THREAD

**Issue by ShubhamVohra** [oracle/node-oracledb#1124]
I have a query.sql file that I am fetching using node's fs module but it is giving the error of invalid and missing option.

The query.sql file looks something like below

> set echo off
   set abc on
   select * from table
   set echo on

**Comment by cjbj** [comment]
This was already answered at https://stackoverflow.com/questions/57170014/importing-sql-script-and-running-it-using-node-oracledb

**Comment by ShubhamVohra** [comment]
But that didn't answer my question. I have to run the script using oracledb module. Where I need the Java JDK to be installed.

**Comment by cjbj** [comment]
Since the discussion is already on Stackoverflow, let's continue the discussion on that topic there.

You don't need to install a JDK.  There is no Java in node-oracledb.  Installation instructions for node-oracledb are https://oracle.github.io/node-oracledb/INSTALL.html.

**Comment by ShubhamVohra** [comment]
@cjbj I am not connecting to local db. Could you please elaborate on the same as what I need to do. Since, you are not replying on stackoverflow, so asking the same here
