### ISSUE TITLE
Failed to install node-oracledb on windows 10 32bit

### ISSUE THREAD

**Issue by sam17896** [oracle/node-oracledb#1133]
1. With the async/await programming style, make sure you are using 'await' in the right places.

2. Is it an error or a hang or a crash? **error**

3. What error(s) you are seeing?
**a pre-built node-oracledb binary was not found for win32 ia32**.

4. Include a runnable Node.js script that shows the problem.
Include all SQL needed to create the database schema.
**npm i --save oracledb**

5. Run node and show the output of:

```
> process.platform
'win32'
> process.version
'v12.7.0'
> process.arch
'ia32'
require('oracledb').versionString // can't run this command because oracle is not installed
```

6. What is your Oracle Database version? **10G and 11G**

**Comment by cjbj** [comment]
The release pages https://github.com/oracle/node-oracledb/releases/ show the platforms with pre-pre-compiled binaries.

On 32-bit Windows, you will need to compile node-oracledb yourself following https://oracle.github.io/node-oracledb/INSTALL.html#github

**Comment by Nuttapol01** [comment]
Uninstall nodejs 32bit ,install nodejs 64 instead,it work for me.
