### ISSUE TITLE
Typescript Definition now available for 4.0

### ISSUE THREAD

**Issue by connorjayfitzgerald** [oracle/node-oracledb#1136]
The DefinitelyTyped definition for oracledb 4.0 has now been merged and is available to use.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/oracledb

**Comment by connorjayfitzgerald** [comment]
One thing to note...

Due to the refactoring in 4.0, using both default and named exports will result in the named exports being undefined.

For example:

`import oracledb, { OUT_FORMAT_OBJECT } from 'oracledb';`

This will result in OUT_FORMAT_OBJECT being undefined.
Instead, separate out the default and named imports, like so:

`import oracledb from 'oracledb';`
`import { OUT_FORMAT_OBJECT } from 'oracledb';`

[See here for reference](https://github.com/Microsoft/TypeScript/issues/21621)

**Comment by sosoba** [comment]
Have you considered enriching the declaration with generic types for the result (with default Row type). Something like:
```typescript
interface Result<R> {
  rows: R[];
}
        
execute<R=Row>(sql: string, bindParams: BindParameters, options: ExecuteOptions): Promise<Result<R>>;
```

this would allow queries to be typed:

```typescript
   const res = await connection.execute<{X:string}>( 'SELECT X from DUAL' );
```

**Comment by connorjayfitzgerald** [comment]
Good idea!

See PR #37747

**Comment by sosoba** [comment]
I don't know if this is a good place for further comments.
oracledb@4 added a new 

> dbTypeName 

attribute to MetaData result. Type - string, It contains the name of the type the column has in the database, such as "VARCHAR2".

**Comment by connorjayfitzgerald** [comment]
@sosoba 

These missing properties will be added in PR [#37993](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37993)

**Comment by sosoba** [comment]
I have a litle issue: Record in line 581:
```ts
type BindParameters = Record<string, BindParameter | string | number | Date | DBObject | Buffer | null> | BindParameter[] | any[];
```
should also prevent `undefined` because `oracledb@4`treats them as null.

**Comment by connorjayfitzgerald** [comment]
@sosoba Could you send me a code snippet as I'm not sure what you mean?

The types do currently prevent bind parameters being undefined

**Comment by sosoba** [comment]
This js snippet print "1" because oracledb allow to pass `undefined` as null-value parameter:
```js
const oracledb  = require('oracledb');

(async function(){

  const conn = await oracledb.getConnection({user:'TEST',password:'TEST',connectString:'localhost:1521/XE'});
  const res = await conn.execute('SELECT * FROM DUAL where :p1 is null and :p2 is null', {
    p1:null, 
    p2:undefined,
  });
  console.log(res.rows.length);

})();
```
Type definition for `BindParameters` treats it as a mistake.

**Comment by connorjayfitzgerald** [comment]
It’s correct to flag it as a mistake, as oracledb ignores undefined bind parameters. You’ll get an error saying not all variables bound. 

You can test this by doing 
{
    p1: null,
    p2: undefined as any
}

**Comment by sosoba** [comment]
I'm trying again: 
```js
{
   p1: null,
}
```
give me `ORA-01008 : Not all variables bound`, but
```js
{
   p1: null,
   p2: undefined as any
}
```
give me success. Oracledb translate undefined to null. 

```js
Object.keys( { p1 : null, p2 : undefined } ); // [ 'p1', 'p2' ]
```

**Comment by connorjayfitzgerald** [comment]
Just tried again and you're right, it was treated as null. I'm sure I tried that yesterday!
This will be fixed in [#38496](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38496)

**Comment by sosoba** [comment]
Thank you.

**Comment by sosoba** [comment]
I have a doubt about [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/oracledb/oracledb-tests.ts](url). Asset at line 160:
```ts
 assert.deepStrictEqual(row, [1]);
```
is based on select without `order by` statement and there is no guarantee that database engine will allways return one in first row.

**Comment by sosoba** [comment]
Regadles to documentation:

> The default value for extendedMetaData is false. With this value, the result.metaData result.resultSet.metaData objects only include column names.

Could you add question marks to other fields than `name` in `interface Metadata`

**Comment by cjbj** [comment]
Updates for node-oracledb 4.1 got merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40653

Thank you @connorjayfitzgerald  !

**Comment by cjbj** [comment]
@connorjayfitzgerald has got a TypeScript PR ready for node-oracledb 5: DefinitelyTyped/DefinitelyTyped#45781

I think I'll close this old announcement issue - otherwise it could remain open forever!
