### ISSUE TITLE
Using oracledb synchronous?

### ISSUE THREAD

**Issue by LegoDummy** [oracle/node-oracledb#1138]
I am very sorry if my question has already been answered, but is there a way to use oracledb synchronous in node js? Basically what I am trying to do, is to create a function where I can pass some parameters and th result of the executed query will be returned. The problem is that that the `return myRes` does not wait to for the functions to be executed.

```js
module.exports = function(query, params, app){

const oracledb = require("oracledb");
const dbconfig = require("./dbconfig.js");
const paths = require("./paths.js");

oracledb.autoCommit = true;

var appPath = paths(app);
var config = dbconfig(appPath);

function test(query, params, config) {
    return new Promise(async function(resolve, reject) {
        let connection;
  
        try {
            connection = await oracledb.getConnection(config);
  
            const result = await connection.execute(query, params);
            resolve(result.rows);
  
        } catch (err) {
            reject(err);
        } finally {
            if (connection) {
                try {
                    await connection.release();
                } catch (e) {
                    console.error(e);
                }
            }
        }
    });
}
  
async function run() {
    try {
        const res = await test(query, params, config);
        console.log(res);
        return res;
    } catch (err) {
        console.error(err);
    }
}
  
var myRes = run();
console.log(myRes);

return myRes;
}
```

I hope my dumbness does not bother you guys to much. Thank you in advance for reading my question.

**Comment by dmcghan** [comment]
Synchronous alternatives to the asynchronous APIs have been discussed in the past. However, they seem like a bad idea now that async/await is a thing.

Your function should return a promise, not the result. It should resolve the result at the appropriate time. Users of your function would just put `await` in front and it would work as though it were synchronous.

**Comment by LegoDummy** [comment]
Thank you very much for helping! Everything works fine now!
