### ISSUE TITLE
order by desc

### ISSUE THREAD

**Issue by xforceco** [oracle/node-oracledb#114]
Is it supposed to work with order by desc? I see it does not have any effect when I use desc

Examples:
suppose I have a table TESTING with id="1" in first row, id="2" in second row ..... (total 100 rows)
I run "select * from TESTING where rownum = 10 order by id DESC;" in oracle NATIVELY

is not the same as

"select * from TESTING where rownum = 10 order by id DESC" running in nodejs with node-oracledb

**Comment by cjbj** [comment]
Works for me.  

It would be useful to have code snippets, versions and platform info.  (And a definition of what "natively" really means!)
