### ISSUE TITLE
node-oracledb not able to install on azure functions with win32 ia32

### ISSUE THREAD

**Issue by AzharShaikhSE** [oracle/node-oracledb#1140]
npm i oracledb is throwing the below error:

"a pre-built node-oracledb binary was not found for Node.js v8.11.1 (NODE_MODULE_VERSION=57) on win32 ia32"

can you please suggest how can I install it on azure? thanks!

**Comment by cjbj** [comment]
There is no prebuilt binary for ia32.  The available binaries are listed on the [releases page](https://github.com/oracle/node-oracledb/releases).  Use another system (Oracle Cloud?!) or compile the driver yourself https://oracle.github.io/node-oracledb/INSTALL.html#github
