### ISSUE TITLE
How to warm up connection pool - Initial pool.getConnection takes over 10 seconds

### ISSUE THREAD

**Issue by dwntwnbrown** [oracle/node-oracledb#1142]
Log output from pool.getConnection first time:

2019-08-20 12:50:46.743 debug: Getting database connection
2019-08-20 12:50:46.860 info: Connection pool [default] started
2019-08-20 12:50:46.860 debug: before getConnection number of connections in use: 0
2019-08-20 12:50:46.860 debug: before getConnection number of connections open: 0
2019-08-20 12:50:57.012 debug: after getConnection number of connections in use: 1
2019-08-20 12:50:57.012 debug: after getConnection number of connections open: 1

Pool statistics:
...total up time (milliseconds): 10154
...total connection requests: 1
...total requests enqueued: 0
...total requests dequeued: 0
...total requests failed: 0
...total request timeouts: 0
...max queue length: 0
...sum of time in queue (milliseconds): 0
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 0
...avg time in queue (milliseconds): 0
...pool connections in use: 1
...pool connections open: 1
Related pool attributes:
...poolAlias: default
...queueTimeout (milliseconds): 60000
...poolMin: 0
...poolMax: 4
...poolIncrement: 1
...poolTimeout (seconds): 60
...poolPingInterval: 60
...sessionCallback: undefined
...stmtCacheSize: 30
Pool status:
...status: 6000
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 10

3. Include a runnable Node.js script that shows the problem.

Initial pool creation with default values:

    this.pool = await oracledb.createPool({
      _enableStats: true,
      user: dbConfig.user,
      password: dbConfig.password,
      connectString: dbConfig.connectString
    });

    logMgr.info("Connection pool [" + this.pool.poolAlias + "] started");

    logMgr.debug("before getConnection number of connections in use: " +
      this.pool.connectionsInUse);
    logMgr.debug("before getConnection number of connections open: " +
      this.pool.connectionsOpen);

    let connection = await this.pool.getConnection();

    logMgr.debug("after getConnection number of connections in use: " +
      this.pool.connectionsInUse);
    logMgr.debug("after getConnection number of connections open: " +
      this.pool.connectionsOpen);

    this.pool._logStats();

4. Run node and show the output of:

process.platform - darwin
process.version - v12.8.0
process.arch - x64
require('oracledb').versionString - 4.0.0

instantclient_12_2

5. What is your Oracle Database version?

Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

**Comment by cjbj** [comment]
I'd like to know what triggers this, but the 'solution' is probably the same as https://github.com/oracle/node-oracledb/issues/1126#issuecomment-521066287

Do you know if the DB service has any configuration settings (e.g. to broadcast FAN events)?

Are you using a simple connection string, or do you have a tnsnames.ora entry with various other options?

Do you have a sqlnet.ora file configured?  What if you add `DISABLE_OOB=ON` to a sqlnet.ora file?  (On macOS I use $HOME/.sqlnet.ora - with leading full stop)

**Comment by dwntwnbrown** [comment]
I am not sure about the configuration settings - I can try and follow up on that.

Simple connection string (//uri:1521/sid)

I did already have a sqlnet.ora file with the DISABLE_OOB=ON to resolve the hanging node server when trying to shutdown gracefully calling the pool.close() method.

I did verify that setting events: false as an option to the pool create resolved the issue:

2019-08-20 16:52:47.225 debug: before getConnection number of connections in use: 0
2019-08-20 16:52:47.225 debug: before getConnection number of connections open: 0
2019-08-20 16:52:47.723 debug: after getConnection number of connections in use: 1
2019-08-20 16:52:47.724 debug: after getConnection number of connections open: 1

Thanks for the assistance.

**Comment by dwntwnbrown** [comment]
FAN looks like a feature that is only available on a Real Application Cluster (RAC) database.  None of the databases we work on are RAC.

**Comment by cjbj** [comment]
@dwntwnbrown Can I get you to reproduce the problem with some tracing enabled?

In your sqlnet.ora add something like:
```
ADR_BASE=/tmp/mylogs
TRACE_LEVEL_CLIENT=16
```

Make the directory:
```
mkdir /tmp/mylogs
```

Then run your app (with events left at the default of enabled).   You will see traces in a subdir of `/tmp/mylogs`.  For me, they are in `/tmp/mylogs/oradiag_cjones/diag/clients/user_cjones/host_2709986801_110/trace`.

Zip up the contents and [mail me](https://github.com/cjbj).  Or put the .trc file in a [gist](https://gist.github.com), if there is nothing secret in it.

Thanks!

**Comment by dwntwnbrown** [comment]
@cjbj Requested zip file has been emailed

**Comment by dwntwnbrown** [comment]
Moving from instant client 12.2 to 18.1 also resolves the issue.

**Comment by cjbj** [comment]
Thanks for the update @dwntwnbrown, and also for the debugging you did.

**Comment by cjbj** [comment]
node-oracledb 4.1 will revert `events` back to *false* so this shouldn't happen in out-of-the-box usage. 

Also see #1126
