### ISSUE TITLE
Binding named oracle type with nested record and a null date results in Error: ORA-01841: (full) year must be between -4713 and +9999, and not be 0

### ISSUE THREAD

**Issue by dwntwnbrown** [oracle/node-oracledb#1144]
1. With the async/await programming style, make sure you are using 'await' in the right places.

In the example code below when uncommenting the setting of the date field (select sysdate into td.today from dual;) in the nested record the application runs to completion.

2. Is it an error or a hang or a crash?
error

3. What error(s) you are seeing?
Error: ORA-01841: (full) year must be between -4713 and +9999, and not be 0

4. Include a runnable Node.js script that shows the problem.
```
'use strict';

const oracledb = require('oracledb');
const dbConfig = require('./dbconfig-test.js');

async function run() {

  let connection, result;

  try {

    connection = await oracledb.getConnection(dbConfig);

    let stmts = [

      `drop package testtypepkg`,

      `drop procedure getTestType`,

      `create package testtypepkg as

        type testday is record (
          today date);

        type testtype is record (
          id  number,
          day testtypepkg.testday);
       end;`,

      `create procedure getTestType(tt out testtypepkg.testtype)
       as
         td testtypepkg.testday;
       begin
         tt.id := 1;

         -- ************************************************
         -- Uncomment the following line and runs successful
         -- ************************************************
         -- select sysdate into td.today from dual;

         tt.day := td;
       end;`
    ];

    for (const s of stmts) {
      try {
        await connection.execute(s);
      } catch(e) {
        if (e.errorNum != 942 && e.errorNum != 4043)
          console.error(e);
      }
    }

    let result = await connection.execute(
      `declare t testtypepkg.testtype;
       begin
         getTestType(t);
         :rtnType := t;
       end;`,
      { rtnType: { dir: oracledb.BIND_OUT, type: "TESTTYPEPKG.TESTTYPE" } },
      { outFormat: oracledb.OUT_FORMAT_OBJECT });

    // cannot stringify the result or access the day record from testtype
    // when the today field is not populated.
    // results in Error: ORA-01841: (full) year must be between -4713 and +9999, and not be 0
    console.log(JSON.stringify(result));

    console.log(result.outBinds.rtnType.DAY);

  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

run();
```

5. Run node and show the output of:

process.platform - darwin
process.version - v12.8.0
process.arch - x64
require('oracledb').versionString - 4.0.1

instantclient_18_1

6. What is your Oracle Database version?

Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

**Comment by cjbj** [comment]
Thanks for the nice testcase.

Uninitialized values like that can cause problems.  This is not node-oracledb specific.

But it's not so clear to me why if I do initialize it to `td.today := null;` I also get the same error.  

@pvenkatraman will take a look.

**Comment by cjbj** [comment]
@dwntwnbrown the PL/SQL group have made a fix that resolves this issue.  It is tracked as Oracle bug 30267269 and will be available in some future version of Oracle. The fix only requires an updated client library.  A backport request to make the fix available in a 19c patch has been logged.  If you need the fix, request a patch from Oracle Support.  Thanks for reporting it.

**Comment by lrecknagel** [comment]
If anyone comes over this issue and need a hacky fix, maybe the following helps:
(Please let me know if the the idea is too bad).

```js
const makeOra01841CatchProxy = object => new Proxy(object, {
  get(obj, prop) {
    try {
      return obj.prop;
    } catch (error) {
      console.error(`${ prop } | ${ error.name }`);
      return undefined;
    }
  },
});
```
