### ISSUE TITLE
Docker node-oracledb

### ISSUE THREAD

**Issue by RizziWilliam** [oracle/node-oracledb#1147]
i have been using node-oracledb in a backend project, now i need to run the project with docker.

```
FROM node:10.16.0-stretch-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:10.16.0-stretch-slim
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
ENV API_PORT=3000
ENV NODE_ENV=production
CMD ["npm", "start"]
```

Everything work's fine, but when i try to reach a endpoint, this error appears.

`DPI-1047: Cannot locate a 64-bit Oracle Client library: \"libclntsh.so: cannot open shared object file: No such file or directory\". See https://oracle.github.io/odpi/doc/installation.html#linux for help\nNode-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html\nYou must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.\nIf you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from \nhttp://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html\n",`

Already look into the issues but couldn't solve my problem. Can you guys help me out?

**Comment by dmcghan** [comment]
@RizziWilliam Have a look at this blog post from @OsBlaineOra:
https://learncodeshare.net/2019/08/27/howto-connect-your-nodejs-app-in-docker-to-your-oracle-database/

And this one from @cjbj:
https://blogs.oracle.com/opal/dockerfiles-for-node-oracledb-are-easy-and-simple

Note that there are some additional dependencies needed for node-oracledb. They are both using Oracle Linux which makes it easier to install Oracle dependencies, but you should be able to adapt that to your OS if you can't change to Oracle Linux. 

Here's a Dockerfile from the Slack channel that someone recently published:

```dockerfile
FROM node:12.8.1-slim

ADD ./clients/ .

# Installs all necessary requirements to run the oracle instant client
RUN apt-get update \
 && apt-get install -y unzip wget libaio1 \
 && mkdir -p opt/oracle \
# ADD ORACLE INSTANT CLIENT from local system
 && unzip instantclient-basic-linux.x64-19.3.0.0.0dbru.zip -d /opt/oracle \
 && mv /opt/oracle/instantclient_19_3 /opt/oracle/instantclient

# Setup the path to find the instantclient with node-oracledb library
ENV LD_LIBRARY_PATH="/opt/oracle/instantclient"

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
```

As you can see, he's just copying the dependencies in (first had to download them to the local machine) and extracting them where they need to go.

**Comment by cjbj** [comment]
In summary, read the the node-oracledb installation instructions https://oracle.github.io/node-oracledb/INSTALL.html#instzip !

It could avoid a class of problems if ldconfig was used instead of setting LD_LIBRARY_PATH.

**Comment by RizziWilliam** [comment]
Taking a look into the links and examples. 
The difference is that a don't have the unzip files in the computer where the backend is running.

**Comment by RizziWilliam** [comment]
I managed to make it work. 
```
FROM node:10.16.0-stretch-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:10.16.0-stretch-slim
WORKDIR /app
RUN apt-get update && apt-get install -y alien libaio1 
ADD oracle-instantclient*.rpm /tmp/
RUN alien -i /tmp/oracle-instantclient*.rpm && \
    rm -rf /var/cache/yum && \
    rm -f /tmp/oracle-instantclient*.rpm && \
    echo /usr/lib/oracle/12.2/client64/lib > /etc/ld.so.conf.d/oracle-instantclient12.2.conf && \
    ldconfig
COPY --from=builder /app .
EXPOSE 3000
ENV API_PORT=3000
ENV NODE_ENV=production
ENV PATH=$PATH:/usr/lib/oracle/12.2/client64/bin
CMD ["npm", "start"]
```

doesn't seen to be the best approach, but it's working. Wasn't able to use the https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/19/Dockerfile

**Comment by cjbj** [comment]
What about a Dockerfile like this?:

```
FROM node:10.16.0-stretch-slim

WORKDIR /tmp
RUN apt-get update && apt-get install -y alien libaio1
RUN wget http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient19.3-basiclite-19.3.0.0.0-1.x86_64.rpm
RUN alien -i --scripts oracle-instantclient*.rpm
RUN rm -f oracle-instantclient19.3*.rpm && apt autoremove && apt clean

WORKDIR /myapp
ADD package.json /myapp/
ADD index.js /myapp/
ADD dbconfig.js /myapp/
RUN npm install

CMD exec node index.js
```

Personally I'd use two Dockerfiles or images, one with Node & Instant Client, and the other with the app.

**Comment by RizziWilliam** [comment]
It's required to change the node version to be able to use instant client 19.3?

**Comment by cjbj** [comment]
@RizziWilliam
- Node.js 8.16+, 10.16+ and 12+ can be used with node-oracledb 4
- node-oracledb 4 will work with Oracle client 11.2 or later
- Oracle Client can connection to multiple versions of Oracle DB, see https://support.oracle.com/epmos/faces/DocumentDisplay?id=207303.1 In summary, Oracle Client 19, 18 and 12.2 can connect to Oracle Database 11.2 or greater. Oracle Client 12.1 can connect to Oracle Database 10.2 or greater. Oracle Client 11.2 can connect to Oracle Database 9.2 or greater.

 If you're all fine, can you close this issue?

**Comment by RizziWilliam** [comment]
Thank you for the help.
