### ISSUE TITLE
oracledb getConnection is not a function

### ISSUE THREAD

**Issue by LyssenkoAlex** [oracle/node-oracledb#1149]
# Answer the following questions
1. Describe the problem and show the error you have.
While trying to connect to remote oracle db get error getConnection is not a function

2. What Node.js version are you using?  Run node and show the output of:

OS version:
CentOS Linux release 7.5.1804 (Core)
NodeJs.Version:
v10.16.3
Db version:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
Client:
oracle-instantclient19.3-basic-19.3.0.0.0-1.x86_64.rpm

process.arch - 64
process.platform - linux
process.version - v10.16.3

3. Are you installing into vanilla Node.js, or using something like Electron?
Vanilla Node,js

4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?

64-bit
[listing.txt](https://github.com/oracle/node-oracledb/files/3578343/listing.txt)

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.
[xxxxx@xxxx lib]$ echo $LD_LIBRARY_PATH
/usr/lib/oracle/19.3/client64/lib

6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
no oracle bd on linux mashine

**Comment by cjbj** [comment]
What's the actual code you are running?

How did you install the Instant Client RPM - did libaio get pulled correctly?

Do you need to set LD_LIBRARY_PATH - the RPM should run ldconfig?  Look in /etc/ld.conf.so.d for the instant client file.

**Comment by LyssenkoAlex** [comment]
Code list:
[code_list.txt](https://github.com/oracle/node-oracledb/files/3578647/code_list.txt)


LD_LIBRARY_PATH is set 

echo $LD_LIBRARY_PATH
/usr/lib/oracle/19.3/client64/lib

I did
sudo sh -c "echo /usr/lib/oracle/19.3/client64/lib > /etc/ld.so.conf.d/oracle-instantclient.conf"
export LD_LIBRARY_PATH=/usr/lib/oracle/19.3/client64/lib

Got error:
TypeError: connection.getConnection is not a function

**Comment by LyssenkoAlex** [comment]
I checked connection with python code, it Works.

**Comment by cjbj** [comment]
Check the [examples](https://github.com/oracle/node-oracledb/blob/master/examples/webappawait.js#L54) and use `await` or a callback so the pool creation completes before you start using.

It would be wise to rename variables logically: use `pool` for the pool, not `connection`.  And try `oracledb` instead of `mysql` . . . .

**Comment by LyssenkoAlex** [comment]
Thanks for great help!
await helped!
I tried oracle connections according this example:
https://dev.to/saulojoab/how-to-get-data-from-an-mysql-database-in-react-native-53a4
it is about mysql.
But it did not work.
when i added asyn and await everything OK!
thanks a lot!!

**Comment by LyssenkoAlex** [comment]
thanks
