### ISSUE TITLE
Object Out Example error: ORA-04043: object NETBALL.TEAMTYPE does not exist 

### ISSUE THREAD

**Issue by gaurang171** [oracle/node-oracledb#1150]
1. With the async/await programming style, make sure you are using 'await' in the right places.
yes

2. Is it an error or a hang or a crash?
error

3. What error(s) you are seeing?
{ Error: ORA-04043: object NETBALL.TEAMTYPE does not exist
    at Connection.execute (C:\XXXXXXXXX\node_modules\oracledb\lib\connection.js:169:17)
    at C:\XXXXXXXXX\node_modules\oracledb\lib\util.js:180:16
    at new Promise (<anonymous>)
    at Connection.execute (C:\XXXXXXXXX\node_modules\oracledb\lib\util.js:168:14)
    at run (C:\XXXXXXXXX\plsqlvarrayrecord.js:104:37) errorNum: 4043, offset: 0 }

4. Include a runnable Node.js script that shows the problem.
Include all SQL needed to create the database schema.
https://github.com/oracle/node-oracledb/blob/master/examples/plsqlvarrayrecord.js

5. Run node and show the output of:

```
process.platform: 'win32'
process.version: 'v10.16.0'
process.arch: 'x64'
require('oracledb').versionString: '4.0.1'
```

6. What is your Oracle Database version?
Oracle Database 10g Enterprise Edition Release 10.2.0.3.0 - 64bi

**Comment by cjbj** [comment]
- you'd need to give a short, runnable script and the SQL to create the type.

- you may have issues with such an old DB, since support for interaction for various DB types in C clients (such as node-oracledb) was only added with Oracle DB 12.1

**Comment by gaurang171** [comment]
Thank you @cjbj for pointing to the document. I missed the client and database version needs.
