### ISSUE TITLE
Can i set maxSize in count of characters, not in bytes?

### ISSUE THREAD

**Issue by urzt** [oracle/node-oracledb#1151]
Hello,
Can i set ```maxSize``` in count of characters, not in bytes?
Thnx

**Comment by cjbj** [comment]
The bind maps down to something like https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/bind-define-describe-functions.html#GUID-55C47708-5468-4106-89BE-1AB60861D037 where value_sz is documented as 'The maximum size possible in bytes of any data value (passed using valuep) for this bind variable. This size is always expected to be the size in bytes.'
