### ISSUE TITLE
Failure on AIX: ORA-24374: define not done before fetch or execute and fetch

### ISSUE THREAD

**Issue by sibintv** [oracle/node-oracledb#116]
We can not connect our node application to oracle database which are installed in AIX operating system ,  Can connect to the database from external Linux OS . Is there any known issues for AIX for oracledb npm module . we are able to install oracledb module , but getting an error "ORA-24374: define not done before fetch or execute and fetch" when trying to connect . any help is greatly appreciated

**Comment by cjbj** [comment]
Can you post a reproducible test case - one that works absolutely unchanged on Linux i.e. uses the same credentials and connection string on both platforms.

**Comment by sibintv** [comment]
Create a test project using node and express (node version v0.10.38, npm 1.3.6 )
express -c stylus sample
cd sample && npm install
npm install oracledb

create a app1.js sample file to get a query from oracle 12c which is hosted in same server

###########################
var oracledb = require('oracledb');
oracledb.getConnection(
  {
    user          : "username",
    password      : "passwordd",
    connectString : "localhost:1521/DB"
  },
  function(err, connection)
  {
    if (err) {
console.log ("xyz");
      console.error(err.message);
      return;
    }
    connection.execute(
      "SELECT count(*) as X from phylum ",
      [],
      function(err, result)
      {
        if (err) {
console.log ("abc");
          console.error(err.message);
          return;
        }
        console.log(result.rows);
      });
  });
########################################

while try to start application from AIX, we are getting 
bash-3.2# node app.js 
abc
ORA-24374: define not done before fetch or execute and fetch

The same script running on a Centos machine , connecting to the same above database in AIX returns (connection string changed to remote IP from localhost)

[root@mymachine sample]# node app1.js 
[ [ 9 ] ]

**Comment by sibintv** [comment]
app.js and app1.js are same files

**Comment by cjbj** [comment]
@sibintv  Do other queries work? What about DML statements? Is this all 64bit?  What version of AIX?

@schmafu since you added AIX build support, I wonder if you able to reproduce this problem?

**Comment by sibintv** [comment]
Yes,
We can not login to our application which is hotsted in AIX , but able to login from application hosted in CentOS using the same database  
AIX version is 7.1
All installed packages are 64bit

**Comment by schmafu** [comment]
@cjbj I am sorry I no longer have access to an AIX machine :/

**Comment by sibintv** [comment]
@cjbj Can you suggest how can we troubleshoot more ? . We are stuck with this issue for last two weeks .
Does anyone succeeded on work with AIX / nodejs / Oracle ?

**Comment by cjbj** [comment]
Can you query other datatypes?  Can you do DML statements (not queries)? 
What's the exact version of the Oracle client libraries and Oracle DB you are using?

**Comment by sibintv** [comment]
DML works fine. Select doesn't seem to work. We were able to insert/update some data but selecting via application fails .

Client Shared Library 64-bit - 12.1.0.2.0
System name:    AIX
Release:        1
Version:        6
Oracle Database 12c Release 12.1.0.1.0 - 64bit Production
PL/SQL Release 12.1.0.1.0 - Production
CORE    12.1.0.1.0      Production
TNS for IBM/AIX RISC System/6000: Version 12.1.0.1.0 - Production
NLSRTL Version 12.1.0.1.0 - Production

**Comment by cjbj** [comment]
Can you debug the driver and step through code execution, comparing what happens on Linux with what happens on AIX?

**Comment by pvenkatraman** [comment]
Does this query fail for any database types or only for INTEGER types?  Similar script executing "SELECT COUNT(*) from <table>" works good on Linux/Windows.

**Comment by sibintv** [comment]
@pvenkatraman 
We are not able to execute any select/fetch statements from the database ,
for example
       "select name from zone",

No issues with Linux for the same statement (both in Ubuntu and Redhat)

**Comment by cjbj** [comment]
@sibintv don't worry about debugging for the moment, @pvenkatraman is going to look into the problem.

**Comment by sibintv** [comment]
waiting for @pvenkatraman

**Comment by pvenkatraman** [comment]
What is the AIX version you are using.  You have mentioned both 6.1 & 7.1 in the thread.

**Comment by sibintv** [comment]
Sorry for the Confusion , Its 7.1

**Comment by sibintv** [comment]
@pvenkatraman , Any updates ?

**Comment by cjbj** [comment]
@sibintv we are waiting on access to an AIX machine.  Are you able to install with --debug and step through the code on AIX and Linux?

**Comment by sibintv** [comment]
Can you please comment the steps to debug , since we are not familiar with this

**Comment by cjbj** [comment]
It's C debugging: attach to a running process and step through the calls, seeing what is different on Linux vs AIX.

**Comment by sibintv** [comment]
@cjbj , we heard the recent release of oracledb 0.7.0 with Simple SELECT statement implementation , Will this fix our issue in AIX ?

**Comment by cjbj** [comment]
@sibintv there was no specific change but perhaps the altered code paths behave differently.

**Comment by sibintv** [comment]
@cjbj , There was no change in new version(oracledb 0.7.0 ) also . Its still not working in AIX
@pvenkatraman , Any updates ?

**Comment by cjbj** [comment]
@sibintv it will be fixed in the next version, 1.1.  Sorry for the delay.

**Comment by sibintv** [comment]
@cjbj ,Thanks for the update . We are waiting for the version, 1.1.

**Comment by cjbj** [comment]
@sibintv I just pushed 1.1 which fixes the query problem.  Let us know how you go.  

There are a couple of test diffs on AIX that we are still taking a look at.

**Comment by sibintv** [comment]
Will test and let you know

**Comment by sibintv** [comment]
sorry for the late reply
I got worked in AIX with  1.1 release, Thanks for the support

**Comment by cjbj** [comment]
@sibintv thanks for checking.  There was a REF CURSOR fix for AIX in 1.2, as well.
