### ISSUE TITLE
connectString : DESCRIPTION_LIST not working

### ISSUE THREAD

**Issue by chandreshraj** [oracle/node-oracledb#1162]
This is the URL that is being used in connectString :  which is not working
```js
connectString : "(DESCRIPTION_LIST=
    (FAILOVER=on)(LOAD_BALANCE=off)
    (DESCRIPTION= 
        (ADDRESS=(protocol_address_information))
        (ADDRESS=(protocol_address_information))
        (ADDRESS=(protocol_address_information))
        (CONNECT_DATA= 
            (SERVICE_NAME=(SID=sid))
        )
    )
    (DESCRIPTION= 
        (ADDRESS=(protocol_address_information))
        (ADDRESS=(protocol_address_information))
        (ADDRESS=(protocol_address_information))
        (CONNECT_DATA= 
            (SERVICE_NAME=(SID=sid))
        )
    )
)"
```
but with the "DESCRIPTION": it is connecting to DB
```js
connectString : "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = host)(PORT = port))(CONNECT_DATA =(SID= sid)))"
```
### --here is say's DESCRIPTION works what about DESCRIPTION_LIST..??

# If I am using it wrong way please correct it.

**Comment by cjbj** [comment]
I don't understand your question.  Do you have an error?  Connection strings in node-oracledb are the same as in tools like SQL*Plus.

**Comment by chandreshraj** [comment]
{ Error: ORA-12154: TNS:could not resolve the connect identifier specified errorNum: 12154, offset: 0 }
ORA-12154: TNS:could not resolve the connect identifier specified

Above is the error I am getting while using the DISTRIBUTION_LIST

**Comment by cjbj** [comment]
Where did you get the syntax from?  Doesn't `(SERVICE_NAME=(SID=sid))` look a little suspicious?

**Comment by cjbj** [comment]
One related example that I have handy is slide 39 from https://static.rainfocus.com/oracle/oow19/sess/155356052830600180DE/PF/DEV4625-Scalability-and-High-Availability-for-Oracle-Database-Python-Applications_1568931704636001Qx1H.pdf

Google around and check the documentation.  Start by finding your service names. This is not specific to node-oracledb. Good luck!

**Comment by cjbj** [comment]
Closing - no feedback
