### ISSUE TITLE
NJS-045, Angular electron app with oracledb error

### ISSUE THREAD

**Issue by smallg** [oracle/node-oracledb#1164]
i use electron and angular to build app for test
electron 7.0.0
angular 8
If i don't use oracledb, everything is ok
but if i install oracledb(4.0.1), and use like this:
```javascript
try {
      const oracledb = require('oracledb');
      console.log(oracledb);
      console.log(oracledb.oracleClientVersion);
    } catch (error) {
      console.log(error);
    }
```

the error code is:
![image](https://user-images.githubusercontent.com/225962/67379946-35655180-f5bc-11e9-8696-2c6234ae6f11.png)

**Comment by smallg** [comment]
BTW, my test repo is: https://github.com/smallg/angular-electron

**Comment by cjbj** [comment]
Have you reviewed previous questions?  E.g. https://github.com/oracle/node-oracledb/issues/1141#issuecomment-523011669 ?

**Comment by smallg** [comment]
@cjbj i follow that, but still not work.
could you please clone my repo, and test it?
Thanks

**Comment by cjbj** [comment]
@smallg how are you going with this?

**Comment by cjbj** [comment]
Closing - no update
