### ISSUE TITLE
Can't execute UPDATE

### ISSUE THREAD

**Issue by urzt** [oracle/node-oracledb#1166]
Hello,
I can't execute this code. And i have not any error, its not handle.
Execute-function does not working and promise stay in Pending.
This SQL-query work correctly in my SQL-Developer client.
This code with SELECT or INSERT working correctly. 
What i'am doing wrong?
Thnx

```
try {

   connection = await oracledb.getConnection({ 
                user: dbConfig.user, 
                password: dbConfig.password, 
                connectString: dbConfig.connectString
   });

   result = await connection.execute(
		`UPDATE "SYSTEM".AUTH_SESSIONS 
                 SET DATE = SYSTIMESTAMP + interval '${config.Time.inMinutes}' minute 
                 WHERE ID = :id 
                `,
		{  autoCommit: true },
		{ id: { val: id, type: oracledb.STRING, maxSize: 44*2  } }
   )

   console.log(result)

} catch (err) {

   console.log(err)

}
```

**Comment by dmcghan** [comment]
There are a lot of things wrong here.

1. You should not be working with objects in SYSTEM. Use SYSTEM to create your own schema and work with objects there.
2. You have reversed the order of your options and bind variables. You'll need to swap those.
3. Even though `config.Time.inMinutes` looks developer contolled, you should probably use a bind variable with `numtodsinterval` anyway:

```
update t
set c = systimestamp + numtodsinterval(:time_in_minutes, 'MINUTE')
where c2 = :id;
```

4. Where are you closing the connection?

**Comment by urzt** [comment]
Thankoyu, its works for me.
1. Check
2. It's an answer
3. Check
4. I show a part of code, i close connection later.

Can you tell me, why when i use asynchronous requests - i get errors:
 - NJS-018: invalid ResultSet;
 - NJS-003: invalid connection
Its a common error?
