### ISSUE TITLE
Bind transactions

### ISSUE THREAD

**Issue by GuiJordao21** [oracle/node-oracledb#1169]
IS there a way to bind transactions between connections? I looked it up on the documentation and didn't found anything about it.

**Comment by dmcghan** [comment]
@GuiJordao21 I've never heard of such a thing in the Oracle world. Transactions are tied to sessions and each connection has its own session.

Could you please provide an example of how you would use such a feature?

**Comment by cjbj** [comment]
@GuiJordao21 do you mean something like the functionality of the `DBMS_XA` package?  Last time I played with it was a while back; see p 230 of http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html

> The DBMS_XA package can be used to start, resume and complete database transactions. Web applications can rely on the database to store the transaction state. If you have multiple mid-tier web servers, this removes the need to track the state of a set of SQL operations. The only shared information needed by each web request is a numeric key identifying the transaction.

**Comment by cjbj** [comment]
Closing - no update
