### ISSUE TITLE
Win trouble with oracledb.js and oracledb.node

### ISSUE THREAD

**Issue by rlacroce** [oracle/node-oracledb#117]
Hi, i'm new on node.js and i need to connect with oracle DB 9.
Follow installation step i do:
1) install instant_client 11 (it work with ODBC test)
2) installa node (it work!)
3) set env var (i think it work!)
4) install oracledb driver (npm install oracledb) ... it work!...

At least i create a simple example and i got an error on "var oracle = require('oracledb');" ... someone can help me?  Thanks...

>node example.js
>C:\Programmi\nodejs\node_modules\oracledb\lib\oracledb.js:28
>   throw err;
          ^
>Error: error: 127C:\Programmi\nodejs\node_modules\oracledb\build\Release\oracledb.node
>    at Error (native)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Module.require (module.js:365:17)
>    at require (module.js:384:17)
>    at Object.<anonymous> (C:\Programmi\nodejs\node_modules\oracledb\lib\oracledb.js:23:15)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)

**Comment by cjbj** [comment]
Sorry, this slipped through.  I expect the Oracle libraries are not in your PATH.
