### ISSUE TITLE
select statement causes NJS-024: memory allocation failed on AIX, but works fine on Linux

### ISSUE THREAD

**Issue by jungand** [oracle/node-oracledb#1170]
I have the following code which runs as expected on linux but produces errors on AIX.
Although I'm quite new to node I would suspect this could be an issue with the node-oracledb lib. For me it looks like it's related to the fact that the statements which run into errors have where conditions. 
I haven't tried any other statements like DML yet because I wanted to make sure that I can
continue with my efforts because the AIX platform is a 'hard' requirement for me.

Could someone kindly have a look at this issue.

**Code**

taken from example provided here: https://oracle.github.io/node-oracledb/doc/api.html

```
...
async function runtest() {
  let conn;

  try {
    conn = await oracledb.getConnection(config);

    let result;

    console.log("'select user from dual'");
    try {
      result = await conn.execute('select user from dual');
      console.log(result.rows);
    } catch (err) {
      console.log(err);
    }

    console.log("'select user from dual', {}");
    try {
      result = await conn.execute('select user from dual', {});
      console.log(result.rows);
    } catch (err) {
      console.log(err);
    }

    console.log("'select * from all_users where rownum < 5', {}");
    try {
      result = await conn.execute('select * from all_users where rownum < 5', {});
      console.log(result.rows);
    } catch (err) {
      console.log(err);
    }

    console.log("'select * from all_users where username like :username', { username: 'BRKS%' }");
    try {
      result = await conn.execute('select * from all_users where username like :username', { username: 'BRKS%' } );
      console.log(result.rows);
    } catch (err) {
      console.log(err);
    }
  } catch (err) {
    console.log(err);
  } finally {
    if (conn) { // conn assignment worked, need to close
       await conn.close();
    }
  }
}

console.log('platform: '+process.platform);
console.log('version: '+process.version);
console.log('arch: '+process.arch);
console.log('oracledb version: '+require('oracledb').versionString);
runtest();

```
**AIX**

AIX 7.1
Oracle 11.2.0.4
Instantclient 12.2 + 19.3
node-oracledb 4.0, built with gcc 6.3.0

> node /home/ajung/nodedemo/t/querytest.js
platform: aix
version: v12.13.0
arch: ppc64
oracledb version: 4.0.1
'select user from dual'
Error: NJS-024: memory allocation failed
    at Connection.execute (/home/ajung/nodedemo/node_modules/oracledb/lib/connection.js:169:17)
    at /home/ajung/nodedemo/node_modules/oracledb/lib/util.js:180:16
    at new Promise (<anonymous>)
    at Connection.execute (/home/ajung/nodedemo/node_modules/oracledb/lib/util.js:168:14)
    at runtest (/home/ajung/nodedemo/t/querytest.js:66:27)
'select user from dual', {}
Error: NJS-024: memory allocation failed
    at Connection.execute (/home/ajung/nodedemo/node_modules/oracledb/lib/connection.js:169:17)
    at /home/ajung/nodedemo/node_modules/oracledb/lib/util.js:180:16
    at new Promise (<anonymous>)
    at Connection.execute (/home/ajung/nodedemo/node_modules/oracledb/lib/util.js:168:14)
    at runtest (/home/ajung/nodedemo/t/querytest.js:74:27)
'select * from all_users where rownum < 5', {}
Error: NJS-024: memory allocation failed
    at Connection.execute (/home/ajung/nodedemo/node_modules/oracledb/lib/connection.js:169:17)
    at /home/ajung/nodedemo/node_modules/oracledb/lib/util.js:180:16
    at new Promise (<anonymous>)
    at Connection.execute (/home/ajung/nodedemo/node_modules/oracledb/lib/util.js:168:14)
    at runtest (/home/ajung/nodedemo/t/querytest.js:82:27)
'select * from all_users where username like :username', { username: 'BRKS%' }
[
  [ 'BRKSCI', 964, 2018-10-12T14:50:00.000Z ],
  [ 'BRKSCEP', 239, 2018-10-12T14:49:54.000Z ],
  [ 'BRKSCED', 230, 2018-10-12T14:49:54.000Z ]
]

**LINUX**

Red Hat Enterprise Linux 7.5
Oracle 11.2.0.4
Instantclient 12.2 + 19.3
node-oracledb 4.0, installed with npm

-bash-4.2$ node /home/ajung/nodedemo/t/querytest.js
platform: linux
version: v12.13.0
arch: x64
oracledb version: 4.0.1
'select user from dual'
[ [ 'DEMOUSER' ] ]
'select user from dual', {}
[ [ 'DEMOUSER' ] ]
'select * from all_users where rownum < 5', {}
[
  [ 'SYS', 0, 2018-10-12T13:22:11.000Z ],
  [ 'SYSTEM', 5, 2018-10-12T13:22:11.000Z ],
  [ 'OUTLN', 9, 2018-10-12T13:22:13.000Z ],
  [ 'DIP', 14, 2018-10-12T13:23:25.000Z ]
]
'select * from all_users where username like :username', { username: 'BRKS%' }
[
  [ 'BRKSCI', 964, 2018-10-12T14:50:00.000Z ],
  [ 'BRKSCEP', 239, 2018-10-12T14:49:54.000Z ],
  [ 'BRKSCED', 230, 2018-10-12T14:49:54.000Z ]
]

**Comment by cjbj** [comment]
The SQL itself won't have direct significance but the results returned might.

The last time I recall issues with NJS-024 was also on AIX but way back with node-oracledb 1, and that was with exetendedMetadata set to true

Can you refine the testcase?  Is it datatypes, is it number of rows?
Can you try node-oracledb 3.1?

**Comment by jungand** [comment]
unfortunately I wasn't able to install/build node-oracledb 3.1.2 (or any other than 4.0.1) on my test server:

```
$ export CC=gcc
$ npm config set proxy http://anonymous:anonymous@xxx.xxx.xxx.xxx:8080/
$ npm install https://github.com/oracle/node-oracledb/releases/download/v3.1.2/oracledb-src-3.1.2.tgz

> oracledb@3.1.2 install /home/ajung/nodedemo-oradb-3.1.2/node_modules/oracledb
> node-gyp rebuild

gmake: Entering directory '/home/ajung/nodedemo-oradb-3.1.2/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njsCommon.o
In file included from ../src/njsCommon.h:55:0,
                 from ../src/njsCommon.cpp:52:
/home/ajung/.cache/node-gyp/12.13.0/include/node/v8.h:21:18: fatal error: memory: No such file or directory
 #include <memory>
                  ^
compilation terminated.
gmake: *** [oracledb.target.mk:166: Release/obj.target/oracledb/src/njsCommon.o] Error 1
gmake: Leaving directory '/home/ajung/nodedemo-oradb-3.1.2/node_modules/oracledb/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/node-v12.13.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System AIX 7.1
gyp ERR! command "/opt/node/node-v12.13.0-aix-ppc64/bin/node" "/opt/node/node-v12.13.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ajung/nodedemo-oradb-3.1.2/node_modules/oracledb
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```
I've tried several other sql statements, too. All worked fine on Linux, but ran into this NJS-024 error when a where condition was defined. No matter how many rows are returned or if the condition is supplied through a bind variable or not.

**Comment by anthony-tuininga** [comment]
I have discovered the source of the issue. AIX returns NULL when asked to allocate zero bytes. Linux returns a non-NULL pointer. This patch eliminates this particular issue, but there may be others -- will look into it futher!

```
diff --git a/src/njsConnection.c b/src/njsConnection.c
index a68bddc1..8d623384 100644
--- a/src/njsConnection.c
+++ b/src/njsConnection.c
@@ -1873,7 +1873,8 @@ static bool njsConnection_initBindVars(njsBaton *baton, napi_env env,
     njsVariable *var;
     uint32_t i;
 
-    // determine the numbe of bind variables
+    // determine the number of bind variables; if none are provided, nothing
+    // further needs to be done
     if (bindNames) {
         NJS_CHECK_NAPI(env, napi_get_array_length(env, bindNames,
                 &baton->numBindVars))
@@ -1881,6 +1882,8 @@ static bool njsConnection_initBindVars(njsBaton *baton, napi_env env,
         NJS_CHECK_NAPI(env, napi_get_array_length(env, binds,
                 &baton->numBindVars))
     }
+    if (baton->numBindVars == 0)
+        return true;

```

**Comment by anthony-tuininga** [comment]
FYI, I found a number of others and have resolved all of them. This will be included in 4.1 when it is released.

**Comment by jungand** [comment]
Christopher and Anthony, thank you very much for replying to this post.
This is wonderful news. Thank you for diving into this issue and for your fixes. I'm looking forward to see my stuff working on AIX with the new version. Could you already estimate when it will be available ?

**Comment by cjbj** [comment]
@jungand node-oracledb 4.1 is out with the memory allocation fixes for AIX.  Let us know how it goes.

**Comment by jungand** [comment]
Thank your very much. I can confirm that it works  correctly now.

**Comment by cjbj** [comment]
@jungand let us know what you create and use node-oracledb for.  Otherwise we may just think no one uses the driver!
