### ISSUE TITLE
Node Event Loop is not empty

### ISSUE THREAD

**Issue by sesteva** [oracle/node-oracledb#1174]
After the connection is closed, the event loop is not empty; therefore the process does not exit .
The code below successfully closes the connection. 
Any pointers on what is wrong on the code or what can be done as the next step to debug this?
Maybe a setTimeout o similar that needs to be cleared/unref?
I've looked into the code and I could only find those on the pool or stream related parts which Im not using as far as I understand.

platform darwin
version v12.3.1
arch x64
oracledb 4.0.1
Oracle 12.1

```
execute({ query, args = [] }) {
    let connection
    return new Promise(async (resolve, reject) => {
      try {
       connection = await oracledb.getConnection(dbConfig);
        if (connection) {
          const result = await connection.execute(query, args);
          resolve(result);
        }
        return resolve([]);
      } catch (error) {
        const payload = {
          error,
          code: "BILLING_EXECUTION"
        };
        Report.send(payload);
        reject("Could not fetch billing data");
      } finally {
        if (connection) {
          try {
            await connection.close();
          } catch (error) {
            const payload = {
              error,
              code: "BILLING_CLOSING_CONNECTION"
            };
            Report.send(payload);
          }
        }
      }
    });
  }
```

**Comment by dmcghan** [comment]
This is not a standalone test case. For example, `execute` is called from somewhere else and `Report.send` is defined somewhere else. Why do you think the driver is at fault here?

**Comment by danilohgds** [comment]
One concern which I have is the mixture between promise approach and async await style all within one block.

I would suggest to have the whole method flow rewritten in a proper concise way. connection.execute is both promise and await compliant, so no reason to have this approach mixture.

**Comment by sesteva** [comment]
Thank you both for your replies.

@danilohgds I originally wrote it with async/await only as it is my preferred way. Example on oracleDB show this mixed approach and so I wanted to provide the closest to the familiar approach. Anyway, with both syntax/combination methods the same problem arises.

@dmcghan This is the only execute I have on the expressJS server. Report.send is just a wrapper for console.log awaiting a future more elaborated implementation. The server does have another endpoint which has some logic. If I consume ONLY this other endpoint, when the process is killed,  the event loop is empty. If I consume ONLY the endpoint making the connection to the DB, when the process is killed, the event loop is not empty.

**Comment by cjbj** [comment]
@sesteva the [examples](https://github.com/oracle/node-oracledb/tree/master/examples) are not mixed.

The bottom line is: give us a complete, standalone, runnable testcase.  Include any necessary SQL to create data. And show us how you are telling that the event loop is not empty.  Thanks!

**Comment by dmcghan** [comment]
@sesteva 

> when the process is killed

What do you mean by that? How are you killing the process?


> the event loop is not empty

What do you mean by that? How do you know it's not empty?

**Comment by sesteva** [comment]
Here is the smallest setup to reproduce the issue.
[repo](https://github.com/sesteva/test-oracledb-event-loop)
Im using Docker image oracleinanutshell/oracle-xe-11g 

`yarn install`

**Scenario 1**
yarn start
Go the browser or POSTMAN and hit http://localhost:3000
You will get a Hello World response
Interrupt the process using Ctrl-C or CMD-C
Then do yarn start again. Do over...you should have no problem..

**Scenario 2**
yarn start
Go the browser or POSTMAN and hit http://localhost:3000
You will get a Hello World response
Go the browser or POSTMAN and hit http://localhost:3000/client
Interrupt the process using Ctrl-C or CMD-C
Then do yarn start again. 
You will get "Error: listen EADDRINUSE: address already in use :::3000"

Something keeps running and it only happens when using the oracledb module.
I'm completely opened to the possibility I'm missing something on my code.

My notes so far:
There is no error when closing the connection.
I've tried using the [wtfnode](https://www.npmjs.com/package/wtfnode) module to see if a socket, timer or something was hanging. I could not spot to the offender.

**Comment by cjbj** [comment]
For a web app, I'd expect to see a connection pool.  Look at how [webappawait.js](https://github.com/oracle/node-oracledb/blob/master/examples/webappawait.js) does it.  Dan has some other examples in one or more of his blog posts.

Since you're on a Mac, add `disable_oob=on` to your [sqlnet.ora](https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin) file,

**Comment by sesteva** [comment]
HI @cjbj The actual application is a graphql layer running on AWS lambda. I've tried both the single connection and the pool options using oracledb module directly and using Knex. 
The above issue still comes up on those setups.

I will use the disable_oob flag and report the results. 
Thanks!

**Comment by sesteva** [comment]
I've setup sqlnet.ora and executed the above-described scenarios 1 and 2 with the above-linked project.
Unfortunately, I'm still getting the same error Error: listen EADDRINUSE: address already in use :::3000 only after the DB path is called.

**Comment by cjbj** [comment]
Can you show exactly how you set up sqlnet.ora?  On my Mac, for day to day testing, I use `~/.sqlnet.ora` (with leading `.`) and don't set `TNS_ADMIN`.  

Go back to using a pool and make sure that interrupts invoke `pool.close()` and use an explicit 0 or greater drain time.

**Comment by sesteva** [comment]
Based on the docs, I've added sqlnet.ora to instantclient_18_1/network/admin
I've only added that flag
`disable_oob = on`

This is my tnsnames.ora
```
XE =
(DESCRIPTION=
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 49161)
  )
  (CONNECT_DATA =
    (SERVICE_NAME=xe)
  )
)
```

I'll setup the pooling in the test repo and report back.

**Comment by sesteva** [comment]
Here is the branch with the pool and using process SIGTERM  and SIGINIT to close the pool [repo](https://github.com/sesteva/test-oracledb-event-loop/tree/feat/pool)

Here is the branch with a single connection and using SIGTERM and SIGINIT to close the connection INSTEAD of doing it in the **finally** statement.
[repo](https://github.com/sesteva/test-oracledb-event-loop/tree/feat/singleconn)

In both cases the symptom is gone, the event loop seems to be empty after the connection is closed. We can restart without getting the error about the process still being active.

So what is the producing the symtom when we close the connection in the **finally** statement?

**Comment by cjbj** [comment]
Last time we looked at interrupt handling in Node.js it seemed to get in some rebroadcast loop.

I'm glad you have a solution.
