### ISSUE TITLE
Add function to retrieve connection pool statistics as an object

### ISSUE THREAD

**Issue by jalfonso** [oracle/node-oracledb#1176]
The current pool._logStats() functionality is great, but it would be nice if we could obtain the same metrics as an object rather than a console dump.  Use cases include display of statistics in a diagnostic web page and time-series usage analytics/monitoring.

**Comment by cjbj** [comment]
@jalfonso would you be able to fill in the [OCA](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md) and submit a pull request?

**Comment by cjbj** [comment]
@jalfonso how often do you gather stats?  Are they always enabled?  Have a look at https://github.com/oracle/node-oracledb/issues/1178 and let me know how/if the extra sampling would work for you.  If so, you could add it to any PR you create to return metrics as an object.

**Comment by jalfonso** [comment]
Thanks @cjbj.  I will look into the OCA.  

I am currently collecting pool statistics every 5 minutes in an app that always has stats enabled.  I am interested in your ideas for additional sampling metrics.

**Comment by cjbj** [comment]
@jalfonso I guess you are archiving the stats and can run time-series analysis on the values.  In this scenario the overhead of #1178 is something you don't need, or maybe don't even want.

https://github.com/oracle/node-oracledb/issues/839 is a request for a log4j compliant logging facility.  There's definitely room for node-oracledb improvement and for moving `_logStats()` out of the "_" prefixed namespace.

**Comment by cjbj** [comment]
A `getStatistics()` function landed in https://github.com/oracle/node-oracledb/commit/d4ca9840f5a443102c0bc71c843df9a450aace9b and will be in node-oracledb 5.2

**Comment by cjbj** [comment]
The pool stats were formally moved from a simple object used in  node-oracledb 5.2 into a [poolStatistics class](https://oracle.github.io/node-oracledb/doc/api.html#poolstatisticsclass) in node-oracledb 5.3.  (This got postponed from 5.2 because we needed to pin down a pesky bug prior to the 5.2 release)
