### ISSUE TITLE
Need Advise on Helpers class to create connection and execute query/Stored proc.

### ISSUE THREAD

**Issue by Rajanusa** [oracle/node-oracledb#1177]
1. Review the [user manual](https://oracle.github.io/node-oracledb/doc/api.html)

2. Describe the problem
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.
I develop node.js library that has helper class for oracle database access.
There is oracledb module and it has service which has method to create connection and execute the query. I could abstract query execution but could not abstract stored proc execution.
so the helpers class return connection to consumer and it can be used to execute stored proc.

This library would be used in Nestjs API app. so each request to API may execute stored proc / query through this helpers class. now I creating connection and executing and closing the connection. 

I think creating pool is best approach.
If create a pool on application load and close the pool on application is good idea right?
Please advise

3. Include a runnable Node.js script that shows the problem.
This is the helper class with 2 methods. One is to execute query and another one is to create connection return the same to consumer who can execute the stored proc and close the connection.

```ts

@Injectable()
export class OracleDBService {
  constructor(
    @Inject(ORACLE_DB_OPTIONS)
    private readonly oracleDbOptions: OracleDBOptions[],
  ) {}

  async executeQuery(
    dbName: string,
    query: string,
    bindValue: Array<any> = [],
  ) {
    let localConnection: any;
    try {
      let oracleDbOption = this.oracleDbOptions.filter(x => x.name == dbName);
      if (!oracleDbOption) {
        throw Error('Connection string does not exist');
      }
      let localConnection = await oracledb.getConnection({
        user: oracleDbOption[0].user,
        password: oracleDbOption[0].password,
        connectString: oracleDbOption[0].connectString,
      });
      const result = await localConnection.execute(query, bindValue);
      await localConnection.close();
      return result;
    } finally {
      if (localConnection) {
        try {
          await localConnection.close();
          console.log();
        } catch (err) {
          console.log('Error when closing the database connection: ', err);
        }
      }
    }
  }

  async getConnection(dbName: string) {
    let oracleDbOption = this.oracleDbOptions.filter(x => x.name == dbName);
    if (!oracleDbOption) {
      throw Error('Connection string does not exist');
    }

    let localConnection = await oracledb.getConnection({
      user: oracleDbOption[0].user,
      password: oracleDbOption[0].password,
      connectString: oracleDbOption[0].connectString,
    });

    return localConnection;
  }
}
```
Include all SQL needed to create the database schema.

The more details you give, the more we can help.

4. Run node and show the output of:

```ts
process.platform 				: "win32"
process.version				: "v12.10.0"
process.arch					: "x64"
require('oracledb').versionString 	: "4.0.1"
```

Please advise whether I can create pool on constructor of this class and can close it when application close.

If I create a pool, will it maintain a connection to database, just a pool is created for concurrent user to execute the script. when executing the query/stored proc it connect to database.

5. What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by cjbj** [comment]
Without giving specific advice on your implementation, you almost certainly want to use a connection pool if you are creating a long-lived service.  By definition pools keep connections open, though the pool can grow or shrink.  Read the [manual](https://oracle.github.io/node-oracledb/doc/api.html#connpooling).  You should try and gracefully close the pool when the app shuts down.  The doc discusses this a bit.

**Comment by Rajanusa** [comment]
Please confirm my understanding 
if I create pool when nodejs apps starts and close the pool when the nodejs process exist, It just create pool and does not have connection to database right?
What is actually happen when we create pool and when we call get pool.getConnection() 
How do find optimum pool size?

My app use this pool for query dashboard and admin related purpose. so when loading the app it may have many query and subsequently it may execute based on user action.

if I create pool on the app start and close the pool on app exist good?

**Comment by cjbj** [comment]
> if I create pool when nodejs apps starts and close the pool when the nodejs process exist, It just create pool and does not have connection to database right?

When you create the pool it will have [`poolMin`](https://oracle.github.io/node-oracledb/doc/api.html#propdbpoolmin) connections open all the time.  You can set it to 0 if you really want, but this would not be common.

When you close the pool, those connections will be closed.

> 
> What is actually happen when we create pool and when we call get pool.getConnection()

Refer to the [extensive documentation](https://oracle.github.io/node-oracledb/doc/api.html#connpooling).  Also check the [examples](https://github.com/oracle/node-oracledb/tree/master/examples).

> How do find optimum pool size?

You can assess how many connections your database can handle, and your can monitor the pool statistics in node-oracledb, see the documentation [Connection Pool Sizing](https://oracle.github.io/node-oracledb/doc/api.html#conpoolsizing).  Also see  https://github.com/oracle/node-oracledb/issues/1178.

> 
> My app use this pool for query dashboard and admin related purpose. so when loading the app it may have many query and subsequently it may execute based on user action.
> 
> if I create pool on the app start and close the pool on app exist good?

Yes.  From the documentation: "Generally applications will create a pool once as part of initialization. After an application finishes using a connection pool, it should release all connections and terminate the connection pool by calling the pool.close() method."

> 
> when ever anywhere need to execute query can get connection and execute query
> is this good design.

Yes

> 
> or
> For each query execution/ stored proc , create pool and get connection and execute query and close the connection and pool is right?

Don't do this.

Read the documentation and let us know if you have any questions about it.

**Comment by cjbj** [comment]
closing - no update
