### ISSUE TITLE
Wrong binds if property in object have another order

### ISSUE THREAD

**Issue by mynoheart** [oracle/node-oracledb#118]
In documentation be example:
```sql
connection.execute(
   "UPDATE mytab SET name = :name "
 + "WHERE id = :id "
 + "RETURNING id, name INTO :rid, :rname",
  {
    id:    1001,
    name:  "Krishna",
    rid:   { type: oracledb.NUMBER, dir: oracledb.BIND_OUT },
    rname: { type: oracledb.STRING, dir: oracledb.BIND_OUT }
  },
  function(err, result)
  {
    if (err)
    {
      console.error(err);
      return;
    }
    console.log(result.outBinds);
  });
```

In query ```:name``` before ```:id```, but in bind object versa. Then bindings to be as:
```:name``` <<< 10001 and ```:id``` <<< "Krishna".

**Comment by dmcghan** [comment]
@mynoheart I ran a test using your code and things worked just fine. The order of the binds should not matter when using the object syntax.

How are you confirming that things are not working? Is it that the result.outBinds is undefined? If that's the case then you are probably on an older version of  node-oracledb. RETURNING INTO was added in version 0.5.0. Please confirm your at that version or later.

**Comment by mynoheart** [comment]
Thanks for quick reply.
I'm sorry. I have error when build query and wrong interpret error from Oracle.
Issue to be close.
