### ISSUE TITLE
How can i use parallel requests to DB?

### ISSUE THREAD

**Issue by urzt** [oracle/node-oracledb#1180]
Hello,
how can i use many parallel requests to DB? When i try it i have errors like:
```
NJS-003: invalid connection
```
```
NJS-018: invalid ResultSet
```
(it cant close connection (because it was closed by other request))

I tried to use pool of connections (like at [this article](https://jsao.io/2018/03/creating-a-rest-api-database-basics/)) for resovle this problem, but it did not help.

My code like there https://jsao.io/2018/03/creating-a-rest-api-database-basics/

Thnx

**Comment by dmcghan** [comment]
What do you mean by "many parallel requests"? Are you using a pool? You said you "tried" one, but it didn't help. You should still be using one!

The errors you're showing don't have to do with "parallel requests", per se. They are more likely related to the way you've written the code (timing issues). Please show us the code that is producing the errors.

**Comment by cjbj** [comment]
Closing - no update
