### ISSUE TITLE
NJS-005: invalid value for parameter2 with queries without bind parameters

### ISSUE THREAD

**Issue by stephan-wolf-ais** [oracle/node-oracledb#1185]
Using a query without binding parameters can result in error NJS-005. 

The reason ist that somtimes the empty values are treated as string in javascript -> error or as an empty array -> success. 

We fixed t his temporary checking the type of binding values parameter a2 in connection.js:90 and assigning and empty array if the type other than array.

Callstack:
Dec 09 10:59:18 9PB9P42 Node-RED[21642]: 9 Dec 10:59:18 - [error] [oracledb:c29d439c.d9ef68] Error: NJS-005: invalid value for parameter 2
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at Object.assert (/home/admin/.node-red/node_modules/oracledb/lib/util.js:146:11)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at Connection.execute (/home/admin/.node-red/node_modules/oracledb/lib/connection.js:90:16)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at Connection.execute (/home/admin/.node-red/node_modules/oracledb/lib/util.js:185:19)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at OracleServer.node.query (/home/admin/.node-red/node_modules/node-red-contrib-oracledb-mod/lib/oracledb.js:305:33)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at OracleDb.<anonymous> (/home/admin/.node-red/node_modules/node-red-contrib-oracledb-mod/lib/oracledb.js:94:25)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at OracleDb.emit (events.js:210:5)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at OracleDb.Node.receive (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at FunctionNode.Node.send (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:224:14)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at sendResults (/usr/local/lib/node_modules/node-red/node_modules/@node-red/nodes/core/core/80-function.js:52:18)
Dec 09 10:59:18 9PB9P42 Node-RED[21642]:     at FunctionNode.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/@node-red/nodes/core/core/80-function.js:231:21)

**Comment by anthony-tuininga** [comment]
Can you provide an example? That way we don't have to try to guess what you are trying to do!

**Comment by stephan-wolf-ais** [comment]
Hello, We found out that the bug is in the calling module. Sorry for that. We can close it here and I will file a bug in the correct module
