### ISSUE TITLE
How to 'describe' pl/sql procedures and packages ?

### ISSUE THREAD

**Issue by jungand** [oracle/node-oracledb#1187]
I'm looking for a way to find out the metadata of a pl/sql procedure or function, either standalone or as part of a package. I have to dynamically create the bind variables and have to find out their names, types and direction. 
I was hoping that something similar to sqlplus' describe command or OCIDescribeAny() was available. In the docs I've seen getDbObjectClass() and getStatementInfo() but I wasn't sure if these calls can be used for my purposes. At least none of them brought the results I was looking for.

```
const result = await connection.execute(
      `BEGIN
         no_proc(:i, :io, :o);
       END;`,
      {
        i:  'Chris',  // Bind type is determined from the data.  Default direction is BIND_IN
        io: { val: 'Jones', dir: oracledb.BIND_INOUT },
        o:  { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }
      }
    ); 
```
Referring to your exampIe code, I wanted to 'describe' no_proc() or bla_pkg.no_proc() in order to fetch enough information to dynamically generate the parameter list and the bind args. 
My code gets a fully qualified string ("begin bla_pkg.no_proc('arg1', 11); end;") as input and i have transform this into something I can feed to execute().

I'm running node-oracledb (4.1) on AIX7, node.js Version 12.13, Oracle 11.2.0.4

**Comment by cjbj** [comment]
Thanks for the clear detail.

Try queries like:
```
select argument_name, data_type, in_out from user_arguments where object_name = 'MYPROC';
```

I don't really want to expose `OCIDescribeAny()` in node-oracledb.  (i) It's info is limited, (ii) you'd still need to explicitly extract the package.procedure name from your string (iii) there is still a round-trip (iv) I'm not sure there is enough demand for yet-another-method, and (v) node-oracledb apps can customize a query from views like `(user|all|dba)_arguments`, `(user|all|dba)_procedures` etc to get precisely the info needed.

Convince me of the need for a new method!

**Comment by sosoba** [comment]
> 
> 
> Thanks for the clear detail.
> 
> Try queries like:
> 
> ```
> select argument_name, data_type, in_out from user_arguments where object_name = 'MYPROC';
> ```
> 

My suggestion:
```sql
    select * 
      from all_procedures p
left  join all_arguments a on a.object_id=p.object_id and a.subprogram_id=p.subprogram_id and a.overload=p.overload
```
Because procedures without arguments has no records inside `user|all|db_procedures`.

**Comment by jungand** [comment]
Thank you very much, guys, for your suggestions. Looks like I was so focused getting this done with oracledb that I've simply overlooked the most obvious approach. I will continue with fetching meta data from these views.
@cjbj I agree that at least for finding procedure arguments there's no need for a new method.

**Comment by cjbj** [comment]
Thank you all.  I'll close this now.
