### ISSUE TITLE
committed statements on pooled connection are intermittently rolled back

### ISSUE THREAD

**Issue by saschamonteiro** [oracle/node-oracledb#1188]
a connection pool with 64 connections  
logs show
Attempting to execute INSERT INTO ...
1 insert statements to execute
All insert statements were successful: [{"rowsAffected":1}]
Commit successful

But the record was NOT in the DB, even though Commit was successful,
all was fine without connection pool, so suspect there may be something there,
but need to know if I am not doing something wrong here
after enabling autoCommit there were no issues anymore, but then we can't rollback if there are multiple statements
oracle.autoCommit = true

```
const oracle = require('oracledb')
const doExecute = (conf, statements) => {
        return new Promise( (accept, reject) => {
            if(statements && statements.length > 0) {
                oracle.getConnection((err, conn) => {
                    if(err) {
                        reject(`Could not get connection to database: ${err}`)
                    }
                    else {
                        const promises = []
                        for(let v of statements) {
                            promises.push( new Promise( (ok3, err3) => {
                                log.verbose(`Attempting to execute ${v}`)
                                conn.execute(v).then( ok1 => {
                                    ok3(ok1)
                                }, err1 => {
                                    log.verbose(`Could not execute ${v}: ${err1}`)
                                    err3(err1)
                                })
                            }))
                        }

                        log.verbose(`${promises.length} insert statements to execute`)
                        Promise.all(promises).then( ok => {
                            log.verbose(`All insert statements were successful: ${JSON.stringify(ok)}`)
                            conn.commit().then( ok1 => {
                                log.verbose('Commit successful')
                                // closeConnection(conn) ;
                                accept(ok1)
                            }, err1 => {
                                // closeConnection(conn) ;
                                reject(`Commit failed: ${err1}`)
                            })
                        }, err => {
                            log.verbose(`Not all insert statements were successful. Rolling back: ${err}`)
                            conn.rollback().then( ok1 => {
                                log.verbose(`Rollback completed successfully: ${ok1}`)
                                // closeConnection(conn) ;
                                reject(err)
                            }, err1 => {
                                log.error(`Error while attempting to roll back: ${err1}`)
                                // closeConnection(conn) ;
                                reject(err)
                            })
                        }).finally(() => {
                            closeConnection(conn) ;
                        })
                    }
                })
            }
            else {
                reject("No statements found to execute")
            }
        })
    }
```

```
> process.platform
'linux'
> process.version
'v10.16.0'
> process.arch
'x64'
> require('oracledb').versionString
'4.0.1'
> require('oracledb').oracleClientVersionString
'11.2.0.2.0'
```

5. What is your Oracle Database version?
11g XE

**Comment by cjbj** [comment]
My first suggestion would be to remove all uses of `Promise.all()`. It's not doing what you think, and is bound to lead to concurrency problems - which it sounds like you are experiencing.  See @dmcghan's point 3 in https://github.com/oracle/node-oracledb/issues/1186#issuecomment-565109120

The next version of the documentation will explicitly mention `Promise.all` in the section https://oracle.github.io/node-oracledb/doc/api.html#numberofthreads

My second suggestion would be to use the async/await style of programming, see all the current [examples](https://github.com/oracle/node-oracledb/tree/master/examples) which will make the code flow easier to understand and get right.

If your code is ever intended for inserting multiple rows into one table, then use [`executeMany()` ](https://oracle.github.io/node-oracledb/doc/api.html#executemany)instead of repeated `execute()` calls.  The former will be a _lot_ faster.

**Comment by saschamonteiro** [comment]
thanks, I'll have a look, we are not planning multiple rows into one table, but rather a transaction of records in different tables, if one fails we need to roll back, if all successful commit

**Comment by cjbj** [comment]
Closing - no update
