### ISSUE TITLE
connection.close() hangs without an error.

### ISSUE THREAD

**Issue by chaeron** [oracle/node-oracledb#1191]
Using oracledb v4.1 (latest).  Oracle InstantClient BasicLite v19.5 (again latest version). Oracle db version 11.1 (yeah...I know...old version of Oracle, but we have to be compatible with a client environment). Running the client on an Ubuntu 18.04 Linux system.  DBMS is remote on a WinServer platform.

We open the connection fine. Do a bunch of reads on many tables using result sets. Always close the result set after we're done with the specific table reads. We're using only async/await on all oracle function calls.

No updates or inserts ever. Just reads.

When we do an await connection.close() at the end, it hangs forever without throwing any errors.

Any ideas on how to mitigate this or what might be causing it?

Thanks!

**Comment by cjbj** [comment]
You'll need to give a testcase, since there is a good chance it's a timing issue in your code.  Also check your sqlnet.ora - Maybe `DISABLE_OOB=ON` will change the behavior, perhaps to uncover a latent error.  There are few reference to this option in the node-oracledb manual.

**Comment by cjbj** [comment]
Closing - no update
