### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by davidrtpereira** [oracle/node-oracledb#1193]
Error executing query on table with column with data type CLOB.

```
process.version
'v12.14.0'

process.arch
'x64'

require('oracledb').versionString
'4.1.0'

require('oracledb').oracleClientVersionString
'11.2.0.4.0'
```

What is your Oracle Database version?
11G

Table Structure SQL

```
CREATE TABLE "CAPTURA"."CAPTURA_XML" 
   (	"CHNFE" VARCHAR2(44 BYTE), 
	"XML" CLOB NOT NULL ENABLE, 
	 PRIMARY KEY ("CHNFE"))
```

Error:

![image](https://user-images.githubusercontent.com/20539715/71599095-38367280-2b28-11ea-8512-d5b1d06a941d.png)

console.log **stream** variable:

https://gist.github.com/davidrtpereira/3f6b4e152d898018dcc15974858af757

Modificated lines 340 and 349 to node_modules\knex\lib\dialects\oracledb\index.js, returned success in query:
https://gist.github.com/davidrtpereira/d5a66fd53becc443fd291f54f8963f37

![image](https://user-images.githubusercontent.com/20539715/71599756-ef33ed80-2b2a-11ea-9950-4a477e87641b.png)

**Comment by cjbj** [comment]
Thanks for sharing.  It seems you are reporting an issue in Knex?  The node-oracledb project is separate from Knex.  Do you want me to transfer the issue to the project looking after your Knex module? Did you install vanilla Knex or a fork?

**Comment by davidrtpereira** [comment]
@cjbj  you are right. In fact this is a problem within knex. I appreciate the willingness to transfer the issue, but you can let me do it.

Thank you!
