### ISSUE TITLE
Connection to Oracle Cloud ATP instance

### ISSUE THREAD

**Issue by cheslyn** [oracle/node-oracledb#1199]
Hello,

I currently have a 12c client setup for Node Db that works perfect.

Am now trying to connect to an OCI ATP Database. (Autonomous db)
Followed the documentation on 
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionadb

Query.
Where do I place the content of the files in the wallet.zip ?
mainly the cwallet.sso ?

I appended the tnsnames.ora and sqlnet.ora content to the 12.c relevent tnsnames and sqlnet. 

Currently when I try to establish a connection to the ATP instance I get a 
[Error: ORA-28759: failure to open file] { errorNum: 28759, offset: 0 }

Note: The ATP connection works fine from SqlDeveloper using the wallet file. 

Would appreciate any pointers on this. 

Thanks
Cheslyn

**Comment by cjbj** [comment]
From cloud wallets, C-based apps like node-oracledb only need the `cwallet.sso`, `sqlnet.ora`, and `tnsnames.ora` files.  The rest can be deleted.  These are typically all placed in the same directory, but `cwallet.sso` can be put elsewhere. Don't forget to keep `cwallet.sso` secure.

The common gotcha is that, depending where `cwallet.sso` is, you need to edit `sqlnet.ora` to change the wallet location path.  Details matter, so if you want more help you'll have to share exactly what you've got & done.

Node-oracledb doc about network configuration file placement is in [Optional Oracle Net Configuration](https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin).  

Here's the ATP documentation: [Connect with Python, Node.js, and other Scripting Languages](https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/connecting-nodejs.html#GUID-AB1E323A-65B9-47C4-840B-EC3453F3AD53).

Personally, I think it's easiest to unzip the wallet and copy the files to your `/whatever/instantclient_XX_Y/network/admin` directory (if you are using Instant Client).  This way you don't need to edit `sqlnet.ora` and you don't need to set TNS_ADMIN.

**Comment by cjbj** [comment]
LOL.  I forgot I wrote this up as "official" doc recently: [Connecting to Oracle Autonomous Database](https://oracle.github.io/node-oracledb/doc/api.html#connectionadb).  (I can see room for improvements in the doc)

**Comment by cjbj** [comment]
@cheslyn I updated the doc section to mention the mapping between sqlnet.ora and the directory containing the cwallet.sso.

**Comment by cheslyn** [comment]
Thanks a lot.
It worked, appreciate the prompt support. 
-Cheslyn
