### ISSUE TITLE
null varchar type cause all to be null

### ISSUE THREAD

**Issue by b2dac** [oracle/node-oracledb#12]
VARCHAR2 columns that have one or more null values cause the entire column to be null.

As a way around this, I was able to use an isnull(column, '') which will cause things to work properly, meaning the data that is null will be blank and the data that has a value is there.

**Comment by cjbj** [comment]
Got a testcase?

**Comment by b2dac** [comment]
In the process of creating the test case, I wanted to limit the amount of data to as few rows as possible. While doing that, I retested the query and the issue would not occur. I will try to narrow this down and once I do I will create a testcase.

**Comment by b2dac** [comment]
Sorry, but I'm gonna have to close this issue for now because I cannot reproduce it. Yesterday, it was consistently happening and now it's not. The only thing that has changed, since yesterday, is that there are now additional rows that users have inputted and other rows that were altered. But even while excluding these additions the issue does not occur. Perhaps it has to do with an altered row. Regardless, I will reopen it if I can narrow it down. Sorry for the inconvenience.

**Comment by cjbj** [comment]
No problems.  Keep an eye out for it.
