### ISSUE TITLE
bindDefs not working with oracledb.VARCHAR2 and oracledb.INTEGER

### ISSUE THREAD

**Issue by loupduqc** [oracle/node-oracledb#1203]
I have a bind statement that works with a connection.execute with the data and the bind together, but when trying to optimize it to a executeMany, the use of bindDefs in the options makes it so it doesn't work.

Working bind statement for the execute:
```
{
	TypeCarte: { val: this.TypeCarte, dir: oracledb.BIND_IN, type: oracledb.VARCHAR2 },
	CardNumber: { val: this.CardNumber, dir: oracledb.BIND_IN, type: oracledb.INTEGER },
	ExpMonth: { val: this.ExpMonth, dir: oracledb.BIND_IN, type: oracledb.INTEGER },
	ExpYear: { val: this.ExpYear, dir: oracledb.BIND_IN, type: oracledb.INTEGER },
	Id: { dir: oracledb.BIND_OUT, type: oracledb.INTEGER }
 }
````

Example of it not working in a bindDefs:
```
const bind = informationCredits.map(info => info.ToSqlBind())
const id = await connection.executeMany(
    insertInformationCreditSQL,
    bind, 
    { 
        autoCommit: true,
        bindDefs: {                  
            TypeCarte: {type: oracledb.VARCHAR2, maxSize: 20 },
            CardNumber: {type: oracledb.INTEGER },
            ExpMonth: {type: oracledb.INTEGER },
            ExpYear: {type: oracledb.INTEGER },
            Id: {dir: oracledb.BIND_OUT, type: oracledb.INTEGER }
        }
    }
);
```

It return the following error:

> Error: NJS-060: type must be specified for bind "TypeCarte"

And when I change TypeCarte to the type String it gives

> Error: NJS-060: type must be specified for bind "CardNumber"

It will stop complaining about CardNumber type if I set it to NUMBER
But at that point, the query just doesn't work since there's a type miss match.

**Comment by cjbj** [comment]
Those constants are not predefined.

See https://oracle.github.io/node-oracledb/doc/api.html#executebindparamtype

**Comment by cjbj** [comment]
I should note that the table I linked to is for node-oracledb 4.2, but you've had one day to upgrade already, right?  With older versions of node-oracledb you will want to stick with this set of constants: https://oracle.github.io/node-oracledb/doc/api.html#oracledbconstantsnodbtype
