### ISSUE TITLE
JavaScript and Oracle Database Office Hours - Feb 4

### ISSUE THREAD

**Issue by OsBlaineOra** [oracle/node-oracledb#1206]
The next JavaScript and Oracle Database Office Hours (for 30 minutes!) will be on February 4, 2020 at 21:00 - 21:30 UTC

Join the webinar to find out "What's new in node-oracledb 4.2 and how it matters to you" then you can ask us your node-oracledb questions.

https://asktom.oracle.com/pls/apex/asktom.search?oh=727

**Comment by cjbj** [comment]
The Office Hours recording is now available at https://asktom.oracle.com/pls/apex/asktom.search?oh=6906.
