### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/oracle_db - Not found, npm ERR! 404  'oracle_db@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by gellban** [oracle/node-oracledb#1207]
# Do these first

- Review and follow the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html)

- If you have a `DPI-1047`, `DPI-1050` or `DPI-1072` error, review both the above again before opening an issue.

# Answer the following questions

1. Describe the problem and show the error you have.
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.

C:>npm install oracle_db
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/oracle_db - Not found
npm ERR! 404
npm ERR! 404  'oracle_db@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:...\2020-01-28T17_16_59_769Z-debug.log

#my PC installation
#download and install node.jsv12.14.1:
it will upgrade your old version
#install all required build. you may get error 404. just ignore it and go to the next step:
npm install oracle_db 
#install from source code:
https://oracle.github.io/node-oracledb/INSTALL.html#instwin:
npm install https://github.com/oracle/node-oracledb/releases/download/v4.1.0/oracledb-src-4.1.0.tgz

- Review the [troubleshooting tips](https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting)

===========================
2. What Node.js version are you using?  Run node and show the output of:
Node V12.14.1
```
process.platform
process.version
process.arch
require('oracledb').versionString
require('oracledb').oracleClientVersionString
```

> process.platform
'win32'
> process.version
'v12.14.1'
> process.arch
'x64'
> require('oracledb').versionString
'4.1.0'
> require('oracledb').oracleClientVersionString
'19.5.0.0.0'
>      

3. Are you installing into vanilla Node.js, or using something like Electron?
No
4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
64
5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.
C:\instantclient_19_5
6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
there are no ORACLE_HOME, ORACLE_BASE

**Comment by dmcghan** [comment]
There's no underscore. It's just:

```
npm install oracledb
```

**Comment by gellban** [comment]
Thank you!
