### ISSUE TITLE
How to connect to remote oracle database through LDAP ?

### ISSUE THREAD

**Issue by Chandra01B** [oracle/node-oracledb#1212]
Problem : I am trying to connect to remote Oracle Database through LDAP on Windows 10 machine. But node-oracledb driver doesn't recognize below connection string format.

`connectString: "ldap://[ldap server name]:port/[service name],[ldap context]"`

I also tried few other ldap formats. But here is the error I am getting.

`Error: ORA-12538: TNS: no such protocol adapter`

I am able to connect to a remote oracle database through LDAP from SQL Developer with following JDBC URL format:

`jdbc:oracle:thin:@ldap://[LDAP Server]:[port]/[DB Service Name],[LDAP context]`

Also checked this link. Setup seems to be fairly complicated and hard to understand.   
https://stackoverflow.com/questions/31994159/how-do-you-connect-to-an-ldap-server-using-node-oracledb

Lot of changes occurred since then and new versions have been released.Is there a simpler set up to make node-oracledb to talk to ldap ? 

I did try setting up ldap.ora and sqlnet.ora and placed them in $oracle_instant_client_home\network\admin directory. But I am not sure what to pass for **connectString** in db-config.js ?

sqlnet.ora :
```
# sqlnet.ora
# Place this file in the network/admin subdirectory or your 
# $ORACLE_HOME location.
NAMES.DIRECTORY_PATH = (LDAP)
```
ldap.ora
```
# ldap.ora
# Place this file in the network/admin subdirectory or your 
# $ORACLE_HOME location.
DIRECTORY_SERVERS = (your-server.your-organization:389:636)
DEFAULT_ADMIN_CONTEXT = "ldap-ou-designation"
DIRECTORY_SERVER_TYPE = ad
```

Node.js version : 10.15
Oracle Instant Client version: Instant Client Win64 19.5
node-oracledb : 3.1.2

**Comment by cjbj** [comment]
There have been no changes to the underlying Oracle client libraries that I know of, so the best answer from me is still the one in that stackoverflow post.

@onmp may know more.

**Comment by Chandra01B** [comment]
Thanks Chris. I resolved my issue. Here is what I did. 

1. ldap.ora file

```
# ldap.ora
# Place this file in the network/admin subdirectory or your 
# $ORACLE_HOME location.
DIRECTORY_SERVERS = (your-server.your-organization:389:636)
DEFAULT_ADMIN_CONTEXT = "ldap-ou-designation"
DIRECTORY_SERVER_TYPE = OID
```
2. sqlnet.ora

```
# sqlnet.ora
# Place this file in the network/admin subdirectory or your 
# $ORACLE_HOME location.
SQLNET.AUTHENTICATION_SERVICES=(NTS)
NAMES.DIRECTORY_PATH = (LDAP)
```
3. Placed both ldap.ora and sqlnet.ora in $oracle_instant_client_home\network\admin. When I downloaded instant client I didn't have network\admin folder so I created it.
4. Created an environment variable TNS_ADMIN=$oracle_instant_client_home\network\admin.
5. dbconfig.ora

```
module.exports = {
  user          : process.env.NODE_ORACLEDB_USER,
  password      : process.env.NODE_ORACLEDB_PASSWORD,
  connectString : "[ORACLE_DB_SERVICE_NAME]",
};
```
I was missing  TNS_ADMIN environment variable. That's why my set up didn't work before. Like Chris J mentioned in multiple places, node-oracledb is an OCI client just like SQL*Plus. So I followed same configuration as my database team used for connecting to database.

**Comment by cjbj** [comment]
@Chandra01B thanks for sharing!  I'm glad you got it going.
