### ISSUE TITLE
BUG Random number format 2.3000000000000003

### ISSUE THREAD

**Issue by andriusphoto** [oracle/node-oracledb#1213]
Hi,
when we try to pass the number 2.3 to the database function, the function gets 2.3000000000000003, so it doesn't happen with all the numbers, if we send 2.2 then we get 2.2

```
  public execute(query: string, bindParams: oracledb.BindParameters = {}, options: oracledb.ExecuteOptions = {}) {
    return this._connection.execute(query, bindParams, options)
  }
```

NLS_DATE_FORMAT=YYYY-MM-DD HH24:MI:SS;
NLS_LANG=LITHUANIAN_LITHUANIA.BLT8MSWIN1257;
NLS_NUMERIC_CHARACTERS=.,
ORA_SDTZ=UTC;

process.platform = linux
process.version =  v12.16.1
process.arch = x64
require('oracledb').versionString 4.2
require('oracledb').oracleClientVersionString 18.3.0.0.0

 Oracle Database version: Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

**Comment by danilohgds** [comment]
I dont think this is a big... most likely a mishandling with floating points...are you using any libraries like bignumber.js?

**Comment by anthony-tuininga** [comment]
Agreed. This is not a bug. See issue #793 for more information.

**Comment by andriusphoto** [comment]
Thank you!
