### ISSUE TITLE
“libclntsh.dylib.19.1” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by prudrara241** [oracle/node-oracledb#1216]
I have gone through the instructions to install node-oracledb for MacOS

- Review and follow the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html)

When i run my node, i am getting this “libclntsh.dylib.19.1” cannot be opened because the developer cannot be verified.

Any pointer on how to resolve/debug this.

**Comment by cjbj** [comment]
You're on Catalina?  Technically not supported :(  I'm avoiding upgrading.  See https://github.com/oracle/python-cx_Oracle/issues/341

**Comment by prudrara241** [comment]
Yes, i am on Catalina OS.

**Comment by cjbj** [comment]
OK.  See above post.  Good luck!

**Comment by cjbj** [comment]
@fsconrado if you want to connect to Oracle DB 10.2 you would need to be using Oracle Client libraries 11.2 or 12.1.

**Comment by redheadedstep** [comment]
For anyone with this issue, there is a simple fix outlined at this url, but I'll document it here.  Basically all the files in the instantclient_19_* folder are flagged with an extra attribute called "com.apple.quarantine".

https://oraontap.blogspot.com/2020/01/mac-os-x-catalina-and-oracle-instant.html

Here is the fix:

1. Some of the files ship without WRITE rights so we will need to fix that first:
```
$ cd instantclient_19_8
$ chmod u+w *
```

2. Next we will remove the extra attribute:
```
$ cd ..
$ xattr -r -d -s com.apple.quarantine instantclient_19_8
```

3. To test that this worked, simply run sqlplus or, in my case with the oci8 php extension, run the `php -i` command
```
$ php -i | grep "oci"
$ sqlplus
```

I tested this on OS Ventura and Catalina
