### ISSUE TITLE
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found".

### ISSUE THREAD

**Issue by DiogoSimaoMadeira** [oracle/node-oracledb#1218]
# Answer the following questions

1. Describe the problem and show the error you have.
I am trying to connect a remote oracle data base and i am with the following error:
DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found".

I was checking the links and the documentation, but the problems continue.

2. What Node.js version are you using?  Run node and show the output of:
node version: v12.13.0
```
DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help\nNode-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html\nYou must have 64-bit Oracle client libraries in your PATH environment variable.\nIf you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from\nhttp://www.oracle.com/technetwork/topics/winx64soft-089540.html\nA Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.\n
```

3. Are you installing into vanilla Node.js, or using something like Electron?
Node.js

4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
64-bit

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.
C:\oracle\instantclient_19_5

6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).

**Comment by DiogoSimaoMadeira** [comment]
Some more information:
I am using the Windowns 10;
Instant Client it was installed with the command: npm install oracledb 
VS redistributable with vc_redist.x64.exe

**Comment by cjbj** [comment]
I'll need more detail: do you know what VS redistributable that was?  Can you open a terminal window, list the directory where Instant Client is installed, show us what PATH is set to, and then run Node.js?  Cut & paste and show us.

**Comment by arun290636** [comment]
@cjbj I| am facing the same problem . Error as below:

{ Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html


Steps:
OS- mac
Installed 'oracledb' npm package via npm install
When i run below code :
var oracledb = require('oracledb');
oracledb.getConnection(
  {
    user          : "qa",
    password      : "test",
    connectString : "ip/database"
  },
  function(err, connection)
  {
    if (err) { console.error(err); return; }
    connection.execute(
      "SELECT * FROM test "
    + "WHERE name = 'abc'",
      function(err, result)
      {
        if (err) { console.error(err); return; }
        console.log(result.rows);
      });
  });

below error is thrown
{ Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html

**Comment by cjbj** [comment]
@arun290636 you're on a mac, so the solution will be different.  Read https://oracle.github.io/node-oracledb/INSTALL.html#instosx and (when you get to Catalina) read https://github.com/oracle/node-oracledb/issues/1216.  If you still have problems, open a new issue instead of updating this Windows issue.

**Comment by DiogoSimaoMadeira** [comment]
@cjbj you are right!! It is working. Thank you for your support!

**Comment by RachelGanonNew** [comment]
hi I I'm facing the same issue , appreciate any help

**Comment by cjbj** [comment]
@RachelGanonNew Review https://oracle.github.io/node-oracledb/INSTALL.html#instosx and open a new issue with lots of detail if you still have problems.

**Comment by RachelGanonNew** [comment]
@cjbj thanks for the quick response 👍
