### ISSUE TITLE
UTF-8 For Thai leng

### ISSUE THREAD

**Issue by popzadid** [oracle/node-oracledb#122]
I Installing node-oracledb and i compile with it and it work's in English 
In case of insert data with REST API with json in application node is seeing Thai but after insert data is look like  เธฃเนเธงเธกเธเธฒเธฃเธเนเธฒ4 (ISO-8859-11) and UTF-8 is ร่วมการค้า4 did you have any idea to convert this to utf-8 than you  and my db is  NLS_LANG is AMERICAN_AMERICA.TH8TISASCII

**Comment by cjbj** [comment]
Do you need to set NLS_LANG to one of the UTF8 char sets?
Regardless, can you post a .js script that has the problem?  Give us the DB character set and the NLS_LANG setting(s) you tried.
Also see https://github.com/oracle/node-oracledb/issues/100 and https://github.com/oracle/node-oracledb/issues/62

**Comment by popzadid** [comment]
Thank for you replied It can't be edit NLS_LANG  to UTF-8 Because have a old data in use with  AMERICAN_AMERICA.TH8TISASCII  and i don't know what happen if i convert it to UTF-8 
and this 
a simple code
app.post('/api/addRerqester', function(req, res){
	var REQSTR_ID = req.body.REQSTR_ID;
	var REQSTR_NAME = req.body.REQSTR_NAME;

	var resultBuffer = encoding.convert(REQSTR_NAME, 'tis620');
	var buffer = legacy.encode(REQSTR_NAME, 'tis-620');
	console.log(buffer);
	oracledb.getConnection(
	{
		user          : dbConfig.user,
		password      : dbConfig.password,
		connectString : dbConfig.connectString
	},
	function(err, connection)
	{
		if (err) {
			console.error(err.message);
			return;
		}  

		connection.execute(
			"SELECT REQSTR_NAME FROM REQUESTER WHERE REQSTR_ID = 1",
			function(err, result)
			{
				if (err) { console.error(err.message); return; }
				js = result.rows;
				console.log(js);
				connection.execute(
					"INSERT INTO REQUESTER(REQSTR_ID,REQSTR_NAME,CREATE_DATE) VALUES (:REQSTR_ID, :REQSTR_NAME, :CREATE_DATE)",
					[11032, resultBuffer,reStirngDate(getdate)],
					{ autoCommit: true},
					function(err, result)
					{
						if (err) { console.error(err.message); return; }
						console.log("Rows inserted: " + result.rowsAffected);
						res.send(resultBuffer);
					});
			});
	});
	// doRelease(connection);
});

in code i try to convert my data (REQSTR_NAME ) to author format like TIS-620 , ISO-8859-11 but in database it save null data

**Comment by cjbj** [comment]
Check the various Oracle NLS references for how character set conversion might affect you. 

It would be really help to have a complete, standalone test.  What is the DB character set?  Can you give us some test data?

**Comment by cjbj** [comment]
We made some NLS changes in node-oracledb 1.0.
See https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md and
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#nls
Try it again with the new version.
