### ISSUE TITLE
error when query CLOB json

### ISSUE THREAD

**Issue by NgoDuy2197** [oracle/node-oracledb#1223]
hello 
i create DB Oracle 19c and table name is "s_inv" with a COlumn name is "doc" and  type is CLOB, i create "check (doc is json)" and run query below the OR condition is wrong. 1=1 but it's resolve ((1=1) or ... or ...) = false

![image](https://user-images.githubusercontent.com/46311410/75949314-6776b080-5ed8-11ea-92fa-558f1028df28.png)

select *
from s_inv a 
where
a.sec<>'njr9e9ngd9' 
and (
(1=1)
or (a.doc.root.sec='njr9e9ngd9')
or (a.doc.root.sec='omr36o6r43')
) order by id

**Comment by cjbj** [comment]
Please ask SQL questions at asktom.oracle.com or stackoverflow.com.   Thanks!
