### ISSUE TITLE
SQL*Plus core dump on AIX

### ISSUE THREAD

**Issue by jungand** [oracle/node-oracledb#1226]
After I was able to spend some time finishing my node-oracledb project on my DEV system I though I could just copy the entire stuff to a pre-PROD system where we don't have internet access.  nodejs, ~~installclient~~ instantclient, <project>/node_modules are exact copied of what I have on the DEV system. 

But even my first trivial test fails on the prod system

```
const oracledb = require('oracledb');

console.log("OS platform " + process.platform + ' on ' + process.arch);
console.log("nodejs version " + process.version);
console.log("oracledb version " + oracledb.versionString);
console.log("oracle client version " + oracledb.oracleClientVersionString);

const config = {
  user          : 'rcmtest',
  password      : 'rcm20191209',
  connectString : 'localhost/rcm'
};

async function get_data(id) {
  console.log('read data of userid ' + id);
  let conn;
  try {
    console.log('first lets get a connection');
    conn = await oracledb.getConnection(config);
    console.log('then execute the query');
    const result = await conn.execute(
      'select * from all_users where username = :id', [id]
    );
    console.log(result.rows[0]);
  } catch (err) {
    console.log(err);
  } finally {
    if (conn) {
       await conn.close();
    }
  }
}

get_data('BRKVIEW');
```

This output is created on DEV:
```
 $ LIBPATH=/applications/oracle/instantclient/instantclient_19_6 node t/firsttry.js
OS platform aix on ppc64
nodejs version v12.13.0
oracledb version 4.2.0
oracle client version 19.6.0.0.0
read data of userid BRKVIEW
first lets get a connection
then execute the query
[ 'BRKVIEW', 66, 2018-10-12T14:49:53.000Z ]
```

and this on pre-PROD
```
$ LIBPATH=/applications/oracle/instantclient/instantclient_19_6 node t/firsttry.js
OS platform aix on ppc64
nodejs version v12.13.0
oracledb version 4.2.0
Illegal instruction(coredump)
```

After spending hours of checking what might be different on these two machines I've come to my wit's end and turn to you masters to ask for a hint what else I could check or fix. 

I'm almost sure that this is not a problem of node-oracledb because sqlplus runs into this error, too, while it works well on the DEV server.

```
$ $LIBPATH/sqlplus ajung@localhost/rcm
Illegal instruction(coredump)
```
So even it's most probably not an issue with oracledb you might be able to point me in the right direction.

regards, 
Andreas

**Comment by cjbj** [comment]
Without firsthand AIX experience, my only guess would be a library clash.

Do you have other Oracle software on your machine?  Why don't you export LIBPATH?  I interpret what you said ('installclient') to mean Instant Client.  What other environment Oracle variables are set?

**Comment by jungand** [comment]
On both servers I have 11.2.0.4 installed with an database instance I wanted to connect to via ajung@localhost/rcm. I don't have any other ORACLE environment variables set. 
Of course, I have started with LIBPATH set as environment variable, which leads to the same result. But since I'm going start my application via inetd, setting LIBPATH in the prefix is a little bit closer to my target scenario. But It really doesn't make a difference here.

**Comment by cjbj** [comment]
When you copied binaries across did they get corrupted?  Did all sym links get recreated?

**Comment by jungand** [comment]
checked almost everything. Even every single file with cksum

**Comment by jungand** [comment]
Now I've downloaded an older version of instantclient and tried my test script against this version. And with instantclient_12_2 it WORKED !!
I guess somebody in the instantclient team would be interested in this issue.

**Comment by cjbj** [comment]
Did you happen to check the Oracle client install guide to see what OS was supported by 19.6, and what other requirements there were?

Instant Client is just a bundling of libraries from the DB, so the AIX porting team would be the ones interested - but they would need to know what your system was.

**Comment by jungand** [comment]
instantclient 19.3 and 19.6 worked well with sqlplus and oracledb on my DEV system which looks like this:
```
# prtconf
System Model: IBM,9119-MME
Machine Serial Number: 65A090D
Processor Type: PowerPC_POWER8
Processor Implementation Mode: POWER 8
Processor Version: PV_8_Compat
Number Of Processors: 2
Processor Clock Speed: 4024 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
LPAR Info: 20 tarcms
Memory Size: 12288 MB
Good Memory Size: 12288 MB
Platform Firmware level: SC860_138
Firmware Version: IBM,FW860.42 (SC860_138)
Console Login: enable
Auto Restart: true
Full Core: false
```
...and it crashes on the pre-PROD system
```
# prtconf
System Model: IBM,9117-MMA
Machine Serial Number: 657F0F0
Processor Type: PowerPC_POWER6
Processor Implementation Mode: POWER 6
Processor Version: PV_6_Compat
Number Of Processors: 1
Processor Clock Speed: 4208 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
LPAR Info: 24 drcm01
Memory Size: 8192 MB
Good Memory Size: 8192 MB
Platform Firmware level: EM350_108
Firmware Version: IBM,EM350_108
Console Login: enable
Auto Restart: true
Full Core: false
```

By examining the setup of both system I notice now that there's more difference than I thought (P6 vs P8). 
Anyway, I hope this helps to find the issue. 
I'd say this ticket can be closed since this was clearly not a problem with node-oracledb.
Thank you very much, cjbj

**Comment by kubo** [comment]
[Oracle 19c AIX client requires](https://docs.oracle.com/en/database/oracle/oracle-database/19/axcli/operating-system-checklist-for-oracle-database-on-ibm-aix-on-power-systems-64-bit.html#GUID-0A0691E3-7BC8-48F0-A189-7D978DDB7E45):
* AIX 7.1 Technology Level 5 Service Pack 1 (7100-05-01-1731) or later, 64-bit kernel
* AIX 7.2 Technology Level 2 Service Pack 1 (7200-02-01-1731) or later, 64-bit kernel

I guess that the pre-PROD system is older than the required OS versions. Could you run `oslevel -s` to print the OS information such as `7100-05-01-1731`?

**Comment by jungand** [comment]
surprisingly the DEV server is even older than the pre-PROD

DEV:
# oslevel -s
7100-00-10-1334

pre-PROD:
# oslevel -s
7100-04-05-1720

**Comment by kubo** [comment]
It is surprising. I thought that the core dump was caused by the OS version but it isn't correct.

The cause of illegal instruction may be what the message says. Oracle 19c client may use instructions for processors newer than POWER 6.
https://www.ibm.com/support/knowledgecenter/SSGH3R_16.1.0/com.ibm.xlcpp161.aix.doc/compiler_ref/opt_arch.html

**Comment by cjbj** [comment]
@kubo that could be right.  Oracle support Doc ID 2621030.1 says:

>         18c/19c Database/Client on AIX Installed successfully.
> 
>         But when executing the oracle utilities like: sqlplus,lsnrctl,expdp etc ,it fails with error:Illegal instruction
> 
>         This issue on Power 6 machine.
> 
>         /usr/sbin/prtconf
>         Processor Type: PowerPC_POWER6
>         Processor Implementation Mode: POWER 
> 
>         >./sqlplus
>         Illegal instruction
> 

There is a patch; the reference is bug 29591343.

**Comment by jungand** [comment]
I guess, using the 12.2 instantclient is the best option for me as it works well on both platforms and doesn't require installation of patches on PROD systems.
Thank you all for your support. I'm happy to understand the situation now and have an idea of how I can push my project forward. I think the ticket can be closed
