### ISSUE TITLE
How to kill close existing connection pool if second pool connection fails on startup

### ISSUE THREAD

**Issue by Enado95** [oracle/node-oracledb#1228]
Does `process.once('SIGTERM', closePoolAndExit).once('SIGINT', closePoolAndExit)`  handle database connection errors.I'm using two different connection pools like this:

```
const oracledb = require('oracledb')

const createFirstPool = async () => {
  try {
    await oracledb.createPool({
      user: process.env.first_DATABASE_USER,
      password: process.env.first_DATABASE_PASSWORD,
      connectionString: `(DESCRIPTION=(ADDRESS=(PROTOCOL=${process.env.first_DATABASE_PROTOCOL})(HOST=${process.env.first_DATABASE_HOST})(PORT=${process.env.first_DATABASE_PORT}))
                          (CONNECT_DATA=(SERVER=${process.env.first_DATABASE_SERVER})(SID=${process.env.first_DATABASE_SID})))`,
      poolMin: parseInt(process.env.first_POOL_MIN),
      poolMax: parseInt(process.env.first_POOL_MAX),
      poolIncrement: parseInt(process.env.first_POOL_INCREMENT),
      poolTimeout: parseInt(process.env.first_POOL_TIMEOUT),
      poolAlias: process.env.first_POOL_ALIAS
    })
    console.log('Connection pool for first started')
  } catch (error) {
    console.error('Error starting first connection pool: ' + error.message)
    process.exit(1)
  }
}

const createSecondPool = async () => {
  try {
    await oracledb.createPool({
      user: process.env.second_DATABASE_USER,
      password: process.env.second_DATABASE_PASSWORD,
      connectionString: `(DESCRIPTION=(ADDRESS=(PROTOCOL=${process.env.second_DATABASE_PROTOCOL})(HOST=${process.env.second_DATABASE_HOST})(PORT=${process.env.second_DATABASE_PORT}))
                          (CONNECT_DATA=(SERVER=${process.env.second_DATABASE_SERVER})(SID=${process.env.second_DATABASE_SID})))`,
      poolMin: parseInt(process.env.second_POOL_MIN),
      poolMax: parseInt(process.env.second_POOL_MAX),
      poolIncrement: parseInt(process.env.second_POOL_INCREMENT),
      poolTimeout: parseInt(process.env.second_POOL_TIMEOUT),
      poolAlias: process.env.second_POOL_ALIAS
    })
    console.log('Connection pool for second started')
  } catch (error) {
    console.error('Error starting second connection pool: ' + error.message)
    process.exit(1)
  }
}

async function closePoolAndExit() {
  console.log('\nTerminating')
  try {
    // Get the pool from the pool cache and close it when no
    // connections are in use, or force it closed after 10 seconds
    // If this hangs, you may need DISABLE_OOB=ON in a sqlnet.ora file
    await oracledb.getPool(process.env.FIRST_POOL_ALIAS).close(10)
    await oracledb.getPool(process.env.SECOND_POOL_ALIAS).close(10)
    console.log('Pool closed')
    process.exit(0)
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}
```
 My index.js looks like this: 
```
const express = require('express')
const app = express()
if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config()
}

const { createFirstPool, createSecondPool, closePoolAndExit } = require('./src/config/db')

const port = process.env.PORT || 3600
app.listen(port, async () => {
  try {
    console.log('Initializing database module')
    await createSecondPool()
    await createFirstPool()
    console.log(`Listening on port ${port}`)
  } catch (error) {
    console.error({ message: err })

    process.exit(1) // Non-zero failure code
  }
})

process.once('SIGTERM', closePoolAndExit).once('SIGINT', closePoolAndExit)
```
Does this suffice for what i want to achieve?

**Comment by cjbj** [comment]
> Does process.once('SIGTERM', closePoolAndExit).once('SIGINT', closePoolAndExit) handle database connection errors

Not directly. They are invoked by signals to the process.

> Does this suffice for what i want to achieve?

What exactly do you want to achieve?

It's recommended to shut pools down cleanly when the app finishes.  If you don't, then the database may take a while (depending on various settings and factors) to realize that connections are dead and then releasing the DB resources being used by them.

**Comment by Enado95** [comment]
I just basically want to close all pools that were opened prior to a failing pool when starting the application

**Comment by cjbj** [comment]
I would remove the `exit()` calls (and probably the try/catch blocks) in `createFirstPool` and `createSecondPool`, and make your error handler in index.js call `closePoolAndExit`.

`closePoolAndExit` should check to see if the pools exist in the cache before trying to close them.  It could/should also be called from the interrupt handlers, so that killing the process happens nicely.

`createFirstPool` and `createSecondPool` look like candidates to be merged into one function which accepts parameters.  If app startup time is an issue, you could probably parallelize the two calls - as long as you wait for both to finish before continuing.

If you're lucky @dmcghan will put together some sample code.

Out of interest, why do you need multiple pools?

**Comment by Enado95** [comment]
I’m using two different databases. It’s not two pools on the same database.
Is there something wrong with the approach?

**Comment by cjbj** [comment]
If you have two databases then two pools is probably good.  I have to assume you need pooling - but most people do.

If you want to discuss this in person, join the next [Office Hours](https://devgym.oracle.com/pls/apex/dg/office_hours/727) and we can discuss all the pros & cons. You can tell us details.  I'm sure everyone will have a slightly different opinoon about the best practice architecture

**Comment by Enado95** [comment]
Okay thanks for that, I'll join. I'll move the `closePoolAndExit()` to the index.js try catch block and test.

**Comment by Enado95** [comment]
Works fine.
