### ISSUE TITLE
Error 'invalid value for parameter 2'

### ISSUE THREAD

**Issue by Gustavoohrq** [oracle/node-oracledb#1229]
1. Review the [user manual](https://oracle.github.io/node-oracledb/doc/api.html)

2. Describe the problem
**I am in error when executing a procedure. You're saying that my second parameter is incorrect.
.**.

3. Include a runnable Node.js script that shows the problem.
`(await connection).executeMany('
execute prc_cancela_despesa(:1,:2,:3)', {
            1: ano,
            2: gCompraNumero,
            3: numeroPedido,
        });`
   The more details you give, the more we can help.

4. Run node and show the output of:

```
Error: NJS-005: invalid value for parameter 2
    at Object.assert (C:\Users\gustavo.mariano\Desktop\Projetos\pd-janus-aprovacoes-api\node_modules\oracledb\lib\util.js:146:11)
    at Connection.executeMany (C:\Users\gustavo.mariano\Desktop\Projetos\pd-janus-aprovacoes-api\node_modules\oracledb\lib\connection.js:184:14)
    at C:\Users\gustavo.mariano\Desktop\Projetos\pd-janus-aprovacoes-api\node_modules\oracledb\lib\util.js:202:16
    at new Promise (<anonymous>)
    at Connection.executeMany (C:\Users\gustavo.mariano\Desktop\Projetos\pd-janus-aprovacoes-api\node_modules\oracledb\lib\util.js:190:14)  
    at router.put (C:\Users\gustavo.mariano\Desktop\Projetos\pd-janus-aprovacoes-api\src\routes\pedidos.js:80:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

5. What is your Oracle Database version?

Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
PL/SQL Release 11.2.0.1.0 - Production
"CORE	11.2.0.1.0	Production"
TNS for Linux: Version 11.2.0.1.0 - Production
NLSRTL Version 11.2.0.1.0 - Production

**Comment by dmcghan** [comment]
What is the `(await connection)` for?

Regarding the error, if you look at the doc:
https://oracle.github.io/node-oracledb/doc/api.html#-427-connectionexecutemany

You'll see that the first parameter is a string and the second, in your case, should be an array of binds. It can be an array of arrays or an array of objects. 

What datatypes are `ano`, `gCompraNumero`, and `numeroPedido`? If they are scalars and not arrays, perhaps you should be using just `execute`? Do you want to execute the statement many times?

**Comment by Gustavoohrq** [comment]
`ano`, `gCompraNumero` and `numeroPedido`, are variables that contain integer values. `(await connection)`  I'm using because the visual studio code completed automatically. Vou executar essa  procedure só uma vez

**Comment by dmcghan** [comment]
I would change `(await connection)` to just `connection`, it's confusing as it is.

If they are variables with integers, then why are you using `executeMany` and not just `execute`?

**Comment by cjbj** [comment]
Or better, change it to `await connection` like in https://github.com/oracle/node-oracledb/blob/master/examples/em_plsql.js#L60:
```
 const result = await connection.executeMany(sql, binds, options);
```

Or, with your data, using [`execute()`](https://github.com/oracle/node-oracledb/blob/master/examples/example.js#L119) as @dmcghan hypothesized:

```
result = await connection.execute(sql, binds, options);
```
