### ISSUE TITLE
Copy oracle Instant Client zip files from src folder to docker image

### ISSUE THREAD

**Issue by Enado95** [oracle/node-oracledb#1230]
I want to know if I can copy the Instant Client zip files from my project src folder to the docker image when it is created. I don't have access to the machine where docker runs so I'd like to know if this is possible.

**Comment by cjbj** [comment]
There are many ways to handle Instant Client.  See https://oracle.github.io/node-oracledb/INSTALL.html#docker  and https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1

**Comment by Enado95** [comment]
So for more context the only option I was advise to use was no. 3. Where I copy the instant client files. Wanted to know if I can commit the client files with my code and then copy them to the image when it’s being created. I won’t have access to the machine where docker is run. So this is the only option I was given.

**Comment by cjbj** [comment]
Why wouldn't you be able to do that? Try it and see !

The only general issue is 'committing'. It sounds like you are using a source code control system, and generally, but not always, large binaries are not committed into them.

**Comment by Enado95** [comment]
Well I’m doing ci/cd we use kubernetes to host our apps, but we have our
own image repository and when building our application we can’t connect to
external resources. So the the client files would have to be downloaded
then copied to the image.

**Comment by cjbj** [comment]
Sounds like a good use case for copying.

**Comment by Enado95** [comment]
Is there a preferred Node 12 image to use?

**Comment by cjbj** [comment]
I think it is personal preference.

**Comment by Enado95** [comment]
I chose the one used in your example `node:12-buster-slim`. Thanks

**Comment by cjbj** [comment]
Sounds good.  I'll close this issue.
