### ISSUE TITLE
how to access another schema when connect current schema through config

### ISSUE THREAD

**Issue by wowtrxqn** [oracle/node-oracledb#1237]
in my connectString schema is 'aaa', but my login api call another schema 'bbb' ,so how to define entity with these crossing schema table ?

**Comment by cjbj** [comment]
What do you mean 'login api'?

The only node-oracledb control is [`currentSchema`](https://oracle.github.io/node-oracledb/doc/api.html#propconncurrentschema).  Anything else needs to be done via SQL or done in the DB (e.g. with a database link).

**Comment by danilohgds** [comment]
Usually, connection strings consist of the database address, SID and port, and the schema is referenced on every query, for example:

```javascript
// for this example connection string would look like this connectString: "localhost/xe"

const result = connection.execute("select * from schemaA.tableA", {}, null);
const otherSchemaresult = connection.execute("select * from schemaB.tableB", {}, null);
```
Only control DB has is the property currentSchema, equal to an alter session command. You can access as many schemas as your user has access to, by purely selecting them in SQL like shown above.

**Comment by wowtrxqn** [comment]
> What do you mean 'login api'?
> 
> The only node-oracledb control is [`currentSchema`](https://oracle.github.io/node-oracledb/doc/api.html#propconncurrentschema). Anything else needs to be done via SQL or done in the DB (e.g. with a database link).

thanks

**Comment by wowtrxqn** [comment]
> Usually, connection strings consist of the database address, SID and port, and the schema is referenced on every query, for example:
> 
> ```js
> // for this example connection string would look like this connectString: "localhost/xe"
> 
> const result = connection.execute("select * from schemaA.tableA", {}, null);
> const otherSchemaresult = connection.execute("select * from schemaB.tableB", {}, null);
> ```
> 
> Only control DB has is the property currentSchema, equal to an alter session command. You can access as many schemas as your user has access to, by purely selecting them in SQL like shown above.

thanks
