### ISSUE TITLE
Oracle Nodejs library - Passing Array to Oracle stored proc

### ISSUE THREAD

**Issue by Rajanusa** [oracle/node-oracledb#1238]
1. Review existing [enhancement requests](https://github.com/oracle/node-oracledb/labels/enhancement)

2. Describe your new request in detail
I need to pass array to oracle stored proc as input parameter.
The array could primitive type or custom object.
The use case is to filter record for a column with multiple values.
Consumer app pass list of values as array that need to be received as input parameter with corresponding pl-sql type and use it in select query to filter using IN clause or other alternative.

3. Give supporting information about tools and operating systems.  Give relevant product version numbers
We use nodejs oracle library , Windows 10 and Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by anthony-tuininga** [comment]
Please take a look at the documentation: [here](https://oracle.github.io/node-oracledb/doc/api.html#plsqlcollections) and [here](https://oracle.github.io/node-oracledb/doc/api.html#sqlwherein) and [here](https://oracle.github.io/node-oracledb/doc/api.html#objects). This covers what you are requesting, I believe. If you don't think that is the case, please provide additional information about your problem so we can help further.

**Comment by cjbj** [comment]
And check out the [examples](https://github.com/oracle/node-oracledb/tree/master/examples).
