### ISSUE TITLE
ORA-01406: fetched column value was truncated

### ISSUE THREAD

**Issue by freeman983** [oracle/node-oracledb#124]
select * from(SELECT USERCODE,
                 NICKNAME,
                 USERNAME,
                 F_NAME,
                 F_VERSIONNAME,
                 REGDATE,
                 IWEEK,
                 CASE
                   WHEN REGDATE <= ORDERDATE THEN
                    1
                   ELSE
                    0
                 END IF_CZ,
                 COUNT(USER_ID) CNT
            FROM T_WH_TEMP1 T1, T_WH_TEMP2 T2
            WHERE T1.USERDATE = T2.USERTIME(+)
            GROUP BY USERCODE,
                    NICKNAME,
                    USERNAME,
                    F_NAME,
                    F_VERSIONNAME,
                    REGDATE,
                    IWEEK,
                    CASE
                      WHEN REGDATE <= ORDERDATE THEN
                       1
                      ELSE
                       0
                    END)

**Comment by cjbj** [comment]
@freeman983 Please give some context such as the CREATE TABLE command, a few insert statements and the character set info.  

Did you look at https://github.com/oracle/node-oracledb/issues/62 ?

**Comment by freeman983** [comment]
I'm sorry, our data is more complex, I using the test data and can't reproduce this exception, but using paging query is ok ，like 

                 select * from ( select row_.*, rownum rownum_ from ( ' + sql + ' ) row_ where rownum <= 10)       where rownum_ > 0;


Remove the packing of the paging will be an error

**Comment by cjbj** [comment]
If you get a testcase, let us know.
