### ISSUE TITLE
DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found"

### ISSUE THREAD

**Issue by Sicmatr1x** [oracle/node-oracledb#1244]
I follow the installation instructions do and still got this issue.

I use macOS Catalina 10.15.4

```
DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
[2020-04-29T10:32:22.413] [ERROR] ncrerror - Error: TypeError: Cannot read property 'getConnection' of undefined
```

I copy all files of the zip into the lib folder

```
iMAC:~ sic$ cd lib
iMAC:lib sic$ ls
BASIC_LICENSE			libclntsh.dylib.19.1		libociei.dylib
BASIC_README			libclntshcore.dylib.19.1	libocijdbc19.dylib
adrci				libnnz19.dylib			liboramysql19.dylib
genezi				libocci.dylib			network
libclntsh.dylib			libocci.dylib.10.1		ojdbc8.jar
libclntsh.dylib.10.1		libocci.dylib.11.1		ucp.jar
libclntsh.dylib.11.1		libocci.dylib.12.1		uidrvci
libclntsh.dylib.12.1		libocci.dylib.18.1		xstreams.jar
libclntsh.dylib.18.1		libocci.dylib.19.1
```

and my .bash_profile file is like 

```
export PATH=/Users/sic/lib:$PATH
export PATH=/Users/sic/flutter/bin:$PATH
```

2. What Node.js version are you using?  Run node and show the output of:

```
process.platform darwin
process.version v12.16.2
process.arch x64
require('oracledb').versionString 4.2.0
```

**Comment by cjbj** [comment]
Sorry I don't have a solution.  Instant Client is not certified on Catalina.  And the recent Node.js builds have also 'broken' it on earlier macOS versions.

See https://github.com/oracle/node-oracledb/issues/1239

**Comment by casperle** [comment]
@Sicmatr1x @cjbj 

Hi guys. After few hours of trying I made it working on my macbook with Catalina 10.15.4.
What I have done:

1. Installed python 2.7 from here https://www.python.org/downloads/release/python-2718 - the prepacked python which comes with macOs can partially cause the issue
2. installed node version 12.16.1 - newer versions are compiled differently https://nodejs.org/en/blog/release/v12.16.2/
3. downloaded the instantclient_19_3 and moved it inside ~/oracle folder
4. created symlink ~/lib/libclntsh.dylib -> ~/oracle/instantclient_19_3/libclntsh.dylib
5. removed installed node_modules in my application
6. reinstalled packages using yarn - npm should work as well

Hope this helps.

**Comment by cjbj** [comment]
This is being followed up in #1239.

**Comment by rafael-trevisan** [comment]
> @Sicmatr1x @cjbj
> 
> Hi guys. After few hours of trying I made it working on my macbook with Catalina 10.15.4.
> What I have done:
> 
> 1. Installed python 2.7 from here https://www.python.org/downloads/release/python-2718 - the prepacked python which comes with macOs can partially cause the issue
> 2. installed node version 12.16.1 - newer versions are compiled differently https://nodejs.org/en/blog/release/v12.16.2/
> 3. downloaded the instantclient_19_3 and moved it inside ~/oracle folder
> 4. created symlink ~/lib/libclntsh.dylib -> ~/oracle/instantclient_19_3/libclntsh.dylib
> 5. removed installed node_modules in my application
> 6. reinstalled packages using yarn - npm should work as well
> 
> Hope this helps.

I confirm your suggestions work beautifully in a fresh-installed Catalina 10.15.4

I wish I had found your comment a couple of hours ago... I wasted too much time here troubleshooting this thing...

**Comment by phuwn** [comment]
> @Sicmatr1x @cjbj
> 
> Hi guys. After few hours of trying I made it working on my macbook with Catalina 10.15.4.
> What I have done:
> 
> 1. Installed python 2.7 from here https://www.python.org/downloads/release/python-2718 - the prepacked python which comes with macOs can partially cause the issue
> 2. installed node version 12.16.1 - newer versions are compiled differently https://nodejs.org/en/blog/release/v12.16.2/
> 3. downloaded the instantclient_19_3 and moved it inside ~/oracle folder
> 4. created symlink ~/lib/libclntsh.dylib -> ~/oracle/instantclient_19_3/libclntsh.dylib
> 5. removed installed node_modules in my application
> 6. reinstalled packages using yarn - npm should work as well
> 
> Hope this helps.

I've followed this instruction and it worked well. In my case, I think you guys don't need to remove the whole node_modules folder, just uninstall oracledb package and reinstall it using: npm install --python={python2.7 location} oracledb
