### ISSUE TITLE
Error: DPI-1047 ... libnsl.so.1: errno: symbol not found

### ISSUE THREAD

**Issue by mhechthz** [oracle/node-oracledb#1245]
Hi,

I use nodere-node-contrib-oracledb-mod inside the nodered docker container. Installation of oracle was tricky, but finally seemed to work. Than I got errors of missing libraries libnsl, libaio, libresolv and ld-linux-x86-64. So I copied all  from /lib/x86_64-linux-gnu to a local subdirectory. The local subdirectory is reachable from docker.

As I try to connect now I get the following:
`
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "Error relocating /data/ora/instantclient_19_5/libnsl.so.1: errno: symbol not found". See https://oracle.github.io/odpi/doc/installation.html#linux for helpNode-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.htmlYou must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html`
As far as I now, docker uses the system libraries, so regardless of copying them to a different directory, it should work. Inside the docker container the libraries are not installed. So I have no other libraries available. My version e.g. for libnsl is libnsl-2.27.so (checked also 2.26 and 2.31). I'm using oracledb4.2.0.

What can I do now?

**Comment by cjbj** [comment]
What's the container OS and the the OS version used by nodered?

Don't manually copy files around.  Just install the necessary OS packages using the OS package management system

For the specific error you gave, make sure the 'libnsl' package is installed in the container.  E.g on Oracle Linux you could run `yum install -y libaio libnsl` in your Dockerfile.

Review [Using node-oracledb in Docker](https://oracle.github.io/node-oracledb/INSTALL.html#docker) and [Docker for Oracle Database Applications in Node.js and Python](https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1).

**Comment by mhechthz** [comment]
This is the Docker file:

https://github.com/node-red/node-red-docker/blob/master/.docker/Dockerfile.alpine 

There is no yum or apt-get. I managed to run wget and unzip insid the container to provide oracle and I managed to hand over the ORACLE_HOME and GL_LIBRARY_PATH. The only thing missing are the 4 libraries. It should be not so hard to provide  appropriate files in a subdirectory instead of buildin an entire new Cocker-File (which I never did before and think will take a long time)

**Comment by mhechthz** [comment]
Meanwhile I provided the glibc-libraries of alpine to the container. What I now get is the following:
`Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "Error relocating /data/apkpack/usr/lib/libnsl.so.1: __asprintf: symbol not found". See https://oracle.github.io/odpi/doc/installation.html#linux for helpNode-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.htmlYou must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html`
The LD_LIBRARY_PATH is `/lib:/usr/lib:/data/ora/instantclient_19_5:/data/alpinegclib/usr/lib`. All Files are in PATH and `asprintf ` is in  `/lib/ld-musl-x86_64.so.1`.  This is what is required by libnsl.so.1 (ldd libnsl.so.1 output `... /lib/ld-musl-x68_64.so.1`.

**Comment by cjbj** [comment]
Alpine?  I'll have to let you Google & sort that out yourself.

I'd recommend using a supported OS that isn't going to give you installation or runtime grief.

**Comment by mhechthz** [comment]
Well,  its the official node-red docker container https://nodered.org/docs/getting-started/docker.

Ok, maybe I try a little bit more to get it running. If I have any news, I let you know.

**Comment by Adhikaripr** [comment]
Any update on this, in facing the same issue

**Comment by cjbj** [comment]
When node-oracledb 6.0 is released, you could try it's default Thin mode, since that won't need Instant Client which seems to be [your problem](https://stackoverflow.com/questions/76183898/how-to-setup-oracle-instant-client-in-node-alpine-docker-ppc64le).  Or try x64

**Comment by sosoba** [comment]
> When node-oracledb 6.0 is released, you could try it's default Thin mode

Is there already more code publicly available than https://github.com/oracle/node-oracledb/blob/310203de4e2e5a4244e7b0b836f50f902597ce16/package.json#L3 ?

**Comment by cjbj** [comment]
@sosoba I appreciate the eagerness.  All the public code is .... public.

**Comment by Adhikaripr** [comment]
> Alpine? I'll have to let you Google & sort that out yourself.
> 
> I'd recommend using a supported OS that isn't going to give you installation or runtime grief.

Is there supported OS for ppc64le? I am also getting same libnsl.so.1 not found error.

**Comment by yasirharis** [comment]
@cjbj I  tried `6.0.0-dev` and got this error -> NJS-045: cannot load a node-oracledb Thick mode binary for Node.js. 

Already following guidance from this: https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html#github

but still got this issue. Any idea?

**Comment by yasirharis** [comment]
@cjbj I tried `6.0.0-dev` thin mode in alpine:13.4.2

node_modules/oracle_db/build/Release:
`oracledb.node`

simple js scripts:
`
   const cas = require('oracledb');
    console.warn(cas.oracleClientVersion);
    console.warn(cas.oracleClientVersionString);
`

output:
`Segmentation fault`

are there any missing things?

**Comment by sharadraju** [comment]
@yasirharis  The thin mode is not yet out. 
The code that you see on Github does not include the code for thin mode, but some extra functionalities that will be used by 6.0.0 when it is fully released.
The Thin mode will not require the binary file `oracledb.node` when it is released.

So please wait until the node-oracledb 6.0.0 is officially released.

**Comment by Adhikaripr** [comment]
anyone has solution for the libnsl.so.1, i tried 
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add --update libaio libnsl && \
    ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 but still it's not working.

**Comment by yasirharis** [comment]
> anyone has solution for the libnsl.so.1, i tried RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && apk add --update libaio libnsl && ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 but still it's not working.

hi @Adhikaripr I manage to use node-oracledb in alpine:3.14.2
 
try this :
`
RUN printf "https://uk.alpinelinux.org/alpine/v3.14/main\nhttps://uk.alpinelinux.org/alpine/v3.14/community\n" > /etc/apk/repositories

RUN apk add --no-cache musl libaio libc6-compat krb5-libs
RUN apk add --update libc6-compat gcompat krb5-libs
`

**Comment by Adhikaripr** [comment]
> > anyone has solution for the libnsl.so.1, i tried RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && apk add --update libaio libnsl && ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 but still it's not working.
> 
> hi @Adhikaripr I manage to use node-oracledb in alpine:3.14.2
> 
> try to combine this on your dockerfile : ` FROM node:14.18.1-alpine3.14
> 
> RUN printf "[https://uk.alpinelinux.org/alpine/v3.14/main\nhttps://uk.alpinelinux.org/alpine/v3.14/community\n](https://uk.alpinelinux.org/alpine/v3.14/main%5Cnhttps://uk.alpinelinux.org/alpine/v3.14/community%5Cn)" > /etc/apk/repositories
> 
> RUN apk add --no-cache musl libaio libnsl libc6-compat krb5-libs RUN apk add --update libc6-compat gcompat krb5-libs `

thanks I tried that but still Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "Error loading shared library libnsl.so.1: No such file or directory (needed by /code/instantclient/libclntsh.so)

**Comment by cjbj** [comment]
@Adhikaripr are you still on ppc64le?  Did you try a different architecture? Did you try getting SQL*Plus working?

**Comment by yasirharis** [comment]
@cjbj or maybe you can share something so we can help you check the issue.

On my side,
~I put all .so files that needed by instant client into one folder
![image](https://github.com/oracle/node-oracledb/assets/9350797/6c0fbf7d-753c-41c1-86cc-e12781e28880)

~check each file dependeny using `ldd` or `lddtree` to make sure no missing dependency.
~and set LD_LIBRARY_PATH to that folder.

**Comment by Adhikaripr** [comment]
After sym-linking these three it finally worked for ppc64le.
RUN ln -s /usr/lib/libnsl.so.3  /usr/lib/libnsl.so.1
RUN ln -s /usr/lib/libc.so /usr/lib/libresolv.so.2
RUN ln -s /lib64/ld64.so.2 /usr/lib/ld64.so.2
