### ISSUE TITLE
NJS-018: invalid ResultSet with OUT SYS_REFCURSOR

### ISSUE THREAD

**Issue by mdecurtins** [oracle/node-oracledb#1246]
I have a procedure that takes an ID as an IN parameter and a SYS_REFCURSOR as an OUT parameter. The procedure does some logic, inserts some rows in a table as a side effect, and opens a cursor for any conflicts that arose during calculation. In most cases, the cursor would contain < 10 rows, and in some cases the cursor would have 0 rows (if no conflicts arose during calculation).

My calling code in Node looks like this:
```js
const sql = `
BEGIN
    calculate_meetings( :courseId, :cursor );
END;
`

const params = {
  courseId: 1234,
  cursor: {
    type: oracledb.CURSOR,
    dir: oracledb.BIND_OUT
  }
}

const ROWS_PER_FETCH = 50
connection.execute( sql, params, function onExecuteRefcursor( err, result ) {
  if ( err ) throw err
  let records = []
  let rows
  do {
    rows = result.outBinds.cursor.getRows( ROWS_PER_FETCH )
    // Merge the results.
    // records = [...records, ...rows]
  } while ( rows.length === ROWS_PER_FETCH )

  result.outBinds.cursor.close()
})
```
I am more or less exactly following the [refcursor example](https://github.com/oracle/node-oracledb/blob/master/examples/refcursor.js) in the API docs.

When I run the code, I can see that the procedure **successfully executes** in the database (it inserts some rows in a table and I can see that these rows are being inserted), but when I go to read from the cursor in Node, I get the following error:
```
Promise {
  <rejected> Error: NJS-018: invalid ResultSet
      at ResultSet.getRows (/path/to/node_modules/oracledb/lib/resultset.js:104:10)
      at /path/to/node_modules/oracledb/lib/util.js:202:16
      at new Promise (<anonymous>)
      at ResultSet.getRows (/path/to/node_modules/oracledb/lib/util.js:190:14)
      at onExecuteRefcursor (/path/to/src/db/database.js:180:43)

```
The error seems to be coming from the call to `getRows()`. If I log `result.outBinds.cursor`, I get:
```js
{ cursor:
   ResultSet {
     _rowCache: [],
     _processingStarted: false,
     _convertedToStream: false,
     _allowGetRowCall: false,
     _connection:
      Connection {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _dbObjectClasses: {},
        _pool: [Pool] },
     _fetchArraySize: 100 } }
```
If I log `result.outBinds.cursor.metaData`, it is `undefined`. I'm not sure if this is expected behavior or if I have to configure the connection to provide metadata.

My procedure is as follows:
```sql
CREATE PROCEDURE calculate_meetings ( 
  in_course_id IN NUMBER,
  conflicts OUT SYS_REFCURSOR
) AS
  ...variable declarations
BEGIN
  ...procedure body
  ...
  OPEN conflicts FOR SELECT * FROM TABLE ( CAST( l_conflicting_dates AS conflicts_table ) );
END;
```
The variable `l_conflicting_dates` is a VARRAY of custom type `conflict_record`. The types are defined in the schema outside of the procedure body, e.g.
```sql
CREATE TYPE conflict_record AS OBJECT ( ...columns... );
CREATE TYPE conflicts_table AS TABLE OF conflict_record;
```

The problem seems to stem from the call to `getRows()`. We are using direct fetch for all SQL statements. `ResultSet` does not seem to be enabled unless specified by an option `{ resultSet: true }`, but according to the [docs on the ResultSet class](http://oracle.github.io/node-oracledb/doc/api.html#resultsetclass), specifying an OUT cursor always returns a `ResultSet`. I do not think I need to pass this as an explicit option (and the refcursor example does not suggest this either).

I don't tend to think it's an issue that the cursor might possibly return 0 rows. My understanding is that case is already handled by the method call.

Again, the procedure executes successfully, but reading from the cursor is what's causing the `NJS-018: invalid ResultSet` error.

Any help is greatly appreciated!

Node platform: linux x64
Node version: 10.16.3
node-oracledb version: 4.0.1
Oracle InstantClient version: 12.2.0.1.0
Oracle Database version: 12c Release 1 (12.1.0.2)

**Comment by dmcghan** [comment]
The difference between your code and the example you referenced is the use of async/await. Learning to use async/await, which builds on top of promises, is key in Node.js development. Have a look at this post if you'd like to learn more: https://jsao.io/2017/07/how-to-get-use-and-close-a-db-connection-using-async-functions/

The first thing you should do is wrap the code you showed us in a function. Maybe it already is and you're just showing us the body. Once it's in a function, you can put the `async` keyword in front of the function keyword to make the function an AsyncFunction. Then, within that function, you can use the `await` keyword so that you don't have to use callbacks. The code will continue to execute asynchronously as it always has, but it will read as though it's synchronous.

Study the example again and try to make your code more that example. Show us the updated code if you have problems getting it to work.

**Comment by mdecurtins** [comment]
@dmcghan I understand that there's that difference. I'm using an existing wrapper for the `connection.execute()` class that was written to work with the connection pool configuration for our applications, and all of that code is using callbacks. I can't easily switch to `async/await` without going back and refactoring existing code.

Yes, the code I posted was already in an `async` function, one that's using an explicit Promise constructor. We're aware that this is an anti-pattern and needs to be updated. I'm not sure I see any reason, though, based on the API docs, why reading from a cursor shouldn't work in a callback as well as in an `async/await` situation.

**Comment by dmcghan** [comment]
I'll comment on some of the lines of code you showed to explain the problem.

```javascript
// You said it would be hard to switch to async/await, I'm not sure what you mean by that.
// The following function, on onExecuteRefcursor, is not async, but it could easily be made so.
connection.execute( sql, params, function onExecuteRefcursor( err, result ) {
  if ( err ) throw err
  let records = []
  let rows

  do {
    // Here, within a synchronous loop, you are making a call to an asynchronous function.
    rows = result.outBinds.cursor.getRows( ROWS_PER_FETCH )
    // Merge the results.
    // records = [...records, ...rows]
  } while ( rows.length === ROWS_PER_FETCH )

   // Here, you are closing the cursor that your still processing in the synchronous loop. You will reach this line way before the loop is done.
  result.outBinds.cursor.close()
})
```

Try replacing those lines with these ones:
```javascript
connection.execute( sql, params, async function onExecuteRefcursor( err, result ) {
  if ( err ) throw err
  let records = []
  let rows

  do {
    rows = await result.outBinds.cursor.getRows( ROWS_PER_FETCH )
    // Merge the results.
    // records = [...records, ...rows]
  } while ( rows.length === ROWS_PER_FETCH )

  await result.outBinds.cursor.close()
})
```

**Comment by mdecurtins** [comment]
What I meant about switching to `async/await` is that my code is not calling the Oracledb `connection.execute()` method directly --- I am dealing with pre-existing wrapper code for that method that handles checking out a connection from the pool and does any type conversions. It uses the `Async` package but the wrapper method itself is invoked synchronously. It is written using callbacks. I believe this code will need to change, but I am not in a position to do that just now. I apologize for any confusion there. (I should note that regular SQL statements run just fine. I can read properties from the return value of `connection.execute()`, such as `result.rows` from regular SELECT statements and `result.rowsAffected` for DML statements. This is the first time any code is using OUT binds.) Hopefully that provides useful additional context.

Your version with `await` did not resolve the issue. I am trying to determine if there is a connection configuration problem that is interfering with obtaining a valid `ResultSet`.

**Comment by dmcghan** [comment]
So the code you're showing us is not the code you're using? Or is it that your reference to `connection` is a reference to your wrapper? Can you show us the wrapper's `execute` method? 

I'll venture a guess that it's closing connections in addition to checking them out of the pool. This will not work for cursors, which need the connection to be open while you're processing them.

**Comment by mdecurtins** [comment]
Yes, it's very possible that the wrapper code is closing the connection before the code to read from the cursor is executed. Looking at other search results for `NJS-018: invalid ResultSet` it does seem like the most likely explanation is that the connection is being closed too early.

I'm not sure how much of the wrapper code I should be sharing, (it's also not my code) but the relevant piece is this:
```js
function _releaseConn (err, result) {
  connection.close(function onConnectionClose (error) {
    if (err) {
      console.error(err)
    }
    if ( error ) {
      console.error( error )
    }
    callback(err, result)
  })
}

if (err) {          
   console.error(err)
   _releaseConn(err, null)
     return
}
```
This code is called within the callback to `connection.execute()`. The reference to `callback(err, result)` is the callback passed to the wrapper function (in my case, the callback is the `onExecuteRefcursor` function). 

I know that's not the easiest thing to follow but because the callback is invoked in the process of closing the connection, it does seem like any function I pass that would expect an open connection (for reading from the cursor) would be called too late.

**Comment by dmcghan** [comment]
Yeah, I'm not sure what all the wrapper is offering you or if you must always use it. In the past, I've written wrappers named `simpleExecute` that does at least part of what your wrapper does. The name of my wrapper is chosen to indicate it should be used only for simple use cases but, as you've found, it will not work for all. In the cases where it will not work, you simply don't use it.

**Comment by mdecurtins** [comment]
I'll see if I can get around it, thanks.

**Comment by mdecurtins** [comment]
I was able to write a workaround for the preexisting wrapper code and now that I have an open connection, the cursor is working as expected. Closing this issue.

**Comment by mdecurtins** [comment]
FWIW a more helpful error message might be nice if it's able to be determined that the connection was closed before the cursor was processed :)

**Comment by alichampion** [comment]
> 



> I was able to write a workaround for the preexisting wrapper code and now that I have an open connection, the cursor is working as expected. Closing this issue.

Hi, @mdecurtins can you share the code for wrapper which resolved your issue.

**Comment by cjbj** [comment]
@alichampion this is a very old issue.  Look at the examples in https://github.com/oracle/node-oracledb/tree/main/examples for up to date code.

**Comment by alichampion** [comment]
> @alichampion this is a very old issue. Look at the examples in https://github.com/oracle/node-oracledb/tree/main/examples for up to date code.

Hi, @cjbj you are right!

I have tried ResultSet1, ResultSet2 and even resultsettoquerystream but I'm getting this error `NJS-018 invalid ResultSet`!

Can you checkout this link https://github.com/typeorm/typeorm/issues/8687#issue-1146956436?
