### ISSUE TITLE
DPI-1050 when binding 'false' to a NUMBER column with 11.2 Oracle Client

### ISSUE THREAD

**Issue by newlukai** [oracle/node-oracledb#1249]
1. Review the [user manual](https://oracle.github.io/node-oracledb/doc/api.html)

Done. Didn't find an answer

2. Describe the problem

My Node application creates a connection pool on startup. The first thing this app then does is to `execute` a `SELECT` statement. If there are distinct tables missing (i. e. the `SELECT` statement errors, these are created by my app, `executing` some `CREATE TABLE` statements. This works.

After this initialization my app waits for incoming requests to `execute` `INSERT` statements using the very same connection pool created during the app startup.

In a productive environment I encountered an error DPI-1050 stating that the provided client library 11.2 doesn't suffice the required version 12.1. After(!) the initial connection pool creation. This really puzzles me and I have no clue why (DB version is 11.2, client library also) and how (the app already `execute`d statements successfully) this happens.

3. Include a runnable Node.js script that shows the problem.

I didn't drill the issue down yet.

4. Run node and show the output of:

```
process.platform = "linux"
process.version = "v12.14.0"
process.arch = "x64"
require('oracledb').oracleClientVersionString = "4.2.0"
require('oracledb').oracleClientVersionString = "11.2.0.3.0"
```

5. What is your Oracle Database version?

Oracle Database 11g Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
CORE	11.2.0.4.0	Production  
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

I would be really happy about an idea how to solve this DPI-1050 issue.

**Comment by anthony-tuininga** [comment]
Can you set the environment variable `DPI_DEBUG_LEVEL` to the value 8 and report the output? That will help determine what feature you are trying to access that is not supported with version 11.2.

**Comment by newlukai** [comment]
Fortunately I can :) Read from bottom to top, I added some app logging where I obfuscated some business details:

```
[2020-05-12 09:39:04][DEBUG][insert()][#57][null][null] - INSERTING an entry into TableX. INSERT INTO TableX (ColumnA,ColumnB,ColumnC,ColumnD,ColumnE,ColumnF,ColumnG,ColumnH) VALUES (?0?,?1?,?2?,?3?,?4?,?5?,?6?,?7?)
ODPI [29254] 2020-05-12 09:39:04.809: internal error DPI-1050: Oracle Client library is at version 11.2 but version 12.1 or higher is needed (dpiConn_newVar / check Oracle Client version)
[2020-05-12 09:39:04][DEBUG][insert()][#26][null][null] - Entered TableX entry insertion.
[2020-05-12 09:38:14][DEBUG][getDBVersion()][#70][null][null] - Got results for retrieval of database version. [ { VERSION: '2.0.0' } ]
[2020-05-12 09:38:14][DEBUG][initialize()][#32][null][null] - Successfully connected to database.
[2020-05-12 09:38:14][DEBUG][anonymous()][#69][null][null] - Connection established.
[2020-05-12 09:38:14][DEBUG][anonymous()][#62][null][null] - Connection pool created. Connecting Oracle.
[2020-05-12 09:38:14][DEBUG][_createPool()][#53][null][null] - Creating pool for connections to Oracle.
ODPI [29254] 2020-05-12 09:38:14.607: ODPI-C 3.4.0-dev
ODPI [29254] 2020-05-12 09:38:14.607: debugging messages initialized at level 8
```

**Comment by cjbj** [comment]
Is that INSERT via `execute()` or `executeMany()`?  What are the data types you are binding?  Got a shareable testcase?

**Comment by newlukai** [comment]
It's `INSERT` via `execute`:

```
execute('INSERT INTO TableX (ColumnD,ColumnB,ColumnC,ColumnG,ColumnJ,ColumnF,ColumnH,ColumnI) VALUES (:0,:1,:2,:3,:4,:5,:6,:7)', [
  'stringWith40Characters------------------',
  'stringWith18Charac',
  '9characte',
  'stringWith26Characters----',
  '6chars',
  false,
  0,
  1162337
]);
```

TableX was should have been created via:
```CREATE TABLE TableX
(
	ColumnA NUMBER(20),
	ColumnB varchar (128),
	ColumnC varchar (128),
	ColumnD varchar (128),
	ColumnE NUMBER(10),
	ColumnF NUMBER(5),
	ColumnG varchar (128),
	ColumnH NUMBER(10),
	ColumnI NUMBER(10),
	ColumnJ varchar (32),
	CONSTRAINT PK_TX_CA PRIMARY KEY(ColumnA)
)```

Oracle SQL Developer confirms:

```
CREATE TABLE "USER"."TABLEX" 
   (	"COLUMNA" NUMBER(20,0), 
	"COLUMNB" VARCHAR2(128 BYTE), 
	"COLUMNC" VARCHAR2(128 BYTE), 
	"COLUMND" VARCHAR2(128 BYTE), 
	"COLUMNE" NUMBER(10,0), 
	"COLUMNF" NUMBER(5,0), 
	"COLUMNG" VARCHAR2(128 BYTE), 
	"COLUMNH" NUMBER(10,0), 
	"COLUMNI" NUMBER(10,0), 
	"COLUMNJ" VARCHAR2(32 BYTE)
   )
```

Yes, there is a sequence for ColumnA :)

If necessary I would try to reproduce this locally tomorrow.

Thantk you very much in advance.

**Comment by newlukai** [comment]
Wow. I instantly could reproduce this error locally. Please [find my testcase here](https://github.com/newlukai/gh1249).

I'm running an Oracle XE 11.2 locally:
```
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
PL/SQL Release 11.2.0.2.0 - Production
"CORE	11.2.0.2.0	Production"
TNS for 64-bit Windows: Version 11.2.0.2.0 - Production
NLSRTL Version 11.2.0.2.0 - Production
```

**Comment by newlukai** [comment]
Sorry, I forgot the version information. Added it in the repo, on my machine it's as follows:

```
process.platform: win32
process.version: v12.13.0
process.arch: x64
oracledb.versionString: 4.2.0
oracledb.oracleClientVersionString: 11.2.0.2.0
```

**Comment by cjbj** [comment]
Even with recent versions, trying to insert a boolean isn't going to work:

```
darwin
v12.16.3
x64
5.0.0-dev
19.3.0.0.0
Got connection.
Inserted Infos.
Got version. [ { VERSION: '2.0.0' }, { VERSION: '2.0.0' } ]
[Error: ORA-00932: inconsistent datatypes: expected NUMBER got BOOLEAN] {
  errorNum: 932,
  offset: 109
}
```
Is that what's triggering the DPI-1050 with your Oracle version?

**Comment by newlukai** [comment]
… d'oh …
That's correct. Well, thanks.

The message led me on the wrong track. I'm wondering which part of the chain is responsible for DPI messages. Is it worth an issue?

**Comment by cjbj** [comment]
I've made a note in our DPI 'to do' list that this occurs with the 11.2 client.  But since the expected ORA error is shown with at least 12.2, my assessment is that the problem may not be the highest priority task !

Thanks for reporting it.

**Comment by newlukai** [comment]
Thanks for your support :)
