### ISSUE TITLE
Can't install oracledb on windows 7 64 bit

### ISSUE THREAD

**Issue by nuskyazhar** [oracle/node-oracledb#125]
I have installed oracle 11g - 64bit
I have extracted  instantclient-basic and  instantclient-sdk to 'C:\instantclient_12_1'

Environment variables

OCI_INCLUDE_DIR --> C:\instantclient_12_1\sdk\include
OCI_LIB_DIR --> C:\instantclient_12_1\sdk\lib\msvc\vc10
Path --> C:\instantclient_12_1\vc10;C:\instantclient_12_1
when i run 'npm install oracledb' i get the following error

  dpiEnv.cpp
D:\LearningTests\NodeTestCodes\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file
 or directory [D:\LearningTests\NodeTestCodes\node_modules\oracledb\build\oracledb.vcxproj]
  dpiEnvImpl.cpp
..\src\dpi\src\dpiEnvImpl.cpp(28): fatal error C1083: Cannot open include file: 'oratypes.h': No such file or directory [D:\LearningTests\NodeTestCod
es\node_modules\oracledb\build\oracledb.vcxproj]
  dpiException.cpp
  dpiExceptionImpl.cpp
D:\LearningTests\NodeTestCodes\node_modules\oracledb\src\dpi\include\dpiStmt.h(29): fatal error C1083: Cannot open include file: 'oci.h': No such fil
e or directory [D:\LearningTests\NodeTestCodes\node_modules\oracledb\build\oracledb.vcxproj]
  dpiConnImpl.cpp
..\src\dpi\src\dpiConnImpl.cpp(28): fatal error C1083: Cannot open include file: 'oratypes.h': No such file or directory [D:\LearningTests\NodeTestCo
des\node_modules\oracledb\build\oracledb.vcxproj]
  dpiDateTimeArrayImpl.cpp
..\src\dpi\src\dpiDateTimeArrayImpl.cpp(30): fatal error C1083: Cannot open include file: 'oratypes.h': No such file or directory [D:\LearningTests\N
odeTestCodes\node_modules\oracledb\build\oracledb.vcxproj]
  dpiPoolImpl.cpp
D:\LearningTests\NodeTestCodes\node_modules\oracledb\src\dpi\include\dpiStmt.h(29): fatal error C1083: Cannot open include file: 'oci.h': No such fil
e or directory [D:\LearningTests\NodeTestCodes\node_modules\oracledb\build\oracledb.vcxproj]
  dpiStmtImpl.cpp
..\src\dpi\src\dpiPoolImpl.cpp(29): fatal error C1083: Cannot open include file: 'oratypes.h': No such file or directory [D:\LearningTests\NodeTestCo
des\node_modules\oracledb\build\oracledb.vcxproj]
  dpiUtils.cpp
..\src\dpi\src\dpiStmtImpl.cpp(33): fatal error C1083: Cannot open include file: 'oratypes.h': No such file or directory [D:\LearningTests\NodeTestCo
des\node_modules\oracledb\build\oracledb.vcxproj]
D:\LearningTests\NodeTestCodes\node_modules\oracledb\src\dpi\include\dpiStmt.h(29): fatal error C1083: Cannot open include file: 'oci.h': No such fil
e or directory [D:\LearningTests\NodeTestCodes\node_modules\oracledb\build\oracledb.vcxproj]
D:\LearningTests\NodeTestCodes\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file o
r directory [D:\LearningTests\NodeTestCodes\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/123#issuecomment-113868009

**Comment by nuskyazhar** [comment]
thank you very much. setting these 2 environment variables fixed the problem

set OCI_LIB_DIR=C:\oracle\instantclient_12_1\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient_12_1\sdk\include

**Comment by umapathy08** [comment]
thank you., it works
