### ISSUE TITLE
Document prebuilt binaries compatibility with OL7

### ISSUE THREAD

**Issue by silviuburceadev** [oracle/node-oracledb#1251]
- Include a link to the documentation section or the example
[Install -> 3.2.1. Install Prerequisites](https://oracle.github.io/node-oracledb/INSTALL.html#321-install-prerequisites)
- Describe the confusion
It's not clear if the prebuilt binaries, built on Oracle Linux 6, work on Oracle Linux 7 and which glibc version is needed.
- Suggest changes that would help
The docs describe that prebuilt binaries 'will require a compatible glibc', but doesn't say a word about the possible compatible versions. In the [3.10 section](https://oracle.github.io/node-oracledb/INSTALL.html#-310-node-oracledb-installation-from-source-code), it is noted that 'GCC 4.4.7 (the default on Oracle Linux 6)'. According to [these](https://access.redhat.com/solutions/19458) [links](https://blogs.oracle.com/wim/oracle-linux-7-for-arm-is-now-generally-available), GCC 4.8.x is the default on OL7. Is it guaranteed that node-oracledb work with 4.8.x? Or anything that's 4.4.x or higher will do?

As a small side note, I'm trying to migrate from 2.2.x running on OL6 to something newer(hopefully 4.x) on OL7, this is how I got confused.

**Comment by cjbj** [comment]
Points noted and thanks for taking the time to bring it up.

**Comment by cjbj** [comment]
The next doc push will have improved wording.
