### ISSUE TITLE
Adding carriage returns '\n' to text on insert and update

### ISSUE THREAD

**Issue by madsteer** [oracle/node-oracledb#1252]
1. Review the [user manual](https://oracle.github.io/node-oracledb/doc/api.html)

**2. Describe the problem**
The issue is I can't seem to add a newline character at the beginning of or end of a string when doing an insert or update to a table.  So if I try to add:
`\nI'm losing the cr at the beginning of the message`
or
`I'm losing the cr at the end of the message\n`
after I perform a select to get the row back I'm getting:
`I'm losing the cr at the beginning of the message`
and
`I'm losing the cr at the end of the message`
respectively.  If I were to insert `I'm not losing my \ncr\n in the middle` upon select I get `I'm not losing my \ncr\n in the middle` and get to keep the '\n' characters in the middle of the message.

Not sure if this is Oracle the database doing this or node-oracledb the node module, but since this is a rewrite of working Perl code using the same oracle database and tables, I feel like it might be the node-oracledb node module causing the issue (or my NodeJS code)

**3. Include a runnable Node.js script that shows the problem.**

This is in an express app, so it's hard to show a complete example as it is in the app, but here's the gist of it:
```
let pool = oracles.getPool();
let connection = await pool.getConnection();
let log = `I'm losing the cr at the end of the message\n`
let hostname = 'server1'
let sql = 'insert into logs_table (log,hostname) values(:log,:hostname)';
let binds = { log, hostname };
let rows = '';
try {
    rows = await connection.execute(sql, binds, { autoCommit: true });
  } catch (error) {
    connection.rollback(err => { if (err) { console.log('failed to rollback'); } });
    throw error;
  } finally {
    connection.close(err => { if (err) { console.log('failed to release connection'); } });
  }

console.log(rows);

sql = `select * from logs_table where where hostname = 'server1'`;
connection = await pool.getConnection();
try {
  rows = await connection.execute(sql);
catch (error) {
  throw error;
} finally {
  connection.close(err => { if (err) { console.log('failed to release connection'); } });
}

console.log(rows);
```

**4. Run node and show the output of:**

```
1 row inserted


{ "hostname": "server1", "log": "I'm losing the cr at the end of the message" }
```

**5. What is your Oracle Database version?**  I don't actually know the answer to this.  The Oracle DB installation is managed by another area.  I'm using version `3.1.2` of node-oracledb and version `10.13.0` of NodeJS

**Comment by cjbj** [comment]
Your testcase doesn't run (what is `binds`?), but my own test seems fine:
```
{
  metaData: [ { name: 'C1' } ],
  rows: [ { C1: 'newline\n' }, { C1: 'nonewline' } ]
}
```

Try using `select dump(yourcol) from yourtable` to check what is stored in the column.

**Comment by madsteer** [comment]
I updated the OP with `binds`.  Sorry about that.  the app has this code spread out amongst several modules in a larger express app, so I was attempting to combine it here for simplicity.

I'll take a look at that `select dump(yourcol)`  thx

**Comment by madsteer** [comment]
I determined it was our code that was removing the newline characters.  `'\n  I am a string  \n  '.trim()` ends up being `'I am a string'`  Sorry to waste everyone's time.  thanks for the responses.
