### ISSUE TITLE
Error: NJS-045: cannot load a node-oracledb binary for Node.js 12.4.0 (darwin x64)

### ISSUE THREAD

**Issue by fgprodigal** [oracle/node-oracledb#1253]
```
process.platform: darwin
process.version: v12.16.3
process.arch: x64
require('oracledb').versionString: 4.2.0
require('oracledb').oracleClientVersionString: 19.3.0.0.0
```

This is my repo:
[https://github.com/fgprodigal/oracledb-test](https://github.com/fgprodigal/oracledb-test)

It is initialed by vue-cli and vue add electron, I added require("oracledb") in background.js, when i run 'yarn run electron:serve', the error mentioned above appears.

I've read some earlier issues, I added copy-webpack-plugin but still not work, so please help me, what is going wrong with electron or webpack?

**Comment by cjbj** [comment]
What's the OS version?

**Comment by fgprodigal** [comment]
This error appears on both macOS 10.14.6 and windows 10 x64 1909

**Comment by cjbj** [comment]
Last time I tried electron, I think I used https://github.com/n-riesco/oracledb-electron-builder

To use webpack you need to patch the lib/oracledb.js file, or build the current master branch.  See https://github.com/oracle/node-oracledb/issues/1156#issuecomment-571554125  But I don't see webpack in your example?

Neither Electron or Webpack will package Instant Client, so you will need to install that separately.

**Comment by fgprodigal** [comment]
ok, I'll try oracledb-electron-builder.

my project was created by vue-cli, webpack can be configured by vue.config.js
[https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config](https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config)

> vue.config.js
```javascript
const CopyWebpackPlugin = require('copy-webpack-plugin')
const path = require("path")

function resolve (dir) {
  return path.join(__dirname, dir);
}

module.exports = {
  publicPath: "./",
  devServer: {
    // can be overwritten by process.env.HOST
    host: "0.0.0.0",
    port: 8080
  },
  configureWebpack: config => {
    config.plugins.push(
      new CopyWebpackPlugin({
        patterns: [
          {
            from: resolve('node_modules/oracledb/build'),
            to: 'node_modules/oracledb/build'
          }
        ]
      })
    )
  },
  chainWebpack: config => {
    config.resolve.alias
      .set("@", resolve("src"))
      .set("src", resolve("src"))
      .set("common", resolve("src/common"))
      .set("components", resolve("src/components"));
  }
};
```

**Comment by cjbj** [comment]
Try node-oracledb 5. See https://github.com/oracle/node-oracledb/issues/1156#issuecomment-598017250

Also check out the new [macOS installation doc](https://oracle.github.io/node-oracledb/INSTALL.html#instosx) and new [initialization doc](https://oracle.github.io/node-oracledb/doc/api.html#initnodeoracledb).
