### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by max-pub** [oracle/node-oracledb#1258]
Any plans to support [deno](https://deno.land)?

**Comment by cjbj** [comment]
Not from me at the moment.  But feel free to start working on it :)

**Comment by ksmarty** [comment]
Has there been any progress on this? I've attempted to import it using both skypack and esm.sh but both return errors.

**Comment by cjbj** [comment]
@ksmarty I've not heard of anyone working on this.

**Comment by cjbj** [comment]
I just played with deno and node-oracledb 6.0 Thin mode. There are a couple of calls to `os` module functions that Deno technically [needs to support ](https://github.com/denoland/deno/issues/17850), but these could be worked around with some node-oracledb modification if necessary.  Also there is are two usages of `buffer.Buffer.byteLength()` that Deno doesn't like.

In summary, a Deno-enthusiast could improve Deno and/or node-oracledb.  Our group will focus on exposing database features in node-oracledb, and enhancing Thin mode functionality.  I will close out this issue and wait for your PRs!
