### ISSUE TITLE
How to get the result after insert.

### ISSUE THREAD

**Issue by kutata** [oracle/node-oracledb#1259]
Our company use the old version 3.1.2.
After run  `conn.execute('insert user_name into user_table')`

It only return us  `{ rowsAffected: 1 }`

But I need to know what `user_id` had generated with this new row,
could you please tell me how to do，I had already spend lots of time to search this!

**Comment by cjbj** [comment]
In all versions, to get data, use [DML RETURNING](https://oracle.github.io/node-oracledb/doc/api.html#dmlreturn):

> “DML RETURNING” statements (such as INSERT ... RETURNING ... INTO ...) are a way information can be returned about row changes from DML statements. For example you can use DML RETURNING to get the ROWIDs of newly inserted rows. Another common use case is to return auto incremented column values .

With node-oracledb you can get the ROWID of the last inserted row using the [results.lastRowid](https://oracle.github.io/node-oracledb/doc/api.html#execlastrowid).

Please feel free to suggest any documentation updates that would have let you find those references more easily.

**Comment by kutata** [comment]
Thank you bro, great helpful!

**Comment by jobin-daniel** [comment]
use the results.lastRowid to make a query on the same table like "SELECT * FROM YOUR_TABLE WHERE ROWID = :lastRowid"

lastRowid looks like
"AAAS/tAAFAAAA/QAAB"
