### ISSUE TITLE
Connection Retry

### ISSUE THREAD

**Issue by jaw187** [oracle/node-oracledb#126]
Is there any support for retrying failed connections?

**Comment by cjbj** [comment]
@jaw187 Not natively. Can you tell me your use case?  What load or failure cases are you trying to handle? Are you using pooling?  Do you want retry capabilities, or connections to block until they succeed?

**Comment by jaw187** [comment]
I've got a QA database which has some issues allowing clients to connect.  I've had a tough time getting support internally, so I decided to just wrap the function which creates the pool inside another function and track a count of failures.


```
    var failedAttempts = 0;
    var retries = options.retries || internals.defaults.retries;

    var connect = function () {

        DB.init(options.db, function (err, db) {

            if (err) {
                if (failedAttempts < retries) {
                    ++failedAttempts;
                    return connect();
                }
                return next(err);
            }

            return next();
        });
    };
```

I'd rather just pass along an option to your library to get the same effect.

**Comment by cjbj** [comment]
@jaw187 Is pool creation the main problem for you, or is it getting connections from the pool? 

Have you seen https://github.com/oracle/node-oracledb/pull/50 ?   If there was a blocking createPool(), would you still want some timeout capability?

**Comment by jaw187** [comment]
Pool creation is the only problem that I've been told is an issue.  I wouldn't use `createPoolSync`, I'd still like to return an error after a specific number of retries.

**Comment by cjbj** [comment]
@jaw187 thanks

**Comment by dmcghan** [comment]
@jaw187 I'm not sure if you still need a fix for the issue with getting connection from the pool, but I just added support for connection request queueing at the pool level to orawrap. It limits the number of active connections in a pool to the poolMax setting. I'd love it if you could give it a test and/or provide some feedback.

**Comment by cjbj** [comment]
I'm going to close this.  The recently implemented [connection pool queue](https://github.com/oracle/node-oracledb/blob/v1.8.0/doc/api.md#propdbqueuerequests) (derived from OraWrap) should handle most cases where you need to restrict the pool size, which is the common use case.  There are no plans to trap Oracle connection errors and retry when there is a server side or network connection issue.
