### ISSUE TITLE
Unable to run script on node-oracledb(windows 10) - new to nodejs

### ISSUE THREAD

**Issue by kscsekar** [oracle/node-oracledb#1260]
Installed node.js and oracle-adb. But unable to run script - not sure if I am following the right steps
C:\Program Files\nodejs>node D:\cqn\node-test-oracledb-copy\examples\insert1.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'oracledb'
Require stack:
- D:\cqn\node-test-oracledb-copy\examples\insert1.js

The script is copied by one of customer from github examples for CQN

5. What is your Oracle Database version?
Trying to use oracle autonomous DB

**Comment by kscsekar** [comment]
Sorry Got work around by copying from working setup.

**Comment by cjbj** [comment]
I'll close this then.  Installation instructions are at https://oracle.github.io/node-oracledb/INSTALL.html, if you ever need them.
