### ISSUE TITLE
Cypress Project: Error: NJS-045: cannot load a node-oracledb binary for Node.js 

### ISSUE THREAD

**Issue by Weavingtempest** [oracle/node-oracledb#1261]
Running into issues with setting up node-oracledb in a cypress project. I'm unable to import the library. I'm getting the following error when running the project, 

```
Error: NJS-045: cannot load a node-oracledb binary for Node.js 12.13.0 (darwin x64) 
  Node.js require('oracledb') error was:...
```

I have attempted the following, 
- Downgrade node to v10.16
- Manually compiled node-oracledb by following the steps mentioned [here](https://oracle.github.io/node-oracledb/INSTALL.htmll) 

Cypress v4.8.0

node output
```
darwin
'v10.16.3'
'x64'
'4.2.0'
'19.3.0.0.0'
```
Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
PL/SQL Release 12.2.0.1.0 - Production
"CORE	12.2.0.1.0	Production"
TNS for Linux: Version 12.2.0.1.0 - Production
NLSRTL Version 12.2.0.1.0 - Production

**Comment by Weavingtempest** [comment]
Opps, did not mean to put this as a bug meant for this to be a question.

**Comment by cjbj** [comment]
Maybe try setting `DYLD_LIBRARY_PATH` to your Instant Client directory in the process/shell that directly invokes Node.js.

However ff you manually compiled node-oracledb 5.0.0-dev from the master branch, look at https://github.com/oracle/node-oracledb/blob/master/doc/api.md#oracleclientloading.  My current usage with node-oracledb 5.0.0-dev on macOS 10.14 (Mojave) is to run `ln -s /Users/cjones/instantclient_19_3/libclntsh.dylib $(npm root)/oracledb/build/Release`

**Comment by Weavingtempest** [comment]
@cjbj Sadly I was unable to get this working within a cypress project. I was able to start a node project and import the node-oracledb lib into a .js file and run it. I worked closely with another co-worker who was able to run node-oracledb lib from within a cypress project. We reinstalled, checked files, manually added libs, confirmed exports, paths, etc. Still no dice. Ended up writing code to make use of sqlplus available on the local machine. 

One major difference from your setup and mine is I'm on the Cataline OS. We had to take libs out of quarantine in Cataline due to the increased security. Not sure if there is something else I'm missing permission wise, but sadly had to table getting this working due to sprint demands.

**Comment by cjbj** [comment]
Sorry to hear you moved on. The major difference is not Catalina (which we have been testing on) but that you are using Cypress.  We are close to releasing node-oracledb 5 and I would be very interested to get your feedback on whether the new `initOracleClient()` method helps you.

**Comment by cjbj** [comment]
@Weavingtempest node-oracledb was just released which should help (or have helped). Check out the new [macOS installation doc](https://oracle.github.io/node-oracledb/INSTALL.html#instosx) and new [initialization doc](https://oracle.github.io/node-oracledb/doc/api.html#initnodeoracledb).  There's an extra (obvious) tip in https://blogs.oracle.com/opal/node-oracledb-50-adds-nested-cursors-database-startup-and-prefetch-tuning too.

**Comment by ice1080** [comment]
Hello @cjbj, I work with @Weavingtempest and have been trying to do the same thing for a different project: use node-oracledb inside a cypress environment. Just wanted to give an update on this. It appears that cypress does not have a node version available in its spec files, so even trying to import/require oracledb causes immediate failure with this error:
```> NJS-069: node-oracledb 5.1.0 requires Node.js 8.16 or later```
I tried logging the node version in cypress and got back 0:
```process.version.substring(1).split(".").map(Number);
// this returned [ 0 ]
```
However, for anyone else that may see this in the future, I was able to get node-oracledb to work with cypress by writing a cypress plugin for it:
src/plugins/dbPlugin.js:
```
let _connection;

// https://www.sitepoint.com/javascript-design-patterns-singleton/
const DbPluginUtil = {

    async setupDb(config) {
        // has to be in this method or even importing this file will break stuff in cypress
        const oracledb = require('oracledb');
        oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
        oracledb.autoCommit = true;

        oracledb.initOracleClient({configDir: config['TNS_ADMIN_LOCATION']});
        _connection = await oracledb.getConnection({
            user: config['DB_USER'],
            password: config['DB_PASSWORD'],
            connectString: config['DB_CONNECT_STRING'],
        });

        return null;
    },

    async testConnection(config) {
        if (!_connection) {
            await this.setupDb(config);
        }
    },

    async executeDbStatement(statement, config) {
        await this.testConnection(config);

        try {
            return await _connection.execute(statement);
        } catch (e) {
            throw new Error('failed to execute: ' + statement + '\n' + e.message);
        }
    },
}

Object.freeze(DbPluginUtil);

function loadDBPlugin(config) {
    return {
        async executeDbStatement({statement}) {
            return await DbPluginUtil.executeDbStatement(statement, config);
        },
    }
}

module.exports = {
    loadDBPlugin
}
```

Then in cypress/plugins/index.js:
```
const {loadDBPlugin} = require("../../src/plugins/dbPlugin");
...
    // in the module.exports function:
    on('task', loadDBPlugin(config));
```
Then usage in your cypress tests looks like this:
```
cy.task('executeDbStatement', {
    statement: 'select user from dual',
})
    .then((response) => {
        expect(response['rows'][0]['USER']).to.equal('bla');
    });
```

**Comment by cjbj** [comment]
@ice1080 this is excellent - thanks for sharing.  I'll change the issue subject to help people find your tip.

Is there any way / any need to set up a connection pool?

**Comment by ice1080** [comment]
@cjbj someone could definitely make another cypress task to set that up as well if they wanted. All my cypress stuff was running synchronously and my use case was real simple, but it shouldn't be difficult to extend to add that.

**Comment by labkapapka** [comment]
> Hello @cjbj, I work with @Weavingtempest and have been trying to do the same thing for a different project: use node-oracledb inside a cypress environment. Just wanted to give an update on this. It appears that cypress does not have a node version available in its spec files, so even trying to import/require oracledb causes immediate failure with this error: `> NJS-069: node-oracledb 5.1.0 requires Node.js 8.16 or later` I tried logging the node version in cypress and got back 0:
> 
> ```
> // this returned [ 0 ]
> ```
> 
> However, for anyone else that may see this in the future, I was able to get node-oracledb to work with cypress by writing a cypress plugin for it: src/plugins/dbPlugin.js:
> 
> ```
> let _connection;
> 
> // https://www.sitepoint.com/javascript-design-patterns-singleton/
> const DbPluginUtil = {
> 
>     async setupDb(config) {
>         // has to be in this method or even importing this file will break stuff in cypress
>         const oracledb = require('oracledb');
>         oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
>         oracledb.autoCommit = true;
> 
>         oracledb.initOracleClient({configDir: config['TNS_ADMIN_LOCATION']});
>         _connection = await oracledb.getConnection({
>             user: config['DB_USER'],
>             password: config['DB_PASSWORD'],
>             connectString: config['DB_CONNECT_STRING'],
>         });
> 
>         return null;
>     },
> 
>     async testConnection(config) {
>         if (!_connection) {
>             await this.setupDb(config);
>         }
>     },
> 
>     async executeDbStatement(statement, config) {
>         await this.testConnection(config);
> 
>         try {
>             return await _connection.execute(statement);
>         } catch (e) {
>             throw new Error('failed to execute: ' + statement + '\n' + e.message);
>         }
>     },
> }
> 
> Object.freeze(DbPluginUtil);
> 
> function loadDBPlugin(config) {
>     return {
>         async executeDbStatement({statement}) {
>             return await DbPluginUtil.executeDbStatement(statement, config);
>         },
>     }
> }
> 
> module.exports = {
>     loadDBPlugin
> }
> ```
> 
> Then in cypress/plugins/index.js:
> 
> ```
> const {loadDBPlugin} = require("../../src/plugins/dbPlugin");
> ...
>     // in the module.exports function:
>     on('task', loadDBPlugin(config));
> ```
> 
> Then usage in your cypress tests looks like this:
> 
> ```
> cy.task('executeDbStatement', {
>     statement: 'select user from dual',
> })
>     .then((response) => {
>         expect(response['rows'][0]['USER']).to.equal('bla');
>     });
> ```

Hi, I use node-oracledb Thin Mode (without Oracle library), will it work?
This row  oracledb.initOracleClient({configDir: config['TNS_ADMIN_LOCATION']}); use Oracle library?

**Comment by sharadraju** [comment]
@labkapapka You can remove initOracleClient() from this code.

**Comment by labkapapka** [comment]
@sharadraju unfortunately it doesn't work



> @labkapapka You can remove initOracleClient() from this code.

in this case:

1
taskexecuteDbStatement, {statement: select * from PTEMPDATA}
CypressError
cy.task('executeDbStatement') failed with the following error:



> NJS-125: "connectString" cannot be empty or undefined. Bequeath connections are not supported in Thin mode

**Comment by sharadraju** [comment]
@labkapapka I have a working test case. Please join the node-oracledb [ slack channel ](https://join.slack.com/t/node-oracledb/shared_invite/enQtNDU4Mjc2NzM5OTA2LWMzY2ZlZDY5MDdlMGZiMGRkY2IzYjI5OGU4YTEzZWM5YjQ3ODUzMjcxNWQyNzE4MzM5YjNkYjVmNDk5OWU5NDM) and ping me

**Comment by labkapapka** [comment]
> @labkapapka I have a working test case. Please join the node-oracledb [ slack channel ](https://join.slack.com/t/node-oracledb/shared_invite/enQtNDU4Mjc2NzM5OTA2LWMzY2ZlZDY5MDdlMGZiMGRkY2IzYjI5OGU4YTEzZWM5YjQ3ODUzMjcxNWQyNzE4MzM5YjNkYjVmNDk5OWU5NDM) and ping me. We can connect, if possible.

thanks!
maybe it work!
I configured connection credentials and seems it work!

**Comment by labkapapka** [comment]
> @labkapapka Yes you have to configure the DB credentials in the `cypress.config.js` file similar to:
> 
> ```
> const { loadDBPlugin } = require("./cypress/plugins/dbPlugin");
> 
> module.exports = defineConfig({
>   e2e: {
>     setupNodeEvents(on, config) {
>       // implement node event listeners here
>       on('task', loadDBPlugin(config));
>     },
>   },
>   env: {
>     DB_USER: "user",
>     DB_PASSWORD: "password",
>     DB_CONNECTSTRING: "localhost/orclpdb"
>   },
> });
> ```

Hi!
Could you help me again?)
I need to use variable sid in this statement:
statement: `select * from PTEMPDATA where SID="${sid}"
but I get Error:
taskexecuteDbStatement, {statement: select * from PTEMPDATA where SID="undefined"}
How to use variable in this statement?

**Comment by cjbj** [comment]
@sharadraju will you share the solution?

**Comment by sharadraju** [comment]
@cjbj @labkapapka Attached my sample cypress test solution with node-oracledb 6.0.3 here
[cypresstest.zip](https://github.com/oracle/node-oracledb/files/12451116/cypresstest.zip)
