### ISSUE TITLE
Tried upgrading from node 12.13.0 to 12.18.0 getting error DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1)

### ISSUE THREAD

**Issue by chakradhari** [oracle/node-oracledb#1262]
# Do these first

I upgraded node version 12.13.0 to 12.18.0 the started receving this error.

Steps I followed.

1) rm -rf node_modules
2) npm cache clean -f
3) switched to my new version of node (12.18.0)
4) npm install
5) npm start

Then I started getting following error.

[22:03:37 NGConnectorDI:error] event="ngconndi.creatRoutes.error" method="catch" message="DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html" 
[22:03:37 NGConnectorDI Service:error] Error: NJS-047: poolAlias "default" not found in the connection pool cache

When I revert back to node 12.13.0 it seems to be working fine.

# Answer the following questions

1. Describe the problem and show the error you have.
[22:03:37 NGConnectorDI:error] event="ngconndi.creatRoutes.error" method="catch" message="DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found".

2. What Node.js version are you using?  Run node and show the output of:

```
process.platform - Mac OS (Mojave)
process.version - Node 12.18.0
process.arch
require('oracledb').versionString - 4.1.0
require('oracledb').oracleClientVersionString 
```

3. Are you installing into vanilla Node.js, or using something like Electron?
   Node - 12.18.0
4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  64 -bit

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.
<img width="663" alt="Screen Shot 2020-06-12 at 10 19 32 PM" src="https://user-images.githubusercontent.com/17154826/84526410-deeb8580-acfa-11ea-8aa9-019109a23ee6.png">

**Comment by cjbj** [comment]
Unless you are connecting to some really old DB, you could/should use Instant Client 19.  It will let you connect to Oracle DB 11.2 or later.

Try setting DYLD_LIBRARY_PATH to your Instant Client directory.  This will need to be done in each terminal or process that invokes Node.js.  Also see https://github.com/oracle/node-oracledb/issues/1239#issuecomment-637948310

**Comment by chakradhari** [comment]
@cjbj I did try adding DYLD_LIBRARY_PATH but it still won't work.

**Comment by cjbj** [comment]
@chakradhari if you want more help you'll need to give exact details of where things are installed and how they are set.

**Comment by chakradhari** [comment]
@cjbj I have been upgrading node oracledb quite a while I always follow the same steps.

**Comment by cjbj** [comment]
> I have been upgrading node oracledb quite a while I always follow the same steps.

Node.js is now being [compiled differently](https://nodejs.org/en/blog/release/v12.16.2/) on macOS.  And node-oracledb is necessarily changing too, see all the previous references.

**Comment by cjbj** [comment]
Node-oracledb 5.0 is out with changed install instructions on macOS.  Since putting libraries in ~/lib no longer works with recent Node.js versions, and Catalina has other restrictions, look at the new options in node-oracledb 5. Check out the new [macOS installation doc](https://oracle.github.io/node-oracledb/INSTALL.html#instosx) and new [initialization doc](https://oracle.github.io/node-oracledb/doc/api.html#initnodeoracledb).
