### ISSUE TITLE
CQN is not working with Oracle Autonomous Database (ATP/ADW) - Error: ORA-01031: insufficient privileges

### ISSUE THREAD

**Issue by hitrov** [oracle/node-oracledb#1263]
Runnable example:
https://github.com/hitrov/node-cqn

As this ADB is a free tier Database for only testing purposes I expose credentials as it will be terminated upon the issue resolve.

Example scripts were taken from https://github.com/oracle/node-oracledb/tree/master/examples and remain unchanged.
```
$ NODE_ORACLEDB_USER=books_admin NODE_ORACLEDB_PASSWORD=MyPassword000 NODE_ORACLEDB_CONNECTIONSTRING=cqn19c_high node examples/cqn2.js
[Error: ORA-01031: insufficient privileges] {
  errorNum: 1031,
  offset: 0
}
```

```
$ NODE_ORACLEDB_USER=books_admin NODE_ORACLEDB_PASSWORD=MyPassword000 NODE_ORACLEDB_CONNECTIONSTRING=cqn19c_high node examples/version.js
Run at: Mon Jun 15 2020 15:50:56 GMT+0300 (Eastern European Summer Time)
Node.js version: v12.18.0 (darwin x64)
Node-oracledb version: 4.2.0
Oracle Client library version: 19.3.0.0.0
Oracle Database version: 19.5.0.0.0
```

You must have Oracle client files installed https://www.oracle.com/database/technologies/instant-client.html
In order to connect:
1. unzip `Wallet_cqn19c.zip`
2. copy absolute path to unzipped directory e.g. /home/user/Wallet_cqn19c and replace `DIRECTORY` config value in `sqlnet.ora` to copied one.
3. set environment variable TNS_ADMIN equals to path provided above, for example:
```
export TNS_ADMIN=/home/user/Wallet_cqn19c
```

**Comment by hitrov** [comment]
Same happened with version 18 of Oracle ADB.
As well as with ADMIN user.
Example user (`books_admin` above) was created with 
```
CREATE USER books_admin IDENTIFIED BY MyPassword000;
GRANT CONNECT, RESOURCE TO books_admin;
GRANT UNLIMITED TABLESPACE TO books_admin;
GRANT CHANGE NOTIFICATION TO books_admin;
```
This does not help also
```
GRANT DWROLE TO books_admin;
```

**Comment by hitrov** [comment]
Self-hosted Oracle DB XE doesn't have such issue described.

**Comment by hitrov** [comment]
Also I checked on Windows environment with Oracle 18c ADB, same thing

**Comment by cjbj** [comment]
With Cloud you would need to use client initiated CQN connections.  CQN was disabled prior to this.  But whether or not any CQN support has since been enabled in any of the DB services is something I don't currently know.

**Comment by hitrov** [comment]
Hi @cjbj thanks for your reply, the thing is that client initiated connections were introduced since 19c, but Oracle never claimed that CQN shouldn’t work in 18c ADB :) That’s something that I need to try, thank you

**Comment by hitrov** [comment]
@cjbj here's what i am getting on Linix env
(as macOS client is only 19.3 for some reason, `clientInitiated` is not supported there)
```
Run at: Tue Jun 16 2020 21:21:15 GMT+0300 (Eastern European Summer Time)
Node.js version: v10.20.1 (linux x64)
Node-oracledb version: 4.2.0
Oracle Client library version: 19.6.0.0.0
Oracle Database version: 19.5.0.0.0
```
if i don't set port then
```
Error: ORA-24912: Listener thread failed. Group Notification  not supported for registraiton with OCI_SECURE_NOTIFICATION mode
```
with port set
```
Error: ORA-24912: Listener thread failed. OCI_ATTR_SUBSCR_PORTNO attribute cannot be set for registration with OCI_SECURE_NOTIFICATION mode
```
do you have any suggestions?

**Comment by sdsuy** [comment]
GRANT CONNECT, RESOURCE, DBA TO books_admin;

**Comment by sdsuy** [comment]
[https://oracle.github.io/node-oracledb/doc/api.html#examplesodaawait](url)
Users require the CREATE TABLE privilege and the SODA_APP role.

**Comment by hitrov** [comment]
thanks @sdsuy as i mentined here user was granted such privileges https://github.com/oracle/node-oracledb/issues/1263#issuecomment-644124405 and `ADMIN` (most privileged in ADB) user has exactly the same problems.

**Comment by hitrov** [comment]
There’s an opened service request in Oracle Support SR #3-22886551391
I am using Oracle Autonomous Database (Transaction Processing) on shared infrastructure (always free)

**Comment by cjbj** [comment]
On Slack, @hitrov tells me CQN (with `clientInitated`) is working on Always Free ATP DBs.  

Note grouped notifications for client initiated connections are not yet supported.

**Comment by hitrov** [comment]
Thanks @cjbj , just got the same update from Oracle Support on my Service Request
```
Good day. Thanks for the updates, yes got below updates internally:

1)Yes Grouping is not supported in ADW as of now.
2) IP and Port setup is blocked in ADW environments and hence clientInitiated is required for extra security purpose.
```

**Comment by asadbsse** [comment]
Getting following error on e 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production with instant client library version 19.10.0.0.0 
**ORA-24912: Listener thread failed. Failed to get IP address of host.**

**Comment by asadbsse** [comment]
Getting following error using CQN on 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production with instant client library version 19.10.0.0.0 
**ORA-24912: Listener thread failed. Failed to get IP address of host.**

Running following example from http://oracle.github.io/node-oracledb/doc/api.html#cqn

```
const connection = await oracledb.getConnection({
    user          : "myUser",
    password      : *****,
    connectString : "myschema/XEPDB1",
    events        : true
});

function myCallback(message) {
    console.log(message);
}

const options = {
    sql      : `SELECT * FROM mytable`,  // query of interest
    callback : myCallback                // method called by notifications
};

await connection.subscribe('mysub', options);

```
