### ISSUE TITLE
initOracleClient does not find the client [node-oracledb@v5]

### ISSUE THREAD

**Issue by robsonkades** [oracle/node-oracledb#1268]
After install node-oracledb v5 the method `initOracleClient` not available

my package.json
"oracledb": "^5.0.0",

http://oracle.github.io/node-oracledb/doc/api.html#initnodeoracledb

**Comment by robsonkades** [comment]
@cjbj 

I am debugging and finding the problem.

The lib expects to have two bars, now it has managed to find the client

So it worked for me:

oracledb.initOracleClient ({libDir: 'C: \\\\ oracle \\\\ instantclient_19_6'});

**Comment by cjbj** [comment]
Thanks for the report!  I've updated the doc.
