### ISSUE TITLE
oracledb.initOracleClient does not work when oracle database is x86 and nodejs x64

### ISSUE THREAD

**Issue by robsonkades** [oracle/node-oracledb#1270]
oracledb.initOracleClient() works very well in an environment running isolated from the server, but if the oracle database is running on x86 and nodejs on x64, there will be errors that cannot load the lib.

Even if you change to oracledb.initOracleClient(), the x64 client directory will not work.

Windows x64
Nodejs x64
Oracle x86 database

Even passing the 64x client to oracledb.initOracleClient(), it seems that it ignores and tries to get what is defined in the path

Envs:

CLIENT: x64
ORACLE_CLIENT: C: \\oracleclient\\instantclient_19_6

SERVER x86
LD_LIBRARY_PATH: %ORACLE_HOME%\lib
ORACLE_HOME: C:\oraclexe\app\oracle\product\11.2.0\server 
PATH: C: \oraclexe\app\oracle\product\11.2.0\server\bin

**Comment by cjbj** [comment]
- Can you share the exact code snippet you are using.
- set DPI_DEBUG_LEVEL to 64 and share the log output.

Thanks!

**Comment by robsonkades** [comment]
@cjbj

set env DPI_DEBUG_LEVEL  with 64
 
`const oracledb = require('oracledb');

try {
  oracledb.initOracleClient({ libDir: 'C:\\\\oracle\\\\instantclient_19_6' });
} catch (err) {
  console.log(err);
}
`

**output**
`Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/node-oracledb/INSTALL.html for help
    at OracleDb.initOracleClient (C:\wiipo\Integrador\resources\app.asar\node_modules\oracledb\lib\oracledb.js:142)
    at Object.<anonymous> (C:\wiipo\Integrador\resources\app.asar\src\lib\connection.js:4)
    at Object.<anonymous> (C:\wiipo\Integrador\resources\app.asar\src\lib\connection.js:20)
    at Module._compile (internal/modules/cjs/loader.js:967)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004)
    at Module.load (internal/modules/cjs/loader.js:815)
    at Module._load (internal/modules/cjs/loader.js:727)
    at Function.Module._load (electron/js2c/asar.js:738)
    at Module.require (internal/modules/cjs/loader.js:852)
    at require (internal/modules/cjs/helpers.js:74)
`

node: "12.14.1"
arch: "x64"

**Comment by robsonkades** [comment]
`
c:\test>node index.js
ODPI [16304] 2020-07-01 13:03:51.439: ODPI-C 4.0.1
ODPI [16304] 2020-07-01 13:03:51.441: debugging messages initialized at level 64
ODPI [16304] 2020-07-01 13:03:51.452: Context Parameters:
ODPI [16304] 2020-07-01 13:03:51.454:     Oracle Client Lib Dir: C:\\oracle\\instantclient_19_6
ODPI [16304] 2020-07-01 13:03:51.458: Environment Variables:
ODPI [16304] 2020-07-01 13:03:51.460:     ORACLE_HOME => "C:\oraclexe\app\oracle\product\11.2.0\server"
ODPI [16304] 2020-07-01 13:03:51.465:     PATH => "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\node;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin"
ODPI [16304] 2020-07-01 13:03:51.507: load in parameter directory
ODPI [16304] 2020-07-01 13:03:51.509: load in dir C:\\oracle\\instantclient_19_6
ODPI [16304] 2020-07-01 13:03:51.513: load with name C:\\oracle\\instantclient_19_6/oci.dll
ODPI [16304] 2020-07-01 13:03:51.545: load by OS failure: The specified module could not be found
c:\test\node_modules\oracledb\lib\oracledb.js:142
    this._initOracleClient(options);
         ^

Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/node-oracledb/INSTALL.html for help
    at OracleDb.initOracleClient (c:\test\node_modules\[4moracledb[24m\lib\oracledb.js:142:10)
    at Object.<anonymous> (c:\test\index.js:3:10)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

`

**Comment by robsonkades** [comment]
@cjbj  Maybe I found the problem:

https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1912

**Comment by anthony-tuininga** [comment]
Windows no longer minds the forward slash in directory paths. I doubt that is the issue.

From the output you also have the environment variable ORACLE_HOME set. This should __NOT__ be set when using Instant Client. Please clear this value if you intend to use Instant Client. If you're on the same machine as the XE installation you __CAN__ use that instead. But please don't try to mix and match!

**Comment by robsonkades** [comment]
@anthony-tuininga 

My problem is when it runs on the same machine as XE. But our client's database is 86x and the node-oracledb is running on x64.

Even configuring node-oracledb to use the Instant Client 64x

**Comment by anthony-tuininga** [comment]
A few things for you to try:

- Remove the environment variable ``ORACLE_HOME``
- Make sure that the contents of ``C:\Oracle\Instantclient_19_6`` are indeed 64-bit
- In a command prompt, set ``PATH`` to include ``C:\Oracle\instantclient_19_6`` and remove the call to ``oracledb.initOracleClient()``. This will indicate whether the forward slash in the call to ``oracledb.initOracleClient()`` is indeed causing the problem (I don't think it is)

**Comment by robsonkades** [comment]
@anthony-tuininga 

**Tests running on the same machine with XE**

They have all been removed as oracle envs;

64x instantclient path written
https://www.oracle.com/br/database/technologies/instant-client/winx64-64-downloads.html

**this log is when not defined initOracleClient**
```
c:\test>node index.js
ODPI [04424] 2020-07-01 17:51:10.489: ODPI-C 4.0.1
ODPI [04424] 2020-07-01 17:51:10.492: debugging messages initialized at level 64
ODPI [04424] 2020-07-01 17:51:10.500: Context Parameters:
ODPI [04424] 2020-07-01 17:51:10.503: Environment Variables:
ODPI [04424] 2020-07-01 17:51:10.505:     PATH => "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\node;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\oracle\instantclient_19_6;"
ODPI [04424] 2020-07-01 17:51:10.544: check module directory
ODPI [04424] 2020-07-01 17:51:10.548: module name is \\?\c:\test\node_modules\oracledb\build\Release\oracledb-5.0.0-win32-x64.node
ODPI [04424] 2020-07-01 17:51:10.558: load in dir \\?\c:\test\node_modules\oracledb\build\Release
ODPI [04424] 2020-07-01 17:51:10.564: load with name \\?\c:\test\node_modules\oracledb\build\Release/oci.dll
ODPI [04424] 2020-07-01 17:51:10.570: load by OS failure: The specified module could not be found
ODPI [04424] 2020-07-01 17:51:10.575: load with OS search heuristics
ODPI [04424] 2020-07-01 17:51:10.578: load with name oci.dll
ODPI [04424] 2020-07-01 17:51:10.590: load by OS failure: The specified module could not be found
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/node-oracledb/INSTALL.html for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at OracleDb.getConnection (c:\test\node_modules\oracledb\lib\oracledb.js:272:25)
    at OracleDb.getConnection (c:\test\node_modules\oracledb\lib\util.js:175:19)
    at run (c:\test\index.js:16:37)
    at Object.<anonymous> (c:\test\index.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errorNum: 0,
  offset: 0
}
```

**this log is when is defined initOracleClient**
```
c:\test>node index.js
ODPI [15120] 2020-07-01 17:57:18.325: ODPI-C 4.0.1
ODPI [15120] 2020-07-01 17:57:18.326: debugging messages initialized at level 64
ODPI [15120] 2020-07-01 17:57:18.335: Context Parameters:
ODPI [15120] 2020-07-01 17:57:18.336:     Oracle Client Lib Dir: C:\\oracle\\instantclient_19_6
ODPI [15120] 2020-07-01 17:57:18.343: Environment Variables:
ODPI [15120] 2020-07-01 17:57:18.346:     PATH => "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\node;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\oracle\instantclient_19_6;"
ODPI [15120] 2020-07-01 17:57:18.381: load in parameter directory
ODPI [15120] 2020-07-01 17:57:18.389: load in dir C:\\oracle\\instantclient_19_6
ODPI [15120] 2020-07-01 17:57:18.393: load with name C:\\oracle\\instantclient_19_6/oci.dll
ODPI [15120] 2020-07-01 17:57:18.400: load by OS failure: The specified module could not be found
c:\test\node_modules\oracledb\lib\oracledb.js:142
    this._initOracleClient(options);
         ^

Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/node-oracledb/INSTALL.html for help
    at OracleDb.initOracleClient (c:\test\node_modules\[4moracledb[24m\lib\oracledb.js:142:10)
    at Object.<anonymous> (c:\test\index.js:3:10)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m
```

**Comment by anthony-tuininga** [comment]
Those logs demonstrate that the forward slash is not an issue. Something else is missing from your configuration that causes the DLL to "not be found". What that is I have no idea, unfortunately! See the installation documentation and look carefully. Make very sure that the OCI.DLL in question is indeed a 64-bit DLL and that all of the dependencies are present.

**Comment by robsonkades** [comment]
@anthony-tuininga 

It worked  !!!  🏆 

I tested again with an older version of Instant Client (18.5.0.0.0)
The latest version must have been broken (19.6.0.0.0)

Now I'm going to go back to all the environment variables and define the client manually.

**Comment by robsonkades** [comment]
With all the environment variables defined. 

Working perfectly with oracledb.initOracleClient

```
c:\test>node index.js
ODPI [03056] 2020-07-01 18:51:03.436: ODPI-C 4.0.1
ODPI [03056] 2020-07-01 18:51:03.438: debugging messages initialized at level 64
ODPI [03056] 2020-07-01 18:51:03.446: Context Parameters:
ODPI [03056] 2020-07-01 18:51:03.449:     Oracle Client Lib Dir: C:\instantclient18\instantclient_18_5
ODPI [03056] 2020-07-01 18:51:03.454: Environment Variables:
ODPI [03056] 2020-07-01 18:51:03.457:     ORACLE_HOME => "C:\oraclexe\app\oracle\product\11.2.0\server"
ODPI [03056] 2020-07-01 18:51:03.463:     PATH => "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\node;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;"
ODPI [03056] 2020-07-01 18:51:03.502: load in parameter directory
ODPI [03056] 2020-07-01 18:51:03.510: load in dir C:\instantclient18\instantclient_18_5
ODPI [03056] 2020-07-01 18:51:03.514: load with name C:\instantclient18\instantclient_18_5/oci.dll
ODPI [03056] 2020-07-01 18:51:03.520: load by OS successful
ODPI [03056] 2020-07-01 18:51:03.523: validating loaded library
CONNECT
```

**Comment by anthony-tuininga** [comment]
Excellent! Its still good practice __NOT__ to set the environment variable ``ORACLE_HOME`` if you are not using a full Oracle Client or Database installation.

**Comment by robsonkades** [comment]
Wouldn't it be nice for someone to investigate this problem further? Or fix this compatibility break

**Comment by kubo** [comment]
@robsonkades 
What version of Windows x64 do you use?
If it is Windows 7 or Windows 8 (excluding 8.1), Oracle 19 client seems unsupported. (see [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/ntcli/operating-system-checklist-for-oracle-database-client-installation-on-microsoft-windows.html#GUID-DB33F444-969C-48EC-A6CC-83E938499DCB)).

**Comment by robsonkades** [comment]
@kubo Windows Server 2019.

Instant Client (18.5.0.0.0) 64x
 - Windows 10 -> x64 OK
 - Windows Server 2019  x64 OK
 - node-oracledb v5

Instant Client (19.6.0.0.0) 64x
 - Windows 10 -> x64 SUCCESS
 - Windows Server 2019  x64 FAILUDE
 - node-oracledb v5

**Comment by kubo** [comment]
@robsonkades 
Did you installed Microsoft Visual Studio 2017 Redistributable on the Windows Server 2019?

In https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html
> The 19.6 Basic package requires the [Microsoft Visual Studio 2017 Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by cjbj** [comment]
> Excellent! Its still good practice NOT to set the environment variable ORACLE_HOME if you are not using a full Oracle Client or Database installation.

You definitely don't want to have ORACLE_HOME set with Instant Client, since this can lead to errors like ORA-1804.

If you have Win Server 2019, you could try uninstalling XE and making sure that Instant Client 19 is usable. This would confirm you have the correct redistributable as @kubo indicated.

I'm not a Windows person, but I wonder if you have anything in the registry that is different between your Windows 10 and Windows Server 2019 machines, e.g. in `HKEY_LOCAL_MACHINE\SOFTWARE\ORACLE`?

**Comment by robsonkades** [comment]
@kubo It was really the Microsoft Visual Studio 2017 Redistributable
the installed version was from 2013.

MY MISTAKE 🐴 .

@cjbj Removing ORACLE_HOME is a little tricky for us, as it hurts our customers.
But I believe that if everything were x64 it would work without problems, in this specific case or the client has an oracle x86 on an x64 machine.
I hope this is not common.

I also don't know much about windows. but from what I looked at in the `regedit` I saw no difference.

Thanks to all for your help!!!!

**Comment by cjbj** [comment]
@robsonkades Thanks for the investigation.  I don't know how to fiddle registry settings, but your code could unset ORACLE_HOME at runtime before initOracleClient is called.  I hope the new function does make it easier for you to distribute apps.

And thanks @kubo !  Your advice is always on target.
