### ISSUE TITLE
Could not install node-oracledb on Free Autonomous Oracle Cloud

### ISSUE THREAD

**Issue by cc13com** [oracle/node-oracledb#1273]
Hi,

I'm working on a Free Autonomous Oracle Cloud with oraclelinux-release-7.8-1.0.7.el7.x86_64 and tried to install node.js with node-oracledb followed the instruction on [Build a Node.js Application](https://docs.oracle.com/en/cloud/paas/atp-cloud/atpdg/node-js-application.html#GUID-D8DB1C0F-2234-4991-AE63-CB72E3233103).

With running the command: `sudo yum install -y node-oracledb-node10` I get the following error:
`Loaded plugins: langpacks, ulninfo
No package node-oracledb-node10 available.
Error: Nothing to do`

After searching I tried the following:
`sudo yum install -y node-oracledb-node12`

With result:
```
Loaded plugins: langpacks, ulninfo
Resolving Dependencies
--> Running transaction check
---> Package node-oracledb-node12.x86_64 0:4.1.0-1.el7 will be installed
--> Processing Dependency: nodejs < 13 for package: node-oracledb-node12-4.1.0-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: node-oracledb-node12-4.1.0-1.el7.x86_64 (ol7_developer_nodejs12)
           Requires: nodejs < 13
           Installed: 1:nodejs-6.17.1-1.el7.x86_64 (@ol7_developer_EPEL)
               nodejs = 1:6.17.1-1.el7
           Available: nodejs-12.4.0-1.0.1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.4.0-1.0.1.el7
           Available: nodejs-12.16.1-1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.16.1-1.el7
           Available: nodejs-12.16.3-1.0.1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.16.3-1.0.1.el7
           Available: nodejs-12.17.0-1.0.1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.17.0-1.0.1.el7
           Available: nodejs-12.18.0-1.0.1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.18.0-1.0.1.el7
           Available: nodejs-12.18.1-1.0.1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.18.1-1.0.1.el7
           Available: nodejs-12.18.2-1.0.1.el7.x86_64 (ol7_developer_nodejs12)
               nodejs = 12.18.2-1.0.1.el7
           Available: 1:nodejs-6.14.3-1.el7.x86_64 (ol7_developer_EPEL)
               nodejs = 1:6.14.3-1.el7
           Available: 1:nodejs-6.16.0-1.el7.x86_64 (ol7_developer_EPEL)
               nodejs = 1:6.16.0-1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

What should I do?

**Comment by cjbj** [comment]
The Linux group (who own those packages) maintain this doc: http://yum.oracle.com/oracle-linux-nodejs.html It may be more up to date than the cloud doc, since they recently added Node.js 12.  And I see I need to update https://oracle.github.io/node-oracledb/INSTALL.html#instnoderpms too.

**Comment by cc13com** [comment]
Unfortunately the doc behind your first link is similar:

` For example, on Oracle Linux 7, the node-oracledb RPM for Node.js 10 is named:

node-oracledb-node10

$ sudo yum install node-oracledb-node10
`

With the same result on my machine.

**Comment by cjbj** [comment]
This installs 12.18 for me on an Always Free Cloud compute instance:
```
sudo yum install -y oracle-release-el7 oracle-nodejs-release-el7
sudo yum-config-manager --disable ol7_developer_EPEL
sudo yum install -y nodejs
```
Looks like the default Cloud yum repos is different (is older?) than a default OL7 system. 
How did I know to disable EPEL?  See example 1 of https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1

**Comment by cc13com** [comment]
Thanks @cjbj, that works for me.

**Comment by cjbj** [comment]
Thanks for the confirmation.

I've updated https://oracle.github.io/node-oracledb/INSTALL.html#instnoderpms to show disabling EPEL.  The Linux group will also update their node-oracledb instructions.  And I've sent a message to the Cloud doc owner.
