### ISSUE TITLE
question for large string insert

### ISSUE THREAD

**Issue by DOVER123** [oracle/node-oracledb#1277]
i have a quesiton about large string.

i read the  Documentation 18.4 
![图片](https://user-images.githubusercontent.com/17616876/87632424-f8557680-c76b-11ea-8457-28b4c18daa25.png)

if i have a large string,not from file,just string,how can i insert it into a table like  the way Documentation 18.4 do?

**Comment by cjbj** [comment]
Is the LOB smaller than 1 GB? See [18.1 Simple Insertion of LOBs](https://oracle.github.io/node-oracledb/doc/api.html#basiclobinsert).

**Comment by DOVER123** [comment]
> Is the LOB smaller than 1 GB? See [18.1 Simple Insertion of LOBs](https://oracle.github.io/node-oracledb/doc/api.html#basiclobinsert).

ok,18.1 works ,thank you
