### ISSUE TITLE
Error: ORA-12170: TNS:Connect timeout occurred { errorNum: 12170, offset: 0 }

### ISSUE THREAD

**Issue by manikandang14study** [oracle/node-oracledb#1279]
Hi,
I was able to connect to Oracle Cloud19c and XE from my windows machine ones (yesterday couple of times) but now I am getting the below error
[Error: ORA-12170: TNS:Connect timeout occurred] {
errorNum: 12170,
offset: 0
}

Code :
const oracle = require('oracledb');
const connection_local = await oracle.getConnection({
            user: "sys",
            password: 'password',
            connectString: "xe"
        });

TNS:

XE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )

Machine 
Version:
Node: 12.11.1
oracledb :^5.0.0

Note : I am able to connect to both the DBs from SQLPLUS.

I have XE running on my machine
I tried restarting my machine, server times, it doesn't work. Not sure what is happening . Any help will be appreciated.

thanks in advance.

**Comment by cjbj** [comment]
Does the error occur all the time? What kind of load is your app under?

**Comment by manikandang14study** [comment]
I just trying to connect to Oracle DB, get few records, process it and push it to Mongo.
Below is the sample connection function.

const sampleConnection = async () => {
    const oracle = require('oracledb');
    let connection_local;
    try {
        connection_local = await oracle.getConnection({
            user: "sys",
            password: 'Mani123',
            connectString: "XE"
        });
        console.log(connection_local);
    } catch (err) {
        console.log(err); 
    }
}
sampleConnection();

I am using XE tnsnames,sqlnet for both XE and Cloud.
