### ISSUE TITLE
rowsAffected is missing for "SELECT FOR UPDATE" queries (contrary to documentation)

### ISSUE THREAD

**Issue by dbausch-rea** [oracle/node-oracledb#1280]
**What versions are you using?**

 I'm using node-oracledb 4.2.0 but from the code I see that the problem is still present in 5.0.

 >>     process.platform
 >'linux'
 >>     process.version
 >'v12.18.2'
 >>     process.arch
 >'x64'
 >>     require('oracledb').versionString
 >'4.2.0'
 >>     require('oracledb').oracleClientVersionString
 >'19.6.0.0.0'

**Is it an error or a hang or a crash?**

It is an error. Documentation says explicitely that `rowsAffected` is available for "SELECT FOR UPDATE" queries, but it's not.

> 4.2.6.4.7 `rowsAffected`
>
> Number rowsAffected
>
> For [DML][14] statements (including SELECT FOR UPDATE) this contains
> the number of rows affected, for example the number of rows
> inserted. For non-DML statements such as queries and PL/SQL statements,
> `rowsAffected` is undefined.
>
> Due to Node.js type limitations, the largest value shown will be
> 2<sup>32</sup> - 1, even if more rows were affected.  Larger values will wrap.

**What error(s) or behavior you are seeing?**

`result.rowsAffected` is missing/undefined, because the query is treated like a read-only query because it has queryVars

This is the respective code section from njsConnection.cpp (function `njsConnection_executeAsync`)
```
    // for queries, initialize query variables
    if (baton->numQueryVars > 0) {

        baton->queryVars = calloc(baton->numQueryVars, sizeof(njsVariable));
        if (!baton->queryVars)
            return njsBaton_setError(baton, errInsufficientMemory);
        if (!njsVariable_initForQuery(baton->queryVars, baton->numQueryVars,
                baton->dpiStmtHandle, baton))
            return false;

    // for all other statements, determine the number of rows affected, process
    // variables (to manage LOBs, REF cursors, PL/SQL arrays, etc.) and process
    // implicit results
    } else {
        if (dpiStmt_getRowCount(baton->dpiStmtHandle,
                &baton->rowsAffected) < 0)
            return njsBaton_setErrorDPI(baton);
        baton->bufferRowIndex = 0;
        if (!njsVariable_process(baton->bindVars, baton->numBindVars, 1,
                baton))
            return false;
        if (!njsConnection_processImplicitResults(baton))
            return false;
    }
```

**Comment by cjbj** [comment]
@pvenkatraman is going to check if this is a doc or code issue.

**Comment by cjbj** [comment]
This was assessed to be a doc issue; I've fixed that. `rowsAffected` cannot be obtained from the OCI code for SELECT FOR UPDATE. Thanks for reporting it.
