### ISSUE TITLE
Error: NJS-005: invalid value for parameter 2

### ISSUE THREAD

**Issue by romulot** [oracle/node-oracledb#1281]
Hello,
I have a problem at the time of execution, when I try to put 2 parameters in the execute the error occurs, how would it be possible to pass two parameters?

Oracle version 5.0
Node Version: 12.18.3

Code:
```
RamusOracle.prototype.par = function(callback) {
    var rslt = new Object();
    (async function() {
      try{
         connection = await oracledb.getConnection({
              user : 'USER',
              password : 'PASS',
              connectString : 'CONNECT'
         });
         //console.log(getConnection);
         await connection.execute( RamusSQL, callback);
 
      } catch(err) {
          console.log("Error: ", err);
        } finally {
          if (connection) {
            try {
              await connection.close();
            } catch(err) {
              console.log("Error when closing the database connection: ", err);
            }
          }
        }
      })()
  
    
}
```

Error:  Error: NJS-005: invalid value for parameter 2

**Comment by romulot** [comment]
Delete the callback?
I need the callback to use the prototype

**Comment by pvenkatraman** [comment]
In that case, you can try not using async/await model.  Then oracledb.getConnection would also need callback.

**Comment by romulot** [comment]
Sorry I'm new to node, could you give me an example?

**Comment by romulot** [comment]
Error:  TypeError: connection.execute is not a function

`RamusOracle.prototype.par = function(callback) {
    var rslt = new Object();
    function s() {
      try{
         connection = await oracledb.getConnection({
              user : 'USER',
              password : 'PASS',
              connectString : 'CONNECT'
         });
         //console.log(getConnection);
         await connection.execute( RamusSQL, callback);
 
      } catch(err) {
          console.log("Error: ", err);
        } finally {
          if (connection) {
            try {
              await connection.close();
            } catch(err) {
              console.log("Error when closing the database connection: ", err);
            }
          }
        }
      s()
  
    
}`

**Comment by anthony-tuininga** [comment]
What @pvenkatraman is trying to say is that this line:

```
await connection.execute( RamusSQL, callback);
```

needs to be replaced by these lines:

```
await connection.execute(RamusSQL);
callback();
```

When using async/await you do not pass a callback through. You could also do this:

```
RamusOracle.prototype.par = async function() {
```

And then you wouldn't need to call the callback. Of course you'd have to adjust the calling code to use await -- so it depends on what you require.

**Comment by romulot** [comment]
I tried replaced
```
await connection.execute(RamusSQL);
callback();
```
but an error occurred
Error:  TypeError: callback is not a function

```
RamusOracle.prototype.par = function(callback) {
    var rslt = new Object();
    (async function() {
      try{
         connection = await oracledb.getConnection({
              user : 'USER',
              password : 'PASS',
              connectString : 'CONNECT'
         });
         //console.log(getConnection);
         await connection.execute( RamusSQL);
         callback();
      } catch(err) {
          console.log("Error: ", err);
        } finally {
          if (connection) {
            try {
              await connection.close();
            } catch(err) {
              console.log("Error when closing the database connection: ", err);
            }
          }
        }
      })()  
}
```

**Comment by anthony-tuininga** [comment]
What code are you using to call par() on RamusOracle? That suggests you're not passing a callback function but something else!

**Comment by romulot** [comment]
I used not passing the callback and it worked. thank you!
`RamusOracle.prototype.par = async function() {`

**Comment by anthony-tuininga** [comment]
Glad you got it worked out! I'm assuming your question is answered now and will close this -- but feel free to reopen if that was not the case!
