### ISSUE TITLE
Is it possible to create views with node-oracledb? Is there any examples?

### ISSUE THREAD

**Issue by dlabsz** [oracle/node-oracledb#1282]
1. What versions are you using?

2. Describe the problem

3. Include a runnable Node.js script that shows the problem.

**Comment by dlabsz** [comment]
oracledb versio5.00, I have tried to create view with node-oracledb by using union of oracle tables and then tried to use normal fetch using the generated view.

**Comment by cjbj** [comment]
Yes.

I suggest you get the SQL statements working in SQL*Plus or SQL Developer first, and then pass them to `execute()` like other SQL statements.  There's nothing magic, so there is no specific example.

SQL syntax is out of scope of this repo. You can ask at https://asktom.oracle.com/
