### ISSUE TITLE
How to fetch message_properties value from Oracle Advanced Queue

### ISSUE THREAD

**Issue by samuthan** [oracle/node-oracledb#1283]
1. What versions are you using?

Give your database version. 12.2

Also run node and show the output of:

    process.platform win32
    process.version 'v10.21.0'
    process.arch 'x64
    require('oracledb').versionString  4.2.0
    require('oracledb').oracleClientVersionString '19.3.0.0.0

2. Describe the problem

How to get the sender_id(Message_properties) value from Oracle Advanced Queue at the time of dequeue the message

3. Include a runnable Node.js script that shows the problem.

**Comment by cjbj** [comment]
Look at [aqobject.js](https://github.com/oracle/node-oracledb/blob/master/examples/aqobject.js).  You can edit `deq()`  to access properties directly like:
```
      console.log('Dequeued:  ', msg.payload.NAME);
```

If this isn't what you wanted, then please give a runnable testcase that creates a queue, and then enqueues & dequeues a message.

**Comment by samuthan** [comment]
This is not resolved my issue. Sure I will create the testcase and share it. 

Actually I am looking like below 

Functionality is Enqueue happened from PLSQL script with below properties. And Dequeue happened from Node JS application 

message_properties  DBMS_AQ.MESSAGE_PROPERTIES_T
message_properties.sender_id      := SYS.AQ$_AGENT(SYS_CONTEXT ('USERENV', 'SESSION_USER'), NULL, NULL);

In node JS application, i need to find the sender_id value available in Queue table

**Comment by lordvlad** [comment]
I'm having an similar case where I need the `enqueue_time`. `AdvancedQueueMessage<T>` only has a `delay` property, but it is always 0 for some reason. In the java libs we have `AQMessageProperty.getEnqueueTime()`

**Comment by cjbj** [comment]
@lordvlad could you open a new issue so we can track it as an enhancement request?

**Comment by lordvlad** [comment]
> [@lordvlad](https://github.com/lordvlad) could you open a new issue so we can track it as an enhancement request?

done https://github.com/oracle/node-oracledb/issues/1725
