### ISSUE TITLE
Bug while using integer in binding parameters

### ISSUE THREAD

**Issue by flpb** [oracle/node-oracledb#1284]
1. What versions are you using? oracledb 5.0.0
    Oracle 12c
    NODE VERSION: v12.18.3
    NPM VERSION: 6.14.6
    process.platform: linux
    process.version: v12.18.3
    process.arch: x64
    require('oracledb').versionString: 5.0.0
    require('oracledb').oracleClientVersionString: 19.8.0.0.0

2. Is it an error or a hang or a crash?
Crash

3. What error(s) or behavior you are seeing?
My process is crashing the cluster.. because of the oracledb binding parameter (when it's an integer).. you can reproduce by creating a simple table as follows:
-- create table oracledb
```
CREATE TABLE P_USER 
(	"ID" NUMBER(19,0) CONSTRAINT "USER_ID_PK" NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
         CONSTRAINT "USER_ID_PK" PRIMARY KEY ("ID")
);
```
-- insert a few names
```
INSERT INTO P_USER (Id, Name) Values (1, 'Felipe');
INSERT INTO P_USER (Id, Name) Values (1, 'Adrian');
INSERT INTO P_USER (Id, Status, Name) Values (1, 0, 'Newton');
COMMIT;
```

4. Include a runnable Node.js script that shows the problem.

```
const oracledb = require('oracledb');

const tableName = 'P_USER';
const user = 'USER_NAME';
const password = 'PASSWORD';
const host = 'HOST:PORT';
const databaseName = 'DB_NAME';

const searchForActiveUsersOracle = async () => {
  const connection = await oracledb.getConnection({
    user,
    password,
    connectString: `${host}/${databaseName}`
  });
  const result = await connection.execute(`SELECT * FROM ${tableName} WHERE Q.STATUS = :status`, { status: 1 });
  console.log('result: ', result);
  return result;
}
```

A few details on this..
If I use this whitout binding param => it works fine
If I use as a binding param but whit string `{ status: '1' }` => it works fine
The problem seems to always occur on the bindings with integer or decimal.

PS: I asked the same question on knex because I thought it was an error on their side (https://github.com/knex/knex/issues/3968), but today I tried to replicate the same without knex and came across the same problem.. so.. that's why I'm here..

Thanks in advance and sorry for poor english ^^

**Comment by cjbj** [comment]
It works for me (with changes such as removing the `Q.`). Output is like:

```
result:  {
  metaData: [ { name: 'ID' }, { name: 'STATUS' }, { name: 'NAME' } ],
  rows: [ [ 1, 1, 'Felipe' ], [ 1, 1, 'Adrian' ] ]
}
```

Is your exception handling complete?  Are you getting an unexpected value somewhere?
Is having a DB link (shown in the knex issue) relevant?

**Comment by flpb** [comment]
Yes it's relevant to use alias in my case in other parts of code.. of course for this short query is irelevant.. but for some of them not. Some will be using joins or uses dblink.. this was working fine on my previous code wich used `oracledb: "^2.3.0"` (i know a bit outdated huh?)

_Is your exception handling complete? Are you getting an unexpected value somewhere?_
Did you get any kind of error?

**Comment by flpb** [comment]
I just replaced by this..
```
try {
    const result = await connection.execute(`SELECT * FROM ${tableName} WHERE Q.STATUS = :status`, { status: 1 });
    console.log('result: ', result);
    return result;
  } catch (err) {
    console.log(err);
    return err;
  }
```
As you mentioned to try to get some kind of errors but it didn't help..

I tried to replace whitout the alias `Q.` (as you mentioned):
`const result = await connection.execute(`SELECT * FROM P_USER WHERE STATUS = :status`, { status: 1 });`
It's still getting the same result as before..
It only works with string in bind params or not use binding at all (raw query).

**Comment by cjbj** [comment]
You'll have to keep debugging and see what works and what doesn't, to try and get more information that might help determine the cause.

**Comment by flpb** [comment]
I am telling you.. It did not show any kind of log it suddenly stops.. for me the only thing that crashs **is** the binding param when it's a integer or a decimal.. you couldn't reproduce?

**Comment by cjbj** [comment]
Keep working on it and try and explain more.  What do you mean by crash? Is there any kind of error? Is there any Oracle trace generated?

**Comment by flpb** [comment]
I guess it could be something with my own environment.. or a problem using linux with instant client 19_8..
You tried that configuration - linux, instant client 19.8, npm and node at my versions?

I tried to use the **same code** with integer param on `windows` using the last instant client `19.6` it worked fine.. for basic and basic light instant clients..

The problem is still showing at linux (basic light or basic instant client 19_8 as described above).

ODPI [00016] 2020-08-11 12:13:18.330: ODPI-C 4.0.1
ODPI [00016] 2020-08-11 12:13:18.330: debugging messages initialized at level 64
ODPI [00016] 2020-08-11 12:13:18.338: Context Parameters:
ODPI [00016] 2020-08-11 12:13:18.338: Environment Variables:
ODPI [00016] 2020-08-11 12:13:18.338:     ORACLE_HOME => "/usr/lib/instantclient"
ODPI [00016] 2020-08-11 12:13:18.338:     TNS_ADMIN => "/usr/lib/instantclient"
ODPI [00016] 2020-08-11 12:13:18.338:     LD_LIBRARY_PATH => "/usr/lib/instantclient"
ODPI [00016] 2020-08-11 12:13:18.338: check module directory
ODPI [00016] 2020-08-11 12:13:18.338: module name is /app/node_modules/oracledb/build/Release/oracledb-5.0.0-linux-x64.node
ODPI [00016] 2020-08-11 12:13:18.339: load in dir /app/node_modules/oracledb/build/Release
ODPI [00016] 2020-08-11 12:13:18.339: load with name /app/node_modules/oracledb/build/Release/libclntsh.so
ODPI [00016] 2020-08-11 12:13:18.339: load by OS failure: Error loading shared library /app/node_modules/oracledb/build/Release/libclntsh.so: No such file or directory
ODPI [00016] 2020-08-11 12:13:18.339: load with OS search heuristics
ODPI [00016] 2020-08-11 12:13:18.340: load with name libclntsh.so
ODPI [00016] 2020-08-11 12:13:18.352: load by OS successful
ODPI [00016] 2020-08-11 12:13:18.352: validating loaded library

I'm trying to provide DEBUG information but I don't know how to trace..

There are something wrong with my linux environment that is actually not binding because of a especific lib?

**Comment by cjbj** [comment]
I tested on Linux with 19.8 instant client and I even managed to find a 12.2 DB.

DPI_DEBUG_LEVEL 64 is only for tracing library loading - and your library loaded fine.  Other levels are in the [ODPI-C documentation](https://oracle.github.io/odpi/doc/user_guide/debugging.html).

Can you:

- try other combinations (different client versions, different database).  
- give a complete, _runnable_ example instead of the snippets you provided.  Make the code create the tables, insert data, and then call your query.  You haven't said whether it actually reproduces without a db link or join - a testcase will clear this up for me.
- Try something like this (with your correct directory name): `rm -rf $HOME/instantclient/log/diag/clients && mkdir -p $HOME/instantclient/log/diag/clients` and see if there are trace files in a  `$HOME/instantclient/log/diag/clients/.../trace/` directory.  If you do this, you may want to remove the directory later, or make sure it does fill up with logs.

**Comment by flpb** [comment]
Well.. that was fun... We had to take a few steps back and try another docker image from dockerhub.. cause definetly It was a environment problem.. and I was the only one with this kind of problem.
Dockerhub has this image `alpine` https://hub.docker.com/_/alpine?tab=tags alpine version was 3.12.0
Wich i was using.. instaled the oracle library and instantclient..

Then We tried `FROM centos:7`
With the same isntant client 19.8 (instantclient-basiclite-linuxx64-19-8.zip) it worked fine..

We moved to the centos because we couldn't afford to try to solve what was wrong with alpine.. thank you for your time and cooperation on this.. :)

**Comment by cjbj** [comment]
I've [always recommended](https://stackoverflow.com/questions/53263972/oracle-on-alpine-linux/53291026#53291026) avoiding Alpine for exactly this kind of reason.  

I would query why use Centos when you could just as easily use Oracle Linux and get an OS that has actually been tested with the Oracle client software !  There are Oracle Linux Dockerfiles here: 

- https://github.com/oracle/docker-images/tree/master/OracleInstantClient 

and here:  
- https://github.com/oracle/docker-images/tree/master/OracleLinuxDevelopers/oraclelinux7/nodejs.  

Also see https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1

**Comment by hyamanieu** [comment]
> I've [always recommended](https://stackoverflow.com/questions/53263972/oracle-on-alpine-linux/53291026#53291026) avoiding Alpine for exactly this kind of reason.
> 
> I would query why use Centos when you could just as easily use Oracle Linux and get an OS that has actually been tested with the Oracle client software ! There are Oracle Linux Dockerfiles here:
> 
>     * https://github.com/oracle/docker-images/tree/master/OracleInstantClient
> 
> 
> and here:
> 
>     * https://github.com/oracle/docker-images/tree/master/OracleLinuxDevelopers/oraclelinux7/nodejs.
> 
> 
> Also see https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1

Your solution may be integrated in services having to talk with various servers, oracle sql being one among many. Just changing the whole architecture because Oracle says so is not a satisfying response. Similar comments came up under your stackoverflow post you're linking.
[It's not as if Alpine is not used: it's the top official image on docker hub with 1 billion+ downloads and almost 10 thousand stars.](https://hub.docker.com/search?image_filter=official&q=)

**Comment by cjbj** [comment]
@hyamanieu Alpine Linux is not a supported/tested OS.  It's the most different flavor to those we do test.  It's a platform that has the most instability. I would love for us to support it, but we don't. I would argue that a rational 'architecture' should take  operational requirements such as stability into account.
