### ISSUE TITLE
[Error: ORA-28040: No matching authentication protocol]

### ISSUE THREAD

**Issue by msreef** [oracle/node-oracledb#1286]
1. What versions are you using?
I don't know 100% the database version but when connecting in dbvis it says major db version is 19.

process.platform = win32
process.version = v10.16.3'
process.arch = x64
require('oracledb').versionString = '5.0.0'
require('oracledb').oracleClientVersionString = '11.2.0.1.0'

2. Describe the problem

I'm a complete Oracle noob and new to node/express as well so please excuse my ignorance.
I'm trying to connect to my work's Oracle test database for an express project that I'm working on. I can connect using a database viewer program in Windows (dbVisualizer), so the connection/credentials are correct, but I'm getting the error below when trying to set it up through node/express.
[Error: ORA-28040: No matching authentication protocol]

In my sqlnet.ora file:
```
SQLNET.AUTHENTICATION_SERVICES= (NONE)
NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT)
```

I'm connecting to TEST2, and the relevant line from my tnsnames.ora file is:
```
TEST2=
  (DESCRIPTION=
    (ADDRESS=
      (PROTOCOL=TCP)
      (HOST=xxxxxxxxxx.rds.amazonaws.com)
      (PORT=1521)
    )
    (CONNECT_DATA=
      (SERVICE_NAME=test2)
    )
  )
```

In my test.js file to test the connection

```
const oracledb = require('oracledb');

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;

const mypw = ''  // set mypw to the hr schema password

async function run() {

  let connection;

  try {
    connection = await oracledb.getConnection(  {
      user          : "xxxxxx",
      password      : "xxxxxxxxxx",
      connectString : "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=xxxxxxxxxxxxxds.amazonaws.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=test2)))"
    });

    const result = await connection.execute(
      'SELECT * FROM organisation'
    );
    console.log(result.rows);

  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

run();
```

From what I understand this is a authentication issue, but I don't know if it's something I can fix on my client end or if it has to be done on the server.

**Comment by cjbj** [comment]
At a guess, try upgrading your Oracle client libraries (from 11.2.0.1).  Check the https://oracle.github.io/node-oracledb/INSTALL.html and ask questions as needed.  I'd probably try using [Instant Client](https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html) and then pass the Instant Client directory to the initOracleClient() method, but I don't know your system or requirements.

**Comment by msreef** [comment]
Thanks for your tip, I upgraded my software to version 19 (using this link https://www.oracle.com/database/technologies/oracle19c-windows-downloads.html) and that has fixed the issue.
