### ISSUE TITLE
Segfaulting Randomly

### ISSUE THREAD

**Issue by BlenderDude** [oracle/node-oracledb#1287]
Issue Versions:
```
Oracle Database version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
PLATFORM        linux
VERSION v10.18.1
ARCH    x64
ORACLE VERSION  5.0.0
ORACLE CLIENT VERSION   19.8.0.0.0
```

Error type: Segfault Error

Behavior: At random times, the oracledb library will segfault and doesn't give me any meaningful output.

Reproducibility: Not sure how to give a runnable version of code, but really what I'm looking for is some insight into the segfault stack. Using the `segfault-handler` library, I was able to extract where the segfault was occurring in the client library. Here is the stack I was given.

```
[
'/app/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x303f) [0x7f4ff84d703f]',
'/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0) [0x7f4ffaa8d0e0]',
'/usr/lib/oracle/19.8/client64/lib/libclntsh.so(kgrdub2c+0x11) [0x7f4fda46ec31]',
'/usr/lib/oracle/19.8/client64/lib/libclntsh.so(kpuubrid2c+0x3a) [0x7f4fd9512e3a]',
'/app/node_modules/oracledb/build/Release/oracledb-5.0.0-linux-x64.node(dpiOci__rowidToChar+0x45) [0x7f4ff82a0025]',
'/app/node_modules/oracledb/build/Release/oracledb-5.0.0-linux-x64.node(dpiRowid_getStringValue+0xec) [0x7f4ff82a709c]',
'/app/node_modules/oracledb/build/Release/oracledb-5.0.0-linux-x64.node(njsVariable_getScalarValue+0x229) [0x7f4ff8289449]',
'/app/node_modules/oracledb/build/Release/oracledb-5.0.0-linux-x64.node(+0x2603e) [0x7f4ff828203e]',
'/app/node_modules/oracledb/build/Release/oracledb-5.0.0-linux-x64.node(+0x191e7) [0x7f4ff82751e7]',
'/usr/local/bin/node() [0x90620c]',
'/usr/local/bin/node() [0xa6b2b5]',
'/usr/local/bin/node() [0xa6f65f]',
'/usr/local/bin/node() [0xa80f08]',
'/usr/local/bin/node(uv_run+0x14b) [0xa6ff9b]',
'/usr/local/bin/node(_ZN4node5StartEPN2v87IsolateEPNS_11IsolateDataERKSt6vectorISsSaISsEES9_+0x565) [0x9045d5]',
'/usr/local/bin/node(_ZN4node5StartEiPPc+0x48f) [0x90285f]',
'/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f4ffa6fd2e1]',
'/usr/local/bin/node() [0x8bbe95]' 
]
```

It appears to be something in the `rowidToChar` function, but I have no idea what is causing it. If anyone has some insight into what might be the problem, I could find a way to reproduce it in an isolated test. Without knowledge of what's causing the crash, I have no way of isolating the problem.

**Comment by anthony-tuininga** [comment]
This may be due to a optimization bug. @cjbj can give you the environment variable to set to avoid it. Or you can avoid selecting the same rowid multiple times.

**Comment by BlenderDude** [comment]
@anthony-tuininga Thanks, it seems like the view that was created for this project has duplicate row id's baked into its design...so hopefully the environment variable will fix the problem and I won't have to bug the DBAs.

**Comment by cjbj** [comment]
See if https://github.com/oracle/python-cx_Oracle/issues/315#issuecomment-498710438 helps - try setting the environment variable ORA_OCI_NO_OPTIMIZED_FETCH to 1.  If it does help, the good news is that the base bug was recently fixed and will be in the next major release of Oracle libraries.  If anyone wants to ask Oracle Support for a backport, refer to bug 26225722.

**Comment by BlenderDude** [comment]
@cjbj The environment variable seemed to fix the issue. Is there any ETA on the next major version's release?

**Comment by cjbj** [comment]
@BlenderDude thanks for the confirmation that the work-around works.  The time-range I'm allowed to quote about the future release is too vague to be helpful.
