### ISSUE TITLE
oracledb 4.2 /  oracledb.initOracleClient is not a function

### ISSUE THREAD

**Issue by eboats** [oracle/node-oracledb#1288]
1. What versions are you using?

Give your database version.  12.2

    process.platform   darwin
    process.version      v8.16.1
    process.arch          x64
    require('oracledb').versionString     4.2.0
    require('oracledb').oracleClientVersionString   19.3.0.0.0

2. Describe the problem

Since my application is on node 8.16, am trying to use your oracledb 4.2 (since apparently 5.0 isn't supported for node 8).  I've put my sqlnet.ora file in a ../db/oracle dir and am using 
``` 
oracledb.initOracleClient({configDir: '../db/oracle'})  
```
to tell oracledb where to find my sqlnet.ora but am getting error "oracledb.initOracleClient is not a function".   Was there some other way to specify a sqlnet.ora file location in oracledb 4.2?   Basically, when I try to do a pool.close, it's hanging so your docs say to create a sqlnet.ora file that includes  DISABLE_OOB=on 

3. Include a runnable Node.js script that shows the problem.

**Comment by cjbj** [comment]
Set TNS_ADMIN to the directory where your sqlnet.ora is. see https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin:

> If initOracleClient() is not called, or it is called but configDir is not set, then default directories are searched for the configuration files. They include:
> 
> - $TNS_ADMIN
> - /opt/oracle/instantclient_19_6/network/admin if Instant Client is in /opt/oracle/instantclient_19_6.
> - /usr/lib/oracle/19.6/client64/lib/network/admin if Oracle 19.6 Instant Client RPMs are used on Linux.
> - $ORACLE_HOME/network/admin if node-oracledb is using libraries from the database installation.

initOracleClient() was new in 5.0 so it won't be available in 4.2.

node-oracledb 5.0 installs and 'runs' on 8.16 but we didn't do any release testing with that combination.

**Comment by eboats** [comment]
Thanks so much for the fast response!  I've tried setting TNS_ADMIN to the dir where my sqlnet.ora is but am still seeing that the pool close is hanging.  The sqlnet.ora just includes DISABLE_OOB=on.

The oracledb.getPool() returns quickly but the close call hangs.

await oracledb.getPool().close(10);

I have to kill the process to shutdown node.  Any ideas about how to resolve?  Thanks again.

**Comment by cjbj** [comment]
"prove it" :) Give us a runnable code file that reproduces the problem.  Show how you are setting TNS_ADMIN.  Give us your exact sqlnet.ora contents. Give us your DB version.  Give us a pstack or similar to show the stack in the hung process.
