### ISSUE TITLE
How to make executemany command faster

### ISSUE THREAD

**Issue by binlu999** [oracle/node-oracledb#1293]
We are using node.js to call oracle database stored procedure. The code segment is:

```javascript
        let spName = config.TARGET_IMPORT_SP_NAME
        let plsql = `CALL ${spName} (:input, :output)`;
        const options = {
            bindDefs: [
              { type: "OCS_ADMIN.SP_I_WML_ROUTE"  },
              { dir: oracledb.BIND_OUT , type: "DB_TYPE_NAME"  },
            ]
          }; 
        let startTime = (new Date()).getTime();
        log.info(" Start DB call %s", startTime);
        **const result = await connection.executeMany(plsql, binds,options);**
        let endTime = (new Date()).getTime();
        log.info(" End DB call %s", endTime);
        log.info("Duration of DB execution %s ", endTime - startTime);
        log.info(`Oracle result: `+JSON.stringify(result));
```

The  execution time connection.executeMany is about 1.8 seconds. However, we have a python implementation with exactly same logic, same loading, same run time environment and same database setting, the python execute the same stored procedure only in 200 ms. Is there anyway I can change to make executeMany faster?
Thanks

**Comment by anthony-tuininga** [comment]
Is this difference from #292?

**Comment by anthony-tuininga** [comment]
> Hi Anthony,
> It is a different issue. We are using Oracle 11g and oracle instantclient 19.1.

Sorry, I got the wrong issue number. I meant #1292!

**Comment by binlu999** [comment]
Yes. It is same issue. I created that as Enhancement which I thought is not correct.

**Comment by anthony-tuininga** [comment]
Ok. I'll close this one, then, and change the label on the other one to be a question instead of an enhancement.
