### ISSUE TITLE
node oracleDB to use kerberos authentication to connect to DB

### ISSUE THREAD

**Issue by divyamvpandian** [oracle/node-oracledb#1296]
Hi All,
Am using nodeJS for a graphQL application and use node-oracleDB to make a DB connection using username and pwd and want to see if i can use same lib to connect DB via kerberos,

**Comment by perpetualv** [comment]
What are you using to make the database connection? Full Oracle client install, JDBC connection, Instant client?

**Comment by divyamvpandian** [comment]
I am using full oracle client install

**Comment by perpetualv** [comment]
in that case you SHOULD be able to use the same library - the full client does include the kerberos libraries.

**Comment by perpetualv** [comment]
There are some decisions you'll need to make up-front
- where are you going to store the Kerberos ticket (in most cases I let the OS libraries take care of that, put it in the default directory)
- how are you going to retrieve the ticket and periodically refresh it - most KDCs have a time-to-live assigned. Usually it's 8-hours but I've seen everything from one-hour to 24-hour auto renewing

**Comment by divyamvpandian** [comment]
I have a kerberos tkt but while making a connection from node using oracledb, i don't see any way of providing krb cc file path or to indicate it has to be a kerberos auth

**Comment by cjbj** [comment]
@perpetualv is the expert, but assuming the [Oracle doc ](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-9C4553E5-59ED-418E-B2B5-13E2E55B5E65)is correct in saying you connect SQL*Plus like:

    $ sqlplus /@net_service_name

then in node-oracledb try using [`externalAuth`](https://oracle.github.io/node-oracledb/doc/api.html#propdbisexternalauth) like:

```
const config = { connectString: "net_service_name", externalAuth: true };
const connection = await oracledb.getConnection(config);
```

**Comment by divyamvpandian** [comment]
@perpetualv @cjbj 

Thank you very much. It worked. Also I had to point TNS_ADMIN properly where sqlnet ora is present with KERB config.

**Comment by cjbj** [comment]
@divyamvpandian thanks for the feedback.  If you care to share more details I would love to update the node-oracledb doc.

**Comment by divyamvpandian** [comment]
Sure, we had kerberos initialized in the box where oracle client is installed and node App deployed. I made sure below points

1) TNSNAMES.ora to have proper connection string info for the service name.
 
2) sqlnet.ora to have proper kerberos config as below
SQLNET.KERBEROS5_CC_NAME=pathname_to_credentials_cache_file
SQLNET.KERBEROS5_CONF=pathname_to_Kerberos_configuration_file
SQLNET.KERBEROS5_CONF_MIT=TRUE 
SQLNET.AUTHENTICATION_SERVICES=(BEQ,KERBEROS5)

 3) Env variable TNS_ADMIN with path where tnsnames and sqlnet ora file present. LD_LIBRARY_PATH set to Oracle client lib folder

4) And then below config and connection worked in nodeJs app.

const config = { connectString: "net_service_name", externalAuth: true };
const connection = await oracledb.getConnection(config);

**Comment by cjbj** [comment]
@divyamvpandian thank you for the information.  I'm sure it will help other users.

Regarding point 3, if you were able to put the files in the network/admin subdirectory of Instant Client then you wouldn't need to set TNS_ADMIN.  I'd recommend using `ldconfig` to set the library search path instead of LD_LIBRARY_PATH, if possible.
