### ISSUE TITLE
Are nested cursors with unions supported?

### ISSUE THREAD

**Issue by maelswarm** [oracle/node-oracledb#1297]
Only occurs with node-oracledb (SQL works in SQLDeveloper)

1. What versions are you using?

    Oracle Database 11g Release 11.2.0.1.0 - 64bit Production
    PL/SQL Release 11.2.0.1.0 - Production
    "CORE	11.2.0.1.0	Production"
    TNS for Linux: Version 11.2.0.1.0 - Production
    NLSRTL Version 11.2.0.1.0 - Production

    win32
    v12.18.1
    x64
    5.0.0
    12.2.0.1.0

2. Is it an error or a hang or a crash?

    Error

3. What error(s) or behavior you are seeing?

    ``` Error: DPI-1028: query position 5 is invalid ```

```js
    const sql = `
      select 'ORDTL' as table_name, table_changes_trimmed('ORDTL') as data from dual union select 'ORHDR' as table_name, table_changes_trimmed('ORHDR') as data from dual
    `;
```

4. Include a runnable Node.js script that shows the problem.

```js
    const conn = await OracleDB.getConnection(config.get('database.pool.alias'));

    const sql = `
      select 'ORDTL' as table_name, table_changes_trimmed('ORDTL') as data from dual union select 'ORHDR' as table_name, table_changes_trimmed('ORHDR') as data from dual
    `;
    const binds: OracleDB.BindParameters = {};

    const result: any = await conn.execute(sql, binds);
```

**Comment by cjbj** [comment]
Start by checking the [manual](https://oracle.github.io/node-oracledb/doc/api.html#refcursors):  `BIND_OUT_CURSOR` isn't a node-oracledb constant.

**Comment by cjbj** [comment]
I see you've edited the question.  What about giving a _runnable_ test case?

**Comment by maelswarm** [comment]
@cjbj 
Are nested cursors with unions supported?
I'm finding I only receive the given error when using them.

**Comment by anthony-tuininga** [comment]
Please provide a runnable test case. Nested cursors with unions are supported...so if you are getting an error we need to know what you are trying to do!
