### ISSUE TITLE
Error on CentOS

### ISSUE THREAD

**Issue by temochutlashvili** [oracle/node-oracledb#1299]
1. CentOS 7 = 3.10.0-1062.el7.x86_64
    Oracle DB 12c

    process.platform = 'linux'
    process.version = 'v12.18.4'
    process.arch = 'x64'
    require('oracledb').versionString = '5.0.0' (also tried with 4.2.0)
    require('oracledb').oracleClientVersionString = '12.1.0.2.0' ( tried with 18.1)

2. The problem

When i run following script:

```
const oracledb = require('oracledb');

const dbConfig = {
    user: 'user',
    password: 'pass',
    connectString: 'database:port/orcl'
}

const connection = await oracledb.getConnection(dbConfig);
```
im getting the following error:

[Error: ORA-00604: error occurred at recursive SQL level 1
ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at line 5] {
  errorNum: 604,
  offset: 0
}

it only happens on CentOS machine, everything ok with same node versions etc. on Ubuntu, Windows.

**Comment by anthony-tuininga** [comment]
This is happening during the `oracledb.getConnection()` call? Can you confirm by setting the environment variable `DPI_DEBUG_LEVEL` to the value 4 and then rerun your script?

**Comment by temochutlashvili** [comment]
Output:
```
ODPI [30065] 2020-09-16 16:06:34.332: ODPI-C 4.0.1
ODPI [30065] 2020-09-16 16:06:34.332: debugging messages initialized at level 4
ODPI [30065] 2020-09-16 16:06:34.337: fn start dpiContext_createWithParams
ODPI [30065] 2020-09-16 16:06:34.355: fn end dpiContext_createWithParams -> 0
ODPI [30074] 2020-09-16 16:06:34.355: fn start dpiContext_initConnCreateParams(0x48f2660)
ODPI [30074] 2020-09-16 16:06:34.355: fn end dpiContext_initConnCreateParams(0x48f2660) -> 0
ODPI [30074] 2020-09-16 16:06:34.355: fn start dpiContext_initCommonCreateParams(0x48f2660)
ODPI [30074] 2020-09-16 16:06:34.355: fn end dpiContext_initCommonCreateParams(0x48f2660) -> 0
ODPI [30074] 2020-09-16 16:06:34.355: fn start dpiConn_create(0x48f2660)
ODPI [30074] 2020-09-16 16:06:39.676: fn end dpiConn_create(0x48f2660) -> -1
[Error: ORA-00604: error occurred at recursive SQL level 1
ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at line 5] {
  errorNum: 604,
  offset: 0
}
ODPI [30065] 2020-09-16 16:06:39.687: fn start dpiContext_destroy(0x48f2660)
ODPI [30065] 2020-09-16 16:06:39.687: fn end dpiContext_destroy(0x48f2660) -> 0
```

**Comment by anthony-tuininga** [comment]
Yep. That's where it is happening. Do you have a logon trigger or something equivalent?

**Comment by temochutlashvili** [comment]
Tbh, im not aware of any, cant tell if there is one, since im not admin of the database.

If there is one why it gives error on this particular system?

**Comment by anthony-tuininga** [comment]
It could be due to the fact that an element of the environment is different on CentOS and the logon trigger is not taking that into account. You can try connecting via SQL*Plus on CentOS as well. That uses the same Oracle Client libraries.

**Comment by temochutlashvili** [comment]
Got the same using sqlplus.

So i guess this is not an this package issue.

**Comment by anthony-tuininga** [comment]
Right. You'll have to ask the administrator of the database to look into the situation. I'll close this, then.

**Comment by temochutlashvili** [comment]
Thank you for fast response
