### ISSUE TITLE
getRow is undefined,when we use resutlSet in the option(parameter) of execute method

### ISSUE THREAD

**Issue by Dravidamsandeep** [oracle/node-oracledb#1301]
let  traverseResults = async (resultSet)=> {
            console.log(resultSet)
            const fetchedRows = [];
            while (true) {
              const row = await resultSet.getRow();
              if (!row)
                break;
              for (let i = 0; i < row.length; i++) {
                if (row[i] instanceof oracledb.ResultSet) {
                  const rs = row[i];
                  row[i] = await traverseResults(rs); // replace a cursor with its expansion
                  await rs.close();
                }
              }
              fetchedRows.push(row);
            }
            return fetchedRows;
          }
  let  conn = await oracledb.getConnection(pollAliasName');
        const fetchedResult =  await  conn.execute(query,paramsForQuery,{resultSet: true}); 
        const result= await traverseResults(fetchedResult.resultSet);     
        await fetchedResult.resultSet.close();   

-my connection eshtablished and absolute fine,
-paramsForQuery is hold the parameters.

is that mandatory , params should be empty array or [],when we use resultSet ?

**Comment by cjbj** [comment]
It makes answering quicker if we get code that we can run with `node x.js`.  And if the [issue logging template](https://raw.githubusercontent.com/oracle/node-oracledb/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md) is filled in.  Thanks!
