### ISSUE TITLE
Getting Error number 1400 offset 513. what is the cause of this error

### ISSUE THREAD

**Issue by runslow917** [oracle/node-oracledb#1302]
Hi . I am running executeMany() method to bulk insert But  getting the below error and not understanding where the issue is.
```
connection.executeMany(query,bindParams, { ...options, autoCommit: true }, (err, result) => {
                    connection.release();
                    if (!err) {
                        logger.debug({"query_output":JSON.stringify(result)});
                        let data = result.rows ? result.rows : result;
                        resolve({ 'status': 'OK', 'data': data });
                    }
                    else {
                        logger.error('error while getting the result in bulk', { err });
                        resolve({ 'status': 'ERROR', 'error': err });
                    }
                });
```
I have checked the query and bindParams(by position, array of arrays) are proper . Not understanding below error output which i'm getting

`{"err":{"errorNum":1400,"offset":513},"level":"error","message":"error while getting the result in bulk","timestamp":"2020-09-21 19:31:52"}`

Please let me know what is causing this error and how to resolve it. Thanks

**Comment by anthony-tuininga** [comment]
You're missing key information provided in the error -- namely the error mesage. Perhaps just use `console.log()` to print out the results of the error first? Error 1400 is "cannot insert NULL into <some_object>". That suggests you are trying to pass a null value into your executeMany() and the database is rejecting this data.

How many rows are you trying to insert? For executeMany(), the offset is the row number (0-based) at which the error took place. You can use batch errors to avoid getting the exception and then look at the results and determine what to do. See the [documentation](https://oracle.github.io/node-oracledb/doc/api.html#handlingbatcherrors) for more details on this.
