### ISSUE TITLE
Nested cursor resultSet from a PL/SQL stored procedure 

### ISSUE THREAD

**Issue by shyamavedham** [oracle/node-oracledb#1303]
Hi, I am writing a rest api to call a PL/SQLstored procedure which returns a nested cursor. I am able to fetch the outer cursor very quickly using quertyToStream(). Can someone please help me in fetching the inner cursors.
My Stored procedure call is like “BEGIN :x = stored_proc_1(:y, :z); END;”. :x is a cursor with 5 normal columns and 2 cursors like this.
Select col1, col2 , col3……, cursor (select col 11, col12 from t1) nested_cursor_1, cursor (select col 11, col12 from t2) nested_cursor_2 from t3;

**Comment by cjbj** [comment]
In your streaming code, check whether each item's datatype is `instanceof oracledb.ResultSet`.  If it is, then it is a nested cursor.  You can convert that RS to another stream with [resultset.toQueryStream()](https://oracle.github.io/node-oracledb/doc/api.html#toquerystream).
