### ISSUE TITLE
Periodic timeouts getting db connection 

### ISSUE THREAD

**Issue by eboats** [oracle/node-oracledb#1305]
1. What versions are you using?

Give your database version.   12.2

Also run node and show the output of:

    process.platform     linux
    process.version       v8.17.0
    process.arch
    require('oracledb').versionString    4.2.0
    require('oracledb').oracleClientVersionString    19.8.0.0.0

2. Describe the problem

Sporadic timeouts getting a TCPS database connection from node 8 express REST service running in aws kubernetes container.  Using a connection pool with  min =1, max 4, poolIncrement =1, pingPoolInterval = 60.   Db is set up with TLS and am using a Oracle Wallet and custom sqlnet.ora file ( pasted below).  I've noticed a few ORA - 25408 in logs.

Db connectivity works fine for a few hours after deployment, but then occasional hanging/timeouts occur.  It appears that connections are geting lost or disconnected, or become stale in pool?  Am using the default UV_THREADPOOL_SIZE env value. Do I need to increase that or any other params I can set to avoid lost connections that result in service timeouts?  I'm using a slightly older version of your library since my service is still on Node 8. 

3. Include a runnable Node.js script that shows the problem.

Code that creates db connection pool :
```
const config = require('config');
const oracledb = require('oracledb');
const dbConfig = config.get("database_mc");

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;


const closePoolAndExit = async () => {
  logger.info('Oracle connection pool terminating');
  try {
    await oracledb.getPool().close(10);
    logger.info('Oracle connection pool closed');
    process.exit(0);
  } catch(e) {
      logger.error('Error closing Oracle connection pool ' + e);
      process.exit(1);
  }
}

const init = async () => {
    try {
      logger.info(`Attempting to create Oracle connection pool for connectString: ${dbConfig.connectString}`);
      await oracledb.createPool({
        user          : dbConfig.username,
        password      : dbConfig.password,
        connectString : dbConfig.connectString,
        poolMin       : dbConfig.poolMin,
        poolMax       : dbConfig.poolMax,
        poolIncrement : dbConfig.poolIncrement,
        poolPingInterval: dbConfig.poolPingInterval
      });
  
     logger.info(`Oracle connection pool created for connectString: ${dbConfig.connectString}`);

    } catch (e) {
        logger.error('Error creating Oracle connection pool: ' + e);
        throw e;
    }
}

process
  .once('SIGTERM', closePoolAndExit)
  .once('SIGINT',  closePoolAndExit);

init();

module.exports = {
  getConnection: () => oracledb.getConnection(),
  getPool: () => oracledb.getPool()
}
```
Code that uses db connection pool 
```
const oracle = require('./../utils/oracle');

async function getMcInfoByConsumerId(barId) {

  let conn;
  try {
    logger.debug(`getMcInfoByConsumerId  - pool connection in use: ${oracle.getPool().connectionsInUse}`);
    logger.debug(`getMcInfoByConsumerId - pool connection open: ${oracle.getPool().connectionsOpen}`);
    conn = await oracle.getConnection();
    logger.debug('getMcInfoByConsumerId - got oracle connection');

    const result = await conn.execute(
      `SELECT *
       FROM FOO.MKTNG_TBL
       WHERE MKTNG_ID = :barId
       AND IS_LATEST_IND = 'Y'`,
      [barId]
    );
    return result ? result.rows : '';

  } catch (e) {
    logger.error('Error in getMcInfoByConsumerId: ' + e);
    throw e;
  } finally {
    if (conn) {
      try {
        logger.debug('attempting to close oracle connection');
        await conn.close();  // release the connnection back to the pool
        logger.debug('getMcInfoByConsumerId - Oracle Connection released back to pool');
      } catch (e) {
        logger.error('Error in getMcInfoByConsumerId releasing db connection: ' + e);
      }
    }
  }
}
```
Contents of sqlnet.ora file
```
DISABLE_OOB=on

WALLET_LOCATION =
             (SOURCE =
                 (METHOD = FILE)
                 (METHOD_DATA =
                        (DIRECTORY = /usr/src/app/db/oracle/$NODE_ENV)
                   )
              )
SQLNET.AUTHENTICATION_SERVICES = (TCPS,BEQ,NTS)
SSL_CLIENT_AUTHENTICATION=FALSE
SSL_VERSION = 1.0
SSL_CIPHER_SUITES = (SSL_RSA_WITH_AES_256_CBC_SHA)

SQLNET.EXPIRE_TIME=10
```

Include all SQL needed to create the database schema.

Use a gist for long code: see https://gist.github.com/

Format code by using three backticks on a line before and after code snippets, for example:

**Comment by cjbj** [comment]
What call is throwing the error?  What are the pool stats like?

Are you using DRCP?  Are you using a DB network service that has AC or TAC enabled? What about TAF?

You probably saw https://github.com/oracle/node-oracledb/issues/1304#issuecomment-705863144 Note the comment about  sqlnet.expire_time.  Also see https://oracle.github.io/node-oracledb/doc/api.html#connectionpremclose 

Since your poolMax is 4, you theoretically don't need to bump UV_THREADPOOL_SIZE.  Doing so is unlikely to help resolve your issue.  But it wouldn't hurt to have it a bit bigger in case the app is trying to do DB and non-DB work at the same time.

You might need to do some network tracing and get someone to look at the logs.  @onmp is our Net contact (thought @perpetualv also seems to have some skills!)  For anything complex, working through Oracle Support is the best since they are set up to handle this.

**Comment by eboats** [comment]
Thanks so much for the response!  I got answers on a few questions :  not using DHCP, and AC/TAC is not enabled.  No TAF enabled in the current TNS entry.

The odd thing is that we don't have any problems in our development environment - the issues only started occuring when promoting to a pre-prod test env, so does seem environment related. 

A few questions:
- I'm using the instantclient-basiclite-linux.x64-19.8.0.0.0dbru.zip for our setup, would it help to try the full instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instead?
- Would setting the poolPingInterval to something less than 60 secs be a good idea?

The pool stats from a particulary bad period are below.  The most recent problems occurred over a 30 minute period and then seemed to resolve after that in this case. 

2020-10-09T10:36:43.845-07:00
Pool statistics:
19
2020-10-09T10:36:43.845-07:00
...total up time (milliseconds): 3696672
20
2020-10-09T10:36:43.845-07:00
...total connection requests: 17
21
2020-10-09T10:36:43.845-07:00
...total requests enqueued: 10
22
2020-10-09T10:36:43.845-07:00
...total requests dequeued: 0
23
2020-10-09T10:36:43.845-07:00
...total requests failed: 0
24
2020-10-09T10:36:43.845-07:00
...total request timeouts: 10
25
2020-10-09T10:36:43.845-07:00
...max queue length: 5
26
2020-10-09T10:36:43.845-07:00
...sum of time in queue (milliseconds): 600005
27
2020-10-09T10:36:43.845-07:00
...min time in queue (milliseconds): 0
28
2020-10-09T10:36:43.845-07:00
...max time in queue (milliseconds): 0
29
2020-10-09T10:36:43.845-07:00
...avg time in queue (milliseconds): 60001
30
2020-10-09T10:36:43.845-07:00
...pool connections in use: 4
31
2020-10-09T10:36:43.845-07:00
...pool connections open: 4
32
2020-10-09T10:36:43.845-07:00
Related pool attributes:
33
2020-10-09T10:36:43.845-07:00
...poolAlias: default
