### ISSUE TITLE
Date returning wrong value

### ISSUE THREAD

**Issue by JasonMan34** [oracle/node-oracledb#1306]
1. What versions are you using?
Node v12.16.1
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production

* process.platform - win32
* process.version - v12.16.1
* process.arch - x64
* require('oracledb').versionString - 5.0.0
* require('oracledb').oracleClientVersionString - 19.6.0.0.0

2. Is it an error or a hang or a crash?
Error

3. What error(s) or behavior you are seeing?

I have a date column in my DB. When querying it with SQLDeveloper like so
```sql
SELECT some_date as "Some date",
       cast(some_date as timestamp) at time zone 'UTC' as "Some date UTC"
FROM mytable
FETCH NEXT 1 ROWS ONLY;
```
I get back:  
| Some date | Some date UTC |
|-|-|
| 10-11-2017 00:00:00 | 09-NOV-17 10.00.00.000000000 PM UTC |

![image](https://user-images.githubusercontent.com/13543641/95779871-8988aa80-0cd3-11eb-8a00-b164db2e0660.png)

When running this code in Node:
```js
const oracledb = require('oracledb');

const dbConfig = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  connectString: process.env.DB_TNSNAME,
};

oracledb.getConnection(dbConfig).then(async conn => {
  const result = await conn.execute('SELECT some_date FROM mytable FETCH NEXT 1 ROWS ONLY');
  console.log(result.rows[0][0]);
});
```

I get this output: `2017-11-09T21:00:00.000Z`  
And when converting this date to local time, for example with moment:
```js
console.log(moment(date).format('YYYY/MM/DD HH:mm:ss'));
```
I get `2017/11/09 23:00:00`

So basically, it seems the date I get when querying the DB through JS is 1 hour behind the date when querying through SQL developer.  
I suspect this has something to do with NOV-09 being regular time (so my local time is GMT+2) and the fact that it's currently DST (my local time is GMT+3), but how do I actually fix this?

4. Include a runnable Node.js script that shows the problem.

Creating the database:
```sql
ALTER DATABASE SET TIME_ZONE = '+00:00';
ALTER SESSION SET TIME_ZONE='Asia/Jerusalem';
CREATE TABLE repro_date_bug_table ("some_date" DATE);
INSERT INTO repro_date_bug_table VALUES(TO_DATE('10-11-2017 00:00:00', 'DD-MM-YYYY HH:mm:ss'));

-- Should resolve to:
-- Some date:       10-11-2018 00:00:00 (Using 'DD-MM-YYYY HH24:MI:SS' NLS Date format)
-- Some date UTC:   09-NOV-17 10.00.00.000000000 PM UTC
SELECT some_date as "Some date",
       cast(some_date as timestamp) at time zone 'UTC' as "Some date UTC"
FROM repro_date_bug_table
FETCH NEXT 1 ROWS ONLY;
```

Repro code:
```js
const oracledb = require('oracledb');

const dbConfig = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  connectString: process.env.DB_TNSNAME,
};

oracledb.getConnection(dbConfig).then(async conn => {
  const result = await conn.execute('SELECT some_date FROM repro_date_bug_table FETCH NEXT 1 ROWS ONLY');
  console.log(result.rows[0][0]);
});
```

**Comment by cjbj** [comment]
Must be a bug in SQL Developer then? :)

Your test case doesn't show the Oracle 'session' timezone being set.  Start by adding something like `process.env.ORA_SDTZ = 'Asia/Jerusalem';` to the top of your script, see [example.js](https://github.com/oracle/node-oracledb/blob/master/examples/example.js).  Also review the doc [Fetching Dates and Timestamps](https://oracle.github.io/node-oracledb/doc/api.html#datehandling).

Let us know if this helps.

**Comment by JasonMan34** [comment]
`process.env.ORA_SDTZ = 'Asia/Jerusalem';`

This did solve the problem. Thank you. But now my question is why, and what are the implications of it  
I thought that everything on the DB is saved in UTC, so no matter what my session timezone is, the date will be fetched in UTC, then be converted to my timezone if needed. So no matter which timezone I'm in, I would expect to get `09-NOV-17 10.00.00.000000000 PM UTC`, or rather the JavaScript equivalent `2017-11-09T22:00:00.000Z`

Why does changing the session timezone in my Node program change the value of the fetched date's ISO string?

**Comment by cjbj** [comment]
Dates are fetched as TIMESTAMP WITH LOCAL TIME ZONE.  Check the doc link above, and the references at the foot of that doc section.
