### ISSUE TITLE
Appending duplicate column names with "_1" etc like Oracle SQL Developer

### ISSUE THREAD

**Issue by amroczeK** [oracle/node-oracledb#1307]
I have the need to append "_1", "_2" ... "_4" etc to the column results returned to node-oracledb after a query is made to Oracle DB because the project I am working on has 30k legacy SQL queries used in another system, which has them stored in .pk3 files that my observability application reads from to fetch the SQL query for a given chart.

A lot of these queries have the potential to have duplicate column names in the SELECT statement because the person who wrote the query didn't alias them. So it might not be feasible to manually edit all of the cases that require aliasing.

I am using KNEX Query Builder to execute these queries, when the data is returned duplicate columns & rows get merged because the result is a JavaScript Object. I've raised this issue with knex [https://github.com/knex/knex/issues/3993](https://github.com/knex/knex/issues/3993) and they pointed me to modifying node-oracledb to achieve my desired result.

After some googling I came across this similar issue and solution by @dmcghan [https://github.com/oracle/node-oracledb/issues/930#issuecomment-398106736](https://github.com/oracle/node-oracledb/issues/930#issuecomment-398106736) which I have tried to implement into node-oracledb.

**My Attempt**
```
// oracledb/lib/connection.js
// inside line 32, 'async function execute(sql, a2, a3) { .. }
// I have added the following

if (result && result.metaData) {
  let metaData = result.metaData;
  let columns = metaData.map((obj) => obj.name);

  const findDuplicates = (arr) => {
    const filtered = arr.filter((item, index) => arr.indexOf(item) !== index);
    return [...new Set(filtered)]
  }
  const duplicates = findDuplicates(columns);

  if (duplicates.length) {
    duplicates.forEach((e, i) => {
    let count = 0;
    metaData.forEach((obj, idx) => {
    if(obj.name === e){
      count++
      metaData[idx].name = metaData[idx].name + `_${count}`
    }
  })
 })
 result.metaData = metaData;
}
}
```

Result from **let result = await conn.execute(query);** after above implementation:

```
{ metaData:
   [ { name: 'DATETIME' },
     { name: 'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)' },
     { name: 'PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLDRBTRANSPLMN0' } ],
  rows: [ ... ]
```

Result from **let result = await conn.execute(query);** before above implementation:

```
{ metaData:
   [ { name: 'DATETIME' },
     { name: 'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)' },
     { name: 'PMPDCPVOLDLSRB_1' },
     { name: 'PMPDCPVOLDLSRB_2' },
     { name: 'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLDRBTRANSPLMN0' } ],
  rows: [ ... ]
```

@dmcghan I understand that Knex might not be reading the columns from the metadata, so editing the metadata is probably the wrong route.

```
const runKnex = async () => {
  try {
    await knex.transaction(async (trx) => {
      const result = await trx.raw(query);
      console.log(result)
    });
  } catch (error) {
    console.log(error);
  }
};
```

trx.raw() will create/get a oracledb connection and use connection.execute(..) to fire the query.

Data/result returned by knex after querying oracledb with the above implementation:
```
[ { DATETIME: ...,
    'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)': 19499863,
    PMPDCPVOLDLSRB: 11773,
    'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB': 19511637,
    PMPDCPVOLDLDRBTRANSPLMN0: 19516584 },
  { ... }
]
```

@dmcghan Do you know where else in the node-oracledb library I can edit the column names before the data is returned to knex, like in the query stream? I'm at a loss.

**Comment by cjbj** [comment]
Also see https://github.com/oracle/node-oracledb/issues/1250

**Comment by amroczeK** [comment]
@cjbj thanks mate, so based on your comment below - it's probably a better idea for me to write a script and identify all queries that are missing aliases and push them back onto the team who wrote them to fix them, rather than create additional overhead during the query process.

> For future readers, the work-arounds are (i) use a column alias in the query - which is easy but only when you have control over the SQL (ii) Use OUT_FORMAT_ARRAY.

**Comment by cjbj** [comment]
@amroczeK you should push back on the SQL even if you find a workaround.

- Can [Knex handle](https://github.com/knex/knex/issues/3993#issuecomment-708136110) `oracledb.OUT_FORMAT_ARRAY` ?

- If not, you could hack [connection.js](https://github.com/oracle/node-oracledb/blob/v5.0.0/lib/connection.js#L32) and force it to always internally fetch as OUT_FORMAT_ARRAY, and then do some post processing into OUT_FORMAT_OBJECT format before it returns.   And suffer any performance and memory degredation.

- Or submit a PR for #1250 I believe it is all handled now in https://github.com/oracle/node-oracledb/blob/v5.0.0/src/njsResultSet.c#L303

**Comment by cjbj** [comment]
@amroczeK did you try `oracledb.OUT_FORMAT_ARRAY`?

**Comment by amroczeK** [comment]
@cjbj The knex team is hardcoding oracledb's output format as OBJECT.

```
const fetchAsync = promisify(function (sql, bindParams, options, cb) {
        options = options || {};
        options.outFormat =
          client.driver.OUT_FORMAT_OBJECT || client.driver.OBJECT;
        if (!options.outFormat) {
          throw new Error('not found oracledb.outFormat constants');
        }
.....
```

If I change options.outFormat to OUT_FORMAT_ARRAY, then will only return the result of rows and not the column names. I would have to create a pull request and add the ability to pass in options to set outFormat to either ARRAY or OBJECT and then change the way knex parses the data. I think it would be a fair bit of work.

**Comment by cjbj** [comment]
If you get the results as array, can you then (in your code) construct the equivalent JS object format?

**Comment by cjbj** [comment]
@amroczeK I'm going to close this since it's been open a month.  

Discussion on duplicate column solutions can be followed up in the enhancement issue https://github.com/oracle/node-oracledb/issues/1250
