### ISSUE TITLE
Performance oracle db vs Java WebService

### ISSUE THREAD

**Issue by OscarValdez** [oracle/node-oracledb#131]
Which is the best way to perform actions on an oracle database for a web application(CRUD operations and making reports): by using NodeJS with the oracledb driver or  with a java Web Service and its respective driver?, Why?

Which approach would be more easy to maintain in a long perspective?

Thanks in advance

**Comment by cjbj** [comment]
I understand you want to hear from users about the merits of the technologies but I would encourage you to do some testing and evaluate your results by measuring against your organization's skill sets, and your business requirements on deployment, performance and scalability.

**Comment by RogelioGaytan** [comment]
I think it's kinda messy the fact that you must put your code insed all de callback for example when you have to use oracledb.getConecction.

**Comment by RogelioGaytan** [comment]
What do you think about it @cjbj  ?

**Comment by cjbj** [comment]
@RogelioGaytan you might want to post your question in a more general Node.js forum.

**Comment by alexsantos** [comment]
@RogelioGaytan Callbacks are a Node.js characteristic... it's how it works (Promises and so can put some sugar on top...)

@OscarValdez If you need some special feature that is only available on the JDBC driver... then you must go for a web service in Java. If it's just basic select/insert then it depends on your use case.

**Comment by RogelioGaytan** [comment]
Thanks @alexsantos :)
