### ISSUE TITLE
oracledb Number Data type precision shows more number

### ISSUE THREAD

**Issue by msudhayaraj** [oracle/node-oracledb#1315]
Database + version: ORACLE 11g
OS: Ubuntu 16.04 LTS
oracledb@4.2.0

**oracledb Number Data type precision shows more number**

I had a column in oracledb with number data type **(NUMBER(19,2))** , When execute the query in plsql developer i got the result correctly.But execute the same via node oracledb  the precision goes wrongly.

**Actual table value is : 457444.47**
**Got the Result from oracledb is : 457444.47000000003**

Help me to resolve this, Thanks in advance

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/1314

**Comment by cjbj** [comment]
Since you logged another issue showing you tried fetchAsString, I'll close this one.
