### ISSUE TITLE
Returning into ERROR:ORA-01745

### ISSUE THREAD

**Issue by zhanglaifu** [oracle/node-oracledb#1320]
Hello, developer, I found a problem when I was using ORacleDB. I wanted to insert a data and return autoincrement ID by returning into, but I kept returning the wrong ORA-01745. Why is that
![error](https://user-images.githubusercontent.com/37335105/99780674-c3aa5f00-2b51-11eb-8838-ef35e90968f5.png)
![database](https://user-images.githubusercontent.com/37335105/99780717-d2911180-2b51-11eb-9fe3-7f8b7a8ef161.png)

**Comment by cjbj** [comment]
Please update your question with the text of the code.   Please make it runnable and include the SQL to create the table(s). I can't read what you are trying to do.  Thanks!  
Oh, and answer the issue logging template questions: https://github.com/oracle/node-oracledb/blob/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md

**Comment by zhanglaifu** [comment]
//create table
create table hz_test(  
    trade_id    varchar2(20),  
    serial_number    varchar2(20)
)


//js
(async() =>{
    const oracledb = require("oracledb");

    let connection = await  oracledb.getConnection({
        user: 'rep',
        password: 'rep',
        connectString: ' 132.11.11.11/hzdb',
    });
    //what I use is to connect the 50 machine , when I use hz_test table I can get the expect result 
    //but when I use dbLink to connect the other machine ,It will throw the Error
    let sqlText = "insert into  hz_test@hz50 values (3,'1123')  RETURNING serial_number into :ID";
    let params = {
        ID:{
            dir:oracledb.BIND_OUT,
            type:oracledb.STRING
        },
        
    }
    let result = await connection.execute(sqlText,params,{autoCommit:true});
    console.log(result);
})()


1、What versions are you using?
    oracledb 5.0.0
    node  14.8.0
2、Describe the problem
Returning into error-01745 error with INSERT statement when using Oracle dblink to connect tables of other machines.But with a local table it is possible to insert and return data normally

3、Include a runnable Node.js script that shows the problem



//create table
create table hz_test(  
    trade_id    varchar2(20),  
    serial_number    varchar2(20)
)


//js
(async() =>{
    const oracledb = require("oracledb");

    let connection = await  oracledb.getConnection({
        user: 'rep',
        password: 'rep',
        connectString: ' 132.11.11.11/hzdb',
    });
    //what I use is to connect the 50 machine , when I use hz_test table I can get the expect result 
    //but when I use dbLink to connect the other machine ,It will throw the Error
    let sqlText = "insert into  hz_test@hz50 values (3,'1123')  RETURNING serial_number into :ID";
    let params = {
        ID:{
            dir:oracledb.BIND_OUT,
            type:oracledb.STRING
        },
        
    }
    let result = await connection.execute(sqlText,params,{autoCommit:true});
    console.log(result);
})()

**Comment by zhanglaifu** [comment]
1、What versions are you using?
    oracledb 5.0.0
    node  14.8.0
2、Describe the problem
Returning into error-01745 error with INSERT statement when using Oracle dblink to connect tables of other machines.But with a local table it is possible to insert and return data normally

3、Include a runnable Node.js script that shows the problem

//create table
create table hz_test(  
    trade_id    varchar2(20),  
    serial_number    varchar2(20)
)


//js
(async() =>{
    const oracledb = require("oracledb");

    let connection = await  oracledb.getConnection({
        user: 'rep',
        password: 'rep',
        connectString: ' 132.11.11.11/hzdb',
    });
    //what I use is to connect the 50 machine , when I use hz_test table I can get the expect result 
    //but when I use dbLink to connect the other machine ,It will throw the Error
    let sqlText = "insert into  hz_test@hz50 values (3,'1123')  RETURNING serial_number into :ID";
    let params = {
        ID:{
            dir:oracledb.BIND_OUT,
            type:oracledb.STRING
        },
        
    }
    let result = await connection.execute(sqlText,params,{autoCommit:true});
    console.log(result);
})()

**Comment by cjbj** [comment]
I don't know your Oracle versions or how you are creating the dblink, but I'm guessing this is not something Oracle supports.  When I tried it with 19c Client to a 20c DB, I got:
```
[Error: ORA-22816: unsupported feature with RETURNING clause] {
  errorNum: 22816,
  offset: 21
}
```
