### ISSUE TITLE
Error: NJS-069: node-oracledb 5.0.0 requires Node.js 8.16 or later

### ISSUE THREAD

**Issue by handayoung11** [oracle/node-oracledb#1323]
![image](https://user-images.githubusercontent.com/37053970/100205510-8de9e980-2f48-11eb-9991-cf2f6598f6af.png)
I can't know why this error is happen.....
Help me please
It's my code.
![image](https://user-images.githubusercontent.com/37053970/100205603-ae19a880-2f48-11eb-870a-7fe92f810325.png)
![image](https://user-images.githubusercontent.com/37053970/100205624-b4a82000-2f48-11eb-896f-2fe5cd129154.png)

And it's terminal.
![image](https://user-images.githubusercontent.com/37053970/100205788-e620eb80-2f48-11eb-8428-b928c3218e15.png)

My oracledb module version is 5.0.0, I use oracle database and did prerequisites.
I set bin of OracleDB.. but it's not work

**Comment by cjbj** [comment]
Please edit your post and remove the images.  Cut and past the text of the code etc.  Thanks!

**Comment by cjbj** [comment]
I see the word 'webpack' in there. Hopefully you saw https://github.com/oracle/node-oracledb/issues/1156#issuecomment-598017250

**Comment by SchoolOgre** [comment]
Did you ever solve this, as I have the same problem. I have oracledb 5 and node.js 15.5 
and it wants  "v8.16 or later" :(  
I noticed I only have this problem when using React.

**Comment by cjbj** [comment]
@SchoolOgre do some tracing and see what Node is actually being used.  Instead of continuing this closed thread, you should/could open a new one but only do this if you can provide more details about what is installed and how.

**Comment by RomanShitovGH** [comment]
> Вы когда-нибудь решали это, у меня такая же проблема. У меня есть oracledb 5 и node.js 15.5,
> и он хочет "v8.16 или новее" :(
> Я заметил, что у меня эта проблема возникает только при использовании React.

SchoolOgre, у меня такая же ошибка.
Error: NJS-069: node-oracledb 5.1.0 requires Node.js 8.16 or later 
Нашли ли вы решение, поделитесь пожалуйста.
Компоненты:
"node": "^15.4.0",
"node-oracledb": "^1.0.2",
"oracledb": "^5.1.0",
"react": "^17.0.1",

**Comment by SchoolOgre** [comment]
I may be wrong; but basically, I think we need two components; which is a shame. 
Use only oracledb on the db facing part- providing a data access service, and only React on the browser facing side which builds the actual web pages; and your react components can call your data access service ( http get etc).

**Comment by RomanShitovGH** [comment]
> I may be wrong; but basically, I think we need two components; which is a shame.
> Use only oracledb on the db facing part- providing a data access service, and only React on the browser facing side which builds the actual web pages; and your react components can call your data access service ( http get etc).

Спасибо за подсказку, буду пробовать.
Ну а вы как решили проблему с node.js и oracledb ?

**Comment by SchoolOgre** [comment]
> > I may be wrong; but basically, I think we need two components; which is a shame.
> > Use only oracledb on the db facing part- providing a data access service, and only React on the browser facing side which builds the actual web pages; and your react components can call your data access service ( http get etc).
> 
> Спасибо за подсказку, буду пробовать. Хотя я читал что React на прямую не может общаться с базой данных.
> Ну а вы как решили проблему с node.js и oracledb ?

I didn't solve it. I avoided it by having two separate JS applications. They use http requests to talk to each other. I am hoping someone will tell me how to fix it, or that this (2 apps) is the correct and only way to do it.

**Comment by RomanShitovGH** [comment]
> > > I may be wrong; but basically, I think we need two components; which is a shame.
> > > Use only oracledb on the db facing part- providing a data access service, and only React on the browser facing side which builds the actual web pages; and your react components can call your data access service ( http get etc).
> > 
> > 
> > Спасибо за подсказку, буду пробовать. Хотя я читал что React на прямую не может общаться с базой данных.
> > Ну а вы как решили проблему с node.js и oracledb ?
> 
> I didn't solve it. I avoided it by having two separate JS applications. They use http requests to talk to each other. I am hoping someone will tell me how to fix it, or that this (2 apps) is the correct and only way to do it.

В общем я понял свою ошибку. У меня есть oracle - nodejs - react. Подключать модуль oracledb можно только в файле сервера server.js . И уже к server.js обращаться из react запросами fetch. А я по неопытности стал подключать модуль и в server.js и в app.jsx . Отсюда и была ошибка сборки проекта Error: NJS-069: node-oracledb 5.1.0 requires Node.js 8.16 or later
Т.к. напрямую react общаться с базой не может, только через прослойку.
Я может банальные вещи говорю и кто-то скажет "lol". 
Но для себя я проблему решил!

**Comment by SchoolOgre** [comment]
> > > > I may be wrong; but basically, I think we need two components; which is a shame.
> > > > Use only oracledb on the db facing part- providing a data access service, and only React on the browser facing side which builds the actual web pages; and your react components can call your data access service ( http get etc).
> > > 
> > > 
> > > Спасибо за подсказку, буду пробовать. Хотя я читал что React на прямую не может общаться с базой данных.
> > > Ну а вы как решили проблему с node.js и oracledb ?
> > 
> > 
> > I didn't solve it. I avoided it by having two separate JS applications. They use http requests to talk to each other. I am hoping someone will tell me how to fix it, or that this (2 apps) is the correct and only way to do it.
> 
> В общем я понял свою ошибку. У меня есть oracle - nodejs - react. Подключать модуль oracledb можно только в файле сервера server.js который запускается на Node.js . И уже к server.js обращаться из react запросами fetch. А я по неопытности стал подключать модуль и в server.js и в app.jsx . Отсюда и была ошибка сборки проекта Error: NJS-069: node-oracledb 5.1.0 requires Node.js 8.16 or later
> Т.к. напрямую react общаться с базой не может, только через прослойку.
> Я может банальные вещи говорю и кто-то скажет "lol".
> Но для себя я проблему решил!

Yes - I think we are agreeing - you have to have 2 parts. One connects to DB, one to the browser. 
But (to me as a novice in this) the documentation does not make this very obvious.  

ура :)
