### ISSUE TITLE
Number Data type column return the whole number, (85.00 returns 85 )

### ISSUE THREAD

**Issue by msudhayaraj** [oracle/node-oracledb#1324]
1. What versions are you using?

 **OS: Ubuntu 16.04 LTS**
 **Oracledb 4.1.0** 
**Database + version: ORACLE 11g**

2. Is it an error or a hang or a crash?

**No**

3. What error(s) or behavior you are seeing?

**Number Data type column return the whole number, (85.00 returns 85 )**

4. Include a runnable Node.js script that shows the problem.

```
// Sample  code
var oracledb = require('oracledb');
var strConnection = {
  user: 'USER',
  password: 'PASSWORD',
  connectString: "ConnectionString"
};
oracledb.poolMin = 3;
oracledb.poolMax = 100;
oracledb.poolIncrement = 1;
oracledb.poolPingInterval = 60; // seconds
oracledb.poolTimeout = 60;

async function test() {
  let pool = await oracledb.createPool(strConnection);

  let conn = await pool.getConnection();

  let updateQry = 'select * from TESTNUMBER';

  let res2 = await conn.execute(updateQry);

  console.log(res2);
}
test();
```

**DB script**

` create table TESTNUMBER(
  cr_amount   NUMBER(19,2)
  ); `
-- insert script
`
insert into TESTNUMBER values(45.00);
insert into TESTNUMBER values(55.50);
insert into TESTNUMBER values(55.56);
commit;
`

When run the select query from plsql developer i am getting the values what i am inserted.
But while running above code the vale **0** is not returned.
**45.00** becomes **45**
**45.50** becomes **45.5**
**45.55** becomes **45.55 , this is correct.** Like that why all the values not returned.
how can i get the same values, what i am inserted in db.
I tried **fetchAsString** , its also behave like above.
I need a value db inserted value as it is. 
Help me to get the result. Thanks in advance.

**Comment by cjbj** [comment]
Having a trailing 0 is an output display representation choice.  There are various things you can do, e.g. https://stackoverflow.com/a/56187796/4799035  Google might show more.

I'll close this issue, since it isn't specific to node-oracledb.  Good luck!
