### ISSUE TITLE
same query result 0 in node-oracledb but result is existed in oracle client

### ISSUE THREAD

**Issue by spilown** [oracle/node-oracledb#1325]
1. What versions are you using?

Give your database version.

Also run Node.js and show the output of:

    process.platform : darwin
    process.version: v12.16.1
    process.arch: x64
    require('oracledb').versionString: 5.0.0
    require('oracledb').oracleClientVersionString: 19.3.0.0.0

2. Is it an error or a hang or a crash?
  NO, 

3. What error(s) or behavior you are seeing?
run same query in nodejs and datagrip but get different result
from nodejs -> result 0
from datagrip -> get some result

this issue raised from specific query attached below
the point is **'where IS_ABC is not null '**
if i remove last line , i can get result  but add this line result is 0 

code in: https://gist.github.com/spilown/91208365e36a26eee3a08339f15e132d

**Comment by cjbj** [comment]
- Check you are connected to the same database in the node.js app and datagrip
- Check you have committed any transaction in datagrip
- Write a non-web script that shows the problem with console.log() 
- If the above doesn't help, then give us the SQL to create the table and insert data, and the non-web app script that shows the problem

**Comment by cjbj** [comment]
PS Instant Client 19.8 is out for macOS, see https://blogs.oracle.com/opal/notarized-macos-oracle-instant-client-packages-make-installation-easier

**Comment by spilown** [comment]
@cjbj 
I figured out which part was the problem, and this is like an oracle function, which is defined in an external db. This is normally displayed in datagrip, but in nodejs, if a where condition is entered, the value cannot be retrieved normally.
Checked to connect to the same db and testing locally. Triple checked
Please refer to the address below
https://gist.github.com/spilown/a5e14f413a1a32ea7d397d5fa7281bac

**Comment by cjbj** [comment]
Try running that query in SQL*Plus in the same terminal that you run Node.js
