### ISSUE TITLE
Can't set recipient_list in the Advanced Queue

### ISSUE THREAD

**Issue by MaximKokovin** [oracle/node-oracledb#1326]
Hi! I'm using node-oracle 4.2.0 version.

I'm trying put the message in the queue using .enqOne() method. But oracle return error (Error: ORA-24033: no recipients for message). How can i set recipients for my message?

https://gist.github.com/MaximKokovin/2c4cceaaedc43a2fb1f1e1f27c6eaaaf

This sql-script add message to the queue
https://gist.github.com/MaximKokovin/28462546ccb72555ef5eb3750c371c6e

**Comment by cjbj** [comment]
Is this some JMS-ish queue?

**Comment by MaximKokovin** [comment]
i think no but i don't sure. This is oracle advanced queue (pl/sql).

**Comment by cjbj** [comment]
Details matter!

**Comment by MaximKokovin** [comment]
@cjbj i don't use JMS queue. only advanced queuing (AQ).

**Comment by cjbj** [comment]
As discussed on Slack, how was the queue created?

**Comment by cjbj** [comment]
Marking as an enhancement so this doesn't get auto closed without investigation.  It's not clear if driver changes can or need to be made, but I'd like to know.

**Comment by cjbj** [comment]
An update: the AQ team have looked at this.  Some driver layer changes would be needed.  I'll leave this open until they can be scheduled.

**Comment by cjbj** [comment]
Support for this was just merged to the main branch.  See https://oracle.github.io/node-oracledb/INSTALL.html#githubtags for how to build it.

**Comment by cjbj** [comment]
node-oracledb 5.5 contains this patch.
