### ISSUE TITLE
Node-oracledb 5.1 is Available

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#1327]
Node-oracledb 5.1 is available.

- [release announcement](https://blogs.oracle.com/opal/faster-json-with-node-oracledb-51-and-oracle-database-21s-new-oson-storage-format)
- [changelog](https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md)

**Comment by connorjayfitzgerald** [comment]
The updated TypeScript definitions are in PR
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50035

**Comment by sosoba** [comment]
Hey Connor. I'd like to remind you that npm package `@types/oracledb` has still two dependencies: `@types/node` and `dotenv`. The first of them is necessary but `dotenv` is only necessary for unit tests on CI. Could you try to change it into npm dev dependency?.

**Comment by connorjayfitzgerald** [comment]
@sosoba Good spot. Sure, I'll look into that
