### ISSUE TITLE
Inserting big polygons to SDO Geometry gives error

### ISSUE THREAD

**Issue by alperdincer** [oracle/node-oracledb#1328]
Hi, 

I'm working on a spatial project to insert geometry and attribute data to Oracle as shown in following gist : 

https://gist.github.com/alperdincer/5322bd40183cbc0b5e41fedd80af3822

The code is working for small geometries like Points, but it doesn't work for large polygons which passes 32 KB. 

I got **"NJS-058: maxSize of 0 is too small for value of length 42 in row 0"** error for big polygons.

Is there any way to pass this limitation? 

Technical Details 
---------------------------------
Database version : 12.1.0.2.0
process.platform : win32
process.version : v14.15.1
process.arch : x64
require('oracledb').versionString : 5.0.0
require('oracledb').oracleClientVersionString : 12.1.0.2.0

**Comment by cjbj** [comment]
- Do the examples in [Inserting Objects](https://oracle.github.io/node-oracledb/doc/api.html#objectinsert) help?  They show binding SDO_GEOMETRY as an object itself.

- Please give a runnable testcase ie. include the data.

- When in doubt, try a recent Oracle client library, e.g. 19.9

Tagging @dlapp, who is the Spatial expert.

**Comment by alperdincer** [comment]
I'm also working on it to insert to table as an object with following JS object : 

`                var geomC = {
                    type: 'MDSYS.SDO_GEOMETRY',  
                    val: {   
                      SDO_GTYPE: 2004,
                      SDO_SRID: 4326,
                      SDO_POINT: null,
                      SDO_ELEM_INFO: [ 1, 1003, 1 ],
                      SDO_ORDINATES: [ 36.281885500000044, 38.40247449900005,36.382108, 38.368129499000077,36.400921, 38.25966549900005, ..................,36.281885500000044, 38.40247449900005 ]
                    }
                };`

This is working with single execute() function, but it is not working with executeMany() function and I got the following error : 

"NJS-012: encountered invalid bind data type in parameter 2"

I've tested each binding with execute() and they are working, but when I use same bindings as an array with executeMany(), I got error.

@dlapp any suggestions for inserting geometries from gdal?

**Comment by cjbj** [comment]
@alperdincer without having runnable code, it makes it hard for us to help you.  Can you give a file (with SQL and data) that shows the problem?

**Comment by alperdincer** [comment]
I prepared a sample data and code which is attached below. SQL is added above the test.js file and data is in the SHP folder. Please let me know if there are any missing points. 

[ora_gdal_test.zip](https://github.com/oracle/node-oracledb/files/5665590/ora_gdal_test.zip)

Thanks.

**Comment by dlapp** [comment]
@alperdincer Can you capture the SQL inserts that are generated?

**Comment by cjbj** [comment]
@alperdincer You can do that by setting DPI_DEBUG_LEVEL to 16 as shown in https://oracle.github.io/node-oracledb/doc/api.html#tracingsql

**Comment by alperdincer** [comment]
@cjbj I've enabled debug level via "set DPI_DEBUG_LEVEL=16" at windows, but still don't get any SQL messages for inserts. Do you have any suggestions to capture SQL inserts?

By the way, I found an alternative solution to my problem. I've created a procedure that took CLOB as input and send WKT text as CLOB to procedure and it worked.

**Comment by anthony-tuininga** [comment]
You need to set DPI_DEBUG_LEVEL in the *same* shell that is running Python. This will cause messages to be printed to stdout. If you set it elsewhere it will have no effect. It will look like this:

```
ODPI [10962] 2020-12-10 09:00:54.851: ODPI-C 4.1.0
ODPI [10962] 2020-12-10 09:00:54.851: debugging messages initialized at level 16
ODPI [10962] 2020-12-10 09:01:19.559: SQL select user from dual
```

**Comment by alperdincer** [comment]
@anthony-tuininga I did it in the same shell with "set DPI_DEBUG_LEVEL=16" in windows shell and still don't get the messages you mentioned. 

Anything else to find a way to see debug messages?

**Comment by anthony-tuininga** [comment]
Did you run Node.js in the same shell?

**Comment by cjbj** [comment]
@alperdincer any update?

**Comment by alperdincer** [comment]
I'm waiting for the production server to get the debug messages. I didn't get any debug messages on our testing server. We will be getting our production server (an Exadata server) within 2 weeks and check what happens there.
