### ISSUE TITLE
QBE to SQL

### ISSUE THREAD

**Issue by haarse** [oracle/node-oracledb#1329]
Hi,

Anyone who knows if there exists any Query By Example (QBE) to SQL translator/parser for javascript/typescript?
Example:
Let's say that we have a GraphQL server that implements its resolvers using Node-Oracledb
Then we could send a filter with QBE in the query from GraphQL server.
When we get to the Node-OracleDB we want to translate the QBE to SQL.
`{ "$query" : { "salary" : { "gt" : 10000 } } }`
Should be transformed to:
`salary > 10000`

Does anything like this exist in the SODA implementation?

Regards
Håkan

**Comment by cjbj** [comment]
What graphsql server are you using?  Do you have control over the QBE syntax?

**Comment by haarse** [comment]
Hi Chris,
Right now I'm evaluating Apollo. I'm about to test to use graphql-tools also to be able to modularize my schema and resolvers into many files.

Yes, I can have control of the QBE syntax.

Regards
Håkan

**Comment by cjbj** [comment]
With control over the QBE syntax, then maybe it's not a lot of effort to pass it directly to SODA?

Let us know how you go.
