### ISSUE TITLE
Cursor gets lost during error

### ISSUE THREAD

**Issue by volkmarbuehringer** [oracle/node-oracledb#133]
every callback with an error looses one cursor

so writing code, which ignores errors ( insert with unique constraint ) is not possible

**Comment by dmcghan** [comment]
@volkmarbuehringer Could you explain what "looses one cursor" means? Also, why can't you just ignore the error?

**Comment by volkmarbuehringer** [comment]
after 1000 errors, it says too many open cursors with open_cursors = 1000
so after 1000 ignored errors it stops
( with the same connection/transaction )

**Comment by cjbj** [comment]
@volkmarbuehringer Please post the code that reproduces the problem.  Check the statement cache size and your DB open_cursors parameter.
