### ISSUE TITLE
Error when creating index with property order specified as number

### ISSUE THREAD

**Issue by tomas-mechura** [oracle/node-oracledb#1331]
# What versions are you using?

ATP 19c - DB version
linux  - process.platform
v10.22.1  - process.version
x64  - process.arch
5.1.0  - oracledb.versionString
19.6.0.0.0  - oracledb.oracleClientVersionString

# Is it an error or a hang or a crash?

error

# What error(s) or behavior you are seeing?

According to index spec - https://docs.oracle.com/en/database/oracle/simple-oracle-document-access/adsdi/soda-index-specifications-reference.html#GUID-00C06941-6FFD-4CEB-81B6-9A7FBD577A2C

The index property `order` can be specified by string or number. If using number `1` the index creation ends with error:
```
{ [Error: ORA-00907: missing right parenthesis
ORA-06512: at "XDB.DBMS_SODA_ADMIN", line 3449
ORA-06512: at "XDB.DBMS_SODA_ADMIN", line 444
ORA-06512: at "XDB.DBMS_SODA_ADMIN", line 3440
ORA-06512: at line 1] errorNum: 907, offset: 0 }
```

It works when using `"asc"`

# Include a runnable Node.js script that shows the problem.

[examples/soda1.js](https://github.com/oracle/node-oracledb/blob/master/examples/soda1.js#L65) - just switch line with index definition from:
```
        "order": "asc" } ] };
```
to
```
        "order": 1 } ] };
```

**Comment by cjbj** [comment]
This is a SODA issue being tracked as Oracle bug 32356340.

Since there is no node-oracledb component, I'll close this issue.
