### ISSUE TITLE
Facing disconnection issues ORA-03114: not connected to Oracle soda after every 8-12 hours.

### ISSUE THREAD

**Issue by AbdulHaadi6** [oracle/node-oracledb#1332]
Database Version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0
Platform: linux
Version: v12.18.3
Arch: x64
Version String: 5.0.0
Client Version String: 19.8.0.0.0

All the apps that are connected with Oracle Soda database are continuously disconnecting after every 8 to 12 hours.
The apps have to be restarted to connect back.

 
```
const oracledb = require('oracledb');

oracledb.autoCommit = true;

var connection;

initClient();

async function initClient() {
    try {
        oracledb.initOracleClient({ libDir: '/home/ubuntu/instantclient', configDir: '/home/ubuntu/instantclient/network/admin' });
        connection = await oracledb.getConnection({
            user: "xyz",
            password: "pass",
            connectString: 'string'
        });

        return connection;

    } catch (err) {
        console.error(err);
    }
}

async function getConnection() {
    return connection;
}

async function closeConnection() {

}

async function getSodaDatabase() {
    try {
        const soda = await connection.getSodaDatabase();
        return soda;
    } catch (err) {
        console.error(err);
    }
}

module.exports = {
    getSodaDatabase,
    initClient,
    getConnection,
    closeConnection
}


```

**Comment by cjbj** [comment]
You'll need to do some investigation.  Maybe you have a firewall timing out connections?  Review your sqlnet.ora settings.
Review what is happening when the timeout occurs.  Review why you are keeping connections open for so long. Review whether you should be using a connection pool, and releasing connections back to the pool when the connections are not in use.  Review Oracle "client side" and DB tracefiles.

**Comment by AbdulHaadi6** [comment]
> You'll need to do some investigation. Maybe you have a firewall timing out connections? Review your sqlnet.ora settings.
> Review what is happening when the timeout occurs. Review why you are keeping connections open for so long. Review whether you should be using a connection pool, and releasing connections back to the pool when the connections are not in use. Review Oracle "client side" and DB tracefiles.


We have a scenario of connecting our apps to the db and one single connection is being used for this. Plz recommend that if standalone or pool connections should be used. Here is our sqlnet.ora code.

`
WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="c:\\instantclient\\network\\admin")))
SSL_SERVER_DN_MATCH=yes
`

**Comment by cjbj** [comment]
> Plz recommend that if standalone or pool connections should be used

It depends.  If the connection is not being used for long periods of time, then a pool (even with just one connection) could make sense, since it will give you some of the connection high availability features. More information about the life cycle and usage of the connection would be needed before making a decision.
