### ISSUE TITLE
Error: DPI-1002: invalid dpiConn handle

### ISSUE THREAD

**Issue by jacopocappelli1989** [oracle/node-oracledb#1333]
Hi have an Express project with db.js file with connection pool like this:
```const oracledb = require('oracledb');
oracledb.poolMax = 50;
oracledb.autoCommit = false;
oracledb.connectionClass = 'HRPOOL';
const config = require('./config').getConfig();

function init_pool_dbcomune(force, callback) {
        oracledb.createPool({
                user: config.DBCOMUNE.USER,
                password: config.DBCOMUNE.PASSWORD,
                connectString: config.DBCOMUNE.CONNECT_STRING
            },
            function (err, pool) {
                if (err) {
                    console.error(err.message);
                }
                exports.pool_dbcomune = pool;
         });
}

init_pool_dbcomune();

exports.getPoolDbComune = async function () {
    if (typeof pool_dbcomune.getConnection === 'undefined') {
        process.exit(22);
    }
    return pool_dbcomune;
};

exports.createDbComune = async function (callback) {
    await init_pool_dbcomune(true, function(pool){
        console.log("return pool dbcomune -----------------------");
        return pool;
    });
};
```

And in routes file i use this as this:
```
router.post('/add', auth.verifyToken, function(req, res, next) {
    db.pool_dbcomune.getConnection(function (err, connection2) {
            if (err) {
                console.error(err.message);
                return;
            }

            model.DoSomething(connection2,req.body, function(err,data){
                if(err){
                    res.sendStatus(404);
                    connection2.rollback();
                    connection2.close();
                }else{
                    res.send("ok");
                    connection2.commit();
                    connection2.close();
                }

            });
        });

});
```

Node version: v12.18.2
oracledb: 4.2.0 or 5.1.0 (same error)
Oracle: 12.1.0.2.v19 an Amazon RDS
Oracle client library: 12.2

The problem is random, sometimes works other not (same code).

Someone can help me to understand how solve?

Thanks,
Jacopo

**Comment by anthony-tuininga** [comment]
You are missing calls to `await` (or callbacks as you use for creating the pool) in your calls to `connection2.rollback()` and `connection2.commit()` and `connection2.close()`. So you are setting up a race condition. Depending on which gets done first you are going to get the error or it is going to work!

**Comment by jacopocappelli1989** [comment]
Thanks Anthony but I can't understand.

You mean as this?
```
router.post('/add', auth.verifyToken, function(req, res, next) {
    db.pool_luniversotuo.getConnection(function (err, connection2) {
            if (err) {
                console.error(err.message);
                return;
            }

            model. DoSomething(connection2,req.body, function(err,data){
                if(err){
                    connection2.rollback(function(){
                        connection2.close();
                        res.sendStatus(404);
                    });
                }else{
                    connection2.commit(function (){
                        connection2.close();
                        res.send("ok");
                    });
                }

            });
        });

});
```

Because I receive 200 OK (mean that res.send("ok"); is executed) but no data is on database (commit have an error)

Thanks,
Jacopo

**Comment by anthony-tuininga** [comment]
Yes. You need to do something like that. You should be checking the error, though on commit -- as I presume that if the commit fails for some reason you don't want to send "ok". Or better still, just use asysc/await. :-)

**Comment by jacopocappelli1989** [comment]
Thanks very much no I understand!
But can I understand why commit give error?

I want to solve the error (if is it possible) and manage it.

Thanks again

**Comment by anthony-tuininga** [comment]
You're very welcome! Close the issue if you believe the matter is resolved.

It is highly unlikely the commit would be causing an error, but not impossible. As such you should simply check for the error and respond with an error. In your code you aren't logging the error anywhere or returning it to the user -- so if something does go wrong you'll just know what it went wrong, but not why!
