### ISSUE TITLE
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by cheslyn** [oracle/node-oracledb#1334]
Recently we migrated one of our database instances from Oracle on premise to OCI. 
Since then though all the ports and firewalls are open Node JS is not able to connect to the OCI instance. 

It throws the following error
{ [Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor] errorNum: 12514, offset: 558 }

Note: This was working perfectly fine pre-migration, and also still working for other onpremise databases.

1. What versions are you using?
Node ver : 10.15.1
2. Is it an error or a hang or a crash?

3. What error(s) or behavior you are seeing?
No data gets retrieved and the node pkg returns the following error
{ [Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor] errorNum: 12514, offset: 558 }

4. Include a runnable Node.js script that shows the problem.

Current format of the dbconfigure.js
module.exports = {
   user          : process.env.NODE_ORACLEDB_USER || "SSO307006453",
  password      : "xxxxxxxxxxxx",

Options tried
  //connectString : "oscaroltp-db.int.bkrh.oracleoutsourcing.com:1521/oscaroltp",
  connectString : "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oscaroltp-db.int.bkrh.oracleoutsourcing.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=oscaroltp)))",
 externalAuth  : process.env.NODE_ORACLEDB_EXTERNALAUTH ? true : false
};

Note from the Node server telnet is going through fine. 
Verified and found that the Host / Port / Service names are all matching. 

Please let us know how to fix this issue ?

Thanks
Cheslyn

**Comment by cjbj** [comment]
It looks like you are connecting to a DB server that has the network listener running.  This is good.  But the listener doesn't know about the DB service name you are using in the connect string. The first thing to do is work with support and your admins to make sure SQL*Plus can connect from the servers you want to run Node.js on.  (GitHub isn't the place for this, sorry.  And telnet isn't a useful test).  Then we can help with the node-oracledb side.

**Comment by cjbj** [comment]
@cheslyn where are you at with this?

**Comment by cjbj** [comment]
Closing - no update
