### ISSUE TITLE
Getting recent data delays after successful inserts/updates

### ISSUE THREAD

**Issue by alperdincer** [oracle/node-oracledb#1335]
We've been working on a NodeJS project for a while and last week we started to deploy to production server (Exadata), but we have faced an unexpected problem, which when we insert or update a table and after get the recent data, we didn't get the updates. When we waited for 10-20 seconds, we got the updated data from SELECT queries. By the way, we can see the recent data in SQL Developer immediately. This behavior is not available on our testing server, which both Oracle and NodeJS are working on the same machine, but when we moved to production servers, which ExaData and NodeJS are on different servers, we faced to delays of recent data. 

We are using Pooled connections for our application and we can't figure out what to do? Any suggestions to overcome the problem from our side? Or any suggestions to production platform to work with NodeJS?

Technical Details
Database version : 12.1.0.2.0
process.platform : win32
process.version : v14.15.1
process.arch : x64
require('oracledb').versionString : 5.1.0
require('oracledb').oracleClientVersionString : 12.1.0.2.0

**Comment by cjbj** [comment]
Can you describe 'which when we insert or update a table and after get the recent data, we didn't get the updates.' more?

Who's we? Do you mean you query after insert?  Are you sure the query and insert are sequential and the insert has finished before you query?

**Comment by alperdincer** [comment]
Let me explain the problem as follows:

There is an "announcement" table described : 
`
CREATE TABLE announcements (
  id NUMBER GENERATED ALWAYS AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  title VARCHAR2(100),
  a_content CLOB,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  a_type NUMBER DEFAULT 0,
  created_by NUMBER,
  created_at TIMESTAMP,
  deleted_by NUMBER
)
`

* The Oracle connections is created as follow:
`
await oracledb.createPool({
        user: user,
        password: pass,
        connectString: serverConfig.db.connectionString,
        poolIncrement : 0,
        poolMax       : 4,
        poolMin       : 4,
        poolPingInterval : 1
    });
`

* And all queries are executed by the following function : 

`
function simpleExecute(statement, binds = [], opts = {}) {
    return new Promise(async (resolve, reject) => {
        let conn;

        opts.outFormat = oracledb.OBJECT;
        opts.autoCommit = true;

        try {
            conn = await oracledb.getConnection();
            const result = await conn.execute(statement, binds, opts);
            resolve(result);
        } catch (err) {
            console.log("---- DB ERROR -----");
            console.log(err);
            console.log("---- DB ERROR -----");
            reject(err);
        } finally {
            if (conn) { 
                try {
                    await conn.close();
                } catch (err) {
                    console.log(err);
                }
            }
        }
    });
}

`

* From the user interface, users trying to create a new announcement from the controller below : 

`
async function addAnnouncement (req, res, next) {
    try {
        const body = req.body;    
        const contents = {
            title: body.title,
            a_content: body.a_content,
            start_date: body.start_date + " 00:01",
            end_date: body.end_date + " 23:59",
            userId : utils.decryptText(body.userId)
        };
        
        const announcementResult = await announcementDBAPI.addAnnouncement(contents);
        if (announcementResult.rowsAffected == 1) {
            res.status(200).send({ success: true });
        }
        else {
            res.status(200).send({ success: false });
        } 
    }
    catch (err) {
        console.log(err);
        console.log("Error-0057");
        res.status(200).send({ success : false });
    }
}

`

* DB API is as follows : 

`
async function addAnnouncement (context) {
    const binds = {
        title: context.title,
        a_content: context.a_content,
        start_date: context.start_date,
        end_date: context.end_date,
        userId: parseInt(context.userId)
    };
    let insertSql = 'INSERT INTO announcements (title, a_content, start_date, end_date, created_by, created_at) VALUES ';
    insertSql += '(:title, :a_content, TO_TIMESTAMP(:start_date, \'DD/MM/YYYY HH24:MI\'), TO_TIMESTAMP(:end_date, \'DD/MM/YYYY HH24:MI\'), :userId, SYSDATE)';
    const result = await database.simpleExecute(insertSql, binds);
    return result;
}
`

* After this insert, when clients get "success" message, it gets GET request from "getAnnouncements" controller with following "SELECT" query, but it gets the rows without the new row inserted even this row is accessible from SQL Developer. 

`
async function getAnnouncements (context) {
    let binds = {
    };

    var selectSql = 'SELECT fl.id AS "id", fl.title AS "title", fl.a_content AS "a_content", ' +
                    ' (SELECT fullname FROM users WHERE id = fl.created_by) AS "created_by_ref", fl.created_by AS "created_by", ' +
                    ' TO_CHAR(fl.start_date, \'DD/MM/YYYY\') AS "start_date", ' +
                    ' TO_CHAR(fl.end_date, \'DD/MM/YYYY\') AS "end_date", ' +                    
                    ' TO_CHAR(fl.created_at, \'DD-MM-YYYY HH24:MI\') AS "created_at", ' +
                    ' TO_CHAR(fl.updated_at, \'DD-MM-YYYY HH24:MI\') AS "updated_at", ' +
                    '   CASE WHEN SYSDATE >= start_date AND SYSDATE <= end_date THEN 1 ' + 
                    '        WHEN start_date > SYSDATE AND end_date > SYSDATE THEN 2 ' + 
                    '        ELSE 0 ' + 
                    '   END AS "a_status", ' +
                    '   CASE WHEN SYSDATE >= start_date AND SYSDATE <= end_date THEN \'Current\' ' + 
                    '        WHEN start_date > SYSDATE AND end_date > SYSDATE THEN \'Future\' ' + 
                    '        ELSE \'Past\' ' + 
                    '   END AS "a_status_ref", ' +
                    ' (SELECT fullname FROM users WHERE id = fl.updated_by) AS "updated_by_ref", fl.updated_by AS "updated_by" ' +
                    ' FROM announcements fl WHERE fl.deleted_by = 0 ';

    selectSql += ' ORDER BY fl.id';

    const result = await database.simpleExecute(selectSql, binds);
    return result;
}
`

This workflow can be also valid for other tables. When we insert/update a new row, we can access it immediately from SQL Developer, but "SELECT" queries get recent data after 10-20 seconds later.

Please let me know if additional info is needed. We are stuck to fix the problem.

**Comment by cjbj** [comment]
A few observations
- remove the promise stuff from simple-execute (Dan's forgotten why he had this, but it doesn't seem necessary since [async returns promises](https://github.com/oracle/node-oracledb/issues/1227#issuecomment-597759995)).
- Use backticks around SQL instead of the string concatenation and escaping of embedded quotes
- Your `poolPingInterval` seems aggressive, i.e not good for scaling
- I'm not a fan of overuse of autocommit.  It has it's place but review whether you need it on for all inserts.
- The data handling is something to review.  To verify that your data got inserted, retrieve `lastRowid` after the insert and do a simple query for that rowid, without the complex WHERE clause.

**Comment by cjbj** [comment]
And make sure clocks are in sync, and you have set ORA_SDTZ, if necessary - depending how you are getting your original date values.

**Comment by alperdincer** [comment]
Thanks @cjbj for your suggestions. We have fixed the related ones and checked again, but the problem still continues. Then IT department of our customer find the problem that there is a proxy server which caches the requests. They disabled the caching of our requests and problem solved. 

Sorry for taking your time for this kind of problem.

**Comment by cjbj** [comment]
Thanks for letting us know the solution.  I'm glad you got it solved.
