### ISSUE TITLE
Getting ORA-12571 while running from Windows WSL

### ISSUE THREAD

**Issue by saachinsiva** [oracle/node-oracledb#1337]
Hello

We have NestJS serverless application that connects to Oracle DB and it worked well until couple of days back and then it started throwing below error. This happens when the application tries to configure the connection pool. Please note that we do our development on Windows WSL (Linux) and we have installed latest Oracle instant-client and node-oracle db version (5.1). What's even weirder is that the app connects to DB successfully if I run from Windows command prompt but only the very first request works and when I send second request it crashes my serverless process while configuring the connection pool. However we are able to connect to DB using DBeaver with no issues at all.

At this point, we do not know what is causing this issue, serverless-offline/ node-oracle/wsl or any other factors outside of these. 

Please advise. Thanks in advance.

Error from WSL :

> 2021-01-29 05:40:26.937 [info] - Database secret retrieved successfully. (in db.service.ts:185)
> 2021-01-29 05:40:26.938 [info] - Connecting to database with connection name default... (in db.ts:28)
> 2021-01-29 05:40:27.204 [info] - Database secert retrieved successfully. (in db.service.ts:235)
> [Error: ORA-12571: TNS:packet writer failure] {
>   errorNum: 12571,
>   offset: 0
> }
> offline: (λ: index) RequestId: ckki5nqdd000212lqhzr8eoxf  Duration: 2202.84 ms  Billed Duration: 2300 ms

Windows command prompt (First Http Request) :

> 2021-01-29 05:52:25.854 [info] - Initializing databases... (in db.service.ts:46)
> 2021-01-29 05:52:25.855 [info] - Database secret retrieved successfully. (in db.service.ts:185)
> 2021-01-29 05:52:25.856 [info] - Connecting to database with connection name default... (in db.ts:28)
> 2021-01-29 05:52:26.255 [info] - Database connection pool for connection name default configured successfully ... (in db.ts:30)
> 2021-01-29 05:52:26.256 [info] - All the services are initialized. (in service_initializer.ts:51)
> [Nest] 24064   - 01/29/2021, 5:52:26 AM   [RoutesResolver] SharedController {/api}: +0ms
> [Nest] 24064   - 01/29/2021, 5:52:26 AM   [RouterExplorer] Mapped {/api/refreshCache, POST} route +1ms
> [Nest] 24064   - 01/29/2021, 5:52:26 AM   [RouterExplorer] Mapped {/api/staticDataByKeys, POST} route +0ms
> [Nest] 24064   - 01/29/2021, 5:52:26 AM   [RoutesResolver] ClearanceController {/api}: +0ms
> [Nest] 24064   - 01/29/2021, 5:52:26 AM   [RouterExplorer] Mapped {/api/clearance, POST} route +1ms
> [Nest] 24064   - 01/29/2021, 5:52:26 AM   [NestApplication] Nest application successfully started +2ms

Windows command prompt (Second Http Request) :

> 2021-01-29 05:54:45.132 [info] - Initializing databases... (in db.service.ts:46)
> 2021-01-29 05:54:45.301 [info] - Database secert retrieved successfully. (in db.service.ts:235)
> 2021-01-29 05:54:45.346 [info] - Connecting to database with connection name default... (in db.ts:28)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 3221225477
> npm ERR! iq-submission-service@1.0.0 startw: `set APP_ENV=local& set AWS_REGION=us-east-1& node --max-old-space-size=8096 --inspect=127.0.0.1:9230 node_modules/serverless/bin/serverless offline --noAuth --dontPrintOutput --noTimeout --httpPort 9085
> npm ERR! Exit status 3221225477
> npm ERR!
> npm ERR! Failed at the iq-submission-service@1.0.0 startw script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\smasilamani\AppData\Roaming\npm-cache\_logs\2021-01-29T10_54_45_846Z-debug.log

**Comment by cjbj** [comment]
@saachinsiva how are you going with this?  Did you try in a supported OS environment?

**Comment by saachinsiva** [comment]
> @saachinsiva how are you going with this? Did you try in a supported OS environment?

Hello 

I was able to fix it and the reason why it was failing is due to our new Oracle version 19c which automatically enabled out of band break. By adding this `DISABLE_OOB=on` to Sqlnet.ora I was able to make it work again.

Thanks

**Comment by cjbj** [comment]
Excellent.  And thanks for sharing the exact solution.  I'll pass the scenario onto our Net team.

I'll close this issue.

**Comment by cjbj** [comment]
@saachinsiva our Net team is interested in taking a look for their own reference.  Are you able to send traces (when disable_oob is not set)?

On the node-oracledb side (aka the client), manually create /somewhere/mylogs and set a client sqlnet.ora:

  adr_base=/somewhere/mylogs
  diag_adr_enabled=on
  trace_level_client=16

On the DB server side, add trace_level_server=16 to the DB server sqlnet.ora. DB traces will be in somewhere like /opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace

You can email me traces (see my profile)

**Comment by saachinsiva** [comment]
> @saachinsiva our Net team is interested in taking a look for their own reference. Are you able to send traces (when disable_oob is not set)?
> 
> On the node-oracledb side (aka the client), manually create /somewhere/mylogs and set a client sqlnet.ora:
> 
> adr_base=/somewhere/mylogs
> diag_adr_enabled=on
> trace_level_client=16
> 
> On the DB server side, add trace_level_server=16 to the DB server sqlnet.ora. DB traces will be in somewhere like /opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace
> 
> You can email me traces (see my profile)

@cjbj 
Sure will send you by end of day.

**Comment by saachinsiva** [comment]
@cjbj 

Hello

Sorry for the delay. I do not have access to our database so I cannot enable the logs on the server side but I here by attach the log file from the client side.

Note: Actual server name and dname have been changed in the trace file.
[trace.zip](https://github.com/oracle/node-oracledb/files/6045733/trace.zip)

Thanks

**Comment by cjbj** [comment]
@saachinsiva I'll pass it on.

**Comment by cjbj** [comment]
@saachinsiva The developers managed to reproduce it and have logged Oracle bug 32555079. A fix is planned. In the meantime, continue with the workaround. Thanks for taking the time to generate the traces.

**Comment by abrar-khan007** [comment]
Clear all temps then restart hope error will not pop , empty cache
