### ISSUE TITLE
Endless Loop w/ Installing on Windows

### ISSUE THREAD

**Issue by GaryFurash** [oracle/node-oracledb#134]
Whenever I have to install on Windows I end up in an endless loop of Visual Studio/C++ "hell" (not finding libraries, etc.). It would be awesome if someone could just share some pre-built windows binaries. It would be quicker for me to install the NodeJS version that matched whatever pre-built windows binary you shared than to manually install. Seriously, I'll pay someone $5 for this :-)

**Comment by cjbj** [comment]
Let's use https://github.com/joeferner/node-oracle/issues/134#issuecomment-118103093 for followup.

**Comment by cjbj** [comment]
Whoops.  I updated the link to point to the correct node-oracledb issue.
