### ISSUE TITLE
Error: ORA-21561: OID generation failed 

### ISSUE THREAD

**Issue by sasikumar2493** [oracle/node-oracledb#1344]
Hi Everyone,

Please help us to fix this issue.

When we are connecting our node JS application with Oracle Database 12c we are getting this issue intermittently in our production environment, we tried changing the host entry file with fully qualified name but still no luck.

Thanks in advance

**Comment by cjbj** [comment]
This is not specific to node-oracledb.  It's a network configuration issue, which you'll need to resolve.

I believe you have contacted Support about it?

**Comment by sasikumar2493** [comment]
Hello, but in same server when we are connecting .net application with oracle database, there is no problem in it.

**Comment by cjbj** [comment]
The error is coming from several layers below the node-oracledb driver.  If you look at the tech stack https://oracle.github.io/node-oracledb/doc/api.html#usermanual you can see the Oracle Client libraries. 

Your .NET app may be "managed", which is a completely different implementation.  

I don't like these errors either and have managed to get some code enhancements in the client libraries for some cases.  But fundamentally some uniqueness is required so global UIDs can be generated.

If you have an intermittent error, I'm guessing you have an intermittent timeout somewhere, perhaps DNS.

You could do worse than update your Oracle client libraries.  What version are you using (the issue template asked for this kind of detail for a reason !!!)?

**Comment by sasikumar2493** [comment]
Hello Christopher,

Currently we are using Oracle instant client 12.2 and the database version is 12c.

**Comment by cjbj** [comment]
Start by updating Oracle Instant Client.  The current version (19.10) will connect to your 12c DB.

**Comment by sasikumar2493** [comment]
Yes, we are connecting with Oracle Instant Client 19.10.

But once if we are rebooting the server, we are not getting the error for two weeks after that we started getting the error.
