### ISSUE TITLE
while connect Oracle db found OID (ora error)

### ISSUE THREAD

**Issue by ram2412** [oracle/node-oracledb#1347]
1. What versions are you using?

11.5

Give your database version.
Oracle 12.2
Also run Node.js and show the output of:

    process.platform
    process.version
    process.arch
    require('oracledb').versionString
    require('oracledb').oracleClientVersionString

-->

2. Is it an error or a hang or a crash?
Crash
3. What error(s) or behavior you are seeing?

White try to execute any pl sql block we found 
ORA-21561: OID generation failed
Cut and paste text showing the command you ran.  No screenshots.

Use a gist for long screen output and logs: see https://gist.github.com/

-->

4. Include a runnable Node.js script that shows the problem.

**Comment by cjbj** [comment]
Fix your network and/or computer configuration. 

You don't give the version of the Oracle client libraries.  Assuming they are circa 12.2, you could do worse than update them.  The current releases will still connect to Oracle DB 12.2.

Check some google hits.  See https://github.com/oracle/node-oracledb/issues/1344

**Comment by onmp** [comment]
Can you please turn on sqlnet tracing and upload the trace file?  Hopefully the trace file will help identifying the problem.
