### ISSUE TITLE
Add support for Apple Silicon - darwin arm64

### ISSUE THREAD

**Issue by mmunte-impeo** [oracle/node-oracledb#1349]
When using nodejs **compiled** for Apple Silicon, using the oracledb package will fail at runtime with the error:

NJS-045: cannot load a node-oracledb binary for Node.js xxx (darwin arm64) 

Please provide an darwin arm64 binary

**Comment by cjbj** [comment]
I agree.  However we need Oracle client libraries first, and that's out of scope of this project.

**Comment by mmunte-impeo** [comment]
@cjbj thx for the prompt reply. Do you know what is the best way to create a feature request for oracle to provide client libraries for ARM? I am happy to create a ticket asking for it.

I only cared to create a ticket for Apple Silicone, but since Windows 10 ARM is in insiders preview, this applies to Windows as well.

**Comment by cjbj** [comment]
@mmunte-impeo I think you need to go through Oracle Support.

Regarding Apple M1 specifically, it is a 'known' issue that I am in contact with our porting group on.  But having your official request logged via Oracle Support is always helpful.

**Comment by H0UST0N** [comment]
are we still unresolved?

**Comment by cjbj** [comment]
@H0UST0N Did you try building node-oracledb from source code and using the Intel Instant Client with Rosetta?

**Comment by H0UST0N** [comment]
> @H0UST0N Did you try building node-oracledb from source code and using the Intel Instant Client with Rosetta?

I managed to install oracle-db but I couldn't make instantclient work

> Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found.  Did find:
>         /usr/local/lib/libclntsh.dylib: mach-o, but wrong architecture
>         /usr/local/lib/libclntsh.dylib: mach-o, but wrong architecture
>         /Users/houston/Downloads/instantclient_19_8/libclntsh.dylib.19.1: mach-o, but wrong architecture". See https://oracle.github.io/node-oracledb/INSTALL.html for help
> Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
> You must have the arm64 Oracle Instant Client Basic or Basic Light package libraries in
> /usr/local/lib or set by calling oracledb.initOracleClient({libDir: "/my/instant_client_directory"}).
> Oracle Instant Client can be downloaded from https://www.oracle.com/database/technologies/instant-client.html
>

**Comment by cjbj** [comment]
Did you install Rosetta?

**Comment by jwinkels** [comment]
Same problem here... 
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found. Did find:
/usr/local/lib/libclntsh.dylib: mach-o, but wrong architecture
/usr/local/lib/libclntsh.dylib: mach-o, but wrong architecture
/Users/houston/Downloads/instantclient_19_8/libclntsh.dylib.19.1: mach-o, but wrong architecture". See https://oracle.github.io/node-oracledb/INSTALL.html for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the arm64 Oracle Instant Client Basic or Basic Light package libraries in
/usr/local/lib or set by calling oracledb.initOracleClient({libDir: "/my/instant_client_directory"}).
Oracle Instant Client can be downloaded from https://www.oracle.com/database/technologies/instant-client.html

I've installed Rosetta and using it in Terminal. 
Also tried to create a Ticket at Oracle Support but unfortunately Oracle Instant Client is not available at product list.

**Comment by lednhatkhanh** [comment]
@jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.

**Comment by cjbj** [comment]
@lednhatkhanh thanks for sharing that info!

**Comment by H0UST0N** [comment]
> @jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.

thank you!
it worked out!

**Comment by jwinkels** [comment]
> @jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.

What do you mean with "install node from the homepage directly". I tried to build node, I tried to install node by binary. The result was the same. Of course I used the Mac Version of node.

**Comment by H0UST0N** [comment]
> > @jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.
> 
> @lednhatkhanh What do you mean with "install node from the homepage directly". I tried to build node, I tried to install node by binary. The result was the same. Of course I used the Mac Version of node.

I deleted all versions of node from my machine and downloaded the following version and installed normally:

https://nodejs.org/dist/v14.17.5/node-v14.17.5.pkg

I tried version 16 but it didn't work

**Comment by lednhatkhanh** [comment]
@H0UST0N It's because nodejs 16 supports M1 natively, running the installer will install `arm64` version.

@cjbj I really hope that node-oracledb will support M1 before Nodejs 16 becomes LTS.

**Comment by cjbj** [comment]
@lednhatkhanh this is not a node-oracledb issue (yet).  We need Instant Client on M1 first, which I don't have direct control over.

**Comment by luckyyyyy** [comment]
> @lednhatkhanh这不是 node-oracledb 问题（还）。我们首先需要 M1 上的 Instant Client，我无法直接控制它。

we hope to have it soon ╥﹏╥

**Comment by luckyyyyy** [comment]
> @lednhatkhanh this is not a node-oracledb issue (yet). We need Instant Client on M1 first, which I don't have direct control over.

we hope to have it soon ╥﹏╥

**Comment by platzhersh** [comment]
@H0UST0N @lednhatkhanh So you are saying one should install the intel version of Node to be able to use the intel version of oracle-nodedb at the moment?
Asking, because I did that first (with v12), and the performance of node running on Rosetta was horribly bad. I could give it another go with v14.

**Comment by luckyyyyy** [comment]
> @H0UST0N @lednhatkhanh So you are saying one should install the intel version of Node to be able to use the intel version of oracle-nodedb at the moment?
> Asking, because I did that first (with v12), and the performance of node running on Rosetta was horribly bad. I could give it another go with v14.

Using Rosetta run nodejs performance is bad, but it is also the only way to use Oracle client

**Comment by leoromanovsky** [comment]
I had success installing intel node using nvm and rosetta terminal following this guide; https://gist.github.com/LeZuse/bf838718ff2689c5fc035c5a6825a11c

**Comment by chill389cc** [comment]
I can also confirm, installing node-v14.17.5 from the installer after fully uninstalling node (see [this](https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x?rq=1) thread) allows for `npm install oracledb` to run without issue. Thanks!

**Comment by tcastelly** [comment]
Hello,

I have slightly the same error on Linux ARM:
> NJS-067: a pre-built node-oracledb binary was not found for linux arm64

Because Oracle Client for Linux ARM is available I thought it will works.

**Comment by khanh-le-otsv** [comment]
Does anyone knows how to use Nodejs 16 with the Rosetta Instant Client? Thank you.

**Comment by nibravo** [comment]
> I had success installing intel node using nvm and rosetta terminal following this guide: https://gist.github.com/LeZuse/bf838718ff2689c5fc035c5a6825a11c
> 
> I was then able to run `npm install` in the [typeorm](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md) project, which uses `node-oracledb`

Hello @leoromanovsky, have you noticed a lack of performance by using this approach? 
I currently building an ETL from OracleDB to Postgresql using an Intel Macbook, and I'm worried the development will become a hell If I switch to a M1 macbook as I'm currently planning to do.

Thanks a lot!

**Comment by tcastelly** [comment]
> Does anyone knows how to use Nodejs 16 with the Rosetta Instant Client? Thank you.

Hello,

Unfortunately I did not managed to run my application with NodeJS 16. But, the `oracledb` is available on Linux arm64. I simplified the process with a Docker image. [Here an example](https://github.com/shenron/docker-node/tree/master/oracle_client/example).

I hope it can help.

I'm looking forward for a native solution 🤞

**Comment by stephanieraymos** [comment]
> @jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.

THIS is what finally fixed it for me.
I'm on an m1 macbook air
Current node version: 16.11.0 (but also tried with node versions 14 and 15 and had no luck.)
Instantclient 19_8

This error occured when attempting lint my vue project on commit:
`cannot load a node-oracledb binary for Node.js 16.11.0 darwin arm64`

When I attempted to install oracledb I got this error:
`a pre-built node-oracledb binary was not found for darwin arm64`

I tried install via yarn and npm and also tried using rosetta.

I also tried this on a fresh project with no dependencies in package.json.

And FINALLY! - I went and downloaded the macOS installer .pkg [here](https://nodejs.org/en/download/)
Went through the installation process, and then I was able to `yarn add oracledb` using Rosetta. In order to commit I also had to use Rosetta but it WORKED!

**Comment by nibravo** [comment]
> > @jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.
> 
> THIS is what finally fixed it for me. I'm on an m1 macbook air Current node version: 16.11.0 (but also tried with node versions 14 and 15 and had no luck.) Instantclient 19_8
> 
> This error occured when attempting lint my vue project on commit: `cannot load a node-oracledb binary for Node.js 16.11.0 darwin arm64`
> 
> When I attempted to install oracledb I got this error: `a pre-built node-oracledb binary was not found for darwin arm64`
> 
> I tried install via yarn and npm and also tried using rosetta.
> 
> I also tried this on a fresh project with no dependencies in package.json.
> 
> And FINALLY! - I went and downloaded the macOS installer .pkg [here](https://nodejs.org/en/download/) Went through the installation process, and then I was able to `yarn add oracledb` using Rosetta. In order to commit I also had to use Rosetta but it WORKED!

Hi @stephanieraymos , by which way did you install IntantClient? I managed to install oracledb by installing node with the official PKG and run npm in a Terminal running with Rosetta 2, but I can't manage to work InstantClient (installed by homebrew).

Thanks a lot!

**Comment by stephanieraymos** [comment]
> Hi @stephanieraymos , by which way did you install IntantClient? I managed to install oracledb by installing node with the official PKG and run npm in a Terminal running with Rosetta 2, but I can't manage to work InstantClient (installed by homebrew).
> 
> Thanks a lot!

Hi, I installed it from [here](https://www.oracle.com/database/technologies/instant-client/macos-intel-x86-downloads.html) on the oracle website. Good luck.

**Comment by rathboma** [comment]
Firstly - thank you for maintaining this library!

Question -- is it possible to have the native components of this package compile on apple/arm64 CPUs even if the instant client isn't available?

I have an Electron app that I distribute to both intel and arm64 macs, but building two separate binaries for the app under MacOS (one with Oracle support, one without) is a total pain.

While I get that it won't 'work' without the instant client being migrated to arm64, if this library can at least be included in arm packages it would be a huge benefit on it's own (at least to me!).

**Comment by rathboma** [comment]
I just downloaded and compiled this repo on my M1 mac, and everything seems to compile fine? I could run `install`, `buildbinary` and `buildpackage`.

Am I missing something?
If not, could builds for arm-mac, and arm-linux be added to your CI scripts?

**Comment by rathboma** [comment]
@masterodin ^ this would help you too right?

**Comment by MasterOdin** [comment]
We currently work around the package not being installable on M1 by having a separate install script that removes this from the package.json, updates the lock file, and then re-inserts whatever is necessary. It's hacky, but it works:

```
const { spawnSync } = require('child_process');
const { copyFileSync, readFileSync, unlinkSync, writeFileSync } = require('fs');
const path = require('path');

const expandDeps = ['oracledb@^5.2.0'];

const yarnLockPath = path.join(__dirname, 'yarn.lock');
const yarnBakPath = `${yarnLockPath}.bak`;
copyFileSync(yarnLockPath, yarnBakPath);

copyFileSync(
  path.join(__dirname, 'package.json'),
  path.join(__dirname, 'package.json.bak'),
);

const packageJson = JSON.parse(
  readFileSync(path.join(__dirname, 'package.json'), 'utf8'),
);
expandDeps
  .map((dep) => dep.split('@')[0])
  .forEach((pkg) => delete packageJson.dependencies[pkg]);
writeFileSync(
  path.join(__dirname, 'package.json'),
  JSON.stringify(packageJson, null, 2),
);

spawnSync('yarn', { cwd: __dirname, stdio: 'inherit' });

copyFileSync(
  path.join(__dirname, 'package.json.bak'),
  path.join(__dirname, 'package.json'),
);
unlinkSync(path.join(__dirname, 'package.json.bak'));

const lockfile = require('@yarnpkg/lockfile');
const { isEqual } = require('lodash');

const oldYarnLock = lockfile.parse(readFileSync(yarnBakPath, 'utf8')).object;
const yarnLock = lockfile.parse(readFileSync(yarnLockPath, 'utf8')).object;
const yarnLockDeps = Object.values(yarnLock);

// For every dependency we need to expand, we find the corresponding entry in
// the old lockfile and copy it over to the new lockfile, adding any of its dependencies
// to the list of dependencies to expand if it's not already in the new lockfile.
while (expandDeps.length) {
  const dep = expandDeps.shift();
  const oldDep = oldYarnLock[dep];
  // We first check if we have a matching dependency in our new lockfile falling back
  // on copying over the old dependency object if we don't. yarn condenses lockfile
  // entries based on the objects being the same memory reference vs checking their
  // contents, so if we just use `oldDep`, then it'll appear as its own entry even
  // if it would make sense to condense it with another entry of that package.
  yarnLock[dep] = yarnLockDeps.find((d) => isEqual(d, oldDep)) || oldDep;
  Object.entries(yarnLock[dep].dependencies || {}).forEach(([key, version]) => {
    const newDep = `${key}@${version}`;
    if (!yarnLock[newDep]) {
      expandDeps.push(newDep);
    }
  });
}

unlinkSync(yarnBakPath);
writeFileSync(yarnLockPath, lockfile.stringify(yarnLock), {
  encoding: 'utf8',
});
```

At this point given the above, having the dependency itself be installable would be nice to be able to get away from having to do `yarn m1-install` instead of `yarn install`, but it's pretty low importance given that actually connecting to Oracle would still be broken, and preventing us from producing proper M1 builds of the app.

**Comment by rathboma** [comment]
For those interested, here's a version with compiled binaries for ARM64 darwin and ARM64 linux. It works, although on Mac you can't connect due to the lack of an available instant client, still helpful non the less:

https://www.npmjs.com/package/bks-oracledb

**Comment by cjbj** [comment]
@rathboma thanks for sharing.  If you update the readme & repo links then people looking at that npm package page will know what it for.

Also, has anyone looked at creating a macOS universal binary with the npm tooling?

**Comment by codytooker** [comment]
I'm like many others am running into the same problem. However I can't install node from the nodejs.org site, simply because I need NVM for the many other projects I work on with different base node environments.  

Does anyone know if it's possible to have `nvm` as default for the system but set a particular directory to use a completely different version of node not managed by `nvm`, and if if so how?

**Comment by bryzaguy** [comment]
Would it be possible to use the Linux arm64 client?
https://www.oracle.com/database/technologies/instant-client/linux-arm-aarch64-downloads.html

Their blog gives me the impression it might be possible:
https://blogs.oracle.com/linux/post/oracle-linux-9-with-qemu-on-an-m1-mac

**Comment by cjbj** [comment]
A related link: https://github.com/oracle/docker-images/issues/2447

**Comment by stevefan1999-personal** [comment]
Would you guys like to provide a ARM64 prebuilt binaries as well?

**Comment by cjbj** [comment]
@stevefan1999-personal I had a quick look at this for the 5.5 release but hit some tool chain issues and decided not to delay that release.

**Comment by chandra-wego** [comment]
> > @jwinkels @H0UST0N You probably installed node with either `nvm` or `brew`, by doing that you will install the `arm64` version and get this error. The only solution for now is to download and install node from the homepage directly.
> 
> thank you! it worked out!

It Worked , Thanks

**Comment by arthurlch** [comment]
November 2022 -  installing node-v14.17.5 from pkg directly is still the soution to this problem for arm64.

Any version from ~ node-v15.xx.xx will not work.

**Comment by cjbj** [comment]
@arthurlch do you know why the newer ones won't work?  There are 64-bit tar.gz packages on https://nodejs.org/en/download/ that appear to be Intel only:
```
cjones@mac:~/Downloads/node-v18.12.1-darwin-x64/bin$ file node
node: Mach-O 64-bit executable x86_64
```

**Comment by arthurlch** [comment]
@cjbj I'd like to be able to give you a correct answer, therefore for now I can only make a guess. 

The newer version might not work with Rosetta due to some issues with vectors version, it is merely speculations. 

It should be technically possible to install it tho but will not be able to run correctly.

Might be able to have a workout around using docker and running instantclient with it. Would probably be able to avoid dealing with both architectures. 

If I find a way to make the newer version I will share it here.

**Comment by jodem** [comment]
Hello a solution that works with nvm : https://gist.github.com/LeZuse/bf838718ff2689c5fc035c5a6825a11c
you need to open a terminal with rosetta enable (duplucate your terminal utility and rename it to convinience) then with nvm you can install the node version you need .

node -e 'console.log(process.arch)' should give you x64

**Comment by MasterOdin** [comment]
Happy new year @cjbj. I was wondering if there was any update on the state of a node "thin client" that you had mentioned here/other issues? Anything the community could do to help the process?

**Comment by cjbj** [comment]
@MasterOdin I'm in a meeting about it just now.  

I need to be careful about not making public commitments the team can't keep.  I will say that it was pretty cool to try the code we do have with Webpack.  Having a single, not huge, presumably portable JS file that connected to the DB was fun.  There were some Webpack packaging warnings during build.  Community focus on these if/after we release code would be good.

**Comment by cyates81** [comment]
@cjbj Hello, are you saying that we may soon have a node oracle driver that doesn't require the instant client? That sure would be awesome.

In my case using Rosetta is difficult because I work on a lot of projects that don't require oracledb and switching back and forth between x64 and arm64 is a pain. Really hoping for a native darwin arm64 build soon.

Thanks!

**Comment by cjbj** [comment]
@cyates81 that is the plan. It will have 'Thin' and 'Thick' modes similar to python-oracledb, see [here](https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html), and similar functionality availability differences between the modes.

**Comment by enzofrnt** [comment]
Hi, I'm having issue on Mac with Apple Silicon… And i'm french so that hard for me to understand what is going on… Can someone help me ?
```
enzofournet@Enzos-MacBook-Pro ~ % npm i oracledb
npm ERR! code 87
npm ERR! path /Users/enzofournet/node_modules/oracledb
npm ERR! command failed
npm ERR! command sh -c -- node package/install.js
npm ERR! oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for darwin arm64
npm ERR! oracledb ERR! Try compiling node-oracledb source code using https://oracle.github.io/node-oracledb/INSTALL.html#github

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/enzofournet/.npm/_logs/2023-02-02T10_45_46_489Z-debug-0.log
```

**Comment by tcastelly** [comment]
> Hi, I'm having issue on Mac with Apple Silicon… And i'm french so that hard for me to understand what is going on… Can someone help me ?
> 
> ```
> enzofournet@Enzos-MacBook-Pro ~ % npm i oracledb
> npm ERR! code 87
> npm ERR! path /Users/enzofournet/node_modules/oracledb
> npm ERR! command failed
> npm ERR! command sh -c -- node package/install.js
> npm ERR! oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for darwin arm64
> npm ERR! oracledb ERR! Try compiling node-oracledb source code using https://oracle.github.io/node-oracledb/INSTALL.html#github
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/enzofournet/.npm/_logs/2023-02-02T10_45_46_489Z-debug-0.log
> ```

Like explained above, right now you don't have an arm64 (m1/m2) binary for oracledb. But you can build it yourself for Linux arm64 and used it throw a Linux container.
Or try to install and run your application with NodeJS x86 and Rosetta.

**Comment by enzofrnt** [comment]
thx, now is installed, but my vscode extension can't find it
<img width="299" alt="image" src="https://user-images.githubusercontent.com/63660254/216387279-35cf8724-224e-4d7e-893f-81b24fbb280b.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/63660254/216387410-41a6114f-4e11-48f2-a6d6-a97456458145.png">
Any idea ?

**Comment by enzofrnt** [comment]
> > thx, now is installed, but my vscode extension can't find it <img alt="image" width="299" src="https://user-images.githubusercontent.com/63660254/216387279-35cf8724-224e-4d7e-893f-81b24fbb280b.png"> <img alt="image" width="466" src="https://user-images.githubusercontent.com/63660254/216387410-41a6114f-4e11-48f2-a6d6-a97456458145.png"> Any idea ?
> 
> Have you configured the instant client? If not you'll need to do that and install oracledb on a project basis not a global. Installing oracledb does not connect the instant client.

Obviously, i don't know how npm work.. But I understand what you mean.
So, I will need to find a way to install oracledb on the client of my vscode extension, but how ?

**Comment by enzofrnt** [comment]
https://user-images.githubusercontent.com/63660254/216397724-7d1370b1-3266-4d9b-bbd2-7021d45f6519.mov
That strange.

**Comment by enzofrnt** [comment]
That strange, look

https://user-images.githubusercontent.com/63660254/216398475-d6ad2af7-3736-4e0f-9230-0f3d42d00938.mp4

**Comment by enzofrnt** [comment]
I try some things 

<img width="1025" alt="Capture d’écran 2023-02-04 à 21 59 00" src="https://user-images.githubusercontent.com/63660254/216789418-c3c668f2-a416-4869-9189-855e32a5dbdd.png">
<img width="978" alt="Capture d’écran 2023-02-04 à 21 58 07" src="https://user-images.githubusercontent.com/63660254/216789422-a4046fd0-3f38-4e7c-973d-581239e33919.png">

**Comment by enzofrnt** [comment]
the error is the same in vscode.. btw

**Comment by akim3235** [comment]
> I had success installing intel node using nvm and rosetta terminal following this guide: https://gist.github.com/LeZuse/bf838718ff2689c5fc035c5a6825a11c
> 
> I was then able to run `npm install` in the [typeorm](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md) project, which uses `node-oracledb`

I found this guidance a bit tedious. There is a much shorter way. In your terminal:
```
$ nvm uninstall 16
$ arch -x86_64 zsh 
$ nvm install 16
$ nvm alias default 16
``` 

Check:
`$ arch 
` should show i386

Switch back to arm architecture:
`arch -arm64 zsh`

**Comment by enzofrnt** [comment]
Nice, thanks. But, I just find another extension.

**Comment by cjbj** [comment]
The other piece is to install Instant Client x86 on your M1/M2 machine.  You can simply run the same commands that you run on Apple Intel:
```
  cd $HOME/Downloads

  curl -O https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
  curl -O https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-sqlplus-macos.x64-19.8.0.0.0dbru.dmg

  hdiutil mount instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
  hdiutil mount instantclient-sqlplus-macos.x64-19.8.0.0.0dbru.dmg

  /Volumes/instantclient-basic-macos.x64-19.8.0.0.0dbru/install_ic.sh

  hdiutil unmount /Volumes/instantclient-basic-macos.x64-19.8.0.0.0dbru
  hdiutil unmount /Volumes/instantclient-sqlplus-macos.x64-19.8.0.0.0dbru
```
With this, your i386 Node.js code is initialized the same on M1 and Intel:

**Comment by ada-lovecraft** [comment]
> The other piece is to install Instant Client x86 on your M1/M2 machine. You can simply run the same commands that you run on Apple Intel:
> 
> ```
>   cd $HOME/Downloads
> 
>   curl -O https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
>   curl -O https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-sqlplus-macos.x64-19.8.0.0.0dbru.dmg
> 
>   hdiutil mount instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
>   hdiutil mount instantclient-sqlplus-macos.x64-19.8.0.0.0dbru.dmg
> 
>   /Volumes/instantclient-basic-macos.x64-19.8.0.0.0dbru/install_ic.sh
> 
>   hdiutil unmount /Volumes/instantclient-basic-macos.x64-19.8.0.0.0dbru
>   hdiutil unmount /Volumes/instantclient-sqlplus-macos.x64-19.8.0.0.0dbru
> ```
> 
> With this, your i386 Node.js code is initialized the same on M1 and Intel:
> 
> ```
> oracledb.initOracleClient({ libDir: process.env.HOME + '/Downloads/instantclient_19_8' });
> ```

You... you just made my life easier. I award you a billion internet points.

**Comment by wenjiasen** [comment]
If you are not using an Oracle database and are only encountering this error due to the installation of `TypeORM`, you can add `omit = peer` in the `.npmrc` file to skip the installation.

**Comment by cjbj** [comment]
The [just-released node-oracledb 6.0](https://medium.com/@sharad-chandran/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2)'s default Thin mode works very nicely on M1 since it doesn't need Instant Client.

Providing Instant Client for M1 is out of scope of the node-oracledb driver project so I'll close this issue.

**Comment by mason2205** [comment]
I'm still facing with this problem although I tried many way. Anyone can help me

**Comment by platzhersh** [comment]
Just use version 6 of the package

mason2205 ***@***.***> schrieb am Sa., 28. Okt. 2023, 09:11:

**Comment by josephtveterihc** [comment]
I am connecting to an old database I have no control over. Our pipeline needs to run on Node 18. So I must use node-oracledb ^6.0 Thick Mode.

Has anyone got this to build/run?

node-oracledb ^6.0 Thick Mode
Node: v18.20.2
Mac M2 chipset (darwin arm64)

If I had hair I would be pulling it out.

**Comment by usersina** [comment]
In yarn, you can simply build the dependency from source

```bash
yarn add oracledb --build-from-source
```

**Comment by sharadraju** [comment]
> > @josephtveterihc @wattry macOS ARM Instant Client is now available! https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html https://www.oracle.com/database/technologies/instant-client/downloads.html https://www.oracle.com/database/technologies/instant-client/precompiler-downloads.html
> > Please run your Thick mode code with the latest macOS ARM Instant Client.
> 
> @sharadraju awesome thanks! Is there a timeline on when it will be included as part of the package build binaries so we don't have to manage that build in an external process?

Hopefully in a future release, that comes soon :)

**Comment by gauravbadola20** [comment]
i did all these things, but still not resolved this issue.

**Comment by sharadraju** [comment]
> i did all these things, but still not resolved this issue.

The latest version of node-oracledb (6.6 onwards) has Apple ARM 64 binaries. Please upgrade to the latest version
