### ISSUE TITLE
Webpack Error: NJS-069: node-oracledb 5.1.0 requires Node.js 8.16 or later

### ISSUE THREAD

**Issue by kaddalasiva** [oracle/node-oracledb#1352]
node version is 12.19.0
npm version is 7.6.3
oracledb version is  5.1.0
<img width="1792" alt="Screenshot 2021-03-18 at 5 54 59 PM" src="https://user-images.githubusercontent.com/43607808/111657063-1a3e5600-8831-11eb-88c2-5f5f3680848b.png">
can some one help me? Thanks

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/1156#issuecomment-598017250 for everything I know about it.

**Comment by kaddalasiva** [comment]
hay,hai @cjbj 
i am very new to this , How can i do this? can you help me Please?

**Comment by cjbj** [comment]
@kaddalasiva I'm not a webpack user, sorry.

**Comment by cjbj** [comment]
For future readers of this issue, check out my blog post [Bundling node-oracledb JavaScript apps with Webpack](https://node-oracledb.readthedocs.io/en/latest/user_guide/appendix_a.html#featuresummary).
