### ISSUE TITLE
Geopy

### ISSUE THREAD

**Issue by sdamte0428** [oracle/node-oracledb#1353]
1. What versions are you using?

2. Describe the problem

3. Include a runnable Node.js script that shows the problem.

how do I find the distance between two addresses using pl sql or using geopy library in python to find driving distance ?

Thanks,

**Comment by cjbj** [comment]
That's off topic in two directions for this repo, so excuse me closing this.

For SQL & PL/SQL you can ask at asktom.oracle.com or at https://community.oracle.com/tech/developers/categories/sql_and_pl_sql  

For Python geopy I'll have to let you google where to post.

**Comment by sdamte0428** [comment]
Hello, 
 I am using python 3.8 and running my program on virtual machine .I am using ArcGIS Rest API integrated with the company website .


the code seems not having a problem but when I pass the file path to pick up the origins and destination address , it automatically giving me error message e" OS error:[Errno 2] No such file or directory " the file and path does exist.

Thanks,

**Comment by cjbj** [comment]
This isn't a Python repo.  Please ask your question on another forum.
