### ISSUE TITLE
"Error: ORA-01008: not all variables bound" when reusing bind values

### ISSUE THREAD

**Issue by danailch456** [oracle/node-oracledb#1355]
Node version: 14.15.1
Node-oracledb version: 5.1.0
Oracle DB version: 11.2.0.4.0 Enterprise Edition

I am executing the following 2 queries inside Oracle SQL Developer and it works as intended: 
```
SELECT * FROM RANDOM_TABLE WHERE FIELD0 = :0 OR FIELD1 = :0

SELECT * FROM RANDOM_TABLE WHERE FIELD0 = :0 OR FIELD1 = :0 AND FIELD2 = :1
```

However when I try executing the same queries but through node-oracledb, the first one works as intended (uses the only given bind to fill both uses of **:0**), but on the second query I get the following error `Error: ORA-01008: not all variables bound` which by the looks of it is caused by node-oracledb expecting 3 bind parameters, insted of using the first bound value to fill both of it's references and after that using the second.

nodejs code:
```
connection.execute(
  'SELECT * FROM RANDOM_TABLE WHERE FIELD0 = :0 OR FIELD1 = :0', 
  [9],
  { outFormat: 4002, maxRows: 1 }
);

connection.execute(
  'SELECT * FROM RANDOM_TABLE WHERE FIELD0 = :0 OR FIELD1 = :0  AND FIELD2 = :1', 
  [9, 99],
  { outFormat: 4002, maxRows: 1 }
);
```

**Comment by cjbj** [comment]
Likely a difference between JDBC and OCI.  (Feel free to log a bug against JDBC!)

From the [doc](https://oracle.github.io/node-oracledb/doc/api.html#bind):

> The position of the array values corresponds to the position of the SQL bind parameters as they occur in the statement, regardless of their names. This is still true even if the bind parameters are named like :0, :1, etc
