### ISSUE TITLE
executeMany() is taking much longer time to execute

### ISSUE THREAD

**Issue by sarikonda1** [oracle/node-oracledb#1356]
excuteMany() is taking nearly 4 mins to update 14388 records. is there any way to update as much as less time possible ??.

Please see my oracle pool configuration for reference..

pool = await oracledb.createPool({
      user: process.env.NODE_ORACLEDB_USER,
      password: process.env.NODE_ORACLEDB_PASSWORD,
      connectString: process.env.NODE_ORACLEDB_CONNECTIONSTRING,
      poolMin: 10,
      poolMax: 50,
      poolIncrement: 5  
    })
    
 one more question ..
 i am doing doing bulk insert using executeMany() to insert 100000 ..it's taking almost 20mins to execute...
 But i need to execute in as less time as possible..
 Please update me the solution 
 Am very thankfull for your solution...

**Comment by sarikonda1** [comment]
excuteMany() is taking nearly 4 mins to update 14388 records. is there any way to update as much as less time possible ??.

Please see my oracle pool configuration for reference..

pool = await oracledb.createPool({
user: process.env.NODE_ORACLEDB_USER,
password: process.env.NODE_ORACLEDB_PASSWORD,
connectString: process.env.NODE_ORACLEDB_CONNECTIONSTRING,
poolMin: 10,
poolMax: 50,
poolIncrement: 5
})

one more question ..
i am doing doing bulk insert using executeMany() to insert 100000 ..it's taking almost 20mins to execute...
But i need to execute in as less time as possible..
Please update me the solution
Am very thankfull for your solution...

**Comment by cjbj** [comment]
Dup of #1358
