### ISSUE TITLE
Slow queries with date in binds (oracle 11g)

### ISSUE THREAD

**Issue by Crutchmaster** [oracle/node-oracledb#1357]
db verison: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

process.platform >> "linux"
process.version >> "v12.18.0"
process.arch >> "x64"
require('oracledb').versionString >> 5.1.0 
require('oracledb').oracleClientVersionString >> 11.2.0.4.0

```
let oracle = require('oracledb');

let conn = await oracle.getConnection(host, user, blahblahblah);

let slowSql = "select a,b,c from x.tbl where dt1 >= :dt1 and dt2 <= :dt2";
let bindWithDates = {
  dt1 : new Date("2021-03-01"),
  dt2 : new Date("2021-03-31")
}
conn.execute(slowSql, bindWithDates) // <--- 1500-2000 ms

let fastSql = "select a,b,c from x.tbl where dt1 >= to_date(:dt1) and dt2 <= to_date(:dt2)";
let bindWithStrings = {
  dt1 : "2021-03-01",
  dt2 : "2021-03-31"
}
conn.execute(fastSql, bindWithStrings) // <--- 300-400 ms
```

I can write runnable Node.js script with db schema if you really need it.

**Comment by cjbj** [comment]
- Check the EXPLAIN PLAN to see what the Oracle DB optimizer is doing
- Try a more recent version of Oracle DB like 19.9 or later - not something that is ~64 dog years (!) old.  There have been various Oracle DB optimizer improvements when binding dates, e.g. fixes to bug 12882092 and bug 31253713.  Contact Oracle Support for more information - the optimizer's behavior is out of scope of the node-oracledb project.
- Try binding with an explicit type `oracledb.DB_TYPE_DATE`, see https://oracle.github.io/node-oracledb/doc/api.html#executebindparamtype
- Try using hints

**Comment by Crutchmaster** [comment]
> Try a more recent version of Oracle DB like 19.9 or later

¯\_(ツ)_/¯
Enterprise production
>not something that is ~64 dog years (!) old

Tomorrow this old dog works fine. I will try hints or something else.
Oracle problems, issue can be closed, thanks for help.

**Comment by cjbj** [comment]
@Crutchmaster Let us know how you go.  Thanks for taking the time to report the issue; it's good to have on record.
