### ISSUE TITLE
executeMany() bulk update/insert issue

### ISSUE THREAD

**Issue by sarikonda1** [oracle/node-oracledb#1358]
excuteMany() is taking nearly 4 mins to update 14388 records. is there any way to update as much as less time possible ??.

Please see my oracle pool configuration for reference..

pool = await oracledb.createPool({
user: process.env.NODE_ORACLEDB_USER,
password: process.env.NODE_ORACLEDB_PASSWORD,
connectString: process.env.NODE_ORACLEDB_CONNECTIONSTRING,
poolMin: 10,
poolMax: 50,
poolIncrement: 5
})

one more question ..
i am doing doing bulk insert using executeMany() to insert 100000 ..it's taking almost 20mins to execute...
But i need to execute in as less time as possible..
Please update me the solution
Am very thankfull for your solution...

**Comment by cjbj** [comment]
The first thing you need to do is identify why it is slow:
- Do you have a connection issue with [threading](https://oracle.github.io/node-oracledb/doc/api.html#numberofthreads)
- Is reading the data into Node.js and/or constructing the bind argument slow?
- Is your network slow? 
- Do have table indexes that are causing inserts to be slow?

**Comment by sarikonda1** [comment]
hello @cjbj please find below my comment for your question

Do you have a connection issue with threading ---> NO
Is reading the data into Node.js and/or constructing the bind argument slow -> No it's taking in msec
Is your network slow? --> No not at all
Do have table indexes that are causing inserts to be slow-->I don't have indexs on the table which am performing query
Check for best practices, e.g. this (which is old; there might be better resources out there).--->Yeah used same 
If the data is on disk, then use SQL*Loader, perhaps with the Direct Path load feature?  --> i don't have data on DIsk


And even i try to set SET UV_THREADPOOL_SIZE  value BUt still it's fetting slowly...
For 55222 records update it's taking also 25 mins to complete it 
In that update query i do have only one where condition...


Please find some reference:::

Query::
update SomeTable set ASSOCN_CLIENT_ID=:1,DWNSTRM_IND=:2,CLNT_ORDR_NUM=:3,PRODT_EFF_DT=to_date(:4,'YYYY-MM-DD'),PRODT_TERM_DT=to_date(:5,'YYYY-MM-DD') where  ASSOCN_ORDR_NUM=:6;

options = { outFormat: oracledb.OUT_FORMAT_OBJECT, autoCommit: true };
updateBindData = [ ['1','2', '3','4', '5','6'] , ['1','2', '3','4', '5','6']  , ['1','2', '3','4', '5','6']  ..........55222 Records]
 connection.executeMany(updateQuery, updateBindData, options);

P.S ::: ASSOCN_ORDR_NUM does have uniq values in the column..

**Comment by cjbj** [comment]
Why is it slow?  You need to debug it more and tell us what part of the system is slow.  Is there a pattern when you insert different numbers of rows?  Try using SQL*Loader and see how fast that is.

**Comment by frg-tarasov** [comment]
I have faced with interesting problem about `executeMany`. I don't know it's ok or not but `executeMany` really slow with procedures when a procedure has out parameters.

I have created [demo repository](https://github.com/frg-tarasov/node-oracledb-bulk-insert) which shows this. I wrapped output parameters with begin-end variables and it has began work very quickly.

Measures:

```bash
'time 1: 14.962s' # with out parameters
'time 2: 223.178ms' # without
```

**Comment by cjbj** [comment]
@frg-tarasov please open a new issue.  Thanks!

**Comment by frg-tarasov** [comment]
Ok, I will do.

**Comment by cjbj** [comment]
I'm closing this issue since the original requestor hasn't responded.
