### ISSUE TITLE
Which Approach of getting a connection should preffered and if both are unique then explain the difference

### ISSUE THREAD

**Issue by sannPropelApps** [oracle/node-oracledb#1359]
const oracledb = require('oracledb');

let conn;

// like this ,first getting pool and then connection from that pool
const myPool = oracledb.getPool(process.env['poolAliasName']);
        conn = myPool.getConnection(process.env['poolAliasName']);

// or directly from db using pool alias name

        conn = await oracledb.getConnection(process.env['poolAliasName']);

**Comment by cjbj** [comment]
The end result is the same: you get a connection.  Use whatever syntax makes your code cleanest and easiest to understand.  I.e. use the simplest one.  If you use the first code snippet, don't forget to add an `await` when getting the connection.

If you only have one pool, then you could get rid of the poolAliasName and let it default, see [webapp.js](https://github.com/oracle/node-oracledb/blob/v5.1.0/examples/webapp.js).  Hope this helps.
