### ISSUE TITLE
Error while installing oracledb! (npm and node are installed though)

### ISSUE THREAD

**Issue by BalaRavilla** [oracle/node-oracledb#136]
Hi, I have been trying to install oracledb with node npm in my windows os. I have followed almost all possibilities and finally ended up with a strange error that i could not debug anymore. Before i giveup, i just wanted to check here if i cen get some help.

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\software\\node\\nodejs\\\\node.exe',
1 verbose cli   'D:\\software\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'oracledb' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose install initial load of D:\software\node\nodejs\package.json
5 warn package.json nodeinstall@1.0.0 No repository field.
6 warn package.json nodeinstall@1.0.0 No README data
7 verbose installManyTop reading scoped package data from D:\software\node\nodejs\node_modules\npm\package.json
8 verbose installManyTop reading scoped package data from D:\software\node\nodejs\node_modules\socket.io\package.json
9 info package.json socket.io@1.3.5 No license field.
10 verbose readDependencies loading dependencies from D:\software\node\nodejs\package.json
11 silly cache add args [ 'oracledb', null ]
12 verbose cache add spec oracledb
13 silly cache add parsed spec { raw: 'oracledb',
13 silly cache add   scope: null,
13 silly cache add   name: 'oracledb',
13 silly cache add   rawSpec: '',
13 silly cache add   spec: '*',
13 silly cache add   type: 'range' }
14 silly addNamed oracledb@*
15 verbose addNamed "*" is a valid semver range for oracledb
16 silly addNameRange { name: 'oracledb', range: '*', hasData: false }
17 silly mapToRegistry name oracledb
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry http://registry.npmjs.org/
20 silly mapToRegistry uri http://registry.npmjs.org/oracledb
21 verbose addNameRange registry:http://registry.npmjs.org/oracledb not in flight; fetching
22 verbose request uri http://registry.npmjs.org/oracledb
23 verbose request no auth needed
24 info attempt registry request try #1 at 8:15:41 PM
25 verbose request id bf5ec723db84671d
26 http request GET http://registry.npmjs.org/oracledb
27 info retry will retry, error on last attempt: Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//registry.npmjs.org/oracledb
28 info attempt registry request try #2 at 8:16:13 PM
29 http request GET http://registry.npmjs.org/oracledb
30 info retry will retry, error on last attempt: Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//registry.npmjs.org/oracledb
31 info attempt registry request try #3 at 8:17:18 PM
32 http request GET http://registry.npmjs.org/oracledb
33 verbose stack Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//registry.npmjs.org/oracledb
33 verbose stack     at Redirect.onResponse (D:\software\node\nodejs\node_modules\npm\node_modules\request\lib\redirect.js:94:27)
33 verbose stack     at Request.onRequestResponse (D:\software\node\nodejs\node_modules\npm\node_modules\request\request.js:1088:22)
33 verbose stack     at ClientRequest.emit (events.js:107:17)
33 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
33 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
33 verbose stack     at Socket.socketOnData (_http_client.js:317:20)
33 verbose stack     at Socket.emit (events.js:107:17)
33 verbose stack     at readableAddChunk (_stream_readable.js:163:16)
33 verbose stack     at Socket.Readable.push (_stream_readable.js:126:10)
33 verbose stack     at TCP.onread (net.js:538:20)
34 verbose cwd D:\software\node\nodejs
35 error Windows_NT 6.1.7601
36 error argv "D:\\software\\node\\nodejs\\\\node.exe" "D:\\software\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
37 error node v0.12.6
38 error npm  v2.11.2
39 error Exceeded maxRedirects. Probably stuck in a redirect loop http://www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//www.oracle.comhttp//registry.npmjs.org/oracledb
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by cjbj** [comment]
What what steps did you follow, starting from a clean environment, to get to this error?

**Comment by BalaRavilla** [comment]
Hi cjbj, 
I appreciate your reply.
i have first installed node and npm, then i have mounted oracle client and node-oracle-master in the same folder where node is installed. Then i installed python and VB C++ compiler.
When i worked within oracle network, the proxy didnt work untill i change registry to http instead of https.
Then i have set all the paths,
OCI_LIB_DIR=D:\software\node\nodejs\instantclient_12_1\sdk\lib\msvc\vc10
OCI_INCLUDE_DIR=D:\software\node\nodejs\instantclient_12_1\sdk\include
NODE_PATH=D:\software\node\nodejs\node_modules
ORACLE_HOME=C:\oraclexe\app\oracle\product\10.2.0\server
and all the installed locations in Path.
Before i mount oracledb and client , there were other errors but i fixed all of them with simple changes but this time, it says the mentioned max redirects error for everything, i mean for any install command i try.
One more thing i noticed is that the cache memory increases like anything when i enter install -g command like in gbs, and i manually have to abort and clean the npm cache.
I uninstalled everything and tried installing, same issue persists.
I have oracle 10 g installed in my system, i believe that does not have anything to do with this, does it?
BTW, i am new to node, this is my first install exp.
Have a look at the folder where i installed :
![image](https://cloud.githubusercontent.com/assets/13209385/8588347/adcf9e60-2626-11e5-97e1-c0e4b4d1ba47.png)

**Comment by cjbj** [comment]
You are mixing instructions.  OCI_INCLUDE_DIR is not used for this driver.  RTM and/or send me email.

**Comment by BalaRavilla** [comment]
I used that as a fix for some other issue, i tried to give you all the env variables..

**Comment by StdInOut** [comment]
Hello all

I could access my Oracle DB at AWS using node and JS but when I try to access the same database through typescript interfaces, I have exactly the same error described  by BalaRavilla.

I imported oracledb as bellow:

import * as db from '../node_modules/@types/oracledb' and got the following error:

node hello.world2.js
module.js:472
    throw err;
    ^

Error: Cannot find module '../node_modules/@types/oracledb'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/josecaodaglio/OneDrive/Dev/forum/database/connection.js:2:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)


Can you give me a direction? I am really stuck on this for some days now. 

Thanks

**Comment by StdInOut** [comment]
Hello 

I'm sorry to you with something that is surely my problem but I am couldn't solve the problem.

I am able to connect to an oracle instance using the example provided in node-oracledb, but when I try to use the typescript interfaces, I can't go forward.

I used the following code in my TS file:
import * as db from '/Users/myself/OneDrive/Dev/forum/node_modules/@types/oracledb' ;

but when I try to execute the transpiled code, I got the following error:

$ node hello.world2.js
module.js:472
    throw err;
    ^
 Error: Cannot find module '/Users/josecaodaglio/OneDrive/Dev/forum/node_modules/@types/oracledb'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/josecaodaglio/OneDrive/Dev/forum/database/connection.js:3:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Could you give me a direction?

Thanks

**Comment by dmcghan** [comment]
@StdInOut This should probably be a new/separate issue. See if this helps: https://github.com/oracle/node-oracledb/issues/501#issuecomment-267460619
