### ISSUE TITLE
Simple Web Application example using node-oracledb

### ISSUE THREAD

**Issue by amroczeK** [oracle/node-oracledb#1360]
Hey everyone I've developed a simple web application as an example of how to run SQL queries against Oracle Databases using Oracle's database driver node-oracledb for NodeJS.

The application allows you to fetch and present results, run up to 10 queries concurrently and bind up to 5 variables per query.

ReactJS with Bootstrap 5 for the frontend, NodeJS and ExpressJS for the backend.

Feel free to augment it and use it in any projects where you need to pull and present data from an Oracle database.

Github: https://github.com/amroczeK/node-oracledb-webapp

**Comment by cjbj** [comment]
Thanks for sharing.  I'll close this an issue since it's been open for some time now.
