### ISSUE TITLE
how to get notified when my pool is closed directly from oracle db and how to avoid closing of connections/sessions and  pools in oracle db

### ISSUE THREAD

**Issue by sannPropelApps** [oracle/node-oracledb#1361]
//config
Pool: {
      user: process.env.user,
      password: process.env.password,
      connectionString: process.env.connectionString ,
      threadPoolSize: 60,
      poolMin: 80,
      poolMax: 80,
      poolIncrement: 0,
      queueTimeout:240000,
      poolAlias:'PoolConn122',
      _enableStats:true
    }

**Comment by cjbj** [comment]
Please rephrase the question and put it in the content of this issue. Can you explain more about what cases you are trying to handle and why you need to handle them?

If you have questions about https://oracle.github.io/node-oracledb/doc/api.html#connectionha then also post them update
