### ISSUE TITLE
sodaDatabase.openCollection(<non-existent-object>) returns a non-null collection object

### ISSUE THREAD

**Issue by gfyoung** [oracle/node-oracledb#1364]
1. What versions are you using?

`Give your database version`: **19c**

Also run Node.js and show the output of:

`process.platform`: **darwin**

`process.version`: **v16.0.0**

`process.arch`: **x64**

`require('oracledb').versionString`: **5.1.0**

`require('oracledb').oracleClientVersionString`: `19.8.0.0.0`

2. Is it an error or a hang or a crash?

Error

3. What error(s) or behavior you are seeing?

`sodaDatabase.openCollection(<non-existent-object>)` returns a non-null collection object.

https://oracle.github.io/node-oracledb/doc/api.html#sodadbopencollection states it should be `null`.

4. Include a runnable Node.js script that shows the problem.

```javascript
const oracledb = require('oracledb');
const obj = "<non-existent-object>";

oracledb.autoCommit = true;

conn = oracledb.getConnection({...});

sodaDb = conn.getSodaDatabase();

sodaDb.openCollection(obj, (err, collection) => {
  console.log(collection);
});
```

**Comment by cjbj** [comment]
The doc doesn't mention null.  It says it will be undefined, which is what I see.  

```
$ node t.js
undefined
```

Can you show your output from the script?

**Comment by gfyoung** [comment]
> The doc doesn't mention null. It says it will be undefined

Sorry, typo there.  Weird...I tried running my script this morning, and I'm getting `undefined` as well.

It used to output something like this:

~~~
SodaCollection({ _database: SodaDatabase })
~~~

**Comment by cjbj** [comment]
@gfyoung maybe you had been testing a few combinations and had already created a collection?

**Comment by gfyoung** [comment]
It might be but not 100% sure.

That being said, it's evident that it's likely something on my end that I'll have to figure out, not with this library.

Thanks for the assistance @cjbj!
