### ISSUE TITLE
How to cancel/break an sql before the result set is returned?

### ISSUE THREAD

**Issue by niallosul** [oracle/node-oracledb#1366]
1. What versions are you using?

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

process.platform: win32
process.version: v14.15.0
process.arch: x64
oracledb version: 5.1.0
oracleClientVersionString: 19.3.0.0.0

2. Describe the problem

I'm attempting to run connection.break() on a long-running sql (in my case, an FTS that doesn't return anything for ~3 minutes). The break works as expected on a 'normal' select, when the result set is returned and processing. However, if I call connection.break() while still waiting on the initial response from the db, it seems that the sql is maybe still running on the DB, and I cannot close the connection until connection.callTimeout has completed.

Should calling .break() prior to the result set being returned work? Or is there another way to close a connection that is in that state?

I'm not sure how to set up a blocking SQL as I've described, I've just been using an FTS against a bigger table in our DB. In the code below, I switch between two sqls, one that starts processing the resultset immediately, and would take ~30 seconds to complete if not interrupted and the other that 'hangs' waiting on the FTS to complete on the DB

3. Include a runnable Node.js script that shows the problem.
```
const oracledb = require('oracledb');
const { Transform } = require('stream');
const fs = require('fs');
const path = require ('path');
const config = require('./config');

//let sqlObj = {sql:config.timeoutSQL, params:{name:'test1'}};//<-SQL that takes ~3 mins to get a response
let sqlObj = {sql:config.transSQL, params:{startDtTm:'11012019160000', endDtTm:'11012019190000'}}; //<- immediate response,  takes ~30 seconds to complete

(async()=>{
	await oracledb.createPool(config.db)

	let conn = await oracledb.getPool().getConnection()
	conn.callTimeout = 1000 * 10 //Timeout after 10 seconds
	
	let ws = fs.createWriteStream(path.join(__dirname+'/test_'+Date.now()+'.txt'))
	let jsonifier = new Transform({writableObjectMode: true,transform(row,enc,cb){cb(null, JSON.stringify(row))}});

	let stream = await conn.queryStream(sqlObj.sql,sqlObj.params)
	
	stream.on('error',err=>console.log('%s - STREAM ERROR->, %s', new Date(), err.message))
	stream.on('close',async()=>await closeConn())

	console.log('%s - STARTING PIPE', new Date())
	stream.pipe(jsonifier).pipe(ws)

        //This calls .break() after 5 seconds
	setTimeout(()=>{
		console.log('%s - CALLING BREAK', new Date())
		conn.break(async(err)=>{
			console.log('%s - IN BREAK CALLBACK, ERR-> ', new Date(), err?err.message:'')
			await closeConn()
		})
	}, 5000)

	async function closeConn(){
		try{
			console.log('%s - CLOSING CONNECTION', new Date())
			await conn.close()
			console.log('%s - CONNECTION RELEASED', new Date())
			await oracledb.getPool().close()
			console.log('%s - DISCONNECTED', new Date())
		}
		catch(err){
			console.log('%s - CLOSING ERROR: %s', new Date(), err.message)
		}
	}

})()

```

**Comment by cjbj** [comment]
Do you have `disable_oob=on` in the [sqlnet.ora](https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin) file used by node-oracledb?

**Comment by niallosul** [comment]
Hi @cjbj  - I did set that up at one point in my initial troubleshooting with our real app, and didn't see any change in behavior, but I tried it again with this stripped down test case, and it definitely does help. I'm now getting an ORA-01013, which is different from the case where the resultset has started, but that's completely fine - I'll be able to work with this. Much appreciated
