### ISSUE TITLE
Re-use / cache previously fetched db types outside a closed connection

### ISSUE THREAD

**Issue by eliellis** [oracle/node-oracledb#1367]
1. What versions are you using?

`"oracledb": "^5.1.0"`

2. Describe the problem

I have an oddly specific use-case and have scoured the documentation for an answer to this and wondering if this could be a possibility for potential improvement...

In my particular situation, I am trying to run a single procedure (the same procedure each time) over and over in parallel using a pool. The procedure itself has PL/SQL record types as both IN binds and OUT binds. Pulling connections from a pool works well, no problems getting parallel execution for trivial statements working, but I'm having an issue where after releasing the connections, I cannot re-use any DBObjectClass-es created with a released connection. One PL/SQL record used for the binds in question is a deeply nested structure / complex type and takes a while (seconds) to pull back from the database. I'd like to cache the DBObjectClass for that record and reuse it on subsequent runs of the procedure, but it looks like I must keep a single connection open and unused (cannot release it while using its DBObjectClass types). Is there any chance I am fundamentally misunderstanding how to cache and reuse a database type in `node-oracledb`? If not, would it be possible to add some additional behavior to support this use case? Ideally, I'd like to be able to cache the database type in some kind of serializable structure to keep warm-up to a once-in-a-while thing, but if there are some external factors preventing that in particular, merely being able to re-use a type from a closed connection would definitely suffice. Below I have included a repro in typescript with details redacted/changed, but from the structure of the code it should be (hopefully!) clear enough what I'm getting at...

3. Include a runnable Node.js script that shows the problem.
This is a minimal "workaround" with details changed, but should be runnable against any procedure with like-kind structure, where the changes to make it "slow" are noted in the comments.

```typescript
'use strict';

import os from 'os';
import oracledb from 'oracledb';

process.env.UV_THREADPOOL_SIZE = os.cpus().length.toString(); // 12 in my case
const myPoolSize = 10; 
const numStmts = 100;

console.log('UV_THREADPOOL_SIZE       :', process.env.UV_THREADPOOL_SIZE);
console.log('poolMin & poolMax        :', myPoolSize);
console.log('number of selects to run :', numStmts);

const config = {
  user: process.env.ORACLE_USER,
  password: process.env.ORACLE_PASSWORD,
  connectString: 'connection string',
};

async function executeQuery(query, pool: oracledb.Pool) {
  let connection: oracledb.Connection;
  try {
    connection = await pool.getConnection();
    console.log(pool.connectionsInUse);
    const result = await connection.execute(
      query.query,
      query.binds
    );
    return result;
  } catch (err) {
    console.log(err);
  } finally {
    if (connection) {
      console.log('Attempting to close connection.');
      await connection.close();
      console.log('Connection closed');
    }
  }
}

async function run() {
  const pool = await oracledb.createPool({
    user: config.user,
    password: config.password,
    connectString: config.connectString,
    poolMax: myPoolSize,
    poolMin: myPoolSize,
    poolIncrement: 0,
    poolAlias: 'default',
    sessionCallback: (c, t, cb) => {
      console.log('here');
      cb();
    },
  });

  console.log('Pool creation complete');

  const listOfNumbers = [1234, 5678];

  console.log('Getting types...'); // this takes around 30s (latter type is the larger one)
  const connection = await pool.getConnection();
  const InputTab = await connection.getDbObjectClass(
    'USER_SCHEMA.LIST_OF_NUMBERS'
  );
  const OutputTab = await connection.getDbObjectClass( // the big one (3-4 levels of RECORD types in RECORD types). can be any "big" type
    'USER_SCHEMA.VERY_LARGE_RECORD_TYPE'
  );
  console.log('Got types!');

  // from here, cannot release the above connection and continue to use the object classes
  // if we change the type: values of the binds below to their string names, we could,
  // but upon each run of executeQuery, the cached types are lost and fetched again in the next iteration
  // making running the procedure in parallel pointless without keeping a single connection open
  // to "share" the types

  await Promise.all(
    Array(numStmts)
      .fill(0)
      .map(async (v, idx) => {
        const startTime = Date.now();
        console.log(`execute #${idx}.           Started at`, startTime);
        await executeQuery(
          {
            query: `CALL user_schema.proc(:numList, :resultsTab)`,
            binds: {
              rcIdList: {
                val: listOfNumbers,
                type: Input,
              },
              resultsTab: {
                dir: oracledb.BIND_OUT,
                type: Output,
              },
            },
          },
          pool
        );
        const endTime = Date.now();
        console.log(
          `execute #${idx} took ${endTime - startTime} ms.  Ended at`,
          endTime
        );
      })
  );
  await connection.close();
}

async function closePoolAndExit() {
  console.log('\nTerminating');
  try {
    // Get the pool from the pool cache and close it
    // If this hangs, you may need DISABLE_OOB=ON in a sqlnet.ora file
    await oracledb.getPool().close(0);
    console.log('Pool closed');
    process.exit(0);
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}

process.once('SIGTERM', closePoolAndExit).once('SIGINT', closePoolAndExit);

run();

```

**Comment by anthony-tuininga** [comment]
Unfortunately,  object types are tied very closely to a particular checked out connection, and once that connection has been returned to the pool, all of the object types associated with that connection become invalid. Currently, the node-oracledb driver uses the Session Pool concept available in the Oracle Client libraries, but connections stored in that pool are C-level constructs. As such, the Node.js wrapper is recreated each time. Changing the code to use a Node.js connection pool instead would solve that problem, but would lose the benefits associated with the Session Pool in the Oracle Client libraries. Creating such a connection pool without losing the benefits associated with the Session Pool construction would be a significant enhancement, so I'll let @cjbj comment on if and when such an enhancement might be considered.

In the meantime, if you have a situation like this, your best bet is to have a connection dedicated to dealing with this (or a pool of these connections that you create and manage yourself if you need more than one). It could cache the object type and then perform any work needed to deal with that object type.

**Comment by cjbj** [comment]
Yes, it would be a significant amount of work in the client libraries.  Thanks for 'voting' for this improvement, since that helps us prioritize.

**Comment by cjbj** [comment]
Since the change is in the layer(s) beneath node-oracledb, I'm going to close this issue.  The request is noted - I logged Oracle enhancement 32937584 for it.
