### ISSUE TITLE
When will 5.2-dev have a release built off that is available in npm?

### ISSUE THREAD

**Issue by ahammonds7** [oracle/node-oracledb#1372]
Wondering when we will be able to just use the code in 5.2-dev like this:

```
  "dependencies": {
    "oracledb": "5.2.0"
  },
```

This code fixed an issue similar to #1369 for me

**Comment by cjbj** [comment]
The definitive answer is a question for the developers.  If they would only work faster, harder, smarter etc etc... :)

@ahammonds7 you can help by running your own tests on 5.2.0-dev and letting us know the good & bad.

**Comment by ahammonds7** [comment]
Haha. Yeah I get that! If we only had all the time in the world!

Yeah so far there have been no issues with it. Is has worked very well!
