### ISSUE TITLE
Daylight Savings Time zones Incorrect on INSERTS after 2040

### ISSUE THREAD

**Issue by charleaux** [oracle/node-oracledb#1374]
1. What versions are you using?

Database version: 
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

process.platform
win32

process.version
v14.16.0

process.arch
x64

require('oracledb').versionString
5.0.0

require('oracledb').oracleClientVersionString
19.6.0.0.0
   

2. Is it an error or a hang or a crash?
error

3. What error(s) or behavior you are seeing?

When inserting dates after 2040 the date is being inserted with the wrong timezone offset. It does not take into account daylight savings.

If we insert a date 2040-04-01 it is inserted correctly
```
Date / DUMP(DATE)
4/1/2040	/ Typ=12 Len=7: 120,140,4,1,1,1,1
```

If we insert a date 2041-04-01 it is inserted incorrectly
```
Date / DUMP(DATE)
3/31/2041 11:00:00 PM / Typ=12 Len=7: 120,141,3,31,24,1,1
```

4. Include a runnable Node.js script that shows the problem.
SQL TO CREATE TABLE
```
CREATE TABLE date_issue_replicate
(
    id            NUMBER
                     GENERATED BY DEFAULT ON NULL AS IDENTITY    START WITH 1
                     NOT NULL,
    start_date    DATE
);
```

Javascript Code to do the Insert
```
await connection.execute(
  'truncate table date_issue_replicate',
  {},
  {
	autoCommit: true,
  }
);

let startDate = new Date('2040-04-01T04:00:00.000Z');

await connection.execute(
  `INSERT INTO date_issue_replicate (start_date) VALUES (:startDate)`,
  {
	startDate,
  },
  { autoCommit: true }
);

startDate = new Date('2041-04-01T04:00:00.000Z');

await connection.execute(
  `INSERT INTO date_issue_replicate (start_date) VALUES (:startDate)`,
  {
	startDate,
  },
  { autoCommit: true }
);
```

**Comment by charleaux** [comment]
I forgot to mention my timezone settings:
```
  "DBTIMEZONE": "+00:00",
  "SESSIONTIMEZONE": "America/New_York"
```

**Comment by anthony-tuininga** [comment]
I just tried with this script -- which is very similar to yours but is complete and performs the fetch as well:
```
const oracledb = require('oracledb');

const config = {
  user: "user",
  password: "password",
  connectString: "host/service_name"
};

async function run() {
  const conn = await oracledb.getConnection(config);
  await conn.execute("truncate table date_issue_replicate");
  const date1 = new Date('2040-04-01T04:00:00.000Z');
  const date2 = new Date('2041-04-01T04:00:00.000Z');
  let sql = "insert into date_issue_replicate (start_date) values (:1)";
  await conn.execute(sql, [date1]);
  await conn.execute(sql, [date2]);
  await conn.commit();
  sql = "select start_date from date_issue_replicate";
  console.log("Date 1 inserted:", date1);
  console.log("Date 2 inserted:", date2);
  const results = await conn.execute(sql);
  console.dir(results.rows, {depth: null});
  await conn.close();
}

run();
```

Running it I get this output:
```
Date 1 inserted: 2040-04-01T04:00:00.000Z
Date 2 inserted: 2041-04-01T04:00:00.000Z
[ [ 2040-04-01T04:00:00.000Z ], [ 2041-04-01T04:00:00.000Z ] ]
```

I don't see anything strange going on there. The values in the database look reasonable, too. Can you run my script and see if you get the same output as I do?

**Comment by charleaux** [comment]
I see the same issue happening however the snip above shows the data incorrectly on the select so its hard to see that there was an issue with the insert.

If you try modify your sql here it'll be easier to see.
```
    sql =
      'select start_date, dump(start_date) as dump_start_date from date_issue_replicate';
```

dump lets you see what the database is actually storing and it's very helpful when debugging date issues.

This is what I got with the DUMP turned on:

```
Date 1 inserted: 2040-04-01T04:00:00.000Z
Date 2 inserted: 2041-04-01T04:00:00.000Z
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,4,1,1,1,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,3,31,24,1,1' ]
]
```

**Comment by anthony-tuininga** [comment]
I still don't see an issue. I checked the values in the database earlier and didn't see anything wrong with the inserted values. Adding the dump to the query shows the following output:
```
Date 1 inserted: 2040-04-01T04:00:00.000Z
Date 2 inserted: 2041-04-01T04:00:00.000Z
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,3,31,23,1,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,3,31,23,1,1' ]
]
```

**Comment by charleaux** [comment]
Interesting, I've tested on a few database servers in my environment but I never tried different time zones.

Can I get the values you have so I can attempt to set my session to the same as yours?
```
    sql = 'select dbtimezone, sessiontimezone from dual';
    results = await connection.execute(sql);
    console.dir(results.rows, { depth: null });
```
results this is what i'm using now:
```
[ [ '+00:00', 'America/New_York' ] ]
```


Should I use America/Denver for Mountain time?
 https://docs.oracle.com/cd/B13866_04/webconf.904/b10877/timezone.htm

**Comment by anthony-tuininga** [comment]
These are the values I have:
```
[ [ '+00:00', '-06:00' ] ]
```

You should be able to use `America/Denver` or just `-06:00`.

**Comment by charleaux** [comment]
No issues with -6

```
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,3,31,23,1,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,3,31,23,1,1' ]
]
[ [ '+00:00', '-06:00' ] ]
```

But America/Denver gives me a different outcome

```
Date 1 inserted: 2040-04-01T04:00:00.000Z
Date 2 inserted: 2041-04-01T04:00:00.000Z
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,3,31,23,1,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,3,31,22,1,1' ]
]
[ [ '+00:00', 'America/Denver' ] ]
```

This is interesting all my servers are currently setup using America/New_York

**Comment by anthony-tuininga** [comment]
That *is* interesting! I tried simply setting the `TZ` environment variable before running. I tried `America/New_York` and `America/Denver` and didn't notice any problems. I am using Linux, though, so perhaps that is relevant?

**Comment by charleaux** [comment]
Perhaps it is, I'll see if I can get a Linux VM up and test it out.

All the systems I've been working on are Windows Server 2019 or Windows 10

**Comment by charleaux** [comment]
I just confirmed that on OEL8 this does not happen.

Only happens on Windows. Not sure what to do to move forward on this one.

**Comment by anthony-tuininga** [comment]
Not sure, either. @cjbj may have some ideas. If you have Oracle Support you can log a support ticket with them.

**Comment by charleaux** [comment]
I have support, just wasn't sure if that was the correct venue for dealing with issues in node-oracledb.

I'll open a ticket there.

**Comment by anthony-tuininga** [comment]
They can't deal with issues with node-oracledb, but this appears to be an issue with a particular configuration and not specifically with node-oracledb. They can at least help you figure out if this is a problem with *your* configuration or if this is a known issue with Windows. You can also try with 19.11 client to see if that makes a difference.

**Comment by charleaux** [comment]
I've tried this on my home pc with the oracle vagrant image and windows 10 with the issue, and I've tested it out at work on the servers there (Windows 2012 & 2019) with the same issue.

I feel this is probably a bug with the instant client for Windows x64 but it's probably one of those things that is outside my ability to prove beyond a doubt.

My issue is that I can't replicate in sqlplus or toad so I anticipate a little finger pointing.

**Comment by cjbj** [comment]
Let's ask @pvenkatraman to try it on Windows first.

**Comment by pvenkatraman** [comment]
I tried with same samples and on my laptop (so Indian Standard time IST) - did not set any TZ, ORA_SDTZ environment variables.

node examples\issue1374.js
insert date value : Sun Apr 01 2040 09:30:00 GMT+0530 (India Standard Time)
insert date value 2: Mon Apr 01 2041 09:30:00 GMT+0530 (India Standard Time)
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,4,1,10,31,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,4,1,10,31,1' ]
]

My environment is:
node examples\version.js
Run at: Wed May 26 2021 12:04:22 GMT+0530 (India Standard Time)
Node.js version: v15.8.0 (win32 x64)
Node-oracledb version: 5.2.0-dev
Oracle Client library version: 19.9.0.0.0
Oracle Database version: 23.1.0.0.0

My observations are consistent with Anthony's.
Thanks,

**Comment by charleaux** [comment]
Can you attempt to set the ORA_SDTZ environment variable to America/New_York? 
```
ORA_SDTZ=America/New_York
```
I don't have the issue if I set it to a specific timezone like -6:00 but then I miss out on the DST changes

**Comment by pvenkatraman** [comment]
Tried few ORA_SDTZ values:


set ORA_SDTZ="America/New_York"
node examples\issue1374.js
insert date value : Sun Apr 01 2040 09:30:00 GMT+0530 (India Standard Time)
insert date value 2: Mon Apr 01 2041 09:30:00 GMT+0530 (India Standard Time)
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,4,1,10,31,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,4,1,10,31,1' ]
]

set ORA_SDTZ="America/San_Francisco"
node examples\issue1374.js
insert date value : Sun Apr 01 2040 09:30:00 GMT+0530 (India Standard Time)
insert date value 2: Mon Apr 01 2041 09:30:00 GMT+0530 (India Standard Time)
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,4,1,10,31,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,4,1,10,31,1' ]
]


set ORA_SDTZ="America/Denver"
node examples\issue1374.js
insert date value : Sun Apr 01 2040 09:30:00 GMT+0530 (India Standard Time)
insert date value 2: Mon Apr 01 2041 09:30:00 GMT+0530 (India Standard Time)
[
  [ 2040-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,140,4,1,10,31,1' ],
  [ 2041-04-01T04:00:00.000Z, 'Typ=12 Len=7: 120,141,4,1,10,31,1' ]
]

**Comment by charleaux** [comment]
I just noticed that the DUMP of the dates didn't change with the different timezones. Is something wrong?

**Comment by pvenkatraman** [comment]
node examples\version.js
Run at: Wed May 26 2021 20:47:20 GMT+0530 (India Standard Time)
Node.js version: v15.8.0 (win32 x64)
Node-oracledb version: 5.2.0-dev
Oracle Client library version: 19.9.0.0.0
Oracle Database version: 23.1.0.0.0

on Windows 10

**Comment by charleaux** [comment]
I think we can close this BUG out. I was unable to get windows to work as you have but I still have two solid ideas of how to move forward.

1) Switch over to Linux which will work or
2) Set SessionTIMEZONE and DBTIMEZONE to +00:00 and do date.toUTCString() from my frontend to make sure all dates are transmitted in UTC.

Both are solid options. I appreciate all the help.
