### ISSUE TITLE
How to Solve error- "Error: NJS-012: encountered invalid bind data type in parameter 2"? What is wrong in my code?

### ISSUE THREAD

**Issue by ritikasingh333** [oracle/node-oracledb#1375]
Hi,

I am executing Oracle stored procedure in my NodeJs application and facing issue with  bind data type. Here is the details:
(Here is the stackoverflow question link for the same:  https://stackoverflow.com/questions/67515013/how-to-bind-object-to-oracle-procedure-call-in-node-js)

1. Version:
    Database Version: **Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0**
    process.platform: **win32**
    process.version: **v10.16.2**
    process.arch: **x64**
    require('oracledb').versionString: **5.1.0**
    require('oracledb').oracleClientVersionString: **18.4.0.0.0**

2. problem:
    I am getting error: "**Error: NJS-012: encountered invalid bind data type in parameter 2**" while executing the procedure.

3. runnable Node.js script
   ```
   const result = await conn.execute("BEGIN calculate_allhealthoutcomes.HealthOutcomeCalculator(:input, :output); END;",
        {
            input: { dir: oracledb.BIND_IN,
                    val: {
                            PatientAge:35,
                            PatientGender:"M",
                            Height: 155,
                            Weight: 60,
                            WristCircumference:10,
                            ForearmCircumference:7,
                            WaistSize:33,
                            HipSize:38,
                            ActivityLevel:"HIGH"
                        },
                    type: oracledb.OBJECT
            },
            output: { dir: oracledb.BIND_OUT, type: oracledb.OBJECT }
        }, {});  

4. Here is the calculate_AllHealthOutcomes Package code:
```
create or replace PACKAGE calculate_AllHealthOutcomes AS
PROCEDURE HealthOutcomeCalculator (i_InputParameterTable IN allVariables.InputParameterTable,
o_OutputParameterTable OUT allVariables.OutputParameterTable);
END calculate_AllHealthOutcomes;
```


5. Here is the allVariables Package code:**
```
create or replace PACKAGE allVariables AS
TYPE GeneralHealthInputPrmtrsRcrd IS RECORD (PatientAge NUMBER,
PatientGender VARCHAR2(1),
Height NUMBER,
Weight NUMBER,
WristCircumference NUMBER,
ForearmCircumference NUMBER,
WaistSize NUMBER,
HipSize NUMBER,
ActivityLevel VARCHAR2 (20));
TYPE GeneralHealthInputPrmtrsTable IS TABLE OF GeneralHealthInputPrmtrsRcrd;
TYPE OutputParameterRecord IS RECORD ( Serial_Id NUMBER,
Analysis_Name VARCHAR2(20),
Analyzed_Value NUMBER,
Analyzed_Outcome VARCHAR2(20),
Alert_Severity VARCHAR2(10),
Alert_Message VARCHAR2(250));
TYPE OutputParameterTable IS TABLE OF OutputParameterRecord INDEX BY BINARY_INTEGER;
TYPE InputParameterRecord IS RECORD (InputParameter_Name VARCHAR2 (100),
InputParameter_Value VARCHAR2 (2000));
TYPE InputParameterTable IS TABLE OF InputParameterRecord INDEX BY BINARY_INTEGER;
END allVariables; 
```

6. PROCEDURE calculate_AllHealthOutcomes Package Body Code
``` 
create or replace PACKAGE BODY calculate_AllHealthOutcomes AS

PROCEDURE HealthOutcomeCalculator   (i_InputParameterTable              IN                   allVariables.InputParameterTable,
                                     o_OutputParameterTable                 OUT              allVariables.OutputParameterTable) IS
                                                
v_Rowcount                                 BINARY_INTEGER:=0;
v_ErrorRowCount                        BINARY_INTEGER:=0;
v_InputParamaterTable             allVariables.InputParameterTable;
v_OutputParameterTable          allVariables.OutputParameterTable;
v_ErrorMessageTable                  manage_ErrorMessages.TableType;

BEGIN
calculate_GeneralHealthOutcome.GeneralHealthRiskCalculator (i_InputParameterTable,v_OutputParameterTable,v_ErrorMessageTable);
IF v_OutputParameterTable.COUNT = 0  THEN
   IF v_ErrorMessageTable.COUNT >0 THEN
      IF manage_ErrorMessages.isFailure(v_ErrorMessageTable) THEN
         v_ErrorRowCount := 1;
         v_OutputParameterTable(v_Rowcount).Serial_Id := v_ErrorRowcount;
         v_OutputParameterTable(v_Rowcount).Analysis_Name :=NULL;
         v_OutputParameterTable(v_Rowcount).Analyzed_Value :=   NULL;
         v_OutputParameterTable(v_Rowcount).Analyzed_Outcome := NULL;
         v_OutputParameterTable(v_Rowcount).Alert_Severity := v_ErrorMessageTable( v_ErrorRowCount). Error_Message_Severity ;
         v_OutputParameterTable(v_Rowcount).Alert_Message := v_ErrorMessageTable( v_ErrorRowCount).Error_Message ;
     ELSE
          o_OutputParameterTable := v_OutputParameterTable;
      END IF;
   ELSE
         o_OutputParameterTable := v_OutputParameterTable;
   END IF;
ELSIF v_OutputParameterTable.COUNT > 0  THEN
  o_OutputParameterTable := v_OutputParameterTable;
END IF;

EXCEPTION

WHEN OTHERS THEN

NULL;
END HealthOutcomeCalculator;                                                
END calculate_AllHealthOutcomes;
```
Please Help, TIA

**Comment by cjbj** [comment]
Can you answer the issue template questions?  The versions might matter: https://raw.githubusercontent.com/oracle/node-oracledb/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md

You can also see there how to edit your post to use markdown for formatting

You'll also need to reduce the test case size by removing unnecessary columns, parameters, types etc,

Most importantly we need something runnable, so give us some kind of `HealthOutcomeCalculator()` implementation.

Thank you.

**Comment by ritikasingh333** [comment]
@cjbj I have updated my question which includes answer to the issue template questions. Also I have included HealthOutcomeCalculator() procedure definition.

Thank You

**Comment by cjbj** [comment]
@ritikasingh333 is your problem with the IN or the OUT bind?  Try simplifying your code and removing whichever works.  Try removing some attributes of the type to simplify and show you where the problem might be.

**Comment by ritikasingh333** [comment]
@cjbj I removed attribute type from both BIND_IN and BIND_OUT, it is throwing same error

**Comment by anthony-tuininga** [comment]
The problem is that you are stating the type as `oracledb.OBJECT`. That is insuffiicent. You need to specify the type name as shown in the following code, which works as expected:

```
const oracledb  = require('oracledb');

const config = {
  user: "nodejs",
  password: "password",
  connectString: "host/service_name"
};

async function run() {
  const conn = await oracledb.getConnection(config);
  const sql = `
    BEGIN
      calculate_allhealthoutcomes.HealthOutcomeCalculator(:input, :output);
    END;`;
  const binds = {
    input: {
      dir: oracledb.BIND_IN,
      val: {
        PatientAge:35,
        PatientGender:"M",
        Height: 155,
        Weight: 60,
        WristCircumference:10,
        ForearmCircumference:7,
        WaistSize:33,
        HipSize:38,
        ActivityLevel:"HIGH"
      },
      type: "ALLVARIABLES.INPUTPARAMETERTABLE"
    },
    output: {
      dir: oracledb.BIND_OUT,
      type: "ALLVARIABLES.OUTPUTPARAMETERTABLE"
    }
  };
  const result = await conn.execute(sql, binds);
  console.log("Result:", result);
  await conn.close();
}

run();
```

**Comment by ritikasingh333** [comment]
@anthony-tuininga Thank You! It is working, No error is there but Output is empty array. Am I doing any thing wrong?
```
Result: { outBinds: { output: [ADMIN.OUTPUTPARAMETERTABLE] [] } }
```

**Comment by anthony-tuininga** [comment]
That's something only you can answer! If your PL/SQL code is populating this object, it will show up in the output. The code I saw didn't populate the object so it is empty. You can hack your PL/SQL to force a value in the object just to convince yourself of that fact. :-)

**Comment by ritikasingh333** [comment]
@anthony-tuininga Thank You for the help! PL/SQL code is coded by my team member, I have discussed with him.
