### ISSUE TITLE
executeMany() is slow when using PL/SQL OUT binds

### ISSUE THREAD

**Issue by frg-tarasov** [oracle/node-oracledb#1376]
1. What versions are you using?
Database version: Oracle Database 11g Release 11.2.0.3.0 - 64bit Production

Node.js output:

```
process.platform: linux
process.version: v14.16.1
process.arch: x64
require('oracledb').versionString: 5.1.0
require('oracledb').oracleClientVersionString: 12.1.0.1.0
```

2. Is it an error or a hang or a crash?
It's performance problem.

3. What error(s) or behavior you are seeing?

I have faced with interesting problem about `executeMany`. I don't know it's ok or not but `executeMany` really slow with procedures when a procedure has out parameters.

I have created [demo repository](https://github.com/frg-tarasov/node-oracledb-bulk-insert) which shows this. I wrapped output parameters with begin-end variables and it has began work very quickly.

Measures:

```bash
'time 1: 14.962s' # with out parameters
'time 2: 223.178ms' # without
```

**Comment by cjbj** [comment]
@frg-tarasov that's a nice little teaser: returning more data to node-oracledb is faster.
Someone will need to sit down and debug through the stack.
You could try DPI_DEBUG_LEVEL=12 and see where the time is being spent.

**Comment by frg-tarasov** [comment]
I haven't understood what are you mean in this phrase "returning more data to node-oracledb is faster".
Can you explain? Because it's faster when I'm not returning anything.

**Comment by cjbj** [comment]
Test 1 returns OUT bind data through to node-oracledb, but is faster than test 2 which doesn't have OUT binds.

**Comment by frg-tarasov** [comment]
No, it doesn't.
The second case shows time in ms. It is faster a lot.

**Comment by cjbj** [comment]
LOL!

**Comment by anthony-tuininga** [comment]
This is expected behavior due to a "feature" of PL/SQL. When only input variables are found, the `executeMany()` call only requires a single round trip. When output variables are found, however, the `executeMany()` call effectively turns into a series of `execute()` calls -- so in your case 1000 round-trips. As noted, that makes a significant difference in performance!

**Comment by cjbj** [comment]
I re-labeled this as a question, since the "feature" is not in node-oracledb's control.  However I will note it in the documentation.  And I will log an enhancement request in Oracle tracking system.

**Comment by frg-tarasov** [comment]
Thanks for explanations!
