### ISSUE TITLE
Returning gives "Buffer too small" error

### ISSUE THREAD

**Issue by lbaldini** [oracle/node-oracledb#138]
I'm trying to insert a record and read, as a result, the last value of the sequence. In other words I'm trying to execute this query:

`
insert into Data (
  ID,
  FirstName,
  LastName
) values (
  Data_ID.nextval,
  'Luca',
  'Baldini'
) 
returning ID into :counter
`

where *Data_ID* is a valid sequence.

I've used the following JS code:

```javascript
var params = {outFormat: App.oracledb.OBJECT, autoCommit: !pthis.transaction};
params.counter = {type: App.oracledb.NUMBER, dir: App.oracledb.BIND_OUT};
//
this.connection.execute(sql, [], params, function (error, result) {
...
```

But I keep getting the error * Error: NJS-016: Buffer is too small for OUT binds*

I've tryied looking at oracledb source code and I've found that in file njsConnection.cpp (lines 744-812) that error is generated if the maxLen of a string param is too smal OR if there is any exception with error code different from 24343... 

Is there something wrong with my code? Or do I need to change something? I've tryied declaring the out parameter as STRING... I've also tryied returning a STRING, i.e.:

` returning 'done' into :counter`

but nothing changes...

**Comment by dmcghan** [comment]
@lbaldini It appears that you are putting your binds on your options object. These are two separate parameters when calling execute. Use the second parameter for your binds, the one you're currently passing an empty array ([]). See the example here: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#dmlreturn

**Comment by lbaldini** [comment]
You are right! That was the problem! Thanks!!!
For anyone experiencing the problem, that's my code:

```javascript
var params = {outFormat: App.oracledb.OBJECT, autoCommit: !pthis.transaction};
var bind = {counter: {type: App.oracledb.NUMBER, dir: App.oracledb.BIND_OUT}};
//
this.connection.execute(sql, bind, params, function (error, result) {
...
```

The Issue can be closed.
