### ISSUE TITLE
How can i Insert some fields in table, but not all of them?

### ISSUE THREAD

**Issue by hey-jackLon** [oracle/node-oracledb#1380]
I wan to insert some fields ,but I can not do it.
like INSERT INTO E_LINE_JQ_RELATE (ID,SPOT_ID,LINE_NO,ROAD_NO) VALUES (22,'696','gb123456','gb123456_001');

**Comment by cjbj** [comment]
Is this a question about node-oracledb or is it a SQL question for https://asktom.oracle.com/?  What have you tried and what results or errors did you get?

It would help us if you updated your post with the answers to the [issue template](https://raw.githubusercontent.com/oracle/node-oracledb/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md) questions.

Also see http://tinyurl.com/stack-checklist

Thank you.
