### ISSUE TITLE
How can i Insert some fields in table, but not all of them?

### ISSUE THREAD

**Issue by hey-jackLon** [oracle/node-oracledb#1381]
1. What versions are you using?
 "oracledb": "^5.1.0"

2. Describe the problem
I want to use `INSERT INTO E_LINE_JQ_RELATE (id,spot_id,line_no,road_no) VALUES (22,'696','gb123456','gb123456_001');` this sql to insert some data.
but console
ORA-01036: illegal variable name/number
{
  status: -1,
  detail: 'ORA-01036: illegal variable name/number'
}

3. Include a runnable Node.js script that shows the problem.

**Comment by hey-jackLon** [comment]
Oracle version is 'Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production'

**Comment by cjbj** [comment]
Please show us the CREATE TABLE clause so we know the column names.

And show a runnable JavaScript file that gives the error.

If it helps, you can use https://github.com/oracle/node-oracledb/blob/master/examples/example.js. Change the CREATE statement, and modify the executeMany() to be an execute().
