### ISSUE TITLE
Running in Dockerfile unable to install oracle db

### ISSUE THREAD

**Issue by gregz07** [oracle/node-oracledb#1382]
Just running this Dockerfile, it gives npm ERR! oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for linux arm64.. 

Can I get some help selecting the image versions that will allow me to install node-oracledb ? This is my Dockerfile as of now

Apologies if I labeled the issue poorly
```
FROM oraclelinux:8 as builder
 
RUN dnf -y install oracle-release-el8
RUN dnf -y install oracle-instantclient19.10-basic
 
RUN rm -rf /usr/lib/oracle/client64/bin
WORKDIR /usr/lib/oracle/client64/lib/
RUN rm -rf *jdbc* *occi* *mysql* *jar
 
FROM node as apiproxy
 
COPY --from=builder /usr/lib/oracle /usr/lib/oracle
COPY --from=builder /usr/share/oracle /usr/share/oracle
COPY --from=builder /etc/ld.so.conf.d/oracle-instantclient.conf /etc/ld.so.conf.d/oracle-instantclient.conf
 
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade && apt-get install -y libaio1 && \
    apt-get -y autoremove && apt-get -y clean && \
    ldconfig
 
FROM apiproxy
 
WORKDIR /usr/src/app

ADD *.js ./
 
RUN npm install oracledb && echo 'Oracle db installed'

CMD /bin/bash
```

**Comment by cjbj** [comment]
There isn't a pre-built node-oracledb binary for ARM.  You need to install from source code.  Instructions are [here](https://oracle.github.io/node-oracledb/INSTALL.html#github).  Arguably this is simplest:

```
npm install https://github.com/oracle/node-oracledb/releases/download/v5.1.0/oracledb-src-5.1.0.tgz
```

You might want to do this in the builder, so you can install any necessary compiler etc without having it in the final image.

Or you can [build your own package](https://oracle.github.io/node-oracledb/INSTALL.html#compilepackage) once, and use that for future container builds.

**Comment by gregz07** [comment]
Hey thanks so much for taking your time for answering me. Yeah it worked, thanks! 

But just for my own edification and for understanding this problem in the future:
 - In Windows a similar Dockerfile ran without a problem:

` 
     
     FROM oraclelinux:7-slim as builder
 
     ARG release=19
     ARG update=5
 
     RUN yum -y install oracle-release-el7
     RUN yum -y install oracle-instantclient${release}.${update}-basiclite
 
     RUN rm -rf /usr/lib/oracle/${release}.${update}/client64/bin
     WORKDIR /usr/lib/oracle/${release}.${update}/client64/lib/
     RUN rm -rf *jdbc* *occi* *mysql* *jar
 
     FROM node:16-buster-slim as apiproxy
 
     COPY --from=builder /usr/lib/oracle /usr/lib/oracle
     COPY --from=builder /usr/share/oracle /usr/share/oracle
     COPY --from=builder /etc/ld.so.conf.d/oracle-instantclient.conf /etc/ld.so.conf.d/oracle-instantclient.conf
 
     RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade && apt-get install -y libaio1 && \
              apt-get -y autoremove && apt-get -y clean && \
              ldconfig
 
     FROM apiproxy
 
     WORKDIR /usr/src/app
 
     ADD *.js ./
 
     RUN npm install oracledb && echo 'Installed'
 
     CMD /bin/bash`

So oraclelinux:7-slim does have the binary for node-oracledb, but the oraclelinux:8 doesn't have ? Is that it ? 

Thanks a lot man, cheers!

**Comment by cjbj** [comment]
The prebuilt node-oracledb binaries are for x86_64.  They will work with Oracle Linux 7 and Oracle Linux 8 (and others).

I tried your original Dockerfile.  It worked fine for me.   Note you are running the node-oracledb install on a Node.js image (e.g. node:16-buster-slim), not an Oracle Linux image, so you need to make sure this is x86_64.

**Comment by cjbj** [comment]
For all I know, JDBC-thin might be better than JDBC-thick, but comparing between languages is something you need to judge for yourself by benchmarking and factoring in development costs.  If you wanted raw speed you would use C via OCI directly.

Use wise architectural and design choices - use session pools, avoid round-trips, tune the app etc etc.  If services are stopping and starting frequently (like a functionless server model could do) you might want to look at using DRCP to avoid the cost of DB server process creation. This last tip would be true for JDBC too.
