### ISSUE TITLE
Follow-up question to "Client Result Cache #1368"

### ISSUE THREAD

**Issue by EmmEsch** [oracle/node-oracledb#1385]
Hi there,

We got a very helpful description on how to make the oracle client result cache work in https://github.com/oracle/node-oracledb/issues/1368 [see details of database version, node version, problem and script in that issue].

We have enabled CRC on the DB server side as you’ve explained it the response of the above-named issue.

Looking at the explain plan of our queries now using the hint /*+ result_cache */, the result cache has been used:
```
------------------------------------------------------------
| Id  | Operation             | Name                       |
------------------------------------------------------------
|   0 | SELECT STATEMENT      |                            |
|   1 |  RESULT CACHE         | fr1xjyzf0bnfq6frnvu113nht9 |
|   2 |   SORT GROUP BY NOSORT|                            |
|   3 |    TABLE ACCESS FULL  | TABLE_ABC123              |
------------------------------------------------------------
	
Result Cache Information (identified by operation id):
------------------------------------------------------
    1 -
```
However, when we have a look at the executions-attribute of table v$sqlarea (According to your example at the URL https://gist.github.com/cjbj/b147c04cf9b85a2384e5a1a17ba00064: “select executions from v$sqlarea where sql_text = :q1”), the number of executions increases with each new execution of queries tagged with “/*+ result_cache */” activated despite the explain plan showing the use of the result cache.

I therefore have the following two questions for you:

1.: Why does the query plan show us the use of the result cache for queries using the hint “/*+ result_cache */”, but v$sqlarea.executions still increases with each execution of the query? Has the Client Result Cache been used (as the query plan suggests) or not (as v$sqlarea.executions suggests)?

2.: Are there other possibilities to check whether a query has used the client result cache?

Thank you very much for your help,

Emmanuel

**Comment by cjbj** [comment]
I did a quick test to a DB which did not have CRC enabled.  My EXPLAIN PLAN output was similar to yours so I assume it reflects that the query had the hint, but doesn't say anything more about whether the client cache was actually enabled or used.

We don't have stats in the Oracle Client library to show what requests _didn't_ get sent to the DB - and I don't believe the DB has post hoc recording about what it hadn't seen.  You could enable SQL*Net or network tracing and compare what is being sent across the network.  Or you could compare raw app performance.   Overall, if you are not seeing the execution count difference in `v$sqlarea` then you won't be using the cache.

Check that my app shows the execution count difference in your environment. Triple check you are connecting to the right services.  Check that you are not opening new standalone connections for each `execute()` call  - either keep the connection open or use a connection pool.

**Comment by EmmEsch** [comment]
Hi Christopher. Thank you very much for your test and explanation. We'll try it again in our environment.
