### ISSUE TITLE
Error: ORA-03106: fatal two-task communication protocol error

### ISSUE THREAD

**Issue by sannPropelApps** [oracle/node-oracledb#1388]
After getting a connection from pool,it is throwing Error: ORA-03106: fatal two-task communication protocol error,what may be  the cause,though pool was created successfully and connection from that pool successfully.

**Comment by cjbj** [comment]
Check for trace files.  Google shows various causes.  Last time I saw this was when I was executing the exact same query text in the same connection with a LOB, the first time with fetchAsString, and the second time getting a Lob.
