### ISSUE TITLE
Trying to manually close the connection if it exceeds certain time,but it is erroring out with 'DPI-1010:not connected'

### ISSUE THREAD

**Issue by sannPropelApps** [oracle/node-oracledb#1389]
```
const executeSQLQuery = (query, params, options = {}) => {
  return new Promise(async (resolve, reject) => {
      let conn;
      let throwTimeOutError = true;
let conn;
      console.log('@@@@@  QUERY EXECUTING @@@@: ', query, params);
      try {
        console.log('connecting to pool...',oracledb.poolAlias);
        //process.env['poolAliasName']
        
             pool = oracledb.getPool(process.env['poolAliasName']);
          conn = await pool.getConnection();
        console.log('connection details:',conn);  
        let result;
        setTimeout(()=>{
          if(throwTimeOutError){
            if (conn) { // conn assignment worked, need to close
              try {
              
                           await conn.close();
                
                console.log('closing connection new SQL');
              } catch (err) {
                console.log(err);
              }
            }
            reject({message:'Query did not responsed in time.'});
          }
        },300000);
        result = await conn.execute(query, params);
        //console.log('executed');
        throwTimeOutError = false;
        resolve(result);
      } catch (err) {
        reject(err);
        throwTimeOutError = false;
        console.log(err,'coming');
      } finally {
        if (conn) { // conn assignment worked, need to close
          try {
                       await conn.close();
            
            console.log('closing connection new SQL');
          } catch (err) {
            console.log(err);
          }
        }
      }    
     
  });
}
```

**Comment by cjbj** [comment]
What's the question?! If you are trying to close it, and it is already closed, is there an issue?

**Comment by cjbj** [comment]
- Reviewing this issue now it's morning, I can see you have two connection `close()` calls.  Are you sure you're not calling both?  If you had supplied a _runnable script_ I would have run it and done some debugging..... :)
- Are you sure your first connection `close()` shouldn't be a [`break()`](https://oracle.github.io/node-oracledb/doc/api.html#break)?
- Have you looked at using [`callTimeout`](https://oracle.github.io/node-oracledb/doc/api.html#propconncalltimeout)?
- Do you really need to use resolve/reject when you're already using async/await style programming?  Someone in one of the issues in this repo, Dan succinctly pointed out 
   > "AsyncFunctions (async/await) automatically return promises. Values returned from the function resolve the promise. Errors thrown reject the promise."
- Please answer the issue template when logging issues!
- It helps if you can use markdown formatting https://help.github.com/github/writing-on-github/basic-writing-and-formatting-syntax. I edited your post to add formatting.
