### ISSUE TITLE
got concurrency issue with ATP(free 20G oracle cloud database)

### ISSUE THREAD

**Issue by x0us** [oracle/node-oracledb#1392]
I'm use "oracledb": "5.2.0" and my config setting is default:
```
        this.connectionParams = {
            connectString:  process.env.DB_CONNECTION_STRING,
            user:           process.env.DB_USER,
            password:       process.env.DB_PASSWORD
        };
```
I got a big problems (exceed sessions limatation or oracle admin net issue) when i do query data in a loop, i enclosed the code below, I have to query the old and compare the difference, if i sleep 5s in the loop, it works as well, but i'm trying to find a more elegance way for this, please any suggestions, thank you.

ps: I dont have issue for bulk insert due to use executeMany.

```
// my query code
for(const product of products) {
      const sql = `SELECT * FROM CTP_CD WHERE CATEGORY=${product .category} AND PRODUCT=${product.spuId}`
     await OracleDB.execute(sql)
}
```
below is my OracleDB function, you see, JUST BASIC QUERY
```
    static async execute(sql: string, binds?: oracledb.BindParameters[] | undefined, options?:oracledb.ExecuteManyOptions | oracledb.ExecuteOptions | undefined) {
        let connection: oracledb.Connection | undefined;
        let result: any

        try {
            connection = await this._instance.pool.getConnection();

            if(binds && options){
                result = await connection.executeMany(sql, binds, options);
            }else{
                result = await connection.execute(sql);
                console.log(result)
            }

        } catch (err) {
            console.error(err);

        } finally {
            if (connection) {
                try {
                    connection.close();
                    return result
                } catch (err) {
                  console.error(err);
                }
            }
        }
    }
```

**Comment by cjbj** [comment]
Try `await connection.close()`

**Comment by cjbj** [comment]
You **must** use bind variables instead of string interpolation in this:
```
const sql = `SELECT * FROM CTP_CD WHERE CATEGORY=${product .category} AND PRODUCT=${product.spuId}`
```

Bind variables will help protect against SQL injection issues, and will give you performance and scalability benefits.

There are probably even more efficient ways to architect your code, doing just one `execute()` and getting the results of multiple SELECT calls in the single return output.  Perhaps via PL/SQL.  Whether this makes sense will depend on how you want to consume the data in the app.

**Comment by x0us** [comment]
@cjbj thank you so much!!!!!i didn't notice a mistake there....yeah...its solved. I'm so sorry for the silly mistake.
And also thank you for the security tips, I do changed it...
Have a nice day...
