### ISSUE TITLE
Is it possible to deploy on IBM Cloud Foundry?

### ISSUE THREAD

**Issue by x0us** [oracle/node-oracledb#1393]
Hi oracle 
I'm trying to deploy to IBM cloud foundry but failed, the main problem is: oracledb.initOracleClient(). I also upload the the instantclient-basic-linuxx64.zip and my wallet.zip(oracle cloud atp connect files) and unzip all of them in the right place and no chance..

first of all, in windows PC(due to i install that kind of oracle client) program works fine, second, it really drives me crazy on deloyment now :)   

I feel quite confusing that must use “key” files to connect database, as you know some cloud platform like the cloud foundry, you don‘t have too much controls on it, it's impossible to install some libs.

So just want to know is it possible to run on cloud foundry? if answer is yes, and HOW?

thank you so much for your times, i trap in this for couples of day, please help.

**Comment by cjbj** [comment]
Make sure you read the doc about the limitations of using `initOracleClient()` on Linux and understand that you _must_ set the library search path before Node.js starts. Just calling `initOracleClient({libDir: ...})` on Linux won't do what you think it might do.  This is different to Windows.

I don't know anything about Cloud Foundry.  If you describe the errors we can try and help.

**Comment by x0us** [comment]
@cjbj thank you for the response, i do realize i must set library search path, my code looks like
```
    private async createPool() {
        oracledb.initOracleClient({configDir: '../oracle/network/admin'});
        oracledb.autoCommit = true
}
```
I also notice blow information in guide, so if IBM doesn't install libaio, does that mean it's never work?

"You will need the operating system libaio package installed. On some platforms the package is called libaio1. Run a command like yum install -y libaio or apt-get install -y libaio1, depending on your Linux distribution package manager."

**Comment by cjbj** [comment]
You definitely need libaio or equivalent.

**Comment by cjbj** [comment]
private async createPool() {
        oracledb.initOracleClient({libDir: '../oracle/network/admin'});
        oracledb.autoCommit = true
}

If you are following our common naming pattern, you should change `libDir` to `configDir`.

**Comment by anthony-tuininga** [comment]
You need to set the environment variable `LD_LIBRARY_PATH` *before* you start your process or use `/etc/ld.so.conf` to set the library search path globally. Setting it via the `libDir` parameter will not work -- as Chris mentioned and you discovered! That is the reason for the first error in your last message. The second error simply means that you haven't set the library search path -- and you need to do so.

**Comment by x0us** [comment]
@anthony-tuininga  thank you so much.. got through eventually. below is the solution for someone whom meets the same issue with IBM cloud foundry:

1. add .profile in root path
2. add your oracle client custom path
```
export LD_LIBRARY_PATH=/home/vcap/app/dest/oracle:$LD_LIBRARY_PATH
```

thanks you so much @anthony-tuininga @cjbj
