### ISSUE TITLE
Guide to pool size based on how many requests

### ISSUE THREAD

**Issue by GuiJordao21** [oracle/node-oracledb#1395]
1. What versions are you using? ^4.0.0

2. Describe the problem

I would like to know if there are any recommendations on how much connections in my pool based on requests, e.g. poolMaxSize: 10 if dealing with 10 requests per second

3. Include a runnable Node.js script that shows the problem.

**Comment by cjbj** [comment]
@GuiJordao21 there are too many variables for any useful guide to be given: application-tier CPUs, networks, DB, what the SQL statements do.  Even sizing the pool to cope with the number of users concurrently executing statements doesn't give a full picture of whether the DB tier can cope with that load, or whether there is better throughput by having a smaller pool.

**Comment by GuiJordao21** [comment]
@cjbj thanks for your answer! Do you have some reading material on the subject to recommend so I can give the necessary attention to this matter in my company's specific scenario?

**Comment by cjbj** [comment]
@GuiJordao21 check out https://oracle.github.io/node-oracledb/doc/api.html#conpoolsizing and https://oracle.github.io/node-oracledb/doc/api.html#tuning

There are a lot of Node.js tuning resources around.  Every bit helps to reduce the load on the system.
