### ISSUE TITLE
Got issue on sql execute? Bug or  Compatibility

### ISSUE THREAD

**Issue by x0us** [oracle/node-oracledb#1398]
my version is: 5.2.0 the follow sql can run in sql tools and got data, exp:

SELECT * FROM (SELECT A.*, ROWNUM RN FROM(SELECT * FROM PRODUCT WHERE RATE > 1 ORDER BY CREATED_AT DESC) A WHERE ROWNUM <=10) WHERE RN >=0

but when i use node-oracledb, i got error.
```js

    async getRise(start:number, end:number): Promise<ProductDB[] | undefined>{
      const result = await OracleDB.execute(
        `SELECT * FROM (SELECT A.*, ROWNUM RN FROM(SELECT * FROM PRODUCT WHERE RATE> 1 ORDER BY CREATED_AT DESC) A WHERE ROWNUM <=:end) WHERE RN >=:start`,
         {start: start, end: end},
         {
           outFormat: OUT_FORMAT_OBJECT,
         }
      ) 
      return result?.rows
    }

```
execute SELECT * FROM (SELECT A.*, ROWNUM RN FROM(SELECT * FROM PRODUCT WHERE RATE> 1 ORDER BY CREATED_AT DESC) A WHERE ROWNUM <=:end) WHERE RN >=:start error

i'm pretty sure  start, end is number and assigned.
I don't know why this happened, please suggestion, thanks

**Comment by x0us** [comment]
a little update:

if i run like this by node-oracle( exp: end=10, start=0):

SELECT * FROM (SELECT A.*, ROWNUM RN FROM(SELECT * FROM PRODUCT WHERE RATE > 1 ORDER BY CREATED_AT DESC) A WHERE ROWNUM <=${end}) WHERE RN >=${start}.

I got wired empty array result.
[
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {}
  ]

if i run in sql tools, it works fine...

**Comment by x0us** [comment]
a little update

i use 'SELECT * FROM (SELECT A.*, ROWNUM RN FROM(SELECT * FROM PRODUCT WHERE RATE> 1 ORDER BY CREATED_AT DESC) A WHERE ROWNUM <=${end}) WHERE RN >=${start}' 

for temp solution, any idea?

**Comment by cjbj** [comment]
>  i got error.

What error?

> i'm pretty sure start, end is number and assigned.

Prove it to us! Give us a complete, runnable script that shows the problem.

**Comment by x0us** [comment]
> > i got error.
> 
> What error?
> 
> > i'm pretty sure start, end is number and assigned.
> 
> Prove it to us! Give us a complete, runnable script that shows the problem.

My fault... there is my sample repo
[https://github.com/x0us/node-oracledb-issue](url)

After some troubleshooting, I figured out, it's not an error, it just can't get return. the return value is null. but if i use ${xxx}, it works fine...
[https://github.com/x0us/node-oracledb-issue/blob/master/src/index.ts](main.ts)

**Comment by cjbj** [comment]
Since you say you figured this out, I'll close the issue.  Make sure to use bind variables for performance.  If your DB is 12c, then use the newer OFFSET / FETCH NEXT syntax, see [Limiting Rows and Creating Paged Datasets](https://oracle.github.io/node-oracledb/doc/api.html#pagingdata).
