### ISSUE TITLE
Pooling   "Cannot open further sessions"

### ISSUE THREAD

**Issue by RogelioGaytan** [oracle/node-oracledb#140]
Hi

 I'm trying to use pools in my app, and it works great, but for some reason it happens that node crashes, or sometimes it does not make the query execute from browser, and in the console keeps telling me >"Cannot open further sessions" But my configuration for creating the pool is:

```
oracledb.createPool({
      user            : dbConfig.user,
      password        : dbConfig.password,
      connectString   : dbConfig.connectString,
      poolMin         : 4,
      poolMax         :100 ,
      poolIncrement   : 5,
      poolTimeout     : 0
    },

```

The test i'm doing is by opening 6 diferent browsers (so it would be 6 connections in theory) but sometimes it goes wrong throwing that messages in console.

Is there any oher configuration or parameter that i'm missing?

Thanks in advance

**Comment by cjbj** [comment]
Are you correctly closing the connection if there is an execution error()?

**Comment by RogelioGaytan** [comment]
Yes i did have the connection.release() in an error ocurred.

But then i added the release when the execute function succeded and it seems that it was fixed. I don't know if this is a good practice because then the pool has to reopen the conection. Or is this approach correct?. 


Thanks

**Comment by dmcghan** [comment]
@RogelioGaytan Yes, you need to release the connection whether or not an error occurs. This is because a transaction is started in the database when you first use a connection. The driver doesn't know if you plan on reusing the connection for multiple executions as part of that transaction, so it's your responsibility to release it when you no longer need it.

**Comment by RogelioGaytan** [comment]
Thank you all my problem is solved by releasing the connection every time it is used.
