### ISSUE TITLE
Mac M1: NJS-067: a pre-built node-oracledb binary was not found for darwin arm64

### ISSUE THREAD

**Issue by pangkhon** [oracle/node-oracledb#1400]
1. What versions are you using?

2. Describe the problem.

3. Are you installing into vanilla Node.js, or using something like Electron?

4. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?

6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).

**Comment by cjbj** [comment]
Yes, there is no pre-built binary for that architecture.  See https://github.com/oracle/node-oracledb/issues/1349
