### ISSUE TITLE
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". #1218

### ISSUE THREAD

**Issue by luckyyyyy** [oracle/node-oracledb#1404]
## What versions are you using?
    process.platform: win32
    process.version: v16.6.1
    process.arch: x64
    require('oracledb').versionString: 5.2.0
    require('oracledb').oracleClientVersionString: 12 / 19
    vs: 2019 , install vs2017 and vs2015 build tools

## Is it an error or a hang or a crash?

use instantclient_12_1  Report error
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". #1218

Use instantclient_19_12 to successfully connect to the server

## What error(s) or behavior you are seeing?

![image](https://user-images.githubusercontent.com/9210430/132496555-b0347b44-75a7-40a1-8699-651e17074302.png)

## Include a runnable Node.js script that shows the problem.
```javascript
import oracledb from 'oracledb';

if (process.platform === 'win32') { // Windows
  oracledb.initOracleClient({ libDir: 'C:\\oracle\\instantclient_12_1' });
  // oracledb.initOracleClient({ libDir: 'C:\\oracle\\instantclient_19_12' });
}
```

![image](https://user-images.githubusercontent.com/9210430/132496055-1ef2a156-0e60-4e7c-b82a-93bab8faae6f.png)

![image](https://user-images.githubusercontent.com/9210430/132496078-63412c8c-3f2d-43f3-aa24-1b8ca8b49b81.png)

**Comment by anthony-tuininga** [comment]
Set the environment variable `DPI_DEBUG_LEVEL` to the value 64 and then rerun your code. Share the output here -- but as text, not an image! Take a look at the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html#-34-node-oracledb-installation-on-microsoft-windows) and make sure you are doing everything you need to do. Note as well that you can't have 32-bit and 64-bit mixing nd matching!

**Comment by luckyyyyy** [comment]
> Set the environment variable `DPI_DEBUG_LEVEL` to the value 64 and then rerun your code. Share the output here -- but as text, not an image! Take a look at the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html#-34-node-oracledb-installation-on-microsoft-windows) and make sure you are doing everything you need to do. Note as well that you can't have 32-bit and 64-bit mixing and matching!

ODPI [11232] 2021-09-08 22:27:23.437: ODPI-C 4.2.1
ODPI [11232] 2021-09-08 22:27:23.437: debugging messages initialized at level 64
123
ODPI [11232] 2021-09-08 22:27:23.442: Context Parameters:
ODPI [11232] 2021-09-08 22:27:23.442:     Oracle Client Lib Dir: c:\oracle\instantclient_12_1
ODPI [11232] 2021-09-08 22:27:23.442: Environment Variables:
ODPI [11232] 2021-09-08 22:27:23.442:     PATH => "C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\IncrediBuild;C:\Users\root\AppData\Local\Microsoft\WindowsApps;C:\Users\root\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\root\AppData\Roaming\npm"
ODPI [11232] 2021-09-08 22:27:23.442: load in parameter directory
ODPI [11232] 2021-09-08 22:27:23.442: load in dir c:\oracle\instantclient_12_1
ODPI [11232] 2021-09-08 22:27:23.442: load with name c:\oracle\instantclient_12_1/oci.dll
ODPI [11232] 2021-09-08 22:27:23.442: load by OS failure: The specified module could not be found

I checked the path to make sure the file existed.

downloaded the https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html#license-lightbox
This is 64-bit

**Comment by luckyyyyy** [comment]
@anthony-tuininga 
I use 19.12.0.0.0 and connect to server 10.2.0.1.0. It is ok, but the document describes that server 12 is the minimum support. Is there any unknown problem?

**Comment by anthony-tuininga** [comment]
@luckyyyyy , I believe that no testing has been performed against 10.2 database -- as far as I know that database is no longer supported anyway. You really should upgrade. :-)

From your debugging output it looks like you have covered the obvious issues. You will probably need to use Windows debugging tools to find out why it refuses to load the DLL. One possibility is the absence of the appropriate VS redistributable. @cjbj may be able to help more when he wakes up.

**Comment by luckyyyyy** [comment]
> @luckyyyyy , I believe that no testing has been performed against 10.2 database -- as far as I know that database is no longer supported anyway. You really should upgrade. :-

Thank you. I'll try to find out

**Comment by jifbrodeur** [comment]
Hi, I can confirm the issue with node-oracle 5.2 with instant client 19.2 cannot locate 64 bit Oracle Client Library DPI-1047 against an Oracle DB v. DB 18.3.0.0. Same configuration with Instant Client 18.5 works fine.
Thanks
Jean-François Brodeur
