### ISSUE TITLE
Error "Cannot read property '_getConnection' of undefined" during runtime upgrading to Typescript 4.4

### ISSUE THREAD

**Issue by deadratfink** [oracle/node-oracledb#1408]
Describe the problem

Hello,

we are using this package in v5.2 in one of our projects with Typescript 4.3 on top of Node.js 14 to access the oracle DB and everything is working fine so far.

One day we upgraded to Typescript 4.4 and received following error during _runtime_:

```json
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property '_getConnection' of undefined",
    "awsRequestId": "86de41f3-79d7-48aa-b419-f98eb52a7f6b",
    "stack": [
        "TypeError: Cannot read property '_getConnection' of undefined",
        "    at N (/var/task/av-create-accounts.js:2:1414450)",
        "    at /var/task/av-create-accounts.js:2:1441145",
        "    at t.getOracleConnection (/var/task/av-create-accounts.js:2:1465074)",
        "    at new c (/var/task/av-create-accounts.js:2:1462453)",
        "    at e.getServiceValue (/var/task/av-create-accounts.js:2:1482740)",
        "    at e.get (/var/task/av-create-accounts.js:2:1480527)",
        "    at Function.e.get (/var/task/av-create-accounts.js:2:1484047)",
        "    at Runtime.t.handler (/var/task/av-create-accounts.js:2:1470220)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}
```

So we investigated this and drilled it down to the the following piece of code used in our project:

```typescript
import { Connection, getConnection } from 'oracledb';

export function getOracleConnection(username: string, password: string, connectString: string): Promise<Connection> {
  return getConnection({
    user: username,
    password,
    connectString,
  });
}
```

without using a connection pool. The exported oracledb package's function `getConnection` itself refers to a `this._getConnection(connAttrs)`:

```
async function getConnection(a1) {
  let pool;
  let poolAlias;
  let connAttrs = {};

  // verify the number and types of arguments
  nodbUtil.checkArgCount(arguments, 0, 1);
  if (arguments.length == 0) {
    poolAlias = defaultPoolAlias;
  } else {
    nodbUtil.assert(typeof a1 === 'string' || nodbUtil.isObject(a1),
      'NJS-005', 1);
    if (typeof a1 === 'string') {
      poolAlias = a1;
    } else {
      connAttrs = a1;
      if (connAttrs.poolAlias) {
        poolAlias = connAttrs.poolAlias;
      }
    }
  }

  // if a pool alias is available, acquire a connection from the specified pool
  if (poolAlias) {
    pool = poolCache[poolAlias];
    if (!pool) {
      throw new Error(nodbUtil.getErrorMessage('NJS-047', poolAlias));
    }
    return await pool.getConnection(connAttrs);

  // otherwise, create a new standalone connection
  } else {
    try {
      return await this._getConnection(connAttrs);
    } catch (err) {
      if (err.message.match(/DPI-1047/)) {
        err.message += "\n" + nodbUtil.getInstallHelp();
      }
      throw err;
    }
  }
}
```

which looks like the `_getConnection` stated in the error message above. Looks like a `this`-binding done somewhere, but at least I couldn't find a reference to it in the file.

After some research we found a breaking change in Typescript 4.4 stated in [More-Compliant Indirect Calls for Imported Functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#more-compliant-indirect-calls-for-imported-functions) which could be a hint that the `this` is not defined by that change in Typescript.

Have you ever experienced problems with that error? Or have you tested the lib with Typescript 4.4 already? Maybe we are doing something wrong? 

At the moment we might see only a workaround using a connection pool so that we do not land in the else branch. Any other hints or suggestions to handle it different would be highly appreciated. Thanks in advance.

**Comment by cjbj** [comment]
I've seen a few reports.  Thanks for doing the investigation.  I'll mark this as a bug so it can be investigated.

We are not testing with Typescript (yet).

**Comment by anthony-tuininga** [comment]
Can you provide a simple, standalone TypeScript example that demonstrates the problem? As Chris mentioned, we have not been testing with TypeScript and my initial attempts have only been partially successful. Thanks!

**Comment by cjbj** [comment]
@deadratfink ping.  Can you test this?  Thanks!

**Comment by deadratfink** [comment]
Hi, 

thx for fast reaction. I will try to check it out as soon as possible, hopefully today ;-) I will give feedback once checked.

Btw, its not released yet, just in a separate branch, right?

Best regards,
Jens

**Comment by deadratfink** [comment]
Ok, I will try to setup locally first. Maybe it is not possible due to a special setup we have (OracleDb in AWS VPC and Lambda Layer with native Oracle Driver) I need to deploy it to dev and try it there. For this I need at least a branch to point NPM to in dependencies. So, it would be cool if the patch is on a branch I can point to my package.json. Alternatively, i can clone the repo and patch by myself. For the latter, do I need to execute some pre-stuff to make the lib „runnable“?

**Comment by deadratfink** [comment]
@anthony-tuininga BTW, it was fine with TS v4.3. The problem raised after we switched to v4.4.

**Comment by cjbj** [comment]
@deadratfink in case it helps, I pushed @anthony-tuininga's patch to the main branch.  However, since the change is in the JS layer, you may find it as easy to install 5.2 normally and then patch the JS file, similar to the suggestion in https://github.com/oracle/node-oracledb/issues/1391#issuecomment-884568248

**Comment by deadratfink** [comment]
Ah ok understood. Unfortunality, not. As I mentioned above we have a special setup with AWS Lambda Layer (for the native drivers - ok, ...this could be done on MacOs locally) and DB running in VPC (therefore, I cannot reach it from local machine). A colleague might be on a VM somehow located in AWS but he is on vacation till next Monday. Have another one but he has not tried that setup so much. This or the other way, it could last a while to get results by that. Trying the patching at the moment...

**Comment by cjbj** [comment]
@deadratfink thanks for persevering and confirming @anthony-tuininga's patch.

We should  be wrapping up the two-phase commit functionality for 5.3 in the next week or so (finally, finally after waiting for an early TPC adopter to get time to test, and after a tweak or two!!). So we plan to go straight to a 5.3 release once our normal release & stress tests have been run after that.
