### ISSUE TITLE
node_module_register error

### ISSUE THREAD

**Issue by sameer-coder** [oracle/node-oracledb#142]
Guys,

Got the following error and node refused to restart on pm2

Error: /opt/webapp/node_modules/oracledb/build/Release/oracledb.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/webapp/node_modules/oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Node version : v0.12.7
oracledb version : 0.6

What could be the cause of this issue and what would be the workaround?

Thanks for the help

**Comment by recunius-espoc** [comment]
I just ran into that error. It turned out I had an environment problem when running mocha. When I ran mocha I executing mocha installed against the node 0.10.* release.

**Comment by cjbj** [comment]
It does sound like a version mismatch.  Either fix the environment like @recunius-espoc suggested or rebuild node-oracledb for your current version of Node

**Comment by sameer-coder** [comment]
It might be a version mismatch issue because i upgraded node from 0.10 to 0.12 
but when i encouter this error i am able to simply restart node and everything works fine. Just not able to avoid this error from occuring. I tried to uninstall oracledb and do a fresh install but the error persists. Also it happens at a specific time of the day everyday. Weird

Any ideas guys?

**Comment by cjbj** [comment]
@sameer-coder I don't have any pearls on wisdom on this; except to triple check the environment.

**Comment by sameer-coder** [comment]
@cjbj I will do that....thanks for looking at the issue.

**Comment by cjbj** [comment]
@sameer-coder I saw it today when I upgraded Node from 0.10.x to 0.10.40 via brew on OS X.  It went away after I rebuilt.

**Comment by sameer-coder** [comment]
@cjbj  I had upgraded from Node 0.10.x to v0.12.7 after which the error started to appear. Ever since i have rebuilt the error seems to have gone away. :+1: 

Guess we can close this issue now.
