### ISSUE TITLE
fetchAsString support for object types

### ISSUE THREAD

**Issue by eliellis** [oracle/node-oracledb#1431]
1. What versions are you using?

5.2.0

2. Describe the problem

I've been using the library for quite some time now (loving it btw!) and have just run into something I was curious about. I'm dealing with some date values coming back from a stored proc that are `TIMESTAMP WITH TIME ZONE` typed, and these values are being returned by the procedure nested within a database object type, therefore this portion of the documentation applies:

> The options fetchAsBuffer and fetchAsString do not affect values in objects queried from the database.

This presents the unique challenge of not being able to interpret these dates appropriately in JS the way things are now. I of course understand I could change the procedure, or wrap it and do casting to strings in PL/SQL before consuming the values in JS. However this gets a little funny–changing the proc would impact a handful of other (ancient) consumers also dependent on the same proc, and while writing a PL/SQL wrapper would definitely work, it seems like an ugly approach if the driver itself could handle it as it does elsewhere.

I was wondering if there is a hard limitation with how these object types are handled at the ODPI level or some other serious hinderance that keeps `fetchAsString` from being supported in the above scenario, and if not, would like to ask kindly if it could be "added to the list." Thanks so much for your hard work on this library! 🙂

**Comment by cjbj** [comment]
@eliellis thanks for the example.

Fundamentally, we (as a community) have to decide how to do this conversion.  The existing fetchAs functionality asks the DB to do a conversion.  For objects that isn't possible. You can help by prototyping such a conversion in JavaScript.  What types need to be handled (e.g. [lobs](https://github.com/oracle/node-oracledb/issues/1222))?  Can we overload the fetchAs* attributes or would that break existing apps, meaning we need yet-another-setting?  Anthony asked other questions earlier.

**Comment by eliellis** [comment]
@cjbj 

Thanks for the link! Digging deeper into those issues, mine seems similar and the context was useful for getting the gears turning on anything new that might come of this.

I just wanted to clarify–by __prototype__ in this case, are you meaning give a couple brief psuedo-code examples of what this *could* look like in JS, and the scenarios that would need to be covered, along with any immediate caveats or considerations that might need to be taken into account? If so I can certainly take a crack at it and sketch-out what I think would be a decent and somewhat consistent.

**Comment by cjbj** [comment]
@eliellis your clarification is correct.  The more detail, the better.  Particularly around the actual conversion. Thanks!

**Comment by cjbj** [comment]
The node-oracledb 6.0 [output type handler converter](https://node-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#using-fetch-type-handlers-with-converters) functionality can be used to map object attributes.

Using the data inserted in [selectobject.js](https://github.com/oracle/node-oracledb/blob/main/examples/selectobject.js), the following converter:
```
function fth(metaData) {
  if (metaData.name == 'FARM' && metaData.dbType === oracledb.DB_TYPE_OBJECT) {
    return {converter: formatFarmer};
  }
}

function formatFarmer(val) {
  const v = {
    'FARMERNAME':val.FARMERNAME,
    'SEASON':val.SEASON.toLocaleString('de-DE'),
    'HARVEST': val.HARVEST,
  };
  return v;
}
```
and the query
```
    result = await connection.execute(
      `SELECT id, farm FROM no_farmtab WHERE id = 1 `,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT, fetchTypeHandler: fth }
    );

    for (const row of result.rows) {
      const farm = row.FARM;
      console.log('\nFarm is:', farm);
    }
```
prints the mapped date:
```
Farm is: {
  FARMERNAME: 'MacDonald',
  SEASON: '25.5.2023, 11:09:51',
  HARVEST: [CJ.DBHARVESTTYPE] [ 'Apples', 'Pears', 'Peaches' ]
}
```

**Comment by eliellis** [comment]
@cjbj I know I never got back around to this, but thank you! This is exactly the type of feature I was looking for. I appreciate all the hard work you and the other maintainers are putting into this library.
