### ISSUE TITLE
trascation gets commited when not asked to

### ISSUE THREAD

**Issue by adfel70** [oracle/node-oracledb#1435]
1. What versions are you using?
Give your database version.
19.9
Also run Node.js and show the output of:

    process.platform linux
    process.version node 14.15.4
    process.arch x64
    require('oracledb').versionString 5.2.0
    require('oracledb').oracleClientVersionString 21.1.0.0.0

2. Is it an error or a hang or a crash? no

3. What error(s) or behavior you are seeing?
I am using oracle nodejs driver to insert/update many records to multiple tables in a single transaction

the cmds are Not a plain sql but a PLSQL scripts that use if else  lock etc and apex.

what i do is this:
i create a connection (using a pool but i also tried using a single new connection and experienced the same issues).

OracleDb.autoCommit = false;
// create pool....
const con = pool.getConnection();
const cmds = // created cmds...
for(const cmd of cmds) {
  await con.exectute(cmd, { autoCommit: false} );
}

await con .commit();
await con.close()

what i have noticed is that when i execute the first command in the array it is not inserted into the db (i verified this using sql developer)
but when i execute the second command, the first command got committed even though i did not explicitly committed it and i passed autocommit: false

i cant post the code itself since it is too long 

how i found out about this:
i got an exception in the middle of the transaction (undefined column name in the table) but noticed that all the prior inserters/ updates were committed even though i called rollback.

when there is no exception all the commands are working but the every previous command is committed when the current command gets executed (with autoCommit = false)

(the command are working properly - when i run then one by one in sql developer - so the problem is not in the commands them selves.)

**Comment by cjbj** [comment]
You'll have to give actual SQL statements being run for us to help diagnose any issue.  If you can't share, then we'll have to close this issue and let you do the debugging.  Note there is a technical difference between 'inserted' and 'committed'.  I'm guessing that your first row was inserted but not committed.  If you did INSERT then SELECT using the same connection you would get the data returned, but if you do the SELECT in another tool you wouldn't.  I'm also guessing you have some DDL commands (e.g. CREATE or DROP). From the [doc](https://oracle.github.io/node-oracledb/doc/api.html#transactionmgt) "Note: Oracle Database will implicitly commit when a DDL statement is executed irrespective of the value of autoCommit."

**Comment by cjbj** [comment]
@adfel70 let us know how your debugging goes.  There's nothing more we can comment unless you post a complete, runnable script that shows the problem.
