### ISSUE TITLE
Query response has numeric columns 

### ISSUE THREAD

**Issue by anurajdark** [oracle/node-oracledb#1439]
I am executing a get query for which column names are coming in metaData and rows are coming in numeric fashion. An example is below: 
```
{
    "metaData": [{
        "name": "id",
        "name": "email"
    }],
    "rows": [
        ["1", "abc@gmail.com"],
        ["2", "xyz@gmail.com"]
    ]
}
```

Is there a way so that rows are returned in keyvalue pair as shown below: 

```
{
    "metaData": [{
        "name": "id",
        "name": "email"
    }],
    "rows": [
        ["id": "1", "email": "abc@gmail.com"],
        ["id": "2", "emai": "xyz@gmail.com"]
    ]
}
```

Any help in this will be very helpful. Thanks

**Comment by pvenkatraman** [comment]
Try:
oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
---Do the query
Refer to section 1.2.1 for example: https://oracle.github.io/node-oracledb/doc/api.html#oracledbconstantsoutformat
The metadata will not come in OBJECT format.

**Comment by anurajdark** [comment]
Thanks @pvenkatraman , this worked. Closing the ticket.
