### ISSUE TITLE
Keep a connection alive

### ISSUE THREAD

**Issue by xforceco** [oracle/node-oracledb#144]
As far as I am understanding, whenever I have to execute one sql statement, I have to open a new connection. Is it possible to force a connection alive so that I can keep executing statements?

**Comment by krismohan** [comment]
The connection object passed into the callback of getConnection is open till the application explicitly does a release() on that connection. You can execute as many statements as you want till then. Or if your logic is to execute a statement whenever there is a user request and you do not want to hold up the connection but want other threads to reuse it, you can look at the connection pooling feature.

**Comment by dmcghan** [comment]
@xforceco I wrote a post you may be interested in: https://jsao.io/2015/07/relational-to-json-with-node-js/

This show how you can use a connection to execute multiple statements in parallel. It also shows the benefits of using a connection pool.

**Comment by xforceco** [comment]
@dmcghan Thank you for the useful great post. But there is a little strange in the pool file, as createPool seems never get called, or will it automatically call?

**Comment by dmcghan** [comment]
@xforceco You are correct, I didn't show the file that called createPool. That was my test file - it created the pool and then started a loop through the departments table to test the performance of the solution.

I updated the post with a comment above the createPool function declaration. Hopefully that will help future readers. Sorry for the confusion!
