### ISSUE TITLE
How can I send my wallet to TypeOrm.io?

### ISSUE THREAD

**Issue by EdissonG** [oracle/node-oracledb#1442]
My TypeOrm connection code is as follows:

```
import oracledb from "oracledb";
​import​ ​{​ createConnection  ​}​ ​from​ ​"typeorm"​; 

oracledb.initOracleClient({ libDir: 'D:\\MaterialSkywork\\Oracle\\instantclient_21_3' });

createConnection({
    type: "oracle",
    username: "admin",
    password: "password",
    database: "DB_high",
    ​   ​synchronize​: ​true​, 
}).then(connection => {
    console.log(connection)
}).catch(error => console.log(error));
     

​export​ ​default​ createConnection;
```

But since I can't use the wallet I have connection problems and I get a TNS `ORA-12533` error back.

![image](https://user-images.githubusercontent.com/64019193/142022819-54acc430-185c-4539-bdc1-4ee4f5df4ae0.png)

**Comment by cjbj** [comment]
@EdissonG  The recut 19.13 Instant Client for Linux x86-64 supports the 1-way TLS (aka wallet-less) feature of Oracle Cloud DBs.  So if you can move to Linux (or wait for Windows Instant Client to catch up), then you won't need a wallet.
