### ISSUE TITLE
Q: Reduce time for data insertion through procedure

### ISSUE THREAD

**Issue by aanurraj** [oracle/node-oracledb#1443]
Hi I am using the node-oracledb for my application but it is too long to insert the data. I am doing following:

- Getting data from an excel sheet.
- Converting data rows into objects list.
- Inserting that data using a db procedue.

I have almost 13,000 records its takes nearly 34 mins to upload (most of the time it fails).

Any efficient way is welcomed

**Comment by cjbj** [comment]
See https://oracle.github.io/node-oracledb/doc/api.html#batchexecution

Also explore turning disabling indexes and constraints, and other DB optimizations eg re logging.
