### ISSUE TITLE
How to solve the problem of windows 32-bit

### ISSUE THREAD

**Issue by bingqianggg** [oracle/node-oracledb#1444]
![image](https://user-images.githubusercontent.com/87006181/142846891-d0d55ca5-8591-45d6-8134-744ca8b18266.png)

**Comment by cjbj** [comment]
It helps us if you answer the questions in the templates: https://github.com/oracle/node-oracledb/issues/new/choose

At a guess, you need to compile the binary module using the instructions in https://oracle.github.io/node-oracledb/INSTALL.html#github
We don't have pre-built binaries for 32-bit.

PS: not everyone can read screenshots, so please cut & paste text instead next time!  Thank you.
