### ISSUE TITLE
node-oracle on openshift

### ISSUE THREAD

**Issue by glifx** [oracle/node-oracledb#1447]
I try to run node-oracle on Openshift. 
The build from https://github.com/oracle/node-oracledb was successful.
After the scale up of node-oracle I see the following messae:

Environment:
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@6.14.14
npm info using node@v14.17.5_
**npm ERR! missing script: start**

In a second try cloned from GITHUB to my private BITBUCKET repo and added 
the following line to the package.json file:
"scripts": {
    .......
    "start": "node index.js",
The POD is not able to start and I cannot see an error message.

I am grateful for any help

**Comment by abrar-khan007** [comment]
Are u able to create build

**Comment by glifx** [comment]
Yes, the buld is successful
....
STEP 10: COMMIT temp.builder.openshift.io/mntechecklist-test/node-oracledb-1:0d05f974
Getting image source signatures
Copying blob sha2...................
Writing manifest to image destination
Storing signatures
Pushing image image-registry.openshift-image-registry.svc:5000/heck-test/node-oracledb:latest ...
Getting image source signatures
Copying blob sha256:..................
................
Writing manifest to image destination
Storing signatures
Successfully pushed image-registry.openshift-i..........
Push successful

**Comment by glifx** [comment]
A stupid question:
Is node-oracldb an own application (e.g. to be able to run as POD)  or “only” a part or function of an existing node.js pplication. 
In the second case, do I have to add node-oracledb as dependency to my package.json application?
