### ISSUE TITLE
Link to http://ora.cl/wHu returns 404

### ISSUE THREAD

**Issue by morgo** [oracle/node-oracledb#145]
In the project sub-description there is a link to http://ora.cl/wHu

I clicked on it for more details, but it resulted in a 404.

**Comment by cjbj** [comment]
Hi @morgo, thanks for pinging.  I logged a ticket earlier today to get that looked at.

**Comment by cjbj** [comment]
For the record the base URL redirected to is http://www.oracle.com/technetwork/database/database-technologies/node-js/index.html
