### ISSUE TITLE
nodejs如何连接多个oracle数据库

### ISSUE THREAD

**Issue by yi-xiaobai** [oracle/node-oracledb#1450]
### 最近接到一个新需求 如何使用`nodejs`连接两个及以上的数据库呢 各位大大们有没有什么好点解决办法呢 并发不是很大

**Comment by cjbj** [comment]
If I translated that correctly, you need to use different usernames, passwords and connect strings. Each database will have unique values. See https://oracle.github.io/node-oracledb/doc/api.html
