### ISSUE TITLE
NJS-007 invalid value for "poolMax" in parameter 1

### ISSUE THREAD

**Issue by yi-xiaobai** [oracle/node-oracledb#1451]
await oracledb.createPool({
            poolMax: 10,

            poolMin: 1,

            poolTimeout: CONFIG.ORACLE_POOL_TIME_OUT

        })

**Comment by cjbj** [comment]
Please answer the template questions https://raw.githubusercontent.com/oracle/node-oracledb/main/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md

Please give a complete program.
