### ISSUE TITLE
Not able to connecte with server

### ISSUE THREAD

**Issue by mh-i2c** [oracle/node-oracledb#1453]
-->
1. What versions are you using?
I am using version 12c and also try this thing on version 19c.

2. Describe the problem

I am able to connect with the database and execute queries but the problem is that once I have tried the same thing in a different file then I am getting an issue. I mean s that I am able to do the thing on just one file, but when I am creating one pool and connect with that pool on a different file then get an error.

3. Include a runnable Node.js script that shows the problem.
Create a database connection pool code : 
 file is index.js

```
const oracleDB = require("oracledb");
let conn;
const dbConnection = async () => {
      try {
                 oracleDB.initOracleClient({ libDir: "C:\\Oracle\\Middleware\\Oracle_Home\\bin" });
                conn = await oracleDB.createPool({
                                 user: 'system',
                                 password: 'Oracle123',
                                 connectString: 'localhost:1521/hard',
                                 poolIncrement: 0,
                                 poolMax: 4,
                                 poolMin: 4
                  });
        conn = await oracleDB.getConnection();
        console.log("Successfully connected to Oracle!",conn);
        } catch (error) {
            console.log(err)
       } finally {
           if (conn) {
               try {
                  await conn.close();
              } catch (err) {
                 console.error(err);
           }
       }
   }
}

dbConnection();
```

Database connection  code : 
file with name  simpleExecute.js

```
const oracleDB = require("oracledb");

async function simpleExecute(statement, binds = [], opts = {}) {
    let conn = "";
    let result = [];
    opts.outFormat = oracleDB.OBJECT;

    try {
        conn = await oracleDB.getConnection();
        result = await conn.execute(statement, binds, opts);
        return (result);
    } catch (err) {
        console.error(err);
        throw (err);
    } finally {
        if (conn) { // conn assignment worked, need to close
            try {
                await conn.close();
            } catch (err) {
                console.error(err);
            }
        }
    }
}
```

Query implement code : 

this one is query execution file: excution.js

```
const database = require("./simpleExecute");

database.simpleExecute("select * from response")
        .then(data => {  console.log("Executed", data); })
        .catch(err => {  console.log("Error", err);  });

module.exports.simpleExecute = simpleExecute;
```

Text : 
```
Server is running
Successfully connected to Oracle!
        Error: NJS-047: poolAlias "default" not found in the connection pool cache
    at OracleDb.getConnection (F:\A_Hardik\A_comapny\db_level_logger\node_modules\oracledb\lib\oracledb.js:267:13)
    at OracleDb.<anonymous> (F:\A_Hardik\A_comapny\db_level_logger\node_modules\oracledb\lib\util.js:178:19)
    at Object.simpleExecute (F:\A_Hardik\A_comapny\db_level_logger\lib\simpleExecute.js:8:31)
    at dbLogs (F:\A_Hardik\A_comapny\db_level_logger\lib\index.js:13:18)
    at Layer.handle [as handle_request] (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:323:13)
    at F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:341:12)
    at next (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:275:10)
    at F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\body-parser\lib\read.js:130:5
Error Error: NJS-047: poolAlias "default" not found in the connection pool cache
    at OracleDb.getConnection (F:\A_Hardik\A_comapny\db_level_logger\node_modules\oracledb\lib\oracledb.js:267:13)
    at OracleDb.<anonymous> (F:\A_Hardik\A_comapny\db_level_logger\node_modules\oracledb\lib\util.js:178:19)
    at Object.simpleExecute (F:\A_Hardik\A_comapny\db_level_logger\lib\simpleExecute.js:8:31)
    at dbLogs (F:\A_Hardik\A_comapny\db_level_logger\lib\index.js:13:18)
    at Layer.handle [as handle_request] (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:323:13)
    at F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:341:12)
    at next (F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\express\lib\router\index.js:275:10)
    at F:\A_Hardik\A_comapny\db_level_logger\test\node_modules\body-parser\lib\read.js:130:5
```

I have tried this code with async/await and try and catch and with the call back function as well.

Thank you very much for your help

**Comment by cjbj** [comment]
Can you edit your question and replace the code screen shots with actual runnable code that I can run to see  the error. Also replace error screen shots with cut & paste text.  Thanks

**Comment by mh-i2c** [comment]
> Can you edit your question and replace the code screen shots with actual runnable code that I can run to see the error. Also replace error screen shots with cut & paste text. Thanks

Please check my code and update me soon

**Comment by cjbj** [comment]
Can you format the code (as code!), and remove screenshots?  Thanks.

**Comment by mh-i2c** [comment]
> Can you format the code (as code!), and remove screenshots? Thanks.

Sorry but i am not able to edit some of code can you please check that one update me soon please

**Comment by mh-i2c** [comment]
> > Can you format the code (as code!), and remove screenshots? Thanks.
> 
> Sorry but I am not able to edit some of the code can you please check that one update me soon, please
Hello @cjbj  please update me about the issue

**Comment by mh-i2c** [comment]
Hello please update me regarding the issue if this is bug or problem in your package and update me so we can do something else or anything doing wrong then also update us

Thank you

**Comment by cjbj** [comment]
hi @mh-i2c It's a bug in your code.  

Make sure the process starts the connection pool before any users requests to the app are handled.

I don't know the relationship of index.js to your app.  Your output shows 'Server is running' but I don't see that message in the code you shared.

**Comment by cjbj** [comment]
@mh-i2c look at https://github.com/oracle/oracle-db-examples/tree/master/javascript/rest-api for inspiration.

**Comment by mh-i2c** [comment]
I think you did't understand what actually i am saying 
By using index.js file you can connect with database and execute queries by using conn veritable  but 
the problem is that i am creating my database pool in my index file but i need to execute queries on my other file or folder then it possible to do.
