### ISSUE TITLE
Can not get all values in the error object

### ISSUE THREAD

**Issue by haarse** [oracle/node-oracledb#1456]
I'm trying to write the eventually Oracle error I get to a file.
But when using JSON.stringify(err), the properties **message and stack** seems to be non-enumerable.
I found it impossible to save these two properties and write them out.
Is this true?
I'm using Typescript, but I don't think that is the problem.

`try {
    connection = await oracledb.getConnection( {
      user          : "hr",
      password      : mypw,
      connectString : "localhost/XEPDB1"
    });

    const result = await connection.execute(
      `SELECT qwerty
       FROM departments
       WHERE manager_id = :id`,
      [103],  // bind value for :id
    );
    console.log(result.rows);

  } catch (err) {
    **console.log(JSON.stringify(err));**
    console.error(err);
  } finally {
}`

You can see the difference in the two console functions result.
Can I get the values it in some other way?

**Comment by cjbj** [comment]
This isn't specific to node-oracledb:

```
let x = new Error('abc');
console.log(x.propertyIsEnumerable('message'));  // false
```

**Comment by haarse** [comment]
Ok, thanks.
I missed to check that.

**Comment by cjbj** [comment]
Comments, ideas and suggestions for improving error messages are welcome. (In particular I'd love to see a PR to print the error stack better, see https://github.com/oracle/node-oracledb/issues/465)
