### ISSUE TITLE
Is there a way to get the instant client version?

### ISSUE THREAD

**Issue by deostroll** [oracle/node-oracledb#1463]
Is there some way to get what instant client oracledb module is working with? This might help with including that data in performance reports and stuff.

**Comment by cjbj** [comment]
It's been discussed but I don't believe this is portably (or easily) available from the OS.   PRs welcome.  The closest might be to enable tracing with DPI_DEBUG_LEVEL=64

**Comment by deostroll** [comment]
Closing the issue. 

Given the constraint, I think the better way to get hold of where your oracle instant client is installed, and, its better that path name has the desired version somewhere in its name. On windows we might need a better alternative. But on linux-based OS we can echo the environment variable `LD_LIBRARY_PATH` (or within node `process.env.LD_LIBRARY_PATH`).
