### ISSUE TITLE
RETURNING INTO outBinds data elements returned as arrays

### ISSUE THREAD

**Issue by kbhanush** [oracle/node-oracledb#148]
When I use outBinds to get an inserted row, data is returned with each value in the key-value pair as an array, like this - 

{ ITEM_ID: [ 22 ],
  OFFER_ID: [ 81 ],
  OFFER_BY: [ 42 ],
  OFFER_CREATE_DATE: [ '27-JUL-15' ],
  OFFER_AMOUNT: [ 1500 ],
  OFFER_STATUS: [ null ] }

I now have to unwrap each value to use it in my controller ( I am using angularJS) 

Does anyone know of a better way to do this? Can data be returned simply an a JSON object, like it would in a select call - 

{ ITEM_ID: 22,
  OFFER_ID: 81,
  OFFER_BY: 42,
  OFFER_CREATE_DATE: '27-JUL-15',
  OFFER_AMOUNT:1500 ,
  OFFER_STATUS:  null  }

Note: Im ok with dates being returned as strings, my question is about the format only

**Comment by cjbj** [comment]
@kbhanush Thanks for bringing it up.  I'd like to hear other peoples comments on this behavior of RETURNING INTO bind variables. 

You will have to unwrap the values.  The "DML RETURNING" behavior of Oracle Database allows arrays of values to be returned.  After lengthy debate about common cases vs general cases vs how we might in future allow PL/SQL arrays to be bound, we eventually decided that node-oracledb should always return an array for RETURNING INTO bind variables.  See the note in https://github.com/oracle/node-oracledb/blob/master/doc/api.md#dmlreturn

**Comment by cjbj** [comment]
@kbhanush I'm closing this for now.
(PS congrats on the success of the Node & node-oracledb hackathon you ran in Santa Clara!)
