### ISSUE TITLE
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.17.0 (darwin, x64)

### ISSUE THREAD

**Issue by pc-jdk** [oracle/node-oracledb#1491]
1. What versions are you using?

2. Describe the problem.

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.17.0 (darwin, x64)
Cannot load /Users/Documents/Project Repo/value-api/node_modules/oracledb/build/Release/oracledb.node
DPI-1050: Oracle Client library is at version 11.2 but must be at version 0.0 or higher
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html

4. Are you installing into vanilla Node.js, or using something like Electron?
Nodejs version 8.17.0 
5. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?

Oracledb instant client version 19_8 (64X)

Inserted .dylib files in usr/local/lib

6. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?

7. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).

**Comment by cjbj** [comment]
Is this a duplicate of https://stackoverflow.com/questions/71655549/oracledb-add-on-binary-for-node-js-8-17-0-mac-64-intel/71668915#71668915 ?  See my answer there.
