### ISSUE TITLE
IO 错误: Undefined Error

### ISSUE THREAD

**Issue by DYY-Serious** [oracle/node-oracledb#1492]
![MH@Y7OMPA1S3$B8I1YCCFUL](https://user-images.githubusercontent.com/101509133/163328723-689e4682-9573-4aca-9f60-c32cc1815464.png)

**Comment by cjbj** [comment]
This repo is for node-oracledb but you are using jdbc.  Try asking at https://community.oracle.com/tech/developers/categories/java_database_connectivity
