### ISSUE TITLE
NJS-047: poolAlias "MARTM" not found in the connection pool cache

### ISSUE THREAD

**Issue by raoakky22** [oracle/node-oracledb#1494]
1- version
  oracledc-"5.2.0"

2- problem

facing these two issues 
NJS-047: poolAlias "MARTM" not found in the connection pool cache
pattern of NJS 047 is off on off on kind so it works then it stops then it works again then it stops

NJS-046: poolAlias "BMTR" already exists in the connection pool cache Request

we have pool and initialisation is also being done.

**Comment by cjbj** [comment]
Since I don't know your code, all I can do is commiserate.  It sounds like you have a problem with async.
