### ISSUE TITLE
Problem in connection to on premise oracle from aws

### ISSUE THREAD

**Issue by prasadnn** [oracle/node-oracledb#1498]
Hi, I am currently trying to connect to on premise oracle db through nodejs code deployed in AWS,
I have set the instant client properly but when I try to get the connection it is getting timed out,
when I try the same thing in my laptop I am able to connect to oracle and execute queries but 
when I try to run it from aws it is getting timedout. In AWS lambda I have set the maximum time limit as 
15 minutes. I am not seeing any exception in the logs, please suggest how to proceed further.

Oracle db version - 19.0.0
Instant client version  - 21_6
node-oracle db version - 5.3.0

Regards,
Prasad

**Comment by cjbj** [comment]
What's the error?

Ask your AWS contacts.  It sounds like a networking problem.
