### ISSUE TITLE
Support external authorization

### ISSUE THREAD

**Issue by dvtylr** [oracle/node-oracledb#15]
It seems that all the plumbing is in place to support external accounts.  I tested the implementation by setting dpienv_->isExternalAuth(true); to true in the Oracledb constructor and was able to connect via Kerberos so it seems to work except that I do not see a way to set this value dynamically.  I would think a reasonable behaviour is to assume isExternalAuth if no user name is provided.

**Comment by cjbj** [comment]
Allowing external auth is high on our todo list.  Thanks for the confirmation of its priority.

**Comment by cjbj** [comment]
External authentication is available in 0.4.1
