### ISSUE TITLE
ErrorNum: 0 what does it mean?

### ISSUE THREAD

**Issue by Mohammed-Ahmed-Ismail** [oracle/node-oracledb#1500]
I'm having this error {"errorNum":0,"offset":0} while performing an Update, it happen most times not at all  , someone knows the meaning of this return ? Is it related to high amounts of requests ? If i need to change change some attribute when creating pool to solve that ?

kindly find the below code that catch the mention error
```
async function execute() {
    let connection = await connectionPool.getConnection();
    try {
        oracledb.fetchAsString = [ oracledb.CLOB ];
        let result = await connection.execute(...arguments);
        return result;
    } catch (error) {
        logger.error({ Error: error, Data: arguments });
        return -1;
    } finally {
        await connection.close();
    }
}
```
using "oracledb":  4.1.0

**Comment by cjbj** [comment]
[I formatted your code: use triple back ticks on their own line for code blocks]

Without an actual test case I can't guess what's going on.   No one else has reported it.
What version of Oracle DB and Oracle client libraries do you have?
You code raises a couple of questions:
- Why keep setting fetchAsString all the time?  This should be set during initialization
- why not catch errors from getConnection, and also then check whether the connection exists before trying to close it?
- Where are you passing the arguments from?  Do you have some race condition occurring where values are changing?

**Comment by sosoba** [comment]
Maybe you are trying to retrieve CLOB content from the result ouside this function while the connection is already closed by your wrapper.
