### ISSUE TITLE
Using Object.keys() and Object.values() to create INSERT binding params dynamically

### ISSUE THREAD

**Issue by EvanGrillo** [oracle/node-oracledb#1502]
_**This could be related to a bug, feature request, or misunderstanding of documentation in #bind section.**_

```
TABLE: {
	‘one’: number,
	‘two’: varchar,
	‘three’: varchar,
	‘four’: varchar,
	‘five’: date
 }
```
**_Each column in the table is nullable_**

Ideally, we can target columns based on payload:
```
let payload = {
	‘one’: 1,
	‘three’: ‘3’,
	‘five’: new Date(‘2022-06-09’)
 }
```

Use Object.keys() & Object.values() to 
```
connection.execute(
	‘
		INSERT INTO table_name (:fields)
		VALUES (:values)
	`,
	{
		fields: Object.keys(payload), 
		values: Object.values(payload) 
	}
)
```

**What's the correct way to dynamically create binding params for both columns and values?**

**Comment by cjbj** [comment]
You can bind data, but not the text of the SQL statement, so you will have to dynamically (and carefully - watch out for SQL Injection issues) concatenate text to create the SQL statement, and only use bind variables for data.  See [Binding Column and Table Names in Queries](https://oracle.github.io/node-oracledb/doc/api.html#sqlbindtablename).  The documentation [Binding Multiple Values to a SQL WHERE IN Clause](https://oracle.github.io/node-oracledb/doc/api.html#sqlwherein) has a technique for constructing SQL statements that contain bind variables.  You can combine the techniques from both sections to achieve your goal.

**Comment by EvanGrillo** [comment]
Thanks for your help. So with guards and bind handling, a simple implementation may look like:
```
connection.executeMany(
	‘
		INSERT INTO table_name (${['one', 'three', 'five'})
		VALUES (${[:1, :3, TO_DATE(:5, 'YYYY-MM-DD')]})
	`,
	[[1, '3', new Date()]]
)

**Comment by cjbj** [comment]
Thanks for sharing!
