### ISSUE TITLE
Error: ORA-12170: TNS:Connect timeout occurred

### ISSUE THREAD

**Issue by Serban123** [oracle/node-oracledb#1506]
I want to connect node.js to oracle db and I am getting this error: 

```
Error: ORA-12170: TNS:Connect timeout occurred
    at async run (C:\nodejs\oracle\index.js:21:18) {
  errorNum: 12170,
  offset: 0
}
```

This is the code that I wrote to make the select 

```
const oracledb = require('oracledb');

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;

 

async function run() {

  let connection;

  try {
    oracledb.initOracleClient({libDir: 'C:\\instantclient_21_6'});
  } catch (err) {
    console.error('Whoops!');
    console.error(err);
    process.exit(1);
  }


  try {
    connection = await oracledb.getConnection( {
      user          : "xxx",
      password      : "xxx",
      connectString : "(tnsnames address)))"
 });

    const result = await connection.execute(
      `select * from persons`
    );
    console.log(result.rows);

  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

run();
```

I am a newbie in nodejs and I would like to know what I am doing wrong or be given a working example. I also installed the oracle instant client

**Comment by cjbj** [comment]
[I edited your question to put triple-backticks around code so it formats nicely]

Your node-oracledb installation appears fine.  It is probably the connection string you are using in the application, and/or whether the database is running that is the problem.

Do you know if the database is up?  Can you connect with another tool like SQL\*Plus?

Is your database on the same machine where Node.js is running?

**Comment by Serban123** [comment]
The database is on another machine and I have to connect through a vpn to access it. It works if I access it with toad

**Comment by sosoba** [comment]
Use a utility like `netstat` to check that both connections (from Toad and Node) are to the same IP and with the same source address.

**Comment by cjbj** [comment]
Can you give a more complete, but still redacted, example of the connect string you are using?
