### ISSUE TITLE
Setting connection.module to undefined failes

### ISSUE THREAD

**Issue by ReneBeszon** [oracle/node-oracledb#1507]
Dear all,

reading the documentation from connection.module setting it to undefined is allowed

![image](https://user-images.githubusercontent.com/70770935/177326725-e90adc34-f0e5-498c-bf6e-327606d31941.png)

but when doing so, it results in a database error

NJS-004: invalid value for property module

when setting to "" everything works fine.

**Comment by cjbj** [comment]
Our doc https://oracle.github.io/node-oracledb/doc/api.html#propconnmodule carefully doesn't mention anything about undefined.

It seems you are showing the Typescript definition from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/oracledb.  Can you open an issue there and ping @dannyb648? I also see @sla100 has made some contributions.

**Comment by cjbj** [comment]
Closing. As mentioned, this should be reported about the typescript definition file.
