### ISSUE TITLE
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library

### ISSUE THREAD

**Issue by surajkrishan** [oracle/node-oracledb#1512]
1. What versions are you using?

    "oracledb": "^5.4.0",

3. Describe the problem

Getting DPI-1047 error even tho i have given the path of oracle client lib.

5. Include a runnable Node.js script that shows the problem.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/32816421/187632636-44407b1c-4a3d-4054-94d1-f6b9546a3ca8.png">

**Comment by cjbj** [comment]
Can you cut & paste code?  Not everyone can read screen shots.

Also read the [doc](https://oracle.github.io/node-oracledb/doc/api.html#initnodeoracledb) about initOracleClient() on Linux:
> If you set libDir on Linux and related platforms, you must still have configured the system library search path to include that directory before starting Node.js.

**Comment by surajkrishan** [comment]
Hi @cjbj - I actually found the example oracle code which I have followed, and it worked.
But I personally feel why we need a separate client lib to be placed alongside with code.
It should be part of node_module itself would be really great.

**Comment by cjbj** [comment]
@surajkrishan check out https://github.com/oracle/node-oracledb/issues/1497
