### ISSUE TITLE
node-oracledb v5.5.0 is available

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#1515]
node-oracledb v5.5.0 is available.  Along with some fixes, this release supports authentication with OAuth2 tokens in Oracle Cloud. See the [release announcement](https://cjones-oracle.medium.com/node-oracledb-5-5-for-oracle-db-supports-oauth2-token-authentication-15e30737ad81) and [CHANGELOG](https://github.com/oracle/node-oracledb/blob/main/CHANGELOG.md).

**Comment by sschneider-ihre-pvs** [comment]
It seems that in the current version the driver is searched not in node_modules but in the project root/src folder.
`Exception has occurred: DriverPackageNotInstalledError: Oracle package has not been found installed`

**Comment by cjbj** [comment]
There were no changes in that area.  Also my scripts run fine.  Can you provide more information?  Maybe make sure your directory hierarchy below _and above_  your current directory don't have other node_modules folders.

**Comment by sschneider-ihre-pvs** [comment]
I use a nx workspace where there is node_modules in the root folder but the search path for the oracle driver is ./src but only in 5.5.0, when I revert to 5.4.0 it works.

**Comment by sschneider-ihre-pvs** [comment]
okay maybe that was some kind of hicup, i reinstalled 5.5 and not it seems to work
