### ISSUE TITLE
How node-oracledb can work in AWS Lambda?

### ISSUE THREAD

**Issue by dimotech** [oracle/node-oracledb#1518]
1. What versions are you using? 5.4.0

2. Describe the problem

Could we have an official example to make oracle work in aws lambda? Right now I having some issues on the instant client in lambda layer? And it's telling me  "DPI-1047: Cannot locate a 64-bit Oracle Client library: \"/opt/oracle-instant-client/lib/libclntsh.so: file too short\".

3. Include a runnable Node.js script that shows the problem.

**Comment by cjbj** [comment]
Hopefully a Lambda user will contribute that doc.  Until then, search this repo for previous discussions.  Also check out StackOverflow.  There are various posts there for node-oracledb or the related cx_Oracle driver that may help.
