### ISSUE TITLE
Test a variable to be an instance of ResultSet class

### ISSUE THREAD

**Issue by fedulovivan** [oracle/node-oracledb#152]
Is it possible to make following trick
``` javascript
// get access to class constructor
var ResultSet = require("oracledb").ResultSet;
// ...
if(result.resultSet instanceof ResultSet) {
// now we know we working with result set class
// ...
}
```

**Comment by cjbj** [comment]
Would using this be sufficient?:
```
    if (Object.prototype.toString.call(result.resultSet) == '[object ResultSet]') {
    . . . 
    }
```

**Comment by fedulovivan** [comment]
Thanks, this is a solution. But can't your option be simpler, just like `result.resultSet === "[object ResultSet]"`?

**Comment by cjbj** [comment]
@fedulovivan In contexts where a string is expected that should work.

PS I think you meant "==" not "==="

**Comment by cjbj** [comment]
This is now possible in 1.7
