### ISSUE TITLE
vscode + WSL2 64 ubuntu-18.04   DPI-1047: Cannot locate a 64-bit Oracle Client library. help me plz

### ISSUE THREAD

**Issue by mike-hor** [oracle/node-oracledb#1522]
1. What versions are you using?
    vscode + WSL2 64 ubuntu-18.04

2. Describe the problem
 
    I use vscode and wsl2 ubuntu:18.04 to develop nodejs app.
    I download the oracle Instant Client unzip to the path:
    /home/hyh/ops-next/server/instantclient_11_2/linux
    and  then add  env
    export LD_LIBRARY_PATH=/home/hyh/ops-next/server/instantclient_11_2/linux:$LD_LIBRARY_PATH
    but,i get error.
    - thorw error, 
    Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "/home/hyh/ops-next/server/instantclient_11_2/linux/libclntsh.so: cannot open shared object file: No such file or directory"
    - and i add symbol link
    ```shell
    cd  /home/hyh/ops-next/server/instantclient_11_2/linux
    ln -s libclntsh.so.11.1 libclntsh.so
    ```
    - thorw another error
    Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libnnz11.so: cannot open shared object file: No such file or directory"
    
        but i find libnnz11.so in the path /home/hyh/ops-next/server/instantclient_11_2/linux ,the error make me so confused.
    - so,what shoud i do,by the way code running well in windwos.

3. my code
```js
const oracledb = require("oracledb");
const path = require("path");
const platform = process.platform;
const libDir = platform == 'win32' ? path.resolve(process.cwd(), 'instantclient_11_2', 'windows') : path.resolve(process.cwd(), 'instantclient_11_2', 'linux');
console.log(libDir);  //    /home/hyh/ops-next/server/instantclient_11_2/linux
try {
    oracledb.initOracleClient({
        libDir
    });
    oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
} catch (err) {
    if (err.message.indexOf('NJS-077') < 0) {
        console.log(err)
    }
}

```

**Comment by cjbj** [comment]
- Unless you really need to connect to something like Oracle DB 9.2, you could/should upgrade Instant Client.  
- On Linux, calling `initOracleClient()` doesn't do what you (and we all) want it to do.  The error about libnnz will occur if the system library search path (e.g. LD_LIBRARY_PATH, or that set by ldconfig) doesn't contain the Oracle client libraries _before_ Node.js starts.  You should avoid passing libDir to `initOracleClient()` on Linux.
- From Googling for the people who are using Instant Client on WSL, it seems like all you would need is LD_LIBRARY_PATH set.  Make sure Node.js is being invoked by a shell where LD_LIBRARY_PATH is set correctly.

**Comment by mike-hor** [comment]
tks,I reslove the problem.
as you say,just export $LD_LIBRARY_PATH ,not use libDir(musut in node shell,before node runing).
