### ISSUE TITLE
Node Module Did not self-register on Window | node-oracledb Prebuilt Binary issue

### ISSUE THREAD

**Issue by darshithedpara** [oracle/node-oracledb#1530]
**1. What versions are you using?**

    process.platform : win32
    process.version: v14.20.1
    process.arch: x64
    require('oracledb').versionString: Not able to get due to above error
    require('oracledb').oracleClientVersionString: Not able to get due to above error

----------------------------------------

**2. Describe the problem.**

npm i oracledb
![image](https://user-images.githubusercontent.com/22654104/201596221-b8386c68-b6e7-453c-8ad2-e8c12099e4a6.png)

It is giving error when tried to getConnection of remote oracledb:

**node oracle.mjs** : below is the content of my source code.
![image](https://user-images.githubusercontent.com/22654104/201596989-27fce3a7-9666-466f-95ee-5fa19d486f7c.png)

**Error I am getting :**
![image](https://user-images.githubusercontent.com/22654104/201597077-d557cd1f-d034-41bf-a0db-f1c30618ac4e.png)

----------------------------------------

**3. Are you installing into vanilla Node.js, or using something like Electron?**
Vanilla Nodejs v14.20.1

----------------------------------------

**4. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?**

**Location :** C:\Oracle\Client\19.3.0_64
"It is 64-bit"

----------------------------------------

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?
NOT SET

----------------------------------------

6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
**ORACLE_HOME=C:\Oracle\Client\19.3.0_64**

----------------------------------------

**Comment by cjbj** [comment]
Please don't use screenshots since not everyone can read them, and we can't cut & paste from them.

**Comment by darshithedpara** [comment]
> Please don't use screenshots since not everyone can read them, and we can't cut & paste from them.
I am using Remote machine and I am not able to copy the source codes @cjbj

**Comment by pvenkatraman** [comment]
1. Instant client directory should be in the PATH environment variable.
2. Your second screen shots shows that it is not able to load oracledb.node.  NODE_PATH environment variable is required and should point to lib/ directory where oracledb.js is available.

**Comment by darshithedpara** [comment]
Hi @pvenkatraman , There is not lib folder in my installation, Can you please explain in detail ?
![image](https://user-images.githubusercontent.com/22654104/201601537-8ffb77aa-f768-4764-ac57-df0817118511.png)

**Comment by pvenkatraman** [comment]
1. npm install oracledb -> this creates node_modules\ directory and pulls in different modules including oracledb\
Look in node_modules\oracledb\lib\ directory contains oracledb.js and add this directory to NODE_PATH environment variable.
2. Add C:\Oracle\Client\19.3.0_64\bin directory to PATH environment variable and try again.

**Comment by darshithedpara** [comment]
1] C:\Oracle\Client\19.3.0_64\bin and C:\Oracle\Client\19.3.0_64 is already exist in system env PATH
2] I have added NODE_PATH as you instructed

still getting same error @pvenkatraman

**Comment by pvenkatraman** [comment]
In your cmd window - do echo %PATH% and echo %NODE_PATH% and check whether these directories are included.

**Comment by darshithedpara** [comment]
Yes It's there @pvenkatraman 
![image](https://user-images.githubusercontent.com/22654104/201605275-bec2e8b1-c36f-40fd-ae66-226d5d931fdb.png)

**Comment by pvenkatraman** [comment]
NODE_PATH should not include oracledb.js.  only the directory.

**Comment by darshithedpara** [comment]
Yes I've tried that , still I am getting same error of module did not self register @pvenkatraman 
![image](https://user-images.githubusercontent.com/22654104/201608003-f02127a8-8d71-4169-9212-9a38c4fb2912.png)

**Comment by darshithedpara** [comment]
I want to know what causing the issue, It is issue with node or node-oracledb binary ? or may be PATH env issue ?

Can you please ? @pvenkatraman @cjbj

**Comment by cjbj** [comment]
Checked Google?  I can see a few hits with various suggestions for debugging.
I still can't read screen shots properly but I see you have Instant Client and some full client installed. Maybe you have a clash?

**Comment by darshithedpara** [comment]
Yes you're right I have put that instantClient by downloading manually and I have updated PATH variable but that also not worked so I am not using that instantClient anymore also removed any reference in PATH variable.
@cjbj

**Comment by sharadraju** [comment]
@darshithedpara Are you still facing this issue?

**Comment by darshithedpara** [comment]
Yes @sharadraju

**Comment by sharadraju** [comment]
@darshithedpara Have you tried installing other npm modules? Do they give the same error?
You can try rebuilding npm in your machine as shown [here](https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register).

Also, node-oracledb for Windows users will require the [Visual Studio 2017 Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) as shown [here](https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html#quick-start-node-oracledb-installation). Please let us know if it is installed.

**Comment by darshithedpara** [comment]
npm rebuild - I’ve tried no luck.
and In my machine I have these redistribution libs
![image](https://user-images.githubusercontent.com/22654104/206680229-e544a6f3-ce07-4fee-95c9-7bb8f206e74e.jpg)

Please advise should I need to install 2017 even if 2015-2022 is installed ? @sharadraju
