### ISSUE TITLE
Not able to initialize client when running with specific group (sg command)

### ISSUE THREAD

**Issue by Alankarsharma** [oracle/node-oracledb#1531]
1. What versions are you using?
process.platform: linux
process.version: v18.9.0
process.arch: x64
require('oracledb').versionString: 5.3.0
require('oracledb').oracleClientVersionString: 21.8.0.0.0

2. Is it an error or a hang or a crash?
Error: Cannot locate a 64-bit Client library: "libnnz21.so"

3. What error(s) or behavior you are seeing?
If I run program using command "node test.js" it works properly.
But if I use command 'sg groupabc -c "node test.js"' in this case I get an error.
I have tried changing permission on on instantclient folder, but always got same error.

4. Include a runnable Node.js script that shows the problem.
const oracledb = require('oracledb');
oracledb.initOracleClient({libDir: 'path to instant client folder'})

**Comment by cjbj** [comment]
This is a limitation of the client libraries on Linux.  It's documented in https://oracle.github.io/node-oracledb/doc/api.html#oracleclientloadinglinux :

> Note on Linux initOracleClient() is only useful to force immediate loading of the libraries because the libraries must also be in the system library search path, i.e. configured with ldconfig or set in LD_LIBRARY_PATH, before Node.js is started.

**Comment by Alankarsharma** [comment]
LD_LIBRARY_PATH is also set. If I run following code even then behavior is exactly same.
const oracledb = require('oracledb');
oracledb.initOracleClient();

**Comment by anthony-tuininga** [comment]
How is `LD_LIBRARY_PATH` set? If it is not set *before* the process starts it has no effect.

**Comment by Alankarsharma** [comment]
I have set it in command line before running program.
Have verified value also in program by printing it on console log.

**Comment by cjbj** [comment]
Show us _exactly_ how you set the variable.

Do you have the nnz file?    Do you have any permissions issues?

**Comment by Alankarsharma** [comment]
export LD_LIBRARY_PATH=/data/instantclinet  (I have renamed original instantclient_21_8 to instantclient)
This is how LD_LIBRARY_PATH is set.
On same terminal session I am running 'node test.js' and  'sg groupabc -c "node test.js"' commands.

**Comment by cjbj** [comment]
I've not played with sg but anything like that has a good change of not propagating environment settings.  Try using ldconfig as recommended in the node-oracledb installation instructions.

**Comment by Alankarsharma** [comment]
What's the default folder location where it will search?
I will try to create a link and test.

**Comment by Alankarsharma** [comment]
Tried with ldconfig, it worked. Thanks.
