### ISSUE TITLE
thin mode support for node-oracledb

### ISSUE THREAD

**Issue by liudonghua123** [oracle/node-oracledb#1533]
I searched `thin mode` in issues, found https://github.com/oracle/node-oracledb/issues/1497, however the original issue have closed. So I opened a new issue to track the `thin mode` support in `node-oracledb`.

I noticed that python's implementation has already finished, see https://github.com/oracle/python-oracledb#dependencies-and-interoperability. So maybe node's implementation could be soon.

**Comment by VegarRingdalAibel** [comment]
This sounds very nice, will also be easier to support deno/bun or any other new libs if it ever comes. 👍

**Comment by liudonghua123** [comment]
Any updates?

**Comment by cjbj** [comment]
@liudonghua123 nothing to share yet.  There is a little bit of discussion on [Slack](https://github.com/oracle/node-oracledb#-help) about it.

**Comment by MasterOdin** [comment]
@cjbj it looks like your link leads to the 6.0.0-dev readme, and not a slack thread? Was that intentional?

**Comment by cjbj** [comment]
@MasterOdin Partly intentional.  The README has the link for joining Slack.  I'll update the link to the project home page section with the same Slack info.

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/1550 :)

**Comment by liudonghua123** [comment]
@cjbj wow, good work! 😄

**Comment by cjbj** [comment]
Done!  See https://medium.com/@sharad-chandran/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2

**Comment by liudonghua123** [comment]
Thanks for your nice work!
