### ISSUE TITLE
Add support for windows 11  arm64 

### ISSUE THREAD

**Issue by woderchen** [oracle/node-oracledb#1534]
Hi 
I re-compiled project on new window 11 ARM64,   got error as below,
Error: NJS-045: cannot load a node-oracledb binary for Node.js 14.17.5 (win32 arm64)

would you please tell me the plan for windows arm64?  or any way to fix it...
 
my envrioment:
OS: windows 11 arm64
node  v14.17.5
python v2.7.15

**Comment by sharadraju** [comment]
Pre-built node-oracledb binaries are available only for Windows 64-bit, Linux x86_64, and macOS (Intel x86) for now.

For other platforms, you would need to check if Oracle client libraries are supported in your Windows configuration. Please check the [link](https://docs.oracle.com/en/database/oracle/oracle-database/21/ntcli/operating-system-checklist-for-oracle-database-client-installation-on-microsoft-windows.html#GUID-DB33F444-969C-48EC-A6CC-83E938499DCB) for the supported list of platforms for Oracle Client libraries.
I don't think the 32-bit Windows platform is supported.

For more details, please check
[https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html#prerequisites](https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html#prerequisites)

**Comment by woderchen** [comment]
I see, Thanks for your quickly feedback.
