### ISSUE TITLE
Debugging ORA-01008

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [oracle/node-oracledb#1536]
1. What versions are you using?
oracledb 5.5.0
db 11g

windows 10

2. Describe the problem

I make a raw sql call to a package with bindings and I face a ORA-01008, but when I execute it manually in any db client it works. So my questions, how do I debug what variable is not referenced correctly?
I followed the trail through the js part already but then `this._execute` makes a leap for the c part I figure. And that is where the power of the node debugger fails me.

**Comment by pvenkatraman** [comment]
Can you provide more details like:
- Exact sQL statement
- Bind parameters

Thanks

**Comment by sschneider-ihre-pvs** [comment]
I can't

**Comment by pvenkatraman** [comment]
ORA-01008 : Not all variables bound, You are obviously missing one or more bind parameter.  You need to make sure that you are providing bind parameters for all bind variables.

**Comment by sharadraju** [comment]
@sschneider-ihre-pvs
Please provide us the JS code with a redacted version of the SQL statement (with the table and column names changed) that is being passed in the JS app?
This will help us to identify which bind parameter is not matched correctly.
