### ISSUE TITLE
Surprising default session timezone setting

### ISSUE THREAD

**Issue by bjouhier** [oracle/node-oracledb#154]
When I execute `SELECT SESSIONTIMEZONE FROM dual` I get the following results:
- SQLDeveloper:  `Europe/Paris`.
- oracledb driver: `+02:00`

It looks like the driver sets the timezone to a fixed value which is the current timezone offset. 

As this is summer in Paris, I was getting correct values for summer dates, but a 1hr offset on winter dates. Took me a while to understand what was going on. I was expecting the driver to pick the same default as other tools.

I got rid of all my timezone offset issues by executing `ALTER SESSION SET TIME_ZONE='00:00'` after connecting.

**Comment by cjbj** [comment]
Comparing with SQL*Plus is a better match, and that gives the same results as node-oracledb for me

**Comment by bjouhier** [comment]
Maybe, but as a user I'm expecting _local_ time to take daylight saving time into account. Applying today's offset to all dates is not very meaningful: a meeting that I attended at 4PM in January will show up as 5PM if I look at it now, but will be back at 4PM if I look again in November, weird!

On the other hand it avoids bugs when computing diffs between dates (one in summer and one in winter).

This strengthens the argument that the date's default should be UTC rather than local because local is too brittle (if you don't enable DST it looks weird to the user, if you enable DST you take the risk of buggy computations).

**Comment by larryaubstore** [comment]
This issue should be reopen. For now, I have to execute 'ALTER SESSION SET TIME_ZONE='00:00'' before every request. IMO, it's not acceptable.

**Comment by dmcghan** [comment]
@larryaubstore Are you unable to set the `ORA_SDTZ` environment variable?

```bash
$ export ORA_SDTZ='UTC'
$ node index.js 
```

**Comment by larryaubstore** [comment]
Thank you. 

May I give you a suggestion ? It is possible to document this in the README.md ?

**Comment by dmcghan** [comment]
@larryaubstore The README.md is more of a jumping off point to other pages like INSTALL and doc.

The doc you're looking for is here: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-9163-fetching-date-and-timestamps

**Comment by cjbj** [comment]
node-oracledb 6.0 has changed the behavior of DATE and TIMEZONE types to be more standard.  I'll close this old issue; open new ones if there are new questions.
