### ISSUE TITLE
Regarding timeouts

### ISSUE THREAD

**Issue by r0drigor** [oracle/node-oracledb#1541]
1. What versions are you using?

- Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- process.platform: win32
- process.version: v16.13.1
- process.arch: x64
- oracledb.version: 5.5.0
- oracledb.clientVersion: 21.7.0.0.0

2. Describe the problem.

Several questions here regarding timeouts.
I'm running a query that has a certain execution time and I've tested with different callTimeout values.

> testing timeout of 5 seconds and execution time of 12
> error #0: Error: DPI-1080: connection was closed by ORA-3156
> #0: milliseconds elapsed = 10016

Always takes around double the time of the timeout to close the connection. Why does this happen?

> testing timeout of 5 seconds and execution time of 8
> error #0: Error: DPI-1067: call timeout of 5000 ms exceeded with ORA-3156
> #0: milliseconds elapsed = 8031

The same 5 second timeout now doesn't close the connection, but rather it calls the correct timeout at around the same time of the execution time.
Why does this happen?

> Error: DPI-1080: connection was closed by ORA-3156

I'm still getting the record inserted into the table when I get this error, and it seems like it shouldn't work this way (autoCommit = true).

3. Include a runnable Node.js script that shows the problem.

Node.js script:
```
const oracledb = require('oracledb');

async function run() {
  let pool;
  let start;
  let duration;
  let timeout = 5;
  let executionTime = 12;
  console.log(`testing timeout of ${timeout} seconds and execution time of ${executionTime}`);

  try {
    oracledb.autoCommit = true;
    pool = await oracledb.createPool({
      user: 'user',
      password: 'password',  // mypw contains the hr schema password
      connectString: '<connectionString>/TEST',
      poolMax: 1, // maximum size of the pool
      poolMin: 0, // let the pool shrink completely
      poolIncrement: 1, // only grow the pool by one connection at a time
      poolTimeout: 0  // never terminate idle connections
    });

    for (let i = 0; i < 5; i++) {
      let connection;
      try {
        connection = await pool.getConnection();
        connection.callTimeout = timeout * 1000;
        start = Date.now();
        result = await connection.execute("BEGIN DBMS_SESSION.SLEEP(${executionTime}); INSERT INTO TEST.STARWARS(MOVIE, YEAR) VALUES('Episode VI - The Return of the Jedi', '1983'); END;");
        // connection.commit();
        console.log("Result is:", result);
      } catch (err) {
        // connection.rollback();
        console.log(`error #${i}: ${err}`);
        // throw (err);
      } finally {
        duration = Date.now() - start;
        if (connection) {
          try {
            await connection.close(); // Put the connection back in the pool
          } catch (err) {
            // throw (err);
          }
        }
        console.log(`#${i}: milliseconds elapsed = ${Math.floor(duration)}`);
      }
    }

  } catch (err) {
    console.error(err.message);
  } finally {
    await pool.close();
  }
}

run();
```

SQL script:
```
CREATE SCHEMA TEST

CREATE TABLE TEST.STARWARS 
   (	"MOVIE" VARCHAR2(200 BYTE), 
	"YEAR" VARCHAR2(20 BYTE), 
	"INSERT_DATE" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 

```

**Comment by oliveirabc** [comment]
Hi, 

I'm observing the same thing with:

```
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
process.platform: linux
process.version: v18.12.1
process.arch: x64
oracledb.versionString: 5.5.0
oracledb.oracleClientVersionString: 21.8.0.0.0
```
Just a note that I'm not really sure about your test: Did you observe records being committed for all the errors or just some?
On my tests, I did observe records committed for both DPI-1080 and DPI-1067.

Also, and for comparison, I've done some java testing with the JDBC driver ojdbc8.jar with the same database and statements and:
- did not observe records committed in case of timeout
- always returns the same timeout error:
```
(72000/1013) ORA-01013: user requested cancel of current operation
ORA-06512: at "SYS.DBMS_SESSION", line 435
ORA-06512: at line 1

```

**Comment by cjbj** [comment]
> Always takes around double the time of the timeout to close the connection. Why does this happen?

From the [doc](https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#limiting-the-time-taken-to-execute-statements):

> After a timeout occurs, node-oracledb attempts to clean up the internal connection state. The cleanup is allowed to take another callTimeout milliseconds.
