### ISSUE TITLE
CQN is not working with clientInitiated true option

### ISSUE THREAD

**Issue by Shubh0817** [oracle/node-oracledb#1542]
1. What versions are you using?

Give your database version.
select * from product_component_version;
output: VERSION:19.0.0.0.0
	     VERSION_FULL:19.18.0.0.0
	     STATUS:Production
	     PRODUCT:Oracle Database 19c Enterprise Edition 

Also run node and show the output of:
    process.platform:'linux'
    process.version:'v18.12.1'
    process.arch:'x64'
    require('oracledb').versionString:'5.2.0'
    require('oracledb').oracleClientVersionString:'21.9.0.0.0'

2. Describe the problem

function callThisFun(message) {
    const printMessage = JSON.stringify(message?.tables)
    console.log(printMessage)
    logger.info(`db change info: ${printMessage}`)
}
  const options = {
        clientInitiated: true,
        callback: callThisFun,
        events: true,
        sql: `Select * from MASTER_TABLE_CRUD_DEMO`,
    }

let connection = await oracledb.getConnection(pool);
connection.subscribe(tableName, options);

I am not getting any issue while running code but when I change or alter table in DB then my callback function is not getting invoked.

**Comment by cjbj** [comment]
Try a 19c client just in case it (being the LTS version) has some additional patch from the CQN team.

Some options like grouping may not be supported by clientInitiated.

As a general rule it wouldn't hurt to update to node-oracledb 5.5.

**Comment by Shubh0817** [comment]
> Try a 19c client just in case it (being the LTS version) has some additional patch from the CQN team.
> 
> Some options like grouping may not be supported by clientInitiated.
> 
> As a general rule it wouldn't hurt to update to node-oracledb 5.5.

I have updated node-oracledb to 5.5.0 with instant client 19.18.0.0.0.

still clientInitiated field is not working.

I tried with ip and port but facing issue as [Error: ORA-24912: Listener thread failed. Listen failed.] {
  errorNum: 24912,
  offset: 0
}

Note-> My DB and App is on different server.
