### ISSUE TITLE
The new node-oracledb release with Thin mode is coming soon!

### ISSUE THREAD

**Issue by sharadraju** [oracle/node-oracledb#1550]
Hey, We are wrapping up our next release of node-oracledb and boy, have we got something exciting coming soon for you! A 1-step install, 1 MB footprint, and no Oracle Instant Client libraries needed!
Stay tuned to my blog: [https://medium.com/@sharad-chandran](https://medium.com/@sharad-chandran) for more!
Here is a sneak peek of what I tried:
![SimpleQuery2](https://user-images.githubusercontent.com/86588332/237058835-51b7aaa0-ea27-4e0d-9a68-00c0ee2120b1.png)

**Comment by sosoba** [comment]
Hello. I suggest you consider a parallel release of lightweight the thin-only package. 
Since `npm-cli` supports aliases, there is no problem with multiple variants of a common api.
```bash
npm install oracledb@npm:oracledb-thin-only
```
```js
import {getConnection} from 'oracledb';
```

**Comment by cjbj** [comment]
@sosoba thanks for the suggestion.  In the short term, you will be able to run `npm run prune all` post install to remove all the thick mode binaries, letting you use Thin mode. https://github.com/oracle/node-oracledb/blob/main/package/prunebinaries.js

**Comment by liudonghua123** [comment]
> Hello. I suggest you consider a parallel release of lightweight the thin-only package. Since `npm-cli` supports aliases, there is no problem with multiple variants of a common api.
> 
> ```shell
> npm install oracledb@npm:oracledb-thin-only
> ```
> 
> ```js
> import {getConnection} from 'oracledb';
> ```

This thin mode node-oracledb seems not publish yet.

```
D:\code\node\oracle_db_test>yarn add oracledb@npm:oracledb-thin-only
yarn add v1.22.17
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/oracledb-thin-only: Not found".
info If you think this is a bug, please open a bug report with the information provided in "D:\\code\\node\\oracle_db_test\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

D:\code\node\oracle_db_test>npm install oracledb@npm:oracledb-thin-only
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/oracledb-thin-only - Not found
npm ERR! 404
npm ERR! 404  'oracledb-thin-only@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Liu.D.H\AppData\Local\npm-cache\_logs\2023-05-10T04_57_27_136Z-debug-0.log

D:\code\node\oracle_db_test>
```

**Comment by cjbj** [comment]
@liudonghua123 the title of this announcement was 'is coming soon' !

Also the syntax you used was a suggestion by @sosoba and won't be the one to use at the time of release.

**Comment by jimji1005** [comment]
amazing! finally going to be able to ditch my intel 'soon' 👍🏻

**Comment by yasirharis** [comment]
good job @cjbj . Finally I can remove extra steps and files when using this package.

**Comment by kuldeepsinghkarki** [comment]
Hi @sharadraju, eagerly waiting for this release as I am on Apple Silicon.
Any tentative dates for the same please as it will help me to schedule my dev plans.

**Comment by liudonghua123** [comment]
any news about this feature? 😄

**Comment by cjbj** [comment]
Node-oracledb 6.0 is here ! See https://github.com/oracle/node-oracledb/issues/1552
