### ISSUE TITLE
Support Native Network Encryption in thin mode

### ISSUE THREAD

**Issue by jvisker** [oracle/node-oracledb#1557]
1. Describe your new request in detail

It would be great if we could use native encryption with the thin client.

2. Give supporting information about tools and operating systems.  Give relevant product version numbers

N/A

Similar to this issue for the python oracle client: https://github.com/oracle/python-oracledb/issues/94

**Comment by cjbj** [comment]
For better or worse, the same response holds as for python-oracledb: The current Oracle plan is to focus on TLS. This is out of our hands.

**Comment by cjbj** [comment]
Spoke to the powers-that-be againt.  We won't be supporting NNE in Thin mode.  The solutions are to use TLS or Thick mode.  Sorry!
