### ISSUE TITLE
Do I need to set the pool size and `UV_THREADPOOL_SIZE` in Thin mode?

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#1562]
I have another question about Thin mode. Previously, I was providing both `DB_ORACLE_POOL_SIZE` and `UV_THREADPOOL_SIZE` in order to maximize the connections. My understanding is Instant Client would hold a thread until a request finished.

Does it mean, I no longer need to set both `DB_ORACLE_POOL_SIZE` and `UV_THREADPOOL_SIZE` in Thin mode, and there are just normal (TCP?) requests that will be handled by libuv directly?

_Originally posted by @jameschenjav in https://github.com/oracle/node-oracledb/issues/1554#issuecomment-1567854336_

**Comment by jameschenjav** [comment]
Thanks. That will simplify my CLI app a lot, at least I don't need to worry about setting env vars.

I use `DB_ORACLE_POOL_SIZE` as `poolMax` for my CLI tool, and for some reason I thought that's something like `ORA_SDTZ` in my .env file. btw, I assume `ORA_SDTZ` is not being used in Thin mode as well?

I haven't tried running node http server in cluster mode. Not sure how is Oracle connection pool working with `fork` in Thick mode? I think the Thin mode is pretty straightforward on the other hand.

**Comment by sharadraju** [comment]
ORA_SDTZ is an optional environment variable used to set the session time zone for the environment where your app is run. It is supported both in Thin and Thick modes.
