### ISSUE TITLE
Upgrade to 6.0 - Query Processing Issue

### ISSUE THREAD

**Issue by slewis30328** [oracle/node-oracledb#1566]
Recently upgraded to 6 from 5.5 and had an issue with SELECT processing for a query that returns 1,500 rows.  Query has approx 30 columns in select and no joins - columns just contain NUMBER and VARCHAR2 types. The query does have an IN clause and 3 (where/and) conditions.  Query returns in 1.5 seconds in TOAD client. Inside app, query would just hang - eventually web server thread would drop and call would terminate.  I read some other posts about issues with 6 and tried setting fetchArraySize.  Initially, that param was not set.  I set it to 5, restarted node and re-ran the query in app - result came back in sub-second.  Concerned about the impact of this and all downstream effects, I removed the param and rolled back to 5.5.0 and everything was functioning normal again. Before rolling back, I also played with memory allocated on nodejs server and that did not have an impact.  I work on a very large - mission critical app - and the DB/Oracle layer plays a major part in every aspect.  I don't have the cycles to disect what's going on with this. I would think this would be enough info for you all to figure this out. I have been using this driver for a long time and never had any issues. 

oracledb: Upgraded to 6.0.0 from 5.5.0
Oracle: 19.14.0.0.0
Node: 17.4.0
OS: Windows

**Comment by cjbj** [comment]
@slewis30328 is this Thin or Thick mode?  ie. do you call `initOracleClient()` (to enable Thick mode which uses Instant Client libraries)?

**Comment by slewis30328** [comment]
I didn't make any modifications to code after I upgraded - never specified thick or thin and I don't call initOracleClient(). Based on the way the docs read, I would be automatically in thin after upgrade. Sounds like if I want to use 6, I need to call initOracleClient() - so thick will be used. I will try this out and let you know.  Thanks for quick response.

**Comment by cjbj** [comment]
> Sounds like if I want to use 6, I need to call initOracleClient()

In the short term, that should get you going.  But once we can reproduce the issue and fix it, then you should be fine to go back to Thin mode.  Note that Thin mode doesn't support some of Oracle's high availability features like Application Continuity and Transparent Application Continuity. Depending on your definition of 'mission critical', and whether you are using these features, you may still want to keep running in Thick mode.

**Comment by anthony-tuininga** [comment]
@slewis30328, please try this patch. Thanks to @sudarshan12s, we were able to replicate the issue and resolve it:

```diff
diff --git a/lib/thin/protocol/messages/withData.js b/lib/thin/protocol/messages/withData.js
index 72302b77..b1af419b 100644
--- a/lib/thin/protocol/messages/withData.js
+++ b/lib/thin/protocol/messages/withData.js
@@ -582,7 +582,7 @@ class MessageWithData extends Message {
   }
 
   getBitVector(buf, numBytes) {
-    this.bitVector = buf.readBytes(numBytes);
+    this.bitVector = Buffer.from(buf.readBytes(numBytes));
   }
 
   processBindParams(buf, params) {
```

**Comment by sharadraju** [comment]
The patch in `lib/thin/protocol/messages/withData.js` for this issue is now available, as indicated by the link above. To apply this patch, simply copy this file to your lib folder and replace the older version.
This will be incorporated in the 6.0.2 release.

**Comment by slewis30328** [comment]
I installed 6.0.1, applied the patch and it resolved the issue.  Thanks for your help and quick response.
