### ISSUE TITLE
Untracked config file for tests (minor)

### ISSUE THREAD

**Issue by bjouhier** [oracle/node-oracledb#157]
Would be nice to have the test connection parameters out of source control. 

One way it to add `test/dbConfig.js` to `.gitignore` and  introduce a `test/dbConfig-template.js` that `npm install` will copy to `test/dbConfig.js`.

**Comment by cjbj** [comment]
@bjouhier the next drop will dereference environment variables like this:

module.exports = {
  user          : process.env.NODE_ORACLEDB_USER || "hr",
  password      : process.env.NODE_ORACLEDB_PASSWORD || "welcome",
  connectString : process.env.NODE_ORACLEDB_CONNECTIONSTRING || "localhost/orcl",
  externalAuth  : process.env.NODE_ORACLEDB_EXTERNALAUTH ? true : false
};

I think this is less error prone, and perhaps more useful for automated testing?

**Comment by cjbj** [comment]
PS arguments for/against using *_CONNECTIONSTRING instead of *_CONNECTSTRING are welcome.  (I'm hoping to have connectionString as an alias of connectString one day, but ....)

**Comment by bjouhier** [comment]
I'm using the other technique because our app config has lots of parameters but the `process.env` trick will be perfect.

**Comment by cjbj** [comment]
@bjouhier I can also easily add test/dbConfig-template.js to .gitgnore.  Let me know.

**Comment by cjbj** [comment]
@bjouhier do you want a change, or can I close this?

**Comment by bjouhier** [comment]
Let's keep it simple. process.env is enough. I'm closing
