### ISSUE TITLE
NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode

### ISSUE THREAD

**Issue by venkateshkolisetty-ctl** [oracle/node-oracledb#1584]
1. What versions are you using?

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

process.platform: `win32`
process.version: ` v18.16.0`
process.arch: `x64`
require('oracledb').versionString: `6.0.2`
require('oracledb').oracleClientVersionString:
```
Uncaught:
Error: NJS-089: getting the Oracle Client version is not supported by node-oracledb in Thin mode
    at throwErr (~\node_modules\oracledb\lib\errors.js:591:10)
    at Object.throwNotImplemented (~\node_modules\oracledb\lib\errors.js:600:3)
    at get oracleClientVersionString [as oracleClientVersionString] (~\node_modules\oracledb\lib\oracledb.js:1064:14) {
  code: 'NJS-089'
```

2. Is it an error or a hang or a crash?

`Error`

3. What error(s) or behavior you are seeing?

```
Process exited with code 1
Uncaught Error Error: NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode
    at throwErr (~\node_modules\oracledb\lib\errors.js:591:10)
    at encode (~\node_modules\oracledb\lib\thin\protocol\messages\auth.js:208:20)
    at _encodeMessage (~\node_modules\oracledb\lib\thin\protocol\protocol.js:105:20)
    at _processMessage (~\node_modules\oracledb\lib\thin\protocol\protocol.js:146:18)
    at connect (~\node_modules\oracledb\lib\thin\connection.js:547:28)
    at processTicksAndRejections (internal/process/task_queues:95:5)
```

4. Include a runnable Node.js script that shows the problem.

```
import * as oracledb from 'oracledb';
oracledb.createPool({
                user: 'username'
                , password: 'password'
                , connectString: 'host:port/sid'
            }).then((pool) => {
                resolve(pool);
            }).catch((err) => {
                reject(err);
            });
```

**Comment by cjbj** [comment]
The first one, NJS-089 is obvious: don't call that function in Thin mode.  Remove the call, or change to [Thick mode](https://node-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enabling-node-oracledb-thick-mode).

The second one, NJS-116, is answered in https://stackoverflow.com/a/76436179/4799035

**Comment by venkateshkolisetty-ctl** [comment]
I am trying to connect to `Oracle 12.2.0.1.0` and the verified that the parameter `sec_case_sensitive_logon` is set to `true`.
Even though the configuration is supported by the Thin mode, I am getting erro.

**Comment by cjbj** [comment]
Regenerate your password as per the steps on SO.

**Comment by venkateshkolisetty-ctl** [comment]
I tried regenerating the password but I am getting same error.
I also tried to connecting 3 different databases having same configuration and I see same error.

**Comment by sosoba** [comment]
Try to run a fresh database via docker compose:
```yaml
services:
  XEPDB1:
    image:  container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - '1521:1521'
    environment:
      ORACLE_PWD: 'oracle'
```
and connect as:
```js
await oracledb.getConnection({
  user: 'PDBADMIN',
  password: 'oracle',
  connectString:'localhost/XEPDB1',
});
```

**Comment by sharadraju** [comment]
Hi @venkateshkolisetty-ctl, It seems that the user is using a less secure 10G password verifier for some reason.
Can you run the following query:
```
SELECT USERNAME FROM DBA_USERS WHERE ( PASSWORD_VERSIONS = '10G 'OR PASSWORD_VERSIONS = '10G HTTP ')
AND USERNAME <> 'ANONYMOUS';
```
You might want to check the following documentation to upgrade your password verifier - [Resetting password verifiers](https://docs.oracle.com/en/database/oracle/oracle-database/21/spuss/finding-and-resetting-user-passwords-10g-password-version.html#GUID-D7B09DFE-F55D-449A-8F8A-174D89936304)

**Comment by sharadraju** [comment]
Node-oracledb's Thin mode supports 11G and higher password verifiers. 
To reset your password verifier, please follow the steps listed here - [Resetting Oracle Database password verifiers](https://docs.oracle.com/en/database/oracle/oracle-database/21/spuss/finding-and-resetting-user-passwords-10g-password-version.html#GUID-D7B09DFE-F55D-449A-8F8A-174D89936304).

**Comment by venkateshkolisetty-ctl** [comment]
Thank you

**Comment by emonsalves** [comment]
Hellou how resolve this i have the same problem

**Comment by diegomansua** [comment]
@sharadraju Hello, I'm getting the same error `Error: NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode` and:

- `sec_case_sensitive_logon` is true
- `password_versions` for the user is `10G 11G 12C`

I would've thought that having `11G and 12C` on top of `10G` would make it possible to connect, but it doesn't seem to be the case. Is it that `password_versions` should _not_ have `10G` at all?

Thank you.

**Comment by sharadraju** [comment]
@diegomansua Yes, the password_versions should not have 10G for the users as it is less secure and will be the default password verifier. As indicated in this link  - [Resetting Oracle Database password verifiers](https://docs.oracle.com/en/database/oracle/oracle-database/21/spuss/finding-and-resetting-user-passwords-10g-password-version.html#GUID-D7B09DFE-F55D-449A-8F8A-174D89936304), the recommendation is to remove 10G from password-versions completely.

**Comment by emonsalves** [comment]
thx a lot! i can fix it!
