### ISSUE TITLE
Please make autocommit variable assignable and changable in connection.

### ISSUE THREAD

**Issue by gintsgints** [oracle/node-oracledb#159]
Documentation said that AutoCommit is OracleDB property and it cannot be changed for old connections.

Would be nice if this variable would be stored in connection object and therefore changed there.

**Comment by cjbj** [comment]
Currently it can be changed after connecting but I wouldn't recommend it since this will change all connections and, in general, be hard to debug. You should use the execute() option setting https://github.com/oracle/node-oracledb/blob/master/doc/api.md#executeoptions for each execute.

Tell us more about your app and how you are connecting and updating the database(s).

**Comment by gintsgints** [comment]
I have work on progress at sequelize project "oracle dialect" (I have fork there), so all code is aiviable there.

https://github.com/gintsgints/sequelize

All connection stuff for oracle is there - https://github.com/gintsgints/sequelize/tree/master/lib/dialects/oracle

I already considered implement that using execute. Sounds like this is way to go.

**Comment by cjbj** [comment]
@gintsgints It's great to see sequelize support for node-oracledb happening.  Are you planning on submitting a pull request upstream to the main project? 

Using the execute() option will definitely avoid any unwanted side effects.

**Comment by gintsgints** [comment]
yes it is in my plans.

**Comment by cjbj** [comment]
@gintsgints Excellent.  Let us know the progress.

**Comment by gintsgints** [comment]
Have two showstopers now. One is TIMESTAMP column other is autogenerated ID's.
For now working around with triggers and sequence. But I do not like that way.

**Comment by dmcghan** [comment]
@gintsgints What version of the database are you using? 12c introduced identity columns which solve the need to create triggers and sequences. Here's a good article on the topic:
https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1

**Comment by gintsgints** [comment]
@dmcghan yes... I tought about identity columns in 12c. But I would like to support older databases too.

**Comment by cjbj** [comment]
@gintsgints can you conditionally swap between IDENTITY columns and triggers/sequences?  We have an open task to add a node-oracledb method that gives you the DB version; this would help you choose the option to use.

Do you need a pure TIMESTAMP? Can you use TIMESTAMP WITH LOCAL TIME ZONE for the moment? Or  work around it with a PL/SQL OUT bind fetched as a string:

```
var sql = "BEGIN SELECT systimestamp into :bv from dual; END;";
var binds = { bv: { dir: oracledb.BIND_OUT, type: oracledb.STRING } };
```

**Comment by gintsgints** [comment]
Actualy sequelize already using query to get oracle version.
But yes... it's done that way that you can with little modification check version and use IDENTITY instead - https://github.com/gintsgints/sequelize/commit/cacc0f59a10377d6154944afcae9d26242bf81f9

I will try to use TIMESTAMP WITH LOCAL TIME ZONE and let you know how it goes.

**Comment by gintsgints** [comment]
TIMESTAMP workaround works with local time zone. TY.

Tough I have more errors to fix myself now :)
