### ISSUE TITLE
Missing precision and scale are defaulted to incorrect values

### ISSUE THREAD

**Issue by josephzidell** [oracle/node-oracledb#1590]
Thank you for providing this wonderful NPM package!

I have discovered a bug when a `NUMBER` data type that uses Oracle's defaults, are different than what the metaData defaults them to.

1. What versions are you using?
6.0.3 (latest)

I'm using Oracle 19c (please note this cannot be changed)

```txt
process.platform: 'darwin',
process.version: 'v18.15.0',
process.arch: 'x64',
oracledb.versionString: '6.0.3'
oracledb.oracleClientVersionString gave an error:
`NJS-089: getting the Oracle Client version is not supported by node-oracledb in Thin mode`
```

2. Is it an error or a hang or a crash? This is an error

3. What error(s) or behavior you are seeing?

I ran the following:

```ts
const connection = await oracledb.getConnection({
	user: '...',
	password: '...',
	connectString: '...',
});

const result = await connection.execute(
	'SELECT * FROM <table_name> FETCH NEXT 1 ROWS ONLY',
	[],
	{ outFormat: oracledb.OUT_FORMAT_OBJECT },
);

await connection.close();

console.log(result.metaData);
```

Observed behavior:
- When a `NUMBER` column's data type has a precision and scale, `metaData` sets them correctly.
- However, when a `NUMBER` column's data type does not specify them, and indeed both precision and scale are optional, the metaData defaults them to values different than the Oracle Documentation says they actually do.

Data Type: "NUMBER" (without specifying precision and scale)

Observed results:
```
{
  name: '...',
  dbType: [DbType DB_TYPE_NUMBER],
  nullable: false,
  precision: 0, // <-- Oracle defaults this to 38
  scale: -127,  // <-- Oracle defaults this to 0
  dbTypeName: 'NUMBER',
  fetchType: [DbType DB_TYPE_NUMBER],
  converter: [Function: converter]
}
```

According to [the documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html), the following are true:
1. The data type is defined as `NUMBER [ (p [, s]) ]`
2. The precision p can range from 1 to 38.
    <img width="833" alt="image" src="https://github.com/oracle/node-oracledb/assets/1812443/69d42f64-6d63-4d2e-8376-189c10274295">
3. `NUMBER(p)`: This represents a fixed-point number with precision p and scale 0 and is equivalent to `NUMBER(p,0)`.
4. `NUMBER`: The absence of precision and scale designators specifies the maximum range and precision for an Oracle number.
    <img width="833" alt="image" src="https://github.com/oracle/node-oracledb/assets/1812443/07924c83-6979-4b86-8a3d-3adb797e8279">

5. Include a runnable Node.js script that shows the problem.

<details>
  <summary>SQL:</summary>

  ```sql
  CREATE TABLE "FOO"."TABLE1" 
  (	"COLUMN1" NUMBER
  ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  TABLESPACE "FOO_DEFAULT_TAB" ;
  ```
</details>

<details>
  <summary>Node.js script:</summary>

  ```ts
  import oracledb from 'oracledb';
  
  (async () => {
  	const connection = await oracledb.getConnection({
  		user: '...',
  		password: '...',
  		connectString: '...',
  	});
  
  	const result = await connection.execute(
  		'SELECT * FROM TABLE1 FETCH NEXT 1 ROWS ONLY',
  		[],
  		{ outFormat: oracledb.OUT_FORMAT_OBJECT },
  	);
  
  	await connection.close();
  
  	console.log(result.metaData);
  })();
  ```
</details>

**Comment by cjbj** [comment]
I understand the confusion. But the node-oracledb values are actually derived from the Oracle Call Interface behavior. See for example OCI_ATTR_PRECISION and OCI_ATTR_SCALE in "Table 8-13 Attributes of Columns of Tables or Views" in the [OCI Doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/describing-schema-metadata.html#GUID-B4EE393C-FE7F-4BA5-91A4-7CF6FC171C46).

For node-oracledb check the description of `metaData` in the [`connection.execute()` doc](https://node-oracledb.readthedocs.io/en/latest/api_manual/connection.html#id8) which says the same:

> For numeric columns: when precision is 0, then the column is simply a NUMBER. If precision is nonzero and scale is -127, then the column is a FLOAT. Otherwise, it is a NUMBER(precision, scale).

In your example, the precision is 0 so you have a NUMBER.

**Comment by cjbj** [comment]
@josephzidell it's a different API with different semantics.
