### ISSUE TITLE
Node-oracledb 6.1.0 is now available!

### ISSUE THREAD

**Issue by sharadraju** [oracle/node-oracledb#1599]
node-oracledb v6.1.0 is available. See the [release announcement](https://medium.com/@sharad-chandran/node-oracledb-6-1-for-oracle-db-brings-in-enhanced-advanced-queuing-support-and-more-afa4f373b107) and [CHANGELOG](https://node-oracledb.readthedocs.io/en/latest/release_notes.html) for details.
This release contains AQ enhancements, new attributes and bug fixes for the previous 6.0.x releases, including the patches provided for the issues raised by our users. Thank you for reporting the issues promptly!

Pre-built binaries are available for Node.js 14.6 or later.

Windows 64-bit (x64) (built with VS 2017)
macOS 64-bit (Intel x64)
Linux 64-bit (x86-64) (built on Oracle Linux 7)
Linux ARM 64-bit

For other environments, refer to [INSTALL](https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html) on building from source code.

**Comment by tgillus** [comment]
@sharadraju Thank you for the support that you all provide for this library. Are there plans in the near future to update the TypeScript type definitions to reflect version 6.1.0? The latest type definitions seem to define types for version 5.3.

**Comment by cjbj** [comment]
@tgillus our friend @dannyb648 is working on updates.

**Comment by tgillus** [comment]
@cjbj Thank you for the update.

**Comment by tgillus** [comment]
@sharadraju Thanks so much!
