### ISSUE TITLE
rowsAffected return property issue

### ISSUE THREAD

**Issue by bchr02** [oracle/node-oracledb#16]
I have the below code which is structured in a way that allows the session to be logged into our ERP vendor's schema. Perhaps there is a better way to do this (if anyone has suggestions, I am all ears) but for now this is working. The top section is for authenticating the session and the bottom is for the DML operation. When running this, the result does not populate the rowsAffected column. I can only assume it's because of the way it's structured. Is there any way I can use sql%rowcount to bind it to rowsAffected so I don't have to use a seperate outBind?

````sql
declare
	C DIA_RL_PKG.CURSOR_TYPE;
	V_PWD VARCHAR2(100) := NULL;
	SYSUR NUMBER;
	i number;
begin

	begin
		/* ... ERP vendor session authentication code */
		OPEN C FOR SELECT PWD, SYSUR_AUTO_KEY FROM SYS_USERS WHERE USER_NAME = :username;
		FETCH C INTO V_PWD , SYSUR;
		CLOSE C;
		C := qc_sc_pkg.validate_password(:username, V_PWD);
		CLOSE C;
	end;

	begin
		update mytable set mycolumn = 1 where mycolumn = :mycolumn;
		i := sql%rowcount; // can I populate rowsAffected property this was?
	end;
end;
````

**Comment by bchr02** [comment]
I just use an out Bind for now like this:
````sql
:rowsAffected := sql%rowcount;
````
So instead of getting this result:
````javascript
{ rowsAffected: 1,
  outBinds: { },
  rows: undefined }
````
I get this:
````javascript
{ rowsAffected: undefined,
  outBinds: { rowsAffected: 1 },
  rows: undefined }
````

not a big deal. But it would be easier to not have to define the out bind both in javascript and in sql.

**Comment by cjbj** [comment]
I don't see a feasible, automatic way to do this kind of mapping.  For one thing, the whole PL/SQL engine would need changes. Your solution with an OUT bind is good.

If you are doing your own authentication, setting the client_id might be something to consider.
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propconnclientid

**Comment by bchr02** [comment]
@cjbj thanks for the reply. I will take a look at setting the client_id, as it sounds like an interesting solution that would allow me to make use of pooled connections with this type of authentication.
