### ISSUE TITLE
Oracle net connect error

### ISSUE THREAD

**Issue by danielsrod** [oracle/node-oracledb#1600]
1. What versions are you using?
6.1.0

3. Is it an error or a hang or a crash?
crash

4. What error(s) or behavior you are seeing?
error: Failed to connect
      at connect (node:net:222:18)
      at /home/danielsrod/projects/personal/bun-databases/node_modules/oracledb/lib/thin/sqlnet/ntTcp.js:181:22

5. Include a runnable Node.js script that shows the problem.
```
import oracledb, { 
    BindParameters, 
    ExecuteOptions, 
    BIND_IN, 
    STRING, 
    NUMBER, 
    PoolAttributes, 
    OUT_FORMAT_OBJECT, 
    BIND_OUT, 
    Pool, 
    Connection,
    Result,
    createPool,
    getConnection,
} from 'oracledb';

const options: PoolAttributes = {
    user: '',
    password: '',
    connectionString: ``,
};

const connection: Pool = await createPool(options);
const db: Connection = await getConnection(options);

const sql: string = `
    
`;

const binds: BindParameters = {
    
}

const execOptions: ExecuteOptions = {
    autoCommit: true,
    outFormat: OUT_FORMAT_OBJECT,
};

const result: Result<unknown> = await db.execute(sql, binds, execOptions);
console.log(result.rows);
process.exit(0);

```

**Comment by danielsrod** [comment]
error is in net.connect function

in file: node_modules/oracledb/lib/thin/sqlnet/ntTcp.js
line: 181

the connection string is not parsing the port, and need to be a number, not a string
a string being used in net.connect(port, address, cb), port must be a integer

just put a Number in port [Number(port)] and looks fine.

**Comment by sharadraju** [comment]
Is this a BUN script?
