### ISSUE TITLE
Switching to CDB$ROOT in thin mode throws error

### ISSUE THREAD

**Issue by ovaris** [oracle/node-oracledb#1607]
1. What versions are you using?
Oracle Enterprise 19.19.0.0 (arm)

> process.platform
'darwin'
> process.version
'v16.20.2'
>     process.arch
'arm64'

Node.js v16.20.2 with "oracledb": "6.1.0",

2. Is it an error or a hang or a crash?
Error

4. What error(s) or behavior you are seeing?

```
Transaction: 3231519232414744, 3 ms, ROLLBACK, error: ORA-01435: user does not exist\nHelp: https://docs.oracle.com/error-help/db/ora-01435/
```

I'm trying to add supplemental data (for undo purposes) with latest version of node oracle library (6.1.0) by executing following SQL's:
```sql
    await execute('alter session set container=CDB$ROOT')
    await execute('ALTER DATABASE ADD SUPPLEMENTAL LOG DATA')
    await execute('alter session set container=XE')
```
but trying to switch to root container throws error "ORA-01435: user does not exist"

This worked fine previously with driver version 5.2.0, which of course runs in thick mode etc.

Any ideas?

**Comment by sharadraju** [comment]
Thank you for using node-oracledb's latest version.
one quick question is: 
- Is the user same for both the PDB and CDB$ROOT?

**Comment by ovaris** [comment]
> Thank you for using node-oracledb's latest version. one quick question is:
> 
> * Is the user same for both the PDB and CDB$ROOT?

Not sure if understand your question correctly, do you mean user we are using to connect to the DB, if so it's the same

**Comment by ovaris** [comment]
Hi, thanks. I've now confirmed that error is only thrown in Thin mode. We are using default SYSTEM user. So maybe there's something going on with Thin mode and character encoding ($ sign?).

**Comment by sharadraju** [comment]
Thanks @ovaris. We will look into this.

**Comment by ovaris** [comment]
Okay, it seems that `connection.currentSchema = 'XXX'` is breaking this so if I set currentSchema into `SYSTEM` it works also in thin mode.

```javascript
const oracledb = require('oracledb')
// oracledb.initOracleClient()
console.log('oracledb version: ' + oracledb.versionString)
console.log('oracledb thin mode: ' + oracledb.thin)
if (!oracledb.thin) {
  console.log('oracle client version: ' + oracledb.oracleClientVersionString)
}

executeSql().then(() => console.log('Done'))

async function executeSql() {
  let pool = null
  let connection = null
  try {
    pool = await oracledb.createPool({
      user: 'SYSTEM',
      password: 'oracle',
      connectString: 'local.oracle.fi:1521/xe',
    })

    connection = await pool.getConnection()
    connection.currentSchema = 'NNN' // <--- Causes error!
    await connection.execute('alter session set container=CDB$ROOT')
    await connection.execute('ALTER DATABASE ADD SUPPLEMENTAL LOG DATA')
    await connection.execute('ALTER DATABASE DROP SUPPLEMENTAL LOG DATA')
    await connection.execute('alter session set container=XE')
    await connection.commit()
  } catch (e) {
    console.log(e)
  } finally {
    if (connection) {
      await connection.close()
    }
    if (pool) {
      await pool.close(10)
    }
  }
}
```

**Comment by sharadraju** [comment]
Thanks @ovaris. We will look into it.

**Comment by sudarshan12s** [comment]
@ovaris. sorry for delay. I verified on 5.2 and 5.5 with instant client 19.8 , the error `ORA-01435` is seen with non existing user like 'NNN'. 
The current line below is just a local assignment and the actual schema change is sent to the server in next round trip, i.e  in     `await connection.execute('alter session set container=CDB$ROOT')` call which is rejected with the error, `ORA-01435`  from server , as the schema existence is first verified.. This is expected scenario.. 

`connection.currentSchema = 'NNN'`

**Comment by sharadraju** [comment]
@ovaris as indicated by @sudarshan12s in the comment above, Can you let us know the instant client version that you used with node-oracledb 5.2, where this code worked?

**Comment by ovaris** [comment]
@sharadraju I'm sorry for the delay. Unfortunately I dont' have that information available anymore because instant client was installed with brew on Mac OS on my previous computer. Current version on this computer is `19.8.0.0.0dbru` but I can't verify if that error still exists.

**Comment by sharadraju** [comment]
No problem, @ovaris.
Can you run the sample test case that you provided [here](https://github.com/oracle/node-oracledb/issues/1607#issuecomment-1750095086) with your latest Oracle Client version (19.8.0.0.0dbru) if possible?

If not, I will close this issue for now and then you can re-open the issue if required.

**Comment by ovaris** [comment]
@sharadraju Yes, I can verify, error still exists:
```bash
brew list instantclient-basic
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#################################################################################################################################################################################### 100.0%
/opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/libnnz19.dylib
/opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/libociei.dylib
/opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/libocijdbc19.dylib
/opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/liboramysql19.dylib
/opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/ (13 other files)

➜  sqlplus --version

SQL*Plus: Release 19.0.0.0.0 - Production
Version 19.8.0.0.0


➜  node test.js                 
oracledb version: 6.2.0
oracledb thin mode: true
Error: ORA-01435: user does not exist
Help: https://docs.oracle.com/error-help/db/ora-01435/
    at Protocol._processMessage (/xxx/node_modules/oracledb/lib/thin/protocol/protocol.js:172:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ThinConnectionImpl._execute (/xxx/node_modules/oracledb/lib/thin/connection.js:195:7)
    at async ThinConnectionImpl.execute (/xxx/node_modules/oracledb/lib/thin/connection.js:927:14)
    at async Connection.execute (/xxx/node_modules/oracledb/lib/connection.js:861:16)
    at async Connection.<anonymous> (/xxx/node_modules/oracledb/lib/util.js:165:14)
    at async executeSql (/xxx/test.js:23:5) {
  offset: 0,
  errorNum: 1435,
  code: 'ORA-01435'
}
Done
```

**Comment by sudarshan12s** [comment]
> @sharadraju Yes, I can verify, error still exists:
> 
> ```shell
> brew list instantclient-basic
> ==> Downloading https://formulae.brew.sh/api/cask.jws.json
> #################################################################################################################################################################################### 100.0%
> /opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/libnnz19.dylib
> /opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/libociei.dylib
> /opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/libocijdbc19.dylib
> /opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/liboramysql19.dylib
> /opt/homebrew/Cellar/instantclient-basic/19.8.0.0.0dbru/lib/ (13 other files)
> 
> ➜  sqlplus --version
> 
> SQL*Plus: Release 19.0.0.0.0 - Production
> Version 19.8.0.0.0
> 
> 
> ➜  node test.js                 
> oracledb version: 6.2.0
> oracledb thin mode: true
> Error: ORA-01435: user does not exist
> Help: https://docs.oracle.com/error-help/db/ora-01435/
>     at Protocol._processMessage (/xxx/node_modules/oracledb/lib/thin/protocol/protocol.js:172:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ThinConnectionImpl._execute (/xxx/node_modules/oracledb/lib/thin/connection.js:195:7)
>     at async ThinConnectionImpl.execute (/xxx/node_modules/oracledb/lib/thin/connection.js:927:14)
>     at async Connection.execute (/xxx/node_modules/oracledb/lib/connection.js:861:16)
>     at async Connection.<anonymous> (/xxx/node_modules/oracledb/lib/util.js:165:14)
>     at async executeSql (/xxx/test.js:23:5) {
>   offset: 0,
>   errorNum: 1435,
>   code: 'ORA-01435'
> }
> Done
> ```

@ovaris , So Does it pass with node-oracledb version: 5.2/5.5 with instant client 19.8 and not throw error ORA-1435?

**Comment by ovaris** [comment]
@sudarshan12s Sorry but it's too complicated to test it with older Thick client (on MacOS), on my behalf this issue can be closed since we figured out how to get around the issue, which is not to set the `connection.currentSchema`

**Comment by sudarshan12s** [comment]
Thanks @ovaris . I shall close it for now. This is expected behaviour for non-existing schema..
