### ISSUE TITLE
DPI-1047: Cannot locate 64-bit Oracle Client library: libclntsh.so error with Docker

### ISSUE THREAD

**Issue by saikoushik5** [oracle/node-oracledb#1617]
1. What versions are you using?

Give your database version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.17.0.0.0

    Node Version:  12.22.9
    oracledb:  "^5.0.0"

2. Is it an error or a hang or a crash? 
Error

3. What error(s) or behavior you are seeing?

![image](https://github.com/oracle/node-oracledb/assets/148313661/d480febe-bf6c-4374-ae28-d1f75f1b585d)

4. Include a runnable Node.js script that shows the problem.

```
const oracledb = require('oracledb');
const config = {
  user: 'testuser',
  password: 'testpassword',
  connectString: `(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(Host = 'testhost')(Port = 1522,
    )})))(CONNECT_DATA =(sid = 'testsid')(SERVER=dedicated)))`,
};
let conn;
try {
  conn = await oracledb.initOracleClient(config);
} catch (err) {
  console.error('Whoops!');
  console.error(err);
  process.exit(1);
} finally {
  conn.close();
}

```
Please help me resolve this error.

**Comment by sharadraju** [comment]
Please upgrade to the latest version node-oracledb 6.2 and also use Node.js 14.6 or later.
If this issue still persists, let us know, if you have configured LD_LIBRARY_PATH to point to the Oracle Instant Client libraries.

**Comment by cjbj** [comment]
@saikoushik5 see [Docker for Oracle Database Applications in Node.js and Python](https://blogs.oracle.com/opal/post/part-1-docker-for-oracle-database-applications-in-nodejs-and-python).

**Comment by saikoushik5** [comment]
> @saikoushik5 see [Docker for Oracle Database Applications in Node.js and Python](https://blogs.oracle.com/opal/post/part-1-docker-for-oracle-database-applications-in-nodejs-and-python).

@sharadraju @cjbj 
From oracledb v6.2.0, is it mandatory to use Oracle Instant client image in docker while doing the CI build? Is my understanding correct?
We have an existing old application with oracledb version v5.0.0, and we didn't install any Oracle related docker images in our CI pipeline and its working like a charm till few days back.

**Comment by cjbj** [comment]
> From oracledb v6.2.0, is it mandatory to use Oracle Instant client image in docker while doing the CI build?

You don't need to use an Oracle-owned or -created image.  But with node-oracledb 5.x you do need Oracle client libraries installed somehow.  The blog post gives tips.  

Since you now state that your setup used to work, then you will need to dig into what has changed.

From node-oracledb 6.0 the Instant Client itself is optional but does give some extra functionality.  We now call that mode 'Thick mode', see https://node-oracledb.readthedocs.io/en/latest/user_guide/appendix_a.html for the differences.

**Comment by saikoushik5** [comment]
> Please upgrade to the latest version node-oracledb 6.2 and also use Node.js 14.6 or later. If this issue still persists, let us know, if you have configured LD_LIBRARY_PATH to point to the Oracle Instant Client libraries.

@sharadraju 
I have upgraded the oracledb package to 6.2.0 and Node to v14.18.3. And now I get this error. 
Any suggestions?
![image](https://github.com/oracle/node-oracledb/assets/148313661/417a3e9a-47b4-4f76-8500-9a399571abca)

**Comment by sharadraju** [comment]
This error means that the oracledb package has not been installed locally to the Nestjs or typeorm directory that you have.

As the error indicates, please run `npm install oracledb --save` in the directory where your typeorm/nest.js app is running.

**Comment by sharadraju** [comment]
@saikoushik5 Please let us know if you were able to progress on this issue?

**Comment by saikoushik5** [comment]
> @saikoushik5 Please let us know if you were able to progress on this issue?
Yes. It's resolved. Thanks for asking

**Comment by sharadraju** [comment]
Great!
Please let us know how you solved the issue as well. It will useful for other users.

**Comment by saikoushik5** [comment]
> Great! Please let us know how you solved the issue as well. It will useful for other users.

We added this code in our Dockerfile and freeze the package version to 5.0.0 and its working.

`# Install oracleclient`
`USER root`
`RUN wget https://objs3parlow01.fr.world.socgen:4443/byo-ad016-dev-acid/oracle/oracle-instantclient-basic-21.5.0.0.0- 
  1.x86_64.rpm && \`
`  mv oracle-instantclient-basic-21.5.0.0.0-1.x86_64.rpm /tmp/ && \`
` yum -y install /tmp/oracle-instantclient*.rpm && echo /usr/lib/oracle/21.5/client64/lib > /etc/ld.so.conf.d/oracle-instantclient21.5.conf && ldconfig`

`ENV PATH=$PATH:/usr/lib/oracle/21.5/client64/bin`

`USER $user`
