### ISSUE TITLE
Node V.20.9.0

### ISSUE THREAD

**Issue by ArmSirichai99** [oracle/node-oracledb#1624]
Hola a todos, he intentado instalar el paquete oracledb en mi proyecto pero debe haber un problema con el paquete "@azure/msal-node@1.18.4" ya que no soporta el Node V20.

npm install oracledb
npm WARN config init.author.email Use `--init-author-email` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm ERR! code 87
npm ERR! path /Users/local/test/node_modules/oracledb
npm ERR! command failed
npm ERR! command sh -c node package/install.js
npm ERR! oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for darwin arm64
npm ERR! oracledb ERR! Try compiling node-oracledb source code using https://oracle.github.io/node-oracledb/INSTALL.html#github

npm ERR! A complete log of this run can be found in: /Users/local/.npm/_logs/2023-11-16T12_38_43_320Z-debug-0.log

**Comment by sudarshan12s** [comment]
Yes, the binary is not available for macOS ARM, Its only for intel. thin mode needs to be used on macOS ARM.

**Comment by cjbj** [comment]
Thick mode could be used if you install Intel Node.js binary and use Rosetta - check my blog on medium.com.

But thin mode will be easier if it has the functionality you need.

**Comment by sudarshan12s** [comment]
@ArmSirichai99 , From the logs, it looks like you are installing `node-oracledb version 5.5 `or prior to 6.2.  Can you try with latest version,  `node-oracledb 6.2`?

**Comment by sharadraju** [comment]
I am closing this as this is a known behavior with macOS ARM and node-oracledb. Please see @cjbj's comment.

> Thick mode could be used if you install Intel Node.js binary and use Rosetta - check my blog - https://medium.com/oracledevs/how-to-install-node-oracledb-5-5-and-oracle-database-on-apple-m1-m2-silicon-941fccda692f - on medium.com. But thin mode will be easier if it has the functionality you need.
