### ISSUE TITLE
Accept an object as first parameter in `execute` et al.

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oracle/node-oracledb#1629]
The popular npm module [sql-template-tag](https://www.npmjs.com/package/sql-template-tag#oracledb) supports oracledb in the latest version 5.2.0. So we can write code like this:

```js
const query = sql`select * from emp where deptno = ${deptno} order by sal desc`;
const result = session.execute(query.statement, query.values);
```

However, I'd like to make the code more compact. Similar to MySQL and PostgreSQL. Something like this:

```js
const result = session.execute(sql`select * from emp where deptno = ${deptno} order by sal desc`);
```

To make it work, the [`execute` function](https://github.com/oracle/node-oracledb/blob/39db94174bfd0c16faba17f49a5d5dc719551936/lib/connection.js#L841-L907) and related functions need to accept a JSON object as first parameter. Similar to the [implementation in MySQL for `query`](https://github.com/mysqljs/mysql/blob/dc9c152a87ec51a1f647447268917243d2eab1fd/lib/Connection.js#L180-L199). The object contains a `statement` field with positional bind parameters for oracledb. The bind values are provided in the `values` field.

IMO this would improve the usability in a backward-compatible way. Making the use of bind parameters as simple as in MySQL and PostgreSQL.

Using the sql-template-tag makes template literals containing large SQL statements easy to read, even with positional bind parameters. It's similar to static SQL in PL/SQL. This makes the use of named bind parameters in a lot of cases unnecessary.

**Comment by sharadraju** [comment]
HI @PhilippSalvisberg 
Thank you for using node-oracledb. I assume the npm module sql-template-tag supports the latest node-oracledb version of 6.2, not 5.2 :)
Thank you for suggesting this feature. Rest assured, we are evaluating this enhancement as it looks interesting!

**Comment by PhilippSalvisberg** [comment]
>I assume the npm module sql-template-tag supports the latest node-oracledb version of 6.2, not 5.2 :)

I was referring to the sql-template-tag version. ;-)

>Rest assured, we are evaluating this enhancement as it looks interesting!

Sounds promising. Thank you.

**Comment by PhilippSalvisberg** [comment]
Hi @sudarshan12s, 

If you can provide me with a compiled version that runs on macOS Silicon, I'd be happy to try it out. No problem, If this is not possible/too complicated. I will test it once 6.4 is released.

Thank you for including this change.

**Comment by sharadraju** [comment]
Hi @PhilippSalvisberg 
I have added  the latest change to the GitHub repo [here](https://github.com/oracle/node-oracledb/commit/86ce4d4ef7e4bec9eb730853959cd86d4ac6bc58).

All you need to do is the following:
- Take the latest`lib/connection.js` file and replace it in your local file.($NODE_ORACLEDB/lib/connection.js file
- Run your test case.

Since this is a JavaScript changesm there is no need for any compile.

**Comment by PhilippSalvisberg** [comment]
Works, but I had to change the signature for `execute` in `@types/oracledb/index.d.ts`

from

```js
        execute<T>(sql: string): Promise<Result<T>>;
```

to 

```js
        execute<T>(sql): Promise<Result<T>>;
```

or 

```js
        execute<T>(sql: string|unknown): Promise<Result<T>>;
```

to avoid an `Argument of type 'Sql' is not assignable to parameter of type 'string'.ts(2345)` error in my test.

**Comment by PhilippSalvisberg** [comment]
So, besides the change of the driver, this [file/line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c51ed7cf76b71412fe35d687645a723dfc269612/types/oracledb/index.d.ts#L916) needs to be patched as well when working with TypeScript.

**Comment by anthony-tuininga** [comment]
Looks to me like a new Interface needs to be added and another option for execute() added instead. Your solution works but leaves the interface undefined -- a good stopgap solution but not a good final one!

**Comment by sudarshan12s** [comment]
Thanks @PhilippSalvisberg for pointing it out. We will check on updating the types definition..

**Comment by PhilippSalvisberg** [comment]
Thanks, @sudarshan12s for taking care of the TypeScript types definitions. Very much appreciated.

**Comment by sharadraju** [comment]
@PhilippSalvisberg This is now available in node-oracledb 6.4. We have raised a PR for the TypeScript update

**Comment by sudarshan12s** [comment]
The type definition change [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68961) is here.

**Comment by lucasbraun** [comment]
By the way, this is now also part of mle-js-oracledb, i.e. for In-Database JavaScript in Oracle 23.5:
- https://blogs.oracle.com/developers/post/whats-new-in-multilingual-engine-235-support-for-sqltemplatetag
- https://oracle-samples.github.io/mle-modules/docs/mle-js-oracledb/23ai/classes/api.IConnection.html#execute.execute-2

**Comment by PhilippSalvisberg** [comment]
Perfect. Thanks @lucasbraun
