### ISSUE TITLE
What is the limit on the number of items in Array

### ISSUE THREAD

**Issue by nimah99** [oracle/node-oracledb#1639]
Supposed, there is array bind like this : 

    binds = ['Christopher', 'Hazel', 'Samuel'];
    
    For this bind example has 3 items in array.
    
    What is limit number of items in array?
    expected limit item is up to 50K or maybe 100K and more with each item has 8 digit string.
    
    then can be execute using this query : 
    sql = "select first_name, last_name from employees where first_name in (";
    for (var i=0; i < binds.length; i++) sql += (i > 0) ? ", :" + i : ":" + i;
    sql += ")"; 
    
    
    Thank you...

**Comment by sosoba** [comment]
IMHO the number of bound variables is limited to 256.

See `ODCIVARCHAR2LIST` in [doc](https://node-oracledb.readthedocs.io/en/latest/user_guide/bind.html#binding-multiple-values-to-a-sql-where-in-clause).

**Comment by nimah99** [comment]
So, i need to use ODCIVARCHAR2LIST? 

like this : 
const inlist = ['Christopher', 'Hazel', 'Samuel', ....100K more];
const binds = { bv: { type: 'SYS.ODCIVARCHAR2LIST', val: inlist } };


sql = "select first_name, last_name from employees where first_name in (:bv)"; 

?

**Comment by sosoba** [comment]
You can use any VARCHAR2 table. SYS.ODCIVarchar2List are built-in and public:.
