### ISSUE TITLE
Cursor performance question

### ISSUE THREAD

**Issue by xforceco** [oracle/node-oracledb#164]
Is there any difference with performance when I do

 "execute("select * from table ..... )"
 vs 
executing a procedure that does "select * from table ...", followed by returning the cursor (then fetch all rows using getRows() ) ?

**Comment by cjbj** [comment]
The real questions are whether the performance difference is noticeable or significant in your environment, and whether architectural concerns or business practices would cause you to prefer one or the other?

What do your benchmarks show?

Crossing the PL/SQL to SQL boundary is more expensive than not doing it.  But can you even measure it? Creating a ResultSet is more expensive than not creating one, but the sizing of maxRows will have an impact too.

**Comment by xforceco** [comment]
I am trying to replace three separate select statement with a store procedure in database that wraps those three statements, and each has a out-bind parameter to return cursors to nodejs.

I wonder whether using cursor would have significant impact on the performance. As far as I know, after getting back the cursors, I need to fetch the result from the db again, would this cause possible-slow down when compared to "native select"?

**Comment by krismohan** [comment]
How big are the resultsets? (how many rows are fetched typically by the application from each of these?)

**Comment by xforceco** [comment]
You may assume each select statement would select 200k records

**Comment by krismohan** [comment]
In that case (large number of rows) you may not see much of a performance difference. Yes, you can group the selects into a procedure and iterate over the cursors to look at the rows.
If the resultsets are small (say around 10), and you have many such resultsets, combining may show better performance, as the execute round trips are minimized and fetch round trips are the same. You can test it out.

**Comment by xforceco** [comment]
OK, thank you for the useful info.
