### ISSUE TITLE
Type error when using type ExecuteOptions after upgrade to type definitions version 6.2.1

### ISSUE THREAD

**Issue by doberkofler** [oracle/node-oracledb#1647]
1. What versions are you using?

    process.platform: darwin
    process.version: 20.11.0
    process.arch: x64
    require('oracledb').versionString: 6.3.0

2. Is it an error or a hang or a crash?

Type error

4. What error(s) or behavior you are seeing?

When using the latest TypeScript type definitions version 6.2.1.

It seems as if the typeScript type definition for `ExecuteOptions` is wrong as it specifies `type` as number instead of the new `DbType`:

```typescript
        fetchInfo?:
            | Record<
                string,
                {
                    type: number;
                }
            >
            | undefined;
```

When for example using:

```typescript
const options: oracledb.ExecuteOptions = {
		fetchInfo: {
			TEXT: {type: oracledb.STRING},
		},
	};
```
TypeScript complains that `oracledb.STRING` is not of type `number`

**Comment by sharadraju** [comment]
Hi @doberkofler This is a known issue with the latest types/node-oracledb 6.2.1. Please see the node-oracledb public slack channel:
https://node-oracledb.slack.com/archives/CCM8AMSF7/p1708716476100249
Please raise an issue in the GitHub repo:
https://github.com/DefinitelyTyped/DefinitelyTyped
