### ISSUE TITLE
Missing property fetchTypeHandler in type ExecuteOptions

### ISSUE THREAD

**Issue by doberkofler** [oracle/node-oracledb#1648]
1. What versions are you using?

   process.platform: darwin
   process.version: 20.11.0
   process.arch: x64
   require('oracledb').versionString: 6.3.0

2. Is it an error or a hang or a crash?

   Type error

3. What error(s) or behavior you are seeing?

The type definition of `ExecuteOptions` does not contain the property `fetchTypeHandler` as specified in the documentation.

**Comment by sharadraju** [comment]
Hi @doberkofler This seems to be a TypeScript issue.
As per the advice from the maintainer, please use latest types/node-oracledb 6.2.0 for a stable version.
Please raise an issue in the GitHub repo:
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by doberkofler** [comment]
Created https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/68759
