### ISSUE TITLE
Data type not supported

### ISSUE THREAD

**Issue by dhsingh** [oracle/node-oracledb#165]
Hi,

I am using this driver to get the data from siebel database.i have one column their data type is DTYPE_NOTE and i am getting error while executing the query from this driver.

"NJS-010: unsupported data type in select list".

Is there any way to resolve this issue.?

Thanks

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/147
You will need to write & call an intermediate PL/SQL block.
