### ISSUE TITLE
logStatistics() method is not correctly explained in docs

### ISSUE THREAD

**Issue by danieldiazastudillo** [oracle/node-oracledb#1655]
1. What is the link to the documentation section that needs improving?
https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#connection-pool-monitoring

2. Describe the confusion
The code snippet provided to explain logging it's calling from `poolStatistics` when it should be calling from the `pool` variable
```js
const poolstatistics = pool.getStatistics();

console.log(poolstatistics.currentQueueLength);  // print one attribute
poolstatistics.logStatistics();                  // print all statistics to the console. (WRONG!)

```

3. Suggest changes that would help
```js
const poolstatistics = pool.getStatistics();

console.log(poolstatistics.currentQueueLength);  // print one attribute
pool.logStatistics(); // print all statistics to the console. (WRONG!)

```

**Comment by sharadraju** [comment]
Thank you for using node-oracledb. 
There are two ways to log the pool statistics.
One is by using the `poolStatistics` object, which we have shown here and the other is to use the `pool` object.
The poolStatistics object is different from the pool object and it can be used to log the pool statistics.

We have also said in the very next line in [connection pool monitoring user guide](https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#connection-pool-monitoring) on how to log statistics using the pool object.

**Comment by monita1208** [comment]
Both `pool.logStatistics()` and `poolstatistics.logStatistics()` are identical with same result and can use either of them.
You have to use poolStatistics class object to access single attribute data.
