### ISSUE TITLE
createPool() could support privilege: oracledb.SYSDBA

### ISSUE THREAD

**Issue by andylwelch** [oracle/node-oracledb#1657]
1. Describe your new request in detail

Currently it is not possible to create a connection pool with privilege. Given individual connections accept this, it would be a nice to have option to streamline many requests in a pool.

2. Give supporting information about tools and operating systems.  Give relevant product version numbers

Thanks for your work, the v6 thin client is great!

**Comment by sharadraju** [comment]
Thanks for using node-oracledb Thin mode.

We will explore this!

**Comment by andylwelch** [comment]
Thanks @sharadraju . Yes I can confirm this is working now. I am no longer getting the error:
`Error: ORA-28009: connection as SYS should be as SYSDBA or SYSOPER`

I didn't realise it was meant to be supported as the automatically included types docs I was clicking through to said;
- [OracleDB.PoolAttributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6511f02c4d6645db8decac9471dbcef861954b24/types/oracledb/index.d.ts#L2613) doesn't include the `privilege` option and,
- [ConnectionAttributes.privilege](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6511f02c4d6645db8decac9471dbcef861954b24/types/oracledb/index.d.ts#L1918) explicitly stated: ` * Note only non-pooled connections can be privileged.`

I now realise these types are maintained independently.

 Thanks again for your work!
