### ISSUE TITLE
darwin arm64 doesn't support yet ? 

### ISSUE THREAD

**Issue by pyh0414** [oracle/node-oracledb#1658]
Database: 11.2
process.platform: darwin
process.version: v16.18.0
process.arch: 'arm64'
require('oracledb').versionString: 6.4.0
require('oracledb').oracleClientVersionString: 

https://github.com/oracle/node-oracledb/releases
https://www.oracle.com/database/technologies/instant-client/downloads.html

I don't see support for arm64 in the above, so maybe it's not supported yet?

**Comment by sharadraju** [comment]
@pyh0414 The latest node-oracledb version does work in ARM 64 in the Thin mode starting from version 6.0. 
Note that the Thin mode does not use Oracle Instant Client libraries. 
However for advanced Oracle Database functionalities like HA, AQ etc., Oracle Instant Client libraries are required, which are not yet released on ARM64.
Please see [node-oracledb 6.0 release announcement](https://medium.com/oracledevs/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2)  and the latest [node-oracledb documentation](https://node-oracledb.readthedocs.io/en/latest/index.html) to understand the Thin and Thick modes.

**Comment by cjbj** [comment]
There is no macOS ARM version of Oracle Client or Oracle Instant Client at the moment.  Considering running a Linux container and using the ARM Linux Instant Client.  This is what I do.

**Comment by sharadraju** [comment]
@pyh0414 
Some good news for you!
macOS ARM Instant Client is now available!
https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html
 https://www.oracle.com/database/technologies/instant-client/downloads.html
 https://www.oracle.com/database/technologies/instant-client/precompiler-downloads.html
