### ISSUE TITLE
Azure web app - DPI-1047 cannot locate a 64-bit Oracle Client Library

### ISSUE THREAD

**Issue by flash4174** [oracle/node-oracledb#1663]
Hi All,

I have an issue connecting to Oracle Database from Azure web app.

Due to NNE I have to use thick client, but on Azure I receive the eroor message mentioned in the title.

Oracledb version: 6.4.0
Node-oracledb version: 1.0.2

On Azure the web app is running on Linux server with Nodejs.

I couldn't find any working solution on the internet.

Could you please advise?

Thanks.

**Comment by sharadraju** [comment]
This is a duplicate install/configuration issue of https://github.com/oracle/node-oracledb/issues/1611. Closing this.

Also note that this is a Azure configuration issue over which we as maintainers of node-oracledb have little control over.
