### ISSUE TITLE
Apple M2: NJS-045: cannot load a node-oracledb Thick mode binary for Node.js. Please try using Thin mode.

### ISSUE THREAD

**Issue by siva90144** [oracle/node-oracledb#1666]
it's throwing error for Apple m2 chip. how to fix it?
NJS-045: cannot load a node-oracledb Thick mode binary for Node.js. Please try using Thin mode.

What versions are you using?
6.4.0
Oracle Database 19c Enterprise Edition Release Version 19.20.0.0.0

Also run Node.js and show the output of:

process.platform: Mac m2
process.version: 14.3.1
process.arch: arm64
node js version: v20.0.0

**Comment by sharadraju** [comment]
There is no Instant Client for Apple M1/M2, so we do not have Thick mode support. You can use Thin mode though.
Please let us know the script that  you are running.

Also we only support Node.js 14.6 or later. So please upgrade your Node.js version.
This has already been made clear in 
https://github.com/oracle/node-oracledb/issues/1658
You can try the following workaround detailed in this blog:
https://medium.com/oracledevs/how-to-install-node-oracledb-5-5-and-oracle-database-on-apple-m1-m2-silicon-941fccda692f

**Comment by cjbj** [comment]
Thin mode is definitely preferred, but you can use node-oracledb 6 Thick mode on M1/M2/M3 via Apple's Rosetta.  Follow the instructions in my blog [How to Install node-oracledb 5.5 and Oracle Database on Apple M1/M2 Silicon](https://medium.com/oracledevs/how-to-install-node-oracledb-5-5-and-oracle-database-on-apple-m1-m2-silicon-941fccda692f).

```
cjones@cjones-mac:/tmp$ node v.js
Run at: Thu Apr 25 2024 09:59:41 GMT+1000 (Australian Eastern Standard Time)
Node.js version: v22.0.0 (darwin x64)
Node-oracledb version: 6.4.0
Oracle Client library version: 19.16.0.0.0
Oracle Database version: 23.3.0.23.9
[ 'Full Instant Client', '19.16.0.0.0', 'node-oracledb : 6.4.0 thk' ]
```

where `v.js` is:

```
const oracledb = require('oracledb');
const dbConfig = require('./dbconfig.js');

clientOpts = { libDir: process.env.HOME + '/Downloads/instantclient_19_16' };
oracledb.initOracleClient(clientOpts);

async function doit() {
  console.log("Run at: " + new Date());
  console.log("Node.js version: " + process.version + " (" + process.platform, process.arch + ")");
  console.log("Node-oracledb version:", oracledb.versionString);
  console.log("Oracle Client library version:", oracledb.oracleClientVersionString);

  let connection = await oracledb.getConnection(dbConfig);
  console.log("Oracle Database version:", connection.oracleServerVersionString);

  const sql = `SELECT UNIQUE CLIENT_OCI_LIBRARY, CLIENT_VERSION, CLIENT_DRIVER
         FROM V$SESSION_CONNECT_INFO
         WHERE SID = sys_context('USERENV', 'SID')`;

  const result = await connection.execute(sql);
  console.dir(result.rows[0], { depth: null });

  connection.close();

}

doit();
```

**Comment by sharadraju** [comment]
@siva90144 
macOS ARM Instant Client is now available!
https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html
https://www.oracle.com/database/technologies/instant-client/downloads.html
https://www.oracle.com/database/technologies/instant-client/precompiler-downloads.html

Please run your Thick mode code with the latest macOS ARM Instant Client.
