### ISSUE TITLE
Improve error message when there is an issue in host connection

### ISSUE THREAD

**Issue by danielferayte** [oracle/node-oracledb#1673]
Hello i would like ro report an error when connecting to the database when the host is not an ip
![image](https://github.com/oracle/node-oracledb/assets/152923719/8f7f6bc2-891d-4d81-83f1-f95dc9f015f5)
i get the next message error:
![image](https://github.com/oracle/node-oracledb/assets/152923719/976d169e-cc3d-4146-a0a5-50f647f68d62)
I am not sure what is the problem, it happes whin any host
The version i am using is the oracledb 6.5 and nodejs vs20

**Comment by cjbj** [comment]
Looks like some parsing in node-oracledb has broken and you're not seeing the real error. Node-oracledb 6.0 throws (in my environment): `Error: NJS-515: error in Easy Connect connection string: could not resolve hostname: ip-10-142-132-50.aws.lnig.com`

**Comment by danielferayte** [comment]
I already try in my environment, with the version you mentioned and i get the same error, so that is the message i get when connecting directly from the database client, which is right because the host is in a private network and the local machine can't find it, but since i get a different error in the code i though maybe something was broken in the last version, so yeah there is a bug in the parsing that is not showing the real error. Thanks!

**Comment by sharadraju** [comment]
Hi @danielferayte 
Is the connect string a valid connect string?
The earlier DNS look up error in node-oracledb 6.0 (`NJS-515: error in Easy Connect connection string: could not resolve hostname: ip-10-142-132-50.aws.lnig.com`) was removed in the later versions to improve network performance.

**Comment by danielferayte** [comment]
Hi @sharadraju , yes, the connect string is a validad string i just changed a number in the ip to make an example of the error message, without exposing the real one, but even the real one wouldn't be accesible because the private network and we would get the same error.  I though because the host name is a little different it was not contemplated.

**Comment by sharadraju** [comment]
Thanks @danielferayte We will definitely look to make the error message more informative and user-friendly!

**Comment by sharadraju** [comment]
The error message is now improved in 6.7.1 release.
