### ISSUE TITLE
Upgrading from 5.5.0 to latest 6 version

### ISSUE THREAD

**Issue by karkan20** [oracle/node-oracledb#1675]
Title: Error NJS-516 when Upgrading from 5.5.0 to 6.0 or 6.5.1 in Thin Mode

Using Node.js 20 framework.

Describe the problem:

I am trying to upgrade the version of my project from 5.5.0 to 6.0.0 or 6.5.1 major versions. However, I encounter an error when creating a pool:

```
NJS-516: no configuration directory set or available to search for tnsnames.ora
```

I'm not sure what is missing. As per my understanding, `configdir` is an optional parameter for thin mode.

I have tried the examples provided in the repository, but they are more or less the same for thin mode and do not resolve the issue.

**Steps to reproduce:**

1. Upgrade the project version from 5.5.0 to 6.0.0 or 6.5.1.
2. Attempt to create a pool in thin mode

Actual behavior:

The error `NJS-516: no configuration directory set or available to search for tnsnames.ora`

Can anyone help to understand what could be missing from dbconfig?

**Comment by anthony-tuininga** [comment]
What is *in* your database configuration? The connect string is important in particular. Note that if you are upgrading from 5.5.0 you can also add a call to `oracledb.initOracleClient()` which will enable thick mode -- which should work in the same way as 5.5.0 did.

**Comment by sharadraju** [comment]
@karkan20 LDAP is not supported in node-oracledb's default Thin mode. You will have to use the [Thick mode](https://node-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enabling-node-oracledb-thick-mode).

However, the documentation is missing, which we will update. Thanks for bringing this to our attention!

**Comment by karkan20** [comment]
It is working for thin mode in 5.5.0 version. 
So if I want to upgrade to 6.0.0 I need to use thick mode?

**Comment by sharadraju** [comment]
node-oracledb 5.5 does not  have a 'Thin' mode. The thin mode was released in node-oracledb 6.0. Please see the [node-oracledb 6.0 release announcement](https://medium.com/oracledevs/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2)

**Comment by karkan20** [comment]
With 5.5.0 version, I am not calling oracledb.initOracleClient() in my database.js before creating the pool. 
Still it worked so my understanding is if I do not call initOracleclient then it's in thin mode..

**Comment by sharadraju** [comment]
@karkan20 Please let us know your platform and if you are using LDAP?

**Comment by karkan20** [comment]
Windows platform

**Comment by karkan20** [comment]
Ok so what I understand is before 6.0 version if we don't call specifically initOracleclient and if there is client library available in the oracle home path then it will do the connection. 

But post 6.0 release as thin mode being default mode, we have to specifically mention initoracleclient for ldp connection to work.

**Comment by sharadraju** [comment]
> Ok so what I understand is before 6.0 version if we don't call specifically initOracleclient and if there is client library available in the oracle home path then it will do the connection.
> 
> But post 6.0 release as thin mode being default mode, we have to specifically mention initoracleclient for ldp connection to work.

Yes.

**Comment by karkan20** [comment]
Thanks for clearing out.
