### ISSUE TITLE
Next.js 14 Thin mode: Critical dependency

### ISSUE THREAD

**Issue by saphitv** [oracle/node-oracledb#1678]
1. What versions are you using?
database version: 19.0.0
platform: win32
node version: v21.4.0
arch: x64
library version: 6.5.1

2. Describe the problem
When I do a build of a nextjs application with oracledb in Thin mode I get build warnings.

```
./node_modules/oracledb/lib/oracledb.js
Dependency critical: the require function is used in such a way that dependencies cannot be extracted statically.

Track the import of the require module:
./node_modules/oracledb/lib/oracledb.js
./node_modules/oracledb/index.js
./src/actions/others.ts
./src/components/view/topbar/top-bar.tsx
./src/app/page.tsx
```

The file that is shown performs this simple import (I don't think import is the problem):
`import { BIND_OUT, CLOB, STRING} from "oracledb";`

Is there any way to resolve this warning?

**Comment by sosoba** [comment]
IMHO you should use CommonJS default import:
```js
import oracledb from 'oracledb';

const { BIND_OUT, CLOB, STRING } = oracledb;
```

**Comment by saphitv** [comment]
Hi, unfortunately I had already tried this since I originally thought it was a problem with the import. I tried again now but the problem persists

**Comment by sharadraju** [comment]
@saphitv We are not able to replicate this issue.
Can you provide a sample code that reproduces this issue.

**Comment by sharadraju** [comment]
Since Next.js uses webpack, This warning is thrown. This has already been documented here:
https://medium.com/oracledevs/bundling-node-oracledb-javascript-apps-with-webpack-597c452f71f
```
The ‘Critical dependency’ warning can be ignored. It occurs because Webpack is unable to analyze the Thick mode binary that node-oracledb optionally loads with require() so Webpack can’t see if there are any further dependencies. Since the demo isn’t using Thick mode, this warning is not an issue.

```
