### ISSUE TITLE
Node version 20 upgrade is failing with node-oracledb v6.5.1

### ISSUE THREAD

**Issue by rajive007** [oracle/node-oracledb#1682]
My node version upgrade to 20 is failing with node-oracledb v6.5.1 on Oracle Db with encryption. But it works good with oracle DB without encryption.Error received is NJS-500: connection to the Oracle Database was broken\nNJS-521

**Comment by sharadraju** [comment]
Please define what encryption means? Do you mean NNE on Oracle Database?

**Comment by rajive007** [comment]
Thanks for the quick response. Below are the request details.

Yes Encryption is NNE on oracle db.
We are upgrading from node 16  to 20 version with node-oracledb 4.2.0  to node-oracledb 6.5.1 version
The platform that the lambda is running on is Linux. We are using thick mode on code.

And also do you recommend any other version of node-oracledb which can be used as a work around for this issue.

**Comment by anthony-tuininga** [comment]
Thin mode (the default) does not support NNE currently. You have to use thick mode. node-oracledb 4.2.0 only had thick mode but node-oracledb 6.5.1 uses thin mode by default, so you have to add a call to `oracledb.initOracleClient()` before creating your first connection. Thick mode supports NNE so your connection issues should go away.

**Comment by cjbj** [comment]
@rajive007 see the doc [Enabling node-oracledb Thick Mode](https://node-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enabling-node-oracledb-thick-mode).

**Comment by rajive007** [comment]
I will try the above options and let you know in case of issue.

**Comment by sharadraju** [comment]
Closing this issue as this is NNE related.
