### ISSUE TITLE
`esbuild --bundle` no longer works with v6.6.0 as missing packages

### ISSUE THREAD

**Issue by eGust** [oracle/node-oracledb#1688]
1. What versions are you using?
6.6.0

2. Is it an error or a hang or a crash?
error when run `esbuild --bundle --platform=node`

3. What error(s) or behavior you are seeing?
```
✘ [ERROR] Could not resolve "@azure/app-configuration"

    node_modules/.pnpm/oracledb@6.6.0/node_modules/oracledb/lib/configProviders/azure.js:46:41:
      46 │     ({AppConfigurationClient } = require("@azure/app-configuration"));
         ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@azure/app-configuration" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@azure/identity"

    node_modules/.pnpm/oracledb@6.6.0/node_modules/oracledb/lib/configProviders/azure.js:47:143:
      47 │ ...ential, ChainedTokenCredential, ManagedIdentityCredential, EnvironmentCredential} = require("@azure/identity"));
         ╵                                                                                                ~~~~~~~~~~~~~~~~~

  You can mark the path "@azure/identity" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@azure/keyvault-secrets"

    node_modules/.pnpm/oracledb@6.6.0/node_modules/oracledb/lib/configProviders/azure.js:156:41:
      156 │         const { SecretClient } = require("@azure/keyvault-secrets");
          ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@azure/keyvault-secrets" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "oci-common"

    node_modules/.pnpm/oracledb@6.6.0/node_modules/oracledb/lib/configProviders/ociobject.js:56:25:
      56 │     oci.common = require('oci-common');
         ╵                          ~~~~~~~~~~~~

  You can mark the path "oci-common" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "oci-objectstorage"

    node_modules/.pnpm/oracledb@6.6.0/node_modules/oracledb/lib/configProviders/ociobject.js:57:32:
      57 │     oci.objectstorage = require('oci-objectstorage');
         ╵                                 ~~~~~~~~~~~~~~~~~~~

  You can mark the path "oci-objectstorage" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@azure/keyvault-secrets"

    node_modules/.pnpm/oracledb@6.6.0/node_modules/oracledb/lib/configProviders/ociobject.js:160:43:
      160 │           const { SecretClient } = require("@azure/keyvault-secrets");
          ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@azure/keyvault-secrets" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

6 of 8 errors shown (disable the message limit with --log-limit=0)
 ELIFECYCLE  Command failed with exit code 1.
```

4. Include a runnable Node.js script that shows the problem.
```js
// foo.mjs
import OracleDB from 'oracledb';

const main = async () => {
  const connection = await OracleDB.getConnection({
    // ...
  });
  try {
    const result = await connection.execute('SELECT 1 FROM dual');
    console.log(result.rows);
  } finally {
    await connection.close();
  }
};

main();
```

```bash
pnpm esbuild foo.mjs --bundle --platform=node --format=cjs --outfile=/dev/null
```

**Comment by eGust** [comment]
After added more dependencies, I was able to bundle it.

```diff
   "devDependencies": {
+    "@azure/app-configuration": "^1.6.1",
+    "@azure/identity": "^4.4.0",
+    "@azure/keyvault-secrets": "^4.8.0",
+    "oci-common": "^2.89.4",
+    "oci-objectstorage": "^2.89.4",
+    "oci-secrets": "^2.89.4",
}
```

However, the bundled file size significantly increased from 3.6m to 6.9m, and the packaged tgz file increased from 489k to 905k.

There is no code change.

**Comment by sharadraju** [comment]
Hi @eGust ,
Thanks for using node-oracledb.
These errors are because we have added conditional requires to external Azure and OCI packages in node-oracledb for centralized configuration support.

Please add these packages (@azure/app-configuration, @azure/identity, @azure/keyvault-secrets, oci-common, oci-objectstorage)  to the --external flag during build as indicated.

**Comment by sharadraju** [comment]
> After added more dependencies, I was able to bundle it.
> 
> ```diff
>    "devDependencies": {
> +    "@azure/app-configuration": "^1.6.1",
> +    "@azure/identity": "^4.4.0",
> +    "@azure/keyvault-secrets": "^4.8.0",
> +    "oci-common": "^2.89.4",
> +    "oci-objectstorage": "^2.89.4",
> +    "oci-secrets": "^2.89.4",
> }
> ```
> 
> However, the bundled file size significantly increased from 3.6m to 6.9m, and the packaged tgz file increased from 489k to 905k.
> 
> There is no code change. Only upgraded oracledb from 6.5.1 to 6.6.0

Please do not add them in devDependencies

**Comment by eGust** [comment]
Thanks @sharadraju 

I am able to bundle with `--external:@azure/app-configuration --external:@azure/identity --external:@azure/keyvault-secrets --external:oci-common --external:oci-objectstorage --external:oci-secrets`. The package tgz size is 494k now.

**Comment by sharadraju** [comment]
Thanks @eGust for confirming.
Closing this issue as the question is answered

**Comment by anthony-tuininga** [comment]
If those packages get added to the `optionalDependencies` key of `package.json` in the `oracledb` module, does that resolve the difficulty for you as well? We can look into doing so, if so!

**Comment by niels-k-86** [comment]
For those of you who are experiencing this same issue when using NextJS: you can set a custom Webpack config in your config. There you can mark packages as external.

In your `next.config.(m)js` file, do this:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: config => {
    /**
     * These packages need to be added as external, else Oracle DB will try to load them due to a
     * Webpack bug.
     *
     * See these two issues for more information:
     * - https://github.com/oracle/node-oracledb/issues/1688
     * - https://github.com/oracle/node-oracledb/issues/1691
     **/
    config.externals.push(
      ...[
        "@azure/app-configuration",
        "@azure/identity",
        "@azure/keyvault-secrets",
        "oci-common",
        "oci-objectstorage",
        "oci-secrets",
      ],
    )

    return config
  },
}

export default nextConfig
```

**Comment by Luk4h** [comment]
> For those of you who are experiencing this same issue when using NextJS: you can set a custom Webpack config in your config. There you can mark packages as external.
> 
> In your `next.config.(m)js` file, do this:
> 
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   webpack: config => {
>     /**
>      * These packages need to be added as external, else Oracle DB will try to load them due to a
>      * Webpack bug.
>      *
>      * See these two issues for more information:
>      * - https://github.com/oracle/node-oracledb/issues/1688
>      * - https://github.com/oracle/node-oracledb/issues/1691
>      **/
>     config.externals.push(
>       ...[
>         "@azure/app-configuration",
>         "@azure/identity",
>         "@azure/keyvault-secrets",
>         "oci-common",
>         "oci-objectstorage",
>         "oci-secrets",
>       ],
>     )
> 
>     return config
>   },
> }
> 
> export default nextConfig

Does not work anymore.

**Comment by Luk4h** [comment]
For devs using next, you should include `oracledb` on your `serverExternalPackages` on `next.config`:
```ts
const nextConfig: NextConfig = {
	/* config options here */
	serverExternalPackages: ["oracledb"],
};
```

**Comment by sharadraju** [comment]
@eGust @niels-k-86 @rodrilima A permanent fix is now available for this as we have moved all of the configuration store code to the plugins extension.
Now the bundlers should not see this issue
