### ISSUE TITLE
segmentation fault while closing connection pool to db

### ISSUE THREAD

**Issue by arvydasKezunas** [oracle/node-oracledb#1690]
1. What versions are you using?
nodejs version: v20.16.0
process.platform | linux
process.version | v20.16.0
process.arch | x64
oracle.versionString | 5.5.0 
oracle.oracleClientVersion 2113000000

2. Describe the problem
sometimes after calling and point and closing connection pool to database i`m getting segmentation fault error that crashes the application and restarts it, issue is reproducable only on dockerized container.

`oracleDB.Connection.closeConnection`

adding logs just before crash happened with last log before crashing
https://gist.github.com/arvydasKezunas/40dd947df27f40589e49d3f9a1db15b4

**Comment by sharadraju** [comment]
Hi @arvydasKezunas Please upgrade to the latest version of node-oracledb 6.6.

Starting from node-oracledb 6.0 onwards, we have the 'Thin' and 'Thick' modes. 
The Thin mode is written purely in JavaScript and does not require Oracle Client libraries to connect to Oracle Database. We also made Thin mode as the default mode in node-oracledb 6.0. 
Please see the following blogs to understand the  Thin and Thick modes in node-oracledb:

[Node-oracledb 6.0](https://medium.com/oracledevs/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2)

[How do I choose between Thin and Thick modes](https://itnext.io/how-do-i-choose-between-thin-and-thick-modes-in-node-oracledb-6-0-c516d202a71f)

If your application does not use the Oracle Database advanced features and does not require Thick mode-only features, an upgrade of node-oracledb to the latest version (6.6) should work for you.

**Comment by arvydasKezunas** [comment]
thank you for response, it worked
