### ISSUE TITLE
Error: Module not found: Can't resolve '@azure/app-configuration' 

### ISSUE THREAD

**Issue by Dongw1126** [oracle/node-oracledb#1691]
1. What versions are you using?
- Node.js version
```
Node.js: 20.16.0
arch: x64
platform: win32
```

- package version
```
next: "14.2.5"
oracledb: "^6.6.0"
```

- database version
```
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production  
Version 19.24.0.1.0
```  

2. Is it an error or a hang or a crash?  
error

3. What error(s) or behavior you are seeing?

```
Import trace for requested module:
./node_modules/oracledb/lib/configProviders/ sync ^\.\/.*$
./node_modules/oracledb/lib/oracledb.js
./node_modules/oracledb/index.js
./src/app/api/v1/test/route.js
 ⨯ ./node_modules/oracledb/lib/configProviders/azure.js:46:32
Module not found: Can't resolve '@azure/app-configuration'

https://nextjs.org/docs/messages/module-not-found
```

4. Include a runnable Node.js script that shows the problem.  
  
When I write the code below and call http://localhost:3000/api/v1/test,  
I get "Module not found: Can't resolve '@azure/app-configuration'" error.  

I haven't written any code related to azure and I'm getting an error even though I just added `require('oracledb')`.
 Please check this error.

I've also attached the minimal executable code as a zip file.
```
// app/api/v1/test/route.js

export const dynamic = 'force-dynamic'

const oracledb = require('oracledb');

export async function GET() {
    return Response.json('Hello', { status: 200 })
}
```
[test.zip](https://github.com/user-attachments/files/16633214/test.zip)

**Comment by sharadraju** [comment]
Hi @Dongw1126 Are you using any package bundlers like esbuild or webpack in your application?

**Comment by sharadraju** [comment]
Next.js seems to use webpack, which tries to load the azure modules, even if it is conditionally required. This is the same issue as https://github.com/oracle/node-oracledb/issues/1688

**Comment by Dongw1126** [comment]
> Hi @Dongw1126 Are you using any package bundlers like esbuild or webpack in your application? If yes, please see #1688

Thanks for the quick reply.
I added `"@azure/app-configuration": "^1.6.1"` as a dependency and the error doesn't occur anymore.
But wouldn't it be better to modify it so that it can run without having to install additional dependencies?

**Comment by sharadraju** [comment]
This is a webpack issue, which it does not ignore conditional requires.
I will try to see if something can be done from our end to ensure that webpack can ignore them.
See https://github.com/webpack/webpack/issues/8826 .

**Comment by Dongw1126** [comment]
> This is a webpack issue, where it does not ignore conditional requires. I will try to see if something can be done from our end to ensure that webpack can ignore them. See [webpack/webpack#8826](https://github.com/webpack/webpack/issues/8826) .

Thank you.  
If this is a duplicate issue, I think you can close it.

**Comment by sharadraju** [comment]
Closing this issue for now. We will try to find a solution on this.

**Comment by sharadraju** [comment]
@Dongw1126 Reopening this issue as I think I may found a fix to work with frameworks like Next.js that use webpack. This is similar to the fix given in #1156.
Here is how to apply the fix:
```
Unzip the attached configProviders.zip file to a new directory (D:\temp\configProviders)
Navigate to the application folder, where the node modules, including oracledb are installed (e.g., test/node_modules).
Navigate to the oracledb/lib folder.
Replace the configProviders directory in this directory with the new configProviders directory (i.e.,D:\temp\configProviders)
Remove the .next folder and rebuild the Next.js project again

```
[configProviders.zip](https://github.com/user-attachments/files/16637775/configProviders.zip)

Please try this fix and let me know.

**Comment by Dongw1126** [comment]
As you mentioned, modifying node_modules works fine. No more errors.  
However, modifying node_modules should be added to my CICD pipeline. Or I could use `patch-package`.
Anyway, both of the solutions you mentioned work fine.   
Thank you.

**Comment by sosoba** [comment]
The ideal solution would be to move the Azure-enabled code into a separate package as a oracledb plugin and optionally include it in user project.

**Comment by sharadraju** [comment]
> The ideal solution would be to move the Azure-enabled code into a separate package as a oracledb plugin and optionally include it in user project.

Thank you for the suggestion @sosoba. We will look into it.

**Comment by niels-k-86** [comment]
You can set a custom Webpack config in NextJS. There you can mark packages as external. In your `next.config.(m)js` file, do this:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: config => {
    /**
     * These packages need to be added as external, else Oracle DB will try to load them due to a
     * Webpack bug.
     *
     * See these two issues for more information:
     * - https://github.com/oracle/node-oracledb/issues/1688
     * - https://github.com/oracle/node-oracledb/issues/1691
     **/
    config.externals.push(
      ...[
        "@azure/app-configuration",
        "@azure/identity",
        "@azure/keyvault-secrets",
        "oci-common",
        "oci-objectstorage",
        "oci-secrets",
      ],
    )

    return config
  },
}

export default nextConfig
```

**Comment by sharadraju** [comment]
Closing this issue as there are workarounds and configuration changes available to solve the issue.

However we will look to actively move the config Providers related code as a plugin in the upcoming releases

**Comment by drollinger** [comment]
Thought I would mention another work around using turbopack since nextjs is mentioned in this issue and it doesn't have an externals config option.

`experimental: {
    turbo: {
      resolveAlias: {
        '@azure/app-configuration': 'data:text/javascript,export default {};',
        '@azure/identity': 'data:text/javascript,export default {};',
        '@azure/keyvault-secrets': 'data:text/javascript,export default {};',
        'oci-common': 'data:text/javascript,export default {};',
        'oci-objectstorage': 'data:text/javascript,export default {};',
        'oci-secrets': 'data:text/javascript,export default {};',
      },
    }
  }`
