### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by hertzg** [oracle/node-oracledb#17]
Selecting rows from database returns "?????" for non ASCII characters

```
var OracleDB = require( 'oracledb')

OracleDB.getConnection({
  user: '...',
  password: '...',
  connectString: '...',
}, function(err, conn) {
  conn.execute('SELECT ....', function(err, res){
    console.log('res', res)
  })
})
```
Returns ??????  (question marks) for all utf8 data (for both varchar2 and nvarchar2 columns)

**Comment by cjbj** [comment]
NLS support is our on list of things to do.  

What client & server character sets are you using?  What are your NLS settings, and what is the client locale set to?

**Comment by hertzg** [comment]
I've solved the question marks issue by setting the `NLS_LANG` environment variable before running the application. Which I think is counter-intuitive compared to other drivers (which provide a method to set character encoding at the connection level at least) or this should be mentioned in the drivers documentation, at least as a caveat (?) 

```
NLS_LANG=AMERICAN_AMERICA.UTF8 node src/main.js
```

**Comment by soyuka** [comment]
That's the way oracle works @hertzg.

**Comment by cjbj** [comment]
Node-oracledb 1.0 now always sets the Oracle client characterset to AL32UTF8.
We also created the start of an NLS section in the manual: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#nls

NCHAR/NVARCHAR support is pending.

**Comment by brunodenis** [comment]
Hi,

May you please be more specific ? I am trying to read data with accents with no success even with NLS_LANG set to "FRENCH_FRANCE.WE8MSWIN1252"
