### ISSUE TITLE
Version 6.7.0 has a relative path that doesn't start with './'

### ISSUE THREAD

**Issue by drollinger** [oracle/node-oracledb#1708]
1. What versions are you using?
Oracledb: Version 6.7.0
I'm building with next build which uses webpack
Next: Version 15.0.3

2. Is it an error or a hang or a crash?
Build crash

3. What error(s) or behavior you are seeing?
When building with webpack default configuration I get the following error.
```
./node_modules/oracledb/lib/oracledb.js:668:45
Module not found: Can't resolve 'thin/sqlnet/paramParser.js'
Did you mean './thin/sqlnet/paramParser.js'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories
```
```
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
  666 | //-----------------------------------------------------------------------------
  667 | async function getNetworkServiceNames(configDir) {
> 668 |   const { NLParamParser, tnsnamesFilePath } = require('thin/sqlnet/paramParser.js');
      |                                             ^
  669 |   const nlParamParser =  new NLParamParser;
  670 |   const filePath = tnsnamesFilePath(configDir);
  671 |   const aliasht = await nlParamParser.initializeNlpa(filePath);

```

I can add the preferRelative option in my configuration file (in my case next.config.js) and things work
```
  // Webpack needs this configuration for the oracle package
  webpack: (config) => {
    config.externals.push(
      ...[
        '@azure/app-configuration',
        '@azure/identity',
        '@azure/keyvault-secrets',
        'oci-common',
        'oci-objectstorage',
        'oci-secrets',
      ],
    )
    config.resolve.preferRelative = true
    return config
  },
  ```
  
  However, there's new upcoming turbopack integration that doesn't have this option as far as I could see and also, it would be nice if we could just have the path be correct.

4. Include a runnable Node.js script that shows the problem.
next build

Thanks for making this package! Having a thin mode node package has made the dev experience with oracledb so much better

**Comment by sharadraju** [comment]
This is a duplicate issue of #1706 and a patch is already there.
It will be fixed in 6.7.1
