### ISSUE TITLE
Unable to connect NestJS with Oracle Autonomous Database using TypeORM and Oracle Wallet (ORA-12506, NJS-511)

### ISSUE THREAD

**Issue by B0nam** [oracle/node-oracledb#1709]
I am trying to connect my NestJS application to Oracle Autonomous Database using TypeORM. I have configured everything in TypeORM, but I am encountering issues with the connection.

I set up the `app.module.ts` with the necessary connection settings, but it does not work as expected.

Here is my `app.module.ts` configuration:

```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ConfigModule } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true, envFilePath: '../../.env' }),
    TypeOrmModule.forRoot({
      type: 'oracle',
      host: 'adb.sa-saopaulo-1.oraclecloud.com',
      sid: '<ssid>_high.adb.oraclecloud.com',
      database: '<db_name>',
      username: '<username>',
      password: '<password>',
      connectString: '<database>_high',
      autoLoadEntities: true,
      synchronize: true,
      logging: true,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

In my `.env` file, I have set the `TNS_ADMIN` variable like this:

```env
// Other .env variables that are being used directly
TNS_ADMIN=../../wallet/Wallet_<database>
```

**Error:**

The error I receive when trying to connect is:

```
[Nest] 58658  - 22/11/2024, 15:42:56   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: NJS-511: connection to listener at host <ip address> port 1522 was refused. (CONNECTION_ID=...)
Cause: ORA-12506
    at Object.throwErr (...node_modules/oracledb/lib/errors.js:693:10)
    at NetworkSession.connect2 (/.../node_modules/oracledb/lib/thin/sqlnet/networkSession.js:244:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NetworkSession.connect1 (.../node_modules/oracledb/lib/thin/sqlnet/networkSession.js:320:23)
    at async NetworkSession.connect (.../node_modules/oracledb/lib/thin/sqlnet/networkSession.js:542:5)
    at async ThinConnectionImpl.connect (.../node_modules/oracledb/lib/thin/connection.js:775:5)
    at async ThinPoolImpl.bgThreadFunc (.../node_modules/oracledb/lib/thin/pool.js:455:11)
^C
```

I configured the `app.module.ts` file with the correct details for the Oracle Autonomous Database and set the `TNS_ADMIN` variable in the `.env` file to point to the Oracle Wallet directory. I expected the connection to work in the same way as it does when using Oracle SQL Developer, with SSL/TLS configuration for secure communication.

- The connection works fine using the Oracle SQL Developer client.
- I have allowed my IP address in the Oracle Cloud Infrastructure configuration (OCI).
- The issue does not appear to be related to ACL filtering.

Here is a screenshot from my Oracle Developer Client connection for reference:
[oracle developer client connection](https://i.sstatic.net/4amAleYL.png)

**Comment by B0nam** [comment]
I figured it out, I was missing the Oracle client...

Basically, to connect a NestJS application to Oracle Autonomous Database using TypeORM, you need to configure your environment to use the Oracle Instant Client and Oracle Wallet for secure database access. Here’s an outline of the solution:

1. **Install the Oracle Instant Client**: Ensure that the client is installed and available on your system. This library is essential for TypeORM to communicate with the Oracle database. You’ll need the path to the client library, such as `libclntsh.so`.

2. **Download and Configure Oracle Wallet**: Obtain the Oracle Wallet files from the Oracle Cloud Infrastructure (OCI). These files include `tnsnames.ora`, `ewallet.pem`, and others required for secure communication. Place them in a directory accessible by your application.

3. **Set Environment Variables**: Use environment variables to store database credentials (username, password) and the location of the Oracle Wallet directory (`TNS_ADMIN`).

4. **Initialize the Oracle Client**: Configure your application to load the Instant Client at runtime. This ensures the application can locate the required libraries (e.g., `libclntsh.so`) and use the Oracle Wallet for connections.

5. **TypeORM Configuration**: Adjust TypeORM settings to use the database connection string and Oracle Wallet credentials securely.

I got the solution from this repo: [GitHub Repository](https://github.com/kwt1326/pet_adoption_app).  
Big thanks to kwt1326!

**Comment by cjbj** [comment]
@B0nam you don't necessarily need Instant Client to connect to Oracle Autonomous Database - but you do need to make sure to pass the correct parameters, since these differ (for historic reasons) between Thin and Thick mode.  I use Thin mode with ADB all the time.

**Comment by B0nam** [comment]
I was only able to get it working with the parameters mentioned above 😞. Could you provide the parameters that worked for you, or share any links to documentation or code examples? I would really appreciate it!

**Comment by cjbj** [comment]
@B0nam To use Oracle ADB-S with mTLS (i.e a wallet), my typeorm ormconfig.json from the quickstart https://typeorm.io/#/ (that I created a while back) used the `extra` attribute to pass the Thin mode PEM wallet location and password and tnsnames.ora location.  It looks like:

```
{
  "type": "oracle",
  "username": "cj",
  "password": "xxxxx",
  "connectString": "cjmtls_high",
  "synchronize": true,
  "logging": false,
  "extra" : {
    "configDir": "/Users/cjones/q/Cloud/alwaysfree/CJMTLS",
    "walletLocation": "/Users/cjones/q/Cloud/alwaysfree/CJMTLS",
    "walletPassword": "xxxx"
  },
  "entities": [
    "src/entity/**/*.ts"
  ],
  "migrations": [
    "src/migration/**/*.ts"
  ],
  "subscribers": [
    "src/subscriber/**/*.ts"
  ],
  "cli": {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
}
```

For completeness, if 1-way TLS was used (i.e. no wallet), then the `extra` attribute isn't needed for Thin (or Thick) modes, since you just need the DB credentials and the connect descriptor from the ADB-S console.

**Comment by B0nam** [comment]
> @B0nam To use Oracle ADB-S with mTLS (i.e a wallet), my typeorm ormconfig.json from the quickstart https://typeorm.io/#/ (that I created a while back) used the `extra` attribute to pass the PEM wallet location and password and tnsnames.ora location needed for Thin mode. It looks like:
> 
> ```
> {
>   "type": "oracle",
>   "username": "cj",
>   "password": "xxxxx",
>   "connectString": "cjmtls_high",
>   "synchronize": true,
>   "logging": false,
>   "extra" : {
>     "configDir": "/Users/cjones/q/Cloud/alwaysfree/CJMTLS",
>     "walletLocation": "/Users/cjones/q/Cloud/alwaysfree/CJMTLS",
>     "walletPassword": "xxxx"
>   },
>   "entities": [
>     "src/entity/**/*.ts"
>   ],
>   "migrations": [
>     "src/migration/**/*.ts"
>   ],
>   "subscribers": [
>     "src/subscriber/**/*.ts"
>   ],
>   "cli": {
>     "entitiesDir": "src/entity",
>     "migrationsDir": "src/migration",
>     "subscribersDir": "src/subscriber"
>   }
> }
> ```
> 
> For completeness, if 1-way TLS was used (i.e. no wallet), then the `extra` attribute isn't needed for Thin (or Thick) modes, since you just need the DB credentials and the connect descriptor from the ADB-S console.

Thank you very much!

**Comment by B0nam** [comment]
An additional piece of information that might help someone: you need to disable the "Require mutual TLS (mTLS) authentication" option and configure an ACL filter to allow the IP address of the connection in the Autonomous Database settings. This will enable access without a wallet and without the driver.

![image](https://github.com/user-attachments/assets/930c042d-1847-4e84-9ba0-90e548da77b5)
Disable the option mentioned above

![image](https://github.com/user-attachments/assets/b6d27530-1579-48f3-a562-57db7c82e157)
Add your ip, CIDR or VNC

Where is the code i used:

```
import { Module } from '@nestjs/common'
import { AppController } from './app.controller'
import { AppService } from './app.service'
import { ConfigModule } from '@nestjs/config'
import { TypeOrmModule } from '@nestjs/typeorm'

@Module({
	imports: [
		ConfigModule.forRoot({ isGlobal: true, envFilePath: '../../.env' }),
		TypeOrmModule.forRoot({
			type: 'oracle',
			username: process.env.DB_USERNAME,
			password: process.env.DB_PASSWORD,
			connectString: process.env.DB_CONNECTION,
			autoLoadEntities: true,
			synchronize: true,
			logging: true,
		}),
	],
	controllers: [AppController],
	providers: [AppService],
})
export class AppModule {}
```

env file:
```
DB_USERNAME=usename
DB_PASSWORD=password
DB_CONNECTION=(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=<host>))(connect_data=(service_name=<service name>))(security=(ssl_server_dn_match=yes)))
```

**Comment by cjbj** [comment]
@B0nam and using 1-way TLS should be faster, too.
