### ISSUE TITLE
No `privilege` property on `GetPooledConnectionOptions` nor `Poolattributes` in 6.7.0

### ISSUE THREAD

**Issue by indymaat** [oracle/node-oracledb#1714]
1. What versions are you using?

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.17.0.0.0

```json
  "dependencies": {
    "@types/oracledb": "^6.5.2",
    "oracledb": "^6.7.0",
    "pino": "^9.5.0",
    "zod": "^3.24.0",
    "zod-validation-error": "^3.4.0"
  },
  "devDependencies": {
    "@babel/preset-typescript": "^7.26.0",
    "@types/jest": "^29.5.14",
    "@types/node": "^22.10.1",
    "jest": "^29.7.0",
    "pino-pretty": "^13.0.0",
    "ts-jest": "^29.2.5",
    "ts-node": "^10.9.2",
    "tslib": "^2.8.1",
    "typescript": "^5.7.2"
  }
```

```
PS> node
Welcome to Node.js v20.17.0.
Type ".help" for more information.
>     process.platform
'win32'
>     process.version
'v20.17.0'
>     process.arch
'x64'
>     require('oracledb').versionString
'6.7.0'
>     require('oracledb').oracleClientVersionString
undefined
>
```

3. Is it an error or a hang or a crash?

It's a missing property; `privilege`

5. What error(s) or behavior you are seeing?

I am unable to pass in a value for the `privilege` property on the types `GetPooledConnectionOptions` and `Poolattributes`, because they dont exist? 
[Your 6.7.0 documentation clearly states that](https://node-oracledb.readthedocs.io/en/v6.7.0/user_guide/connection_handling.html#privileged-connections):
  - **Thin mode**: For [standalone connections](https://node-oracledb.readthedocs.io/en/v6.7.0/user_guide/connection_handling.html#standaloneconnection), you must set the [privilege](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#getconnectiondbattrsprivilege) property in [oracledb.getConnection()](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#oracledb.getConnection)
  - **Thin mode with pooling**: For [pooled connections](https://node-oracledb.readthedocs.io/en/v6.7.0/user_guide/connection_handling.html#connpooling) with node-oracledb Thin mode, you must set the [privilege](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#createpoolpoolattrsprivilege), [user](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#createpoolpoolattrsuser), and [password](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#createpoolpoolattrspassword) properties in [oracledb.createPool()](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#oracledb.createPool)
  - **Thick mode**: For node-oracledb Thick mode, privileged connections can only be created with a [heterogeneous pool](https://node-oracledb.readthedocs.io/en/v6.7.0/user_guide/connection_handling.html#connpoolproxy). You must set the [homogeneous](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#createpoolpoolattrshomogeneous) property to false in [oracledb.createPool()](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#oracledb.createPool) to use a heterogeneous pool. You can then specify the [privilege](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#getconnectiondbattrsprivilege), [user](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#getconnectiondbattrsuser), and [password](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/oracledb.html#getconnectiondbattrspassword) properties in [pool.getConnection()](https://node-oracledb.readthedocs.io/en/v6.7.0/api_manual/pool.html#pool.getConnection).

But i just cannot see that property...

7. Include a runnable Node.js script that shows the problem.

[I made a Stackblitz ](https://stackblitz.com/edit/node-7f8ju56g?file=index.ts) because the error occurs when editing the file and Github Gists do not offer that.

**Comment by sharadraju** [comment]
The document clearly states that privilege property must be set in getConnection() function. What is the error that you get when you pass in the `privilege` property? The spelling is `privilege`, not `privilige`. Please check if the spelling is right.
I am not sure what you mean by types `GetPooledConnectionOptions` and `Poolattributes`? Are these Typescript attributes

I went to the StackBlitz page and I am not sure what I should be searching for?

Please provide a clearer test case for the same with proper replication steps.

**Comment by indymaat** [comment]
Sorry for being unclear, and my bad for the typo `privilige` instead of `privilege`. 

In the Stackblitz, u could try and add a value for the `privilege` property in the call to `createPool` and `getConnection`. I know screenshots are not advised, but it is way easier to explain...

![image](https://github.com/user-attachments/assets/caa42001-797b-49ad-ae33-25ff62b4d9f8)

![image](https://github.com/user-attachments/assets/e161b991-68da-439b-bffe-27f988b78924)

I would have expected the `privilege` property, but apparently it does not exist?

**Comment by sharadraju** [comment]
@indymaat Thanks for the clarification. It seems you are asking about the property not appearing in the AutoComplete list.
The privilege property or any other property of the config object for that matter will not appear in the pop-up list. You can try with other properties like user, password etc. They won't appear either.
But that does not mean they are not supported.
You can try adding the privilege property and see if the program runs correctly and let us know. If you are unable to run the program even after adding a "privilege" property or get an error, then let us knw,

The auto-complete feature is a property of the in-built tool (VSCode, I assume in this case).

**Comment by indymaat** [comment]
Haha okay, sorry, still not clear my bad. The autocomplete in StackBlitz does not really work as it does in my own VS Code environment. 

Simply put; the `privilege` property does not exist on GetPooledConnectionOptions or Poolattributes:

![image](https://github.com/user-attachments/assets/237d5f50-985c-489c-a621-d074f796d3a3)
![image](https://github.com/user-attachments/assets/3ea47e10-9bbd-46ec-a5c5-63161bba0df5)

Thanks for bearing with me.

**Comment by sudarshan12s** [comment]
The autocomplete issue is because the types defination for poolAttributes does not have [privilege](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/db295b65efa378c52e25b556d55d7f53a825eb27/types/oracledb/index.d.ts#L2628).

Thanks for letting us know. We will check and fix this. For now, we can ignore the TS error.

As per ORA-28009, It should only come if privilege is not passed. Can you confirm this by printing `poolAttributes`  it before calling `createPool` . Does it happen through simple js program. (just to avoid some typescript settings removing this property ...).

**Comment by sosoba** [comment]
Small advice. In this situation you can give `expect-error` directive:

```ts
const poolAttributes: PoolAttributes = {
    //@ts-expect-error - until types fixed
    privilege: oracledb.SYSDBA,
}
```
In the future, when the types are updated, the compiler will inform you that the comment is no longer necessary.

**Comment by sharadraju** [comment]
This issue (or PR) needs to be raised in https://github.com/DefinitelyTyped repo.
 I am closing this issue here

**Comment by indymaat** [comment]
Thanks everyone!

@sudarshan12s I forgot to implement the `homogoneus: false` property. I have a working connection as `SYSDBA` now.

If I change `node_modules\@types\oracledb\index.d.ts` to include the `privilege` parameter, type checking as expected. 

I was not aware of the `DefinitelyTyped` repository, will try to create a PR if I have time.

**Comment by sudarshan12s** [comment]
> Thanks everyone!
> 
> @sudarshan12s I forgot to implement the `homogoneus: false` property. I have a working connection as `SYSDBA` now.
> 
> If I change `node_modules\@types\oracledb\index.d.ts` to include the `privilege` parameter, type checking as expected.
> 
> I was not aware of the `DefinitelyTyped` repository, will try to create a PR if I have time.

Thanks for confirming. I will be raising PR soon and will update on this.

**Comment by sudarshan12s** [comment]
[PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71458) is opened for the type change.
