### ISSUE TITLE
Identify clob, blob field in query

### ISSUE THREAD

**Issue by mikollaay** [oracle/node-oracledb#173]
Hi !
Can I identify field type returned by query ? 
How to distinguish between clob and blob types, if types are not known before query?

Thanks.

**Comment by randomailer** [comment]
`lob typeof  == 'object'`

or

`var Readable = require('stream').Readable;`
`lob instanceof Readable`

**Comment by cjbj** [comment]
@mikollaay good question, and one I asked during pre-release testing!  Short answer is that we have an action item to make it possible.

**Comment by mikollaay** [comment]
How about to add some Result Object Properties => metaData like 
metaData: [ { name: 'ID', type: 'VARCHAR2' }, { name: 'PHOTO', type: 'BLOB' }, { name: 'DESCR', type: 'CLOB' } ] }

**Comment by cjbj** [comment]
@mikollaay that's a good point, and is on the long 'todo' list at some stage (along with column lengths etc).  I was thinking more about allowing some kind of introspection by setting a new property of Lob.

**Comment by cjbj** [comment]
@mikollaay node-oracledb 1.2 implements a Lob [`type`](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#proplobtype) attribute.  Take a look.
