### ISSUE TITLE
console.log(con)

### ISSUE THREAD

**Issue by xpiwo** [oracle/node-oracledb#175]
*edited original issue*, only minor annoyance:

can't use console.log(con):
```
console.log(con);
Error: NJS-015: action is a write-only property
```

& quick question:

are bind parameters auto escaped? or it needs to be done manually?

Thanks.

**Comment by cjbj** [comment]
@xpiwo Did you get the async.waterfall working?  Can you share some code for others to learn from?

The Connection object write-only properties have been "discussed".  There is a purist, technical argument against letting them be read: PL/SQL procedures can also be used to change the values. If this happens, then the driver properties won't get updated and will show values that are/were not used.  I will continue to try an convince the team that the benefits of making the properties readable outweigh this issue.  What do you think?

Bind parameters do not need escaping by you or the driver.  They are never interpreted as commands.  You can see the behavior of the bind data as a single entity in the 'IN (:ids)' example from https://github.com/oracle/node-oracledb/issues/137

**Comment by xpiwo** [comment]
i would say console.log is used 100% when trying to debug something, so preferably it should work as expected.
i think it is better to document that the values may change / add some 'warning' property if you really want.

---

there was no issue with async, just the error (node 0.10.38) threw me off : 
```
.node-gyp/0.10.38/src/node_object_wrap.h:61: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = Pool]: Assertion `handle->InternalFieldCount() > 0' failed.
```

when trying to async.waterfall([pool.getConnection]), will lose the reference to 'this' and needs an empty wrapper function.
```
async.waterfall([function(cb){
    pool.getConnection(cb);
}]);
```

Thanks.

**Comment by cjbj** [comment]
@xpiwo thanks for the info.
