### ISSUE TITLE
Support for 'Long' numbers

### ISSUE THREAD

**Issue by darthg0d** [oracle/node-oracledb#177]
Since JS Number supports only upto 2^53 sized integers (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number), any table column with an integer value longer than that gets truncated to 53-bits.

Any plans on supporting these long INTs? Possibly using an existing package (like https://www.npmjs.com/package/long)?

**Comment by darthg0d** [comment]
For example, a value like <code>17249138680355831</code> becomes <code>17249138680355800</code>.

When I enable <code>oracledb.fetchAsString = [ oracledb.NUMBER ];</code>, the value is returned as <code>17249138</code>.

**Comment by cjbj** [comment]
@darthg0d there no current plans by us for "3rd party" integration, but I'd be interested if you want to submit a PR.

The fetchAsString behavior is a bug.  Ouch.

**Comment by darthg0d** [comment]
Fixing the 'fetchAsString' would do the trick for me.

If I can find time to add support for long INTs, I'll definitely send a PR.

**Comment by cjbj** [comment]
@darthg0d fetchAsString is fixed in 1.1.  Thanks for your patience.

**Comment by darthg0d** [comment]
Awesome! Thanks!
