### ISSUE TITLE
PL/SQL execution triggering callback before it's finished

### ISSUE THREAD

**Issue by vincentserpoul** [oracle/node-oracledb#178]
Hi,

I am not sure this is the expected behaviour but I notice the following:

```
var testSQL = 'BEGIN
    dbms_lock.sleep(10);
END;'
console.log(new Date().getTime() / 1000);
connection.execute(testSQL, function(err) {
      console.log(new Date().getTime() / 1000);
});
```
timings logged:
1440557674.026
1440557674.028

I was expecting the two times to be 10s apart, and callback called after the PL/SQL has been executed, but it calling back almost immediately.

Is it what is expected?

**Comment by cjbj** [comment]
@vincentserpoul add some error handling.  I am guessing you will see `PLS-00201: identifier 'DBMS_LOCK' must be declared`.

```
cjones@cjones-mac:~/n$ node dbmslock.js 
Connecting as cj
1440562525.562
ORA-06550: line 1, column 7:
PLS-00201: identifier 'DBMS_LOCK' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
1440562525.568
cjones@cjones-mac:~/n$ node dbmslock.js 
Connecting as system
1440562530.433
1440562540.445
```

**Comment by vincentserpoul** [comment]
It actually works fine now!
It was my callback implementation that was wrong!

thank you
