### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by shikelong** [oracle/node-oracledb#179]
platform: windows 10 64bit
node Version: v0.12.2

### the error info
```bash
 C:\Users\shikelong\Desktop\爬虫\spider_node\app>node oracledbtest.js
C:\Users\shikelong\AppData\Roaming\npm\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: %1 is not a valid Win32 application.
C:\Users\shikelong\AppData\Roaming\npm\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\shikelong\AppData\Roaming\npm\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
--------
### my path setting:

Path: C:\instantclient_12_1;
OCI_INC_DIR: C:\instantclient_12_1\sdk\include
OCI_LIB_DIR: C:\instantclient_12_1\sdk\lib\msvc

I had readed the [issue 35](https://github.com/oracle/node-oracledb/issues/35)
But my Path is Ok.and the `oci.dll` existed. So what error about my environment？ thx.

**Comment by shikelong** [comment]
![ocidll](https://cloud.githubusercontent.com/assets/4499997/9603203/c06b3c56-50e1-11e5-8e22-4b6daef246a4.png)

**Comment by krismohan** [comment]
May be the instant client you downloaded was for 32bit?

**Comment by shikelong** [comment]
both instant client and node were 64bit.
![64](https://cloud.githubusercontent.com/assets/4499997/9603578/29012ddc-50e4-11e5-8b0c-badb458fba05.png)

**Comment by bchr02** [comment]
It appears that you installed node-oracledb globally. What was the output you got after you installed it?

It shouldn't make a difference but can you try to copy the app into "c:\test" then install the node-oracledb module locally and then try running "node oracledbtest.js" I wonder if the Unicode characters "爬虫" are causing an issue. Please let us know what happens. Thanks.

**Comment by shikelong** [comment]
Thanks!  It caused by the Unicode characters. After I change the file `oracledbtest.js`'s path to c:/. Then I "node oracledbtest.js", the connection is ok.

**Comment by bchr02** [comment]
okay, great. I'm glad you got it working.

@cjbj is this a bug with node-oracledb?

**Comment by cjbj** [comment]
@bchr02 I'll get it checked out. Instinctively I'd say not, but it's easy to check.

**Comment by BrianJVarley** [comment]
I came across this same error after inheriting a Meteor project compiled using the 32bit arc for OracleDB.
I was trying to compile with a 64bit version of node and Oracle instaclient and got the `Error: %1 is not a valid Win32 application.`

Deleting the existing node_modules. Then opening a 32bit Node.js command prompt and running `npm install` then `meteor run`  solved the error.
