### ISSUE TITLE
Can you manually exclude statement caching?

### ISSUE THREAD

**Issue by xpiwo** [oracle/node-oracledb#182]
It it possible to explicitly exclude some statement from the cache? setDisableStatementCaching? 

Thanks.

**Comment by krismohan** [comment]
Any reason why you need that? LRU ones are thrown off the cache if the cache is full.

**Comment by xpiwo** [comment]
i don't want to cache 'on the fly' dynamic statements and to push off cached statements.

**Comment by cjbj** [comment]
@xpiwo any chance you can use bind variables for this kind of statement?  How's the statement caching working out for you in general?

@krismohan do you want to add a doNotCache option to execute() that indicates OCIStmtRelease should use OCI_STRLS_CACHE_DELETE?

**Comment by xpiwo** [comment]
It might be possible to use bind variables and pass a bunch of nulls/empty strings, but that's ugly.

The do not cache flag is the feature request i was aiming for :)

Thanks.

**Comment by krismohan** [comment]
It is feasible. OCI supports it as Chris mentioned.

**Comment by cjbj** [comment]
A new `keepInStmtCache` attribute in now available in node-oracledb 5.3 to handle this situation.  Thanks for your patience!
