### ISSUE TITLE
Installation instructions for windows are incomplete

### ISSUE THREAD

**Issue by rogergl** [oracle/node-oracledb#183]
To make the installation work I had to:

1) use the x64 native tools command shell

2.) call npm install oracledb with the -msvs_version=2013 flag

**Comment by cjbj** [comment]
@rogergl what Windows version were you on?  What compiler version?  What didn't work or gave an error unless you did this?

**Comment by rogergl** [comment]
npm install oracledb failed with various error messages as soon as the installer tried to compile something. I'm using Windows 8.1 and Visual-Studio 2013.

**Comment by cjbj** [comment]
@rogergl thank you!

**Comment by bchr02** [comment]
@rogergl Thanks for this information. I hope you can further help us to narrow down what specific in your environment is causing you to have to perform these extra steps. 

Can you please confirm if the following is a correct description of your environment and if not let us know what is different? (I am interested to know the specific editions of each. for ex VS2013 Ultimate not just VS2013) 

* Windows 8.1 64bit
* Visual Studio Community 2013 with Update 5
* 64bit Oracle Instant Client 12.1.0.2.0

Also, can you run "node -v" and provide the output. Thanks.

**Comment by cjbj** [comment]
@bchr02 I've had a couple of users email me verbose logs from failed Windows installs.  They show output like:
```
  verbose about to build C:\some\long\redacted\pre-existing\path\node_modules\oracledb
```
Soon after that, there is the first sign of failure:
```
  info oracledb@1.0.0 Failed to exec install script
```
What do you think? permission problem?  I haven't yet come across this on OS X or Linux

**Comment by bchr02** [comment]
Not sure. Need more info. Can you foward me some of the emails? I would like to see more of the logs.

**Comment by cjbj** [comment]
@bchr02 Sorry I can't forward the emails due to privacy requirements. I am waiting to hear back from the users what further investigation uncovered.

**Comment by bchr02** [comment]
no worries, it's just that what you provided is not a lot to go on. Is there any other details that they provided that you could post here?

**Comment by cjbj** [comment]
We did some work on the instructions in 1.2 (thanks @bchr02 !).  I will close this.

If anyone has specific suggestions, please open new issues.
