### ISSUE TITLE
Cannot open further sessions

### ISSUE THREAD

**Issue by scottchantry** [oracle/node-oracledb#184]
I have an app that can have hundreds of concurrent connections and when the number of connections exceeds my pools maximum I get:

ORA-24418: Cannot open further sessions.

Is there a way to have it queue the request and wait for an available connection or do I need to set my poolMax very high?

**Comment by cjbj** [comment]
This seems a popular question.

For now you will have to either size the system to cope with the max load, or alternatively handle the error & retries in the app code.

Check some of the other discussions, e.g
https://github.com/oracle/node-oracledb/issues/126
https://community.oracle.com/message/12810848
https://community.oracle.com/message/12947929

**Comment by dmcghan** [comment]
@scottchantry I just added support for connection request queueing at the pool level to orawrap. It limits the number of active connections in a pool to the poolMax setting. I'd love it if you could give it a test and/or provide some feedback.
