### ISSUE TITLE
Instant Client and ORACLE_HOME

### ISSUE THREAD

**Issue by Stallwort** [oracle/node-oracledb#185]
This is just an FYI that might be helpful to some. These comments can be moved/marked as needed.

In a windows environment, using the instant client in the ..\node_modules\oracledb\build\Release folder works great.  I am only using 3 dll's from Oracle 12g:  oci.dll, oraociei12.dll, and oraons.dll  (actually, it seems to work fine in any parent folder also). 

However, if you are needing to use the instant client in an environment that has a different Oracle version installed with an ORACLE_HOME environment variable set, then you will likely find you get an error:  ORA-12154: TNS:could not resolve the connect identifier specified.  The trick is to simply set ORACLE_HOME to an empty string before you call into oracledb:
```javascript
process.env.ORACLE_HOME = '';
````
Now it should work fine.

**Comment by bchr02** [comment]
@Stallwort Per [Oracle here](http://docs.oracle.com/cd/B10501_01/win.920/a95490/orahome.htm) and [Burleson Consulting here](http://www.dba-oracle.com/t_windows_oracle_home.htm), ORACLE_HOME should not be set as a system environmental variable and instead only as a local environmental variable within a script or command line in cases when multiple release of Oracle are being used. Therefore, I do not understand a use case for setting it to a blank string. If ORACLE_HOME is not set then whatever oracle directory appears first within PATH takes precedent. Therefore, I think it would be useful to point out that, when multiple instant clients are installed, within ones node script one could manually assign the value where they would like to point to using process.env.ORACLE_HOME.

**Comment by Stallwort** [comment]
@bchr02 Thanks for the links.  If my software were to only run in an environment that I could control, then I probably would never have even noticed this.  I was in error thinking that the instant client would be picked up first before ORACLE_HOME.  This oversight of not checking ORACLE_HOME (because in my development environment, everything was working) baffled me for a bit.  Now for sure I know to do the ORACLE_HOME check.  Thanks.

**Comment by bchr02** [comment]
After getting some clarification (https://github.com/oracle/node-oracledb/issues/190#issuecomment-137676427) on the proper way to utilize ORACLE_HOME, here is how it could be done within the same script...

````javascript
process.env['oracle_home'] = 'c:\\nodeappfolder\\oracle';
process.env['path'] = process.env['oracle_home'] + ';' + process.env['path'];
var oracledb = require('oracledb');
````

the key is to add these two lines to the top of your script before ```require('oracledb')```. Don't ask me why but apparently these two lines get processed before the variables get hoisted... I was thinking I would have to do this:
````javascript
var oracledb;
process.env['oracle_home'] = 'c:\\nodeappfolder\\oracle';
process.env['path'] = process.env['oracle_home'] + ';' + process.env['path'];
oracledb = require('oracledb');
````
but for reasons I can't explain the other way works as well. Does anyone know why?

**Comment by krismohan** [comment]
The PATH should be over %ORACLE_HOME%\bin, not ORACLE_HOME.

**Comment by bchr02** [comment]
@krishmohan Not during my testing. Your mileage may very. Bottom line is that Path needs to point to the oracle dll's.

**Comment by krismohan** [comment]
Yes. In a regular client installation, they will be under ORACLE_HOME\bin.
