### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by JGLiv** [oracle/node-oracledb#187]
I've followed the installation instructions for Linux, and everything is ok up until trying to npm install oracledb (using io.js v3.3.0)

$ npm install oracledb

npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data

> oracledb@1.1.0 install /home/john/test/node_modules/oracledb
> node-gyp rebuild

>make: Entering directory `/home/john/test/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o

>In file included from ../src/njs/src/njsOracle.h:56:0,
>                 from ../src/njs/src/njsOracle.cpp:53:
>../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
>   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
>                           ^
>../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
>   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
>                 ^
>../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
>   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
>                           ^
>../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
>   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
>                           ^
>../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
>     , node::smalloc::FreeCallback callback
>             ^
>../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
>     , node::smalloc::FreeCallback callback
>                                   ^
>../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
>../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
>         v8::Isolate::GetCurrent(), data, length, callback, hint);
>                                                  ^
>../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
>         v8::Isolate::GetCurrent(), data, length, callback, hint);
>                                                            ^
>../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
>../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
>     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
>                                                                   ^
>../node_modules/nan/nan.h:768:67: note: candidates are:
>In file included from ../node_modules/nan/nan.h:25:0,
>                 from ../src/njs/src/njsOracle.h:56,
>                 from ../src/njs/src/njsOracle.cpp:53:
>/home/john/.node-gyp/3.3.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
> NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
>                                        ^
>/home/john/.node-gyp/3.3.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
>/home/john/.node-gyp/3.3.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
> NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
>                                        ^
>/home/john/.node-gyp/3.3.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
>In file included from ../src/njs/src/njsOracle.h:56:0,
>                 from ../src/njs/src/njsOracle.cpp:53:
>../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
>../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
>     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
>                                                             ^
>../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
>     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
>            ^
>../src/njs/src/njsOracle.cpp: In static member function ‘static void Oracledb::Async_AfterGetConnection(uv_work_t*)’:
>../src/njs/src/njsOracle.cpp:761:28: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/john/.node-gyp/3.3.0/include/node/node.h:282): Use >FatalException(isolate, ...) [-Wdeprecated-declarations]
>     node::FatalException(tc);
>                            ^
>../src/njs/src/njsOracle.cpp: In static member function ‘static void Oracledb::Async_AfterCreatePool(uv_work_t*)’:
>../src/njs/src/njsOracle.cpp:915:29: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/john/.node-gyp/3.3.0/include/node/node.h:282): Use >FatalException(isolate, ...) [-Wdeprecated-declarations]
>     node::FatalException (tc);
>                             ^
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory `/home/john/test/node_modules/oracledb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-34-generic
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/john/test/node_modules/oracledb
gyp ERR! node -v v3.3.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 3.13.0-34-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "oracledb"
npm ERR! node v3.3.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/john/test/npm-debug.log

Any idea what is causing this or how to fix it?

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/172
