### ISSUE TITLE
fetchAsString oracledb.CLOB support

### ISSUE THREAD

**Issue by GaryRogers** [oracle/node-oracledb#188]
Would it be possible to support CLOBs in fetchAsString?

I'm having a hell of a time dealing with simple CLOBS I've used to serialize JSON objects to the database. These _could_ be varchar2's (especially in Ora12) but I can't guarantee a length of a serialized object, so I've got CLOBs for that purpose.

Supporting CLOBs in fetchAsString, with logPrefetchSize support would be the bee's knees.

**Comment by cjbj** [comment]
CLOB via fetchAsString is planned.  Thanks for filing this issue, since it helps us prioritize.

**Comment by GaryRogers** [comment]
Muchas Gracias!

**Comment by atiertant** [comment]
@cjbj need it too

**Comment by cjbj** [comment]
@atiertant OK!  It's on our list.  What about inserting - Streams OK?

**Comment by atiertant** [comment]
@cjbj are you talking about bind in?

**Comment by cjbj** [comment]
@atiertant I'm talking theoretical, 'if you could do anything, what would it be?'

**Comment by atiertant** [comment]
i would need insert and read : 
javascript String in Clob,
javascript Buffer in Blob,
javascript Date in Timestamp

this is not easy to find what type of binding currently working or not.
could you had a table relating progress somewhere?

**Comment by bchr02** [comment]
+1, just ran into an issue where this would have helped.

**Comment by sagiegurari** [comment]
see:
https://github.com/sagiegurari/simple-oracledb#usage-query
and
https://github.com/sagiegurari/simple-oracledb#usage-insert

for string/buffer support in LOBs without needing to work with streams.

**Comment by lenny76** [comment]
with simple-oracledb I solved my problem!
thanks
+1

**Comment by behroozshafiabadi** [comment]
Need it too
+1

**Comment by sagiegurari** [comment]
@behroozshafiabadi check my previous comment, it will solve your issue.

**Comment by cjbj** [comment]
There's a bunch of underlying LOB improvements in node-oracledb 1.12.0-dev on GitHub.  The fetchAsString support for queries got delayed, but there is bind support for Strings and Buffers to PL/SQL LOB parameters.  We didn't want to delay getting 1.12.0-dev out any longer.  The [doc](https://github.com/oracle/node-oracledb/blob/v1.12.0-dev/doc/api.md#lobhandling).  Test it out and send us feedback so we can make an npm release.  I'll leave this issue open until fetchAsString is done.

**Comment by cjbj** [comment]
Oh, and you can INSERT strings and buffers directly in 1.12.0-dev

**Comment by cjbj** [comment]
`fetchAsString` support for CLOBs is now in 1.12.1-dev on the master branch in GitHub.  Check it out.  You'll want to link node-oracledb with Oracle Client libraries 12.1.

**Comment by cjbj** [comment]
Node-oracledb 1.12 with `fetchAsString` support for CLOBs is now on npm: https://blogs.oracle.com/opal/entry/node_oracledb_1_12_working
