### ISSUE TITLE
copy the installation from one computer to another ?

### ISSUE THREAD

**Issue by rogergl** [oracle/node-oracledb#189]
Is it possible to copy the oracledb installation from one computer to another ? I tried to copy the complete node_modules folder, containing the oracledb installation, and the instant client folder from the development server to the production server. I installed the Visual Studio 2013 redistributables but I get the following error  as soon as I try to require the oracledb module:

C:\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: The specified module could not be found.
C:\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by cjbj** [comment]
I suspect it's possible in some circumstances, which is why things like node-pre-gyp exist, but it has not been investigated by us.  Check you have set PATH to the location of Instant Client

**Comment by pvenkatraman** [comment]
Have you set the required environment variables.  Check %NODE_PATH% particularly.

**Comment by rogergl** [comment]
Yes, I have set the PATH. But it still does not work.

**Comment by bchr02** [comment]
Okay, so I tried doing the same exact thing as you and had the same exact problem. The solution was to install [Microsoft Visual C++ 2010 Redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=26999).

Here is how I figured this out. But first, I want to mention my testing environment (in case anyone is curious). 
* Windows 7 64bit
* 64bit Node 0.12.7
* Visual Studio Community 2013 with Update 5 (which also installed Visual C++ 2012 Redistributable)

My initial reaction was by moving a node app which has a compiled copy of node-oracledb, it should work simply by copying it to another 64bit Windows computer with Visual C++ 2012 Redistributable. But this was not the case and instead I got the same error msg:
> Error: The specified module could not be found.

So, what I did was install a program called Dependency Walker and used it to open ```oracledb.node``` which was in the ```node_modules\oracledb\build\Release``` folder. This immediately showed that there was an error opening a file by the name of MSVCR100.DLL. A google search later and I have discovered that this file belongs to Visual C++ 2010 Runtime, not the 2012. I then installed the Visual C++ 2010 Runtime and was able to use my node app.

**Comment by rogergl** [comment]
Thanks installing the 2010 Redistributables helped.

**Comment by bchr02** [comment]
@cjbj can we remove the dependency of Visual Studio Redistributable by linking the dll statically? Or maybe if there was a way to show the missing dll within the error message...instead of getting "Error: The specified module could not be found." something like "MSVCR100.DLL could not be found."

**Comment by cjbj** [comment]
@bchr02 short answer no.

We incorporated a section on moving binaries between Windows machines into the INSTALL guide (thanks @bchr02).  I will close this issue which has been dormant for a few weeks.
