### ISSUE TITLE
use of ORACLE_HOME does not work on Windows

### ISSUE THREAD

**Issue by bchr02** [oracle/node-oracledb#190]
It is a common practice to use the ORACLE_HOME environmental variable instead of including the Oracle directory in PATH, especially when multiple Oracle clients are installed, however, this does not work with node-oracledb 1.1 on Microsoft Windows.

I was helping someone out with [Issue #185](https://github.com/oracle/node-oracledb/issues/185) when I thought I would try to make use of it and noticed that it didn't work. I set it as a system environmental variable restarted my command prompt but it still did not work. Must be a bug.

**Comment by bchr02** [comment]
Steps you could use to verify this on Microsoft Windows:
1. Within the Advanced tab of System Properties click Environmental Variables.
2. Under System Variables find "Path" and Edit it.
3. Skim through it and remove any reference to an Oracle folder. 
2. Click New and add ORACLE_HOME so that it points to the proper Oracle folder.
3. open a command prompt up and navigate to a folder that contains a node-oracledb app.
4. try running it.

**Comment by cjbj** [comment]
What version of Windows?

There's nothing specific to node-oracledb about this that I know of - this is all just handled by the Oracle client libs.

**Comment by bchr02** [comment]
Windows 7 Pro 64bit with the Oracle client from the following ZIP file: ```instantclient-basic-windows.x64-12.1.0.2.0```

**Comment by bchr02** [comment]
btw, I noticed you gave this a tag of "Install Issue" however the issue is not with the installation but rather the usage of the module after it's installed.

**Comment by cjbj** [comment]
@bchr02 re the tag, I guess I was thinking of it as an "install & configuration" issue.

**Comment by pvenkatraman** [comment]
set OCI_INC_DIR=%ORACLE_HOME%\oci\include
set OCI_LIB_DIR=%ORACLE_HOME%\oci\lib\msvc
and make sure %PATH% has %ORACLE_HOME% already.

**Comment by bchr02** [comment]
Okay that makes sense now. Thank you @pvenkatraman

**Comment by krismohan** [comment]
There is a typo above. The PATH should be over %ORACLE_HOME%\bin, not %ORACLE_HOME%.

**Comment by bchr02** [comment]
@krishmohan Not during my testing. Your mileage may very. Bottom line is that Path needs to point to the oracle dll's.
