### ISSUE TITLE
Concurrent connection limit

### ISSUE THREAD

**Issue by DefunctExodus** [oracle/node-oracledb#192]
Good Morning,

I am just wondering if there is a concurrent connection limit? We are currently hitting a wall when we have 30 + connections at the same time to various databases (some may be to the same one), It seems to constantly cause a core dump well the servers have essentially zero load on them during this time.

We have started using a limiter to keep the amount of connections limited to about 5 at the same time which keeps us from running into the problem but it just seems like patch fix.

**Comment by cjbj** [comment]
There's no limit on the node-oracledb side.

Got a testcase?

**Comment by cjbj** [comment]
Closing this due to lack of response.

For future readers, the connection queuing mentioned in https://github.com/oracle/node-oracledb/issues/126#issuecomment-143369249 may be interesting,
