### ISSUE TITLE
oracledb windows server specified procedure fail

### ISSUE THREAD

**Issue by happilymarrieddad** [oracle/node-oracledb#194]
I can't seem to get node to compile and run with the oracle driver. I keep getting this error.

![selection_005](https://cloud.githubusercontent.com/assets/6416323/9746368/ce987f0c-5634-11e5-98a8-cec131d79931.jpg)

![selection_006](https://cloud.githubusercontent.com/assets/6416323/9746414/0048e0c8-5635-11e5-839a-07ea94db68ac.jpg)

I hope this is enough information. I'm not a windows guy but the system I'm working with is windows and there is nothing I can do about that. The adapter I'm building has to be on that system. Thanks!!!

'''
node -e "console.log(process.arch, require('os').arch())"
'''
returns ia32 ia32

**Comment by happilymarrieddad** [comment]
I think it might have to do something with the driver.. I've tried both the 64 bit and the 32 bit one from oracle's website... I mean the instant client... I wish this was as easy as MySQL lol.

**Comment by bchr02** [comment]
Check out my install video:https://www.youtube.com/watch?v=I23XTkUMrtM
Also, what version of the oracle client did you download? Looks like a version prior to 11g because I only see vc8/9 folders in your screen shot. 
I would use Visual Studios 2013, latest 11g client and set the environmental variables at the system level not the user level. Also make sure your update path env variable so that it includes the oracle folder which contains oci.dll. 
    _____________________________

**Comment by happilymarrieddad** [comment]
Thanks man I'm watching your video right now so I'm not sure if it works but I wanted to point out that I can't install Visual Studio 2013 because I'm running an older version of Windows. I can compile and I got the C++ libraries to build when I run npm install for oracledb. I think my problem may be somewhere in the path or something. I'll get back to you once I'm done watching your video and diagnosing. Thanks!

**Comment by happilymarrieddad** [comment]
hey man I finished your video and now it wont compile at all.  here is the images for what is going on. Thanks!

![selection_008](https://cloud.githubusercontent.com/assets/6416323/9748690/d5f00b8a-5643-11e5-8c54-72112253998b.png)
![selection_009](https://cloud.githubusercontent.com/assets/6416323/9748691/d5f0903c-5643-11e5-83c9-90539746429d.png)

**Comment by cjbj** [comment]
"Unresolved external symbol" sounds like PATH doesn't contain the Oracle libraries.

**Comment by bchr02** [comment]
Also, keep in mind, if you changed any of your environmental variables using "System Properties" they won't be available to any existing open command prompt windows. However, simply opening a new command prompt will have the changes.

**Comment by bchr02** [comment]
If you are still having issues, please let us know what version of Visual Studios you have installed. I think you will need Visual Studio 2008 based on having a VC9 folder.

**Comment by happilymarrieddad** [comment]
Thanks. In the first picture I showed what paths I have set up in the system variables. I'll start downloading and installing visual studio 2008. Can you please verify if you are available that the paths are correct for me. Thanks!

**Comment by happilymarrieddad** [comment]
Do you know what the "unresolved external symbol" is?

**Comment by bchr02** [comment]
path env var does not include the oracle librabries as @cjbj mention here: https://github.com/oracle/node-oracledb/issues/194#issuecomment-138721273

**Comment by bchr02** [comment]
I just looked it up. Based on your screen shot, I see that you have Windows Server 2008 installed. Visual Studio's 2013 **is compatible** with that OS. [see this](https://www.visualstudio.com/en-us/products/visual-studio-2013-compatibility-vs.aspx)

Assuming you still have Visual Studio 2013 installed, to get up and running, download the 12g **basic** ZIP and the 12g **SDK** ZIP [from here](http://www.oracle.com/technetwork/topics/winx64soft-089540.html). Then extract them both into a new folder here "C:\oracle\instantclient".

Now, just open a command prompt and manually set everything by copying, pasting and executing each of the following lines:
set OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient\sdk\include
set path=C:\oracle\instantclient;%path%
npm install oracledb

Ongoing, and after you get it working, you will need to update your environmental variables (PATH, OCI_LIB_DIR, OCI_INC_DIR) within System Properties to match the above paths. For the path variable just add "C:\oracle\instantclient;" (without the quotes) in front of whatever it's already set to.

**Comment by bchr02** [comment]
also, if you can, I would remove OCI_VERSION user environmental variable. You don't need that for node-oracledb and I am not sure if it might cause issues. Ony your first screen shot I see that you have that set.

**Comment by happilymarrieddad** [comment]
I removed the user environmental variables, removed all the instantclient stuff, downloaded 12.1.0.2.0 instant client, set system env to the new instant client, removed all visual studio stuff.  When I run the installer for Visual Studio 2013 it says I need a newer version of Windows. Do you know why that might be?

**Comment by bchr02** [comment]
That's strange. Send a screen shot of the error.

**Comment by happilymarrieddad** [comment]
![selection_013](https://cloud.githubusercontent.com/assets/6416323/9767159/05f2aca2-56da-11e5-86d1-54b8cbea0178.png)

**Comment by happilymarrieddad** [comment]
The most frustrating thing is I can get it to work really easily on my Linux Mint box and my Windows 7 VM.... It seems to me to be an issue with Windows Server or something... I'm not a windows guy so I'm not sure.

**Comment by bchr02** [comment]
Sorry, I was wrong. [Here](https://www.visualstudio.com/en-us/visual-studio-2015-system-requirements-vs#30) is that exact version's system requirements. It shows you need at least Server 2008 R2. Therefore, keep the instantclientnt folder (the one with the VC9 folder) and download and install Visual Studios 2008.

Then in your command prompt use:
set OCI_LIB_DIR=C:\oracle\instantclientnt\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclientnt\sdk\include
set path=C:\oracle\instantclientnt;%path%
npm install oracledb

**Comment by happilymarrieddad** [comment]
is that going to cause a problem? it says it is 32 bit.

**Comment by happilymarrieddad** [comment]
when you say I need to use the instantclient, which one are you saying? should I grab the one that is 32bit or 64bit? should I grab version 11 or version 12? Thanks!

**Comment by happilymarrieddad** [comment]
Ok, I followed your instructions and this is the error I am getting now. 

![selection_015](https://cloud.githubusercontent.com/assets/6416323/9769612/68838bd0-56e8-11e5-9f1e-e8259e8c2112.png)

**Comment by bchr02** [comment]
use the same bitness for everything. so if you are using node 32bit (which it appears you are) then use 32 bit oracle instant client. Use 32bit 11.2.0.4.0 which can be downloaded from [here](http://www.oracle.com/technetwork/topics/winsoft-085727.html) but be sure to scroll down to the 11.2.0.4.0 version.

**Comment by happilymarrieddad** [comment]
ok I'm still getting the new error do you know why that might be?

**Comment by bchr02** [comment]
try: 
npm install  oracledb --msvs_version=2008

**Comment by happilymarrieddad** [comment]
do you know what the Itanium version is?

**Comment by bchr02** [comment]
no, why?

**Comment by happilymarrieddad** [comment]
one of the options on oracles website says itanium... btw thanks so much for spending so much time helping me!

**Comment by bchr02** [comment]
I don't think you need an Itanium oracle version. You should be able to use the 32bit one.

**Comment by happilymarrieddad** [comment]
ok the 2008 stuff didn't work so I'm trying 2010 and 64 bit. I'l let you know when I finish.

**Comment by happilymarrieddad** [comment]
ok I installed visual studio 2010 and had to use the --msvs_version=2010 in order to get it to recognize the visual studio VS_build.exe thing but now I'm getting this error. Have you seen this before?


![selection_016](https://cloud.githubusercontent.com/assets/6416323/9775098/ed140a48-5709-11e5-8139-21d107e44f4b.png)

**Comment by bchr02** [comment]
You may need to install:

* [Microsoft Windows SDK for Windows 7 and .NET Framework 4](https://www.microsoft.com/en-us/download/details.aspx?id=8279) which supports Windows Server 2008.

* SP1 for Visual Studio 2010

* [Visual C++ 2010 SP1 Compiler Update for the Windows SDK 7.1](http://www.microsoft.com/en-us/download/details.aspx?id=4422)

this advice is based on [this](http://stackoverflow.com/a/18779641). If you look toward the bottom it says:
>On x64 environments, the last update in the list fixes errors about missing compilers and
>
>error **MSB4019**: The imported project "C:\Microsoft.Cpp.Default.props" was not found.

**Comment by happilymarrieddad** [comment]
is it possible to get an already complied node_module of oracledb or will that not work??

**Comment by bchr02** [comment]
Since you are having all these issues, I decide to test out your setup as closely as possible.

I can now confirm that the following steps work on a fresh install of Windows Server Standard 2008 x64 with SP2:

Steps in order (with links to downloads):
* [32 bit Visual Studios 2008](http://download.microsoft.com/download/A/5/4/A54BADB6-9C3F-478D-8657-93B3FC9FE62D/vcsetup.exe)
* [32 bit Node 0.12.7](https://nodejs.org/dist/v0.12.7/node-v0.12.7-x86.msi)
* [32 bit Python 2.7](https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi) (when installing choose the option to add python to path)
* [32 bit Oracle Instant Client Basic ZIP Version 11.2.0.4.0](http://download.oracle.com/otn/nt/instantclient/11204/instantclient-basic-nt-11.2.0.4.0.zip)
* [32 bit Oracle Instant Client SDK ZIP Version 11.2.0.4.0](http://download.oracle.com/otn/nt/instantclient/11204/instantclient-sdk-nt-11.2.0.4.0.zip)
* uncompress Oracle Instant Client Basic ZIP into C:\oracle\instantclient
* uncompress Oracle Instant Client SDK ZIP into C:\oracle\instantclient

* C:\oracle\instantclient should now look like this:
![image](https://cloud.githubusercontent.com/assets/10158167/9775920/524ee15a-5721-11e5-9db1-6d9fb6458533.png)

* Next, open a command prompt and type:
````
set OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient\sdk\include
set path=C:\oracle\instantclient;%path%
npm install oracledb
````

and it should work. It did for me.

**Comment by happilymarrieddad** [comment]
awesome. thanks so much!!! I will start on it on a bare install of windows 2008 server

**Comment by bchr02** [comment]
My pleasure. Let us know how it goes.

By the way, in response to:
>is it possible to get an already complied node_module of oracledb or will that not work??

Yes, it is possible. I have done it [here](https://github.com/oracle/node-oracledb/issues/189#issuecomment-137874533)

When I compiled a 64bit oracledb using Visual Studio 2013 and moved it to another computer, the only thing I needed on the other computer was [Microsoft Visual C++ 2010 Redistributable Package (x64)](http://www.microsoft.com/en-us/download/details.aspx?id=14632)

**Comment by happilymarrieddad** [comment]
I know it works on my windows 7 machine after being compiled.. the compiling is the issue I'm having. thanks so much again man I think this should work... studio it just taking forever to install

**Comment by happilymarrieddad** [comment]
dang now I'm getting this... lol I did a clean install and just copied and pasted from your post.

![selection_017](https://cloud.githubusercontent.com/assets/6416323/9776410/3040a5a0-5715-11e5-8fec-57905f9cca80.png)

**Comment by bchr02** [comment]
Are you sure you set the include directory correctly?

**Comment by happilymarrieddad** [comment]
yes, I will post a screen shot in the morning when I am in the office and I have access to the server again. I've been trying to install it on a Windows 7 VM but I'm having trouble there as well lol. could you post a tutorial on windows 7 and I can just copy the node_module to the windows server 2008 box. thanks!

**Comment by happilymarrieddad** [comment]
this is the error i'm getting in windows 10

![capture](https://cloud.githubusercontent.com/assets/6416323/9780706/646f5df6-5749-11e5-8f52-7fcefe94d6a2.PNG)

**Comment by happilymarrieddad** [comment]
the above is Node 0.12.7 and when I use node 4.x I get this really long message  

![capture2](https://cloud.githubusercontent.com/assets/6416323/9780953/325dcb6a-574c-11e5-820e-98ac6d5c9706.PNG)

**Comment by cjbj** [comment]
Node 4 requires NAN 2 which is not yet included by node-oracledb.

**Comment by pvenkatraman** [comment]
Please check the python version (python --version)  this should be 2.7 or higher.  The python directory should be in path.

**Comment by happilymarrieddad** [comment]
which version of node should I use?

**Comment by happilymarrieddad** [comment]
the python version I'm using is 2.7.10 Thanks!

**Comment by happilymarrieddad** [comment]
0.12.7 64bit complies just fine now to see if it connects!!!!!!!!!!

**Comment by bchr02** [comment]
I just double-checked my instructions and it's all correct. I am not sure why it's not working for you.

>I've been trying to install it on a Windows 7 VM but I'm having trouble there as well lol. could you post a tutorial on windows 7 and I can just copy the node_module to the windows server 2008 box. thanks!

The steps outlined in [my video](https://www.youtube.com/watch?v=I23XTkUMrtM) should help you but since Node.js was recently updated to version 4, instead of downloading the node version that shows up as the most recent, you'll need to click "Other Downloads" then at the top click ../ to go up one directory and search for version v0.12.7 x64, alternatively here is the [direct download link.](https://nodejs.org/dist/v0.12.7/x64/node-v0.12.7-x64.msi). 

After you compile, you can take the node_modules folder and copy it to your Windows Server 2008 box and the only things you will need to install is the same version of [Node.js x64](https://nodejs.org/dist/v0.12.7/x64/node-v0.12.7-x64.msi) and [Microsoft Visual C++ 2010 Redistributable Package (x64)](http://www.microsoft.com/en-us/download/details.aspx?id=26999)

I tested what I write above to a computer with a fresh install of Windows Server Std 2008 SP2 x64 and it works.

**Comment by happilymarrieddad** [comment]
Thanks so much for your help bchr02. It compiles now just fine!!! I'm going to test the adapter with the oracledb which is a LOT farther than I've gotten before. Thanks!!!!!!

**Comment by bchr02** [comment]
you are welcome. I am glad you are making some progress. I just made some edits to my [last post](https://github.com/oracle/node-oracledb/issues/194#issuecomment-139274709) because I noticed there were a few steps missing.

For testing, I recommend keeping it simple by editing and using the repos example files. These two:
* [dbconfig.js](https://github.com/oracle/node-oracledb/blob/master/examples/dbconfig.js)
* [select1.js](https://github.com/oracle/node-oracledb/blob/master/examples/select1.js)

**Comment by happilymarrieddad** [comment]
ok now I'm getting this AFTER compiling. Do you know what it is?

![selection_018](https://cloud.githubusercontent.com/assets/6416323/9792456/6710b376-579d-11e5-8c40-041cdc7022a1.png)

**Comment by bchr02** [comment]
maybe a path issue. did you set your path?

please provide the full results of the following command:
> echo %path%

**Comment by happilymarrieddad** [comment]
![selection_020](https://cloud.githubusercontent.com/assets/6416323/9792810/5a7b89d6-579f-11e5-88a2-a49b9bd5a015.png)

**Comment by bchr02** [comment]
What version of Visual Studio did you compile with?

If you downloaded everything to c:\oracle\instantclient why is D:\Oracle\Ora11g\bin there?

**Comment by happilymarrieddad** [comment]
D:\Oracle\Ora11g\bin is for the database I'm trying to connect to. I didn't put it there. I compiled with Visual Studio 2013. Should I add the oracle instant client files to the path?

**Comment by happilymarrieddad** [comment]
Ok, I added the instant client stuff to the path and it works but I'm now getting a no listener error lol

**Comment by bchr02** [comment]
in command prompt type:
>set path=C:\oracle\instantclient;%path%

so, you don't have to keep doing that each time you open a command prompt you should update your path variable in System Settings and make sure that C:\oracle\instantclient appears first.

**Comment by happilymarrieddad** [comment]
ok I did that and this is what I am getting now

![selection_021](https://cloud.githubusercontent.com/assets/6416323/9793125/191b3d68-57a1-11e5-84ac-3c6690684f5b.png)

**Comment by happilymarrieddad** [comment]
ok I think this is closed. It's working!!!!!!!!

**Comment by bchr02** [comment]
Awesome news!

**Comment by happilymarrieddad** [comment]
Ok

1) Install Windows 7 and run all the updates
2) Install Node 0.12.7 64bit
3) Install Python 2.7
4) Grab the 64bit v.12 Oracle Instant Client SDK and Basic and put them in the C:\oracle\instantclient folder
5) Add to path using the method above by bchr02
6) Run npm install oracledb
7) copy folder to Windows 2008 Server
8) Install C++ 2010 Redistributable  on 2008 Server box
9) Add OracleInstantClient to System Variables
10) Enjoy!!!!

**Comment by cjbj** [comment]
@bchr02 great work - thanks.

**Comment by happilymarrieddad** [comment]
This is already closed but I wanted to say make sure your oracledb client files are in     c:\oracle\instantclient      or it won't work.

**Comment by cjbj** [comment]
@happilymarrieddad the client files can be anywhere as long as OCI_*_DIR are set as needed.  If setting them is problematic for whatever reason, then putting the client in `c:\oracle\instantclient` will work because it is the default location the node-oracledb installer looks for.
