### ISSUE TITLE
install oracledb error

### ISSUE THREAD

**Issue by lusicong** [oracle/node-oracledb#195]
npm install -g oracledb

C:\Users\lusicong\AppData\Roaming\npm\node_modules\oracledb>if not defined npm_c
onfig_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

c:\users\lusicong\appdata\roaming\npm\node_modules\oracledb\src\njs\src\njsOrac
le.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保
存为 Unicode 格式以防止数据丢失 (..\s
rc\njs\src\njsIntLob.cpp) [C:\Users\lusicong\AppData\Roaming\npm\node_modules\o
racledb\build\oracledb.vcxproj]
c:\users\lusicong\appdata\roaming\npm\node_modules\oracledb\src\njs\src\njsConn
ection.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文
件保存为 Unicode 格式以防止数据丢失 (
..\src\njs\src\njsIntLob.cpp) [C:\Users\lusicong\AppData\Roaming\npm\node_modul
es\oracledb\build\oracledb.vcxproj]
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
C:\Users\lusicong\.node-gyp\0.12.7\Release\node.lib : fatal error LNK1136: 无效
或损
坏的文件 [C:\Users\lusicong\AppData\Roaming\npm\node_modules\oracledb\build\orac
led
b.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)

**Comment by lusicong** [comment]
C:\Users\lusicong.node-gyp\0.12.7\Release\node.lib : fatal error LNK1136: 无效
或损
坏的文件 [C:\Users\lusicong\AppData\Roaming\npm\node_modules\oracledb\build\orac
led
b.vcxproj]
gyp ERR! build error

**Comment by lusicong** [comment]
node -v 
v0.12.7
node-gyp -v
v2.0.2

**Comment by lusicong** [comment]
Visual Studios 2013

**Comment by lusicong** [comment]
![abc](https://cloud.githubusercontent.com/assets/13955593/9753646/5d6efad6-56f2-11e5-93cc-e18343664670.png)

**Comment by cjbj** [comment]
Interesting. https://msdn.microsoft.com/en-us/library/ms173715.aspx

Emacs is showing a mix of different encodings for different source files.  Hmm

**Comment by lusicong** [comment]
During the install,I cann't edit the source files,and after that error all files ware deleted.

**Comment by cjbj** [comment]
My colleague reproduced the C4819 warnings. His compilation succeeded despite them.  The messages were warnings which we will fix. 

I don't know whether they are the cause of the LNK1136 error in your environment.

Try cloning the git repository and editing the files with warnings.  Each has some stray whitespace-ish characters in a comment. Then install from your local directory with 'npm install ./node-oracledb'.

**Comment by lusicong** [comment]
I tried to change the files to utf-8. The warnings ware disappear.
bug also LNK1136 error.

C:\Users\lusicong\.node-gyp\0.12.7\Release\node.lib 
this file is 0kb.

C:\Users\lusicong\.node-gyp\0.12.7\Release\node.lib : fatal error LNK1136: 无效
或损
坏的文件 [C:\Users\lusicong\AppData\Roaming\npm\node_modules\oracledb\build\orac
led
b.vcxproj]

**Comment by lusicong** [comment]
![11111](https://cloud.githubusercontent.com/assets/13955593/9756922/1ba911ae-5710-11e5-936c-73c344d1e67d.png)

**Comment by lusicong** [comment]
![12345](https://cloud.githubusercontent.com/assets/13955593/9757044/be7be32a-5710-11e5-8d72-98226a43ccbc.png)

**Comment by akq** [comment]
your node-gyp is broken, try to reinstall it.

**Comment by lusicong** [comment]
Reinstall also dosn't work!

npm uninstall -g node-gyp
unbuild node-gyp@3.0.1

**Comment by octokyle** [comment]
node.js v0.12.3 works for me. You may have a try.

**Comment by octokyle** [comment]
You may check whether your node.js and oracle instant client are both X64 version or both X86 version.

**Comment by octokyle** [comment]
@lusicong You may check whether your node.js and oracle instant client are both X64 version or both X86 version.

**Comment by lusicong** [comment]
Done! Thanks a lot. I change the node.js X64 to X86, and vc2003 express to community.
![image](https://cloud.githubusercontent.com/assets/13955593/9806502/ca361a6a-5877-11e5-9625-2d770269a5e4.png)

**Comment by cjbj** [comment]
Thanks everyone for helping on this.
