### ISSUE TITLE
Any way to set up timeout for connection? 

### ISSUE THREAD

**Issue by wolfeatyou** [oracle/node-oracledb#199]
i catch "Timeout while sql execute" exception after 3 second delay

**Comment by cjbj** [comment]
@wolfeatyou There's nothing specific in node-oracledb for timing out.  There are various Oracle DB controls such as resource management that can be used.  If you play around with Node timeouts and node-oracledb's [break()](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#break), let us know how it goes.

**Comment by Stono** [comment]
@cjbj - break() can only be used on a connection object, however if you can't connect - you just get stuck in a massive timeout, and the application doesn't reply to SIGTERM.

So what I believe @wolfeatyou (and me) are looking for, it a way to say "try and connect for 5 seconds, then error"

**Comment by dmcghan** [comment]
@Stono This question was closed almost 2 years ago. Could you please open a new one? Please include details about whether you're using a connection pool or not.

**Comment by cjbj** [comment]
@Stono it's being tracked in https://github.com/oracle/node-oracledb/issues/671.  Very platform dependent.

**Comment by cjbj** [comment]
For future searchers finding this topic, in a [previous issue](https://github.com/oracle/node-oracledb/issues/627#issuecomment-281901869) I'd mentioned there are Oracle Net settings that may be useful:

> I have on my 'to look at' list the OCI call [timeout attributes](http://docs.oracle.com/database/122/LNOCI/handle-and-descriptor-attributes.htm#GUID-2B6D06A7-8EDF-46FF-BDEF-320D293DCA65__GUID-43CFAD8D-AF5F-4A97-B51B-D696B6CF4D1C)  They map to [Oracle Net parameters ](https://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#GUID-4A19D81A-75F0-448E-B271-24E5187B5909) (note the unit is different) which you could set in a sqlnet.ora file right now without waiting for node-oracledb to have an API to set them.

>

**Comment by dmcghan** [comment]
@nalbion This thread was originally related to a SQL execution timeout issue (likely related to Workspace Manager). It then moved on to connection.break() not working, which is being tracked in #671. What you're asking about is queuing on getConnection, right?

There's already [a queue on getConnection](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connpoolqueue). Its timeout can be configured via [queueTimeout](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-3219-oracledbqueuetimeout).

**Comment by nickperkinslondon** [comment]
queueTimeout does not work!
That's the point.
It always waits 60 seconds!

**Comment by dmcghan** [comment]
@nickperkinslondon Do you have a test case that demonstrates that it's not working?

**Comment by cjbj** [comment]
The doc at https://oracle.github.io/node-oracledb/doc/api.html#connectionha now has just a bit more on the topic of preventing the establishment of connections over the wire to the DB from appearing to hang if there is a network issue.  E.g. use SQLNET.OUTBOUND_CONNECT_TIMEOUT in a sqlnet.ora file (on the Node.js tier).  To prevent the same when executing statements there are other parameters mentioned, or you can now use [`callTimeout`](https://oracle.github.io/node-oracledb/doc/api.html#propconncalltimeout) directly in node-oracledb.

**Comment by rnogueira-namoadigital** [comment]
hi @cjbj do you know if there is any solution better then a Promise race like @nalbion suggested before? I tried the callTimeout but it does not worked

**Comment by cjbj** [comment]
@rnogueira-namoadigital see my immediately [previous answer](https://github.com/oracle/node-oracledb/issues/199#issuecomment-540244697).

**Comment by rnogueira-namoadigital** [comment]
please, do you have any straightforward example using callTimeout?

**Comment by Raphzor** [comment]
Kind of a bit old thread, but if someone comes up here like I did, here is a short example that might help to solve the timeout issue, as @rnogueira-namoadigital asked for:

```ts
import * as OracleDB from "oracledb";

export class OracleDBHandler {
  static async execute(query: string): Promise<OracleDB.Result<unknown>> {
    try {
      const connection = await OracleDB.getConnection({
        user: process.env.RDS_USERNAME,
        password: process.env.RDS_PASSWORD,
        connectionString: `${process.env.RDS_HOSTNAME}/${process.env.RDS_SID}`,
      });
      connection.callTimeout = 10 * 1000; // Reduced the timeout to 10 secs

      const rows = await connection.execute(query, [], {
        outFormat: OracleDB.OUT_FORMAT_OBJECT,
      });
      await connection.close();

      return rows;
    } catch (exception) {
      console.error("Got an error during OracleDb connection: ", exception);
    }
  }
```

**Comment by alexlambdas** [comment]
> @cjbj would something like this work, or is it just likely to leave orphan connections?
> 
> ```js
> return Promise.race([
>     oracledb.getConnection(attributes).then(conn => {
>         console.info('Connected to Oracle');
>         return conn;
>     }),
>     new Promise((resolve, reject) => {
>         setTimeout(() => {
>             reject('Timed out waiting for Oracle connection');
>         }, 5000);
>     })
> ]);
> ```

woouu @Raphzor this is elegant, cute and excelent solution, I don´t know why I had not thought about it. thanks a lot!!

**Comment by cjbj** [comment]
@alexlambdas 

The Oracle net attributes I mentioned in an earlier answer are still a prime option.  From https://oracle.github.io/node-oracledb/doc/api.html#dbcalltimeouts :
>To limit the amount of time taken to establish new connections to Oracle Database, use Oracle Net options like [SQLNET.OUTBOUND_CONNECT_TIMEOUT](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-0857C817-675F-4CF0-BFBB-C3667F119176) in a [sqlnet.ora](https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin) file or [CONNECT_TIMEOUT](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-F20C5DC5-C2FC-4145-9E4E-345CCB8148C7) in a [connection string](https://oracle.github.io/node-oracledb/doc/api.html#easyconnect).
