### ISSUE TITLE
Make the binary module compatible with Node 0.12 & io.js 1.0.x using NaN

### ISSUE THREAD

**Issue by raymondfeng** [oracle/node-oracledb#2]
NaN provides the abstraction to keep C/C++ addon code compatible with underlying V8 APIs. See: https://github.com/rvagg/nan.

As a reference, we use NaN in https://github.com/strongloop/strong-oracle.

**Comment by vkurchatkin** [comment]
+1

**Comment by hertzg** [comment]
:+1:

**Comment by jeffm13** [comment]
+1

**Comment by Qard** [comment]
+1

**Comment by pkoretic** [comment]
+1

**Comment by mkozjak** [comment]
+1

**Comment by jma3s** [comment]
+1

**Comment by eyko** [comment]
+1

**Comment by toddhay** [comment]
+1 for the io.js support.  Any sense as to when you might get to this or should I stick with NodeJS for the time being?

**Comment by hertzg** [comment]
@cjbj Any update for this issue?

**Comment by cjbj** [comment]
I can't give an ETA, sorry.  

I notice no one has submitted a PR adding support. What should I read into that? :)

**Comment by alexsantos** [comment]
+1

**Comment by rightson** [comment]
+1

**Comment by bjouhier** [comment]
+1

**Comment by iwater** [comment]
+1

**Comment by volkmarbuehringer** [comment]
+1

**Comment by MathieuClusiau** [comment]
+1

**Comment by mjhasbach** [comment]
+1

**Comment by syrinx2012** [comment]
+1

**Comment by amarauk00** [comment]
+1

**Comment by flakekun** [comment]
+1

**Comment by raviv** [comment]
+1

**Comment by kdclaw3** [comment]
+1

**Comment by needforspeed** [comment]
+1

**Comment by haruitk** [comment]
NaN v1.7.0 supports node v0.12. Does that make any difference?

**Comment by Bigous** [comment]
@haruitk look at the pull request #43

**Comment by haruitk** [comment]
@Bigous so the fix is on the way, as soon as its approved. Thanks!

**Comment by danielb2** [comment]
:+1:

**Comment by scottchantry** [comment]
+1

**Comment by Dahriel** [comment]
+1

**Comment by andrewbrereton** [comment]
+1

**Comment by xuxiankun** [comment]
+1

**Comment by juancancela** [comment]
+1

**Comment by zxqfox** [comment]
:+1:

**Comment by cjbj** [comment]
We've merged https://github.com/oracle/node-oracledb/pull/43  

node-oracledb now builds with Node.js 0.10, 0.12 and also with io.js.
