### ISSUE TITLE
Compatibillity for Node JS v4.0.0

### ISSUE THREAD

**Issue by teraspace** [oracle/node-oracledb#200]
By default my linux has updated NodeJS to 4.0.0 from 0.12.7. And oracledb driver crash with segmentation fault.

**Comment by mikollaay** [comment]
+1

**Comment by cjbj** [comment]
@teraspace You'd need to recompile the add-on after a Node.js upgrade, just like normal.  However you will need to wait for a while. See https://github.com/oracle/node-oracledb/issues/198

**Comment by mikron** [comment]
+1
