### ISSUE TITLE
INSERT ALL does not update last column

### ISSUE THREAD

**Issue by mandeluna** [oracle/node-oracledb#201]
Does this affect anyone else?

*Example schema:*

```
CREATE TABLE FACILITY_HISTORY
  (
	CODE VARCHAR2(10 CHAR) NOT NULL,
	USER_ID VARCHAR2(255 CHAR) NULL,
  	DESCRIPTION VARCHAR2(255 CHAR) NULL,
	ATTRIBUTE VARCHAR2(255 CHAR) NULL,
	OLD_VALUE VARCHAR2(255 CHAR) NULL,
	NEW_VALUE VARCHAR2(255 CHAR) NULL,
  	CHANGE_DATE TIMESTAMP NULL
  )
```

*Sample query:*

```
INSERT ALL
    INTO FACILITY_HISTORY (user_id, code, description, attribute, old_value, new_value )
    VALUES ('::1', 'RGA28', 'Changed', 'address', '"A galaxy far, far, far away"', '"New Address"')
    INTO FACILITY_HISTORY (user_id, code, description, attribute, old_value, new_value )
    VALUES ('::1', 'RGA28', 'Moved', 'location', '{"type":"Point","coordinates":[-104.7,50.4]}', '{"type":"Point","coordinates":[-104.3,50.5]}')
SELECT * FROM DUAL
```

*Result:*

`select * from facility_history`

CODE  |  USERID  |  DESCRIPTION | ATTRIBUTE  |  OLD_VALUE  |  NEW_VALUE | CHANGE_DATE
--------- | ------------ | -------------------- |------------------| ------------------ | ----------------- | -----------------
RGA28|	::1 |	Moved |	location |	{"type":"Point","coordinates":[-104.7,50.4]} | {"type":"Point","coordinates":[-104.3,50.5]}	| 11-SEP-15 05.36.42.707355000 AM
RGA28 |	::1 |	Changed | address |	"A galaxy far, far, far away" |	(null) | 11-SEP-15 05.36.42.707281000 AM

When using node, new_value is always (null) for the last value in the "values" clause of the "INTO <table_name>" expression.

If I copy and paste the expression from the node debugger into SQL developer the query behaves as expected.

**Comment by cjbj** [comment]
Post a node-oracledb testcase so we can help.

**Comment by cjbj** [comment]
Closing due to lack of response from filer.
