### ISSUE TITLE
Parens in wrong places actually crashes node itself

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#203]
"INSERT INTO mylobs (id, b) VALUES (:id, EMPTY_BLOB()) RETURNING (b) INTO (:lobbv)",

The last two sets of parens around (b) and (:lobbv) crash node with a crash report.  When removed, all works as expected.

(I know the parens aren't necessary, but you probably don't want it to crash.  :-)

**Comment by cjbj** [comment]
@sanfords thanks for the report

**Comment by cjbj** [comment]
@sanfords This is fixed in node-oracledb 1.2
See the release notes at https://blogs.oracle.com/opal/entry/node_oracledb_1_2_0
