### ISSUE TITLE
Simplified interface around blobs

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#204]
Thank you for this excellent library.

The interface around blobs/clobs is much more complicated than similar libraries for other engines. A simplified interface would be most welcome. Perhaps one that treats buffers as node-oracledb does other Plain Old Types. :-)

And if not a simpler interface, perhaps someone could provide an example for insert/select/update from/to/from a Buffer object?

Thanks again!

**Comment by bjouhier** [comment]
Returning LOBs as a single chunk would be an anti-pattern for node.

The `lob.iLob` member exposes a much simpler API:
```
lob.iLob.read(function(err, data) { ... });
```
Would it be possible to officially _bless_ this API for people who want a simpler API and who do not _just pipe_ the result.

**Comment by cjbj** [comment]
@bjouhier sounds like a good goal. We should talk!

**Comment by sanfords** [comment]
I can't really use the record until the blobs arrive anyway, so I'd be just fine with the select waiting until they arrive.  (Or are inserted/updated.)  Perhaps an option for `waitForLobs:true` could allow for both worlds: Users who want to use pipes, and users who don't.

**Comment by bjouhier** [comment]
Been thinking a bit more about this issue. Streams are great because they make it possible to read and write very large LOBs (hi-res images, videos) but LOBs are also often used for small/medium size pieces of data (JSON and XML payloads, HTML documents, low-res images, etc). For all these usages it would be nice to have the simpler API.  

Ideally, the API should let you pass CLOBs as strings and BLOBs as Buffers, in both directions, very much like VARCHAR and RAW.

**Comment by cjbj** [comment]
Also see #188

**Comment by sanfords** [comment]
I've been under the impression that medium/large blobs are more efficient as BFILEs.  I'm planning on switching to these for my medium/large blobs once they're supported.

**Comment by cjbj** [comment]
@sanfords so far, BFILE support has been lower down on the priority list. But we'll keep in mind that you have a desire to try it.

**Comment by sanfords** [comment]
Wonderful!  But I actually desire to use it extensively.  :-)

**Comment by sagiegurari** [comment]
Take a look at: https://github.com/sagiegurari/simple-oracledb#usage-query
it will read all BLOB and CLOB fields when you query and return you string/Buffer instead.
naturally you need to be careful not to load too much as CLOBs can be gigs in size and you will not have enough memory.
But for normal use cases, it should be fine.

**Comment by cjbj** [comment]
I'm going to close this issue now.  There was a big LOB revamp in the 1.12.0-dev release (only on GitHub). Checkout the [doc](https://github.com/oracle/node-oracledb/blob/v1.12.0-dev/doc/api.md#lobhandling)!  You can easily insert Strings and Buffers with the native support.  (The query fetchAsString part got delayed, but you can get Strings and Buffers directly from PL/SQL OUT binds now).  There are some size-gotchas with older Oracle clients. We will continue to smooth things out. Please hammer on it and give feedback before we freeze and do an npm release.  Thanks!

**Comment by yamanksin** [comment]
// return all CLOBs as Strings
  oracledb.fetchAsString = [ oracledb.CLOB ];

Take a look at :http://oracle.github.io/node-oracledb/doc/api.html#lobhandling
