### ISSUE TITLE
wrong number result with extra 0000000001 at the tail

### ISSUE THREAD

**Issue by haiwen-shaw** [oracle/node-oracledb#206]
when query a number field from a view, some results look strang: it add a 0000001 or 000003 at the tail. for example, the right result should be 0.57, but it returned **0.57000000000001** instead:

`[ { HOLDTIME: 0.5700000000000001 } ] `
`[ { HOLDTIME: 2990.4500000000003 } ]`

some other records returned with a 000000003.
I'm sure that the value in database is correct and I verified with `to_char` . I could not find out the pattern for now. but I got the **same records** with this kind of problem every time.

**Comment by cjbj** [comment]
A JavaScript number precision issue?

The [fetchAsString](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbfetchasstring) and [fetchInfo](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#executeoptions) features might be useful for you.

**Comment by haiwen-shaw** [comment]
Yes, `fetchAsString` fix this issue. thank you!
