### ISSUE TITLE
LOB stream emits close before end

### ISSUE THREAD

**Issue by bjouhier** [oracle/node-oracledb#208]
I'm getting a premature `close` event when reading a LOB. I'm expecting to get one or more `data` events followed by an `end` event and then a `close` event. 

Instead I'm getting the `data` events followed by a `close` event.

**Comment by cjbj** [comment]
Thanks @bjouhier

**Comment by cjbj** [comment]
Fixed in node-oracledb 1.2.  
Release notes are at: https://blogs.oracle.com/opal/entry/node_oracledb_1_2_0
