### ISSUE TITLE
Make installation easier

### ISSUE THREAD

**Issue by atiertant** [oracle/node-oracledb#21]
hi,
i think the driver installation could be easier :

installing mysql driver is done using only one command : **npm install mysql**

for installing an oracle driver you should :
- install instant client
- install the sdk
- set PATH
- set some environment variables 
- solve compilation errors...

couldn't instant client include binary for node driver?
node driver can't try to detect default folder path if environment variables aren't set ?

**Comment by cjbj** [comment]
The next batch of fixes include changes for Linux installation.  The Oracle libraries will be searched for in standard locations, and RPATH can be used so you won't need to set LD_LIBRARY_PATH at runtime.

**Comment by cjbj** [comment]
I'm going to close this issue. See
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instrpm
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#linuxadv

There are no plans to bundle Instant Client binaries.
New issues can be created for specific requirements, similar to #18
