### ISSUE TITLE
oracledb on change event

### ISSUE THREAD

**Issue by happilymarrieddad** [oracle/node-oracledb#214]
Is there any on change event or oracle? I was hoping to avoid having to poll a database for changes and only update when there is actually a change. Thanks!

**Comment by dmcghan** [comment]
@happilymarrieddad Check out my post on Oracle's Continuous Query Notification. Although it's not integrated with the driver, it can be used to avoid polling: https://jsao.io/2015/02/real-time-data-with-node-js-socket-io-and-oracle-database/

**Comment by pyhedgehog** [comment]
Yes, Oracle has [Publish-Subscribe feature](http://docs.oracle.com/database/121/LNOCI/oci09adv.htm#LNOCI16716). And [there](http://cx-oracle.readthedocs.org/en/latest/connection.html#Connection.subscribe) is example binding for it.
