### ISSUE TITLE
how to compile with older version of GLIBC_2.14 ?

### ISSUE THREAD

**Issue by Cheyenne55** [oracle/node-oracledb#217]
Hello,

I would like to know if it possible to compile oracledb with an older version of glibc (2.12 for instance) and how to proceed?

Upgrading glibc is not always possible in the target environment.

Thanks!

**Comment by cjbj** [comment]
Hi @Cheyenne55 what's the problem/error and what environment are you using?

**Comment by Cheyenne55** [comment]
I installed oracledb with nodejs on Ubuntu 14.04 LTS (with GLIBC 2.14) at home.
Then I copied the installation to a platform Red Hat 6.6 (which has only the 2.12 version) at my workplace.

The error comes when starting the node server :

version `GLIBC_2.14' not found (required by /node_modules/oracledb/build/Release/oracledb.node)

**Comment by cjbj** [comment]
I'd look at building in a compatible environment, e.g. the free [Oracle Linux](http://public-yum.oracle.com/), perhaps running it inside [VirtualBox](https://www.virtualbox.org/) if don't have a machine to dedicate to it.
