### ISSUE TITLE
Windows Install clarification

### ISSUE THREAD

**Issue by bchr02** [oracle/node-oracledb#22]
@cjbj I noticed within: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin That it guides one to use everything 64bit for the install. This might confuse someone needing to install it on a 32bit Windows system. I actually have a 32bit server that I successfully got node-oracledb running on.

Unless there is something I am missing, I think it might make sense to at least reference the fact that it's possible to install on 32bit Windows OS's.

**Comment by cjbj** [comment]
@bchr02 I can add a note.

**Comment by bchr02** [comment]
Also please see my comments here: https://github.com/oracle/node-oracledb/issues/7#issuecomment-74775275 which will likely need some additional changes. Thanks.

**Comment by cjbj** [comment]
@bchr02 There are a lot of combinations of Windows architecture, compiler and instant client that theoretically work but have not been tested - for example you should be able to use Instant Client 11g.  Windows install steps might always need to be more open due to the number of permutations that would be impossible to document sanely. 

One goal I had for the instructions is to create a set of steps that will bootstrap a beginner, and allow the examples in the examples dir to be used (hence the -g and setting NODE_PATH).  When/if we are officially on npmjs.com I will revisit this general direction.

**Comment by bchr02** [comment]
I understand and this makes sense but you should at least make it known when something is not a requirement.

Why even be specific then when specifying what to install and include the architecture? Why not just leave that out?

**Comment by bchr02** [comment]
I would try to at least incorporate what I write here: https://github.com/oracle/node-oracledb/issues/7#issuecomment-74775275 because not knowing that version 12 of Instant Client is needed in order to "skip this step" would cause major headaches to a beginner.

**Comment by cjbj** [comment]
I will be reviewing the steps. Mentioning some specifc details allows the set of instructions to be consistent.  For example I could reference x64 everywhere.

Regarding 12c, I still have a feeling 11g can be used if the tool chain is correct.

**Comment by bizybuck** [comment]
I was receiving the error

Error:  The specified module could not be found.
D:\\[project_path]\node_modules\oracledb\build\Release\oracledb.node
....

To resolve the issue, I referenced this [similar problem](https://github.com/joeferner/node-oracle/issues/90) and used [Dependency Walker](http://www.dependencywalker.com/) to determine that OCI.dll and IESHIMS.dll could not be found in D:\\[project_path]\node_modules\oracledb\build\Release\oracledb.node.  I updated the system path to include C:\Program Files\Internet Explorer and D:\oracle\instantclient\basic (I moved everything from D:\oracle\instantclient\basic\instantclient_12_1 to D:\oracle\instantclient\basic), then uninstalled and reinstalled oracledb.

**Comment by bizybuck** [comment]
Also, working through step 6.5 from VS 2013 Express's Developer command Prompt for VS2013 launched as an Administrator worked well.

**Comment by cjbj** [comment]
@bizybuck had you set PATH to include Instant Client before you hit the problem?

**Comment by bizybuck** [comment]
@cjbj I had, yes.  This may be a one-off but just making you're aware of the possibility of this occurring in case other people encounter the same issue.

**Comment by cjbj** [comment]
@bizybuck thank you

**Comment by cjbj** [comment]
@bchr02 I've made some tweaks to the Windows install doc including referencing 32 bit installs.  Comments are welcome.  I'll close this specific issue for now.
