### ISSUE TITLE
Is it ok to use Q.all ?

### ISSUE THREAD

**Issue by rgilliar** [oracle/node-oracledb#220]
I'm using the following code

    let promises = _.map(payload.values, (value: IMeasurementItem) => {
		return qo.execute(sql,
			[ measurementId, value.measuredValue, value.referenceValue],
			{ autoCommit: false },
			this.connection);						
	});									
	return Q.all(promises);

qo is a simple Promise wrapper:

    export default class Qo {

        static execute(sql: string, bindParams, options, connection) {
            return Q.Promise<IOracleResult>(function(resolve, reject) {
                connection.execute(sql, bindParams, options, function(err, results) {
                    if (err) {
                        return reject(err);
                    }
                   resolve(results);
               });
          });
       }
   }

Is it ok to do this, or will I run into problems since the oracledb driver probably uses multiple threads ?

**Comment by dmcghan** [comment]
@rgilliar I wrote about a similar topic here: https://jsao.io/2015/03/making-a-wrapper-module-for-the-node-js-driver-for-oracle-database/

Almost all async APIs are going to use multiple threads or processes. Generally speaking, promises should work with all of these APIs.
