### ISSUE TITLE
connect didn't get any response or error message

### ISSUE THREAD

**Issue by Kotama520** [oracle/node-oracledb#222]
hi, i follow the simple query example to make a .js, but when I run it , I didn't get any response or error message, here is my code, how can I fix it?  thanks.

```
var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "x",
    password      : "x",
    connectString : "ip:port/x"
  },
  function(err, connection)
  {
    if (err) { console.error(err.message); return; }

    connection.execute(
      "SELECT * FROM table",
      [110],  // bind value for :id
      function(err, result)
      {
        if (err) { console.error(err.message); return; }
        console.log(result.rows);
      });
  });
```

**Comment by cjbj** [comment]
@Kotama520 Tell us about your environment.

With your testcase I get the error "ORA-01036: illegal variable name/number" because you are passing a bind value without having a matching bind variable in the SQL statement.

**Comment by Kotama520** [comment]
Win7 64bit

I remove the bind value and still can not get any message. I tried to add some console log in the oracledb.js

console.log(oracledb);
var oracledb_ins = new oracledb.Oracledb();
console.log(oracledb_ins);
console.log("test");

//output result
{ Oracledb: [Function: Oracledb],
  Connection: [Function: Connection],
  Pool: [Function: Pool],
  ResultSet:[Function: ResultSet],
  ILob: [Function: ILob] }

it looks like new oracledb.Oracledb() didn't success.

**Comment by cjbj** [comment]
I'd be interested to hear what you are trying to attempt.  You seem to have strayed from the examples?

**Comment by Kotama520** [comment]
I just tried to figured out that why I can't get any response or error message, I thought it didn't connect success.

**Comment by cjbj** [comment]
Follow the examples and tell us more about what you have installed and how you are running it.

**Comment by cjbj** [comment]
Closing: no response for a month.
