### ISSUE TITLE
Do not error out when requesting connections

### ISSUE THREAD

**Issue by milaniliev** [oracle/node-oracledb#224]
Hi,

We hit a weird behavior in node-oracledb recently having to do with built-in connection pooling. It seems it returns an error when all DB pool connections are in use and another is requested.

In my mind, a database pool is used like so: for every new independent DB operation, check a connection out of the pool, do operations, release connection. The purpose of the pool is to provide a fixed number of connections to more than that many requests without bottlenecking all of them behind a single long request.

So, in an application with hundreds of small requests per hour, we set the connection pool at max 10. We expected that if all 10 connections are busy and an 11th `getConnection()` call is made, that request will block until a connection is available and then the callback will be executed. What happens instead is the callback is called immediately with the `ORA-24418: Cannot open further sessions` error. 

Is there a chance that this behavior can be changed, either by default or as an option to `getConnection`? I'm not sure what usage patterns benefit from the current behavior; it seems like the blocking behavior is a more common case. I'm willing to draw up the PR for this if it sounds like a reasonable change.

Thanks for node-oracle!

Milan Iliev

**Comment by dmcghan** [comment]
@milaniliev I just added support for connection request queueing at the pool level to [orawrap](https://github.com/OraOpenSource/orawrap). It limits the number of active connections in a pool to the poolMax setting. I'd love it if you could give it a test and/or provide some feedback.

**Comment by cjbj** [comment]
(Following up #225 here as well)  @milaniliev @mrapczynski we hear you and will work towards a good solution. Some people want a retry limit, others want a timeout.  For the moment, implementing your own queue is powerful and controllable.

The underlying OCI blocking mode (see #225) could be exposed - however this would block each thread trying to get a session.  You can try it yourself by cloning from GitHub, changing the mode, then install with 'npm install ./node-oracledb'.

**Comment by cjbj** [comment]
Also see https://github.com/oracle/node-oracledb/issues/126

**Comment by krismohan** [comment]
OCI offers a blocking mode (actually default in OCI). But the challenge in using it for node is that the getConnection/doDBwork/releaseConnection are not atomically done by any method, continuously sitting inside a worker thread of Node. All of these three operations are async methods that get on/off the worker threads. If we provide blocking option on getConnection, if at anytime all the connections in the pool are busy (have been checked out), and there are more requests from all the threads, they just block on the getConnection call and do not release even the worker threads. So the ones which need to release the connections are waiting for free worker threads which they are not going to get. Leads to deadlock.

Please see suggestions from cjbj and dmcghan.
