### ISSUE TITLE
 Ability to change the session pool mode

### ISSUE THREAD

**Issue by mrapczynski** [oracle/node-oracledb#225]
Very early on when first starting to use this excellent driver, I would get bit by the `ORA 00018 - Maximum number of sessions exceeded` problem even when I was properly releasing connections. I figured out how to use Promises effectively to force a large user-induced SQL workload into a queue to make it go away. And I thought I would have to live with that that, i.e. no blocking to wait for an available connection. But then looking through the OCI docs, and there is a session pool attribute that can block and wait when the session pool is full:

https://docs.oracle.com/database/121/LNOCI/ociaahan.htm#LNOCI17845

Is it possible to make OCI_ATTR_SPOOL_GETMODE acessible at the Node level so we can determine what kind of session pool behavior we want?

I'm fine with the current default and not suggesting you change it, but I think it would be to have some optional control over this so that if I want to introduce a blocking wait at the driver level, then I can.

I prefer to keep the pool constrained say for example 8 connections for 8 CPUs since they should be async I/O operations outside of the Node event loop, and there could be situations when I need the session pool to expect some contention and deal with it.

**Comment by dmcghan** [comment]
@mrapczynski I understand you're looking for an OCI level solution for this issue and that you've already implemented a workaround in your own code... However, I added connection request queueing at the pool level to [orawrap](https://github.com/OraOpenSource/orawrap). It limits the number of active connections in a pool to the poolMax setting. I'd love it if you could give it a test and/or provide some feedback.

**Comment by cjbj** [comment]
@mrapczynski I will close this but followup on the very similar #224

**Comment by cjbj** [comment]
Also see https://github.com/oracle/node-oracledb/issues/126
