### ISSUE TITLE
Is there a roadmap available ?

### ISSUE THREAD

**Issue by doberkofler** [oracle/node-oracledb#229]

**Comment by cjbj** [comment]
We reevaluate priorities after each release based on how we are seeing node-oracledb used, and what features requests are made here. We will keep the active release cycle going. From scanning the other GitHub issues you can see common priorities (installation, Node 4, simplified api for smaller LOBs, bugs etc)  Is there anything specific you want to know about? Don't forget you can contribute code (under the [OCA](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md) at any stage.

**Comment by doberkofler** [comment]
I personally love to have a simple roadmap in the projects I use but do understand that it is very much a moving target.

**Comment by cjbj** [comment]
@doberkofler we're going to try creating an issue for each upcoming release containing the things we want to work on.  It is a moving target and we want to keep the frequent release cycle, so there can be no guarantees.  The bigger tasks (like seeing whether we can release binaries) will be ongoing projects. I'll get to this after the weekend.

**Comment by doberkofler** [comment]
Thank you for your feedback and regarding the release of binaries I fully agree that this would be a huge improvement for this project.

**Comment by cjbj** [comment]
@doberkofler thanks should go to @bchr02 who is making great progress on binaries in #18

**Comment by cjbj** [comment]
@doberkofler See #234
