### ISSUE TITLE
Remove outFormat.OBJECT to simplify the API

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#23]
In https://github.com/oracle/node-oracledb/issues/6#issuecomment-74690171 @jeffm13 suggested removing the optional outFomat.OBJECT behavior. In a future release, column names will be available elsewhere so the user application will be able to construct the equivalent objects that outFormat.OBJECT provides.

Any comments/votes/thoughts?

**Comment by zorrofox** [comment]
I'd like to remove it, or just as the outFormat.OBJECT is the default behavior.

**Comment by cjbj** [comment]
@zorrofox removing it, or keeping it as the default seem opposite ideas.  Can you comment more about your reasons?

**Comment by zorrofox** [comment]
Sorry, I miss understood your idea. My opinion is use the outparam.OBJECT as the default beehives but not to remove it. It's very convenient.

**Comment by cjbj** [comment]
@zorrofox your vote is noted.

**Comment by cj10** [comment]
I think that both outFormats should be retained. I would use ARRAY in some circumstances and
OBJECT in others.

ARRAY should remain the default because it is quicker, and because OBJECT is useful
only if the resultset has suitable (and unique) column names.

**Comment by bchr02** [comment]
I personally like using outFormat.OBJECT and wouldn't mind it being the default. In my opinion, being able to refer to columns by their name makes ones code more readable and understandable, which to me is most important.

**Comment by cjbj** [comment]
So far we are not planning to remove OBJECT. I'll leave this open in case anyone else wants to comment or offer off-the-wall suggestions.

**Comment by cjbj** [comment]
I'm closing this.  There is enough support for OBJECT as being a usable and understandable format.
Note: for better performance use the default ARRAY format.
