### ISSUE TITLE
Pre-Built Developer VM

### ISSUE THREAD

**Issue by bchr02** [oracle/node-oracledb#230]
I think it would be useful to a lot of people if (at some point) Oracle offered a VirtualBox pre-built VM with:
- Oracle Linux
- Oracle Database XE
- Node.js

Does anyone else agree?

**Comment by cjbj** [comment]
I'd like to see +1's.

The VM we'd aim to augment is the "Database App Development VM" http://www.oracle.com/technetwork/community/developer-vm/index.html#dbapp

**Comment by doberkofler** [comment]
+1

**Comment by Bigous** [comment]
+1

**Comment by uadev** [comment]
Docker image should be available as well

**Comment by Buto** [comment]
+1

**Comment by hparicha** [comment]
+1

**Comment by dmcghan** [comment]
I would like to see Node.js added to the App Dev VM as well. But as far as installs go, adding Node.js is quite simple. I wrote an updated blog post on this topic to help. I added Node.js via NVM which helps with running different versions of Node.js as needed. I hope it helps:
https://jsao.io/2015/10/creating-a-local-sandbox-for-node-js-and-oracle-database/

**Comment by derickbailey** [comment]
has anyone built a docker image, yet? if not, i may take a stab at this in the next few days. not sure how successful I'll be, since i'm pretty new to docker... but i want this for one of my big apps i'm currently supporting, and potentially a new app i'm building.

**Comment by bchr02** [comment]
Yes, I did. But just oracledb and the client libraries. I didn't install the full Oracle database. I'll add it to docker hub so you can have a look soon. Not in front of my computer right now.

**Comment by derickbailey** [comment]
@bchr02 that's exactly what i need, thanks! :)

I'm already using https://github.com/wnameless/docker-oracle-xe-11g for the oracle install in docker. it works very well. recommended for anyone that wants the fastest way to stand up an oracle xe for development purposes.

**Comment by bchr02** [comment]
@derickbailey Here it is: [Example of node-oracledb within Docker](https://github.com/bchr02/oracledb_example)

**Comment by derickbailey** [comment]
@bchr02 that's great! thank you for that :) I should be able to get my docker needs met with that as an example, quite easily.

**Comment by cjbj** [comment]
@bchr02 good work.

For reference, also see https://technology.amis.nl/2016/04/06/create-oracledb-enabled-node-js-application-container/ and https://technology.amis.nl/2016/04/10/create-and-run-docker-container-with-node-js-and-node-oracle-db-driver-from-windows-using-vagrant-and-virtualbox/

**Comment by sharadraju** [comment]
Closing this as it is not an enhancement we can be doing in this repo.

**Comment by cjbj** [comment]
There's a docker image at https://docs.oracle.com/en-us/iaas/oracle-linux/developer/index.htm which may be useful to some developers.
