### ISSUE TITLE
OS X "El Capitan": DYLD_LIBRARY_PATH not working unless SIP is turned off

### ISSUE THREAD

**Issue by cristobal** [oracle/node-oracledb#231]
In the latest release off `OS-X` using the `DYLD_LIBRARY_PATH` is not possible unless *[System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection)* (SIP) is disabled.

Meaning that setting the `DYLD_LIBRARY_PATH` will have no effects on spawned sub shells and therefore using the node client is no longer possible unless one turns off (SIP) as explained [here](http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html).

This is true in most of the cases, where one starts a subprocess that will run and use the `node-oracledb`  module. This issue meant for discussion on any solutions on how to circumvent disabling SIP or should it just be added as a section to the README and wiki for OS X.

**Comment by cjbj** [comment]
Cross referencing: https://github.com/oracle/node-oracledb/issues/149

**Comment by cjbj** [comment]
@cristobal did you try the script from #419? Any comments on impact, security, useful etc?

**Comment by cristobal** [comment]
Sorry been busy at work, but will try it later today and get back at you with a comment later or tomorrow morning.

**Comment by cristobal** [comment]
Ok finally got time to try out the script. The script works however i did need to modify it to suit my need. However the command for extracting the `$VER` in the `updatepaths` function should be modified. Since it's not guaranteed to work correctly, as far as i can see. Should be this instead.

```
local VER=`ls $IC_DIR/libclntsh.dylib.* | awk '{print $NF'} | xargs basename | sed s/libclntsh.dylib.//g`
```

Then you are always guaranteed to get out the version string.

**Comment by cristobal** [comment]
Hmm however thinking a bit further on the topic if this was a part of post install step of the *node oracledb client*. Should it not just be done for all OS platform just not OS X. As far as i know it's best to avoid the use of *LD_LIBRARY_PATH* at all.

**Comment by cjbj** [comment]
Let's keep this open to track a good resolution

**Comment by cjbj** [comment]
Closing; see #149

**Comment by cristobal** [comment]
:+1:

**Comment by cjbj** [comment]
Instant Client 12.1 for OS X is now available from: http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html

Updated installation instructions are at: http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst
