### ISSUE TITLE
Get CLOB values synchronically

### ISSUE THREAD

**Issue by frtrev** [oracle/node-oracledb#232]
I am having trouble reading CLOBs, I checked the example and it seems pretty easy, but since it explains getting the data is Async, and the it only reads one row and one field, is there any way to force it to read synchronously? Or if I could see an example of how to read a two or three column table loop, you know for each row, read the value, if its a CLOB do this, if its a regular data type do this instead.

**Comment by octokyle** [comment]
What about reading rows into a result set? I ever wrote a case that accesses CLOB values in a result set. https://gist.github.com/octokyle/82fb14f5b0e26e56ca7e

**Comment by sagiegurari** [comment]
This should help you
https://github.com/sagiegurari/simple-oracledb#usage-query
