### ISSUE TITLE
node-oracledb 1.3 

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#234]
Heads up that we want to keep a short release cycle without too much destabilization before the big Oracle OpenWorld conference, which is fast approaching

These are the things we might get to look at:

New features:

  - Add attributes to show the Oracle Database version of a connection, and the run-time Oracle Client library version in use.  Useful for testing.

Bugs:

  - ~~See if we can pin down the aggregate row bug (#80)~~ Fix not planned for 1.3.  Cause was identified but we need further discussion on the solution
  - Look at the 4K DML RETURNING issue (#226)
  - Any other crashes etc that get reported before release

The rest of our time is for long term, ongoing investigation post 1.3 (i.e. has no ETA):
  - What is involved in delivering precompiled binaries (we need to sync up with @bchr02)
  - NAN 2 / Node 4 (@bigous is doing all the hard work)
  - Scope out a LOB string/buffer API for small LOBs

I'll update this issue if there are any changes to the plan.

(PS let me know if you're coming to the OOW conference in San Francisco)

**Comment by jeveloper** [comment]
Thanks ! 
Please fix that bug related to some sort of class that no longer exists/works in NodeJS 4 /IoJS 3.x .

**Comment by cjbj** [comment]
@jdeveloper I don't understand? Did you mean NAN 2 support?  I mentioned that above.

**Comment by Bigous** [comment]
@jeveloper You can try with the pull request #227, but it's not safe to run in production yet. Accessors are working as expected but fail at assertion of returned type to JS environment and the garbage collector from 4.1.1 crashes when you use raw types. If you does not use these features, you are good to go.

**Comment by jeveloper** [comment]
Thanks @Bigous , seems like i'd rather wait for 1.3 with that fix.
Referring to NAN 2 support and overall stability under nodejs 4.x

**Comment by cjbj** [comment]
@jeveloper See my first entry on this issue: NAN 2 is NOT on the roadmap for 1.3.  We want NAN 2 just as much as you, but there is [work to be done](https://github.com/oracle/node-oracledb/pull/227#issuecomment-146319060). If this work gets done early, then great, but I won't hold up 1.3 waiting for it.

@jeveloper try the PR out.  @Bigous has updated it and we need feedback.

**Comment by Bigous** [comment]
Just to complement, Now the PR is safe to be used.

**Comment by cjbj** [comment]
I updated the initial entry of this issue to point out that #80 isn't going to be fixed in 1.3.  The cause was identified but we need to discuss and explore solutions.

**Comment by cjbj** [comment]
Closing since 1.3 is out.  I'll create a 1.4 plan soon.
