### ISSUE TITLE
Lint JavaScript code with eslint

### ISSUE THREAD

**Issue by doberkofler** [oracle/node-oracledb#235]
I would suggest adding a lint step for all the existing JavaScript code in the project to:
* find problematic patterns
* find code that doesn't adhere to certain style guidelines

**Comment by cjbj** [comment]
@doberkofler Are there any current issues?  I run a linter.

**Comment by doberkofler** [comment]
@cjbj A few very minor style inconsistencies but no issues, I nevertheless think, that some strict style guidelines as part of a CI workflow would help to keep the JS in shape when multiple users work on the project. Clearly this is not an important issue and was just an idea.

**Comment by cjbj** [comment]
The big questiona are which linter and which style should be used?

**Comment by doberkofler** [comment]
@cjbj I'm a little biased but would definitely use eslint and i personally adopt the good old jslint style.

**Comment by cjbj** [comment]
@doberkofler I'm closing this now. I've beefed up my lint rules and will fix a few coding issues in the examples for the next release.

**Comment by doberkofler** [comment]
@cjbj excellent!
