### ISSUE TITLE
OS X getConnection requires "hostname" entry in host file. 

### ISSUE THREAD

**Issue by timschambers** [oracle/node-oracledb#238]
Hi,

Everytime I tried using oracledb.getConnection, the console kept spitting back "ORA-21561: OID generation failed". This error apparently had something to do with the hosts file. 

After some research, I solved the issue with this answer:
http://stackoverflow.com/a/21332056

The issue is that it should not have applied to this problem: I was not connecting to localhost but to a remote Oracle Database. 

Does anyone know why this step is needed?

Also: in case that link expires, the solution is to type "hostname" in the shell, and then edit /etc/hosts to have the following line. 

<code>127.0.0.1 localhost < insert result from the hostname command here >  </code>

And if the line starting with "127.0.0.1" is already present, just append the "hostname" result to its end.

**Comment by cjbj** [comment]
@timschambers this is an annoying 'paper-cut' issue that has bitten me too.  The Oracle Net component on the client doesn't like a non fully configured machine. I feel there should be some tolerance; I have previously raised it with the Oracle Net devs to see if improvements can be made.  I will continue to see if I can get them to bump its priority.

**Comment by timschambers** [comment]
here's hoping they can put in the effort to get this change in.

thank you, cjbj.

**Comment by cjbj** [comment]
There are valid reasons why a unique name is needed.  I'll see what I do to improve the situation.

**Comment by gvenzl** [comment]
I had the very same issue just today. I connect to a remote database on a virtual environment with an IP starting with. Why do I need to add my local machine name to the hosts file 127.0.0.1 entry if the names are totally different?

**Comment by cjbj** [comment]
@gvenzl it's important for unique generation of GUIDs
