### ISSUE TITLE
Error: NJS-003: invalid connection

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#240]
I'm importing a few thousand records individually using node.async.  I've got a record with about 30 columns, one of which is a blob.  I perform the insert and it works very well, similar to this:

```
SQL-3 ALTER TABLE zft ADD (n1 NUMBER,n2 NUMBER,b1 BLOB,b2 BLOB)
SQL-4 INSERT INTO ZFT (b1,b2,n1,n2) VALUES (EMPTY_BLOB(),EMPTY_BLOB(),:n1,:n2) RETURNING b1,b2 INTO :b1,:b2
VAR-4 { b1: { type: 2007, dir: 3003 },  b2:{ type: 2007, dir: 3003 }, n1:10, n2:20 }
```

From the result, I then stream to the lob from a Buffer with the following:

```
var streamBufferToOracle = function(sourceBuffer, lob, next) {
  var self = this;
  var passthrough = new stream.PassThrough();

  passthrough.on('end', function(err) {
    console.log("passthrough end", err || "success");
    return next(err);
  });

  passthrough.on('error', function(err) {
    console.log("passthrough error", err);
    return next(err);
  });

  lob.on('error', function(err) {
    console.log("lob error: ", err);
    console.log(lob);
  });

  passthrough.pipe(lob);
  passthrough.end(sourceBuffer);
}
```

This runs **really** fast.  Until somewhere between 200 and 4000 inserts.  And then my .js dies with this error:

```
Error: NJS-003: invalid connection
    at Error (native)
    at Lob.close ([]/node_modules/oracledb/lib/oracledb.js:103:15)
    at []/node_modules/oracledb/lib/oracledb.js:87:14
```

Shooting in the dark: If I comment out [line 103 of oracledb.js](https://github.com/oracle/node-oracledb/blob/master/lib/oracledb.js##L103), it works fine.

My max connection count is set at 300 in the pool, and I've verified that my high watermark for the actual connection count is ~75.  I have confirmed that on.lob('close'...) is called before the release is called.

I'm stuck.  Any ideas?

**Comment by sanfords** [comment]
The solution:

```
var streamBufferToOracle = function(sourceBuffer, lob, next) {
  var self = this;
  var passthrough = new stream.PassThrough();

  lob.on('error', function(err) {
    console.log("lob error", err);
    return next(err);
  });

  lob.on('close', function(err) {
    console.log("lob close", err);
    return next(err);
  });

  passthrough.write(sourceBuffer, function() {
    passthrough.pipe(lob);
    passthrough.end();
  });
}
```

**Comment by wmertens** [comment]
I'm also hitting this problem.

@sanfords @cjbj I'm confused as to how the solution works, and also why this is not documented as the way to upload blobs.

I don't see the functional difference between pipe+end vs write+pipe?

**Comment by cjbj** [comment]
@wmertens I'm not sure if this is the same as the cases we've seen when the connection gets garbage collected if the connection isn't referenced in the execute callback.

Doc & examples PR's would be great.

On another note: that incorrectly emitted Writeable 'close' event is going away in node-oracledb 1.6.  Streams only has 'close' on Readable: https://nodejs.org/api/stream.html

**Comment by wmertens** [comment]
I think it turned out to be unfinished files that I was creating streams from and using to upload as a BLOB. In any case I can't reproduce it any more and I didn't change my call logic, which turns out to be very similar to what oraclewrap does.
