### ISSUE TITLE
Make node-oracledb package installable with npm

### ISSUE THREAD

**Issue by gintsgints** [oracle/node-oracledb#241]
It would be very nice if we do not need to compile this package our self. How about getting it to npm repository?

This is needed for travis setup.  https://github.com/cbandy/travis-oracle

So we can make test builds on oracle related stuff.

**Comment by dmcghan** [comment]
@gintsgints The package is available via npm:
https://www.npmjs.com/package/oracledb

Or did I miss understand you?

**Comment by cjbj** [comment]
@gintsgints follow #18
