### ISSUE TITLE
Lowercase keys in results

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#242]
Per the docs `3.2.7 outFormat`: `The property name follows Oracle's standard name-casing rules. It will commonly be uppercase, since most applications create tables using unquoted, case-insensitive names.`

Is there any way to force that to lowercase, short of walking all results and re-assigning the keys?

Thanks!

**Comment by dmcghan** [comment]
@sanfords Just give your columns aliases wrapped in double quotes:

```sql
select actual_column_name as "whateverYouLike"
from some_table
```

**Comment by sanfords** [comment]
Fair 'nuf.  Thanks!
