### ISSUE TITLE
Simple Oracle Document Access in Node.js?

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#243]
The [SODA (Simple Oracle Document Access) for Java](https://github.com/oracle/SODA-FOR-JAVA) has been released on GitHub.  How useful would it be to have a SODA API in Node.js?

**Comment by bchr02** [comment]
It would be cool if you guys could create a controller/connector for [swagger-node](https://github.com/swagger-api/swagger-node). Maybe SODA would make that easier to accomplish so +1.

**Comment by mrapczynski** [comment]
@cjbj That's way cool - definitely would be worth having when JSON is a native data format in the language as is the case with Node.
