### ISSUE TITLE
Only 100 records retried 

### ISSUE THREAD

**Issue by kumarmugu** [oracle/node-oracledb#244]
Hi,

I am using node-oracledb driver (version 0.4.1) for my application. Select query is returning maximum of 100 records only.  

I have noticed that it is defined  in \src\njs\src\njsOracle.cpp
#define MAX_ROWS 100
Line no: 35 

It is reverting more records if I increase this defined count in the same file.

Can we configure it in our application?
OR
is it resolved in the latest versions ?

Thanks in advance,
K.Mugunthan

**Comment by cjbj** [comment]
See [maxRows](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbmaxrows). However I'd recommend using a [ResultSet](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsetclass)

If possible, upgrade to the latest node-oracledb, which is 1.2 at time of writing.

**Comment by kumarmugu** [comment]
Thanks for your help @cjbj . I will use maxRows attribute or ResultSet. I am unable to upgrade to latest version immediately. Lets do it in next phase. 

Regards,
K.Mugunthan.
