### ISSUE TITLE
a require problem ../build/Debug/oracle_bindings

### ISSUE THREAD

**Issue by cai520senlin** [oracle/node-oracledb#246]
Cannot find module '../build/Debug/oracle_bindings',is this problem is i didn't install vs2012?

**Comment by cjbj** [comment]
This is not a node-oracledb problem.  You probably want [Joe Ferner's driver](https://github.com/joeferner/node-oracle/issues/265) or [StrongLoop's driver](https://github.com/strongloop/strong-oracle/issues/53)

**Comment by cjbj** [comment]
P.S. Use [node--oracledb](https://www.npmjs.com/package/oracledb)!
