### ISSUE TITLE
How to change the expired password?

### ISSUE THREAD

**Issue by a-langer** [oracle/node-oracledb#248]
Connection is used this way:

``` javascript
oracledb.getConnection(
  {
    user          : "name",
    password      : "expired_password", // password has expired
    connectString : "localhost/XE",
  },
// this code
```

How do I get a request to change the password?

**Comment by dmcghan** [comment]
@a-langer Typically an admin would do this for you with code that looks like the following given a username of "hr" and a new password of "secret".
```sql
alter user hr identified by secret;
```

Admins can also create a profile with an unlimited password life time and assign the profile to you:
```sql
create profile service_account_profile limit password_life_time unlimited;
alter user hr profile service_account_profile;
```

**Comment by a-langer** [comment]
Thanks for the reply.
In my case, need a way to change a user's password without administrator intervention. The method "getConnection" supports the change old password?

**Comment by dmcghan** [comment]
@a-langer At this point, because the password is expired, you'll first need to connect to the database as an admin user to reset the other user's password. 

In the future you can reset your own password before it expires via the code provided.

**Comment by a-langer** [comment]
The usual method of changing password is not working?
For example in "SQLPLUS" I did:
```javascript
SQLPLUS name/expired_password@localhost/XE
Changing password for expired_password
Old password: expired_password
New password: new_password
Retype new password: new_password
Password changed
```

Through oracledbэто can be done?

**Comment by dmcghan** [comment]
@a-langer The SQLPlus output you're showing doesn't look right. It should look like this:
sqlplus username/password

SQL*Plus: Release 12.1.0.2.0 Production on Thu Oct 15 16:23:29 2015

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

ERROR:
ORA-28001: the password has expired

Changing password for username
New password: 
Retype new password: 
Password changed

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

**Comment by a-langer** [comment]
Yes, I agree. I was writing from memory and made a mistake. There is a way to change the password using oracledb as in sqlplus?
```
ERROR:
ORA-28001: the password has expired
Changing password for username
New password: 
Retype new password: 
Password changed
```

**Comment by dmcghan** [comment]
@a-langer I don't think so, not like SQLPlus. But why not use SQLPlus one time and then automate the process moving forward with oracledb?

**Comment by cjbj** [comment]
The 'connect-and-change-an-expired-password-in-one-operations' feature isn't implemented in node-oracledb.

For reference, it is implemented in PHP OCI8; see the second example at http://php.net/oci_password_change.

**Comment by a-langer** [comment]
@dmcghan Do you offer a way to run "SQLPLUS" from nodejs using "child_process.exec" ? Please describe in detail. I do not understand what it is about.

**Comment by a-langer** [comment]
@cjbj There are plans to implement a 'connect-and-change-an-expired-password-in-one-operations' in the node-oracledb ?

**Comment by cjbj** [comment]
@a-langer I left this open as an 'enhancement'.  It is not high on the list - but feel free to persuade us of its importance.   Do you often connect to Node with different credentials?  How often are you likely to encounter an expired password?

Or ... you could submit a PR with a patch!

**Comment by a-langer** [comment]
@cjbj I face this problem constantly. My project uses a user authorization by Oracle. 
Each user uses his account to connect to the database. Lifetime account password periodically expires.
Because of the lack of opportunity to change the expired password had to stop work on my project.
Send a PR with the patch I can't, because I don't know C++, sorry :)

**Comment by cjbj** [comment]
@a-langer I understand about C++.  Perhaps you can suggest a method signature that would work for you?  Do you want an overloaded getConnection, or a new method?

**Comment by a-langer** [comment]
@cjbj  
Need a new method to change the password, for example:
```javascript
oracledb.ChangePassword(     // new method "ChangePassword"
  {
    user            : "name",  // user login
    old_password    : "old_password", // old password
    new_password    : "new_password" // new password
  }
)
```
To use need a way to monitor error codes Oracle (Like in PHP http://php.net/oci_password_change). 
For example, this method may be:
```javascript
 oracledb.err()  // fictional method of obtaining the error code Oracle
```
At the moment I don't know the way to get error codes Oracle, but in the end it should look like this:
```javascript
oracledb.getConnection(
  {
    user          : "name",
    password      : "expired_password", // password has expired
    connectString : "localhost/XE"
  },
function(err, connection)
  {
    if (err) {
            var ORACLE_OCI_ERR = oracledb.err() // fictional method of obtaining the error code Oracle
            if (ORACLE_OCI_ERR = '28001'){ // "ORA-28001: the password has expired"
              oracledb.ChangePassword(     // new method "ChangePassword"
                {
                  user            : "name",
                  old_password    : "expired_password", // old password
                  new_password    : "new_password" // new password
                }
              )
              console.log('password is changed')
            }
    }
    // this code
  }

```

**Comment by sagiegurari** [comment]
The error object should hold the error code (error.code) and I don't think we need to add C like syntax like oracledb.err or that windows getLastError() method and stuff like that.
And change password (should be changePassword) should get a callback with error in case of issues.
naturally no '_' in property names.

**Comment by a-langer** [comment]
@sagiegurari This code is not the final implementation. Colback is omitted in order not to complicate the example. The characters '_' removed.

**Comment by sagiegurari** [comment]
Think this a more js approach:
````js

oracledb.getConnection(connectOptions, function (conErr, connection) {
    if (conErr) {
        if (conErr.code === oracledb.errorCodes.SOMEPASSWORD_ERROR_CODE) {
            oracledb.changePassword({
                user: 'myuser',
                oldPassword: 'old password value',
                newPassword: 'new password valeu'
            }, function (passErr) {
                if (passErr) {
                    console.log('unable to change password')
                } else {
                    console.log('changed password worked.')
                }
            })
        } else {
            //different error handling
        }
    } else {
        //continue flow
    }
});
````
But need to think from security point of view if this is something you should do via nodejs oracle driver or not (I have no idea if it is recommended)

**Comment by a-langer** [comment]
@sagiegurari Yes, your code is more similar to the style of Javascript.
With security problems should not be. Even the "sqlplus" and "SQL-developer" can change the password when you connect.

**Comment by cjbj** [comment]
To change the password like that requires connecting first.  But if you can't connect because the password has expired then ...

Hence there is a connect-and-change-password-operation in Oracle.  So we need two modes just like PHP's: http://php.net/manual/en/function.oci-password-change.php 

Brainstorming: there could be an `oracledb.connectChangePassword(username, oldpw, newpw, connectString, function cb(err, connection))` method and a `connection.changePassword(oldpw, newpw, function cb(err))` method.

**Comment by a-langer** [comment]
@cjbj I like one versatile way to change the password. Method ```oracledb.connectChangePassword()``` is quite suitable for this. 
For example:
When you first connect you need to track the error code "28001":
```javascript
if (conErr.code === oracledb.errorCodes.SOMEPASSWORD_ERROR_CODE) { // err code = 28001
oracledb.connectChangePassword(username, oldpw, newpw, connectString, function cb(err, connection))
}
```
For any password change to replicate this method:
```javascript
oracledb.connectChangePassword(username, oldpw, newpw, connectString, function cb(err, connection))
```

**Comment by cjbj** [comment]
Node-oracledb 2.2 supports [password changing](https://oracle.github.io/node-oracledb/doc/api.html#changepassword), and '[connect-and-change-an-expired-password-in-one-operation](https://oracle.github.io/node-oracledb/doc/api.html#changingpassword)' .

**Comment by srirambtechit** [comment]
> The usual method of changing password is not working?
> For example in "SQLPLUS" I did:
> 
> ```js
> SQLPLUS name/expired_password@localhost/XE
> Changing password for expired_password
> Old password: expired_password
> New password: new_password
> Retype new password: new_password
> Password changed
> ```
> 
> Through oracledbэто can be done?

Thanks, I can able to reset password, Oracle 8i though
