### ISSUE TITLE
simple-oracledb: a node-oracledb wrapper providing a simplified API

### ISSUE THREAD

**Issue by sagiegurari** [oracle/node-oracledb#249]
The current API is pretty complex and requires lots of coding, especially when you are readying many rows and each row got LOBs.
it is an async mess and if I have to do it everywhere I pull JSONs from the database it will be pretty painful.
So I wrote a library: https://github.com/sagiegurari/simple-oracledb to help resolve most simple use cases for nodejs working with oracle (well.... my use cases anyway, but from the LOB issue #19 I saw it was a pretty common use case).
I know I can't push it to the oracledb repo since it is kind of going against the oracle design which is more correct from memory and performance point of view when working on huge amount of data, but most use cases are not like that.

Right now I added a query that works like the execute('select ....', ....) but the output is an array of objects with fields.
All rows are read (regardless if it is using rows or resultset), all CLOBs are read and converted to string, all BLOBs are read and converted to Buffer.
https://github.com/sagiegurari/simple-oracledb#usage-query

Although I only support a simplified query right now, I'm working on it and soon will push a simpler update/insert as well.

Hope it helps others.

**Comment by sagiegurari** [comment]
Added support for INSERT with CLOB/BLOB types as well.
No need to stream the data to the output bindings after the INSERT is finished.

**Comment by cjbj** [comment]
@sagiegurari I wanted to acknowledge the work you have done.  I haven't had a chance to do more than scan it. 

If there are features that should be added to node-oracledb we should discuss them. @dmcghan will be seeing what bits of his https://github.com/OraOpenSource/orawrap make sense to be included with node-oracledb, e.g. queuing for pool.getConnection requests.

**Comment by sagiegurari** [comment]
Thanks, it is still evolving based on my needs which mainly have to do with JSONs stored in CLOB (what can I say, js developer abusing a relational database :laughing: )
That is why I originally wrote that I'm not entirely sure it fits an official api, but definitely would help nodejs developers.

2 things that do come to mind right away, is that i made the callback optional in the connection.release and pool.terminate as there is really nothing that you can do in those callbacks to handle the issue, so why bother make it mandatory.

Anyhow, it is very much still work in progress and I have many ideas to make it more nodejs like.
Once it is more complete, I'll post here the list of features and we can review to see what can go into an official api and what should stay as an extension.

**Comment by cjbj** [comment]
@sagiegurari I've taken the liberty of updating the issue topic.  Looking forward to your contributions to node-oracledb

**Comment by cjbj** [comment]
@sagiegurari I'm going to close this now.
If you update your package.json to depend on node-oracledb, your wrapper will appear on https://www.npmjs.com/package/oracledb (yes I know you might not want to do that for various build-related reasons)
