### ISSUE TITLE
Installation - Node Version

### ISSUE THREAD

**Issue by BuiltInParris** [oracle/node-oracledb#25]
When I went to install it, it wouldn't let me npm install unless I was using version 0.10 of NodeJS. I didn't see this explicitly stated in the documentation, which is relatively important considering the current version is 0.12.

**Comment by cjbj** [comment]
Indeed it's not spelled out yet. When #2 is fixed I will review the prerequistes.  INSTALL.md currently says "The node-oracledb release has been tested with Node.js 0.10.35 on 64-bit Oracle Linux." and package.json checks for 0.10.  These are big hints but we can improve it.

**Comment by cjbj** [comment]
Please review the 0.4.1 doc
