### ISSUE TITLE
Ubuntu 15.04 Error on installation 

### ISSUE THREAD

**Issue by rozzwalla** [oracle/node-oracledb#252]
I followed the installation guide for Linux on Zip Files, the Ubuntu Server already has the latest node-gyp and nodejs installed but still encountering an issue during installation.

Below is the stack trace. Executed the insallation as 

sudo -E npm install oracledb 
sudo npm install oracledb

Both are generating the same issue

../src/njs/src/njsOracle.cpp: In static member function ‘static void Oracledb::Async_AfterCreatePool(uv_work_t*)’:
../src/njs/src/njsOracle.cpp:915:29: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/osboxes/.node-gyp/4.2.1/include/node/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException (tc);
                             ^
oracledb.target.mk:115: recipe for target 'Release/obj.target/oracledb/src/njs/src/njsOracle.o' failed
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory '/root/WebstormProjects/oracle-storage/node_modules/oracledb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/WebstormProjects/oracle-storage/node_modules/oracledb
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "oracledb"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WebstormProjects/oracle-storage/npm-debug.log

**Comment by cjbj** [comment]
You'll need https://github.com/oracle/node-oracledb/pull/227 to use Node 4.
NPM should have given you a warning that Node 4 isn't (yet) supported.
