### ISSUE TITLE
Is it possible to create bindVars dynamically?

### ISSUE THREAD

**Issue by unotecjapan** [oracle/node-oracledb#254]
I'm a newbie with JavaScript and Node.js.
I tested blob ins while referring to the document.

I created a simple table to my DB(Oracle 11g).
```
CREATE TABLE FILETEST(
	NAME	VARCHAR2(60),
	FILE_DATA	BLOB
);
```
```javascript
connection.execute(
	"INSERT INTO filetest (name, file_data) VALUES (:name, EMPTY_BLOB()) RETURNING file_data INTO :lobbv",
	{ name: req.files.myfile.name, lobbv: {type: oracledb.BLOB, dir: oracledb.BIND_OUT} },
	{ autoCommit: false },
```

It worked well.

Now, I want to create bindVars dynamically. Like below.
```javascript
	var obj = new Object();
	var obj2 = new Object();
	obj2.type = oracledb.BLOB;
	obj2.dir = oracledb.BIND_OUT;
	obj.name = req.files.myfile.name;
	obj.lobby = obj2;

connection.execute(
	"INSERT INTO filetest (name, file_data) VALUES (:name, EMPTY_BLOB()) RETURNING file_data INTO :lobbv",
	obj,
	{autoCommit: false},
```
But it shows this error.
```
	ORA-01036: illegal variable name/number
```
Is it possible to create bindVars dynamically?

I'm using oracledb1.3, node.js v0.12.7, Oracle11g r2.

**Comment by cjbj** [comment]
Works for me. I modified examples/clobinsert1.js:

```javascript
    binds = { id: 1, lobbv: {type: oracledb.CLOB, dir: oracledb.BIND_OUT} };
    console.log(binds);

    var obj = new Object();
    var obj2 = new Object();
    obj2.type = oracledb.CLOB;
    obj2.dir = oracledb.BIND_OUT;
    obj.id = 1;
    obj.lobbv = obj2;
    console.log(obj);

    connection.execute(
      "INSERT INTO mylobs (id, c) VALUES (:id, EMPTY_CLOB()) RETURNING c INTO :lobbv",
//      binds,
      obj,
      { autoCommit: false },  // a transaction needs to span the INSERT and pipe()
      function(err, result)
      {
```

**Comment by unotecjapan** [comment]
Thanks for reply, it also works with BLOB?
I can't understand what's the difference between my code and your code expect for BLOB/CLOB.

**Comment by unotecjapan** [comment]
Yesterday, I tested with CLOB.
However it also didn't work ...
```
ORA-01036: illegal variable name/number
```
Is this a issue of my environment?

Win7, oracledb1.3, node.js v0.12.7, instant client 12.1.0.1.0
Oracle 11g R2

I'll change the version of instant client, and retry...

**Comment by cjbj** [comment]
@unotecjapan check the console.log() output of your object vs. a hand-constructed object - you can see the two console.log() calls in my code snippet.

If you still have problems, then post a small, complete script that has the problem.
