### ISSUE TITLE
Procedure returning multiple curosrs

### ISSUE THREAD

**Issue by narendra-agashe** [oracle/node-oracledb#257]
I am calling a procedure and this procedure returns multiple cursors, How can i fetch rows from these cursors. current example shows fetching rows from a single cursor.

Thanks!!

**Comment by bmassouda** [comment]
I am having the same issue.  Is this supported in the current release.  Any help would be much appreciated.

**Comment by praneethkk** [comment]
I am looking for support on the same issue. Does this support oracle procedures returning multiple cursors?

**Comment by sagiegurari** [comment]
do you mean?
```sql
returning col1, col2 into var1, var2
```

**Comment by bmassouda** [comment]
more like proc returning multiple cursors (eg. proc_name(cur1_out, cur2_out, cur3_out)  where cur1_out, cur2_out, cur3_out are cursors).

**Comment by narendra-agashe** [comment]
Yes, Brian explained it well. That's what I am looking to do. I could be missing something from the example but if I am pointed to the relevant example, it will be a huge help.
Thanks!

**Comment by cjbj** [comment]
@narendra-agashe @praneethkk  there's no magic to it.  Follow something like https://github.com/oracle/node-oracledb/blob/master/examples/refcursor.js, passing each BIND_OUT ref cursor to a function like the given fetchRowsFromRS().  You can choose whether to fetch completely from each cursor before proceeding with the next cursor, or whether you want to interleave fetches from different ref cursors.
