### ISSUE TITLE
Reading UDT's

### ISSUE THREAD

**Issue by milindkhurd** [oracle/node-oracledb#259]
We use UDT's as arguments and return types to procedure calls. Is there a way to use UDT's with node.js?

E.g
select value(t) from vp_customer t where pkey = 123;

The view here returns a custom user defined data type e.g. CUSTOMER created as an object type in oracle. 

I am expecting a json object e.g.
{"CustUniqueid": "1234567890", "Name": "Sample", "Address":{"HouseNo":"1234", "ZipCode":"77057"}, "Company": "Node.js"}

**Comment by ecowden** [comment]
+1

I've run into UDTs many times when trying to connect web applications to our Oracle systems. Marshaling UDTs between application code and Oracle code has been a moderate pain point when we used JVM-based languages as well. It would really help streamline collaboration between "web" development and Oracle development groups if this were dead simple, and I like @milindkhurd's JSON-based example.

For our uses, I'd prioritize this south of #18 (precompiled binary) and #227 (Nan update). I'd put it above  things like #243 (SODA support), which might be interesting to experiment with in the future but don't really exist in our current codebase.

Thanks!

**Comment by cjbj** [comment]
@milindkhurd I'm going to close this as a dup of https://github.com/oracle/node-oracledb/issues/147

@ecowden thanks for your prioritization comments.
