### ISSUE TITLE
needed the format for connectstring

### ISSUE THREAD

**Issue by jygnash** [oracle/node-oracledb#26]
IF the tnsnames.ora file has entry can somebody tell us the connect string value.

xyz.xyz.com  =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = host1)(PORT = 1355))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = xyz.xyz.com)
	)
  )

**Comment by jygnash** [comment]
[//]host_name[:port][/service_name][:server_type][/instance_name]

**Comment by cjbj** [comment]
xyz.xyz.com i.e the bit before the first "=".  Unless you have a sqlnet.ora with a DEFAULT_DOMAIN setting of xyz.com, in which case use xyz.
https://docs.oracle.com/database/121/NETRF/sqlnet.htm#NETRF191

Alterntively, just use the Easy Connect syntax "host1:1355/xyz.xyz.com"  See https://docs.oracle.com/database/121/NETAG/naming.htm#NETAG255
