### ISSUE TITLE
Can't install OracleDB using latest Node version

### ISSUE THREAD

**Issue by vrmerlin** [oracle/node-oracledb#262]
I'm getting these errors when I try to install oracledb:

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7
    npm ERR! code ENOTSUP

    npm ERR! notsup Unsupported
    npm ERR! notsup Not compatible with your version of node/npm: oracledb@1.3.0
    npm ERR! notsup Required: {"node":">=0.10.28 <3"}
    npm ERR! notsup Actual:   {"npm":"2.14.7","node":"4.2.1"}

Can someone upgrade the package.json file to support 4.2.1?

**Comment by sagiegurari** [comment]
its not just updating package.json.
it has to do with the native c compilation.
you will have to wait for pull request #227

**Comment by vrmerlin** [comment]
Ok, thanks, I'll wait for that.

**Comment by vrmerlin** [comment]
Make that nodejs 5.0.0 support, which just came out today. :-)
