### ISSUE TITLE
Getting error in Windows 7 while running npm install oracledb

### ISSUE THREAD

**Issue by jvanderpump** [oracle/node-oracledb#263]
I have tried running 'npm install oracledb' command from powershell as well as from cmd as an admin and runnin npm cache clean command as well but again n again getting same error. Any idea how to resolve this?

C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm>npm install oracledb
npm WARN checkPermissions Missing write access to C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm\node_modules
npm@3.1.0 C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm
└── oracledb@1.3.0  extraneous

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\ggangal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v0.12.0
npm ERR! npm  v3.1.0
npm ERR! path C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm\node_modules
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, access 'C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm\node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, access 'C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm\node_modules']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\ggangal\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm\npm-debug.log

Thanks

**Comment by octokyle** [comment]
According to error code 'EPERM', it might be NPM permission error. The error message also gives tips " Please try running this command again as root/Administrator". You may as well check Permission Error part on npm site. [https://github.com/npm/npm/wiki/Troubleshooting]

**Comment by cjbj** [comment]
@jvanderpump Also try upgrading from 0.12.0 to something more recent, like 0.12.7 https://nodejs.org/download/release/latest-v0.12.x/

**Comment by jvanderpump** [comment]
@cjbj & @octokyle  - Thanks for your reply. According to Troubleshooting page I am able to run npm cache clean to resolve permission issues but no luck. I also Updated node to 0.12.7 and now I am getting different error:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Develop\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Develop\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm\node_modules\oracledb
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm@3.3.10 C:\Users\ggangal\AppData\Roaming\npm\node_modules\npm
└── nan@1.9.0  extraneous

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Develop\\nodejs\\\\node.exe" "C:\\Develop\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.0
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!   npm-debug.log

**Comment by cjbj** [comment]
Check out @bchr02's article on [Installing node-oracledb on Microsoft Windows](https://community.oracle.com/docs/DOC-931127)

You may be interested to monitor the progress of https://github.com/oracle/node-oracledb/issues/18

**Comment by jvanderpump** [comment]
Thanks a lot @cjbj . I was able to successfully install oracle db by going through https://community.oracle.com/docs/DOC-931127. Very nicely written article.

**Comment by bchr02** [comment]
Thanks @jvanderpump I'm glad the article helped you.
