### ISSUE TITLE
Error: The device is not ready.

### ISSUE THREAD

**Issue by lauort** [oracle/node-oracledb#266]
Hi all,

Since 1 week i can not manage to connect using oracle db. I uninstalled , installed...... please anyone with this error? or any idea how to solve it?

Note: I clone the project into another folder and the problem still persists.

More info: the line which fails is: require("../build/Release/oracledb")

**Comment by cjbj** [comment]
@lauort please post some details about what you are installing, where, and how.

**Comment by cjbj** [comment]
Closing due to lack of update

**Comment by lauort** [comment]
Hi @cjbj ,

Sorry for no answer, I was off for 2 weeks. I can not solve the problem but I make a clean installation in a linux system and all work perfect. I thought that is a problem in windows oracle driver.

Regards, and sorry again.
