### ISSUE TITLE
No way to create triggers

### ISSUE THREAD

**Issue by mrchess** [oracle/node-oracledb#268]
I'm trying to create a simple trigger programatically:

```
CREATE SEQUENCE USER_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER USER_ID_TRG BEFORE
  INSERT ON USER FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := USER_ID_SEQ.NEXTVAL;
END;
```

But I cannot do this because when I try to execute this via 

`connection.execute(sql)`

It throws:

`ORA-00933: SQL command not properly ended`

**Comment by cjbj** [comment]
@mrchess You'll need two execute() calls since you have two statements.  (And don't forget to remove the semi-colon on the first statement, since it is a SQL statement.)

If/when you have Oracle 12c, you won't need a sequence or trigger.  You will be able to use an IDENTITY column.

```sql
CREATE TABLE t2 (id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10));
```

See http://docs.oracle.com/database/121/SQLRF/statements_7002.htm#CJAHCAFF

**Comment by mrchess** [comment]
Thanks about for the `IDENTITY` info... didn't know about that. 

But in regards to the `TRIGGER`. I should have posted this bit too in my original issue. I tried running them as two separate statements.

When I try to run the trigger statement:

`connection.execute('CREATE OR REPLACE TRIGGER USER_ID_TRG BEFORE INSERT ON USER FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := USER_ID_SEQ.NEXTVAL; END', []...)

I get this:

`ORA-24344: success with compilation error`

And the trigger is not created.

Is this a bug?

**Comment by krismohan** [comment]
I think you are missing the semicolon after END. The semicolon is expected to be part of the statement. By the way is your table name USER? Isn't that a keyword?

**Comment by cjbj** [comment]
@mrchess I am using #80 to track how 'success with error' should be handled.

**Comment by mrchess** [comment]
Hmm ok I think this seemed to work when adding back the ;.

I will try it.

One reason I thought it failed is because both `err` and `result` return
`undefined` when you create triggers. So I wasn't sure how to indicate the
command executed succesfully.
Thanks!

**Comment by cjbj** [comment]
Having both `err` and `result` undefined may be a symptom of the issue with the 'success with error' or 'success with info' problem.
