### ISSUE TITLE
AIX Support

### ISSUE THREAD

**Issue by schmafu** [oracle/node-oracledb#27]
I successfully compiled the node-oracledb modul for AIX on node 0.10.33. I had to add following entry to the binding.gyp:

```javascript
 [
      'OS=="aix"', {
        "variables" : {
          "oci_inc_dir%" : '<!(echo ${OCI_INC_DIR:="/opt/oracle/instantclient_12_1/sdk/include/"})',
          "oci_lib_dir%" : '<!(echo ${OCI_LIB_DIR:="/opt/oracle/instantclient_12_1/"})',
        }
      }
 ]
```

I also had to build node from scratch, see https://github.com/andrewlow/node - the precompiled IBM node sdk did not work and got me some linking errors (unresolved symbol v8:: etc)

**Comment by cjbj** [comment]
Can you sign the contributor agreement and submit a pull request?  See https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md

**Comment by cjbj** [comment]
Closed by https://github.com/oracle/node-oracledb/pull/29
Thanks for the contribution!
