### ISSUE TITLE
ORA-56600 when using database connection pool

### ISSUE THREAD

**Issue by bennuXu** [oracle/node-oracledb#270]
Hello! Please consider following scenario:

We have:

os:win7 64
oracledb v 1.3 compiled with instant client v12.1.0.2 and vs2012
oracle dbms 11.2.0.1.0 Enterprise Edition on linux

when using database connection pool by adding ':POOLED' to url on win7 64,it gets connection successful,but executes sql fail with "ORA-56600 Illegal Call [First call inconsistency]".
if remove ':POOLED' from url, it wokrs fine.

with ':POOLED', it works just fine on linux.

**Comment by cjbj** [comment]
- can you share some Node.js code that reproduces the problem?
- had you started the pool on the database side?

**Comment by bennuXu** [comment]
the pool on the database side is started with command 'dbms_connection_pool.start_pool();'

__Node.js code:__

* _oracle.js:_
```javascript
var oracledb = require('oracledb');
oracledb.connectionClass = 'TEST_POOL';
var dbconfig =   {
    user          : "test",
    password      : "test",
    connectString : "$IP:$PORT/$SID:POOLED"
  };
exports.getConnection = function(callback) {
  oracledb.getConnection(dbconfig, function(err, connection) {
    if(err) {
      callback(err, null);
    } else {
      callback(null, connection);
    }
  })
}
```

* _test.js_
```javascript
var oracle = require('./oracle')
var findSQL = 'select account, name, email from tb_users where account=:account';
exports.find = function(account) {
	oracle.getConnection(function(err, connection) {
    if(err) {
      console.error('cannot get db connection:', err);
      return;
    }

    connection.execute(findSQL, {
      account: account
    }, {
      outFormat: 4001
    }, function(err, data) {
      if(err) {
        console.error('get user error', err);
      } else {
        console.log(JSON.stringify(data.rows));
        connection.release(function(err){});
      }
    })
  })
}
```

**Comment by cjbj** [comment]
Do you get a similar error with SQL*Plus on the Windows machine?

**Comment by bennuXu** [comment]
i reinstalled the oracledb, it works fine now. thx.

**Comment by cjbj** [comment]
Curious; thanks for letting us know.
