### ISSUE TITLE
Express + OracleDB does leaves a hanging process when terminated

### ISSUE THREAD

**Issue by mrchess** [oracle/node-oracledb#271]
I created a repo for the bug with express + OracleDB, in the most minimal code that reproduces the bug.

https://github.com/mrchess/oracledb-express

When I start this express server, and terminate it with `CTRL+C` the node process does not terminate and lingers in the background.

Any thoughts of this?

**Comment by cjbj** [comment]
Dup of https://github.com/oracle/node-oracledb/issues/128

**Comment by cjbj** [comment]
Closing due to lack of update
