### ISSUE TITLE
oracledb for rasperry pi

### ISSUE THREAD

**Issue by hg-smart** [oracle/node-oracledb#273]
Hi all,
tried to install oracledb on rasperrypi, as there is no native oracle client available there would be no way to install oracledb on rasperry (raspian / debian) ?

Or can oracledb maybe in the future use pure jdbc (java) ... ?

Best
Hansjoerg

**Comment by cjbj** [comment]
No plans to use JDBC for oracledb.

As always, letting us know what you are doing helps us plan ahead, so thanks for bringing it up.

**Comment by hg-smart** [comment]
Just wanted to use oracleDB on a rasperry pi platform, as Oracle Client is not available, this means oracledb as node project is also not possible, right ?

**Comment by cjbj** [comment]
Does JET run on Raspberry Pi?  http://www.ateam-oracle.com/oracle-jet-with-nodejs/

**Comment by hg-smart** [comment]
yes - I installed,Jet quickly and easily  but why  ?

pi@raspberryhg ~/dev/jet $ sudo npm install express-generator -g
/usr/local/bin/express -> /usr/local/lib/node_modules/express-generator/bin/express
express-generator@4.13.1 /usr/local/lib/node_modules/express-generator
├── sorted-object@1.0.0
├── commander@2.7.1 (graceful-readlink@1.0.1)
└── mkdirp@0.5.1 (minimist@0.0.8)
pi@raspberryhg ~/dev/jet $


express-generator@4.13.1 /usr/local/lib/node_modules/express-generator
├── sorted-object@1.0.0
├── commander@2.7.1 (graceful-readlink@1.0.1)
└── mkdirp@0.5.1 (minimist@0.0.8)

pi@raspberryhg ~/dev/jet $ express oraclejetwithnodejs

   create : oraclejetwithnodejs
   create : oraclejetwithnodejs/package.json
   create : oraclejetwithnodejs/app.js
   create : oraclejetwithnodejs/public
   create : oraclejetwithnodejs/public/javascripts
   create : oraclejetwithnodejs/public/images
   create : oraclejetwithnodejs/public/stylesheets
   create : oraclejetwithnodejs/public/stylesheets/style.css
   create : oraclejetwithnodejs/routes
   create : oraclejetwithnodejs/routes/index.js
   create : oraclejetwithnodejs/routes/users.js
   create : oraclejetwithnodejs/views
   create : oraclejetwithnodejs/views/index.jade
   create : oraclejetwithnodejs/views/layout.jade
   create : oraclejetwithnodejs/views/error.jade
   create : oraclejetwithnodejs/bin
   create : oraclejetwithnodejs/bin/www

   install dependencies:
     $ cd oraclejetwithnodejs && npm install

   run the app:
     $ DEBUG=oraclejetwithnodejs:* npm start


pi@raspberryhg ~/dev/jet $ cd oraclejetwithnodejs/
pi@raspberryhg ~/dev/jet/oraclejetwithnodejs $
pi@raspberryhg ~/dev/jet/oraclejetwithnodejs $
pi@raspberryhg ~/dev/jet/oraclejetwithnodejs $
pi@raspberryhg ~/dev/jet/oraclejetwithnodejs $ npm install

debug@2.2.0 node_modules/debug
└── ms@0.7.1

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie-signature@1.0.6
└── cookie@0.1.3

serve-favicon@2.3.0 node_modules/serve-favicon
├── etag@1.7.0
├── ms@0.7.1
├── parseurl@1.3.0
└── fresh@0.3.0

morgan@1.6.1 node_modules/morgan
├── on-headers@1.0.1
├── basic-auth@1.0.3
├── depd@1.0.1
└── on-finished@2.3.0 (ee-first@1.1.1)

express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── cookie@0.1.3
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── methods@1.1.1
├── content-type@1.0.1
├── vary@1.0.1
├── etag@1.7.0
├── fresh@0.3.0
├── range-parser@1.0.3
├── path-to-regexp@0.1.7
├── serve-static@1.10.0
├── content-disposition@0.5.0
├── parseurl@1.3.0
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)
└── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)

body-parser@1.13.3 node_modules/body-parser
├── content-type@1.0.1
├── bytes@2.1.0
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (statuses@1.2.1, inherits@2.0.1)
├── iconv-lite@0.4.11
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── raw-body@2.1.4 (unpipe@1.0.0, iconv-lite@0.4.12)

jade@1.11.0 node_modules/jade
├── commander@2.6.0
├── character-parser@1.2.1
├── void-elements@2.0.1
├── jstransformer@0.0.2 (is-promise@2.1.0, promise@6.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── constantinople@3.0.2 (acorn@2.6.2)
├── with@4.0.3 (acorn@1.2.2, acorn-globals@1.0.9)
├── uglify-js@2.5.0 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.5.3, yargs@3.5.4)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
└── clean-css@3.4.7 (source-map@0.4.4, commander@2.8.1)
pi@raspberryhg ~/dev/jet/oraclejetwithnodejs $

**Comment by hg-smart** [comment]
express install successful, will try jet later

**Comment by hg-smart** [comment]
oracle jet came up on rasperrypi port 3000 but did not do what was described in options (used Oracle Jet Quickstart Basic), does this mean JET runs on raspberrypi ? But why did you ask ?

**Comment by cjbj** [comment]
It was a suggestion phrased as a question; you will need to followup with the JET team.
