### ISSUE TITLE
QUESTION - multiple execute in parallel with same connection

### ISSUE THREAD

**Issue by sagiegurari** [oracle/node-oracledb#275]
Is it safe to run the connection.execute multiple times to enable parallel execution?
for example
````js
connetion.execute(...., callback1);
connetion.execute(...., callback2);
````
one right after the other and than checking results in the async callbacks?

**Comment by cjbj** [comment]
@sagiegurari they won't actually run in parallel. There will be queued, effectively waiting for the one connection to be available.

**Comment by sagiegurari** [comment]
ok.... not great. with jdbc if i created multiple statements with same connection and run all those statements, in different threads, is the behavior the same?

**Comment by sagiegurari** [comment]
Ok, thanks.
