### ISSUE TITLE
Crash while fetching a 12MB CLOB

### ISSUE THREAD

**Issue by rezrov** [oracle/node-oracledb#276]
I'm trying to fetch a CLOB from within a Promise, like so:

```javascript
getClob = function (conn, lob, passthru) {
    return new Promise(function (resolve, reject) {

        var clob = "";

        if (lob === null) {
            resolve({connection: conn, data: null, passthru: passthru});
            return;
        }
        lob.pieceSize = 500000;
        lob.setEncoding('utf8');  // set the encoding so we get a 'string' not a 'buffer'
        lob.on('data', function (chunk) { clob += chunk; console.log("Added chunk("+chunk.length+") to clob("+clob.length+")");});
        lob.on('end', function () { resolve({connection: conn, data: clob, passthru: passthru}); console.log("Returned clob("+clob.length+")")});
        lob.on('error', function (err) { reject(err); });
    });
};
```
When fetching a CLOB of approximately 12MB, I get the error pasted below. This error occurs for many different values of pieceSize or if pieceSize is not set at all. However, if pieceSize is set to a value larger than the CLOB, the error does not occur and everything works as expected. I'm using node v0.12.6 on Linux with Oracle instant client 11.2.0.4.

Also note that this code does not fail when fetching a smaller (~1MB) CLOB, whether or not pieceSize is set.

***
Added chunk(500000) to clob(500000)
Added chunk(500000) to clob(1000000)
Added chunk(500000) to clob(1500000)
...
Added chunk(500000) to clob(12000000)
Added chunk(500000) to clob(12500000)
Added chunk(271625) to clob(12771625)
Returned clob(12771625)
*** Error in '/usr/bin/node': double free or corruption (!prev): 0x0000000001158b00 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7207b)[0x7fc7afff807b]
/lib64/libc.so.6(+0x7754e)[0x7fc7afffd54e]
/lib64/libc.so.6(+0x77d3b)[0x7fc7afffdd3b]
/save/site/node_modules/oracledb/build/Release/oracledb.node(_ZN4ILob7cleanupEv+0x1a)[0x7fc7af15a8ba]
/save/site/node_modules/oracledb/build/Release/oracledb.node(_ZN4ILob7ReleaseERKN2v820FunctionCallbackInfoINS0_5ValueEEE+0x115)[0x7fc7af15aad5]
/usr/bin/node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0xa7)[0x5f59c7]
/usr/bin/node[0x612409]
[0xb3d4c0740e]
======= Memory map: ========
00400000-00d68000 r-xp 00000000 08:04 6309621                            /usr/bin/node
00f67000-00f68000 r--p 00967000 08:04 6309621                            /usr/bin/node
00f68000-00f6f000 rw-p 00968000 08:04 6309621                            /usr/bin/node
00f6f000-01271000 rw-p 00000000 00:00 0                                  [heap]
2f6b100000-2f6b1e5000 rw-p 00000000 00:00 0 
5acc000000-5acd000000 rw-p 00000000 00:00 0 
5acd000000-5ace000000 rw-p 00000000 00:00 0 
b3d48e7000-b3d4900000 ---p 00000000 00:00 0 
b3d4900000-b3d4905000 rw-p 00000000 00:00 0 
b3d4905000-b3d4906000 ---p 00000000 00:00 0 
b3d4906000-b3d4907000 rwxp 00000000 00:00 0 
b3d4907000-b3d4a00000 ---p 00000000 00:00 0 
b3d4a00000-b3d4a05000 rw-p 00000000 00:00 0 
b3d4a05000-b3d4a06000 ---p 00000000 00:00 0 
b3d4a06000-b3d4a07000 rwxp 00000000 00:00 0 
b3d4a07000-b3d4b00000 ---p 00000000 00:00 0 
b3d4b00000-b3d4b05000 rw-p 00000000 00:00 0 
b3d4b05000-b3d4b06000 ---p 00000000 00:00 0 
b3d4b06000-b3d4b07000 rwxp 00000000 00:00 0 
b3d4b07000-b3d4c00000 ---p 00000000 00:00 0 
b3d4c00000-b3d4c05000 rw-p 00000000 00:00 0 
b3d4c05000-b3d4c06000 ---p 00000000 00:00 0 
b3d4c06000-b3d4cff000 rwxp 00000000 00:00 0 
b3d4cff000-b3f48e7000 ---p 00000000 00:00 0 
e61e5b6000-e61e9b6000 rw-p 00000000 00:00 0 
21719c00000-21719c15000 rw-p 00000000 00:00 0 
3aa55f2d000-3aa55f40000 ---p 00000000 00:00 0 
3aa55f40000-3aa55f60000 rw-p 00000000 00:00 0 
3aa55f60000-3aa55f8d000 ---p 00000000 00:00 0 
4f283c00000-4f283d00000 rw-p 00000000 00:00 0 
57314a00000-57314b00000 rw-p 00000000 00:00 0 
6866a900000-6866aa00000 rw-p 00000000 00:00 0 
b4c80d00000-b4c80d35000 rw-p 00000000 00:00 0 
b59a6400000-b59a6500000 rw-p 00000000 00:00 0 
c44e1500000-c44e1600000 rw-p 00000000 00:00 0 
13612e000000-13612e100000 rw-p 00000000 00:00 0 
18930dd00000-18930de00000 rw-p 00000000 00:00 0 
18f1f3500000-18f1f3600000 rw-p 00000000 00:00 0 
1a2a66604000-1a2a66614000 rw-p 00000000 00:00 0 
1a2a66614000-1a2a66804000 ---p 00000000 00:00 0 
1c5de4900000-1c5de4a00000 rw-p 00000000 00:00 0 
20f1bee00000-20f1bef00000 rw-p 00000000 00:00 0 
2256e1000000-2256e1025000 rw-p 00000000 00:00 0 
2c355ad00000-2c355ae00000 rw-p 00000000 00:00 0 
2d7507c00000-2d7507d00000 rw-p 00000000 00:00 0 
2ea858900000-2ea858a00000 rw-p 00000000 00:00 0 
32bda8309000-32bda830a000 r-xp 00000000 00:00 0 
3396cb500000-3396cb525000 rw-p 00000000 00:00 0 
3413aef00000-3413af000000 rw-p 00000000 00:00 0 
36fb24300000-36fb24400000 rw-p 00000000 00:00 0 
3fe3a8400000-3fe3a8500000 rw-p 00000000 00:00 0 
7fc78c000000-7fc78c023000 rw-p 00000000 00:00 0 
7fc78c023000-7fc790000000 ---p 00000000 00:00 0 
7fc790000000-7fc79002c000 rw-p 00000000 00:00 0 
7fc79002c000-7fc794000000 ---p 00000000 00:00 0 
7fc794000000-7fc79402d000 rw-p 00000000 00:00 0 
7fc79402d000-7fc798000000 ---p 00000000 00:00 0 
7fc798000000-7fc798b4f000 rw-p 00000000 00:00 0 
7fc798b4f000-7fc79c000000 ---p 00000000 00:00 0 
7fc79c000000-7fc79c1e9000 rw-p 00000000 00:00 0 
7fc79c1e9000-7fc7a0000000 ---p 00000000 00:00 0 
7fc7a2777000-7fc7a2778000 ---p 00000000 00:00 0 
7fc7a2778000-7fc7a2f78000 rw-p 00000000 00:00 0                          [stack:16273]
7fc7a2f78000-7fc7a2f79000 ---p 00000000 00:00 0 
7fc7a2f79000-7fc7a3779000 rw-p 00000000 00:00 0                          [stack:16272]
7fc7a3779000-7fc7a377a000 ---p 00000000 00:00 0 
7fc7a377a000-7fc7a3f7a000 rw-p 00000000 00:00 0                          [stack:16271]
7fc7a3f7a000-7fc7a3f7b000 ---p 00000000 00:00 0 
7fc7a3f7b000-7fc7a477b000 rw-p 00000000 00:00 0                          [stack:16270]
7fc7a477b000-7fc7a4786000 r-xp 00000000 08:04 3415938                    /lib64/libnss_files-2.21.so
7fc7a4786000-7fc7a4985000 ---p 0000b000 08:04 3415938                    /lib64/libnss_files-2.21.so
7fc7a4985000-7fc7a4986000 r--p 0000a000 08:04 3415938                    /lib64/libnss_files-2.21.so
7fc7a4986000-7fc7a4987000 rw-p 0000b000 08:04 3415938                    /lib64/libnss_files-2.21.so
7fc7a4987000-7fc7a4991000 r-xp 00000000 08:04 3424442                    /lib64/libnss_nis-2.21.so
7fc7a4991000-7fc7a4b90000 ---p 0000a000 08:04 3424442                    /lib64/libnss_nis-2.21.so
7fc7a4b90000-7fc7a4b91000 r--p 00009000 08:04 3424442                    /lib64/libnss_nis-2.21.so
7fc7a4b91000-7fc7a4b92000 rw-p 0000a000 08:04 3424442                    /lib64/libnss_nis-2.21.so
7fc7a4b92000-7fc7a4b99000 r-xp 00000000 08:04 3416112                    /lib64/libnss_compat-2.21.so
7fc7a4b99000-7fc7a4d98000 ---p 00007000 08:04 3416112                    /lib64/libnss_compat-2.21.so
7fc7a4d98000-7fc7a4d99000 r--p 00006000 08:04 3416112                    /lib64/libnss_compat-2.21.so
7fc7a4d99000-7fc7a4d9a000 rw-p 00007000 08:04 3416112                    /lib64/libnss_compat-2.21.so
7fc7a4d9a000-7fc7abed5000 r-xp 00000000 08:04 6952469                    /usr/lib64/oracle/11.2.0.4/client/lib64/libociei.so
7fc7abed5000-7fc7abfd4000 ---p 0713b000 08:04 6952469                    /usr/lib64/oracle/11.2.0.4/client/lib64/libociei.so
7fc7abfd4000-7fc7abfd5000 rw-p 0713a000 08:04 6952469                    /usr/lib64/oracle/11.2.0.4/client/lib64/libociei.so
7fc7abfd5000-7fc7abfd6000 r-xp 00000000 08:04 5243053                    /lib64/libaio.so.1.0.1
7fc7abfd6000-7fc7ac1d5000 ---p 00001000 08:04 5243053                    /lib64/libaio.so.1.0.1
7fc7ac1d5000-7fc7ac1d6000 r--p 00000000 08:04 5243053                    /lib64/libaio.so.1.0.1
7fc7ac1d6000-7fc7ac1d7000 rw-p 00001000 08:04 5243053                    /lib64/libaio.so.1.0.1
7fc7ac1d7000-7fc7ac1eb000 r-xp 00000000 08:04 3416081                    /lib64/libnsl-2.21.so
7fc7ac1eb000-7fc7ac3eb000 ---p 00014000 08:04 3416081                    /lib64/libnsl-2.21.so
7fc7ac3eb000-7fc7ac3ec000 r--p 00014000 08:04 3416081                    /lib64/libnsl-2.21.so
7fc7ac3ec000-7fc7ac3ed000 rw-p 00015000 08:04 3416081                    /lib64/libnsl-2.21.so
7fc7ac3ed000-7fc7ac3ef000 rw-p 00000000 00:00 0 
7fc7ac3ef000-7fc7ac679000 r-xp 00000000 08:04 6952467                    /usr/lib64/oracle/11.2.0.4/client/lib64/libnnz11.so
7fc7ac679000-7fc7ac778000 ---p 0028a000 08:04 6952467                    /usr/lib64/oracle/11.2.0.4/client/lib64/libnnz11.so
7fc7ac778000-7fc7ac7ba000 rw-p 00289000 08:04 6952467                    /usr/lib64/oracle/11.2.0.4/client/lib64/libnnz11.so
7fc7ac7ba000-7fc7ac7bc000 rw-p 00000000 00:00 0 
7fc7ac7bc000-7fc7aee3f000 r-xp 00000000 08:04 6952468                    /usr/lib64/oracle/11.2.0.4/client/lib64/libclntsh.so.11.1
7fc7aee3f000-7fc7aef3e000 ---p 02683000 08:04 6952468                    /usr/lib64/oracle/11.2.0.4/client/lib64/libclntsh.so.11.1
7fc7aef3e000-7fc7af103000 rw-p 02682000 08:04 6952468                    /usr/lib64/oracle/11.2.0.4/client/lib64/libclntsh.so.11.1
7fc7af103000-7fc7af12b000 rw-p 00000000 00:00 0 
7fc7af12b000-7fc7af168000 r-xp 00000000 08:04 1447840                    /save/site/node_modules/oracledb/build/Release/oracledb.node
7fc7af168000-7fc7af367000 ---p 0003d000 08:04 1447840                   /save/site/node_modules/oracledb/build/Release/oracledb.node
7fc7af367000-7fc7af369000 r--p 0003c000 08:04 1447840                    /save/site/node_modules/oracledb/build/Release/oracledb.node
7fc7af369000-7fc7af36a000 rw-p 0003e000 08:04 1447840                    /save/site/node_modules/oracledb/build/Release/oracledb.node
7fc7af36a000-7fc7af36b000 ---p 00000000 00:00 0 
7fc7af36b000-7fc7afb6b000 rw-p 00000000 00:00 0                          [stack:16266]
7fc7afb6b000-7fc7afb81000 r-xp 00000000 08:04 6690678                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7fc7afb81000-7fc7afd80000 ---p 00016000 08:04 6690678                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7fc7afd80000-7fc7afd81000 r--p 00015000 08:04 6690678                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7fc7afd81000-7fc7afd82000 rw-p 00016000 08:04 6690678                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7fc7afd82000-7fc7afd84000 r-xp 00000000 08:04 3414510                    /lib64/libdl-2.21.so
7fc7afd84000-7fc7aff84000 ---p 00002000 08:04 3414510                    /lib64/libdl-2.21.so
7fc7aff84000-7fc7aff85000 r--p 00002000 08:04 3414510                    /lib64/libdl-2.21.so
7fc7aff85000-7fc7aff86000 rw-p 00003000 08:04 3414510                    /lib64/libdl-2.21.so
7fc7aff86000-7fc7b0117000 r-xp 00000000 08:04 3413719                    /lib64/libc-2.21.so
7fc7b0117000-7fc7b0317000 ---p 00191000 08:04 3413719                    /lib64/libc-2.21.so
7fc7b0317000-7fc7b031b000 r--p 00191000 08:04 3413719                    /lib64/libc-2.21.so
7fc7b031b000-7fc7b031d000 rw-p 00195000 08:04 3413719                    /lib64/libc-2.21.so
7fc7b031d000-7fc7b0321000 rw-p 00000000 00:00 0 
7fc7b0321000-7fc7b0338000 r-xp 00000000 08:04 3413835                    /lib64/libpthread-2.21.so
7fc7b0338000-7fc7b0537000 ---p 00017000 08:04 3413835                    /lib64/libpthread-2.21.so
7fc7b0537000-7fc7b0538000 r--p 00016000 08:04 3413835                    /lib64/libpthread-2.21.so
7fc7b0538000-7fc7b0539000 rw-p 00017000 08:04 3413835                    /lib64/libpthread-2.21.so
7fc7b0539000-7fc7b053d000 rw-p 00000000 00:00 0 
7fc7b053d000-7fc7b0636000 r-xp 00000000 08:04 3414431                    /lib64/libm-2.21.so
7fc7b0636000-7fc7b0836000 ---p 000f9000 08:04 3414431                    /lib64/libm-2.21.so
7fc7b0836000-7fc7b0837000 r--p 000f9000 08:04 3414431                    /lib64/libm-2.21.so
7fc7b0837000-7fc7b0838000 rw-p 000fa000 08:04 3414431                    /lib64/libm-2.21.so
7fc7b0838000-7fc7b0928000 r-xp 00000000 08:04 6690663                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6.0.20
7fc7b0928000-7fc7b0b28000 ---p 000f0000 08:04 6690663                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6.0.20
7fc7b0b28000-7fc7b0b30000 r--p 000f0000 08:04 6690663                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6.0.20
7fc7b0b30000-7fc7b0b32000 rw-p 000f8000 08:04 6690663                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6.0.20
7fc7b0b32000-7fc7b0b47000 rw-p 00000000 00:00 0 
7fc7b0b47000-7fc7b0b4d000 r-xp 00000000 08:04 3420473                    /lib64/librt-2.21.so
7fc7b0b4d000-7fc7b0d4d000 ---p 00006000 08:04 3420473                    /lib64/librt-2.21.so
7fc7b0d4d000-7fc7b0d4e000 r--p 00006000 08:04 3420473                    /lib64/librt-2.21.so
7fc7b0d4e000-7fc7b0d4f000 rw-p 00007000 08:04 3420473                    /lib64/librt-2.21.so
7fc7b0d4f000-7fc7b0f61000 r-xp 00000000 08:04 6292152                    /usr/lib64/libcrypto.so.1.0.0
7fc7b0f61000-7fc7b1160000 ---p 00212000 08:04 6292152                    /usr/lib64/libcrypto.so.1.0.0
7fc7b1160000-7fc7b117e000 r--p 00211000 08:04 6292152                    /usr/lib64/libcrypto.so.1.0.0
7fc7b117e000-7fc7b118a000 rw-p 0022f000 08:04 6292152                    /usr/lib64/libcrypto.so.1.0.0
7fc7b118a000-7fc7b118e000 rw-p 00000000 00:00 0 
7fc7b118e000-7fc7b11f9000 r-xp 00000000 08:04 6308534                    /usr/lib64/libssl.so.1.0.0
7fc7b11f9000-7fc7b13f8000 ---p 0006b000 08:04 6308534                    /usr/lib64/libssl.so.1.0.0
7fc7b13f8000-7fc7b13fd000 r--p 0006a000 08:04 6308534                    /usr/lib64/libssl.so.1.0.0
7fc7b13fd000-7fc7b1404000 rw-p 0006f000 08:04 6308534                    /usr/lib64/libssl.so.1.0.0
7fc7b1404000-7fc7b1424000 r-xp 00000000 08:04 6309608                    /usr/lib64/libuv.so.1.0.0
7fc7b1424000-7fc7b1624000 ---p 00020000 08:04 6309608                    /usr/lib64/libuv.so.1.0.0
7fc7b1624000-7fc7b1625000 r--p 00020000 08:04 6309608                    /usr/lib64/libuv.so.1.0.0
7fc7b1625000-7fc7b1626000 rw-p 00021000 08:04 6309608                    /usr/lib64/libuv.so.1.0.0
7fc7b1626000-7fc7b162b000 r-xp 00000000 08:04 6309604                    /usr/lib64/libhttp_parser.so.2.3
7fc7b162b000-7fc7b182b000 ---p 00005000 08:04 6309604                    /usr/lib64/libhttp_parser.so.2.3
7fc7b182b000-7fc7b182c000 r--p 00005000 08:04 6309604                    /usr/lib64/libhttp_parser.so.2.3
7fc7b182c000-7fc7b182d000 rw-p 00006000 08:04 6309604                    /usr/lib64/libhttp_parser.so.2.3
7fc7b182d000-7fc7b1842000 r-xp 00000000 08:04 5243027                    /lib64/libz.so.1.2.8
7fc7b1842000-7fc7b1a41000 ---p 00015000 08:04 5243027                    /lib64/libz.so.1.2.8
7fc7b1a41000-7fc7b1a42000 r--p 00014000 08:04 5243027                    /lib64/libz.so.1.2.8
7fc7b1a42000-7fc7b1a43000 rw-p 00015000 08:04 5243027                    /lib64/libz.so.1.2.8
7fc7b1a43000-7fc7b1a65000 r-xp 00000000 08:04 3417090                    /lib64/ld-2.21.so
7fc7b1c08000-7fc7b1c09000 ---p 00000000 00:00 0 
7fc7b1c09000-7fc7b1c18000 rw-p 00000000 00:00 0                          [stack:16274]
7fc7b1c18000-7fc7b1c19000 ---p 00000000 00:00 0 
7fc7b1c19000-7fc7b1c29000 rw-p 00000000 00:00 0                          [stack:16269]
7fc7b1c29000-7fc7b1c2a000 ---p 00000000 00:00 0 
7fc7b1c2a000-7fc7b1c3a000 rw-p 00000000 00:00 0                          [stack:16268]
7fc7b1c3a000-7fc7b1c3b000 ---p 00000000 00:00 0 
7fc7b1c3b000-7fc7b1c54000 rw-p 00000000 00:00 0                          [stack:16267]
7fc7b1c62000-7fc7b1c64000 rw-p 00000000 00:00 0 
7fc7b1c64000-7fc7b1c65000 r--p 00021000 08:04 3417090                    /lib64/ld-2.21.so
7fc7b1c65000-7fc7b1c66000 rw-p 00022000 08:04 3417090                    /lib64/ld-2.21.so
7fc7b1c66000-7fc7b1c67000 rw-p 00000000 00:00 0 
7ffd0d991000-7ffd0d9b2000 rw-p 00000000 00:00 0                          [stack]
7ffd0d9da000-7ffd0d9dc000 r--p 00000000 00:00 0                          [vvar]
7ffd0d9dc000-7ffd0d9de000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Command terminated by signal 6

**Comment by cjbj** [comment]
Please post a complete code snippet that reproduces the problem.  Thanks!

**Comment by cjbj** [comment]
What if you change lob.on 'end', to lob.on 'close' ?

**Comment by rezrov** [comment]
I've combined and whittled down the failing code here: https://gist.github.com/rezrov/0a5063d15f5e5255a994
This code fails the same way whether I use lob.on 'end or lob.on 'close'.

**Comment by cjbj** [comment]
It doesn't reproduce for me on OS X or on Oracle Linux 6, 64 bit with
11.2.0.4 Instant Client to a 12.1.0.2 AL32UTF8 database, using
84090545 bytes of ASCII data.

```
. . .
Added chunk(500000) to clob(83000000)
Added chunk(500000) to clob(83500000)
Added chunk(500000) to clob(84000000)
Added chunk(90545) to clob(84090545)
Returned clob(84090545)
Wrote file ./export/run_1_export.txt
Closing connection
Released Connection
Closing pool
Pool's Closed!
```

Some questions & thoughts:

- What version is the DB?  What OS etc?
- What character set is the DB?
- Is it data dependent?
- Try a long string of ASCII characters, e.g. repeated 'a';
- 32bit or 64 bit linux?
- Try 0.12.7

**Comment by rezrov** [comment]
Some answers:
- Database is Oracle XE 11.2 on Windows XP 64-bit (vmware).
- Client is Linux 4.0 64 bit, Oracle instant client 11.2.0.4.0 (vmware).
- Character set is UTF8.
I'll work on some of your suggestions as soon as I can, thanks.

**Comment by jorgen81** [comment]
For what it's worth, I experienced similar problems using default chunk size of about 8kB. When the content exceeded the chunk size I got the same error. For me, it worked to increase the chunk size so that I get all the content in one chunk, so that can be a temporary fix.

I use [sath89's Docker image](https://hub.docker.com/r/sath89/oracle-xe-11g/) with Oracle XE 11g and Centos6 on the client using instant client 12.1.0.2.0. Character set is also utf-8 and it's storing stringified json data.

**Comment by cjbj** [comment]
We can see a code bug with LOBs.  Just need to verify the fix since reproducing the bug is a little variable.  The problem might be the cause of the various crashes people are seeing.

**Comment by cjbj** [comment]
@rezrov If this is still an issue in 1.5, yell out.

**Comment by rezrov** [comment]
Just ran the same set of tests as before after updated to node 5 and node-oracledb 1.5. Happy to report no issues. Thanks!
