### ISSUE TITLE
Failed with Symbol not found: _OCIEnvNlsCreate on El Capitan

### ISSUE THREAD

**Issue by akemisetti** [oracle/node-oracledb#278]
I am getting the following error
*************************************************************************************
dyld: lazy symbol binding failed: Symbol not found: _OCIEnvNlsCreate
  Referenced from: /Users/akemisetti/node_modules/oracledb/build/Release/oracledb.node
  Expected in: dynamic lookup

dyld: Symbol not found: _OCIEnvNlsCreate
  Referenced from: /Users/akemisetti/node_modules/oracledb/build/Release/oracledb.node
  Expected in: dynamic lookup

[Finished in 0.1s with exit code -5]
-****************************************************************************************
node version -- v4.2.2
npm version -- 2.14.7
OS X version elcapitan
xcode -- 7.0
Apple LLVM version 7.0.0 (clang-700.0.72)

I have used the latest branch from Richard Natal.
I have set the DYLD_LIBRARY_PATH env variable at run time.

**Comment by Bigous** [comment]
Hi, it is, probably, a problem with x86 / x64 linking / executing (with one comes first in path).

As you are using node 4.2.2, i suppose that you are using the pull request #227. It's not official yet, but it does not change the behavior of OCI linking and execution... We have 2 issues discusing problems with El Capitain, #149 and #231.

hope have helped.
