### ISSUE TITLE
Getting list of all tables in a DB/Schema

### ISSUE THREAD

**Issue by grug** [oracle/node-oracledb#279]
Hey there,

I'm getting the following error when executing the following query with node-oracledb:

```
SELECT OBJECT_NAME
FROM ALL_OBJECTS || '@' || :db
WHERE OWNER = :schema
    AND (
        OBJECT_TYPE = ''TABLE''
        OR OBJECT_TYPE = ''VIEW''
        OR OBJECT_TYPE = ''SYNONYM''
    )
ORDER BY OBJECT_NAME
```

If I execute this query in an Oracle console (substituting the placeholders for actual values, of course), it executes fine. However, when I execute this in my Node application, I get the following error:

"ORA-00933: SQL command not properly ended"

Is anyone able to assist with why I'm getting this error? I can confirm that my placeholders are definitely populating with the values I intended them to be populated with.

Thanks!

edit: even if I try do
```
SELECT OBJECT_NAME
FROM ALL_OBJECTS || @ || :db
```

I still get the same error

**Comment by cjbj** [comment]
Post your actual Node code (as a runnable example) so we can see the details.

**Comment by grug** [comment]
I have re-read my question and I can see why it might seem important that the accompanying Node code would be useful - I should have mentioned that I was just executing a query using the execute() function and that I had the two bindings that you can see in my query. Fortunately the code didn't require any work - only my query did, as I had a fundamental misunderstanding of how bindings worked. Since then I have worked out the solution. I changed the query from what I had in my original post to:
```
SELECT OBJECT_NAME
FROM ALL_OBJECTS@<hard coded db name here>
WHERE OWNER = :schema
AND (
    OBJECT_TYPE = 'TABLE'
    OR OBJECT_TYPE = 'VIEW'
    OR OBJECT_TYPE = 'SYNONYM'
)
ORDER BY OBJECT_NAME;
```

And everything worked as expected!

Thanks for taking the time to look at my question originally - it is much appreciated @cjbj !!!
