### ISSUE TITLE
fatal error LNK1106: invalid file or disk full: cannot seek to 0x1B844 [D:\nodeoracletest\node_modules\oracledb\build\oracledb.vcxproj]

### ISSUE THREAD

**Issue by vivekbrahmadandi** [oracle/node-oracledb#280]
Hi,
     Getting an issue while installing node oracle db in windows 7 .
Followed steps from the URL : https://community.oracle.com/docs/DOC-931127

Node version:v0.12.7

command used for installing oracle db :  npm install oracledb

Error Log in console ----
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(12): warning C4005: 'WIN32_LEAN_AND_MEAN' : macro redefinition [D:\nodeoracletest\node_modules\oracledb\build\oracledb.vcxproj]
          command-line arguments :  see previous definition of 'WIN32_LEAN_AND_MEAN'
C:\Users\vivekb\.node-gyp\0.12.7\Release\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x1B844 [D:\nodeoracletest\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\nodeoracletest\node_modules\oracledb
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodeoracletest\npm-debug.log

**Comment by cjbj** [comment]
Is your disk full?

**Comment by vivekbrahmadandi** [comment]
no Christopher. Infact it has more space in GB :)

**Comment by vivekbrahmadandi** [comment]
C:\Users\vivekb.node-gyp\0.12.7\Release\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x1B844 [D:\nodeoracletest\node_modules\oracledb\build\oracledb.vcxproj]

Do we need to install npm node-gyp in before installing node oracle db

**Comment by bchr02** [comment]
To troubleshoot this, here is what I would try:
* check hard drive for corruption ```chkdsk  C: /F``` and ```chkdsk  D: /F```
* use the C drive instead of the D drive for your app.
* I noticed ```C:\Users\vivekb.node-gyp\``` is this your windows username? I would try installing node to another location.

**Comment by vivekbrahmadandi** [comment]
Thanks Bill and Christopher , it worked out.

**Comment by cjbj** [comment]
@bchr02 did all the hard work.

@vivekbrahmadandi what was the cause?

**Comment by vivekbrahmadandi** [comment]
@cjbj   manually I deleted the  folder vivekb.node-gyp in C drive then done check drive .
Anyway thanks @cjbj !
