### ISSUE TITLE
Installation problem (Ubuntu 15.10)

### ISSUE THREAD

**Issue by lauort** [oracle/node-oracledb#281]
Hi,

I made a clean installation into a Ubuntu 14 without problems and now in Ubuntu 15.10, I have this problem. I uploaded the debug file, more info:

- Node version: 4.2.2
- Npm version: 2.14.7

Regards.

[npm-debug.txt](https://github.com/oracle/node-oracledb/files/35608/npm-debug.txt)

**Comment by cjbj** [comment]
The current status of support for 4.2 & 5.0 is at: https://github.com/oracle/node-oracledb/issues/115#issuecomment-156983381
