### ISSUE TITLE
Hi, i have problem install V. 1.4.0 in windows 64 bits

### ISSUE THREAD

**Issue by fabialvarado** [oracle/node-oracledb#283]
please watching logs

 verbose stack Error: oracledb@1.4.0 install: `node-gyp rebuild`
405 verbose stack Exit status 1
405 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
405 verbose stack     at emitTwo (events.js:87:13)
405 verbose stack     at EventEmitter.emit (events.js:172:7)
405 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
405 verbose stack     at emitTwo (events.js:87:13)
405 verbose stack     at ChildProcess.emit (events.js:172:7)
405 verbose stack     at maybeClose (internal/child_process.js:818:16)
405 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
406 verbose pkgid oracledb@1.4.0
407 verbose cwd C:\Users\XXXXXXXXX\Documents\node
408 error Windows_NT 6.1.7600
409 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
410 error node v4.2.2
411 error npm  v2.14.7
412 error code ELIFECYCLE
413 error oracledb@1.4.0 install: `node-gyp rebuild`
413 error Exit status 1
414 error Failed at the oracledb@1.4.0 install script 'node-gyp rebuild'.
414 error This is most likely a problem with the oracledb package,
414 error not with npm itself.
414 error Tell the author that this fails on your system:
414 error     node-gyp rebuild
414 error You can get their info via:
414 error     npm owner ls oracledb
414 error There is likely additional logging output above.
415 verbose exit [ 1, true ]
416 verbose unbuild node_modules\oracledb
417 info preuninstall oracledb@1.4.0
418 info uninstall oracledb@1.4.0

**Comment by cjbj** [comment]
Did you check https://community.oracle.com/docs/DOC-931127 ?

In the email you sent me directly I noticed your username contains a period.  Is this coincidentally like https://github.com/oracle/node-oracledb/issues/280#issuecomment-157272064, or does node-gyp not like periods in path component names?

**Comment by fabialvarado** [comment]
MMM interesting,

I'm going to check

**Comment by fabialvarado** [comment]
hello, my problem was solved.

I need administrator privileges.
Thank you
