### ISSUE TITLE
Number of rows in result from SELECT

### ISSUE THREAD

**Issue by alexwhitman** [oracle/node-oracledb#285]
Is it possible to get the number of rows selected from a result?  The `result` object has a `rowsAffected` property but this is always `undefined` for SELECT queries.

**Comment by nvme978** [comment]
You can get use result.rows.length to get the length of the result array.
This will normally be the row count.

**Comment by alexwhitman** [comment]
Sorry, should have mentioned that I'm using `resultSet: true`.  When this is used `result.rows` is `undefined`.

**Comment by fedulovivan** [comment]
It is not possible to count affected rows unless resutset won't be completely fetched. You should probably need to run `SELECT COUNT(*) ...WHERE ...` query to obtain suchlike data.

**Comment by cjbj** [comment]
As @fedulovivan you have to explicitly ask for the number of rows, or fetch them all.  This is an "Oracle Database thing".

This post by my colleague Jeff Smith has a slant on the topic: http://www.thatjeffsmith.com/archive/2012/02/sql-magic-trick-getting-row-count-without-fetching-all-rows/
