### ISSUE TITLE
compilation error ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

### ISSUE THREAD

**Issue by atiertant** [oracle/node-oracledb#286]
can't install node-oracledb on linux using npm :  
 
 CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/njs/src/njsOracle.h:56:0,
                 from ../src/njs/src/njsOracle.cpp:53:
../node_modules/nan/nan.h:328:47: erreur: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
oracledb.target.mk:116: recipe for target 'Release/obj.target/oracledb/src/njs/src/njsOracle.o' failed
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1

**Comment by atiertant** [comment]
oups https://github.com/nodejs/nan/issues/394 working after update node

**Comment by cjbj** [comment]
Somehow I was able to install on 0.10.28 using my normal steps: `\rm -rf ./node_modules/oracledb ./node_modules/nan $HOME/.node-gyp $HOME/.npm && npm cache clean && npm install oracledb`

```
. . .
 SOLINK_MODULE(target) Release/obj.target/oracledb.node
  SOLINK_MODULE(target) Release/obj.target/oracledb.node: Finished
  COPY Release/oracledb.node
make: Leaving directory `/home/cjones/n/node_modules/oracledb/build'
oracledb@1.5.0 node_modules/oracledb
└── nan@2.1.0
cjones@localhost:~/n/dataaccess_node-oracledb$ node -v
v0.10.28
```
