### ISSUE TITLE
Don't rely on instant client

### ISSUE THREAD

**Issue by wmertens** [oracle/node-oracledb#288]
Thank you for making this client, the previous options drove me and others to just wrap sqlclient or php.

However, it is still quite a nightmare to install because of the instant client dependency, which is rather huge, requires manual admin intervention to install and update, causes problems on os x, is not available on less mainstream linux distributions and simply not possible on ARM platforms (a viable dedicated server option).

All these reasons contribute to the fact that Oracle is shunned as a backend for Node frameworks and applications.

It would be wonderful if all you needed to talk to Oracle was this project, by simply using npm install…

Thanks for your efforts so far in any case!

**Comment by cjbj** [comment]
@wmertens thanks for taking the time to comment.

For the record, Instant Client Zip files can be used on any compatible Linux.

There are no immediate plans to get rid of the dependency on Oracle Client.  Once you get past the install requirement (work is ongoing in making this easier), then there are many benefits.  The client lets the driver take advantage of significant and advanced feature set that is common and well tested.  These include various caches, network optimizations, diagnostics, high availability features etc.

Are you actually using ARM?
