### ISSUE TITLE
node: corrupted double-linked list

### ISSUE THREAD

**Issue by bennuXu** [oracle/node-oracledb#289]
In node v0.12.7 I'm getting the following exception regularly:

>*** glibc detected *** /usr/local/bin/node: corrupted double-linked list: 0x000000001f106120 ***
>======= Backtrace: =========
>/lib64/libc.so.6[0x3e8426f463]
>/lib64/libc.so.6[0x3e84271a7c]
>/lib64/libc.so.6[0x3e84272d4b]
>/lib64/libc.so.6(__libc_memalign+0xba)[0x3e8427407a]
>/lib64/ld-linux-x86-64.so.2(__tls_get_addr+0xb1)[0x3e83e10091]
>/home/hrdew/instantclient_12_1/libnnz12.so[0x2afe877ad9ab]
>/home/hrdew/instantclient_12_1/libnnz12.so(ztca_Init+0x44)[0x2afe877ae9d4]
>/home/hrdew/instantclient_12_1/libnnz12.so[0x2afe8762b968]
>/home/hrdew/instantclient_12_1/libnnz12.so(ztca_GetRandom+0x15)[0x2afe8762b915]
>/home/hrdew/instantclient_12_1/libnnz12.so(ztcr2rnd+0x8c)[0x2afe8762d72c]
>/home/hrdew/instantclient_12_1/libnnz12.so(ztcsh+0x88)[0x2afe8760d1f8]
>/home/hrdew/instantclient_12_1/libclntsh.so.12.1(kpusattr+0x4a3)[0x2afe84504873]
>/home/hrdew/instantclient_12_1/libclntsh.so.12.1(OCIAttrSet+0xb)[0x2afe8452e48b]
>/home/hrdew/daas/node_modules/oracledb/build/Release/oracledb.node(_ZN8ConnImpl12initConnImplEbbRKSsPhjS1_S1_+0x13b)[0x2afe7d17a09b]
>/home/hrdew/daas/node_modules/oracledb/build/Release/oracledb.node(_ZN8ConnImplC1EP7EnvImplP6OCIEnvbjRKSsS5_S5_S5_+0x8b)[0x2afe7d17a4bb]
>/home/hrdew/daas/node_modules/oracledb/build/Release/oracledb.node(_ZN7EnvImpl13getConnectionERKSsS1_S1_iS1_b+0x7a)[0x2afe7d177f5a]
>/home/hrdew/daas/node_modules/oracledb/build/Release/oracledb.node(_ZN8Oracledb19Async_GetConnectionEP9uv_work_s+0x6d)[0x2afe7d1598ed]
>/usr/local/bin/node[0xc7d9e9]
>/usr/local/bin/node[0xc8aad2]
>/lib64/libpthread.so.0[0x3e8520683d]
>/lib64/libc.so.6(clone+0x6d)[0x3e842d4fcd]

uname -a

>Linux stpass-web 2.6.18-371.8.1.el5 #1 SMP Thu Apr 24 18:19:36 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue

>CentOS release 5.9 (Final)
>Kernel \r on an \m

Any ideas?

**Comment by cjbj** [comment]
Not much to go on. Got a test case?

**Comment by cjbj** [comment]
Closed due to lack of response
