### ISSUE TITLE
Can connect but then no query works

### ISSUE THREAD

**Issue by paulkav1** [oracle/node-oracledb#293]
Have installed oracledb per instructions on NodeJS 4.2.

Trying to connect to Oracle 10g (10.2)

Connection appears to work - no error.

Then any query (select * from dual;) fails with ORA-01036: illegal variable name/number.

Able to connect to this database with same credentials using SQL Developer (or Java).

**Comment by paulkav1** [comment]
Connection {
  oracleServerVersion: 1002000400,
  action: null,
  module: null,
  clientId: null,
  stmtCacheSize: 30 }

**Comment by cjbj** [comment]
Show us your Node.js script.  And check the use of the bind and the options parameters.

**Comment by paulkav1** [comment]
config.js:
    oracleUser          : process.env.NODE_ORACLEDB_USER || "amsread",
    oraclePassword      : process.env.NODE_ORACLEDB_PASSWORD || "amsread",
    oracleConnectString : process.env.NODE_ORACLEDB_CONNECTIONSTRING || "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=amsprod)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=psamsp)))"

gridNet.js:
var oracledb = require('oracledb');
...
// Oracle
oracledb.getConnection({
        user          : config.oracleUser,
        password      : config.oraclePassword,
        connectString : config.oracleConnectString
    },
    function(err, connection) {
        if (err) {
            console.error(err.message);
            return;
        }
        console.log(connection);
        connection.execute(
            "SELECT * FROM PSAMSP.CA_FOLLOWUP_QUEUE;", [180], function(err, result) {
                if (err) {
                    console.error(err.message);
                    doRelease(connection);
                    return;
                }
                console.log(result.metaData);
                console.log(result.rows);
                doRelease(connection);
            });
    });

function doRelease(connection) {
    connection.release(
        function(err) {
            if (err) {
                console.error(err.message);
            }
        });
}
// end of Oracle

**Comment by paulkav1** [comment]
I am not familiar with the bind and options parameters and I don't think I am using them

**Comment by cjbj** [comment]
[180] is a bind value but your SQL statement doesn't have a corresponding ":variable".
Check the manual https://github.com/oracle/node-oracledb/blob/master/doc/api.md#sqlexecution
You can see the ":did" in the SQL string (section 9.1.1.) is replaced by the 180 when the statement executes.  (I can see where some extra explanation in the manual will help.)
Binding is described in https://github.com/oracle/node-oracledb/blob/master/doc/api.md#bind

**Comment by paulkav1** [comment]
Thank you.

The query kept failing because I was passing an argument [180] and there was no matching : parameter in the SQL. Changing it to [] (no arguments) solves it.
