### ISSUE TITLE
Compilation of version 1.4 using gcc 4.4.7

### ISSUE THREAD

**Issue by fedulovivan** [oracle/node-oracledb#295]
Hello!

It is stated that latest released version 1.4 requires compiler supporting c++11 standard.
However I noticed module could be successfully compiled with gcc v 4.4.7 available on RHEL 6.2

Can this have some pitfalls?

Gcc version output:
```
[***@localhost home]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
```

**Comment by sagiegurari** [comment]
you are probably using an older nodejs version.
nodejs 4 and up would require it, while nodejs 0.12 and older would not.

**Comment by fedulovivan** [comment]
@sagiegurari You are right, this was tested with nodejs 0.12.7
So, unless we are on old version of nodejs this requirement regarding c++11 compiler is not relevant at all? 
Also I suppose information in change log should be refined then, currently given one confuses a bit.

**Comment by cjbj** [comment]
@fedulovivan I updated the [release notes](https://github.com/oracle/node-oracledb/releases/tag/v1.4.0) the other day, and will also update CHANGELOG.

The check for C++11 compatibility is in NAN https://github.com/nodejs/nan/blob/master/nan.h#L40

**Comment by fedulovivan** [comment]
My apologizes, but it is still not clear for me, can oracledb v1.4.0 be compiled with gcc 4.4.7 and further used, or not.

**Comment by krismohan** [comment]
Yes, you can, with Node 0.10 and 0.12 versions.
