### ISSUE TITLE
ETIMEDOUT error

### ISSUE THREAD

**Issue by paulkav1** [oracle/node-oracledb#296]
I run my program and get all 7600 records, then release the connection. All appears good.

Then some time later I get 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.110.20.85:5432
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

If the query completed and connection is released, what is causing the timeout?

Code follows:
oracledb.getConnection({user: config.oracleUser, password: config.oraclePassword, connectString: config.oracleConnectString}, function(err, connection) {
    if (err) {
        console.error(err.message);
        return;
    }
    //console.log(connection);
    //{resultSet: true}
    connection.execute("SELECT * FROM SW$ADMIN.CA_FOLLOWUP_QUEUE WHERE FLUP_WK_NUM != 'REPAIRED' AND FLUP_WK_STATUS IS NOT NULL AND FLUP_WK_STATUS < '70'", [], {maxRows: 12000}, function(err, result) {
        if (err) {
            console.error(err.message);
            doRelease(connection);
            return;
        }
        //console.log(result.metaData);
        console.log(result.rows);
        console.log('processed ' + result.rows.length.toString());
        //fetchRow(connection, result.resultSet);
        doRelease(connection);
    });
});

function doRelease(connection) {
    connection.release(function(err) {
        if (err)
            console.error(err.message);
        else
            console.log('released OK');
    });
}

**Comment by dmcghan** [comment]
@paulkav1 What file is this code contained in? Can you show us the code around 141 of events.js? Also, what about the code around lines 874 and 897 of util.js?

What's the overall context here? How are you executing this test?

**Comment by paulkav1** [comment]
Good questions.

The Oracle connection is working perfectly here.

While I was having an issue the other day I added another database (Postgres) and this error is coming from there.

Sorry to have wasted your time.
