### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by wywwolf** [oracle/node-oracledb#297]
systeminfo:windows7x64,node is 0.12.7
"npm install oracle" is successful.
D:\nodetest>node app.js
====================begin test========================
D:\nodetest\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: The specified module could not be found.
D:\nodetest\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\nodetest\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

The app.js as follow:
console.log("====================begin test========================");
var oracledb = require("oracledb");  
console.log("====================create oracledb========================");
console.log("Oracle client library version number is " + oracledb.oracleClientVersion);
oracledb.getConnection({  
     user: "autotrade",  
     password: "autotrade",  
     connectString: "rac:1521"  
}, function(err, connection) {if (err) {console.error(err.message); return; }  
     connection.execute( "SELECT * FROM ctp_tradingaccount WHERE tradingday='20151201'",  
     [],  
     function(err, result) {  
          if (err) {  
               console.error(err.message);  
               doRelease(connection);  
               return;  
          }  
          console.log(result.metaData);  
          console.log(result.rows);  
          doRelease(connection);  
     });  
});  
  
function doRelease(connection) {  
     connection.release(  
          function(err) {  
               if (err) {console.error(err.message);}  
          }  
     );  
}
  
=============================================
Path=C:\oracle\instantclient;C:\Python27\;C:\Python27\Scripts;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\

OCI_INC_DIR=C:\Oracle\instantclient\sdk\include
OCI_LIB_DIR=C:\Oracle\instantclient\sdk\lib\msvc

========================================
npm install oracledb

D:\nodetest>npm install D:\Documents\GitHub\node-oracledb
-
> oracledb@1.4.0 install D:\nodetest\node_modules\oracledb
> node-gyp rebuild

D:\nodetest\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\P
rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
     Creating library D:\nodetest\node_modules\oracledb\build\Release\oracledb.
  lib and object D:\nodetest\node_modules\oracledb\build\Release\oracledb.exp
  Generating code
  Finished generating code
  oracledb.vcxproj -> D:\nodetest\node_modules\oracledb\build\Release\\oracledb
  .node
oracledb@1.4.0 node_modules\oracledb
└── nan@2.1.0

**Comment by wywwolf** [comment]
When I uninstall node v0.12.7,after install node 4.2.2,
D:\nodetest>npm install D:\Documents\GitHub\node-oracledb
-
> oracledb@1.4.0 install D:\nodetest\node_modules\oracledb
> node-gyp rebuild

D:\nodetest\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\P
rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node  rebuild )

===============================
until now ,nothing happen.

**Comment by cjbj** [comment]
On Linux, after installing & deinstalling & getting issues, I would have suggested cleaning right up:

```
\rm -rf ./node_modules/oracledb ./node_modules/nan $HOME/.node-gyp $HOME/.npm && npm cache clean
```
And then starting again

**Comment by wywwolf** [comment]
when I create a new dir, execute "npm install oracledb", test connect to oracle is ok

**Comment by cjbj** [comment]
@wywwolf does that mean this issue can be closed?

**Comment by cjbj** [comment]
Closing do to lack of updates
