### ISSUE TITLE
sh: node-gyp: command not found

### ISSUE THREAD

**Issue by kimmatdol** [oracle/node-oracledb#298]
hi.

installed node-oracledb with CentOS

error message

------------------------------------------------------------------------------------------------------------------
> oracledb@1.4.0 install /home/kimmatdol/workspace/messenger/node_modules/oracledb
> node-gyp rebuild

sh: node-gyp: command not found
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/home/kimmatdol/node/bin/node" "/home/kimmatdol/node/bin/npm" "install"
npm ERR! node v0.12.8
npm ERR! npm  v2.14.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! oracledb@1.4.0 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the oracledb@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kimmatdol/workspace/messenger/npm-debug.log

------------------------------------------------------------------------------------------------------------------------------

but already installed node-gyp.

"npm install node-gyp"
result : node-gyp@3.2.1

how fixed this error?

please help me.

**Comment by wywwolf** [comment]
please close this issue

**Comment by kimmatdol** [comment]
to wywwolf.

why?

**Comment by wywwolf** [comment]
sorry, i am wrong!

**Comment by cjbj** [comment]
@kimmatdol did you follow https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instzip ? And if not, then tell us what command you executed.

**Comment by cjbj** [comment]
Closing due to lack of response
