### ISSUE TITLE
resultSet has memory Leak in Node 4.2

### ISSUE THREAD

**Issue by volkmarbuehringer** [oracle/node-oracledb#307]
all the fetched Data is kept in memory after 

resultSet.getRows()

the memory consumption is steadily increasing during the fetch of a large table.

even after the closing of connection and resultSet the memory is not freed

(driver version 1.4, Node 4.2 )

**Comment by volkmarbuehringer** [comment]
for selects containing a lob column, it seems the memory is being released, after the fetching of the lob

**Comment by sagiegurari** [comment]
The docs state that lobs must be fully read for memory to be released.

**Comment by volkmarbuehringer** [comment]
yes,
but in selects without lob columns, the memory is not released for resultsets

**Comment by cjbj** [comment]
Our testing recently uncovered some memory growth, which we'll look at.  However can we have your testcase to confirm it is the same? And the Node & Oracle version, and whether you've done anything fancy with garbage collection and memory use.

**Comment by volkmarbuehringer** [comment]
node 4.2, oracle client 12.1
the memory growth is huge, all the fetched data, also confirmed with --optimize_for_size
with a lob column in the select, the growth is very slow

**Comment by cjbj** [comment]
@volkmarbuehringer What's your testcase (including DDL to create the table)?

**Comment by cjbj** [comment]
@volkmarbuehringer this is fixed in 1.9.1.  Thanks for your patience.
