### ISSUE TITLE
Allow testing failure modes

### ISSUE THREAD

**Issue by wmertens** [oracle/node-oracledb#308]
I would like to have unit tests for my database functions, but I don't know the many failure modes of Oracle.

Is there some way that the oracle db could be mocked with something returning all the possible errors?

It is also hard to determine when to retry and when to give up. Some guidance in how to handle the different classes of errors at different points in the API would be nice.

**Comment by cjbj** [comment]
@wmertens Oracle DB has a long history and there are lots of errors codes https://docs.oracle.com/database/121/ERRMG/toc.htm
The complexity of the situation is known but I don't have an easy answer.  At a different level there is work ongoing on Application Continuity http://www.oracle.com/technetwork/products/clustering/ac-overview-1967264.html (which is in JDBC from 12.1) and making this more widely usable.
