### ISSUE TITLE
npm install fails on Windows 7

### ISSUE THREAD

**Issue by KevinSheedy** [oracle/node-oracledb#311]
`npm install oracledb` is failing on Windows 7

    if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-    gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    gyp WARN install got an error, rolling back install
    gyp ERR! configure error
    gyp ERR! stack Error: write EPROTO
    gyp ERR! stack     at Object.exports._errnoException (util.js:874:11)
    gyp ERR! stack     at exports._exceptionWithHostPort (util.js:897:20)
    gyp ERR! stack     at WriteWrap.afterWrite (net.js:763:14)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-    gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\dev\sandbox_workspace\oracle-node\node_modules\oracledb
    gyp ERR! node -v v4.2.2
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"     "install" "oracledb" "--save-dev"
    npm ERR! node v4.2.2
    npm ERR! npm  v2.14.7
    npm ERR! code ELIFECYCLE
    
    npm ERR! oracledb@1.4.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the oracledb@1.4.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the oracledb package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls oracledb
    npm ERR! There is likely additional logging output above.

[npm-debug.log.txt](https://github.com/oracle/node-oracledb/files/64244/npm-debug.log.txt)

**Comment by cjbj** [comment]
Some background info about what your environment, compiler etc are would be useful.

**Comment by KevinSheedy** [comment]
Hi @cjbj 

Windows 7 Enterprise Service Pack 1
Node v4.2.2
npm 2.14.7
SQL*Plus: Release 11.2.0.3.0 Production

What compiler are you referring to? I haven't seen anything about a dependency on a compiler in the docs?
Thanks

**Comment by cjbj** [comment]
On 17/12/2015 11:03 pm, KevinSheedy wrote:
> Hi @cjbj <https://github.com/cjbj>
>
> Windows 7 Enterprise Service Pack 1
> Node v4.2.2
> npm 2.14.7
> SQL*Plus: Release 11.2.0.3.0 Production
>
> What compiler are you referring to? I haven't seen anything about a dependency on a compiler in the docs?
> Thanks


Check out
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin
and
https://community.oracle.com/docs/DOC-931127

**Comment by KevinSheedy** [comment]
Thanks @cjbj 
I've created a [Pull Request](https://github.com/oracle/node-oracledb/pull/313) with some suggested changes to the README.md
