### ISSUE TITLE
Character set

### ISSUE THREAD

**Issue by brunodenis** [oracle/node-oracledb#312]
CharacterSet is default to AL32UTF8 but this causes issues when reading data with accents.

https://docs.oracle.com/database/121/NLSPG/ch3globenv.htm#NLSPG193:
"Should the NLS_LANG Setting Match the Database Character Set?"
"The NLS_LANG character set should reflect the setting of the operating system character set of the client. For example, if the database character set is AL32UTF8 and the client is running on a Windows operating system, then you should not set AL32UTF8 as the client character set in the NLS_LANG parameter because there are no UTF-8 WIN32 clients. Instead, the NLS_LANG setting should reflect the code page of the client. For example, on an English Windows client, the code page is 1252. An appropriate setting for NLS_LANG is AMERICAN_AMERICA.WE8MSWIN1252."

How can I change default characterset ? setting proper env values does not affect results, accents are never shown.
Thanks in advance for your help.

**Comment by cjbj** [comment]
You can't change the character set (without modifying the source); we set it to AL32UTF8 to be congruent with V8's use of UTF8 for Javascript strings.

Are you able to represent your data in a JS string?

**Comment by brunodenis** [comment]
What do you mean by represent ?
Data I get :
{ rows: [ { TEST: 'roro' }, { TEST: 'r‚ro' } ],
  resultSet: undefined,
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'TEST' } ] }
Data I should get :
{ rows: [ { TEST: 'roro' }, { TEST: 'réro' } ],
  resultSet: undefined,
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'TEST' } ] }

**Comment by cjbj** [comment]
@brunodenis, can you

- use 'réro' in a Node app that doesn't include node-oracledb
- give us a proper testcase (including SQL*Plus script to create data, list the versions of everything, give us information about your Oracle NLS settings, the OS codepages etc)

Thank you.

**Comment by cjbj** [comment]
@brunodenis any news?

**Comment by cjbj** [comment]
Closing due to lack of feedback. 

Our NLS team say the referenced doc refers to typical Windows configurations: as long as data processed by node-oracledb is guaranteed to be UTF-8 then the node-oracled to DB communication is OK.
