### ISSUE TITLE
ORA-24416: Invalid session Poolname was specified

### ISSUE THREAD

**Issue by mchapliuk** [oracle/node-oracledb#314]
oracledb v.1.5.0
oracle XE 11
node v.5.0.0

Hello,

I'm trying to use Connection Pool in my app. Connections work well, but after I decided to use pools, I've got a problem when I'm accessing a connection 
`ORA-24416: Invalid session Poolname was specified`:

```javascript
db.createPool(connAttrs, function (error, pool) {
        console.log(pool);
        if (error) {
            utils.handleError(response, 500, 'Error creating a connection Pool', error.message);
            return;
        }

        pool.getConnection(function (error, connection) {
            if (error) {
                console.trace();
                console.log(error);

                ----- >> * PROBLEM GOES IN THIS BLOCK *
                utils.handleError(response, 500, 'Error connecting to DB', error.message);
                return;
            }

            connection.execute(
                'SELECT ...',
                function (error, result) {
                    if (error) {
                        utils.handleError(response, 500, 'Error getting the User', error.message);
                    } else {
                        if (result.rows.length === 1) {
                            console.log(result);
                            response.writeHead(200, {
                                'Content-type': 'application/json'
                            });
                            response.end(JSON.stringify(new UserModel(result.metaData, result)));
                        }

                        // response.end(JSON.parse(result.rows));
                    }

                    // release the connection
                    connection.release(function (error) {
                        if (error) {
                            console.log(error.message);
                        } else {
                            console.log('POST /login : connection released');
                        }
                    });
                });

        })

        pool.terminate(function (error) {
            if (error) {
                console.error('Pool teminate error: %s', error.message);
            } else {
                console.log('Pool /login : terminated');
            }
        });
    });
```

What am I doing wrong?

*UPD*: logs

`/u01/app/oracle/diag/tnslsnr/ppp-laptop/listener/trace/listener.log`

Started with pid=12526
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=ppp-laptop)(PORT=1521)))
Listener completed notification to CRS on start

TIMESTAMP * CONNECT DATA [* PROTOCOL INFO] * EVENT [* SID] * RETURN CODE
WARNING: Subscription for node down event still pending
28-DEC-2015 12:50:53 * (CONNECT_DATA=(CID=(PROGRAM=)(HOST=ppp-laptop)(USER=oracle))(COMMAND=status)(ARGUMENTS=64)(SERVICE=LISTENER)(VERSION=186647040)) * status * 0
Dynamic address is already listened on (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=ppp-laptop)(PORT=1521)))
28-DEC-2015 12:50:54 * service_register * XE * 0
28-DEC-2015 12:50:55 * service_update * XE * 0
28-DEC-2015 12:51:00 * service_update * XE * 0
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=ppp-laptop)(PORT=8080))(Presentation=HTTP)(Session=RAW))
28-DEC-2015 12:51:01 * service_update * XE * 0
Mon Dec 28 12:51:04 2015

**Comment by cjbj** [comment]
From quick code inspection are you terminating the pool too soon? Try removing the terminate() call.

**Comment by mchapliuk** [comment]
@cjbj Thanks, it works!
