### ISSUE TITLE
Failure on calling Oracle Function

### ISSUE THREAD

**Issue by avorobyev** [oracle/node-oracledb#315]
I have oracledb 0.9.0 I'm calling the function (custom one listed above as well as code for calling) and it works fine on Mac OS but fails on Windows. Error provided below.

FUNCTION GET_NEXT_BUSINESS_DATE (start_date IN DATE DEFAULT sysdate,  days_ahead IN NUMBER DEFAULT 1) RETURN DATE;

Code for calling function:

module.exports.getNextBusinessDate = function (startDate) {
    module.exports.log("Getting next business date");
    var dateToCheck = startDate;
    if (!startDate) {
        dateToCheck = new Date();
    }
    dateToCheck = new Date();
    console.log(dateToCheck);
    return execute(econUser,
        "BEGIN " +
        ":ret := PACKAGE_NAME.GET_NEXT_BUSINESS_DATE(:dateToCheck);" +
        "END;",
        {
            dateToCheck: {
                type: oracledb.DATE,
                dir: oracledb.BIND_IN,
                val: dateToCheck
            },
            ret: {
                dir: oracledb.BIND_OUT,
                type: oracledb.DATE
            }
        }
    ).then(function (result) {
        return result.outBinds.ret;
    }, function(error) {
        return console.log(error);
    });
};

Error I'm getting:

Getting next business date Mon Dec 28 2015 15:47:12 GMT-0800 (Pacific Standard Time)

events.js:85 throw er; // Unhandled 'error' event ^ Error: protractor exited with code 3221225477

npm ERR! Windows_NT 6.1.7601 npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "protractor" "--" "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=********" npm ERR! node v0.12.7 npm ERR! npm v2.11.3 npm ERR! code ELIFECYCLE npm ERR! SVB-Angular@0.0.0 protractor: gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=********" npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the SVB-Angular@0.0.0 protractor script 'gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=********"'. npm ERR! This is most likely a problem with the SVB-Angular package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=********" npm ERR! You can get their info via: npm ERR! npm owner ls SVB-Angular npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request: npm ERR! C:\Integration_test_040new\npm-debug.log Build step 'Execute Windows batch command' marked build as failure Finished: FAILURE

Is there any bug in oracledb specific for Windows or it is a wrong usage?

**Comment by cjbj** [comment]
Upgrade from 0.9 to the current node-oracledb 1.5 and try again.

**Comment by cjbj** [comment]
Closing due to lack of response.
