### ISSUE TITLE
How support oracle 9i

### ISSUE THREAD

**Issue by PanYuntao** [oracle/node-oracledb#316]
Hello,
I've got a problem when I'm accessing a connection ,get error [Error: ORA-03134: Connections to this server version are no longer supported. 

oracledb v.1.5.0
Oracle9i Enterprise Edition Release 9.2.0.1.0 
node v.0.12

**Comment by kubo** [comment]
@PanYuntao 
What Oracle client version do you use?

According to [this Oracle Japan page](http://www.oracle.com/jp/system-requirement/interoperability-support-195844-ja.html) (You need Oracle support ID to see its original English document `Note:207303.1`.)

client  |  server | interoperability
------- | ------ | -----
12.1.0 | 9.2.0 | Error: ORA-03134
11.2.0 | 9.2.0 excluding 9.2.0.1, 9.2.0.2 and 9.2.0.3 | supported
11.2.0 | 9.2.0.1, 9.2.0.2 and 9.2.0.3 | not supported

**Comment by kubo** [comment]
Connections between Oracle 10.1.0 client and Oracle 9.2.0.1 server were supported.
Could you install Oracle 10.1 instant client and try the following command instead of `npm install oracledb`?
```shell
npm install "github:kubo/node-oracledb#oracle10g"
```
It installs node-oracledb which may work with Oracle 10.1 or higher client.
https://github.com/kubo/node-oracledb/commit/30b31d065af908ef0c422794511ddf87133c4f8e

Well, I confirmed that it was successfully compiled with Oracle 10.1 but haven't tested whether it works.

**Comment by PanYuntao** [comment]
@kubo  Thanks for your help ,my Oracle client is 11.2  ,Oracle Server is 9.0.1 .
run `npm install "github:kubo/node-oracledb#oracle10g"` get error:
```
[root@ccit LightappSync]# npm install "github:kubo/node-oracledb#oracle10g"
npm ERR! git clone git@github.com:github:kubo/node-oracledb undefined
npm ERR! git clone git@github.com:github:kubo/node-oracledb undefined
npm ERR! addLocal Could not install github:kubo/node-oracledb#oracle10g
npm ERR! Error: ENOENT, stat 'github:kubo/node-oracledb#oracle10g'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by cjbj** [comment]
Try the official node-oracledb with 11.2 client - it may actually work.  But Oracle Database 9.2 is obsolete and isn't getting patches etc so I can't recommend using it. The support note no longer says 'supported' - it says 'was [supported]'

There is a difference between 'supported' (as in telephone support & patches) and 'supported' (as in works). The matrix generally lists the former. I forget whether the early 9.2.0.x database versions can actually be connected to from 11.2 client.  Try it and let us know.  And then upgrade your database.

**Comment by PanYuntao** [comment]
I try run my app  use node-oracledb again,it's ok!  client version 11.2
 ,database server version 9.2.0.1 ,
Can't run in the morning,I guess it's a database problem 。:(

2016-01-04 10:39 GMT+08:00 Christopher Jones <notifications@github.com>:

**Comment by cjbj** [comment]
@PanYuntao thanks.
