### ISSUE TITLE
setting LD_LIBRARY_PATH from within node script on Linux?

### ISSUE THREAD

**Issue by vrmerlin** [oracle/node-oracledb#317]
On my Linux server, I can set the environment variable LD_LIBRARY_PATH to /app/tools/oracle/12.1/instantclient_12_1 and my application works fine. However, I'd rather set that environment variable from within my www startup script:

```
process.env.LD_LIBRARY_PATH = '/app/tools/oracle/12.1/instantclient_12_1';
var orawrap = require('orawrap');
var oracledb = require('oracledb');
```

but when I do this, I get an error (``libclntsh.so.12.1: cannot open shared object file: No such file or directory``). 

My reasoning is that I'd like to have the specific Oracle client version reference stored with the source code, not with the user login scripts.  Any ideas on why this doesn't work?

John

**Comment by cjbj** [comment]
Generally you can't control when a process will do symbol resolution, so you need to set environment variables like LD_LIBRARY_PATH (and ORACLE_HOME, if used) in the parent shell of the process that uses client libraries.

**Comment by vrmerlin** [comment]
darn... ok, thanks. Sigh, i love node.js but miss JDBC....
