### ISSUE TITLE
Issue trying to use koa.js generators

### ISSUE THREAD

**Issue by sdbroscious** [oracle/node-oracledb#319]
When I look at the sample node-oracle code in the git repo, it all appears to be based on nested callbacks. I’m trying to integrate it into a node.js project that uses koa.js as the web server. The cool thing about koa is that it relies on co.js and generators to help manage flow within an app. The trouble I’m having is in a REST endpoint that calls out to oracle via node-oracle to return a result set that’ll then be displayed. The problem appears to be that with the nested callbacks I can’t leverage koa’s strength to tell the process (function call out to oracle) to, essentially, wait until it returns before rendering the body to a client. Lastly, I’m trying to move the oracle code to a separate file/function in an effort to separate concerns: the endpoint is the controller and the oracle code becomes the model (or data object layer).

Not sure if this makes any sense but thought I’d take a stab and see if you have any advice.

Thanks,

David

**Comment by ecowden** [comment]
The root issue is that node-oracledb relies on the callback style, like most pre-ES2015 APIs, including Node's core APIs. Functions accept a callback -- they don't return a promise. What co and koa are doing with `yield` is to automagically resolve promises. Essentially, it's the same thing that async/await will give us with ES2016, but it works now. If you don't have a promise, however, `yield` doesn't do you any good.

The good news is that you can use a library like [bluebird](http://bluebirdjs.com/docs/getting-started.html) to "promisify" callback-style APIs so that they return promises. It's something I expect to be doing a lot while the community gets around to adopting promises directly:

```
'use strict'

const koa = require('koa')
const oracledb = require('oracledb')
const bluebird = require('bluebird')

module.exports = {
  list: function* list(next) {
    // Use the bluebird library to "promisify" the callback-style function.
    // See bluebird's docs for more details.
    const getConnection = bluebird.promisify(oracledb.getConnection, {
      context: oracledb
    })
    
    // Demonstration only. Ideally, this would come from a pool instead of
    // opening a new connection for each request.
    let conn = yield getConnection({
      user: "...",
      password: "...",
      connectString: "..."
    })

    // Another way to "promisify" callback-style functions
    conn = bluebird.promisifyAll(conn)

    try {
      // Yield to the promise returned from the promisified function.
      // note that we're calling "executeAsync", not "execute"!
      let result = yield conn.executeAsync(
        "SELECT * FROM wherever",
        [],
        {
          outFormat: oracledb.OBJECT
        }
      )
      // Do whatever we want with the result
      this.status = 200
      this.body = result.rows
    } catch (e) {
      // TODO error handling as appropriate
    } finally {
      // TODO this can be better generalized
      conn.releaseAsync()
    }

  }
}
```

**Comment by cjbj** [comment]
I'd love to see some posts on topics like this.  Maybe even an OTN article.  Any volunteers?

**Comment by ecowden** [comment]
Barring any surprises, I can probably put something together later this week or this weekend. What would you like to see? The various ways of working with async, such as callbacks, promises, async generators and async/await? More about using node-oracledb with co and koa? Something else?

**Comment by cjbj** [comment]
@ecowden if you want to write for OTN, I'd need a summary to forward to OTN to see if they have budget and will commission an article.  Or you just could post here at your own leisure and depth. Other than that, yes to all the above.

**Comment by ecowden** [comment]
I decided to tackle `generators` and `co` first. I tried to avoid retreading old ground and tackled it from a bit different direction. [Here's it is.](https://medium.com/@evan.cowden/what-do-generators-have-to-do-with-async-77fc59dc1f8d#.jbj4ioy2u).

Next up is some discussion of Oracle with Koa!

**Comment by cjbj** [comment]
@ecowden A great start.  I'm looking forward to the next episode.

**Comment by cjbj** [comment]
Closing this old thread.
