### ISSUE TITLE
Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by senlin-wei** [oracle/node-oracledb#320]
yesterday i have installed and run frist right; but today it run this error. please tell me why.
Error: The specified procedure could not be found.
f:\test\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (f:\git_new\course1\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by cjbj** [comment]
Check your `PATH`.

**Comment by cai520senlin** [comment]
OCI_INC_DIR ： C:\instantclient_12_1\sdk\include 
OCI_LIB_DIR ：C:\instantclient_12_1\sdk\lib\msvc
path : C:\instantclient_12_1
i just write this in my path

**Comment by schuttsm** [comment]
I'm seeing this issue too.  npm install worked fine.

Running nodejs 5.3 on windows 7.  Python 2.7, vc++ 2015

**Comment by cjbj** [comment]
@schuttsm Check PATH is OK and you have the 32 or 64 bit Oracle client libraries, which ever you need to match your environment.

**Comment by happilymarrieddad** [comment]
@cjbj  hey man you helped me with a development server and now I'm having this problem on a production server. It keeps saying precedure not found.. I set the LIB and INC environmental variables, downloaded the SDK and Basic Libraries, set the path and it keeps saying procedure not found.. Do you know what could be causing this?

**Comment by cai520senlin** [comment]
if you set the LIB and INC path right and use vs2010  under normal condition, it will install this library right .not found just a path error.

**Comment by happilymarrieddad** [comment]
nm after messing with it for a while I got it to work. Thanks!

**Comment by cjbj** [comment]
@cai520senlin can this be closed now?

**Comment by cjbj** [comment]
Closing due to lack of feedback.

**Comment by ashishnayak7** [comment]
I am facing this issue, please help!

**Comment by ronakpatil** [comment]
@ashishnayak7 me too...Can you please help

**Comment by cjbj** [comment]
@ronakpatil This is a closed issue.  Open a new issue and provide the details the issue template suggests.  Thanks!
