### ISSUE TITLE
unable to install oracledb from npm install

### ISSUE THREAD

**Issue by rapidosai** [oracle/node-oracledb#324]
I am unable to install oracledb by doing npm install oracledb
This is the error I am getting,

npm ERR! EBUSY, rmdir 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
npm ERR! error rolling back Error: EBUSY, rmdir 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build'
npm ERR! error rolling back at Error (native)
npm ERR! error rolling back { [Error: EBUSY, rmdir 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build']
npm ERR! error rolling back errno: -4082,
npm ERR! error rolling back code: 'EBUSY',
npm ERR! error rolling back path: 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build' }

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\vsaipras\Desktop\nodeoracle\npm-debug.log

**Comment by isian8814** [comment]
Is it because you are missing the Oracle Instant Client Basic and SDK Packages ?

**Comment by cjbj** [comment]
Check out:
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin
https://community.oracle.com/docs/DOC-931127
https://github.com/oracle/node-oracledb/issues/18

**Comment by cjbj** [comment]
Closing due to lack of feedback.
