### ISSUE TITLE
When inserting values with date using stored procedure

### ISSUE THREAD

**Issue by amjadparacha** [oracle/node-oracledb#325]
I want to insert some records in database using oracle stored procedure through nodejs, input parameters contains all kind data of datatypes. Every time i call this stores procedure i get "ORA-00900: invalid SQL statement" error.

parseXMLFromRequest(req, function(bindInsert){
	if(bindInsert){
		connection.execute("BEGING LG_TRANSACTION_REQUEST_LOG_PKG.INSERT_RECORD(:O_LOG_ID, :P_TRANSACTION_ID, :P_REQUEST_DATE, :P_MSISDN, :P_SERVICE_ID, :P_REQUEST_TYPE, :P_OPERATION, :P_VENDOR_ID, :P_IP, :P_INFO_TYPE, :P_SERVICE_TYPE, :P_CONSENT_TYPE, :P_PartyA_PartyB, :P_PartyA_MSISDN, :P_IsCampaign, :P_Consent_Expiry, :O_ErrorCode, :O_ErrorDesc); END;", 
		bindInsert,
		function (err, result) {
			if (err || result.rowsAffected === 0) {
				// Error
				res.set('Content-Type', 'application/json');
				res.status(400).send(JSON.stringify({
					status: 400,
					message: err ? "Input Error" : "User doesn't exist",
					detailed_message: err ? err.message : ""
				}));
			} else {
				// Resource successfully updated. Sending an empty response body. 
				res.status(204).end();
			}
		});
	}
});

function parseXMLFromRequest(req, cb){
	req.setEncoding('utf8');
	if(req.method == 'POST'){
		req.on('data', function(data){
		var parser = new xml2js.Parser();
		parser.parseString(data, function(err, result){
			var bindInsertVars = {
				O_LOG_ID:			{type: oracledb.NUMBER, dir: oracledb.BIND_OUT},
				P_TRANSACTION_ID: 	result.LocationRequestMessage.RequestHeader[0].TranscationID[0],
				P_REQUEST_DATE: 	new Date().toISOString().replace(/T/, ' ').replace(/\..+/, ''),
				P_MSISDN: 			result.LocationRequestMessage.RequestBody[0].MSISDN[0],
				P_SERVICE_ID:		result.LocationRequestMessage.RequestBody[0].ServiceID[0],
				P_REQUEST_TYPE: 	1,
				P_OPERATION:		1,
				P_VENDOR_ID:		result.LocationRequestMessage.RequestHeader[0].TranscationID[0],
				P_IP:			req.headers['host'],
				P_INFO_TYPE:		1,
				P_SERVICE_TYPE: 	0,
				P_CONSENT_TYPE:		0,
				P_PartyA_PartyB:	0,
				P_PartyA_MSISDN:	"",
				P_IsCampaign:		0,
				P_Consent_Expiry:	0,
				O_ErrorCode:		{type: oracledb.STRING, dir: oracledb.BIND_OUT, maxSize: 40},
				O_ErrorDesc:		{type: oracledb.STRING, dir: oracledb.BIND_OUT, maxSize: 400}
			};
			cb(bindInsertVars);
		});
		});
	}	
}

**Comment by dmcghan** [comment]
Just going for the "low hanging fruit" here, try changing `BEGING` to `BEGIN`.

**Comment by amjadparacha** [comment]
my bad....thanks dmcghan
