### ISSUE TITLE
Install/Run example step: set LD_LIBRARY_PATH Fedora 23

### ISSUE THREAD

**Issue by kbitson** [oracle/node-oracledb#326]
Using XE 11g on Fedora 23

After install, running an example program threw
<code>libclntsh.so.11: cannot open shared object file: No such file or directory</code>

I had to run 
<code> export LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib </code> 

instead of using <code>source</code>

**Comment by cjbj** [comment]
Thanks for the report.  I don't know what you were `source`ing but LD_LIBRARY_PATH needs to be set. This is mentioned in https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instzip

**Comment by kbitson** [comment]
Referencing step 4.3 from Installation on Linux with a Local Database. Step 4.3 states that the <code> LD_LIBRARY_PATH </code> can be set by sourcing <code> oracle_env.sh </code>
