### ISSUE TITLE
Add Examples for returning cursor as an array for use in Node scripts

### ISSUE THREAD

**Issue by Anthropic** [oracle/node-oracledb#328]
It would help new Node developers using Oracle to update the refcursor example to show how to compile a cursor into an array result for use by Node instead of just showing how to console.log everything.

Anyone can make up their own variant, but an official best practise supported method would be a great seed for developers to start from.

**Comment by cjbj** [comment]
@Anthropic can you submit a pull request?

**Comment by Anthropic** [comment]
Do you prefer a change to the current one or add a new one if I have time?

**Comment by cjbj** [comment]
@Anthropic Perhaps a new one?  But I'm open to an update if you want.  Don't forget to submit an OCA request as per https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md

**Comment by derickbailey** [comment]
I was going to open a request for the same, as I've found it rather difficult to deal with the require recursion to pull all of the data that is needed. i'd be happy to try my hand at this, review @Anthropic's code, or whatever i can do to help on this.

**Comment by Anthropic** [comment]
I haven't got time until the end of the month so if you have any free time
prior to that by all means give it a go Derick! :)

**Comment by derickbailey** [comment]
ok, i've got something worth sharing at least: https://gist.github.com/derickbailey/26eaf4e144eea851af01

I don't know that this is really good enough to submit to this repo as documentation or a good example... this isn't the greatest code, yet... but it's what i'm currently using in my app and it serves my needs.

if other people like this, i can certainly submit it or a modified version of it (recognizing that i'll have to drop my copyright claim, etc - i've already signed the oracle contributor agreement)

**Comment by derickbailey** [comment]
ok, i've got something worth sharing at least: https://gist.github.com/derickbailey/26eaf4e144eea851af01

I don't know that this is really good enough to submit to this repo as documentation or a good example... this isn't the greatest code, yet... but it's what i'm currently using in my app and it serves my needs.

if other people like this, i can certainly submit it or a modified version of it (recognizing that i'll have to drop my copyright claim, etc - i've already signed the oracle contributor agreement)

**Comment by cjbj** [comment]
@derickbailey did you ever get your OCA sorted?

**Comment by cjbj** [comment]
The current [`refcursor.js`](https://github.com/oracle/node-oracledb/blob/master/examples/refcursor.js) example shows how to use node-oracledb 5.2's `getRows()` to get all the rows back in an array with one call.  And although the other example snippet shows a loop over `getRows(numRows)` that does call `console.log()`, it's easy enough for any JavaScript developer to append to an array in that loop, if an array is desired.

I don't see us doing more, so I'm going to close this enhancement request.
