### ISSUE TITLE
best practice for opening / closing connections?

### ISSUE THREAD

**Issue by derickbailey** [oracle/node-oracledb#331]
In my previous experience with Oracle and .NET, I would typically open a connection at application startup and re-use that one connection throughout the life of the application. The intent was to not overwhelm the Oracle server with too many connections, as the apps tended to have a lot of users. 

Now, working in Node, I find myself wondering if this is what I should be doing, still. 

I don't think want to open one connection per request lifecycle, as I could have thousands of requests per second... but i'm wondering what the best practice really is. 

Should I open one connection at app startup, and just re-use it? Or should I do connection per HTTP request? Or ???

**Comment by cjbj** [comment]
@derickbailey somewhere in the middle you should find a sweet spot balancing performance and resource utilization.  You would almost certainly not want to open a connection per request for any app under load. Start with a small node-oracledb connection pool and do some benchmarking with your app(s).  If, in future, you end up with a lot of mid-tier processes and hence connections, and as a result are starting to see DB resource issues from having a lot of connections, then look at also using DRCP.

**Comment by derickbailey** [comment]
can you expand on that a little? 

what is the general use case for the connection pool? where should it be set up, and when should a connection from the pool be used? 

should i request a connection from the pool for each stored proc that i need to call? or ???

thanks!

**Comment by cjbj** [comment]
If your 'mid-tier' aka Node.js is not giving enough throughput because user requests are waiting for your single connection to become available, then consider using a pool.  Start the pool when Node starts, and then get/release connections as required.

There are some points on page 8 & 9 in the still valid whitepaper http://www.oracle.com/technetwork/database/database-technologies/php/whatsnew/building-best-drivers-131920.pdf  [node-oracledb's connection pool internally uses an OCI Session Pool]

**Comment by derickbailey** [comment]
Ok, that's making more sense now. I'll check out that pdf as well. Thanks, yo!

**Comment by derickbailey** [comment]
one more q: 

in the docs for connection pooling, it says that the connection should be released when no longer neeeded (https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connpooling). Does this mean I should always do `pool.getConnection(...)` and `connection.release(...)` for every call I make? 

```js
pool.getConnection((err, conn) => {

  // ... do stuff

  conn.release(errorHandler);

});
```

**Comment by derickbailey** [comment]
nevermind. i answered my own question by not closing my connections and the pool telling me there are too many open connections :)

**Comment by cjbj** [comment]
Don't forget to release connections in your error handling code paths too.
