### ISSUE TITLE
CPU spike / leak, when sending SIGINT to running process with open connection

### ISSUE THREAD

**Issue by derickbailey** [oracle/node-oracledb#332]
If I have an open connection within my Express.js app, and I send a SIGINT (pressing ctl-c or using the `kill` command line), the CPU usage for this node process will spike to > 100% and run forever.

This happens with nothing more than a default Express.js app, and having one open connection to Oracle within the app. For demonstration purposes, I have created a repository with the needed code, here: https://github.com/derickbailey/node-oracledb-cpu-leak

Here is a screenshot showing the CPU after starting my demo app: 

![image](https://cloud.githubusercontent.com/assets/75190/12430359/d647c3c8-beb4-11e5-8bf8-b84ace030218.png)

Here is a screenshot of me pressing ctl-c once:

![image](https://cloud.githubusercontent.com/assets/75190/12430398/0773da2c-beb5-11e5-81d7-bff81a9953a1.png)

And finally, the resulting CPU spike:

![image](https://cloud.githubusercontent.com/assets/75190/12430406/1984eeea-beb5-11e5-8f58-326609764d62.png)

I don't know what the cause of this is, but I can prevent this by not opening an Oracle connection in the demo code. The other fix that I know of, so far, is to ensure my Oracle connection is closed by capturing `process.on("SIGINT", ...)` and `process.on("oncaughtException", ...)` to ensure I close my connection. But this is a workaround, I think, and may still allow the possibility of the Oracle library spiking my CPU and leaking the TCP/IP port binding from Express.

**Comment by cjbj** [comment]
Thanks for the analysis.  I'm going to close it as a dup of #128, which we still have high on the todo list.

**Comment by derickbailey** [comment]
ok, cool. i didn't see that other one when i searched the issues... guess i looked for the wrong terms :)
