### ISSUE TITLE
Rewrite in typescript

### ISSUE THREAD

**Issue by Bigous** [oracle/node-oracledb#333]
Hi @cjbj , I'm working with angular2 for while now and having the typescript definitions is awesome - code completion, hints, etc... I wrote an oracle.d.ts and made a pull to TSD people DefinitelyTyped/DefinitelyTyped#7697 but I was thinking that it would be great to rewrite the javascript part of the driver in typescript and expose the definitions and so on, so we don't need tsd to have the oracledb definitions... and it would be generated automatically by the typescript transpiler...

We have an issue #169 asking for that too...

I could halp with it, what do you think?
[]s

**Comment by cjbj** [comment]
@Bigous Sounds cool, but is there enough JS to merit another layer of abstraction?  If it makes development and debugging and maintenance easier, and attracts contributors then we could do it.  (BTW, any comments on https://github.com/oracle/node-oracledb/pull/321#issuecomment-172214766 ?) 

@dmcghan any comments?

**Comment by Bigous** [comment]
@cjbj Typescript is Javascript with types... When I submitted the issue I was thinking about having just the 2 javascript files written in typescript, so the driver would get easier to use (because the typing and help would be at the script part which would be bundled with the driver... I was not thinking about having it entirely in Typescript... But I liked the idea.

**Comment by dmcghan** [comment]
Generally speaking, I like TypeScript. I like what it does and what it has to offer. For medium to large projects I can understand why a development group may chose to use it. However, the driver is mostly developed in C. Excluding the tests and examples there's only about 100 lines of JavaScript code so I'm not really sure what, if anything, TypeScript would have to offer at this point.

Also, one of the main motivators of expanding the JavaScript layer is to allow the JavaScript community more opportunity to contribute to the project. There are a lot of people that know JavaScript but TypeScript has not become mainstream, and like CoffeeScript, it may never become the norm. 

My vote would be to stick with plain old JavaScript for now. If TypeScript ever becomes the norm or if the project ever gets to an unruly size, then I'd revisit this issue. 

In the mean time I do think we should provide and maintain a .d.ts file for the library.

**Comment by cjbj** [comment]
@Bigous a thin driver (either in pure JS or typescript) is a dream but not a plan.  Node-oracledb will be based on Oracle Client for the foreseeable future.

**Comment by Bigous** [comment]
Agreed with both... about .d.ts, I posted one in tsd repository... if you thing we should move it to be here, I can make a pull request here.
About the adoption of Typescript, it is increasing a lot... specially after angular2 adopting it.
But for now, we should stick to the plan. I'll close the issue, when we get more js code ill open another one...

**Comment by bjouhier** [comment]
There is also a lot of activity around [flow](http://flowtype.org/). Flow has the advantage of being a lot less intrusive than typescript: it can be added incrementally and it does not impose a new language. It also has some very cool features like distinguishing between nullable and non-nullable types. The React and Babel communities are behind it.

So the matter is not settled and it is probably wise to be in wait-and-see mode at this stage.

**Comment by Bigous** [comment]
Typescript does not impose a new language and it can be added incrementally too... the comunities behind it are Microsoft and Google... but yeap... lets wait more ;)

**Comment by bjouhier** [comment]
@Bigous thanks for the correction. I had looked at typescript very early and it was its own language at the time. I had missed the convergence with ES6. Makes it much more attractive.
