### ISSUE TITLE
Unresolved link on Oracle

### ISSUE THREAD

**Issue by roboweaver** [oracle/node-oracledb#34]
I'm wondering if the node-oracledb needs to have the 32-bit Instant Client = I'm getting link errors and the version of msvc that is being called is in the Program Files (x86) folder which would indicate that a 32-bit executable is being used.

My current failure is when it tries to link:

```
     Creating library C:\Users\rweaver\AppData\Roaming\npm\node_modules\oracled
  b\build\Release\oracledb.lib and object C:\Users\rweaver\AppData\Roaming\npm\
  node_modules\oracledb\build\Release\oracledb.exp
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIHandleFree [C:\U
sers\rweaver\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIEnvCreate [C:\Us
ers\rweaver\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
```

A bunch more link errors print, but all seem to be related to the build project in the oracldb/build folder.

I can post the log if you need, the npm error on the screen is:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rweaver\AppData\Roaming\npm\node_modules\oracledb
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! oracledb@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@0.3.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! cwd C:\Projects\3rdParty.new\oracle\node-oracledb
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by cjbj** [comment]
You can build with 64 bit client.  We haven't tested 32bit but other people report it works.
To help people identify your issue, can you list what you have done and installed, and how you installed it, starting with letting us know which version of Windows you have!  Thanks.

**Comment by mradamlacey** [comment]
I got this working successfully after much gnashing of teeth.

My environment:
- WIndows 7 x64
- Visual Studio 2013 compiler (vc12)
- NodeJS x64 v0.10.35
- Python 2.7

_Here's my important notes:_

- Follow instructions from `README.md`, take care of the following:
  - Make sure the NodeJS architecture (x86 vs x64) matches the architecture of the Oracle client installation
  - Do NOT set the `PYTHON` environment variable (or if you do make sure it works) - if this env var is not pointing at a Python executable then `node-gyp` is going to fail with process `spawn ENEONT` errors
- Use NodeJS v0.10.35 - haven't tested on another version
- Find `~./node-gyp/0.10.35/common.gypi` - for me this was in: `%USERPROFILE%\.node-gyp\0.10.35` (this could be different depending on how you installed node, and if you chose a different node version)
    - Make the following changes below to add `msbuild_toolset` line to the below `Debug` section AND to the `Release` section.

```javascript
'Debug': {
  'defines': [ 'DEBUG', '_DEBUG' ],
  'cflags': [ '-g', '-O0' ],
  'conditions': [
    ['target_arch=="x64"', {
      'msvs_configuration_platform': 'x64',
      'msbuild_toolset': 'v120_xp'             // added to target VS 2013 compiler
    }],
  ],
  ```

Without this change to `common.gypi` it looks like node-gyp was only targeting the VS2010 compiler (I have both installed on my machine), and I got the following error:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\tools\node-oracledb\build\oracledb.vcxproj]
```

I hope this helps someone...

**Comment by cjbj** [comment]
Thanks for the detail.  This piece of the jigsaw will help.

**Comment by roboweaver** [comment]
My environment:
* Windows 7 x64
* Visual Studio Community 2013
* NodeJS v0.10.36 x64
* Python 2.7.9 x64

I made the modifications to add the msbuild_toolset as shown above (also modified the platform to be x64, since in my common.gypi it was showing x86 before.

I'll try going to the v0.10.35 version to see if that makes any difference.

**Comment by roboweaver** [comment]
OK, it was a bit issue - I had installed x86 when I downgraded to v0.10.36 of Node.

I also had to get around a self-signed certificate error I was seeing as described at http://stackoverflow.com/questions/9626990/receiving-error-error-ssl-error-self-signed-cert-in-chain-while-using-npm

```
npm config set strict-ssl false
```
Got everything built without mucking with the common.gypi this time.

**Comment by jasondouglas777** [comment]
Done!
node 10.35 x64.
Oracle client 12.1 x64.
activatin the right compiler(amd64).

setting the variables:
set client_dir=C:\jason\generic_workspace\oracleclient\instantclient_12_1

set oci_lib_dir=%client_dir%\sdk\lib\msvc
set oci_inc_dir=%client_dir%\sdk\include

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"

set path=%path%;%client_dir%
set lib=%lib%;%client_dir%;
set libpath=%lib%;%client_dir%;

and running installer:
mpn install oracledb.
