### ISSUE TITLE
Installation problem on Windows 7

### ISSUE THREAD

**Issue by yellingmonkees** [oracle/node-oracledb#342]
Hay everybody,

i get an errror installing oracledb on Windows 7. 

I carried out the instructions in the INSTALL.md. 
My configurations by now:

I added the following entries to the PATH variable: 

`C:\Python27\;
C:\Program Files\nodejs\;
D:\Oracle\instantclient;
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include;
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;`

I also added these enviorment variables:

`OCI_INC_DIR = C:\Oracle\instantclient\sdk\include
OCI_LIB_DIR = C:\Oracle\instantclient\sdk\lib\msvc`

Before that i installed NodeJS (64 bit), Python 2.7 (also 64 bit) , Visual Studio 12 CE (32 bit - there is no 64 bit version) and the oracleinstantclient (64 bit) (both: sdk and basic) - version 12. 

When I want to install oracledb via npm i get the following error message: 

`c:\users\trwolff\.node-gyp\4.2.6\include\node\v8.h(18): fatal error C1083: Cann
ot open include file: 'stddef.h': No such file or directory (..\src\njs\src\njs
Connection.cpp) [PATH\TO\PROJECT\node
_modules\oracledb\build\oracledb.vcxproj]`

There are several similar error messages which all refer to different missing files. 

After these errors there is another error: 

`gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1` 

The end of the npm-debug.log files contains the following errors: 

`420 info install oracledb@1.5.0
421 verbose unsafe-perm in lifecycle true
422 info oracledb@1.5.0 Failed to exec install script
423 verbose unlock done using C:\Users\trwolff\AppData\Roaming\npm-cache\_locks\oracledb-bc9e3088268a1dda.lock for C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2\node_modules\oracledb
424 verbose stack Error: oracledb@1.5.0 install: `node-gyp rebuild`
424 verbose stack Exit status 1
424 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
424 verbose stack     at emitTwo (events.js:87:13)
424 verbose stack     at EventEmitter.emit (events.js:172:7)
424 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
424 verbose stack     at emitTwo (events.js:87:13)
424 verbose stack     at ChildProcess.emit (events.js:172:7)
424 verbose stack     at maybeClose (internal/child_process.js:821:16)
424 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
425 verbose pkgid oracledb@1.5.0
426 verbose cwd C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2
427 error Windows_NT 6.1.7601
428 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
429 error node v4.2.5
430 error npm  v2.14.12
431 error code ELIFECYCLE
432 error oracledb@1.5.0 install: `node-gyp rebuild`
432 error Exit status 1
433 error Failed at the oracledb@1.5.0 install script 'node-gyp rebuild'.
433 error This is most likely a problem with the oracledb package,
433 error not with npm itself.
433 error Tell the author that this fails on your system:
433 error     node-gyp rebuild
433 error You can get their info via:
433 error     npm owner ls oracledb
433 error There is likely additional logging output above.
434 verbose exit [ 1, true ]
435 verbose unbuild node_modules\oracledb
436 info preuninstall oracledb@1.5.0
437 info uninstall oracledb@1.5.0
438 verbose unbuild rmStuff oracledb@1.5.0 from C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2\node_modules
439 info postuninstall oracledb@1.5.0
440 silly gentlyRm C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2\node_modules\oracledb is being purged from base C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2
441 verbose gentlyRm don't care about contents; nuking C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2\node_modules\oracledb
442 silly vacuum-fs purging C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2\node_modules\oracledb
443 silly vacuum-fs quitting because other entries in C:\Users\trwolff\Dropbox\Studium\Sem_06\BI_II\webshop\BI2\node_modules`

I spend almost the whole day trying to fix these issues. 

So I would be very glad for any kind of support! :)

**Comment by cjbj** [comment]
Did you review https://community.oracle.com/docs/DOC-931127 ?
Also did you see the prebuilt binaries at https://github.com/oracle/node-oracledb/issues/18#issuecomment-146434124 ?

**Comment by yellingmonkees** [comment]
@cjbj Yes, I reviewed the installation guide from oracle community. 

Now: I uninstalled Python, Visual Studio and Node. After this I installed Visual Studio 2013 Update 5, Node 4.2.6 (64 bit) and Python 2.7.11 (64 bit). Now I get the following error:

`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [C:\Users\PATH\AppData\Roaming\npm\node_modules\oracled
b\build\oracledb.vcxproj]`

For me it looks like the installation progress expects a different build tool than my installed build tool. Maybe because I installed and uninstalled Visual Studio 2015 CE before?

**Comment by cjbj** [comment]
@yellingmonkees is this still an issue?

**Comment by vshekhar2015** [comment]
I followed the instruction at https://community.oracle.com/docs/DOC-931127 and have been getting this error for a few days now. 

434 error Windows_NT 6.1.7601
435 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb" "--save"
436 error node v4.2.3
437 error npm  v2.14.7
438 error code ELIFECYCLE
439 error oracledb@1.7.1 install: `node-gyp rebuild`
439 error Exit status 1
440 error Failed at the oracledb@1.7.1 install script 'node-gyp rebuild'.
440 error This is most likely a problem with the oracledb package,
440 error not with npm itself.
440 error Tell the author that this fails on your system:
440 error     node-gyp rebuild

**Comment by dominhhai** [comment]
I got this error on Win Server 2008 too.
Are there any ideas to fix this problem?

**Comment by dominhhai** [comment]
I have installed successfully on my Win Server 2008 64 bit.
In my case, I have to use `node-v0.12.7-x64` version.
Node `4` or `5` do not work.

**Comment by sagiegurari** [comment]
@dominhhai you sure you have a new compiler? try using vs community 2015

**Comment by dominhhai** [comment]
@sagiegurari  Thank for your suggestion.
I haven't tested with Community 2015 yet.
I'm using Visual Studio 2012.
And, my question is that: Why can not VS 2012 compile with Node 4 or 5?

**Comment by sagiegurari** [comment]
you need C11 supporting compiler when using node 4 because v8 (google js engine) now needs it to compile.

**Comment by dominhhai** [comment]
:100:  thank you very much!
