### ISSUE TITLE
Assigning connection to a variable

### ISSUE THREAD

**Issue by yusiswtor** [oracle/node-oracledb#347]
Hi,

I've been using oracle for a fair while now, but just started using it for node projects. I'm finding the code hard to maintain, as I need to add tons of gibberish to each api call. There are probably better ways to go around it, but I haven't found them yet (still getting used to it). However, what would be a lot easier to use would be if I could create a variable for the connection similar to how most other db drivers do it. 

In MySQL I'd do this:
```
var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 10,
  host            : 'example.org',
  user            : 'bob',
  password        : 'secret'
});

app.get("/api/example", function(req,res) {

pool.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
  if (err) throw err;
  console.log('The solution is: ', rows[0].solution);
});

});
```

But for oracle, I find myself having to recreate the pool every time I want to perform a query like this:
```
app.get("/api/example", function(req,res) {
  oracledb.createPool (
    {
      user          : "",
      password      : "",
      connectString : ""
    },
    function(err, pool)
    {
      pool.getConnection (
        function(err, connection)
        {
          var sql = 'SELECT 1 + 1 AS solution';
          connection.execute(sql, function(err,results) {
            // handle result / errors / release etc
          });
        });
      }
    );
  });
```

Which makes it lots harder to maintain. Again, there might be an easier way of doing this, but after trying to read your (extensive!) docs, I havent found a better way of doing it.

**Comment by sagiegurari** [comment]
you must reuse the pool and should not recreate it.
For example (really raw and basic example):
````js
oracledb.createPool({
    //pool attributes
}, function (err, pool) {
    if (err) {
        //stop app.... or something...
    } else {
        var app = //create express

        app.get("/api/example", function (req, res) {
            pool.getConnection(function (err, connection) {
                var sql = 'SELECT 1 + 1 AS solution';
                connection.execute(sql, function (err, results) {
                    // handle result / errors / release etc
                });
            });
        });
    }
});
````

**Comment by yusiswtor** [comment]
I realize that's a possibility, but again - it feels clunky. What if I need to perform queries to other db types? It just feels like a mess when I have to create connections within connections.

**Comment by sagiegurari** [comment]
you query multiple DBs? if so create the pools at the boot of your app.
reuse those pools as needed.
I'm not sure what is a mess, and please be specific, because I really would like to understand.
1. using pools? thats the more correct and common way of using database connections. every language/framework got and uses pools.
2. create a pool per DB/schema, ya, that too is common, but another thing which you must do is to reuse those pools, and not create each time a new one. 
3. callbacks in javascript? wrap with promises.

so i'm not sure what is a mess (and i don't work for oracle, but really the api is very common and standard to work with DBs).

**Comment by yusiswtor** [comment]
I work across multiple, and can often run cross-checks on two oracle databases and a mysql database (and occasionally mongodb as well). 

1. I use pools, and those I like. What I'm having issues understanding is how to query multiple pools in the same api route. As far as I can understand, I would need to do something like:

```
oracledb.createPool({
    //pool attributes
}, function (err, pool) {
oracledb.createPool({ 
//pool attrs },
function (e, secondPool) {
// etc etc
```

What I would find to be a lot easier and cleaner in my code, would (simplified) be:
var firstPool = oracledb.createPool({ pool attrs });
var secondPool = oracledb.createPool({ pool2 attrs});

app.get("/api/asd", function(req,res) {
firstpool.execute("select 1+1 as solution", function(e,results) {
// results 1
});
secondpool.execute("select 2+2 as secondSolution", function(e,results) {
// results 2
});
mysqlPool.query("select actualsolution from table", function(e,rows,fields) {
// results mysql
});
// Handle results.
});

Naturally I'd handle all this with promises.

2. Like you say, common, and I use it for mysql as outlined above.

3. I don't know what you're asking here? I have no issues handling my callbacks. 

I don't understand how to reuse the pools in a clean way, without creating pools within pools within pools (poolCeption?), and that's what I find a mess.

**Comment by sagiegurari** [comment]
why not create an object which holds the pools and you access them via name
````js
//boot of app
myPools = {};
oracledb.createPool(..., function (err, pool) {
  myPools.people = pool;
});
//and so on....

//when you need it, for example in some express middleware....
myPools.people.getConnection(....)
myPools.cars.getConnection(....)
````

by the way, something that I use a lot is async: https://github.com/caolan/async
so you could create multiple actions and run them in parallel, sequence and so on....
and i guess each action (function) is handling a different database.

**Comment by yusiswtor** [comment]
I've tried creating an object like that before but it failed horribly. Mayhaps I did it wrong then. I'll give it another whirl - if it is indeed possible to do that, then my question is solved really. 

I'm a huge fan of async myself, and use it extensively where possible (one instance where I'm running ~70 db queries :+1: )

**Comment by yusiswtor** [comment]
Believe @sagiegurari has solved this for me. Closing for now.

**Comment by cjbj** [comment]
@yusiswtor check out https://github.com/sagiegurari/simple-oracledb which @sagiegurari might have been too polite to mention.

**Comment by yusiswtor** [comment]
Thanks @cjbj - will look into it! Don't see how saying that could come across as impolite - like I said, I've not used oracle in node besides a couple of queries, so a simpler api to start off with could be better.
