### ISSUE TITLE
Runtime issue in Windows

### ISSUE THREAD

**Issue by mradamlacey** [oracle/node-oracledb#35]
I was able to build successfully in Windows but running into an issue running an example.  Command:
```
node examples/connect.js
```

output:
```
Error: %1 is not a valid Win32 application.
D:\Users\alacey\AppData\Roaming\npm\node_modules\oracledb\build\Release\oracledb.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Users\alacey\AppData\Roaming\npm\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Anyone have any success in actually running this module on Windows and connecting successfully?

It appears that the native module loader is attempting to load a 32 bit module, but I do know I built node-oracledb using the 64 bit compiler.

I can confirm that I am running the 64 bit version of node.exe...  Any ideas?

**Comment by sagiegurari** [comment]
try with a 32bit node.exe
that is what i use on windows and i also compile with 32bit and it works good.
if it works for you with 32bit node.exe, than it means you compiled it as 32bit which is possible since the node that you use in runtime, might not be same node you used with npm install.

**Comment by roboweaver** [comment]
Took me a few days to get the 64-bit working. You have to make sure everything you have is 64-bit, and that all the appropriate environment variables are properly set.

**Comment by lvchaoin** [comment]
I got exactly the same problem, and change to 32bit node.exe still doesn't work.
I even could not compile with 32bit node.exe, only can compile with 64bit node follow the instruction, here are some out put while compiling with 32 bit node. Any suggestion would be appreciate !
```
 Creating library C:\Users\charlie.lv\AppData\Roaming\npm\node_modules\orac
  ledb\build\Release\oracledb.lib and object C:\Users\charlie.lv\AppData\Roamin
  g\npm\node_modules\oracledb\build\Release\oracledb.exp
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIHandleFree [C:\U
sers\charlie.lv\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxpro
j]
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIEnvCreate [C:\Us
ers\charlie.lv\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj
]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIAttrSet [C:\Use
rs\charlie.lv\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCITransRollback [
C:\Users\charlie.lv\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vc
xproj]
```

**Comment by roboweaver** [comment]
That's the same error I was seeing when trying to compile with a mix of 64 and 32 bit binaries.

In my case I had installed the 32-bit node after I was told I needed to downgrade to the earlier version of node that is required for the node-oracledb to compile. I used the MSI from http://nodejs.org/dist/v0.10.36/x64/

You also have to make sure your OCI environment variables are pointing to the right location for the 64-bit libs and headers as noted in the install guide https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin

**Comment by Bigous** [comment]
Hi @mradamlacey, 
I don't know if you still need help, but when it happend to me was just because oci.dll was not in the path (or had the wrong oci.dll in the path first - eg. if you compile x64 and the one that was find first in the path is x86), so node.js (or iojs) cannot load the oracledb.node because it cannot resolve the dependency.

**Comment by mradamlacey** [comment]
Appreciate the help - I will double check my path and report back with my results.

**Comment by mradamlacey** [comment]
Verified my path (and that `oci.dll` was coming from the expected location) and I am able to successfully compile and run an example.  Thanks for the help!

**Comment by sreeshan90** [comment]
oci.dll was not in path.. Works like a charm now! Thanks mradamlacey!

**Comment by flytoj2ee** [comment]
@mradamlacey yes, same problem in window7 system.
