### ISSUE TITLE
Can't find "msbuild.exe"

### ISSUE THREAD

**Issue by sunojvijayan** [oracle/node-oracledb#351]
When I install, it gives me this error.

gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Stu
dio C++ 2008+ installed?

But I already have Visual studio installed and it is in "C:\Program Files (x86)\MSBuild\12.0\Bin"

Please help.

**Comment by cjbj** [comment]
Did you check https://community.oracle.com/docs/DOC-931127 and https://www.youtube.com/watch?v=I23XTkUMrtM and #18 ?

**Comment by sunojvijayan** [comment]
Yes got it thanks a lot.
