### ISSUE TITLE
Getting meaningful error context

### ISSUE THREAD

**Issue by evan-king** [oracle/node-oracledb#354]
Is there any way to retrieve more meaninful information about errors when they occur?

For example:
`ORA-00932: inconsistent datatypes: expected NUMBER got TIMESTAMP`
On what field/output value did this occur?  Did it happen in the query, or some trigger?

`ORA-00942: table or view does not exist`
What table/view name?  Where in the query was this problem encountered?

`ORA-00911: invalid character`
What character?  And where in the query was it encountered?

As they stand, the error messages barely manage to vaguely gesture in the general direction of the problem.  Am I missing something, or are there plans to flesh out error context later?  At present it seems the best thing I can do is log the query and parameters along with error messages, which is a bit much and still not that helpful.

**Comment by cjbj** [comment]
There is a task on the ToDo list to add more info like offsets to the error object.  But it keeps getting pushed down by bigger issues.  Somethings will be constrained by Oracle's historic design and what the database sends back to OCI.

**Comment by dmcghan** [comment]
This post talks a little more about how Node.js is moving to use error codes:
https://medium.com/the-node-js-collection/node-js-errors-changes-you-need-to-know-about-dc8c82417f65

Something to consider...

**Comment by sagiegurari** [comment]
Might be wrong here, but the issue opened is meant to help developers understand the issue and resolve it during development time and less for automatic handling in the js code based on the error type/code in production.

When a person is asking that the error message will explain what field for example caused the ORA-00932 error, he is asking help to fix his code and not to put an 'if' in his code for ORA-00932.

**Comment by dmcghan** [comment]
@sagiegurari You're right, but someone asked about error codes here: https://github.com/oracle/node-oracledb/issues/732

@cjbj wants to use this issue to track "error message" related enhancements. Sorry for the confusion!

**Comment by sagiegurari** [comment]
ya that one fits exactly what you were talking about.

**Comment by cjbj** [comment]
node-oracledb 2.1 now passes through what is available from the underlying libraries: effectively this is the offset into the SQL statement that caused the problem. 

Some of the original request items are well out of scope for node-oracledb or the underlying libraries: they are Oracle Database messages that are now 'historic' and unlikely to change - but feel free to contact the DB team yourself to make sure they don't repeat old mistakes when they add new messages.  I try to influence developers when I get a chance, too.
