### ISSUE TITLE
What is the correct way to close a ResultSet?

### ISSUE THREAD

**Issue by niallosul** [oracle/node-oracledb#355]
I've just started working with node-oracledb, and have a question about ResultSet processing. I've set up a test script similar to this: [https://github.com/oracle/node-oracledb/blob/master/examples/resultset2.js] 

I'm using a connection pool and I've incorporated async.queue to throttle the connection requests, but nothing too adventurous.  

For the most part it works perfectly. However, every now and then (roughly ever 4-5 test runs)  connection.release() throws the NJS-032 error (Connection cannot be released because a database call is in progress). I've dug through all the documentation I can find, and I'm not sure how this can be happening.

Could the resultset.close() function potentially be calling the callback before all the db work is done? Is there another way to make sure that the db calls are all finished before calling connection.release()?

I've found that simply adding a one second pause before releasing the connection seems to fix the problem, but that's obviously a terrible hack. Whatever database call is in process seems to take an arbitrary time (less that a second) to complete because using nextTick or similar does nothing to fix the problem

Any help greatly appreciated

**Comment by sagiegurari** [comment]
You are going to be asked for a test case real soon :)
But seriously, your description is too high level without any concrete info to help.

**Comment by niallosul** [comment]
Sorry - this wasn't meant to be a issue, just a question about the API. I can put together a simple test case, but so far I'm only seeing the problem with a remote database, so it's a little tricky to recreate locally. 

Specifically I'm asking about [these release notes](https://blogs.oracle.com/opal/entry/node_oracledb_1_5_0)

And the line "If you experience the errors NJS-030, NJS-031 or NJS-032 you should fix your app so the connection release occurs after all database operations have concluded."

All I'm really doing after the resultset rows go to 0 is this:

function doRelease(connection){
 connection.release(function(err){
      if (err) { console.error(err.message); }
  });
}

function doClose(connection, resultSet){
  resultSet.close(function(err){
      if (err) { console.error(err.message); }
      doRelease(connection);
    });
}

But I'm seeing an error on connection.release(), specifcally when it's called from the resultSet.close() callback and I'm not sure what else I can do to ensure all database operations have concluded?

Sorry if this is too high level - should I take to SO?

**Comment by forgotPassword** [comment]
the problem is probably that you are calling doClose too early, not in the actual release code...

**Comment by sagiegurari** [comment]
1. you sure you didn't run any other operation with same connection?
2. any LOBs related to whatever operation you are doing? (LOBs must be read fully once you started)

**Comment by dmcghan** [comment]
@niallosul I don't think you need to take this question to SO. Ultimately you should be able to release the connection if you've truly finished working with it.

@sagiegurari was right... Can you please provide a test case? :)

**Comment by niallosul** [comment]
Thanks all - I put together a test case without using async.queue to throttle the connection requests, and I haven't seen the issue occur, so it's probably just something I'm doing incorrectly in the callbacks for the queue. If I see this come up again (without async.queue), I'll put together a proper test case and submit it
