### ISSUE TITLE
How do we implement connection pooling

### ISSUE THREAD

**Issue by sunojvijayan** [oracle/node-oracledb#356]
I have worked on mySql but not in oracle. Is there any way you can do connection pooling in oracle, If so is there any example for that? Thanks in advance.

**Comment by cjbj** [comment]
Check the manual: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connpooling and look at https://github.com/oracle/node-oracledb/blob/master/examples/webapp.js
