### ISSUE TITLE
Any other tool   for C/C++ build environment to install node oracle db other than visual studio 2013

### ISSUE THREAD

**Issue by vivekbrahmadandi** [oracle/node-oracledb#357]
As visual studio 2013 is not free software, do we have any other alternative to use node oracle db.
I've tried installing gcc compiler using MinGW, it's not working 

Error:

C:\Users\vivekb\AppData\Roaming\npm\node_modules\oracledb\build\binding.sln : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 200
8 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.

**Comment by sagiegurari** [comment]
Visual studio community 2015.
The vs express edition exists for almost 10 years I think and its also free

**Comment by vivekbrahmadandi** [comment]
Thanks   sagiegurari
