### ISSUE TITLE
Extend metaData object of query result with datatype, precision and scale.

### ISSUE THREAD

**Issue by smarushchenko** [oracle/node-oracledb#358]
Hello,

This is enhancement request to get more detailed meta information about query of execute method. Currenly names of columns are only accessible and would be nice to have Oracle datatype and length of columns as well. This information is already collected in dpiStmtImpl.cpp (StmtImpl::getMetaData) but njsResultSet.cpp (NAN_GETTER(ResultSet::GetMetaData)) takes only column names.

Thank you!
Kind regards,
Sergey

**Comment by pvenkatraman** [comment]
Can you describe your requirement more elaborately.  Why do you need database type (Oracle dataType) or do you want database type mapped to v8 type?

**Comment by smarushchenko** [comment]
The simplest case is to let a user to enter and execute sql statement and get results into a grid. Without knowing column datatypes it's impossible to understand even alignment of results. This information may not be necessary when you develop an application against predefined dataset but if you would like to implement some technical or generic solution it would be very helpful. I think Oracle datatypes would be more informative then v8 types for such kind of usage. Likely for some developers it would be useful to have both Oracle and v8 types. It should not be big overhead on memory and network (if any) also as I hope.

**Comment by smarushchenko** [comment]
Also I underestimated simplicity of this improvement. It's quite easy (I hope) for resultSet results but will require more efforts for "simple" (not resultSet) results due to lack of this information within eBaton structure.

**Comment by krismohan** [comment]
By 'grid', if you mean you want to display, you could get all the results as strings. But yes, for alignment, you may want to know the max lengths (for varchar columns). Isn't the requirement by a JS app really to know the JS type equivalents? I agree Oracle type will give more information (like fixed char vs varchar, date vs timestamp etc.), but if majority needs only the JS type and maxlength, we can think of providing them quickly.
Exposing Oracle types is easy for the driver, but it passes the complexity of interpreting it to the app. Want to go with what works best for you!

**Comment by smarushchenko** [comment]
Yes, I meant the UI. It's very important to have facilities to differentiate types of data that come from a database as well as its size. On UI, strings usually aligned to left border but numbers to right one. Knowledge of data size let developers to restrict length and format of input fields and to check values entered by a user .
Since Oracle SQL and PL/SQL are strongly typed in contrast to JavaScript I think that knowledge of Oracle data types provides more significant information for developers. Actually I think its enough to provide numeric value of Oracle data type how it goes from OCI call.
If you say that JS type and maxlength are quite easy for you (though Oracle types are what you already have and not need to map) please implement it at first. I hope it will cover at least 95% of needs Node/Oracle applications.
Thank you for your concern!

**Comment by cjbj** [comment]
Just throwing this out there, since it has some relationship to the question: you're probably aware of USER_TAB_COLUMNS.

**Comment by smarushchenko** [comment]
Yes, I'm aware of Oracle dictionary. But here we have at least two issues:
1 - unnecessary overhead since query metadata are already known
2 - as of my example - for ad-hoc queries it's not always easy to determine names of tables and related columns.

**Comment by leolmi** [comment]
@smarushchenko  waiting for the fix and without any pretense of breaking the terms of the original license, you can use this procedure to perform tests: 
[oracledb-datatypes](https://github.com/leolmi/oracledb-datatypes)

**Comment by cjbj** [comment]
@leolmi Can you submit a PR for the change?  (You will need to sign the OCA - see https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md)

**Comment by smarushchenko** [comment]
@leolmi Thank you! I've just checked your code and it seems to be working fine. Both in ResultSet and not ResultSet modes. Would be nice to see it included into the node-oracledb respository soon. Ohterwise it can become confilcting soon.
Many thanks!

**Comment by sanfords** [comment]
I need this too.  We want to format our dates as they come out of Oracle.  Doing this from the metadata will be decidedly more robust.  :-)

**Comment by sanfords** [comment]
Did someone make a PR on this?  Making another package is kind of odd.  We're hoping to use this to fix #408.

**Comment by cjbj** [comment]
Node-oracledb 1.10 has extended metadata thanks to @leolmi for #386.
