### ISSUE TITLE
Simple cursor example

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#359]
Hello,

  Is there a simple cursor example?  The ones available all seem to involve procedures.  Ideally I'd like to feed the library an arbitrary query and call getRows where I can see a record and/or stream LOBs as necessary.

Thanks!

**Comment by sagiegurari** [comment]
I'm not entirely sure what you are missing, but if you run a query with option resultset = true
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#executeoptions

than you get a resultset object 
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsetclass
and you scroll via rows using getRow/getRows functions and for each row you can read the values/LOBs

**Comment by sanfords** [comment]
Thank you.  So I don't even need to declare a cursor?  I can just use the resultSet with a very large number for maxRows?

**Comment by cjbj** [comment]
@sanfords if you check out https://github.com/oracle/node-oracledb/pull/321 you can see a streaming implementation suggestion from @sagiegurari It would be great to get your feedback on it

**Comment by sanfords** [comment]
I suspect getRows will work well for my needs for the moment.
