### ISSUE TITLE
Does the pool class property connectionsInUse type is Boolean?

### ISSUE THREAD

**Issue by zorrofox** [oracle/node-oracledb#36]
Hi,

   I am just confused, the connectionsInUse is really Boolean? 

![image](https://cloud.githubusercontent.com/assets/1528417/6478523/c4751af2-c26f-11e4-8ace-1a36b7381f3e.png)

**Comment by cjbj** [comment]
No - thanks for picking this up.

**Comment by cjbj** [comment]
This is fixed in the 0.4.1 tag.
