### ISSUE TITLE
Inserting and retrieving a TIMESTAMP(5)

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#360]
What's the best way to insert and retrieve a timestamp(5)?  We're currently handling these as JS Date objects, but their resolution only goes to milliseconds.

**Comment by dmcghan** [comment]
As you say, JavaScript dates only do milliseconds. What are you trying to do? Could you just use strings and conversions?

**Comment by sanfords** [comment]
I'm considering a few options.  One is a Date object with our own "subseconds" key.  I believe when I do a select on timestamp(5) columns that I get them back as a JS Date object.  I'll play around with `fetchAsString`.  I just don't what best practices are for this.

**Comment by dmcghan** [comment]
What are you trying to do?

**Comment by sanfords** [comment]
Sorry.  :-)  I'm trying to insert and select high fidelity timestamps to 1/10000 second resolution.

**Comment by cjbj** [comment]
@sanfords are you manipulating them in Node? How?

**Comment by sanfords** [comment]
We'll be doing all sorts of things with the timestamps:  We'll be offsetting them.  We'll be doing queries with them.  We'll be writing them to files and reading them back.  I'm more interested in maintaining fidelity when we read/write to/from the oracle.

**Comment by cjbj** [comment]
String is likely the best bet.  Are you offsetting them in Node, or just in SQL?

**Comment by sanfords** [comment]
We'll be offsetting in Node.  But doing queries with formats with to_timestamp().  Is `fetchAsString` my best bet?

**Comment by dmcghan** [comment]
@sanfords Have you considered doing your offsetting in the database? Oracle's support for this is pretty amazing. Generally speaking, I'm not a fan of DATE or TIMESTAMP. DATE isn't precise enough and neither has the compete picture. 

My favorite date datatype is TIMESTAMP WITH LOCAL TIME ZONE. With this type, time zones are normalized to the database time zone when the data is stored. Then when retrieved, their converted for you according to the session time zone (which you can set prior to executing your queries).

For the vast majority of folks, this is probably the date/time data type they should be using. Yeah, there are some adjustments to be made with date arithmetic, such as using of intervals, but it's worth it! Also, there may be some rare exceptions where people actually do want to capture the time zone related information. In those cases TIMESTAMP WITH TIME ZONE would be more appropriate but the conversions with that type must be done manually.

`fetchAsString` should work for you. Just don't forget to set the corresponding NLS parameter (NLS_TIMESTAMP_FORMAT, NLS_TIMESTAMP_TZ_FORMAT, etc.). 

```sql
    connection.execute(
      "begin execute immediate q'[alter session set nls_timestamp_format='YYYY-MM-DD HH24.MI.SSXFF']'; end;",
      function(err){
        // other work here
      }
    );
```

There's also `fetchInfo` at the `execute` level and of course you can always do manual conversions in SQL and PL/SQL.

**Comment by sanfords** [comment]
Allowing Oracle to do the heavy lifting will be a win.  And I think fetching these timestamps as a string will be good too.

Thank you both very much for the advice.  It's very appreciated.

**Comment by sanfords** [comment]
We've run into a snag with this.  We use fetchAsString to get our high resolution TIMESTAMP out of the database without any loss.  However, how can we tell which resulting columns are actually TIMESTAMP columns?  We use 'AS' extensively throughout our code and there's no way for us to know which columns are TIMESTAMP columns and which are just masquerading strings.  

We could loop over all results and match against a regex, but that's kind of weird.  And slow, I imagine.

Is there a trick to this?  Say, for a given query, what are the types for each resulting column?

**Comment by sanfords** [comment]
We've run into a snag with this. We use fetchAsString to get our high resolution TIMESTAMP out of the database without any loss. However, how can we tell which resulting columns are actually TIMESTAMP columns? We use 'AS' extensively throughout our code and there's no way for us to know which columns are TIMESTAMP columns and which are just masquerading strings.

We could loop over all results and match against a regex, but that's kind of weird. And slow, I imagine.

Is there a trick to this? Say, for a given query, what are the types for each resulting column?

**Comment by cjbj** [comment]
@sanfords the metadata improvements such as https://github.com/oracle/node-oracledb/pull/386 may help.  This isn't planned for 1.9.1.  Likely to be soon after that.

**Comment by sanfords** [comment]
Ok, I think we'll hack together a quick "Does this result match a regex for a timestamp?" function and then get rid of it when #386 is merged.  :-)  Thank you!
