### ISSUE TITLE
Support for Oracle Advanced Queues

### ISSUE THREAD

**Issue by mrapczynski** [oracle/node-oracledb#362]
Title pretty much sums it up. Being able to access AQ streams as event emitters would be incredible.

**Comment by cjbj** [comment]
Native AQ is something I've been wanting.  Even had some talks with the AQ team, but other priorities arose ...

Pull Requests welcome.

In the meantime AQ can be accessed via PL/SQL

**Comment by volkmarbuehringer** [comment]
put the dequeue into a pl/sql procedure and return a ref-cursor after selecting your data
based on the dequeued stuff

the execution of the dequeuer-procedure can be called with async.forever or a highland
stream and the timeout-error can be ignored in node.js, better than hanging forever in
the queue

and use a dedicated connection for queuing, no pooled connections


procedure dequeuerin( p_recordset out sys_refcursor, queuename in varchar2 default null ) as

dequeue_options dbms_aq.dequeue_options_t;
msg_prop        DBMS_AQ.message_properties_t ;
  message         crm_message_type;
  msgid           raw(16);
transer number;
queuert varchar2( 50 ) := nvl( queuename,'EDV.CRMTRANSPORTIN');

begin
dequeue_options.wait := 60;

 DBMS_AQ.DEQUEUE( 
              queue_name               => queuert,
              dequeue_options          => dequeue_options,
              message_properties => msg_prop,
              payload            => message,
              msgid              => msgid);

 open p_recordset for 
 select y.*
   from edv.lt_dokument y where  y.dok_id = message.id ;

end;

**Comment by dmcghan** [comment]
@volkmarbuehringer 

> and use a dedicated connection for queuing, no pooled connections

Could you elaborate on that point? Both the OCI pool and DRCP use dedicated connections. Is there a problem with either of those?

**Comment by volkmarbuehringer** [comment]
I mean a direct connect without the pool, which is dedicated only to the queue

set action and module in the connection and monitor it in v$session



Am 02.03.2016 um 00:27 schrieb Dan McGhan:

@volkmarbuehringer<https://github.com/volkmarbuehringer>

and use a dedicated connection for queuing, no pooled connections

Could you elaborate on that point? Both the OCI pool and DRCP use dedicated connections. Is there a problem with either of those?

—
Reply to this email directly or view it on GitHub<https://github.com/oracle/node-oracledb/issues/362#issuecomment-190962076>.


Prounix Gesellschaft für Softwareentwicklung mbH - Geschäftsführer: Andreas Decker - Handelsregister: Amtsgericht Bonn HRB 5855 - Sitz der Gesellschaft: Bonn

**Comment by cjbj** [comment]
Support for AQ RAW queues (i.e. Node.js String or Buffer messages) was pushed to https://github.com/oracle/node-oracledb/tree/dev-4.0.  You can install with `npm install oracle/node-oracledb#dev-4.0`, see https://github.com/oracle/node-oracledb/issues/1053.  The [documentation](https://github.com/oracle/node-oracledb/blob/dev-4.0/doc/api.md#aq) is on the branch.

Native support for PL/SQL object messages can't be added until node-oracledb supports binding types.

**Comment by cjbj** [comment]
Node-oracledb 4.0 has been released with the enhancement for AQ. You can pass Strings, Buffers, or objects. Doc is at https://oracle.github.io/node-oracledb/doc/api.html#aq

The release announcement is at https://blogs.oracle.com/opal/oracle-db-named-objects-and-advanced-queuing-support-new-in-node-oracledb-40
