### ISSUE TITLE
question: connectString format

### ISSUE THREAD

**Issue by artemave** [oracle/node-oracledb#366]
Given this connection url - `jdbc:oracle:thin:@(description=(address=(host=HOSTNAME)(protocol=tcp)(port=PORT))(connect_data=(service_name=SERVICENAME)(server=SHARED)))` - can I specify `(description=...)` part directly as `connectString` property in `getConnection`? 

I am trying to avoid having `tnsnames.ora` file, but rather pass the connection from environment variable (connection will include address list, so the simple host/port doesn't cut it).

**Comment by cjbj** [comment]
What did your testing show?

In general yes, you could use 
```
connectString: "(DESCRIPTION=..."
```

Also see https://github.com/oracle/node-oracledb/blob/master/doc/api.md#notjdbc

**Comment by artemave** [comment]
Indeed it does. That was an unrelated problem in my code. Thanks!
