### ISSUE TITLE
Error:  0509-130 Symbol resolution failed for libclntsh.a(shr.o)

### ISSUE THREAD

**Issue by sreenivasulun** [oracle/node-oracledb#367]
Dear Cjbj,

I installed node-oracledb in IBM AIX 6.1 (6100-09)  successfully, 
used python 2.6.8, gcc-4.8.3_1, gcc-c++-4.8.3_1 .

I used node-oracledb library along with kraken.js server , when I start the server, I am getting the following error,

Please provide help
===============================================================

/home/kkb/KKBV71/Deployment/SIT/node/xls-ecomm/node_modules/oracledb/lib/oracledb.js:28
    throw err;
          ^
Error:  0509-130 Symbol resolution failed for /home/kkb/KKBV71/Deployment/SIT/node/oracleclientzip/instantclient/libclntsh.a(shr.o) because:
        0509-136   Symbol CreateIoCompletionPort (number 2977) is not exported from
                   dependent module /unix.
        0509-136   Symbol GetMultipleCompletionStatus (number 2978) is not exported from
                   dependent module /unix.
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/kkb/KKBV71/Deployment/SIT/node/xls-ecomm/node_modules/oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! AIX 1
npm ERR! argv "/home/kkb/ibm/node12/bin/node" "/home/kkb/ibm/node12/bin/npm" "start"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! xls-ecomm@0.1.0 start: `node server.js`

**Comment by sreenivasulun** [comment]
Dear cjbj,

I resolved using the below command,
mkdev -l iocp0

Thank you,
Sreeni

**Comment by NorbertoValverde** [comment]
Sreeni, thank you for this tip. I can resolve the problem.

Norberto.

**Comment by cjbj** [comment]
@NorbertoValverde thanks for commenting.  What is your AIX version and Oracle Client version?

**Comment by kubo** [comment]
I'm not sure but I guess that [this preinstallation task](https://docs.oracle.com/database/121/AXDBI/pre_install.htm#AXDBI8086) is required to install not only Oracle database server but also Oracle instant client.

**Comment by cjbj** [comment]
@kubo thanks for digging that up

**Comment by rookieplayer007** [comment]
I am having Oracle EBS 11.5.9 / 11.5.10
upgraded to AIX 5.3 TL 12

Still having the problem after enabling 

lsdev | grep iocp
iocp0      Available       I/O Completion Ports

what else could be done ?

cat /oraapp/prodcomn/admin/log/PROD_oraapp/adapcctl.txt

adapcctl.sh version 115.43

/oraapp/prodora/iAS/Apache/Apache/bin/apachectl start: httpd started
Syntax error on line 17 of /oraapp/prodora/iAS/Apache/modplsql/cfg/plsql_pls.conf:
Cannot load /oraapp/prodora/iAS/Apache/modplsql/bin/modplsql.so into server:    0509-130 Symbol resolution failed for /oraapp/prodora/iAS/lib/libclntsh.a(shr.o) because:
        0509-136   Symbol pw_post (number 262) is not exported from
                   dependent module /unix.
        0509-136   Symbol pw_wait (number 263) is not exported from
                   dependent module /unix.
        0509-136   Symbol pw_config (number 264) is not exported from
                   dependent module /unix.
        0509-136   Symbol aix_ora_pw_version3_required (number 265) is not exported from
                   dependent module /unix.
        0509-022 Cannot load module /oraapp/prodora/iAS/Apache/modplsql/bin/modplsql.so.
        0509-026 System error: Cannot run a file that does not have a valid format.
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command.
/oraapp/prodora/iAS/Apache/Apache/bin/apachectl start: httpd could not be started

adapcctl.sh: exiting with status 3


adapcctl.sh: exiting with status 3
