### ISSUE TITLE
1.7 define properties breaks api.

### ISSUE THREAD

**Issue by sagiegurari** [oracle/node-oracledb#369]
The latest changes of 1.7 are not good.
You broke simple-oracledb with all these defineProperties because you didn't set them as writable.
functions must be writable so we can swap them.
this is critical issue for me and I hope this doesn't mean I have to wait 1 month for an update on this.
this is a killer to any wrapper libraries and based on what I see on the issues, many write such wrappers internally in their projects.

**Comment by sagiegurari** [comment]
I can do a pull request to fix all these issues but only if you push it quickly.
I can't understand why it was set like that which limits the ability to extend the api. It is very frustrating.

**Comment by dmcghan** [comment]
@sagiegurari, sorry for the frustration! I'll address this on our side. As to how soon we can push that's Chris' call.

**Comment by cjbj** [comment]
@sagiegurari I've pushed a quick 1.7.1 to GitHub.  We'll see if anything else high priority gets reported by early testers, and do some proper release testing, before pushing to npm.

**Comment by sagiegurari** [comment]
Appreciate the quick fix of this.
I tested 1.7.1 and it works good.

**Comment by dmcghan** [comment]
:+1:

**Comment by cjbj** [comment]
I've pushed 1.7.1 to npm

**Comment by sagiegurari** [comment]
1.7.1 from npm works good. thanks a lot.
