### ISSUE TITLE
Issue installing oracledb driver in RedHat 6.6 with NodeJS 5.7.0

### ISSUE THREAD

**Issue by juveguevara** [oracle/node-oracledb#370]
Hello,

We used to be working with NodeJS 0.10.x and oracledb driver without issues in RedHat v6.6. Today we had upgraded NodeJS to v5.7.0 and by the time is compiling node-gyp the process fails:

417 error node v5.7.0
418 error npm  v3.7.5
419 error code ELIFECYCLE
420 error oracledb@1.7.1 install: `node-gyp rebuild`
420 error Exit status 1
421 error Failed at the oracledb@1.7.1 install script 'node-gyp rebuild'.
421 error Make sure you have the latest version of node.js and npm installed.
421 error If you do, this is most likely a problem with the oracledb package,
421 error not with npm itself.
421 error Tell the author that this fails on your system:
421 error     node-gyp rebuild
421 error You can get information on how to open an issue for this project with:
421 error     npm bugs oracledb
421 error Or if that isn't available, you can get their info via:
421 error     npm owner ls oracledb
421 error There is likely additional logging output above.
422 verbose exit [ 1, true ]

Attached you can find log file for your reference, 
[oracledb-npm-debug.zip](https://github.com/oracle/node-oracledb/files/155496/oracledb-npm-debug.zip)
Could you please help and provide your inputs. Thank you very much

**Comment by dmcghan** [comment]
Did you install the instant client via RPMs or zip files? If zip files, you'll need to set some environment variables during install (from the install instructions):

```
export OCI_LIB_DIR=/opt/oracle/instantclient_12_1
export OCI_INC_DIR=/opt/oracle/instantclient_12_1/sdk/include
``` 

Can you check that?

**Comment by juveguevara** [comment]
it was via RPMs, we also tried re-installing both clients again - re-ran rpm -ivh on both of them. still having the same error

**Comment by cjbj** [comment]
@juveguevara Were there errors earlier in the output?  Building add-ons for Node 4 & 5 needs a C++11 compatible compiler.  The default compiler on RHEL6 is not C++11 compatible. 

Try installing with `npm --verbose install oracledb` and check the compiler messages.

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#prerequisites "When building with Node 4 onwards, the compiler must support C++11. Note the default compiler on Oracle Linux 6 and RHEL 6 does not have the required support. Install a newer compiler or upgrade to Oracle Linux 7."

**Comment by juveguevara** [comment]
i got now, it makes sense, our gcc is 4.4.7-11. Is there a NodeJS version in between, newer than 0.10.x but less than 4 that is compatible with oracledb driver and gcc 4.4.7-11? Thanks a lot for all your help @cjbj and @dmcghan

**Comment by sagiegurari** [comment]
You have 0.12 but any reason why not just upgrade the compiler? I use centos 6.5 or 6.6 which is basically like redhat and with upgraded compiler I am able to work with node4

**Comment by cjbj** [comment]
The Software Collections library is just one of the places you can get a newer compiler.  RHEL have such a collection. Oracle's SCL channel for OL6 is free at http://yum.oracle.com/oracle-linux-6.html 
User doc is at https://docs.oracle.com/cd/E52668_01/E59096/html/index.html

**Comment by rknell** [comment]
For anyone else coming across this and trying to install on RHEL6 this is what worked for me:

> You also need to have an up-to-date version of devtools installed
>  [http://unix.stackexchange.com/questions/125609/install-latest-gcc-on-rhel-6-x86-64](http://unix.stackexchange.com/questions/125609/install-latest-gcc-on-rhel-6-x86-64)
>  
>  Worked for me. This will need to be done before installing the app for the first time otherwise 
> there will be build errors.
>  
>  I also needed to set the GCC compiler env manually using this command
>  `env CC=/opt/rh/devtoolset-2/root/usr/bin/gcc CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ npm install oracledb`

Thats taken from our own private documentation
