### ISSUE TITLE
client installation document errors

### ISSUE THREAD

**Issue by serkanberksoy** [oracle/node-oracledb#372]
Hi,

There are two errors on client installation document;
1) After exporting zip, you are renaming them to clientinstaller after that you are using export commands like below. They should not have _12_1 at the end of the folder name.
export OCI_LIB_DIR=/opt/oracle/instantclient_12_1
export OCI_INC_DIR=/opt/oracle/instantclient_12_1/sdk/include

2) There is a problem with INC_DIR variable. If you set it to /sdk/include installation can't find libclntsh.so
If you set it to clientinstaller folder then installation can't find oci.h.
I had to copy all .h files to clientinstaller.
I guess the link command here;
ln -s libclntsh.so.12.1 libclntsh.so
should be executed in /sdk/include having link to 2 folders above the tree.

Cheers

**Comment by cjbj** [comment]
1 - This was deliberate but could be improved.  A subsequent sentence says "If Instant Client is in /opt/oracle/instantclient and you have no other Oracle software installed, then these variables are not required" So the example is technically correct. It shows what to set if you haven't done the rename.  

2 - Retest and give us more background context if there is a problem.  Your hack sounds weird. Are you sure you set both OCI_LIB_DIR and OCI_INC_DIR?

**Comment by serkanberksoy** [comment]
I sure did. If I hadn't it gives another error. I am on a deadline and I was trying frantically to figure out what to do at the time and tried many things. :) To be sure I need to setup another environment and recreate the same problem.

**Comment by cristtopher** [comment]
hi, i have the same issue.
When i run:
`npm install oracledb --save`

node-oracledb ERR! Error: Cannot find $OCI_LIB_DIR/libclntsh.dylib
node-oracledb ERR! Error: Do you need to run 'cd $OCI_LIB_DIR && ln -s libclntsh.dylib.* libclntsh.dylib'?
node-oracledb ERR! Error: See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

but:

`ls $OCI_LIB_DIR`
libclntsh.dylib		libclntsh.dylib.11.1	libnnz11.dylib		libociei.dylib		npm-debug.log

Best Regard.

**Comment by cjbj** [comment]
@cristtopher not enough info was given.  Which bits of the install instructions did you follow?

All I can really say is "it works for me"

```
cjones@mac:/tmp$ export OCI_LIB_DIR=$HOME/instantclient
cjones@mac:/tmp$ export OCI_INC_DIR=$HOME/instantclient/sdk/include
cjones@mac:/tmp$ npm install oracledb --save

> oracledb@1.7.1 install /private/tmp/node_modules/oracledb
> node-gyp rebuild

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsResultSet.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsIntLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiCommon.o
  SOLINK_MODULE(target) Release/oracledb.node
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/package.json'
/private/tmp
`-- oracledb@1.7.1 
  `-- nan@2.1.0 

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
cjones@mac:/tmp$ node --version
v5.8.0
cjones@mac:/tmp$ ls node_modules/oracledb/
CHANGELOG.md	LICENSE.md	README.md	binding.gyp	build		index.js	lib		package.json	src		test
cjones@mac:/tmp$ ```

**Comment by cjbj** [comment]
In 1.8 I changed the lines you reported point 1.  
Is there still an issue with point 2?

**Comment by cjbj** [comment]
Closing due to lack of feedback.
