### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by yxgang** [oracle/node-oracledb#373]
node-oracledb ERR! Error: Cannot find Oracle library libclntsh.so
node-oracledb ERR! Error: See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

gyp: Call to 'INSTURL="https://github.com/oracle/node-oracledb/blob/master/INSTALL.md"; ERR="node-oracledb ERR! Error:"; if [ -z $OCI_LIB_DIR ]; then OCI_LIB_DIR=`ls -d /usr/lib/oracle/*/client*/lib/libclntsh.* 2> /dev/null | tail -1 | sed -e 's#/libclntsh[^/]*##'`; if [ -z $OCI_LIB_DIR ]; then if [ -z "$ORACLE_HOME" ]; then if [ -f /opt/oracle/instantclient/libclntsh.so ]; then echo "/opt/oracle/instantclient/"; else echo "$ERR Cannot find Oracle library libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; else if [ -f "$ORACLE_HOME/lib/libclntsh.so" ]; then echo $ORACLE_HOME/lib; else echo "$ERR Cannot find \$ORACLE_HOME/lib/libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi; else if [ -f "$OCI_LIB_DIR/libclntsh.so" ]; then echo $OCI_LIB_DIR; else echo "$ERR Cannot find \$OCI_LIB_DIR/libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi; else if [ -f "$OCI_LIB_DIR/libclntsh.so" ]; then echo $OCI_LIB_DIR; else echo "$ERR Cannot find \$OCI_LIB_DIR/libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi;' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-123.9.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hana/node_modules/oracledb
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

[root@iZ285kjayftZ hana]# echo $LD_LIBRARY_PATH
/usr/lib/oracle

[root@iZ285kjayftZ oracle]# ls /usr/lib/oracle/ -lh
total 79M
-rwxrwxr-x 1 root root  25K Aug 25  2013 adrci
-rw-rw-r-- 1 root root  449 Aug 25  2013 BASIC_LITE_README
-rwxrwxr-x 1 root root  47K Aug 25  2013 genezi
-r-xr-xr-x 1 root root  368 Aug 25  2013 glogin.sql
lrwxrwxrwx 1 root root   17 Mar  7 18:33 libclntsh.so -> libclntsh.so.11.1
-rwxrwxr-x 1 root root  52M Aug 25  2013 libclntsh.so.11.1
-r-xr-xr-x 1 root root 7.7M Aug 25  2013 libnnz11.so
lrwxrwxrwx 1 root root   11 Mar  7 18:33 libnnz.so -> libnnz11.so
lrwxrwxrwx 1 root root   15 Mar  7 18:33 libocci.so -> libocci.so.11.1
-rwxrwxr-x 1 root root 1.9M Aug 25  2013 libocci.so.11.1
-rwxrwxr-x 1 root root 9.5M Aug 25  2013 libociicus.so
-r-xr-xr-x 1 root root 162K Aug 25  2013 libocijdbc11.so
-r-xr-xr-x 1 root root 1.5M Aug 25  2013 libsqlplusic.so
-r-xr-xr-x 1 root root 1.5M Aug 25  2013 libsqlplus.so
drwxr-xr-x 3 root root 4.0K Mar  7 18:21 network
-r--r--r-- 1 root root 2.0M Aug 25  2013 ojdbc5.jar
-r--r--r-- 1 root root 2.7M Aug 25  2013 ojdbc6.jar
drwxrwxr-x 4 root root 4.0K Aug 25  2013 sdk
-r-xr-xr-x 1 root root 9.2K Aug 25  2013 sqlplus
-rw-rw-r-- 1 root root  443 Aug 25  2013 SQLPLUS_README
-rwxrwxr-x 1 root root 188K Aug 25  2013 uidrvci
-rw-rw-r-- 1 root root  66K Aug 25  2013 xstreams.jar

**Comment by cjbj** [comment]
The unanswered question is: what instructions did you follow.  Did you set OCI_LIB_DIR and OCI_INC_DIR?

**Comment by cjbj** [comment]
I guess that was a 'no'.

**Comment by tomdavidson** [comment]
Same problem here, following the [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md):

> If Instant Client is in /opt/oracle/instantclient and you have no other Oracle software installed, then these variables are not actually required. 

but when I do set the two env vars i end up with 
`node-oracledb ERR! Error: Cannot find $OCI_LIB_DIR/libclntsh.so   `
rather than 
`node-oracledb ERR! Error: Cannot find Oracle library libclntsh.so   `

**Comment by cjbj** [comment]
@tomdavidson (1) this issue is closed, so can you start a new one? (2) include all the steps you followed  - sorry I'm not able to guess what is wrong (3) details like which platform you are on are always helpful
