### ISSUE TITLE
oracledb silently fails on require

### ISSUE THREAD

**Issue by lebolo** [oracle/node-oracledb#374]
I recently updated to node v5.7.1 (and npm v3.8.0) and now node crashes silently on `var oracle = require("oracledb");`

I can track it to `oracledb.js` line 188: `oracledbInst = new oracledbCLib.Oracledb;`

But I can't get a stack trace or anything else. Node just quits. It was working before on node v5.1.0.

If it helps, the same happens with the strong-oracle package.

**Comment by FreakinaBox** [comment]
this looks the same as the issue i raised a few days ago #371

**Comment by lebolo** [comment]
Yeah, seems like it. Sorry, forgot to say that I'm on Windows 7!

**Comment by cjbj** [comment]
@lebolo you need to reinstall node-oracledb when you upgrade.  And make sure PATH has the right Oracle libraries.  I'm closing this just like the strong-oracle issue is closed.
