### ISSUE TITLE
Number  is automatically formatted

### ISSUE THREAD

**Issue by mailto-kkk** [oracle/node-oracledb#375]
Hi,

I am using oracle driver 1.3.0 to communicate from Node js. We have one procedure which will return the number as an output.

When we print this output in node js, the decimal point is automatically converted to comma operator(,)But when we test this procedure in DB itself, it is printing with dot operator.

I am not setting any locale settings in my node js application. I want the same output as same as Oracle DB.

If you have any suggestions, please advice.

**Comment by cjbj** [comment]
Are you fetching it as a string?  Some sample code would have helped me. If Oracle is doing the conversion it is likely the territory component of `NLS_LANG`having an effect. You will likely need to do `export NLS_NUMERIC_CHARACTERS=",."` 

Also, I suggest keeping up to date with current node-oracledb versions.
