### ISSUE TITLE
inserting multiple clobs into one row

### ISSUE THREAD

**Issue by bgora** [oracle/node-oracledb#376]
Hi,

Lets say I need to insert multiple rows into a table each containing 3 clobs.

create table my_table(id number, clob1 clob, clob2 clob, clob3 clob);

I have now something similar to:

```javascript
function read_insert() {
oracledb.getConnection( 
{ user,pw,connectstring }, function(err,conn) {
var files_arr = ['file1','file2','file3','file4','file5'];
async.each(files_arr,function(file,callback) {
 fs.readFile(file,'utf8', function(err,data) {
   var obj = {};
   obj.clob1 = data;
   obj.clob2 = modify2(data);
   obj.clob3 = modify3(data);
   ora_insert_data(obj,conn,callback);
 }
 }, function(err) {
      // final callback commit here 
    }
});
});
}

function ora_insert_data(obj,conn,cb) {
 async.waterfall([
  function(callback) {
     conn.execute( 
       // do initial insert with obj.clob1 here, generate a sequence and pass it to a next callback on 'finish' event
      );
  },
  function(seq,callback) {
     conn.execute(
       // update with obj.clob2 where id = seq 
       // call a callback with a seq on a 'finish' event
     );
  },
  function(seq,callback) {
     conn.execute(
       // update with obj.clob3 where id = seq
       // call a final callback on a 'finish' event
     );  
  }], function(err,result) {
      // final callback in waterfall
      cb(null);
  }
 );
}
```

with async.each I loop through files, reading a file and createing 2 modified copies of it, so I have  3 clobs to insert. I pass all 3 clobs as an object (obj) to ora_insert_data function.
ora_insert_data uses async.waterfall. First function in waterfall inserts the first clob generating a sequence number which is passed to the second function which updates the table with the second clob where id = sequence number from the previous finction etc.

It works but sometimes I end up with a corrupted clob. It looks the like 

<"H�FO���H��E��������H<"H�^OH�H<"H�^I��I;���H�H<"H�FO���H���Ѓ���O�������H<"H�VOH�H<"H�VO����H����2�����H<"H�FOH��(����H�H<"H�FoH�� ���I�X;"I;���H�]������8>"ARRH�H<"H�8>"�I�]��H�����H�H<"H�������I��"L9S���H�SI;U���L�R�A�z�uH�RI��>"ARPRH��"H�w/�WH�����H��M�UL9R�u)�����qH��$�H�����I;U�u3���I;U�u ����I;U���3����M�UL9Q�����W�*�.��������M�UL9Q�����W�*�.��������M�UL9Q�����W�*�.��k�e���M�UL9P�u)���H��qH��$�H�������I;E�u3����I;E�u ����I;E��3����M�UL9R�����W�*�.��������M�UL9P�����W�*�.�����������fP��������M�UL9V�u)���qH��$�H�������I;u�u3����I;u�u ����I;u��>3����M�UL9W��.��W�*�.������M�UL9V����W�*�.��������M�UL9W�����W�*�.��������M�UL9R�����W�*�.��������M�UL9P��v��W�*�.��\�V���M�UL9P�u)���H��qH��$�H�������I;E�

it seems like it happens randomly. Sometimes everything is fine, sometimes it happens with one file sometimes with the other. I rewieved the files and they are fine.

So Im just confused if the whole process as I wrote it is right or could it be a bug in oracle driver ?

**Comment by cjbj** [comment]
It could be anything.  Can you give us a runnable testcase (and include the CREATE TABLE command)?

**Comment by dmcghan** [comment]
I'd recommend swapping out your async.each for async.eachSeries. Since you're only using a single connection this should help ensure that you finish with one file before moving to the next.

**Comment by bgora** [comment]
sorry for a delay.

At the same day as I posted I replaced async.each with async.eachLimit and the limit is 2 and now it works just fine. But still confused why it happended. Another strange issue was that sometimes clob3 was inserted into clob1 column (as i used async.each). 

Anyway I will prepare the testcase with all the informations. 

Thanks for your replies

**Comment by dmcghan** [comment]
My advice would be to use eachSeries. Basically a connection should be doing one thing at a time. I'd venture a guess that if you compare the time between async.eachSeries and async.eachLimit (with 2), you'll find that they finish at about the same time (and without any strange issues). This is because a connection can't do anything more than one thing at a time, even if you ask it to.

If you want to speed this up some you'd have to use multiple connections. Just keep in mind that each connection would get it's own session to the database, so the work couldn't be done as a single transaction.

**Comment by cjbj** [comment]
@bgora did you find a runnable testcase for us?  I would like to check into how we can improve.

**Comment by bgora** [comment]
sorry, have a tight schedule right now. Could not prepare the test case. 
I'll do it this week for sure

**Comment by sagiegurari** [comment]
seems working fine to me
https://github.com/sagiegurari/simple-oracledb/blob/a3a13c9731e593cc0b76a4165a498b219f2b1590/test/spec/integration-spec.js#L585-L617

**Comment by cjbj** [comment]
Closing.  Let us know if you find a testcase.
