### ISSUE TITLE
TypeError: oracledb.getConnection is not a function

### ISSUE THREAD

**Issue by rushtoner** [oracle/node-oracledb#377]
I'm on a Mac (OS X 10.11.3 El Capitan) and trying to get this driver working.
I have v 11_2 of the instant client and sdk installed and have built oracledb.node.

When I try to run select1.js from the examples I get "TypeError: oracledb.getConnection is not a function".

node david$ ls node_modules
oracledb.node
node david$ node -v
v4.3.1
node david$ node select1.js 
/Users/david/w/node/select1.js:36
oracledb.getConnection(
         ^

TypeError: oracledb.getConnection is not a function
    at Object.<anonymous> (/Users/david/w/node/select1.js:36:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

What am I doing wrong?

**Comment by cjbj** [comment]
That's the oracledb.js class not extending or the C library not being able to be loaded.
- Cleanup any node_modules directories where an old oracledb might be installed and found by node
- Follow https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx  
- I don't recommend running install in the source dir, if you have cloned the repo
- For dev testing, I tend to clean the cache (and delete the config dirs just in case the clean doesn't work!):
 ` \rm -rf ./node_modules/oracledb ./node_modules/nan $HOME/.node-gyp $HOME/.npm && npm cache clean && npm install oracledb`

**Comment by cjbj** [comment]
@rushtoner What's the status on this?

**Comment by cjbj** [comment]
Closing due to lack of feedback.
