### ISSUE TITLE
"parallel" connections to DB

### ISSUE THREAD

**Issue by vlavorini** [oracle/node-oracledb#379]
Hello,

    I'm using the async module (1.5.2) on nodejs.
I have set up two functions for writing in two different tables in the same DB.
If I use the "series" control flow everything goes as expected, while if I use the "parallel" Oracle replies with a (misleading) error: ORA-01036: illegal variable name/number .
What's happening?
Thank you

**Comment by dmcghan** [comment]
Can you please supply a test case so we can reproduce? Generally speaking, a connection can only do one thing at a time. If you want to do these things in parallel you'll need multiple connections. 

I've noticed that sometimes the connection objects themselves may act as a serialization device. So if we did a `connection.execute` followed immediately by another (not in the callback for the first), the connection would do one execute operation and then the other when the first is finished. That's why I'm a little surprised by your findings. A test case would be helpful in tracking down the issue (if there really is one).

**Comment by vlavorini** [comment]
Sure, this is the code. This should call two different connections, is it true?


`
var registerMainTable= function (ID_ls, ID_se, ID_n, ID_n2, req, callback)
{ ....
       registerSQL(sql_string, sql_object, function(err, result){ ...}
}

var registerVisualAffections= function (ID_ls, ID_se, ID_n, ID_n2, affections, callback)
{....
      registerSQL(sql_string, sql_object, function(err, result){ ...}
}

var registerSQL = function (sql_query, sql_object, callback) {
    oracledb.getConnection(
        {
            user          : dbConfig.user,
            password      : dbConfig.password,
            connectString : dbConfig.connectString
        },
        function(err, connection)
        {
            if (err) {...}
            connection.execute(sql_string,sql_object,
                               {autoCommit: true},
                               function(err, result)
                               {
                                   if (err) {...}
                                   else {
                                       doRelease(connection);
                                       return callback(null, result);
                                   }
                               });
        });
}

         

data2SQL.push(function(callback){
        registerVisualAffections( ID_ls, ID_se, ID_n, ID_n2, req.body.all_visual_affections, function(error, result){
                if (error){ ...}
                return callback(null, result);
                })
        }); 
data2SQL.push(function(callback){
        registerMainTable(ID_ls, ID_se, ID_n, ID_n2, req, function(error, result){
                if (error){...}
                return callback(null, result);
                });
        });
async.series(data2SQL, function(errAsync, result){
        if (errAsync){...}   
        callbackTot(null, result);
        });
`

**Comment by dmcghan** [comment]
I don't think you need 2 different connections. If it's 1 transaction that you want to succeed or fail as a single unit of work, then you use 1 connection. The key is to do one thing at a time with the connection. 

With "series", you're ensuring that the work done with one element in the array is complete before moving on to the next. 

Now, if each element in the array can be a separate transaction and you want more speed, that's where multiple connections come into play and perhaps more importantly, connection pools, which will reduce the overhead associated with opening and closing connections.

**Comment by vlavorini** [comment]
Ok, thank you. I'll turn to connection pools then.

Ad maiora
