### ISSUE TITLE
Installation on OSX

### ISSUE THREAD

**Issue by XiaolanLin** [oracle/node-oracledb#38]
I got this error after I reinstall my node to v0.10 and also set the paths.
/src/dpi/include/dpiStmt.h:29:11: fatal error: 'oci.h' file not found
# include <oci.h>
          ^
1 error generated.
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/oracledb
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok 
npm ERR! oracledb@0.3.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the oracledb@0.3.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/xiaolanlin/Documents/node-oracledb
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xiaolanlin/Documents/node-oracledb/npm-debug.log
npm ERR! not ok code 0

**Comment by kathan** [comment]
@XiaolanLin Did you set OCI_LIB_DIR and OCI_INC_DIR in your environment?
Where is your Oracle instant client installed?

**Comment by XiaolanLin** [comment]
Yes I set them in the bash_profile and double checked. they are both correct. 

I got this message 
> oracledb@0.3.1 install /usr/local/lib/node_modules/oracledb
> node-gyp rebuild

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/njs/src/njsOracle.cpp:28:
In file included from ../src/njs/src/njsOracle.h:36:
In file included from ../src/dpi/include/dpi.h:35:
In file included from ../src/dpi/include/dpiEnv.h:36:
In file included from ../src/dpi/include/dpiPool.h:33:
In file included from ../src/dpi/include/dpiConn.h:29:
../src/dpi/include/dpiStmt.h:29:11: fatal error: 'oci.h' file not found
# include <oci.h>
          ^
1 error generated.
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 14.0.0

**Comment by kathan** [comment]
I see that you're installing globally. If you're using sudo to do that, remember the -E option that transfers your environment variables to the sudo environment.

**Comment by XiaolanLin** [comment]
@kathan 
Cool!
Finally resolved!

**Comment by cjbj** [comment]
@kathan nice pick up.
