### ISSUE TITLE
Build with VC++

### ISSUE THREAD

**Issue by dominhhai** [oracle/node-oracledb#380]
Can I build with [VC++](https://www.microsoft.com/en-us/download/details.aspx?id=49983) instead of normal VC? Installing VC is really hard work!

**Comment by cjbj** [comment]
@dominhhai did you try? Also have you seen #18?

**Comment by dominhhai** [comment]
I tried to build with Node v5 and VC++, but it did not work.

**Comment by cjbj** [comment]
What didn't work?

**Comment by cjbj** [comment]
@dominhhai did you see https://github.com/nodejs/node/pull/5627 ?

**Comment by dominhhai** [comment]
@cjbj thank for your mention. I will take time to test again when can take time.
Sorry for my late.
After installing with VC++ (fail), I removed VC++ and do not have much time to check again.
Btw, my env: Windows Server 2008 - 64bit.

**Comment by cjbj** [comment]
@dominhhai I'll close this until you can revisit it.
