### ISSUE TITLE
the length of the result is limit?

### ISSUE THREAD

**Issue by cai520senlin** [oracle/node-oracledb#381]
I found that the maximum length of the result is 100, how to modify the maximum length?

**Comment by cjbj** [comment]
Read the manual:  https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbmaxrows
Or use a ResultSet (recommended):  https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsethandling
Or wait for https://github.com/oracle/node-oracledb/pull/321 to be merged.
