### ISSUE TITLE
 The specified procedure could not be found

### ISSUE THREAD

**Issue by raymondzb** [oracle/node-oracledb#382]
I know others have posted about this issue, and I've viewed the answers to these posts, but still not able to get around this.  Here's what happens when I try to run select1.js from the examples directory:

$ node select1.js
C:\wamp\www\nodetests\node_modules\oracledb\lib\oracledb.js:32
    throw err;
    ^

Error: The specified procedure could not be found.
\\?\C:\wamp\www\nodetests\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp\www\nodetests\node_modules\oracledb\lib\oracl                                                                                                                edb.js:27:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Here is what my system PATH variable looks like:

C:\oracle\instantclient;C:\Python27\;C:\Python27\Scripts;C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\HP SimplePass\x64;C:\Program Files (x86)\HP SimplePass\;C:\Program Files (x86)\Intel\iCLS Client\;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\nodejs\;C:\apache-maven-3.3.9-bin.tar\apache- -3.3.9\bin;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\oracle\instantclient;C:\Users\raymond\.dnx\bin;C:\Users\raymond\AppData\Roaming\npm;C:\apache-maven-3.3.9-bin.tar\apache-maven-3.3.9\bin;C:\Program Files\nodejs;

And here are the values of my OCI_ system variables:

OCI_INC_DIR = C:\oracle\instantclient\sdk\include
OCI_LIB_DIR = C:\oracle\instantclient\sdk\lib\msvc

I am running a local instance of Oracle 11g express edition.  I think I read somewhere that if I am running a local db, the values of the OCI_* system variables actually need to point to the oci/ directory of the local oracle installation, but I am not sure if this is causing my problem.

Any help would be greatly appreciated.

**Comment by cjbj** [comment]
You could be on the right track. You are building with Instant Client but using oracle XE libraries at runtime because they occur first in PATH.  What version of Instant Client do you have?

Try installing with OCI_*_DIR set to the XE ORACLE_HOME directories - see midway through https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#64-install-the-add-on
Or change your PATH before you run Node.

**Comment by raymondzb** [comment]
Hi Chris,

My version of Instant Client is 12.1.0.2.0 (x64).   

In the meantime, I have gone ahead and reset my OCI_*_DIR system variables to the xe oracle_home directories as follows:

OCI_INC_DIR = C:\oraclexe\app\oracle\product\11.2.0\server\oci\include
OCI_LIB_DIR =  C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC

Unfortunately, I am still getting the same exact error as before - being thrown by the same file and line number.

The error is being thrown by this part of lib/oracledb.js:

try {
  oracledbCLib =  require('../build/Release/oracledb');
} catch (err) {
  if (err.code === 'MODULE_NOT_FOUND') {
    oracledbCLib = require('../build/Debug/oracledb');
  } else {
    throw err;
  }
}

**Comment by raymondzb** [comment]
@cjbj 

Hi Chris, was wondering if you have any more thoughts on this...

**Comment by cjbj** [comment]
@raymondzb I'm not a Windows user.  It still sounds like a clash of libraries.  You don't say how you are installing.

**Comment by cjbj** [comment]
Closing due to lack of feedback.
