### ISSUE TITLE
connection.execute is not a function

### ISSUE THREAD

**Issue by Aethyn** [oracle/node-oracledb#384]
Hi guys,  
Currently I'm trying to make a REST app with node js, express, and OracleDB.
I want to create an object named "user" from the session. A user is made like that :
```

// at the first connection : 
app.get('/', function(req, res){
    user = req.session;
    // Retrieve an Oracle connection object as a promise
    oracleDB.getConnection().then(function(promise) {
        user.connection = promise;
        res.end('done');
    }).catch(function(promise) {
        console.log('Rejected promise : ' + promise);
    });
});
```
  
Then, on any page (for example : /search) : 
  
```
app.get('/search', function(req, res) {
    user.connection.execute(query, [params] {
        // Process resultSet
    });
    res.end(result);
};
```

Unfortunately, I have a "execute is not a function" error. But if I log my connection Object (with console.log(user.connection) for example), the connection object seems to be perfectly good...
He's shows me an object containing oracleServerVersion, action, module, clientId, stmtCacheSize, etc...  

Can anyone help me please?

**Comment by dmcghan** [comment]
Hi Aethyn,

The driver currently doesn't support promises, though support is planned for a future release. Note that even when promise support is added, your `then` and `catch` functions will not receive a promise, they will receive the connection or error respectively (I see your using them correctly, but the parameter names are misleading). 

The next issue is that you're not passing getConnection any parameters. You'll likely need to pass the user, password, and connectString that you want to use to connect to the database: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionhandling

Also, because your building a web server, I highly recommend using a connection pool over getting your connections from the base class - this will result in much better performance and scalability: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connpooling

I hope that helps. If you have more questions, please provide a test case that we can use to reproduce what you're doing and the errors you're seeing. It doesn't have to be your actual code, just enough to get us on the same page.

**Comment by Aethyn** [comment]
Hi, and thanks for the answer :)
Actually I forgot to post the other part of my getConnection() code... Sorry for the inconvenience.

I made a connection object like this :  
Connection.js  
```
// Requires
var oracledb = require('oracledb');
var dbConfig = require('./dbconfig');
var Promise = require('promise');
// Constructor
Connection = function() {
};
// Method getConnection()
Connection.prototype.getConnection = function() {
    // getConnection return a promise
    return new Promise(function(resolve, reject) {
        // Promise is resolve or reject here
        console.log("I get my connection");
        oracledb.getConnection(dbConfig, function(err, connection){
            if(err) {
                throw err;
            }
            // If resolve
            console.log("Connection resolved");
            resolve(connection);
        });
    });
};
// Exports
module.exports = Connection;
```

Si I really give the dbConfig (which is a classical TNS user/password/connectString) to my getConnection. And then I call the prototype.getConnection on my app with :  
```
    userConnexion.getConnection().then(function(promise) {
        user.connexion = promise;
        monUserManager.addUser(user);
        res.end('done');
    }).catch(function(promise) {
        console.log('Promise rejetée : ' + promise);
    });
```
I did that because of the asynchronous nature of javascript. I need to create an user from a session, then link a unique connection to this user (one connection per user), so I must instanciate my connection everytime a user connect. Then I need to execute some queries (typically CRUD) and it's here that it told me "execute isn't a function" despite my object is "trustable" (I log it in the console and it seems good).  
But yeah, I agreed with you, it doesn't return a promise but a connection or an error. My naming is misleading, you're right.  
Currently I'm making a "beta version" but the release will use pool instead of "classical" connection. But I'm pretty newbie with nodejs/express, so I implement things step by step.  
(PS : I apologize about my english, as you probably see, it's not my main language).

**Comment by sagiegurari** [comment]
1. you keep a connection per user. many users, many connections. that is not good design.
connections should be shared via pool to minimize load on network/memory/database and so on...

2. if a user connection gets corrupted/stale, than the user has to logout and login to continue to work. again the solution is a pool and to get a connection at the start of the service and release it at the end.

**Comment by dmcghan** [comment]
I see... 

My advice, if doing things step by step, would be to NOT create your own connection wrapper. That took you in the wrong direction anyway (as you really needed a pool wrapper).

Just use the core driver, no wrapper (and thus no promises), and go straight to a connection pool. Get that working and then add sugar (wrappers, promises, etc.) if you want.

**Comment by Aethyn** [comment]
Thank you guys, you help me a lot, and your arguments are convincing !
So the connection wrapper is definitely not a good choice...
I will use a connection pool, then maybe wrap and using promises instead of callbacks if it is needed.
I close this issue, thanks again ;)

PS : @dmcghan, I found your pool wrapper module on JSAO.io, I will certainly try something like that. Good job for this ! It's pretty nice.

**Comment by cjbj** [comment]
@Aethyn I must have missed seeing you close this.  Node-oracle 1.7.1 has an inbuilt pool wrapper.  It was derived from the OraWrap on on @dmcghan had on jsao.io. And check out the 1.9.0 Development branch which has native promise support: https://github.com/oracle/node-oracledb/issues/410#issuecomment-211724112
