### ISSUE TITLE
Question: How can I log or trace the querys that driver does? Some connection option?

### ISSUE THREAD

**Issue by javiercornejo** [oracle/node-oracledb#385]
Thanks Oracle team

**Comment by cjbj** [comment]
The db has a lot of tracing functionality, including in enterprise manager.  There is nothing built into the node-oracledb.

**Comment by cjbj** [comment]
Bit hasty there.  
To make best use of server side tracing, see https://github.com/oracle/node-oracledb/blob/master/doc/api.md#endtoend
