### ISSUE TITLE
Change Instant Client location

### ISSUE THREAD

**Issue by dominhhai** [oracle/node-oracledb#389]
I moved the Instant Client from `C:/Oracle/instantclient` to `E:/Oracle/instantclient` and change the `Path` with new location. Then I can not connect to the DB.
Do you have the same experience?

**Comment by bchr02** [comment]
Just add the following directly to your app:
```javascript
process.env['ORACLE_HOME'] = path.join('E:/Oracle/instantclient');
process.env['OCI_LIB_DIR'] = path.join(process.env.ORACLE_HOME, '/sdk/lib/msvc');
process.env['OCI_INC_DIR'] = path.join(process.env.ORACLE_HOME, '/sdk/sdk/include');
process.env['PATH'] = process.env.ORACLE_HOME + ';' + process.env['PATH'];
```

**Comment by dominhhai** [comment]
@bchr02 Can you tell me why we have to add `PATH` directly in the app?
I think that it is not difference from using Windows's system env.
Btw, Do we need the `OCI_LIB_DIR ` and `OCI_INC_DIR `?
In the [installation docs](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin) says that
> Tell the installer where to locate the Oracle client libraries and header files by setting the `OCI_LIB_DIR` and `OCI_INC_DIR` variables. These variables are only needed during installation, not at run time. Do not add them to `PATH`.

**Comment by cjbj** [comment]
@bchr02 `OCI_*_DIR` are only used during installation.  There is very, very rarely the need to set `ORACLE_HOME` when using Instant Client.

@dominhhai what errors are you getting?

**Comment by dominhhai** [comment]
@cjbj Sorry, I am late. I started successfully. I have to restart the `cmd` for getting the new `Path` because of it was changed after changing InstantClient location.
Btw, I use `ORACLE_HOME` for `tnsname.ora` config file.
@bchr02 I  do not need `OCI_*_DIR` to run app.

**Comment by cjbj** [comment]
@dominhhai thanks for letting us know.
