### ISSUE TITLE
path conflict with old node-oracle

### ISSUE THREAD

**Issue by danschumann** [oracle/node-oracledb#39]
`OCI_LIB_DIR` apparently is required by both modules except is supposed to be set differently.  Any chance to have it smartly detect if this variable is set one level deeper ( the node-oracle way ) ?  During any transition period it would make things easier

**Comment by kathan** [comment]
@danschumann Can you give a more specific example of what you're trying to accomplish?

**Comment by vizjerai** [comment]
```node-oracle``` for windows needs ```OCI_LIB_DIR``` to be set to ```C:\instantclient_12_1\sdk\lib\msvc\vc11``` for Visual Studio 2012
```node-oracledb``` for windows needs ```OCI_LIB_DIR``` to be set to ```C:\instantclient_12_1\sdk\lib\msvc```

[node-oracle/install.md](https://github.com/joeferner/node-oracle/blob/master/INSTALL.md)
[node-oracledb/install.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#65-install-the-driver)

**Comment by cjbj** [comment]
The path is different because node-oracle needs Oracle C++ libraries, whereas node-oracledb uses C libraries which are not as version specific.
