### ISSUE TITLE
Unable to Install in Windows

### ISSUE THREAD

**Issue by arindam-chattopadhya** [oracle/node-oracledb#391]
[npm-debug.zip](https://github.com/oracle/node-oracledb/files/191324/npm-debug.zip)

Attached is the issue log while trying to install oracledb from npm.

**Comment by arindam-chattopadhya** [comment]
Hi is there any update on this issue that I faced while trying to install oracledb from npm

**Comment by cjbj** [comment]
Not enough information was provided.
Check out https://community.oracle.com/docs/DOC-931127 and #18 
If you have a specific question, perhaps about a specific error, we may be able to help.

**Comment by arindam-chattopadhya** [comment]
Hi
   I was able to resolve the issue. After setting the environment variables  OCI_LIB_DIR and OCI_INC_DIR  to point to Oracle libraries and headers are in a non-default location resolved the issues. Change the following according to your local Oracle Installation of Oracle XE or client.
Create Windows Environement variables as follows -
OCI_LIB_DIR = E:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC
OCI_INC_DIR= E:\oraclexe\app\oracle\product\11.2.0\server\oci\include
