### ISSUE TITLE
ORA-12514: Error

### ISSUE THREAD

**Issue by chanupol** [oracle/node-oracledb#394]
How do I fix this error >>> "ORA-12514: TNS:listener does not currently know of service requested in connect descriptor" and "NJS-032: connection cannot be released because a database call is in progress" . These error when I looping the large data to insert.
Thank you.

**Comment by chanupol** [comment]
When I changed the connection like this

 user          : process.env.NODE_ORACLEDB_USER || "hr",
            password      : process.env.NODE_ORACLEDB_PASSWORD || "oral",
            connectString : process.env.NODE_ORACLEDB_CONNECTIONSTRING || "xxx.xxx.xxx"

I got this error

node(13046,0x70000028d000) malloc: *** error for object 0x1017128a8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

**Comment by cjbj** [comment]
Are hr, oral and xxx.xxx.xxx valid - did you get connection working?

Sounds you are releasing the connection while it is still in use.  But, without code we can't comment.

**Comment by chanupol** [comment]
var database = new Database();

    oracledb.getConnection(database.oracleConfig(), function (err, connection) {
        if (err) {
            console.error(err.message);
            database.DoRelease(connection);
            callback(err, null);
        } else {

            var strSproc = "BEGIN SP_INSERT_VIDEOLENGTH(:degreeCode," +
                ":degreeName," +
                ":subjectGroupCode," +
                ":subjectGroupName," +
                ":periodCode," +
                ":subjectCode," +
                ":subjectName," +
                ":subjectNameEng," +
                ":subjectDesc," +
                ":creditDesc," +
                ":creditCalGrade," +
                ":creditCalPrice," +
                ":tchCode," +
                ":tchName," +
                ":isTeacherSpecial," +
                ":isTeacherActive," +
                ":totalPoint," +
                ":rtmpStreamIntro," +
                ":setCode," +
                ":setDesc," +
                ":vdoSetTotalVdoLength," +
                ":unitId," +
                ":unitName," +
                ":vdoUnitTotalVdoLength," +
                ":topicNo," +
                ":topicName," +
                ":totalTopicVdoLengthInMinute," +
                ":rtmpStream);End;";

            connection.execute(strSproc,
                {
                    degreeCode: vdoLengthData.payload.degreeCode,
                    degreeName: vdoLengthData.payload.degreeName,
                    subjectGroupCode: vdoLengthData.payload.subjectGroupCode,
                    subjectGroupName: vdoLengthData.payload.subjectGroupName,
                    periodCode: vdoLengthData.payload.periodCode,
                    subjectCode: vdoLengthData.payload.subjectCode,
                    subjectName: vdoLengthData.payload.subjectName,
                    subjectNameEng: vdoLengthData.payload.subjectNameEng,
                    subjectDesc: vdoLengthData.payload.subjectDesc,
                    creditDesc: vdoLengthData.payload.creditDesc,
                    creditCalGrade: vdoLengthData.payload.creditCalGrade,
                    creditCalPrice: vdoLengthData.payload.creditCalPrice,
                    tchCode: vdoLengthData.payload.tchCode,
                    tchName: vdoLengthData.payload.tchName,
                    isTeacherSpecial: (vdoLengthData.payload.isTeacherSpecial) ? 'Y' : 'N',
                    isTeacherActive: (vdoLengthData.payload.isTeacherActive) ? 'Y' : 'N',
                    totalPoint: vdoLengthData.payload.totalPoint,
                    rtmpStreamIntro: vdoLengthData.payload.rtmpStreamIntro,
                    setCode: vdoLengthData.payload.setCode,
                    setDesc: vdoLengthData.payload.setDesc,
                    vdoSetTotalVdoLength: vdoLengthData.payload.vdoSetTotalVdoLength,
                    unitId: vdoLengthData.payload.unitId,
                    unitName: vdoLengthData.payload.unitName,
                    vdoUnitTotalVdoLength: vdoLengthData.payload.vdoUnitTotalVdoLength,
                    topicNo: vdoLengthData.payload.topicNo,
                    topicName: vdoLengthData.payload.topicName,
                    totalTopicVdoLengthInMinute: vdoLengthData.payload.totalTopicVdoLengthInMinute,
                    rtmpStream: vdoLengthData.payload.rtmpStream
                },
                function (err, result) {
                    if (err) {
                        console.error(err.message);
                        database.DoRelease(connection);
                        callback(err, null);
                    } else {
                        database.DoRelease(connection);
                        callback(null, null);
                    }
                });
        }
    });

**Comment by cjbj** [comment]
Try releasing in a callback, not before the callback is called?  You might find it easier to use the async package - see how it is used in some of the [examples](https://github.com/oracle/node-oracledb/tree/master/examples).

**Comment by chanupol** [comment]
@cjbj  Thank you so much.
