### ISSUE TITLE
returning clause does not bind with out parameter

### ISSUE THREAD

**Issue by volkmarbuehringer** [oracle/node-oracledb#4]
var bindvars = {
      a:  req.params.namer,
      b: JSON.stringify(req.body), 
      c:  { type: oracle.NUMBER, dir : oracle.BIND_OUT },
    }

 req.connection.execute("INSERT INTO postdaten(name,t,j) values ( :a, systimestamp,:b) returning id into :c", bindvars,

no bind_outs are existing after execution

in a procedure call bind_outs are working properly

**Comment by cjbj** [comment]
Thanks for reporting this.  It's a known issue on our list; your report helps prioritize it.

**Comment by marlic7** [comment]
+1

**Comment by danschumann** [comment]
I think this is needed for us to be able to use this repo.

**Comment by danschumann** [comment]
(we're returning a single value by the way)

**Comment by vizjerai** [comment]
This feature is required to switch to this project. And the example above is exactly what we are doing.

**Comment by cjbj** [comment]
I'm sitting in a meeting right now discussing edge cases and how to make them easy.

**Comment by jamhall** [comment]
Any update on this issue? What was the outcome from the meeting? Thanks!

**Comment by cjbj** [comment]
@jamhall the feature is being worked on.

**Comment by jamhall** [comment]
Excellent. Thanks for your reply.

**Comment by aberigle** [comment]
hi @cjbj, any ETAs on this feature?

Thanks!

**Comment by cjbj** [comment]
@aberigle I don't do ETAs, but I will say we had a long meeting last night to triple-check we have the best design for RETURNING INTO binds with (future) PL/SQL IN/OUT array binds and normal IN array insert binds and any future OCI plans. A SQL RETURNING INTO clause can return an array, but we think most people will only be returning a single value. The outcome (and here's the timing hint) was that the code we currently have is not planned to change: a RETURNING INTO bind will always return an array, containing zero or more elements depending what was matched by the DML statement. Only string & number datatypes will be supported at first.

**Comment by aberigle** [comment]
@cjbj thanks for the input! 

I'll be keeping an eye on this issue

**Comment by cjbj** [comment]
@aberigle That's definitely the last time I give a release date hint. But now we something to play with.  Yay.  Check my comments in https://blogs.oracle.com/opal/entry/node_oracledb_0_5_0

Note RETURNING INTO bind variables are always returned as arrays of zero or more elements.
