### ISSUE TITLE
Question: Is Git required for anything other than cloning this repo?

### ISSUE THREAD

**Issue by mello151** [oracle/node-oracledb#40]
I know this is a terrible question, however, humor me please. I have a restricted work environment and we don't use Git nor are we even allowed to install Git. The best I can do is download the zip and run the install with Node. Outside of cloning this repo, is Git required for anything?

**Comment by cjbj** [comment]
You can use the ZIP just fine.
Also see https://github.com/oracle/node-oracledb/issues/1#issuecomment-72080904
Official Oracle Legal & management approval to add node-oracledb to the npm registry is making progress.
