### ISSUE TITLE
select with char data type bind condition doesn't match rows

### ISSUE THREAD

**Issue by saknarak** [oracle/node-oracledb#400]
If have a column that has <code>CHAR(4)</code> data type

<code>SELECT * FROM mytable WHERE code='ABC';</code>

when I query this statement from sql developer tools, result is return correctly.

but when is query in node-oracledb, no result found

<code>connection.execute(
      "SELECT * FROM mytable WHERE code=:code",
      {code:'ABC'}, ...</code>

but if i filled with space (char(4)), it found that row.

<code>connection.execute(
      "SELECT * FROM mytable WHERE code=:code",
      {code:'ABC       '}, ...</code>

How to fixed this problem?
Thank in advance.

**Comment by cjbj** [comment]
Node-oracledb exposes just a 'string' type to the app.  When binding variables it treats strings as the varchar type (not the old, blank-padded, 'fixed char').  It's the equivalent of doing
```
  -- this doesn't return any rows.
   var bv varchar2(4)
   exec :bv := 'ABC';
   select * from mytable where code=:bv;
```

vs 
```
  -- this returns the expected row
  var bv char(4)
  exec :bv := 'ABC';
  select * from mytable where code=:bv;
```

So you will need to do your own blank padding in your input variable, as you found.  Alternatively update the table datatype to varchar2.

Let us know the impact to you.  This will help us know where we need to be heading with the type system.

The same thing happens in PHP OCI8 by default.  However PHP binding lets the type be overridden:
```
// This returns the expected row
$v = "ABC"; 
oci_bind_by_name($s, ":bv", $v, -1, SQLT_AFC);  // bind as fixed char instead of the default SQLT_CHR
```

**Comment by saknarak** [comment]
Thank you for your suggestion.
I can't change data type because may be has impact on other application.

Now I have 2 choices

1. not use binding, just concatenate query string
<pre><code>var code = "ABC";
var sql = "SELECT * FROM mytable WHERE code='" + code + "'";
// need to escape string to prevent sql injection
connection.execute(sql, function(res) {});</code></pre>

2. padding value, need to know length of char column
<pre><code>var code = (code+'                 ').substr(0, 4)
connection.execute( "SELECT * FROM mytable WHERE code=:code", {code:'ABC '}, ...</code></pre>

**Comment by cjbj** [comment]
Option 1 is dangerous.

What about option 3 - use a PL/SQL wrapper:

```
  create or replace function mymap (p1 IN char) return varchar2 as
  l1 varchar2(4);
  begin
    select code into l1 from mytable where code=p1;
    return l1; 
  end;
  /
  show errors
```

You can call this in node-oracledb using:
```
sql =  "begin :ov := mymap(:iv); end;";
binds = {
  iv: 'ABC',
  ov: { dir: oracledb.BIND_OUT, type: oracledb.STRING, maxSize: 4 }
};
```

**Comment by cjbj** [comment]
Closing this old question.  I've noted that a way to override the bind type is needed.
