### ISSUE TITLE
NJS-003: invalid connection

### ISSUE THREAD

**Issue by liuyan19880121** [oracle/node-oracledb#401]
When i export data from table, i got below error.
```
D:\code\oracle>node app.js
Trace: [Error: NJS-003: invalid connection]
    at ResultSetReadStream.<anonymous> (D:\code\oracle\app.js:69:13)
    at emitOne (events.js:90:13)
    at ResultSetReadStream.emit (events.js:182:7)
    at onNextRowRead (D:\code\oracle\node_modules\oracledb\lib\resultset-read-stream.js:67:14)
    at onClose (D:\code\oracle\node_modules\oracledb\lib\resultset-read-stream.js:96:7)
```

testcase:
```js
var oracledb = require('oracledb');
var ws = require('fs').createWriteStream('test.out');

oracledb.getConnection({
    user          : "test",
    password      : "test",
    connectString : "ora"
},function(err, connection){

  if (err) return console.trace(error);

  var stream = connection.queryStream('select * from dual connect by level <= 10000 ');

  stream.on('data', function(data){
    ws.write(data + '\n');
  });

  stream.on('end', function() {
    ws.end();
  })

  stream.on('error', function (error) {
    console.trace(error);
  });
});
```

env:
```
OS: window7
node:  v5.10.0
oraclient: 12.1
```

**Comment by dmcghan** [comment]
@liuyan19880121 Thanks for the test case! Please try the following, which just releases the connection:

```javascript
var oracledb = require('oracledb');
var ws = require('fs').createWriteStream('test.out');

oracledb.getConnection({
    user          : "test",
    password      : "test",
    connectString : "ora"
},function(err, connection){

  if (err) return console.trace(error);

  var stream = connection.queryStream('select * from dual connect by level <= 10000 ');

  stream.on('data', function(data){
    ws.write(data + '\n');
  });

  stream.on('end', function() {
    ws.end();
    connection.release();
  })

  stream.on('error', function (error) {
    console.trace(error);
  });
});
```

**Comment by liuyan19880121** [comment]
@dmcghan Thanks for you response. This issue not happened after i add code to release connection.
So the root reason is the connection was released by GC if it's not referenced by others?

**Comment by dmcghan** [comment]
Well, not quite. You had a connection open when your Node.js process was ending. I'm not sure what the correct behavior in that situation should be... I got 3 different, seemingly random, outcomes: it succeeded, it threw the error you reported, or it did a core dump. 

I'll review with @cjbj, but the issue is easily avoidable in your example by releasing the connection.

**Comment by cjbj** [comment]
@liuyan19880121 yes, the connection gets released unless it is referenced. A similar thing happens when streaming LOBs. Generally this isn't observed except in small test cases.

**Comment by intergleam** [comment]
so should I close or release the connection?

**Comment by cjbj** [comment]
@intergleam See https://github.com/oracle/node-oracledb/blob/master/doc/api.md#release
Please open new issues for new questions; this issues was about LOBs.

**Comment by hackchan** [comment]
async function execQuery(sql) {
  return new Promise(async (resolve, reject) => {
    try {
      connection = await pool.getConnection();
      let response = await connection.execute(sql, {}, { autoCommit: true });
     
      resolve(response.rows);
    } catch (error) {
   
      reject(error);
    } finally {
 
      if (connection) {
        try {
          await connection.close();
        } catch (error) {
          console.log(error);
        }
      }
    }
  });
}

some times NSJ-003 invalid conection ????

**Comment by cjbj** [comment]
@hackchan this issue was closed two years ago.    Please open a new issue.  Don't mix promises and async/await unless you have a good reason.

**Comment by fikriharjo** [comment]
Thanks for the information, that was so helpful

**Comment by cjbj** [comment]
@fikriharjo review the example https://github.com/oracle/node-oracledb/blob/main/examples/selectstream.js which is current best practice usage of events.  I will edit @dmcghan's example in the comments above to make sure people don't release connections in the 'end' event.
