### ISSUE TITLE
How am I able to store the results returned from example result1.js?

### ISSUE THREAD

**Issue by isian8814** [oracle/node-oracledb#403]
Hi ,

It used recursive way to fetch rows. How am I able to store the results from this recursive methods?

function fetchOneRowFromRS (resultSet, rowArray) {
        resultSet.getRow( // get one row
            function (err, row) {
                if (err) {
                    doClose(resultSet); // always close the result set
                    //defer.reject('Error when fetching rows from result set \n ErrMsg: ' + err.message);
                } else if (!row) {                // no rows, or no more rows
                    doClose(resultSet); // always close the result set
                } else {
                    rowCount++;
                    //rowArray.push(row);
                    rowArray.push(row);
                    //console.info(row);
                    fetchOneRowFromRS(resultSet);
                }
            });

**Comment by sagiegurari** [comment]
maybe you should take a look at 
https://github.com/sagiegurari/simple-oracledb#usage-query
if you want to query and get an object with all rows read.

````js
//do this one time
var oracledb = require('oracledb');
var SimpleOracleDB = require('simple-oracledb');
SimpleOracleDB.extend(oracledb);

//get a connection via pool or via oracledb as usual
var connection = .....

connection.query('SELECT department_id, department_name FROM departments WHERE manager_id < :id', [110], function onResults(error, results) {
  if (error) {
    //handle error...
  } else {
    //print the 4th row DEPARTMENT_ID column value
    console.log(results[3].DEPARTMENT_ID);
  }
});
````

**Comment by isian8814** [comment]
yes you are right, this method will more straightforward to get returned results.

Just curious, what is resultset for? @sagiegurari

**Comment by sagiegurari** [comment]
resultset is used to fetch rows 1 or more at a time.
connection.query enables to fetch all in 1 shot which is good if you want everything in memory.
it will also read all LOBs into strings/buffers for you.

**Comment by isian8814** [comment]
So it means if I only just need some of rows, not all rows. I do not need to do it recursively to fetch all rows.
Correct?

**Comment by sagiegurari** [comment]
yap.

**Comment by dmcghan** [comment]
@isian8814 To be clear, the ResultSet class isn't really for getting one row at a time. [From the documentation](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsetclass):

> Result sets allow query results to fetched from the database one at a time, or in groups of rows. This enables applications to process very large data sets.
> 
> Result sets should also be used where the number of query rows cannot be predicted and may be larger than a sensible maxRows size.

To put it another way, imagine you have a table with 10 gigs of data in your table but you're running Node.js on a server with only 5 gigs of memory. It would be impossible to get all the data from the table in one shot into your Node.js process. That's when you can use the ResultSet.

`connection.execute` is simpler to use in many cases, and it allows you to specify the maxRows option as high as you can handle (it defaults to 100). But for very large tables, or if you don't know the size that may come back, the ResultSet, or the QueryStream (which is just syntactic sugar on top of the ResultSet), is the way to go.

Have a look here for more details:
https://jsao.io/2015/07/an-overview-of-result-sets-in-the-nodejs-driver/
