### ISSUE TITLE
unique id for each connection

### ISSUE THREAD

**Issue by sivacreatives** [oracle/node-oracledb#405]
Is there a property to get unique id for each getConnection ? It can be numbers or anything, just to differentiate each connection while logging the connections open and release.

**Comment by cjbj** [comment]
I know where you're [coming from](https://github.com/oracle/node-oracledb/issues/398. The answer is you need to track it yourself, perhaps with `select sys_context('userenv','sid'), sid from v$mystat where rownum=1;`
