### ISSUE TITLE
Instead of having to install Visual Studio on windows ,maybe add this as different solution

### ISSUE THREAD

**Issue by paran0a** [oracle/node-oracledb#406]
Hello,

My OS : Windows 10 64bit

I'd like to point to a guide on installing c++ compiler that is not Visual Studio.
 
[Guide](
https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245)

Instead of installing Visual studio I installed build tools as linked above.
I've set my ENV Paths , and installed ORACLE IC. ( I already had py 2.7 )

It was fast and simple and everything was working, as opposed to my previous experience of trying to get everything working with Visual Studio.

Just something that could help others.

**Comment by cjbj** [comment]
Thanks @paran0a. Maybe someone will find it useful.  If I recall correctly, you need a recent Node version too.  I think it was mentioned in an issue here, but I can't quickly locate the reference.

**Comment by cjbj** [comment]
This announcement has been open for enough time.  Closing it now.  I've noted it could be reviewed & added to the doc.
