### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by mendrik** [oracle/node-oracledb#407]
Hi,

I had a few problems installing this on windows 10. Turns out oracledb.vcxproj has hard-coded paths to C:\oracle\instantclient\sdk\include. Once I moved my instant client installation there, it worked nicely. 
Maybe this could be fixed, so people can choose their oracle stuff installation dir.

br,
/A

**Comment by cjbj** [comment]
@mendrik oracledb.vcxproj isn't part of node-oracledb.  Did you use the [pre-built binaries](#18) from @bchr02?

**Comment by mendrik** [comment]
well it was run during npm install oracledb. It was reporting about errors in the file, so I sort of cheated to open it before it was removed :) but as noted earlier, the invalid paths was in there.

**Comment by cjbj** [comment]
@mendrik There is a default path used in binding.gyp, maybe the vcxproj file was created as part of the build?  I don't use Windows so I don't know.   What values did you have OCI_INC_DIR and OCI_LIB_DIR set to before you ran 'npm install oracledb'? Did you follow https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin ?

**Comment by mendrik** [comment]
@cjbj I also assume the vcxproj file is created on the fly to fake a ms visual studio project. I did set the OCI_ variables to my actual folder. I don't know exactly how the underlying build runs on windows, just spotted that path there, and once I moved my oracle client to that location npm install oracledb ran through without errors.

**Comment by cjbj** [comment]
@mendrik can you do some more investigation, or should I close this?

**Comment by mendrik** [comment]
not the right way to go, but let's close it, since I got it working :)
