### ISSUE TITLE
Binary Double support

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#408]
What's the status of Binary Double support?  I see the comment here:

[dataTypeBinaryDouble.js](https://github.com/oracle/node-oracledb/blob/db5950f1cf17d6c7f786de0dd711a1291e870321/test/dataTypeBinaryDouble.js)

We could use some movement on this.

Thank you!

**Comment by cjbj** [comment]
@sanfords There are lots of things on the 'to do' list.  I would like to try to keep focus on #18, for example.

**Comment by sanfords** [comment]
Can you tell me a bit about how close dataTypeBinaryDouble is?  Where the problems are and what needs work?

**Comment by cjbj** [comment]
@sanfords it has not been looked at.

**Comment by sanfords** [comment]
Hmm.  Support seems to be in there, but the test is skipped?  Not a whole lot of detail in the comments.

**Comment by cjbj** [comment]
Sorry I don't have much to add.  There may be pre-code floating around but that's it.  Perhaps you can comment about what conversion to/from the JS type system you envision?

**Comment by sanfords** [comment]
Gottcha.  We're currently using `Number` for columns.  Numbers max out at ~10E135.  But Javascript uses IEEE doubles everywhere.  And IEEE doubles max out at ~10E308.  So the numbers we can save with node-oracledb are a subset of the numbers JS/Double/IEEE supports natively.  (If we throw a number > ~10E135 at node-oracledb, it returns an error.)

Ideally, we really need to be able to set and retrieve doubles bit for bit.  `Number` was probably easier to implement.  But `BINARY_DOUBLE` is more correct.  I am aware that Oracle's arithmetic is not 100% IEEE compliant, but I'm only asking for storage and retrieval.

`BINARY_DOUBLE` appears throughout the codebase.  I'm guessing support for it is really close.

**Comment by sanfords** [comment]
It seems if we do TO_BINARY_DOUBLE the value gets in to the DB just fine.  But when we select it the value is truncated to a `Number`.  If we can get types out, a la #358, perhaps we can quickly leverage that to do the conversion correctly.

**Comment by cjbj** [comment]
@sanfords thanks for the updates. As always, we prioritize based on demand and interest. I can't comment on when BINARY_DOUBLE support will land. Our scheduling is too dynamic (though @krismohan has been talking about how we can have a better roadmap!).

**Comment by sanfords** [comment]
We're taking a look at making BINARY_DOUBLE work over here.  If we figure it out, we'll make a pull request.  

If you or any of your team has any thoughts about this, please feel free to share.  :-)

**Comment by cjbj** [comment]
@sanfords that would be excellent.  Don't forget to submit the [OCA](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md) for the PR. If you don't do a full implementation (RETURNING INTO?), then try and make it fail gracefully!

**Comment by sanfords** [comment]
Is there now a way to set/get a binary double now with node-oracle?  Thank you.

**Comment by cjbj** [comment]
I'd have to revisit the fine points, but that test has been enabled and I know you can query BINARY_DOUBLE columns.

**Comment by sanfords** [comment]
Right!  I just did a search for BINARY_DOUBLE and found test/dataTypeBinaryDouble.js with this:

``` * NOTE
 *   BINARY_DOUBLE support is still under enhancement.
 *   There is precision issue. This test is suspended.
```

But BINARY_DOUBLE is elsewhere in this repo.  Sounds like it's close but not working.  We will need full IEEE double precision: What goes in must come out.

**Comment by cjbj** [comment]
Support for BINARY_DOUBLE was added back in v2.
