### ISSUE TITLE
Promises (Feature Request)

### ISSUE THREAD

**Issue by Gi60s** [oracle/node-oracledb#409]
It would be nice if developers had the option to use either the callback paradigm or the promise paradigm when using your library.

It would be pretty easy to detect if the user passed in the callback function as a parameter. If they did then call the callback when its time, otherwise return a promise that is resolved or rejected when complete.

Are there plans for this? If not what is the possibility that it might occur?

**Callback Paradigm**

```js
oracledb.getConnection(
  {
    user          : "hr",
    password      : "welcome",
    connectString : "localhost/XE"
  },
  function(err, connection)
  {
    if (err) { console.error(err.message); return; }

    connection.execute(
      "SELECT department_id, department_name " +
        "FROM departments " +
        "WHERE manager_id < :id",
      [110],  // bind value for :id
      function(err, result)
      {
        if (err) { console.error(err.message); return; }
        console.log(result.rows);
      });
  });
```

**Promise Paradigm**

```js
oracledb.getConnection(
  {
    user          : "hr",
    password      : "welcome",
    connectString : "localhost/XE"
  })
  .then(function(connection)
  {
    return connection.execute(
      "SELECT department_id, department_name " +
        "FROM departments " +
        "WHERE manager_id < :id",
      [110])  // bind value for :id
      .then(function(result)
      {
        console.log(result.rows);
      });
  })
  .catch(function(err) {
    console.error(err.message);
  });
```

**Comment by dmcghan** [comment]
We are working on this. Have a look here for details:
https://jsao.io/2016/03/extending-the-javascript-layer/

The QueryStream is already out...

**Comment by cjbj** [comment]
@Gi60s you must be channelling @dmcghan.  Other than needing a `return conn.release();` it looks exactly like the planned doc example for the feature.

**Comment by Gi60s** [comment]
Awesome. I'm glad to see a stream support there too.
