### ISSUE TITLE
Connection Pooling throws error

### ISSUE THREAD

**Issue by narendra-agashe** [oracle/node-oracledb#41]
I am using Connection pool in my code and i get below error

util.js:355
  desc = Object.getOwnPropertyDescriptor(value, key) || { value: value[key] };
                ^
Error: NJS-015: action is a write-only property
    at Function.getOwnPropertyDescriptor (native)
    at formatProperty (util.js:355:17)
    at util.js:294:14
    at Array.map (native)
    at formatValue (util.js:293:19)
    at inspect (util.js:140:10)
    at Console.exports.format (util.js:27:20)
    at Console.log (console.js:53:34)
    at PATH\server\routes\routeMappings.js:158:15
[nodemon] app crashed - waiting for file changes before starting...

I did a simple connection to check if database is connecting and it works.
My code for connection pooling is as follows

//code Start
var oracledb = require('oracledb');
var cp = null; //just to keep an handle on pool object, gets instantiated in createPool's callback.

oracledb.createPool (
  {
    user : 'user',
	password : 'password',
	connectString : 'IP:PORT/DB_NAME',
	poolMax : 10,
	poolMin : 2,
	poolIncrement : 2,
	poolTimeout : 4
  },
  function(err, pool) {
    console.info(pool);
    if (err) {
      console.error('createPool() callback: ' + err.message);
      return;
    }
    cp = pool;
    pool.getConnection(
    function (err, connection) {
      //console.info(connection);
      if (err) {
        console.error('getConnection() callback: ' + err.message);
        return;
      }

      connection.execute(
          "SELECT  distinct ul.user_id ,ul.login ,ul.full_name"
          + " FROM    cmsrk_user_detail ul"
          + " WHERE   ul.login= LOWER(:login)"
          + " AND     ul.active_ind = 1",
        ['agashen'],
        function (err, result) {
          if (err) {
            console.error(err.message);
            return;
          }
          console.log(result.rows);
        });

      
/* Release the connection back to the connection pool */

      connection.release(
        function (err) {
          if (err) {
            console.error('release() callback: ' + err.message);
            return;
          }
        }
      );
    }
  );
  });

 function drain(){
  console.info('i got drained.!')
   cp.terminate();
 }

/**
 * Any of these signals can be used to indicate NodeJS server shutdown
 */

process.once("SIGINT", drain);
process.once("SIGTERM", drain);
process.once('SIGUSR2', drain);

//Code End

I am using Node 0.10.35 with express.
With consoles i could figure out that pool is getting created but i get an error on pool.getConnection()

I am confused as where am i going wrong.

Thanks!

**Comment by narendra-agashe** [comment]
I got this working, there was a snag in my code which was causing it to release connection while it is executing the statement.
Thanks!
Please close/cancel/delete this thread, issue.

**Comment by cjbj** [comment]
@narendra-agashe Are you going to blog or share your working code ?
