### ISSUE TITLE
Assign a new connection in an object attribute after released the old one

### ISSUE THREAD

**Issue by Aethyn** [oracle/node-oracledb#412]
Hi everybody,
Currently I have some issues with connections :
I have an object "user" containing a "connection" attribute. I give an Oracle connection to this user (with access to only one table on the database) with getConnection(), then, after an authentication, I want to release the current connection (with release()) and give it a new one (with more rights and access to many tables) with getConnection() again, on the same attribute.

And as I can see, it seems to be not possible. I have a "NJS-003 Invalid connection" after many many time (more than 60sec).

I tried something like:
```
function doRelease(connection){
    connection.release(function(err){
        if(err){
            throw err;
        }
    });
};

function getLimitedConnection = function() {
    return new Promise(function(resolve, reject) {
        oracledb.getConnection(dbConfigLimited, function(err, connection){
            if(err) {
                throw err;
            }
            resolve(connection);
        });
    });
};

function getNormalConnection = function() {
    return new Promise(function(resolve, reject) {
        oracledb.getConnection(dbConfigNormal, function(err, connection){
            if(err) {
                throw err;
            }
            resolve(connection);
        });
    });
};

// So at this moment, my user have a limited connection in user.connection
// Then I link my new (normal) connection to my user with:
// releasing the old one
doRelease(user.connection, function(){
    // Then callback to assign a new one
    connectionFactory.getNormalConnection().then(function(connection){
        user.connection = connection;
    }).catch(function(err){
        console.err(err.message);
    });
});
```
I'm pretty newbie to node (and Oracle), and I know I use some Promises. Actually it's the only way I found to "link" an Oracle connection object to a user JS object as an attribute (and I really need to do that, but if it isn't the best way to do this, I will be happy to hear yours).  
I musn't use connection pools for some technical reasons (it's in the project's specifications).  

If you have some ideas... Thanks for your attention.

**Comment by dmcghan** [comment]
@Aethyn You call `doRelease` and pass along a callback function, but your `doRelease` function doesn't accept or invoke the callback.

Could you elaborate on the technical reasons for no pooling? I'm not saying your wrong, but I'd like to get a better understanding of the types of reasons that might cause someone not to use them in a multi-user environment.

**Comment by dmcghan** [comment]
To be clear, your doRelease should probably look like this:

```javascript
function doRelease(connection, callback){
    connection.release(function(err){
        if (err){
            callback(err);
            return;
        }
  
        callback();
    });
};
```

**Comment by Aethyn** [comment]
Ha, to be honest I had some doubts about that, but I thought I could make callbacks with anything in JS...   
Apparently  I'm wrong :x.  
Well, the idea is to give an unique connection for each client. This app won't have many concurrent connections at the same time (less than 10) and we need to know which client used specifics queries, and where/when/why/etc. It's a sort of settings single-page app. So we want to make the connection as an attribute of the user object, and then log or control what the user do, with this connection/userID link.  
  
If we use a connection pool, it will be more hard to trace the client actions. It will be like the IPv4 protocol for example. I will need to trace which client had a particular connection at a particular moment, to now what this client did. And I think it will be too hard for me to make that.

I hope it's eloquent 'cause as you can see, english isn't my birth language.
I'm the only one working on this project (in a small software engineering company) and the only one who use NodeJS, the others developpers are on others projects (and they don't know node). That's why I'm struggling since February with the oracledb-node :P.
  
In any case, thanks for the answer dmcghan :)

**Comment by dmcghan** [comment]
You're welcome.

Please have a look at the following:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#endtoend

Whether you use connection pools or not (I still think you should), this is the way you should probably go about implementing your tracing logic.

**Comment by cjbj** [comment]
@Aethyn as well as setting the [client id](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#endtoend) to solve the question you asked, you may be interested in the dev branch of node-oracledb that has Promise support: https://blogs.oracle.com/opal/entry/node_oracledb_1_9_0

**Comment by Aethyn** [comment]
@dmcghan @cjbj Thanks for your help guys !
