### ISSUE TITLE
Can't install it on Fedora 23

### ISSUE THREAD

**Issue by jradesenv** [oracle/node-oracledb#413]
I was using it in Windows 8.1 and Ubuntu with success. Now i'm trying to use it in Fedora 23 but can't get it to install.

I'm following the instructions for .zip:
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instzip

Hope anyone will help me. Thanks.

see below my npm-debug.log in attachment (as .txt)
[npm-debug.txt](https://github.com/oracle/node-oracledb/files/226649/npm-debug.txt)

**Comment by cjbj** [comment]
What's the first error in the log?  Did you try installing node-oracledb just by itselft?

**Comment by jradesenv** [comment]
Yeah. Tried it again just now. 
I did export LD_LIBRARY_PATH, OCI_LIB_DIR and OCI_INC_DIR, and then i run npm install oracledb.
This is the new npm-debug.log in attachment

[npm-debug.txt](https://github.com/oracle/node-oracledb/files/227884/npm-debug.txt)

**Comment by cjbj** [comment]
Did you check the first error?  It looks the same "Unsupported".  fsevents seems to be documented as OS X only.

**Comment by jradesenv** [comment]
I got that unsupported in windows and ubuntu too but everything went fine

**Comment by jradesenv** [comment]
could it be a problem with node-gyp or something?

**Comment by jradesenv** [comment]
Finally the error is gone.
Just installed gcc and gcc-c++ and now its working!!!

It wasn't an error with oracledb but with nodegyp.

Thankyou
