### ISSUE TITLE
problem installing node-oracle on Red Hat Enterprise Linux Server release 6.6 (Santiago)

### ISSUE THREAD

**Issue by juanpablogd** [oracle/node-oracledb#415]
Hello

I will paste the whole outcome of the execution of "npm install oracle" below.

../src/njs/src/njsOracle.cpp:1025: error: ‘init’ was not declared in this scope
../src/njs/src/njsOracle.cpp:1025: error: too many initializers for ‘node::node_module’
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory `/usr/lib/oracle/12.1/client64/node_modules/oracledb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/oracle/12.1/client64/node_modules/oracledb
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm verb lifecycle oracledb@1.8.0~install: unsafe-perm in lifecycle false
npm verb lifecycle oracledb@1.8.0~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/oracle/12.1/client64/node_modules/oracledb/node_modules/.bin:/usr/lib/oracle/12.1/client64/node_modules/.bin:/usr/local/bin:/usr/lib/oracle/12.1/client64/bin:/usr/local/bin/node:/Sigdata/mongodb/db/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib/jvm/java-openjdk/bin:/usr/local/jboss/jboss-eap-6.2/bin:/root/bin
npm verb lifecycle oracledb@1.8.0~install: CWD: /usr/lib/oracle/12.1/client64/node_modules/oracledb
npm info lifecycle oracledb@1.8.0~install: Failed to exec install script
npm verb unlock done using /root/.npm/_locks/staging-f99d970a2f4e4ad4.lock for /usr/lib/oracle/12.1/client64/node_modules/.staging
npm WARN enoent ENOENT: no such file or directory, open '/usr/lib/oracle/12.1/client64/package.json'
npm WARN client64 No description
npm WARN client64 No repository field.
npm WARN client64 No README data
npm WARN client64 No license field.
npm verb stack Error: oracledb@1.8.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:244:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:827:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid oracledb@1.8.0
npm verb cwd /usr/lib/oracle/12.1/client64
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--verbose" "install" "oracledb"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

Help please, thanks in advance

**Comment by cjbj** [comment]
Check [INSTALL](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md) to see if you have the appropriate C++ compiler.  The default compiler on RH 6 isn't sufficient for Node.js 4+.  However I would have expected you to see this error: https://github.com/nodejs/nan/blob/master/nan.h#L40

**Comment by juanpablogd** [comment]
SOLVED: I updated the complilador , thanks
see: https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b

**Comment by cjbj** [comment]
@juanpablogd thanks for the link.  EPEL might also have RPMs.
