### ISSUE TITLE
Node > 0.12.7 - not installing 

### ISSUE THREAD

**Issue by jhonyourangel** [oracle/node-oracledb#417]
Hi, and i am back on posting issue.
So i've installed, easily , on windows 7 with node 0.12.7 ( 64bit )

I've tried with newer versions, like 4.4.0 and 5.8.0 and 5.11.0, also in 64bit. But is not working.
The issue is the same as 99.99% of the people that have issue installing oracledb : "node-gyp rebuild".
After weeks of googling, is there a fix for that error ?

on my machine i have installed:
Win 7  64bit
phyton 2.7
node - not yet defined since i keep using the old good 0.12.7, hope there will be a fix for the new NODE 5.11.0.

Oracle drivers: 
Instant client 12.1.0.2.0 (64 bit )

PATH is set
OCI_LIB_DIR is set
OCI_INC_DIR is set

Am i missing something ?

**Comment by jhonyourangel** [comment]
OK, so i strongly believe that is OFFICIAL! oracledb works ONLY on node 0.12.7 and bellow!!!
Some where between 0.10.0 to  0.12.7

**Comment by sagiegurari** [comment]
We use Node 4. Works great.
Your issue is probably old c compiler.

**Comment by jhonyourangel** [comment]
Can you give me some info about your system ?
Like node-gyp version ?

**Comment by sagiegurari** [comment]
We have Windows 7 64 bit with vs 2015 community, we have centos 6.5 with upgraded c++ compiler, Ubuntu, mint and Mac.
All work good. 
We didn't install Node gyp manually.
We use Node 4.2 and npm 3

**Comment by jhonyourangel** [comment]
I know this will annoy you, but cans you please check the node gyp version.
I've found on Google , that the gyp version that I had "2.0.1" was old, so I've installed the "3.3.1" ( if I'm not wrong ) and now is asking me for a CL.exe file in the /Microsoft Visual Studio 14.0/VC/bin" directory, and is not there.

Since this is all documented, it may help future users on this issue.

**Comment by sagiegurari** [comment]
I won't have access to my work PC until next week so can't answer your question.
However your issue has already been answered multiple times regarding Node 4/5 so search for it in the closed issues. The answer should be there.

**Comment by cjbj** [comment]
If you're OK with pre-built, "3rd party" (!) binaries, see #18.

**Comment by sagiegurari** [comment]
sorry for late reply.
the node-gyp installed as part of my npm is "version": "3.2.0"
npm --version
3.5.1
node --version
v4.2.2

**Comment by cjbj** [comment]
Closing due to lack of updates.

**Comment by jhonyourangel** [comment]
hi, sorry for la lack of feedback. i'm still trying to install this " blody " module.
I am trying to find the alignment between versions of node and other problem fix

**Comment by jhonyourangel** [comment]
hi all,
So i manage to install it on win 7, node 4.4.5.
I did a fresh install, and it didn't work. because i also had problems with the windows update, i did another fresh install, this time everything work like a charm.

Solution to make it work at the try ? i don't know. keep trying.
You should be careful at the instructions and the microsoft installs : win sdk, c++ compilers ( that come with visual studio ).
