### ISSUE TITLE
Use NAN 2.3 for Node 6: (node) v8::ObjectTemplate::Set() with non-primitive values is deprecated (node) 

### ISSUE THREAD

**Issue by jeveloper** [oracle/node-oracledb#418]
Node sure if this was already filed with a different name

Running 1.8 and node 6.0
Seeing a lot of these messages in log 

(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

Thanks

**Comment by cjbj** [comment]
This isn't too surprising since NAN 2.2 doesn't support Node 6.

You could try updating package.json to use NAN 2.3.  This hasn't been tested beyond a basic query script - NAN 2.3 was only released a few hours ago.

**Comment by jeveloper** [comment]
Thanks for clarification , sounds like its on the list for next version.

**Comment by cjbj** [comment]
@jeveloper NAN 2.3 needs to be tested; let us know what you find.

**Comment by sant123** [comment]
Regarding with this, when I require oracledb this log appears on the screen.

[log.txt](https://github.com/oracle/node-oracledb/files/245272/log.txt)

**Comment by cjbj** [comment]
@sant123 isn't that because you are using NAN 2.2? Try with 2.3 and let us know how it goes.

**Comment by sant123** [comment]
@cjbj I've just update from NAN 2.2 to 2.3 and the stack trace persist; it appered after I upgrade to Node v.6.0

**Comment by cjbj** [comment]
@sant123 define 'update'?  You need to clone node-oracledb and modify package.json to test properly.

**Comment by sant123** [comment]
@cjbj Let's take a look in Google: make (something) more modern or up to date. I'm just kidding, yes you were right! I was doing the update yes the update in other side.

Thanks, the stack trace is not showing anymore.

**Comment by cjbj** [comment]
@sant123 thanks for the 'update'!

**Comment by jgoux** [comment]
Is there a way to hide these warnings by passing node an option until the next version is published ?

**Comment by cjbj** [comment]
@jgoux I've not looked for a workaround.  You could clone this repo, patch package.json to depend on NAN 2.3, and install from github.

**Comment by whenov** [comment]
@jgoux You can redirect stderr to a log file: `npm start 2>./oracle.log`

**Comment by jgoux** [comment]
@whenov I'm already doing it, it was more for not polluting the file. :+1: 
I'll wait. :smile:

**Comment by cjbj** [comment]
This is fixed in node-oracledb 1.9.1
