### ISSUE TITLE
Oracle node-gyp error

### ISSUE THREAD

**Issue by normancarcamo** [oracle/node-oracledb#421]
Hi everyone, I have some problems when installing oracledb from npm in linux debian wheezy 
<img width="1073" alt="screen shot 2016-04-28 at 2 03 07 pm" src="https://cloud.githubusercontent.com/assets/2402579/14899576/f42a5142-0d49-11e6-812d-ed5b1008573c.png">

Could somebody help to solve this?

**Comment by cjbj** [comment]
What does that first error about g++-4.6 indicate?  Check the compiler [prerequisites](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#prerequisites).

**Comment by normancarcamo** [comment]
Thankyou is true, now that problem was solved.
