### ISSUE TITLE
Current state of Knex + oracledb.

### ISSUE THREAD

**Issue by paran0a** [oracle/node-oracledb#422]
Any official information about these two working together?

I know Knex worked with older driver , but we've had an official driver for quite some time.

I've seen @cjbj offer his help to the knex crew. Did you get anywhere with them?

**Comment by cjbj** [comment]
@paran0a are you following/contributing to https://github.com/tgriesser/knex/pull/990 ?

**Comment by paran0a** [comment]
Huh , somehow I missed it. I'll check it out.

**Comment by cjbj** [comment]
@paran0a I would love your feedback when you check into it.
