### ISSUE TITLE
Crash while fetching NCLOB 

### ISSUE THREAD

**Issue by irakligogiashvili** [oracle/node-oracledb#427]
How can i work with NCLOB ?

**Comment by cjbj** [comment]
Do you have a testcase?  There is no explicit NCHAR/NVARCHAR/NCLOB support in node-oracledb but I don't like it crashing.

**Comment by DatoBula** [comment]
My code doesn't crashes, but when I'm trying to read NCLOB data, I could not read text. I have ILOB type object, but when reading where is `LOB form mismatch` error. Is there any way to work with NCLOB?

**Comment by cjbj** [comment]
http://docs.oracle.com/database/121/SQLRF/functions218.htm#SQLRF06131 ? But you are probably using NCLOB that won't fit into your DB char set?

**Comment by DatoBula** [comment]
@cjbj Thanks, that works for me.

**Comment by jmullaney** [comment]
Is there a workaround for this that can be implemented without changing SQL? (In our architecture, the SQL lives elsewhere and there is a bunch of it referencing tables and views with some NCLOB columns.) So it's impractical (at least at this time) to "TO_CLOB" the NCLOB columns.

**Comment by jmullaney** [comment]
I was able to patch oracledb to add basic read support for NCLOBs. I can't contribute to this project, but if anyone is interested:

The main change is in dpiLob.cpp. Previously it always used the charsetform SQLCS_IMPLICIT, resulting in a mismatched charsetform for NCLOB, which needs SQLCS_NCHAR. Now it determines the form to use from the LOB rather than hard-coding it.

The other changes are to pass the OCI environment to Lob::read(), which is needed to determine the charsetform from the lob.

src\dpi\src\dpiLob.cpp:

          Read from the Lob Locator.

        PARAMETERS
    +     envh                - OCI environment handle
          svch                - OCI service handle
          errh                - OCI error handle
          lobLocator          - Lob locator to be read
      @@ -77,15 +78,21 @@ using namespace dpi;

      */

    - void Lob::read(DpiHandle *svch, DpiHandle *errh, Descriptor *lobLocator,
    + void Lob::read(DpiHandle *envh, DpiHandle *svch, DpiHandle *errh, Descriptor *lobLocator,
                     unsigned long long &byteAmount, unsigned long long &charAmount,
                     unsigned long long offset, void *buf, unsigned long long bufl)
      {
    +   ub1 csfrm = SQLCS_IMPLICIT;
    +   
    +   ociCall(OCILobCharSetForm((OCIEnv *)envh, (OCIError *)errh,
    +                             (OCILobLocator*) lobLocator, &csfrm),
    +           (OCIError *)errh);
    +
        ociCall(OCILobRead2((OCISvcCtx *)svch, (OCIError *)errh,
                            (OCILobLocator *)lobLocator,
                            (oraub8 *)&byteAmount, (oraub8 *)&charAmount,
                            offset, buf, (oraub8)(byteAmount ? byteAmount : bufl),
    -                       OCI_ONE_PIECE, NULL, NULL, 0, SQLCS_IMPLICIT),
    +                       OCI_ONE_PIECE, NULL, NULL, 0, csfrm),


src\dpi\include\dpiLob.h:

      {
       public:

    -   static void read(DpiHandle *svch, DpiHandle *errh, Descriptor *lobLocator,
    +   static void read(DpiHandle *envh, DpiHandle *svch, DpiHandle *errh, Descriptor *lobLocator,
                         unsigned long long &byteAmount,
                         unsigned long long &charAmount,
                         unsigned long long offset,


src\njs\src\njsConnection.cpp:

          goto exitLOB2StringOrBuffer;
        }

    -   Lob::read ( (DpiHandle *) executeBaton->dpiconn->getSvch(),
    +   Lob::read ( (DpiHandle *) executeBaton->dpienv->envHandle(),
    +               (DpiHandle *) executeBaton->dpiconn->getSvch(),
                    (DpiHandle *) executeBaton->dpiconn->getErrh (),
                    lobLocator, byteAmount, charAmount, offset,
                    bind->value, bufLen );


src\njs\src\njsIntLob.cpp:

            // for CLOBs, bufLen is adjusted to handle multi-byte charsets
            bufLen = charAmount * iLob->dpiconn_->getLOBCharExpansionRatio ();
          }
    -     Lob::read((DpiHandle *)iLob->svch_, (DpiHandle *)iLob->errh_,
    +     Lob::read((DpiHandle *)iLob->njsconn_->oracledb_->getDpiEnv()->envHandle(), 
    +               (DpiHandle *)iLob->svch_, (DpiHandle *)iLob->errh_,
                    (Descriptor *)iLob->lobLocator_, byteAmount, charAmount,
                    iLob->offset_, (void *)iLob->buf_, bufLen);

**Comment by cjbj** [comment]
node-oracledb v2 can query NCHAR/NVARCHAR/NCLOB. 

 DML needs further work but may be OK depending on character sets.  See  the [release announcement](https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github) and also the known [issues list](https://github.com/oracle/node-oracledb/issues/716).
