### ISSUE TITLE
Oracledb not working on RHEL(Red Hat Enterprise Linux Server release 6.4) for node 4.0

### ISSUE THREAD

**Issue by maria-braganza** [oracle/node-oracledb#429]
Oracledb not working on RHEL(Red Hat Enterprise Linux Server release 6.4) for node 4.0.
The same works on Ubuntu and Windows machine.
We build the node-gyp and transferred the module to the RHEL machine. We get the following error.

[root@hj-plapsd2260 tool-staging]# node app
module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Debug/oracledb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous>

**Comment by cjbj** [comment]
You probably hit this issue: https://blogs.oracle.com/opal/entry/getting_a_c_11_compatible

**Comment by cjbj** [comment]
Closing due to lack of feedback.
