### ISSUE TITLE
Can a single connection handle multiple result sets?

### ISSUE THREAD

**Issue by xpiwo** [oracle/node-oracledb#430]
How are RS objects connected to Connection objects?

I obtain a single connection, and open 2 rs in series, later i close them in series and release the connection.

This works well. is this the expected use?

Can this be done in parallel? both for opening and closing? or should i stick to series?

Thanks.

**Comment by dmcghan** [comment]
> I obtain a single connection, and open 2 rs in series, later i close them in series and release the connection.

What do you mean by open 2 rs in series? Is this what you're currently doing?

1. get connection
2. execute query 1, which returns a resultset
3. process and close resultset
4. execute query 2, which returns a resultset
5. process and close the resultset
6. close connection

And is this what you want to do?

1. get connection
2. execute query 1 and 2 in parallel, which return resultsets
3. process and close resultsets in parallel
4. close connection

In theory you should be able to do this, however I don't think you'll see much if any as a connection can only do one thing at a time.

Run some tests, let us know what you find! :)

Just remember, the default transaction isolation level (read committed) will give you read consistency from the time you start the query. So if the queries are executed in sequence and there's a long time between executions the database could look very different. The parallel option would help mitigate that. Here's another hybrid option:

1. get connection
2. execute query 1, which returns a resultset
3. execute query 2, which returns a resultset
4. process and close resultsets in series
5. close connection

Of course you could also change the transaction isolation level, use flashback, etc.

**Comment by xpiwo** [comment]
right now the flow is : 

1. get connection
2. execute query 1, which returns a resultset
3. execute query 2, which returns a resultset
4. cleanup: close rs1 & rs2 in series <- mostly i was wondering if this can be done in parallel
5. close connection

this works well (besides the rs memory leak that hopefully will be fixed soon).

if running in parallel, is it right to assume the 2nd rs.close() will be queued until the first one finishes?

**Comment by dmcghan** [comment]
You're flow is missing the processing step (no big deal really). A ResultSet can be compared to a cursor in PL/SQL where the normal sequence is:
1. Parse
2. Bind
3. Execute
4. Fetch

With ResultSets, steps 1-3 are done with the call to execute, so the only thing left is the fetching/processing (and of course the connection management which isn't necessary with PL/SQL).

> if running in parallel, is it right to assume the 2nd rs.close() will be queued until the first one finishes?

Yes, either you do the queuing or the connection will (as it can only do one things at a time). I would recommend doing the queuing in the JavaScript code as it's more explicit and provides more control.
