### ISSUE TITLE
best way to handle multiple transactions, using connection pooling?

### ISSUE THREAD

**Issue by derickbailey** [oracle/node-oracledb#433]
My app is finally at a point where I need to insert multiple levels of data in a parent -> child -> grandchild hierarchy of Oracle tables and relationships.

What's the best way to handle a single transaction around all of the inserts that I need to do, with connection pooling turned on in the oracledb lib for node?

Do I need to explicitly request a single connection from the pool and re-use that one connection for every call?

Right now I am requesting any available connection from the pool, for each separate call to Oracle.

Any advice is appreciated (and please assume I'm not super familiar with Oracle's transactions - i get the gist of it, but i haven't deal with them in about 8 years)

**Comment by sagiegurari** [comment]
You must use the same connection.

Take a look at simple-oracledb for some utilities for that

Run multiple actions in the same transaction:
https://github.com/sagiegurari/simple-oracledb#usage-transaction

Simple way to run an action via pool directly:
https://github.com/sagiegurari/simple-oracledb#usage-run

**Comment by cjbj** [comment]
In general if you use more than one connection you will end up with multiple transactions that are not aware of data changes on the other connections.

For the relationship in the schema you described, @sagiegurari was right and his transaction wrapper looks neat.

Using multiple connections could be a valid solution for, say, parallelizing multiple, independent queries to build up a web page. You would just need to ensure the DB can cope with the overall number of connections.

**Comment by cjbj** [comment]
Closing now.  Ping you have more questions.
