### ISSUE TITLE
"Failed at the oracledb@1.9.2 install script 'node-gyp rebuild'" error

### ISSUE THREAD

**Issue by ElCondor1969** [oracle/node-oracledb#436]
Hi to all.
I try to install oracledb package but there isn't way to do it.
I attached the log file that npm created hoping that it can help.
Bye.

Sergio.
[npm-debug.zip](https://github.com/oracle/node-oracledb/files/277561/npm-debug.zip)

**Comment by ElCondor1969** [comment]
Please don't cosider this issue and close up it.
Thank you.

**Comment by cjbj** [comment]
See #437
