### ISSUE TITLE
Error "'OCI_ERROR_MAXMSG_SIZE2' : undeclared identifier" building with version 1.9.2 and Oracle client 11.2.0.2

### ISSUE THREAD

**Issue by vivane** [oracle/node-oracledb#437]
When I try to build my module (which has 'oracledb' in dependencies), I get following errors: 

`..\src\dpi\src\dpiUtils.cpp(70): error C2065: 'OCI_ERROR_MAXMSG_SIZE2' : undeclared identifier [C:\dev\mdb\db-oracle-orm\node_modules\oracledb\build\oracledb.vcxproj]
..\src\dpi\src\dpiUtils.cpp(72): error C2065: 'OCI_ERROR_MAXMSG_SIZE2' : undeclared identifier [C:\dev\mdb\db-oracle-orm\node_modules\oracledb\build\oracledb.vcxproj]
..\src\dpi\src\dpiUtils.cpp(75): error C2065: 'OCI_ERROR_MAXMSG_SIZE2' : undeclared identifier [C:\dev\mdb\db-oracle-orm\node_modules\oracledb\build\oracledb.vcxproj]
..\src\dpi\src\dpiUtils.cpp(75): error C2660: 'OCIErrorGet' : function does not take 6 arguments [C:\dev\mdb\db-oracle-orm\node_modules\oracledb\build\oracledb.vcxproj]
`

This happens when I use latest - 1.9.2 - version of 'oracledb'. With earlier versions, everything works fine.

**Comment by cjbj** [comment]
Some details would be useful.  What version of the Oracle client libraries & sdk are you using?  
Digging around it looks like this macro was only introduced in 11.2.0.3 - yuck.

**Comment by vivane** [comment]
I believe it is 11.2.0.2.0

**Comment by cjbj** [comment]
For a workaround, upgrade to 11.2.0.3 or fork the repo and use the old message size `OCI_ERROR_MAXMSG_SIZE` instead of `OCI_ERROR_MAXMSG_SIZE2`.

**Comment by vivane** [comment]
For now, I use dependency as "<1.9.0" instead. I understand that I might be missing most recent features implemented in the library but this is the safest way in my situation...

Could you add a check in the code which would verify whether "new" macro is implemented and use the "old" one if not?

**Comment by cjbj** [comment]
I do plan to add the check; I labelled this issue as a 'bug'.

As a _real hack_ you could add the `OCI_ERROR_MAXMSG_SIZE2` macro to `sdk/include/oci.h`.  Set it to the value of `OCI_ERROR_MAXMSG_SIZE` and then install 1.9.2.

**Comment by cjbj** [comment]
Fixed in 1.9.3. Sorry about the inconvenience.

**Comment by vivane** [comment]
Thank you for the prompt fix.
