### ISSUE TITLE
Compatibility with 10g (10.1.0.2.0)

### ISSUE THREAD

**Issue by Arsca** [oracle/node-oracledb#44]
Hi,

I installed according to installation doc and when trying to connect a remote Oracle 10g on Linux 
get this error:

ORA-03134: Connections to this server version are no longer supported.

Regards,

**Comment by cjbj** [comment]
Check the Oracle Support client-server compatibility matrix, Doc ID 207303.1
I'm guessing you have Oracle Database 10gR1.  It's time to upgrade to a supported DB version.

Or, remove the #error in dpiStmt.h and see whether building with Instant Client 11.1 works (it used to, but this is not something that is expected or planned)

**Comment by Arsca** [comment]
Hi,

Compiled it with the instantclient_v.11.2.0.1.0-1 and  managed to query ok.
Thanks.

**Comment by cjbj** [comment]
@Arsca What version DB do you have?

**Comment by Arsca** [comment]
Product version:	Oracle Database 10g Enterprise Edition Release 10.1.0.2.0 - Production
