### ISSUE TITLE
Data type of a field

### ISSUE THREAD

**Issue by ctwardatulsakinah** [oracle/node-oracledb#446]
Hi,

I just wanna ask, can I return the data type of a field such as varchar2, integer, and etc.?

I hope to get the output such as,

[ { name: 'CUST_ID' }, { name: 'CUST_NAME' } ]  --metadata

[ { type : int, size : 11, primaryKey : true },
  { type : varchar2, size : 100, primaryKey : false } ] --data type of field

fetchRowsFromRS(): Got 2 rows
[ { CUST_ID: 1, CUST_NAME: 'trump' },
  { CUST_ID: 2, CUST_NAME: 'exo' } ] --data

If there's any documentation, which documentation and example should i refer?

Thank you for your help.

**Comment by cjbj** [comment]
Search this repo for 'metadata'.  In particular see https://github.com/oracle/node-oracledb/pull/386
