### ISSUE TITLE
when did update successly,console like this,but nothing changed in fact,could you help me?

### ISSUE THREAD

**Issue by SHocker-Yu** [oracle/node-oracledb#447]
var docreate = function (conn, cb) {
  conn.execute(
    "CREATE TABLE test (id NUMBER, name VARCHAR2(20), age VARCHAR2(20),age1 VARCHAR2(20))",
    function(err)
    {
      if (err) {
        return cb(err, conn);
      } else {
        console.log ("Table created");
        return cb(null, conn);
      }
    });
};

var doinsert_autocommit = function (conn, cb) {
  conn.execute(
    "INSERT INTO test VALUES (:id, :nm, :age, :age1)",
    [1, 'Chris',13,14],  // Bind values
    { autoCommit: true},  // Override the default non-autocommit behavior
    function(err, result)
    {
      if (err) {
        return cb(err, conn);
      } else {
        console.log ("Rows inserted: " + result.rowsAffected);  // 1
        return cb(null, conn);
      }
    });
};
var doupdate = function  (conn,cb) {

  conn.execute(
    "UPDATE shocker.test t SET name = '123' WHERE EXISTS(SELECT *FROM test WHERE test.id = 1) ", 

    function  (err,result) {
      if (err) {
        return cb(err,conn);
      } else{
        console.log ("Rows updated:" + result.rowsAffected);
        return cb(null,conn);
      }
    });
};

console:Table dropped
             Table created
             Rows inserted:1
             Rows updated:1
             [[1,'Chris','13','14']]                if update success,it should be [1,'123','13','14']
             Table droped 

What can i do to make the doupdate success?
may be it is about the autocommit?

**Comment by cjbj** [comment]
What's the problem you are seeing?  What have you tried?

**Comment by SHocker-Yu** [comment]
Goodmoring cjbj,sorry to get back to u so latter,im a volunteer at a Animals shelter on weenkends.My English is not good,i mean i cannot effectively describe the problem, a moment ago,i saw your words,and you are right ,i dont try my best to resovle this promblem.So i read the example clobupdate1  again ,i used   
      "UPDATE mylobs SET c = EMPTY_CLOB() WHERE id = :id RETURNING c INTO :lobbv",
      { id: 1, lobbv: {type: oracledb.CLOB, dir: oracledb.BIND_OUT} },
      { autoCommit: false }"
Change some content in there,i resolved my problem,thank you for your unselfish dedication,thank you very much.

**Comment by cjbj** [comment]
@SHocker-Yu I'm glad you solved it.
