### ISSUE TITLE
Installation fails during rebuild

### ISSUE THREAD

**Issue by jordabi** [oracle/node-oracledb#45]
when attempting to perform and npm install on a CentOS machine with a local 11g XE instance, the following error occurs:

[root@localhost node-oracledb]# echo $ORACLE_HOME
/etc/ortab
[root@localhost node-oracledb]# npm install -g
\
> oracledb@0.3.1 install /lib/node_modules/oracledb
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/lib/node_modules/oracledb/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/dpi/include/dpiConn.h:29:0,
                 from ../src/dpi/include/dpiPool.h:33,
                 from ../src/dpi/include/dpiEnv.h:36,
                 from ../src/dpi/include/dpi.h:35,
                 from ../src/njs/src/njsOracle.h:36,
                 from ../src/njs/src/njsOracle.cpp:28:
../src/dpi/include/dpiStmt.h:29:18: fatal error: oci.h: No such file or directory
 # include <oci.h>
                  ^
compilation terminated.
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/oracledb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.10.0-123.20.1.el7.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/oracledb
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! oracledb@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@0.3.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-123.20.1.el7.x86_64
npm ERR! command "/bin/node" "/bin/npm" "install" "-g"
npm ERR! cwd /home/vsatdev/Projects/vsat/node_modules/node-oracledb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by cjbj** [comment]
@jordabi what was the solution?

**Comment by jordabi** [comment]
It was two-fold:

First, I had to change the permissions on
my /usr/local/lib/node_modules/node-modules folder to grant write and then
re-run as me instead of root.

The second seems to be an error in the installation instructions for
installing with a local DB instance.  The directions say to set
 ORACLE_HOME to the path of the oratab file (e.i. /etc/oratab), but when
set that way the build then fails because it can't find the oci.h header
which is included in dpiStmt.h.  The fix was to update ORACLE_HOME to point
to the actual folder defined in oratab which in my case
is /u01/app/oracle/product/11.2.0/xe.

On another note, I am starting to incorporate this driver in place of a
JDBC implementation, but will need support for CLOBs. I can work around
this for the next month or so in development, but once in production, will
need that support.  Do you foresee that functionality be present in the
near term?


On Wed, Mar 11, 2015 at 9:18 AM, Christopher Jones <notifications@github.com

**Comment by cjbj** [comment]
@jordabi Valuable info.  Your last point shows a weakness in the instructions - they actually say "see etc oratab" (as in "look inside and use the path it says") but now I see how it can be misread.  I'll make it clearer.

**Comment by jordabi** [comment]
Cool, thanks.  As for the LOB support, I am about to test this, but do
normal select/inserts into CLOB fields work at present?

On Wed, Mar 11, 2015 at 9:47 AM, Christopher Jones <notifications@github.com

**Comment by cjbj** [comment]
There's no LOB support yet.  But it is being actively worked on.  The V8 engine is being wrestled with but is proving elusive.

**Comment by jordabi** [comment]
I can work around this if need be by chunking text into multiple rows, but
would prefer not to bother.  If you were a betting man, do you think this
would be done in the next 30-45 days?  Just asking for your gut feeling
before I go through the hassle of the work-around.

On Wed, Mar 11, 2015 at 9:55 AM, Christopher Jones <notifications@github.com

**Comment by jordabi** [comment]
Chris,

Can you please assist me with getting this driver configure?  It seems to
have built fine, but I cannot reference it simply as:

var oracledb = require('oracledb');

but rather need to include the full path like

oracledb =
require('/home/vsatdev/Projects/vsat/node_modules/node-oracledb/lib/oracledb'


When I attempt to start my app, I get the following error:

/home/vsatdev/Projects/vsat/node_modules/node-oracledb/lib/oracledb.js:28
    throw err;
          ^
Error: libclntsh.so.11.1: cannot open shared object file: No such file or
directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>
(/home/vsatdev/Projects/vsat/node_modules/node-oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)



I have verified that the library exists in the XE folder, and have exported
ORACLE_HOME and included it in the PATH.

Any ideas what I'm doing wrong?

Thanks,

Bill


On Wed, Mar 11, 2015 at 9:55 AM, Christopher Jones <notifications@github.com

**Comment by jordabi** [comment]
Please disregard.  I found the problem and it was mine.  Missed a couple
steps in the instructions.
