### ISSUE TITLE
Installation issues on Oracle Enterprise Linux

### ISSUE THREAD

**Issue by anthonylai** [oracle/node-oracledb#451]
Tried installing by both the zip and rpm method in Oracle Enterprise Linux, and got the exact same error below.

Can you kindly take a look please?

System details:
-bash-4.2$ cat /etc/*-release
Oracle Linux Server release 7.1
NAME="Oracle Linux Server"
VERSION="7.1"
ID="ol"
VERSION_ID="7.1"
PRETTY_NAME="Oracle Linux Server 7.1"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:1"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.1
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.1
Red Hat Enterprise Linux Server release 7.1 (Maipo)
Oracle Linux Server release 7.1

> oracledb@1.9.3 install /home/aslai/dev/drillinator/node_modules/oracledb
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/aslai/dev/drillinator/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsResultSet.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsIntLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiCommon.o
  SOLINK_MODULE(target) Release/obj.target/oracledb.node
  COPY Release/oracledb.node
cp: preserving permissions for ‘Release/oracledb.node’: Operation not supported
make: *** [Release/oracledb.node] Error 1
make: Leaving directory `/home/aslai/dev/drillinator/node_modules/oracledb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/aslai/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.8.13-55.1.6.el7uek.x86_64
gyp ERR! command "/home/aslai/.nvm/versions/node/v6.2.1/bin/node" "/home/aslai/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aslai/dev/drillinator/node_modules/oracledb
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN drilldown@1.0.0 No description
npm WARN drilldown@1.0.0 No repository field.
npm ERR! Linux 3.8.13-55.1.6.el7uek.x86_64
npm ERR! argv "/home/aslai/.nvm/versions/node/v6.2.1/bin/node" "/home/aslai/.nvm/versions/node/v6.2.1/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@1.9.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aslai/dev/drillinator/npm-debug.log

**Comment by cjbj** [comment]
The error:
```
Release/obj.target/oracledb.node COPY Release/oracledb.node cp: preserving permissions for ‘Release/oracledb.node’: Operation not supported 
make: *** [Release/oracledb.node] Error 1 make:
```

doesn't sound node-oracledb related.  What's special about your filesystem - [are you using NFS](https://www.google.com.au/search?q=cp%3A+preserving+permissions+Operation+not+supported&oq=cp%3A+preserving+permissions+Operation+not+supported&aqs=chrome..69i57j69i58.5217j0j7&sourceid=chrome&ie=UTF-8#q=cp:+preserving+permissions+Operation+not+supported&tbs=qdr:y)?  Where/how/what did you run to do the install?

I was initially reminded of [this recently fixed npm issue](https://github.com/npm/npm/issues/10013), but it is probably unrelated.

**Comment by anthonylai** [comment]
Yep, that's it!  Thank you!

**Comment by mangobin** [comment]
hey, i got the exact same problem as you, can you tell me how do u solve it?

**Comment by cjbj** [comment]
@mangobin the npm install infrastructure doesn't work over NFS.

**Comment by mangobin** [comment]
so this cannot be solved? I am an oracle employee using linux VM, need to deploy the node js project on my virtual machine, how can I do that? thanks

**Comment by anthonylai** [comment]
@mangobin :  you can move your project to a local location like /, build it there, then move it back to where you want it to be.  That was how I resolved it.  Hope this helps.  Thanks.

**Comment by mangobin** [comment]
@anthonylai  awesome!! just tried out! You made my day!!!

**Comment by ferdiebirdie** [comment]
"you can move your project to a local location like /, build it there, then move it back to where you want it to be. That was how I resolved it. Hope this helps. Thanks."

Can you please put the steps here? Thanks!

**Comment by anthonylai** [comment]
@ferdiebirdie 
The issue I encountered was that node-oracledb can not be built in a NFS file system.
As a workaround, you need to npm install locally in a directory that sits locally in the machine you are running on, e.g. the root.
Steps:
1.  sudo mv YOUR_PROJECT /
2.  cd /YOUR_PROJECT
3.  npm install node-oracledb
Hope this helps.
