### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by marczzio** [oracle/node-oracledb#452]
1. What error(s) you are seeing?
```
Unable to resolve some modules:

  "../build/Release/oracledb" in              
/usr/local/bin/testoracle3/node_modules/oracledb/lib/oracledb.js (os.linux.x86_64)
  "../build/Debug/oracledb" in                
/usr/local/bin/testoracle3/node_modules/oracledb/lib/oracledb.js (os.linux.x86_64)

```
`W20160608-23:20:35.150(7)? (STDERR) Error: /usr/local/bin/testoracle3/node_modules/oracledb/build/Release/oracledb.node: undefined symbol: node_module_register`

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`var oracledb = require('oracledb');`. 
command to install => `npm install oracledb --save`
Login as Root

3. What environment variables did you set?  How *exactly* did you set them?
`export PATH=/opt/node-v4.2.3-linux-x64/bin:$PATH`
`export LD_LIBRARY_PATH=/opt/oracle/instantclient_12_1:$LD_LIBRARY_PATH`
`export OCI_LIB_DIR=/opt/oracle/instantclient_12_1`
`export OCI_INC_DIR=/opt/oracle/instantclient_12_1/sdk/include`

4. What is your version of Node.js?
`nodejs version 4.2.3`

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
oracle client version 12.1.0.2.0. Using unzip to install it. and the Dir is in `/opt/oracle/instantclient_12_1/`

6. What is your OS and version?
`ubuntu 14.04`

7. What compiler version did you use?
Well I'm trying it in Meteor.js since meteor version 1.3 can using NPM Package

Thank you

**Comment by cjbj** [comment]
Google for node_module_register - the problem has been seen before when Node versions got mixed.  If you have upgraded Node, then clean up and rebuild node-oracledb.

**Comment by marczzio** [comment]
Do you mean I should re install node on my system?? what version should I use this time??

**Comment by cjbj** [comment]
I would start by cleaning up and reinstalling.  Use whatever version of Node satisfies your business requirements.  Use the latest node-oracledb.  Check the google results for tips on things to look out for.

**Comment by cjbj** [comment]
Closing due to lack of feedback.

**Comment by frenchbread** [comment]
I'm getting the same issue. Tried lots of node versions & times rebuilding. Still getting this error.

**Comment by cjbj** [comment]
@frenchbread Can you open a new issue with some details?

**Comment by frenchbread** [comment]
@cjbj Thanks for quick reply, opened #539.

**Comment by robertosantos13** [comment]
Security context: 000002CE9F625EE1 <JSObject>
    1: createEntityNameFromSymbolChain(aka createEntityNameFromSymbolChain) [G:\ProjetoServico\HtApp\AppEquipeHT\node_modules\typescript\lib\typescript.js:~26339] [pc=000001D5B83667B0](this=0000002215102311 <undefined>,chain=00000393E0CC0B71 <JSArray[1]>,index=0)
    2: symbolToName(aka symbolToName) [G:\ProjetoServico\HtApp\AppEquipeHT\node_modules\typescript\lib\typescript.js:~26322] [pc=000...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFillerObject
 5: v8::internal::MemoryReducer::TearDown
 6: 000001D5B7B847A1

Somebody help me about it
