### ISSUE TITLE
Stored Procedure Params

### ISSUE THREAD

**Issue by evanshortiss** [oracle/node-oracledb#454]
Hi, thanks for the module! 

I think the issue I'm experiencing is likely something simple, but I've had no luck figuring it out. Given the following code:

```js
  var params = {
    p1:  null,
    p2:  'john doe',
    ret:  { dir: oracledb.BIND_OUT, type: oracledb.CURSOR }
  };

  conn.execute(
    "CALL SEARCH_PROC(:p1, :p2, :ret)",
   // "BEGIN SEARCH_PROC(:p1, :p2, :ret); END;", // Yields the same result
    params,
    function (err, ret) {
      if (err) {
        console.log('failed', err);
      } else {
        console.log(ret);
      }
    }
  );
```
The result returned is:

```
{ outBinds: 
       { ret: 
          { metaData: [Object],
            close: [Function],
            getRow: [Function],
            getRows: [Function],
            toQueryStream: [Function: toQueryStream] } },
      rowsAffected: undefined,
      rows: undefined,
      metaData: undefined }
```

Using the older "oracle" module on npm like so:

```js
params = [
      null,
      'john doe',
      new oracle.OutParam(oracle.OCCICURSOR)
];

 conn.execute(
    "CALL SEARCH_PROC(:1, :2, :3);",
    params,
    function (err, ret) {
      if (err) {
        console.log('failed', err);
      } else {
        console.log(ret);
      }
    }
  );
```

Returns rows as expected.

Oracledb (node module): 1.9.3
Mac OS 10.11
node.js 0.10.30

Perhaps it's a simple issue, but I'm failing to crack it.

**Comment by dmcghan** [comment]
You didn't say what the problem was. The output looks good to me. What were you expecting?

**Comment by evanshortiss** [comment]
@dmcghan apologies for not being more clear. No results are returned when using "oracledb", but using "oracle" returns results just fine.

**Comment by dmcghan** [comment]
@evanshortiss With node-oracledb, cursors are returned as ResultSet objects. These objects, as shown in your output, have methods like getRow and getRows that allow you retrieve the actual rows. Here's the doc on how to use them:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsethandling

Here's a blog pose I wrote on them:
https://jsao.io/2015/07/an-overview-of-result-sets-in-the-nodejs-driver/

Alternatively, you could invoke the toQueryStream method and process the ResultSet as a stream:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#streamingresults

**Comment by sagiegurari** [comment]
you can also use simple-oracledb wrapper to get results as an array of objects.
See https://github.com/sagiegurari/simple-oracledb
https://github.com/sagiegurari/simple-oracledb#usage-query

````js
//do this once in boot of app
var oracledb = require('oracledb');
var SimpleOracleDB = require('simple-oracledb');
SimpleOracleDB.extend(oracledb);

//get pool from oracledb library
var pool = ....

//use pool (or connection, but pool is better) to run some action like a query which would return
//all results as an array of objects (all LOBs read as well)
pool.run(function (connection, callback) {
  //run some query and the output will be available in the 'run' callback
  connection.query('SELECT department_id, department_name FROM departments WHERE manager_id < :id', [110], callback);
}, function onActionDone(error, result) {
  //do something with the result/error
});
````

**Comment by pvenkatraman** [comment]
The third parameter to your PL/SQL procedure is of type CURSOR, so you got an object which has a property called metadata, and methods close, getRow, getRows.  The dump of object like this will display data like this only.  You got to use object to fetch data using getRow or getRows method from this cursor object.

**Comment by evanshortiss** [comment]
@pvenkatraman @sagiegurari @dmcghan thanks folks, will give this a try asap.

**Comment by cccabdalla** [comment]
@dmcghan , this link, " https://jsao.io/2015/07/an-overview-of-result-sets-in-the-nodejs-driver/  "
helped me so much.    Thanks.

**Comment by cjbj** [comment]
@cccabdalla also check the changes in v2, see https://blogs.oracle.com/opal/node-oracledb-v2-query-methods-and-fetch-tuning

**Comment by cccabdalla** [comment]
@cjbj , thanks for the helpful link provided.

**Comment by DeepakDonde** [comment]
The link below is not valid anymore:
https://jsao.io/2015/07/an-overview-of-result-sets-in-the-nodejs-driver/

Anyone have alternate link or content?

**Comment by cjbj** [comment]
@DeepakDonde start with the documentation https://node-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-rows-with-result-sets 
and examples:
- https://github.com/oracle/node-oracledb/blob/main/examples/resultset1.js
- https://github.com/oracle/node-oracledb/blob/main/examples/resultset2.js
- https://github.com/oracle/node-oracledb/blob/main/examples/resultsettoquerystream.js

Feel free to ask questions.
