### ISSUE TITLE
Question about tnsnames.ora, where does it need to be placed?

### ISSUE THREAD

**Issue by juveguevara** [oracle/node-oracledb#456]
Hello oracledb team,

I am currently connecting to Oracle database single instance, using below code, and it's working really good. 
oracledb.getConnection({user: *****,password:*****,connectString: server1.company.com},function(err, connection) {......});

I have checked that we have a cluster version that will contain two servers, as shown below:

testp =
  (DESCRIPTION =
    (SDU = 45655)
    (enable = broken)
    (LOAD_BALANCE = yes)
    (ADDRESS = (PROTOCOL = TCP)(HOST = server1.company.com)(PORT = 1526))
    (ADDRESS = (PROTOCOL = TCP)(HOST = server2.company.com)(PORT = 1526))
    (CONNECT_DATA =
      (SERVICE_NAME = testpc)
    )
  ) 

When a server fails-over and is not active the app starts failing because there is no active listeners, so we have to change our code to point to the other active server. i.e. server2.company.com

So, i was reading https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-812-net-service-names-for-connection-strings

And found from the documentation that there is a way to actually create tnsnames.ora and allow the application to read automatically this when it fails-over 

But i am having doubts about where do we need to place tnsnames.ora file, which directory. From the documentation i can see that the file can be located at:

The tnsnames.ora file can be in a default location such as $ORACLE_HOME/network/admin/tnsnames.ora or /etc/tnsnames.ora. Alternatively set the TNS_ADMIN environment variable and put the file in $TNS_ADMIN/tnsnames.ora

But my server is an application server not db server, so it does not contain the ORACLE_HOME, Can you please provide further details about where does the tnsnames.ora needs to be placed?

Thanks in advance

4. What is your version of Node.js?
v0.10.41

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm

6. What is your OS and version?
Red Hat Enterprise Linux Server release 6.6

**Comment by cjbj** [comment]
It's very common for Oracle 'clients' to set the `TNS_ADMIN` environment variable so that the file `$TNS_ADMIN/tnsnames.ora` is read.  You can put the file anywhere it makes sense for your system management.

There is a search hierarchy for `TNS_ADMIN` (at least on Linux). You can `strace` the binary to see where it looks. One place is `/etc/tnsnames.ora`. This is uncommon but if you do this, then you wouldn't need to set `TNS_ADMIN`.
