### ISSUE TITLE
Writing multiple blobs in the same instruction

### ISSUE THREAD

**Issue by vlavorini** [oracle/node-oracledb#457]
Hello,

   is the plugin tested for multiple blob insertion in the DB?

Someone has an example?

Thank you

**Comment by cjbj** [comment]
If you mean inserting into a table that has multiple clob columns, you could get all the returned LOB binds, and use something like `async.eachSeries` to stream into each one in turn.  If you mean insert multiple rows, each containing one lob then repeatedly execute the INSERT and stream into the returned LOB stream.
