### ISSUE TITLE
How to use Secure External Password Store? (Oracle Wallet)

### ISSUE THREAD

**Issue by jmptrader** [oracle/node-oracledb#461]
Dear,

With node-oracledb

How to use Secure External Password Store? 

In production  environment  the  use user/password in clear text is privative (not allowed)

Thank's,
JM

´´´
var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "hr",                    // 
    password      : "welcome",     //
    connectString : "localhost/XE"
  },
 ...
´´´

**Comment by dmcghan** [comment]
@jmptrader Checkout the section on external authentication:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-84-external-authentication

**Comment by jmptrader** [comment]
@dmcghan OK. Thank's.
