### ISSUE TITLE
Need to read and write to XMLTYPE columns

### ISSUE THREAD

**Issue by russfleming** [oracle/node-oracledb#464]
I need to write a service providing a REST interface to our database that holds XMLTYPE data in one of the columns.  

One of the purposes of this service is to provide the XML content to callers.  It will also need to be able to write to this column when callers provide new data.

In writing a small Node.js appliation using Oracledb, I found that I am unable to retrieve the XML data using a select statement.  I get the following error:

**NJS-010: unsupported data type in select list**

Here is the code that generates the error:

        module.connection.execute(
            "select experiment_xml from cm_experiment where cm_experiment_id= :id",
            [req.params.id],  // bind value for :id
            function(err, result)
            {
                if (err) { console.error(err.message); return; }
                console.log(result.rows);
            });

The column "EXPERIMENT_XML" is type XMLTYPE.

Is there a way to do this using Oracledb and Node or do I need to use some other framework?

**Versions:**
node: v4.4.5
npm: 2.15.5
Instantclient: (from BASIC_README file)
     Thu Sep 11 02:53:25 CDT 2014
     Client Shared Library 64-bit - 12.1.0.2.0

**Environment variables:**
OCI_INC_DIR=C:\apps\instanclient_12_64bit\sdk\include
OCI_LIB_DIR=C:\apps\instanclient_12_64bit\sdk\lib\msvc
path has _C:\apps\instanclient_12_64bit_ in it

Running Windows 7 Enterprise 64 bit (6.1 build 7601) English

**Comment by cjbj** [comment]
Until any native support gets added to node-oracledb, you can use some of the techniques outlined in the XMLType chapter of [Underground PHP and Oracle Manual](http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html). They are similar for node-oracledb.

**Comment by cjbj** [comment]
Closing this.  'Temporary LOB' support is really needed, which is tracked in #186 and #204.  Otherwise you end up having to use temporary tables for inserting XML.
