### ISSUE TITLE
Installation issues (move oracledb between two computer, same environment)

### ISSUE THREAD

**Issue by Aethyn** [oracle/node-oracledb#467]
Hi everyone,
So here is my problem :  
- I'm currently working on a nodejs app using oracledb, my app is ended soon, and I must install it on a test server.
- I have two computers (Windows 10, same brands, same configurations, same models and updates, exactly). The first (dev) was installed as described in the documentation (https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin), the second (test) just have a) Instantclient with SDK, b) path and environment vars.

My problem is :  
When I build the oracledb on my dev computer, it works perfectly. I type "node app" to launche the app and I see a console.info information to show the app ip/port.
But the oracledb build need python 2.7, a VC redistributable like vc10/vc12, some additionnal env-vars, etc. And the final users (technical support) musn't install anything except nodejs (obviously) and the app directory on the production environment. No restart, no VC10/12, no python, etc.

So, I tried something, I use the same Node on dev and test (6.2.2), same NPM (3.9.5), same Oracledb (1.9.3) and I tried to build oracledb on the dev computer to copy/paste the full project (including modules) to the test computer. Because technically it is built, so it doesn't need compiling environment anymore ?
But when I'm entering the "node app" command, I have the following error : 

C:\Users\Me\Desktop\app>node server
C:\Users\Me\Desktop\app\node_modules\oracledb\lib\oracledb.js:37
    throw err;
    ^
Error: Le module spécifié est introuvable.
\\?\C:\Users\Me\Desktop\app\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Me\Desktop\app\node_modules\oracledb\lib\oracledb.js:32:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

C:\Users\Me\Desktop\app>

Error is in french and significate "cannot find specified module".
Can anyone help me ?
Thx a lot.

**Comment by cjbj** [comment]
Does https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#winbins help?

**Comment by Aethyn** [comment]
I will try this as soon as possible (probably not before Monday 11th) and tell you if it works.
Thanks for your help !

**Comment by Aethyn** [comment]
Well... It works perfectly, so yes it helps a lot !  
I didn't see this section before, shame on me...  
You can close the issues, thanks a lot @cjbj, you're the best ! :D
