### ISSUE TITLE
ELF file's phentsize not the expected size

### ISSUE THREAD

**Issue by nalbion** [oracle/node-oracledb#468]
I've managed to run `npm install oracledb` locally, but when I deploy to AWS Lambda it throws the following error:

```
{
  "errorMessage": "/var/task/node_modules/oracledb/build/Release/oracledb.node: ELF file's phentsize not the expected size",
  "errorType": "Error",
  "stackTrace": [
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/node_modules/oracledb/lib/oracledb.js:32:19)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)"
  ]
}
```

Local config:
```bash
$ uname -spr
Linux 3.13.0-89-generic x86_64
$ node --version
v4.3.2
$ npm --version
2.14.12
$ cat node_modules/oracledb/package.json | grep version
  "version": "1.9.3",
```

**Comment by nalbion** [comment]
In case it helps:

```
$ npm install oracledb --verbose
npm info using npm@2.14.12
npm info using node@v4.3.2
npm verb install oracledb is installed as 1.9.3
> node-gyp rebuild
gyp info using node-gyp@3.0.3
gyp info using node@4.3.2 | linux | x64
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.6\n"

gyp info spawn args [ '/home/nalbion/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nalbion/workspace/test/node_modules/oracledb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nalbion/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nalbion/.node-gyp/4.3.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/nalbion/.node-gyp/4.3.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/nalbion/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/nalbion/workspace/test/node_modules/oracledb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]

gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/nalbion/workspace/test/node_modules/oracledb/build'
  g++ '-DNODE_GYP_MODULE_NAME=oracledb' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/nalbion/.node-gyp/4.3.2/include/node -I/home/nalbion/.node-gyp/4.3.2/src -I/home/nalbion/.node-gyp/4.3.2/deps/uv/include -I/home/nalbion/.node-gyp/4.3.2/deps/v8/include -I/usr/include/oracle/11.2/client64 -I../src/dpi/src -I../src/dpi/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -fexceptions -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -fexceptions -MMD -MF ./Release/.deps/Release/obj.target/oracledb/src/njs/src/njsOracle.o.d.raw  -c -o Release/obj.target/oracledb/src/njs/src/njsOracle.o ../src/njs/src/njsOracle.cpp
...
  g++ -shared -pthread -rdynamic -m64  -Wl,-soname=oracledb.node -o Release/obj.target/oracledb.node -Wl,--start-group Release/obj.target/oracledb/src/njs/src/njsOracle.o Release/obj.target/oracledb/src/njs/src/njsPool.o Release/obj.target/oracledb/src/njs/src/njsConnection.o Release/obj.target/oracledb/src/njs/src/njsResultSet.o Release/obj.target/oracledb/src/njs/src/njsMessages.o Release/obj.target/oracledb/src/njs/src/njsIntLob.o Release/obj.target/oracledb/src/dpi/src/dpiEnv.o Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o Release/obj.target/oracledb/src/dpi/src/dpiException.o Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o Release/obj.target/oracledb/src/dpi/src/dpiUtils.o Release/obj.target/oracledb/src/dpi/src/dpiLob.o Release/obj.target/oracledb/src/dpi/src/dpiCommon.o -Wl,--end-group -lclntsh -L/usr/lib/oracle/11.2/client64/lib 
  rm -rf "Release/oracledb.node" && cp -af "Release/obj.target/oracledb.node" "Release/oracledb.node"
```

**Comment by cjbj** [comment]
Some shared/static lib thing??  From https://bugzilla.redhat.com/show_bug.cgi?id=121606
> "Upstream glibc has been changed so that when dlopening ET_REL
> objects it will complain about "only ET_DYN and ET_EXEC can be loaded"
> instead of "ELF file's phentsize not the expected size".

You seem to be building with the Instant Client RPMs which will force rpath by default.  Perhaps try the Instant Client zips as used in https://github.com/oracle/node-oracledb/issues/458 ?

**Comment by nalbion** [comment]
Yes, I'm using the RPMs & alien locally, but have also tried the zips (for 11.2) on amzn1.x86_64

**Comment by cjbj** [comment]
Try with the zips locally.

**Comment by nalbion** [comment]
I've created an EC2 instance using the same AMI that the Lambda instances use, but I'm still getting the same error.

Could it be that I haven't copied across the necessary `.so` files in the `lib` directory?  (Could you provide a bare-minimum list of lib files that are required?  I'd like to keep the size of the Lambda function down, especially as AWS enforce a maximum size)

Do I also need libaio.so?

**Comment by nalbion** [comment]
@cjbj I'm working on a "hello world" test app:  https://github.com/nalbion/node-oracledb-lambda-test

So far I've been able to load `require('oracledb')` on the Lambda-like EC2 instance.  

Tomorrow I'll try to complete it to the point where the scripts actually deploy a zip to Lambda.  If the hello world app works I'll close this issue and debug my other app.  If not, hopefully somebody at Oracle will be able to clone the project and debug.

**Comment by nalbion** [comment]
My [node-oracledb-lambda-test](https://github.com/nalbion/node-oracledb-lambda-test) repo should make it easy for somebody (at Oracle) to reproduce.  When I run `npm install oracledb` on an EC2 based on `ami-48d38c2b` I'm no longer getting the "Elephant size" error, but now I'm getting a new error on Lambda:

> Process exited before completing request

I've set the timeout to 30 seconds and the Memory limit to 1536, but the web console says that it's only using 40MB and failing within 65ms.  It the error disappears as soon as I remove the line `require('oracledb')`

The zip archive uploaded to Lambda includes:

```
index.js
package.json
node_modules/oracledb/package.json
node_modules/oracledb/index.js
node_modules/oracledb/lib/connection.js
node_modules/oracledb/lib/lob.js
node_modules/oracledb/lib/oracledb.js
node_modules/oracledb/lib/pool.js
node_modules/oracledb/lib/querystream.js
node_modules/oracledb/lib/resultset.js
node_modules/oracledb/lib/util.js
node_modules/oracledb/build/Release/oracledb.node
lib/libclntsh.so.12.1
lib/libmql1.so
lib/libipc1.so
lib/libnnz12.so
lib/libons.so
lib/libaio.so.1
lib/libclntshcore.so.12.1
```

...am I missing something?

**Comment by nalbion** [comment]
...to answer my own question, yes - I was missing `lib/libociei.so`. @cjbj @oracle is there any way that the size of this file could be reduced?  (It's currently **105 MB**)  Amazon impose [size limits for Lambda](http://docs.aws.amazon.com/lambda/latest/dg/limits.html):

 - 50 MB for a deployment package (.zip file) and 
 - 250 MB for uncompressed code & dependencies

My simple "hello world" application already weighs in at **54 MB** zipped up (fortunately, I can still upload to S3 and get Lambda to download from an S3 URL) and **179 MB** uncompressed.

**Comment by cjbj** [comment]
@nalbion Sounds like you have it working?

Try using the smaller Instant Client 'Basic Lite' package instead of 'Basic'.
https://docs.oracle.com/database/121/LNOCI/oci01int.htm#LNOCI13309 
Table 1-4 tells you which files you need for OCI programs (node-oracledb is an OCI program)

**Comment by nalbion** [comment]
Thanks @cjbj 

For the next person: I've created a "fork" of this repo specifically for Lambda (it actually uses the test project mentioned above to do the build)  

https://github.com/nalbion/node-oracledb-for-lambda

**Comment by nalbion** [comment]
@cjbj I was getting error messages when `libipc1.so`, `libmql1.so` and `libons.so` were not provided (with `libociei.so`).  Is Table 1-4 saying that none of these are required with `libociicus.so`?

**Comment by cjbj** [comment]
@nalbion Table 1-3 of that OCI manual shows the libraries needed for Basic; they differ from those in Base Lite.

Thanks for creating the fork!
