### ISSUE TITLE
Is it possible to promisify execute() using Bluebird?

### ISSUE THREAD

**Issue by bberryhill** [oracle/node-oracledb#47]
I have a scenario where I need to execute the same query across multiple oracle instances. Once all of the queries have returned, combine the results to be emitted back to the client over a websocket.

I've successfully created a pool for each db instance and saved them in an array to be looped through when a query across them is to be executed.

I'm trying to use Bluebird to promisify node-oracledb using:

var oracle = Promise.promisifyAll(require("oracledb"));

That all seems to work until I try to run the function that will execute the promise version of execute() that bluebird promisifyAll is supposed to create (i.e. executeAsync() ). 

I'm getting the following error:

Error executing query: [TypeError: Object #<Connection> has no method 'executeAsync']

So, a couple of questions:
Are there any future plans for promise support being built into node-oracledb?
Is there a different approach I should be using to get promises working for my scenario using either bluebird, or Q, etc.

Below is the function definition I've been trying that raises the error mentions above:

    var calldbs = function (orapools, sql) {
        var finalResults = [];
        // Loop through orapools, get a connection, execute a sql statement
        _.each(orapools, function (orapool) {
                try { // Try getting the connection from the pool
                      orapool.getConnection(function(err, connection){
                        try { // Try to Execute the sql statement
                              finalResults.push(connection.executeAsync(sql, [], {outFormat: oracle.OBJECT})
                              .then(
                                function(results) {
                                  connection.release(function (err) {});
                                  return results;
                                }
                              ));
                        } catch (err) {
                                console.log("Error executing query:", err);
                                return;
                                }
                      })
                } catch (err) {
                                console.log("Error getting connection from orapool:", err);
                                return;
                                }
        });

        Promise.all(finalResults).then(function() {
            emitCalldbsResults(socket, 'my event name', finalResults);
        });
     };

**Comment by dmcghan** [comment]
@bberryhill I'm not sure why promisifyAll didn't work though it may have something to do with how it traverses the object. Technically, you used promisifyAll on the Oracldb class/object, not the connection class or the pool class.

Try calling it on the connection when it's passed in after calling getConnection.

**Comment by alexsantos** [comment]
I myself prefer to use iojs and the core implementation of Promises and generators. For your use-case, I would build my own executeAsync function like this:
```
function executeAsyn(sql, bindParams, options, connection) {
    return new Promise(function (resolve, reject) {
        connection.execute(sql, bindParams, function (err, result) {
            if (err) {
                console.error(err.message);
                reject(err);
            }
            resolve(result.rows);
        });
    });
}
```
With this function I then could use something like tj/co and yield in parallel all those connections.
As an example, you could do something simpler like this:
```
executeAsyn(sql, [40], null, connection).then(console.log).catch(console.error);
```

**Comment by alexsantos** [comment]
One more thing,
you could also wrap the getConnection:
```javascript
function getAsyncConnection(connAttrs) {
    return new Promise(function (resolve, reject) {
        oracledb.getConnection(connAttrs, function (err, connection) {
            if (err) {
                console.error(err.message);
                reject(err);
            }
            resolve(connection);
        });
    });
}
```
This function returns a Promise, so you can do something like this:
```javascript
co(function * () {
    var dbConn = yield getAsyncConnection({
        user: "scott",
        password: "tiger",
        connectString: "192.168.122.241/db11g.home"
    });
    var sql = "SELECT deptno, dname FROM dept WHERE deptno = :did";
    var result = yield executeAsyn(sql, [40], null, dbConn);
    return result
}).then(console.log).catch(onerror);
```
There must be some care about closing this connections... but you get the point. With co, you can process these connections in parallel :+1:

**Comment by bberryhill** [comment]
Thanks @dmcghan and @alexsantos for the tips.

@dmcghan I was thinking along those lines also of promisifying the connection after calling getConnection. Unfortunately  when I try it with this line:

var oraclePromConn = Promise.promisifyAll(connection);

I get the below error:

[Error: NJS-015: action is a write-only property]

@alexsantos I was able to build my own executeAsync function and get it to work using your example. Many thanks for posting it. Next I'll work on getting some chaining or use co to get all of the results collected before emitting the results back to the client over a websocket.

I'm almost tempted to try io.js (or go up to node v0.12 once node-oracledb supports it) for the core implementation of Promises and generators.

I'll post back with my results when I've got something working. Or, if I get stuck again.

**Comment by alexsantos** [comment]
:+1: 
There is already a PR that enables the use of node-oracledb with iojs. I used that to test this code. For now, you must use Bluebird.

**Comment by cjbj** [comment]
@bberryhill that 'write-only property' error is a pain for other reasons too.  I've already got it in the (long) list of things I want the developers to revisit.

**Comment by dmcghan** [comment]
@bberryhill I wrote a more in-depth blog post on this topic: https://jsao.io/2015/03/making-a-wrapper-module-for-the-node-js-driver-for-oracle-database/
