### ISSUE TITLE
Config encryption via driver not instantclient - Lambda

### ISSUE THREAD

**Issue by tomdavidson** [oracle/node-oracledb#471]
I am able to enforce encryption on the client side by configuring the instantclient and setting a env var to the config file. https://github.com/byu-oit-appdev/docker-node-oracledb also referenced in #411 

This works great for our server based apps. Now I am working on some AWS Lambda Functions and have seen some great guidance in #458 - but nothing on encryption specifically.

How do we configure encryption via the node-oracledb driver rather than though system config files for the instantclient? The primary motivation is for my Lambda functions to use encryption without changing things on the db server side.

**Comment by cjbj** [comment]
@tomdavidson encryption is a feature of the underlying Oracle Net component so you will need to continue using Oracle Net's `sqlnet.ora` configuration files.

**Comment by cjbj** [comment]
@tomdavidson I'll close this for now.
