### ISSUE TITLE
installation error on Linux Mint (14.04 ubuntu)

### ISSUE THREAD

**Issue by zzzianzzz** [oracle/node-oracledb#473]
1. What error(s) you are seeing?

npm http GET https://registry.npmjs.org/oracledb
npm http 304 https://registry.npmjs.org/oracledb
npm WARN engine oracledb@1.10.0: wanted: {"node":">=0.10.28 <7"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> oracledb@1.10.0 install /media/d/mintDev/its/node_modules/oracledb
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /media/d/mintDev/its/node_modules/oracledb
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                  
 
npm ERR! weird error 1
npm ERR! not ok code 0

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
npm install oracledb (also installed the npm install -g node-gyp)

3. What environment variables did you set?  How *exactly* did you set them?
export OCI_INCLUDE_DIR=/opt/oracle/instantclient/sdk/include
export OCI_LIB_DIR=/opt/oracle/instantclient 
export PATH=/opt/oracle/instantclient:$PATH
export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH

4. What is your version of Node.js?
v0.10.25 
(Tried reinstalling and installing again. Tried upgrading, does not allow upgrade as it is the latest version?)

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
12.1 (download both sdk, and basic client)
unzip, stored into those folders as above

6. What is your OS and version?
Linux Mint KDE (Ubuntu 14.04) - 64 bit

7. What compiler version did you use?
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
python 2.7

**Comment by cjbj** [comment]
Thanks for the detail.  Try a newer version of Node.  You have 0.10.25 but the installer wants >= 0.10.28

> npm WARN engine oracledb@1.10.0: wanted: {"node":">=0.10.28 <7"} (current: {"node":"v0.10.25","npm":"1.3.10"})
