### ISSUE TITLE
 ORA-12537: TNS: Connection Closed Error

### ISSUE THREAD

**Issue by c011v** [oracle/node-oracledb#478]
I try to insert data into database by for loop when inserting data less than 150  times  , no error message
But more than 150 times , i get this error message   ORA-12537: TNS: Connection Closed Error

Please help me to fix this error ,thanks

Here's my code 

```
    var defer = Q.defer();
    var qDBinsertArr = [];

    for(var i=0;i<data.length;i++){
          var sql="insert into temp_table (seq_no)values(data[i].no)";
        var tempPromise = {};
        (function () {
            tempPromise = database.simpleExecute(sql,[], { autoCommit: true });
            qDBinsertArr.push(tempPromise);
        })();
   }
    Q.all(qDBinsertArr).then(function (results) {
        console.log('Q.all Process Success');
    })
    .catch(function (err) {
        console.log("in qDBinsertArr ERROR: ", err);
        next("Insert Detail Error,Error Message:" + err);
    });

```

Environment
1. OS:Windows 2003 Server 
2. Oracle client 11g
3. Node.js Version: 0.10.38
4. Oracledb Version: 1.9.3

**Comment by dmcghan** [comment]
@c011v Your example is not complete. Could you share your "database" module? Are you using a pool? If so, what is the poolMax? Are you adjusting the UV_THREADPOOL_SIZE?

Is this a close example of what you're actually trying to do? It doesn't seem functional. For example, the value of `data[i].no` will not work as you have it - it's just part of the insert string. 

If this is close to what you're trying to do, then I think it's the wrong approach. You could just load up an array of the values you're trying to insert and send those over in a single round trip/insert statement that does a bulk operation. Let me know if you'd like an example of this - I need to blog about something anyway! :)

If you really need to do it as you have it, then I would suggest adding some flow control. As it's currently written, all of the requests are sent at the "same time" via the loop. That means you're relying on the driver's internal queue to handle the load. That should work generally speaking, but you have less control over that. A better means of doing this would be to use the [async module's eachSeries](http://caolan.github.io/async/docs.html#.eachSeries) method.

**Comment by sagiegurari** [comment]
try the batchInsert function in the simple-oracle extension
https://github.com/sagiegurari/simple-oracledb#usage-batchInsert

**Comment by c011v** [comment]
Thanks @sagiegurari  and  @dmcghan   yours suggestion That's really helpful for me
Here's my database module . A few minutes later ,I will be updated the full example

module.exports = {
  connectString:process.env.ORACLE_CONN || "*******",
  user:process.env.ORACLE_USER || "root",
  password:process.env.ORACLE_PASSWD || "superadmin",
  poolMax: 100000,
  poolMin: 2,
  poolIncrement: 4,
  poolTimeout: 4 
};

**Comment by c011v** [comment]
update database.js

```
var oracledb = require('oracledb');
var Promise = require('es6-promise').Promise;
var async = require('async');
var pool;
var buildupScripts = [];
var teardownScripts = [];

module.exports.OBJECT = oracledb.OBJECT;
module.exports.oracledb = oracledb;

function createPool(config) {
    return new Promise(function(resolve, reject) {
        oracledb.createPool(
            config,
            function(err, p) {
                if (err) {
                  return reject(err);
                }
                pool = p;
                resolve(pool);
            }
        );
    });
}

module.exports.createPool = createPool;

function terminatePool() {
  return new Promise(function(resolve, reject) {
    if (pool) {
      pool.terminate(function(err) {
        if (err) {
          return reject(err);
        }
        resolve();
      });
    } else {
      resolve();
    }
  });
}

module.exports.terminatePool = terminatePool;

function getPool() {
  return pool;
}

module.exports.getPool = getPool;

function addBuildupSql(statement) {
    var stmt = {
        sql: statement.sql,
        binds: statement.binds || {},
        options: statement.options || {}
    };

    buildupScripts.push(stmt);
}

module.exports.addBuildupSql = addBuildupSql;

function addTeardownSql(statement) {
  var stmt = {
    sql: statement.sql,
    binds: statement.binds || {},
    options: statement.options || {}
  };
  teardownScripts.push(stmt);
}

module.exports.addTeardownSql = addTeardownSql;

function getConnection() {
  return new Promise(function(resolve, reject) {
    pool.getConnection(function(err, connection) {
      if (err) {
        return reject(err);
      }
      async.eachSeries(
        buildupScripts,
        function(statement, callback) {
          connection.execute(statement.sql, statement.binds, statement.options, function(err) {
            callback(err);
          });
        },
        function (err) {
          if (err) {
            return reject(err);
          }
          resolve(connection);
        }
      );
    });
  });
}

module.exports.getConnection = getConnection;

function execute(sql, bindParams, options, connection) {
  return new Promise(function(resolve, reject) {
    connection.execute(sql, bindParams, options, function(err, results) {
      if (err) {
        return reject(err);
      }
      resolve(results);
    });
  });
}

module.exports.execute = execute;

function releaseConnection(connection) {
  async.eachSeries(
    teardownScripts,
    function(statement, callback) {
      connection.execute(statement.sql, statement.binds, statement.options, function(err) {
        callback(err);
      });
    },
    function (err) {
      if (err) {
        console.error(err); //don't return as we still need to release the connection
      }
      connection.release(function(err) {
        if (err) {
          console.error(err);
        }
      });
    }
  );
}

module.exports.releaseConnection = releaseConnection;

function simpleExecute(sql, bindParams, options) {
  options.maxRows = 100000;
  return new Promise(function(resolve, reject) {
    getConnection()
      .then(function(connection){
        execute(sql, bindParams, options, connection)
          .then(function(results) {
            resolve(results);
            process.nextTick(function() {
              releaseConnection(connection);
            });
          })
          .catch(function(err) {
            if (err) {
              return reject(err);
            }
            process.nextTick(function() {
              releaseConnection(connection);
            });
          });
      })
      .catch(function(err) {
        reject(err);
      });
  });
}

module.exports.simpleExecute = simpleExecute;
```

**Comment by c011v** [comment]
And here's full example 

```
var database = require('../../database.js');
var Q = require('q');

exports.insert_detail= function (req, res, next) {
    var row_data = req.body
    //########################################
    //      row_data  like this table
    //----------------------------------------
    //       NAME          | Location
    //       Tom           | USA
    //       Tina          | UK
    //       Kawu          | JP
    //       LiLi          | Taiwan
    //       Lee Min-Hwi   | Korea
    //---------------------------------------
    //########################################
    var defer = Q.defer();
    var qDBinsertArr = [];
    for (var i = 0; i < row_data.length; i++) {
        var sql = "insert into memeber (NO,NAME,CITY) values (member_SEQ.nextVal," + row_data[i].Name + "," + row_data[i].location + ")";
        var tempPromise = {};
        (function () {
            tempPromise = database.simpleExecute(sql, [], { autoCommit: true });
            qDBinsertArr.push(tempPromise);
        })();
    }
    Q.all(qDBinsertArr).then(function (results) {
        console.log('Q.all Process Success');
    })
    .catch(function (err) {
        console.log("in qDBinsertArr ERROR: ", err);
        next("Insert Detail Error,Error Message:" + err);
    });

}
```

**Comment by cjbj** [comment]
>  poolMax: 100000,

This is way, way too huge unless you have some super system.

Reduce the size.  Do some debugging with your code to make sure that connections are being released back to the pool.  

Check the pool stats with [`_logStats()`](https://blogs.oracle.com/opal/entry/node_oracledb_1_7_0)

I expect you are flooding the system with too many connections and the DB can't cope with the number of connections you are opening.  You should let the pool queue handle queueing of connections and make sure you have resources (at the DB, and with [UV_THREADPOOL_SIZE](https://github.com/oracle/node-oracledb/blob/v1.10.0/doc/api.md#number-of-threads))

Unless you have a unique business reason to commit each row, you almost certainly want to commit only once, at the very end of inserting.  You should probably open just one connection and insert all rows using that connection, then commit at the end.

In general, if your architecture is what you need, then try and reduce your code to a simple testcase that gives the same error.  At the moment you are expecting us to to that for you.  But since we don't know your system as well as you, this isn't the best way to get the problem resolved.

Also 

> options.maxRows = 100000;

is not going to be very efficient since it means queries will allocate huge buffers, even if they only return one row.  Try using a ResultSet.

Finally, [Sagie's advice](https://github.com/oracle/node-oracledb/issues/478#issuecomment-232707225) shouldn't be ignored since he's already solved your problem.

**Comment by c011v** [comment]
@cjbj  thank your advice. 

I adjusted maxRows  and poolMax .Then the error was gone

Please accept my most cordial thanks for your timely help
```
poolMax: 100, // 
options.maxRows = 100;
```
