### ISSUE TITLE
Getting errors in Electron app

### ISSUE THREAD

**Issue by tulinn** [oracle/node-oracledb#479]
Hi,

I am running Windows 7 with oracledb v1.10.0, electron-prebuilt v1.2.2, electron-rebuild v1.1.5 and node v0.12.7 (and npm v2.11.3). As suggested by @irfannuri I used "node_modules/.bin/electron-rebuild -f -w oracledb" command but got this error:

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@0.12.7 | win32 | x64
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.2.2/iojs-v1.2.2.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: certificate not trusted
gyp ERR! stack at Error (native)
gyp ERR! stack at TLSSocket. (_tls_wrap.js:929:36)
gyp ERR! stack at TLSSocket.emit (events.js:104:17)
gyp ERR! stack at TLSSocket._finishInit (_tls_wrap.js:460:8)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "H:\electron-quick-start\node_modules\electron-rebuild\node_modules\npm\node_modules\node
-gyp\bin\node-gyp.js" "install" "--target=1.2.2" "--arch=x64" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.co
m/atom-shell/dist"
gyp ERR! cwd H:\electron-quick-start
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Process exited with code: 1
Error: Process exited with code: 1
at ChildProcess. (H:\electron-quick-start\node_modules\electron-rebuild\lib\spawn.js:55:26)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

I use Windows PowerShell as Administrator. Please advise on why I might be getting this error. Thank you!

**Comment by dmcghan** [comment]
@tulinn As mentioned in https://github.com/oracle/node-oracledb/issues/449, this is a certificate error - it's not related the driver.

Are you testing this at work? Try testing it on a personal windows machine at home:
https://github.com/electron/electron/issues/1529

**Comment by tulinn** [comment]
Thank you @dmcghan the issue you referred me to solved my problem! As suggested by @mattcollier I called the following commands and it worked:

PS H:\electron-app> cd node_modules\oracledb
PS H:\electron-app\node_modules\oracledb> node-gyp rebuild --target=1.2.8 --arch=x64 --target_platform=win --dist-url=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist --msvs_version=2013
PS H:\electron-app\node_modules\oracledb> cd ..\..
