### ISSUE TITLE
not possible to have two pool connections

### ISSUE THREAD

**Issue by behroozshafiabadi** [oracle/node-oracledb#487]
i use node oracledb 1.7.0 and my projects need to be connected to two database
when i want to create seccond pool i get undefined result 
here my code : 
`function createPool() {
    if (!Config) {
        console.log("oracledb config dose not exist...please set it");
        return;
    }

    for (var key in Config) {
        poolWrapper(key, function (key, pooled) {
            pool[key] = pooled;
            oracledb.autoCommit = true;
            oracledb.fetchAsString = [oracledb.DATE, oracledb.NUMBER];
            console.log('----------->>>', pool);
        })
    }

    function poolWrapper(key, callback) {
        oracledb.createPool(
            Config[key],
            function (err, pooled) {
                if (err) {
                }
                callback(key, pooled);
            }
        );
    }` 

the console result is : 

----------->>> { database1:
   { stmtCacheSize: 30,
     connectionsInUse: 0,
     connectionsOpen: 1,
     poolTimeout: 120,
     poolIncrement: 2,
     poolMin: 1,
     poolMax: 4,
     queueRequests: true,
     queueTimeout: 60000,
     getConnection: [Function: getConnection],
     terminate: [Function: terminate] },
  database2: undefined }

why database2 got undefined ???

**Comment by sagiegurari** [comment]
any reason you ignore the error of the getPool and continue as if all is well?

**Comment by behroozshafiabadi** [comment]
@sagiegurari  : tnx for your remind .i forget to note that
when print it get error :  [Error: ORA-12170: TNS:Connect timeout occurred
]

**Comment by sagiegurari** [comment]
my guess that it is not a second pool limitation.
try to create a pool from the second key first, my guess those settings/db is the issue.

**Comment by dmcghan** [comment]
@behroozshafiabadi You might be interested in [this proposed/future API for working with pools.](https://github.com/oracle/node-oracledb/issues/484) It's built on top of the current APIs (like oracledb.createPool) and supports multiple pools so I know this can work fine.

Perhaps the issue is in the Config object. Could you show us what Config looks like, minus any sensitive information?

**Comment by behroozshafiabadi** [comment]
@dmcghan  tnx a lot problem solved :)
but another terrible bug comes out...can anyone help ?
my max pool size is 4,but after working few with my site...that's grow up to 50
this is my config : 
`{
         connectString: 'IP:port/orcl',    
        user: ***,
        password: ***,
        externalAuth: false,
        poolMax: 4,
        poolMin: 1,
        poolIncrement: 2,
        poolTimeout: 120,
        queueRequests: true
    }` 

what's your issue ?

**Comment by cjbj** [comment]
How do you know it grows to 50?

(Are you sure you are not creating 50 pools?)

**Comment by sagiegurari** [comment]
try to use the following pool property to see how many actual connections open (per pool of course):
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#proppoolconnectionsopen
````js
pool.connectionsOpen
````

**Comment by behroozshafiabadi** [comment]
@cjbj i use oracle system admin query.
`SELECT s.USERNAME,
s.MACHINE,
s.OSUSER,
-- s.sid,
-- s.serial#,
s.PROGRAM,
s.STATUS,
SUM(A.VALUE) AS connections
FROM V$SESSTAT A,
V$STATNAME b,
V$SESSION s
WHERE A.STATISTIC# = b.STATISTIC#
AND s.SID = A.SID
AND b.NAME = 'opened cursors current'
AND s.PROGRAM NOT LIKE '%ORACLE%'
AND s.OSUSER LIKE '%my pc name%'
AND s.PROGRAM not like 'SQL Developer'
GROUP BY s.USERNAME,
s.MACHINE,
s.OSUSER,
s.PROGRAM,
s.STATUS
ORDER BY connections DESC,
s.OSUSER;`

**Comment by behroozshafiabadi** [comment]
@sagiegurari this property usually return 1

**Comment by cjbj** [comment]
It does sound like a code issue.  Since you have access to the code, try debugging and checking how many pools are being created, and when connections are being created.  Also check the pool stats with https://github.com/oracle/node-oracledb/blob/v1.10.1/doc/api.md#connpoolmonitor

You may also be interested in using `select unique(sid), client_driver from v$session_connect_info;`

**Comment by behroozshafiabadi** [comment]
@cjbj is node clustering affect that an multiple my pool ?

**Comment by cjbj** [comment]
Are you using https://nodejs.org/api/cluster.html ?

Node-oracledb connection pools are not shared across processes (and `cluster` documents there is 'no shared state between the workers') so each process will create its own connection pool(s) of whatever configuration you set.

**Comment by behroozshafiabadi** [comment]
@cjbj tank to your navigate
but in 2 cpu num the connection should not rise to 50
i will check code and report you then close this conversation

**Comment by behroozshafiabadi** [comment]
this is my code structure of implement get connection,execute it and release it
get connection from pool : 

`function openConn(config) {
    var deferred = q.defer();
    if (!config) {
        deferred.reject('Connection error: No config!');
    }
    else {
        pool[config].getConnection(function (err, connection) {
            if (err) {
                deferred.reject(err);
            }
            else {
                deferred.resolve(connection);
            }
        })
    }
    return deferred.promise;
}` 

execute query :

`function queryResult(connection, query, passToCallback) {
    var resultArray = [];
    var deferred = q.defer();
    var genericQueryHandler = function (err, results) {
        if (err) {
            console.log('Query:', query, err);
            if (passToCallback) {
                deferred.reject(err, passToCallback);
            }
            else {
                deferred.reject(err);
            }
        }
        else {
            if (passToCallback) {
                deferred.resolve({data: results, passToCallback: passToCallback}); //TODO : we need changes!
            }
            else {
                getResult(results.resultSet, connection);
            }
        }
    };
    connection.execute(query, {}, {
        autoCommit: true,
        outFormat: oracledb.OBJECT,
        resultSet: true,
        maxRows: 100
    }, genericQueryHandler); // no bind Param and options in this use case

    function getResult(result, connection) {
        result.getRow(function (err, row) {                       // get one row
            if (err) {
                console.log("ERROR IN FETCHING ROWS");
            } else if (!row) {
                deferred.resolve(resultArray);
            }
            else {
                resultArray.push(row);
                getResult(result, connection);
            }
        })
    }

    return deferred.promise;
}` 


and then this is for release :

`function closeConn(connection) {
    var deferred = q.defer();
    if (!oracledb.autoCommit) {
        rollback(connection)
            .then(function () {
                close();
            })
            .fail(function (error) {
                close();
            });
    }
    else {
        close();
    }
    function close() {
        connection.release(function (err, result) {
            if (err) {
                console.log('Error while closing the connection!', err);
                deferred.reject(err);
            }
            else {
                console.log('connection close successfully');
//            console.log("Closed successfully!");
                deferred.resolve();
            }
        });
    }

    return deferred.promise;
}` 


before i use node JDBC and my whole project use this structure...so i have to implement oracle db in this way like pas wrapper for jdbc( so this seems distructive ) 

in that way calling this functions similar this :
`dbi.openConn(databasename)
        .then(function (connection) {
            dbi.queryResult(connection, query)
                .then(function (result) {
                    dbi.closeConn(connection);
                })
                .fail(function (error) {
                    dbi.closeConn(connection);
                })
        })
        .fail(function (error) {
            
        });`


is in this way implementation causing connection increasing ???

**Comment by behroozshafiabadi** [comment]
after couple of time finally i attentive to stmtCashSize and set it to 0;
i haven't any idea to performance affect but it work!

**Comment by cjbj** [comment]
@behroozshafiabadi I'm curious. Why did you change the statement cache size?  What problem were you solving?
