### ISSUE TITLE
install oracledb for nodejs on centos 

### ISSUE THREAD

**Issue by Jiafan** [oracle/node-oracledb#488]
# environment
* centos 6.8
* node 6.3.0
* npm 3.10.3

# environment variables
export OCI_HOME=/usr/local/oracle_instantclient
export OCI_LIB_DIR=$OCI_HOME
export OCI_INC_DIR=/usr/local/oracle_instantclient/sdk/include/
export OCI_INCLUDE_DIR=/usr/local/oracle_instantclient/sdk/include/
export OCI_VERSION=12
export NLS_LANG=AMERICAN_AMERICA.UTF8

# error message
*  `node-gyp rebuild`
https://gist.github.com/Jiafan/8e54499a72ddfd5a71cf0583d55c7002

**Comment by cjbj** [comment]
My first thought is 'old compiler'.  See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#prerequisites

**Comment by Jiafan** [comment]
thank you  for your response

my compiler version like this :
gcc version: 4.47
python version: 2.6.6

**Comment by Jiafan** [comment]
Excue me @cjbj ,

I get the same error after updating gcc to 4.8 and python to 2.7

my software environment :
1.  system 6.7
2. gcc 4.8 
3. python 2.7
4. node 6.3 

my instantclient-basic-linux.x64-12.1.0.2.0.zip and instantclient-sdk-linux.x64-12.1.0.2.0.zip was unziped into 
/usr/local/instantclient/

and the environment variables was set:
export OCI_HOME=/usr/local/instantclient
export OCI_LIB_DIR=$OCI_HOME
export OCI_INCLUDE_DIR=$OCI_HOME/sdk/include
export OCI_VERSION=12
export NLS_LANG=AMERICAN_AMERICA.UTF8

Could you give me some advices ?

Thank you  first

**Comment by cjbj** [comment]
You are setting environment variables for the obsolete Node driver https://github.com/joeferner/node-oracle.  Check the instructions for node-oracledb https://github.com/oracle/node-oracledb/blob/master/INSTALL.md and set the expected environment variables.  Sorry I didn't spot that earlier - it's been hectic.

**Comment by Jiafan** [comment]
There is nothing happend  after runing command 'yum install scl-utils devtoolset-3'  successfully as tips here 'https://blogs.oracle.com/opal/entry/getting_a_c_11_compatible' said.

My gcc version is still 4.4.7 and python version still to be 2.6.6.

What should I do next?

**Comment by sagiegurari** [comment]
checkout following blog, thats what i did and it worked for me on centos.
http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/

basically 3 commands:
````sh
sudo wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
sudo yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
scl enable devtoolset-2 bash
````
I guess "-3" is newer than mine but regardless both work.
When I run a build script via jenkins, I do it with following prefix:
````sh
exec scl enable devtoolset-2 ./build.sh
````
where build.sh is my build script that does among other things: npm install
The blog also explains that you can put it in the bashrc so you won't have to do it each time, but I didn't want to do that.

**Comment by Jiafan** [comment]
Thank you very much @sagiegurari  .

**Comment by Jiafan** [comment]
Thank you very much @sagiegurari  .

the command 'scl enable devtoolset-3 bash' worked .

**Comment by Jiafan** [comment]
Thank you @cjbj

**Comment by cjbj** [comment]
@thanks @sagiegurari 

I should put in a shout-out to Oracle Linux, which is free (with optional support) http://www.oracle.com/technetwork/server-storage/linux/downloads/default-150441.html Also see http://yum.oracle.com/
