### ISSUE TITLE
Select on table include CLOB Column

### ISSUE THREAD

**Issue by behroozshafiabadi** [oracle/node-oracledb#489]
Hi
i want to execute select query on table that include CLOB rows....what is normal way ?
is that using streaming ?
is there any way to use traditional execute and give back CLOB as string ?

**Comment by cjbj** [comment]
I'm glad you asked.  Check the [manual](https://github.com/oracle/node-oracledb/blob/master/doc/api.md) and the https://github.com/oracle/node-oracledb/tree/master/examples.  There is no native fetch-as-string support for CLOBs.

**Comment by behroozshafiabadi** [comment]
@cjbj  i read that...but is that mean when i haw about 99 rows,i most set 99 stream reader for my rows ?
seems wierd!

**Comment by sagiegurari** [comment]
@behroozshafiabadi you can use this without opening a single stream:
https://github.com/sagiegurari/simple-oracledb#usage-query
I already wrote this to you in a different issue you comment on.

````js
//do this once on boot of app
var oracledb = require('oracledb');
var SimpleOracleDB = require('simple-oracledb');
SimpleOracleDB.extend(oracledb);

//from now you have more options on the pool and connection object
//pool run for example gives you a connection, no need to release it afterwards, just call the callback
pool.run(function (connection, callback) {
  //run some query and the output will be available in the 'run' callback, no need to open streams to get LOB data, it will be converted to string/buffer depending if it is a CLOB or BLOB
  connection.query('SELECT department_id, department_name FROM departments WHERE manager_id < :id', [110], callback);
}, function onActionDone(error, result) {
  //do something with the result/error
});

//or you can do the simple getConnection
oracledb.getConnection(function onConnection(error, connection) {
    if (error) {
        //handle error
    } else {
        //work with new capabilities (or original oracledb capabilities)
        //again with query you don't need to stream LOBs, you get them as objects
        connection.query('SELECT department_id, department_name FROM departments WHERE manager_id < :id', [110], function onResults(error, results) {
          if (error) {
             //handle error...
          } else {
             //print the 4th row DEPARTMENT_ID column value
            console.log(results[3].DEPARTMENT_ID);
          }
       });
    }
});
````

**Comment by behroozshafiabadi** [comment]
@sagiegurari you wrote greate wrraper.but i cant change my code and replcae it again with wrapper.
i have to read your code to know what is inside your query command that avoid oppening multi stream reader

**Comment by sagiegurari** [comment]
keep in mind that the new query function has same signature as execute so it is not a big change. just function name. to support lob, just add another option in the provided options object.
having stream code everywhere is a nightmare which is why I wrote that lib in the first place.

**Comment by behroozshafiabadi** [comment]
@sagiegurari thanks to your great job....very usful module for me

**Comment by sagiegurari** [comment]
:+1:  enjoy

**Comment by cjbj** [comment]
What size LOBS are you using?  Allocating memory to hold them (instead of streaming) would be something to evaluate.

**Comment by sagiegurari** [comment]
@cjbj that is why the oracledb api makes sense and is the correct way to use LOB, but just not comfortable for use cases where LOBs are used but they are not really big.

We use CLOBs a lot to store JSONs. They aren't big, but they are bigger than 4k so had to use CLOB.
Anyway I parse those strings to JS objects so it is in the memory and I preferred to have a simpler api so I won't have to deal with it everywhere.
Moreover since nodejs likes JSONs so much and thats my number 1 use case, even that I wrapped with a connection.queryJSON function (https://github.com/sagiegurari/simple-oracledb#usage-queryJSON)

So oracledb has a correct api, but can't take away the need for a strait forward simple api.
