### ISSUE TITLE
Compiler/Link error while installing node-oracledb

### ISSUE THREAD

**Issue by sgarggit** [oracle/node-oracledb#49]
Hi ,
 I am getting following error while installing node-oracledb  on Windows7 machine on 32 bit platform.
env. details
node.js version is 0.10.0 (x86)
Oracle client version 11.2.0 (32 bit)
Python version is 2.7 (32 bit)
MSVC version is 2010  (32 bit)

 Creating library C:\Users\sgarg\AppData\Roaming\npm\node_modules\oracledb\build\Release\oracledb.lib and object C:\Users\sgarg\AppData\Roaming\npm\nodemodules\oracledb\build\Release\oracledb.exp
 njsConnection.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class v8::Handle __cdecl node::MakeCallback(class v8::Handle,class v8::Handle,int,class v8::Handl
 e * const)" (__imp?MakeCallback@node@@YA?AV?$Handle@VValue@v8
 @@@v8@@V?$Handle@VObject@v8@@@3@V?$Handle@VFunction@v8@@@3@HQAV23@@Z) [C:\Users
 \sgarg\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
 C:\Users\sgarg\AppData\Roaming\npm\node_modules\oracledb\build\Release\oracledb
 .node : fatal error LNK1120: 1 unresolved externals [C:\Users\sgarg\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
 gyp ERR! build error

Any suggestions are appreciated.

**Comment by cjbj** [comment]
@sgarggit Can you confirm you are really using Node.js 0.10.0?  That seems pretty old.  We have been testing with 0.10.35 and 0.10.36.

**Comment by sgarggit** [comment]
yes, I am using 0.10.0 as package.json has specified node engine version as 0.10.
I also tried with 0.10.35 but no luck. still facing the same issue.

**Comment by sgarggit** [comment]
Thanks for suggestions. Using Node 0.10.35 on 64 bit worked fine.
