### ISSUE TITLE
I can't install/compile the oracledb module on Windows 7 x64

### ISSUE THREAD

**Issue by antonio-castellon** [oracle/node-oracledb#491]
I following the instructions to install the oracledb module and I;m stuck.
Here we have the screenshot about the execution of the installation command.

![image](https://cloud.githubusercontent.com/assets/3425672/17512422/0c3d72d0-5e28-11e6-99e3-1bf7d1bcc2d0.png)

OS: Windows 7 x64
Nodejs : 4.4.7 (x64)
Oracle Client 12.1
Compiler VS 2013() 12.0.40629.0) + (.NET 4.6.01055)

Any ideas? I checked all the guide and I have no idea what's happen :(

Thanks in advance for your response,
Antonio

**Comment by sagiegurari** [comment]
My hunch is that your python installation is the issue.
Can you try to reinstall python and make sure it is python 2.7 (not 3.x)?

**Comment by antonio-castellon** [comment]
it will be strange because my python version shows me: Python 2.7.8, 
In all cases I tested your approach installing the last Python 2.7.12 and I have the same issue. :(

**Comment by antonio-castellon** [comment]
Yeah! I found the error. the python was installed from the Administrator Console and then only the admin has correct access to the python environment, Thanks for all!!
