### ISSUE TITLE
External authentication no longer working

### ISSUE THREAD

**Issue by dvtylr** [oracle/node-oracledb#492]
External authentication using Kerberos results in a "ORA-24429: External authentication is not supported in this mode." error.  External authentication is working fine under version 1.9.3.  The problem occurs with the latest release.

node-oracledb, 1.10.1
Node version 0.10.36.
Oracle Instant client 11.2.0.4
OS RHEL 2.6.32-504.3.3.el6.x86_64

**Comment by cjbj** [comment]
Thanks for reporting it.  It is a known issue and we have a fix; we just need to get a release out.

**Comment by cjbj** [comment]
Try node-oracledb 1.11.  Sorry for the breakage.

**Comment by Lodgebarn** [comment]
I have tried node-oracledb 1.11 and Oracle Wallet certainly does not work. It does work fine with 1.8.0. Any chance of checking this out please.

**Comment by pvenkatraman** [comment]
Just checked with 1.11 and externalAuth is working good.  Can you please provide us a test case/scenario where it is not working so that we can investigate.  Thanks.

**Comment by Lodgebarn** [comment]
This is our scenario. 64 bit windows installation , a nodejs service accessing a local Oracle database on Windows. We are using Oracle Wallet for the authorisation in a file store. I can connect with SQL Developer using the wallet, With the 1.11 binaries the pool we create does not have externalAuth support and gets user/password errors when creating connections. If I replace 1.11 with 1.9.3 binaries everything works fine with no application changes. I can upload files if you need further information.

**Comment by Lodgebarn** [comment]
I just did a further test after a controlled rebuild of the 1.11 binaries for Windows 64 and it is now working OK so panic over. Thanks very much for your quick response.

**Comment by cjbj** [comment]
We'll still look into it to check what can be improved.
