### ISSUE TITLE
Oracledb 1.10, gcc C++11, Node 4, RHEL 6, npm install failing

### ISSUE THREAD

**Issue by kathy-ems** [oracle/node-oracledb#494]
I'm having problems installing oracledb via npm on a new server.

Environment:
- npm oracledb (tried 1.18 and 1.10)
- Node 4 (also tried version 0.10.36)
- Oracle instant client 12 manually installed both the basic and dev
- RHEL 6 server that has been manually upgraded to C++ 11 per these instructions https://blogs.oracle.com/opal/entry/getting_a_c_11_compatible

Here is where the first error shows up during the `npm install --verbose oracledb` command

```
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/gne/home/wwwdata/load_testing/Foundry/dataserver/clobber/node_modules/oracledb/build'
  g++ '-DNODE_GYP_MODULE_NAME=oracledb' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/gne/home/wwwdata/.node-gyp/4.4.7/include/node -I/gne/home/wwwdata/.node-gyp/4.4.7/src -I/gne/home/wwwdata/.node-gyp/4.4.7/deps/uv/include -I/gne/home/wwwdata/.node-gyp/4.4.7/deps/v8/include -I/usr/include/oracle/12.1/client64 -I../src/dpi/src -I../src/dpi/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -fexceptions -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -fexceptions -MMD -MF ./Release/.deps/Release/obj.target/oracledb/src/njs/src/njsOracle.o.d.raw   -c -o Release/obj.target/oracledb/src/njs/src/njsOracle.o ../src/njs/src/njsOracle.cpp
In file included from ../src/njs/src/njsOracle.h:56,
                 from ../src/njs/src/njsOracle.cpp:53:
../node_modules/nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /gne/home/wwwdata/.node-gyp/4.4.7/include/node/node.h:42,
                 from ../src/njs/src/njsOracle.cpp:51:
/gne/home/wwwdata/.node-gyp/4.4.7/include/node/v8.h:336: error: expected unqualified-id before ‘using’
```

It says "error: #error This version of node/NAN/v8 requires a C++11 compiler". Here is the output of the `gcc -v`. Is C++ 11 not installed?
```
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
```
The full outputs of the error `npm install --verbose oracledb`, env var, $PATH and the `gcc -v` are available in this gist:
https://gist.github.com/kathy-ems/124eb70eb2f8655efceba64b498b675f

**Comment by sagiegurari** [comment]
try looking at my answer in issue #488 
specifically: https://github.com/oracle/node-oracledb/issues/488#issuecomment-238148826

**Comment by kathy-ems** [comment]
Thank you @sagiegurari This was helpful!

The sys admin said all the gcc and C++ were installed already. The piece I was missing was to open the bash shell using by executing `scl enable devtoolset-3 bash`. Then run `npm install oracledb` inside the bash prompt.

**Comment by cjbj** [comment]
For the record, also see https://blogs.oracle.com/opal/entry/getting_a_c_11_compatible which covered getting the updated compiler for Oracle Linux 6 (and Red Hat Linux 6)
