### ISSUE TITLE
Question about end-to-end example – why the event loop blocking?

### ISSUE THREAD

**Issue by lukealbao** [oracle/node-oracledb#496]
From [the end-to-end example](https://github.com/oracle/node-oracledb/blob/db5950f1cf17d6c7f786de0dd711a1291e870321/examples/endtoend.js#L64-L69)

```javascript
function sleep(t) {
  var start = new Date().getTime();
  while(new Date().getTime() < start + t) {
    // empty
  }
}

// elsewhere, client code calls this....
sleep(10000);
doRelease(connection);
```

I was surprised to find this code in the example. I believe and hope I'm missing something, because it looks like code written by someone who does not understand the Node event loop. 

Is there a reason this could not have been done with a `setTimeout`? The while loop blocks all execution everywhere in the process for ten seconds, but a timeout would not. 

My company is currently beginning support for Oracle, and I find this code a little concerning, whether as a common (but serious) rookie mistake or as a sign of private implementation constraints. 

Thanks for any clarification you can provide. I'm hoping we can rely on this in production.

**Comment by dmcghan** [comment]
@lukealbao At first glance, it appears that this should have been implemented with setTimeout. As a one off example, there'd be nothing else using the event loop anyway - so it's not too big a deal.

I'll review and update accordingly. Thanks!

**Comment by lukealbao** [comment]
Thanks – I understand that there's nothing else going on in the example, I just think of it as one of the most fundamental gotchas of Node, so a synchronous sleep function in a professional Node library is a bit like seeing a unicorn with three legs. It seemed like it would be bad due diligence on my part (as a person responsible for evaluating the library) not to ask about it. Thanks again.

**Comment by dmcghan** [comment]
@lukealbao lol, I hear you. My testing found setTimeout worked fine so we'll update in the next release. I searched other tests and examples and didn't find that anywhere else.

Thanks for the heads up and please let us know if you spot anything else in the future.
