### ISSUE TITLE
connection.cancel?

### ISSUE THREAD

**Issue by colinrcummings** [oracle/node-oracledb#498]
Looking for a way to cancel a database call in progress in the event a request is canceled. I've tried calling connection.close, but get an error ("NJS-032: connection cannot be released because a database call is in progress"). In tedious, for example, you can call a cancel method to kill the database call in progress, then the call the close method to close the connection. Is there a way to accomplish the same in oracledb?

**Comment by dmcghan** [comment]
Have you tried `connection.break()`?

https://github.com/oracle/node-oracledb/blob/master/doc/api.md#break

**Comment by colinrcummings** [comment]
There it is... Perused the documentation, but evidently not closely enough. Thank you!
