### ISSUE TITLE
windows 10, and Visual Studio 2015 (14.0) install issues

### ISSUE THREAD

**Issue by ainthek** [oracle/node-oracledb#499]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install th
e required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\workspaces\init\nod
e_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe

**Comment by cjbj** [comment]
Installation issues are annoying as always. Best advice is to Review the install instructions.  Read other posts here like https://github.com/oracle/node-oracledb/issues/483 which has some good info.

**Comment by bchr02** [comment]
@ainthek did you try @spoggie's [suggestion](https://github.com/felixrieseberg/windows-build-tools/issues/9#issuecomment-244793165) to ```npm config set msvs_version 2015```.

**Comment by cjbj** [comment]
Closing due to lack of feedback.
