### ISSUE TITLE
How to use TCPS protocol with setting explicitly trustStore

### ISSUE THREAD

**Issue by prabhat2486** [oracle/node-oracledb#504]
Hi,

I could make connection using java as below:

System.setProperty("javax.net.ssl.trustStore", "D://myTrustStoreTestCA");
 System.setProperty("javax.net.ssl.trustStorePassword", "XXXXXXXXXX");
connection = DriverManager.getConnection(
                 "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=localhost(PORT=15444))(CONNECT_DATA=(SERVICE_NAME=BPB2U)))",
                                  "XXXXXX", "XXXXXXX");

How this could be achieved using node-oracle module. To more specifically, how could we set **truststore**, **truststore password** and **tcps** protocol while making connection using oracledb?

**Comment by cjbj** [comment]
This is all handled by Oracle Net Services (formerly called SQL*Net) layer, e.g using [wallets](http://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#NETRF257).
