### ISSUE TITLE
Cannot redefine property: getConnection

### ISSUE THREAD

**Issue by rjtgarg90** [oracle/node-oracledb#505]
When I am using oracledb module to establish the connection. I am getting Cannot redefine property: getConnection

Below is the code

oracledb.getConnection(
			{
				user          : "system",
				password      : "testing",
				connectString : "localhost:1521/XE"
			},
			function(err, connection)
			{
				console.log('ERROR_>, ', err, connection);
				if (err) { console.log('error111',err.message);

					console.error(err.message);

					return; }

				connection.execute(
						"SELECT * FROM system.ABC" ,
						  // bind value for :id
						function(err, result)
						{
							if (err) { console.log('I am here agreement3'); console.error(err.message); return; }
							console.log('** result fetched.. rows are **** ', result.rows);
							console.log('***** result',result);
						}

				);
			});

**Comment by rjtgarg90** [comment]
if I insert configurable:true in oracledb.js, it works fine  
below is the snippet
getConnection: {
        value: getConnectionPromisified,
        enumerable: true,
          configurable: true,
        writable: true
      }

**Comment by dmcghan** [comment]
@rjtgarg90 I don't see where you're redefining `getConnection` in the code you supplied. We make the property writable for this very reason and it's known to work in other libraries that do what you're describing, such as simple-oracledb.

**Comment by rjtgarg90** [comment]
oracledb.getConnection(
{
user : "system",
password : "testing",
connectString : "localhost:1521/XE"
},

is the code where I am redefining getConnection
As getConnection is define as defineProperties in oracledb.js so untill I writre configurable:true. I am not able to proceede

**Comment by rjtgarg90** [comment]
Yes I am taking the reference of the below  code mentioned in the oracledb documentation 

var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "hr",
    password      : "welcome",
    connectString : "localhost/XE"
  },
  function(err, connection)
  {
    if (err) { console.error(err.message); return; }

    connection.execute(
      "SELECT department_id, department_name " +
        "FROM departments " +
        "WHERE manager_id < :id",
      [110],  // bind value for :id
      function(err, result)
      {
        if (err) { console.error(err.message); return; }
        console.log(result.rows);
      });
  });

In a similar way in my api I have passed my parameters in getConnection

**Comment by dmcghan** [comment]
Please provide a reproducible test case that demonstrates the issue you are experiencing.

**Comment by amerishk** [comment]
Hi Dan,

When I am using "node ." to start a server, everything works fine. But, when I use "slc run" the same code gives me an error as mentioned above "Cannot redefine property: getConnection" 

Can you please share your inputs about the reason for the error? 

_Another point to note:_ This is happening when I make a first request to the server i.e. above mentioned error comes when server gets the first request. But, on the subsequent request all works fine. This behavior is bit weird. 

Please suggest.

The Code is very straightforward where we used the example code (from github of node-oracle) and used SLC RUN to start the server instance instead of "NODE ."

**Comment by dmcghan** [comment]
@amerishk I don't have `slc` and don't see an easy way to get it. Have you tried reaching out to StrongLoop for support?

**Comment by amerishk** [comment]
Thanks Dan, but as mentioned, by rjtgarg90, if we add "configurable: true" to the getConnection property of Oracledb instance (in . SLC RUN works fine along with "node ."

Should not we add that so that configuration: true? Please share your view.

**Comment by cjbj** [comment]
@amerishk please work first with StrongLoop as @dmcghan suggested.
