### ISSUE TITLE
Server is offline,npm cannot be used,how to install?

### ISSUE THREAD

**Issue by asdw741111** [oracle/node-oracledb#506]
The server is seperate with Internet,"npm" cmd cannot be used.
Is there some way to install oracledb?
System is Centos.

**Comment by sagiegurari** [comment]
you need an internal npm registry like sinopia so your servers that have no access to the web can go to that internal registry to get the npm dependencies.
however the server that runs that registry must have web access.

**Comment by cjbj** [comment]
Or do some semi-hack and copy installed modules from a machine that does have access to one that doesn't have acess.  We document this for Windows but it should be true for other operating systems.  Care and testing will be needed.

**Comment by bchr02** [comment]
npm install pathToLocalCopyOfOracledb
