### ISSUE TITLE
Can not install node-oracledb on Ubuntu 14.04

### ISSUE THREAD

**Issue by yelichi** [oracle/node-oracledb#507]
#### Answer the following questions:

1. What error(s) you are seeing?

    `gyp ERR! build error`
    `gyp ERR! stack Error: 'make' failed with exit code: 2`
    `gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)`
    `gyp ERR! stack     at emitTwo (events.js:106:13)`
    `gyp ERR! stack     at ChildProcess.emit (events.js:191:7)`
    `gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`
    `gyp ERR! System Linux 3.2.0-23-generic`

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
    `var oracledb = require('oracledb'); `
    command to install =>  `npm install oracledb --save`
    Login as Ubuntu

3. What environment variables did you set?  How *exactly* did you set them?
    
    `1) echo $LD_LIBRARY_PATH`
        `/home/ubuntu/tools/instantclient`
    `2) echo $OCI_LIB_DIR`
        `/home/ubuntu/tools/instantclient`
    `3) echo $OCI_INC_DIR`
        `/home/ubuntu/tools/instantclient/sdk/include`

    `export LD_LIBRARY_PATH=/home/ubuntu/tools/instantclient:$LD_LIBRARY_PATH`
    `export OCI_LIB_DIR=/home/ubuntu/tools/instantclient`
    `export OCI_INC_DIR=/home/ubuntu/tools/instantclient/sdk/include`

4. What is your version of Node.js?

    `Nodejs versino v6.2.2`

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
    
    `1) 12.1.0.2.0-1.x86_64, `
    `2) Using unzip to install it`
    `3) Installation path :/home/ubuntu/tools/instantclient`

6. What is your OS and version?

    `Ubuntu 14.04`
    
7. What compiler version did you use?
    
    `npm -v`
    `3.10.8`

Thank you.

**Comment by cjbj** [comment]
The compiler version can be found by running 'gcc --version'

**Comment by yelichi** [comment]
Millon Thanks for your reply. 
My compiler version :
- gcc(Ubuntu/Linaro 4.6.3-1ubuntu5)4.6.3

**Comment by cjbj** [comment]
I believe you need a newer compiler. node-oracledb uses NAN which enforces this (bceause V8 add-ons require it) https://github.com/nodejs/nan/blob/master/nan.h#L42

**Comment by yelichi** [comment]
Thanks for your helping. It works. I can install the oracledb now. I upgrade my gcc to 4.7, then I try to install again. It installed successfully. Thanks a lot.
