### ISSUE TITLE
getpool

### ISSUE THREAD

**Issue by bulentcaglar** [oracle/node-oracledb#509]
version:
node  : v6.5.0
oracledb : 1.11.0

my code is;

oracledb.createPool(
    {
        poolAlias: 'pool1',
        user: 'hr',
        password: 'hr',
        connectString: 'localhost/XE',
        poolMin: 0,
        poolMax: 5,
        poolTimeout: 0
    },
    function (err, pool) {
        if (err) {
            console.log(err);
        }
    }
);

var pool = oracledb.getPool('pool1');

Error: NJS-047: poolAlias "pool1" not found in the connection pool cache

**Comment by cjbj** [comment]
`createPool` is async, so it hasn't completed before you call `getPool`.
