### ISSUE TITLE
Connection error for Oracle Database in RAC

### ISSUE THREAD

**Issue by Raydekk** [oracle/node-oracledb#510]
Hello,

I'm using node-oracledb v1.10.1 with node.js v4.4.7. I have an express.js web service that connects to an Oracle Database 11gR2 Express Edition, gets the necessary credentials from there for a certain oracle database (environment name is a parameter in the web service) and then connects to that specific database.

This works for any oracle database except when the specific database is a RAC. In my case it has two nodes, I try to connect to node no. 1 and I get the following error:

```
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
```
Telnet to the specific database node IP works, so it's not a network issue.

This is the code I use to connect.
```
function getResConn(envName, getConnString, queryString, res, sendRes) {
   oracledb.getConnection(
      {
        user          : dbConfig.envUser,
        password      : dbConfig.envPass,
        connectString : dbConfig.connectString
      },
      function(err, connection) {
        if (err) {
          logger.error(err.message);
          otherError[0].error = err.message;
          res.send(otherError);                        
          return;
        }
        connection.execute(getConnString,
          [envName],
          {outFormat: oracledb.OBJECT}, //autoCommit: true
          function(err, result) {
            if (err) {
              logger.error(err.message);
              otherError[0].error = err.message;
              if (sendRes) res.send(otherError);            
              return;
            }
            oracledb.getConnection(
              {
                user          : result.rows[0].USERNAME,
                password      : result.rows[0].PASSWORD,
                connectString : result.rows[0].CONNSTRING
              },
              function(err, connection) {
                if (err) {
                  logger.error(err.message);
                  otherError[0].error = err.message;
                  if (sendRes) res.send(otherError);            
                  return;
                }
                connection.execute(
                  queryString,
                  {},
                  {maxRows: 10000, outFormat: oracledb.OBJECT}, //autoCommit: true
                  function(err, result) {
                    if (err) {
                      logger.error(err.message);
                      otherError[0].error = err.message;
                      if (sendRes) res.send(otherError);            
                      return;
                    }
                    if (sendRes) res.json(result.rows);
                    doRelease(connection);
                  }); 
              });    
            doRelease(connection);
          }); 
      });
}

function doRelease(connection) {
  connection.release(
    function(err) {
      if (err) {
        logger.error(err.message);
      }
    });
}

```
OS is CentOS 7 for the interrogating machine, and IBM AIX 7 for the interrogated RAC database. Some version info for the RAC:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
PL/SQL Release 11.2.0.3.0 - Production
CORE	11.2.0.3.0	Production
TNS for IBM/AIX RISC System/6000: Version 11.2.0.3.0 - Production
NLSRTL Version 11.2.0.3.0 - Production

Any idea why connecting to a RAC doesn't work?

Thanks,
Raydekk

**Comment by cjbj** [comment]
The error indicates the connection credentials etc reached the DB and, as the message says, that service wasn't known.  Can you see what other RAC users are using for the connect string? Does lsnrctl on a RAC node tell you what service to use?

Also, In general I don't believe telnet is a sufficient check to validate if ports etc are open for Oracle Net.  Try using SQL*Plus.

**Comment by Raydekk** [comment]
Thanks for the help! I tried an sqlplus from my machine and the server and both of them resulted in the same error (ORA-12514). The problem with RAC nodes can be solved by changing the connection string from something like:
```
sqlplus user/pass@ip:port/sid
```
to
```
sqlplus user/pass@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ip)(PORT=port))(CONNECT_DATA=(SID=sid)))
```

**Comment by dmcghan** [comment]
@Raydekk See this section on the doc on connect strings:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-81-connection-strings

Note that the easy connect syntax does not support SIDs, only service names. You could use the example in [8.1.2](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-812-net-service-names-for-connection-strings) (replacing the connect data with the SID) if you can list out all the databases in a tnsnames.ora file and then convert what you fetch in the database to the correct identifier.
