### ISSUE TITLE
Error to install on windows 8.1

### ISSUE THREAD

**Issue by kimvex** [oracle/node-oracledb#511]
Hi I've been trying to install the module in Windows 8.1 but I always get an erro, and install visual basic 2015, I started a project of c ++ and the necessary dependencies were installed, but still npm not let me install the module, shows me this error.

npm install oracledb
npm WARN package.json oracledbp@1.0.0 No description
npm WARN package.json oracledbp@1.0.0 No repository field.
npm WARN package.json oracledbp@1.0.0 No README data

> oracledb@1.11.0 install C:\Users\A-035653\Documents\programacion\Node.js\oracl                                                                                                                                                                                               e\node_modules\oracledb
> node-gyp rebuild

C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb>if                                                                                                                                                                                                not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm                                                                                                                                                                                               \bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else                                                                                                                                                                                                (node "" rebuild )
Los proyectos de esta soluci▒n se van a compilar de uno en uno. Para habilitar l                                                                                                                                                                                               a compilaci▒n en paralelo, agregue el modificador "/m".
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\include\dpiStmt.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\nj                                                                                                                                                                                               s\src\njsResultSet.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle                                                                                                                                                                                               \node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\include\dpiStmt.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\nj                                                                                                                                                                                               s\src\njsConnection.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracl                                                                                                                                                                                               e\node_modules\oracledb\build\oracledb.vcxproj]
  njsMessages.cpp
  njsIntLob.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\include\dpiStmt.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\nj                                                                                                                                                                                               s\src\njsPool.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\node                                                                                                                                                                                               _modules\oracledb\build\oracledb.vcxproj]
  dpiEnv.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiEnvImpl.h(30): fatal error C1083: No se puede abrir el archivo incl                                                                                                                                                                                               uir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dpi                                                                                                                                                                                               \src\dpiEnv.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_m                                                                                                                                                                                               odules\oracledb\build\oracledb.vcxproj]
  dpiEnvImpl.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiEnvImpl.h(30): fatal error C1083: No se puede abrir el archivo incl                                                                                                                                                                                               uir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dpi                                                                                                                                                                                               \src\dpiEnvImpl.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\no                                                                                                                                                                                               de_modules\oracledb\build\oracledb.vcxproj]
  dpiException.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\include\dpiStmt.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\nj                                                                                                                                                                                               s\src\njsOracle.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\no                                                                                                                                                                                               de_modules\oracledb\build\oracledb.vcxproj]
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\include\dpiStmt.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\nj                                                                                                                                                                                               s\src\njsIntLob.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\no                                                                                                                                                                                               de_modules\oracledb\build\oracledb.vcxproj]
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiConnImpl.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dp                                                                                                                                                                                               i\src\dpiConnImpl.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\                                                                                                                                                                                               node_modules\oracledb\build\oracledb.vcxproj]
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiUtils.h(30): fatal error C1083: No se puede abrir el archivo inclui                                                                                                                                                                                               r: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dpi\s                                                                                                                                                                                               rc\dpiDateTimeArrayImpl.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\o                                                                                                                                                                                               racle\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiEnvImpl.h(30): fatal error C1083: No se puede abrir el archivo incl                                                                                                                                                                                               uir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dpi                                                                                                                                                                                               \src\dpiPoolImpl.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\n                                                                                                                                                                                               ode_modules\oracledb\build\oracledb.vcxproj]
  dpiUtils.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\include\dpiStmt.h(30): fatal error C1083: No se puede abrir el archivo inc                                                                                                                                                                                               luir: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dp                                                                                                                                                                                               i\src\dpiStmtImpl.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\                                                                                                                                                                                               node_modules\oracledb\build\oracledb.vcxproj]
  dpiLob.cpp
  dpiCommon.cpp
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiUtils.h(30): fatal error C1083: No se puede abrir el archivo inclui                                                                                                                                                                                               r: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dpi\s                                                                                                                                                                                               rc\dpiLob.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_mod                                                                                                                                                                                               ules\oracledb\build\oracledb.vcxproj]
..\src\dpi\src\dpiCommon.cpp(28): fatal error C1083: No se puede abrir el archiv                                                                                                                                                                                               o incluir: 'oci.h': No such file or directory [C:\Users\A-035653\Documents\progr                                                                                                                                                                                               amacion\Node.js\oracle\node_modules\oracledb\build\oracledb.vcxproj]
  win_delay_load_hook.cc
C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_modules\oracledb\sr                                                                                                                                                                                               c\dpi\src\dpiUtils.h(30): fatal error C1083: No se puede abrir el archivo inclui                                                                                                                                                                                               r: 'oci.h': No such file or directory (compilando archivo de origen ..\src\dpi\s                                                                                                                                                                                               rc\dpiUtils.cpp) [C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_m                                                                                                                                                                                               odules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail                                                                                                                                                                                               ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\                                                                                                                                                                                               npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                                                                                                               s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej                                                                                                                                                                                               s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\A-035653\Documents\programacion\Node.js\oracle\node_module                                                                                                                                                                                               s\oracledb
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                                                                                               node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\A-035653\Documents\programacion\Node.js\oracle\npm-debug.l                                                                                                                                                                                               og

**Comment by nelreina** [comment]
First of all , windows 8 ?? Seriously ? 

I found the best way to use this package on windows is NOT using windows :). 

I always create an linux VM on my machine (You can use [vagrant ](https://www.vagrantup.com/)for this) with [virtualbox](https://www.virtualbox.org/wiki/Downloads) . Install the oracle client.  And expose the port to you localmachine. It is easy you can keep you configuration in in a Source Control. And reuse it on other pc's . 

I have provision mine with [chef_solo ](https://www.chef.io/)(this more then a year ago) but this code I can not share . (The company I work for does not allow me to). 

Hope that this help you

**Comment by kimvex** [comment]
@nelreinaThanks for your answer friend.

If I would not use my windows, but where development work is in c# and exclusive use of libraries for windows is made and for that reason can not install Linux on my machine or try using mono.

I come from a development environment in Linux and the strange truth when programming in node, but the good thing is that finally achieved the module to work.

**Comment by nelreina** [comment]
But I meant create your API application to Oracle Database with linux. And you can still code in C#.

**Comment by cjbj** [comment]
I believe 'finally achieved the module to work.' means this can be closed?

**Comment by Chairez** [comment]
And what was the problem and consecuent fix?
