### ISSUE TITLE
Read a blob and write it on zip format.

### ISSUE THREAD

**Issue by xdzul** [oracle/node-oracledb#512]
Hello,

I am trying to read a blob content and write it on a file for that I am following the example described on the documentation, section  "11. Working with CLOB and BLOB Data". The blob is a zip (I mean I don't need zip it, it is already a zip stored in the oracle db. The file is created and the size of the file created looks good but when I try to unzip it say: 
Caution: Zip file comment truncated.
Error: unable to seek to beginning of central directory.

connection.execute(
  "SELECT c FROM mylobs WHERE id = :id",
  { id: 1 },
  function(err, result)
  {
    if (err) { console.error(err.message); return; }
    if (result.rows.length === 0) { console.log("No results"); return; }

    var lob = result.rows[0][0];
    if (lob === null) { console.log("CLOB was NULL"); return; }

    lob.setEncoding('utf8');  // we want text, not binary output
    lob.on('error', function(err) { console.error(err); });
    lob.on('close', function() {
      connection.close(function(err) { if (err) console.error(err.message); });
    });

    **console.log('Writing to ' + 'C:\\file.zip');** 
    var outStream = fs.createWriteStream('C:\\file.zip');
    outStream.on('error', function(err) { console.error(err); });
    lob.pipe(outStream);
  });

I am wondering if I need an special treat when it is a compressed file. 

Thank you.

**Comment by cjbj** [comment]
If you are dealing with binary data (ie. a BLOB as I would expect a binary file to be stored as) this line looks suspicious:

```
lob.setEncoding('utf8');  // we want text, not binary output
```

Also, have you confirmed using another tools that the ZIP isn't corrupted in the DB?

**Comment by xdzul** [comment]
I commented the line  lob.setEncoding('utf8') and it works perfectly.

Thanks very much Christopher.
