### ISSUE TITLE
Another Connection Pooling Question

### ISSUE THREAD

**Issue by DavidWhit** [oracle/node-oracledb#513]
In this contrived example 

node 6 
oracle db 1.11
oracle version 11.2.3
windows 7 x64

```
var oracledb = require('oracledb');
var config = require('./dbconfig.js');

const poolAttrs = {
    user: config.user,
    password: config.password,
    connectionString:  config.connectionString,
    externalAuth: false,
    stmtCacheSize: 40,
    poolMax: 40,
    poolTimeout: 120
  }

const executeParams = {
    outFormat: oracledb.OBJECT,
    resultSet: true
  }

oracledb.createPool(poolAttrs)
    .then( pool => {
        console.log(pool) // exists here
        pool.getConnection()
            .then( connection => {
                console.log(connection)
                connection.release()
                })
            .catch( err => console.log(`Get Pool Connecton Error: ${err.message}`))
        pool.close() //too soon
    })
    .catch( err => console.log(`Create Pool Error: ${err.message}` ))
```
1. What error(s) you are seeing?
The pool is created but if I try to open a connection via pool.getConnection() yields:
ORA-24416: Invalid session Poolname was specified if I don't close the Pool then Tns adapter error

Perhaps, my knowledge isn't great with promises the way the docs explain to call create pool 
and in another file import oracledb again but how is that if your not within the Promise? 

The closest example I found of something easier to understand is the example you guys did here.
(https://github.com/oracle/node-oracledb/blob/master/examples/webapppromises.js#L106 )

**Comment by dmcghan** [comment]
@DavidWhit The description of the error you specified, ORA-24416, is: An attempt was made to use a Session Pool that does not exist.

Your "contrived" example only accesses the pool after it's been created successfully, so I'm a little confused.

Are you able to write a test case that we can use to reproduce the error you're getting?

> Perhaps, my knowledge isn't great with promises the way the docs explain to call create pool 
and in another file import oracledb again but how is that if your not within the Promise?

Typically, applications are composed of many files. If you're building a web server that will use the driver to service incoming requests, you will definitely want to use a connection pool. The question becomes: when should you create the pool?

I recommend opening the pool prior to opening the web server, so I often have the logic for both in the same file, which is often the "main" file. So in that file, whether done promises or callbacks, step 1 is to create a connection pool and step 2 is to open the web server. Once the web server is open, requests can start coming in and will be routed according to your routing logic.

The latest version of the driver has an internal pool cache. If you're only using one pool, it will be the default, which has [a nice shortcut](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connpoolcache) for getting a connection (via `oracledb.getConnection`). Typically, files that contain models or similar logic (database calls) will `require` in the base class and make a call to `oracledb.getConnection`. The connection would then come from the default pool that was created in the "main" file.

Does that help?

**Comment by DavidWhit** [comment]
Hi Dan, 
  Yeah that helps I ended up just pulling out the code to play in the original post and now I'll wrap the express server so in effect I would create the connection and then if I call other files etc it should be accessible via the shortcut of just, as you said & the docs, oracledb.getConnection().  The linked example and your explanation helped it click.

For the test case I'm not sure... though in rewriting in callbacks I get ora-12560

**Comment by dmcghan** [comment]
@DavidWhit I'm glad that helped. 

Let us know if you do put together a reproducible test case that we can use to investigate the error you're encountering.

**Comment by DavidWhit** [comment]
Hi Dan,
I got it ooooh boy... I had connectionString instead of connectString.... there goes a day...
Though I ran across another one of your articles  and found it a good read and if anyone sees this before I recommend it.
https://jsao.io/2015/03/making-a-wrapper-module-for-the-node-js-driver-for-oracle-database/#comments

**Comment by cjbj** [comment]
You're not the first to do this.  I have a note to consider adding an alias.
