### ISSUE TITLE
error when deploying node-oracledb application using METEOR UP

### ISSUE THREAD

**Issue by hamdiamine** [oracle/node-oracledb#515]
### For general questions:

Error when i try to deploy my node-oracledb appli using METEOR UP
#### Answer the following questions:
1. What error(s) you are seeing?
   x Verifying Deployment: FAILED
   
   -----------------------------------STDERR-----------------------------------
   erm"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node npm-rebuild.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs meteor-dev-bundle
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls meteor-dev-bundle
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!     /bundle/bundle/programs/server/npm-debug.log
   
   => Redeploying previous version of the app
   
   -----------------------------------STDOUT-----------------------------------
   
   To see more logs type 'mup logs --tail=50'
   ---
2. What _exact_ command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
   mup deploy
3. What environment variables did you set?  How _exactly_ did you set them?
     MONGO_URL='mongodb://127.0.0.1:27017/portail'
     JAVA_HOME=/opt/jdk1.8.0_101
     PATH=$PATH:/opt/jdk1.8.0_101/bin
     PATH=$PATH:/home/hkh/android-sdk-linux/platform-tools
     PATH=$PATH:/home/hkh/android-sdk-linux/tools
     PATH=~/node-v4.5.0-linux-x64/bin:$PATH
     LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
     OCI_LIB_DIR=/opt/oracle/instantclient
     OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
4. What is your version of Node.js?
   4.5.0
5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
   12.1
   unzip
   /opt/oracle/instantclient
6. What is your OS and version?
   LINUX DEBIAN 8 (jessie)
7. What compiler version did you use?

**Comment by cjbj** [comment]
@hamdiamine Did you find a solution?  At a wild guess, you are triggering an 'sudo' and the OCI_*_DIR environment variables are not being passed through.

**Comment by cjbj** [comment]
Closing due to lack of commentary.  There are a few meteor questions open.  Would be good if someone could report back on the current status.
