### ISSUE TITLE
Access Oracle SSL

### ISSUE THREAD

**Issue by cleitonjar** [oracle/node-oracledb#517]
How I configure the parameters for SSL?
1-) In the node-oracledb? How?
2-) Only oracle instant client?

Where to find a documentation?
Best regards

**Comment by cjbj** [comment]
This is all handled by the underlying Oracle Net Service layer.  See http://docs.oracle.com/database/121/NETRF/toc.htm and http://docs.oracle.com/database/121/NETAG/toc.htm

**Comment by dmcghan** [comment]
@cleitonjar Also, see this post for some more info: https://github.com/oracle/node-oracledb/issues/411
