### ISSUE TITLE
Unable to connect to remote RDS server

### ISSUE THREAD

**Issue by lukealbao** [oracle/node-oracledb#518]
## Environment
- OSX 10.10.5
- Node v6.0.0
- node-oracle and clients built and installed according to [OSX instructions](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx)
- Remote server in AWS RDS listening (confirmed TCP connectivity with telnet)

## Current Error

When trying:

```
getConnection({
  user: 'user',
  password: 'password'
  connectString: '<aws-host:port>/<endpoint>'
});
```

I get

```
Error: ORA-21561: OID generation failed

      at Error (native)
```

## Attempted Fix: Register server at loopback

According to every thread I've seen, I should register the host in my /etc/hosts file. When my hosts file looks like this:

```
127.0.0.1 localhost <aws-host>
```

I get this error instead:

```
Error: ORA-12541: TNS:no listener

      at Error (native)
```

Which I assume is because there's no server listening. (I'm not sure why I'd redirect the remote host to the loopback, anyway.)

## Attempted Fix: Register server at ip address

Assuming that I must be missing something, I tried to create an entry in my hosts file with the *actual* publicly routable IP address of the remote server. I still get the `ORA-21561` error.

## Clues

- I know the connectString is correct, because I've gone through the `ORA-12541` and `ORA-12514: TNS:listener does not currently know of service requested in connect descriptor` errors on my way to the current one.

Please help. At a total loss right now. No stack traces or anything.

**Comment by dmcghan** [comment]
@lukealbao I believe the instructions for the /etc/hosts file are for the local host name, not the remote host name.

**Comment by dmcghan** [comment]
@lukealbao Do you have access to the database server? Can you show the status of the listener there (masking anything sensitive)?

```terminal
su - oracle
lsnrctl status
```

Are you using the SID or service same in your connectString. The easy connect syntax only works for service names.

**Comment by lukealbao** [comment]
Ah! Thank you, @dmcghan. Adding an entry for the hostname to the loopback address resolved that specific error. (On to the next errors!)

Is there any easy explanation for why such a finicky-seeming configuration should be required?

**Comment by dmcghan** [comment]
I'm not a DBA, so I'm probably not the best person to ping those questions off of. Perhaps someone else can chime in...

**Comment by cjbj** [comment]
The OID message is because a sufficiently distinguishable set of machine info is needed for unique GUID generation.  We are continuing to bring this up with the Oracle team(s) involved to see if there are alternatives that could be used in a future version of Oracle.
