### ISSUE TITLE
queryStream() using CLOBS

### ISSUE THREAD

**Issue by ktherrien1** [oracle/node-oracledb#519]
Using queryStream() in version 1.8 of oracledb.  Varchars and numbers work great.  Am now trying to return a clob which is over 4000 characters.  does anyone have a code example of how to read the clobs into a variable using the  stream.on('data', function (data) {...  event?  The result set rows are a single clob. Can't use regulate execute() do to memory issues.  The full result set is very large.

**Comment by sagiegurari** [comment]
so look at: https://github.com/sagiegurari/simple-oracledb#usage-query
you can do streaming of resultset like queryStream but LOBs will be converted to string/Buffer instead of streams.

**Comment by dmcghan** [comment]
@ktherrien1 I could put together an example, but I'd like to know a bit more about what you're doing. Would writing the CLOBs to files be sufficient for a demo?

**Comment by ktherrien1** [comment]
Thanks all. The simple-oracle library worked but unfortunately the response time is too slow for what we are building.  Not the software's fault.  It is the verbosity we are storing the data with.

**Comment by dmcghan** [comment]
@ktherrien1 Perhaps a hint would be sufficient... Have you seen the `pause` and `resume` methods of the [Readable Stream](https://nodejs.org/api/stream.html#stream_class_stream_readable) class (QueryStream is an implementation).

**Comment by cjbj** [comment]
@ktherrien1 there is an example that uses the data event in https://github.com/oracle/node-oracledb/blob/master/examples/clobstream2.js
