### ISSUE TITLE
error while installing node-oracledb

### ISSUE THREAD

**Issue by arconale** [oracle/node-oracledb#52]
Hi,

i'm getting the following error while installing node-oracledb on linux 64bits.

[oracle@localhost node-oracledb-master]$ npm install -g
npm ERR! Linux 3.8.13-35.3.3.el7uek.x86_64
npm ERR! argv "/home/oracle/node/node-v0.12.0-linux-x64/bin/node" "/home/oracle/node/node-v0.12.0-linux-x64/bin/npm" "install" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: oracledb@0.4.1
npm ERR! notsup Required: {"node":"=0.10"}
npm ERR! notsup Actual:   {"npm":"2.5.1","node":"0.12.0"}

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oracle/node-oracledb/node-oracledb-master/npm-debug.log

Any suggestions are appreciated.

**Comment by alexsantos** [comment]
For now, you must use node 0.10.x... 0.12 or iojs isn't supported yet.

**Comment by arconale** [comment]
Thank you for responding !
