### ISSUE TITLE
npm install oracledb - osx yosemite

### ISSUE THREAD

**Issue by isabolic** [oracle/node-oracledb#524]
node -v
=> v6.7.0
npm -v
=> 3.10.3

in terminal when I run "npm install oracledb", I get:

489 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
490 error node v6.2.2
491 error npm  v3.9.5
492 error code ELIFECYCLE
493 error oracledb@1.11.0 install: `node-gyp rebuild`
493 error Exit status 1
494 error Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
494 error Make sure you have the latest version of node.js and npm installed.
494 error If you do, this is most likely a problem with the oracledb package,
494 error not with npm itself.
494 error Tell the author that this fails on your system:
494 error     node-gyp rebuild
494 error You can get information on how to open an issue for this project with:
494 error     npm bugs oracledb
494 error Or if that isn't available, you can get their info via:
494 error     npm owner ls oracledb
494 error There is likely additional logging output above.
495 verbose exit [ 1, true ]

**Comment by cjbj** [comment]
Did you follow https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx ?

**Comment by isabolic** [comment]
Resolved, tnx for help
