### ISSUE TITLE
i cannnot install oracle on Windows7 by `npm install` command

### ISSUE THREAD

**Issue by dacuotecuo** [oracle/node-oracledb#528]
_Delete irrelevant parts of this template._
### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/
### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Review your output and logs.  **Google any errors**
Try to install in a different way.  Try some potential solutions.
#### Answer the following questions:
1. What error(s) you are seeing?
   F:\demo\node-oracle>npm --version
   3.10.3

here are the error logs：
F:\demo\node-oracle>npm i oracledb --save --save-exact

> oracledb@1.11.0 install F:\demo\node-oracle\node_modules\oracledb
> node-gyp rebuild

F:\demo\node-oracle\node_modules\oracledb>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [F:\demo\node-oracle\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd F:\demo\node-oracle\node_modules\oracledb
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN node-oracle@1.0.0 No description
npm WARN node-oracle@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "oracledb" "--save" "--save-exact"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     F:\demo\node-oracle\npm-debug.log
1. What _exact_ command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
2. What environment variables did you set?  How _exactly_ did you set them?
   OCI_INC_DIR D:\ORACLE\instantclient_11_2\sdk\include
   OCI_LIB_DIR D:\ORACLE\instantclient_11_2\sdk\lib\msvc
3. What is your version of Node.js?
   F:\demo\node-oracle>node --version
   v6.7.0
4. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
   instantclient_11_2
   D:\ORACLE\instantclient_11_2
5. What is your OS and version?
   windows 7
6. What compiler version did you use?

**Comment by Mo33n** [comment]
I am also facing the same issue, need help.

C:\WINDOWS\system32>npm install -g oracledb
/
> oracledb@1.11.0 install C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb
> node-gyp rebuild


C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\nj
sResultSet.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\nj
sConnection.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  njsMessages.cpp
  njsIntLob.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\nj
sPool.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\nj
sOracle.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiEnv.cpp
  dpiEnvImpl.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpi
Env.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiException.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpi
EnvImpl.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiExceptionImpl.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\nj
sIntLob.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiConnImpl.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dp
iConnImpl.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiStmtImpl.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiDa
teTimeArrayImpl.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiUtils.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpi
PoolImpl.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiLob.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dp
iStmtImpl.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiCommon.cpp
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiLo
b.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  win_delay_load_hook.cc
..\src\dpi\src\dpiCommon.cpp(28): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiUt
ils.cpp) [C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Moeen\AppData\Roaming\npm\node_modules\oracledb
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "oracledb"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log``

**Comment by cjbj** [comment]
Have you seen #18?

**Comment by cjbj** [comment]
Closing - no reply to my last question
