### ISSUE TITLE
Is that possible connect with a non localhost database

### ISSUE THREAD

**Issue by mapaiva** [oracle/node-oracledb#53]
Hello,

I'm testing the driver and comes me a question... Can I access a non localhost database using remote configs? Ex:

``` javascript
var config = {
  user: 'myuser',
  password: 'mypass',
  connectString: '192.168.0.666:1521/vm',
  poolMax: 10,
  poolMin: 2,
  poolIncrement: 4,
  poolTimeout: 4
};
``` 

And case true, need I download the **Oracle Instant Client** and set the global variables in my pc? 
I want use `node-oracledb` with [node-webkit](https://github.com/nwjs/nw.js) and I want to know if exists a simple way to point the location of the **Oracle Instant Client** in the application enviroment.

### Application
bin
&nbsp; |__ driver
&nbsp;&nbsp;&nbsp;&nbsp; |__ instantclient
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |__ binaries...
package.json
index.js

### index.js
``` javascript
//(...)
var config = {
 user: 'myuser',
  password: 'mypass',
  connectString: '192.168.0.666:1521/vm',
  poolMax: 10,
  poolMin: 2,
  poolIncrement: 4,
  poolTimeout: 4,

  LD_LIBRARY_PATH: __dirname + '/bin/driver/instantclient',
  OCI_LIB_DIR: __dirname + '/bin/driver/instantclient',
  OCI_INC_DIR: __dirname + '/bin/driver/instantclient/sdk/include'
};
//(...)
```

Is that possible?

**Comment by cjbj** [comment]
You can access remote databases using node-oracledb.

Instant Client (or any of the other forms of Oracle client libraries) will need to be downloaded to the client machine. In general, LD_LIBRARY_PATH or equivalent will need to be set before the process starts.  OCI_LIB_DIR and OCI_INC_DIR are only needed during build time, not at run time.  

On Linux, you can install the Instant Client RPMs and then you don't need to set any variables. See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#linuxadv

**Comment by mapaiva** [comment]
Thanks for the answer @cjbj . I've installed `node-oracledb` using rpm. But when I try to run a simple test script I have this error:

``` bash
Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/matheus/Documentos/Codit/afx_config/node_modules/oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

The code: 

``` javascript
var oracledb = require('oracledb');

console.log(oracledb);
```

I need to configure something else?

**Comment by cjbj** [comment]
The solution would be to set LD_LIBRARY_PATH to the directory with the Instant Client libraries.

For me to comment further and give guidance, I'd need to know what you installed and how you installed it

**Comment by mapaiva** [comment]
It was my mistake. After the rpm installation I forgot to set the LD_LIBRARY_PATH variable. I did this and it works.

Thank you for your help @cjbj

**Comment by cjbj** [comment]
In the simplest case you shouldn't need to set LD_LIBRARY_PATH unless you had set OCI_LIB_DIR and OCI_INC_DIR during installation.  See the link I mentioned before https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#linuxadv

**Comment by mapaiva** [comment]
@cjbj  Sorry for the reply delay. I've tried install without using rpm after using it and I forgot to delete the OCI_LIB_DIR and OCI_INC_DIR variables to my system. I guess that was the error.
