### ISSUE TITLE
 ORA-24408: could not generate unique server group name

### ISSUE THREAD

**Issue by swamy526** [oracle/node-oracledb#532]
I am facing issue: ORA-24408: could not generate unique server group name..while trying to create pool using createPool()

1. What error(s) you are seeing?
ORA-24408: could not generate unique server group name

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
oracledb.createPool();

3. What environment variables did you set?  How *exactly* did you set them?
not set any en variables

4. What is your version of Node.js?
v4.5.0

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
Instant Client Downloads for Mac OS X (Intel x86)
Version 12.1.0.2 (64-bit)
installation location : /opt/oracle/instantclient

6. What is your OS and version?
MacOS Sierra Version 10.12

7. What compiler version did you use?

**Comment by cjbj** [comment]
Google? :)

http://stackoverflow.com/questions/10484231/ora-24408-could-not-generate-unique-server-group-name#comment30445054_10710126

**Comment by AlokBansal8** [comment]
I am running my code on 2 machines with the following configuration and with original hosts file at /etc

Command: oracledb.createPool()
MacOS Sierra
Instant Client for MacOSX x64 at /opt/oracle/instantclient
Node v7.6.0

It is running on one machine and not on the second machine.
