### ISSUE TITLE
Question: oci.h not found on Mac

### ISSUE THREAD

**Issue by christopherbalz** [oracle/node-oracledb#54]
I have the file `oci.h` at the location pointed to by the environment variable, and as shown below, I exported it.  Separately, I get the same error as the one I show below when running a normal `npm i` scenario from project-foo's root (where I export the env var from a Makefile).  

How can I make `oci.h` be seen?

```
$ export DYLD_LIBRARY_PATH=/Users/cbalz/project-foo/lib/instantclient_11_2

cbalz@chris-m-balz-notebook:~/project-foo/node_modules/oracledb$ npm i

> oracledb@0.4.1 install /Users/cbalz/project-foo/node_modules/oracledb
> node-gyp rebuild
   ...
../src/dpi/include/dpiStmt.h:29:11: fatal error: 'oci.h' file not found
# include <oci.h>
```

```
$ ls -ail $DYLD_LIBRARY_PATH/sdk/include/oci.h
52632310 -r--r--r--@ 1 cbalz  staff  172157 Jun 16  2011 /Users/cbalz/project-foo/lib/instantclient_11_2/sdk/include/oci.h
```

```
$ uname -a
Darwin chrismbnotebook 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```

**Comment by pvenkatraman** [comment]
As per the documentation you need to set OCI_INC_DIR and OCI_LIB_DIR.  OCI_INC_DIR should point to the location where header files are there, and OCI_LIB_DIR for .so files.

**Comment by cjbj** [comment]
@christopherbalz As Venkat said, you need to set some env variables.  Let us know if there are any issues with the documentation: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

**Comment by christopherbalz** [comment]
Thank you!

**Comment by christopherbalz** [comment]
Also: Yes I did see that section (5.5), but I had moved my drivers to the correct place already, so that is why I didn't set those env vars.  I think actually that they need to be set regardless of whether they are in the expected place or not (`/whereever/instantclient/sdk/include`).

**Comment by cjbj** [comment]
@christopherbalz I'll review the doc. It is supposed to indicate that you need to set the env vars during installation if Instant Client is not in /opt/oracle/instantclient

**Comment by rnagulapalle** [comment]
I am having same issue. Followed the document for installtion and seeing below error.

-
> oracledb@0.4.2 install /Users/rnagulapalle/work/oracle/node_modules/oracledb
> node-gyp rebuild

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/njs/src/njsOracle.cpp:28:
In file included from ../src/njs/src/njsOracle.h:36:
In file included from ../src/dpi/include/dpi.h:35:
In file included from ../src/dpi/include/dpiEnv.h:36:
In file included from ../src/dpi/include/dpiPool.h:33:
In file included from ../src/dpi/include/dpiConn.h:29:
../src/dpi/include/dpiStmt.h:29:11: fatal error: 'oci.h' file not found
# include <oci.h>
          ^
1 error generated.
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rnagulapalle/work/oracle/node_modules/oracledb
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "oracledb"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! oracledb@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@0.4.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rnagulapalle/work/oracle/npm-debug.log

My env variables:
export DYLD_LIBRARY_PATH=/Users/rnagulapalle/work/oracle/instantclient_11_2:$DYLD_LIBRARY_PATH

export PATH=/Users/rnagulapalle/work/oracle/instantclient_11_2:$PATH

export OCI_LIB_DIR=/Users/rnagulapalle/work/oracle/instantclient_11_2
export OCI_INC_DIR=/Users/rnagulapalle/work/oracle/instantclient_11_2/sdk/include

**Comment by cjbj** [comment]
@rnagulapalle this issue is technically closed.  Please create a new one.  But first, double check everything is set correctly - and show us how you double checked.

**Comment by rnagulapalle** [comment]
Sure will open a new issue

On Tuesday, April 28, 2015, Christopher Jones <notifications@github.com>
wrote:

> @rnagulapalle <https://github.com/rnagulapalle> this issue is technically
> closed. Please create a new one. But first, double check everything is set
> correctly - and show us how you double checked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oracle/node-oracledb/issues/54#issuecomment-97187682>.
>


-- 
Thanks,
-Raj
