### ISSUE TITLE
Node.js v7.0.0 support

### ISSUE THREAD

**Issue by vcasagrand** [oracle/node-oracledb#540]
**What error(s) you are seeing?**

Library incompatibility error

**What is your version of Node.js?**

v7.0.0

**What is your OS and version?**

Windows 7 x64

**What compiler version did you use?**

Microsoft Visual Studio 2013
Version 12.0.40629.00 Update 5

Visual C++ 2013   06177-004-0444002-02405
Microsoft Visual C++ 2013

**Comment by cjbj** [comment]
This needs a bit more info - and/or you need to do some investigation: does Node 4 work?

**Comment by vcasagrand** [comment]
On node v6.9.1 works, but the module did not initialize after update node to v7.0.0, I have tried to remove and install the module, but just returned to work after the node downgrade.

**Comment by jeveloper** [comment]
On Node 7.X , i'm seeing a lot of warnings during compilation


../src/njs/src/njsUtils.h:299:29: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated (declared at /home/nh/.node-gyp/7.1.0/include/node/v8.h:8436): Use maybe version [-Wdeprecated-declarations]
     val = v8value->ToUint32()->Value();

**Comment by cjbj** [comment]
@jeveloper those warnings are covered in https://github.com/oracle/node-oracledb/issues/526

**Comment by jeveloper** [comment]
Yes :)

Just letting you know that 7.1 and node oracle lib works well , OSX and Linux distro, both were able to install and build (nodegyp compiled it).
Not sure if this error still is relevant.

**Comment by cjbj** [comment]
@jeveloper that's good to hear.  Feedback is always useful - we really appreciate it.

**Comment by jeveloper** [comment]
btw how can you and i connect via linkedin?

you know what would be great , is figure out how to get node-oracledb into azure functions or aws lambda 
its a bit of a challenge

**Comment by jeveloper** [comment]
I use AWS RDS with oracle , cheapest option out there for a small business i run.
I don't believe there is lambda/functions alternative on oracle cloud

**Comment by vcasagrand** [comment]
Ok, thanks, I have updated to v7.1.0 and tried a new installation, it produces some warnings but compiles.

**Comment by jeveloper** [comment]
@vcasagrand  YAY :) glad this worked out
