### ISSUE TITLE
Help installing on Windows with Node 4.x+

### ISSUE THREAD

**Issue by jdbranham** [oracle/node-oracledb#541]
I received errors like the following -
```.node-gyp\4.5.0\include\node\v8.h(2520): error C2989: 'v8::Int32' : class template has already been declared as a non-class template
node_modules\oracledb\src\dpi\src\dpiConnImpl.h(30): fatal error C1083: Cannot open include file: 'oci.h'
.node-gyp\4.5.0\include\node\v8.h(3288): error C2143: syntax error : missing ';' before '<'
.node-gyp\4.5.0\include\node\v8.h(3288): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

And found this solution -

If you are building the add-on with Node 4.x+, Visual Studio 2013 is required at minimum due to the C++ 11 features that are required. 
[C++ Feature comparison of Visual Studio](https://msdn.microsoft.com/en-us/library/hh567368.aspx)

**Comment by cjbj** [comment]
Thanks.  Did you try Node 6 & 7?

**Comment by suhail-ansari-apconic** [comment]
Guys seriously your installation is very time consuming and a headache to be honest. For Microsoft SQL Server we just have to install a npm package and we are done. With oracle installation is a mess for support on client machines. 

Please consider ease of deployment when building these installations as most of these installation are done by clients or by support personals, and it is not easy to make it work.

**Comment by cjbj** [comment]
@suhail-ansari-apconic did you check #18?
