### ISSUE TITLE
What version of Oracle Database does this support?

### ISSUE THREAD

**Issue by NickHeiner** [oracle/node-oracledb#542]
What version of Oracle Database does this support? I see that 12 is the latest version, but does it also support 11? 

(Ideally, this information would be in the README.)

Thanks!

**Comment by cjbj** [comment]
[INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md) has the information.  Having info in only in one place is generally a good thing (tm), but I can update the current README text "Various Oracle Database and Oracle Client versions" in this case.

**Comment by NickHeiner** [comment]
Ah, that makes sense. I agree that having information only in one place is a good thing. You could add a pointer in README.md that says "check INSTALL.md for supported versions".

**Comment by cjbj** [comment]
Sometime in the last couple of weeks I added this under the Prereqs subheading of the Installation section of the README, so you'll see the change in the next node-oracledb drop.  

Thanks for the feedback!
