### ISSUE TITLE
Specified Module could not be found during oracleDB require

### ISSUE THREAD

**Issue by jaipreet-chhatwal** [oracle/node-oracledb#545]
Hi Team , 

Need a urgent help .
I had built node-oracledb module on a **windows 64 bit** /node 4.2.3 with oracle client libraries 12.1 .and visual studio 2012 installed.
i am able to install and execute the module perfectly fine in the current machine .

I copied the entire project to a **windows 2008 R2 64 bit server** /node 4.2.3 with oracle client libraries 12.1 .and visual studio 2012 installed. 
I have configured the Path and with path to instantClient libraries . But while running i am getting the following exception

"the Specified module could not be found "

Please let me know : The probable causes for the same .

**Comment by dudleyjosh** [comment]
I think I finally solved this "Error: The specified module could not be found." issue related to oracledb.node.

I used a free utility called [Dependency Walker](http://www.dependencywalker.com/) to discover that oracledb.node is also dependent on MSVCR100.dll which is part of the Visual C++ 2010 SP1 Redistributable Package.

32Bit: Microsoft Visual C++ 2010 SP1 Redistributable Package (x86) 
[http://www.microsoft.com/de-de/download/details.aspx?id=8328](http://www.microsoft.com/de-de/download/details.aspx?id=8328)

64Bit: Microsoft Visual C++ 2010 SP1 Redistributable Package (x64) 
[http://www.microsoft.com/en-us/download/details.aspx?id=13523](http://www.microsoft.com/en-us/download/details.aspx?id=13523)

Once I also installed the correct Microsoft Visual C++ 2010 SP1 Redistributable Package it worked fine.

**Comment by jaipreet-chhatwal** [comment]
thanks for the reply
