### ISSUE TITLE
ORA-00604: error occurred at recursive SQL level 1 ORA-01422: exact fetch returns more than requested number of rows

### ISSUE THREAD

**Issue by doubletaketech** [oracle/node-oracledb#546]
I get this error, no matter what query I try to execute ...
CONNECT ERR: ORA-00604: error occurred at recursive SQL level 1 ORA-01422: exact fetch returns more than requested number of rows ORA-06512: at line 24

Any ideas?  My code is below.  The query is 
var query = 'Select b.csn, b.BADGEKEY from lenel.badge where b.id=1026149'; 

Thank you,
Donnie

`
server.method('queryOracle',function(data,next) {
                                                var oracledb = require('oracledb');
                                               
                                                 var q = data.query;
                                               
                                                                oracledb.getConnection({ 
                                                     user: data.user, 
                                                     password: data.password, 
                                                     connectString: data.connectString 
                                                }, function(err, connection) { 
                                                     if (err) { 
                                                          console.error('CONNECT ERR: '+err.message); 
                                                          next(err.message)
                                                          return; 
                                                     } 
                                                     connection.execute(q,function(err, result) { 
                                                                console.log('query results: '+result)
                                                          if (err) { 
                                                               console.error('Query ERR: '+err.message); 
                                                               next(err.message);
                                                               doRelease(connection); 
                                                               return; 
                                                          } 
 
                                                          next(result);
                                                          doRelease(connection); 
                                                    }); 
                                                }); 
                                                  
                                                function doRelease(connection) { 
                                                     connection.release( 
                                                         function(err) { 
                                                               if (err) {console.error(err.message);next(err.message)} 
                                                          } 
                                                     ); 
                                                } 
 
 
});
`

**Comment by doubletaketech** [comment]
This error occurs in getConnection, so the query never even executes, so I have no idea when it is saying stuff about rows returned ... when it never even get to the execute function?

**Comment by cjbj** [comment]
I was going to guess a trigger issue and my [top google choice](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::p11_question_id:4018285967344) indeed has some similar occurrences with triggers. 

Even if not a trigger, check whether you get the same error with SQL*Plus (to the same schema).

**Comment by doubletaketech** [comment]
@cjbj ,  Thank you!  I told this to the DBA here and it was enough to help him fix the problem!  Thank you!
