### ISSUE TITLE
Location to already build module ?

### ISSUE THREAD

**Issue by Wifsimster** [oracle/node-oracledb#548]
There is a way to get/download already build module for Windows 7 x64 ?

2 days trying  to build the module and compilation errors keep showing, i give up !

**Comment by dmcghan** [comment]
@Wifsimster Have you seen this? https://github.com/oracle/node-oracledb/issues/18

It's not from Oracle, so you have to trust the developer...

**Comment by cjbj** [comment]
Closing - no new comments for a month.
