### ISSUE TITLE
NJS-006: Invalid Type for parameter 2

### ISSUE THREAD

**Issue by TEQUIL4** [oracle/node-oracledb#549]
Hello, 

i am using the Oracle node to connect to a Oracle 11g DB on Windows 7. 
When i try to send a query  (any, insert, select...) by setting the msg.query property, it causes Node Red to crash and i get the following error:

Error: NJS-006: invalid type for parameter 2
      at Object.assert (C:\......\oracledb\lib\util.js:78:11)
      at Connection.execute (C:\......\oracledb\lib\connection.js:87:16)
      at Connection.execute (C:\......\oracledb\lib\util.js:97:19)
      at OracleServer.node.query  (C:\......\oracledb\lib\oracledb.js:186:33)
      at OracleServer.node.queryQueued  (C:\......\oracledb\lib\oracledb.js:255:22)
      at C:\......\oracledb\lib\oracledb.js:146:30
      at C:\......\oracledb\lib\oracledb.js:215:7

Do you have any idea what the problem could be?

**Comment by dmcghan** [comment]
Can you show us the code that causes the problem?

**Comment by TEQUIL4** [comment]
Well, i am using the Node Red version of this node (node-red-contrib-oracledb)
, so it isnt that easy to post the code. But i realize that this is probably the wrong place to come with this problem.
So i thank you for the response and i guess this issue can be closed or deleted.
Have a nice day.

**Comment by cjbj** [comment]
@TEQUIL4 At a guess there is an not-yet supported datatype.  It would be nice to know exactly, so we know what to prioritize.  If you can dig in the code bit, let us know what you find.

**Comment by TEQUIL4** [comment]
The problem is that i dont know which program calls the functions causing the error. I think the exception is thrown by an Assert function that doesnt pass but i couldnt find the caller function. 
I could Attach the source files causing the error but i dont know if it would be helpful for you since Node Red handles the execution.

**Comment by cjbj** [comment]
@TEQUIL4 keep looking!

**Comment by cjbj** [comment]
Closing - no updates for a month

**Comment by rb442e** [comment]
Hi cjbj, I am getting below error: 

NJS-008: invalid type for "type" in parameter 2

I tried checking all the types and everything looks ok it uses some db types (like pds.addrlist_tab)



create or replace
PROCEDURE     getuser (
   userplanid_in          IN     NUMBER,
   channel_in               IN     varchar2,
   sourcename_in            IN     varchar2,
   userplanid_out            OUT NUMBER,
   subuserplanid_out         OUT NUMBER,
   planusershipid            OUT varchar2,
   userid_out                OUT VARCHAR2,
   clientid_out                OUT NUMBER,
   organizationname            OUT VARCHAR2,
   usertypecode              OUT VARCHAR2,
   gender                      OUT VARCHAR2,
   dateofbirth                 OUT date,
   firstname                   OUT VARCHAR2,
   lastname                    OUT VARCHAR2,
   addresslist                 OUT addrlist_tab,
   phonelist                   OUT phonelist_tab,
   emaillist                   OUT emaillist_tab,
   dependentlist               OUT dependentlist_tab,
   userenddate               OUT date,
   contactpreference           OUT varchar2,
   calloptoutFlag              OUT VARCHAR2,
   CalloptoutText              OUT VARCHAR2,
   PathFlag_out               OUT VARCHAR2,
   Pathrec_out                OUT pds.PathuserIdentification_OBJ,
   registrationreturncode      OUT varchar2,
   errorcode                   OUT number
)

var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');

oracledb.getConnection(
    {
        user: dbConfig.user,
        password: dbConfig.password,
        connectString: dbConfig.connectString
    },
  function (err, connection) {
      if (err) { console.error(err.message); return; }

      const bindvars = {
          userplanid_in: { val: 1685847931, dir: oracledb.BIND_IN, type: oracledb.NUMBER },
          channel_in: { val: 'ADMIN', dir: oracledb.BIND_IN, type: oracledb.STRING },
          sourcename_in: { val: 'PHR_UE', dir: oracledb.BIND_IN, type: oracledb.STRING },
          userplanid_out: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
          subuserplanid_out: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
          planusershipid: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          userid_out: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          clientid_out: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
          organizationname: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          usertypecode: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          gender: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          dateofbirth: { dir: oracledb.BIND_OUT, type: oracledb.DATE },           
          firstname: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          lastname: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
          addresslist: { dir: oracledb.BIND_OUT, type: 'pds.addrlist_tab' },
          phonelist: { dir: oracledb.BIND_OUT, type: 'pds.phonelist_tab' },
          emaillist: { dir: oracledb.BIND_OUT, type: 'pds.emaillist_tab' },
          dependentlist: { dir: oracledb.BIND_OUT, type: 'pds.dependentlist_tab' },
		userenddate: { dir: oracledb.BIND_OUT, type: oracledb.DATE },
		contactpreference: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
		calloptoutFlag: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
		CalloptoutText: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
		PathFlag_out: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
		Pathrec_out: { dir: oracledb.BIND_OUT, type: 'pds.PathuserIDENTIFICATION_OBJ' },
		registrationreturncode: { dir: oracledb.BIND_OUT, type: oracledb.STRING },
		errorcode: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
};
connection.execute(
    "BEGIN pds.getuser_esb(:userplanid_in, :channel_in, :sourcename_in, :userplanid_out, :subuserplanid_out, :planusershipid, :userid_out, :clientid_out, :organizationname, :usertypecode, :gender, :dateofbirth, :firstname, :lastname, :addresslist, :phonelist, :emaillist, :dependentlist, :userenddate, :contactpreference, :calloptoutFlag, :CalloptoutText, :PathFlag_out, :Pathrec_out, :registrationreturncode, :errorcode); END;",
    bindvars,
    function (err, result) {
        if (err) {
            console.error(err.message);
            doRelease(connection);
            return;
        }
        console.log(result.outBinds);
        doRelease(connection);
    });
});

**Comment by rb442e** [comment]
Can you please help?

**Comment by rb442e** [comment]
If this issue not resolved we may need to think something else than Node

**Comment by dmcghan** [comment]
@rb442e This issue has been closed for months. Could you please create a new one?

**Comment by rb442e** [comment]
ok thanks
