### ISSUE TITLE
Compile error with node v0.10.35 AND VS2012

### ISSUE THREAD

**Issue by ckjinni** [oracle/node-oracledb#55]
I followed install guide but can't connect oracle.

(I'm Korean, so my English is hard to understand but I tried to use easy word...)

I use node.js v0.10.35 and compiler (VS2012 express edition)

WHEN I comment 'npm install -g' THEN send me a error like this.

==========================================================================

D:\node-oracledb-master>npm install -g
-
> oracledb@0.4.1 install C:\Users\user\AppData\Roaming\npm\node_modules\oracledb
> node-gyp rebuild

npm ERR! oracledb@0.4.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the oracledb@0.4.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "-g"
npm ERR! cwd D:\node-oracledb-master
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

=========================================================================

So, I commend 'node-gyp rebuild' and also send me a error message.

=========================================================================

D:\node-oracledb-master>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.10.35 | win32 | ia32
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\node-oracledb-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\.node-gyp\\0.10.35\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user\\.node-gyp\\0.10.35',
gyp info spawn args   '-Dmodule_root_dir=D:\\node-oracledb-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\node-oracledb-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]

  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsMessages.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
     D:\node-oracledb-master\build\Release\oracledb.lib 
     D:\node-oracledb-master\build\Release\oracledb.exp 

dpiEnvImpl.obj : error LNK2001: _OCIHandleFree 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: _OCIEnvCreate 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCIAttrSet 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCITransRollback 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj
]
dpiConnImpl.obj : error LNK2001: _OCISessionGet 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCIBreak 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCIHandleAlloc 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCIAttrGet 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCITransCommit 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: _OCISessionRelease 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxpro
j]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIDescriptorAlloc 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracl
edb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCINumberFromReal 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracle
db.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIIntervalToNumber 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\orac
ledb.vcxproj
]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIArrayDescriptorAlloc 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\
oracledb.vcx
proj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIDateTimeSubtract 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\orac
ledb.vcxproj
]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIDescriptorFree 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracle
db.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIIntervalFromNumber 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\or
acledb.vcxpr
oj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIArrayDescriptorFree 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\o
racledb.vcxp
roj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIDateTimeIntervalAdd 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\o
racledb.vcxp
roj]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCIDateTimeConstruct 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\ora
cledb.vcxpro
j]
dpiDateTimeArrayImpl.obj : error LNK2001: _OCINumberToReal 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb
.vcxproj]
dpiPoolImpl.obj : error LNK2001: _OCISessionPoolDestroy 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vc
xproj]
dpiPoolImpl.obj : error LNK2001: _OCISessionPoolCreate 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcx
proj]
dpiStmtImpl.obj : error LNK2001: _OCIBindByPos2 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: _OCIBindByName2 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: _OCIParamGet 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: _OCIStmtPrepare2 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]

dpiStmtImpl.obj : error LNK2001: _OCIStmtRelease 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: _OCIStmtFetch2 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: _OCIDefineByPos2 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]

dpiStmtImpl.obj : error LNK2001: _OCIStmtExecute 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
dpiUtils.obj : error LNK2001: _OCIErrorGet 외부 기호를 확인할 수 없습니다. [D:\node-oracledb-master\build\oracledb.vcxproj]
D:\node-oracledb-master\build\Release\oracledb.node : fatal error LNK1120: 32개의 확인할 수 없는 외부 참조입니다. [D:\node-oracled
b-master\build
\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\node-oracledb-master
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

=============================================================================

I tried to uninstall and reinstall node.js and VS2012 twice but same error.

also I upgrade node.js version and also downgrade version.

but same error, same time. (LNK2001 error)

I set my enviroment variable, install right version of Python.

what should I do? Please send me some advices.

**Comment by pvenkatraman** [comment]
Do you have OCI_LIB_DIR environment variable set?  This should point to directory where Oracle DLLs are available.

**Comment by ckjinni** [comment]
yes, I have OCI_LIB_DIR environment variable set.

**Comment by cjbj** [comment]
Start by telling us what you installed, where you installed it, what environment variables you have set and what values they have.

**Comment by cjbj** [comment]
@ckjinni please review the updated install instructions and see if you get any further
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin

**Comment by ckjinni** [comment]
https://www.dropbox.com/s/i8nre1ypmz5ze9q/oracledb_install_failed.pdf?dl=0

I capture my computer to setting node.js and oracledb ( link is PDF file )

I use Win7 (32bit) and no install oracle in the local.

I need some help so give me some advice to see my PDF file.

**Comment by cjbj** [comment]
@ckjinni thanks for the excellent summary of what you have done.  I am guessing you downloaded the node-oracle ZIP file from GitHub and extracted it to node-oracledb-master?  You don't need to download the source manually anymore. It will automatically be downloaded by 'npm install oracledb'.

Try running 'npm install oracledb' in another directory and/or remove the node-oracledb-master source code.

Also, check that 'SET PATH' shows the Instant Client directory.

Google for 'npm refusing to install as a dependency of itself' to find more information.

**Comment by ckjinni** [comment]
https://www.dropbox.com/s/0wg0ce2nljivdby/oracledb_install_failed2.pdf?dl=0

TRY 'NPM install oracledb ' and check 'SET PATH' but 'node-gyp rebuild' error is so powerful...

I think this is node-gyp problem.... I try to 'npm install node-gyp' or 'reinstall node_js' but not help.

**Comment by pvenkatraman** [comment]
can you provide is what is in %OCI_LIB_DIR% before running "npm install oracledb".  Your settings are good, but you are getting missing symbol linker errors. Thanks,

**Comment by ckjinni** [comment]
how can I provide %OCI_LIB_DIR%  ??? I don't understand

**Comment by cjbj** [comment]
In the command shell just before you do 'npm install oracledb' do 
SET OCI_LIB_DIR
or
echo %OCI_LIB_DIR%

**Comment by ckjinni** [comment]
https://www.dropbox.com/s/nngahkh6v5tlby0/oracledb_failed3.jpg?dl=0

I run 'SET OCI_LIB_DIR' and this is result image. I think node-gyp is big problem.

**Comment by pvenkatraman** [comment]
do "dir %OCI_LIB_DIR%" and pass on the result, and then try node-gyp rebuild command.

**Comment by ckjinni** [comment]
https://www.dropbox.com/s/4jin1r1raxept6l/oracledb_failed5.jpg?dl=0
https://www.dropbox.com/s/7rk1z7ydn1bfkl9/oracledb_failed6.jpg?dl=0

same error. I really thank you for your help

**Comment by varshnes** [comment]
Did you have sdk downloaded for Oracle/instantclient....if yes add OCI_LIB_Dir to your path which could be C:\oracle\instantclient\sdk\lib\msvc....you are missing this PATH

**Comment by bmulcahy** [comment]
install the windows sdk 7.1
