### ISSUE TITLE
Can not get oracledb to install without errors...

### ISSUE THREAD

**Issue by chevalierc** [oracle/node-oracledb#551]
###Intro:
I've had a bit of trouble installing this guy again. I have it working on my dev machine and have been trying to imitate that in addition to following through your guide and [this one (installing there exact versions)](https://community.oracle.com/docs/DOC-931127)

#### Answer the following questions:

1. What error(s) you are seeing?

https://gist.github.com/chevalierc/303d4abd2e10c4af00d6314a27d27998

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

**environment:**
Windows Server 2012 Standard
64 bit OS, x64-based-processor
Running everything as admin

**Installed:**
node v4.2.3
ms visual c++ 2010 x64 - 10.0.40219
ms visual c++ 2015 x64 - 14.0.24210
ms visual c++ 2015 x86 - 14.0.24210
ms visual c++ Build Tools (installed via `npm install --global --production windows-build-tools`)
Python 2.7.11 (installed via `npm install --global --production windows-build-tools`)
instantclient-basic-windows.x64-12.1.0.2.0
instantclient-sdk-windows.x64-12.1.0.2.0

3. What environment variables did you set?  How *exactly* did you set them?
```
$ echo $PATH
/h//bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/h/bin:C:oracle/instantclient:/c/Program Files/EMC NetWorker/nsr/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/nodejs:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files/EMC NetWorker/nsr/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/nodejs:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:C:oracle/instantclient:/usr/bin/vendor_perl:/usr/bin/core_perl
```
Set via control panel. [windows] > [settings] > [edit the system environmental variables] > [enviromental variables]

4. What is your version of Node.js?
```
$ node -v
v4.2.3
```

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

```
$ cd c:oracle/instantclient/sdk
$ ls
admin/  demo/  include/  lib/  ott.bat  ottclasses.zip  SDK_README
```

6. What is your OS and version?

Windows Server 2012 Standard
64 bit OS, x64-based-processor

7. What compiler version did you use?

c++ compiler??? I'm not sure. I've tried uninstalling/ installing various versions. On my dev machine (where I did install this guy successfully) I had many installed

### Final Note:
Really have to get this working. If you need more information please ask and I will provide right away.

**Comment by cjbj** [comment]
Can you copy the binary from the dev machine? https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#winbins

What have you been able to google on the error about the __pfnDliNotifyHook2 symbol?  I can see various hits talking about node-gyp problems.  Maybe some info in one of the discussions will help?

One extra complexity could be the old version of Node 4.  The last release was 4.6.2 and you are using 4.2.3.

**Comment by chevalierc** [comment]
@cjbj 
RE: Binaries
That was something I had tried (and will try differently now). Something I was confused about was if the destination environment had to match the source environment? (aka node versions, window versions, c++ compiler version)

RE: node version
I chose that simply because that was what the example instructions mentioned.

--thanks as always cjbj

**Comment by chevalierc** [comment]
Solved it after a few more hours of tweaking this morning:

Here is the 3 steps that finally worked
1. `npm install --global --production windows-build-tools`
2. Copied the instant client folder from my dev machine (it had more files in it then the other. I think this was what really did it)
3. `set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140`

Another fun ride with node-gyp ;)

**Comment by cjbj** [comment]
I appreciate hearing the resolution.  PR's for the installation guide are very welcome.
