### ISSUE TITLE
Do this library have oracle bulk insertion feature ? If yes, kindly give me any example.

### ISSUE THREAD

**Issue by Mo33n** [oracle/node-oracledb#554]
I want to insert the multiple records in a table in the optimal way.

**Comment by nmaynes** [comment]
@Mo33n This is not really an issue. Are you trying to figure out how to run PL/SQL from a node webapp? For more information on running FORALL statements see [this ](http://www.oracle.com/technetwork/issue-archive/2012/12-sep/o52plsql-1709862.html) Oracle tech network article.

**Comment by ggrimbert** [comment]
If you have the primarykey inside your insert, just do insert all https://www.techonthenet.com/oracle/questions/insert_rows.php

If you have an identity column, you have to change to this : 
```
INSERT ALL INSERT INTO table (column_name1,column_name2)
    with rowAttr as (
      SELECT value as "column_name1",value as "column_name2" FROM DUAL UNION ALL
      SELECT value as "column_name1",value as "column_name2" FROM DUAL
    )
  SELECT * FROM rowAttr
```

**Comment by sagiegurari** [comment]
if its performance boost you are looking for, this won't help you.
if you are looking for simplicity of pushing many inserts and wrapping all of them automatically in a single commit/rollback than it will:
https://github.com/sagiegurari/simple-oracledb#Connection+batchInsert

**Comment by Mo33n** [comment]
Thanks all , @ggrimbert  solution works for me. 
cheers.
