### ISSUE TITLE
Handling number presicion

### ISSUE THREAD

**Issue by jcrosswhite-arrow** [oracle/node-oracledb#555]
Hello,

How should I go about handling money and currency within Oracle?  I have a table with the following column defined:
`PRICE NUMBER(15,2)`

And a row with a price of 38.73.  I ran this very simple test:

```
var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "xxx",
    password      : "xxx",
    connectString : "xxx"
  },
  function(err, connection)
  {
    if (err) { console.error(err); return; }
    connection.execute(
      "SELECT price FROM jc_parts where part_id = 54",
      function(err, result)
      {
        if (err) { console.error(err); return; }
        console.log(result);
      });
  });
```

And I get the following result:

```
{ rows: [ [ 38.730000000000004 ] ],
  resultSet: undefined,
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'PRICE' } ] }
```

If I run the same query from sqlplus, I get:

```
SQL> select price from jc_parts where part_id = 54;

     PRICE
----------
     38.73
```

I'd rather not change the query (i.e. using to_char) since I'm encountering this issue by using a framework.  Is there a way to handle this?

SELECT version FROM v$instance -> 11.2.0.3.0
Instantclient version -> linux.x64-12.1.0.2.0
oracledb version -> ^1.11.0

**Comment by ggrimbert** [comment]
Same problem here 
427.78 becomes 427.78000000000003.

There is no way that I force the mapping of the column to string to make it to number again

**Comment by cjbj** [comment]
For the moment, look at https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbfetchasstring

**Comment by ggrimbert** [comment]
This cannot be the solution. 
I'm pretty sure that you use a float to get te the result of the request and this is what created this problem.

**Comment by sagiegurari** [comment]
maybe use [toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) if you know what the expected format is?
Since this is money, I guess toFixed(2) should work, no?

**Comment by cjbj** [comment]
@ggrimbert from the [source code](https://github.com/oracle/node-oracledb/blob/v1.11.0/src/njs/src/njsConnection.cpp#L2106) `/* Double is used for all numeric types */`

Anyway, I'll get someone to review the scenario and code.  Number precision is tricky; Oracle's precision is greater than Node's so you may see always see some edge case surprises (this example may be one of them).  This leads on to the original question "How should I go about handling money and currency within Oracle?"  This is self answering: do it in Oracle, not Node.  I'd argue the Oracle's number handling is better suited for this task than Node's.

**Comment by bjouhier** [comment]
Or get read/write values as strings and use a big number / big decimal library in JS. https://github.com/andyperlitch/jsbn is a good starting point.

**Comment by ggrimbert** [comment]
Getting all number to String cannot be the solution, for numbers without precision, I don't want a String.

In my case, it's effectively a price, but defined with ```NUMBER(15,5)```

I'm gessing if you shouldn't think about getting the column definition and if it's number, do the toFixed by yourself, before returning the number. 
I can't do this in my code, I am currently working on Oracle support for Sequelize, and the only way to call toFixed is at the return of the execute() call for each row Oracle is giving back, so it's a big problem for performance.

I use BigNumber library for price handling : https://github.com/MikeMcl/bignumber.js/

For now, I saw this problem arriving only with price when I try to define a BigNumber. At this point, I get : 
```
Error: new BigNumber() number type has more than 15 significant digits: 427.78000000000003
```

I have a workaround, but I cannot take care of this in every piece of my application.

**Comment by bjouhier** [comment]
The problem is not the Oracle driver, it is JavaScript and its lack of a proper decimal data type:
```sh
$ node -e 'console.log(0.2 + 0.7)'
0.8999999999999999
```

**Comment by sagiegurari** [comment]
its actually has to do with floating point precision standards implemented in js and many other languages (for example java).
So I'm not sure how you would bypass the issue without toFixed/string so on...

for example, in java you would also run into same issues

````java
public class Test {
  public static void main(String[] args) {
    System.out.println(0.2 + 0.7);
  }
}
````

would also output: **0.8999999999999999**

it sucks but you need to learn to be careful when using floating points.
So I still suggest to use toFixed in this case.

**Comment by jcrosswhite-arrow** [comment]
Thank you all for the help on this.  I did want to stay away from treating currency as floats in JS, so having it as a string is very helpful.  Either doing it globally via '[fetchAsString](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbfetchasstring)' or on a column by column basis using '[fetchInfo](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#--42433-fetchinfo)'.  I may stay away from '[toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)' for now just because it does rounding for me, and I'd hate to introduce errors this way - but that may work for others.

Thank you all.
