### ISSUE TITLE
Closing connection throws error...

### ISSUE THREAD

**Issue by paulogdm** [oracle/node-oracledb#556]
Hello! Quick question, Im doing something like this:

```
function(data, cb){
	oracledb.getConnection(config, function(err, conn){
		if(err){...} else {
			conn.execute(oracleqrs.getTables, {}, {}, function(err, result){
				if(err){...} else {...});
				conn.release(function(error){
					console.info("Failed to release!" + error);
				});
			});
		}
	})
},
```
Console outputs "Failed to release!" and "error" is undefined, weird uh?
(https://github.com/paulogdm/oramon)
Any hints?

**Comment by sagiegurari** [comment]
Error is undefined because it doesnt throw an error.
The release callback is always invoked even if there was no error, and the error object is defined only if there actually was an error.

**Comment by paulogdm** [comment]
Omg, I feel stupid, sorry for this post... Guess um a little tired =).
