### ISSUE TITLE
Setting Location of Binary Add-on Explicitly 

### ISSUE THREAD

**Issue by brucemack** [oracle/node-oracledb#558]
My goal is to ask the package to load the native binary add-on (oracledb.node) from an explicit location that is outside of the regular node_modules file hierarchy.  I am doing this to make it easy for people inside of my organization to install the package without needing to do any native compilation.  

In other words: I want create a version of the package that is **pure JavaScript** and will work **under the assumption that the user already has the Oracle Instant Client and node-oraclledb add-on binary present on their machine**.

I believe it all boils down to this line in oracledb.js:

`oracledbCLib =  require('../build/Release/oracledb');`

Ideally, an option would be provided that allows the user of the package to point to an explicit path where the oracledb.node binary is located. The mechanism used to specify the location would need to be worked out - possibly an environment variable.

I think this change might be useful in general since it opens the possibility of un-bundling the JavaScript part of this package from the native C++ part of it.

NOTE: I am not asking for a version of the package that already contains pre-built binaries.  That appears to be a request that has already been made and has been the subject of lively discussion.  

Any thoughts/comments on this would be welcomed. If the concept is workable I will submit a PR.

**Comment by cjbj** [comment]
You can currently set the NODE_PATH environment variable (for each user), as you might do for globally installed packages. I think this would be simpler than fiddling with code.

**Comment by brucemack** [comment]
Thanks for the quick reply, and apologies if this is a Node.JS noob question.  

I would have thought that the NODE_PATH (or something similar) would be the solution, but given that the require() call in the oracledb.js file calls out an **explicit path** (i.e. starts with "../"), I don't think the NODE_PATH is being used.

The Node.JS documentation at this location provides the algorithm used to resolve require() calls: [https://nodejs.org/api/modules.html#modules_all_together](url).

The salient part of the logic is copied below:

require(X) from module at path Y
1. If X is a core module,
   a. return the core module
   b. STOP
2. **If X begins with './' or '/' or '../'**
   a. LOAD_AS_FILE(Y + X)
   b. LOAD_AS_DIRECTORY(Y + X)
3. LOAD_NODE_MODULES(X, dirname(Y))
4. THROW "not found"

My understanding is that the NODE_PATH doesn't get used until step 3 above.  I would be happy to be proven wrong here because the NODE_PATH behavior is exactly what I was looking for.

**Comment by cjbj** [comment]
NODE_PATH works for cases I've seen.  One example is [here](https://github.com/OraOpenSource/OXAR/blob/master/profile.d/30oos_nodejs.sh) when the driver is installed globally like [this](https://github.com/OraOpenSource/OXAR/blob/master/scripts/node-oracledb.sh#L13).  Try it out and let us know what you find.

**Comment by cjbj** [comment]
@brucemack ping.  What did you find?

**Comment by brucemack** [comment]
Thanks for the comments and the examples.  But I think you are misunderstanding my question.

It's very clear from your example that it is possible to install the **entire oracledb module** in a central location, pointed to by NODE_PATH.  That can be done using the npm install -g command, or even by manually moving the module from another machine and adjusting the NODE_PATH variable accordingly.  No argument there.

My original question related to the native portion of the oracledb module only (oracledb.node).  I was hoping to be able to install **that single binary file** somewhere on the machine and have the oracledb module (pure JavaScript) be able to resolve it.  NODE_PATH does not work given the semantics from the documentation that I quoted above.

What I'm talking about is exactly what is happening with the Oracle OCI DLLs (Instant client).  The OCI DLLs are resolved from a location on the machine using PATH/LD_LIBRARY_PATH and this seems completely natural.  I was hoping is to be able to do the same thing with the oracledb.node DLL.  That narrows the amount of customization that has to be performed on a machine and would make it a lot easier for the JavaScript part of the oracledb module to be evolved without making people handle the re-building of the native part of the code (which isn't always easy for people who are familiar with getting Perl, C++ compilers, etc. configured).

Anyhow, thanks for the input on this question.

**Comment by cjbj** [comment]
There are only a few extra .js files that node-oracledb needs, and they tend to be coupled with the binary so it makes sense to keep them together.  Also the oracle.node library is dynamically loaded by Node.js; it isn't on PATH/LD_LIBRARY_PATH. What you could look at is creating a wrapper Node.js package consisting of only an index.js with a single line like this, loading node-oracledb's index.js or oracledb.js from where ever you have installed node-oracledb:
```
module.exports = require('/Users/cjones/n/node_modules/oracledb/lib/oracledb.js');
```

**Comment by cjbj** [comment]
@brucemack How are you going with this?
