### ISSUE TITLE
Unable to use same parameters for bind_inout?

### ISSUE THREAD

**Issue by lukealbao** [oracle/node-oracledb#561]
DB outformat is currently OBJECT. I'd like to pass in a single object for bindparams and have the persistent values returned into an outBinds object using the same keys. (outBind keys do not match column keys exactly.)

### Query

```javascript
const query = 'INSERT INTO bins (ID, SETTINGS, UPDATEDAT, CREATEDAT) '
    + 'VALUES (:id, :settings, :updatedAt, :createdAt) '
    + 'RETURNING ID, SETTINGS, CREATEDAT, UPDATEDAT '
    + 'INTO :id, :settings, :createdAt, :updatedAt';

const bindParams = { 
  id: { val: '123412', dir: 3002, type: 2001 },
  settings: { val: '{"foo":"bar"}', dir: 3002, type: 2001 },
  updatedAt: { val: 1480523069232, dir: 3002, type: 2002 },
  createdAt: { val: 1480523069232, dir: 3002, type: 2002 } 
};

// ....
connection.execute(query, bindParams)
.then(console.log)
.catch(console.error);
```

### Expected Behavior
Expecting the returned value for `outBinds` to be:

```
{
  id: '1234',
  settings: '{"foo":"bar"}',
  updatedAt: 1480523069232,
  createdAt: 1480523069232
}
```

### Actual Behavior

Throws
```
ORA-01400: cannot insert NULL into ("ROOT_TESTING"."BINS"."CREATEDAT")
```

Is it not possible to have the out bind to the same parameter as the in bind? When I remove the whole `RETURNING...INTO...` clause from the query, it works fine.

**Comment by dmcghan** [comment]
@lukealbao Hmmm. I would have expected a bind/type error. The values for the dates should be JS dates, not epoch/Unix numeric timestamps. 

What do you get if you change that?

**Comment by lukealbao** [comment]
Same thing, I think.

```javascript
const query = 'INSERT INTO bins (ID, SETTINGS, UPDATEDAT, CREATEDAT) '
  + 'VALUES (:id, :settings, :updatedAt, :createdAt) '
  + 'RETURNING ID, SETTINGS, CREATEDAT, UPDATEDAT '
  + 'INTO :id, :settings, :createdAt, :updatedAt';

// console printout. dates are Date objects
const params = { 
  id: { val: '123413', dir: 3002, type: 2001 },
  settings: { val: '{"foo":"bar"}', dir: 3002, type: 2001 },
  updatedAt:
   { val: Wed Nov 30 2016 16:17:47 GMT-0500 (EST),
     dir: 3002,
     type: 2003 },
  createdAt:
   { dir: 3002,
     type: 2003,
     val: Wed Nov 30 2016 16:17:47 GMT-0500 (EST) } 
};

connection.execute(query, params).then(console.log);
```

Throws

```
Unhandled rejection Error: ORA-01400: cannot insert NULL into ("ROOT_TESTING"."BINS"."CREATEDAT")
```

**Comment by lukealbao** [comment]
It also seems to be the case that if the bind parameters are just a key/val map it works ok:

```javascript
const params = { 
  id: '123413',
  settings: '{"foo":"bar"}',
  updatedAt:  Wed Nov 30 2016 16:17:47 GMT-0500 (EST),
  createdAt: Wed Nov 30 2016 16:17:47 GMT-0500 (EST) 
};

connection.execute(query, params).then(console.log);
````

// OK

**Comment by cjbj** [comment]
Use different variables for the IN and OUT parts. From the [OCI Manual](http://docs.oracle.com/database/122/LNOCI/binding-and-defining-in-oci.htm#LNOCI16403)

> "No duplicate binds are allowed in a DML statement with a RETURNING clause, and no duplication is allowed between bind variables in the DML section and the RETURNING section of the statement"

My test cases (with 1.10.1, 1.11, and unreleased 1.12) show different behavior to yours: outBinds is not set.  There is no error.  I'll add a dev task to review this to see if some message can be displayed. I'll also update the node-oracledb doc.

Your error about NULL made me think of the fixes for handling NULLs with INOUT binds that have gone into node-oracledb 1.12 (due out soon) - but you weren't using NULLs and my results with 1.10 and 1.11 were the same as 1.12.  Perhaps my tests didn't trigger that issue?  If you have a runnable test case, send it through.

**Comment by lukealbao** [comment]
Thanks, @cjbj. I guess I don't understand what an IN/OUT bind is used for. Can you help me there?

As for getting the null error, I think any INOUT on a "NOT NULL" column produces the error. Running the code below (with `config` defined) on v1.11.0 on Node v4.4.6 and oracleServerVersion 1201000200 reproduces the error for me:

```js
const oracle = require('oracledb');
const Promise = require('bluebird');
oracle.Promise = Promise;
oracle.outFormat = oracle.OBJECT;
oracle.autoCommit = true;

const config; // = CONNECTION PARAMS

const queries = {
  dropTable: 'DROP TABLE foo',
  createTable: 'CREATE TABLE foo (ID INTEGER, NAME VARCHAR2(256) NOT NULL)',
  createRow: 'INSERT INTO foo (ID, NAME) VALUES (:id, :name) '
    + 'RETURNING ID, NAME into :id, :name'
};

const bindParams = {
  id: {val: 1, type: oracle.NUMBER, dir: oracle.BIND_INOUT},
  name: {val: 'Luke', type: oracle.STRING, dir: oracle.BIND_INOUT}
};

Promise.using(oracle.getConnection(config), (conn) => {
  return conn.execute(queries.dropTable)
    .catch(() => {
      return; // hide drop unknown table errs.
    })
    .finally(() => {
      return conn.execute(queries.createTable);
    })
    .then(() => {
      return conn.execute(queries.createRow, bindParams);
    });
})
.then(console.log)
.catch(err => {console.log(err.stack);});
```

**Comment by cjbj** [comment]
The quote I gave:

> no duplication is allowed between bind variables in the DML section and the RETURNING section of the statement

applies to your statement.

Your DML part:

```
'INSERT INTO foo (ID, NAME) VALUES (:id, :name) '
```

uses `:id` and `:name`.

And your `RETURNING` part:

```
    + 'RETURNING ID, NAME into :id, :name'
```

also uses `:id` and `:name`.  This is duplication.

You will need to change your SQL to something like:

```
  createRow: 'INSERT INTO foo (ID, NAME) VALUES (:id, :name) '
    + 'RETURNING ID, NAME into :id2, :name2'
```    

and bind like:

```
const bindParams = {
  id: {val: 1, type: oracle.NUMBER, dir: oracle.BIND_IN},
  name: {val: 'Luke', type: oracle.STRING, dir: oracle.BIND_IN}
  id2: {type: oracle.NUMBER, dir: oracle.BIND_OUT},
  name2: {type: oracle.STRING, dir: oracle.BIND_OUT}
};
```

Although you would think IN OUT binds could be used, OCI won't allow them in the `RETURNING INTO` context for whatever technical reason it has.  The contexts where they are useful is for PL/SQL, such as:

```
CREATE OR REPLACE PROCEDURE my_in_out (p_id IN OUT NUMBER, p_name IN OUT VARCHAR2) AS
. . .

```

**Comment by cjbj** [comment]
@lukealbao ping

**Comment by lukealbao** [comment]
Sorry -- yeah thank you I just used separate bindings, but I still don't understand the use case for in/out bindings. But that's ok. 

I had kept this issue open because you'd asked for a testable case for the null errors. Was the above snippet able to replicate the error for you under 1.12?

**Comment by dmcghan** [comment]
@lukealbao To take what @cjbj said a bit further, imagine you had this stored procedure (notice the in out parameter):

```sql
create or replace procedure calculate_raise (
  p_salary in out number
)

is

begin

  p_salary := p_salary * 1.03;

end;
```

You could call that with the following Node.js script:
```javascript
var oracledb = require('oracledb');
var config = require('./dbConfig.js');

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }

  connection.execute(
    "begin calculate_raise(:salary); end;",
    {
      salary: { 
        val: 100, 
        dir: oracledb.BIND_INOUT, 
        type: oracledb.NUMBER
      }
    },
    function(err, result) {
      if (err) {
        throw err;
      }

      console.log(result.outBinds.salary); // 103

      connection.close(function(err) {
        if (err) {
          throw err;
        }
      });
    }
  );
});
```

**Comment by cjbj** [comment]
@lukealbao I was able to reproduce it, thanks. The behavior is 'expected' so I didn't do more than add a note to my wish list that it would be nice if a useful error message was displayed.

The example @dmcghan gave is good.  There's an older one in [plsqlproc.js](https://github.com/oracle/node-oracledb/blob/master/examples/plsqlproc.js) too. PRs welcome.

I'll close this now. Thanks for using node-oracledb.
