### ISSUE TITLE
Leakage of pool._connectionsOut counter and consequent NJS-040 exception

### ISSUE THREAD

**Issue by fedulovivan** [oracle/node-oracledb#562]
node-oracledb: **1.10.0**
nodejs: **0.12.7**
operating system: **ubuntu 14.04**, **rhel 7.2**
oracle instantclient: **12.1**

Hello,
we have faced with an issue with queuing pooled connections, which finishes with series of NJS-040 exceptions and disability to check-out new connections from pool.

**Scenario**:
- init pool with queuing enabled (default lib behavior), limit max pool size to 10
- do 10 queries, which involve reading result set
- each result set reading operation terminates with invocation of [connection.release](https://github.com/oracle/node-oracledb/blob/v1.10.0/lib/connection.js#L165)
- we have a custom callback passed to release method, which (callback) internally throws an exception (our application bug)
- this seems to prevent invocation of [pool._onConnectionRelease](https://github.com/oracle/node-oracledb/blob/v1.10.0/lib/connection.js#L176)
- value of [_connectionsOut](https://github.com/oracle/node-oracledb/blob/v1.10.0/lib/pool.js#L376) is not decreasing
- as a result, after 10 requestes, we have all further [requested connections queued](https://github.com/oracle/node-oracledb/blob/v1.10.0/lib/pool.js#L176) and eventually failed with NJS-040.

**Comment by cjbj** [comment]
How many threads do you have? The doc has some good information about the use of connections and threads: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#numberofthreads
I'd start by bumping the number of threads, and/or decreasing the connection pool size. Then check that all your code paths are releasing connections.

**Comment by fedulovivan** [comment]
Actually I did not performed any analysis around threads utilization. But this is reproduced at very low traffic. Below is snapshot of counters, provided **\_logStats** right before first **NJS-040** has happened. Notice that value of counter **pool connections in use** is zero. I assume that **\_connectionsOut** is equal to **poolMax** at this moment, which is 20 in our certain case.
```
Pool statistics:
...total up time (milliseconds): 50588347
...total connection requests: 3507
...total requests enqueued: 60
...total requests dequeued: 58
...total requests failed: 0
...total request timeouts: 0
...max queue length: 2
...sum of time in queue (milliseconds): 1005
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 175
...avg time in queue (milliseconds): 17
...pool connections in use: 0
...pool connections open: 2
Related pool attributes:
...queueRequests: true
...queueTimeout (milliseconds): 60000
...poolMin: 0
...poolMax: 20
...poolIncrement: 1
...poolTimeout (seconds): 60
...stmtCacheSize: 30
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: undefined
```

**Comment by cjbj** [comment]
I don't have any super magic insight into your app's architecture or usage.  Try my earlier suggestions and do some debugging.  Let us know what you find.  I assume you've fixed your "application bug" too, right?

**Comment by fedulovivan** [comment]
Please use snippet below to reproduce issue.
The trick is our application is not terminating on uncaught exceptions.

```javascript
var oracledb = require('oracledb');
var requests = 20;
var poolMax = 10;
var counters = {obtained: 0, released: 0};
var uncaughtExceptionHandler = function(err) {
    console.error("[Uncaught Exception]\n", err.stack || err);
};
process.on('uncaughtException', uncaughtExceptionHandler);
oracledb.createPool({
    _enableStats: true,
    user: '***',
    password: '***',
    connectString: '192.168.1.***',
    poolMax: poolMax,
    queueTimeout: 1000
}, function(err, pool) {
    if (err) return console.error('createPool', err);
    while(requests > 0) {
        try {
            pool.getConnection(function(err, conn) {
                if (err) return console.error('getConnection', err);
                console.log('obtained');
                counters.obtained++;
                conn.execute('SELECT 1 FROM DUAL', function(err, result) {
                    if (err) return console.error('execute', err);
                    conn.release(function(err) {
                        if (err) return console.error('release', err);

                        // uncomment this to reproduce issue
                        // throw new Error('bazinga');

                        console.log('released');
                        console.log('_connectionsOut', pool._connectionsOut);
                        counters.released++;
                    });
                });
            });
        } catch (e) {
            console.error('caught exeption', e);
        }
        requests--;
    }
    setTimeout(function() {
        pool._logStats();
        console.log('_connectionsOut', pool._connectionsOut);
        console.log(counters);
    }, 5000);
});
```

**Comment by cjbj** [comment]
Help me out here: what exactly is the plan and which bits are you setting just for the example vs need/want to set in your real app?  

For a start, you are doing 20 requests with a connection pool of 10.  When I run your code with the `throw` commented, I see queue NJS-040 timeouts due to the small value of `queueTimeout`.  Is this what you see?  

Then there are counters after the commented `throw` call, so when I do uncomment that line those counters aren't going to be reached.  If I move the `throw` lower then when I run the script it finishes with `{ obtained: 10, released: 10 }` (and 10 requests were queued and timed out).  If I increase the value of `queueTimeout` then I get `{ obtained: 20, released: 20 }` (and can see that 10 requests were queued and dequeued).

A very small `queueTimeout` isn't going to help make the app resilient to load spikes.  Is this setting needed by the app (what is your aim by setting it low?), or is it just for this example?

**Comment by cjbj** [comment]
The other interesting test is to set `poolMin` higher, so that the connections are pre-created before the app does 'work'. The startup time is a bit higher but the initial `getConnection()` calls don't wait for connections to be established to the DB, so it all balances out.  This change improves throughput in this small test, and is another way to make the NJS-040's disappear if you have a short `queueTimeout`

**Comment by fedulovivan** [comment]
Please refer to lines 172-176 of [connection.js](https://github.com/oracle/node-oracledb/blob/v1.10.0/lib/connection.js)
if **releaseCb** throws an execption, **_onConnectionRelease** is not invoked, as a consequence [_connectionsOut](https://github.com/oracle/node-oracledb/blob/v1.10.0/lib/pool.js#L376) is growing.

**Comment by sagiegurari** [comment]
In addition, my question would be, why is the release callback called before the self._pool._onConnectionRelease();
if for any reason the self._pool._onConnectionRelease(); fails, the release callback should be called with the relevant error, no?

**Comment by cjbj** [comment]
Just a drive-by comment: you are looking at old code.

**Comment by sagiegurari** [comment]
that's true, didn't notice. 
With the new code it looks like the order of things is good.
wonder if this is reproducible with 1.12

**Comment by fedulovivan** [comment]
Right, interface of communication between pool and connection was reworked between 1.10 and 1.12, I assume is should not be reproducible with 1.12.

**Comment by fedulovivan** [comment]
@cjbj, I confirm this issue is **not reproduced** with *oracledb 1.11.0*

**Comment by cjbj** [comment]
@fedulovivan thanks for confirming it was already fixed.
@sagiegurari thanks, too, for your review.
