### ISSUE TITLE
Install issue on macOS

### ISSUE THREAD

**Issue by Gusbenz** [oracle/node-oracledb#563]
Hey all,

I've been working through some issues trying to get up and running. I've fixed some on my own by googling but I have seem to hit all wall with this one!

Any help would be great, and thank you for your time in advance! 

Error snippet can be found [here](https://gist.github.com/Gusbenz/e95adadb59c392b94fef32900ff63bf1)

I've followed issue template suggestions, but alas! 

1. See  [here](https://gist.github.com/Gusbenz/e95adadb59c392b94fef32900ff63bf1)

2. npm i oracle or npm install

3. Environment variables are set correctly, since I was facing that issue but seemed to have fixed it.

4. Tried on various versions of node via nvm. Node 6.9.2 was the first and no others have worked. Tried 3.3.1 and 4.7 also.

5. Oracle client (e.g. Instant Client) is 12.1

6. macOS 10.12.1 -- Sierra

7. gcc version is `Apple LLVM version 8.0.0`

Thanks very much again!

**Comment by cjbj** [comment]
The fundamental problem is that there are two Node add-ons with similar names.  We had lots of discussion about what name to use for the new extension and, well, it is what it is.

You are trying to install the old, unmaintained add-on.  Try `npm install oracledb` instead.  Note the 'db' at the end of the name. If you want to install the current 1.12.0-dev branch, use `npm install oracle/node-oracledb.git#v1.12.0-dev`

The OS X install instructions are [here](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx)

**Comment by Gusbenz** [comment]
Wow, ok. So sorry to have wasted your time! My googling confused my npm install commands. Works great. Thanks so much!

**Comment by cjbj** [comment]
No problems.
