### ISSUE TITLE
How to make createPool() or getConnection() async?

### ISSUE THREAD

**Issue by WindzCUHK** [oracle/node-oracledb#564]
My app needs to connect to multiple oracle DBs and run the same query.
Some of them may become inaccessible for few hours.

My connection code:
```js
const arrayOfConnAttrs = []; // my db destinations

arrayOfConnAttrs.forEach(function (connAttrs) {
  console.log(`start connect to ${connAttrs.connectString}`);
  oracledb.getConnection(connAttrs, function (err, conn) {

    console.log(`done connect to ${connAttrs.connectString}`);

    if (err) return;
    // some query code...
  });
});
```

### code output
14:00:00 start connect to [127.0.0.1:11111/a]
14:00:00 start connect to [127.0.0.1:22222/b]
14:00:00 start connect to [127.0.0.1:33333/c]

14:00:01 done connect to [127.0.0.1:11111/a]
14:00:10 done connect to [127.0.0.1:22222/b]
**14:00:11 done connect to [127.0.0.1:33333/c]**

In case b is inaccessible now, I got (connect in series, c will wait for b to timeout ???):

### But I expect (connect in parallel, no wait for b):
14:00:01 done connect to [127.0.0.1:11111/a]
**14:00:01 done connect to [127.0.0.1:33333/c]**
14:00:10 done connect to [127.0.0.1:22222/b]

I have tried to use createPool(). It is also the same. T.T

**Comment by cjbj** [comment]
'Inaccessible' could mean a few things.  I suspect you should tune the network parameters to make sure timeouts are faster. Create a file `$TNS_ADMIN/sqlnet.ora` (don't forget to set `TNS_ADMIN` so it is read!)  Then you can configure things like [`SQLNET.OUTBOUND_CONNECT_TIMEOUT`](http://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#NETRF427), [`SQLNET.RECV_TIMEOUT`](http://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#NETRF227), and [`SQLNET.SEND_TIMEOUT`](http://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#NETRF228). Others settings may apply depending on your circumstances or requirements.  You may also want to configure the OS TCP timeouts (e.g. see #443).  Finally you may want to create a `tnsnames.ora` file to configure the DB service setting [`('ENABLE=BROKEN')`](http://docs.oracle.com/database/122/NETRF/local-naming-parameters-in-tnsnames-ora-file.htm#NETRF431).

**Comment by WindzCUHK** [comment]
Thx for the settings.

For 'Inaccessible', I mean network disconnect or the DB process is killed.

As it is a middleware to server some users' ad-hoc DB queries, the services' address list cannot be preset in  `tnsnames.ora`.

Although the timeout settings can shorten the waiting time, is there ways to run getConnection() in parallel?

**Comment by cjbj** [comment]
Sounds like a special situation; it'll be worth reviewing and testing carefully - but you know that.

You could construct the full connection string in the app, a basic example is:
```javascript
connAttrs.connectString = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost.example.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=orcl)))";
```
These strings can be augmented with whatever options  that you need, such as `(ENABLE=BROKEN)`.

Regarding parallel connections, look at using the `async` package.

A way to speed up connections is to use [DRCP](https://github.com/oracle/node-oracledb/blob/v1.12.0-dev/doc/api.md#drcp), since this starts a pool of available DB process 'servers' that will be ready & waiting for connections, saving the cost of starting a server process for each connection.  You need to use a node-oracledb connection pool to use DRCP, but it can be as small as you want.

If you end up using connection pools, you probably want to use node-oracledb 1.12 with its new [`poolPingInterval`](https://github.com/oracle/node-oracledb/blob/v1.12.0-dev/doc/api.md#proppoolpoolpinginterval) parameter (and will want to use Oracle 12.2 client as soon as that becomes available - see the [pool pinging doc ](https://github.com/oracle/node-oracledb/blob/v1.12.0-dev/doc/api.md#connpoolpinging) for why).

**Comment by WindzCUHK** [comment]
Thank for the help. It is good to know that I can set the connection timeout in the connection string instead of the os env. outside the code.

I am not familiar with with the `async` package. But, I think is the underlying implementation of the getConnection() queue up my connection tasks (or some executor) and run them in series (that's why I need to wait for the previous connection to timeout before establishing the next connection). Would you mind to explain more on how to make it parallel using `async` package?

**Comment by sagiegurari** [comment]
http://caolan.github.io/async/docs.html#parallel

**Comment by cjbj** [comment]
(Thanks @sagiegurari!)

@WindzCUHK don't get tricked by not having enough [threads to do work](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#numberofthreads).

There is certainly some necessary serialization at various points due to the underlying OCI library, but take a look at async.  Since you seem to have a semi-special case that we don't really know, you may need a mix of solutions, including making sure connecting is very fast, maybe even possibly having multiple Node processes.

Here's one messy, hacked, test script I had for dedicated connections:

```javascript
'use strict';

//process.env.UV_THREADPOOL_SIZE=10

// A connect string that takes time to fail
var bogusConnectString = "www.google.com/xyz";

// Similulate a connection being used for this amount of millisecs
var SlowOpTime = 10000;

var connAttrs = require('./dbconfig.js');
var async = require('async');
var oracledb = require('oracledb');

var doconnect = function(v, cb) {
  let ts1 = (new Date().getTime() - starttime);
  let cs = (v == 5 ? bogusConnectString : connAttrs.connectString);
  console.log(`${v}: ${ts1} start connect to ${cs}`);
  oracledb.getConnection(
    {  user: connAttrs.user,
       password: connAttrs.password,
       connectString: cs
    },
    function (err, conn) {
      if (err) { console.log("Connection failed: " + err.message);}
    setTimeout(function() {  // simulate some work being done on a connection
      let ts2 = (new Date().getTime() - starttime);
      console.log(`${v}: ${ts2} done connect to ${cs}`);
      cb(null, {id:v, ts: ts2, cs: cs, connection: conn});  // don't pass back error for this example
    }, (v != 4 ? 0 : SlowOpTime));
  });
};

var starttime = new Date().getTime();

const arrayOfConnAttrs = [0,1,2,3,4,5,6,7,8,9];

async.map(
  arrayOfConnAttrs,
  doconnect,
  function (err, results) {
    var endtime = new Date().getTime();
    console.log("Total Time is " + (endtime-starttime) + " milliseconds");
    results.forEach(function(r) {
      console.log("Connection id: " + r.id + " connected at: " + r.ts + " to  " + r.cs + (r.connection ? ' connected' : ' not connected'));
    });
    if (err) {
      console.error("In waterfall error cb: ==>", err, "<==");
    }
  });
```

Output shows that all connections started close together.  There were only 4 threads so connections 0-3 had to complete first;

Connection #4 did 'work' for and extra 10 seconds.  Connection #5 failed.  With this particular async.map call, the final callback wasn't invoked until everything had finished.  You may or may not want that.

```
cjones@mac:~/n$ node issue564b.js 
0: 0 start connect to localhost/orcl
1: 18 start connect to localhost/orcl
2: 20 start connect to localhost/orcl
3: 20 start connect to localhost/orcl
4: 20 start connect to localhost/orcl
5: 20 start connect to www.google.com/xyz
6: 20 start connect to localhost/orcl
7: 20 start connect to localhost/orcl
8: 20 start connect to localhost/orcl
9: 20 start connect to localhost/orcl
2: 521 done connect to localhost/orcl
3: 522 done connect to localhost/orcl
0: 522 done connect to localhost/orcl
1: 524 done connect to localhost/orcl
6: 970 done connect to localhost/orcl
7: 1042 done connect to localhost/orcl
8: 1476 done connect to localhost/orcl
9: 1479 done connect to localhost/orcl
4: 10969 done connect to localhost/orcl
Connection failed: ORA-12170: TNS:Connect timeout occurred

5: 120719 done connect to www.google.com/xyz
Total Time is 120719 milliseconds
Connection id: 0 connected at: 522 to  localhost/orcl connected
Connection id: 1 connected at: 524 to  localhost/orcl connected
Connection id: 2 connected at: 521 to  localhost/orcl connected
Connection id: 3 connected at: 522 to  localhost/orcl connected
Connection id: 4 connected at: 10969 to  localhost/orcl connected
Connection id: 5 connected at: 120719 to  www.google.com/xyz not connected
Connection id: 6 connected at: 970 to  localhost/orcl connected
Connection id: 7 connected at: 1042 to  localhost/orcl connected
Connection id: 8 connected at: 1476 to  localhost/orcl connected
Connection id: 9 connected at: 1479 to  localhost/orcl connected
```

Uncommenting the UV_THREADPOOL_SIZE line gave a different output profile:

```
cjones@mac:~/n$ node issue564b.js 
0: 1 start connect to localhost/orcl
1: 19 start connect to localhost/orcl
2: 20 start connect to localhost/orcl
3: 20 start connect to localhost/orcl
4: 20 start connect to localhost/orcl
5: 20 start connect to www.google.com/xyz
6: 21 start connect to localhost/orcl
7: 21 start connect to localhost/orcl
8: 21 start connect to localhost/orcl
9: 21 start connect to localhost/orcl
0: 509 done connect to localhost/orcl
6: 544 done connect to localhost/orcl
2: 609 done connect to localhost/orcl
8: 631 done connect to localhost/orcl
1: 657 done connect to localhost/orcl
3: 721 done connect to localhost/orcl
7: 735 done connect to localhost/orcl
9: 754 done connect to localhost/orcl
4: 10738 done connect to localhost/orcl
Connection failed: ORA-12170: TNS:Connect timeout occurred

5: 120617 done connect to www.google.com/xyz
Total Time is 120617 milliseconds
Connection id: 0 connected at: 509 to  localhost/orcl connected
Connection id: 1 connected at: 657 to  localhost/orcl connected
Connection id: 2 connected at: 609 to  localhost/orcl connected
Connection id: 3 connected at: 721 to  localhost/orcl connected
Connection id: 4 connected at: 10738 to  localhost/orcl connected
Connection id: 5 connected at: 120617 to  www.google.com/xyz not connected
Connection id: 6 connected at: 544 to  localhost/orcl connected
Connection id: 7 connected at: 735 to  localhost/orcl connected
Connection id: 8 connected at: 631 to  localhost/orcl connected
Connection id: 9 connected at: 754 to  localhost/orcl connected
```

**Comment by WindzCUHK** [comment]
@cjbj Really thanks a lot.

`UV_THREADPOOL_SIZE` is what I want. I don't believe I missed this setting in the doc...

Btw, is there any differences in term of execution sequence in the code below?
```
const myCallbackForAllConnection;
const arrayOfConnAttrs = [];
const tasks = arrayOfConnAttrs.map( ca => oracledb.getConnection.bind(ca) );
async.parallel(tasks, myCallbackForAllConnection);
```

```
const myCallbackForEachConnection;
const arrayOfConnAttrs = [];
arrayOfConnAttrs.forEach( ca => oracledb.getConnection(ca, myCallbackForEachConnection) );
```
