### ISSUE TITLE
Secure data pull from remote oracle database as json into Node application server

### ISSUE THREAD

**Issue by sohaib-khan** [oracle/node-oracledb#567]
Hi Team,
We are developing an application and using node driver for oracle. I want to know if the data pulled from the remote oracle database using this package secure if not how can we make the data delivered from remote oracle database server into node secure or encrypted.

Please advise.

**Comment by dmcghan** [comment]
@sohaib-khan Are you referring to encrypting the data as it travels between the database and client (Node.js app)? If so, have you seen [this thread](https://github.com/oracle/node-oracledb/issues/411#issuecomment-230881031)?

**Comment by sohaib-khan** [comment]
@dmcghan Yes secure connection between database and client node.js app. So when do we set those variable to get the encryption. We compiling node-oracledb in ubuntu. These variable need to be in oracle database sqlnet.ora? If so then maybe that is not a option for us as we do not have access to client oracle database and are not able to change such parameters?

**Comment by sohaib-khan** [comment]
@dmcghan Does the following sequence looks ok to get the secure connection? Did I understand the thread properly?

Create sqlnet.ora file:
---------------------------------------------------------------------
vi /opt/oracle/conf/sqlnet.ora

Add the following lines:
---------------------------------------------------------------------
SQLNET.CRYPTO_CHECKSUM_TYPES_CLIENT = (MD5)
SQLNET.ENCRYPTION_TYPES_CLIENT = (AES256)
SQLNET.ENCRYPTION_CLIENT = required
SQLNET.CRYPTO_CHECKSUM_CLIENT = required


Add the TNS_ADMIN variable in the sequence below and install via npm:
---------------------------------------------------------------------
export ORACLE_HOME=/opt/oracle/instantclient
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME
export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
export TNS_ADMIN=/opt/oracle/config
export OCI_LIB_DIR=/opt/oracle/instantclient
export OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
npm install oracledb

**Comment by cjbj** [comment]
Security is a specialist topic. I'd recommend reviewing documentation including: http://docs.oracle.com/database/122/DBSEG/keeping-your-oracle-database-secure.htm#DBSEG504 and http://docs.oracle.com/database/122/DBSEG/configuring-network-data-encryption-and-integrity.htm#DBSEG9581 not to mention https://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#NETRF182

I did note that you have unnecessarily set ORACLE_HOME.  You don't need to set it.

Also OCI_*_DIR are install-time variables.  LD_LIBRARY_PATH and TNS_ADMIN are runtime settings, so generally you don't need both pairs set at the same time.

**Comment by sohaib-khan** [comment]
@cjbj Thanks for the input. 

So what I have done is used SQLNET.ENCRYPTION_CLIENT=requested in sqlnet.ora and before I start node.js TNS_ADMIN env variable is set to point to the sqlnet.ora.

**Comment by cjbj** [comment]
@sohaib-khan in the DB doc I linked to, it shows how to configure this on the DB side, so that all clients use encryption and don't depend on having a client-side (aka for Node.js) sqlnet.ora file.
