### ISSUE TITLE
Does not install on Windows 10 Pro x64, NodeJS 6.9.2

### ISSUE THREAD

**Issue by radio-miskovice** [oracle/node-oracledb#569]
Cannot install on Windows 10 Pro x64, NodeJS 6.9.2.

I have VS Express and Visual Studio 2015.  For some strange reason, this driver insists on using the obsolete Visual Studio 2010.  It suggests to edit oracledb.vcxproj in the node_modules tree - but this file woud be overwritten by npm in the next installation attempt.

NPM LOG:

C:\dev\dbdesign> npm i --save oracledb

> oracledb@1.11.0 install C:\DEV\dbdesign\node_modules\oracledb
> node-gyp rebuild

C:\DEV\dbdesign\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\bin\nvm\v6.9.2\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset
 = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\DEV\dbdesign\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\bin\nvm\v6.9.2\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\bin\\nvm\\v6.9.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\DEV\dbdesign\node_modules\oracledb
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "oracledb" 
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\DEV\dbdesign\npm-debug.log

**Comment by radio-miskovice** [comment]
I forgot to mention I have Oracle Instant Client Basic & SDK installed in C:\oracle\instantclient_12_1 but I think it does not matter because the compilation does not even start.

Frankly, I don't quite understand why this module uses C++ compilation, which is always a big problem in any NodeJS module on Windows, and not Java, which more or less works much more reliably...

**Comment by cjbj** [comment]
From your comment on #18, it seems like you don't need help?  If you do, you'll need to add more detail about what you have installed and where.  And also be more technical about what 'insists' means.

**Comment by radio-miskovice** [comment]
Yes, I eventually found the answer to my problem elsewhere.  Thanks for help...

"insists" means what is in the error log: 

> error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset
= 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools. 

Well, since we live in the end of 2016, I do not intend to install VS2010... That's why I used the i-word.

What tools I have instaled, and where, is all mentioned in my post, by the way :-) I followed all the recommendations.

In my opinion it would be nice if you actually tried to do something with this package if it really is intended for the Windows platform as well - such as improved detection of what is the actual development framework installed (there are only a few possibilities, so I suppose it is not a big deal).

Also, I would have appreciated having a link to the compiled binary version of the driver. This "go find yourself" from people who actually **know** there is a solution to a frequently occurring problem is something I do not like in general.

**Comment by AlokBansal8** [comment]
@cjbj this is very problematic for some of us to get stuck with this library on windows. Please fix the library.

**Comment by Anantha-R** [comment]
Set the visual studio version which you have in your local to Npm by running below command.
npm config -g set msvs_version 2015
