### ISSUE TITLE
fail to install driver in an offline windows server 2008 environment

### ISSUE THREAD

**Issue by imrosenkavalier** [oracle/node-oracledb#57]
Hi Experts,

I'm running a project to let Javascript connect to Oracle 11g Database.

My server environment is Windows Server 2008 R2 , 64 bit.

I followed installation steps but encountered problem on install driver step.

I installed following components
  1.Microsoft Visual C++ 2010 SP1 Redistributable Package (x64)
  2.Git-1.9.5
  3.node-v0.10.0-x64

Since it's an offline environment, I downloaded "node-oracledb-master.zip" and extracted it.

I also download instantclient-basic-windows.x64-12.1.0.2.0.zip and instantclient-sdk-windows.x64-12.1.0.2.0.zip, then copy this two folders under C:\Oracle\instantclient.

before installed the driver, I also set OCI_LIB_DIR and OCI_INC_DIR with following commands:
set OCI_LIB_DIR=C:\Oracle\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\Oracle\instantclient\sdk\include

But if I ran the command "npm install -g" I got following error:

	C:\Users\admin\AppData\Roaming\npm\node_modules\oracledb>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
	\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
	gyp http GET http://nodejs.org/dist/v0.10.0/node-v0.10.0.tar.gz
	gyp WARN install got an error, rolling back install
	gyp ERR! configure error
	gyp ERR! stack Error: getaddrinfo ENOTFOUND
	gyp ERR! stack     at errnoException (dns.js:37:11)
	gyp ERR! stack     at Object.onanswer [as oncomplete] (dns.js:124:16)
	gyp ERR! System Windows_NT 6.1.7601
	gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
	gyp ERR! cwd C:\Users\admin\AppData\Roaming\npm\node_modules\oracledb
	gyp ERR! node -v v0.10.0
	gyp ERR! node-gyp -v v0.8.5
	gyp ERR! not ok
	npm ERR! oracledb@0.3.1 install: `node-gyp rebuild`
	npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
	npm ERR!
	npm ERR! Failed at the oracledb@0.3.1 install script.
	npm ERR! This is most likely a problem with the oracledb package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls oracledb
	npm ERR! There is likely additional logging output above.

	npm ERR! System Windows_NT 6.1.7601
	npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"   "install" "-g"
	npm ERR! cwd C:\node-oracledb
	npm ERR! node -v v0.10.0
	npm ERR! npm -v 1.2.14
	npm ERR! code ELIFECYCLE
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     C:\node-oracledb\npm-debug.log
	npm ERR! not ok code 0

Do I miss something? Please help me figure out how to fix the problem, thank you~

**Comment by alexsantos** [comment]
From the log, it is trying to get the node source code. Have you tried
downloading the node source package and compiling it instead of getting the
binary?
Alex
Em 24/03/2015 07:42, "imrosenkavalier" <notifications@github.com> escreveu:

**Comment by imrosenkavalier** [comment]
Hi Alex
Thanks for your reply. 
I'm really new about this tool and I'm not sure what should I do.
I uninstall node.js installed by MSI and then download node-v0.10.0.tar.gz and extracted it into a specific folder.
I also add the folder to path variable.
But I cannot use npm command, instead I try to input "vcbuild.bat test" and got following message:
"Failed to create vc project files."
Should I do any manual configuration to the source package then retry the npm command?
Thanks for your help again~

Wade

**Comment by alexsantos** [comment]
Hi Wade,
I never installed node on a Windows machine :-) Maybe someone here with
that experience might help you a little more.
Have you tried compiling node from source instead of the msi binary?
Alex

2015-03-24 8:35 GMT+00:00 imrosenkavalier <notifications@github.com>:

**Comment by imrosenkavalier** [comment]
Hi Alex,
Sorry, I don't know how to compile node from source.
Where can I find the command list for this tool?

Wade

**Comment by Bigous** [comment]
Hi @imrosenkavalier ,
If you can perform the development in a similar environment, but online, you could copy your entire directory from your development environment to the offline server.
Normally this works well on Windows.

**Comment by alexsantos** [comment]
Hi Wade,
look here for node-gyp: https://github.com/TooTallNate/node-gyp
There it explains that "node-gyp downloads the necessary development files
for the target version"


2015-03-24 10:05 GMT+00:00 imrosenkavalier <notifications@github.com>:

**Comment by cjbj** [comment]
@imrosenkavalier if you really are using Node.js 0.10.0 then try a more recent version of Node.js.  See https://github.com/oracle/node-oracledb/issues/49#issuecomment-84997485

I'm hesitant to semi-arbitrarily require  >= 0.10.35 in package.json, but maybe I should.

**Comment by Bigous** [comment]
@cjbj /agree
