### ISSUE TITLE
Examples/Documentation code not working with Promises

### ISSUE THREAD

**Issue by ashutoshmittal2309** [oracle/node-oracledb#570]
Describe exactly what you did and what you want to happen.

I was  trying to use the node-oracledb module on mac  and was able to connect successfully but as per documentation the first parameter in the response function is "Err" and second is "Connection" or "Result"
I used the same on Mac but when i am running against Oracle 1102000400 i am seeing the the values are interchanged and i am seeing Connection/Resultset values in first parameter. Below code is working for me and not the one under documentation -

In below code when i get a response i have to set "Connection" as the first parameter but while in examples and documentation it is set as second parameter.

 **oracleDB.getConnection(connectionData).then(**function(connection, err)** {
        if(err !== undefined) {
            console.error("Error during connection - " + err.message);
            return;
        }
        console.log('Connection successful' + connection);

        connection.execute("<Select Query>").then(**function(result, err)** {
            console.dir(result);
        });**

Is this expected behavior for Mac machine and does it vary by the O/S being used.

#### Answer the following questions:

1. What error(s) you are seeing?

As mentioned above i have to write code differently than what is mentioned in documentation for Mac machine

4. What is your version of Node.js?
v4.4.0

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
12_1

6. What is your OS and version?

Darwin 80e65001f7be 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

**Comment by cjbj** [comment]
Take a look at this example: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#promiseoverview

**Comment by ashutoshmittal2309** [comment]
Yes, I checked this but if you look at any of the examples they are written differently which is not working for me.

**Comment by cjbj** [comment]
All examples except that section on Promises use standard callback style.  They are not expected to work with Promises unless you change the syntax.  Documentation on methods shows the two different prototypes for callback and Promise usage, for example the [`execute()` documentation](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#execute )  has

> ##### Prototype
> 
> Callback:
> ```
> execute(String sql, [Object bindParams, [Object options,]] function(Error error, [Object result]){});
> ```
> Promise:
> ```
> promise = execute(String sql, [Object bindParams, [Object options]]);
> ```
> 

You can follow either style that you find comfortable with.

**Comment by ashutoshmittal2309** [comment]
Thanks a lot for this and it really helps. This was my first time trying the module out and i went traditional promise way i am used too while looking at the examples.
I missed few details in that which caused this. Thanks for your help.

**Comment by cjbj** [comment]
No problem.  If you have suggestions or PR's let us know.

Don't forget the doc on the master branch is for 1.12.0-dev which can only be installed from GitHub, not npmjs.com
