### ISSUE TITLE
why slow when execute select statement with like condition

### ISSUE THREAD

**Issue by JackFong** [oracle/node-oracledb#571]
i want to execute select statement with like condition
execute('select * from table where c1 like :cp', { cp: { val: '%' + clv, dir: oracledb.BIND_IN, type: oracledb.STRING } }, null)
this sql only return one row, but it cost 14s to get result.
so i change code to:
execute('select * from table where c1 like \'%' + clv + '\'', [], null)
this time only cost 534ms to get result.

so what different between two methods ?

**Comment by dmcghan** [comment]
@JackFong There shouldn't be a difference. The code you're showing use doesn't look valid (nested quotes). Can you provide a reproducible test case?

**Comment by cjbj** [comment]
I'd first test the two variants in SQL*Plus and check the query execution plan and costs (see [SET AUTOTRACE](http://docs.oracle.com/database/122/SQPUG/tuning-SQL-Plus.htm#SQPUG534)).  This will rule out any optimizer differences.  Then make sure your node-oracledb tests are 'fair' and there is no caching going on in one but not the other.

**Comment by cjbj** [comment]
Closing - no update.
