### ISSUE TITLE
Oracle 12c R2 release support

### ISSUE THREAD

**Issue by sonia1588** [oracle/node-oracledb#578]
Does oracledb node module support Oracle 12c R2 release -  Cloud first?

**Comment by dmcghan** [comment]
@sonia1588 I've done some tests against the 12.2 Exadata Express cloud service, seems to work fine.

**Comment by cjbj** [comment]
If you are connecting to Exadata Express then get the updated 12.1 client: http://www.oracle.com/technetwork/database/database-technologies/scripting-languages/cloud-3080568.htmlIf using DBCS you can use other client versions.
