### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jctransfi** [oracle/node-oracledb#581]
I've been having some issues installing (or rather reinstalling) the oracledb module. We were coming from 0.7.0 and recent efforts to update node and npm have resulted in some issue reinstalling the module.

Tried cleaning npm cache and deleting $HOME/.node-gyp as well. Also ran into the nan module not being found. Tried to manually install nan as well.

The latest error is in the following gist

https://gist.github.com/jctransfi/923d025b87749b208883e627b2beae18

**Comment by cjbj** [comment]
Check the first error: https://gist.github.com/jctransfi/923d025b87749b208883e627b2beae18#file-gistfile1-txt-L10

You don't mention the platform but for Oracle Linux, you can get an updated compiler from https://yum.oracle.com.  See https://docs.oracle.com/cd/E52668_01/E59096/html/section_e3v_nbl_cr.html

Or upgrade to a more recent OS version such as Oracle Linux 7.

**Comment by jctransfi** [comment]
Ugh. My bad Christopher. Went through a couple of upgrades elsewhere as well and missed this completely.

**Comment by cjbj** [comment]
@jctransfi don't worry; it's a common 'gotcha'.
