### ISSUE TITLE
NJS-010: unsupported data type in select list (TIMESTAMP WITH TIME ZONE)

### ISSUE THREAD

**Issue by ggrimbert** [oracle/node-oracledb#585]
Hi, 

I am having this error  while trying to select data from TIMESTAMP WITH TIME ZONE type.
```
NJS-010: unsupported data type in select list
```

I've seen https://github.com/oracle/node-oracledb/issues/160, but fetch as string doesn't work.

I've setted it like this : 
```js
this.lib = require('oracledb');
this.lib.maxRows = 500;
this.lib.Promise = require('bluebird');
this.lib.fetchAsString = [ this.lib.DB_TYPE_TIMESTAMP_TZ, this.lib.DB_TYPE_DATE, this.lib.DB_TYPE_TIMESTAMP, this.lib.DB_TYPE_TIMESTAMP_LTZ ];
```

In fact, it seems that the fetchAsString doesn't do anything, I tried setting just this.lib.DB_TYPE_TIMESTAMP_TZ but it doesn't work neither.

the sql commands passed are : 
```sql
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE users (id NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, dateField TIMESTAMP WITH TIME ZONE NULL,CONSTRAINT PKusersid PRIMARY KEY (id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "groups" (id NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, dateField TIMESTAMP WITH TIME ZONE NULL,CONSTRAINT PKgroupsid PRIMARY KEY (id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE group_user (createdAt TIMESTAMP WITH TIME ZONE NOT NULL, updatedAt TIMESTAMP WITH TIME ZONE NOT NULL, userId, groupId,CONSTRAINT PKgroup_useruserIdgroupId PRIMARY KEY (userId, groupId),CONSTRAINT FKgroup_useruserId FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE ,CONSTRAINT FKgroup_usergroupId FOREIGN KEY (groupId) REFERENCES "groups" (id) ON DELETE CASCADE )'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
INSERT INTO users (id,dateField) VALUES (DEFAULT,TO_TIMESTAMP('2014-02-20 00:00:00.00','YYYY-MM-DD HH24:MI:SS.FF')) RETURNING id INTO :id
INSERT INTO "groups" (id,dateField) VALUES (DEFAULT,TO_TIMESTAMP('2014-02-20 00:00:00.00','YYYY-MM-DD HH24:MI:SS.FF')) RETURNING id INTO :id
SELECT createdAt, updatedAt, userId, groupId FROM group_user group_user WHERE group_user.userId = 1 AND group_user.groupId IN (1)
```

There's no insert in group_user anymore, first a select is made, then the insert and after another select, but the select on group_user fails.

**Comment by dmcghan** [comment]
@ggrimbert Please provide _reproducible_ test cases. A reproducible test case should be more complete, perhaps a SQL script to create database objects and a complete JavaScript script that demonstrates the issue.

If I run your SQL commands, I create 3 tables, insert rows into 2 of them, and then try to select a row from the third which doesn't have any rows.

**Comment by ggrimbert** [comment]
You have the reproducible test case in my previous post.

The test case is selecting with an empty table. As I said, First a select, then an insert and Finally another select.

The problem appears at the first select (the test fails as Oracle returns an error, so insert isn't made).

I'm not complaining about the select that returns nothing, but about the Select statement on the table (which is not populated at the time the select query is made) that returns an error NJS-010

**Comment by dmcghan** [comment]
@ggrimbert Neither this or the other post has a reproducible test case. I want to copy/paste your JavaScript code, maybe run an npm install, and then be able to run the script and see the error you're getting.

**Comment by dmcghan** [comment]
@ggrimbert Give me a few minutes, I will create a reproducible test case for you to explain what I mean.

**Comment by dmcghan** [comment]
@ggrimbert Okay, it would be great to get something like this from you:

```javascript
var oracledb = require('oracledb');
var config = require('./dbConfig.js');

oracledb.fetchAsString = [ 
  oracledb.DB_TYPE_TIMESTAMP_TZ, 
  oracledb.DB_TYPE_DATE, 
  oracledb.DB_TYPE_TIMESTAMP, 
  oracledb.DB_TYPE_TIMESTAMP_LTZ
];

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }

  connection.execute(
    ` create table tswtz_test (
        createdat TIMESTAMP WITH TIME ZONE NOT NULL
      )
    `,
    function(err, result) {
      if (err && err.message != 'ORA-00955: name is already used by an existing object\n') {
        throw err;
      }

      connection.execute(
        'select createdat from tswtz_test',
        function(err, result) {
          if (err) {
            throw err;
          }

          console.log(result.rows);
          console.log('test complete');

          connection.close(function(err) {
            if (err) {
              throw err;
            }
          });
        }
      );
    }
  );
});
```

Notice that I've eliminated code that's not related to the problem being described. If you give this to me, I can immediately reproduce the problem.

Okay, now onto the solution...

Looking at the [doc for oracledb.fetchAsString](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbfetchasstring), it says:
> The valid types that can be mapped to strings are DATE, NUMBER and CLOB.

This works:
```javascript
var oracledb = require('oracledb');
var config = require('./dbConfig.js');

oracledb.fetchAsString = [ 
  oracledb.DATE
];

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }

  connection.execute(
    ` create table tswtz_test (
        createdat TIMESTAMP WITH TIME ZONE NOT NULL
      )
    `,
    function(err, result) {
      if (err && err.message != 'ORA-00955: name is already used by an existing object\n') {
        throw err;
      }

      connection.execute(
        'select createdat from tswtz_test',
        function(err, result) {
          if (err) {
            throw err;
          }

          console.log(result.rows);
          console.log('test complete');

          connection.close(function(err) {
            if (err) {
              throw err;
            }
          });
        }
      );
    }
  );
});
```

**Comment by ggrimbert** [comment]
I see what you wanted to say, sorry for not doing it before, I thought that just sql queries would have been enough.

I've modified this to use promises and to have the same parameters as in Sequelize : 
```js
var oracledb = require('oracledb');
var config = require('./dbConfig.js');
oracledb.Promise = require('bluebird');
oracledb.maxRows = 500;

oracledb.fetchAsString = [ 
  oracledb.DATE
];

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }

  connection.execute(
    `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE users (id NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, dateField TIMESTAMP WITH TIME ZONE NULL,CONSTRAINT PKusersid PRIMARY KEY (id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`, [],{ outFormat: 4002, autoCommit: true })
   .then(result => {
	   console.log('1');
		connection.execute(
        `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "groups" (id NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, dateField TIMESTAMP WITH TIME ZONE NULL,CONSTRAINT PKgroupsid PRIMARY KEY (id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`, [],{ outFormat: 4002, autoCommit: true })
        .then(result => {
			console.log('2');
			connection.execute(
			`BEGIN EXECUTE IMMEDIATE 'CREATE TABLE group_user (createdAt TIMESTAMP WITH TIME ZONE NOT NULL, updatedAt TIMESTAMP WITH TIME ZONE NOT NULL, userId, groupId,CONSTRAINT PKgroup_useruserIdgroupId PRIMARY KEY (userId, groupId),CONSTRAINT FKgroup_useruserId FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE ,CONSTRAINT FKgroup_usergroupId FOREIGN KEY (groupId) REFERENCES "groups" (id) ON DELETE CASCADE )'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`, [],{ outFormat: 4002, autoCommit: true })
			.then(result => {
				console.log('3');
				connection.execute(
				`INSERT INTO users (id,dateField) VALUES (DEFAULT,TO_TIMESTAMP('2014-02-20 00:00:00.00','YYYY-MM-DD HH24:MI:SS.FF'))`, [],{ outFormat: 4002, autoCommit: true })
				.then(result => {
					console.log('4');
					connection.execute(
					`INSERT INTO "groups" (id,dateField) VALUES (DEFAULT,TO_TIMESTAMP('2014-02-20 00:00:00.00','YYYY-MM-DD HH24:MI:SS.FF'))`, [],{ outFormat: 4002, autoCommit: true })
					.then(result => {
						console.log('5');
						connection.execute(
						`SELECT createdAt, updatedAt, userId, groupId FROM group_user group_user WHERE group_user.userId = 1 AND group_user.groupId IN (1)`, [],{ outFormat: 4002, autoCommit: true })
						.then(result => {
							console.log('6');
							connection.close();
						});
					});
				});
			});
		});
	})
	.catch(error => {
		connection.close();
		throw error;
	});
});
```

This works, on the same DB, using the sames queries...
But this still fails with Sequelize. What I don't understand is that these are the same queries, the same way of calling them (execute with same parameters), and it fails.

**Comment by dmcghan** [comment]
@ggrimbert  Hmmm... Is there a place we can read the code you're writing for Sequelize?

**Comment by ggrimbert** [comment]
I'll see if I can push my code on our github and give you access.

By the way thanks for helping

**Comment by ggrimbert** [comment]
I tried again this morning after replacing the initialization code inside Sequelize by yours, and this works...
Don't know what happened but this works now.

For now, I don't understand how I am supposed to work with the date returned. I've got this : 
```
09-JAN-17 09.18.36.363600 AM +00:00
```

How can I format this to get a real Date object ?

**Comment by dmcghan** [comment]
@ggrimbert Glad to hear it's working now.

> For now, I don't understand how I am supposed to work with the date returned.

The driver will normally return a JS date object, but you asked for a string via fetchAsString so you got a string back. When you do this, the values of `NLS_DATE_FORMAT`, `NLS_TIMESTAMP_FORMAT`, and `NLS_TIMESTAMP_TZ_FORMAT` are used to convert the Oracle datetime value to a string. You could set those to a format that JavaScript can parse with the date constructor.

But why not just get the JS date?

Also, when inserting, why don't you bind using a JS date instead of a string?

**Comment by cjbj** [comment]
@ggrimbert leaving aside the specific issues which @dmcghan is discussing with you, one question is how would you expect a query for a TIMESTAMP WITH TIME ZONE column to represent the date and timezone in JavaScript?  Do you care about the TIME ZONE?

**Comment by ggrimbert** [comment]
I was expecting that the string returned by Oracle would be a Javascript format, so I can directly make a new date() of this String. And the date i wass having is ```20-FEB-14 12.00.00.000000 AM +01:00``` and a new Date with this returns the error ```invalid date```.

I need the timezone, as the date is inserted with +00:00, I need the timezone to come back and get the same date, with same hour.

For the date Sequelize tried to insert (20/02/2014 00:00:00 +00:00), if I don't care about the timezone, I get the 19/02/2014 23:00:00 +01:00), so the date is incorrect.

But using  ```TIMESTAMP WITH LOCAL TIME ZONE``` and inserting using ```TO_TIMESTAMP_TZ```, I have the result that I want.

**Comment by cjbj** [comment]
@ggrimbert TIMESTAMP WITH TIME ZONE means that there is a specified TIME ZONE that someone thought important to know about.  How would you like to see that handled in JS.  Should the driver return a non-JS date object that has the date & the time zone?

If you haven't seen it, check out https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#datehandling and @dmcghan's https://jsao.io/2016/09/working-with-dates-using-the-nodejs-driver/

**Comment by cjbj** [comment]
node-oracledb v2 now supports TIMESTAMP WITH TIMEZONE natively.  See https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github and check the [doc](https://github.com/oracle/node-oracledb/blob/dev-2.0/doc/api.md) for details.
