### ISSUE TITLE
ORA-56600 corrupts the connection

### ISSUE THREAD

**Issue by zeodtr** [oracle/node-oracledb#587]
The connection corruption occurs with the following conditions:

1. There is a table with a varchar2 column, and has one or more records
1. execute('select...') is called for that table with the bind parameter with the number type (which mismatches with the actual column type)

The flow is as follows:

1. When the execute('select...') is called for the first time, ORA-01722 error is returned.
1. But for the second time and onward it returns `ORA-56600: DRCP: Illegal call [First call inconsistency]`.
1. After that, even the call with the correct data type parameter also returns `ORA-56600: DRCP: Illegal call [First call inconsistency]`, seemingly when the same connection is used from the pool.

**How to reproduce the error**

First, create the table and insert a record as follows: (if the table has no records, no error occurs (even no ORA-01722))

```
create table ORA_56600_TEST ( TEST_COL varchar2(10) );
insert into ORA_56600_TEST values('abc');
commit;
```

Then, Run the following code (replace the '****' in the options of the createPool call with the actual values.)

```javascript
'use strict';

function illegalCallTest()
{
    var oracledb = require('oracledb');
    var pool;

    oracledb.autoCommit = true;
    oracledb.createPool(
        {
            connectString: '****/****:POOLED',
            user         : '****',
            password     : '****',
            poolMin      : 1,
            poolMax      : 2,
            poolIncrement: 1,
            poolTimeout  : 2
        }, function (err, _pool)
    {
        if (err) { console.error('ERROR: oracledb.createPool', err); return; }
        console.log('pool created');
        pool = _pool;
        setTimeout(doIllegalCall, 500);
        setInterval(doIllegalCall, 7000);
        setInterval(doNormalCall, 2500);
    });

    // ORA-56600: DRCP: Illegal call [First call inconsistency]
    function doIllegalCall()
    {
        pool.getConnection(function (err, conn)
        {
            if (err) { console.error('doIllegalCall: getConnection', err); return; }
            conn.execute("select * from ORA_56600_TEST where TEST_COL = :1", [ 2 ],
                function (err, results)
            {
                if (err) { console.error('ERROR: doIllegalCall: execute', err); }
                else { console.log('doIllegalCall: execute: success'); }
                conn.release(function (err)
                {
                    if (err) { console.error('ERROR: doIllegalCall: releaseConnection', err); }
                });
            });
        })
    }

    // normal
    function doNormalCall()
    {
        pool.getConnection(function (err, conn)
        {
            if (err) { console.error('ERROR: doNormalCall: getConnection', err); return; }
            conn.execute("select * from ORA_56600_TEST where TEST_COL = :1", [ '2' ],
                function (err, results)
            {
                if (err) { console.error('ERROR: doNormalCall: execute', err); }
                else { console.log('doNormalCall: execute: success'); }
                conn.release(function (err)
                {
                    if (err) { console.error('ERROR: doNormalCall: releaseConnection', err); }
                })
            });
        })
    }
}

console.log('starting');
illegalCallTest();
```

When the above code is running, you can see that the doNormalCall() mostly returns ORA-56600, but occasionally succeeds. I think that's because that the corrupt connection times out and discarded, then it receives a fresh connection.

**Environments**

* Environment variables
    * OCI_INC_DIR=C:\Oracle\instantclient\sdk\include
    * OCI_LIB_DIR=C:\Oracle\instantclient\sdk\lib\msvc
* Node.js version: v4.4.5
* oracledb node module version: 1.12.2
    * (I've also tested with 1.9.3. The symptom is almost the same, but it does not return ORA-01722 for the first call - instead it always returns ORA-56600.)
* Instant client
    * Version: 12.1.0.2.0
    * Installed location: C:\Oracle\instantclient
    * Install method: unzip
* OS
    * client: Windows 10
    * DB server: Windows 2012
* Oracle version: 12.1.0.1.0
* Compiler version: Visual Studio 2013 version 12

**Comment by cjbj** [comment]
@zeodtr an interesting little testcase that we will investigate.  The best solution may be to add 56600 to [this switch list](https://github.com/oracle/node-oracledb/blob/v1.12.2/src/dpi/src/dpiConnImpl.cpp#L555) so you only see the ORA-56600 once.  A change I'd like to get in regarding statement caching (to not cache statements that error) may also help.

**Comment by zeodtr** [comment]
@cjbj Thanks for the reply. I think that returning ORA-01722 seems more appropriate, if the situation permits.

BTW, More information is as follows: (Maybe these can serve as hints.)

* When the column type is NUMBER and the value type for the binding variable is string, the error occurs only when the value cannot be cast to the NUMBER type (that is, the string value has non-digit character)
* If the table has more columns, the situation gets more complex. When WHERE clause references multiple columns and the predicates for the other columns that have the binding variables (those have correct data type) guarantee that no record will be selected, no error occurs.

**Comment by cjbj** [comment]
@zeodtr In 1.13 the error ORA-56600 will trigger a session drop when a connection is released back to the pool.  This means it won't be reused, and a new, usable session will be created next time the pool grows.  You will still see the ORA-56600 once.

**Comment by zeodtr** [comment]
@cjbj Thank you!
