### ISSUE TITLE
Fail to install node-oracledb at Windows 7 Desktop.

### ISSUE THREAD

**Issue by amaruak00** [oracle/node-oracledb#59]
Hello.
I tried to solve this problem by myself, but there is some errors and I can't solve this.

Specification:
OS : MS Windows 7 32bit
Node : v0.10.36
(at first, I tried to install this module at v0.12 nodejs, but I saw that version is not supported now, so I downgraded node.js to v0.10.36)

I followed every steps below :
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin

It may has a same environment except OS is not 64 bit, but 32 bit(x86).
(So I installed all programs supporting 32 bit OS.)

I caught errors below(Language: Korean):

C:\nodejs\node-oracledb>npm install -g

> oracledb@0.4.1 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb
> node-gyp rebuild

C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb>node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
이 솔루션의 프로젝트를 한 번에 하나씩 빌드합니다. 병렬 빌드를 사용하려면 "/m" 스위치를 추가하십시오.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsMessages.cpp
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\njs\src\njsMe
ssages.cpp) [C:\Users\Administrator
\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiEnv.cpp
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\njs\src\njsOr
acle.cpp) [C:\Users\Administrator\A
ppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\njs\src\njsCo
nnection.cpp) [C:\Users\Administrat
or\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\njs\src\njsPo
ol.cpp) [C:\Users\Administrator\App
Data\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiEn
v.cpp) [C:\Users\Administrator\AppD
ata\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(554): warning C4244: '인수' : 'sb8'에서 'size_t'(으)로 변환하면서 데이터가 손실될 수 있습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\
oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(559): warning C4244: '인수' : 'sb8'에서 'size_t'(으)로 변환하면서 데이터가 손실될 수 있습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\
oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(615): warning C4244: '인수' : 'sb8'에서 'size_t'(으)로 변환하면서 데이터가 손실될 수 있습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\
oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(827): warning C4244: '인수' : 'sb8'에서 'size_t'(으)로 변환하면서 데이터가 손실될 수 있습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\
oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(833): warning C4244: '인수' : 'sb8'에서 'size_t'(으)로 변환하면서 데이터가 손실될 수 있습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\
oracledb.vcxproj]
  dpiEnvImpl.cpp
C:\Users\Administrator\.node-gyp\0.10.36\deps\v8\include\v8.h(184): warning C4506: 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' 인라인 함수에 대한 정의가 없습니
다. (..\src\nj
s\src\njsPool.cpp) [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\Administrator\.node-gyp\0.10.36\deps\v8\include\v8.h(184): warning C4506: 'v8::Persistent<v8::FunctionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' 인

라인 함수에 대한 정의가 없습니다. (..\src\njs\src\njsPool.cpp) [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\Administrator\.node-gyp\0.10.36\deps\v8\include\v8.h(184): warning C4506: 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' 인라인 함수에 대한 정의가 없습니
다. (..\src\nj
s\src\njsOracle.cpp) [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\Administrator\.node-gyp\0.10.36\deps\v8\include\v8.h(184): warning C4506: 'v8::Persistent<v8::FunctionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' 인

라인 함수에 대한 정의가 없습니다. (..\src\njs\src\njsOracle.cpp) [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiException.cpp
  dpiExceptionImpl.cpp
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\vector(60): warning C4506: 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' 인라인 함수에 대한 정의가 없습
니다. (..\src\n
js\src\njsConnection.cpp) [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\vector(60): warning C4506: 'v8::Persistent<v8::FunctionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)'
인라인 함수에 대한 정의가 없습니다. (..\src\njs\src\njsConnection.cpp) [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiEn
vImpl.cpp) [C:\Users\Administrator\
AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiEx
ceptionImpl.cpp) [C:\Users\Administ
rator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiCo
nnImpl.cpp) [C:\Users\Administrator
\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiDa
teTimeArrayImpl.cpp) [C:\Users\Admi
nistrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiPo
olImpl.cpp) [C:\Users\Administrator
\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiSt
mtImpl.cpp) [C:\Users\Administrator
\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ 예외 처리기가 사용되었지만 해제 의미 체계가 활성화되지 않았습니다. /EHsc를 지정하십시오. (..\src\dpi\src\dpiUt
ils.cpp) [C:\Users\Administrator\Ap
pData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
LINK : fatal error LNK1181: 'C:\oracle\instantclient\sdk\lib\msvc.obj' 입력 파일을 열 수 없습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! oracledb@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@0.4.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! cwd C:\nodejs\node-oracledb
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

The final error

LINK : fatal error LNK1181: 'C:\oracle\instantclient\sdk\lib\msvc.obj' 입력 파일을 열 수 없습니다. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]

means 'cannot open input file'.

can you solve this problems?

**Comment by cjbj** [comment]
Please give information about your compiler, Instant Client, and the OCI_LIB_DIR and OCI_INC_DIR environment variables

**Comment by amarauk00** [comment]
I'm sorry for missing important specifications.

Compiler : MS .NET Framework 4.5.1
(I got this by installing Microsoft Visual Studio Express 2013 for Windows Desktop.)

Instant Client : for Microsoft Windows(32-bit)
(URL : http://www.oracle.com/technetwork/topics/winsoft-085727.html)

And I downloaded instantclient-basic-nt-12.1.0.2.0.zip and instantclient-sdk-nt-12.1.0.2.0.zip,
extracted C:\oracle\instantclient. (both files extracted same location)

OCI_LIB_DIR : C:\oracle\instantclient\sdk\lib\msvc
OCI_INC_DIR : C:\oracle\instantclient\sdk\include

Thanks for comments in my article.

**Comment by cjbj** [comment]
@amaruak00 Review the recently updated install instructions in https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin

**Comment by amaruak00** [comment]
Thank you for your comments.
But still I cannot install this module.

![img1](https://cloud.githubusercontent.com/assets/11643062/6932277/0ddfc708-d852-11e4-8045-f597c451286d.PNG)

I installed Python 2.7.9 and Node.js v0.10.38.

And downloaded Oracle Instant Client v12.1(for Windows 32bit) sdk and basic at 
C:\oracle\instantclient,
C:\oracle\instantclient _12_1

Also I set variables as below.
![img2](https://cloud.githubusercontent.com/assets/11643062/6932323/9c595b66-d852-11e4-967e-915eb7034450.PNG)

I started Developer Commang Prompt which path is C:\Program Files\Microsoft Visual Studio 12.0\Common7\Tools\Shortcuts.

and I confirmed Path variables by typing set path, 

![img3](https://cloud.githubusercontent.com/assets/11643062/6932344/ee99384c-d852-11e4-845d-66f7b51ccade.PNG)

and there has Python, node.js and Oracle directions.

So, I typed "npm install oracledb". and I saw same error message.

![img4](https://cloud.githubusercontent.com/assets/11643062/6932367/4ff5c952-d853-11e4-9fcb-ecabda81ba0b.PNG)

(fatal error means : cannot open input file)


again, thanks for your kindness.

**Comment by cjbj** [comment]
Is this one of those Windows permissions things; do you need to be running something as administrator to set variables or run commands?  I vaguely recall some trick about Windows telling you variables were set but they were only available to a single user. I'm just guessing here - sorry.  I am not a Windows user.

**Comment by Michaellqs** [comment]
I encountered the same issue here.
Tried everything about the environment variables and etc.
Alway open command prompt as administrator.
The error is still the same.

**Comment by amaruak00** [comment]
My Windows account is Administrator. and I set variables not only Single user's PATH but also System user's.

and I think https://github.com/oracle/node-oracledb/issues/63 may have same issue.

**Comment by cjbj** [comment]
One possible thing to do is install the SQL*Plus instant client bundle (unzip into the same instant client dir) and check that the sqlplus.exe command runs.

**Comment by amaruak00** [comment]
sqlplus.exe runs well.

The main error is : 
LINK : fatal error LNK1181: cannot open input file 'C:\oracle\instantclient\sdk\lib\msvc.obj' .

In the C:\oracle\instantclient\sdk\lib, there is no msvc.obj file. It is a folder.

and MSDN says, "Another possible cause for LNK1181 is that a long file name with embedded spaces was not enclosed in quotation marks. In that case, the linker will only recognize a file name up to the first space, and then assume a file extension of .obj. The solution to this situation is to enclose the long file name (path plus file name) in quotation marks."
(URL : https://msdn.microsoft.com/en-us/library/y6b12xkc.aspx)

I think Windows Builer want to access C:\oracle\instantclient\sdk\lib\msvc\[Some Files], but the path was cut and Builder makes C:\oracle\instantclient\sdk\lib\msvc + '.obj', it makes CANNOT OPEN error.

What should I do in this case?

**Comment by Bigous** [comment]
@amaruak00 Could you remove the ; (semicolon) from your ORA_INC_DIR and ORA_LIB_DIR and try again?

**Comment by amaruak00** [comment]
@Bigous Thank you for your comment. It was installed and I can use node-Oracledb. Thanks!
