### ISSUE TITLE
Cannot select into BLOB column after changing column type from CLOB

### ISSUE THREAD

**Issue by ggrimbert** [oracle/node-oracledb#590]
Hi,

I am having a strange behavior with node-oracledb and blob columns.

I'm still working on Sequelize, and I have some tests that create a table with the same fields, but different types, then insert and select into these tables.

Tables are deleted / created for each test.

#### Answer the following questions:

1. What error(s) you are seeing?
Unhandled rejection Error: ORA-00932: inconsistent datatypes: expected CHAR got BLOB

In fact, after some researches, the 2nd select ````SELECT id, field FROM users "user"````, after the creation of the table with BLOB type, always error by throwing with the type of the previous test.

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
I just execute a simple select request into a table.

Here is a way to reproduce : 
```js
var oracledb = require('oracledb');
var config = require('./dbConfig.js');
oracledb.Promise = require('bluebird');
oracledb.maxRows = 500;

oracledb.fetchAsString = [
    oracledb.DATE
];

oracledb.getConnection(config, function (err, connection) {
    if (err) {
        throw err;
    }

    connection.execute(`BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
	.then(result => {
		connection.execute(`BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
		.then(result => {
			connection.execute(`BEGIN EXECUTE IMMEDIATE 'CREATE TABLE users (id NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, field CHAR(255) NULL,CONSTRAINT PKusersid PRIMARY KEY (id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -095 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
			.then(result => {
				connection.execute(`SELECT i.index_name,i.table_name, i.column_name, u.uniqueness, i.descend FROM user_ind_columns i INNER JOIN user_indexes u ON (u.table_name = i.table_name AND u.index_name = i.index_name) WHERE i.table_name = UPPER('users') ORDER BY INDEX_NAME, COLUMN_NAME`, [], { outFormat: 4002, autoCommit: true })
				.then(result => {
					connection.execute(`INSERT INTO users (id,field) VALUES (DEFAULT,'foobar')`, [], { outFormat: 4002, autoCommit: true })
					.then(result => {
						connection.execute(`SELECT id, field FROM users "user"`, [], { outFormat: 4002, autoCommit: true })
						.then(result => {
							connection.execute(`select table_name,constraint_name, owner from all_constraints where constraint_type in ('U', 'R') and table_name = 'USERS' and owner = 'SEQUELIZE' order by table_name, constraint_name`, [], { outFormat: 4002, autoCommit: true })
							.then(result => {
								connection.execute(`BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEQUELIZE.USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
								.then(result => {
									connection.execute(`BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
									.then(result => {
										connection.execute(`BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
										.then(result => {
											connection.execute(`BEGIN EXECUTE IMMEDIATE 'CREATE TABLE users (id NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, field BLOB NULL,CONSTRAINT PKusersid PRIMARY KEY (id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -095 THEN RAISE; END IF; END;`, [], { outFormat: 4002, autoCommit: true })
											.then(result => {
												connection.execute(`SELECT i.index_name,i.table_name, i.column_name, u.uniqueness, i.descend FROM user_ind_columns i INNER JOIN user_indexes u ON (u.table_name = i.table_name AND u.index_name = i.index_name) WHERE i.table_name = UPPER('users') ORDER BY INDEX_NAME, COLUMN_NAME`, [], { outFormat: 4002, autoCommit: true })
												.then(result => {
													connection.execute(`INSERT INTO users (id,field) VALUES (DEFAULT,hextoraw('666f6f626172'))`, [], { outFormat: 4002, autoCommit: true })
													.then(result => {
														connection.execute(`SELECT id, field FROM users "user"`, [], { outFormat: 4002, autoCommit: true })
														.then(result => {
															console.dir(result);
															connection.close();
														})
														.catch(error => {
															connection.close();
															throw error;
														});
													})
												})
											})
										})
									})
								})
							})
						})
					})
				})
			})
		})
	})
});
```

You can try changing the type of the first create table statement, the error changes.

Little info, the same requests with Oracle SqlDevelopper works without error.

**Comment by cjbj** [comment]
I didn't dig deeply at this time of night, but try turning off the statement cache as an experiment.
SQL*Plus and SQL Developer are designed for ad hoc queries.  Node-oracledb makes use of the statement cache for performance in production apps, as discussed in the doc, so the query meta data is not repeatedly transferred to node-oracledb. If you change the schema, then you can see errors like the one you reported because that meta data is inconsistent. Oracle DB's general best practice recommendation is for the schema to be created prior to app execution - DDL is 'expensive'.  Anyway, the statement cache is there to be used or disabled as required.

**Comment by ggrimbert** [comment]
Yes, that's it.

I had no idea this kind of thing was implemented, maybe it's the cause to other problems I have...

In the case you have these informations, does this cache really improves the time of requests or it is negligible ?

**Comment by cjbj** [comment]
@ggrimbert our published 'Niles Benchmark' result for OCI saw 'up to' 600% DB CPU reduction, and a response time of up to 15-22% faster. So yes, the reduction of statement parsing and meta data transfer can be significant.

I'd like OCI statement cache invalidation to be smarter but last time it was discussed the extra overhead for cache management was raised as a potential issue.  Since the common/recommended scenario for Oracle production apps is to NOT recreate tables during app execution I can buy this argument. However if an opportunity comes to make improvements, I'll vote for it.

**Comment by ggrimbert** [comment]
Thanks for the info. 

The problem I had will not appear in production as all table creation will be done at the startup. I had this problem as I'm working on integration tests.

The only thing I have to setup is to determine if I'm in test or not, and so disable / enable the cache.

Last question, OCI size seems to be 20 by default, do you have some recommandations for this size ?

**Comment by cjbj** [comment]
@ggrimbert The [default is 30](https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#propdbstmtcachesize).  From the [doc discussion](https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#stmtcache)

> In general, set the statement cache to the size of the working set of statements being executed by the application.

To tune the statement cache size, monitor general application load and the AWR "bytes sent via SQL*Net to client" values.  The latter statistic should benefit from not shipping statement meta-data to node-oracledb.  Adjust the statement cache size to your satisfaction.

**Comment by ggrimbert** [comment]
Thanks a lot.

I've seen 20 in this post https://docs.oracle.com/database/122/LNOCI/oci-programming-advanced-topics.htm#LNOCI16658.


I close this as it's solved.

**Comment by cjbj** [comment]
@ggrimbert let us know how you go.  The OCI statement cache size default is 20 but we used 30 in node-oracledb.  

I would be interested in knowing how many distinct SQL statements people's apps are commonly executing, i.e. the size of the working set of statements.
