### ISSUE TITLE
Install issue on Linux x86_64

### ISSUE THREAD

**Issue by gkbHngr14** [oracle/node-oracledb#591]
Describe exactly what you did and what you want to happen.

I tried very desperately for 8 hours to install oracledb but each time hitting the issue mentioned below.

I have tried to install using RPM as well as zip and followed each and every instruction in the install doc, but it just doesn't work.

Instructions followed mentioned at: 
1. https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instzip
2. https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instrpm

I need help fast, appreciated.

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Review your output and logs.  **Google any errors**
Try to install in a different way.  Try some potential solutions.

For Node 4 onwards, you need a compiler with C++11 support.

Did the error indicate a network connection issue?  Do you need to set `http_proxy`?

Try running `npm cache clean` and deleting the `node_modules/oracledb` directory.

Do you have an old version of `node-gyp` installed?  Try updating it.  Also try deleting `$HOME/.node-gyp` or equivalent.

Did this too, didn't help

#### Answer the following questions:

1. What error(s) you are seeing?

node_modules/oracledb/lib/oracledb.js:38
    throw err;
    ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nnirnakar/test/node_modules/oracledb/lib/oracledb.js:35:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

node select1.js

Logged in as my user.

Also tried sudo -E node select1.js. This suppresses the error but doesn't do anything

3. What environment variables did you set?  How *exactly* did you set them?

export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
export OCI_LIB_DIR=/opt/oracle/instantclient
export OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
export ORACLE_HOME=/usr/lib/oracle/12.1/client64

4. What is your version of Node.js?
v7.4.0
5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
instantclient-basic-linux.x64-12.1.0.2.0

6. What is your OS and version?

Linux .6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 02:36:19 PST 2015 x86_64 x86_64 x86_64 GNU/Linux

7. What compiler version did you use?  For example, with GCC, run `gcc --version`

gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)

**Comment by cjbj** [comment]
Start by telling us the OS version (see /etc/redhat-release or similar), then where you got Node from and how it was installed. Then use a [gist](https://gist.github.com/) to show the commands you are running to install node-oracledb.

Also try a rm -rf node_modules (take a backup first) before installing.  Run 'npm cache clean'.

If you are using Instant Client, don't set ORACLE_HOME - that's not in the instructions!  If that wasn't part of an attempt to find a solution, check that you don't have multiple Oracle libraries conflicting.

**Comment by gkbHngr14** [comment]
OS version:

-sh-4.1$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	OracleServer
Description:	Oracle Linux Server release 6.8
Release:	6.8
Codename:	n/a

Where I got Node from:

397  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  398  export NVM_DIR="/home/nnirnakar/.nvm"
  399  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  401  nvm install 4.4.3
  463  nvm install 7.4.0
  464  nvm use 7.4.0

Did I run rm -rf and npm cache clean?

Yes. I have to do as sudo for both these commands, which I did and these didn't help.

Why did I setup ORACLE_HOME?

Just trying to find solution to this problem. I don't have conflicting libraries.

Gist?

Trying to provide one shortly.

Additional note:

Since this a VM that I'm trying to setup oracledb on, I first downloaded the client zip/rpm on my laptop and then scp'ed them to this linux VM. Not sure that would cause any problems??

**Comment by gkbHngr14** [comment]
Here is the gist:

https://gist.github.com/gkbHngr14/ceca75c6c38849d530f77fad4b1e7bf5

**Comment by gkbHngr14** [comment]
Hi Chris,

I have added more details to the issue. Is it possible to get back to me
quickly?

Thanks
Nagen

On Tue, Jan 17, 2017 at 4:08 AM, Christopher Jones <notifications@github.com

**Comment by cjbj** [comment]
I noticed you set environment variables and then did 'sudo npm install oracledb'.  The install doc has a comment about needing to use 'sudo -E' to preserve environment variables.  However, since you have Instant Client in the default location, that may not matter for node-oracledb.  Maybe it matters for something else, like nvm?  

As a test,  use the node binaries from https://nodejs.org/en/download/.  You can extract them as a normal user and set your PATH to the bin directory. This might help you see if there is a sudo issue.

**Comment by gkbHngr14** [comment]
Thanks - I have in fact tried with sudo -E as well, didn't matter.

I used the binaries from the link you sent and now hitting this issue:

> oracledb@1.12.2 install /home/nnirnakar/node_modules/oracledb
> node-gyp rebuild

make: Entering directory `/home/nnirnakar/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/njs/src/njsOracle.h:56,
                 from ../src/njs/src/njsOracle.cpp:53:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/nnirnakar/.node-gyp/6.9.4/include/node/node.h:42,
                 from ../src/njs/src/njsOracle.cpp:51:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: At global scope:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: At global scope:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:3277: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: At global scope:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:4497: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:4513: error: ‘nullptr’ was not declared in this scope
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/nnirnakar/.node-gyp/6.9.4/include/node/v8.h:7537: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../src/njs/src/njsOracle.h:56,
                 from ../src/njs/src/njsOracle.cpp:53:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’

**Comment by cjbj** [comment]
Oh yes - that's a cleaner error.  You do have a C++11 compatible compiler?  How did you install on the NVM version of node without one?

If you don't have one, follow steps such as https://blogs.oracle.com/opal/entry/getting_a_c_11_compatible and https://github.com/oracle/node-oracledb/issues/488#issuecomment-238148826

**Comment by gkbHngr14** [comment]
Thanks. I'm having trouble installing SCL. It finishes with:

Total                                           7.8 MB/s | 521 MB     01:06     
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID ec551f03: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle


GPG key retrieval failed: [Errno 14] Could not open/read file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle

And I can't run scl enable devtoolset-3 since the environment doesn't find scl.

**Comment by gkbHngr14** [comment]
Ignore. I was able to fix this, thanks

**Comment by gkbHngr14** [comment]
I was able to successfully install oracledb(using scl enable devtoolset-3 -- npm install oracledb).

But when I run an example js, such as node select.js, I get the following:

node_modules/oracledb/lib/oracledb.js:38
    throw err;
    ^

Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nnirnakar/node_modules/oracledb/lib/oracledb.js:35:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by gkbHngr14** [comment]
I set the LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH and this error went away..but the bad news is:

When I run node select.js, it does nothing, doesn't establish DB connection or execute other commands, simply exits immediately.

**Comment by gkbHngr14** [comment]
Please ignore - I'm doing another test.

**Comment by gkbHngr14** [comment]
The second test succeeded. Thank you for all your help!

**Comment by cjbj** [comment]
@gkbHngr14 I'm glad you got there in the end.  I'll see what doc improvements can be made.
