### ISSUE TITLE
get particular column data from result set 

### ISSUE THREAD

**Issue by calvinrajat** [oracle/node-oracledb#592]
I am getting a the following dbResponse with resultSet as "true"  :

dBResponse  { rows: undefined,
  resultSet:
   { metaData:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  outBinds: undefined,
  rowsAffected: undefined,
  metaData:
   [ { name: 'CNFIG_ID' },
     { name: 'BOB_CD' },
     { name: 'BND_CD' },
     { name: 'INFOMTN_TYPE_CD' },
     { name: 'PTCOL_TYPE_CD' } ] }

is there a way to get data of BOB_CD column only from the resultSet ?
I dont want the complete data from the resultSet using fetchRowsFromRS method.

**Comment by cjbj** [comment]
In the SELECT statement, include only the columns you want. And use a WHERE clause.  Then choose whether to use `execute()` with or without a ResultSet, or use `queryStream()`. Note #158 is still open.
