### ISSUE TITLE
Can't Suspend / Kill Process once Oracle connection made. 

### ISSUE THREAD

**Issue by Gusbenz** [oracle/node-oracledb#593]
I'm not sure why, but on macOS once I've made a connection to my DB I can't suspend the process (ctrl-z) or kill it (ctrl-c). It just sits. I'm unsure if that's a bug or something I've done wrong in my code. I am closing the connection as from y'all's example:

```js
let doRelease = (connection) => {
  connection.close(
    (err) => {
      if (err) {
        console.error(err.message);
      }
    });
};
```

<img width="333" alt="screen shot 2017-01-18 at 3 04 20 pm" src="https://cloud.githubusercontent.com/assets/12821230/22080907/70b3d858-dd8f-11e6-9bd8-6d4c70005fd7.png">

I'm using:

• HapiJS
• HapiSwagger --- so, Swagger

Thanks!

**Comment by cjbj** [comment]
See if https://github.com/oracle/node-oracledb/issues/128 or https://github.com/oracle/node-oracledb/blob/master/examples/webapp.js#L204 help

**Comment by Gusbenz** [comment]
@cjbj that did it. Thanks so much. Got to learn about [https://nodejs.org/api/process.html](process). Thanks again!

**Comment by cjbj** [comment]
No problems.  I will still prod development about the general problem.
