### ISSUE TITLE
Crash when calling a procedure without passing the right parameters

### ISSUE THREAD

**Issue by senamaud** [oracle/node-oracledb#594]
This happen only on Windows with Node 6. When I had Node 4.4.4, it was not crashing.
On Linux and Mac OS, it works like it's supposed to be.
I run this API on 4 different computers. 
- Linux (Node 6.9.4, Instant Client 12.1): **OK**
- Mac OS (Node 6.9.4, Instant Client 11.2): **OK**
- Windows 2008 (Node 4.4.4, Instant Client 12.1): **OK**
- Windows 2008 (Upgraded to Node 6.9.4, Instant Client 12.1): **NOT OK**
- Windows 2012 (Node 6.9.4, Instant Client 12.1): **NOT OK**

I deleted the **node_modules** folder and then executed

- npm install
- npm start
- POST to API using Postman

1. What error(s) you are seeing?

**On Windows only:**
```
PID 6712 received SIGSEGV for address: 0xfccda06d
SymInit: Symbol-SearchPath: '.;C:\Dev\PROJECT;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download
/symbols;', symOptions: 530, UserName: 'Administrator'
OS-Version: 6.1.7601 (Service Pack 1) 0x112-0x3
c:\dev\PROJECT\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\dev\PROJECT\node_modules\segfault-handler\src\segfault-handler.cpp (116): segfault_handler
0000000076DD98EB (ntdll): (filename not available): vsprintf_s
0000000076DD81F2 (ntdll): (filename not available): RtlUnwindEx
0000000076DD8B58 (ntdll): (filename not available): RtlRaiseException
000007FEFCCDA06D (KERNELBASE): (filename not available): RaiseException
f:\dd\vctools\crt\vcruntime\src\eh\throw.cpp (136): _CxxThrowException
c:\dev\PROJECT\node_modules\oracledb\src\dpi\src\dpiutils.cpp (86): ociCallCommon
c:\dev\PROJECT\node_modules\oracledb\src\njs\src\njsconnection.cpp (1825): Connection::Async_Execute
000000013F531C57 (node): (filename not available): uv_fs_poll_getpath
000000013F51DE14 (node): (filename not available): uv_once
000000013FC92211 (node): (filename not available): uncompress
0000000076CB59CD (kernel32): (filename not available): BaseThreadInitThunk
0000000076DEA561 (ntdll): (filename not available): RtlUserThreadStart
[nodemon] app crashed - waiting for file changes before starting...
```

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

In my API route:
```
.post('/logincrash', function (req, res) {
            db.execute({
                sql: "BEGIN PKG_USER.USER_CONNECT(:username, :password, :cursor, :l_error); END;",
                bindParams: req.body,
                cursorFlag: true
            })
                .then(function (result) {
                    if (result.outBinds.l_error == null) {
//... source code
                    }
                    else
                        res.status(401).json({
                            success: false,
                            message: result.outBinds.l_error
                        });
                })
                .catch(function (err) {
                    console.error(err);
                    res.status(400).json({error: err.message});
                });

```
Then I simply do a **POST on /logincrash without passing any parameters**.
Of course, if I check that I have all the parameters, I will not crash. **In Linux and Mac OS, everything is fine**,  if I don't pass the parameters :username and :password then I will end up in the *catch* condition.
**In Windows, it just crash** with the error you can see over. It's not going inside the **then** or **catch**

3. What environment variables did you set?  How *exactly* did you set them?
```
Windows Variables
OCI_INC_DIR=c:\oracle\instantclient_12_1\sdk\include
OCI_LIB_DIR=c:\oracle\instantclient_12_1\sdk\lib\msvc
Path=c:\oracle\instantclient_12_1\
```

4. What is your version of Node.js?
```
node: v6.9.4
npm: 3.10.10
node-oracledb: 1.12.2 (1.11.0 had the same problem)
```

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
```
Instant Client 12.1
```

6. What is your OS and version?
```
Windows 2008 R2 and 2012
```

7. What compiler version did you use?  For example, with GCC, run `gcc --version`
```
Microsoft Visual Studio 2015
```

**Comment by cjbj** [comment]
What is the PL/SQL procedure definition and what are the values of the bind variables?  I.e. do you have a standalone testcase?

**Comment by cjbj** [comment]
Why/what is `cursorFlag` in the `execute()` call?

**Comment by dmcghan** [comment]
@senamaud Are you able to execute any of the examples with the driver on Windows?

**Comment by senamaud** [comment]
Everything is working well in Linux and Mac OS, this is only happening in Windows with Node 6
And everything else is working well in Windows, I have no problem whatsoever. This is the only thing happening.

When I do a post to my "unprotected" API branch /logincrash **without passing any parameters**, it will try to send a query to the function PKG_USER.USER_CONNECT.

With Linux or Mac OS, it will simply return
```
{
  "error": "ORA-01008: not all variables bound"
}
```

But in Windows, instead of going in
```
.catch(function (err) {
                    console.error(err);
                    res.status(400).json({error: err.message});
                });
```
It will crash with the error I mentioned.
To avoid the crash, instead of using req.body directly, I'm using another parameter where I copy all the needed parameters.

```
 var params = {};
 params['l_error'] = {dir: db.oracledb.BIND_OUT, type: db.oracledb.STRING, maxSize: 4000};

 // Check if all variables are in the array req.body
 // If not add them with null values
 params.username = (req.body['username'] == null) ? '' : req.body['username'];
 params.password = (req.body['password'] == null) ? '' : req.body['password'];
```

This way, the call to the procedure will have all the needed parameters.

The cursor is not important, it's just another parameters passed to the function in the package.
I'll come with a standalone testcase later.

**Comment by cjbj** [comment]
@senamaud if you have a complete standalone testcase, someone can check it quickly.  Without one, this will get queued until someone has a bigger chunk of time to spend on trying to guess what you are doing, and what types are involved.

**Comment by senamaud** [comment]
When doing the standalone testcase, we found somewhat where it's happening.

We are using 'segfault-handler' and sometimes, it is triggered by some errors like we had with the bind variables.

So we now do a check to see if we are in win32 environment `if (process.platform === 'win32') {`
If so, we don't use segfault-handler

    } else {
        var SegfaultHandler = require('segfault-handler');
        SegfaultHandler.registerHandler('crash.log');
    }

Here is the code to reproduce the problem. Why it's happening, we didn't understand it clearly but we just ignore this module when we are in Windows and everything is fine now.

[windows_testcase.txt](https://github.com/oracle/node-oracledb/files/729181/windows_testcase.txt)

Up to you if you want to investigate more about why this is happening with node-oracledb and wrong number of bind variables. For me, this is closed.

**Comment by cjbj** [comment]
@senamaud thanks for the test case; we'll take it from from.  From a quick inspection do we just invoke it with `/crashonlyonwindows`?
