### ISSUE TITLE
I want to login "as sysdba"

### ISSUE THREAD

**Issue by dotmaik1** [oracle/node-oracledb#596]
Could you tell me the way to login to the database as sysdba, I need to monitor something

Thanks

Error:
ORA-28009: connection as SYS should be as SYSDBA or SYSOPER

Node version:
v6.9.4

**Comment by cjbj** [comment]
node-oracledb 1.12 doesn't support SYSDBA connections.   One workaround could be to create a micro service using Python cx_Oracle

**Comment by cjbj** [comment]
node-oracledb 2.1 supports privileged connections including SYSDBA.

**Comment by kalifaboy** [comment]
even for the node-oracledb 1.13.1, privileged connections are not supported ?

**Comment by cjbj** [comment]
@kalifaboy privileged connection support was added in 2.1.  It's time to upgrade!

**Comment by kalifaboy** [comment]
Hi again. Even after upgrading the node-oracledb to the version 2.1.2, i could not have a privileged to the database. In fact i tried to display the constant oracledb.SYSDBA to check if it exists, but it tells me that it is undefined.

**Comment by cjbj** [comment]
Check your install(s).  I get:

```
> console.log(oracledb.versionString);
2.1.2
> console.log(oracledb.SYSDBA);
2
```


The code defining it is at https://github.com/oracle/node-oracledb/blob/master/lib/oracledb.js#L422

**Comment by kalifaboy** [comment]
The npm list command gives me this : 
![oradbversion](https://user-images.githubusercontent.com/31644166/36597198-47a6ba00-18a0-11e8-9cff-600752ecd02f.PNG)

And in the node shell, the problem persists ::
![pboradb](https://user-images.githubusercontent.com/31644166/36597243-6e0f5418-18a0-11e8-9f85-690bac5e99cc.PNG)

So what could the problem be ?

**Comment by dmcghan** [comment]
@kalifaboy Please run the following to determine what you're actually pulling in:

```javascript
const path = require('path');

console.log(path.resolve('oracledb'));
```

**Comment by kalifaboy** [comment]
![test](https://user-images.githubusercontent.com/31644166/36667365-85f4d020-1ae5-11e8-8fad-08b6da779e18.PNG)

**Comment by dmcghan** [comment]
Sorry, I wrote that in a hurry... 👀

Could you please run this?

```js
console.log(require.resolve('oracledb'));
```

**Comment by kalifaboy** [comment]
Sure, no problem :)

![newone](https://user-images.githubusercontent.com/31644166/36682143-43276f0a-1b12-11e8-90f2-08d99aaa545d.PNG)

**Comment by dmcghan** [comment]
Okay, now run this from a terminal:

```bash
cat /home/oracle/node_modules/oracledb/package.json
```

**Comment by kalifaboy** [comment]
Thank you for your reply. When i update the oracledb package with npm, it's still in the same version (2.0.15). My node version is 6.11.1 and npm is 3.10.10

**Comment by dmcghan** [comment]
@kalifaboy Try doing an uninstall, followed by an install:

```bash
npm uninstall oracledb -s
npm install oracledb -s
```

**Comment by kalifaboy** [comment]
It worked. Thank you.
