### ISSUE TITLE
Getting accidental exit with SIGSEGV

### ISSUE THREAD

**Issue by priyavivek1** [oracle/node-oracledb#598]
Hi, 

i am using oracle-nodedb module in our project. Somehow our server is exiting with following trace. 

Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.899Z pid:21702 worker:6 7fdb29441000-7fdb29640000 ---p 00354000 fc:02 323091                     /usr/lib/oracle/12.1/client64/lib/libclntshcore.so.12.1
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.900Z pid:21702 worker:6 7fdb29640000-7fdb2965b000 rwxp 00353000 fc:02 323091                     /usr/lib/oracle/12.1/client64/lib/libclntshcore.so.12.1
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.901Z pid:21702 worker:6 7fdb2965b000-7fdb2965f000 rwxp 00000000 00:00 0 
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.901Z pid:21702 worker:6 7fdb2965f000-7fdb29660000 r-xp 00000000 fc:02 291657                     /lib64/libaio.so.1.0.1
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.901Z pid:21702 worker:6 7fdb29660000-7fdb2985f000 ---p 00001000 fc:02 291657                     /lib64/libaio.so.1.0.1
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.902Z pid:21702 worker:6 7fdb2985f000-7fdb29860000 rwxp 00000000 fc:02 291657                     /lib64/libaio.so.1.0.1
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.902Z pid:21702 worker:6 7fdb29860000-7fdb29876000 r-xp 00000000 fc:02 291502                     /lib64/libnsl-2.12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.903Z pid:21702 worker:6 7fdb29876000-7fdb29a75000 ---p 00016000 fc:02 291502                     /lib64/libnsl-2.12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.903Z pid:21702 worker:6 7fdb29a75000-7fdb29a76000 r-xp 00015000 fc:02 291502                     /lib64/libnsl-2.12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.903Z pid:21702 worker:6 7fdb29a76000-7fdb29a77000 rwxp 00016000 fc:02 291502                     /lib64/libnsl-2.12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.904Z pid:21702 worker:6 7fdb29a77000-7fdb29a79000 rwxp 00000000 00:00 0 
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.904Z pid:21702 worker:6 7fdb29a79000-7fdb29abd000 r-xp 00000000 fc:02 323098                     /usr/lib/oracle/12.1/client64/lib/libons.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.905Z pid:21702 worker:6 7fdb29abd000-7fdb29cbc000 ---p 00044000 fc:02 323098                     /usr/lib/oracle/12.1/client64/lib/libons.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.905Z pid:21702 worker:6 7fdb29cbc000-7fdb29cbe000 rwxp 00043000 fc:02 323098                     /usr/lib/oracle/12.1/client64/lib/libons.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.906Z pid:21702 worker:6 7fdb29cbe000-7fdb2a165000 r-xp 00000000 fc:02 323094                     /usr/lib/oracle/12.1/client64/lib/libnnz12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.907Z pid:21702 worker:6 7fdb2a165000-7fdb2a365000 ---p 004a7000 fc:02 323094                     /usr/lib/oracle/12.1/client64/lib/libnnz12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.907Z pid:21702 worker:6 7fdb2a365000-7fdb2a3c7000 rwxp 004a7000 fc:02 323094                     /usr/lib/oracle/12.1/client64/lib/libnnz12.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.907Z pid:21702 worker:6 7fdb2a3c7000-7fdb2a3c8000 rwxp 00000000 00:00 0 
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.908Z pid:21702 worker:6 7fdb2a3c8000-7fdb2a53e000 r-xp 00000000 fc:02 323092                     /usr/lib/oracle/12.1/client64/lib/libipc1.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.909Z pid:21702 worker:6 7fdb2a53e000-7fdb2a73e000 ---p 00176000 fc:02 323092                     /usr/lib/oracle/12.1/client64/lib/libipc1.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.911Z pid:21702 worker:6 7fdb2a73e000-7fdb2a741000 rwxp 00176000 fc:02 323092                     /usr/lib/oracle/12.1/client64/lib/libipc1.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.911Z pid:21702 worker:6 7fdb2a741000-7fdb2a746000 rwxp 00000000 00:00 0 
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.912Z pid:21702 worker:6 7fdb2a746000-7fdb2a7b8000 r-xp 00000000 fc:02 323093                     /usr/lib/oracle/12.1/client64/lib/libmql1.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.913Z pid:21702 worker:6 7fdb2a7b8000-7fdb2a9b7000 ---p 00072000 fc:02 323093                     /usr/lib/oracle/12.1/client64/lib/libmql1.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.913Z pid:21702 worker:6 7fdb2a9b7000-7fdb2a9ba000 rwxp 00071000 fc:02 323093                     /usr/lib/oracle/12.1/client64/lib/libmql1.so
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.914Z pid:21702 worker:6 7fdb2a9ba000-7fdb2a9bc000 rwxp 00000000 00:00 0 
Jan 24 11:41:20 rhel6-8h882 strong-pm: 2017-01-24T16:41:20.914Z pid:21702 worker:6 7fdb2a9bc000-7fdb2a9fc000 r-xp 00000000 fc:02 564914                     /var/lib/strong-pm/svc/1/work/eaec7d585afda6015a421d61e107020a8510d7ed.1484852513195/node_modules/oracledb/build/Release/oracledb.node
Jan 24 11:41:58 rhel6-8h882 strong-pm: 2017-01-24T16:41:58.277Z pid:26723 worker:0 ERROR supervisor worker id 7 (pid 21819) accidental exit with SIGSEGV

Any thoughts?

**Comment by cjbj** [comment]
All I can glean from that is that you are using node-oracledb with some StrongLoop software on Linux and are getting a crash.  

Potential action items:
- give more information about versions and environment
- add tracing and identify what part of the program is crashing and see how it is being used.
- create a smaller testcase that crashes

**Comment by trivedispt** [comment]
Can someone say which version of oracledb has this issue?

**Comment by priyavivek1** [comment]
This was a issue in 1.6.0 and seems to be resolved in 1.9.2. Thanka. Please close this.

**Comment by cjbj** [comment]
@priyavivek1 If that wasn't a typo, try using the latest version, which currently is 1.12.2.
