### ISSUE TITLE
Bind Params Missing Causing DB Fail due to the same server is getting crashed. 

### ISSUE THREAD

**Issue by talasila66** [oracle/node-oracledb#599]
Bind Parameters  Missing Causing DB Fail due to the same server is getting crashed. 

**Example query:**

- info: Executing sql: SELECT name from employee WHERE  ID=:id , **bind params:  ,** options: undefined
25-01-2017 22:13:05.368 - info: Shutting down
25-01-2017 22:13:05.369 - info: Closing database pool
25-01-2017 22:13:10.973 - info: initializing oracle db pool...
25-01-2017 22:13:12.353 - info: oracle db pool created...
25-01-2017 22:13:12.355 - info: SERVER - Starting process

In the above query my bind parameters are coming as blank due to the same my server is getting crashed. Can you please help on the same?

**Comment by cjbj** [comment]
Versions?  Reproducible testcase?  Any test I try gives expected node-oracledb or Oracle client errors about missing or undefined parameters.  Without some details all I can do is sympathize.

**Comment by talasila66** [comment]
Will reopen the issue with more logs and details
