### ISSUE TITLE
Talking about Node.js at Oracle OpenWorld conference

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#60]
The OOW conference call for papers is open: https://www.oracle.com/openworld/call-for-proposals.html
It would be great to see some node-oracledb users summit talk proposals.

**Comment by cjbj** [comment]
The OOW conference call-for-papers finishes in a couple of days: https://www.oracle.com/openworld/call-for-proposals.html
Have you submitted a node-oracledb talk?

**Comment by dmcghan** [comment]
Thanks for the reminder. I'll get my submissions in by tomorrow!
