### ISSUE TITLE
Cannot open include file: 'iomanip': No such file or directory 

### ISSUE THREAD

**Issue by prashanthmadi** [oracle/node-oracledb#602]
I have followed the steps listed at below link to install oracledb on Azure App services
https://github.com/oracle/node-oracledb/blob/4ce25971a6a70af5b261a4af7545e780cdfca9f0/INSTALL.md#instwin

* I have installed instantclient "basic" and "sdk" from http://www.oracle.com/technetwork/topics/winsoft-085727.html
* set PATH to D:\home\site\tools which has all my instantclient content
* set OCI_LIB_DIR=D:\home\site\tools\sdk\lib\msvc 
* set OCI_INC_DIR=D:\home\site\tools\sdk\include 

 and it gives me below error when i  run
> npm install oracledb 
```
Cannot open include file: 'iomanip': No such file or directory 
[D:\home\site\wwwroot\node_modules\oracledb\build\oracledb.vcxproj]
```
Total error stack at below link
https://gist.github.com/prashanthmadi/b2baafe254e5fc926db124b8f606ea4d

**Is this iomanip part of instantclient or C++ development/build libraries ?**

**Comment by cjbj** [comment]
From https://www.google.com.au/search?q=iomanip it looks like part of VC.

**Comment by cjbj** [comment]
@prashanthmadi any update?

**Comment by prashanthmadi** [comment]
sorry forgot to update this thread. Azure App services doesnt have C/C++ build tools to build this... we had to move the module manually after building it in local environment...
