### ISSUE TITLE
SQL Error- uncaughtException: read ECONNRESET

### ISSUE THREAD

**Issue by talasila66** [oracle/node-oracledb#608]
**04-02-2017 10:45:36.178 - info: ERROR: Unable to execute the SQL:  Error: ORA-01036: illegal variable name/number

    at Error (native)
04-02-2017 10:45:36.179 - error: undefined:tabs_model:queryContractExist:IS_DEFAULT:Error:Error: ORA-01036: illegal variable name/number

04-02-2017 10:48:56.512 - info: Shutting down
04-02-2017 10:48:56.513 - info: Closing database pool
04-02-2017 10:48:56.513 - info: Terminating oracle db pool...
04-02-2017 10:48:56.516 - error: uncaughtException: read ECONNRESET date=Sat Feb 04 2017 10:48:56 GMT+0300 (AST), pid=1176, uid=200, gid=501, cwd=/opt/packages/TestingBuild/ execPath=/opt/softwares/node/node-v0.12.17-linux-x64/bin/node, version=v0.12.17, argv=[node, /opt/softwares/passenger/passenger-5.0.30/src/helper-scripts/node-loader.js], rss=105660416, heapTotal=67045632, heapUsed=36385264, loadavg=[0.2490234375, 0.1533203125, 0.10009765625], uptime=6373090
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)
04-02-2017 10:48:56.518 - error: Error occured: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)
04-02-2017 10:48:56.518 - info: Shutting down
04-02-2017 10:48:56.519 - info: Closing database pool
04-02-2017 10:48:56.519 - info: Terminating oracle db pool...
04-02-2017 10:48:56.536 - info: node-oracledb connection pool terminated
04-02-2017 10:49:01.001 - info: initializing oracle db pool**

**Comment by anthony-tuininga** [comment]
Can you provide the SQL that is failing? This can happen (for example) because you are specifying a bind variable that doesn't actually exist in the SQL statement you are executing. Providing the execute() call that is failing will help figure that out.

**Comment by talasila66** [comment]
@anthony-tuininga You are correct, I am executing a select query multiple times to check whether particular record exist in Database or not. With Different possible bind parameters. 

But This Should Has to Cause a ECONNRESET issue? Your quick suggestion to avoid this scenario will be helpful to me.

Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)
07-02-2017 18:42:25.675 - error: Error occured: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)

**Comment by anthony-tuininga** [comment]
Can you provide the code that is causing this problem?

**Comment by talasila66** [comment]
sure will provide the same

**Comment by talasila66** [comment]
Below code has been executed with different idno and val several time as 

1st time
--------
123,frt

2ndTime
--------
345,ytr

like this it has been executed several times, I can't use each series because inputs are user interactive. 

**empDB.empDetails = function(idno,val, modelCallback) {
    
    oracle_db.doConnect(function(err, connection) {
        if (err) {           
            oracle_db.doRelease(connection, function(err) {
                modelCallback(err);
            });
        } else {
            oracle_db.executeSql(connection, {
                sql:"SELECT empname from EMPLOYEE where empid=:empid and val=:val" ,
                bindParams: [idno,val]
            }, function(err, results) {
                if (err) {
                   
                    oracle_db.doRelease(connection, function(err) {
                        modelCallback(failureResponse);
                    });
                } else {
					var sucessResponse={
							empname:""
						};
                    if (results && results.rows && results.rows.length > 0) {
						sucessResponse.empname=results.rows[0][0];                       
                        oracle_db.doRelease(connection, function(err) {
                            modelCallback(null,sucessResponse);
                        });
                    } else {
                        oracle_db.doRelease(connection, function(err) {
                            modelCallback(null,sucessResponse);
                        });
                    }
                }
            });
        }
    });
};**

**Comment by cjbj** [comment]
That code doesn't have the implementation of `executeSql` and also isn't runnable.  Do some debugging and check what SQL you are executing and what bind parameters are being passed.
The error "ORA-01036: illegal variable name/number" is mentioned in
https://github.com/oracle/node-oracledb/blob/v1.12.2/examples/select2.js.
A straight forward example that gives ORA-01036 is 
```
      var oracledb = require('oracledb');

      oracledb.getConnection(
        { user: "hr", password: "welcome", connectString: "localhost/XE" },
        function(err, connection)
        {
          if (err) {
            console.log('%s', err);
            return;
          }

          connection.execute(
            "SELECT * from DUAL",
            // {},  // <== missing placeholder bind parameter for the execute() call
            { maxRows: 150 },  // an option, not a bind variable
            function(err, result)
            {
              if (err) {
                console.log('%s', err);
                return;
              }
              console.log(result.rows);
            });
        });
```

**Comment by talasila66** [comment]
Bind parameters  are never passed empty values.  Issue was ECONNRESET  Error.

**Comment by cjbj** [comment]
@talasila66 it *was* an issue, or it *is* an issue?  Did you resolve it?  The first error in your log is the ORA-01036.  Normally fixing the first error is a good thing.

**Comment by talasila66** [comment]
@cjbj Resolved ORA-01036 issue

ECONNRESET  still an open issue which I am facing, suspecting connection time out issue, will work around the same.

**Comment by cjbj** [comment]
Thanks for the info.

**Comment by natereinhardt** [comment]
Was there any solution or a way to mitigate this? Im coming across read ECONNRESET frequently.

**Comment by cjbj** [comment]
@natereinhardt it's likely due to your network configuration.  There are a lot of Google hits on it :) Open a new issue with all details and someone may be able to give a more precise answer.
