### ISSUE TITLE
Migrating from node-oracle to node-oracledb

### ISSUE THREAD

**Issue by hellboy81** [oracle/node-oracledb#61]
I am trying to migrate code form `joeferner/node-oracle` to `oracle/node-oracledb`.

I am missing following identifiers in this lib: `OutParam`, `OCCIINT` and so on

How can I now use [Out Params](https://github.com/joeferner/node-oracle#out-params)

For example:

```js
oracle.execute('..', [...,
   new oracle.OutParam(oracle.OCCISTRING),
]
)
````

**Comment by vizjerai** [comment]
```node-oracledb``` still doesn't bind the out parameters for ```returning``` see #4

**Comment by hellboy81** [comment]
And how can I migrate this code?

**Comment by cjbj** [comment]
@hellboy81 In these early days of node-oracledb, it's a good time to give feedback on what does & doesn't work for you. Work on new features is in progress. 

You can already bind OUT parameters for PL/SQL calls: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#outbind  Support for RETURNING INTO is in our plan.
