### ISSUE TITLE
LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [oracle/node-oracledb#611]
1. What error(s) you are seeing?
https://gist.github.com/tiagomsmagalhaes/0275567d73add7de895be5ab100bca27

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`npm i oracledb --save`

3. What environment variables did you set?  How *exactly* did you set them?
System variables
`OCI_LIB_DIR D:\app\Tiago\product\11.2.0\client_1\oci\lib\msvc`
`OCI_INC_DIR D:\app\Tiago\product\11.2.0\client_1\oci\include`

I've set SYSPATH to Python and also to oracle client whose version is client 11.2.0 32bit

4. What is your version of Node.js? Now it's 6.3.1 x86

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
instant client 11.2.0 32bit
D:\app\Tiago\product\11.2.0\client_1

6. What is your OS and version?
Windows 10 Home.

7. What compiler version did you use?  For example, with GCC, run `gcc --version`
I don't have gcc... But i have installed Visual C++ Build Tools

**Comment by cjbj** [comment]
Did you add the Oracle client library directory to PATH?

**Comment by tiagomsmagalhaes** [comment]
Yes

**Comment by cjbj** [comment]
@tiagomsmagalhaes any update on your end?

**Comment by tiagomsmagalhaes** [comment]
@cjbj I have made a clean setup on other computer that did not had instant client, and got it to work. 

Unfortunately, the current version of the module isn't suitable for the way our backend is structured as we use ORDS to connect to our databases and most of the API's execute procedures from packages that return JSON from the server.

**Comment by cjbj** [comment]
@tiagomsmagalhaes What would you like in node-oracledb for ORDS?

**Comment by tiagomsmagalhaes** [comment]
@cjbj actually, what I had in mind was to substitute ORDS as there is no easy way to import/export automatically the web services, unless they are also in the schemas. Or being used in an APEX application which we don't use.

The methods in ORDS are almost identical in structure. They end up executing a service procedure from the database, and this service procedure runs one (or more) procedures to return the data as JSON.

**Comment by cjbj** [comment]
@tiagomsmagalhaes  Are you thinking node-oracledb could have tooling to create/expose/export/import Node.js web services?  Wouldn't this be better handled in a Framework layer above node-oracledb?

**Comment by tiagomsmagalhaes** [comment]
@cjbj I havent mentioned any middleware to handle the request because I thought it would be implicitly stated. My apologies for that.  I was using Express.js

**Comment by cjbj** [comment]
@tiagomsmagalhaes I'm going to close this but will keep it in mind.
