### ISSUE TITLE
html usage

### ISSUE THREAD

**Issue by dotmaik1** [oracle/node-oracledb#613]
I might be a noob to ask this, but can you please tell me how can I draw an HTML table withe the result of a query made with oracledb

Thanks

PM,0.625845737483085,04:18:17 PM,0.631858995676754,04:19:17 PM,0.6321743470304441,04:20:18 PM,0.731869594145043,04:21:18 PM,0.632069194943446,04:22:18 PM,0.548902195608782,04:23:19 PM,0.665225345085648,04:24:19 PM,0.764881942135018,04:25:19 PM,0.532445923460898,04:26:19 PM,0.6317539484621779,04:27:19 PM,0.615333444204224,04:28:20 PM,0.648594711458507,04:29:20 PM,0.996512207274539,04:30:20 PM,0.764500581685225,04:31:21 PM,0.8642180488615591,04:32:21 PM,0.747508305647841,04:33:21 PM,0.830426839395449,04:34:22 PM,0.681176275128759,04:35:22 PM,0.709459459459459,04:36:21 PM,0.879522071025556,04:37:22 PM,0.714285714285714,04:38:22 PM,0.714285714285714,04:39:23 PM,0.830426839395449,04:40:23 PM,0.79773973741067,04:41:23

**Comment by sagiegurari** [comment]
There are many ways to achieve this and you need to be more specific.
I can give 1 of many examples,
1. on server side, lets say you use express, you can implement a REST service via express middleware that queries the DB and returns the output as a JSON
2. on client, lets say you use angular, you can use $resource to invoke the REST service, load the data to the client.
3. use ng-repeat on the rows and ng-bind on every column to draw the html table.

but like I said there are unlimited ways to get this done and you didn't specify what frameworks you are using on server or client.

**Comment by dotmaik1** [comment]
I'm using plain javascript since I'm not jet familiar with Angular and I'm working on the client side

**Comment by sagiegurari** [comment]
so if I understand correctly, you don't have an issue to execute a query via node oracle but you do seek knowledge on how to expose it via REST and how to call that REST in the client and use the output to create some HTML table.
If i'm right, i'm not sure node oracledb project page is the place to ask these questions.
If you want, I can give you links per subject but you need to learn the basics of DOM manipulation, ajax and javascript and do some googling.

**Comment by dotmaik1** [comment]
Thats exactly what I need, I already learning DOM, ajax and so on Thanks
