### ISSUE TITLE
Supporting Bulk/Batch Insert

### ISSUE THREAD

**Issue by hiren-intellectdesign** [oracle/node-oracledb#614]
Does this version of Oracle Driver support Bulk/Batch INSERT like it is supported in Java e.g. java.sql.Statement.executeBatch().

Referred the documentation: https://github.com/oracle/node-oracledb/blob/master/doc/api.md
But couldn't find any such option. There is some mention about using PL/SQL block, but is that efficient option for inserting large set of data (let's say 50k records)?
Any other easier option to achieve this natively in NodeJS driver (instead of having PL/SQL function)?

**Comment by sagiegurari** [comment]
Could be wrong but the oci does not support it (from what i read in the oci docs).
You could use a wrapper function for it but it would make internally the multiple insert/update calls.

https://github.com/sagiegurari/simple-oracledb#Connection+batchInsert

**Comment by cjbj** [comment]
OCI has it, as does [ODPI-C](https://oracle.github.io/odpi/doc/public_functions/dpiStmt.html#c.dpiStmt_executeMany), which will soon be the base for node-oracledb.  But it has not been exposed through to node-oracledb. You could try https://github.com/oracle/node-oracledb/blob/master/doc/api.md#plsqlindexbybinds

**Comment by sagiegurari** [comment]
Will support for it planned in the odpi version?

**Comment by cjbj** [comment]
@sagiegurari everything's on the list for consideration!  The question is what is the priority?!

**Comment by hiren-intellectdesign** [comment]
@cjbj Thanks for reply. Looked at the link
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#plsqlindexbybinds

But I still see problem with bulk insert of records having multiple columns. For ex:
Id, Name, Dept
10, "John", "Engineering"
20, "Steve", "Sales"
30, "Dave", "Support"

If I have read documentation correctly, it supports passing **ONLY** NUMBER or STRING Array as bind parameter to the PL/SQL block. And NOT array of Record.
So, with above example, one needs to pass 3 arrays (one for each column - Id, Name, Dept), which seems too much of a task (to convert Records to Arrays of Columns) - especially where I have 50+ columns as a part of record.

Wish, there was better way of bulk insert :(

**Comment by cjbj** [comment]
@hiren-intellectdesign yes on both counts.   Another potential solution is the INSERT/UNION syntax

**Comment by hiren-intellectdesign** [comment]
Thanks for suggestion, however I see INSERT/UNION is likely to face maximum query length problem (64k?) even with 5000 records to insert.

Original requirement is to fire a SELECT that can support more than 1000 items in IN clause. Hence, thought of bulk inserting keys into temp table first and then applying SQL join to temp table for executing SELECT.

Apparently, this is turning out to be too much of a task.
- Create bulk insert procedure
- Converting Records into Array of Columns
- Bulk insert into <Temp> table (using procedure accepting array of columns)
- Build & Execute SELECT query using <Temp> table

Wondering, if this is all worth. Is there any better option with Oracle?

**Comment by dmcghan** [comment]
@hiren-intellectdesign What version of the database are you using?

**Comment by hiren-intellectdesign** [comment]
Currently using Oracle 12c (12.1.0.1.0) - 64bit
However, solution is targeted to support both 11g and 12c.

**Comment by dmcghan** [comment]
@hiren-intellectdesign I see. 

Could you please provide some more details?

> Create bulk insert procedure

You likely don't need to do this, though pre-compiled code is almost always better than an anonymous PL/SQL block.

> Converting Records into Array of Columns

When you say "records" do you mean JavaScript objects? So you're converting an array of objects to separate arrays of either string or number, correct?

> Bulk insert into table (using procedure accepting array of columns)

This is the part I'm wondering if you can skip. The Node.js driver binds arrays in as PL/SQL associative arrays. In Oracle 12c, you can use the `table` operator with associative arrays, [as illustrated here](http://stevenfeuersteinonplsql.blogspot.com/2016/02/use-table-operator-with-associative.html). If you want to support 11g, you'll need to convert the associative arrays to nested table types (I think they can be in package specs but may need to be at the schema level).

Have a look [at this](https://github.com/oracle/node-oracledb/issues/137) for an example. The main difference is that you'd be converting one array type to another rather than a string to an array.

**Comment by cjbj** [comment]
Throwing this out there: External Tables and SQL*Loader are very useful for speedy, large data loads.  Or perhaps convert to JSON (or another representation) in Node.js, pass it as a LOB to a PL/SQL procedure and decompose the JSON string for insert (or just insert into a JSON column in Oracle 12.1)

**Comment by hiren-intellectdesign** [comment]
@dmcghan Thanks for reply and suggestions.

> > Create bulk insert procedure

> You likely don't need to do this, though pre-compiled code is almost always better than an anonymous PL/SQL block.

Agreed, this will be one time procedure creation.

> > Converting Records into Array of Columns

> When you say "records" do you mean JavaScript objects? So you're converting an array of objects to separate arrays of either string or number, correct?

Yes. Array of Javascript Objects. Will have to be converted to array of columns to be able to bulk insert using procedure. Please see 6th comment in this issue chain - https://github.com/oracle/node-oracledb/issues/614#issuecomment-279229171

> > Bulk insert into table (using procedure accepting array of columns)

> This is the part I'm wondering if you can skip. The Node.js driver binds arrays in as PL/SQL associative arrays. In Oracle 12c, you can use the table operator with associative arrays, [as illustrated here](http://stevenfeuersteinonplsql.blogspot.com/2016/02/use-table-operator-with-associative.html). If you want to support 11g, you'll need to convert the associative arrays to nested table types (I think they can be in package specs but may need to be at the schema level).

For the example you shared; is there a NodeJS way of doing the same? Just to highlight, my SELECT filter data (of 10K+ items) is in NodeJS (not in DB table yet). I think, that is where the limitation is (supporting bulk insert of JSON objects). Tried explaining in my earlier [comment](https://github.com/oracle/node-oracledb/issues/614#issuecomment-279229171)

I also see your suggestion [here](https://github.com/oracle/node-oracledb/issues/137#issuecomment-120036280), of achieving bulk insert with slightly different way.

@cjbj 
I think, I now know that there are workarounds possible, but all comes with string and array conversions/manipulations, alongwith likely performance overhead. And all this just for supporting SELECT with undefined N number of items in IN clause.

Is there any sight of introducing NodeJS support for bulk insert like in Java e.g. java.sql.Statement.executeBatch() ? I see, that should settle some undesirable workarounds in the process.

**Comment by dmcghan** [comment]
@hiren-intellectdesign Here's an example... I found that arrays couldn't be bound into SQL statements, so it's a 2 step process: 1 PL/SQL and 1 SQL.

Also, I'm demonstrating how to do this in memory with a table function rather than inserting into another table. This may or may not be the best solution for you...

Okay, imagine we have this table that we want to filter:
```sql
create table t (
  id     number not null,
  attr_1 varchar2(2) not null,
  attr_2 number not null
);

insert into t (id, attr_1, attr_2) values (1, 'FL', 100);
insert into t (id, attr_1, attr_2) values (2, 'NY', 500);
insert into t (id, attr_1, attr_2) values (3, 'CA', 300);
insert into t (id, attr_1, attr_2) values (4, 'FL', 200);
insert into t (id, attr_1, attr_2) values (5, 'NY', 90);
insert into t (id, attr_1, attr_2) values (6, 'CA', 80);
```

The first thing to do is to create some types and a package:
```sql
-- These types will allow the table function to work
create or replace type thing_t as object (
  attr_1 varchar2(50),
  attr_2 number
);

create or replace type thing_ntt as table of thing_t;
/


-- This package will contain a private nested table type with setter and getter methods.
create or replace package p
as

-- These types are here so the Node.js driver can bind into them
type vc2_aat is table of varchar2(50)
  index by pls_integer;

type number_aat is table of number
  index by pls_integer;

procedure set_things(
  p_attr_1s in vc2_aat,
  p_attr_2s in number_aat
);

function get_things

  return thing_ntt;

end p;
/

create or replace package body p
as

g_things thing_ntt;

procedure set_things(
  p_attr_1s in vc2_aat,
  p_attr_2s in number_aat
)

is

  l_thing  thing_t;

begin

  g_things := thing_ntt();

  for x in 1 .. p_attr_1s.count
  loop
    l_thing := thing_t(p_attr_1s(x), p_attr_2s(x));
    
    g_things.extend();
    g_things(g_things.count) := l_thing;
  end loop;

end;

function get_things

  return thing_ntt

is

begin

  return g_things;

end;

end p;
/
```

With that in place, now we can do this. Note that there are 2 round trips, one sets the private nested table type via array bindings while the other uses it in a query:
```javascript
var oracledb = require('oracledb');
var config = require('./dbconfig');
var jsThings = [
  {attr1: 'NY', attr2: 500},
  {attr1: 'FL', attr2: 200},
  {attr1: 'CA', attr2: 80}
];

oracledb.getConnection(config, function(err, connection) {
  var attr1Vals = [];
  var attr2Vals = [];

  if (err) {throw err;}

  jsThings.forEach(function(thing) {
    attr1Vals.push(thing.attr1);
    attr2Vals.push(thing.attr2);
  });
  
  connection.execute(
   `begin

      p.set_things(:attr_1_vals, :attr_2_vals);
      
    end;`, 
    {
      attr_1_vals: {
        type: oracledb.STRING,
        dir: oracledb.BIND_IN,
        val: attr1Vals
      }, 
      attr_2_vals: {
        type: oracledb.NUMBER,
        dir: oracledb.BIND_IN,
        val: attr2Vals
      }
    }, 
    function(err, result) {
      if (err) {throw err;}

      console.log('The proc was called successfully!');
      console.log('Now that the package global is set, let\'s execute the query!');

      connection.execute(
       `select *
        from t
        where (attr_1, attr_2) in (
          select attr_1, attr_2
          from table(p.get_things)
        )`,
        function(err, result) {
          if (err) {throw err;}

          connection.release(function(err) {
            if (err) {throw err;}

            console.log('Here are the rows we got...');
            console.log(result.rows);

            console.log('Connection released.');
          });
        }
      );
  });
});
```

I hope that helps!

**Comment by cjbj** [comment]
Node-oracledb 2.2 introduces [connection.executeMany()](https://oracle.github.io/node-oracledb/doc/api.html#executemany) (also see [Batch Statement Execution](https://oracle.github.io/node-oracledb/doc/api.html#batchexecution)) making batch data insert more efficient.  Take a look!
