### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by indapublic** [oracle/node-oracledb#615]
OS: CentOS release 6.8 (Final)
Node: 6.9.5 or 7.4.0 (via nvm)
Oracle Client: 12.1 (installed from rmp packages)

I have exception while executing simple nodejs file with only declaration oracledb
```
var oracledb = require('oracledb');
```

> /usr/share/api/node_modules/oracledb/lib/oracledb.js:38
>     throw err;
>     ^
> 
> Error: Module did not self-register.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:597:18)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/share/api/node_modules/oracledb/lib/oracledb.js:35:19)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)

Upgrading/downgrading node and reinstalling oracledb not solved my problem. How I can to fix it? Thank you in advance

**Comment by indapublic** [comment]
Hm. Downgrade node to v0.10.48 and all is fine.

**Comment by sagiegurari** [comment]
My guess that npm install failed with node 6 due to missing c11 supported compiler.

**Comment by indapublic** [comment]
@sagiegurari Thank for reply. But I don't see any errors while `npm install`

**Comment by sagiegurari** [comment]
so maybe you can reinstall again with node 6?
than check the output to see there were no errors during the c compilation of the oracledb module.
if you didn't see any, check the node module to see if the output of the installation is valid, for example look for oracledb.node under the build dir, for example:
node_modules/oracledb/build/Release/oracledb.node

**Comment by cjbj** [comment]
Perhaps try `npm install --verbose oracledb`

**Comment by surjikal** [comment]
Hitting the same issue on Linux (node v6), but it seems to work under OSX strangely.

**Comment by surjikal** [comment]
@indapublic I'm not sure what's the proper way of fixing this, but I think it has to do with having a non-nvm node, and nvm nodes, on the same server. Anyway, here's how I got it to work:

```
nvm use 6
npm install oracledb

# This will fail...
node -e "require('oracledb')"

# So we now fix it!
cd node_modules/oracledb

# We get the node-gyp binary that is for the selected node version
# Alternatively, just do which node-gyp and see if it's the correct binary
nodepath=$(dirname `which node`)
nodegyp=$nodepath/node-gyp

# Not sure if this is required but doesn't hurt
$nodegyp install

$nodegyp rebuild

# It should now work!
node -e "require('oracledb')"
```

**Comment by cjbj** [comment]
Some nice sleuth work
