### ISSUE TITLE
NJS-006: invalid type for parameter 1

### ISSUE THREAD

**Issue by indapublic** [oracle/node-oracledb#616]
OS: CentOS release 6.8 (Final)
Node: v0.10.48
Oracle Client: 12.1 (installed from rmp packages)
"oracledb": "1.12.2"

```
var oracledb = require('oracledb');

oracledb.getConnection({
  user: 'user',
  password: 'password',
  connectString: 'sid'
}).then(function (connection) {
  console.log('ok');
}).catch(function (err) {
  console.error(err);
});
```

> /usr/share/api/node_modules/oracledb/lib/util.js:80
>     throw new Error(getErrorMessage(errorCode, messageArg1));
>           ^
> Error: NJS-006: invalid type for parameter 1
>     at Object.assert (/usr/share/api/node_modules/oracledb/lib/util.js:80:11)
>     at Oracledb.getConnection (/usr/share/api/node_modules/oracledb/lib/oracledb.js:170:16)
>     at Oracledb.getConnection (/usr/share/api/node_modules/oracledb/lib/util.js:99:19)
>     at Object.<anonymous> (/usr/share/api/test.js:4:10)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)

Credentials are correct. Sqlplus connected successfully.

Same code is working on local OSX with same database (via VPN)

**Comment by sagiegurari** [comment]
in node 10 you don't have promise support without you adding it manually.
so while working with node 0.10 you need to provide a callback function instead of promise.

**Comment by dmcghan** [comment]
@indapublic Or you can import a promise library and use that:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-191-custom-promise-libraries

**Comment by indapublic** [comment]
Of course :( Sorry, my fault
