### ISSUE TITLE
Driver usage guidelines for RAC

### ISSUE THREAD

**Issue by hiren-intellectdesign** [oracle/node-oracledb#618]
Hello, being novice to RAC, I was trying to understand in documentation:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md
if there are any specific guidelines for using this driver in Oracle RAC setup?

Any specific settings/limitations to be kept in mind while using Node version of Oracle driver? Or it is expected to work just as it would with non-RAC instance (without any config change at client application end)?

**Comment by cjbj** [comment]
Node-oracledb is a standard OCI client so there's no specific setting.  But if you enable events in [oraacess.xml](https://docs.oracle.com/database/121/LNOCI/oci10new.htm#CEGEFIBH) you should get Connection Load Balancing for RAC, if the DB service is sending events.

**Comment by cjbj** [comment]
Node-oracledb 2.2 has an '[events](https://oracle.github.io/node-oracledb/doc/api.html#propdbevents)' property so you no longer need to use an oraaccess.xml file.
