### ISSUE TITLE
download blob value from oracledb as file

### ISSUE THREAD

**Issue by RavGup** [oracle/node-oracledb#619]
Hi,

I am storing the PDF file in the blob type column in oracle. I want download that file stored in BLOB type.
Can anyone help me out for this.?

**Comment by dmcghan** [comment]
@RavGup This is a very generic question. Are you trying to get the BLOB from Oracle to Node.js (just right it as a file there)? Are you trying to stream the BLOB through an API for end users to download?

What exactly are you trying to do?

**Comment by RavGup** [comment]
Thanks dmcghan for response. I am trying to get the BLOB from Oracle to Node.js and stream that BLOB through API to end user to download.

**Comment by dmcghan** [comment]
@RavGup Start by reading this:
https://jsao.io/2015/03/throttled-file-loading-with-node-js-oracle-database/

Note that the sample code could be simplified at this point because the driver now supports arrays.

**Comment by RavGup** [comment]
@dmcghan read the article. It asked reader to do that part in which I am facing an issue.(Downloading the file).
I have a oracle package that returns the BLOB column. what should I do to that BLOB column to pass it to browser to download the file?

**Comment by dmcghan** [comment]
@RavGup 

> It asked reader to do that part in which I am facing an issue.(Downloading the file).

Could you please indicate where it asks the reader to download the file?

**Comment by RavGup** [comment]
"While the sample application manages the buffer as files are streaming into the database it doesn’t do the same when users are downloading files – I**’ll leave that as an exercise for the reader!** Also, in production ready code, additional logic should be added to track the maximum number of connections that are able to post to the “/api/files” endpoint at any given time."

Above the "Managing file sizes" section.

**Comment by dmcghan** [comment]
@RavGup Please have another look. Download the app according to the instructions at the bottom. Look at the source code. Try to run the app (may need to run the version of node-oracledb that was used then).

Let me know if you have any questions then.

**Comment by cjbj** [comment]
The next version of node-oracledb (1.13) will have a `fetchAsBuffer` setting to return BLOBs as buffers; until then you can get them as instances of Lob which are Node Streams and stream them out.  Check the [doc](https://github.com/oracle/node-oracledb/blob/master/doc/api.md) and the [examples](https://github.com/oracle/node-oracledb/tree/master/examples).

**Comment by RavGup** [comment]
@dmcghan @cjbj Thanks for response. I downloaded the code. Below is my implementation. 

`exports.downloadFile = function(req,res){
  db.executePackage("ssa_data.PKG_SSA_RG18927.SSA_GetFile(:refCur);",
      {
        refCur: { type: oracledb.CURSOR, dir: oracledb.BIND_OUT }
      },
       function(error,returnRows){
        if (error) {  
          console.error(error);  
          return;  
        } 
        console.log(returnRows);
        res.setHeader('Content-type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=some_file.pdf');
        var data = new Buffer(returnRows.DATA,'base64');
        //var data = new Buffer(returnRows.DATA);
        //data = Buffer.concat(returnRows.DATA);
        res.end();
      })
}`

In above code, "returnRows" contains below response.
[{"DATA":{"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":2,"_writableState":{"objectMode":false,"highWaterMark":16384,"needDrain":false,"ending":false,"ended":false,"finished":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"iLob":{"valid":true,"autoCloseLob":true,"type":2007,"offset":1,"pieceSize":8132,"length":800774,"chunkSize":8132}}}]

How can I have this BLOB to be converted into file.

**Comment by cjbj** [comment]
To expand on my previous answer look at lobstream1.js and lobstream2.js in the [examples](https://github.com/oracle/node-oracledb/tree/master/examples) directory.  If you have questions once you've tried them, yell out.

**Comment by luis-17** [comment]
Hello @cjbj  
I have problem, I verify the examples but get is error: 
`
ERROR	[Error: DPI-1040: LOB was already closed] { errorNum: 0, offset: 0 }
`
This is my code: 

`
     const clobPDF = dataDocumentos[0].contenido; // BLOB get field from BD Oracle
      if (clobPDF === null) { 
        console.log("CLOB was NULL");
        return;
      }
      const promiseDemo = await new Promise((resolve, reject) => {
        const clob = '';
        clobPDF.setEncoding('utf8');  // we want text, not binary output
    
        clobPDF.on('end', function() {
          console.log("clobPDF.on 'end' event ", clob);
        });
        clobPDF.on('close', function() {
          console.log("clobPDF.on 'close' event");
          // resolve();
        });
        clobPDF.on('error', function(err) {
          console.log("clobPDF.on 'error' event");
          console.error(err);
        });
        clobPDF.on('data', function (chunk) {
          console.log("Added chunk("+chunk.length+") to clob("+clob.length+")");
          clob += chunk;
        });
        console.log('resultPDF clobclob ==>', clob);
      });
      console.log('promiseDemo ==>', promiseDemo);

`
I wish I could get the PDF in a buffer or base64 and then upload it to a S3 bucket in serverless lamdba
Help me, y use oracledb 4.2

**Comment by cjbj** [comment]
@luis-17 this issue was closed long ago.  Please open a new one and carefully answer the issue template - you'll need to give a runnable testcase.
