### ISSUE TITLE
ORA-01406 error, not support oracle function ?

### ISSUE THREAD

**Issue by binlaniua** [oracle/node-oracledb#62]
## sql
![image](https://cloud.githubusercontent.com/assets/5960462/6910529/e53decd8-d786-11e4-91af-77035157fdcb.png)

## error
Error: ORA-01406: fetched column value was truncated

**Comment by cjbj** [comment]
@binlaniua can you reproduce this with a simpler table and post the CREATE TABLE statement so we can see the data types?

**Comment by wilkolazki** [comment]
Hi,
I have the same problem. Unfortunatelly I did not manage to reduce the data to locate the exact cause. 
Anyway, my query has about 70 columns. I am trying to fetch about 100 000 rows. The same query runs without problem in Pl/Sql Developer.

Tomorow I will try to reduce the column list until I find problematic column. Then I will try to reproduce it on artificial data.

Best regards,
SWilk

**Comment by cjbj** [comment]
Let us know your NLS environment too.

**Comment by wilkolazki** [comment]
Here it is:

    NLS_LANG=POLISH_POLAND.AL32UTF8  

```
{
"NLS DATABASE PARAMETERS": 
{rows:
   [ [ 'NLS_RDBMS_VERSION', '12.1.0.1.0' ],
     [ 'NLS_NCHAR_CONV_EXCP', 'FALSE' ],
     [ 'NLS_LENGTH_SEMANTICS', 'BYTE' ],
     [ 'NLS_COMP', 'BINARY' ],
     [ 'NLS_DUAL_CURRENCY', '$' ],
     [ 'NLS_TIMESTAMP_TZ_FORMAT', 'DD-MON-RR HH.MI.SSXFF AM TZR' ],
     [ 'NLS_TIME_TZ_FORMAT', 'HH.MI.SSXFF AM TZR' ],
     [ 'NLS_TIMESTAMP_FORMAT', 'DD-MON-RR HH.MI.SSXFF AM' ],
     [ 'NLS_TIME_FORMAT', 'HH.MI.SSXFF AM' ],
     [ 'NLS_SORT', 'BINARY' ],
     [ 'NLS_DATE_LANGUAGE', 'AMERICAN' ],
     [ 'NLS_DATE_FORMAT', 'DD-MON-RR' ],
     [ 'NLS_CALENDAR', 'GREGORIAN' ],
     [ 'NLS_NUMERIC_CHARACTERS', '.,' ],
     [ 'NLS_NCHAR_CHARACTERSET', 'AL16UTF16' ],
     [ 'NLS_CHARACTERSET', 'EE8ISO8859P2' ],
     [ 'NLS_ISO_CURRENCY', 'AMERICA' ],
     [ 'NLS_CURRENCY', '$' ],
     [ 'NLS_TERRITORY', 'AMERICA' ],
     [ 'NLS_LANGUAGE', 'AMERICAN' ] ],
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'PARAMETER' }, { name: 'VALUE' } ] }
},
"NLS SESSION PARAMETERS": 
 { rows:
   [ [ 'NLS_LANGUAGE', 'POLISH' ],
     [ 'NLS_TERRITORY', 'POLAND' ],
     [ 'NLS_CURRENCY', 'zł' ],
     [ 'NLS_ISO_CURRENCY', 'POLAND' ],
     [ 'NLS_NUMERIC_CHARACTERS', ', ' ],
     [ 'NLS_CALENDAR', 'GREGORIAN' ],
     [ 'NLS_DATE_FORMAT', 'RR/MM/DD' ],
     [ 'NLS_DATE_LANGUAGE', 'POLISH' ],
     [ 'NLS_SORT', 'POLISH' ],
     [ 'NLS_TIME_FORMAT', 'HH24:MI:SSXFF' ],
     [ 'NLS_TIMESTAMP_FORMAT', 'RR/MM/DD HH24:MI:SSXFF' ],
     [ 'NLS_TIME_TZ_FORMAT', 'HH24:MI:SSXFF TZR' ],
     [ 'NLS_TIMESTAMP_TZ_FORMAT', 'RR/MM/DD HH24:MI:SSXFF TZR' ],
     [ 'NLS_DUAL_CURRENCY', 'zł' ],
     [ 'NLS_COMP', 'BINARY' ],
     [ 'NLS_LENGTH_SEMANTICS', 'BYTE' ],
     [ 'NLS_NCHAR_CONV_EXCP', 'FALSE' ] ],
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'PARAMETER' }, { name: 'VALUE' } ] }
}
```

**Comment by wilkolazki** [comment]
I have narrowed the issue down to one column. 
``` 
       COLUMN_NAME: 'DESCRIPTION',
       DATA_TYPE: 'VARCHAR2',
       DATA_LENGTH: 35 
```

I will try to create a sample create table script tomorow.

**Comment by cjbj** [comment]
@wilkolazki how are you fetching 100K rows?  Do you bump up maxRows that big?

**Comment by wilkolazki** [comment]
Not exactly. There is about that many rows in the view i am fetching data from. At the moment I am experimenting and fetching first "random" 100 rows (no ORDER BY clause). I was palnning to try to bump maxRows to that size to fetch all of them when there was no more error. If that would be impossible, I was going to sort the rows and fetch them all with paging. Anyway, I have to somehow get all of them and save them as json

**Comment by wilkolazki** [comment]
Hi,

I was able to reproduce this error on artificial data:

```sql
-- Create table
create table TEST_NODE_ORA_01406_TAB
(
  DESCRIPTION VARCHAR2(35) not null
);
alter table TEST_NODE_ORA_01406_TAB
  add constraint TEST_NODE_ORA_01406_PK primary key (DESCRIPTION)
  using index;

insert into test_node_ora_01406_tab 
select substr(lpad( Rownum, 3 , '0' ) || 'ZAŻÓŁĆ GĘŚLĄ JAŹŃ ZAŻÓŁĆ GĘŚLĄ JAŹŃ', 1, 35)
From dual
Connect By Rownum <= 101
```

```javascript
function(err, connection) {
    var query = " select * from vera.TEST_NODE_ORA_01406_TAB t  order by description ";
    //query += " offset 1  rows fetch next 100 rows only ";
    connection.execute(query, [], {}, function(err, result) {
            if (err) {
                console.error(err);    
                connection.release(console.error);
                return;
            }             
            console.log( result);
            connection.release(console.error);
     }
}
```

The query without the OFFSET clause gives the ORA-01406 error. If I uncomment the offset clause and skip at least one row, then the query works correctly. It does not matter if I use limit the rows from 1 to 100 or from 0 to 99. If the query tries to fetch all rows, then it throws error. If the result set is reduced, then it works.

There is one more weird thing. There is something wrong with charset encoding. The "working" query returns malformed: [ '002ZAŻÓŁĆ GĘLĽ JAŃ ZAŻ' ] instead of [ '002ZAŻÓŁĆ GĘŚLĄ JAŹŃ ZAŻÓŁĆ GĘŚLĄ J' ]. 

I hope this helps to reproduce the issue.
Sorry for being so chaotic in this post.

**Comment by cjbj** [comment]
@wilkolazki To run with my AL32UTF8 database, I had to increase the column size so the INSERT worked.  I didn't see a 1406 in various tests.  However, with NLS_LANG=POLISH_POLAND.AL32UTF8 and changing the CREATE to use VARCHAR(51), I didn't get any rows returned by the query nor any error.

I know characterset interaction of Node/v8/node-oracledb is yet to be reviewed.  I'll mark this as a bug so it gets looked at when that review happens, if not sooner.

Can you post your OS, Oracle client library version, and database version?  These are always useful.

If anyone else has a testcase, please post it.

**Comment by wilkolazki** [comment]
@cjbj, here are the system details:
```
$ uname -a
Linux devil 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2 x86_64 GNU/Linux
```
Client library version: Release 11.2.0.3.0 - Production 
```
SQL> select * from v$version
SQL> /
 
BANNER                                                                               CON_ID
-------------------------------------------------------------------------------- ----------
Oracle Database 12c Release 12.1.0.1.0 - 64bit Production                                 0
PL/SQL Release 12.1.0.1.0 - Production                                                    0
CORE	12.1.0.1.0	Production                                                                0
TNS for Linux: Version 12.1.0.1.0 - Production                                            0
NLSRTL Version 12.1.0.1.0 - Production                                                    0
```

Anyway, please ignorme my previous comment:
> There is one more weird thing. There is something wrong with charset encoding. The "working" query returns malformed: [ '002ZAŻÓŁĆ GĘLĽ JAŃ ZAŻ' ] instead of [ '002ZAŻÓŁĆ GĘŚLĄ JAŹŃ ZAŻÓŁĆ GĘŚLĄ J' ].

I have tested the same query from PHP and the encoding was malformed in the same way. Something went wrong when I have been writing the test insert. I have corrected it, so the test data contains proper polish characters. So *character encoding conversion works properly*.

Even after I have corrected the data, I still get an error when trying to fetch unlimited result set
The error have something in to do with maxRows option.
```
$ npm start

> oracle-tests@0.0.0 start /home/swilkolazki/www/oracle-tests
> NODE_PATH=/usr/local/lib/node_modules NLS_LANG=POLISH_POLAND.AL32UTF8 node index.js

{ query: ' select count(*) from TEST_NODE_ORA_01406_TAB t  order by description  \n',
  maxRows: 100 } { rows: [ [ 100 ] ],
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'COUNT(*)' } ] }
{ query: ' select * from TEST_NODE_ORA_01406_TAB t  order by description  \n',
  maxRows: 101 } { rows:
   [ [ '001ZAŻÓŁĆ GĘŚLĄ JAŹŃ ZAŻ' ],
     [ '002ZAŻÓŁĆ GĘŚLĄ JAŹŃ ZAŻ' ],
   /* all the rows goes here */
     [ '100ZAŻÓŁĆ GĘŚLĄ JAŹŃ ZAŻ' ] ],
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'DESCRIPTION' } ] }
{ query: ' select * from TEST_NODE_ORA_01406_TAB t  order by description  \n',
  maxRows: 100 } [Error: ORA-01406: fetched column value was truncated]
```
So, the table contains 100 rows. If I fetch them all and set maxRows = 100, I get error. If I set the maxRows = 101, the query executes correctly.

**Comment by cjbj** [comment]
@wilkolazki thanks for the extra detail.

I want to focus on the ORA-1406 in this issue.  (maxRows is covered in https://github.com/oracle/node-oracledb/issues/65 When node-oracledb supports Result Sets https://github.com/oracle/node-oracledb/issues/13 I am anticipating that most people won't need abnormally large maxRows values.)

**Comment by cjbj** [comment]
@binlaniua @wilkolazki try with node-oracledb 1.0.
We made some fixes, see https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md
