### ISSUE TITLE
lob.on is not a function

### ISSUE THREAD

**Issue by RavGup** [oracle/node-oracledb#620]
Hi, Wrote below code to download the oracle BLOB to file. its giving me an error.
lob.on is not a function.

`var doquery=function(cb){
  oracledb.getConnection(db.connAttrs,function(err,connection){
    if (err) {  
          console.error(err.message);  
          return;  
      } 
      connection.execute("SELECT DATA FROM SSA_DATA.SSA_RG18927_TEST WHERE ID = 29",
        function(err,result){
          if (err) {  
            console.error(err.message);  
            db.doRelease(connection);  
            return;  
          }
          var lob = result.rows[0];
          console.log(lob);
          //db.doRelease(connection);  
          return cb(null,lob);
        })
    });
}

var dostream = function(lob, cb){
  console.log(lob.type);
  if (lob.type === oracledb.CLOB) {
    console.log('Writing a CLOB to ');
    lob.setEncoding('utf8');  // set the encoding so we get a 'string' not a 'buffer'
  } else {
    console.log('Writing a BLOB to ');
  }
  
  lob.on(
    'error',
    function(err)
    {
      // console.log("lob.on 'error' event");
      return cb(err);
    });
  lob.on(
    'end',
    function()
    {
      // console.log("lob.on 'end' event");
    });
  lob.on(
    'close',
    function()
    {
      // console.log("lob.on 'close' event");
      return cb(null);
    });

  var outStream = fs.createWriteStream('outFileName.pdf');
  outStream.on(
    'error',
    function(err)
    {
      // console.log("outStream.on 'error' event");
      return cb(err);
    });

  // Switch into flowing mode and push the LOB to the file
  lob.pipe(outStream);
}
exports.downloadFile = function(req,res){
  async.waterfall([doquery,dostream],function(err){
    console.log(err);
  })
}`

When I console out the lob, its give me output but when i try to get lob.type it says undefined.

I think something I am missing because leak of NODEjs knowledge. Just started using NODEjs a few weeks ago.

**Comment by cjbj** [comment]
Can you give us the CREATE TABLE statement?

**Comment by RavGup** [comment]
below I got it from sql developer export utility.

`CREATE TABLE "SSA_DATA"."SSA_RG18927_TEST" 
   (	"ID" NUMBER, 
	"DATA" BLOB, 
	"FILE_SIZE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SSA_DATA" 
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "SSA_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;`

**Comment by dmcghan** [comment]
@RavGup Please learn how to [put code in Github](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). The example in that link is for JavaScript, but you can use 'sql' and other languages too.

Given the following table:
```sql
create table t (
  c clob,
  b blob
);

insert into t (c, b) values (to_clob('x'), to_blob(utl_raw.cast_to_raw('x')));

commit;
```

This test shows type working as expected.
```javascript
var oracledb = require('oracledb');
var config = require('./dbConfig.js');

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }

  connection.execute(
   `select c, b
    from t`,
    function(err, result) {
      if (err) {
        throw err;
      }

      console.log(result.rows[0][0].type === oracledb.CLOB); // true
      console.log(result.rows[0][1].type === oracledb.BLOB); // true

      connection.close(function(err) {
        if (err) {
          throw err;
        }
      });
    }
  );
});
```

**Comment by pvenkatraman** [comment]
Your usage is wrong
    var lob = result.rows[0];
should be
    var lob = result.rows[0][0]  -> 0th row, 0th Column value.
