### ISSUE TITLE
Slides from a recent node-oracledb talk (and some SODA over REST from Node.js demo info)

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#621]
I've posted the slides from a talk I gave at DeveloperWeek, see link on https://blogs.oracle.com/opal/entry/node_oracledb_session_at_developer

If you want more info on using the SODA document-style access over REST (i.e. not using node-oracledb), take a look at the demo https://www.npmjs.com/package/oracle-movie-ticket-demo on npm.

**Comment by sagiegurari** [comment]
The link is broken

> An error occurred while processing your request.
> Reference #30.7c959d50.1487345219.17c7db3

**Comment by cjbj** [comment]
The links OK - it's the site that is broken.  Probably a snafu during a big blogging platform migration.  Try https://developerweek2017.sched.com/event/8uRv?iframe=no  The PDF link is under my pic.

**Comment by sagiegurari** [comment]
Good doc. you should add a reference to this pdf maybe in the main README

**Comment by cjbj** [comment]
@sagiegurari Good idea. It should definitely go somewhere.  I'll upload it to my blog since the conf download site will disappear in a few months, apparently.
