### ISSUE TITLE
"ID" invalid identifier while using RETURNING INTO a table with auto-generated ID column

### ISSUE THREAD

**Issue by kevtran2000** [oracle/node-oracledb#622]
Hi,  this is my insert statement...
.........
   connection.execute(
      "insert into users (login_name, first_name, last_name, email, password_, role_, usergroup_ ) values (:login_name, :first_name, :last_name, :email, :password_, :role_, :usergroup_) " + 
      "returning \"id\" into :return_id ",

      // The "bind value" 180 for the "bind variable" :id
      {   
          login_name:   'testlogin1', 
          first_name:   'testf1', 
          last_name:    'testL1', 
          email:        'testemail1', 
          password_:    'testpwd1', 
          role_:        'testrole1', 
          usergroup_:   'testug1',
          return_id:    { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }  
      },
       { outFormat: oracledb.OBJECT, autoCommit: true },........

The "users" table has a auto-generated ID column and I want that value back after the insert.  Based on the error, can I only return the values that are passed (login_name, first_name, etc.) and not the eventually generated ID?  When I changed my code to pass "login_name" for example, it returns fine.  But I need the ID.  Is this even possible?  Thanks.

**Comment by kevtran2000** [comment]
FYI, I did escaped the DQuotes around id after keyword RETURNING.  It's just not showing up here.  Like I said, code works for all other columns I am trying to returns - except the auto-generated ID.  Thanks.  Please help.

**Comment by dmcghan** [comment]
@kevtran2000 Double quotes around `id` would make it case sensitive. Did you create the table with double quotes around a lower case `id` column?

**Comment by kevtran2000** [comment]
that's it. the column name was changed recently from id to user_id without me knowing, but thanks for pushing me in that direction to see the issue.  Appreciate it.
