### ISSUE TITLE
Error to connect through node-oracledb (1.6.0) ORA-12170: TNS: Connect timeout

### ISSUE THREAD

**Issue by vijaykjothangiya** [oracle/node-oracledb#626]
I am able to see the error in logs like ,
 "Error while executing pool.getConnection method, [Error: ORA-12170: TNS:Connect timeout occurred\n]"

I am calling Oracle via firewall , one time it worked and after that I am not able to connect and always getting above error.

I am able to curl to the Oracle DB server successfully , what could be the cause that I am always getting now ORA-12170: TNS:Connect timeout occurred ?

Please share the potential causes as I checked my database server is up , able to make connection one time which make sense that all connection string and param are correct.

Thanks,
 VJ

**Comment by cjbj** [comment]
Curl doesn't exercise the right stack - as I said in #502 (I deleted your duplicate post from that issue), try SQL*Plus or tnsping.  Sounds like a base network issue, so there's not much I can comment on from the node-oracledb side except this one thing: upgrade to node-oracledb 1.12.2 so you have the connection ping feature.

**Comment by juveguevara** [comment]
When i faced this error it was due to a Firewall issue between different network compartments. After a firewall request was opened and all Oracle db ports were open. oracledbdriver  was able to connect to oracle database. Please check if firewall is blocking.

**Comment by cjbj** [comment]
@juveguevara good point.

**Comment by smalon** [comment]
seems that i got the same problem with vj.
have you fixed your problem? can you show me your solutions?

**Comment by juveguevara** [comment]
yes this issue was fixed, some of the Oracle needed for connection were closed between the different network compartments. I mean the Oracle database was in a network space and the Node server was in another one. The port we used to connect was 1526, but we asked to check and open some other such as 1522

**Comment by smalon** [comment]
ok. i have solved my problem too. we used vpn(linux) to connect to oracle database. however the router did not go with our prospection, so we added a special rule in the router file and fixed this problem.
Anyway, thank you for your reply.

**Comment by andreborgescastro** [comment]
Hellow guys, I am facing the same issue. Also with the same environment (linux vpn). @smalon , how did you solve?

**Comment by cjbj** [comment]
@andreborgescastro best to open a port or whatever your firewall needs.  But for non-production use, if your proxy allows HTTPS, try adding https_proxy and https_proxy_port setting to a connect descriptor or an Easy Connect string, see https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf  This will be slow, hence only useful for quick testing.
