### ISSUE TITLE
Question: Kill long running queries

### ISSUE THREAD

**Issue by devarsh** [oracle/node-oracledb#627]
How can we kill long running queries on the database, can there be support for sending interrupt to the existing running query from the client which kills the session on the database and throws errors to the client, which initiated the session.

Something like in java using `Statement.Cancel()` on the other thread.

Or what can be possible workaround for that.

**Comment by sagiegurari** [comment]
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#break

**Comment by cjbj** [comment]
I have on my 'to look at' list the OCI call [timeout attributes](http://docs.oracle.com/database/122/LNOCI/handle-and-descriptor-attributes.htm#GUID-2B6D06A7-8EDF-46FF-BDEF-320D293DCA65__GUID-43CFAD8D-AF5F-4A97-B51B-D696B6CF4D1C)  They map to [Oracle Net parameters ](https://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#GUID-4A19D81A-75F0-448E-B271-24E5187B5909) (note the unit is different) which you could set in a sqlnet.ora file right now without waiting for node-oracledb to have an API to set them.
