### ISSUE TITLE
Getting - wrong number or types of arguments in call to 'TESTPROC'

### ISSUE THREAD

**Issue by kevtran2000** [oracle/node-oracledb#628]
I confirmed and triple-checked the table and query, but for some reason, I'm still getting the error in the title.  Do you see anything wrong with my code below?  Thanks.

This is my call code in Node...
........
    connection.execute(
      "BEGIN testProc(:result_set, :app_id); END;" ,
      {   
          app_id:         { val: 3, dir: oracledb.BIND_IN },  
          result_set:     { type: oracledb.SYS_REFCURSOR, dir: oracledb.BIND_OUT }, 
      },
       { outFormat: oracledb.OBJECT, autoCommit: true }, ...........

This is my PROCEDURE code.....

create or replace procedure testProc (result_set out sys_refcursor, app_id IN number)
is 
begin
    open result_set
    for
    SELECT ID AS "_id", save_as AS "saveAs", application_id as "application_id", match as "match", name as "name" 
          FROM T_ENTITY WHERE application_id = app_id;
end;

**Comment by anthony-tuininga** [comment]
The type you have specified is incorrect so (in typical JavaScript fashion) you are getting undefined which translates to a null value. :-) Try using oracledb.CURSOR instead. Take a look at the sample for further illumination if you need it.

https://github.com/oracle/node-oracledb/blob/master/examples/refcursor.js

**Comment by kevtran2000** [comment]
That did it. Thank you.

I'm still new to Oracle and even newer to oracledb on NODE.  So previously, we just use connection.execute to run the SELECTs and the resultset in automatically returned.  I'm currently trying to move everything to PROCEDUREs and I need to duplicate that same result sets because there are already a lot of codes written calling and using those results.  Is the link above the only way to create the same result - meaning using "function fetchRowsFromRS(connection, resultSet, numRows)" to grab small #s of rows at a time and concatenating them into a bigger array and return?  Is there a better/easier way that's closer to how connection.execute handle this (just a return value in a callback)?

**Comment by dmcghan** [comment]
@kevtran2000 ResultSet objects have a [`toQueryStream`](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-724-resultsettoquerystream) method that allows you to work with [streams](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#querystream) instead of recursion. It's really just syntactic sugar, but you might prefer it.

Either way, consider writing an async function that takes in the ResultSet or QueryStream and returns the array so you don't have to keep repeating that.

**Comment by cjbj** [comment]
Oracle Database itself can directly return SELECTs embedded in PL/SQL without fiddling with bind variables.  We call it 'Implicit Result Sets'.  It's not exposed through to node-oracledb (maybe one day it will be), but you can see the general idea of how it is used by looking at the PHP implementation https://blogs.oracle.com/opal/entry/using_php_oci8_2_0
