### ISSUE TITLE
oracledb silently failing on require

### ISSUE THREAD

**Issue by danny95djb** [oracle/node-oracledb#629]
**versions:**
windows 10
node v6.9.4
npm 3.10.10
oracledb@1.12.2

Oracledb built fine without any errors. But once used in a javascript file it silently fails.
When oracledb is uninstalled it correctly errors saying "Cannot find module oraceldb".

**Comment by cjbj** [comment]
@danny95djb how do you know it built OK?  Do you have a `node_modules/oracledb/build/Release/oracledb.node` binary?

I've seen a few people modify the `lib/oracledb.js` require of that binary; I'd like to know more about what situations that seems to be necessary and what the real solution is.

**Comment by pvenkatraman** [comment]
Can you provide your %PATH% environment variable value?  Also provide OCI_INC_DIR & OCI_LIB_DIR. Thanks,

**Comment by danny95djb** [comment]
@cjbj yes the oracledb.node binary is present

@pvenkatraman OCI_INC_DIR=C:\oracleBase\home\oci\include
OCI_LIB_DIR=C:\oracleBase\home\oci\lib\msvc

And in regards to the path variable I've tried it with and without pointing to the node_modules, neither work.

**Comment by cjbj** [comment]
@danny95djb we still need more info.  And you need to do some debugging about what directory `lib/oracledb.js` thinks it's in, and what `require()` path would work.

**Comment by danny95djb** [comment]
@cjbj I'm not sure how i would go about debugging this in all honesty.

**Comment by dmcghan** [comment]
@danny95djb For troubleshooting purposes, you could just edit the file and add `console.log` statements to see if you get any output. I've had to do this at times...

**Comment by cjbj** [comment]
Check the correct RTL is installed. 

It may be a red herring, but look at #615 too
