### ISSUE TITLE
How to retrieve auto-increment value created from trigger on CREATE?

### ISSUE THREAD

**Issue by mrchess** [oracle/node-oracledb#631]
This is just a general question.

I am creating using `execute`, on a database that has a trigger that auto-increments a number column. However after I create, all the result says is 

`{ "rowsAffected": 1 }`

My question: Is there a way for it to also return the auto-incremented number so that I can retrieve this row? Or have the full row return on CREATE?

**Comment by dmcghan** [comment]
@mrchess Have you looked at [`returning into`](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#dmlreturn)? You could return all the columns if you needed to.

If that doesn't help, could you please provide some more details? What does your `execute` statement look like? What does the trigger look like?

**Comment by cjbj** [comment]
The `RETURNING INTO` examples [dmlrupd1.js](https://github.com/oracle/node-oracledb/blob/v1.12.2/examples/dmlrupd1.js) and [dmlrupd2.js](https://github.com/oracle/node-oracledb/blob/v1.12.2/examples/dmlrupd2.js) are runnable.

On the database side, with Oracle Database 12.1, you no longer need the SEQUENCE & TRIGGER solution to do auto-incrementing of inserted row columns.  There is a new syntax like:

```
CREATE TABLE itinerary (id NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 1))
```

**Comment by mrchess** [comment]
That looks like the possible solution. Let me try it in the morning and I will follow up! Thanks.
