### ISSUE TITLE
How to auto reconnect

### ISSUE THREAD

**Issue by sibelius** [oracle/node-oracledb#632]
I would like to be able to reconnect when I receive this error:

> ORA-03114: not connected to ORACLE

**Comment by cjbj** [comment]
A little (well, .... a lot) more background about what you are doing and trying to do would help us give you a sensible answer.

**Comment by sibelius** [comment]
I have a Koa server that connect to an oracle database when the server starts. It will query oracle database based on the user request. But sometimes the connection is lost and I would like to reconnect when this happens.

**Comment by cjbj** [comment]
The trick is to stop errors happening in the first place.  I.e. improve your network.  If the app is seeing a connection related ORA error, you need to release the connection and get a new one.  You could code your app to check for connection errors and to retry the application 'work'. 

The node-oracledb driver will transparently handle failures for unused pooled connections by [pinging](https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#connpoolpinging).  Note the comments about how Oracle 12.2 client always does this.

In future, when [Application Continuity](http://docs.oracle.com/database/122/LNOCI/oci-programming-advanced-topics.htm#LNOCI-GUID-A8DD9422-2F82-42A9-9555-134296416E8F) is usable by node-oracledb, the need for apps to manually 'replay' calls will be reduced or eliminated.  The replay will be transparent.

**Comment by sibelius** [comment]
tks, I'll try to improve the connection for now

**Comment by aesalazar** [comment]
We get the same ORA error if our connection goes down.  Then node drivers seem to get stuck in an infinite promise rejection loop.  How do we have break out or let us know so we can try to reestablish the connection?

**Comment by sibelius** [comment]
@aesalazar you should try to use a connection pool

**Comment by dmcghan** [comment]
@aesalazar Can you share more info or provide a test case? Are you saying the connection is broken and then you try to use `execute`?

**Comment by cjbj** [comment]
@aesalazar getting the same error number doesn't mean you have the same cause.  YOu should open a new issue and give some useful info, such as a running code example.
