### ISSUE TITLE
trying to 'npm install oracledb', getting node-gyp rebuild errors

### ISSUE THREAD

**Issue by Stageright** [oracle/node-oracledb#635]
trying to 'npm install oracledb', getting node-gyp rebuild errors

Windows 10 pro x64
.NET Framework 4.5
SDK Win8.1
MS VS 2015 with C/C++ features
Python 2.7
Oracle Instant Client Version 12.1.0.2.0 Basic and SDK
Nodejs version 6.10.0

![image](https://cloud.githubusercontent.com/assets/26083584/23399191/b6bc0abe-fde2-11e6-92fe-ca89c058f931.png)

Path=C:\oracle\instantclient;C:\Python27\;C:\Python27\Scripts;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\

Error:
```
c:\telegram>npm install oracledb

> oracledb@1.12.2 install c:\telegram\node_modules\oracledb
> node-gyp rebuild


c:\telegram\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1181: эх єфрхЄё  юЄъЁvЄ№ тїюфэющ Їрщы "C:\Users\Aaieieno?aoi?\.node-gyp\6.10.0\Release\node.lib"
[c:\telegram\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\telegram\node_modules\oracledb
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'c:\telegram\package.json'
npm WARN telegram No description
npm WARN telegram No repository field.
npm WARN telegram No README data
npm WARN telegram No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.12.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.12.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\telegram\npm-debug.log
```

**Comment by Stageright** [comment]
davidjlynn thanks for responding!
but i have already solved my own issue
so, i follow this instructions:
I have: a) clear Win10 (just installed Win10 Pro x64, user with admin privilegies and named on ENGLISH)
           b) Registered user on Oracle.com (needed for download)
1) Install NodeJS version 6.10.0 x64. 
2) Reboot.
3) Add folder C:\Test, 
4) Opened CMD prompt (run as Administrator)
5) cd c:\test 
6) npm install --global npm 
7) npm install --global --production windows-build-tools 
8) npm install instantclient 
9) on Environment Variables add Path c:\test\instantclient; 
set OCI_LIB_DIR=c:\test\instantclient\sdk\lib\msvc 
set OCI_INC_DIR=c:\test\instantclient\sdk\include 
10) reboot.
11) npm install oracledb

**Comment by Stageright** [comment]
p.s. after the installation oracledb i get error  The specified procedure could not be found (oracle.node)
i'v solved it by installation Microsoft Visual C++ 2010 Redistributable

**Comment by AlokBansal8** [comment]
@Stageright did you performed the fresh reinstall of Oracledb after installing Microsoft Visual C++ 2010 Redistributable? Can you please update your steps in above comment including the Microsoft Visual C++ 2010 Redistributable?

**Comment by Stageright** [comment]
@AlokBansal8 nope, i didn't. 
1. Install NodeJS version 6.10.0 x64.
2. Reboot.
3. Add folder C:\Test,
4. Opened CMD prompt (run as Administrator)
5. cd c:\test
6. npm install --global npm
7. npm install --global --production windows-build-tools
8. npm install instantclient
9. on Environment Variables add Path c:\test\instantclient;
set OCI_LIB_DIR=c:\test\instantclient\sdk\lib\msvc
set OCI_INC_DIR=c:\test\instantclient\sdk\include
10. reboot.
11. npm install oracledb
12. installation Microsoft Visual C++ 2010 Redistributable

**Comment by AlokBansal8** [comment]
@Stageright I was able to install it in Windows. I would recommend using [oracledb-pb](https://www.npmjs.com/package/oracledb-pb) as discussed in #18.

1. Install node from http://www.nodejs.org
2. Start PowerShell with admin privileges
3. Run `Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force`
4. Run `npm install --global npm-windows-upgrade`
5. Run `npm-windows-upgrade --npm-version latest`
6. Install 64Bit: Microsoft Visual C++ 2010 SP1 Redistributable Package (x64) from [here](http://www.microsoft.com/en-us/download/details.aspx?id=13523).
7. Download instant-client as mentioned [here](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#73-install-the-free-oracle-instant-client-zips).
8. Run `npm install oracledb`

**Note:** If you are using oracledb-pb then your 7th and final step would be:
Run `npm install oracledb-pb`

**Comment by prasadmudedla** [comment]
Still having the problem after trying all the above methods. Is there a way to get this for my Windows 10 64-bit machine?

**Comment by mkvepuri** [comment]
have you tried installing  **npm install --global --production windows-build-tools**, and **npm install --global installclient** before installing **npm install --global oracledb**

**Comment by cjbj** [comment]
@prasadmudedla open a new issue and fill in the template you will see.

**Comment by felipeperezsanchez** [comment]
Si tienes problemas al instalar oracledb, quita la referencia del package.json y vuelve a instalar

firt step, remove oracledb reference from package.json

second step. install again oracledb with "npm install oracledb --save"

**Comment by felipeperezsanchez** [comment]
first step: remove oracledb reference from package.json

second step: reinstall oracledb
