### ISSUE TITLE
Float value in query result is adding 00000000001/2/3 at the end. 

### ISSUE THREAD

**Issue by gaurang171** [oracle/node-oracledb#638]
I am trying to query the table with simple query like

`select id, unit_cost from items;`

now the problem is the unit_cost is a float value and most of them are converted as below. 

```
0.94   -> 0.9400000000000001
27.99 -> 27.990000000000002 
0.35   -> 0.35000000000000003
0.47   -> 0.47000000000000003
```
and lot more. 

There are correct values as well like `0.99, 0.89, 1.99 `etc. 

I tried doing `Round(unit_cost ,2)` but didn't help.

I know JavaScript floating point engine has some issues but here i am not doing any arithmetic operations its just simple retrieval of data what we have in database

4. What is your version of Node.js?
6.9.5  (I also tested with 4 & 7)

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
oracle instant client 11.2   11.2.0.4.0

6. What is your OS and version?
Windows 10 64 bits  (Also tested with Redhat 7 64 bit,  and centos 7 64bits)

7. What compiler version did you use?  For example, with GCC, run `gcc --version`
Visual studio 2015  (Also tested with  GCC 4.8.5 20150623)

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#numberhandling and
https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#fetchasstringhandling

**Comment by cjbj** [comment]
For future readers, see the current doc at https://oracle.github.io/node-oracledb/doc/api.html#numberhandling
