### ISSUE TITLE
No listener

### ISSUE THREAD

**Issue by evghenii** [oracle/node-oracledb#639]
ORA-12541: TNS:no listener

I downloaded oracle base and oracle sdk. Run the test.js file to establish a connection. It says ORA-12541: TNS:no listener. It says that i need to do lsnrctl.start. But there is not listener in current 2 packages which i downloaded based on documentation. Im curious who had this problem before and what is the proper way to solve it.

**Comment by cjbj** [comment]
'2 packages'.  Hmm.  Do you have a database?
Regarding curiosity, I think Google has some good info.

**Comment by evghenii** [comment]
sorry i meant this:
instantclient-basic-macos.x64-12.1.0.2.0.zip
instantclient-sdk-macos.x64-12.1.0.2.0.zip

**Comment by cjbj** [comment]
> Do you have a database?

What was the answer to this?

You can get a free Oracle database from http://www.oracle.com/technetwork/database/database-technologies/express-edition/overview/index.html

**Comment by evghenii** [comment]
Thank you.
