### ISSUE TITLE
ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by advancedits** [oracle/node-oracledb#64]
I have installed oracledb on Windows 7 machine.
I am trying to a connect to a remote host

I am able to use sqlplus to connect, meaning sqlplus USER@'//HOST:PORT/SID'

However when I use node with the same information, I get the TNS error:
ORA-12154: TNS:could not resolve the connect identifier specified

Here's the code:
var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "XXXXXX",
    password      : "XXXXXX",
    connectString : "HOST:PORT\SID"
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }

    console.log('Connection was successful!');

    connection.release(
      function(err)
      {
        if (err) {
          console.error(err.message);
          return;
        }
      });
  });

**Comment by cjbj** [comment]
Try a forward slash in the connect string in Node: it should be identical to the one in SQL*Plus (Note the two initial slashes are optional in any usage).

(Technically you are not using a SID in either case; you are using a Service Name.  SIDs don't work with this 'Easy Connect' syntax).

**Comment by advancedits** [comment]
Awesome that worked!! thanks @cjbj
