### ISSUE TITLE
ORA-01036 for bind-in variable separated by space

### ISSUE THREAD

**Issue by AlokBansal8** [oracle/node-oracledb#642]
I am trying to execute following SQL
``` sql
SELECT id, latitude, longitude, type FROM TABLE_NAME WHERE SDO_WITHIN_DISTANCE(GEOLOC, SDO_GEOMETRY('POINT(:lng :lat)',8307),'distance=2500') = 'TRUE'
```
I am getting following error:
1. Error: ORA-01036
2. Command: oracleDB.getPool().getConnection().execute(sql, [bindValues]);
3. `node -v` => `v7.6.0`
4. Mac OS Sierra

However, following sql is running fine
``` sql
SELECT id, latitude, longitude, type FROM TABLE_NAME WHERE SDO_WITHIN_DISTANCE(GEOLOC, SDO_GEOMETRY('POINT(79 10)',8307),'distance=2500') = 'TRUE'
```

**Comment by cjbj** [comment]
In SQL*Plus try the same statement (with appropriate bind variables set with `VAR`):
```
SELECT id, latitude, longitude, type FROM TABLE_NAME WHERE SDO_WITHIN_DISTANCE(GEOLOC, SDO_GEOMETRY('POINT(:lng :lat)',8307),'distance=2500') = 'TRUE'
```
You should see the same error.  You are trying to substitute in a string context.

You could try creating a JS string like:
```
var bv = 'POINT(79 10)'
```
and then execute:
```
SELECT id, latitude, longitude, type FROM TABLE_NAME WHERE SDO_WITHIN_DISTANCE(GEOLOC, SDO_GEOMETRY(:bv,8307),'distance=2500') = 'TRUE'
```

(Warning: untested solution)
