### ISSUE TITLE
npm ELIFECYCLE ERR! Exit status 3221226525 when i use oracledb for nodejs on win 8.1

### ISSUE THREAD

**Issue by syahiaoui** [oracle/node-oracledb#643]
> node ./bin/www

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! expressjs@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the expressjs@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the expressjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs expressjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls expressjs
npm ERR! There is likely additional logging output above.

**Comment by cjbj** [comment]
Did you not see the template questions?

**Comment by syahiaoui** [comment]
I solved the problem pointing to the right version of oracle in my environment variables.
