### ISSUE TITLE
Module not found: ../build/Release/oracledb with React and React-Router

### ISSUE THREAD

**Issue by amngupta** [oracle/node-oracledb#644]
I am running Linux on my machine and working on a project with React and Oracle. At first I tried to make a simple file to test my Oracle connection https://github.com/amngupta/oracleProject/blob/master/index.js
After successfully connecting to my database, I tried to introduce React for my front-end. That is when I started encountering the error `Module not found: ../build/Release/oracledb`.
Whenever I try to import the [oracle class ](https://github.com/amngupta/oracleProject/blob/master/src/queryEngine/init.js) to my App. I am getting the error. 
I am sure my InstantClient is setup properly since running `yarn test-oracle` which runs the [index.js](https://github.com/amngupta/oracleProject/blob/master/index.js) works perfectly. However, as soon as I run my web-app, the same function fails.

**Comment by sibelius** [comment]
I think you should have a server (koa/express) that exposes oracle based on a REST or GraphQL

**Comment by amngupta** [comment]
@sibelius thanks! That solved my problem.
