### ISSUE TITLE
Error: ORA-21561: OID generation failed

### ISSUE THREAD

**Issue by sibelius** [oracle/node-oracledb#645]
Today it stopped working the connection to my oracle database.

I'm receiving this error:

```
Error: ORA-21561: OID generation failed
```

the connection is working fine using RazorSQL client

node v6.10.0
Instant Client 12.2

**Comment by sibelius** [comment]
fixed adding this to my /etc/hosts

`127.0.0.1 localhost ${hostname}`

${hostname} - `hostname` from terminal

**Comment by calebeaires** [comment]
Instead of put the hostname in /etc/hosts, I just did it in the end and it worked:

```
sudo sh -c "echo '/opt/oracle/instantclient' | tee -a /etc/ld.so.conf.d/oracle_instant_client.conf" && sudo ldconfig
```

**all instant client were installed on opt >> oracle folder.**

**Comment by kishorkumarravi** [comment]
> fixed adding this to my /etc/hosts
> 
> `127.0.0.1 localhost ${hostname}`
> 
> ${hostname} - `hostname` from terminal

I couldnt able to save the file. (MacOS Error code: -4960)

**Comment by cjbj** [comment]
@kishorkumarravi does using a HOSTALIASES environment variable pointing to a custom file help?  
https://github.com/oracle/node-oracledb/issues/458#issuecomment-387760515
https://stackoverflow.com/questions/39201869/aws-python-lambda-with-oracle-oid-generation-failed
