### ISSUE TITLE
Crash on querying a table with 256 columns

### ISSUE THREAD

**Issue by dmytro120** [oracle/node-oracledb#647]
### Background
I wrote a Node.js application whose source code is based on the "webapp.js" example and is viewable at https://github.com/dmytro120/xdbc/blob/master/xdbc.js

In my database, I have a table, SAMPLE, whose structure contains 256 columns.

When I used oracledb 1.11, the following query executed fine:
`SELECT * FROM sample WHERE sample_number = 123456`

Where SAMPLE_NUMBER is the primary key of the table, and 123456 is a valid record with values.

### Problem Description
I recently upgraded to oracledb 1.12 in order to be able to fetch CLOBs as strings. Since then, when I execute the above query, my application crashes without any output. I used windbg to examine the crash, and it's a 0xC0000005 ("The thread tried to read from or write to a virtual address for which it does not have the appropriate access.")

If I manually specify the fields in the SELECT clause, there is no crash up until about 100 fields. At 100 fields manually specified, it sometimes crashes, and sometimes not. At 117 fields manually specified, it seems to crash every time.

#### Details
1. What error(s) you are seeing?
No errors; application crashes with no output.

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
Executing the query
`SELECT * FROM sample WHERE sample_number = 123456`
Logged in as database user who has correct privileges to execute this query.

3. What environment variables did you set?  How *exactly* did you set them?
`process.env['XDBC_HOME'] = process.env['LOCALAPPDATA'] + '/Xinth/XDBC/';`
`process.env['ORACLE_HOME'] = path.join('./oci');`
`process.env['TNS_ADMIN'] = process.env['XDBC_HOME'] + 'Network/Admin/';`
Where './oci' is the location of Oracle Instant Client 12.1.0.2.0

4. What is your version of Node.js?
7.7.2 (but also tried with 6.9.2 with same results) for Windows 64-bit.

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
Oracle Instant Client 12.1.0.2.0 for Windows 64-bit, installed to ./oci/ in application directory.

6. What is your OS and version?
Windows 7 64-bit

7. What compiler version did you use?  For example, with GCC, run `gcc --version`
Visual Studio 2015 Community

**Comment by cjbj** [comment]
Probably a dup of the CLOB issues with the new feature.  1.13 has fixes, but go delayed to look at a mem issue.

**Comment by cjbj** [comment]
Try node-oracledb 1.13, which has some CLOB fetchAsString fixes.

**Comment by dmytro120** [comment]
Problem is fixed with 1.13.
Thanks!!!
