### ISSUE TITLE
Oracle Instant Client LITE v12.2 rpm is missing "libmql1.so" and others

### ISSUE THREAD

**Issue by s130059660** [oracle/node-oracledb#648]
--- Using node-oracledb inside a docker container --- 

Previously, I had no problems working with Oracle Instant Client LITE  v12.1. However, the new Oracle Instant Client LITE v12.2 (`oracle-instantclient12.2-basiclite_12.2.0.1.0-2_amd64.deb`) is missing some required libraries:

>`root@7a8f239e70d6:/# node test.js`
`/usr/lib/node_modules/oracledb/lib/oracledb.js:38`
`throw err;`
`^`

> `Error: libmql1.so: cannot open shared object file: No such file or directory`
`at Object.Module._extensions..node (module.js:598:18)`
`root@7a8f239e70d6:/#`

After manual inspection of aforementioned rpm file, I found that neither `libmql1.so` nor other required libraries were supplied in that particular rpm.

To check that the missing libraries where not omitted on purpose by Oracle, I downloaded the zip format of the same lite client (`instantclient-basiclite-linux.x64-12.2.0.1.0.zip`) and found all those missing libraries to be there. So the issue is only in the rpm file.

I could've just used the the full blown rpm client (`oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb`) which doesn't exhibit this issue but that would makes the node container fatter by at least 100 MB.

**Comment by cjbj** [comment]
Known issue; being recut.  I've been very busy, but in a quick test the other day I didn't see any problem building and running node-oracledb even as it is.

**Comment by s130059660** [comment]
Seems Oracle has "silently" updated their Instant Client.
The updated one has fixed the issue for me.

Thanks Oracle/Jones

**Comment by cjbj** [comment]
Yes the 32 & 64 bit 'basiclite' RPMs were just updated. Thanks for confirming and sorry you weren't able to use the new version for a few extra days. 

To reiterate, I don't believe this affected node-oracledb.  The best place to report Instant Client issues that aren't node-oracledb related are Oracle Support or directly to me.  (The lack of version number changes annoy me too; improving the process is another ongoing task I'm aware of.)
