### ISSUE TITLE
NJS-010: unsupported data type in select list

### ISSUE THREAD

**Issue by Dec-** [oracle/node-oracledb#650]
Hi,

I'm getting an error when trying to select table with field date type interval day to second.
NJS-010: unsupported data type in select list

Can someone help me with this problem?

**Comment by dmcghan** [comment]
@Dec- That data type doesn't make sense in JavaScript. If you need it in your application, you probably want to convert it to a string with `to_char`.

Given the following:
```sql
create table t (c interval day to second);

insert into t (c) values (to_dsinterval('0 6:30:00' ));

commit;
```

This script works:
```javascript
var oracledb = require('oracledb');
var config = require('./dbConfig.js');

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }

  connection.execute(
   `select to_char(c)
    from t`,
    function(err, result) {
      if (err) {
        throw err;
      }

      console.log(result.rows[0][0]); // '+00 06:30:00.000000'

      connection.close(function(err) {
        if (err) {
          throw err;
        }
      });
    }
  );
});
```

**Comment by Dec-** [comment]
Thx :)

But im getting new error: 01877. 00000 -  "string is too long for internal buffer"

Any info on that?

**Comment by cjbj** [comment]
@dec what code (and DDL) is giving you that error?
