### ISSUE TITLE
do i need call commit(cb) after execute with {autocommit : true} before close connection?

### ISSUE THREAD

**Issue by ds24ru** [oracle/node-oracledb#653]
hello.

if i'am set autoCommit : true when call execute and after close connection i get "Connection cannot be released because a database call is in progress)"

but if i'am do commit and in callback function call close connection - where no errors.

**Comment by cjbj** [comment]
Please give us a runnable testcase.

**Comment by dmcghan** [comment]
@ds24ru You are likely forgetting to return the result of calling the async method in your promise chain. If you don't return the promise, then `undefined` is returned by default. The `undefined` value is then passed to the next `then` block immediately as there's no promise to resolve first. 

Have another [look at the doc](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#promiseoverview) or this example from a similar question: https://github.com/oracle/node-oracledb/issues/655

**Comment by ds24ru** [comment]
thanks men, it was my mistake in code.
