### ISSUE TITLE
About send the oracle of the array

### ISSUE THREAD

**Issue by step2414** [oracle/node-oracledb#654]
When I send the oracle an array, i will receive an error :`'wrong number or types of arguments in call to 'INPUT_RECHARGE_LOG'`.I according to the development of the document,but i always receive this error,is I write wrong?how to fix it ? please help me to solve this problem,thank you very much!

this is my oracle function 
 ```
function input_recharge_log(l_work_date varchar2,r_tot in recharge_tot_tab) return number
is
begin
 
  for all i in 1 .. r_tot.count
      insert into emp_mess_wx_recharge_log(work_date,
                                           input_date,
                                           input_iccard_no,
                                           input_amnt,
                                           wx_id,
                                           input_id) 
    values (to_date(l_work_date,'yyyymmdd'),
                 r_tot(i).input_date,
                 r_tot(i).input_iccard_no,
                 r_tot(i).input_amnt,
                 r_tot(i).wx_id,
                 r_tot(i).input_id);     
  commit;
  return 0;
exception
  when others then
     --dbms_output.put_line(sqlerrm);
     return 1; 
end;
```
this is my js code  
```
oracle.getConnection(function(err,connection) {
        if (err) {console.log(err);}
        connection.execute("BEGIN :ret :=spk_wx_emp_mess.input_recharge_log(:l_work_date, :r_tot); END;",{l_work_date:'20170316143524',
                                                                                                          r_tot:{dir:oracle.BIND_IN,
                                                                                                                 type:oracle.STRING,
                                                                                                                 val:['20170316143524','13131313131313','100','1230','8284923849284']
                                                                                                                },
                                                                                                          ret:{dir:oracle.BIND_OUT,type:oracle.STRING,maxSize:4000}
    },function (err,result) {
             if (err) { console.log('input_recharge_log with error ',err);}
        })
    })
```

**Comment by cjbj** [comment]
How are `recharge_tot_tab` and `emp_mess_wx_recharge_log` defined?  Check the examples in https://github.com/oracle/node-oracledb/blob/v1.13.0/doc/api.md#plsqlindexbybinds

**Comment by anthony-tuininga** [comment]
Based on the SQL you provided, you are trying to bind an array of PL/SQL records. That is not currently supported by the driver.

**Comment by anthony-tuininga** [comment]
We're tracking this in issue #348

**Comment by dmcghan** [comment]
@anthony-tuininga I just saw this one... I'm not sure it's related to binding PL/SQL record types.

We need to know how `recharge_tot_tab` is defined.

The return type in the PL/SQL procedure is defined as a number but as a string in the JS binding. I'd think an implicit conversion would happen, but maybe not?

**Comment by anthony-tuininga** [comment]
True. It could be an array of a SQL table type instead of a PL/SQL record type -- but they are both handled the same way and they are also both not supported!

**Comment by dmcghan** [comment]
It could be an array of strings, no?

**Comment by dmcghan** [comment]
@anthony-tuininga Sorry. I just saw what you were seeing :)

@step2414 Also see this for more examples you can use until proper support is added to the driver:
https://jsao.io/2017/01/plsql-record-types-and-the-node-js-driver/

**Comment by step2414** [comment]
@cjbj @anthony-tuininga @dmcghan,thank you for your help! the structure of the` recharge_tot_tab`  is  similar to` [(date,id,name),(date,id,name),(date,id,name),...]` and now i think I found a solution like this answer @dmcghan , finally,i hope oracle can support this`records type` in the future!
