### ISSUE TITLE
Does it support Custom Objects for Bind input to Stored procedure ? 

### ISSUE THREAD

**Issue by dsreddy2384** [oracle/node-oracledb#656]
i have Custom Database Object that we would like to pass as input to Stored Procedure.
something like this
--custom_table as OBJECT
{
varchar2,
NUMBER,
varchar2}

--custom_object as table of custom_table
-- store procedure
mypackage.dosomething( test IN VARCHAR2, custom IN custom_object ,cursor OUT SYS_REFCURSOR).

Is there any road map for supporting this ?

**Comment by cjbj** [comment]
This isn't supported as of 1.13.  But keep checking back to see if it is in a future release.
For the moment, you'll have to pass the elements of the object separately as three different bind variables to a wrapper PL/SQL function or block.  This block can then call your existing function.
