### ISSUE TITLE
hotw to outFormat: oracledb.OBJECT with offset and maxnumrows

### ISSUE THREAD

**Issue by souzacristsf** [oracle/node-oracledb#658]
I am using the following command to get more rows

```
Connection.execute (
      Sql,
      {Offset: myoffset, maxnumrows: mymaxnumrows},
      (MaxRows: 1000), cb)
```
How do I use outFormat: oracledb.OBJECT in my case?
I would like to convert array to object using offset and maxRows.
The examples I found had no offset and the maxRows.

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.

v6.9.2

2. What version of node-oracledb are you using?

 oracledb@1.13.0

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

latest,  it is installed disk c:/

4. What is the version of Oracle Database?

Oracle Database 11g Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
CORE	11.2.0.4.0	Production
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

5. What is your OS and version?

Windows 7 profissional 

7. What environment variables did you set?  How *exactly* did you set them?

Everything is working okay

**Comment by cjbj** [comment]
There is no 'Offset' attribute in node-oracledb. Check the [manual](https://github.com/oracle/node-oracledb/blob/master/doc/api.md) for what is available. In general, you want to limit the data queried and transferred from the DB, so you do the limit in SQL.

With Oracle DB 12c, look at using a row-limiting SQL clause such as [OFFSET / FETCH](https://docs.oracle.com/database/122/SQLRF/SELECT.htm#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__BABEAACC):
```
SELECT employee_id, last_name
  FROM employees
  ORDER BY employee_id
  OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
```

Or, for 11.2 and earlier, use a nested query with rownum like
```
select *
from ( select a.*, rownum as rnum
       from (YOUR_QUERY_GOES_HERE -- including the order by) a
       where rownum <= MAX_ROW )
where rnum >= MIN_ROW
```
