### ISSUE TITLE
query change notification (or sub/pub)

### ISSUE THREAD

**Issue by s130059660** [oracle/node-oracledb#659]
There is a cool feature in "python-cx_Oracle" for query change notification (or sub/pub).
https://github.com/oracle/python-cx_Oracle/blob/master/samples/QueryChangeNotification.py

I'm currently making a node.js application that will connect to an Oracle db 
And there is another application (which I have zero control over) connected to the same db.

So, I would like to listen for changes made by that application using a way similar to th python way mentioned above.

Is that possible with the current node-oracledb

Some Information:
- Node.js v7.7.4.
- node-oracledb v1.13.
- Oracle client 12.1.
- Oracle Database 11g.

**Comment by anthony-tuininga** [comment]
That is not currently supported by node-oracledb v1.13 but is a possible enhancement in the upcoming v2 release which is based on the same underlying library (ODPI-C) that cx_Oracle is.

If you can use PL/SQL for your notifications you can do that today. You will need to use the DBMS_CQ_NOTIFICATION package.

**Comment by s130059660** [comment]
Thanks anthony.

But i'm trying to avoid PL/SQL as much as I can.

Hope the new version have close release date

**Comment by cjbj** [comment]
This is being tracked in #559

**Comment by cjbj** [comment]
Note V2 will not initially ship with CQN.  Support for the feature in node-oracledb has not been scheduled.
