### ISSUE TITLE
Incorrect Adjustment of date bind variable during daylight savings (BST)

### ISSUE THREAD

**Issue by pallotjk** [oracle/node-oracledb#661]
### Issue Desciption:

This is an empirical description of our issue.

We are in the UK on "London/Europe" time (BST in summer/GMT in winter).

We have 5 records in our Oracle table (e.g.) "item".

```
name(varchar2(5))    create_dt(date)

ITEM1                 08/MAR/2016 0915
ITEM2                 08/MAR/2016 1015
ITEM3                 08/MAR/2016 1115
ITEM4                 08/MAR/2016 1215
ITEM5                 08/MAR/2016 1315
```

In our node/javascript application code we create a date:
```
var startDt = new Date(2016,2,8,10,0,0);
var bindvars = {date_st: startDate};
```

We then submit this date in the bindvars in our call to your database.simpleExecute 
````
database.simpleExecute(
        'SELECT name FROM item WHERE create_dt > :date_st ',
         bindvars, 
        {
            outFormat: database.OBJECT
        }
    )    
    .then(handleSuccess)
    .catch(handleError);
    
    etc.......
````
We get only ITEM3 to ITEM5 (3 x items) from our query but we would also expect ITEM2 (4 x items).

The strange thing is that if we run this query during the winter (when we are on GMT) then we get the correct result!! (4 x items).  **We only get the issue when we are on BST.**
      
I have debugged this in Visual Studio 2015 by placing a break point at 
```
database.simpleExecute( etc....
```

Then I use the VS "immediate" window to output the date and this is what I get:
```
? bindvars.date_st.toString()
"Tue Mar 08 2016 09:00:00 GMT+0000 (GMT Standard Time)"
```
This looks OK to me!  
When we query directly on the Oracle database 
```
SELECT name FROM item WHERE create_dt > to_date('20160208 10:00:00','YYYYMMDD HH24:MI:SS')
```
We get the correct number of items(4).

This can be fixed by:
```
var startDt = new Date(2016,2,8,10,0,0)
startDt.setMinutes(startDt.getMinutes() + new Date().getTimezoneOffset())
```
Or by using the Oracle "to_date" syntax.
But either looks a little patchy.  

 
#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.
6.9.1
2. What version of node-oracledb are you using?
1.11.1 from https://github.com/bchr02/node-oracledb#prebuild_support
3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

4. What is the version of Oracle Database?
Oracle12
5. What is your OS and version?
Windows 7
6. What compiler version did you use?  For example, with GCC, run `gcc --version`
n/a
7. What environment variables did you set?  How *exactly* did you set them?
n/a
8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
n/a
9. What error(s) you are seeing?
none - just incorrect data returned from data sensitive query

**Comment by dmcghan** [comment]
@pallotjk Did you explicitly set your session time zone? If not, it uses a default from your OS which probably isn't what you want.

See this section of the doc:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#datehandling

**Comment by pallotjk** [comment]
Thx Dan
Ill try tomorrow (late here) then Ill add the outcome to the issue.
Rgds

John

**Comment by cjbj** [comment]
@pallotjk how did you go?  Or will we hear from you again in 6 months?

**Comment by pallotjk** [comment]
Still investigating (DBA/developers are looking at this) - however we believe that this may be a bug with node-oracledb. Remember we are in the UK so, for the query date we are looking at i.e.: 8 March, it really shouldn't matter if we are on (i)local time or (ii)GMT/UTC time as they are exactly the same on that date.  AND why does the same query behave differently if we run the exact same query (i) before and (ii) during the BST period (UK daylight savings).
Part of our problem is that we are running queries against data extracted from a legacy system (which used UK local time).  
We did apply the connection trigger suggested (as per link provided by dmcghan) but this caused other issues. 
Well get back to this thread soon once our investigations are "complete".

**Comment by dmcghan** [comment]
@pallotjk 

What do you get from this (using the driver to execute)?

```sql
select sessiontimezone
from dual
```

Keep in mind that the column in the table is a DATE, it doesn't have a timezone. Part of the problem with using DATE and TIMESTAMP is that the timezone is not explicit, so you have to really know what you're applications are putting in there. 

Is the timezone of your date column GMT/UTC or Europe/London?

When you compare a DATE to a TSWLTZ, Oracle does some conversions, including use of SYS_EXTRACT_UTC on both sides. But UTC from what? That's where the session time zone comes into play. 

Here's an example where the same query gets different results based on the session timezone:
```sql
alter session set time_zone='UTC';
-- Session altered.

select 1
from dual
where to_date('01-apr-2017 12:00', 'dd-mon-yyyy hh24:mi') < to_timestamp_tz('01-apr-2017 12:00 UTC', 'dd-mon-yyyy hh24:mi tzr');
-- no rows selected

alter session set time_zone='Europe/London';
-- Session altered.

select 1
from dual
where to_date('01-apr-2017 12:00', 'dd-mon-yyyy hh24:mi') < to_timestamp_tz('01-apr-2017 12:00 UTC', 'dd-mon-yyyy hh24:mi tzr');
-- 1
```

You can avoid this by explicitly telling Oracle the timezone of your date column with `from_tz`:
```sql
alter session set time_zone='UTC';
-- Session altered.

select 1
from dual
where from_tz(cast(to_date('01-apr-2017 12:00', 'dd-mon-yyyy hh24:mi') as timestamp), 'UTC') < to_timestamp_tz('01-apr-2017 12:00 UTC', 'dd-mon-yyyy hh24:mi tzr');
-- no rows selected

alter session set time_zone='Europe/London';
-- Session altered.

select 1
from dual
where from_tz(cast(to_date('01-apr-2017 12:00', 'dd-mon-yyyy hh24:mi') as timestamp), 'UTC') < to_timestamp_tz('01-apr-2017 12:00 UTC', 'dd-mon-yyyy hh24:mi tzr');
-- no rows selected
```

In your case, the query might look like this if the time zone of the column is 'Europe/London':

```sql
select name
from item 
where from_tz(cast (create_dt as timestamp), 'Europe/London') > :date_st
```

Or like this, if it's UTC:

```sql
select name
from item 
where from_tz(cast (create_dt as timestamp), 'UTC') > :date_st
```

**Comment by cjbj** [comment]
Closing - no feedback.
