### ISSUE TITLE
`node-gyp: command not found` while installing oracledb

### ISSUE THREAD

**Issue by indapublic** [oracle/node-oracledb#662]
Do you have an old version of `node-gyp` installed?  Try updating it.  Also try deleting `$HOME/.node-gyp` or equivalent.

Output for `npm install oracledb --verbose` here: https://gist.githubusercontent.com/indapublic/37d059042cc7b676ca0c2d548656e80f/raw/5a15aa77128576adc3a4158d4cca2e580b2d8725/gistfile1.txt

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.

```
node --version
v7.8.0
```

```
npm --version
4.2.0
```

2. What version of node-oracledb are you using?

Tried to install latest version

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

12.2, installed from archives

```
echo $ORACLE_HOME
/usr/lib/oracle/instantclient_12_2
```

5. What is your OS and version?

```
cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

6. What compiler version did you use?  For example, with GCC, run `gcc --version`

```
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
```

```
python --version
Python 2.7.5
```

7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

`npm install oracledb --verbose` (by root)

9. What error(s) you are seeing?

```
> oracledb@1.13.0 install /tmp/node_modules/oracledb
> node-gyp rebuild

sh: node-gyp: command not found
```

**Comment by indapublic** [comment]
Sorry, If not's your issue, but I can find any information

**Comment by cjbj** [comment]
I see you edited the question; did you fix it?
Did you search for issues with nvm?  E.g. https://github.com/oracle/node-oracledb/issues/615#issuecomment-285853752

**Comment by indapublic** [comment]
@cjbj Accidentally saved post while writing
#615 This is my issue. But there is another reason. This time I just can not install oracledb

**Comment by cjbj** [comment]
Where's your node-gyp located, if you have one?  

Have you tried with a non-nvm Node binary install?

**Comment by indapublic** [comment]
```
node-gyp --version
v3.6.0
```

```
which node-gyp
/root/.nvm/versions/node/v7.8.0/bin/node-gyp
```

> Have you tried with a non-nvm Node binary install?
Are you talking about node-gyp?

**Comment by cjbj** [comment]
So, did you try some things indicated in https://github.com/oracle/node-oracledb/issues/615#issuecomment-285853752 about running node-gyp directly?

All I'm getting is that you hit a problem, but I haven't seen what you've tried to do to solve it.

Regarding binaries, I'm talking about Node.js from https://nodejs.org/en/download/

**Comment by indapublic** [comment]
I'm tried rebuild nodegyp. I installed nodejs from several sources. I tried all install steps on clean CentOS. All the same, unfortunetaly, @cjbj

**Comment by indapublic** [comment]
It's only CentOS issue, I guess. All looks wonderful on OSX

**Comment by cjbj** [comment]
Any progress?

If all else fails, use [Oracle Linux](http://yum.oracle.com/) - it's free and better (TM).

**Comment by sttyerase** [comment]
Why does this even build at all?  Nodejs connectors should be a part of the database client release, just like JDBC comes with Oracle Instant Client.  Python connectors, too.  Make it easy for the users.

**Comment by cjbj** [comment]
@sttyerase I understand the sentiment about build difficulties.  To the specific point about including node-oracledb in Oracle client, I'd vote to keep it (and related drivers like cx_Oracle) in the open source space where we have the ability to make releases whenever we want, as environments can change rapidly or be on a different cycle to the Oracle DB client.  

cx_Oracle has [pre-built binaries](https://blogs.oracle.com/opal/python-cx_oracle-60b2-is-available) on PyPI.  The Node.js stack (e.g node-pre-gyp) for this is a lot more immature and harder to work with, but I haven't forgotten about it.  Once v2 is out with the build advantages of the ODPI-C layer, we'll look at improvements with node-oracledb.

**Comment by sttyerase** [comment]
Thank you, Christopher, for your reply.  I very much agree with the
benefits of keeping the node-oracledb and cx_Oracle driver code in the open
source space.  However, does that preclude Oracle from building it and
releasing it with the client?   In many cases that would be most helpful.
Just a thought.

On Mon, May 29, 2017 at 5:55 AM, Christopher Jones <notifications@github.com

**Comment by cjbj** [comment]
@sttyerase it makes no sense to have multiple distribution methods, one of which (releasing it with the client) would be out of date very quickly and insecure.

**Comment by cjbj** [comment]
Closing due to lack of feedback from @indapublic
