### ISSUE TITLE
how to implement tests?

### ISSUE THREAD

**Issue by sibelius** [oracle/node-oracledb#666]
Should I implement tests against a real oracle database instance or should a mock oracle?

I'm using jest for tests

I would like to do something similar to this one : https://medium.com/@sibelius/testing-a-graphql-server-using-jest-4e00d0e4980e

**Comment by dmcghan** [comment]
This is a difficult question to answer without knowing the specifics of the application and what you're trying to test.

Unit tests often use mock databases (and other services) to keep them fast and simple. Functional/integration tests often hit on a database with a set schema to make sure things work properly.

You'll have to google these terms and figure out what's best for your use case.

**Comment by sibelius** [comment]
I would like to make sure my generated sql queries are valid

is there any package that does something like this?

**Comment by dmcghan** [comment]
@sibelius You definitely want to use the database for that.

**Comment by sibelius** [comment]
can I extract table definitions and validate against it? or to much trouble?

**Comment by dmcghan** [comment]
@sibelius I'm not sure I follow. How would having table definitions validate the SQL you generate against the tables?

**Comment by sibelius** [comment]
- validate SQL (first step)
- validate column and table names (second step)

**Comment by dmcghan** [comment]
@ I don't know anything about your application except that you're generating SQL. The best way I know to validate SQL is to execute it against the database.

**Comment by sibelius** [comment]
against a real database is the best approach, @dmcghan tks for the help

**Comment by C4rmond4i** [comment]
I also want to write unit tests for my graphQL server application, but I'm not sure how to implement them.

Like sibelius, I want to validate my SQL queries, and I know I have to use a real database for that. But I don't know against which schema I should run my tests.

Is it ok to use the same schema as I use for development? And when yes, how should test data for the database be generated? Or is it better to set up a own schema only for tests, already filled with test data?
