### ISSUE TITLE
ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by nitinsinghit** [oracle/node-oracledb#667]
*Delete irrelevant parts of this template.*

Hi ,

I did configure node-oracledb for windows 10 x64. Everything went smooth during installation. What I am not able to figure it out
1. As soon as I install oracle 11g express and run select1.js example I get error `[The specified procedure could not be found. ] error on node-oracle ` If I stop or uninstall oracle 11g express then I get `error ORA-12541: TNS:no listener`

I have installed and uzip Oracle 12.2 client libraries(basic and sdk) in c:/oracle/instantclient
and also set the path for OCI_LIB_DIR and OCI_INC_DIR

Pleas guide me what wrong I am doing here?

Thanks

**Comment by bchr02** [comment]
you need to update PATH environment variable to include c:/oracle/instantclient FIRST before any other paths. So before running you app with need to run this `set PATH=c:/oracle/instantclient;%PATH%`.

**Comment by bchr02** [comment]
You could also set PATH within your app BEFORE your `var oracledb = require('oracledb');`

Something like:

``` javascript
process.env['PATH'] = 'c:/oracle/instantclient;' + process.env['PATH'];
```

**Comment by nitinsinghit** [comment]
@bchr02  I tried both ways and getting error - `ORA-12541: TNS:no listener`. Do I need to install oracle database also?

**Comment by bchr02** [comment]
Well you definitely need a database to connect to. A database does not get installed for you upon installation of node-oracledb. node-oracledb is just a node.js driver for connecting to an oracle database.

**Comment by nitinsinghit** [comment]
@bchr02 As I mentioned above when I installed oracle 11g express  and run select1.js example it breaks. Error I get is```
\nodeOracle\node_modules\oracledb\lib\or
acledb.js:38
    throw err;
    ^

Error: The specified procedure could not be found.
\\?\\nodeOracle\node_modules\oracledb\bu
ild\Release\oracledb.node
```

**Comment by cjbj** [comment]
If you have a database on your machine, then you don't need the Instant Client libraries.  See [INSTALL](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin).  Remove the Instant Client (if not needed for anything else), reinstall node-oracledb (i.e. rebuild to get the correct Oracle libraries used), and try again.

Or, keep both Instant Client and XE but sort out your PATH properly.

**Comment by nitinsinghit** [comment]
@cjbj What folder I need to set for  OCI_LIB_DIR and OCI_INC_DIR if I have oracle 12 XE database on my machine?  Thanks

**Comment by cjbj** [comment]
@nitinsinghit See [INSTALL](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin) for the type of path to use for a 'local database'
```
set OCI_LIB_DIR=C:\oracle\product\12.1.0\dbhome_1\oci\lib\msvc
set OCI_INC_DIR=C:\oracle\product\12.1.0\dbhome_1\oci\include
```
I don't have Windows.  I guess with XE, the path prefix will at least contain `C:\oraclexe\app\oracle\product\11.2.0\server`.

Have you seen #18 ?

**Comment by nitinsinghit** [comment]
Thanks @cjbj !!! I was able to configure Oracle XE successfully.

**Comment by sirish595** [comment]
Hi, i am using the https://github.com/theodo/nodejs-oracledb-buildpack to deploy my node API project to PCF sapce. the oracle installation has went fine and project got deployed successfully with-out any issues. but when i hit my API call to fetch data from oracle db, its throwing the below mentioned error. The path variables - OCI_LIB_DIR and OCI_INC_DIR are configured in the buildpack. 
{
    "error": "ORA-12541: TNS:no listener\n"
}

**Comment by cjbj** [comment]
@sirish595 (i) this issue is closed (ii) ask around and see what your colleagues are using (iii) check Google (iv) start the listener (v) open a new issue.
