### ISSUE TITLE
Oracle Instant Client error in AIX6.1 while trying to execute app

### ISSUE THREAD

**Issue by annjawn** [oracle/node-oracledb#668]
I am trying to test a sample app on our server where I have installed `node-oracledb`. As soon as I run the .js file I see this error-

```
[nsrmsd01:/app/wls/asinst_3/config/OHS/ohs1/dependencies/js]node dbtest.js
terminate called after throwing an instance of 'ExceptionImpl'
  what():  ORA-01804: failure to initialize timezone information

IOT/Abort trap(coredump)
```

I noticed #76 which is similar to this issue however, it seems that scenario is based on Node installed on the DB server. In my case, node is installed in our app server and I can connect to our db server from that server using `sqlplus`. Further, user `oretail` can run `sqlplus` on the app server to connect to the remote db server. 

$ORACLE_HOME is set to the the WLS install home which i think installs the Oracle client on the app server so it looks like below. Using `sqlplus` connects successfully to the db server (which is a separate server).

```
[nsrmsd01:/app/wls/asinst_3/config/OHS/ohs1/dependencies/js]echo $ORACLE_HOME
/app/wls/as_2
```

Is there a specific setup for environment variable for remote db servers?

OS - AIX 6.1
Node Version - 6.10.0
DB Oracle EE - 11.2.0.3.0
Oracle Instant Client - 12.1.0.2.0

**Comment by kushalraid** [comment]
+1
