### ISSUE TITLE
Attribute names isAutoCommit & isExternalAuth changed to autoCommit & externalAuth in node-oracledb 0.5.0

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#67]
Would anyone in this early, pre- version 1.0 development phase of node-oracledb be greatly upset if we changed the attribute names isAutoCommit & isExternalAuth to autoCommit & externalAuth?  No functionality would change, just the names would lose the "is" prefix.

When you look at the list of Oracledb property names those two "is" prefixes stand out awkwardly.
https://github.com/oracle/node-oracledb/blob/master/doc/api.md

**Comment by sagiegurari** [comment]
sounds like a correct change to do

**Comment by cjbj** [comment]
We did change this in node-oracledb 0.5.0: Update your scripts.
