### ISSUE TITLE
Connection.break does not cancel database call

### ISSUE THREAD

**Issue by wvanderdeijl** [oracle/node-oracledb#671]
I am trying to use Connection.break to cancel a pending PL/SQL function execution. However, the break doesn't seem to cancel the execution. If I try to do a `connection.close()` in the break callback it throws `NJS-032: connection cannot be released because a database call is in progress` and the Connection.execute callback is never called.

Any idea what I am doing wrong?

Example code:
```javascript
const oracledb = require('oracledb');
const poolOptions = {
    user: 'system',
    password: 'oracle',
    connectString: 'localhost/xe'
};
console.log('oracledb version', oracledb.version);
oracledb.createPool(poolOptions, (err, pool) => {
    console.log('pool created', err);
    pool.getConnection((err, conn) => {
        console.log('got connection', err);
        console.log('oracle server', conn.oracleServerVersion);
        const sql = 'begin :ret := systimestamp || \'\'; end;';
        const options = { ret: { dir: oracledb.BIND_OUT, type: oracledb.STRING } };
        conn.execute(sql, options, (err, result) => {
            console.log('query complete', err, result);
        });
        conn.break((err) => {
            console.log('break callback', err);
            conn.close((err) => {
                console.log('close callback', err);
            });
        });
    });
});
```

Example output:
```
oracledb version 11300
pool created null
got connection null
oracle server 1102000200
break callback undefined
close callback Error: NJS-032: connection cannot be released because a database call is in progress
    at Error (native)
^C^C^C^C
```

PS. Once this error occurs I can no longer kill the node process with Command-. I have to resort to killing the node process. It actually goes into a 100% cpu loop.

This is all running on latest version of MacOS with oracledb 1.13, instantclient 12.2, and Oracle XE 11.2. The database is running in a docker container.

**Comment by cjbj** [comment]
In this case, I think it is the signal is causing you problems.  I doubt your `break()` is being called. There seems to be some variation with versions (Node & Oracle) and platforms.  See https://github.com/oracle/node-oracledb/issues/128 for some discussion.  Bottom line: add a [signal handler](https://github.com/oracle/node-oracledb/blob/master/examples/webapp.js#L204-L212).

**Comment by wvanderdeijl** [comment]
Sorry for confusing this issue with the sidenote about ctrl-c not working. The main issue is the break() not doing its work. As you can see from the logging I do end up in the break callback so apparently it is doing something. But it is not cancelling the pending database request as the connection.close fails.
This is a simplified version of a real issue I am having where I fail to clean up a database connection in expresses middleware when the pending http request is aborted.

**Comment by cjbj** [comment]
[That's a good lesson about why human multi-tasking doesn't work.]

Bottom line, in subsequent follow up, over a few environments (platforms, VMs etc) there are different behaviors.  It'll need some more research.

**Comment by Stono** [comment]
Adding a signal handler doesn't work @cjbj, I already have it and already do process.exit(0) and it just sticks, I now do `process.kill(process.pid);` after 3 seconds.  It's brutal but the only way that i can get the program to exit

**Comment by VenPot** [comment]
Did anyone find a solution?

**Comment by VenPot** [comment]
@wvanderdeijl how did you address this?

**Comment by dmcghan** [comment]
@VenPot Are you trying to break on Mac, Linux, or Windows?

**Comment by cjbj** [comment]
@VenPot what @dmcghan is getting to is that macOS Instant Client seems to have a bug in this area;  it's being tracked as Oracle bug 25964712.

**Comment by cjbj** [comment]
Revisiting this, it doesn't reproduce with node-oracledb 3.1-dev and Instant Client 12.2.  I get:
```
oracledb version 30100
pool created null
got connection null
oracle server 1800000000
break callback null
query complete { [Error: DPI-1010: not connected] errorNum: 0, offset: 0 } undefined
close callback null
$
```
showing the PL/SQL was broken (and returns an expected error).  This could be a combination of the DPI changes made in V2, or new macOS Instant Client libraries (which were updated 15-Jan-2018 )

Although I didn't need it, in general if you have ^C or break hangs, then try a [sqlnet.ora file ](https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin) containing `DISABLE_OOB=ON`. This helps in network configurations that drop (or in-line) out-of-band breaks,
