### ISSUE TITLE
How to install C/C++ build environment without installing Visual Studio 2013/15 ?

### ISSUE THREAD

**Issue by deveshigate** [oracle/node-oracledb#672]
Hi,

I am trying to install oracledb node driver on windows, but stuck with Prerequisites.

In order to install a C/C++ build environment, do we need to install complete Visual Studio 2013/15 ? Is there any other ways that we can install it separately without installing Visual Studio 2013/15 ?

Please let me know.

OS: Windows 10
NodeJS: 6.0.0
NPM: 3.8.6

**Comment by wvanderdeijl** [comment]
Have a look at https://github.com/felixrieseberg/windows-build-tools
That should install all necessary build tools on windows

**Comment by deveshigate** [comment]
Thanks a lot. I have already found it and was about to try. I hope it will solve the purpose.

**Comment by deveshigate** [comment]
I tried above approach and i am able to install node oracle db driver successfully. But when i run a simple program using node, i am getting error i.e.

D:\Devesh\Runtime>node oracle.js
D:\Devesh\Runtime\node_modules\oracledb\lib\oracledb.js:38
    throw err;
    ^
Error: The specified procedure could not be found.
\\?\D:\Devesh\Runtime\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Devesh\Runtime\node_modules\oracledb\lib\oracledb.js:35:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

I read about this issue and it seems related to PATH issue. But i have already set path i.e.
set OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient\sdk\include

Oracle Instant Client Version - 64-bit - 12.1.0.2.0
Oracle Node Version - 1.13

Is it related to version issue ? Please help.

**Comment by deveshigate** [comment]
Please refer it. it's working for me.

https://github.com/oracle/node-oracledb/issues/105
