### ISSUE TITLE
Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by saballer** [oracle/node-oracledb#673]
I am on Windows 7  64 bit machine. I have installed oracle express 11 g 64 bit. 
I set OCI_LIB_DIR - C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC 
AND
OCI_INC_DIR - C:\oraclexe\app\oracle\product\11.2.0\server\oci\include.
I then did npm install node oracledb and the installation was successful. 

Then I wanted to try examples/select1.js. 

When I run node select1.js  I receive the following errors:
 
C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2\node_modules\oracledb>node select1.js
C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2\node_modules\oracledb\lib\oracledb.js:38
    throw err;
          ^
Error: The specified procedure could not be found.
C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2\node_modules\oracledb\lib\oracledb.js:35:1
9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

What could be causing this error?

**Comment by anthony-tuininga** [comment]
I have seen this before when you have compiled with one version of the OCI libraries and are running with another one (an older one). You can use a tool like Dependency Walker (http://www.dependencywalker.com/) to help figure out if indeed that is taking place. You can also look at your PATH environment variable and see if you have another Oracle Client installation earlier in your PATH.

**Comment by saballer** [comment]
Yes you were correct I had 2 versions, and I re-installed everything. I am only using oracle 11 g express edition. This is the error I am now getting:

C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Pr
ogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C108
3: Cannot open include file: 'oci.h': No such file or directory (..\src\njs\src\njsResultSet.cpp) [C:\Users\sabal.arora\
Documents\AGILE\node-oracleDB2\node_modules\oracledb\build\oracledb.vcxproj]

**Comment by anthony-tuininga** [comment]
The include file 'oci.h' is the main include file for OCI. Check to make sure that it is found in the directory pointed to by OCI_INC_DIR.

**Comment by saballer** [comment]
OCI_LIB_DIR - C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC
OCI_INC_DIR - C:\oraclexe\app\oracle\product\11.2.0\server\oci\include  

These are my paths, not sure why I am still getting error.

**Comment by anthony-tuininga** [comment]
After you make changes you need to make sure that your build directory is cleared. Check the contents to see what it is actually using for the include file directory. Also double check that oci.h is found by issuing the command

`dir %OCI_INC_DIR%\oci.h`

You should see one file there. If you see none, something isn't quite right!

**Comment by saballer** [comment]
So after getting past the last error, I am able to install successfully Oracle DB.

When attempting to test using the examples/select1.js I am receiving the following error:
ORA-12541: TNS:no listener

All my services are running. 

My User is"hr"
Password is "welcome"
And localhost is "localhost:1521/xe"

**Comment by anthony-tuininga** [comment]
That suggests the listener is not running. You can use the command

`lsnrctl status`

at the command prompt to check its status and the command

`lsnrctl start`

to start it up. It should also be available as a Windows service which you can start and stop in the usual way. There are occasions, however, where the listener service is not created until you issue the commands noted above for the first time. Perhaps that is the issue in your case?

**Comment by saballer** [comment]
lsnrctl status gave me the following error:

```
C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2>lsnrctl status

LSNRCTL for 64-bit Windows: Version 11.2.0.2.0 - Production on 17-APR-2017 13:16:48

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
TNS-12541: TNS:no listener
 TNS-12560: TNS:protocol adapter error
  TNS-00511: No listener
   64-bit Windows Error: 2: No such file or directory
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=AFSWWMZTXBDZU9.us.accenturefederal.com)(PORT=1521)))
TNS-12545: Connect failed because target host or object does not exist
 TNS-12560: TNS:protocol adapter error
  TNS-00515: Connect failed because target host or object does not exist
   64-bit Windows Error: 1004: Unknown error
```

lsnrctl start gave me the following error: 
```
C:\Users\sabal.arora\Documents\AGILE\node-oracleDB2>lsnrctl start

LSNRCTL for 64-bit Windows: Version 11.2.0.2.0 - Production on 17-APR-2017 13:18:04

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Starting tnslsnr: please wait...

TNS-12560: TNS:protocol adapter error
 TNS-00530: Protocol adapter error
```

**Comment by cjbj** [comment]
Sounds like the XE DB installation needs revisiting.  Sort that out first.  Make sure you can connect using SQL*Plus.  Then try again with node-oracledb.
