### ISSUE TITLE
Connection Pool, await and async

### ISSUE THREAD

**Issue by StdInOut** [oracle/node-oracledb#675]
Hello Gurus, 

I probably misunderstood the concept of async and await when using it for dealing with connection functions of oracledb.

I've tried to create some wrappers in order to simplify the "Promise chain". So, I've created some functions:

```
...
let connectionPool: db.IConnectionPool;

async function initPool(): Promise<db.IConnectionPool> {
   try {
     connectionPool = await db.createPool(connectionAtributes);
     console.log("ok", connectionPool);
     return connectionPool;
   } catch (err) {
     console.log(err);
   }
};  

export function getPool(): db.IConnectionPool {
   if (! connectionPool) {
       initPool();
   };
   return connectionPool;
};

export function getConnection(): db.IConnection {
    let connection: db.IConnection; 
    
    connectionPool.getConnection().
    then((conn) => {connection = conn; }).
    catch((err) => console.log(err));
    
    console.log(connection.oracleServerVersion);
    return connection; 
};


/// hello world
import * as co from './database/connection';

let sql: string = 'select * from dual where dummy = :p';
let conn: co.TConnection;
let rs  : co.TResultSet;

co.getPool().getConnection().then((c) => conn = c );

rs = co.executeSQL(conn, sql, [{'p': 'X'}]);

rs.getRow().then((r) => (console.log(r))).catch(err => console.log(err));





```

It compiled ok (tsc --lib ES6) but when I execute the code I have the following behavior:

```
select count(*) from v$session where username is not null;
  COUNT(*)
----------
	 2


node hello.world2.js
entrou
/Users/josecaodaglio/OneDrive/Dev/forum/hello.world2.js:7
co.getPool().getConnection().then(function (c) { return conn = c; });
            ^

**TypeError: Cannot read property 'getConnection' of undefined**
    at Object.<anonymous> (/Users/josecaodaglio/OneDrive/Dev/forum/hello.world2.js:7:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3


select count(*) from v$session where username is not null;
  COUNT(*)
----------
	 **6**
/
COUNT(*)
----------
	 2

```

So, the pool connected to database but the code does not block when I supposed it would be. 

I have a good experience writing java and plsql but I am striving now to change the mindset to node/typescript and its asynchronous nature.

Could you guys give me a hint?

1. What is your version of Node.js?  Run examples/version.js to find versions.
v7.7.2

2. What version of node-oracledb are you using?
1.13

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

4. What is the version of Oracle Database?
11.2.0.4.0

5. What is your OS and version?
Mac OS Sierra

6. What compiler version did you use?  For example, with GCC, run `gcc --version`
Tic 2.2.2

**Comment by wvanderdeijl** [comment]
Once you go asynchronous there is no way back and each called also has to be asynchronous.
The initPool function is asynchronous and returns a promise. This means the getPool() function also has to be asynchronous and use the await keyword on the invocation of initPool(). Without the await it will invoke initPool() and gets a promise. However, it is not waiting for the promise to resolve so connectionPool is still undefined

**Comment by StdInOut** [comment]
thanks wvanderdeijl

So the synch / await benefit is that the code will be more understandable, I suppose.
Do you have any best practice / example on how to use oracledb with Typescript? I have a lot of examples but all of them with JS only.

Thanks
