### ISSUE TITLE
Extract Information from variable rows

### ISSUE THREAD

**Issue by theilkhz** [oracle/node-oracledb#677]
I have a question concerning the return of the variable rows.
This is my code. It behaves as it should, that means it returns the correct Array of the SQL Statement.

```javascript
oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      **SQL Statement**,
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }else{
          datadump = result.rows;
          console.log(datadump);
          connection.close();
        }
      });
  });
```
My question is specific to the variable `result.rows`. I noticed that I do not have to initialize the variable _datadump_. It is created within the connection and then printed into the console.

I now want to use this array outside the function, but if I assign a variable from outside the function `oracledb.getConnection`  the result is not stored inside the variable `datadump` from the outside.

## Example
```javascript
var datadump;
oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      **SQL Statement**,
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }else{
          datadump = result.rows;
          connection.close();
        }
      });
  });

console.log(datadump);
```
The return value here is **undefined**
What am I doing wrong, or to ask better how can I get the result in a more elegant way?

I understand that the variable **datadump** is undefined because it did not get any value assigned, but why did it not receive the value from `result.rows` ?

BTW I just started programming with javascript for about 2 months now, so forgive me if my question is stupid.

**Comment by sagiegurari** [comment]
you need to learn a bit about async io in node.js and callbacks + the js event loop.
basically the console.log happens a lot before the getconnection callback and before the execute callback.
checkout few docs from node.js
https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/

**Comment by theilkhz** [comment]
I read the guides and improved my code. 
I noticed that `result.rows` is indeed storing the result inside `datadump`
Thanks for the help
