### ISSUE TITLE
General Question: Best method to insert lots of data, fast

### ISSUE THREAD

**Issue by sanfords** [oracle/node-oracledb#678]
Hello, 

  We have a table that will eventually contain hundreds of millions of rows.  And we need to insert records in blocks of 10,000 to 100,000 rows at a time.  The good news is we only have a few small columns in this table, numeric values only.  (No blobs or streamed objects.)

  What is the absolute fastest way to do these insertions with node-oracledb?

Thanks you!

**Comment by dmcghan** [comment]
@sanfords Have a look at this answer in StackOverflow. The second example uses bulk inserts, which is your best bet:
http://stackoverflow.com/questions/42928986/node-js-oracledb-insert-the-last-date-many-times/42955490#42955490

**Comment by cjbj** [comment]
@sanfords also think about using Data Pump (which is now part of Instant Client, BTW).

**Comment by dmcghan** [comment]
@sanfords Might as well look at Data Pump, SQL*Loader, and External Tables. [This guide covers all three](http://docs.oracle.com/database/122/SUTIL/toc.htm) in parts I, II, and III.

**Comment by sanfords** [comment]
Thank you!  We tested out dmcghan's idea and got a 3x speedup.  We'll look at the others too.

**Comment by cjbj** [comment]
Node-oracledb 2.2 introduces [connection.executeMany()](https://oracle.github.io/node-oracledb/doc/api.html#executemany) (also see [Batch Statement Execution](https://oracle.github.io/node-oracledb/doc/api.html#batchexecution)) making batch data insert more efficient.
