### ISSUE TITLE
Connections are not getting queued in the Connection Pool

### ISSUE THREAD

**Issue by jaipreet-chhatwal** [oracle/node-oracledb#682]
Hello ,

I am using node -oracle module on windows setup with below configuration

1) OS : Windows 64
2)Node version 6.3.1
3) node-oracle version :1.13.1

Below is the oracle props object used to create a pool

    "props": {
        "user": "********",
        "password": "*********************",
        "connectString": "localhost:1521/XE",
        "poolMin": 20,
        "queueRequests" : true,
        "_enableStats"  : true,
        "poolMax": 150,
        "poolTimeout": 1000,
        "poolIncrement" : 5,
        "stmtCacheSize" : 100
        
    },

Issue : The Pool works fine till the concurrency is 10 Req/sec. But when i am increasing the load to 
around 15 Req/seconds , i can see most of the requesting failing .

Pool statistics:
...total up time (milliseconds): 78284
...total connection requests: 2530
...total requests enqueued: 0
...total requests dequeued: 0
...total requests failed: 1459
...total request timeouts: 0
...max queue length: 0
...sum of time in queue (milliseconds): 0
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 0
...avg time in queue (milliseconds): 0
...pool connections in use: 8
...pool connections open: 10
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60000
...poolMin: 10
...poolMax: 150
...poolIncrement: 5
...poolTimeout (seconds): 1000
...poolPingInterval: 60
...stmtCacheSize: 1000000
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 20 

The issues is , the request are not getting queued in the pool , but the property seems to be enabled
in the Pool object .

Does the version of node which i am using supports  queueing /enqueing ..?.  How can i implement the same . Can someone share the sample pooling js implementation using callback . If requried i can also share my file for review .

thanks in advance ,
jaipreet

**Comment by dmcghan** [comment]
@jaipreet-chhatwal That's very strange... Open node_modules/oracledb/lib/pool.js.

Locate the `getConnection` function on line 132. After the variable declarations, say line 137, add the following:
```javascript
console.log(self.queueRequests);
```

Then run the app and see what you get.

**Comment by jaipreet-chhatwal** [comment]
please find below the response , the value comes out to be true.


**self.queueRequests---->true**

Pool statistics:
...total up time (milliseconds): 41137
...total connection requests: 2000
...total requests enqueued: 0
...total requests dequeued: 0
...total requests failed: 380
...total request timeouts: 0
...max queue length: 0
...sum of time in queue (milliseconds): 0
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 0
...avg time in queue (milliseconds): 0
...pool connections in use: 1
...pool connections open: 10
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60000
...poolMin: 10
...poolMax: 150
...poolIncrement: 5
...poolTimeout (seconds): 1000
...poolPingInterval: 60
...stmtCacheSize: 1000000
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 20


regards
Jaipreet

**Comment by dmcghan** [comment]
@jaipreet-chhatwal If the value is true then the next step is to follow the code paths a bit further to find out why it's not working correctly.

On line 156, there's an `if` statement with 3 possible paths. Add console logs to each and the rerun your test. If the queue isn't needed, it will not be used, so throw some load at it and observe the behavior.

**Comment by jaipreet-chhatwal** [comment]
@dmcghan  ,

THis is what i have printed 

  } else if (self._connectionsOut < self.poolMax) { // queueing enabled, but not needed
	  console.log("IFFF self._connectionsOut---->"+self._connectionsOut);
	  console.log("IFFF self.poolMax---->"+self.poolMax);
	  completeConnectionRequest.call(self, getConnectionCb);
  } else { // need to queue the request
	  console.log("ELSEE self._connectionsOut---->"+self._connectionsOut);
	  console.log("ELSEE self.poolMax---->"+self.poolMax);
	  console.log("ELSEE self._usingQueueTimeout---->"+self._usingQueueTimeout);

Result 
self.queueRequests---->true
self.queueRequests---->true
IFFF self._connectionsOut---->8
IFFF self.poolMax---->150

Pool statistics:
...total up time (milliseconds): 60645
...total connection requests: 1996
...total requests enqueued: 0
...total requests dequeued: 0
...total requests failed: 412
...total request timeouts: 0
...max queue length: 0
...sum of time in queue (milliseconds): 0
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 0
...avg time in queue (milliseconds): 0
...pool connections in use: 1
...pool connections open: 10
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60000
...poolMin: 10
...poolMax: 150
...poolIncrement: 5
...poolTimeout (seconds): 1000
...poolPingInterval: 60
...stmtCacheSize: 1000000
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 20


One more Result ::: In the error i am getting below oracle message :ORA-12516: TNS:listener could not find available handler with matching protocol stack\n

regards
jaipreet

**Comment by dmcghan** [comment]
@jaipreet-chhatwal I'm guessing that error is the problem. There are some suggestions around the internet on how to fix it. Give those a try and see what you get.

By the way, you said "error", but are you getting many errors? In other words, do the number of errors equal the number of failed requests?

If so, surely the queue is not the problem.

**Comment by cjbj** [comment]
If most requests are failing, then it's possible the pool isn't maxed out.  New connection requests will see the pool isn't full and will skip the pool queue. Instead, a connection attempt will be made which returns an error and doesn't use a pool entry.  Repeat.  In this scenario, I wouldn't expect the queue to be used.

Check out the pool settings comments in https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md#connpooling You might want to keep poolMin & poolMax the same.

**Comment by cjbj** [comment]
Closing - no feedback.
