### ISSUE TITLE
Fail doing'node-gyp rebuild'

### ISSUE THREAD

**Issue by LaureMonlouis** [oracle/node-oracledb#683]
Hello everyone !

I have seen several issues quite similar but not exactly the same issue.

I have error doing "npm install oracledb", please find attached the log.

I followed instructions there : https://github.com/oracle/node-oracledb/blob/master/INSTALL.md.

I use Windows 7 x64 and I already set my proxy with npm config set https-proxy http://xxxx:xxxx.
It should be ok about environment variables too, I set them.
Here my versions of node and npm :
```bash
$ node --version
v6.10.2
$ npm --version
3.10.10
```
I tried these commands : `npm install node-gyp` (with deleting `$HOME/.node-gyp`) `npm rebuild node-gyp` and everything works fine it seems. So I have no idea what to do know.

Thanks for your help !

[npm-debug.txt](https://github.com/oracle/node-oracledb/files/958636/npm-debug.txt)

**Comment by cjbj** [comment]
Check #18 ?

**Comment by LaureMonlouis** [comment]
Thank you ! It helped me :)
