### ISSUE TITLE
After blob insert with error: Getting ORA-12154: TNS:could not resolve the connect identifier

### ISSUE THREAD

**Issue by larryaubstore** [oracle/node-oracledb#684]
Hi, 

I've used the following example: https://github.com/oracle/node-oracledb/blob/master/examples/lobinsert2.js

Basically, I do the following step:
- I do an insert which returns an error (CANNOT INSERT NULL into one the fields)
- Close the connection
- Do another request
- Get connection fails and return ORA-12154

The getConnection method fails for all other requests, I have to shut down the process to make it work again. 

Do you have any ideas why I'm no longer able to open connection after an error with blob insert ?

**Comment by dmcghan** [comment]
@larryaubstore Can you please provide a reproducible test case?

**Comment by larryaubstore** [comment]
Sorry, it's not possible for me to share my code.

**Comment by dmcghan** [comment]
@larryaubstore You don't have to share your code. But without a reproducible test case, we don't know if there's a problem. Often times people write and example based on their code without anything proprietary or sensitive.

**Comment by larryaubstore** [comment]
I understand your point but it takes a lot a time to do this ...

I found an alternate way to not use blob for now. If this issue become critical, I will take the time to create a reproducible test case. Sorry :-(
