### ISSUE TITLE
The result.rows is []

### ISSUE THREAD

**Issue by FreeGIS** [oracle/node-oracledb#685]
oracle table

create table test (id integer,name varchar2(100),primary key (id));
insert into test values (1,'china');

but I got the result to use oracledb is 👍 
[root@localhost testoracle]# node aa.js
[ { name: 'ID' }, { name: 'NAME' } ]
[]

i got the fulldata to use sqlplus,but no data to use oracledb can you tell me that is why？

**Comment by dmcghan** [comment]
@FreeGIS Could you show us the code you're using? Providing us with a reproducible test case is very helpful.

**Comment by anthony-tuininga** [comment]
Did you commit the data in SQL\*Plus? If not, you will be able to view it just fine in SQL\*Plus but you will not be able to see it in node-oracledb.

**Comment by cjbj** [comment]
Closing - no feedback.
