### ISSUE TITLE
Error: ORA-03113: end-of-file on communication channel, Issue with stale connection from connection pool

### ISSUE THREAD

**Issue by deepakshrma** [oracle/node-oracledb#686]
## Issue with stale connection from connection pool 

We have created a basic library on top of oracledb node module.which consist only execute and some basic utility methods. We are trying to use the connection pool. We are getting ORA-03113: end-of-file issue. We checked the document on pool pining. We applied all the changes mention there like oracledb client and node config. We still getting errors. Please refer to below given details
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbpoolpinginterval 

We have very less user in some of our user environment. This happens when we get request after a long time like 7-8hr.  
Note: We are running services on docker 
**Docker version:** 1.10.3 
**node oracledb config:** 
```js
oracledb.outFormat = oracledb.OBJECT,
var oracleConf = {
    "log": true,
    "poolMax": 30,
    "poolMin": 5,
     "maxRows ":2000
     "idleTimeoutMillis": 180000,
    ...
};
```

**Node.js:** v4.2.6 
**Node.js oracledb**: v1.13.0 
**Oracle client:** 12.2.0.1.0 
**GCC:** gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
**Oracale V:** 
NLSRTL 	11.2.0.3.0	Production
Oracle Database 11g Enterprise Edition 	11.2.0.3.0	64bit Production
PL/SQL 	11.2.0.3.0	Production
TNS for Linux: 	11.2.0.3.0	Production
**OS Details:**
```bash
NAME="Red Hat Enterprise Linux Server"
VERSION="7.0 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.0"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.0 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.0:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0
Red Hat Enterprise Linux Server release 7.0 (Maipo)
Red Hat Enterprise Linux Server release 7.0 (Maipo)
```

**Comment by cjbj** [comment]
Can you describe 'We are getting ORA-03113: end-of-file issue' in more detail?

**Comment by deepakshrma** [comment]
@cjbj Thanks for the reply. 
Like I explained, We have very less user in some of the enviroment. There request are very less. Since we have builded micro-service. The request frequency became more narrow. Whenever server gets request after a long period of time to execute query. The node oracledb lib throws  ORA-03113: end-of-file error.

**Comment by cjbj** [comment]
And then what happens if more requests come in?  Do they also see ORA-3113?

**Comment by deepakshrma** [comment]
We did log stack trace, It seems pool gets reset after that issue.

**Comment by deepakshrma** [comment]
This is the more over lib that we have created:
[Custom node Oracledb](https://gist.github.com/deepakshrma/f9995634e35550006d307b1a5283605b) 
### How to use it 
```js
//initialize the nodedb and pool
var NodeDB = new require('./lib/oracledb');
var oracleConfig = Object.assign({}, $config.app.connectionConfig.oracleConf, {patchConnection: true, verbose:true})
var nodedb = new NodeDB(oracleConfig).init();
nodedb.on('DB:INIT', function (pool) {
    console.log("connection pool has been started");
});
nodedb.on('DB:INIT_ERROR', function (error) {
    console.log("Error while creating pool", error);
});
```
### Oracle config:
```js
var oracleConf = {
    "log": true,
    "poolMax": 30,
    "poolMin": 5,
     "maxRows ":2000
     "idleTimeoutMillis": 180000,
    ...
};
```

**Comment by cjbj** [comment]
I've various thoughts/comments/suggestions:

- work out what is actually killing the connections and stop it; probably a network timeout or DB user profile?

- Confirm you really are using 12.2 client in all node-oracledb environments

- Try with 12.1 client (the default `poolPingInterval` will take effect)

- set `poolMin` to 0 to help reduce the number of unusable sessions in the pool.

**Comment by cjbj** [comment]
And another 'obvious' (thanks @krismohan) point:

- check the app has released all connections back to the pool before the network interruption occurs. If, instead, the app has only called `getConnection()` and then the network fails, a subsequent use of the connection will return the ORA error - this is expected.

**Comment by deepakshrma** [comment]
@cjbj : Thanks.. let me check all the point that you have mentioned above. Will let you know. Please keep this issue open till than.

**Comment by cjbj** [comment]
@deepakshrma  any update on this?  We checked again and didn't see it with 12.x client in our tests.

**Comment by deepakshrma** [comment]
@cjbj : Sry i could not follow you. We have fixed all thing as you mention. Our release date it may end. Since then we are tracking in the lower environments. Till now we did face issue. I m closing issue. I will reopen if there any fix needed.
