### ISSUE TITLE
NJS-002 if creating a new pool after closing a pool before

### ISSUE THREAD

**Issue by C4rmond4i** [oracle/node-oracledb#687]
Hi :)

I am currently developing a REST-Server which uses oracledb. When this server starts, a connection pool gets created. On every request a connection is opened from this pool and closed after the request is finished.
Now I want to this test this server with mocha, and before each test I want to start the server and after each test I want to close it. Every time the server is closed, the connection pool gets closed too.
The problem is, that after I closed my pool via ```pool.close()```, it seems that every new pool created via ```oracledb.createPool()``` is invalid.
I don't know what exactly is the problem, because when ```oracledb.createPool()``` gets called, the error object in the callback is null. I only get an error when trying to create a new connection via ```pool.getConnection()```. The error message is the following:

NJS-002: invalid pool

I don't know if this is a bug or if I am doing something wrong, hope you can help me :)

**Comment by dmcghan** [comment]
@C4rmond4i You're likely referring to the pool you closed. How did you expose it? Do you have a module with an exported property that you're referencing? If so, try exposing a `getPool` method instead and use that to retrieve the pool from within the module.

**Comment by C4rmond4i** [comment]
I'm not sure what exactly you mean, so this is a shortened version of the my code. In my tests, I run ```startServer()``` before each test and ```stopServer()``` after each test. As it seems to me, I don't refer to the old pool, so I don't think that it doesn't work because of this. Can you spot any other mistake I'm doing?
```javascript
const express = require('express');
const oracledb = require('oracledb');
const getConfig = require('./getConfig');
const useMiddlewares = require('./useMiddlewares');

let port;
let app = express();
let server;
let pool;

module.exports.startServer = () =>
    new Promise((resolve) => {
        getConfig().then((config) => {
            port = config.port;
            return oracledb.createPool({
                user: config.user,
                password: config.password,
                connectString: config.connectString,
            });
        }).then((oraclePool) => {
            pool = oraclePool;
            // in the useMiddlewares function I get the connection from the pool
            // and attach it to the express request object
            app = useMiddlewares(app, pool);
            server = app.listen(port, () => {
                resolve();
            });
        }).catch((error) => {
            process.exit(1);
        });
    });

module.exports.stopServer = () =>
    new Promise((resolve, reject) => {
        pool.close().then(() => {
            server.close((error) => {
                if (error) {
                    reject(error);
                } else {
                    resolve();
                }
            });
        }).catch((error) => {
            reject(error);
        });
    });
```

**Comment by dmcghan** [comment]
@C4rmond4i The first thing that stands out is that you're not returning the promises you're declaring in those functions so you can't call `then`/`catch` following their invocations. But that's unrelated.

Could it be that you only have a single instance of the express app? Why not leave the `app` variable declaration where it's at but move the assignment into `startServer`? See if that makes a difference.

You might find [this recent recording interesting](https://www.youtube.com/watch?v=hQgw2WmyuFM).

**Comment by C4rmond4i** [comment]
Thank you very much, i just moved the assignment of the ```app``` variable into ```startServer``` and now my tests are passing and the pool seems valid.

As far as I understand, the promises are returned, because the curly braces of the arrow function are omitted, so I don't need a return statement. These following two ways to write the ```startServer``` function produce the exact same output:
```javascript
module.exports.startServer = () => {
    return new Promise((resolve, reject) => {
        ...
    });
};
```
```javascript
module.exports.startServer = () => 
    new Promise((resolve, reject) => {
        ...
    });
```

**Comment by dmcghan** [comment]
Ah, reminds me of if statements that don't have braces. I'm not a fan of that style so I guess my brain just adds them. :)

Glad it's working for you now.
