### ISSUE TITLE
refcursor as input parameter for node oracle db

### ISSUE THREAD

**Issue by nodeuser2012** [oracle/node-oracledb#689]
I am building an app, which needs to take complex data as input to a stored procedure. Since the support is  confined for only scalar data and oracle pl/sql object types are not supported. can we use oracledb.CURSOR  as BIND-IN parameters.  If possible can you provide any relevant doc

**Comment by cjbj** [comment]
The only way to populate a ref cursor is to pass one from the DB back to the app.  

[Theoretically you can fetch from the returned RC and then pass it back to the DB which can fetch any remaining rows, but this is very uncommon.  You also need to watch out for not displaying all 'prefetched' rows which can 'lose' rows - the 2nd user of the cursor won't see them.  This is easier to show in diagrams than write....]

Write some mapping PL/SQL blocks that assign scalar bind values (bound by node-oracle) to your PL/SQL objects.
