### ISSUE TITLE
when i install electron with node-gyp，i encounter this problem

### ISSUE THREAD

**Issue by mcfly001** [oracle/node-oracledb#690]
C:\Users\zyj266923\.node-gyp\iojs-1.6.2\Release\iojs.lib : fatal error LNK11
06: invalid file or disk full: cannot seek to 0x23755C [D:\desktop-xiami\x-xiam
i-desktop\node_modules\sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fai
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proce
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\node
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--ta
get=1.6.2" "--arch=x64" "--target_platform=win32" "--dist-url=https://atom.io/d
wnload/atom-shell" "--module_name=node_sqlite3" "--module_path=../lib/binding/e
ectron-v1.6-win32-x64"
gyp ERR! cwd D:\desktop-xiami\x-xiami-desktop\node_modules\sqlite3
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild-sqlite3-win"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! XIAMI-MUSIC@3.0.4 rebuild-sqlite3-win: `cd node_modules/sqlite3 && npm
run prepublish && node-gyp configure --module_name=node_sqlite3 --module_path=.
/lib/binding/electron-v1.6-win32-x64 && node-gyp rebuild --target=1.6.2 --arch=
64 --target_platform=win32 --dist-url=https://atom.io/download/atom-shell --mod
le_name=node_sqlite3 --module_path=../lib/binding/electron-v1.6-win32-x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the XIAMI-MUSIC@3.0.4 rebuild-sqlite3-win script 'cd node_mo
ules/sqlite3 && npm run prepublish && node-gyp configure --module_name=node_sql
te3 --module_path=../lib/binding/electron-v1.6-win32-x64 && node-gyp rebuild --
arget=1.6.2 --arch=x64 --target_platform=win32 --dist-url=https://atom.io/downl
ad/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/electron-
1.6-win32-x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the XIAMI-MUSIC package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd node_modules/sqlite3 && npm run prepublish && node-gyp configur
 --module_name=node_sqlite3 --module_path=../lib/binding/electron-v1.6-win32-x6
 && node-gyp rebuild --target=1.6.2 --arch=x64 --target_platform=win32 --dist-u
l=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=
./lib/binding/electron-v1.6-win32-x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs XIAMI-MUSIC
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls XIAMI-MUSIC
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\desktop-xiami\x-xiami-desktop\npm-debug.log

**Comment by cjbj** [comment]
Does your first error indicate a problem?

> invalid file or disk full

Are you using a recent version? 

I'd also recommend reviewing previous issues with Electron and add-ons, since there was once some discussion.

PS the issue template had some questions that help people understand what the base problem might be.

**Comment by mcfly001** [comment]
i'm sorry , i have been resolve this problem but i forget close. i only remove  the .node-gyp folder witch is in the Disk  c and the problem is resolve
