### ISSUE TITLE
download for offline use of the package

### ISSUE THREAD

**Issue by octodevelopers** [oracle/node-oracledb#694]
Hi,
I would like to use the package on a closed network, without access to the internet (with local npm repository, net services, etc.),
on a linux-based server.
Do you have any guidelines for downloading **all** of the components and dependencies needed in order to preform this, other than download a 3rd party add-on which downloads npm's? 
I want to make sure that I will not miss any important dependency or reference in the way.
Thanks.

**Comment by cjbj** [comment]
You may find it easier to install on an identical machine that is network-enabled, and then copy the node_modules/oracledb directory to the other computers.  E.g. like https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#winbins

**Comment by octodevelopers** [comment]
Thanks, will try it out 👍 
is there an option to download the package for **all possible environments**? (Windows 64bit, 32Bit, Linux x86 or Linux x64...)?
I would like to support any application needs in our network.

**Comment by cjbj** [comment]
@octodevelopers theoretically yes, since we only supply source code which is usable everywhere.  But you probably meant binaries, which you will have to build yourself, or use the good work of @bchr02 in #18.
