### ISSUE TITLE
Node.js fails while installing oracle package

### ISSUE THREAD

**Issue by durgeshlingarkar** [oracle/node-oracledb#696]
I am trying to download oracle modules for node.js using following commands on windows 7 machine (64 bit).However the command fails.Below is the error in the log file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'oracle' ]
2 info using npm@4.5.0
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData oracle
8 silly fetchNamedPackageData oracle
9 silly mapToRegistry name oracle
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'oracle',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'oracle',
12 silly mapToRegistry   name: 'oracle',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/oracle
14 verbose request uri https://registry.npmjs.org/oracle
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:09:28 PM
17 verbose request id d7f6a9b75efd161e
18 verbose etag W/"5859be65-4919"
19 verbose lastModified Tue, 20 Dec 2016 23:27:33 GMT
20 http request GET https://registry.npmjs.org/oracle
21 http 304 https://registry.npmjs.org/oracle
22 verbose headers { date: 'Thu, 11 May 2017 06:39:49 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"5859be65-4919"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-lhr6339-LHR',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1494484789.104828,VS0,VE47',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 11 May 2017 06:39:49 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"5859be65-4919"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lhr6339-LHR',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1494484789.104828,VS0,VE47',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/oracle from cache
25 verbose get saving oracle to C:\Users\admin\AppData\Roaming\npm-cache\registry.npmjs.org\oracle\.cache.json
26 verbose correctMkdir C:\Users\admin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule oracle@0.4.1 checking installable status
40 silly cache add args [ 'oracle', null ]
41 verbose cache add spec oracle
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'oracle',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'oracle',
42 silly cache add   name: 'oracle',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed oracle@latest
44 verbose addNamed "latest" is being treated as a dist-tag for oracle
45 info addNameTag [ 'oracle', 'latest' ]
46 silly mapToRegistry name oracle
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'oracle',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'oracle',
49 silly mapToRegistry   name: 'oracle',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri https://registry.npmjs.org/oracle
51 verbose addNameTag registry:https://registry.npmjs.org/oracle not in flight; fetching
52 verbose get https://registry.npmjs.org/oracle not expired, no request
53 silly addNameTag next cb for oracle with tag latest
54 silly addNamed oracle@0.4.1
55 verbose addNamed "0.4.1" is a plain semver version for oracle
56 silly cache afterAdd oracle@0.4.1
57 verbose afterAdd C:\Users\admin\AppData\Roaming\npm-cache\oracle\0.4.1\package\package.json not in flight; writing
58 verbose correctMkdir C:\Users\admin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
59 verbose afterAdd C:\Users\admin\AppData\Roaming\npm-cache\oracle\0.4.1\package\package.json written
60 silly loadAllDepsIntoIdealTree Finishing
61 silly loadIdealTree Finishing
62 silly currentTree lamda
62 silly currentTree +-- bignumber.js@3.1.2
62 silly currentTree +-- core-util-is@1.0.2
62 silly currentTree +-- inherits@2.0.3
62 silly currentTree +-- isarray@0.0.1
62 silly currentTree +-- mysql@2.13.0
62 silly currentTree +-- readable-stream@1.1.14
62 silly currentTree +-- sqlstring@2.2.0
62 silly currentTree `-- string_decoder@0.10.31
63 silly idealTree lamda
63 silly idealTree +-- bignumber.js@3.1.2
63 silly idealTree +-- core-util-is@1.0.2
63 silly idealTree +-- inherits@2.0.3
63 silly idealTree +-- isarray@0.0.1
63 silly idealTree +-- mysql@2.13.0
63 silly idealTree +-- oracle@0.4.1
63 silly idealTree +-- readable-stream@1.1.14
63 silly idealTree +-- sqlstring@2.2.0
63 silly idealTree `-- string_decoder@0.10.31
64 silly generateActionsToTake Starting
65 silly install generateActionsToTake
66 silly generateActionsToTake Finishing
67 silly diffTrees action count 1
68 silly diffTrees add oracle@0.4.1
69 silly decomposeActions action count 8
70 silly decomposeActions fetch oracle@0.4.1
71 silly decomposeActions extract oracle@0.4.1
72 silly decomposeActions test oracle@0.4.1
73 silly decomposeActions preinstall oracle@0.4.1
74 silly decomposeActions build oracle@0.4.1
75 silly decomposeActions install oracle@0.4.1
76 silly decomposeActions postinstall oracle@0.4.1
77 silly decomposeActions finalize oracle@0.4.1
78 silly runTopLevelLifecycles Starting
79 silly executeActions Starting
80 silly install executeActions
81 silly doSerial global-install 0
82 silly doParallel fetch 1
83 verbose correctMkdir C:\Users\admin\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
84 verbose lock using C:\Users\admin\AppData\Roaming\npm-cache\_locks\staging-d6d78cd57fb823f8.lock for E:\Durgesh\node\lamda\node_modules\.staging
85 silly doParallel extract 1
86 silly extract oracle@0.4.1
87 verbose unbuild node_modules\.staging\oracle-dbce3312
88 silly gentlyRm E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312 is being purged from base E:\Durgesh\node\lamda
89 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312
90 verbose tar unpack C:\Users\admin\AppData\Roaming\npm-cache\oracle\0.4.1\package.tgz
91 verbose tar unpacking to E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312
92 silly gentlyRm E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312 is being purged
93 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312
94 silly gunzTarPerm modes [ '777', '666' ]
95 silly gunzTarPerm extractEntry package.json
96 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
97 silly gunzTarPerm extractEntry README.md
98 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
99 silly gunzTarPerm extractEntry LICENSE
100 silly gunzTarPerm modified mode [ 'LICENSE', 420, 438 ]
101 silly gunzTarPerm extractEntry index.js
102 silly gunzTarPerm modified mode [ 'index.js', 420, 438 ]
103 silly gunzTarPerm extractEntry binding.gyp
104 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
105 silly gentlyRm E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312\node_modules is being purged
106 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\.staging\oracle-dbce3312\node_modules
107 silly doParallel preinstall 1
108 silly preinstall oracle@0.4.1
109 info lifecycle oracle@0.4.1~preinstall: oracle@0.4.1
110 silly lifecycle oracle@0.4.1~preinstall: no script for preinstall, continuing
111 silly doReverseSerial remove 0
112 silly doSerial move 0
113 silly doSerial finalize 1
114 silly finalize E:\Durgesh\node\lamda\node_modules\oracle
115 silly doSerial build 1
116 silly build oracle@0.4.1
117 info linkStuff oracle@0.4.1
118 silly linkStuff oracle@0.4.1 has E:\Durgesh\node\lamda\node_modules as its parent node_modules
119 verbose linkBins oracle@0.4.1
120 verbose linkMans oracle@0.4.1
121 silly doSerial global-link 0
122 silly doParallel update-linked 0
123 silly doSerial install 1
124 silly install oracle@0.4.1
125 info lifecycle oracle@0.4.1~install: oracle@0.4.1
126 verbose lifecycle oracle@0.4.1~install: unsafe-perm in lifecycle true
127 verbose lifecycle oracle@0.4.1~install: PATH: C:\Users\admin\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Durgesh\node\lamda\node_modules\oracle\node_modules\.bin;E:\Durgesh\node\lamda\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\Wbem;C:\ProgramData\Oracle\Java\javapath;E:\app\admin\product\11.2.0\client_1\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Python\Python36-32\;C:\Python\Python36-32\Scripts\;C:\Users\admin\AppData\Roaming\Python\Python36\Scripts\;C:\Users\admin\AppData\Roaming\npm
128 verbose lifecycle oracle@0.4.1~install: CWD: E:\Durgesh\node\lamda\node_modules\oracle
129 silly lifecycle oracle@0.4.1~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
130 silly lifecycle oracle@0.4.1~install: Returned: code: 1  signal: null
131 info lifecycle oracle@0.4.1~install: Failed to exec install script
132 verbose unlock done using C:\Users\admin\AppData\Roaming\npm-cache\_locks\staging-d6d78cd57fb823f8.lock for E:\Durgesh\node\lamda\node_modules\.staging
133 silly rollbackFailedOptional Starting
134 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
135 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
136 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
137 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
138 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
139 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
140 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
141 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
142 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
143 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
144 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
145 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
146 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
147 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
148 silly gentlyRm E:\Durgesh\node\lamda\node_modules\oracle is being purged from base E:\Durgesh\node\lamda
149 verbose gentlyRm don't care about contents; nuking E:\Durgesh\node\lamda\node_modules\oracle
150 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
151 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
152 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
153 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
154 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
155 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
156 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
157 silly vacuum-fs purging E:\Durgesh\node\lamda\node_modules\oracle
158 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
159 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
160 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
161 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
162 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
163 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
164 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
165 silly vacuum-fs quitting because other entries in E:\Durgesh\node\lamda\node_modules
166 silly rollbackFailedOptional Finishing
167 silly runTopLevelLifecycles Finishing
168 silly install printInstalled
169 warn enoent ENOENT: no such file or directory, open 'E:\Durgesh\node\lamda\package.json'
170 verbose enoent This is most likely not a problem with npm itself
170 verbose enoent and is related to npm not being able to find a file.
171 warn lamda No description
172 warn lamda No repository field.
173 warn lamda No README data
174 warn lamda No license field.
175 verbose stack Error: oracle@0.4.1 install: `node-gyp rebuild`
175 verbose stack Exit status 1
175 verbose stack     at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
175 verbose stack     at emitTwo (events.js:106:13)
175 verbose stack     at EventEmitter.emit (events.js:191:7)
175 verbose stack     at ChildProcess.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
175 verbose stack     at emitTwo (events.js:106:13)
175 verbose stack     at ChildProcess.emit (events.js:191:7)
175 verbose stack     at maybeClose (internal/child_process.js:886:16)
175 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
176 verbose pkgid oracle@0.4.1
177 verbose cwd E:\Durgesh\node\lamda
178 verbose Windows_NT 6.1.7601
179 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracle"
180 verbose node v6.10.3
181 verbose npm  v4.5.0
182 error code ELIFECYCLE
183 error errno 1
184 error oracle@0.4.1 install: `node-gyp rebuild`
184 error Exit status 1
185 error Failed at the oracle@0.4.1 install script 'node-gyp rebuild'.
185 error Make sure you have the latest version of node.js and npm installed.
185 error If you do, this is most likely a problem with the oracle package,
185 error not with npm itself.
185 error Tell the author that this fails on your system:
185 error     node-gyp rebuild
185 error You can get information on how to open an issue for this project with:
185 error     npm bugs oracle
185 error Or if that isn't available, you can get their info via:
185 error     npm owner ls oracle
185 error There is likely additional logging output above.
186 verbose exit [ 1, true ]

**Comment by cjbj** [comment]
Check https://github.com/oracle/node-oracledb/blob/master/INSTALL.md (and also #18)

**Comment by cjbj** [comment]
Closing due to lack of feedback.
