### ISSUE TITLE
Unable to install. All requirements installed.

### ISSUE THREAD

**Issue by JuanVasquezCabeza** [oracle/node-oracledb#697]
### For installation issues:

Hello, 
Im trying to install oracledb in a windows 7 oc.
I installed visual studio 2015, python 2.7.13, and last version of Node and Npm.
When running npm install oracledb, im getting following errors:

npm verb node v6.10.3
npm verb npm  v4.5.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\juavasqu\AppData\Roaming\npm-cache\_logs\2017-05-15T14_27_
26_784Z-debug.log

Best regards,

**Comment by anthony-tuininga** [comment]
Is there anything more interesting in the complete log of the run? The information provided doesn't help much by itself, unfortunately!

**Comment by JuanVasquezCabeza** [comment]
Thanks for your quick answer.
Next I attach the full log of the operation:

[2017-05-15T16_13_59_938Z-debug - Copy.txt](https://github.com/oracle/node-oracledb/files/1001666/2017-05-15T16_13_59_938Z-debug.-.Copy.txt)

**Comment by anthony-tuininga** [comment]
From the log it looks like you are trying to do this in the directory C:\Windows\System32! Can you try this in another directory? One that you created yourself? You may be running into permissions issues.

**Comment by JuanVasquezCabeza** [comment]
Right:

New Log:

[2017-05-15T16_25_33_490Z-debug.txt](https://github.com/oracle/node-oracledb/files/1001702/2017-05-15T16_25_33_490Z-debug.txt)

**Comment by JuanVasquezCabeza** [comment]
Also getting following message in red in the commandPromt:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\juavasqu\Desktop\node_modules\oracledb\build\oracledb.vcxproj]

**Comment by anthony-tuininga** [comment]
Something doesn't look right. The npm version you claim to be using is 4.5 but the npm that is installed with 6.10.3 is 3.10.10? Can you check that?

**Comment by JuanVasquezCabeza** [comment]
C:\Users\juavasqu\Desktop\Node App>node --version
v6.10.3

C:\Users\juavasqu\Desktop\Node App>npm --version
4.5.0

**Comment by anthony-tuininga** [comment]
The npm version should be 3.10.10 -- that is what is installed with node 6.10.3. There may be issues with using a newer version of npm with an older version of node. And the question is how did you configure your node installation that way?

**Comment by JuanVasquezCabeza** [comment]
Do you think this should be fixed by uninstalling an reinstalling node and npm?

**Comment by anthony-tuininga** [comment]
How are you installing node? If you are using the msi package, it will do everything automatically for you -- both node and npm at the same time.

**Comment by JuanVasquezCabeza** [comment]
the node-v6.10.3-x64.msi is installing the 4.5.0 version of Npm.

**Comment by anthony-tuininga** [comment]
It isn't supposed to be. Take a look [here](https://nodejs.org/en/download/) and note the top line!

**Comment by JuanVasquezCabeza** [comment]
Just Installed the right version of nom by using npm install -g npm@3.10.10
C:\Users\juavasqu\Desktop\Node App>node --version
v6.10.3

C:\Users\juavasqu\Desktop\Node App>npm --version
3.10.10

But still not able to isntall oracledb. Attached Log.


[npm-debug - Copy.txt](https://github.com/oracle/node-oracledb/files/1004754/npm-debug.-.Copy.txt)

**Comment by anthony-tuininga** [comment]
Are you able to build anything else that requires a compiler? Searches suggest that your installation of node-gyp is not setup correctly. It would be nice if the log file contained something useful to go on but it doesn't, unfortunately! Perhaps look [here](https://github.com/nodejs/node-gyp#installation) for inspiration? And test installing another addon that requires a compiler.

**Comment by cjbj** [comment]
Closing due to lack of feedback.

**Comment by santhoshgs** [comment]
followed below steps and it worked.
Catch is - get your NodeJS installed in any of the folder with admin rights, initially my nodejs was installed in ProgramFiles\nodeJs , got this uninstalled and installed other folder having admin rights.

1)npm install --global npm
2)npm install --global --production windows-build-tools
3)npm install instantclient
4)PATH=%cd%\instantclient;%PATH%
set OCI_LIB_DIR=C:\Windows\System32\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\Windows\System32\instantclient\sdk\include
npm install oracledb

**Comment by cjbj** [comment]
@santhoshgs you might want to try the 2.0 branch.

See https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github

Install with `npm install oracle/node-oracledb.git#dev-2.0`
