### ISSUE TITLE
Dates and timestamps with instant client 11.2 require TO_CHAR

### ISSUE THREAD

**Issue by scottrehlander** [oracle/node-oracledb#700]
I will try to spend some time to make an example using the tests, but I'm a bit under the gun right now against a deadline.  

I developed most of my application against Oracle 11g using instant client 12.1 and had no issues.  As soon as I switched to instant client 11.2, I noticed that all SELECT queries against tables with DATE columns failed with DPI-001 internal error messages.  After some digging through the tests, I realized that it won't fail if you add TO_CHAR(DATE_COL) in your SELECT.  Something like this: SELECT ID, TO_CHAR(CREATED_ON) FROM MY_TABLE works fine but SELECT ID, CREATED_ON FROM MY_TABLE fails with DPI-001. 

If I had to guess, I think something is off in the translation of the date object that comes from instant client 11.2 to whatever is used in the node-oracledb lib.  

Sorry that I couldn't be more helpful at the moment, but hopefully anyone else that's running up against it discovers this.

**Comment by cjbj** [comment]
A test would be useful. 

Check that you rebuilt node-oracledb after you changed client versions. 

Our cross-version testing has not shown this issue.

**Comment by cjbj** [comment]
Closing due to lack of feedback.
