### ISSUE TITLE
Deploying a node-oracledb application on Cloud 

### ISSUE THREAD

**Issue by devang28** [oracle/node-oracledb#702]
I have followed and installed the node oracledb from the link [here](https://community.oracle.com/docs/DOC-931127) . To work on the local machine, the method used is appropriate, but how should I resolve the challenges while deploying the same application in a production environment on any cloud service(private or public). Lately, I have been trying to get this work on Pivotal Cloud Foundry`s cloud service but I wasn`t successful. 

Most of the cloud services use their own artifactory or a repository to serve the buildpacks, how should the oracledb be included in one of these nodejs buildpacks? 

Moreover, how should the oracle SDK and Windows SDK(Visual Studio dependency) and Python dependency be handled because in most cases this also wont be there in the cloud environment. 

I am not sure whether this query should have been raised here or any cloud forums but yes since the challenge was with oracledb so I hope  it makes sense.

**Comment by bchr02** [comment]
Give oracledb-pb a try. 

https://www.npmjs.com/package/oracledb-pb

**Comment by cjbj** [comment]
@devang28 you could use Oracle Cloud: https://blogs.oracle.com/opal/scripting-languages-and-oracle-database-cloud-how-to-do-it

node-oracledb is pre-installed on Oracle Application Container Cloud.  For anything else you need to get the node-oracledb shared library and Oracle Instant Client installed. When you've played around, let us know what you decided and how you did it.

**Comment by brunoborges** [comment]
hey @bchr02, is there a reason why one should use oracledb-pb instead of the official driver? oracledb-pb is a fork of this project

**Comment by bchr02** [comment]
My fork doesn't need the dependencies that are needed for compiling, since it includes prebuilt binaries. Also it automatically installs instanctclient and sets up the environment variable so you don't have to. So it makes it easier to get up and running with oracledb.

**Comment by krismohan** [comment]
In case you didn't notice.. Prebuilt binaries are now available for node-oracledb
https://github.com/oracle/node-oracledb/issues/807
