### ISSUE TITLE
Incorrect release notes for 1.13.0

### ISSUE THREAD

**Issue by katerberg** [oracle/node-oracledb#704]
The release documentation indicates that the release notes are available at https://blogs.oracle.com/opal/entry/node_oracledb_1_13_0 but that link appears dead on Oracle's site.

I am looking to upgrade from 1.11.0 and do not know what issues I will encounter.

**Comment by katerberg** [comment]
It looks like it should perhaps point here: https://blogs.oracle.com/opal/node-oracledb-1130-is-available-on-npm

**Comment by cjbj** [comment]
Platform migration hiccup.  Redirects are being looked at. https://twitter.com/ghrd/status/866784346589364224
