### ISSUE TITLE
not able to install oracledb on windows 10

### ISSUE THREAD

**Issue by nehabpdx** [oracle/node-oracledb#707]
windows 10
node 6.10.3
npm 5.0.0
msvs_version=2015

OCI_INC_DIR = C:\Oracle\product\11.2.0\client_1\oci\include
OCI_LIB_DIR= C:\Oracle\product\11.2.0\client_1\oci\lib\msvc
path: C:\Oracle\product\11.2.0\client_1\oci\lib\msvc

python = C:\Users\nbhargava\AppData\Local\Programs\Python\Python36-32\python.exe

D:\EPS_Automation\EPS_Automation\Protractor>npm install --verbose oracledb
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'oracledb' ]
npm info using npm@5.0.0
npm info using node@v6.10.3
npm http fetch GET 304 https://registry.npmjs.org/oracledb 232ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 54ms (from cache)
npm verb correctMkdir C:\Users\nbhargava\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\nbhargava\AppData\Roaming\npm-cache\_locks\staging-6363eec0c86a8878.lock for D:\EPS_Automat
ion\EPS_Automation\Protractor\node_modules\.staging
npm info lifecycle oracledb@1.13.1~preinstall: oracledb@1.13.1
npm info lifecycle nan@2.5.1~preinstall: nan@2.5.1
npm info linkStuff oracledb@1.13.1
npm verb linkBins oracledb@1.13.1
npm verb linkMans oracledb@1.13.1
npm info linkStuff nan@2.5.1
npm verb linkBins nan@2.5.1
npm verb linkMans nan@2.5.1
npm info lifecycle oracledb@1.13.1~install: oracledb@1.13.1

> oracledb@1.13.1 install D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb
> node-gyp rebuild

D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Users\nbh
argava\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  el
se (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js
',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.1
gyp info using node@6.10.3 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "c:\Python27\python.exe" in the PATH
gyp verb `which` succeeded c:\Python27\python.exe c:\Python27\python.exe
gyp verb check python version `c:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned:
 "3.6.1\r\n"
gyp verb could not find "c:\Python27\python.exe". checking python launcher
gyp verb check python launcher python executable found: "C:\\Users\\nbhargava\\.windows-build-tools\\python27\\python.ex
e"
gyp verb check python version `C:\Users\nbhargava\.windows-build-tools\python27\python.exe -c "import platform; print(pl
atform.python_version());"` returned: "2.7.11\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.10.3
gyp verb command install [ '6.10.3' ]
gyp verb install input version string "6.10.3"
gyp verb install installing version: 6.10.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.10.3
gyp verb build dir attempting to create "build" dir: D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\b
uild
gyp verb build dir "build" dir needed to be created? D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\b
uild
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\bu
ild\config.gypi
gyp verb config.gypi checking for gypi file: D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\config.gy
pi
gyp verb common.gypi checking for gypi file: D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\common.gy
pi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\nbhargava\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_
main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\EPS_Automation\\EPS_Automation\\Protractor\\node_modules\\oracledb\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gyp
i',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nbhargava\\.node-gyp\\6.10.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nbhargava\\.node-gyp\\6.10.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node
-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\EPS_Automation\\EPS_Automation\\Protractor\\node_modules\\oracledb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\EPS_Automation\\EPS_Automation\\Protractor\\node_modules\\oracledb\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\nbhargava\.node-gyp\6.10.3
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for ia32 C:\Users\nbhargava\.node-gyp\6.10.3\Release\node.lib
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 5/31/2017 4:01:36 PM.
Project "D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\binding.sln" on node 1 (default target
s).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Win32".
Project "D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\binding.sln" (1) is building "D:\EPS_A
utomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\oracledb\".
  Creating directory "Release\obj\oracledb\oracledb.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\oracledb\oracledb.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\CL.exe /c /I"C:\Users\nbhargava\.node-gyp\6.10.3
  \include\node" /I"C:\Users\nbhargava\.node-gyp\6.10.3\src" /I"C:\Users\nbhargava\.node-gyp\6.10.3\deps\uv\include" /I
  "C:\Users\nbhargava\.node-gyp\6.10.3\deps\v8\include" /IC:\oracle\instantclient\sdk\include /I..\src\dpi\src /I..\src
  \dpi\include /I..\node_modules\nan /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D WIN32_LEAN_AND_MEAN /D NODE_GYP_M
  ODULE_NAME=oracledb /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO
  _DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D BUILDING_NODE_EXTENSION /D _WINDLL /GF /Gm- /MT /GS /
  Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\oracledb\\" /Fd"Release\obj\oracledb\vc140.pd
  b" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /analyze- /errorReport:queue /MP /EHsc ..\src\njs\src\njsOracle.cp
  p ..\src\njs\src\njsPool.cpp ..\src\njs\src\njsConnection.cpp ..\src\njs\src\njsResultSet.cpp ..\src\njs\src\njsMessa
  ges.cpp ..\src\njs\src\njsIntLob.cpp ..\src\dpi\src\dpiEnv.cpp ..\src\dpi\src\dpiEnvImpl.cpp ..\src\dpi\src\dpiExcept
  ion.cpp ..\src\dpi\src\dpiExceptionImpl.cpp ..\src\dpi\src\dpiConnImpl.cpp ..\src\dpi\src\dpiDateTimeArrayImpl.cpp ..
  \src\dpi\src\dpiPoolImpl.cpp ..\src\dpi\src\dpiStmtImpl.cpp ..\src\dpi\src\dpiUtils.cpp ..\src\dpi\src\dpiLob.cpp ..\
  src\dpi\src\dpiCommon.cpp "C:\Users\nbhargava\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_dela
  y_load_hook.cc"
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsConnection.cpp) [D:\E
PS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsResultSet.cpp) [D:\EP
S_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  njsMessages.cpp
  njsIntLob.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsOracle.cpp) [D:\EPS_A
utomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsPool.cpp) [D:\EPS_Aut
omation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  dpiEnv.cpp
  dpiEnvImpl.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiEnv.cpp) [D:\EPS_Auto
mation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  dpiException.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiEnvImpl.cpp) [D:\EPS_
Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsIntLob.cpp) [D:\EPS_A
utomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiConnImpl.h(30): fatal error C1083: Can
not open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiConnImpl.cpp) [D:\EP
S_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cannot
 open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiDateTimeArrayImpl.cpp)
[D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiPoolImpl.cpp) [D:\EPS
_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  dpiUtils.cpp
  dpiLob.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: Can
not open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiStmtImpl.cpp) [D:\EP
S_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  dpiCommon.cpp
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiLob.cpp) [D:\EPS_Auto
mation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  win_delay_load_hook.cc
..\src\dpi\src\dpiCommon.cpp(28): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory [D:\E
PS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cannot
 open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiUtils.cpp) [D:\EPS_Auto
mation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
Done Building Project "D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj" (defau
lt targets) -- FAILED.

Done Building Project "D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\binding.sln" (default ta
rgets) -- FAILED.

Build FAILED.

"D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\binding.sln" (default target) (1) ->
"D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj" (default target) (2) ->
(ClCompile target) ->
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsConnection.cpp) [D:
\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsResultSet.cpp) [D:\
EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsOracle.cpp) [D:\EPS
_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsPool.cpp) [D:\EPS_A
utomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiEnv.cpp) [D:\EPS_Au
tomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiEnvImpl.cpp) [D:\EP
S_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\njs\src\njsIntLob.cpp) [D:\EPS
_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiConnImpl.h(30): fatal error C1083: C
annot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiConnImpl.cpp) [D:\
EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiDateTimeArrayImpl.cpp
) [D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiEnvImpl.h(30): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiPoolImpl.cpp) [D:\E
PS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiStmt.h(30): fatal error C1083: C
annot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiStmtImpl.cpp) [D:\
EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: Ca
nnot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiLob.cpp) [D:\EPS_Au
tomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  ..\src\dpi\src\dpiCommon.cpp(28): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory [D:
\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]
  D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\src\dpi\src\dpiUtils.h(30): fatal error C1083: Cann
ot open include file: 'oci.h': No such file or directory (compiling source file ..\src\dpi\src\dpiUtils.cpp) [D:\EPS_Au
tomation\EPS_Automation\Protractor\node_modules\oracledb\build\oracledb.vcxproj]

    0 Warning(s)
    14 Error(s)

Time Elapsed 00:00:03.41
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\nbhargava\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp
\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\
\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm verb lifecycle oracledb@1.13.1~install: unsafe-perm in lifecycle true
npm verb lifecycle oracledb@1.13.1~install: PATH: C:\Users\nbhargava\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-b
in;D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb\node_modules\.bin;D:\EPS_Automation\EPS_Automation\
Protractor\node_modules\.bin;C:\Oracle\product\11.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system
32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Prog
ram Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Java\jdk1.8.0_121;C:\Program Files\Tort
oiseGit\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\;C:\Program Files\Microsoft SQL Ser
ver\130\Tools\Binn\;C:\Python27\python.exe;C:\Program Files (x86)\nodejs\;C:\Users\nbhargava\AppData\Local\Programs\Pyth
on\Python36-32\python.exe;C:\Users\nbhargava\AppData\Local\Programs\Python\Python36-32\;C:\Users\nbhargava\AppData\Local
\Microsoft\WindowsApps;C:\Users\nbhargava\AppData\Local\atom\bin;C:\Program Files (x86)\MSBuild;C:\Users\nbhargava\AppDa
ta\Roaming\npm
npm verb lifecycle oracledb@1.13.1~install: CWD: D:\EPS_Automation\EPS_Automation\Protractor\node_modules\oracledb
npm info lifecycle oracledb@1.13.1~install: Failed to exec install script
npm verb unlock done using C:\Users\nbhargava\AppData\Roaming\npm-cache\_locks\staging-6363eec0c86a8878.lock for D:\EPS_
Automation\EPS_Automation\Protractor\node_modules\.staging
npm verb stack Error: oracledb@1.13.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\nbhargava\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecy
cle.js:283:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\nbhargava\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.
js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:886:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid oracledb@1.13.1
npm verb cwd D:\EPS_Automation\EPS_Automation\Protractor
npm verb Windows_NT 10.0.14393
npm verb argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\nbhargava\\AppData\\Roaming\\npm\\node_modules\\np
m\\bin\\npm-cli.js" "install" "--verbose" "oracledb"
npm verb node v6.10.3
npm verb npm  v5.0.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nbhargava\AppData\Roaming\npm-cache\_logs\2017-05-31T21_01_45_566Z-debug.log

**Comment by cjbj** [comment]
I see messages "fatal error C1083: Cannot open include file: 'oci.h': No such file or directory"
This means that OCI_INC_DIR isn't set 'correctly' ie. the compiler can't see the variable.   

Also see #18

**Comment by nehabpdx** [comment]
I tried #18 same error i see
