### ISSUE TITLE
Unable to install with node v6.10.2 + npm  v3.10.10

### ISSUE THREAD

**Issue by afirdousi** [oracle/node-oracledb#708]
###  Installation issues:

I review install instructions for MacOS at https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

> My Setup

`node v6.10.2`
`npm v3.10.10`
`Python 2.7.10`
`Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production`
`Mac OS X El Capitan 10.11.6`

> Npm Debug Log 

[Click here](https://gist.github.com/afirdousi/763c8483800475adfd03b022492a93a4) to check npm debug log
[Click here](https://gist.github.com/afirdousi/eed04812eb85bc19cbbf347dcff569a4) to check output of  `npm install --verbose oracledb`

I do have `Xcode installed` on my machine.

>Did the error indicate a network connection issue?  Do you need to set `http_proxy`? 

NO

>Try running `npm cache clean` and deleting the `node_modules/oracledb` directory.

It never got installed in node_modules

> `node-gyp list` gives me the following output

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.2 | darwin | x64
4.0.0
4.4.7
6.10.2
6.2.2
7.9.0
gyp info ok 

```

> `gcc --version` gives me the following 

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Here are the environment variables I set

`export OCI_LIB_DIR=/Users/anasrazafirdousi/Documents/workspace/instaclient`
`export OCI_INC_DIR=/Users/anasrazafirdousi/Documents/workspace/instaclient/sdk/include`

I hope I have given enough information. Is anyone else facing the same?

Any suggestions on what to look into?

Thanks in advance.

**Comment by cjbj** [comment]
This is likely the issue:  https://gist.github.com/afirdousi/eed04812eb85bc19cbbf347dcff569a4#file-oracle-db-install-verbose-L174-L176

Since your DB is 11.2, you should use Instant Client 12.1 (which makes linking node-oracledb easier, but will still connect to DB 11.2).  Installation instructions are in https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

**Comment by afirdousi** [comment]
Installing it all over again exactly on `/opt/oracle/` worked for me. I was using a different project directory while using the same `export` statements given in the guide which was the issue. The exports have the path `opt/oracle/...`.

Thank a bunch @cjbj .
