### ISSUE TITLE
Unable to install. All requirements installed.

### ISSUE THREAD

**Issue by Lebawurscht** [oracle/node-oracledb#709]
Hello,

Im trying to install on Win10. I followed the installation guide step by step (installed Visual Studio, etc.), but i can not install.

C:\dev>npm install oracledb

> oracledb@1.13.1 install C:\dev\node_modules\oracledb
> node-gyp rebuild

C:\dev\node_modules\oracledb>if not defined npm_config_node_gyp (node "c:\dev\emaxx\bpl\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.cc
     Bibliothek "C:\dev\node_modules\oracledb\build\Release\oracledb.lib" und Objekt "C:\dev\node_modules\oracledb\build\Release\oracledb.exp" werden erstellt.
dpiEnv.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDescriptorFree". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnv.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIHandleFree". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnv.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIArrayDescriptorFree". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIEnvNlsCreate". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDescriptorAlloc". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIArrayDescriptorAlloc". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIHandleAlloc". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIMemoryFree". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCITransCommit". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIMemoryAlloc". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIPing". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIContextGetValue". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCITransRollback". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCISessionRelease". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCISessionGet". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIAttrGet". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIServerRelease". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIAttrSet". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIContextSetValue". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIBreak". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDateTimeConstruct". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDateTimeSubtract". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIIntervalGetDaySecond". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDateTimeIntervalAdd". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIIntervalSetDaySecond". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiPoolImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCISessionPoolCreate". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiPoolImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCISessionPoolDestroy". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDefineDynamic". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIStmtExecute". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIDefineByPos2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIBindByName2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIStmtPrepare2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIParamGet". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIBindDynamic". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIBindByPos2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIStmtFetch2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIStmtRelease". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiUtils.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIErrorGet". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobGetChunkSize". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobFreeTemporary". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobGetLength2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobRead2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobWrite2". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobLocatorAssign". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobIsTemporary". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCILobCreateTemporary". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
dpiCommon.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "OCIClientVersion". [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
C:\dev\node_modules\oracledb\build\Release\oracledb.node : fatal error LNK1120: 47 nicht aufgel÷ste Externe [C:\dev\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\dev\emaxx\bpl\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "c:\\dev\\emaxx\\bpl\\node.exe" "c:\\dev\\emaxx\\bpl\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\node_modules\oracledb
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, rmdir 'C:\dev\node_modules'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'C:\dev\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'C:\\dev\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\th\AppData\Roaming\npm-cache\_logs\2017-06-04T12_59_33_965Z-debug.log

**Comment by Lebawurscht** [comment]
[2017-06-04T12_59_33_965Z-debug.txt](https://github.com/oracle/node-oracledb/files/1050328/2017-06-04T12_59_33_965Z-debug.txt)

**Comment by cjbj** [comment]
Generally npm log files aren't that useful but what does this mean in the log:?
```
88 warn Error: EPERM: operation not permitted, rmdir 'C:\dev\node_modules'
88 warn  { Error: EPERM: operation not permitted, rmdir 'C:\dev\node_modules'
88 warn   errno: -4048,
88 warn   code: 'EPERM',
88 warn   syscall: 'rmdir',
88 warn   path: 'C:\\dev\\node_modules' }
89 verbose Please try running this command again as root/Administrator.
```

**Comment by Lebawurscht** [comment]
I have started the dev command promt as admin, this can't be the problem.

**Comment by cjbj** [comment]
What have you tried?  Install into different location?  Different version of npm or node-gyp?

**Comment by Lebawurscht** [comment]
It works now. I had a 32-Bit Oracle Client installed. After i installed a 64-Bit it worked.

**Comment by cjbj** [comment]
Thanks for posting the solution.
