### ISSUE TITLE
Cannot find module 'oracledb'

### ISSUE THREAD

**Issue by jclozadab** [oracle/node-oracledb#71]
Hi,
Dear,

I'm using the following example to start using Node-oracledb (https://www.youtube.com/watch?v=YqMKLTb5-0E), ...
but after having completed the steps, I have the following issue:

[oracle@localhost examples]$ node connect.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oracle/node-oracledb/node-oracledb-master/examples/connect.js:27:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[oracle@localhost examples]$ 

Please let me know how to solve this error.

Regards
JC

**Comment by pvenkatraman** [comment]
Set NODE_PATH environment variable and point it to lib/ directory where oracledb.js is available.

**Comment by jclozadab** [comment]
Hi, pvenkatraman.

The NODE_PATH is correct, see below.  I don't know what happening.

# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
cat /home/oracle/Desktop/readme.txt
export XDB_HOL=/home/oracle/Desktop/Database_Track/XMLDB
export PATH=/home/oracle/node/node-v0.10.28-linux-x64/bin:$PATH
LD_LIBRARY_PATH=/home/oracle/app/oracle/product/12.1.0/dbhome_1/lib
NODE_PATH=/home/oracle/node/node-v0.10.28-linux-x64/lib/node_modules

**Comment by cjbj** [comment]
You show where you think it is set, but you didn't confirm that it is actually set in the shell that invokes node.  Also you should confirm that `ls $NODE_PATH` actually contains `oracledb` (i.e there are no typos in the path).

The install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md have more detail than the video.  The instructions no longer require setting NODE_PATH.

Also, I'd recommend using a newer version of Node 0.10.  The latest is 0.10.38.

**Comment by jclozadab** [comment]
Thank you!

I'm trying to do it all over again with version 0.10.38

**Comment by cjbj** [comment]
For people who do like watching video's, I show a couple of installation methods in https://www.youtube.com/watch?v=3p6rutSLlkg  Windows installation is not discussed in this video.
