### ISSUE TITLE
Performance issue with binding Dates on huge legacy SQL query

### ISSUE THREAD

**Issue by pjatacsukb** [oracle/node-oracledb#711]
Hello!
I have a performance problem with bindig Dates in a huge and complex legacy SQL query.
The query was written by someone else 10 years ago and now I have to use it.
There seems to be a performance issue when I try to bind dates.
I have 3 dates variable that I have to bind:
```SQL
:p_datum_a
:p_datum_c
:p_datum_b
```
I assign those dates and pass it to the SQL query:
```javascript
    let p_datum_a = new Date(dates[0])
    let p_datum_b = new Date(dates[1])
    let p_datum_c = new Date(dates[2])
   ...
   connection.execute(sqlString,{
    p_datum_a,
    p_datum_b,
    p_datum_c
   }).then ... 
```
With this setup the SQL query takes 6 seconds on avarage to run.
However if I try to workaround and 'hand-bind' the dates with replacing the 
`:p_datum_b`  to something along like ` TO_DATE(constructedDateString,'dd-MM-YY')` in the query string, the query run drops to 0.5 seconds tops.
Is there any better solution than the ugly 'hand binding' that I do?

The SQL query:
```SQL
select ugyfel_nev
      ,partner_nev
      ,cimlet_tipus
      ,cimlet_osszeg
      ,forgalmas_darab
      ,selejt_darab
      ,kivont_darab
      ,osszesen_darab
      ,osszesen_osszeg
from (select ugyfel_nev
            ,partner_kod_g4 ||' - ' || partner_nev partner_nev
            ,cimlet_tipus_nev cimlet_tipus
            ,cimlet_osszeg cimlet_osszeg
            ,nvl(sum(db_forgalmas), 0) forgalmas_darab
            ,nvl(sum(db_selejt), 0) selejt_darab
            ,nvl(sum(db_kivont), 0) kivont_darab
            ,sum(nvl(db_forgalmas, 0) + nvl(db_selejt, 0) + nvl(db_kivont, 0)) osszesen_darab
            ,sum(nvl(db_forgalmas, 0) + nvl(db_selejt, 0) + nvl(db_kivont, 0)) * cimlet_osszeg osszesen_osszeg
            ,0 ssz_uf
            ,0 ssz_pa
      from (select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_a
              and et_kod = 'A'
            union all
            select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_b
              and et_kod = 'B'
            union all
            select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_c
              and et_kod = 'C') etfo
          ,g4portal.tranz_tip trti
      where allapot_jel = :p_allapot_jel
        and (ugyfel_kod = :p_ugyfel_kod or :p_ugyfel_kod is null)
        and (partner_kod = :p_partner_kod or :p_partner_kod is null)
        and (et_kod = :p_et_kod or :p_et_kod is null)
        and etfo.tr_irany = 'B'
        and etfo.tr_kod = trti.tr_kod
        and trti.partner_tipus = 'E'
        and ugyfel_nev <> 'BESOROLATLAN'
      group by ugyfel_nev
              ,partner_kod_g4 ||' - ' || partner_nev
              ,cimlet_tipus_nev
              ,cimlet_osszeg
      union all
      select ugyfel_nev
            ,partner_kod_g4 ||' - ' || partner_nev
            ,'��sszesen'
            ,null
            ,null
            ,null
            ,null
            ,null
            ,sum((nvl(db_forgalmas, 0) + nvl(db_selejt, 0) + nvl(db_kivont, 0)) * cimlet_osszeg) osszesen_osszeg
            ,0
            ,1
      from (select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_a
              and et_kod = 'A'
            union all
            select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_b
              and et_kod = 'B'
            union all
            select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_c
              and et_kod = 'C') etfo
          ,g4portal.tranz_tip trti
      where allapot_jel = :p_allapot_jel
        and (ugyfel_kod = :p_ugyfel_kod or :p_ugyfel_kod is null)
        and (partner_kod = :p_partner_kod or :p_partner_kod is null)
        and (et_kod = :p_et_kod or :p_et_kod is null)
        and etfo.tr_irany = 'B'
        and etfo.tr_kod = trti.tr_kod
        and trti.partner_tipus = 'E'
        and ugyfel_nev <> 'BESOROLATLAN'
      group by ugyfel_nev
              ,partner_kod_g4 ||' - ' || partner_nev
      union all
      select ugyfel_nev
            ,'��sszesen'
            ,null
            ,null
            ,null
            ,null
            ,null
            ,null
            ,sum((nvl(db_forgalmas, 0) + nvl(db_selejt, 0) + nvl(db_kivont, 0)) * cimlet_osszeg) osszesen_osszeg
            ,1
            ,0
      from (select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_a
              and et_kod = 'A'
            union all
            select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_b
              and et_kod = 'B'
            union all
            select *
            from et_forgalmak_v
            where dat_feldolgozas = :p_datum_c
              and et_kod = 'C') etfo
          ,g4portal.tranz_tip trti
      where allapot_jel = :p_allapot_jel
        and (ugyfel_kod = :p_ugyfel_kod or :p_ugyfel_kod is null)
        and (partner_kod = :p_partner_kod or :p_partner_kod is null)
        and (et_kod = :p_et_kod or :p_et_kod is null)
        and etfo.tr_irany = 'B'
        and etfo.tr_kod = trti.tr_kod
        and trti.partner_tipus = 'E'
        and ugyfel_nev <> 'BESOROLATLAN'
      group by ugyfel_nev)
order by ugyfel_nev
        ,ssz_uf
        ,partner_nev
        ,ssz_pa
        ,cimlet_osszeg desc
```
1. What is your version of Node.js?  Run examples/version.js to find versions.
v7.2.1
2. What version of node-oracledb are you using?
v1.13.1
3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
1.21.2

**Comment by ChrisSaxonOra** [comment]
To help with performance issues we really need to see your execution plans. 

You can generate these by running:

```
set serverouput off
alter session set statistics_level = all;

your_query

select * from table(dbms_xplan.display_cursor(null, null, 'ALLSTATS LAST'));
```

Please capture the plans for your fast and slow queries and post your findings.

You can read more about getting execution plans at: https://blogs.oracle.com/sql/how-to-create-an-execution-plan

**Comment by cjbj** [comment]
At a wild guess, @ChrisSaxonOra is one of the people behind https://asktom.oracle.com/ - so you can trust him :)

**Comment by pjatacsukb** [comment]
Thank you for your reply, will try to get the execution plan in a few hours!

**Comment by ChrisSaxonOra** [comment]
Yep, that's me @cjbj ;)

@pjatacsukb OK, let us know how you get on. There are other privileges you need as well. I discuss these in this video https://www.youtube.com/watch?v=GeCanC7u8cs

**Comment by cjbj** [comment]
The privileges needed are:
```
grant select on v_$session to cj;
grant select on v_$sql_plan_statistics_all to cj;
grant select on v_$sql_plan to cj;
grant select on v_$sql to cj;
```

**Comment by pjatacsukb** [comment]
Thank you, I will try to get the privileges from our admin.

Az iPhone-omról küldve

2017. jún. 10. dátummal, 0:14 időpontban Christopher Jones <notifications@github.com> írta:

> The privileges needed are:
> 
> grant select on v_$session to cj;
> grant select on v_$sql_plan_statistics_all to cj;
> grant select on v_$sql_plan to cj;
> grant select on v_$sql to cj;
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

Please consider the environment before printing this email.
*********************************************************************
This communication may contain information which is confidential, personal 
and/or privileged. It is for the exclusive use of the intended recipient(s).
If you are not the intended recipient(s), please note that any 
distribution, forwarding, copying or use of this communication or the 
information in it is strictly prohibited. If you have received it in error 
please contact the sender immediately by return e-mail. Please then delete 
the e-mail and any copies of it and do not use or disclose its contents to 
any person.
Any personal views expressed in this e-mail are those of the individual 
sender and the company does not endorse or accept responsibility for them. 
Prior to taking any action based upon this e-mail message, you should seek 
appropriate confirmation of its authenticity.
This message has been checked for viruses on behalf of the company.
*********************************************************************

**Comment by cjbj** [comment]
@pjatacsukb any update?

**Comment by pjatacsukb** [comment]
Working on it, sadly the burocracy is hard to get by here! 

Az iPhone-omról küldve

2017. jún. 19. dátummal, 14:31 időpontban Christopher Jones <notifications@github.com> írta:

> @pjatacsukb any update?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

Please consider the environment before printing this email.
*********************************************************************
This communication may contain information which is confidential, personal 
and/or privileged. It is for the exclusive use of the intended recipient(s).
If you are not the intended recipient(s), please note that any 
distribution, forwarding, copying or use of this communication or the 
information in it is strictly prohibited. If you have received it in error 
please contact the sender immediately by return e-mail. Please then delete 
the e-mail and any copies of it and do not use or disclose its contents to 
any person.
Any personal views expressed in this e-mail are those of the individual 
sender and the company does not endorse or accept responsibility for them. 
Prior to taking any action based upon this e-mail message, you should seek 
appropriate confirmation of its authenticity.
This message has been checked for viruses on behalf of the company.
*********************************************************************

**Comment by cjbj** [comment]
@pjatacsukb we try to encourage DBAs to work with developers since the DB has a lot of information about application flow & execution that is crucial to good application performance and scalability.  You could ask them to watch the 'best practice' video on http://www.oracle.com/technetwork/database/features/oci/index-090945.html

**Comment by pjatacsukb** [comment]
Thank you, we are making progress. I had to explain them in detail why I need these kind of stuff and what is the problem. In a few days i will send the result.

Az iPhone-omról küldve

2017. jún. 20. dátummal, 0:56 időpontban Christopher Jones <notifications@github.com> írta:

> @pjatacsukb we try to encourage DBAs to work with developers since the DB has a lot of information about application flow & execution that is crucial to good application performance and scalability. You could ask them to watch the 'best practice' video on http://www.oracle.com/technetwork/database/features/oci/index-090945.html
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

Please consider the environment before printing this email.
*********************************************************************
This communication may contain information which is confidential, personal 
and/or privileged. It is for the exclusive use of the intended recipient(s).
If you are not the intended recipient(s), please note that any 
distribution, forwarding, copying or use of this communication or the 
information in it is strictly prohibited. If you have received it in error 
please contact the sender immediately by return e-mail. Please then delete 
the e-mail and any copies of it and do not use or disclose its contents to 
any person.
Any personal views expressed in this e-mail are those of the individual 
sender and the company does not endorse or accept responsibility for them. 
Prior to taking any action based upon this e-mail message, you should seek 
appropriate confirmation of its authenticity.
This message has been checked for viruses on behalf of the company.
*********************************************************************

**Comment by pjatacsukb** [comment]
Hello!
I finally managed to get out the execution plan.
So basically what i've done to speed up the query, to hand-bind the dates with replacing them in the query string (TO_DATE).

Here is the execution plan for that:
https://gist.github.com/pjatacsukb/f30a277a61f23710c029d012349ecb05

With the default date binding (p_datum_a, p_datum_b, p_datum_c is javascript date)
https://gist.github.com/pjatacsukb/40a35ca0e10950196446db60af1f50e9

As you can see its quite different.
If you need anything else, I will try to get it!

**Comment by anthony-tuininga** [comment]
Can you try one other thing? Change :p_datum_a to cast(:p_datum_a as date) and see if the performance improves. If it does, then we know it is due to how the data is being bound. In the node-oracledb driver, all Javascript dates are currently bound as "timestamp with local time zone". This ordinarily doesn't cause a problem, but in this case it might be. Please advise! Thanks.

**Comment by pjatacsukb** [comment]
I will try next time in the morning at work. Our DB admin suggested, that the problem seems to be some that because of type miss match, the index doesnt work on some fields which causes a lot of full table scans.

Az iPhone-omról küldve

2017. jún. 21. dátummal, 16:21 időpontban Anthony Tuininga <notifications@github.com> írta:

> Can you try one other thing? Change :p_datum_a to cast(:p_datum_a as date) and see if the performance improves. If it does, then we know it is due to how the data is being bound. In the node-oracledb driver, all Javascript dates are currently bound as "timestamp with local time zone". This ordinarily doesn't cause a problem, but in this case it might be. Please advise! Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

Please consider the environment before printing this email.
*********************************************************************
This communication may contain information which is confidential, personal 
and/or privileged. It is for the exclusive use of the intended recipient(s).
If you are not the intended recipient(s), please note that any 
distribution, forwarding, copying or use of this communication or the 
information in it is strictly prohibited. If you have received it in error 
please contact the sender immediately by return e-mail. Please then delete 
the e-mail and any copies of it and do not use or disclose its contents to 
any person.
Any personal views expressed in this e-mail are those of the individual 
sender and the company does not endorse or accept responsibility for them. 
Prior to taking any action based upon this e-mail message, you should seek 
appropriate confirmation of its authenticity.
This message has been checked for viruses on behalf of the company.
*********************************************************************

**Comment by ChrisSaxonOra** [comment]
You have implicit conversions going on, so a type mismatch is likely the root cause. You can see this in the index range scan of ET_FORG_REPORT_I at lines 18, 28, etc.:

```
  18 - access("P"."TREZOR_BANK_KOD"="E"."BANK_KOD" AND "E"."ET_KOD"='A')
       filter(("E"."ET_KOD"='A' AND INTERNAL_FUNCTION("DAT_FELDOLGOZAS")=:P_DATUM_A))
```
Notice the internal function on DAT_FELDOLGOZAS. Compare this to the scan of ET_FORGALMAK_NUK in lines 15, 25, etc. of the "good" plan

```
15 - access("P"."TREZOR_BANK_KOD"="E"."BANK_KOD" AND "DAT_FELDOLGOZAS"=TO_DATE(' 2017-06-21 00:00:00', 'syyyy-mm-dd hh24:mi:ss') AND 
              "E"."ET_KOD"='A' AND "TR_KOD"="TRTI"."TR_KOD")
```

**Comment by cjbj** [comment]
Changing to an enhancement: we need to expand the bind syntax

**Comment by Pollocks01** [comment]
I am seeing this too: in my case the database field is a TIMESTAMP(6) and I'm seeing INTERNAL_FUNCTION in my execution plan (when run from node) and in my case this prevents partition elimination. A regular explain plan in TOAD gives the desired result - partition elimination.

**Comment by Pollocks01** [comment]
SQL is: select * from ( select * from logger_logs) where 1=1 and SCOPE like 
'%pkg_settlement%' and TIME_STAMP>:TIME_STAMP1 OFFSET :OFFSET ROWS 
FETCH NEXT :LIMIT ROWS ONLY
logger_logs.time_stamp is of data type TIMESTAMP (6) and bound in from node from a javascript DATE variable, and processed internally as an utc date string
plan from node is:
`------------------------------------------------------------------------------------------------------
| Id  | Operation              | Name        | Rows  | Bytes | Cost (%CPU)| Time     | Pstart| Pstop |
------------------------------------------------------------------------------------------------------
|   0 | SELECT STATEMENT       |             |       |       | 67214 (100)|          |       |       |
|*  1 |  VIEW                  |             |  6345 |    43M| 67214   (1)| 00:00:03 |       |       |
|*  2 |   WINDOW NOSORT STOPKEY|             |  6345 |  3209K| 67214   (1)| 00:00:03 |       |       |
|*  3 |    FILTER              |             |       |       |            |          |       |       |
|   4 |     PARTITION RANGE ALL|             |  6345 |  3209K| 67214   (1)| 00:00:03 |     1 |1048575|
|   5 |      PARTITION LIST ALL|             |  6345 |  3209K| 67214   (1)| 00:00:03 |     1 |  LAST |
|*  6 |       TABLE ACCESS FULL| LOGGER_LOGS |  6345 |  3209K| 67214   (1)| 00:00:03 |     1 |1048575|
------------------------------------------------------------------------------------------------------
Predicate Information (identified by operation id):
---------------------------------------------------
 
   1 - filter(("from$_subquery$_003"."rowlimit_$$_rownumber"<=CASE  WHEN (:OFFSET>=0) THEN 
              FLOOR(TO_NUMBER(TO_CHAR(:OFFSET))) ELSE 0 END +:LIMIT AND 
              "from$_subquery$_003"."rowlimit_$$_rownumber">:OFFSET))
   2 - filter(ROW_NUMBER() OVER ( ORDER BY  NULL )<=CASE  WHEN (:OFFSET>=0) THEN 
              FLOOR(TO_NUMBER(TO_CHAR(:OFFSET))) ELSE 0 END +:LIMIT)
   3 - filter(:OFFSET<CASE  WHEN (:OFFSET>=0) THEN FLOOR(TO_NUMBER(TO_CHAR(:OFFSET))) ELSE 0 
              END +:LIMIT)
   6 - filter(("LOGGER_LOGS"."SCOPE" LIKE '%pkg_settlement%' AND 
              INTERNAL_FUNCTION("LOGGER_LOGS"."TIME_STAMP")>:TIME_STAMP1))`

Plan from TOAD is:
`Predicate Information (identified by operation id):
---------------------------------------------------
 
   1 - filter(("from$_subquery$_003"."rowlimit_$$_rownumber"<=CASE  WHEN (:OFFSET>=0) THEN 
              FLOOR(TO_NUMBER(TO_CHAR(:OFFSET))) ELSE 0 END +:LIMIT AND 
              "from$_subquery$_003"."rowlimit_$$_rownumber">:OFFSET))
   2 - filter(ROW_NUMBER() OVER ( ORDER BY  NULL )<=CASE  WHEN (:OFFSET>=0) THEN 
              FLOOR(TO_NUMBER(TO_CHAR(:OFFSET))) ELSE 0 END +:LIMIT)
   3 - filter(:OFFSET<CASE  WHEN (:OFFSET>=0) THEN FLOOR(TO_NUMBER(TO_CHAR(:OFFSET))) ELSE 0 
              END +:LIMIT)
   6 - filter(("LOGGER_LOGS"."SCOPE" LIKE '%pkg_settlement%' AND 
              INTERNAL_FUNCTION("LOGGER_LOGS"."TIME_STAMP")>:TIME_STAMP1))`

**Comment by dmcghan** [comment]
@Pollocks01 This has been marked for enhancement already. 

In the meantime, please try something like this:
```sql
select * from (
  select * 
  from logger_logs
) 
where 1=1 
  and scope like '%pkg_settlement%' 
  and time_stamp > cast(:TIME_STAMP1 as timestamp) 
offset :OFFSET rows
fetch next :LIMIT rows only;
```

**Comment by Pollocks01** [comment]
@dmcghan OK, that's great thanks. My predicates are code generated so it'll be a change to my framework but I'll give it a shot. Thanks!

**Comment by dmcghan** [comment]
Excellent. 

Also, be sure to understand how converting from TSWLTZ to other types works:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-9163-fetching-date-and-timestamps

The short version is that you need to explicitly set your session time zone to what you want. The easiest way is to set the ORA_SDTZ environment variable prior to starting your Node.js app

**Comment by cjbj** [comment]
Node-oracledb 4.2 allows finer grained bind types to be used, see https://blogs.oracle.com/opal/node-oracledb-42-with-improved-data-type-binding and https://oracle.github.io/node-oracledb/doc/api.html#executebindparamtype
