### ISSUE TITLE
Best practices for tests

### ISSUE THREAD

**Issue by C4rmond4i** [oracle/node-oracledb#713]
I want to write unit tests for my graphQL server application, but I'm not sure how to implement them.

Like sibelius in #666 , I want to validate my SQL queries, and I know I have to use a real database for that. But I don't know against which schema I should run my tests.

Is it ok to use the same schema as I use for development? And when yes, how should test data for the database be generated? Or is it better to set up a own schema only for tests, already filled with test data?

**Comment by cjbj** [comment]
I would always try to keep testing separate from development.

You will want a schema that can be recreated in a known, starting state. Either set it up from SQL scripts, or using the rapid provisioning of a cloned DB in [Oracle Multitenant.](https://docs.oracle.com/database/122/CNCPT/overview-of-the-multitenant-architecture.htm#GUID-962835F2-3DD2-4D00-8817-2E63532E00AE).

What test data is needed will depend on the application and the depth of testing you require.

**Comment by C4rmond4i** [comment]
Okay, thank you very much
