### ISSUE TITLE
I cant install npm install oracledb

### ISSUE THREAD

**Issue by emazzu** [oracle/node-oracledb#714]
I cant install  npm install oracledb

fi; fi;' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-16-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xmazzuce/apps/oracle/node_modules/oracledb
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"

any ideas ?????

**Comment by cjbj** [comment]
Check the bits below `Delete irrelevant parts of this template.` in your post.

**Comment by Mo33n** [comment]
+1
Its never been that easy to install this particular package on centos. Need urgent help

lue>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../../nan/nan.h:2124: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetCallHandler(v8::Local<v8::FunctionTemplate>, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>)’:
../../nan/nan.h:2179: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetCallAsFunctionHandler(v8::Local<v8::ObjectTemplate>, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>)’:
../../nan/nan.h:2201: error: ‘NewInstance’ was not declared in this scope
In file included from ../../nan/nan.h:2224,
                 from ../src/njs/src/njsOracle.h:56,
                 from ../src/njs/src/njsOracle.cpp:53:
../../nan/nan_private.h: At global scope:
../../nan/nan_private.h:12: error: expected initializer before ‘<’ token
../../nan/nan_private.h:25: error: expected initializer before ‘<’ token
../src/njs/src/njsOracle.cpp:1329: error: expected ‘}’ at end of input
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory `/opt/node_modules/cbsgui.pkg/node_modules/oracledb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/cbsgui.pkg/node_modules/oracledb
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by cjbj** [comment]
@emazzu you need to include more information about what platform you are on and what commands you have run  - that's what the template questions try to ask.

@Mo33n Centos should be similar to Oracle Linux.  You also didn't include useful information - that makes it hard for us to help you.  At a guess, you don't have a C++11 compatible compiler - it's clearly documented you need one (to build Node 4+ add-ons). If that's the case, install such a compiler or get a newer OS version that does have one.  My notes are here https://blogs.oracle.com/opal/getting-a-c11-compiler-for-node-4,-5-and-6-on-oracle-linux-6  If you search this repo, you can find other comments. e.g. #488.  Hope this helps.

**Comment by cjbj** [comment]
Closing - no update from user.
