### ISSUE TITLE
can't install oracledb 2

### ISSUE THREAD

**Issue by sagiegurari** [oracle/node-oracledb#717]
Your announcement thread is closed for comments so can't comment there.
anyhow, since dev 2.0 branch is not in npm and per your instructions it is recommended to install it via npm, I can't really test it properly.

**Comment by anthony-tuininga** [comment]
Per Chris' [announcement](https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github) you should be able to install via this command:

`npm install oracle/node-oracledb.git#dev-2.0`

Does that not work for you? I just tried it and it seemed to work for me!

**Comment by sagiegurari** [comment]
missed that part. sorry. will test with that
