### ISSUE TITLE
Stored procedure not executing

### ISSUE THREAD

**Issue by scottchantry** [oracle/node-oracledb#72]
I am trying to execute a stored procedure but is not executing. Here is my code:

    connection.execute(
        "BEGIN sp_grading.p_post_grade('201530', '436823', '32447', '1005254', 'F', 'A-', null, null); END;",
        function (err, result) {
           //callback
        });

If I run the above SQL using other programs, it works.  When I run the above code, err is undefined and result is:

    {rowsAffected: undefined, outBinds: undefined, rows: undefined, metaData: undefined}

But when I check, the procedure didn't make the expected changes.  I don't have access to the procedure source but the fact it works as expected in other programs but when I use this driver, it doesn't. Any ideas??

**Comment by cjbj** [comment]
@scottchantry 
- Do you need to explicitly commit?
- create a test stored procedure with the same parameters and make the minimum changes to the JS code to call the test procedure.

**Comment by scottchantry** [comment]
You are correct. I added isAutoCommit to true and it is working now.  Thank you.

**Comment by cjbj** [comment]
@scottchantry I'm glad it was easy!
