### ISSUE TITLE
Passing the query to a pool

### ISSUE THREAD

**Issue by sibelius** [oracle/node-oracledb#720]
Node postgres drives allows 3 ways of doing a query (https://github.com/brianc/node-postgres#intro--examples):

1. Passing the query to a pool
2. Borrowing a client from a pool and executing the query with it
3. Obtaining an exclusive client and executing the query with it

I think the first approach is the best, because it solves a lot of complexity from the user code.

So instead of getting a connection from the connection pool, making a query and releasing the connection to the pool.
It is much easier to only send the query to the pool, and let the pool get a connection and release it

what do you think about this approach?

**Comment by sagiegurari** [comment]
Something like this [pool.parallelQuery](https://github.com/sagiegurari/simple-oracledb#Pool+parallelQuery)

**Comment by cjbj** [comment]
@sibelius we've talked about a one-shot getconnection-execute-release-connection method a bit.  There are some limitations that would occur, or need us to engineer around, e.g. no streaming of LOBs, since that requires the connection to be open.  

There is also the 'fear' that it would ne overused and may reduce application scalability by unnecessary getconnection-releaseconnection calls.

**Comment by mrapczynski** [comment]
There is definitely merit to this. Maybe I don’t get it, but I’m not sold on a scalability issue. A great majority of my SQL queries are one-off statements. I’m sure that’s true for many others. So, this could be a great convenience. The `mysql2` driver does this as well.

`node-oracledb` is very good, but I still add a small convenience function to my projects called `.sql(...)` that uses promises to get a connection from a named pool, run `.execute(...)` on the connection, and release the connection. It’s a significant reduction in repetitive boilerplate coding.

I thought that this is good Oracle hygiene, and I can attest to being burned on the database session counts when we don’t release our connections. In cases where I need to do multiple ops on one leased connection, then I do not use a helper and instead acquire a connection directly and release it.

**Comment by sibelius** [comment]
our final solution was to use one connection per sql query at our GraphQL, as any resolver can be executed out of order

more info here https://github.com/oracle/node-oracledb/issues/867#issuecomment-396909241

**Comment by cjbj** [comment]
@sibelius Thanks for the update. I'll keep an internal note that a one-shot getconnection-execute-close shortcut could be useful, even in the world of async/await.
