### ISSUE TITLE
Error: ORA-12514: TNS:listener does not currently 

### ISSUE THREAD

**Issue by vishal2232** [oracle/node-oracledb#722]
npm i oracledb --save
above was successfully done.
but when i execute my node file it shows me below error.
node servertest.js
**Error: ORA-12514**: TNS:listener does not currently know of service requested in connect descriptor

info:
Linux. My database is on another machine
I just want confirm the connection establishment with my remote oracle DB

**Comment by cjbj** [comment]
Here is the [Connection Strings](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionstrings) documentation.  Check that, and get back to us with more detail about how you or other people normally connect to the DB.

**Comment by vishal2232** [comment]
Great thanks for your response **cjbj** 
right now facing different issue..

Desktop/untit2/node_modules/oracledb/lib/oracledb.js:38
    throw err;
    ^

Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vishal/Desktop/untit2/node_modules/oracledb/lib/oracledb.js:35:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by vishal2232** [comment]
**nodemon Err**
Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

[nodemon] clean exit - waiting for changes before restart
[nodemon] Internal watch failed: watch /home/vishal/instantclient/instantclient_12_2/sdk/demo/occidml.cpp ENOSPC

**Comment by cjbj** [comment]
@vishal2232 you probably found that you needed LD_LIBRARY_PATH to solve the `Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory` error.

I've no idea what you are doing with `/home/vishal/instantclient/instantclient_12_2/sdk/demo/occidml.cpp ENOSPC`

Regarding your `ORA-12514` we can only offer general advice.  Find the database hostname and the service name then use `hostname/servicename` in the `getConnection()` attribute `connectString`.  Can you connect with SQL*Plus?  You can use the same connect string in both SQL*Plus and node-oracledb.

**Comment by vishal2232** [comment]
Thanks a lot **christopher** .
we did it.
