### ISSUE TITLE
Binding PLSQL Table Struc 

### ISSUE THREAD

**Issue by ahummel25** [oracle/node-oracledb#726]
I'm getting `NJS-037: invalid data type at array index 0 for bind ":p_tbltype"` while binding a pl/sql database object table type to a piece of JSON that I'm trying to pass in.

`"oracledb": "github:oracle/node-oracledb#dev-2.0",`

`CREATE OR REPLACE TYPE TBLTYPE IS TABLE OF RECTYPE;`

`RECTYPE` is a database object record type that has several columns.

    const conn = yield getConnection()

      try {
        const result = conn.execute(
          'BEGIN pkg.procedure_name(:p_tbltype, :p_username); END;', {
            p_tbltype: {
              type: oracledb.STRING,
              dir: oracledb.BIND_IN,
              val: fileJSON
            },
            p_username: {
              type: oracledb.STRING,
              dir: oracledb.BIND_IN,
              val: 'name'
            }
          },
          function (err, result) {
            if(err) {
              console.log("ERR = " + err)
              return
            }
            console.log(result)
          }
        )
      } finally {
        releaseConnection(conn)
      }

`fileJSON` looks like:

`[ {  
   VALUE1: 'VAL1',
   VALUE2: 'VAL2',
   VALUE3: 'VAL3',
   VALUE4: 'VAL4' },
  { VALUE1: 'VAL5',
    VALUE2: 'VAL6',
    VALUE3: 'VAL7',
    VALUE4: 'VAL8'
} ]`

So `VALUE1` - `VALUE4` are the column names that are in my `RECTYPE`.

Can I not send in straight JSON like this as data to bind to a PLSQL array object?
#

**Comment by anthony-tuininga** [comment]
This sort of capability is not currently supported by the node-oracledb driver. It is on a long laundry list of features that we would like to implement. I'll let @cjbj comment further if he wishes.

**Comment by cjbj** [comment]
We'll track this in #147. The initial plans would be to map JavaScript objects, not JSON.  Mapping JSON has been raised before but not yet really investigated.
