### ISSUE TITLE
Failed to install oracledb (node-gyp rebuild)

### ISSUE THREAD

**Issue by guilhermechiara** [oracle/node-oracledb#727]
Hi!

I'm trying to install oracledb (latest version) using OS X Sierra 10.12.5, but I'm always getting this error:

> node-oracledb ERR! Error: Cannot find $OCI_LIB_DIR/libclntsh.dylib
> node-oracledb ERR! Error: Do you need to run 'cd $OCI_LIB_DIR && ln -s libclntsh.dylib.* libclntsh.dylib'?
> node-oracledb ERR! Error: See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

I already have installed:

- Xcode (8.3.3)
- Python 2.7
- Instant Client 12.1 (Basic and SDK).

The instantclient installation is at /opt/oracle and I already set the variables: OCI_*_DIR.

If I execute the command: 

> cd $OCI_LIB_DIR && ln -s libclntsh.dylib.* libclntsh.dylib

I got:

> ln: libclntsh.dylib: File exists

I have read and tried many things, but nothing make it work.
Can you guys, help me?

**Comment by cjbj** [comment]
- Show us the output of `ls -l $OCI_LIB_DIR` and `ls -l $OCI_INC_DIR` and `ls -l /opt/oracle`
- Show us the exact npm install command you are running

If you're keen, you could try installing [node-oracledb 2.0.13-Development](https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github) with `npm install oracle/node-oracledb.git#dev-2.0`.  This doesn't need OCI_*_DIR variables.  But it does require the Instant Client to be in `~/lib` or `/usr/local/lib`, see the [2.0.13-dev install instructions](https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md).

**Comment by guilhermechiara** [comment]
**ls -l $OCI_LIB_DIR**
> total 24
> -rw-rw-rw-@  1 gchiara  wheel  485 Jun  8  2016 BASIC_README
> -rw-rw-rw-@  1 gchiara  wheel  489 Jun  8  2016 SQLPLUS_README
> drwxr-xr-x   6 gchiara  wheel  204 Apr 25 13:00 bin
> drwxr-xr-x   3 gchiara  wheel  102 Apr 25 12:53 jdbc
> drwxr-xr-x  12 gchiara  wheel  408 Apr 25 12:59 lib
> lrwxr-xr-x   1 gchiara  wheel   20 Jul  3 12:53 libclntsh.dylib -> libclntsh.dylib.12.1
> drwxr-xr-x   4 gchiara  wheel  136 Apr 25 13:15 network
> drwxr-xr-x   4 gchiara  wheel  136 Apr 25 12:58 rdbms
> drwxrwxrwx@  9 gchiara  wheel  306 Jul  3 12:54 sdk
> drwxr-xr-x   4 gchiara  wheel  136 Apr 25 12:58 sqlplus

**ls -l $OCI_INC_DIR**
> total 3360
> -r-xr-xr-x@ 1 gchiara  wheel   44851 Apr 29  2015 ldap.h
> -r-xr-xr-x@ 1 gchiara  wheel   36543 Apr 29  2015 nzerror.h
> -r-xr-xr-x@ 1 gchiara  wheel   75006 Apr 29  2015 nzt.h
> -r--r--r--@ 1 gchiara  wheel    2115 Oct 15  2002 occi.h
> -r-xr-xr-x@ 1 gchiara  wheel   11649 May  6  2015 occiAQ.h
> -r-xr-xr-x@ 1 gchiara  wheel   35604 May  6  2015 occiCommon.h
> -r-xr-xr-x@ 1 gchiara  wheel   72561 May  6  2015 occiControl.h
> -r--r--r--@ 1 gchiara  wheel   39934 Feb 16  2010 occiData.h
> -r--r--r--@ 1 gchiara  wheel   24778 Oct 29  2007 occiObjects.h
> -r-xr-xr-x@ 1 gchiara  wheel  189648 May  6  2015 oci.h
> -r-xr-xr-x@ 1 gchiara  wheel    7203 Sep 25  2005 oci1.h
> -r--r--r--@ 1 gchiara  wheel   10361 Jul  7  2005 oci8dp.h
> -r-xr-xr-x@ 1 gchiara  wheel  434446 May  6  2015 ociap.h
> -r-xr-xr-x@ 1 gchiara  wheel    6204 Sep 25  2005 ociapr.h
> -r--r--r--@ 1 gchiara  wheel   43001 Sep 25  2005 ocidef.h
> -r-xr-xr-x@ 1 gchiara  wheel    4048 Jul  7  2005 ocidem.h
> -r-xr-xr-x@ 1 gchiara  wheel   11782 May  6  2015 ocidfn.h
> -r--r--r--@ 1 gchiara  wheel    8953 Jul  7  2005 ociextp.h
> -r-xr-xr-x@ 1 gchiara  wheel    6494 Sep 25  2005 ocikpr.h
> -r-xr-xr-x@ 1 gchiara  wheel    7848 May  6  2015 ocixmldb.h
> -r-xr-xr-x@ 1 gchiara  wheel  105155 May  6  2015 ocixstream.h
> -r-xr-xr-x@ 1 gchiara  wheel   30429 May  6  2015 odci.h
> -r-xr-xr-x@ 1 gchiara  wheel    6506 Apr 23  2015 oratypes.h
> -r--r--r--@ 1 gchiara  wheel  102775 Aug  1  2006 ori.h
> -r--r--r--@ 1 gchiara  wheel   15083 Aug  1  2006 orid.h
> -r-xr-xr-x@ 1 gchiara  wheel  158261 May  6  2015 orl.h
> -r-xr-xr-x@ 1 gchiara  wheel   42866 May  6  2015 oro.h
> -r-xr-xr-x@ 1 gchiara  wheel  123766 May  6  2015 ort.h
> -r-xr-xr-x@ 1 gchiara  wheel    9892 Sep  5  2006 xa.h

**ls -l /opt/oracle**
> total 0
> drwxr-xr-x  13 gchiara  wheel  442 Jul  3 15:14 instantclient

I'm using **npm install oracledb**. I also tried **npm install -E oracledb**.

I'll try to install following these steps you showed. As soon as I get some news, I update this thread.

Thank you @cjbj

**Comment by guilhermechiara** [comment]
****

**Comment by cjbj** [comment]
@guilhermechiara For node-oracledb 1.13 you are not setting OCI_*_DIR correctly.  Perhaps they are not exported.  Perhaps you have some shell that is resetting the environment.

**Comment by cjbj** [comment]
Closing - no update from user
