### ISSUE TITLE
require('oracledb') hanging for an extended period of time

### ISSUE THREAD

**Issue by scottrehlander** [oracle/node-oracledb#729]
The node-oracledb is taking an extremely long time to initialize (~15 minutes) on application startup using Red Hat.  The same project runs fine on OSX and Windows.  If I comment out the line `_oracledb = require('oracledb');` and instead change it to `_oracledb = null;` when running in Red Hat the application starts up in seconds.  It appears to hang on line 399 in oracledb.js (`oracledbInst = new oracledbCLib.Oracledb();`).  

If we wait the full 15 minutes or so then the application finishes starting up an runs as expected.  I can't seem to debug any further because, if I understand correctly, it's instantiating the compiled library.  Is there any way I can enable some kind of verbose logging?  I tried Googling everything I could and I don't think anyone else has had this problem.  I can't imagine what would take 15 minutes, maybe it's trying to locate a file on the file system?  Any thoughts on this would be helpful as I'm banging my head against the wall at this point.  :(

Thanks for all of your hard work on this project!

**Versions**
node-oracledb: 1.13
Red Hat: 4.8.6-11
Node: 6.10.3 
Oracle Database Version: 10.1.0.5.0 64 bit
Oracle Instant Client: 11.2
GCC: 4.8.5

**Comment by cjbj** [comment]
1. Confirm that it is the `require()`, and not a later operation, hanging by running:
```
node -p  'require("oracledb")'
```
2. Try using `strace` to see what system calls are taking time:
```
strace -vfttT node -p 'require("oracledb")'
```
or
```
strace -vfttT -o /tmp/nodb.trc node -p 'require("oracledb")'
```

**Comment by scottrehlander** [comment]
Sorry for the delay on this, I needed to wait for an opportunity to bring QA down.  Turns out strace isn't enabled on the QA machine so I need to get IT involved.  I did verify that it is the require("oralcedb") that is taking an extended period of time by running the suggested command.  Stay tuned.

**Comment by cjbj** [comment]
Closing - no update from user
