### ISSUE TITLE
Always getting array result

### ISSUE THREAD

**Issue by danielb2** [oracle/node-oracledb#73]
Hi, I've got my execution specified in the following manner:

``` javascript
var Oracle = require('oracledb');
// ...
connection.execute(sql, [], {outFormat: Oracle.OBJECT }, next);
```

however, the resulting output is always returning as Oracle.ARRAY

Is this working the way it is supposed to?

**Comment by cjbj** [comment]
@danielb2 It works for me and others.  Can you post a complete runnable code snippet that shows the problem?

Platform & version details are generally useful to know.

**Comment by danielb2** [comment]
It worked when trying to reproduce this to make a small snippet. I guess something else is going on :/
