### ISSUE TITLE
npm install oracledb fails on build machines with restricted network access.

### ISSUE THREAD

**Issue by andersjanmyr** [oracle/node-oracledb#730]
Installation fails when I'm trying to build on a build machine with restricted network access.
I don't know if this is the problem, but the ` connect ETIMEDOUT 104.20.22.46:443` in the log looks suspicious.

When I build on OSX or in a docker container on my local machine it works fine. I have tested with both Ubuntu and CentOS.

Any help would be appreciated.

1. What is your version of Node.js?  Run examples/version.js to find versions.
node -v v6.11.0

2. What version of node-oracledb are you using?
oracledb@1.13.1

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
LD_LIBRARY_PATH: /jenkins/workspace/sams-sng-orchestration/tmp/instantclient_12_2_linux
OCI_INC_DIR: /jenkins/workspace/sams-sng-orchestration/tmp/instantclient_12_2_linux/sdk/include

4. What is the version of Oracle Database?
None yet.

5. What is your OS and version?
+ cat /proc/version
21:36:09 Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017

6. What compiler version did you use?  For example, with GCC, run `gcc --version`
+ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

7. What environment variables did you set?  How *exactly* did you set them?
export OCI_LIB_DIR=$tmp_dir/instantclient_12_2_linux
export LD_LIBRARY_PATH=$tmp_dir/instantclient_12_2_linux
export OCI_INC_DIR=$OCI_LIB_DIR/sdk/include

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
Default build user with correct permissions.

9. What error(s) you are seeing?
```
> oracledb@1.13.1 install /jenkins/workspace/sams-sng-orchestration/node_modules/oracledb
21:36:13 > node-gyp rebuild
21:36:13 
21:38:21 gyp WARN install got an error, rolling back install
21:38:21 gyp ERR! configure error 
21:38:21 gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
21:38:21 gyp ERR! stack     at Object.exports._errnoException (util.js:1018:11)
21:38:21 gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1041:20)
21:38:21 gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
21:38:21 gyp ERR! System Linux 3.10.0-514.10.2.el7.x86_64
21:38:21 gyp ERR! command "/jenkins/localtools/sams-sng-orchestration-60/nodejs/bin/node" "/jenkins/localtools/sams-sng-orchestration-60/npm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
21:38:21 gyp ERR! cwd /jenkins/workspace/sams-sng-orchestration/node_modules/oracledb
21:38:21 gyp ERR! node -v v6.11.0
21:38:21 gyp ERR! node-gyp -v v3.6.2
21:38:21 gyp ERR! not ok 
21:38:22 npm ERR! code ELIFECYCLE
21:38:22 npm ERR! errno 1
21:38:22 npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
21:38:22 npm ERR! Exit status 1
21:38:22 npm ERR! 
21:38:22 npm ERR! Failed at the oracledb@1.13.1 install script.
```
Here's a gist with the npm-debug.log, https://gist.github.com/andersjanmyr/77a8f8e8e83de07da9f5d11bc7e8120a

**Comment by cjbj** [comment]
Yes `connect ETIMEDOUT 104.20.22.46:443` will be a site issue that you need to resolve.  How restricted are you?  Have you set http_proxy (and/or https_proxy that npm 5 seems to need).   Alternatively build on a less restrictive machine and copy the node_modules/oracledb dir over.

**Comment by andersjanmyr** [comment]
@cjbj Thanks for the reply, but why does it need to go outside the machine to build the driver? Does it download something? If it does, can I add it manually?

**Comment by cjbj** [comment]
@andersjanmyr for a start, node-oracledb has a dependency on [NAN](https://github.com/nodejs/nan).  Npm may do other book keeping, such as checking versions. You could strace or netstat or whatever to see what it is doing?

**Comment by telkomops** [comment]
set http_proxy=http://uname:password@proxy:proxyport should resolve the issue

**Comment by andersjanmyr** [comment]
@telkomops Thanks for trying, but this doesn't work. There is no access allowed outside to untrusted servers. The only access allowed is our local npm repository.

**Comment by sagiegurari** [comment]
does that local npm registry machine has access to web? can it proxy those calls?

**Comment by cjbj** [comment]
I'm going to close this - you'll need to work out your own network limitations and download and compile somehow that suits your configuration.  Note the [recent update in #18](https://github.com/oracle/node-oracledb/issues/18#issuecomment-322675513): binaries will probably be on GitHub.

**Comment by andersjanmyr** [comment]
Sure, I'm fine with that. I solved it by installing it on a similar machine and copying the files before npm installing.

**Comment by cjbj** [comment]
That seems logical.
