### ISSUE TITLE
Improved Errors

### ISSUE THREAD

**Issue by pirouet** [oracle/node-oracledb#732]
I find that when I encounter an exception (whether user created or Oracle error), the err object return only has one property: message. See https://github.com/oracle/node-oracledb/blob/master/doc/api.md#properror

Given that the error code is available using SQLCODE (please correct me if I am mistaken), it would be nice  to have the error code as a property rather than bundled with the message. Something like:

`
err = {
    code: 'ORA-XXXXX',
    message: 'useful error message'
}
`

The reason behind this is that I would like to take different action depending on the error code. For me, this would in the form of the service layer relaying a different message back to the web/ui layer with informative information to help the end-user without the need for having to parse and sub-string the error message returned.

**Comment by anthony-tuininga** [comment]
The code is readily available as an integer. I trust that would resolve your request? Other attributes that may be of interest are "offset" (parse offset for parse errors, row offsets for multiple execute errors, etc.) and "isRecoverable" (for 12.1 where Transaction Guard is in place). I'm going to treat this as an enhancement request and let @cjbj decide where it goes in the long list of requested enhancements!

**Comment by dmcghan** [comment]
@pirouet [According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error), `code` is a non-standard error property. It seems that Node.js [does use `code`](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_error_code) for a set list of [predetermined error codes](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#nodejs-error-codes).

They talk a little about the use of `code` [here in the `errors` module](https://github.com/nodejs/node/blob/330c8d743e33a83f85389ea8a64e3d3854ea0048/lib/internal/errors.js). Sounds reasonable...

@anthony-tuininga Is an integer sufficient? How would one know if it's an ORA error vs an NJS error? Also, I don't believe the JS layer is setting `code` when it throws errors.

**Comment by anthony-tuininga** [comment]
> @anthony-tuininga Is an integer sufficient? How would one know if it's an ORA error vs an NJS error? Also, I don't believe the JS layer is setting code when it throws errors.

It would be fine if there were different classes for the different types of errors -- but a quick check looks like Node.js doesn't provide an easy way to do that. Some experimentation would be needed.

**Comment by dmcghan** [comment]
@anthony-tuininga You can do things like that, but then the code has to check two things: `instanceOf` on some error class and then the `code`. While maybe easier than using substring on the `message`, it sounds overly complex.

Why don't we put the whole string?

**Comment by anthony-tuininga** [comment]
In that case why not just use startsWith() and leave everything the way it is? The error message starts with ORA- or NJS- so that would seem perfectly reasonable? @pirouet does that resolve your request?

**Comment by cjbj** [comment]
We're using #354 to track the general request to add more context to the error structure so I'll close this one.
