### ISSUE TITLE
Instant Crash on require('oracledb')

### ISSUE THREAD

**Issue by jd-bhge** [oracle/node-oracledb#738]
1. What is your version of Node.js?  8.1.4

2. What version of node-oracledb are you using? 1.13

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed? 11.2 - C:\Oracle\instantclient, Have tried newer versions

4. What is the version of Oracle Database? Various

5. What is your OS and version? Windows 10 ENT

6. What compiler version did you use?  VS2017

7. What environment variables did you set?  Everything in the Guide, via cmd(set PATH=%PATH%;blah

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as? Install went fine, this is an issue when trying to use it. Even just using var oracledb = require('oracledb') results in the below segfault.

9. What error(s) you are seeing? 
PID 27124 received SIGSEGV for address: 0x9d751f28
SymInit: Symbol-SearchPath: '.;c:\users\obfuscatedusername\source\repos\OracleTest\OracleTest;C:\Program Files\nodejs;C:\windows;C:\windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'obfuscatedusername'
OS-Version: 10.0.10586 () 0x100-0x1
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\segfault-handler\src\segfault-handler.cpp (116): segfault_handler
00007FF8A0CEE763 (ntdll): (filename not available): MD5Update
00007FF8A0CB4CAB (ntdll): (filename not available): RtlImageNtHeaderEx
00007FF8A0CB6C94 (ntdll): (filename not available): RtlRaiseException
00007FF89D751F28 (KERNELBASE): (filename not available): RaiseException
f:\dd\vctools\crt\vcruntime\src\eh\throw.cpp (136): _CxxThrowException
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\oracledb\src\dpi\src\dpiutils.cpp (86): ociCallCommon
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\oracledb\src\dpi\src\dpienvimpl.cpp (108): EnvImpl::EnvImpl
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\oracledb\src\njs\src\njsoracle.cpp (81): Oracledb::Oracledb
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\oracledb\src\njs\src\njsoracle.cpp (275): Oracledb::New
c:\users\obfuscatedusername\source\repos\oracletest\oracletest\node_modules\nan\nan_callbacks_12_inl.h (175): Nan::imp::FunctionCallbackWrapper
00007FF78EDEDA40 (node): (filename not available): v8::internal::interpreter::Interpreter::GetDispatchCountersObject
00007FF78E92CC94 (node): (filename not available): std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::zone_allocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
00007FF78E92BEA8 (node): (filename not available): std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::zone_allocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
00007FF78E92BDCB (node): (filename not available): std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::zone_allocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
0000016CECE840C1 ((module-name not available)): (filename not available): (function-name not available)
000000C6C53AD1C8 ((module-name not available)): (filename not available): (function-name not available)

**Comment by cjbj** [comment]
> What is the version of Oracle Database? Various

Are they on the same machine as Node?  My first suspicion was a library version clash.  This might now also be true if you've tried various Oracle client versions.  Make sure you build & run node-oracledb with the same version of the Oracle client.

**Comment by jd-bhge** [comment]
The thing is, I am not even getting that far, the simple act of including the library causes that segfault. I have recompiled at least a dozen times. Tried it on a Raspberry Pi 3 and it worked first time. So I am at a loss haha.

**Comment by cjbj** [comment]
@jd-bhge without more details, it's hard to comment.  Go back to basics, check you only have one set of Oracle libraries on on the machine, make sure you have the correct VS Redistributable.

**Comment by cjbj** [comment]
Closing - no update from user
