### ISSUE TITLE
dyld: Symbol not found: _OCIClientVersion on OS X 10.12 (Sierra)

### ISSUE THREAD

**Issue by David-Sparky** [oracle/node-oracledb#740]
I am trying to use the Oracle Instant Client for local development on my Mac. I successfully installed all the packages and followed the install instructions, but whenever I go to run the server with the node-oracledb I get the following error:

```
dyld: lazy symbol binding failed: Symbol not found: _OCIClientVersion
  Referenced from: <PATH>
  Expected in: flat namespace

dyld: Symbol not found: _OCIClientVersion
  Referenced from: <PATH>
  Expected in: flat namespace

fish: 'node server.js' terminated by signal SIGABRT (Abort)
```

I have tried manually setting `$DYLD_LIBRARY_PATH` but nothing changes.

**Comment by anthony-tuininga** [comment]
Try using these [instructions](https://oracle.github.io/odpi/doc/installation.html#macos). Note that on recent macOS versions DYLD_LIBRARY_PATH can be ignored, depending on your configuration. Which installation of Python are you using? The Xocde version found in /usr/bin is very restrictive. The homebrew and Python.org packages are much less restrictive.

**Comment by cjbj** [comment]
Closing - no feedback.

**Comment by yogithesymbian** [comment]
> Try using these [instructions](https://oracle.github.io/odpi/doc/installation.html#macos). Note that on recent macOS versions DYLD_LIBRARY_PATH can be ignored, depending on your configuration.

i have alr test and not work

**Comment by cjbj** [comment]
@yogithesymbian please stop spamming old issues.
