### ISSUE TITLE
Install oracle-nodedb on SUSE Linux. is this possible???

### ISSUE THREAD

**Issue by bekumu-Hub** [oracle/node-oracledb#741]
Hi All,

I am planning to install Node.js and node-oracledb on a linux machine running Linux SUSE 11.
Here are some details of my setup

**1) Linux server ( dedicated server)**
       -    this server will house node.js and  node-oracle.db installation
       -    it has a full Oracle Client version 12.1.0  installed
       -    OS is SUSE linux 11
      - 
 
**2) Database ( dedicated server)**
          -  Exadata X5 ¼ Rack running an Oracle 12.1.1.2.0 Database

One of the pre-requisites to install node-oracledb is to **install the instant client Basic” plus “Instant Client SDK** software".  I  am assuming that since the full client installation comes with all required libraries and header files,  it should not be required to install the instant client (plus SDK) in addition to that.   Is the assumption correct?

Secondly,   on the Oracle github page **_(https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)_** it is stated that  node-oracledb has been tested with Node versions 4, 6 and 7  on 64-bit Oracle Linux 7  and windows. It further states that node-oarcle-db can also build on other 32-bit Linux systems also, but it is not tested.
My main problem is that i have a Linux virtual  machine running  SUSE Linux 11   not oracle Linux ( or RedHat)
 
My question is......are we save to use our existing Linux SUSE server for node-oracle db installation, although we don't have oracle Linux ( **6** or 7) ??

Thanks in advance for your urgent help

**Comment by cjbj** [comment]
The [pre-requisites](https://github.com/oracle/node-oracledb/blob/v1.13.1/INSTALL.md#-prerequisites) say 'client libraries'.  The Oracle Instant Client is just one way to get these libraries, but the full client is fine.  

If Node works and you have the Oracle client, I wouldn't expect difficulties.  The full client should already have the header files (which are needed for node-oracledb v1 but not v2).  If you want to look, various versions of the client have been officially supported on various versions of SUSE: check your favorite Certification tool e.g. https://support.us.oracle.com

Try installing; it will only take a couple of minutes.  Follow [these instructions](https://github.com/oracle/node-oracledb/blob/v1.13.1/INSTALL.md#instoh) for node-oracledb v1, or [these instructions](https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md#instoh) for node-oracledb v2 (which is not quite yet production).  You'll need to do you own testing, and should evaluate the risks of using open source software in your environment. 

Let us know how you go.

Two tips:  If you can use the 12.2 client, I'd recommend it - it will connect to DB 12.1 just fine.  If you are just starting development, use node-oracledb v2.

**Comment by bekumu-Hub** [comment]
Hi cjbj,

I finally nailed it on SUSE 12 SP2.   Thanks so much for the valued information and tips. They were very helpful.

Here are the details of my test case

Oracle DB version:               Oracle XE;  11.2
Python version:                    python 2.7.9
C-Compiler version ( gcc):   gcc version 4.8.5 (SUSE Linux)
Node.Js Version:                   v6.11.1
node-oracledb version:        node-oracledb V1
Linux OS version:                 SUSE ( SLE 12 SP2)
Test script:                            connect.js  downloaded from gitHub
Output:                                Connection was successful!


I got some warnings while installing node-oracledb via the  command below, although the  process
did not crash..  
                  npm install oracledb

On the Production environment we have  "Exadata X5 ¼ Rack running an Oracle 12.1.1.2.0 Database"
and "SuSE 11 SP4".   SuSE 11  comes with python 2.6.9   and  gcc (version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux)) out of the box. So we might need to recompile in order to upgrade to  gcc 4.7 at least.  We might also need to upgrade to pythonh2.7

**Last question:**  
Although the node.js installation requires  python 2.7, what speaks against using the latest python 3.6 release?

Thanks again!

**Comment by anthony-tuininga** [comment]
The build process for native add-ons (node-gyp) only works with Python 2.7. There has been some discussion in the Node.js group about updating that support, but the preference is to eliminate Python entirely and use Node.js itself for the entire build process -- which is preferable, I think anyway! Once your module is installed you don't need Python at all. And if you use Python for other reasons, you can feel quite free to have both Python 2.7 and Python 3.6 installed and use Python 3.6 for any other Python work you might want to do.

**Comment by bekumu-Hub** [comment]
Thanks guys for the valued contribution.  Would be very nice to eliminate Python entirely.
