### ISSUE TITLE
npm install oracledb not working on Windows7

### ISSUE THREAD

**Issue by mohaanrajj** [oracle/node-oracledb#742]
D:\Public\xampp\htdocs\testApp>npm install oracledb

> oracledb@1.13.1 install D:\Public\xampp\htdocs\testApp\node_modules\oracledb
> node-gyp rebuild

D:\Public\xampp\htdocs\testApp\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Users\z015019-dev\AppData\Roamin
g\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
build/binding.sln(1): Solution file error MSB5014: File format version is not recognized.  MSBuild can only read solution files between versions 7.0 and 9.0, inclusive.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\z015019-dev\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\bui
ld.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\z015019-dev\\AppData\\Roaming\\npm\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Public\xampp\htdocs\testApp\node_modules\oracledb
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\Public\xampp\htdocs\testApp\package.json'
npm WARN testApp No description
npm WARN testApp No repository field.
npm WARN testApp No README data
npm WARN testApp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by cjbj** [comment]
> Solution file error MSB5014: File format version is not recognized. MSBuild can only read solution files between versions 7.0 and 9.0

What does this error mean? A quick Google shows some solutions.

**Comment by cjbj** [comment]
Closing - no update from user
