### ISSUE TITLE
Wrong output from round function 

### ISSUE THREAD

**Issue by RogerKang** [oracle/node-oracledb#744]
the return is :
```
"TEST": 7.140000000000001
```
for the query:
```
select round(7.14, 2) as test from test
```

but the query
```
select round(7.165, 2) as test from test
```
get the expected result:
```
"TEST": 7.17
```

Seems the client meets some issues for handling some specific value in round function.

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md#numberhandling
