### ISSUE TITLE
Node OracleDB Error: The specified procedure could not be found

### ISSUE THREAD

**Issue by telkomops** [oracle/node-oracledb#747]
Error when using OracleDB with Error "The specified procedure could not be found".
Node Install OracleDB went through fine.
Steps executed for build are
- Installed Visual Studio 2017 Visual C++ 14.0
- Downloaded and followed oracle instant client and sdk, OCI_BIN and OCI_INC added
- npm install npm@latest
- npm install node-gyp -g ( before this step removed c:\users\<user>\.node-gyp
- npm install oracledb
Error when running the code with `node app.js`
/app.js contents
``` 
var oracle = require("oracledb");
console.log(oracle)

```
```
gyp info using node-gyp@3.6.2
gyp info using node@6.3.1 | win32 | x64
6.3.1
node 6.3.1
npm 5.3.0
```
```
D:\test\node_modules\oracledb\lib\oracledb.js:38
    throw err;
    ^
Error: The specified procedure could not be found.
\\?\D:\test\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> D:\test\\node_modules\oracledb\lib\oracledb
.js:35:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by anthony-tuininga** [comment]
What are the contents of your PATH environment variable and the values of the OCI_INC_DIR and OCI_LIB_DIR. I assume you are using node-oracledb v1.x but it would be good to confirm that as well.

**Comment by telkomops** [comment]
OCI_INC_DIR Points to 'C:\Oracle\instantclient\lib\msvc'
OCI_LIB_DIR Points to 'C:\Oracle\instantclient\include' 
npm done was for oracledb@1.13.1

**Comment by anthony-tuininga** [comment]
And what is in your PATH environment variable?

**Comment by cjbj** [comment]
See my comment on your duplicate post https://stackoverflow.com/questions/45744822/node-oracledb-error-the-specified-procedure-could-not-be-found
