### ISSUE TITLE
oracle db installation errors

### ISSUE THREAD

**Issue by tharun06** [oracle/node-oracledb#748]
C:.....>npm install oracledb

oracledb@1.13.1 install C:\project\dqf\src\node_modules\oracledb
node-gyp rebuild
C:.....node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Users..\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin....\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0002: Failed to execute command: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe" @c:\Users..\AppData\Local\Temp\tmp1088ea37de474c999e0089bebae5f5c4.rsp". The o

gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users..\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users..\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\project\dqf\src\node_modules\oracledb
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN DQF@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\muthotk\AppData\Roaming\npm-cache_logs\2017-08-18T15_05_05_483Z-debug.log

//Can anyone help me out

9. What error(s) you are seeing?

**Comment by cjbj** [comment]
Refer to the instructions https://github.com/oracle/node-oracledb/blob/v1.13.1/INSTALL.md#instwin
and check out previous discussions.  Also see #18.

Answering the [issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) questions would have been helpful so we know what you have done.

**Comment by tharun06** [comment]
Thanks for the prompt response
What is your version of Node.js? Run examples/version.js to find versions.

v6.10.3

What version of node-oracledb are you using?

 oracledb@1.13.1

What is the version of your Oracle client (e.g. Instant Client)? How was it installed? Where it is installed?
x64-bit - 12.1.0.2.0

What is the version of Oracle Database?

What is your OS and version?

windows 7 enterprise


What compiler version did you use? For example, with GCC, run gcc --version
microsoft visual studio 2015

What environment variables did you set? How exactly did you set them?
OCI_INC_DIR=C:\orc\instantclient_12_1\sdk\include
OCI_LIB_DIR=C:\orc\instantclient_12_1\sdk\lib\msvc


What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?

npm install oracle db




error:



C:\>npm install oracledb

> oracledb@1.13.1 install C:\node_modules\oracledb
> node-gyp rebuild


C:\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Users\muthotk\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0002: Failed to execute command: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe" @C:\Users\muthotk\AppData\Local\Temp\tmp2ea3f3327c054f4bb09125e2dbceadb4.rsp". The operation completed successfully. [C:\node_modules\oracledb\build\oracledb.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\muthotk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\muthotk\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\node_modules\oracledb
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\muthotk\AppData\Roaming\npm-cache\_logs\2017-08-22T20_20_14_096Z-debug.log

![environment variables](https://user-images.githubusercontent.com/27414360/29585689-11eca9fa-8756-11e7-86c5-c665472c3534.PNG)

**Comment by tharun06** [comment]
![error](https://user-images.githubusercontent.com/27414360/29585861-a1a7fc8e-8756-11e7-935b-08f0c46c74d3.PNG)

**Comment by cjbj** [comment]
Was there anything in the verbose install output (see the issue logging template for instructions)?

Does anything in https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md#troubleshooting help? (Note this is actually for v2)

**Comment by tharun06** [comment]
![error](https://user-images.githubusercontent.com/27414360/29595516-ef06bf90-8785-11e7-9121-afb81390608d.PNG)

npm install --verbose oracledb brought me to the same error and I checked the troubleshooting  but it didn't help

**Comment by cjbj** [comment]
I can see some google hits mentioning 32 vs 64 bit clashes.

**Comment by tharun06** [comment]
So what I must do to solve this

**Comment by cjbj** [comment]
Triple-check your build, focussing on architecture (32- v 64-bit).  I've not seen the error before, sorry.
