### ISSUE TITLE
I have visual studio 2017 installed. So, why is this module not installing?

### ISSUE THREAD

**Issue by HarshVardhanKumar** [oracle/node-oracledb#749]
I have read on some blogs related to installing of this module. However they talk about installing Visual Studio 2013. But Since, I already have visual studio 2017 installed, is it still required to install Visual studio 2013?

nodejs version: - 8.4.0
node-oracledb version: - 1.13.1
instantclient version: 12.1.0 installed manually in C:\oracle\instantclient
oracle database : 12c
Os : Windows 10

Environment Variables were set manually using System Properties
![image](https://user-images.githubusercontent.com/13112792/29487471-28ebb952-8517-11e7-89d5-aa6731eed7fa.png)

The screenshot of installation error is shown below: The commands are also shown.
![image](https://user-images.githubusercontent.com/13112792/29487486-81885980-8517-11e7-9ced-eb8d17359cf5.png)

**Comment by cjbj** [comment]
To answer the direct question, the Instant Client download page (e.g. [here](http://www.oracle.com/technetwork/topics/winx64soft-089540.html) for x64) clearly lists the Redistributables that are required by the various Instant Client versions.  You need  Microsoft Visual Studio 2010 Redistributable for Instant Client 12.1.

Your screen shot is showing an SSL or network error - you might want to sort that out first.  Maybe that's what's causing the LNK1107 error.

**Comment by HarshVardhanKumar** [comment]
Hey, Thanks!

**Comment by abtrakt** [comment]
So did you have to install the lower version or is 2017 backward compatible?

**Comment by cjbj** [comment]
@abtrakt You may want to review https://github.com/oracle/node-oracledb/issues/716 and install the development release of node-oracledb v2 which has pre-built binaries (Also see https://github.com/oracle/node-oracledb/issues/803).  The Production release is due out very soon.

**Comment by abrar-khan007** [comment]
#716 #803    WHAT IS THE API ?

**Comment by cjbj** [comment]
@abrar-khan007 chapters 2 - 7 of the [documentation](https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md) describe the v1 API.  The v2 API doc is currently on the dev-2.0 branch but this will merge to master this week.
