### ISSUE TITLE
trying to install oracledb on yosemite

### ISSUE THREAD

**Issue by jaywalker1981** [oracle/node-oracledb#75]
I am trying to install oracledb on my 64 bit yosemite macbook pro. I am getting the following error. I have gone through the instructions a few times but can't figure out what I am doing wrong. Appreciate any help.

env | grep OCI
OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
OCI_LIB_DIR=/opt/oracle/instantclient
MAC:~ jaywalker$ ls /opt/oracle/instantclient/
BASIC_README		libnnz11.dylib		ojdbc5.jar
adrci			libocci.dylib.11.1	ojdbc6.jar
genezi			libociei.dylib		sdk
libclntsh.dylib		libocijdbc11.dylib	uidrvci
libclntsh.dylib.11.1	npm-debug.log		xstreams.jar
MAC:~ jaywalker$ npm install oracledb
npm WARN package.json mongo@0.1.0 No repository field.
npm WARN package.json mongo@0.1.0 No README data
\
> oracledb@0.2.4 install /Users/jaywalker/node_modules/oracledb
> node-gyp rebuild

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/njs/src/njsOracle.cpp:26:
../src/njs/src/njsOracle.h:46:24: error: expected class name
class Oracledb: public ObjectWrap 
                       ^
../src/njs/src/njsOracle.h:67:36: error: unknown type name 'Arguments'; did you
      mean 'v8::internal::Arguments'?
   static Handle<Value>  New(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/jaywalker/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/njs/src/njsOracle.cpp:26:
../src/njs/src/njsOracle.h:70:46: error: unknown type name 'Arguments'; did you
      mean 'v8::internal::Arguments'?
   static Handle<Value>  GetConnection(const Arguments& args);
                                             ^~~~~~~~~
                                             v8::internal::Arguments
/Users/jaywalker/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/njs/src/njsOracle.cpp:26:
../src/njs/src/njsOracle.h:71:36: error: unknown type name 'uv_work_t'
   static void Async_GetConnection(uv_work_t *req);
                                   ^
../src/njs/src/njsOracle.h:72:41: error: unknown type name 'uv_work_t'
   static void Async_AfterGetConnection(uv_work_t  *req);
                                        ^
../src/njs/src/njsOracle.h:75:44: error: unknown type name 'Arguments'; did you
      mean 'v8::internal::Arguments'?
   static Handle<Value>  CreatePool (const Arguments& args);
                                           ^~~~~~~~~
                                           v8::internal::Arguments
/Users/jaywalker/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/njs/src/njsOracle.cpp:26:
../src/njs/src/njsOracle.h:76:34: error: unknown type name 'uv_work_t'
   static void Async_CreatePool (uv_work_t *req );
                                 ^
../src/njs/src/njsOracle.h:77:39: error: unknown type name 'uv_work_t'
   static void Async_AfterCreatePool (uv_work_t *req );
                                      ^
../src/njs/src/njsOracle.h:81:42: error: unknown type name 'AccessorInfo'
                                   const AccessorInfo& info);
                                         ^
../src/njs/src/njsOracle.h:83:42: error: unknown type name 'AccessorInfo'
                                   const AccessorInfo& info);
                                         ^
../src/njs/src/njsOracle.h:85:48: error: unknown type name 'AccessorInfo'
                                         const AccessorInfo& info);
                                               ^
../src/njs/src/njsOracle.h:87:46: error: unknown type name 'AccessorInfo'
                                       const AccessorInfo& info);
                                             ^
../src/njs/src/njsOracle.h:89:48: error: unknown type name 'AccessorInfo'
                                         const AccessorInfo& info);
                                               ^
../src/njs/src/njsOracle.h:91:47: error: unknown type name 'AccessorInfo'
                                        const AccessorInfo& info);
                                              ^
../src/njs/src/njsOracle.h:93:42: error: unknown type name 'AccessorInfo'
                                   const AccessorInfo& info);
                                         ^
../src/njs/src/njsOracle.h:95:44: error: unknown type name 'AccessorInfo'
                                     const AccessorInfo& info);
                                           ^
../src/njs/src/njsOracle.h:97:47: error: unknown type name 'AccessorInfo'
                                        const AccessorInfo& info);
                                              ^
../src/njs/src/njsOracle.h:100:33: error: unknown type name 'AccessorInfo'
                          const AccessorInfo& info);
                                ^
../src/njs/src/njsOracle.h:102:33: error: unknown type name 'AccessorInfo'
                          const AccessorInfo& info);
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jaywalker/node_modules/oracledb
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "oracledb"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! oracledb@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jaywalker/npm-debug.log
MAC:~ jaywalker$

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/2 and the patch https://github.com/oracle/node-oracledb/pull/43

The package.json file in 0.4.2 includes a check that should cause a clearer error message when installing with Node 0.12.  I can't immediately see why this didn't show for you.
