### ISSUE TITLE
Getting this runtime error "Error: ORA-24408: could not generate unique server group name"

### ISSUE THREAD

**Issue by mshref17** [oracle/node-oracledb#750]
Hi,

I am trying to run oracledb in my MAC machine. I installed oracle instant client 12.1 and completed the steps. but still receiving this error

Error: ORA-24408: could not generate unique server group name.

Any idea... please

**Comment by cjbj** [comment]
There are plenty of [google hits](https://stackoverflow.com/questions/10484231/ora-24408-could-not-generate-unique-server-group-name#comment30445054_10710126) on this.  A hostname is necessary for creating a global UID.

Out of interest, what's in your `/etc/hosts`?
