### ISSUE TITLE
Occur Error: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by heartsease546** [oracle/node-oracledb#752]
#### Environment & Settings
- Windows 10 Pro x64
- Node.js v7.10.0 x64
- Oracle InstantClient 12.1 x64

#### Console Message
```
D:\Projects\heartseaseTest>node entry.js
D:\Projects\heartseaseTest\node_modules\oracledb\lib\oracledb.js:38
    throw err;
    ^
Error: %1 is not a valid Win32 application.
\\?\D:\Projects\heartseaseTest\node_modules\oracledb\build\Release\oracledb.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Projects\heartseaseTest\node_modules\oracledb\lib\oracledb.js:35:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

I also read the [issue 35](https://github.com/oracle/node-oracledb/issues/35) & [issue 179](https://github.com/oracle/node-oracledb/issues/179), but my settings and project did not have same problem, the error still existed.
I want to ask what should I do in next step?
Hope and thanks for your help.

**Comment by cjbj** [comment]
How do you know you don't have the same problem?  

What other Oracle software do you have on your machine?

How did you install node-oracledb - did you copy it from another machine?

**Comment by heartsease546** [comment]
@cjbj 
Followed the [issue 35](https://github.com/oracle/node-oracledb/issues/35), I checked my instant client directory, there has `oci.dll`.
And the [issue 179](https://github.com/oracle/node-oracledb/issues/179) is caused by Unicode characters,  all file in my testing directory is English character.

There has no other Oracle software in my computer.
I had tried to copy to my colleagues' computer, it still did not work.

---

I just tried to change the version of Node.js, Oracle Instant Client, Python, from 64 bit to 32 bit.
And then it work successfully.
Thanks for your response.
But I still confuse why the 64bit did not work.

**Comment by cjbj** [comment]
From the not yet-obvious https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md#troubleshooting

> Does your Node.js architecture (32-bit or 64-bit) match the Oracle client library architecture? Run node -p 'process.arch' and compare with, for example, dumpbin /headers oci.dll (on Windows), file libclntsh.dylib (macOS) or file libclntsh.so.* (Linux).

But check you are looking at the right files.
