### ISSUE TITLE
Question:install node-oracledb

### ISSUE THREAD

**Issue by Neil-Pan** [oracle/node-oracledb#754]
An error occured When install node-oracledb that use "npm install oracledb" command.The error info all as follows:
fatal error C1083:can not open the file :"oci.h":No such file or directory

**Comment by anthony-tuininga** [comment]
Please follow the instructions found [here](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md). In particular, if you are using the Instant Client you need to download and install the "SDK" package. You also need to set OCI_INC_DIR and OCI_LIB_DIR to the location where the Oracle Client is installed.

**Comment by Neil-Pan** [comment]
Thanks for your feedback,yes,I have installed something as follows:
OS:windows 7 64 bit
Nodejs:7.10.1
VS:2015
Oracle client:instantclient-basic-windows.x64-12.2.0.1.0  and instantclient-sdk-windows.x64-12.2.0.1.0 
and I have setted the environment variables OCI_INC_DIR and OCI_LIB_DIR.

**Comment by cjbj** [comment]
> I have setted the environment variables OCI_INC_DIR and OCI_LIB_DIR.

If they were set 'correctly' you would not get:

> fatal error C1083:can not open the file :"oci.h":No such file or directory

Perhaps they are not set in the terminal you are using?  Try restarting it.

**Comment by Neil-Pan** [comment]
After change the directory "C:\oracle\instantclient\sdk\include" instead of "C:\oracle\instantclient\instantclient_12_2\sdk\include" of the environment variables OCI_INC_DIR and OCI_LIB_DIR,this issue have been resolved.Thanks for your help.@cjbj
