### ISSUE TITLE
Question: ORM for oracledb

### ISSUE THREAD

**Issue by marcelotmagalhaes** [oracle/node-oracledb#757]
Hello everyone, a little off topic, but is there any ORM for oracledb with schema support that can anyone indicate?

**Comment by seanlee10** [comment]
I had the same question and came across with `typeorm`. 
https://github.com/typeorm/typeorm
It claims it supports `oracle` but the documentation is lacking in details.

**Comment by marcelotmagalhaes** [comment]
Hello Sean, thanks for your help. I also found one, it's called `oracle-sage`:
[https://github.com/FoundationMedicineInc/oracle-sage](https://github.com/FoundationMedicineInc/oracle-sage)
It works for raw queries, but some errors ocurred when I tried to create a schema.

I'm heavily considering create a repository pattern and give up on ORMs for now, until some one matures a little more...

**Comment by seanlee10** [comment]
Yes, I gave up on it too. There's this nice ORM `sequelize` that supports `mysql` and `postgre` nicely. But unfortunately, it doesn't support `oracle` yet. 
https://github.com/sequelize/sequelize

**Comment by marcelotmagalhaes** [comment]
This one looks a nice package indeed. Unfortunately oracle is the one I'm needing, but I will also keep this one in my bookmarks.
Thank you for your help!

**Comment by cjbj** [comment]
There is a Sequelize PR for Oracle support: https://github.com/sequelize/sequelize/pull/7123

Also check out http://knexjs.org/ and https://github.com/Buto/sails-oracledb-sp

**Comment by marcelotmagalhaes** [comment]
Knex looks really good, but a bit complicated. Sure worth take some time to study!
Thank you @cjbj!
