### ISSUE TITLE
Singleton connection

### ISSUE THREAD

**Issue by 1nfinite** [oracle/node-oracledb#758]
I see the documentation do close and reopen the oracle db connection after each statement/transaction is  executed.

My question is: Is this the preferable and best practice for node-oracledb as compared to using singleton for connection?

Also, how can i set up a singleton connection to oracledb.

**Comment by sagiegurari** [comment]
A connection can only run one statement at a time so your app won't scale. not to mentions that transactions would get messed up. so you don't want to go there.

**Comment by 1nfinite** [comment]
@sagiegurari So is there a way to globally open and close connection instead of repeatingly close and reopen connection everytime for each statement? It is somehow redundant for me to repeat the open and close connection statement.

eg: using interceptor to intercept the function

I am expecting something like this.

```
var oracledb = require('oracledb');

oracledb.interceptor.on('start', function() {
    /* init connection */
});

oracledb.interceptor.on('error', function() {
     /* show error */
});

oracledb.interceptor.on('finally', function() {
     /* close connection */
});


 oracledb.execute(
    "SELECT department_id, department_name " +
    "FROM departments " +
    "WHERE manager_id < :id",
    [110],  // bind value for :id
    function(err, result)
    {
    console.log(result.rows);
    });


```

**Comment by sagiegurari** [comment]
you dont reopen for each statement but per flow. and you should be using a connection pool. should be simpler and much faster

**Comment by 1nfinite** [comment]
@sagiegurari whether it is each statement or a flow/using connection or not, it still doesn't solve the problem that we need to code inside each flow/function to open and close the connection for each flow, which seems to be redundant.

Maybe i am not clear what i want. Let me restate it again.
By using a global interceptor, we can intercept the pre-request and response of the code.
Thus, we do not need to rewrite `getConnection` and `doRelease` in each of the flow.
Imagine that one have 100+ flows/api to write, it would be pretty redundant.

You may refer to the enhancement code. A basic idea on it but to be honest, i do not know how can it be implemented. Or is there a built-in functionality for it ?

**Original Code** (notice that we need to open and close connection each time we execute a flow)
```
oracledb.getConnection(
  {
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      "SELECT department_id, department_name " +
        "FROM departments " +
        "WHERE manager_id < :id",
      [110],  // bind value for :id
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
        console.log(result.rows);
        doRelease(connection);
      });
  });
```


**Enhancement Code** (by using an interceptor, we can avoid repeating the code for open and close connection in flow/function)

```
var oracledb = require('oracledb');

oracledb.interceptor.on('start', function() {
    /* init connection */
});

oracledb.interceptor.on('error', function() {
     /* show error */
});

oracledb.interceptor.on('finally', function() {
     /* close connection */
});

/* See here, we do not need to rewrite open and close  connection in the code, it will be handle automatically by the interceptor */

 oracledb.execute(
    "SELECT department_id, department_name " +
    "FROM departments " +
    "WHERE manager_id < :id",
    [110],  // bind value for :id
    function(err, result)
    {
    console.log(result.rows);
    });

Promise.all(
   execute1function,
   execute2function
]).then(function (res) {
   console.log(res);
});

```

**Comment by sagiegurari** [comment]
So maybe this would help you simplify your code
https://github.com/sagiegurari/simple-oracledb#Pool+run

**Comment by cjbj** [comment]
If oracledb.execute() is created, it will do get-connection/execute/release-connection steps, see https://github.com/oracle/node-oracledb/issues/720.

Your general architecture to execute more than one statement on each connection is efficient, and you should be able to code this yourself, like @sagiegurari has.

Watch out for the '.parallel' thoughts unless you are opening multiple connections, because each connection can only do one statement at a time.

I'm going to close this for now, since it appears to be an application design question you have to answer.
