### ISSUE TITLE
How to configure Apache 2.4 to use WebWockets using Node.js Express and Socket.IO?

### ISSUE THREAD

**Issue by bekumu-Hub** [oracle/node-oracledb#759]
<Location /globalsalesreporting_bot/>
    RewriteEngine On
    RewriteCond %{REQUEST_URI}  ^/globalsalesreporting_bot/socket.io            [NC]
    RewriteCond %{QUERY_STRING} transport=websocket    [NC]
    RewriteRule "^/globalsalesreporting_bot/socket.io"           "wss://10.11.74.4:4010/socket.io/" [P,L]

    ProxyPass https://10.11.74.4:4010/
    ProxyPassReverse https://10.11.74.4:4010/
</Location>

</Location

ProxyPass "/XXX_bot/" "https://10.11.74.4:4010/XXX_bot/"
ProxyPassReverse "/XXX_bot/" "https://10.11.74.4:4010/XXX_bot/"

ProxyPass /socket.io/ https://10.11.74.4:4010/socket.io/
ProxyPassReverse /socket.io/ https://10.11.74.4:4010/socket.io/

Can some one guide to the correct steps or tutorial to configure Apache for using WebSockets?

**Comment by cjbj** [comment]
@bekumu-Hub this isn't the best place to ask; but I'll leave the question for a bit.
