### ISSUE TITLE
App crash down with "ExceptionImpl" error (Error while trying to retrieve text for error ORA-01804)

### ISSUE THREAD

**Issue by markusND** [oracle/node-oracledb#76]
Hi everyone.
NodeJS 0.10.36
OracleDB 0.4.2

So I tried to run next app:
```javascript
var oracledb = require( "oracledb" );

var dbConfig = {
  user          : "userName",
  password      : "secWord",
  connectString : "localhost:1521/db"
};

oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function(err, connection)
  {
    if (err) { //1
      console.error( "if (err) 1. err.msg: " + err.message);
      return;
    }
    connection.execute(
      "select *" +
      "from tbl_department",
      [180],
      function(err, result)
      {
        if (err) { //2
          console.error( "if (err) 2. err.msg: " + err.message);
          return;
        }
        console.log(result.rows);
        console.log(result.metaData);
      });
  });
```

And after run - it crushes down immediately with next error:

**[node_dev@testserver nodejs]$** node scripts/oracledb_example.js
*terminate called after throwing an instance of 'ExceptionImpl'*
  *what():  Error while trying to retrieve text for error ORA-01804*
*Aborted*

Well I tried to run with *debug* key like *node debug scripts/oracledb_example.js*
And it showed me error *'ExceptionImpl'* throwing stright on first line
```javascript
    var oracledb = require( "oracledb" );
```
Then I have opened file /node_modules/oracledb/lib/oracledb.js and investigated crash line so it get down on line
```javascript
var oracledb_ins = new oracledb.Oracledb();
```

What should I do?

**Comment by cjbj** [comment]
Useful things for us would be the platform you are on, and the versions of the Oracle client libraries.

Things you can do are check that the node process is using the correct version of the Oracle libraries, and not some other, possibly older version.  What is LD_LIBRARY_PATH set to?

**Comment by markusND** [comment]
**OS:** CentOS release 6.6 (Final) x64
**Oracle:** 11g2
**LD_LIBRARY_PATH:** /u01/app/oracle/product/11.2.0.3/db_1/lib

NodeJS and Oracle 11g2 are installed and work at the same machine.

**Comment by cjbj** [comment]
Does the node process have all the read permissions it needs to access the Oracle files under $ORACLE_HOME?

**Comment by markusND** [comment]
Yep, node process started under user who at the same group that all files of owner.
So I guess it has all necessary permissions.

**Comment by Bigous** [comment]
hi @markusND you are passing the parameter 180 to the query, but the query has no parameter... it should throw the ORA-01036: illegal variable name/number ... 
But you are receiving ORA-01804 (failure to initialize timezone information) and getting an exception when try to get the error message... 
do you have the timezone files in your $ORACLE_HOME and/or are they accessible for user running the nodejs?

**Comment by markusND** [comment]
Hi @Bigous yes my query in sample is incorrect but as I wrote earlier - app gets down on first line and doesn't reach *getConnection* callback.
So u r absolutely right but it's not root cause.

Yeah, all timezone files are located in $ORACLE_HOME/oracore/zoneinfo and all directories and files have group rights for read/execute.

**Comment by cjbj** [comment]
@markusND I'd explore on two fronts: (1) the permission question (2) your environment settings for timezones et al.

Try running node as the Oracle software owner.  Try running SQL*Plus as the user you are currently running Node as.  Try using strace on node.  Is ORA_TZFILE set (validly)?
What does this (as SYSDBA) return?:
`select NAME, VALUE$ from SYS.PROPS$ where NAME like ('DST_%_TT_VERSION');`
What files do you have in `$ORACLE_HOME/oracore/zoneinfo` ?

Check out [Doc ID 1562424.1](https://support.oracle.com/rs?type=doc&id=1562424.1)

**Comment by markusND** [comment]
Amazing, I ran node as the Oracle software owner and it worked great.
It remains only to find out what kind of permissons are requered.

**Comment by cjbj** [comment]
@markusND That's good news.  The two different users might have different environment variables - check those too.

**Comment by markusND** [comment]
Root cause was missing *export* ORACLE_HOME and ORACLE_BASE variables.
I just declare a variables in *.bash_profile* but totaly forgot to do *export*.
So my *.bash_profile* was looked like:
```
ORACLE_BASE=/u01/app/oracle
ORACLE_HOME=/u01/app/oracle/product/11.2.0.3/db_1
CLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc5.jar:$APEX_HOME/utilities
PATH=$PATH:$HOME/bin:$ORACLE_HOME/bin:$ORACLE_HOME/jdk/bin

PATH=$PATH:$HOME/bin

export PATH
export PATH=$PATH:/home/node_dev/nodejs/bin

export OCI_LIB_DIR=$ORACLE_HOME/lib
export OCI_INC_DIR=$ORACLE_HOME/rdbms/public
export OCI_INCLUDE_DIR=$ORACLE_HOME/rdbms/public
export LD_LIBRARY_PATH=$ORACLE_HOME/lib
```

So as u can see above I'm missing export  ORACLE_HOME and ORACLE_BASE variables.
Just added it in *.bash_profile* like that:
```
ORACLE_BASE=/u01/app/oracle
ORACLE_HOME=/u01/app/oracle/product/11.2.0.3/db_1
CLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc5.jar:$APEX_HOME/utilities
PATH=$PATH:$HOME/bin:$ORACLE_HOME/bin:$ORACLE_HOME/jdk/bin

PATH=$PATH:$HOME/bin

export PATH
export PATH=$PATH:/home/node_dev/nodejs/bin

export ORACLE_BASE
export ORACLE_HOME

export OCI_LIB_DIR=$ORACLE_HOME/lib
export OCI_INC_DIR=$ORACLE_HOME/rdbms/public
export OCI_INCLUDE_DIR=$ORACLE_HOME/rdbms/public
export LD_LIBRARY_PATH=$ORACLE_HOME/lib
```
And after reloading *.bash_profile* for current users session it started to work like a kinda magic.
Perfect!

But I must admit - your nodejs package, I mean **oracledb** should throws more informational exceptions 'cuz it truly hard to understand what does it mean - *terminate called after throwing an instance of 'ExceptionImpl'*

**Comment by cjbj** [comment]
I think if the ORA-1804 had been more helpful you might have spotted the problem. The clue is the text "Error while trying to retrieve text".  This means that the Oracle message files could not be located or read.  I have discussed these bootstrap errors with our developers before and will continue to do so.  From the node-oracledb side I'll see if we can print a message that the initialization or bootstrap failed.

**Comment by markusND** [comment]
Yes, it error may means so and may not, cuz when I looked on error *ExceptionImpl* I thought a long while "What does it mean?"
If *node-oracledb* would showed me some error like "Cannot find or get access to oracle files" - I would thoght twise before create this issue.
