### ISSUE TITLE
Must be able to close streams prior to completion

### ISSUE THREAD

**Issue by jsumners** [oracle/node-oracledb#760]
Scenario: client issues a request that hits the route shown below. During that request the client drops for whatever reason. Thus, the request's `close` event is fired. At this point we _must_ clean up; that entails closing the connection to the database. But since the driver is still streaming the `ResultSet`, an `NJS-031` error is thrown.

```
fastify.get('/role/:roleName', roleRouteOpts, (req, reply) => {
    const roleName = req.params.roleName
    if (!fastify.rollerPlugins[roleName]) {
      req.log.error('missing role requested: %s', roleName)
      return reply.code(404).send(null)
    }

    pool.getConnection((err, conn) => {
      if (err) {
        req.log.error('failed to get connection: %s', err.message)
        req.log.debug(err.stack)
        return reply.send(err)
      }

      req.req.on('aborted', () => {
        req.log.warn('client aborted connection')
        conn.close()
      })

      req.req.on('close', (err) => {
        if (err && err.code === 'ECONNRESET') {
          req.log.error('connection terminated early: %s', err.message)
          req.log.debug(err.stack)
        } 
        conn.close() // <=== !!! Will throw NJS-031 because the stream is still going
      })

      doQuery(fastify.rollerPlugins[roleName])

      function doQuery (query) {
        const outStream = new stream.PassThrough()
        const dbstream = conn.queryStream(query, null, {
          outFormat: oracledb.OBJECT
        })

        // You must .trim() error message from Oracle because they add newlines
        dbstream.on('data', (data) => {
          req.log.debug('oracle data: %j', data)
          try {
            const result = JSON.stringify(data)
            outStream.write(Buffer.from(`${result}\n`, 'ascii'))
          } catch (e) {
            req.log.error('failed to send data: %s', e.message)
            req.log.debug(e.stack)
            outStream.write(`{"error":"${e.message.trim()}"}\n`)
          }
        })

        dbstream.on('end', () => {
          req.log.debug('db stream finished')
          outStream.end()
          conn.close()
        })

        dbstream.on('error', (err) => {
          req.log.error('error querying database: %s', err.message)
          req.log.debug(err.stack)
          outStream.write(`{"error":"${err.message.trim()}"}\n}`)
          conn.close()
          outStream.end()
        })

        reply.send(outStream)
      }
    })
  })
```

**Comment by sagiegurari** [comment]
did you try to first call connection.abort() first? it might resolve the issue

**Comment by sagiegurari** [comment]
sorry meant connection.break()

**Comment by jsumners** [comment]
@sagiegurari `conn.break()` does not exist.

**Comment by sagiegurari** [comment]
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#break

**Comment by jsumners** [comment]
Okay, for some reason it didn't like it when I did `conn.break().close()`, but invoking them without a chain worked. However, it did not solve the NJS-031 exception.

**Comment by sagiegurari** [comment]
Look at the signature carefully. You cant just invoke without a callback or without starting up the promise.
See the docs

**Comment by jsumners** [comment]
```
conn.break().then(() => conn.close()).catch((err) => {
  req.log.error('failed to closed db connection: %s', err.message)
  req.log.debug(err.stack)
})
```

^ simply results in the `catch` being invoked and logging the NJS-031 error.

**Comment by sagiegurari** [comment]
So try maybe with simple-oracledb.
After you do require to oracledb, do extend to it using simple-oracledb.
Then the close becomes resilient and with internal retries and also does the break for you internally.
Maybe it will solve the issue. Not sure.

https://github.com/sagiegurari/simple-oracledb#Connection+release

**Comment by cjbj** [comment]
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#streamingresults mentions the experimental `querystream._close()` method.  Please experiment and report back!

It was only in Node 8 that Streams introduced a [destroy()](https://nodejs.org/api/stream.html#stream_readable_destroy_error) method.  Integrating with this is on the todo list.

**Comment by cjbj** [comment]
The Streams `destroy()` method of Node 8 is supported in [node-oracledb 2.1](https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md).
