### ISSUE TITLE
Error install oracledb in Windows 10

### ISSUE THREAD

**Issue by gilbertosil** [oracle/node-oracledb#762]
Hi,
 I´m tryng to install oracledb in my computer with windows 10, but occurs a err. I put the error in an attached file, could you help me, how to resolv it ?

Computer:
- Windows 10;
- Python 2.7.13;
- Node 8.2.1
- Oracle XE(Express Edition)

[OracleDbError.txt](https://github.com/oracle/node-oracledb/files/1326717/OracleDbError.txt)

**Comment by bagl** [comment]
Hi,

"Cannot open include file oci.h" will be most probably caused because you have not setup the OCI_INC_DIR, read this part of Installation guide:

https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#74-install-the-add-on

**Comment by gilbertosil** [comment]
Thank you, Now the installer worked. But when i try to test a simple connectio another erro appeared. 

I am searching here in the list to see if anyone else has ever had the problem.

**Comment by nigilan** [comment]
@gilbertosil What is the error? Are you able to connect to your Oracle XE through SQL Plus?

**Comment by gilbertosil** [comment]
Hello @nigilan !
Sorry for the delay in returning. So by SQL I can connect normally, I'm running the connection example that is in this repository, and I get the error according to the image.
![capturar](https://user-images.githubusercontent.com/1936972/31974475-c6197490-b90a-11e7-82d9-3000c0ef39ee.PNG)

**Comment by cjbj** [comment]
The common problems would be that you don't have Oracle client libraries in PATH, that the Oracle client libraries in PATH are older than the ones that node-oracledb was compiled with, and that you don't have the correct VS Redistributable for your Oracle Client.  If you really are using Oracle XE, then the last two are unlikely.

**Comment by Ethacarinage** [comment]
@gilbertosil  how do you get to solve the first error?

**Comment by gilbertosil** [comment]
@Ethacarinage , I still can't fix the problem. 
I set windows variables:
Path = %cd%\instantclient;
OCI_INC_DIR = C:\oraclexe\app\oracle\product\11.2.0\server\oci\include
OCI_LIB_DIR = C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC

And when I install 
npm install oracledb
npm finish with sucess!
But when I try to run the exampla error persists.

**Comment by gilbertosil** [comment]
@Ethacarinage now test run! 
I set Path with de complete path os instantclient, and set OCI_INC_DIR and OCI_LIB_DIR to de includ and lib inside instantclient.

Thanks @cjbj
