### ISSUE TITLE
Running Error 'Cannot Find oracledb.node' after installing oracledb

### ISSUE THREAD

**Issue by wnasim92** [oracle/node-oracledb#763]
Having trouble when run nodemon server.js - error response says that it cannot find the specific module oracledb.node. However, I successfully npm installed oracledb....but when I look into node_modules/oracledb, I do not see any a oracledb.node file. I only see oracledb.js....

----------------------------------

1. What is your version of Node.js?  Run examples/version.js to find versions.
v6.11.0
2. What version of node-oracledb are you using?
1.13.1
3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
12.2
4. What is the version of Oracle Database?
12.1 - Oracle Database Cloud
5. What is your OS and version?
Windows 10
6. What compiler version did you use?  For example, with GCC, run `gcc --version`
Visual Studio Community 2013
7. What environment variables did you set?  How *exactly* did you set them?
Followed directions on setting Python 2.7 and Oracle installation clients files (including C:\Oracle\instantclient\, OCI_INC_DIR and OCI_LIB_DIR) to PATH 
8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
when I run nodemon server.js
9. What error(s) you are seeing?
C:\Users\wnasim\Documents\DevProjects\reactMobileProject\backendServer>node server.js
C:\Users\wnasim\Documents\DevProjects\reactMobileProject\backendServer\node_modules\oracledb\lib\oracledb.js:38
    throw err;
    ^

Error: The specified module could not be found.
\\?\C:\Users\wnasim\Documents\DevProjects\reactMobileProject\backendServer\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wnasim\Documents\DevProjects\reactMobileProject\backendServer\node_modules\oracledb\lib\oracledb.js:35:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by cjbj** [comment]
Seems typical of the npm/Node search path behavior.  The binary most probably installed in some other node_modules directory.  Have a look around and/or install again.

**Comment by wnasim92** [comment]
got it fixed! i had to be more explicit with the path variables for the client installs. thank you
