### ISSUE TITLE
query slow of binding Dates with order on SQL query

### ISSUE THREAD

**Issue by kingmayko** [oracle/node-oracledb#764]
Hi all, I have a  performance issue with binding dates at below

select * from 
(
 with t as (
 select * from t1 inner join t2 on ...
 ) 
 select  t.*, t3.x from t inner join t4 on ...
 where t.c1 = :1 and t.c2 = :2  order by ..
) where rownum ....

case 1 :  I use normal query string with js template, all it's work fine
case 2 :  I use binding dates, it's query with very long time , and after remove the order condition, it will be fast.

What is your version of Node.js? Run examples/version.js to find versions.
v6.9.2
What version of node-oracledb are you using?
v1.13.1
What is the version of your Oracle client (e.g. Instant Client)? How was it installed? Where it is installed?
1.12.2

**Comment by kingmayko** [comment]
i use ROW_NUMBER() over (order by xxx) instead of normal order,
and the issue is not exist.

**Comment by cjbj** [comment]
What's causing the problem?  The row_number() or the date binding (see #711)?

**Comment by kingmayko** [comment]
data binding,  I use the other tools query (dbeaver) with same schema, and response is very fast.
and see the sql plan which is same at the dbeaver between with and without binding.
I will try the suggestion at #711. (type miss match)

Thanks a lot.

**Comment by kingmayko** [comment]
It's seem same issue as #711 
Thanks
