### ISSUE TITLE
SIGINT/SIGTERM seems to be killing in progress connections

### ISSUE THREAD

**Issue by Stono** [oracle/node-oracledb#765]
Hi, 
I'm trying to gracefully stop an app that uses this driver, I capture SIGINT and SIGTERM with `process.on` successfully, and then my intention is to wait until operations in progress complete.

However any in progress executions seem to just bomb out with this error:

```
ORA-03113: end-of-file on communication channel
```

Which makes me think the SIGTERM is being passed down to the connection pool connections, despite me capturing it at the node level.

Any ideas how I can prevent this from happening?

**Comment by cjbj** [comment]
Nope.
