### ISSUE TITLE
error LNK2001 while installing on windows7

### ISSUE THREAD

**Issue by mazzeiandreait** [oracle/node-oracledb#767]
instantclient 11_2

npm info using npm@5.3.0
npm info using node@v6.11.2
node-gyp -v v3.6.2

i've set 
OCI_LIB_DIR and
OCI_INC_DIR
via command line

npm install oracledb --msvs_version=2015 --verbose

dpiEnv.obj : error LNK2001: unresolved external symbol OCIDescriptorFree

**Comment by cjbj** [comment]
Do you have the correct instant client first in PATH?

**Comment by mazzeiandreait** [comment]
yes i've added at 
C:\oracleinstantlient\instantclient_11_2;

in command line i've setted
set OCI_LIB_DIR=C:\oracleinstantlient\instantclient_11_2\sdk\lib\msvc
set OCI_INC_DIR=C:\oracleinstantlient\instantclient_11_2\sdk\include

![schermata1](https://user-images.githubusercontent.com/32633074/31338409-5d3453bc-acff-11e7-8dbc-d4be15256ab9.JPG)

**Comment by mazzeiandreait** [comment]
i've solved the issue installing instantclient 64 bit
so my configuration is:
win7 64bit
instantclient 12_2
msvs=2015

in the evironment variable i've addedd 
C:\oracle\instantclient1264\instantclient_12_2

then in command line 
set OCI_LIB_DIR=C:\oracle\instantclient1264\instantclient_12_2\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient1264\instantclient_12_2\sdk\include
then
npm install oracledb --msvs_version=2015 

and it works!
