### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by octodevelopers** [oracle/node-oracledb#769]
Hello,

I would like to know if there is a docker support for node-oracledb?
any supported img that includes instant client, windows build tools, Node, etc.
It could make the installation much easier for many people :) 

Thanks!

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/640 etc.

Also see the end of #18 regarding binaries, which will also make things easier for people who use Windows.  

Have you thought about Linux? - I recorded a (not-yet-released) [Two-minute-tech-tip](https://community.oracle.com/community/server_%26_storage_systems/otn-systems-hub/blog/2017/08/23/2-minute-tech-tips-at-openworld-oow17) at Oracle OpenWorld last week where I tried to convince people that Linux was easier to use with open source software :)
