### ISSUE TITLE
Connect to the db from an instance of this db ?

### ISSUE THREAD

**Issue by JYDARTHA** [oracle/node-oracledb#77]
Hi,
In the select 1.js example, how can i query the database if i don't have the informations about user, password and connection string. Actually, i import the database reference, from the controller to the view if the client has been previously  correctly identified, but i don't have his informations. For information, I use zend framework and I'd like to connect and query the client database from the view with JavaScript.

**Comment by cjbj** [comment]
You can't pass a database connection from PHP ZF apps with OCI8 driver to a Node.js node-oracledb. driver. Is your ZF app really connecting to multiple Oracle schemas?

**Comment by JYDARTHA** [comment]
Thanks cjbj,
Well, there's only one schema per user but the web app can be accessed by many users. Each user is authentified at the entrance and this identification is used to connect to his database like this: 
$identity = Oft_App::getInstance()->getCurrentIdentity();
// get oracle data base reference
$id = $identity['oracledb'];

So, now i don't know how to use tho node oracledb, to query the db on client-side.

**Comment by cjbj** [comment]
Fundamentally, you will need valid Oracle DB credentials in node-oracledb to access Oracle DB.
I don't understand your authentication flow - which layer of the app is doing the authentication, and how you carry a user's DB credentials from one HTTP request to another.
