### ISSUE TITLE
error LNK2001

### ISSUE THREAD

**Issue by xuxiaoyu9510** [oracle/node-oracledb#770]
#### Answer the following questions:

1. Node.js：v 8.6.0

2. What version of node-oracledb are you using?

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
Extract instantclient-basic-win-x86-64-11.2.0.1.0 and instantclient-sdk-win-x86-64-11.2.0.1.0 to the same file.

4. What is the version of Oracle Database? 10g

5. What is your OS and version? win7 32bit

6. What compiler version did you use?  vs2015

7. What environment variables did you set?  
PATH:  E:\oracle\instanceclient;</br>
OCI_INC_DIR:  E:\oracle\instanceclient\sdk\include</br>
OCI_LIB_DIR:E:\oracle\instanceclient\sdk\lib\msvc
8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
npm install -g oracledb
9. What error(s) you are seeing?
>  E:\mssserver\node_modules\oracledb>if not defined npm_config_node_gyp (node "E:\
nodeJS\node_global\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gy
p\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
..\src\njs\src\njsConnection.cpp(2177): warning C4244: 'argument': conversion f
rom 'unsigned __int64' to 'std::size_t', possible loss of data [E:\mssserver\no
de_modules\oracledb\build\oracledb.vcxproj]
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.cc
     Creating library E:\mssserver\node_modules\oracledb\build\Release\oracledb
  .lib and object E:\mssserver\node_modules\oracledb\build\Release\oracledb.exp
dpiEnv.obj : error LNK2001: unresolved external symbol _OCIDescriptorFree [E:\m
ssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnv.obj : error LNK2001: unresolved external symbol _OCIHandleFree [E:\mssse
rver\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnv.obj : error LNK2001: unresolved external symbol _OCIArrayDescriptorFree
[E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIEnvNlsCreate [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIDescriptorAlloc
[E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIArrayDescriptorA
lloc [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIHandleAlloc [E:\
mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIMemoryFree [E:\
mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCITransCommit [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIMemoryAlloc [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIPing [E:\mssser
ver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIContextGetValue
 [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCITransRollback [
E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCISessionRelease
[E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCISessionGet [E:\
mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIAttrGet [E:\mss
server\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIServerRelease [
E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIAttrSet [E:\mss
server\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIContextSetValue
 [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiConnImpl.obj : error LNK2001: unresolved external symbol _OCIBreak [E:\mssse
rver\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: unresolved external symbol _OCIDateTi
meConstruct [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: unresolved external symbol _OCIDateTi
meSubtract [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: unresolved external symbol _OCIInterv
alGetDaySecond [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: unresolved external symbol _OCIDateTi
meIntervalAdd [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiDateTimeArrayImpl.obj : error LNK2001: unresolved external symbol _OCIInterv
alSetDaySecond [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiPoolImpl.obj : error LNK2001: unresolved external symbol _OCISessionPoolCrea
te [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiPoolImpl.obj : error LNK2001: unresolved external symbol _OCISessionPoolDest
roy [E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIDefineDynamic [
E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIStmtExecute [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIBindByPos [E:\m
ssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIBindByName [E:\
mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIStmtPrepare2 [E
:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIDefineByPos [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIParamGet [E:\ms
sserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIBindDynamic [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIStmtFetch2 [E:\
mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiStmtImpl.obj : error LNK2001: unresolved external symbol _OCIStmtRelease [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiUtils.obj : error LNK2001: unresolved external symbol _OCIErrorGet [E:\mssse
rver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobGetChunkSize [E:\
mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobFreeTemporary [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobGetLength2 [E:\ms
sserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobRead2 [E:\mssserv
er\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobWrite2 [E:\mssser
ver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobLocatorAssign [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobIsTemporary [E:\m
ssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiLob.obj : error LNK2001: unresolved external symbol _OCILobCreateTemporary [
E:\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
dpiCommon.obj : error LNK2001: unresolved external symbol _OCIClientVersion [E:
\mssserver\node_modules\oracledb\build\oracledb.vcxproj]
E:\mssserver\node_modules\oracledb\build\Release\oracledb.node : fatal error LN
K1120: 47 unresolved externals [E:\mssserver\node_modules\oracledb\build\oracle
db.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nodeJS\node_global\node_modules\np
m\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\nodeJS\\node_global\
\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\mssserver\node_modules\oracledb
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

>  npm ERR! A complete log of this run can be found in:
npm ERR!     E:\nodeJS\node_cache\_logs\2017-10-12T01_52_48_382Z-debug.log

 I've looked at some of the previous questions that have been changed to 64 bit instanceclient or modified environment variables. But I am a 32-bit system, and the environment variable is set correctly. I'm not sure what went wrong.

**Comment by cjbj** [comment]
If you're on Windows 32 bit, perhaps you should stick to 32 bit Node, and 32 bit Instant Client?

**Comment by xuxiaoyu9510** [comment]
Yes,I'm using 32bit.And I had saw all issue about error LNK2001 and try.It's not work

**Comment by cjbj** [comment]
@xuxiaoyu9510 did you get any further?

**Comment by xuxiaoyu9510** [comment]
no。。

**Comment by cjbj** [comment]
Check how PATH is set.  Check whether you have the right VS Redistributable (see the Instant Client download page).

Is your DB on the same machine as Node?  If so, you don't need Instant Client.

If you do use Instant Client, I would use 11.2.0.4 Instant Client, or even 12.2 if your DB is 11.2+.

**Comment by kubo** [comment]
@xuxiaoyu9510 
> Yes,I'm using 32bit.And I had saw all issue about error LNK2001 and try.It's not work

Are you using 32 bit instant client?

In your first comment:
> Extract instantclient-basic-win-x86-64-11.2.0.1.0 and instantclient-sdk-win-x86-64-11.2.0.1.0 to the same file.

They are 64 bit packages.

**Comment by xuxiaoyu9510** [comment]
![image](https://user-images.githubusercontent.com/26201563/33064401-8049e878-cee0-11e7-8f7e-6d9e1e53380d.png)
Was it because I had several versions of VS Redistributable that caused the error?

> Path=C:\Python27\;C:\Python27\Scripts;
E:\oracle\product\10.2.0\db_2\bin;E:\oracle\instanceclient;
C:\Program Files\nodejs\;E:\nodeJS\node_global

There are no 32-bit instance client since 11.2.0.1.0
@kubo

**Comment by kubo** [comment]
>There are no 32-bit instance client since 11.2.0.1.0

`instantclient-basic-win32-11.2.0.1.0.zip` is the 32-bit instant client.

**Comment by kubo** [comment]
> Was it because I had several versions of VS Redistributable that caused the error?

No. VS redistributable is required only at runtime. Even when no redistributable packages are installed, it doesn't cause the link error.

**Comment by cjbj** [comment]
@xuxiaoyu9510 any progress?  If all else fails, you could be an early adopter and try the development version `npm install oracledb@dev` which installs a pre-built binary, see #716

**Comment by xuxiaoyu9510** [comment]
ok,the issue is solved.Wrong instance client.Sorry for wasting everyone's time on such a low-level problem
