### ISSUE TITLE
symbol lookup error undefined symbol: OCIClientVersion

### ISSUE THREAD

**Issue by AugustoEMoreira** [oracle/node-oracledb#775]
1. What is your version of Node.js?  
8.6.0
2. What version of node-oracledb are you using?
1.13.1

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
Instant Cliente -> 12.2(like in the tutorial)

5. What is your OS and version?
Ubuntu 16.04

6. What compiler version did you use?  For example, with GCC, run `gcc --version`
5.4.0

7. What environment variables did you set?  How *exactly* did you set them?
export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
export OCI_LIB_DIR=/opt/oracle/instantclient
export OCI_INC_DIR=/opt/oracle/instantclient/sdk/include

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
When i run the select1.js example script

9. What error(s) you are seeing?
node: symbol lookup error: ~/node_modules/oracledb/build/Release/oracledb.node: undefined symbol: OCIClientVersion

**Comment by AugustoEMoreira** [comment]
ldd ~/node_modules/oracledb/build/Release/oracledb.node output:
```
	linux-vdso.so.1 =>  (0x00007ffdc4399000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f79ed721000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f79ed50b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f79ed2ed000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f79ecf23000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f79ecc1a000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559187e7d000)

```

**Comment by anthony-tuininga** [comment]
Is that the complete output? Its missing a reference to libclntsh.so, which probably explains your error! Can you clean your build directories and post the output of a verbose build? Make sure it includes all of the compile and link commands that are being executed and their output. Something doesn't appear to be working properly there.

**Comment by AugustoEMoreira** [comment]
NPM verbose log:
[npmlog.txt](https://github.com/oracle/node-oracledb/files/1408020/npmlog.txt)

**Comment by anthony-tuininga** [comment]
That file seems to be missing the command lines for compiling/linking. See the attached for my own NPM verbose log: [npmlog.txt](https://github.com/oracle/node-oracledb/files/1408070/npmlog.txt). Without those compile/link lines its going to be very difficult to figure out what the problem is! Once you have those, let me know. Thanks!

**Comment by AugustoEMoreira** [comment]
Sorry, here the correct
[log.txt](https://github.com/oracle/node-oracledb/files/1408100/log.txt)

**Comment by anthony-tuininga** [comment]
That looks fine. So what is the output of the command

ls -l $OCI_LIB_DIR

**Comment by AugustoEMoreira** [comment]
`ls -l $OCI_LIB_DIR         
total 216700
-rwxrwxr-x 1 root root     44220 Jan 26  2017 adrci
-rw-rw-r-- 1 root root       363 Jan 26  2017 BASIC_README
-rwxrwxr-x 1 root root     57272 Jan 26  2017 genezi
-rwxrwxr-x 1 root root   8033199 Jan 26  2017 libclntshcore.so.12.1
lrwxrwxrwx 1 root root        21 Out 23 11:28 libclntsh.so -> libclntshcore.so.12.1
-rwxrwxr-x 1 root root  71638263 Jan 26  2017 libclntsh.so.12.1
-r-xr-xr-x 1 root root   2981501 Jan 26  2017 libipc1.so
-r-xr-xr-x 1 root root    539065 Jan 26  2017 libmql1.so
-r-xr-xr-x 1 root root   6568149 Jan 26  2017 libnnz12.so
-rwxrwxr-x 1 root root   2218687 Jan 26  2017 libocci.so.12.1
-rwxrwxr-x 1 root root 124771800 Jan 26  2017 libociei.so
-r-xr-xr-x 1 root root    158543 Jan 26  2017 libocijdbc12.so
-r-xr-xr-x 1 root root    380996 Jan 26  2017 libons.so
-rwxrwxr-x 1 root root    116563 Jan 26  2017 liboramysql12.so
-r--r--r-- 1 root root   4036257 Jan 26  2017 ojdbc8.jar
drwxrwxr-x 5 root root      4096 Jan 26  2017 sdk
-rwxrwxr-x 1 root root    240476 Jan 26  2017 uidrvci
-rw-rw-r-- 1 root root     74230 Jan 26  2017 xstreams.jar
`

**Comment by AugustoEMoreira** [comment]
ls -l $OCI_LIB_DIR         
-rwxrwxr-x 1 root root     44220 Jan 26  2017 adrci
-rw-rw-r-- 1 root root       363 Jan 26  2017 BASIC_README
-rwxrwxr-x 1 root root     57272 Jan 26  2017 genezi
-rwxrwxr-x 1 root root   8033199 Jan 26  2017 libclntshcore.so.12.1
lrwxrwxrwx 1 root root        21 Out 23 11:28 libclntsh.so -> libclntshcore.so.12.1
-rwxrwxr-x 1 root root  71638263 Jan 26  2017 libclntsh.so.12.1
-r-xr-xr-x 1 root root   2981501 Jan 26  2017 libipc1.so
-r-xr-xr-x 1 root root    539065 Jan 26  2017 libmql1.so
-r-xr-xr-x 1 root root   6568149 Jan 26  2017 libnnz12.so
-rwxrwxr-x 1 root root   2218687 Jan 26  2017 libocci.so.12.1
-rwxrwxr-x 1 root root 124771800 Jan 26  2017 libociei.so
-r-xr-xr-x 1 root root    158543 Jan 26  2017 libocijdbc12.so
-r-xr-xr-x 1 root root    380996 Jan 26  2017 libons.so
-rwxrwxr-x 1 root root    116563 Jan 26  2017 liboramysql12.so
-r--r--r-- 1 root root   4036257 Jan 26  2017 ojdbc8.jar
drwxrwxr-x 5 root root      4096 Jan 26  2017 sdk
-rwxrwxr-x 1 root root    240476 Jan 26  2017 uidrvci
-rw-rw-r-- 1 root root     74230 Jan 26  2017 xstreams.jar

**Comment by anthony-tuininga** [comment]
Can you fix the formatting on that post? Its pretty hard to read!

**Comment by anthony-tuininga** [comment]
Ok. There's the problem. :-) You have created a symbolic link to the wrong library!

cd $OCI_LIB_DIR
rm libclntsh.so
ln -s libclntsh.so.12.1 libclntsh.sh

**Comment by AugustoEMoreira** [comment]
now, npm is not installing the package
[log2.txt](https://github.com/oracle/node-oracledb/files/1408272/log2.txt)

**Comment by anthony-tuininga** [comment]
Double check $OCI_LIB_DIR. The error given is "Cannot find $OCI_LIB_DIR/libclntsh.so"!

**Comment by AugustoEMoreira** [comment]
> Double check $OCI_LIB_DIR. The error given is "Cannot find $OCI_LIB_DIR/libclntsh.so"!

You asked me to delete this file

**Comment by anthony-tuininga** [comment]
Yes, and then recreate it! See comment above.

**Comment by AugustoEMoreira** [comment]
thats works thanks
