### ISSUE TITLE
Json object precision error

### ISSUE THREAD

**Issue by BigLato** [oracle/node-oracledb#779]
I'm using node-oracledb to return a JSON object from the query but I am having some precision issues. Below is my execute command.
`conn.execute('SELECT TO_NUMBER(00000.24500) AS "NUM" from dual', [], { outFormat: oracledb.OBJECT }, function (e, result)`

Instead of returning { "NUM": 0.245 }, I get the following. { "NUM": 0.24500000000000002 }

**Comment by cjbj** [comment]
Check out https://github.com/oracle/node-oracledb/blob/master/doc/api.md#numberhandling and https://github.com/oracle/node-oracledb/blob/master/doc/api.md#fetchasstringhandling.  Yell out if you have further questions.
