### ISSUE TITLE
ORDER BY in query gives me ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by a2441918** [oracle/node-oracledb#781]
Hi I have a query and I am using resultSet to process data. The query works fine but when I append 'ORDER BY name des', it gives me ORA-00933: SQL command not properly ended error.

My post request:

    app.factory('ReportResource', ['$http', '$q', '$filter', '$timeout',
        function ($http, $q, $filter, $timeout) {

            function getJson(age, startRow, numRows, sortCol, sortDir, callback) {
                $http({
                    url:  '/reports/age-report/',
                    method: 'POST',
                    data: {
                        age: age,
                        startRow: startRow,
                        numRows: numRows,
                        sortCol: sortCol,
                        sortDir: sortDir
                    },
                    headers: {
                        'Content-Type': 'application/json'
                    }
                }).then(function(response){
                    console.log(response);
                    callback(response.data);
                });
            }

            function getPage(age, startRow, numRows, sortCol, sortDir) {

                var deferred = $q.defer();

                getJson(age, startRow, numRows, sortCol, sortDir, function (items) {
                    $timeout(function () {
                        //note, the server passes the information about the data set size
                        deferred.resolve({
                            data: items
                        });
                    }, 1500);
                });

                return deferred.promise;
            }

            return {
                getPage: getPage
            };
        }]);

This is my query.

	router.post('/age-report/', jsonParser, function (req, res) {
	    var data = req.body,
               age = data.age,
	        startRow = data.startRow,
	        numRows = data.numRows,
               sortCol = assert.simpleSqlName(data.sortCol),
              sortDir = assert.validSortOrder(data.sortDir);

	    var countQuery = 'SELECT COUNT(*) ' +
	        'FROM this_view ' ;

	    var query = 'SELECT t.NAME "NAME", ' +
	            	't.AGE "AGE" ' +
	        		'FROM this_view t ' +
	        		'ORDER BY NAME desc';

	    var seg,
	        orderBy,
	        offset;

    if(!age){
        seg = ' WHERE "AGE" = '+ '\''+ age+'\'' ;
        query += seg;
        console.log(query);
        countQuery += seg;
    }
	    orderBy = ' ORDER BY UPPER(' + sortCol + ') ' + sortDir;
	    offset = ' OFFSET :start_row ROWS FETCH NEXT :num_rows ROWS ONLY';

	    query += orderBy;
	    query += offset;

	        async.parallel({
	        rows: function (callback) {
	            pool.getConnection(function (err, connection) {
	                logger.info("Begin Connection: " + (new Date().toString()));
	                if (err) {
	                    logger.error(err.message);
	                    return;
	                }

	                logger.info("Begin execute: " + (new Date().toString()));

	                connection.execute(
	                    query,
	                    [],
	                    {
                                start_row: startRow,
                                num_rows: numRows,
	                        resultSet: true,
	                        prefetchRows: 1000
	                    },
	                    function (err, result) {
	                        logger.info("End execute: " + (new Date().toString()));
	                        // var rowsProcessed = 0;
	                        // var startTime;
	                        if (err) {
	                            logger.error(err.message);
	                            callback("Something broke in the first thing");
	                            doRelease(connection);
	                            return;
	                        }
	                        var procJson = [];
	                        function fetchRowsFromRS(connection, resultSet, numRows) {
	                            resultSet.getRows(
	                                numRows,  // get this many rows
	                                function (err, rows) {
	                                    if (err) {
	                                        console.error(err);
	                                        doClose(connection, resultSet); // always close the result set
	                                    } else if (rows.length > 0) {

	                                        /**
	                                         *  For each row in the result, pushes a new object to the rows array
	                                         *  In each new object, the key is assigned and the result row value set
	                                         */
	                                        for (var i = 0; i < rows.length; i++) {
	                                            procJson.push({});
	                                            for (var j = 0; j < resultSet.metaData.length; j++) {
	                                                procJson[i][resultSet.metaData[j].name.toLowerCase()] = rows[i][j];
	                                            }
	                                        }

	                                        //TODO: Add null handling
	                                        logger.info("Send JSON: " + (new Date().toString()));
	                                        logger.info("JSON Sent: " + (new Date().toString()));
	                                        if (rows.length === numRows) // might be more rows
	                                            fetchRowsFromRS(connection, resultSet, numRows);
	                                        else
	                                            doClose(connection, resultSet); // always close the result set
	                                    } else {
	                                        callback(null, procJson);
	                                        doClose(connection, resultSet); // always close the result set
	                                    }
	                                });
	                        }
	                        fetchRowsFromRS(connection, result.resultSet, numRows)
	                    });
	            });
	        },
	        totalRows: function (callback) {
	            pool.getConnection(function (err, connection) {
	                logger.info("Begin Connection: " + (new Date().toString()));
	                if (err) {
	                    logger.error(err.message);
	                    return;
	                }

	                logger.info("Begin execute: " + (new Date().toString()));

	                connection.execute(
	                    countQuery,
	                    function (err, result) {
	                        logger.info("End execute: " + (new Date().toString()));
	                        if (err) {
	                            logger.error(err.message);
	                            callback("Something broke");
	                            doRelease(connection);
	                            return;
	                        }

	                        logger.info("Send JSON: " + (new Date().toString()));
	                        callback(null, result.rows[0][0]);
	                        logger.info("JSON Sent: " + (new Date().toString()));

	                        doRelease(connection);
	                    });
	            });
	        }
	    }, function(err, result){
	        if(err){
	            logger.error(err);
	        }

	        res.send(result);
	    });
	});

Since I am paginating, cant I use ORDER BY in the query itself? 

If I dont use ORDER BY in the query, everything works fine. Please advice. // FIXED BY REMOVING ONE ORDER BY.

This is the error I get in the browser.
    POST  https://localhost:3000/reports/age-report/ net::ERR_EMPTY_RESPONSE

**Comment by dmcghan** [comment]
@a2441918 I have to keep saying this till you fix it - this code is vulnerable to SQL injection. Input from users must be sent into Oracle as bind variables (values) or be properly sanitized (identifiers). 

Also, you don't need two queries, one will work.

I'm guessing you're appending two ORDER BY clauses. Do a console log of the query that's giving you the error and share it here.

**Comment by a2441918** [comment]
@dmcghan When I sanitize the identifiers, I get this error.

ORA-01008: not all variables bound

assert.js:


    function simpleSqlName(name) {
        if (name.length > 30) {
            throw new Error('Not simple SQL');
        }

        /**
         * Fairly generic, but effective. Would need to be adjusted to accommodate quoted identifiers,
         * schemas, etc.
         */
        if (!/^[a-zA-Z0-9#_$]+$/.test(name)) {
            throw new Error('Not simple SQL');
        }

        return name;
    }

    function validSortOrder(order) {
        if (order !== 'desc' && order !== 'asc') {
            throw new Error('Not valid sort order');
        }

        return order;
    }

    module.exports = {
        simpleSqlName: simpleSqlName,
        validSortOrder: validSortOrder
    };

Also I have updated my code with the new sanitized variables.

**Comment by a2441918** [comment]
@dmcghan This is a more simplified version of the console logged query.
 
    SELECT t.NAME "NAME", t.age "AGE" FROM this_view t WHERE ORDER BY name desc  ORDER BY UPPER(name) asc OFFSET :start_row ROWS FETCH NEXT :num_rows ROWS ONLY

**Comment by dmcghan** [comment]
@a2441918 You're getting "ORA-01008: not all variables bound" because you're specifying the bind variables as part of the third parameter to `execute` (which if for options). Bind variables are passed in the second parameter (you currently have an empty array). 

Use the object syntax demonstrated in the third example here: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#bind

**Comment by dmcghan** [comment]
Here's your query with line breaks.
```
SELECT t.NAME "NAME", 
  t.age "AGE" 
FROM this_view t 
WHERE 
ORDER BY name desc 
ORDER BY UPPER(name) asc 
OFFSET :start_row ROWS 
FETCH NEXT :num_rows ROWS ONLY
```

Notice you have 2 ORDER BY clauses. You should only have 1.

**Comment by a2441918** [comment]
@dmcghan Thanks Dan. The bind variable fix worked.

**Comment by a2441918** [comment]
@dmcghan When I use resultSet, does 'WHERE' clause work? So the requriement is that I filter on the data I get by age by entering the age in a search bar and append that as a parameter in WHERE clause in the query. Initial result without WHERE clause works perfectly and I get the data. When WHERE clause is implemented I dont. Do you want me to update the code here?

**Comment by dmcghan** [comment]
@a2441918 Yes, the WHERE clause works just fine.

> When WHERE clause is implemented I dont.

Do you get an error or just no data? Please show the query that you're executing. Better, yet, don't show me (because you'll likely modify it anyway and I don't have your database). 

Instead, take the query from your code and paste it into something like SQL Developer and see if it works there. http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index.html

**Comment by a2441918** [comment]
@dmcghan It works in SQL developer. I have updated my code with the where clause. 

SQL developer returns me a value but I get empty response in the UI.

**Comment by dmcghan** [comment]
@a2441918 What you're saying doesn't add up. If you take the query EXACTLY as you're trying to run it over to SQL Developer and enter EXACTLY the same values for the bind variables, then you will get the same results. 

My guess is your either making modifications to the query (such as dropping clauses you don't think are relevant) or you're not entering the same values for the bind variables.

**Comment by a2441918** [comment]
This is the query I logged.

    SELECT t.NAME "NAME", t.age "AGE" FROM this_view t WHERE "AGE" = '15' ORDER BY t.name desc  OFFSET :start_row ROWS FETCH NEXT :num_rows ROWS ONLY

the query I tried in SQL developer is this

    SELECT t.NAME "NAME", t.age "AGE" FROM this_view t WHERE "AGE" = '15' ORDER BY t.name desc 

And that worked in SQL developer. I just removed everything post OFFSET when querying through SQL developer.

**Comment by dmcghan** [comment]
@a2441918 Why are you removing anything? Execute the query exactly the same with the same bind variables.

**Comment by dmcghan** [comment]
@a2441918 Also, age should not be a literal, it should be a bind variable!

**Comment by a2441918** [comment]
So even if its "name", it should be a bind variable?

**Comment by dmcghan** [comment]
Yes, any values that come from the outside world (supplied by end users, not developers) should be brought in as bind variables to avoid SQL injection.

**Comment by a2441918** [comment]
Thanks. And I can use your simpleSqlName function to sanitize eveyrhting except sortOrder right?

**Comment by dmcghan** [comment]
> simpleSqlName function to sanitize eveyrhting except sortOrder right

That's a broad statement. I'll simply state what that function is for: identifiers that have simple SQL names (table names, view names, column names, etc.).

It's the start of a JavaScript version of this in PL/SQL:
https://docs.oracle.com/database/121/ARPLS/d_assert.htm#ARPLS65389

However, as you look through the list of things that the PL/SQL function covers, you'll see that the JavaScript version needs more work to be as flexible. Right now it just rejects any quotes to play it safe.

**Comment by a2441918** [comment]
Thanks @dmcghan .
