### ISSUE TITLE
Error: NJS-009: invalid number of parameters

### ISSUE THREAD

**Issue by nitinsinghit** [oracle/node-oracledb#784]
I am trying to execute this query 

    "SELECT username, last_login " +
            "FROM dba_users " +
            "WHERE username = :username ",
            {
              username:username
            },

using oracledb nodejs package. Not sure why I am getting `Error: NJS-009: invalid number of parameters`. I can run same query using sql console successfully. Please guide thanks.

**Comment by cjbj** [comment]
Please post a full script and also answer the [issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) questions - they are there so we can help understand what's going on.  Thanks!

**Comment by pvenkatraman** [comment]
Try
        "SELECT username, last_login " +
        "FROM dba_users " +
        "WHERE username = :username ",
        {
          username:  { val : username }
        }

**Comment by nitinsinghit** [comment]
@pvenkatraman sorry no luck

**Comment by cjbj** [comment]
@nitinsinghit you still haven't given us the script you are running.  In particular the execute() call which is presumably the one complaining about parameters.  If we can't see what parameters you have, we can't help you.

**Comment by nitinsinghit** [comment]
@cjbj here is the full script
```
var express = require('express');
var router = express.Router();
var oracledb = require('oracledb');
var config = require('../config.js');
var path = require('path');

router.get('/', function getUser(req, res, next) {
    var username_in = req.query.username;
    oracledb.getConnection(config.database,
    function (err, connection) {
      if (err) {
        res.set('Content-Type', 'application/json');
        res.status(500).send(JSON.stringify({
          status: 500,
          message: 'Error connecting to DB',
          detailed_message: connectionError.message
        }));
        return;
      }

      connection.execute(
        // The statement to execute
        "SELECT username, last_login " +
        "FROM dba_users " +
        "WHERE username = :username_in",
        {
          username: {val:username_in}
        },
        function (err, results) {
          function logError(e) {
            if (e) {
              console.error(e.message); // TODO: Error logging
            }
          }

          if (err) {
            connection.release(err);
            return next(err);
          }

          res.status(200).json(results.rows);
          connection.release(logError);
        });
    }
  );
});

module.exports = router;
```

**Comment by cjbj** [comment]
The code
```
 "WHERE username = :username_in",
        {
          username: username_in
        },
```

should be:

```
 "WHERE username = :username_in",
        {
          username_in: username
        },
```
because the syntax is name:value.

Try this and see what happens.

**Comment by nitinsinghit** [comment]
@cjbj In my script var username_in hold the value and example you gave me username_in is name and username is value. I get error username is not defined. Am I missing something here. 
```
{
     username_in: username
 },
```

**Comment by cjbj** [comment]
That's a different issue.  Check the manual and examples and I'm sure you'll find the solution.

**Comment by dmcghan** [comment]
You declared a variable named `username_in` in `getUser`.

You have a bind variable named `username_in` in your SQL query.

Yet, in your binds you specify:
```javascript
 "WHERE username = :username_in",
        {
          username: username_in
        },
```

With bind variables, you can bind by position using an array or by name (as you are doing). When binding by name you are mapping the value of a property in the object to a bind variable that corresponds with the name of the property.

You have a column named `username`. But that doesn't matter. 

You should have:
```javascript
 "WHERE username = :username_in",
        {
          username_in: username_in
        },
```
