### ISSUE TITLE
No results when the result is less than numRows

### ISSUE THREAD

**Issue by a2441918** [oracle/node-oracledb#785]
I am trying to filter data from a response which gets data using resultSet. I have two ways to get the data, one is without using resultSet and the other is with using.

The one using resultSet doesnt work if my response returns just 3 rows of data which I guess is because its less than numRows (10).

    router.post('/report/', jsonParser, function (req, res) {
    var data = req.body,
        name= data.name,
        startRow = data.startRow,
        numRows = data.numRows,
        sortCol = assert.simpleSqlName(data.sortCol),,
        sortDir = assert.validSortOrder(data.sortDir);

    var countQuery = 'SELECT COUNT(*) ' +
        'FROM this_view ' +
        'WHERE Status = \'Present\' ';

    var query = 'SELECT t.STATUS "STATUS", ' +
        't.NAME "NAME", ' +
        't.ADDRESS "ADDRESS", ' +
        'FROM this_view t ' +
        'WHERE Status = \'Present\' ';

    var seg,
        orderBy,
        offset;

    if(name !== null && name !== ""){
        seg = ' AND "NAME" = '+ '\'' + name + '\'';
        query += seg;
        countQuery += seg;
    }

    orderBy = ' ORDER BY UPPER(' + sortCol + ') ' + sortDir;
    offset = ' OFFSET :start_row ROWS FETCH NEXT :num_rows ROWS ONLY';

    query += orderBy;
    query += offset;

    console.log(query);

    logger.info("Begin: " + (new Date().toString()));

    async.parallel({
                     rows: function (callback) {
            pool.getConnection(function (err, connection) {
                logger.info("Begin Connection: " + (new Date().toString()));
                if (err) {
                    logger.error(err.message);
                    return;
                }

                logger.info("Begin execute: " + (new Date().toString()));

                connection.execute(
                    query,
                    {
                        start_row: startRow,
                        num_rows: numRows
                    },
                    {
                        resultSet: true,
                        prefetchRows: 1000
                    },
                    function (err, result) {
                        logger.info("End execute: " + (new Date().toString()));
                        if (err) {
                            logger.error(err.message);
                            callback("Something broke in the first thing");
                            doRelease(connection);
                            return;
                        }
                        var procJson = [];

                        function fetchRowsFromRS(connection, resultSet, numRows) {
                            resultSet.getRows(
                                numRows,  // get this many rows
                                function (err, rows) {
                                    if (err) {
                                        console.error(err);
                                        doClose(connection, resultSet); // always close the result set
                                    } else if (rows.length > 0) {

                                        /**
                                         *  For each row in the result, pushes a new object to the rows array
                                         *  In each new object, the key is assigned and the result row value set
                                         */
                                        for (var i = 0; i < rows.length; i++) {
                                            procJson.push({});
                                            for (var j = 0; j < resultSet.metaData.length; j++) {
                                                procJson[i][resultSet.metaData[j].name.toLowerCase()] = rows[i][j];
                                            }
                                        }

                                        //TODO: Add null handling
                                        logger.info("Send JSON: " + (new Date().toString()));
                                        logger.info("JSON Sent: " + (new Date().toString()));
                                        if (rows.length === numRows) // might be more rows
                                            fetchRowsFromRS(connection, resultSet, numRows);
                                        else
                                            doClose(connection, resultSet); // always close the result set
                                    } else {
                                        callback(null, procJson);
                                        doClose(connection, resultSet); // always close the result set
                                    }
                                });
                        }
                        fetchRowsFromRS(connection, result.resultSet, numRows);
                    });
            });
        },
        totalRows: function (callback) {
            pool.getConnection(function (err, connection) {
                logger.info("Begin Connection: " + (new Date().toString()));
                if (err) {
                    logger.error(err.message);
                    return;
                }

                logger.info("Begin execute: " + (new Date().toString()));

                connection.execute(
                    countQuery,
                    function (err, result) {
                        logger.info("End execute: " + (new Date().toString()));
                        if (err) {
                            logger.error(err.message);
                            callback("Something broke");
                            doRelease(connection);
                            return;
                        }

                        logger.info("Send JSON: " + (new Date().toString()));
                        console.log(result.rows);
                        callback(null, result.rows[0][0]);
                        logger.info("JSON Sent: " + (new Date().toString()));

                        doRelease(connection);
                    });
            });
        }
    }, function(err, result){
        if(err){
            logger.error(err);
            res.status(404);
            res.send('No Entries');
        }
        else {
            res.send(result);
        }
    });
    });

When "Status" returns me 3 or less results, it doesnt seem to return back anything whereas this code works for me perfectly.

    router.post('/report/', jsonParser, function (req, res) {
    var data = req.body,
        name= data.name,
        startRow = data.startRow,
        numRows = data.numRows,
        sortCol = assert.simpleSqlName(data.sortCol),,
        sortDir = assert.validSortOrder(data.sortDir);

    var countQuery = 'SELECT COUNT(*) ' +
        'FROM this_view ' +
        'WHERE Status = \'Present\' ';

    var query = 'SELECT t.STATUS "STATUS", ' +
        't.NAME "NAME", ' +
        't.ADDRESS "ADDRESS", ' +
        'FROM this_view t ' +
        'WHERE Status = \'Present\' ';

    var seg,
        orderBy,
        offset;

    if(name !== null && name !== ""){
        seg = ' AND "NAME" = '+ '\'' + name + '\'';
        query += seg;
        countQuery += seg;
    }

    orderBy = ' ORDER BY UPPER(' + sortCol + ') ' + sortDir;
    offset = ' OFFSET :start_row ROWS FETCH NEXT :num_rows ROWS ONLY';

    query += orderBy;
    query += offset;

    console.log(query);

    logger.info("Begin: " + (new Date().toString()));

    async.parallel({
        rows: function (callback) {
            pool.getConnection(function (err, connection) {
                logger.info("Begin Connection: " + (new Date().toString()));
                if (err) {
                    logger.error(err.message);
                    return;
                }

                logger.info("Begin execute: " + (new Date().toString()));

                connection.execute(
                    query,
                    {
                        start_row: startRow,
                        num_rows: numRows
                    },
                    function (err, result) {
                        logger.info("End execute: " + (new Date().toString()));
                        if (err) {
                            logger.error(err.message);
                            callback("Something broke in the first thing");
                            doRelease(connection);
                            return;
                        }

                        var procJson = [];

                        /**
                         *  For each row in the result, pushes a new object to the rows array
                         *  In each new object, the key is assigned and the result row value set
                         */
                        for (var i = 0; i < result.rows.length; i++) {
                            procJson.push({});
                            for (var j = 0; j < result.metaData.length; j++) {
                                procJson[i][result.metaData[j].name.toLowerCase()] = result.rows[i][j];
                            }
                        }

                        //TODO: Add null handling
                        logger.info("Send JSON: " + (new Date().toString()));
                        callback(null, procJson);
                        logger.info("JSON Sent: " + (new Date().toString()));

                        doRelease(connection);
                    });
            });
        },
        totalRows: function (callback) {
            pool.getConnection(function (err, connection) {
                logger.info("Begin Connection: " + (new Date().toString()));
                if (err) {
                    logger.error(err.message);
                    return;
                }

                logger.info("Begin execute: " + (new Date().toString()));

                connection.execute(
                    countQuery,
                    function (err, result) {
                        logger.info("End execute: " + (new Date().toString()));
                        if (err) {
                            logger.error(err.message);
                            callback("Something broke");
                            doRelease(connection);
                            return;
                        }

                        logger.info("Send JSON: " + (new Date().toString()));
                        console.log(result.rows);
                        callback(null, result.rows[0][0]);
                        logger.info("JSON Sent: " + (new Date().toString()));

                        doRelease(connection);
                    });
            });
        }
    }, function(err, result){
        if(err){
            logger.error(err);
            res.status(404);
            res.send('No Entries');
        }
        else {
            res.send(result);
        }
    });
    });

This is my final query which I get.

SELECT t.STATUS "STATUS", t.NAME "NAME", t.ADDRESS"ADDRESS" FROM this_view t WHERE Status = 'Present'  AND "NAME" = 'ARUN'  ORDER BY UPPER(name) asc OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

**Comment by a2441918** [comment]
@dmcghan Do you have any suggestions?

**Comment by cjbj** [comment]
@a2441918 getrows() will return all rows, even when the number of rows in the result set is less than the size you pass in.  Keep debugging and I'm sure you'll find a solution (PS @dmcghan is at a conference)

PPS, the way you are concatenating sortCol into the query text makes me nervous.  You should use the value to index into a hardcoded list of column names, and have a default (or throw an error) if a match isn't found.  I've no idea what simpleSqlName does, but don't trust it.

**Comment by a2441918** [comment]
@cjbj Thanks Chris. Will do.

I also have an export button which exports all the results to an excel file. It doesnt seem to work with resultSet. Is there a way to export all data using resultSet or should I write a new query?

**Comment by cjbj** [comment]
(i) you can fetch all data with a resultSet.

(ii) even from the comments in simpleSqlName it isn't secure, so follow my previous suggestion.

I'll close this; if you have new questions, open new issues.
