### ISSUE TITLE
OracleDB installation fails on Windows

### ISSUE THREAD

**Issue by josecarlosbarros** [oracle/node-oracledb#787]
*Delete irrelevant parts of this template.*

### For general questions:
C:\Users\ABE000155\node\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\dev\node-v8.9.1-win-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\dev\node-v8.9.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\dev\node-v8.9.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\dev\node-v8.9.1-win-x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\dev\\node-v8.9.1-win-x64\\node.exe" "C:\\dev\\node-v8.9.1-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ABE000155\node\node_modules\oracledb
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node@1.0.0 No description
npm WARN node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Use `npm install --verbose oracledb`.  Review your output and logs.
Try to install in a different way.  **Google anything that looks like an error.**  Try some potential solutions.

For Node 4 onwards, you need a compiler with C++11 support.  On Linux use GCC 4.7 or later.

Did the error indicate a network connection issue?  Do you need to set `http_proxy`?

Try running `npm cache clean` and deleting the `node_modules/oracledb` directory.

Do you have an old version of `node-gyp` installed?  Try updating it.  Also try deleting `$HOME/.node-gyp` or equivalent.

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.

2. What version of node-oracledb are you using?

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

4. What is the version of Oracle Database?

5. What is your OS and version?

6. What compiler version did you use?  For example, with GCC, run `gcc --version`

7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

9. What error(s) you are seeing?

There are no solutions on Google so please help me.

**Comment by cjbj** [comment]
This looks like the first problem:
```
Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

Check 7.1 in the i[nstallation instructions](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin) for where to get python.

**Comment by cjbj** [comment]
Closing due to no feedback.  Consider trying installing version 2 which was just released; pre-built binaries are available for some architectures.
