### ISSUE TITLE
Can not run after include oracledb 

### ISSUE THREAD

**Issue by chalu-tantiw** [oracle/node-oracledb#788]
I tried to start node server after add oracledb 

System:
OS : windows 10
Node: 7.7.3 
oracledb: 1.13.1

after install following this step 
1. get oracle client and sdk 
2. get Visual Studio 2010 redistributable.
3. get python 2.7 
4. config PATH as following.
--- set OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
--- set OCI_INC_DIR=C:\oracle\instantclient\sdk\include
also include 
--- set Path=C:\oracle\instantclient\

then after start server it shown: 
Error: The specified procedure could not be found.

#105 #320  #382 #673   but It does not work 

Any suggestion for solve this issue?

Thank you in advance.

**Comment by cjbj** [comment]
Hoe do you know install worked?  Where is 'oracle.node'? Do you have the VS Redistributable mentioned on the Instant Client download page?

**Comment by chalu-tantiw** [comment]
Thanks @cjbj 
How do I check that installation is worked?
- I try to run node app and it said 
`Error: The specified procedure could not be found.
\\?\D:\project\ecco\node_modules\oracledb\build\Release\oracledb.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\project\ecco\node_modules\oracledb\lib\oracledb.js
:46:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

`


Where is 'oracle.node'?
- This is my oracle.node path : D:\project\ecco\node_modules\oracledb\build\Release

Do you have the VS Redistributable mentioned on the Instant Client download page?
- Yes, I found that someone's tutotial that translate to my home lang is mention about trying to install VS redistributable

**Comment by cjbj** [comment]
> How do I check that installation is worked?

You know when 'npm install oracledb' gives an error, and you don't have a node_modules/oracledb/build/Release/oracledb.node binary created.  

You say

> This is my oracle.node path : D:\project\ecco\node_modules\oracledb\build\Release

but your error shows 

> Error: The specified procedure could not be found.
> \\?\D:\project\ecco\node_modules\oracledb\build\Release\oracledb.node

What is the "\\?\\".

Assuming you do have oracledb.node in the right place, then check standard things: make sure you have the same architecture (32-bit or 64-bit) Oracle client libraries as your architecture of Node.js.  Make sure they are first in PATH. Triple check you have the correct redistributable for your version of Instant Client (the [INSTALL](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#71-install-prerequisites) lists them.  Maybe read the proposed [troubleshooting guide](https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md#troubleshooting) on the dev-2.0 branch.

**Comment by chalu-tantiw** [comment]
thanks again @cjbj  let me check something following above question

**Comment by cyrilgeorgemv** [comment]
I am getting the same issue since last Friday (24-Nov). Before that every thing was working fine.
Checked the node_modules folder for the specified file oracledb.node and it's there .

**Comment by cjbj** [comment]
@cyrilgeorgemv this issue was opened by someone else (unless you are the same team), so I don't have the details about your environement.  You may want to check the latest comments in #18, but be warned the v2 release is still under development.

**Comment by cyrilgeorgemv** [comment]
@cjbj  Thanks will check it out. When the issue is resolved will comment back with the root cause. :)

**Comment by kubo** [comment]
@cyrilgeorgemv What version of Oracle client do you use? If you use node-oracledb compiled for Oracle 12c with Oracle 11g client, you'll get "The specified procedure could not be found".
(Well, I have not checked it by running node-oracledb on Windows. Just a guess.)

When node-oracledb is compiled for Oracle 12c, `oracledb.node` uses `OCIBindByPos2` in OCI.DLL. If it is used with Oracle 11g client, it cannot run because the `OCIBindByPos2` procedure could not be found in Oracle 11g OCI.DLL.

**Comment by kubo** [comment]
@cyrilgeorgemv If you use Oracle 12.2 client on Windows Vista or Windows Server 2008, you'll get same error because Oracle 12.2 client uses `K32GetModuleBaseNameA` in kernel32.dll but it is available since Windows 7 and Windows Server 2008 R2.

**Comment by cjbj** [comment]
@chalu-tantiw @cyrilgeorgemv If all else fails, you could be an early adopter and try the development version `npm install oracledb@dev` which installs a pre-built binary, see #716.

**Comment by zacliu** [comment]
**I got below error when npm install oracledb, and I have try vcredist_x64 2017 and vcredist_x64 2010 but not working, anyone can help this? thank you.**

c:\users\9909105\.node-gyp\8.9.2\include\node\v8.h(4034): fatal error C1003: error count exceeds 100; stopping compilat ion [D:\loopbackapi\sctacommon\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\loopbackapi\sctacommon\node_modules\oracledb
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by cjbj** [comment]
@zacliu your problem is not related to the topic of this 'issue'.  Also try 'npm install oracledb@dev'

**Comment by cjbj** [comment]
Closing due to lack of feedback.
