### ISSUE TITLE
not able to open oci.lib

### ISSUE THREAD

**Issue by Nanduyana** [oracle/node-oracledb#789]
D:\oracle-db\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1181: cannot open input file 'oci.lib' [D:\oracle-db\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\oracle-db\node_modules\oracledb
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\oracle-db\package.json'
npm WARN oracle-db No description
npm WARN oracle-db No repository field.
npm WARN oracle-db No README data
npm WARN oracle-db No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XYZ\AppData\Roaming\npm-cache\_logs\2017-11-11T08_46_17_506Z-debug.log

**Comment by Nanduyana** [comment]
can someone help me in this regard 

OCI_INC_DIR = C:\oraclexe\app\oracle\product\11.2.0\server\oci\include
OCT_LIB_DIR  = C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC

this is with the installation of oracle XE 11 which is already installed in my PC

and tried with instance client as well but i get the same problem "not able to open oci.lib"

thanks in advance.

**Comment by cjbj** [comment]
Sounds like PATH isn't set.  If you have both Instant Client and XE installed, it can be easy to get path conflicts on Windows.  Check the [install instructions](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin) again.

**Comment by kubo** [comment]
> OCT_LIB_DIR = C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC

Is it typo? `OCT_LIB_DIR` -> `OCI_LIB_DIR`

**Comment by Nanduyana** [comment]
Yes its a Typo.
Thanks for the suggestions,
it was a permission issue, when given full rights for the path then was able to install it
