### ISSUE TITLE
npm install oracledb fails 

### ISSUE THREAD

**Issue by madhukrishna123** [oracle/node-oracledb#791]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Use `npm install --verbose oracledb`.  Review your output and logs.
Try to install in a different way.  **Google anything that looks like an error.**  Try some potential solutions.

For Node 4 onwards, you need a compiler with C++11 support.  On Linux use GCC 4.7 or later.

Did the error indicate a network connection issue?  Do you need to set `http_proxy`?

Try running `npm cache clean` and deleting the `node_modules/oracledb` directory.

Do you have an old version of `node-gyp` installed?  Try updating it.  Also try deleting `$HOME/.node-gyp` or equivalent.

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.
V8.9.1
2. What version of node-oracledb are you using?
default npm install oracledb
3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
c:\oracle\instantclient
4. What is the version of Oracle Database?
not reached till this point. 
5. What is your OS and version?
64 bit wndows server 2008 R2
6. What compiler version did you use?  For example, with GCC, run `gcc --version`
everything given in the configuration
7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

9. What error(s) you are seeing?ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
oracledb:
  C:\Program Files\Microsoft Visual Studio 8\VC\vcpackages\VCBuild.exe D:\svn_m
  adhu\ReduxSimpleStarter-master\node_modules\oracledb-pb\build\oracledb.vcproj
   "Release|x64"
  The following error has occurred during XML parsing:

  File: D:\svn_madhu\ReduxSimpleStarter-master\node_modules\oracledb-pb\build\o
  racledb.vcproj
  Line: 1
  Column: 220
VCBUILD : error Message:  [D:\svn_madhu\ReduxSimpleStarter-master\node_modules\
oracledb-pb\build\binding.sln]
  '9.00' violates enumeration constraint of '7.00 7,00 7.10 7,10 8.00 8,00'.
  The attribute 'Version' with value '9.00' failed to parse.

  The file 'D:\svn_madhu\ReduxSimpleStarter-master\node_modules\oracledb-pb\bui
  ld\oracledb.vcproj' has failed to load.
Done Building Project "D:\svn_madhu\ReduxSimpleStarter-master\node_modules\orac
ledb-pb\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"D:\svn_madhu\ReduxSimpleStarter-master\node_modules\oracledb-pb\build\binding.
sln" (default target) (1) ->
(oracledb target) ->
  VCBUILD : error Message:  [D:\svn_madhu\ReduxSimpleStarter-master\node_module
s\oracledb-pb\build\binding.sln]

    0 Warning(s)
    1 Error(s)

**Comment by cjbj** [comment]
Can you confirm the info given?  The install command you gave is for 'oracledb' but the errors are for 'oracledb-pb' which is fork at  [oracledb-pb](https://www.npmjs.com/package/oracledb-pb)

**Comment by madhukrishna123** [comment]
thanks for checking on this. Both oracledb-pb and oracledb is giving the same error.
I was trying a lot of combinations to get this working. oracledb-pb was the last option. 
I am guessing the version of C:\Program Files\Microsoft Visual Studio 8\VC\vcpackages\VCBuild.exe seems be a problem. Though I am not able to get around this.
I actually very excited to have this node module. Want to really try this.

**Comment by suryadeepchatterjee3107** [comment]
I think this is because of the Node js Version. Npm Oracle db documentation says "This node-oracledb release has been tested with Node 4, 6 and 7 on 64-bit Oracle Linux and Windows. The add-on can also build in some macOS, 32-bit Linux, 32-bit Windows, Solaris and AIX environments, but these architectures have not been fully tested. Node 0.10 and 0.12 have been supported in the past and may still be usable."

**Comment by madhukrishna123** [comment]
[npm-debug.log](https://github.com/oracle/node-oracledb/files/1483072/npm-debug.log)
Looks like it is not a problem with node version. Tried with 6.12.0. Still getting the same error

**Comment by madhukrishna123** [comment]
[error.txt](https://github.com/oracle/node-oracledb/files/1483110/error.txt)

**Comment by cjbj** [comment]
Looks like a compiler issue.  Try https://github.com/oracle/node-oracledb/issues/302#issuecomment-334766018 or wait for #18

**Comment by cjbj** [comment]
@madhukrishna123 did you get any further? If all else fails, you could be an early adopter and try the development version `npm install oracledb@dev` which installs a pre-built binary, see #716.

**Comment by madhukrishna123** [comment]
No I was not able to get any further. Therefore created  ADF BC REST (12.2) service layer based on Entities and View Objects that would help me fetch and save data into a oracle database. Would be great if I could avoid the same and reach to oracle database directly by using oracledb the same from . Thanks for the update I can try the earlyadopter dev version  and let you know if this works for me.

**Comment by madhukrishna123** [comment]
Oracledb@dev installed for me. I am giving it a try. Thanks for the help. I will repoint mycode to point to oracledb driver from ADF BC REST Calls.

**Comment by cjbj** [comment]
@madhukrishna123 thanks for the update.  I'll close this issue.  Keep an eye on the node-oracledb project so you know when we release the "Production" 2.0 package.
