### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by Hyurl** [oracle/node-oracledb#797]
### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Use `npm install --verbose oracledb`.  Review your output and logs.
Try to install in a different way.  **Google anything that looks like an error.**  Try some potential solutions.

For Node 4 onwards, you need a compiler with C++11 support.  On Linux use GCC 4.7 or later.

Did the error indicate a network connection issue?  Do you need to set `http_proxy`?

Try running `npm cache clean` and deleting the `node_modules/oracledb` directory.

Do you have an old version of `node-gyp` installed?  Try updating it.  Also try deleting `$HOME/.node-gyp` or equivalent.

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.
    8.9.1

2. What version of node-oracledb are you using?
    No any, I couldn't even install it.

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
    11.2, it is fine.

4. What is the version of Oracle Database?
    11.2

5. What is your OS and version?
    windows 10

6. What compiler version did you use?  For example, with GCC, run `gcc --version`
    visual studio 2015 enterprise

7. What environment variables did you set?  How *exactly* did you set them?
   I set them exactly as the doc tells me, inc_dir, lib_dir and path are all set properly.

8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
    I just type `npm install oracledb`.

9. What error(s) you are seeing?
    They are pretty long errors, it will cut some off:
    D:\git\modelar2\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: 无法打开包括文件: “oci.h”: No such file
or directory (编译源文件 ..\src\njs\src\njsConnection.cpp) [D:\git\modelar2\node_modules\oracledb\build\oracledb.vcxproj]
D:\git\modelar2\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: 无法打开包括文件: “oci.h”: No such file
or directory (编译源文件 ..\src\njs\src\njsResultSet.cpp) [D:\git\modelar2\node_modules\oracledb\build\oracledb.vcxproj]
  njsMessages.cpp
  njsIntLob.cpp
D:\git\modelar2\node_modules\oracledb\src\dpi\include\dpiLob.h(34): fatal error C1083: 无法打开包括文件: “oci.h”: No such file

Briefly, it says `Not such files`, and I check the directory `D:\git\modelar2\node_modules\`, and there is not even an `oracledb` folder.

I don't know understand, if there isn't an `oracledb` folder, that means I haven't download this module properly, how does the compiling procedure begin? Has the compiling program mistakenly deleted the folder and its files?

**Comment by anthony-tuininga** [comment]
From the error message it would seem that you are missing the OCI header files. You will need to download the "SDK" package for your platform from [here](http://www.oracle.com/technetwork/database/features/instant-client/index-097480.html).

The installation instructions [here](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin) should be followed.

**Comment by Hyurl** [comment]
I guess I've figured out what the problem really was. In the documentation, it says:

Tell the installer where to locate the Oracle client libraries and header files by setting the OCI_LIB_DIR and OCI_INC_DIR variables. **Do not add them to PATH**.

For Instant Client use:

set OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\oracle\instantclient\sdk\include
Use absolute paths for the variable values. These variables are only needed during installation.

If you are installing with a local database or the full Oracle client, then locate the Oracle directory and set the node-oracle installer variables similar to:

set OCI_LIB_DIR=C:\oracle\product\12.1.0\dbhome_1\oci\lib\msvc
set OCI_INC_DIR=C:\oracle\product\12.1.0\dbhome_1\oci\include

My situation was, I set those variables in the vs shell, but I started another shell to install `oracledb`, thus causing the problem. I had been a little confused when I set those variables, but I didn't take it too much. Now I know why.

**Comment by danilohgds** [comment]
@cjbj I believe this can be closed, question has been answered.
