### ISSUE TITLE
Cannot run a SQL statements that contains ";"

### ISSUE THREAD

**Issue by Hyurl** [oracle/node-oracledb#799]
It's very important that this driver should allow users to run several SQL statements at the same time, and can run some complex statements like `begin...end;` clause. I have a statement showing bellow, its fine with other DB tools (tried in Navicat), but with `node-oracledb`, an "ORA-00911: Invalid character“ error will be thrown.

    create table "USERS2" (
            "ID" integer,
            "NAME" varchar(50) default '',
            "GENDER" varchar(10) default 'male',
            "USER_ID" int,
            primary key("ID"),
            foreign key ("USER_ID") references "USERS" ("ID") on delete set null
    );
    begin
            execute immediate 'drop sequence "USERS2_ID_SEQ"';
    exception
            when others then
                    if sqlcode != -0942 then dbms_output.put_line(sqlcode||'---'||sqlerrm);
            end if;
    end;
    /
    create sequence "USERS2_ID_SEQ" increment by 1 start with 10000;
    create or replace trigger "USERS2_TRIGGER" before insert on "USERS2" for each row
    begin
            select "USERS2_ID_SEQ".nextval into :new."ID" from dual;
    end;

This code is meant to create a table that its primary key can autoincrement, when the package doesn't accept a semicolon, I don't know what should I do to achieve that goal. Oracle is a very complex database, simple statements won't be enough.

**Comment by dmcghan** [comment]
@Hyurl The driver's `execute` method executes a single SQL statement or PL/SQL block. What you have is a collection of both, a.k.a. a SQL script. 

If someone took the time, they could write a Node.js module that parses your script (identifying the individual statements) and then executes them with the driver. That's essentially what tools that allow you to run scripts do.

One of the reasons folks may not take the time to write such a module is that there are existing tools, such as SQL*Plus and the more modern [SQLcl](http://www.oracle.com/technetwork/developer-tools/sqlcl/overview/index.html) that already do this. Have you looked at SQLcl?

**Comment by dmcghan** [comment]
@Hyurl I answered a similar question [here in SO](https://stackoverflow.com/questions/47214604/node-oracle-all-or-nothing-query/). Maybe that answer would help if you do need to execute your SQL scripts from Node.js.

**Comment by danilohgds** [comment]
@Hyurl, consider looking up knex, you can chain commands with it, and also u can run your begin end pl-sql blocks as raw commands.

**Comment by cjbj** [comment]
@Hyurl Just so we know what you'd like to do why is it 'important'?  What is special about the SQL command file - is it being used by different projects/programs?  Is it being generated?

**Comment by Hyurl** [comment]
@dmcghan Thanks for your advice, the problem is solved by separating the SQL statement and PL/SQL block.

**Comment by kwent** [comment]
Why this logic is implemented in most native driver as [node-postgres](https://github.com/brianc/node-postgres) or [node-sqlite3](https://github.com/mapbox/node-sqlite3) or [mysqljs](https://github.com/mysqljs/mysql) but not oracle ?

Regards

**Comment by cjbj** [comment]
@kwent Because nobody has submitted a PR for it!  The core team has been focusing mostly on things that you can't do (or do efficiently) yourself in JavaScript.  Since this is an open source project, maybe you can create a discussion proposal?  Cover all the details (how do you want things that are, say, SQL*Plus specific (like SET commands) to behave, how do/if you want callbacks with query output from multiple queries to behave, how you want errors to be handled etc. Then submit a PR. Thanks!
