### ISSUE TITLE
SQL keyword NULL maybe Escape

### ISSUE THREAD

**Issue by DebinHuang** [oracle/node-oracledb#8]
```javascript
connection.execute(
      "SELECT user_name, user_id "
    + "FROM fnd_user "
    + 'WHERE user_name IS NOT NULL'
	+ "AND user_id <= :did",
      [100],
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log(result.rows);
      });
```

And the node-oracledb will report:
ORA-00908: missing NULL keyword

I think maybe the NULL is also keyword for JS, and some where has been escaped.

**Comment by zorrofox** [comment]
This is not about JS, but for C++. Please see this:
http://stackoverflow.com/questions/305349/p-sql-setting-null-value

And I find just have a space char after the NULL and between single quotation marks can resolve this issue.

```javascript
connection.execute(
      "SELECT user_name, user_id "
    + "FROM fnd_user "
    + 'WHERE user_name IS NOT NULL '
    + "AND user_id <= :did",
      [100],
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log(result.rows);
      });
```

**Comment by cjbj** [comment]
The problem seems to due to the missing whitespace in the SQL statement, as @zorrofox noted.
