### ISSUE TITLE
ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by scrapex** [oracle/node-oracledb#801]
I keep getting the following error when running the lambda in aws "ORA-12154: TNS:could not resolve the connect identifier specified". The connection works fine when I try running on my local windows machine or even in an EC2 instance. The issue only happens when deploying on lambda.

I am running Nodejs 6.10.3 and have included all the necessary libraries. There seems to be an issue with the connection string but it works fine else where.

Here is the additional information 
The AWS lambda version of Node is 6.10.3
Node-oracledb version is 1.13.1
Instant Client 12.1
gcc version  4.8.3 20140911 
Environmental variables set (HOSTALIASES ->  /tmp/HOSTALIASES)
All the *.so files are underl "lib" folder in the zip file uploaded to lambda. 

`exports.handler = function(event, context, callback) {
console.log('event:', event);
console.log('context:', context);
try {
oracledb = require('oracledb-for-lambda');
console.log('oracledb: supported');

  var conn = {
	  user: "my user",
	  password: "my password",
	  connectString: "DOMAIN:PORT/DATABASE",
	  externalAuth: false
	};

  oracledb.getConnection(conn, (err, connection) => {
	if (err) {
	  console.log("connection ERROR.."); ->> CODE FAILS HERE
	  console.error(err.message);
	  return;
	}
	console.log("connection successful..");
  });
	

} catch (e) {
    console.log('Failed to load oracledb:');
    console.log(e);
    callback('Failed to load oracledb');
}

if (oracledb != null) {
    callback(null, 'Oracle DB is supported');
} else {
    callback('Did not actually expect to see this, `require(\'oracledb\')` will fail');
}
};`

**Comment by dmcghan** [comment]
Maybe you have this elsewhere, but were do DOMAIN:PORT/DATABASE come from? Can you show us a version of the code a bit closer to what you actually have?

Have you verified that those environment variables are what they should be in Lambda (via console.log or other)?

The next step is to ensure that network connectivity between the servers is what yo expect. Does Lambda have some kind of firewall that needs to be opened up?

Have you tried tnsping?

**Comment by scrapex** [comment]
@dmcghan DOMAIN:PORT/DATABASE is just the connection string to the database hosted in an ec2 instance in the same VPC. I cannot share the exact connection string, but I dont think there is a problem with it since I can connect to the database from my local windows machine as well as an ec2 instance. 

I have also verified the env variables console.log(process.env.HOSTALIASES), etc. 

It might just be a firewall issue but I always thought that lambda would have the same firewall rules as other ec2 instances running on the same VPC. I am not sure how to run tnsping from the lambda, but i'll do some research if thats possible. 

Also, I don't have tnsnames.ora since this is a Lambda function that's why i'm using a connection string as mentioned above.

**Comment by dmcghan** [comment]
@scrapex  If it were my database, I wouldn't have that port open to the world. Check the database firewall too.

**Comment by scrapex** [comment]
@dmcghan I was able to figure out the issue. there was a configuration issue in the  lambda. I did not set up the VPC and subnets correctly therefore the connection issue to the database. Thanks for pointing to the right direction.

**Comment by cjbj** [comment]
@scrapex now you have it working, can you check out the 2.0 Dev release of node-oracledb and see if the pre-built binaries have access to the right glibc etc on Lambda?  Install with 'npm install oracledb@dev'.  See https://github.com/oracle/node-oracledb/issues/716 for details and links e.g to the full INSTALL manual.

**Comment by jenrrygpc** [comment]
I have had the same problem, I solved this problem verifying the configuration of VPC since my lambda couldn't see the server of oracle. but i am very thankful since i had the idea reading the comment above.

**Comment by cjbj** [comment]
For future readers, my colleagues article on connection errors is worth reviewing https://www.thatjeffsmith.com/archive/2014/09/ora-12545-12541-12514-01017/
