### ISSUE TITLE
Set node-oracledb working with a custom environement variable ?

### ISSUE THREAD

**Issue by JocelynDalle** [oracle/node-oracledb#802]
I am willing to create an Electron application for Windows working with oracledb. But the target computer already has an instant_client installed for another Oracle application, so I can't change the Path variable.

My question is to know if it is possible to make my application to listen on a custom environement variable so I don't have to touch the Path environnement variable, and if it's possible, what do i need to do.

**Comment by dmcghan** [comment]
@JocelynDalle

**Comment by bchr02** [comment]
Just modify path for your app environment by adding the following line to the very top of your main file process.env['PATH'] = 'path to instantclient;' + process.env['PATH'];

**Comment by bchr02** [comment]
you can then bundle instant client within your app

**Comment by JocelynDalle** [comment]
It looks like to work perfectly. Thank you very much !
