### ISSUE TITLE
Installation Problem oracledb@dev on Win 10 x64

### ISSUE THREAD

**Issue by awn70** [oracle/node-oracledb#803]
Hi,
I want to use the pre-built binaries but the installation throws this error: 
NJS-054 Binary build/Release/oracledb.node was not installed from oracledb-v2.0.14-node-v57-win32-x64.gz

The output of "npm install --verbose oracledb@dev" is here [https://gist.github.com/awn70/de756737e8c6a6c58454de6a785fe951](https://gist.github.com/awn70/de756737e8c6a6c58454de6a785fe951)

OS: Windows_NT 10.0.16299 x64 (1709)
node: v8.9.1
npm:  v5.5.1

Can anybody tell me what the problem is?
Thanks
Andreas

**Comment by bchr02** [comment]
Looks like your on 64bit Windows but using a 32 bit Node. Which is fine so long as a 32 bit instant client is in your path environment variable.

**Comment by dmcghan** [comment]
@awn70 Looks like you're on Windows 32 bit, I think there are only binaries for 64 bit. However, I'd have expected a different error.

You're getting a "oracledb ERR! socket hang up" error so it's likely network related. Are you doing this from home or work? Are there any HTTP proxies involved?

Please do the Windows equivalent of the following so we can get more insight: 
export NODE_ORACLEDB_TRACE_INSTALL=TRUE

Then rerun the install and you should see some more verbose output. Please let us see that but ensure that nothing private is in the output first.

**Comment by awn70** [comment]
I have added the log for NODE_ORACLEDB_TRACE_INSTALL="TRUE" to the gist above.
AFAIK there is no 32 bit nodejs on my system.

**Comment by cjbj** [comment]
Did you check the 'socket hangup' error?  Anything ring a bell?

Some google hits: 
https://github.com/nodejs/node/issues/9845
https://github.com/request/request/issues/2047

Since you can reproduce it, and we can't, maybe you can help find a solution?

**Comment by cjbj** [comment]
More links:
http://mcranston18.github.io/gulp-sever/
https://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean

I'll give some more concrete debugging suggestions when I'm at work tomorrow.

**Comment by cjbj** [comment]
Actually I think I can repro.  I'll look again at it first thing tomorrow.

**Comment by awn70** [comment]
I'm behind a proxy and in my npm configuration the parameters `proxy` and `https-proxy` are set. I have changed the `registry` to `http://registry.npmjs.org/` but nothing helps. Installing other npm packages works without any problems.

**Comment by cjbj** [comment]
For the moment, I suggest compiling from source code following https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md or using the manual install method (section 3.12.2 in INSTALL). 

The proxy handling code in oracledbinstall.js needs some tweaking; it was all working but perhaps some wider ssl change has broken it.  I've been banging my head against it all day.

**Comment by awn70** [comment]
Compiling from source is not possible, I have visual studio 2017. AFAIK it's only working with vs2015.
Manual installation works!
If you need somebody for proxy installation tests, then let me know.
Thanks!

**Comment by cjbj** [comment]
@awn70 I've made a tweak to the proxy code. (The situation was all very Twilight Zone).  Can you download https://github.com/oracle/node-oracledb/releases/download/v2.0.14/oracledb-2.0.14.tgz and then install it with `npm install oracledb-2.0.14.tgz`?  This will download the binary.

**Comment by awn70** [comment]
Looks good, `oracledb/build/Release` contains a `oracledb.node` binary. You can see the output in the gist above (console2.log).

**Comment by cjbj** [comment]
@awn70 thanks for confirming it works - and for being first to be struck by this latent bug.

We're close to releasing 2.0.15 which will have this fix for proxy support.  npm won't allow republishing, AFAICT so I won't push the patched 2.0.14 there.
