### ISSUE TITLE
ORM with nodeJS

### ISSUE THREAD

**Issue by satodu** [oracle/node-oracledb#804]
Hi,

I want to know if is needed or recomended ORM for use the NODEJS application and OracleDB ..

Thanks and regards

**Comment by dmcghan** [comment]
@satodu That could be a personal preference or a design decision based on what's being built. 

- Are you comfortable with SQL? If so, you might want to use the driver.
- Are you building an app you want to run on multiple databases? If so, ORMs could have some merit.

Personally, I've never been one to use ORMs. I'm comfortable with SQL and I enjoy the power and flexibility of working at the lower level.

**Comment by satodu** [comment]
Hello,
Actually I am using Express to build a microservice. Worked well using Knex.js ( http://knexjs.org/ ), and we built our own models.

Thanks and regards,

For me can close the question. Please tell me if need some information.

**Comment by atiertant** [comment]
@satodu have a look at [offshore](https://github.com/Atlantis-Software/offshore) with [offshore-sql](https://github.com/Atlantis-Software/offshore-sql)
