### ISSUE TITLE
Do you guys support python 3 versions?

### ISSUE THREAD

**Issue by nitinsinghit** [oracle/node-oracledb#806]
#### Answer the following questions:

1. What is your version of Node.js?  v8.9.3

4. What is the version of Oracle Database? 12C 

5. What is your OS and version? Windows 2016

**Comment by cjbj** [comment]
Have you tried the node-oracledb pre-built binaries that don't need building (and don't need Python to install)?  See https://github.com/oracle/node-oracledb/issues/716

Node.js [add-ons](https://nodejs.org/api/addons.html#addons_building) that are built from C code end up using node-gyp which uses gyp which uses Python 2.7.  There is plenty of discussion about moving away from Python 2.7 on the node-gyp repo, e.g. https://github.com/nodejs/node-gyp/issues/960 and https://github.com/nodejs/node-gyp/pull/1092  This is not something that node-oracledb can change directly.

**Comment by nitinsinghit** [comment]
Thanks @cjbj I was able to make it work using [copying node-oracle binaries approach](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#winbins).  I have to use Visual Studio 2015 redistributable for Oracle 12.2client libraries version. Thanks for the help. I avoided using python3
