### ISSUE TITLE
Unable to install oracledb v2.0.15 on Node 7

### ISSUE THREAD

**Issue by aroper23** [oracle/node-oracledb#811]
When I try to install the current version of oracledb by running "npm install oracledb", I get this error:

oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.15-node-v51-linux-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-v2.0.15-node-v51-linux-x64.gz failed with code 404
oracledb ERR! If the error is not network or filesystem related, then review
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and
oracledb ERR! then install from source code with: npm install oracle/node-oracledb.git#v2.0.15
oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

The 404 seems to indicate the gzip isn't available. Looking at the release, I don't see any v51 files for v2.0.15 of oracledb. Are the v51 files missing or perhaps are the files named improperly in this version's configuration in GitHub?

I observed this problem on servers on two different networks.
1. Ubuntu v16.04.2 LTS x64, running node v7.10.1
2. Red Hat Enterprise Server 7.4 x64, running node v7.10.1

**Comment by dmcghan** [comment]
The prebuilt binaries only exist for some versions of Node.js - I think 4, 6, and 8 (those with LTS support). Read more about that [here](https://blogs.oracle.com/opal/node-oracledb-20-with-pre-built-binaries-is-on-npm). 

You can still [install from source](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#github). Try:
`npm install oracle/node-oracledb#v2.0.15`

We can look into handling the error you got better in the future.

**Comment by cjbj** [comment]
Node 7 is dead: https://github.com/nodejs/Release  There are pre-built node-oracledb binaries for Node 4,6,8, & 9 at the moment, and we'll drop 9 pretty quickly when Node 10 comes.

If you have a lot of Node 7 installs, you could host your own binaries: https://github.com/oracle/node-oracledb/blob/master/package/README.md

**Comment by cjbj** [comment]
I updated the [GitHub release notes](https://github.com/oracle/node-oracledb/releases/tag/v2.0.15) to make it clearer.
