### ISSUE TITLE
cannot load the oracledb add-on binary for Node.js 8.9.3 (linux, x64)

### ISSUE THREAD

**Issue by RayeesMir** [oracle/node-oracledb#812]
<img width="1241" alt="ss" src="https://user-images.githubusercontent.com/11449067/34111632-4e23b0d0-e430-11e7-8517-e39436dfd026.png">
I have Followed https://medium.com/oracledevs/creating-a-sandbox-for-learning-node-js-and-oracle-database-dd27706af6c4

 Tutorial to install Oracle. 

npm install oracle/node-oracledb#v2.0.15 instead of npm install oracledb as this is throwing another error

My $NODE_PATH
/root/projects/oracledb-examples/node_modules

I followed [https://github.com/oracle/node-oracledb/issues/712](url) too but it is not working.

**Comment by dmcghan** [comment]
I can see you're running `node select1.js` command as root. However, the instructions are to close the previously opened terminal and open a new one. This means you'll be the oracle user.

I just edited that doc and made the line you missed **bold**. Hopefully,  that will help others going forward. I also added a new `sed` command to account for a change in the latest version of the driver.

Please open a terminal as oracle and repeat those steps. Let me know how it goes...

**Comment by RayeesMir** [comment]
Thanks it worked

**Comment by ideanb** [comment]
@RayeesMir @dmcghan Can you please clarify how you solve this? thank you!
