### ISSUE TITLE
Set Operating system program name

### ISSUE THREAD

**Issue by kwent** [oracle/node-oracledb#814]
Hi,

Is there any way to set the Operating system program name (`PROGRAM`  field) we see while displaying this table:

https://docs.oracle.com/cd/B19306_01/server.102/b14237/dynviews_2088.htm#REFRN30223

Maybe an option on the connection object ?

Regards

**Comment by cjbj** [comment]
What do you want to set it to?  Are you looking for https://github.com/oracle/node-oracledb/blob/master/doc/api.md#the-add-on-name ?

I don't see a way to set `PROGRAM` via the underlying [OCI](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnoci/toc.htm) interface, and I doubt it is settable by SQL.  It's definitely not settable via node-oracledb 2.0.

**Comment by kwent** [comment]
I think they are different. Maybe it's not configurable and using program name by default...

Below a screenshot of other apps values:

<img width="483" alt="screen shot 2017-12-19 at 2 50 20 pm" src="https://user-images.githubusercontent.com/879780/34182656-06dc591a-e4cc-11e7-9113-a9458d172fd5.png">

Versus

<img width="289" alt="screen shot 2017-12-19 at 2 52 29 pm" src="https://user-images.githubusercontent.com/879780/34182727-51fbda2e-e4cc-11e7-9cf8-a9dc6a45eb96.png">

**Comment by cjbj** [comment]
What do you want to do?

SQL Developer uses Thin JDBC; maybe there is some JDBC hook they have to set the PROGRAM value.

A while back we informally standardized the CLIENT_DRIVER to 'name : version'.  Maybe your screen shot shows old and new versions of JDBC in use?  The new format matches node-oracledb, Python cx_Oracle and [PHP OCI8](https://github.com/php/php-src/blob/b611878bb849fcf8c1707a8163d6a5e2e6cbce74/ext/oci8/php_oci8_int.h#L122). @kubo's [ruby-oci8](https://github.com/kubo/ruby-oci8/blob/7dd76428ebd724f6096151ab1a381bae0752535f/lib/oci8/oci8.rb#L140) adopted it too

**Comment by kwent** [comment]
I want to kill a session opened by my app in a safe way.

Means i want to make sure i select `sid` of the session of `current_username` + `my_program@whatever_client_ip`

**Comment by cjbj** [comment]
That sounds like a good question for [Oracle's AskTOM](https://www.google.com.au/search?q=asktom+killing+user+sessions&oq=asktom+killing+user+sessions).

**Comment by cjbj** [comment]
I like Tom's comment in one of those posts 'If you have to do this thousands of times, you have what I would characterize as a "bug" in your application. '  

Why do you need to kill sessions?

**Comment by kwent** [comment]
Looks like the only (SQL) way to implements `Cancel Query` feature.

**Comment by kubo** [comment]
> Means i want to make sure i select `sid` of the session of `current_username` + `my_program@whatever_client_ip`

How about [connection.clientid](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propconnclientid), which sets `V$SESSION.CLIENT_IDENTIFIER`?
Select `CLIENT_IDENTIFIER` column instead of `PROGRAM`.
