### ISSUE TITLE
How to insert a timestamp ?

### ISSUE THREAD

**Issue by mokeddes** [oracle/node-oracledb#817]
I have a timestamp field. What is the correct SQL code to insert a timestamp into this field?

```
    insert into test (time_of_add_doc) 
       values (to_timestamp('22/12/17 09:00:00','DD/MM/RR HH24:MI:SS');
```
(1) One row Added success !

I want to do this from server NodeJS after connecting to my database (Success) 
         
```javascript
 oracledb.getConnection({
        user: 'ctrm',
        password: 'ctrm',
        connectString: "localhost/sig"
      },
      function (err, connection) {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log('Connection was successful!'); //Get Connection success
    
    

   

     connection.execute(      
    
    
        "INSERT INTO test VALUES (:time_of_add_doc)", {
        time_of_add_doc: ('22/12/17 09:00:00','DD/MM/RR HH24:MI:SS'),
        },
        function (err, result) {
          if (err)
            console.error(err.message);
          else
          console.log("Rows inserted " + result.rowsAffected);
      });
    
```

**Comment by mokeddes** [comment]
Oracle's expecting a date and you seem to be passing an array into a single bind variable. Construct a date in node and then bind that. Ensure that the datatypes on both sides are correct and let the interface between Oracle and node apply the standard translation when required
```javascript
    var time_of_add_doc = new Date(2017, 12, 22, 0, 0, 0, 0)
    
    connection.execute(      
    
    
        "INSERT INTO test VALUES (:time_of_add_doc)", {
        time_of_add_doc,
        },
        function (err, result) {
          if (err)
            console.error(err.message);
          else
          console.log("Rows inserted " + result.rowsAffected);
      });
```

You have a trailing comma after `time_of_add_doc: ('22/12/17 09:00:00','DD/MM/RR HH24:MI:SS'),`. I've left it in, but it seems very strange. I can't test to ensure that this is correct at the moment

**Comment by dmcghan** [comment]
@mokeddes Be aware that the timezone of your Node.js server and the database session may not be in sync. You can explicitly set the timezone the default for database sessions via the environment variable ORA_SDTZ. Read more here: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-9163-fetching-dates-and-timestamps
