### ISSUE TITLE
If conn.execute takes more than 15 seconds, how to time out and release connection?

### ISSUE THREAD

**Issue by VenPot** [oracle/node-oracledb#819]
Hi,If conn.execute takes more than 15 seconds, I want to time out and release connection. Is there a setting we can pass?
Thank you for your time!

**Comment by danilohgds** [comment]
Hi VenPot,
There is a setup for queued requests timeout which can be found here: 
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbqueuetimeout

Furthermore if your request is taking 15 seconds to execute, rather than 15 seconds to acquire the connection itself, you should look into ways of tweaking your logic so it becomes faster, there is no way u can achieve such timing control, unless you go into more user specific session attributes that are managed by dbas and system dbas alike..

Nonetheless, please refer to the documentation for cases like this, it will have everything you need, or at least most things :)

**Comment by VenPot** [comment]
Thank you for your time.I noticed the queued request time out but that
didn't fit my use case. When the query takes longer than 15 seconds I can
send a failed response to the user but the query would still be running on
the DB. If it's taking more than 15 sec, I want to cancel or kill the
query. I am sure some one would have run into this scenario and wanted to
know how they handled it either using node oracled db options or by another
means.

**Comment by dmcghan** [comment]
@VenPot The queue timeout refers to how long a request to get a connection will wait (provided all connections in the pool are currently being used) before returning an error.

You could implement a solution for what you need using the [`break`](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-421-connectionbreak) method. Here's an example...

Given the following procedure:
```sql
-- requires execute on dbms_lock

create or replace procedure wait_for_seconds(
  p_seconds in number
)
  return number
is
begin
  dbms_lock.sleep(p_seconds);
end;
```

The following should work:
```javascript
const oracledb = require('oracledb');
const config = require('./dbConfig.js');

async function runTest() {
  let conn;

  try {
    conn = await oracledb.getConnection(config);

    timeout = setTimeout(async () => {
      console.log('Timeout expired, invoking break');

      try {
        // break is async so it might throw an exception, best to wrap with try/catch
        await conn.break();

        console.log('Break finished without error');
      } catch (err) {
        console.log('Break finished with error', err);
      }
    }, 5000);

    console.log('Starting call to 10 second procedure, wait 5 seconds for break');

    await conn.execute(`begin wait_for_seconds(10); end;`);

    console.log('We should never get here because an error is thrown after the break');
  } catch (err) {
    console.error('We get here after catching the error', err);
  } finally {
    console.log('Now we close the connection because it\'s still open');

    if (conn) {
      console.log('Closing connection');

      try {
        await conn.close();
      } catch (err) {
        console.error('Error closing connection', err);
      }

      console.log('Connection closed');
    }
  }
}

runTest();
```

Unfortunately, `break` doesn't currently work on Mac, but it should work fine on Linux and Windows (where it matters most).

You could also look into using Oracle Workspace Manager: https://docs.oracle.com/database/121/ADMIN/dbrm.htm#ADMIN11841

**Comment by cjbj** [comment]
The preferred method of timing out connections is to configure Oracle Net settings like `SQLNET.OUTBOUND_CONNECT_TIMEOUT`.  You may possibly need to tune your network timeout settings, too.  See https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionha
