### ISSUE TITLE
Getting 'error: no error' when requiring 'oracledb'

### ISSUE THREAD

**Issue by JHereu** [oracle/node-oracledb#82]
I am working on a Sails app that manages an Oracle database via oracledb node module.
I've already tested the server in localhost on Ubuntu 14.04 (x64) and Windows 7 (x64) and works fine with a remote Oracle database.

Problem comes when I install this same node app on a Windows 2008 R2 (x64) machine, where the Oracle database is hosted. App is launched fine but when it comes to require the oracledb module, right in this exact command:

    var oracledb = require('oracledb');

I get the following error:

    no errorC:\*PATH TO PROJECT*\node_modules\oracledb\build\Release\oracledb.node

So, it means the error.message is "no error". How is that? Is node building the adapter module wrongly? Any ideas?

Thanks.

**Comment by cjbj** [comment]
The string 'no error' doesn't occur in the node-oracledb source code.
Triple check the environment that app is invoked under e.g. is PATH OK?   Try to avoid having multiple versions of Oracle around - on Windows this is a common source of error.  Are other modules (that are installed where oracledb is installed) usable in the app?

**Comment by JHereu** [comment]
Yes, there are other modules and there is no problem invokating them. I have to say, though, they are no connection ones (such as Winston).

I had some trouble building the oracle module on Windows, as many people had, judging by the posts on issues and forums. So i tried running a version built by Win 7 on my Win 2008 (and another one in Ubuntu) , so maybe there is the problem. 

Next thing, I will try to build the module on the Win 2008 itself. I will post the results once done. 

Thanks for answering.

**Comment by cjbj** [comment]
@JHereu did you identify a cause?

**Comment by JHereu** [comment]
Yes, I did. I finally managed to generate some new binaries on another Win 2008 R2. It was all about the architecture and some VS Redistributable packages I was somehow missing. But it is still weird the error had any message at all...

Anyway, problem is already solved. Thanks for your attention!

**Comment by cjbj** [comment]
@JHereu Thanks for noting the cause.
