### ISSUE TITLE
Support for connecting to specific oracle editions (edition based redefinition)

### ISSUE THREAD

**Issue by mullerpaul** [oracle/node-oracledb#820]
Is there a way in oreacledb to connect to a specific oracle "edition"?  I'd like to use the oracle database feature of "Edition Based Redefinition" (EBR) to upgrade database objects without application downtime and this requires each database session use a specific "edition".  

In JDBC, this is possible by setting the parameter CONNECTION_PROPERTY_EDITION_NAME.  Its also possible with an ALTER SESSION command after connecting; but I am hoping that there is some parameter somewhere that allows me to specify the edition when I create the connection.

    [oracle@vbgeneric oracle_ebr_demo (master)]$ node version.js 
    Run at: Tue Jan 02 2018 14:40:28 GMT-0500 (EST)
    Node.js version: v8.9.3 (linux x64)
    Node-oracledb text format: 2.0.15
    Oracle Client library text format: 12.2.0.1.0
    Oracle Database text format: 12.2.0.1.0

**Comment by anthony-tuininga** [comment]
This is not currently implemented. I'll let @cjbj respond indicating where this fits in the long list of enhancements we would like to implement!

**Comment by cjbj** [comment]
It's on the 'todo' list, but you're the first person I recall actually asking for it.

**Comment by abrar-khan007** [comment]
really  isn't this amazing

**Comment by abrar-khan007** [comment]
i need much more

**Comment by cjbj** [comment]
@abrar-khan007 use the `ALTER SESSION` solution in the meantime.  Or submit a [pull request](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md)!

**Comment by mullerpaul** [comment]
thanks all

**Comment by cjbj** [comment]
Node-oracledb 2.2 has a new '[edition](https://oracle.github.io/node-oracledb/doc/api.html#propdbedition)' property so you no longer need to use ALTER SESSION or ORA_EDITION.

**Comment by mullerpaul** [comment]
Great!  I'll check it out.  Thanks again for the feedback!
