### ISSUE TITLE
problem to execute : npm install oracle/node-oracledb.git#v2.0.15

### ISSUE THREAD

**Issue by kalima26** [oracle/node-oracledb#821]
in executing this line  :
     npm install oracle/node-oracledb.git#v2.0.15
i have this error:
 Error: Command failed: git -c core.longpaths=true config -get remote.origin.url

environement :  windows 7
                           32 bits

**Comment by cjbj** [comment]
Check the install pre-requisites: for this method you need git.  

From the [instructions](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin):

> If you have the git utility, you can install with:
> 
> `npm install oracle/node-oracledb.git#v2.0.15`
>
> Otherwise install using:
> 
> `npm install https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-src-2.0.15.tgz`
