### ISSUE TITLE
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 6.2.1 (linux, x64)

### ISSUE THREAD

**Issue by ranjitsingh2k6** [oracle/node-oracledb#827]
Getting the below error when i packaged my node js modules from mac and copied to linux machine.... I am able to run successfully on windows.

 Cannot load /app/sp/application/node_modules/oracledb/build/Release/oracledb.node /app/sp/application/node_modules/oracledb/build/Release/oracledb.node: **invalid ELF header Node**-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig. If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

**Comment by dmcghan** [comment]
@ranjitsingh2k6 Only pure JavaScript modules can be moved around like that. Modules that compile to binaries (such as node-oracledb) are platform specific - the resulting binary can only be used on that platform.

**Comment by ranjitsingh2k6** [comment]
That’s bad... it means I need to do npm install on all platforms...I work on windows... We don’t have npm installed on Linux boxes... other devs work on Mac... and Dev box are on different Linux version than test and productions...

**Comment by dmcghan** [comment]
Sounds like you need Docker. 👀

**Comment by cjbj** [comment]
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#3122-manually-extracting-pre-built-binaries shows a way of installing without npm.  But overall, I would suggest you revisit your processes and make sure that npm is available to all developers and to the users who bundle your app for produciton.

**Comment by ranjitsingh2k6** [comment]
@cjbj - Thanks for your suggestion... I am going to try that

**Comment by ranjitsingh2k6** [comment]
@cjbj- Thanks and it worked as well... you rock...
