### ISSUE TITLE
Unable to build on node 0.12.2 (Was previously successful) on Windows

### ISSUE THREAD

**Issue by delaneyj** [oracle/node-oracledb#83]
Have 2 machines at the office and one is not able to build the oracledb source.   However the other does it fine (vs2013, no issues).  Testing at home tonight seems to shed some light on the problem.  With a 0.10.* release of node.js it worked fine, once I updated to 0.12.2 it began getting the following error.  All machines are 64bit with the correct redistribution packages installed.

Even though `OCI_LIB_DIR` environment variable is being sent I'm getting a `gyp: Undefined variable oci_lib_dir in binding.gyp while trying to load binding.gyp` error in the build.

I know the other non-working machine at the office is on 0.12.2.  Can someone please verify this is an issue outside of my environment?

**Comment by delaneyj** [comment]
Sorry I didn't see the `package.json` node version limitations.  Is there a timeline for node 0.12.* support?

**Comment by cjbj** [comment]
I can't give timelines - there are too many variables.  You can follow progress in https://github.com/oracle/node-oracledb/issues/2
