### ISSUE TITLE
not able to install node-oracledb on azure cloud 

### ISSUE THREAD

**Issue by himanshushukla254** [oracle/node-oracledb#834]
I am building a web app using azure services.
For that i need to connect to oracle DB deployed on another remote server.

OS Details : System Windows_NT 10.0.14393
I set platform as 64 bit.
Python as 2.7
Visual Studio Version : 2015
Node version : 6.11.1
npm : 3.4.0

after running `npm install oracledb`
In installation i am getting following error.

oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.15-node-v48-win32-ia32.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-v2.0.15-node-v48-win32-ia32.gz failed with code 404
oracledb ERR! If the error is not network or filesystem related, then review 
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and
oracledb ERR! then install from source code with: npm install oracle/node-oracledb.git#v2.0.15
oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Any help ?

**Comment by dmcghan** [comment]
@himanshushukla254 Are you sure it's 64 bit? The "ia32" on the end of the URL (which comes from [process.arch](https://nodejs.org/api/process.html#process_process_arch)) seems to indicate that it's not.

**Comment by himanshushukla254** [comment]
![screenshot 23](https://user-images.githubusercontent.com/15158684/35229933-ad523158-ffba-11e7-9a10-ef9925e845b3.png)

Check this image @dmcghan , i selected 64 bit here.

**Comment by cjbj** [comment]
@himanshushukla254 Maybe you ended up with a 32 bit Node.js on a 64 bit platform?  Or maybe that checkbox only lets you select 32-bit or 64-bit Python - I don't know?

The pre-built node-oracledb binaries are only for 64-bit Windows.  Your options are to compile node-oracledb yourself (see [INSTALL](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)) or work out how to install a 64-bit Node.js.
