### ISSUE TITLE
ORA-06502: PL/SQL: numeric or value error

### ISSUE THREAD

**Issue by a2441918** [oracle/node-oracledb#835]
Hi I am trying to get data from a procedure. For displaying I get 10,20 or 50 records at a time which is no issue. I also have a case where I need to export the whole resultSet to an excel file to be downloaded.

When I try to pass in that information and the procedure returns data, I get ORA-24817 error.

Please help. 

Below is my code.

>     
    router.put('/get-data/', jsonParser, function (req, res) {
    var data = req.body;

    logger.info("Begin: " + (new Date().toString()));

    pool.getConnection(function (err, connection) {
        logger.info("Begin Connection: " + (new Date().toString()));
        if (err) {
            logger.error(err.message);
            return;
        }

        var bindvars = {
            userName: data.userName,
            filterText: data.appId,
            sortCol: data.sortCol,
            numRows: data.numRows,
            startRow: data.startRow,
            resultSet: {dir: oracledb.BIND_OUT, type: oracledb.STRING, maxSize: 1073741822},
            error: {dir: oracledb.BIND_OUT, type: oracledb.STRING, maxSize: 4000}
        };

        console.log(bindvars);

        logger.info("Bindvars Set: " + (new Date().toString()));
        logger.info('***********************************');
        logger.info('Get Data - PUT');
        logger.info('User Name: ', bindvars.userName);
        logger.info('Filter Text: ', bindvars.filterText);
        logger.info('Sort: ', bindvars.sortCol);
        logger.info('Page Length: ', bindvars.numRows);
        logger.info('Start Row: ', bindvars.startRow);
        logger.info('***********************************');

        logger.info("Begin execute: " + (new Date().toString()));

        //PL/SQL function syntax
        connection.execute(
            "BEGIN procedure(:userName, :filterText, :sortCol, :numRows, :startRow, :resultSet, :error); END;",
            bindvars,
            function (err, result) {
                logger.info("End execute: " + (new Date().toString()));
                if (err) {
                    logger.error(err.message);
                    doRelease(connection);
                    return;
                }

                logger.info("Send JSON: " + (new Date().toString()));
                console.log(result);
                res.send(result.outBinds.resultSet);
                logger.info("JSON Sent: " + (new Date().toString()));

                doRelease(connection);
            });
    });
    });

My bindvars is as follows:

        { 
        userName: 'Arun',
        filterText: '',
        sortCol: 'application_name',
        numRows: 3407,
        startRow: 0,
        resultSet: { dir: 3003, type: 2001, maxSize: 32767 },
        error: { dir: 3003, type: 2001, maxSize: 4000 } 
    }

I get the same error even when I try to fetch 200 rows. I increased the memorySize in bindvars to 400000 and tried fetching 3500 rows, I got "NJS-016: buffer is too small for OUT binds". It is now cool with 1000000 size.  I know its a memory issue with the resultSet and I can fix it by increasing the memory. But how do I handle large resultSets where I am not sure about the memory it will consume?

Please advice.

**Comment by dmcghan** [comment]
@a2441918 You are sending `res.send(result);` as though it's a set of rows. It is not. It's an object that allows you to fetch rows in small amounts to avoid memory issues - which is what you're asking about.

Have you read the doc on ResultSets?
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsethandling

Also, see the doc on Query Streams too:
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-913-query-streaming

**Comment by a2441918** [comment]
Sorry Dan. I am using res.send(result.outBinds.resultSet) and I still get the same error.

**Comment by dmcghan** [comment]
@a2441918 That's no different really. Have you read the doc/links I provided?

**Comment by a2441918** [comment]
I did. The database returns me a resultSet. I was thinking to queryStream the resultSet but I get an error resultSet.toQueryStream is not a function. Googling around for solutions.

**Comment by a2441918** [comment]
Can toQuerySteam() applied to only type: oracledb.CURSOR and not to strings? Examples I see are only for cursors.

**Comment by dmcghan** [comment]
Why would you want to make a string a stream? Looking back at your example, you have: `res.send(result.outBinds.resultSet);`. Now that you read the doc on result sets, do you see what's wrong with this?

**Comment by a2441918** [comment]
Yes. I am already getting the data as a resultSet.

**Comment by dmcghan** [comment]
So everything is good now?

**Comment by a2441918** [comment]
Yes Dan. Thank you so much.

**Comment by cjbj** [comment]
> Any way to keep maxSize dynamic?

Although I'm not sure you are using maxSize in the right place, if you are, then the short answer is No.  A longer answer is also No since the driver needs to allocate memory before it sends messages to the database.  I won't get into even longer answers involving rewriting node-oracledb, the impacts on performance, scalability, usability benefits etc etc.

**Comment by cjbj** [comment]
This issue seems to have concluded; I'll close it.
