### ISSUE TITLE
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA

### ISSUE THREAD

**Issue by t0rkh** [oracle/node-oracledb#838]
Hey guys,
I'm facing the problem every time I want to open a connection to a database ( same for full connection string, tnsnames.ora entry or ezconnectstring):
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA

I was getting it to work when I was setting "export TWO_TASK=//server:1521/SERVICE_NAME" but then I only was able to connect to THIS server and not to another one.
Connecting to the db via PHP and full connection string works like a charm.

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
v9.4.0 (linux x64)

2. What is your node-oracledb version?
2.0.15

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
1102000400, 64-bit, /opt/oracle/instantclient_11_2

4. What is your Oracle Database version?
11.2

5. What is your OS and version?
Debian 9 64-bit

6. What is your compiler version?  For example, with GCC, run `gcc --version`
gcc (Debian 6.3.0-18) 6.3.0 20170516

7. What Oracle environment variables did you set?  How *exactly* did you set them?
~/.profile
export LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2
export ORACLE_HOME=/opt/oracle/instantclient_11_2
export TNS_ADMIN=/opt/oracle/instantclient_11_2/network/admin

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
/opt/oracle/instantclient_11_2

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
connection

10. What error(s) you are seeing?
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA

**Comment by t0rkh** [comment]
Found the solution. I was using connectionString instead of connectString.
Sorry for my dumbness, haha.

**Comment by cjbj** [comment]
Common issue; the next release will accept both attributes, see https://github.com/oracle/node-oracledb/issues/703#issuecomment-304199231 to help.

**Comment by abrar-khan007** [comment]
Ok is this necessary to share code

On Mon, Jan 29, 2018 at 3:39 AM, Christopher Jones <notifications@github.com
