### ISSUE TITLE
Windows 7 Compile Errors oracledb node

### ISSUE THREAD

**Issue by notifyanand** [oracle/node-oracledb#84]
error C2270: '_errno' : modifiers not allowed on nonmember functions (..\src\njs\src\njsOracle.cpp) [C:\Users\abc\node_modules\oracledb\build\oracledb.vcxproj]

There are several compile errors

 error C2504: 'ObjectWrap' : base class undefined

error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\njs\src\njsOracle.cpp) [

Node version v0.12.2
MS Visual Studio 2012 Professional
Python 2.7.9

**Comment by delaneyj** [comment]
Think this is tied to my issue #83 that I added last night, try in node 0.10.*

**Comment by notifyanand** [comment]
Thanks for the quick response. I downgraded node to v0.10.38. Compile seems to proceed further. Only to fail in linking.

dpiEnvImpl.obj : error LNK2001: unresolved external symbol _OCIHandleFree

several of them

dpiDateTimeArrayImpl.obj : error LNK2001: unresolved external symbol _OCIDescriptorAlloc

C:\Users\abc\node_modules\oracledb\build\Release\oracledb.node : fatal error LNK1120: 32 unresolved externals [C:\Users\abc\node_modules\oracledb\build\oracledb.vcxproj]

Let me know if you want me to downgrade to any specific version of node.

Here are the environment variables I set before firing the install.

> npm config set python C:\Python27\python.exe
> "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\amd64\vcvars64.bat"
> npm config set oci_lib_dir C:\oracle\instantclient\sdk\lib\msvc
> npm config set oci_inc_dir C:\oracle\instantclient\sdk\include
> npm config set msvs_version 2012 --global
> npm install --verbose oracledb

**Comment by notifyanand** [comment]
Wondering if it has to do with the 32  bit version of node. Where can I get the 64 bit version of 0.10.* node ? I am looking through this directory now http://nodejs.org/dist/

**Comment by notifyanand** [comment]
got it. http://nodejs.org/dist/v0.10.38/x64/
Will post results.

**Comment by notifyanand** [comment]
Compiled good. Here are results.  Thanks for the help. It would be interesting to see why the compile failed in later version of node.

    18 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.71
gyp info ok
npm verb unsafe-perm in lifecycle true
npm info postinstall oracledb@0.4.2
oracledb@0.4.2 node_modules\oracledb
npm verb exit [ 0, true ]
npm info ok
