### ISSUE TITLE
Unable to do npm install for oracledb in Windows 7

### ISSUE THREAD

**Issue by PalanivelKrishnan** [oracle/node-oracledb#841]
Getting npm error on installing the oracledb in windows machine

Node.js version = v6.10.1
NPM Version = 3.10.10

Error details are below

pm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oracledb@2.0.15 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.0.15 install script 'node package/oracledbinst
all.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node package/oracledbinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pk812841\AppData\Roaming\npm\npm-debug.log
[npm-debug.log](https://github.com/oracle/node-oracledb/files/1681028/npm-debug.log)

**Comment by cjbj** [comment]
Can you try `set NODE_ORACLEDB_TRACE_INSTALL=TRUE` in the terminal windows before you run the `npm install`?

**Comment by PalanivelKrishnan** [comment]
Tried with the above command .but still the same error

**Comment by cjbj** [comment]
The log doesn't have much to go on:
```
260 verbose stack Error: oracledb@2.0.15 install: `node package/oracledbinstall.js`
260 verbose stack Exit status 87
```
Can you check your Node is OK?   Do you need admin privs?

**Comment by PalanivelKrishnan** [comment]
I a in the process of upgrading the node.js. will comeback shortly with updates

**Comment by PalanivelKrishnan** [comment]
Hi I have upgraded the node js still getting the same error. It looks like the binary in not available for 
[2018-02-01T11_28_59_972Z-debug.log](https://github.com/oracle/node-oracledb/files/1685327/2018-02-01T11_28_59_972Z-debug.log)

**Comment by cjbj** [comment]
@PalanivelKrishnan you are not getting errors that would lead me to guess that.  But you haven't given much detail:
- are you using 64 bit Node?
- do you have more than one version of Node installed?
- have you upgraded npm? 
etc etc.

Try these steps and see what happens: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#3122-manually-extracting-pre-built-binaries

**Comment by PalanivelKrishnan** [comment]
System Os - 64bit
Uninstalled the old Node.js 6 and installed node.js 9
using the existing npm package installed alongwith node.js 9
Installed the ORacle client 12.1
Installed python2.7
Installed Visual c++ 2015 redistributable package

Doing the npm install as admin only

Any other info needed

**Comment by PalanivelKrishnan** [comment]
Manually extracting oracledb-v2.0.15-node-v59-win32-x64.gz file gives only a flat file.
Please refer the screenshot
![extract](https://user-images.githubusercontent.com/35992573/35679999-f96e1482-077e-11e8-8c17-e96dbc2ef649.png)

![image](https://user-images.githubusercontent.com/35992573/35680016-0c4cbbee-077f-11e8-8c19-a37679ad5bd3.png)

**Comment by dmcghan** [comment]
@PalanivelKrishnan You can't manually extract that file. See the section on that page that shows this command: `node extractpackage.js path=oracledb-v2.0.15-node-v57-darwin-x64.gz`

**Comment by PalanivelKrishnan** [comment]
Hi Dan,

Thanks for clarifying i realized the mistake and was successfully able to extract the binary and placed in Release folder

**Comment by dmcghan** [comment]
Does it work?

**Comment by PalanivelKrishnan** [comment]
Yet to check on that As I have dependency with other team on this. Hope it works

**Comment by PalanivelKrishnan** [comment]
Getting the Module not found error

Error: Cannot find module 'oracledb'
   at Function.Module._resolveFilename (module.js:555:15)
   at Function.Module._load (module.js:482:25)
   at Module.require (module.js:604:17)
   at require (internal/module.js:11:18)

Not sure if anything is missing

**Comment by cjbj** [comment]
@PalanivelKrishnan The lack of detail is really frustrating me today. 
Show the screen shot or log of how you installed node-oracledb and where you are running node from. Go to the directory with your .js script, and run `npm root`.  Is there an oracledb subdirectory under it?

**Comment by nigilan** [comment]
@PalanivelKrishnan I have node-oracledb working windows 7 system. Let me tell you my system specifications: 

Please install node version 6.11.2(64 bit). 

Run the following commands. 

        1.1 Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
        1.2 npm install -g npm-windows-upgrade
        1.3 npm-windows-upgrade -p -v latest
        1.4 npm install -g node-gyp@latest
        1.5 npm config set msvs_version 2015 –global
        1.6 npm install --global windows-build-tools

All the above steps need to be successful. Now , your npm version will be 5+. Set all the necessary environment variables as per the official documentation. Then, try to run 'npm install oracledb' inside your project folder.

**Comment by cjbj** [comment]
@nigilan Now that pre-built binaries are available on Windows, do you actually need windows-build-tools?  I didn't install it when I was testing.  The fewer 3rd party components, the better!

**Comment by PalanivelKrishnan** [comment]
Hi All,

Thanks for the support.
I did the fresh installation of all the softwares as per the documentation and was able to configure the oracle db connection with node.js
Scripts are working fine and the db queries are working.

I observed that multiple version installation and uninstallation of same softwares had an impact

Thanks,
Palanivel

**Comment by nigilan** [comment]
@cjbj I agree.  We will switch to pre-built binaries. Just curious, if I upgrade node version, will it still work the same way?

**Comment by cjbj** [comment]
@PalanivelKrishnan  I'm glad you got it going.

@nigilan There are pre-built binaries for Node 4, 6, 8 & 9 on Windows 64-bit.
