### ISSUE TITLE
Unable to install oracledb v2.0.15 on Node 8.9.x  ( Azure )

### ISSUE THREAD

**Issue by rohit-khanna** [oracle/node-oracledb#844]
I am trying host an API app - nodejs+oracledb, onto MS Azure.

**Azure node: v8.9.4
node-oracledb- v2.0.15
Hosting Environment: MS Azure**

On initial Deployment with just specifying oracledb in package.json:
**i got error:**
oracledb Beginning installation
remote: oracledb Verifying installation
remote: oracledb Binary not found
remote: oracledb Continuing installation
remote: oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.15-node-v48-win32-ia32.gz
remote: oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-v2.0.15-node-v48-win32-ia32.gz failed with code 404
remote: oracledb ERR! If the error is not network or filesystem related, then review
remote: oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and
remote: oracledb ERR! then install from source code with: npm install oracle/node-oracledb.git#v2.0.1
remote: oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

after reading some solutions here: 

1. 

. I tried manually installing oracledb with command: 
"npm install oracledb"  on ApplicationPreview -Console for my API App.
**Error Logs:**
oracledb@2.0.15 install D:\home\site\wwwroot\node_modules\oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Binary not found
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.15-node-v57-win32-ia32.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-v2.0.15-node-v57-win32-ia32.gz failed with code 404
oracledb ERR! If the error is not network or filesystem related, then review 
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and
oracledb ERR! then install from source code with: npm install oracle/node-oracledb.git#v2.0.15
oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md 

2.

. I tried manually installing oracledb with command: 
"npm install oracle/node-oracledb#v2.0.15"  on ApplicationPreview -Console for my API App.
**Error Logs:**
oracledb@2.0.15 install D:\home\site\wwwroot\node_modules\oracledb
> node-gyp rebuild

D:\home\site\wwwroot\node_modules\oracledb>if not defined npm_config_node_gyp (node "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\home\site\wwwroot\node_modules\oracledb\build\oracledb.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error 
gyp ERR! stack Error: `D:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\8.9.3\\node.exe" "D:\\Program Files (x86)\\npm\\5.6.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\site\wwwroot\node_modules\oracledb
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Do i need to install anything else to make it work on AZURE?

**Comment by cjbj** [comment]
The ia32 looks like an Itanium architecture.  Prebuilt binaries are only available for x64.  If you don't have access to x64, you could try compiling the driver from source code, see INSTALL.md.

Also see #834.

**Comment by cjbj** [comment]
@rohit-khanna Excuse the rushed answer earlier. Of course, if I've had a solution I would have posted it.  Maybe something like windows-build-tools will help?
