### ISSUE TITLE
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and

### ISSUE THREAD

**Issue by marcogorak** [oracle/node-oracledb#845]
Hello, I need the help.

I'm trying to install the oracledb module in my project but it returns error stating that dependency python 2.7 is not installed, but this dependency is installed including Visual Studio 2017, below follows the details of the error and the npm logs

C:\Users\XXXXXXXXX\Documents\teste>npm install oracledb
> oracledb@2.0.15 install C:\Users\ms67880\Documents\teste\node_modules\oracledb
> node package/oracledbinstall.js
oracledb Beginning installation
oracledb Verifying installation
oracledb Binary not found
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.15-node-v57-win32-x64.gz
oracledb ERR! read ECONNRESET
oracledb ERR! If the error is not network or filesystem related, then review
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and
oracledb ERR! then install from source code with: npm install oracle/node-oracledb.git#v2.0.15
oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

npm WARN teste@1.0.0 No description
npm WARN teste@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.0.15 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXXXX\AppData\Roaming\npm-cache\_logs\2018-02-14T11_55_04_554Z-debug.log

Details of machine:
Windows 10 64bits
C:\Users\XXXXXXX\Documents\teste>node -v
v8.9.4
Visual Studio 2017 installed 
Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)] on win32

=================================================================================

C:\Users\XXXXXX\AppData\Roaming\npm-cache\_logs\2018-02-14T11_55_04_554Z-debug.log

11230 silly doSerial move 2200
11231 silly doSerial finalize 2200
11232 silly finalize C:\Users\ms67880\Documents\teste\node_modules\oracledb
11233 silly doParallel refresh-package-json 2200
11234 silly refresh-package-json C:\Users\ms67880\Documents\teste\node_modules\oracledb
11235 silly doParallel preinstall 2200
11236 silly preinstall oracledb@2.0.15
11237 info lifecycle oracledb@2.0.15~preinstall: oracledb@2.0.15
11238 silly doSerial build 2200
11239 silly build oracledb@2.0.15
11240 info linkStuff oracledb@2.0.15
11241 silly linkStuff oracledb@2.0.15 has C:\Users\ms67880\Documents\teste\node_modules as its parent node_modules
11242 verbose linkBins oracledb@2.0.15
11243 verbose linkMans oracledb@2.0.15
11244 silly doSerial global-link 2200
11245 silly doParallel update-linked 2200
11246 silly doSerial install 2200
11247 silly install oracledb@2.0.15
11248 info lifecycle oracledb@2.0.15~install: oracledb@2.0.15
11249 verbose lifecycle oracledb@2.0.15~install: unsafe-perm in lifecycle true
11250 verbose lifecycle oracledb@2.0.15~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\ms67880\Documents\teste\node_modules\oracledb\node_modules\.bin;C:\Users\ms67880\Documents\teste\node_modules\.bin;C:\Oracle\product\11.2.0\client_2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\sybase\JS-12_5\bin;C:\sybase\ADO.NET\dll;C:\sybase\OLEDB;C:\sybase\ODBC;C:\sybase\OCS-12_5\lib3p;C:\sybase\OCS-12_5\dll;C:\sybase\OCS-12_5\bin;C:\ProgramData\Oracle\Java\javapath;C:\oracle\product\11.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Python27;C:\Users\ms67880\AppData\Roaming\npm\
11251 verbose lifecycle oracledb@2.0.15~install: CWD: C:\Users\ms67880\Documents\teste\node_modules\oracledb
11252 silly lifecycle oracledb@2.0.15~install: Args: [ '/d /s /c', 'node package/oracledbinstall.js' ]
11253 silly lifecycle oracledb@2.0.15~install: Returned: code: 87  signal: null
11254 info lifecycle oracledb@2.0.15~install: Failed to exec install script
11255 verbose unlock done using C:\Users\ms67880\AppData\Roaming\npm-cache\_locks\staging-bff9aafe1cb0ae12.lock for C:\Users\ms67880\Documents\teste\node_modules\.staging
11256 silly saveTree teste@1.0.0
11256 silly saveTree `-- oracledb@2.0.15
11257 warn teste@1.0.0 No description
11258 warn teste@1.0.0 No repository field.
11259 verbose stack Error: oracledb@2.0.15 install: `node package/oracledbinstall.js`
11259 verbose stack Exit status 87
11259 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
11259 verbose stack     at emitTwo (events.js:126:13)
11259 verbose stack     at EventEmitter.emit (events.js:214:7)
11259 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
11259 verbose stack     at emitTwo (events.js:126:13)
11259 verbose stack     at ChildProcess.emit (events.js:214:7)
11259 verbose stack     at maybeClose (internal/child_process.js:925:16)
11259 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
11260 verbose pkgid oracledb@2.0.15
11261 verbose cwd C:\Users\ms67880\Documents\teste
11262 verbose Windows_NT 10.0.10240
11263 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
11264 verbose node v8.9.4
11265 verbose npm  v5.6.0
11266 error code ELIFECYCLE
11267 error errno 87
11268 error oracledb@2.0.15 install: `node package/oracledbinstall.js`
11268 error Exit status 87
11269 error Failed at the oracledb@2.0.15 install script.
11269 error This is probably not a problem with npm. There is likely additional logging output above.
11270 verbose exit [ 87, true ]

**Comment by cjbj** [comment]
I sense a need to refine those messages.  They don't say Python isn't installed.   But then I helped write the messages so it makes sense to me (suggested improvements are welcome).

This is your error:

> `oracledb ERR! read ECONNRESET`

You have a network problem.  (So the 'If' and the 'Review' in the messages don't apply to you)

This could be a transient issue: try again.  Or maybe you need a proxy set.

**Comment by cjbj** [comment]
Closing - no feedback.
