### ISSUE TITLE
QueryStream broken in Node 4 and 6 (2.1)

### ISSUE THREAD

**Issue by wubzz** [oracle/node-oracledb#847]
1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from 
64-bit v4.8.7 & v6.13.0

2. What is your node-oracledb version?
Latest

10. What error(s) you are seeing?
> Uncaught TypeError: self.destroy is not a function

After [this](https://github.com/oracle/node-oracledb/commit/3a01f671950329995ffb92dbd16c8eac41be186c#diff-48bf250fbca53854300c4ab366a52e04R72) commit our CI tests over at [knex](https://github.com/tgriesser/knex) started breaking with the above error message. After some digging I realized that `.destroy` was added to `ReadableStream` in node 8+, which means the current version of the lib does not work for Node < 8.

The README states
> Use node-oracledb to connect Node.js **4**, **6**, 8 and 9 to Oracle Database.

**Comment by cjbj** [comment]
Hmm.

**Comment by cjbj** [comment]
@dmcghan and @anthony-tuininga have a fix:

```
diff --git a/lib/querystream.js b/lib/querystream.js
index f1a13a4b..bd412e9a 100644
--- a/lib/querystream.js
+++ b/lib/querystream.js
@@ -69,7 +69,7 @@ function QueryStream(resultSet, oracledb) {
     // Using setImmediate to ensure that end event handlers are processed
     // before the destroy logic is invoked.
     setImmediate(function() {
-      self.destroy();
+      self._destroy(null, function() {});
     });
   });
 }
```

When the world (i.e. the Windows people in the team) wake up and we can get Windows binaries built, we'll push a v2.1.1. 

After Spring holiday is over and everyone is back at work, we'll have a postmortem to work out how this got missed!

**Comment by cjbj** [comment]
I've released 2.1.1.  Give it a whirl!

**Comment by elhigu** [comment]
It works! :) 🎉

**Comment by cjbj** [comment]
@elhigu yay!
