### ISSUE TITLE
Bulk/batch insert in oracle db

### ISSUE THREAD

**Issue by amit-mn** [oracle/node-oracledb#849]
The `connection.batchInsert` taking too much time if I have an array with more than 12,000 items. So batch/bulk insert process with **batchInsert** is not quite good in my case.
Is there any way for bulk insert which support up to 50,000 rows at a time in oracledb?

Thanks,
Amit

**Comment by cjbj** [comment]
See #614

You might want to look at Data Pump or even Python cx_Oracle.

**Comment by cjbj** [comment]
Node-oracledb 2.2 introduces [connection.executeMany()](https://oracle.github.io/node-oracledb/doc/api.html#executemany) (also see [Batch Statement Execution](https://oracle.github.io/node-oracledb/doc/api.html#batchexecution)) making batch data insert more efficient.
