### ISSUE TITLE
No news

### ISSUE THREAD

**Issue by richlim** [oracle/node-oracledb#85]
Hello Folks,
no news since more than a month.
Not even NaN build has been approved.
What about forking off and doing it without Oracle guys?
I cannot imagine there are not a couple of people willing and capable of doing it.

**Comment by cjbj** [comment]
Hi @richlim There's been an annoying pesky bug holding up the code for https://github.com/oracle/node-oracledb/issues/4 This has been really frustrating me.  Coding is also happening on result sets and LOBs - these are bigger projects, of course.  NAN approvals have been progressing; only one more is pending.

**Comment by cjbj** [comment]
@richlim can I close this?  We did release RETURNING INTO support.  Development on the other projects is happening.

**Comment by richlim** [comment]
@cjbj please do it.
Many thanks for you've done until now.
Looking forward for more :)

**Comment by cjbj** [comment]
Thank @richlim
