### ISSUE TITLE
problem installing latest version on macOS 10.12.6

### ISSUE THREAD

**Issue by jgfidelis** [oracle/node-oracledb#853]
My env:

node version: 8.9.0
OS: macOS Sierra 10.12.6
node-gyp: v3.6.2

compiler:
```
jgfidelis$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

my ~/lib:
```
jgfidelis$ ls ~/lib
libclntsh.dylib			libocci.dylib.12.1
libclntsh.dylib.12.1		libociei.dylib
libclntshcore.dylib.12.1	libocijdbc12.dylib
libnnz12.dylib			libons.dylib
libocci.dylib			liboramysql12.dylib
```

I downloaded the basic and sdk .zip and copied everything to a folder I created called `/opt/instaclient_12_1`.
The content is:

```
jgfidelis$ ls /opt/instantclient_12_1/
BASIC_README			libociei.dylib
adrci				libocijdbc12.dylib
genezi				libons.dylib
libclntsh.dylib			liboramysql12.dylib
libclntsh.dylib.12.1		ojdbc8.jar
libclntshcore.dylib.12.1	sdk
libnnz12.dylib			uidrvci
libocci.dylib			xstreams.jar
libocci.dylib.12.1
```

 my env variables:

```
export OCI_HOME=/opt/instantclient_12_1
export OCI_LIB_DIR=$OCI_HOME
export OCI_INC_DIR=$OCI_HOME/sdk/include
```

Problem:
On my `package.json` I have: `"oracledb": "^1.13.1",`

When I run `yarn install` I get the error:
```
[1/7] ⡀ bcrypt: ld: building for OSX, but linking against dylib built f
[2/7] ⡀ oracledb: clang: warning: using sysroot for 'iPhoneSimulator' b
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
error /Users/jgfidelis/Development/Entria/natura-graphql/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/jgfidelis/Development/Entria/natura-graphql/node_modules/bcrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/jgfidelis/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jgfidelis/Development/Entria/natura-graphql/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jgfidelis/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jgfidelis/.node-gyp/8.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jgfidelis/.node-gyp/8.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jgfidelis/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jgfidelis/.node-gyp/8.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jgfidelis/Development/Entria/natura-graphql/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  SOLINK_MODULE(target) Release/bcrypt_lib.node
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/lib/libc++.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/lib/libc++.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jgfidelis/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/jgfidelis/.nvm/versions/node/v8.9.0/bin/node" "/Users/jgfidelis/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jgfidelis/Development/Entria/natura-graphql/node_modules/bcrypt
gyp ERR! node -v v8.9.0
```

Is it something with my gcc? Thanks

**Comment by jgfidelis** [comment]
Update:

bcrypt 1.0.3 does not compile anything anymore, but downloads binaries from remote. Once I added to my package.json:
```
"resolution": {
  "bcrypt-as-promised/bcrypt": "1.0.3"
}

The error now is different, compiling oracle:
```
Directory: /Users/jgfidelis/Development/Entria/natura-graphql/node_modules/oracledb
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@9.4.0 | darwin | x64
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp info spawn args [ '/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jgfidelis/Development/Entria/natura-graphql/node_modules/oracledb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jgfidelis/.node-gyp/9.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jgfidelis/.node-gyp/9.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jgfidelis/Development/Entria/natura-graphql/node_modules/oracledb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../src/njs/src/njsOracle.cpp:53:
In file included from ../src/njs/src/njsOracle.h:56:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../src/njs/src/njsPool.cpp:55:
In file included from ../src/njs/src/njsOracle.h:56:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../src/njs/src/njsConnection.cpp:52:
In file included from ../src/njs/src/njsConnection.h:59:
In file included from ../src/njs/src/njsUtils.h:57:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsResultSet.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../src/njs/src/njsResultSet.cpp:52:
In file included from ../src/njs/src/njsResultSet.h:56:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
../src/njs/src/njsMessages.cpp:103:22: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
    va_start (vlist, err);
                     ^
../src/njs/src/njsMessages.cpp:94:48: note: parameter of type 'NJSErrorType' is declared here
string NJSMessages::getErrorMsg ( NJSErrorType err, ... )
                                               ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsIntLob.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../src/njs/src/njsIntLob.cpp:66:
In file included from ../src/njs/src/njsIntLob.h:59:
In file included from ../src/njs/src/njsUtils.h:57:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/njs/src/njsIntLob.cpp:1711:3: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
  cleanup();
  ^
2 warnings generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
../src/dpi/src/dpiEnvImpl.cpp:117:3: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
  cleanup();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
../src/dpi/src/dpiConnImpl.cpp:111:3: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
  cleanup();
  ^
../src/dpi/src/dpiConnImpl.cpp:164:3: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
  cleanup ();
  ^
In file included from ../src/dpi/src/dpiConnImpl.cpp:28:
../src/dpi/src/dpiConnImpl.h:194:16: warning: private field 'pingInterval_' is not used [-Wunused-private-field]
  int          pingInterval_;   // Time to elapse before checking for aliveness
               ^
../src/dpi/src/dpiConnImpl.h:195:17: warning: private field 'lasttick_' is not used [-Wunused-private-field]
  long         *lasttick_;      // next ping time if time elapsed.
                ^
4 warnings generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
../src/dpi/src/dpiPoolImpl.cpp:154:3: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
  cleanup();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
../src/dpi/src/dpiStmtImpl.cpp:120:3: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
  cleanup ();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiLob.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiCommon.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  SOLINK_MODULE(target) Release/oracledb.node
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/lib/libc++.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/lib/libc++.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/oracledb.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/jgfidelis/.nvm/versions/node/v9.4.0/bin/node" "/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jgfidelis/Development/Entria/natura-graphql/node_modules/oracledb
gyp ERR! node -v v9.4.0
```

PS: I switched to node 9.4, if that is a problem, let me know

**Comment by anthony-tuininga** [comment]
Is there a reason you are still using node-oracledb 1.13.1? That's not the latest version any longer! The latest version is now 2.1.1. Its been tested with Node 4,6,8 and 9. Version 1.13.1 was only tested with 4, 6 and 7 -- which may explain the difficulties you are experiencing. Please give 2.1.1 a try. Since 2.1.1 has prebuilt binaries available for you, you won't even have to compile! :-)

**Comment by jgfidelis** [comment]
@anthony-tuininga hey, thanks for the input, firstly.

Secondly, I changed to 2.1.1 on our project and it worked like a charm. Is there any breaking change that we should be aware of?

Thirdly, do you have any idea what was causing this issue? I was having the same issue (`building for OSX, but linking against dylib built for iOS`) in another package, as I mentioned (`bcrypt`). I am the only one in the project having these problems so it must be something to do with my env and I'd rather fix my env then changing packages in a such big project that we have.

Thanks for the help anyway, I will try a bit more to find a solution to my env so we do not have to change anything in the project.

by the way, what is the earliest version with prebuilt binaries available? 2.1, 2.0...?

**Comment by anthony-tuininga** [comment]
> @anthony-tuininga hey, thanks for the input, firstly.

You're welcome.

> Secondly, I changed to 2.1.1 on our project and it worked like a charm. Is there any breaking change that we should be aware of?

Every effort was made to make the change as painless as possible. You can examine the [release notes](https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md) which document the improvements made and all changes. In particular, note the section in the release notes that deals with [changes made since v1](https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md#node-oracledb-v2015-15-dec-2017-changes-since-node-oracledb-version-1). If you notice something that we missed, please log an issue for it!

> Thirdly, do you have any idea what was causing this issue? I was having the same issue (building for OSX, but linking against dylib built for iOS) in another package, as I mentioned (bcrypt). I am the only one in the project having these problems so it must be something to do with my env and I'd rather fix my env then changing packages in a such big project that we have.

I don't know what was causing your issue. I don't use macOS much. Perhaps @cjbj has some suggestions since he uses macOS more regularly.

> by the way, what is the earliest version with prebuilt binaries available? 2.1, 2.0...?

The earliest version with pre-built binaries is 2.0.15, but I would strongly suggest the use of 2.1.1 if you are going to upgrade to 2.x.

**Comment by jgfidelis** [comment]
Ok, thanks. I would love the help of anyone more familiar with `node-gyp` and how can I fix my env. Thanks for the help!

**Comment by cjbj** [comment]
You may also want to upgrade [Instant Client to 12.2](http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html) which has the [improved connection pool 'dead session' detection](https://oracle.github.io/node-oracledb/doc/api.html#propdbpoolpinginterval).

I haven't experienced the 'dylib built for iOS' issue, sorry.
