### ISSUE TITLE
CLIENT_IDENTIFIER is not set with version 2.1.1

### ISSUE THREAD

**Issue by ronnn** [oracle/node-oracledb#854]
We are using the `connection.clientId` property to pass a user ID to the database. With version 1.13.1 this is working as expected. However with 2.1.1 the `CLIENT_IDENTIFIER` stays `null`.

I can reproduce the behavior with the endtoend.js example.
See the following. With 2.1.1 I get
![image](https://user-images.githubusercontent.com/927851/36414528-e3082e46-1622-11e8-9196-600b980c3a77.png)

With 1.13.1
![image](https://user-images.githubusercontent.com/927851/36414468-a7252244-1622-11e8-8e39-00a1366e2ce4.png)

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?
v8.9.3 64bit

2. What is your node-oracledb version?
2.1.1 (not working)
1.13.1 (working as expected)

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
instantclient-<basic/sdk>-windows.x64-12.2.0.1.0
C:\dev\programs\instantclient_64

4. What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

5. What is your OS and version?
Windows 7 64bit

**Comment by anthony-tuininga** [comment]
I have confirmed the issue and already have a solution which corrects it. @cjbj can comment on when that will become part of an official release.

**Comment by cjbj** [comment]
@ronnn an interesting little buglet.  Thanks for reporting it. It's fixed in 2.1.2, which I just pushed to npm.

**Comment by ronnn** [comment]
@cjbj @anthony-tuininga Thank you very much for the quick fix! I can confirm, that it's working as expected. :+1:
