### ISSUE TITLE
Portability issue

### ISSUE THREAD

**Issue by kwent** [oracle/node-oracledb#855]
Hi,

- Using node-oracledb **v2.1.1**.
- All platforms impacted.

So i'm trying to build a software with this oracle driver embedded but i'm hitting a portability issue on all platforms:

Backtrace for OSX:

```
/Users/username/Projects/project/node_modules/electron/dist/Electron.app/Contents/Resources/electron.as…:209 Uncaught Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.2.1 (darwin, x64)
Node.js require() error was: 
  DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node.js require() mapped to /Users/username/Projects/project/app/node_modules/oracledb/build/Release/oracledb.node
Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
```

If i do understand well, this cause my target did not install the Instant Client Library in `~lib` or `/user/local/lib` for (OSX). Fair enough.

What are the environment variables i need to set on each OS at
- compilation time
- runtime

If i read [well](https://github.com/oracle/node-oracledb/blob/04ea440e0a4f2a52df57946a07b1cb812a593474/CHANGELOG.md#node-oracledb-v2015-15-dec-2017-changes-since-node-oracledb-version-1), some environment variables cannot be set anymore starting version 2

Not sure how i make portability works... Some guidance is welcome.

Regards

**Comment by cjbj** [comment]
@kwent thanks for persevering with this.  I look forward to hearing how it goes.

In brief, for node-oracledb 2, no environment variables need to be set during build.  At runtime you just need to make sure Oracle client libraries are in the OS library search path.  All the fine print is captured in [INSTALL](https://oracle.github.io/node-oracledb/INSTALL.html).  For example, users may need proxy environment variables set to do the install, as they probably need for all other internet access.

**Comment by kwent** [comment]
Why Oracle client libraries needs to be installed on the target ?

I thought than they were just needed at the compilation to compile `.node` binary file and the only dependency after this was just that `.node` file.

For example, i have no issues with `sqlite3` with is compiled as well and the binary is shipped while packaging and target is happy but target does not install `sqlite3-dev` libraries at any moment...

Regards

**Comment by cjbj** [comment]
- Oracle [doesn't support linking with static libraries.](https://docs.oracle.com/database/121/LADBN/toc.htm#LADBN118)

- The use of dlopen() allows us to distribute node-oracledb binaries that work with various versions of Oracle client libnraries, which in turn lets you decide which client version/patch level to use, which in turn determines which Oracle features you get and which Oracle DB versions you can connect to.

**Comment by kwent** [comment]
Thanks for your answer. Just to confirm again:

There is no way to do like [sqlite3](https://github.com/mapbox/node-sqlite3#source-install) at all at the moment ?

Cf:
```
The sqlite3 module depends only on libsqlite3. However, by default, an internal/bundled copy of sqlite will be built and statically linked, so an externally installed sqlite3 is not required.
```

My other question is why it's not an option ? (even if i loose in flexibility and version/patch are deterministic).

Regards

**Comment by cjbj** [comment]
@kwent you need to dynamically link with Oracle client libraries: this is identical to sqllite3 depending on libsqlite3.

Some folk in the [Go crowd](https://stackoverflow.com/questions/38785691/trying-to-build-static-cgo-executable-with-oracle-libraries-on-linux-ubuntu) has been doing some hacks to build statically, but I can't recommend that, and I'm not going to try it :)
