### ISSUE TITLE
Install fails with 403 behind proxy

### ISSUE THREAD

**Issue by bjouhier** [oracle/node-oracledb#856]
npm install fails while downloading binary behind corporate proxy with the following error:

```
Error: HTTP proxy request for github.com/oracle/node-oracledb/releases/download/v2.1.1/oracledb-v2.1.1-node-v57-linux-x64.gz failed with code 403
```

Error occurs when running npm install from docker behind corporate proxy. NPM install tries to download binary from github but the request is rejected by our proxy.

I reproduced the problem by running the `node package/oracledbinstall.js` directly. I'm getting the same 403 error.

The problem is due to an invalid host header in the request: https://github.com/oracle/node-oracledb/blob/master/package/oracledbinstall.js#L203

I added a colon between hostname and port:
```
        'host': hostname +':' +  PORT,
```
This fixed the problem.

**Comment by anthony-tuininga** [comment]
Nice! Thanks for reporting this. We'll get this corrected.

**Comment by bjouhier** [comment]
When can we expect a fix published to NPM? This is just to know whether I should revert my dependencies to 1.x or wait for the fix.

**Comment by bjouhier** [comment]
Thanks @cjbj. This is speed!

**Comment by janofass** [comment]
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v57-win32-x64.gz
oracledb ERR! unable to get local issuer certificate
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

**Comment by cjbj** [comment]
Note the [install instructions](https://oracle.github.io/node-oracledb/INSTALL.html#363-install-the-add-on) show how to set the proxy via environment variables and say:

> The node-oracledb binary installer cannot use the npm config set https-proxy value.

This is because npm is not doing the download of the binary.

There is a workaround due to land in https://github.com/oracle/node-oracledb/pull/919
