### ISSUE TITLE
pool.getConnection() fails with "NJS-040: connection request timeout" - why? how to recover?

### ISSUE THREAD

**Issue by aprixon01112017** [oracle/node-oracledb#857]
Node v6.11.4
oracledb 2.1.1
Windows 10 64bit
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
PL/SQL Release 11.2.0.1.0 - Production                                      
CORE	11.2.0.1.0	Production                                                  
TNS for 64-bit Windows: Version 11.2.0.1.0 - Production                     
NLSRTL Version 11.2.0.1.0 - Production                                      

------

I am testing a Express-Server with two test clients and at some point pool.getConnection() fails with a "NJS-040: connection request timeout". Some of the DB request take several seconds to complete. Most of the requests are completed much faster.
After getConnection() fails once I don't get any connection anymore until the restart of the express-server.

What may be the reason?
How can I recover?

In the recorded example, directly before the error occurs, 3 connections are in use with a maximum of 6 connections in use before.

`
info: Connections in use (pool.connectionsInUse): 3. Max: 6
error: Cannot get connection from pool
`

The pool statistics when the error occurs are:
`
...total up time (milliseconds): 685412
...total connection requests: 2100
...total requests enqueued: 1
...total requests dequeued: 0
...total requests failed: 0
...total request timeouts: 1
...max queue length: 1
...sum of time in queue (milliseconds): 60
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 0
...avg time in queue (milliseconds): 60
...pool connections in use: 1
...pool connections open: 20
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60
...poolMin: 20
...poolMax: 50
...poolIncrement: 1
...poolTimeout (seconds): 60
...poolPingInterval: 10
...stmtCacheSize: 30
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 4
`
After resuming execution I don't get a successful conection anymore:

`
Pool statistics:
...total up time (milliseconds): 856011
...total connection requests: 2172
...total requests enqueued: 63
...total requests dequeued: 5
...total requests failed: 0
...total request timeouts: 57
...max queue length: 2
...sum of time in queue (milliseconds): 4034
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 30
...avg time in queue (milliseconds): 64
...pool connections in use: 0
...pool connections open: 20
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60
...poolMin: 20
...poolMax: 50
...poolIncrement: 1
...poolTimeout (seconds): 60
...poolPingInterval: 10
...stmtCacheSize: 30
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 4
`
...

`
Pool statistics:
...total up time (milliseconds): 899353
...total connection requests: 2240
...total requests enqueued: 131
...total requests dequeued: 5
...total requests failed: 0
...total request timeouts: 126
...max queue length: 2
...sum of time in queue (milliseconds): 43776
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 30
...avg time in queue (milliseconds): 334
...pool connections in use: 0
...pool connections open: 20
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60
...poolMin: 20
...poolMax: 50
...poolIncrement: 1
...poolTimeout (seconds): 60
...poolPingInterval: 10
...stmtCacheSize: 30
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 4
`

and so on

**Comment by cjbj** [comment]
You say:

> ...pool connections open: 20 
> Related pool attributes:
> ...poolAlias: default
> ...queueRequests: true
> ...queueTimeout (milliseconds): 60
> ...poolMin: 20 ...poolMax: 50

and

> process.env.UV_THREADPOOL_SIZE: 4

Check out https://oracle.github.io/node-oracledb/doc/api.html#numberofthreads

Also, I'd recommend using Instant Client 12.2 (it will connect to 11.2 DB fine) due to the better [pool pinging behavior](https://oracle.github.io/node-oracledb/doc/api.html#propdbpoolpinginterval).

**Comment by aprixon01112017** [comment]
Same with 

`Oracle client library version number is 1202000100`

for these pool stats 

`
warn: IN USE: 2 (Max: 4) / OPEN: 4 (Max: 4)
error: IN USE: 2 (Max: 4) / OPEN: 4 (Max: 4)
error: Cannot get connection from pool: {}

Pool statistics:
...total up time (milliseconds): 93447
...total connection requests: 294
...total requests enqueued: 1
...total requests dequeued: 0
...total requests failed: 0
...total request timeouts: 1
...max queue length: 1
...sum of time in queue (milliseconds): 60
...min time in queue (milliseconds): 0
...max time in queue (milliseconds): 0
...avg time in queue (milliseconds): 60
...pool connections in use: 2
...pool connections open: 4
Related pool attributes:
...poolAlias: default
...queueRequests: true
...queueTimeout (milliseconds): 60
...poolMin: 2
...poolMax: 8
...poolIncrement: 1
...poolTimeout (seconds): 60
...poolPingInterval: 10
...stmtCacheSize: 30
Related environment variables:
...process.env.UV_THREADPOOL_SIZE: 10
`

**Comment by cjbj** [comment]
- triple check you are setting UV_THREADPOOL_SIZE before threads start, otherwise you will still only have 4 threads
- check you are closing connections.
- check for table deadlocks 
- check machine resource limitations

Basically there isn't enough info in your post to narrow down the cause.  Dig in and try and narrow down the problem.
