### ISSUE TITLE
Not found oracledb-v2.0.14-node-v59-win32-ia32.gz when installing oracledb

### ISSUE THREAD

**Issue by KirillSamoylenko** [oracle/node-oracledb#858]
Hi!
I have Windows 7 32 bit, NodeJs  32, InstantClient 32.. all 32..
When installing oracledb i receive this error:
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.14-node-v59-win32-ia32.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.0.14/oracledb-v2.0.14-node-v59-win32-ia32.gz failed with cod
e 404
Whats wrong?

**Comment by cjbj** [comment]
Prebuilt binaries are [only available for x64](https://github.com/oracle/node-oracledb/releases/tag/v2.1.2), not ia32; 

You can compile the driver from source code following https://oracle.github.io/node-oracledb/INSTALL.html. 

Out of interest, why use is32?

PS version 2.1.2 is out.
