### ISSUE TITLE
Trying retrive query result.rows for external function

### ISSUE THREAD

**Issue by marcogorak** [oracle/node-oracledb#859]
Hellow guys, i need help to recovery result.rows to select query in my function.

I'm trying to retrieve a query in my function but object returns as undefined when I run it in my class, but when I put the console.log it returns the query normally.

How do I retrieve the result.rows in my function?

`import oracledb from 'oracledb';
import config from './config';

class ConnectionFactory {
  constructor() {}

  command(sql) {
   oracledb.getConnection(
      {
        user          : config.username,
        password      : config.password,
        connectString : config.host
      })
      .then(connection => {
       
       connection.execute(sql)
          .then(result => {
            //console.log(result.metaData);
            console.log(result.rows);
            connection.close();
          })
          .catch(err => {
            console.log(err.message);
            connection.close();
            return err.message;
          });

      })
      .catch(err => {
        console.error(err.message);
        return err.message;
      });
  }
}

export default ConnectionFactory;`

**Comment by dmcghan** [comment]
@marcogorak Your function is not async, but it needs to be. For example, you could return a promise which is resolved (with the rows) or rejected (with an error) eventually.

Here's a series that covers the common options: https://jsao.io/2017/06/how-to-get-use-and-close-a-db-connection-using-various-async-patterns/

If you go to the bottom of the page you'll find links to other parts in the series.

**Comment by cjbj** [comment]
Closing - no update from filer.
