### ISSUE TITLE
node: symbol lookup error

### ISSUE THREAD

**Issue by jakepens71** [oracle/node-oracledb#86]
The error is:

node: symbol lookup error: <node application directory>/node_modules/node-oracledb/build/release/oracledb.node: undefined symbol: _ZN4node12MakeCallBackEN2v86HandleINSO_60bjectEEENS1_INSO_8FunctionEEEiPNS1_INSO_5ValueEEE

Connection structure I have been trying:

   oracledb.createPool (
   { 
    user : 'user',
    password : 'password',
    connectString : 'IP:PORT/DB_NAME',
    poolMax : 10,
    poolMin : 2,
    poolIncrement : 2,
    poolTimeout : 4
    },
    function(err, pool) {
    console.info(pool);
    if (err) {
    console.error('createPool() callback: ' + err.message);
    return;
    }
    cp = pool;
    pool.getConnection(
    function (err, connection) {
    //console.info(connection);
    if (err) {
    console.error('getConnection() callback: ' + err.message);
    return;
     }

I know the db name, password, and IP are right because I use them all the time. I have also used multiple databases we have and nothing has worked. Also, it is connecting to an Oracle 11g version, I am currently using node 0.10.0 (only thing I could get to work with this oracle.)

**Comment by jakepens71** [comment]
Seems to be fixed if using 0.10.38

**Comment by cjbj** [comment]
I've seen various errors using older Node 0.10 releases.  The package.json file tries to enforce a more recent version: https://github.com/oracle/node-oracledb/blob/master/package.json#L17
