### ISSUE TITLE
How to run script file .sql with multiple statements?

### ISSUE THREAD

**Issue by huynhsamha** [oracle/node-oracledb#860]
## How to run script file sql with multiple statements?
Now I want to run script file with extension .sql, that contain statements such as CREATE TABLE, CREATE SEQUENCE, ALTER TABLE, CREATE TRIGGER, DROP, ... at one time to restart database.

Because `conn.execute()` only execute one statement once time, what is a correct way for my purpose?

Thanks

**Comment by dmcghan** [comment]
@huynhsamha Did you get an answer to your question? There was a similar question here: https://github.com/oracle/node-oracledb/issues/799

**Comment by cjbj** [comment]
Note there's no command to restart a DB in node-oracledb.  Python's cx_Oracle has the capability, if that helps!: http://cx-oracle.readthedocs.io/en/latest/connection.html#Connection.startup

**Comment by huynhsamha** [comment]
@dmcghan Thanks for your reference, I also found the answer.
