### ISSUE TITLE
March JavaScript and Oracle Database "Office Hours" - come and ask a question

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#863]
Got a question about node-oracledb? You can hop online and chat directly with us.  Myself, @dmcghan @anthony-tuininga and @OsBlaineOra will be online and ready to give you answers in the March  *AskTOM Office Hours* about Node.js and Oracle Database.   

For details and a link to register for email reminders see our [AskTOM Office Hours](https://devgym.oracle.com/pls/apex/dg/office_hours/727) page (look for the big blue Register button if you want reminders).  

On the day come to that [page](https://devgym.oracle.com/pls/apex/dg/office_hours/727) and find the button to join the web cast (it'll be available 5 or so minutes before the start time).  We'll be using Zoom for the conference, so you'll be able to jump right on the call if your browser is configured.  No pre-registration etc will is needed, I'm told - but do it so you get the email reminders.

**Comment by dmcghan** [comment]
Quick update on this Office Hours session... The topic will be async patterns and libraries. We'll discuss the following:

- How Node.js does async
- Node.js callback pattern (both anonymous and named functions)
- Promises
- Async Functions (async/await)
- Streams
- The Async module

**Comment by cjbj** [comment]
The March Office Hours recording is up on the [office hours page](https://devgym.oracle.com/pls/apex/dg/office_hours/727).
