### ISSUE TITLE
Ref Cursor error

### ISSUE THREAD

**Issue by ravipandey1** [oracle/node-oracledb#864]
On using cursor:  { type: oracledb.CURSOR, dir : oracledb.BIND_OUT } I am getting an error of ORA-01036: illegal variable name/number. How to use cursor to avoide this issue

**Comment by anthony-tuininga** [comment]
Can you provide the script that is causing the problem? Its hard to guess with just that small fragment!

**Comment by ravipandey1** [comment]
I am using the following script:-

function (err, connection) {
    if (err) { console.error(err.message); return; }
    
    connection.execute(
      "select DSSP_PROCS.administer_patch_package.schedule_patch('2084018', 'SYSTEM CUSTODIAN') from dual",
      {
        cursor: { type: oracledb.CURSOR, dir: oracledb.BIND_OUT }
      },
      function (err, result) {
        if (err) {
          console.error('Error: ', err.message);
          doRelease(connection);
          return;
        }
        console.log(result.outBinds.cursor.metaData);
        fetchRowsFromRS(connection, result.outBinds.cursor, numRows);
      });
  });

function fetchRowsFromRS(connection, resultSet, numRows) {
  resultSet.getRows( // get numRows rows
    numRows,
    function (err, rows) {
      if (err) {
        console.log(err);
        doClose(connection, resultSet); // always close the ResultSet
      } else if (rows.length === 0) {   // no rows, or no more rows
        doClose(connection, resultSet); // always close the ResultSet
      } else if (rows.length > 0) {
        console.log("fetchRowsFromRS(): Got " + rows.length + " rows");
        console.log(rows);
        fetchRowsFromRS(connection, resultSet, numRows);
      }
    });
}
