### ISSUE TITLE
Super-Low Prio: Fix typo in documentation

### ISSUE THREAD

**Issue by frbender** [oracle/node-oracledb#866]
Take a look at the example at https://github.com/oracle/node-oracledb/blob/master/doc/api.md#getting-the-last-insert-id

You define the type of id to be NUMEBR instead of NUMBER.

**Comment by cjbj** [comment]
Thanks!  I'll fix it.

**Comment by cjbj** [comment]
This was fixed in 2.2.  Thanks for reporting it.
