### ISSUE TITLE
Query execution hang after long idle period

### ISSUE THREAD

**Issue by shadab08** [oracle/node-oracledb#868]
**FAQ**

What is your Node.js version?
node v8.9.4, 64-bit

What is your node-oracledb version?
2.1.2

What is your Oracle client (e.g. Instant Client) version? Is it 64-bit or 32-bit? How was it installed? Where is it installed?
instantclient 12.2, 64-bit
It was installed following installation instructions in directory set using LD_LIB PATH

4. What is your Oracle Database version?
11.2.0.4

5. What is your OS and version?
RHEL 64 bit

6. What is your compiler version?  For example, with GCC, run `gcc --version`
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

7. What Oracle environment variables did you set?  How *exactly* did you set them?
TNS_ADMIN
LD_LIBRARY_PATH
UV_THREADPOOL_SIZE to maxPool

10. What error(s) you are seeing?
ORA-03113: end-of-file on communication channel

The request works fine for about an hour after server start and then hangs up on connection.execute query for few minutes before I get the error "ORA-03113: end-of-file on communication channel".

Current I am using oracle instant client 12.2. I even tried to use instant client 12.1 to use poolPingInterval but that didn't help as well.

I have set BLOCK=ENABLED in **tnsnames.ora** and have following entries in **sqlnet.ora** to enable tracing.

**sqlnet.ora**
*trace_level_client=admin
TNSPING.TRACE_LEVEL = admin
TNSPING.TRACE_DIRECTORY = /tmp/mmdlogs
trace_file_client = cli.trc
trace_directory_client = /tmp/mmdlogs
log_file_client = sqlnet.log
log_directory_client = /tmp/mmdlogs
DIAG_ADR_ENABLED=ON
ADR_BASE=/tmp/mmdlogs
TRACE_LEVEL_CLIENT=16*

**Below is what I see in Oracle client trace files**
*2018-03-01 05:09:30.990044 : nioqper: error from nioqrc
2018-03-01 05:09:30.990058 : nioqper: ns main err code: 12535
2018-03-01 05:09:30.990071 : nioqper: ns (2) err code: 12609
2018-03-01 05:09:30.990084 : nioqper: nt main err code: 0
2018-03-01 05:09:30.990097 : nioqper: nt (2) err code: 0
2018-03-01 05:09:30.990110 : nioqper: nt OS err code: 0
2018-03-01 05:09:30.990131 : nioqer:entry
2018-03-01 05:09:30.990145 : nioqer: incoming err = 12151
2018-03-01 05:09:30.990187 : nttaddr2bnd:entry
2018-03-01 05:09:30.990204 : snlinGetNameInfo:entry
2018-03-01 05:09:30.990222 : snlinGetNameInfo:exit
2018-03-01 05:09:30.990236 : nttaddr2bnd:Resolved to 10.215.100.78
2018-03-01 05:09:30.990282 : nttaddr2bnd:exit
2018-03-01 05:09:30.992659 : nioqce:entry
2018-03-01 05:09:30.992688 : nioqce:exit
2018-03-01 05:09:30.992703 : nioqer: returning err = 12609*

**Code to get and execute query is below**
```javascript
dbConfig.oracle_fxp: {
	user          : "someuser",
	password      : "xyz",
	connectString : "tnsname",
	poolMax       : 20,
	poolMin       : 5,
	poolIncrement : 2,
	poolPingInterval   : 60,
	poolTimeout     : 0,
	stmtCacheSize   : 30,
	queueRequest    : true,
	queueTimeout    : 600000,
	
}


var oracleConnPool;
function initOracleConnPool() {
  oracledb.createPool(
    dbConfig.oracle_fxp,
    function(err, pool) {
      if (err) {
        console.error("createPool() error: " + err.message);
        return;
      }
      oracleConnPool = pool;
      console.log("Connection pool created for Oracle Database");
    }
  );
}

oracleDbOptions.maxRows = 5;

function executeDBQuery(dbQuery, bindParams, callbackMain) {
	logger.debug("Getting connection from pool..");
	oracleConnPool.getConnection(function(err, connection) {
	
		if (err) {
			logger.error("Error in getting connection from pool: ", err);
			logger.error("Failed DB Query: "+dbQuery);
			callbackMain(err);
		}
		else {
			logger.debug("Received connection from pool. Executing Oracle DB query..");		// Get stuck after this statement
			connection.execute(dbQuery, bindParams, oracleDbOptions, function(err, result) {
				if (err) {
					logger.error("Error in executing Oracle DB query: ", err.message);
					logger.error("Failed DB Query: "+dbQuery);
					doRelease(connection);
					callbackMain(err);
				}
				else {
					logger.debug("Sucessfully executed Oracle DB Query");
					if(result) logger.debug("Oracle DB query result: ", result.rows[0]); 
					doRelease(connection);
					callbackMain(null, result.rows);
				}
			});
		}
   
}

function doRelease(connection) {
	if(connection)
		connection.close(function(err) {
			if (err) {
				console.error("Error in releasing Orcle DB connection", err.message);
			}
		});
}            

```

**Comment by shadab08** [comment]
After adding below properties in sqlnet.ora, I am getting error "ORA-12609: TNS: Receive timeout occurred" and all requests after that are successfull.

*SQLNET.OUTBOUND_CONNECT_TIMEOUT=10
SQLNET.RECV_TIMEOUT=3
SQLNET.SEND_TIMEOUT=3*

**Comment by cjbj** [comment]
Is the code representative - or is a connection held 'open' (after getConnection) by the app for a while before being used? How long does the query take to run?  Is it running out of resources to complete (on the DB, maybe)?  Are there are DB trace files - these may be most useful?

**Comment by shadab08** [comment]
The connection is picked up from the connection pool. It happens when our application is idle for a long time (~1hr). Though after setting up the timeout values at client sqlnet.ora as mentioned in post above, I am able to get hold of error in the callback which also invalidates the idle connection and then all subsequent request work perfectly fine. Also, I have added a retry logic so that none of the requests fails. I am also planning to add the parameter SQLNET.EXPIRE_TIME on the server side which will help to close all open connections, in case of abnormal client termination.

**Comment by shadab08** [comment]
I am closing this issue for now as I have found a resolution by tweaking database parameters at client and server side.

**Comment by rameshpalipi** [comment]
Hi Syed,
we are having the same issue that you mentioned. Could you please share details on how you find the resolution.

**Comment by cjbj** [comment]
@rameshpalipi please open a new issue and give some useful detail about your versions and what you are experiencing.  Thanks.
