### ISSUE TITLE
is it possible to divorce transactions from the connection

### ISSUE THREAD

**Issue by jpollard-cs** [oracle/node-oracledb#869]
Is it possible for Oracle transactions to span multiple connections? I understand this would not be as performant and perhaps I'm putting the cart before to horse here so here is the motivation behind this question:

Say you're using connection pooling and for simplicity of this example you limit your `poolMax` to `2`. You have an endpoint that does something like the following pseudo-code (for whatever reason you want to make a query outside of the transaction so you grab another connection):

```
let conn;
db.getConnection()
    .then(c => {
        conn = c;
        conn.execute(sql1)
    })
    .then(r => {
        // do something with results
    })
    .then(db.getConnection)
    .then(c => c.execute(sql2).then(() => c.release()))
    .then(r => {
        // do something with results
    })
    .then(() => conn.execute(sql3))
    .then(() => conn.commit())
    .catch(err => conn.rollback());
```

I'm not sure if there's a legitimate use case for this so I'm asking more out of curiosity (perhaps you have a transaction isolation level of serializable and you really need to get the latest committed data for this query?). In most cases I imagine you could do work outside of the transaction before you begin the transaction or after you commit the transaction (or after you rollback if it's still necessary).

The problem here is that since the connection is tied to the transaction, there's no way to give up the connection mid-transaction and then resume the transaction later on another connection. If you had two calls come in here at the same time then this will result in contention for the two connections that are already in use and the execution will halt until the connections timeout.

**Comment by dmcghan** [comment]
@jpollard-cs 

> is it possible to divorce transactions from the connection

Generally, we relate transactions to sessions, but a lot of people often think of connections and sessions as the same thing.

When you get a connection (physical) with the driver it will have a session (logical) and the transaction will take place within the session. So, in the context of your example, no, you can't separate the two. 

> Is it possible for Oracle transactions to span multiple connections?

Your question can be interpreted different ways... Again, in the context of your example, no.

The pseudocode you supplied looks valid, but the way it's written and with only two connections in the pool it is almost guaranteed to have issues. Oracle supports this kind of workload, but you'd need to provide more connections (and threads) to do it.

> If you had two calls come in here at the same time then this will result in contention for the two connections that are already in use and the execution will halt until the connections timeout

Exactly. The way you've written the code, you're implying that the 2 connections are somehow related and need to wait for each other (so 1 HTTP request needs 2 DB connections). If that's true, then you will have issues with only 2 connections in the pool. 

Choosing the right number of connections and threads to support your unique workload is important.

**Comment by cjbj** [comment]
Check out DBMS_XA.  It gives you a transaction number and you can suspend/resume/cancel transactions. I once wrote it up in "Database Transactions Across Stateless Web Requests" on page 230 of http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html I don't have any info on how well this will work at really large scale.

**Comment by jpollard-cs** [comment]
Yeah I realize this was a somewhat contrived example, but looks like you got my gist! Consider my curiosity officially satisfied. Thanks guys 😃
