### ISSUE TITLE
Encoding data.

### ISSUE THREAD

**Issue by StigmaKim** [oracle/node-oracledb#87]
Hi. I'm newbie at node.js.

I'm in trouble at encoding 'Korean'.

My oracle database has Korean String data, and Console.log(Korean text) is worked.

but when I use execute function and select query, and Console.log(rows), It isn't work.
I set all encoding type in Eclipse as UTF-8. As I think, I have to set something controlling encoding type in oracledb module, But I can`t find how set it.

plz help me. 

Windows 7 64bit
node 0.10.38
Eclipse / NodeClipse

**Comment by cjbj** [comment]
Have you set NLS_LANG? http://docs.oracle.com/database/121/NTDBI/gblsupp.htm#NTDBI2917

**Comment by StigmaKim** [comment]
Yeah, my setting status likes below.
I don't set it. I just check it and take picture. It is already done when I find registry.

![test](https://cloud.githubusercontent.com/assets/11647938/7582149/cf0087f4-f8c5-11e4-99b2-1b82e44be9d6.jpg)


But Still dosen`t work. Help me...

**Comment by cjbj** [comment]
Did you try setting the NLS_LANG to .UTF8?

**Comment by StigmaKim** [comment]
Sorry, I can`t understand what you way exactly.

Where can I set what you say? please, help me with instruction, I'm newbie T_T

**Comment by StigmaKim** [comment]
Thanks a lot!!

I set NLS_LANG AS KOREAN_KOREA.UTF8 and It works properly!!

really thanks cjbj.

**Comment by cjbj** [comment]
@StigmaKim I'm glad you have progress. Make sure to test it well because we haven't done a full NLS review yet.
