### ISSUE TITLE
NJS-054: Binary build/Release/oracledb.node was not installed from  oracledb-v2.1.2-node-v57-win32-x64.gz

### ISSUE THREAD

**Issue by NareshRdyC** [oracle/node-oracledb#873]
*Delete unnecessary parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Use a gist for screen output and logs: see https://gist.github.com/ **Do not paste long output into this issue**.

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

- Review the install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

- Review the troubleshooting tips https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#troubleshooting

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
 --Node.js version is v8.9.4 ; npm version is 5.6.0 ; 64 bit operating system
2. What is your node-oracledb version?
 --Did not specified any specific version
3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
Oracle client with version 11.2.0 is there of 64 bit; Did not installed Instant Client
4. What is your Oracle Database version?
Oracle 11 and above
5. What is your OS and version?
Windows 7 Professsional
6. What is your compiler version?  For example, with GCC, run `gcc --version`

7. What Oracle environment variables did you set?  How *exactly* did you set them?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

10. What error(s) you are seeing?
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from
 oracledb-v2.1.2-node-v57-win32-x64.gz
oracledb ERR! self signed certificate in certificate chain
oracledb ERR! If the error is not network or filesystem related, then review
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation inst
ructions and
oracledb ERR! then install from source code with: npm install oracle/node-oracle
db.git#v2.1.2
oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
npm WARN chat_tpoint@0.0.1 No repository field.
npm WARN chat_tpoint@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.1.2 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs
[2018-03-06T11_52_50_215Z-debug.log](https://github.com/oracle/node-oracledb/files/1784975/2018-03-06T11_52_50_215Z-debug.log)
\2018-03-06T1
1_52_50_215Z-debug.log

**Comment by cjbj** [comment]
> oracledb ERR! self signed certificate in certificate chain

Are you behind some kind of firewall or vpn?

I just tested via our proxy servers and node-oracledb installed fine.

**Comment by NareshRdyC** [comment]
I think firewall might not be restricting, as it got worked from MAC system but not from windows, even both were in same network. I even set below things but no luck
npm config set strict-ssl false
npm install npm -g --ca NULL  
npm install -g oracledb

**Comment by cjbj** [comment]
Keep digging into it and find what is different.  

There are other ways to to install if the network is a problem, see https://oracle.github.io/node-oracledb/INSTALL.html

**Comment by cjbj** [comment]
Closing - no update from filer.

**Comment by yostyle** [comment]
Hi NareshRdyC,

I have the same problem on windows 7 plateform. cjbj please re-open this issue.

**Comment by kczx3** [comment]
I am having the same problem and setting the proxy doesn't seem to help at all.

`set https_proxy=http://proxy.net:8080 && set http_proxy=http://proxy.net:8080 && npm i oracledb`

```
oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v57-win32-x64.gz
oracledb ERR! self signed certificate in certificate chain
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting
```

**Comment by cjbj** [comment]
That sounds like a problem with your network.   If you were using a local trusted server you could use the workaround for the 'self-signed certificate' error noted for testing in https://github.com/oracle/node-oracledb/blob/master/package/README.md

**Comment by mchelen** [comment]
This is an SSL certificate error caused by a self-signed certificate:
`oracledb ERR! self signed certificate in certificate chain`
The problem is that `http.request` is not including the custom Certificate Authority:
https://github.com/oracle/node-oracledb/blob/master/package/oracledbinstall.js#L232
https://stackoverflow.com/questions/22258093/node-js-using-https-request-with-an-internal-ca

This is a common situation on corporate networks where the proxy server decrypts all SSL traffic using a self-signed certificate.

Can someone reopen this issue, or should I create a new one?

**Comment by theothermattm** [comment]
I struggled with this same problem for quite a while because we are on version 2.3.0 of the node-oracledb and then came across this:  https://stackoverflow.com/a/47160447

If you set the `NODE_EXTRA_CA_CERTS` environment variable on node 7.3.0+ you can add your self-signed certificates and npm should respect those values.

Hoping this helps someone in the future!

tagging @mchelen
