### ISSUE TITLE
DLOpen Error, Library not loaded (XXXX.dylib)

### ISSUE THREAD

**Issue by DTaylorBusiness** [oracle/node-oracledb#874]
Attempting to run my build on High Sierra, but when I run `npm test` results in a `library not loaded` error for `libLeapJear.dylib` which should be in the correct location, with the reason being `Image not found`

`exports.lib = {};`

`exports.lib.internal = require('./native/build/bin/KVIZNBIND');`

The `libLeapJear.dylib` is located in `/Users/USER/Documents/Repos/node-kviz/native/build`

**Comment by cjbj** [comment]
This is a new one to me.  Is it node-oracledb related?

**Comment by cjbj** [comment]
Closing - no update from filer.
