### ISSUE TITLE
-- oracledb@2.1.2  invalid

### ISSUE THREAD

**Issue by cktakata** [oracle/node-oracledb#876]
Hi,

I am trying to install and setup oracledb in my project, but always getting a problem. Here's the trace log for npm installation:

> oracledb@2.1.2 install C:\Project\backend-portalvendas\node_modules\oracledb
> node package/oracledbinstall.js

https://gist.github.com/cktakata/f925884fc80125d6054a6414afeeb5eb

I already installed oracleXE, Visual Studio and tried with Instant Client and no success.

Can you give me a hand ? Thanks in advance!

**Comment by cjbj** [comment]
What's the problem / error?  The log shows node-oracledb installation completed OK:

> Node-oracledb 2.1.2 installation complete for Node.js 6.11.4 (win32, x64)

**Comment by cktakata** [comment]
Hi! Thanks for replying.

I fixed the error, it was a missing PATH to the instant client (probably node-oracledb uses the executable file from there). As soon I added the full path, I have no more issues.

Thanks a lot.

**Comment by cjbj** [comment]
Yes it does use libraries there. The documentation on setting PATH to the Instant Client directory is in the [installation guide](https://oracle.github.io/node-oracledb/INSTALL.html#instwin).
