### ISSUE TITLE
Error : installing node-oracledb on Linux

### ISSUE THREAD

**Issue by rohit-khanna** [oracle/node-oracledb#877]
I am trying to install oracledb on my Linux server.  
I have followed the following steps as per[ INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instzip).
1. Set LD_LIBRARY_PATH 
2. set PATH

Error:
` 
npm install oracledb
> oracledb@2.1.2 install /opt/MYSERVER/node_modules/oracledb
> node package/oracledbinstall.js
module.js:540
    throw err;
    ^
Error: Cannot find module '/opt/MYSERVER/node_modules/oracledb/package/oracledbinstall.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm WARN ekho-notification-api@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@2.1.2 install: `node package/oracledbinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@2.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-09T05_00_09_781Z-debug.log
`

Log File details attached. 
[Log File](https://gist.github.com/rohit-khanna/dfa5b06dea6b0d776471d24b73013eb6)

### For installation issues:

- Review the install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
**Did that.**

- Review the troubleshooting tips https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#troubleshooting
**Did that.**

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  
npm@5.6.0
node@v8.9.4

2. What is your node-oracledb version?
**Fresh install**
Removed from Package.JSON  and did npm install oracledb

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
I Used "instantclient-basic-linux.x64-12.2.0.1.0"

4. What is your Oracle Database version?

5. What is your OS and version?
**Linux version 3.10.0-514.16.1.el7.x86_64**

6. What is your compiler version?  For example, with GCC, run `gcc --version`
**gcc version 4.8.5**
7. What Oracle environment variables did you set?  How *exactly* did you set them?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
**LD_LIBRARY_PATH  =/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH**  

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
**npm install oracledb**

10. What error(s) you are seeing?

**Comment by rohit-khanna** [comment]
Updated the Log File:

Also present at: https://gist.github.com/rohit-khanna/dfa5b06dea6b0d776471d24b73013eb6

**Comment by cjbj** [comment]
I won't have a chance to check you log until later.  You can manually install with https://oracle.github.io/node-oracledb/INSTALL.html#3122-manually-extracting-pre-built-binaries

**Comment by rohit-khanna** [comment]
ok let me try....

**Comment by rohit-khanna** [comment]
@cjbj The manual installation was very helpful and worked fine.   :+1: 

Would be very glad if we can figure out the reason for error during "npm install"

**Comment by cjbj** [comment]
Give us a screen log of how you ran the npm install.  Were you using sudo?  How did you install Node?  Do you have more than one version installed?

**Comment by cjbj** [comment]
Closing - no update from filer.
