### ISSUE TITLE
Daylight savings time causes an error with time retrieval when TRUNC function is used.

### ISSUE THREAD

**Issue by bindushastri** [oracle/node-oracledb#878]
Hi, In the database(EDT) the date is inserted as **2018-03-07 00:00:00.0**
In the general case of selection, I'm able to fetch correctly ie.,  **2018-03-07 00:00:00.0 **.
but when I retrieve the data using TRUNC(myDateColumn) the date is pushed back to the previous date ie., **2018-03-06**.
I appreciate your reply in advance.

**Comment by dmcghan** [comment]
@bindushastri Thanks for moving this over. 

> In the database(EDT)

What makes it EDT? Is that just implicit?

What data type is myDateColumn (DATE, TIMESTAMP WITH LOCAL TIME ZONE, etc.)? Also, what value are you setting the session time zone to?

**Comment by bindushastri** [comment]
The Server is located in EDT location and I'm accessing from IST location.
DATE is the datatype for myDateColumn.

**Comment by cjbj** [comment]
@bindushastri the best thing to do is to read the [node-oracledb manual about date handling](https://oracle.github.io/node-oracledb/doc/api.html#datehandling), and then the second thing is to make sure you are setting `ORA_SDTZ` or running `ALTER SESSION SET TIME_ZONE`.

**Comment by dmcghan** [comment]
@bindushastri The physical locations aren't relevant. The OS time zone of the database server is relevant for the SYSDATE and SYSTIMESTAMP functions. The session time zone (which @cjbj mentioned) is relevant for the CURRENT_DATE and CURRENT_TIMESTAMP functions and some implicit conversions.

What do you get when you run the following query from the driver?

```sql
select sessiontimezone session_tz,
  to_date('07-mar-2018','dd-mon-yyyy') dt,
  trunc(to_date('07-mar-2018','dd-mon-yyyy')) trunc_dt
from dual
```

**Comment by dmcghan** [comment]
@bindushastri To clarify my previous statement, the value `ORA_SDTZ` will affect the value returned from `SYSDATE` as it's fetched/bound out of the DB and into JavaScript. This is true for any DATE or TIMESTAMP value as they don't have time zones so `ORA_SDTZ` is assumed. 

What is the time zone of the server running Node.js? The date value you're showing us (**2018-03-07 00:00:00.0 **) doesn't look like a normal date logged to the console, which includes the time zone:
Mon Mar 12 2018 20:31:34 GMT-0400 (EDT)

**Comment by cjbj** [comment]
Closing - no update from filer.
