### ISSUE TITLE
Can't connect to DB using Wallet

### ISSUE THREAD

**Issue by peterj** [oracle/node-oracledb#879]
Here's the code snippet I am trying to run: 

```
const oracledb = require('oracledb');
oracledb.getConnection(
    { externalAuth: true, connectString: 'dbaccess' },
    (err, conn) => {
        if (err) {
            console.error(err);
            process.exit(-1);
        }
        console.log('connected!');

        conn.close(err => {
            if (err) {
                console.error('error closing the connection: ' + err);
            }
            console.log('connection closed');
        });
    }
);
```

I've set the `TNS_ADMIN` to point to the folder with sqlnet.ora, tnsnames.ora and other wallet files. I also updated the `DIRECTORY` in sqlnet.ora file to point to the same folder as `TNS_ADMIN`.

With all that set, when I run the above snippet, I get the following error: 
```
{ Error: ORA-01017: invalid username/password; logon denied errorNum: 1017, offset: 0 }
```

If I change the `externalAuth` to `false` and insert username/password, I am able to connect to the DB. What am I missing?

**Comment by cjbj** [comment]
In off-channel email, the DB is Exadata Express and so the wallet is only used for encryption.  Connecting with a DB username & password is still required.
