### ISSUE TITLE
When/where does the node-oracledb request the c:\oracle\instantclient path variable?

### ISSUE THREAD

**Issue by bmulcahy** [oracle/node-oracledb#88]
When/where does the node-oracledb request the c:\oracle\instantclient path variable?

**Comment by cjbj** [comment]
During installation the compiler needs to know where to find Instant Client.  This is what OCI_LIB_DIR and OCI_INC_DIR are used for.  At runtime the operating system's dynamic linker needs to resolve all the code symbols in node-oracledb's binary library and the Instant Client libraries etc; this is what PATH is used for.

**Comment by bmulcahy** [comment]
what about after the module is built? It still looks for the path does it not?

**Comment by cjbj** [comment]
Code that is compiled with a new library may not find the symbols/functions it expects if you later try to run it with an old library.

Windows doesn't make it too easy if you need to have multiple versions of the same library installed.  If you have a DB already on your machine, you probably don't need Instant Client (this is documented in section 6.3 of https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin).  If you do need multiple versions of Oracle libraries then you will need to change PATH before calling node, possibly in a .bat file.

**Comment by bmulcahy** [comment]
so if I already have a full oracle client I shouldn't need to add the PATH variable only the OCI_LIB_DIR and OCI_INC_DIR?

**Comment by cjbj** [comment]
You only need OCI_LIB_DIR & OCI_INC_DIR set when installing node-oracledb.  At runtime make sure the same library occurs first in PATH.

**Comment by bmulcahy** [comment]
Just wanted to say thank you for all work just one more question.

 What would it take to be able to hard code in the location of the instant client via a variable in a config file instead of it going off a system path? Is the oracle sdk looking for the path variable or is it the node module that looks for it?

**Comment by cjbj** [comment]
Thanks!

Technically it is Windows that is looking for it.  However the trigger in this case is that the node-oracledb DLL needs to use functions defined in the Instant Client DLL (which will then use functions defined in Windows system libraries etc), to put it simply.

I don't think Windows has the 'rpath' feature that Linux has (and node-oracledb uses with Instant Client RPMs).  Have you tried copying the Instant Client libraries to where the node-oracledb library is?  This may work.  I don't have Windows but the equivalent path on Linux would be node_modules/oracledb/build/Release where the oracledb.node file is.

**Comment by bmulcahy** [comment]
I will try that and rebuild. Again thanks for all the hardwork!

**Comment by cjbj** [comment]
@bmulcahy you would build first and then move Instant Client to where the build created the library.

**Comment by bmulcahy** [comment]
Would i need to unnest the files or just keep the all in the instantclient folder? so I would have build\release\instantclient\(all ic files here)

**Comment by bmulcahy** [comment]
actually unnesting it works awesome!

**Comment by cjbj** [comment]
@bmulcahy can you share output of some DIR commands so I (and Windows users) can see which directory you put the files in, and which files.

**Comment by bmulcahy** [comment]
@cjbj Yes let me test on another machine to make sure it works on there as well.

**Comment by bmulcahy** [comment]
I have no system or user env set  for any oracle related products and oracledb still works after if was previously compiled using VS2013. I have tested on two computers and the results were replicated.
```
Directory of .\node_modules\oracledb

05/07/2015  11:21 AM    <DIR>          .
05/07/2015  11:21 AM    <DIR>          ..
05/07/2015  10:46 AM             5,366 binding.gyp
05/07/2015  10:47 AM    <DIR>          build
05/06/2015  03:28 PM                45 index.js
05/06/2015  04:22 PM    <DIR>          lib
05/06/2015  03:28 PM            11,513 LICENSE.md
05/06/2015  04:24 PM             1,603 package.json
05/06/2015  03:28 PM             4,326 README.md
05/06/2015  04:22 PM    <DIR>          src

          


 Directory of .\node_modules\oracledb\build

05/07/2015  10:47 AM    <DIR>          .
05/07/2015  10:47 AM    <DIR>          ..
05/07/2015  10:47 AM        33,554,432 binding.sdf
05/06/2015  03:28 PM               853 binding.sln
05/06/2015  03:28 PM             3,544 config.gypi
05/06/2015  03:28 PM             9,550 oracledb.vcxproj
05/06/2015  03:28 PM             8,715 oracledb.vcxproj.filters
05/07/2015  10:45 AM    <DIR>          Release
          


 Directory of .\node_modules\oracledb\build\Release

05/07/2015  10:45 AM    <DIR>          .
05/07/2015  10:45 AM    <DIR>          ..
09/11/2014  02:52 AM            40,448 adrci.exe
09/11/2014  02:52 AM            19,672 adrci.sym
09/11/2014  02:53 AM               581 BASIC_README
09/11/2014  02:52 AM            84,480 genezi.exe
09/11/2014  02:52 AM            51,696 genezi.sym
05/07/2015  10:22 AM    <DIR>          help
05/06/2015  04:22 PM    <DIR>          obj
09/11/2014  02:49 AM           641,536 oci.dll
09/11/2014  02:49 AM           473,416 oci.sym
09/02/2014  04:17 PM           147,456 ocijdbc12.dll
09/02/2014  04:17 PM            29,048 ocijdbc12.sym
09/11/2014  02:25 AM           508,928 ociw32.dll
09/11/2014  02:25 AM            82,136 ociw32.sym
08/29/2014  05:14 AM         3,692,104 ojdbc6.jar
08/29/2014  05:14 AM         3,698,892 ojdbc7.jar
05/06/2015  03:28 PM               772 oracledb.exp
05/06/2015  03:28 PM             1,716 oracledb.lib
05/06/2015  03:28 PM            94,720 oracledb.node
05/06/2015  03:28 PM           920,576 oracledb.pdb
09/11/2014  02:14 AM            68,096 oramysql12.dll
09/11/2014  02:14 AM            34,856 oramysql12.sym
08/01/2014  07:46 AM         4,694,528 orannzsbb12.dll
08/01/2014  07:46 AM           845,880 orannzsbb12.sym
09/11/2014  01:40 AM         1,099,264 oraocci12.dll
09/11/2014  02:53 AM           843,632 oraocci12.sym
09/11/2014  01:55 AM         1,125,888 oraocci12d.dll
09/11/2014  02:53 AM           945,200 oraocci12d.sym
09/11/2014  02:52 AM       171,764,736 oraociei12.dll
09/11/2014  02:52 AM        11,191,216 oraociei12.sym
08/03/2014  01:59 PM           214,528 oraons.dll
09/11/2014  02:48 AM           310,784 orasql12.dll
09/11/2014  02:48 AM            53,712 orasql12.sym
05/07/2015  10:45 AM    <DIR>          sdk
09/11/2014  02:52 AM            40,448 uidrvci.exe
09/11/2014  02:52 AM            19,672 uidrvci.sym
05/07/2015  10:22 AM    <DIR>          vc10
05/07/2015  10:22 AM    <DIR>          vc11
05/07/2015  10:22 AM    <DIR>          vc12
09/09/2014  09:46 PM            71,202 xstreams.jar
```

**Comment by cjbj** [comment]
@bmulcahy Thanks very much.

If anyone is trying to slim down the install footprint, some of the Instant Client files are not needed or commonly used with node-oracledb.  Scanning the list quickly, these are likely not needed: adrci*, uidrvci*, genezi*, *jdbc*, *mysql*, *occi*.  And probably the vc directories.  Caveat emptor.

**Comment by bmulcahy** [comment]
@cjbj true i haven't done any testing on that but don't think it will cut down on size too much since oraociei12.dll is 164 mb
