### ISSUE TITLE
 NJS-045 VSCode Extension 

### ISSUE THREAD

**Issue by callamaris** [oracle/node-oracledb#881]
Environment:
VSCode Extension (vscode: 1.21.1, node: 7.9.0, )
Oracle 12c (x64, Local Database)
Windows 10 x64 
node-oracledb: 2.1.2

Error:
NJS-045: cannot load the oracledb add-on binary for Node.js 7.9.0 (win32, x64)

Code:
`
var oracledb = require('oracledb');
`

I get this error only when i run it in a vscode extension. Works fine when executed with "node main.js" (node 9.8.0)

**Comment by cjbj** [comment]
What's the full message you get?  Is PATH set?

**Comment by callamaris** [comment]
PATH is set to C:\app\oracle\product\12.1.0\dbhome_1\BIN

Error message:
`
Cannot load C:\Users\myname\Documents\projectdir\node_modules\oracledb\build\Release\oracledb.node
A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\myname\Documents\projectdir\node_modules\oracledb\build\Release\oracledb.node
Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.
	at Object.<anonymous> (C:\Users\myname\Documents\projectdir\node_modules\oracledb\lib\oracledb.js:68:13)
	at Object.<anonymous> (C:\Users\myname\Documents\projectdir\node_modules\oracledb\lib\oracledb.js:536:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.J.Y.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:784)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
`

**Comment by cjbj** [comment]
Try printing PATH before you require() node-oracledb.

VS Code has some settings that you can configure environment variables in.  I've also seen people have to set the env vars in a terminal and then invoke VS Code from that terminal, e.g. this one on macOS that I was looking at just last week: https://stackoverflow.com/posts/36882426/revisions

**Comment by mickeypearce** [comment]
I have a very similar problem. I have exact same environment. It doesn't work when requiring inside vscode extension. Works fine when using normally (not in extension host).

I tried with different architecture (ia32 vs x64), for Node, VSCode, Oracle Driver.

I tried setting process.env['PATH'] before requiring and set PATH to '' but I always get this error.

> NJS-045: cannot load the oracledb add-on binary for Node.js 7.9.0 (win32, x64)
> extensionHostProcess.js:453
> Cannot load ..\vscode-extension-test\test-ext2\node_modules\oracledb\build\Release\oracledb.node
> error: 193\\?\..\vscode-extension-test\test-ext2\node_modules\oracledb\build\Release\oracledb.node
> Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
> You must have 64-bit Oracle client libraries in your PATH environment variable.
> If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
> http://www.oracle.com/technetwork/topics/winx64soft-089540.html
> A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

**Comment by dmcghan** [comment]
I'm not sure if this is a solution that will work for every situation, but it's a start.  I tested VS Code 1.21.1 which uses Electron 1.7.0. Using some notes from [this page](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md), I did the following from a terminal in my extension directory (may need to delete the `oracledb` directory from `node_modules` first):

```bash
# Electron's version.
export npm_config_target=1.7.0
# The architecture of Electron, can be ia32 or x64.
export npm_config_arch=x64
export npm_config_target_arch=x64
# Download headers for Electron.
export npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
export npm_config_runtime=electron
# Tell node-pre-gyp to build module from source code.
export npm_config_build_from_source=true
# Install all dependencies, and store cache to ~/.electron-gyp.
HOME=~/.electron-gyp npm install
```

**Comment by mickeypearce** [comment]
Thanks a lot for help, I finally made it work for my extension host.
```bash
npm install electron-rebuild
.\node_modules\.bin\electron-rebuild.cmd --version=1.7.0 --arch=x64
```

**Comment by cjbj** [comment]
Closing.  No update from original filer, and @mickeypearce seems sorted.
