### ISSUE TITLE
Enhancement: add new property to execute(): Options to specify schema

### ISSUE THREAD

**Issue by davidschwab** [oracle/node-oracledb#884]
Currently, I don't see a way to specify a schema except for explicitly stating directly in the SQL:

```
sql: "select * from <SCHEMA>.<TABLE>"
```

This is an enhancement request to add a new [options property to the execute function](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#executeoptions) that would allow specifying a schema so the sql could instead look like this:

```
sql: "select * from <TABLE>"
```

**Comment by anthony-tuininga** [comment]
This is used as a connection property (connection.currentSchema) in other environments. Would that suit your requirements?

**Comment by cjbj** [comment]
@davidschwab while there's no node-oracledb property to set this at the moment, you can use [ALTER SESSION SET CURRENT_SCHEMA](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/ALTER-SESSION.html#GUID-DC7B8CDD-4F89-40CC-875F-F70F673711D4).

Any future node-oracledb property would pass down the code layers to [OCI_ATTR_CURRENT_SCHEMA](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnoci/handle-and-descriptor-attributes.html#GUID-FB263210-118E-4DB3-A840-1769EF0CB977) which has the same effect (but avoids the round-trip and overhead of the ALTER call)

**Comment by davidschwab** [comment]
@anthony-tuininga Yeah, connection.currentSchema would work for me.
@cjbj Thanks for the info.

**Comment by cjbj** [comment]
This was pushed to the dev-4.0 branch.  See https://github.com/oracle/node-oracledb/issues/1053#issuecomment-472233930 for build steps

**Comment by cjbj** [comment]
@davidschwab Node-oracledb 4.0 has been released with an enhancement for this, see https://oracle.github.io/node-oracledb/doc/api.html#propconncurrentschema.  The release announcement is at https://blogs.oracle.com/opal/oracle-db-named-objects-and-advanced-queuing-support-new-in-node-oracledb-40
