### ISSUE TITLE
Error: NJS-050: data must be shorter than 65535

### ISSUE THREAD

**Issue by muxuehen** [oracle/node-oracledb#885]
run test/clobDMLBindAsString.js ,error is Error: NJS-050: data must be shorter than 65535
help me
example1: 
  sql = 'insert into talk_clob (id ,mess) values (:id, EMPTY_CLOB())'; =>**true**
 updateSql = 'update talk_clob set mess=:mess where id=:id';
 params = {id: '123',mess:richContent};=>**error**   Error: NJS-050: data must be shorter than 65535

example2: 
  sql = 'insert into talk_clob (id ,mess) values (:id, EMPTY_CLOB())'; =>**true**
 updateSql = 'update talk_clob set mess=:mess where id=:id';
 params = {id: {dir: oracledb.BIND_IN,val:'111', type:oracledb.STRING},
        mess: {dir: oracledb.BIND_IN,val:richContent, type:oracledb.CLOB}};=>**error**   Error: NJS-011: encountered bind value and type mismatch in parameter 2

please help me ,help me 

Thanks

**Comment by cjbj** [comment]
Please answer the template questions: https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md

As a (not so wild) guess, you need to upgrade either to node-oracledb v2, or use Oracle 12 client libraries.

**Comment by muxuehen** [comment]
Thanks

**Comment by cjbj** [comment]
I'll close this until you give the requested information.  Otherwise there's nothing further to comment on.
