### ISSUE TITLE
New series on creating a REST API with Node.js and Oracle Database

### ISSUE THREAD

**Issue by dmcghan** [oracle/node-oracledb#888]
I've started a new series: [Creating a REST API with Node.js and Oracle Database](https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/)

The current plan is to touch on the following core topics before going into details on specific features and techniques:

- Web Server Basics
- Database Basics
- Handling GET requests
- Handling PUT, POST, and DELETE requests
- Adding pagination, sorting, and filtering to GET request

I'm making the code available in our [oracle-db-examples repo](https://github.com/oracle/oracle-db-examples/tree/master/javascript/rest-api).

Your questions and comments are welcome!

**Comment by jgcmarins** [comment]
@dmcghan nice approach.
How about a series with [GraphQL](https://github.com/facebook/graphql)?

**Comment by dmcghan** [comment]
@jgcmarins Thanks! 

> How about a series with GraphQL?

That's a great idea, though I'd have to learn a lot more about GraphQL myself! Maybe by the time I'm finished with this series, I'll be ready to take that one on... :)

**Comment by dmcghan** [comment]
@danilohgds 

> I can help you with that one if you would lilke.

Sure! Have you done some work with GraphQL and Oracle Database? How have you approached it so far?

**Comment by danilohgds** [comment]
@dmcghan It was easier than expected.

1. We built a backend in node 6.9.5 that exposes the GraphQL endpoint to consumers.
2. Then we built the GQL queries for all selects
3. All mutations for DML statements.
4. Repositories based on what data they retrieve, userRepository, BooksRepository etc.
5. Build interfaces that describe your database data.
6. Everything above is injected in GraphQL through the context, and the queries defined will route the graphQL request to the repository class:
7. Call GraphQLAPI >  Resolve function in GraphQLFieldConfig returns the oracle call as a Promise. 
8. Return from oracle call is an Observable Objects with the response.

I will upload something to my github repo so you can take a look.  We also considered KNEX as a possible aid for easily building queries, but the lib itself is very new (not production ready if I may say so myself).

**Comment by danilohgds** [comment]
@dmcghan I will work on it, I have the sandbox environment setup in my machine from previous posts you wrote :)

**Comment by jeffm13** [comment]
We've also done a fair amount with graphql.  In fact, most of our new clients for existing API's are now using graphql.  We took a slightly different approach though.  We already have RESTful APIs, giving us access to pretty much everything in our custom order management app. The resolvers in our graphql schema simply invoke those APIs.  It's actually really simple, and probably done in fewer than 100 lines of code for a dozen API's--excluding the type definitions of course. Unfortunately, it's not destined for Github.

**Comment by dmcghan** [comment]
@jeffm13 Sounds interesting...

> We already have RESTful APIs, giving us access to pretty much everything in our custom order management app. 

How were those implemented?


> The resolvers in our graphql schema simply invoke those APIs.

How did this benefit the consumers?


> Unfortunately, it's not destined for Github.

Aww man... :)

**Comment by cjbj** [comment]
@danilohgds @jeffm13 To take the discussion in a different direction: what do you need/want from node-oracledb?

**Comment by jgcmarins** [comment]
I also can share some cool stuff, based on what we've done in production.
In our case, we've implemented a generic Oracle loader/connection handler/pagination handler, based on Facebook's [dataloader](https://github.com/facebook/dataloader) concept.
Those loaders are consumed by GraphQL resolvers which will compose querys, with Oracle's bind variables concept.
Then, GraphQL can solve multiple querys "asynchronously" and return a single result.

**Comment by cjbj** [comment]
This is all really cool.  And seeing the word 'production' is great.  Keep letting us know what you are doing - this helps a lot when upper management are deciding resource allocation across products.  Post here or [send me private email](https://github.com/cjbj). (Any accolades for node-oracledb are also welcome!)

**Comment by dmcghan** [comment]
@jgcmarins That does sound interesting - I'd love to see an example!

**Comment by danilohgds** [comment]
@dmcghan My experience comes from a production implementation, so does the pain of using GraphQL...

@cjbj Things, I'm looking for in the future

1. More Test focused posts, an entire section dedicated on testing strategies that will cover classes that use node-oracledb
2. Easy way to patch rows data to pretty Interface objects.
3. Typescript examples
4. Better coverage on RAC based environments, I know my production app gives me trouble every single time they shift RAC instances for maintenance.

**Comment by dmcghan** [comment]
@danilohgds 

> More Test focused posts

I can do some test focused posts as part of the series I'm doing on REST.


> Easy way to patch rows data to pretty Interface objects.

Can you explain this in more detail?


> Typescript examples

I don't use TypeScript myself, though it's probably a good idea to add some examples...


> Better coverage on RAC based environments

Great idea!

**Comment by jgcmarins** [comment]
@danilohgds, posts about tests sounds really good.

**Comment by danilohgds** [comment]
@dmcghan 

Here's an example: 

Let's say I am fetching some rows from countries table in HR schema. 
In order to get my rows into a interface object, I have to do some iteration and build such object.
I get it that the effort of doing the iteration is somewhat minimal, but what about extra options that lets you the outFormat is an interface. 

```typescript
 return connection.execute(countryQuery,params).then((result: any) =>{
                    console.log(result.rows[0]);
                    let cList:CountryList = {
                            countryId: result.rows[0][0],
                            countryName:  result.rows[0][1],
                            regionId:  result.rows[0][2]
                    }
                    doRelease(connection);
                    return cList;
                }
            );

///And I want to make the rows come as an array of the following interface 
interface CountryList {
    countryId: number;
    countryName: string;
    regionId: number;
}
```

**Comment by cjbj** [comment]
@danilohgds I know @anthony-tuininga and @dmcghan have talked about something like this.   In Python cx_Oracle @anthony-tuininga has [row factories](https://github.com/oracle/python-cx_Oracle/blob/master/samples/tutorial/solutions/rowfactory.py) and [output type converters](https://github.com/oracle/python-cx_Oracle/blob/master/samples/tutorial/solutions/type_output.py).

**Comment by anthony-tuininga** [comment]
One possibility would be to add support for a callable in the "outFormat" parameter to execute. This callable would accept one parameter which is the array of data that would ordinarily be returned. The return value of this function would be what is returned to the calling application instead. This would give you the ability to do anything you wished inside that callable and is the equivalent to cx_Oracle's row factory. Do you think this would address your request?

**Comment by dmcghan** [comment]
@danilohgds I tried to create a mockup of what @anthony-tuininga was suggesting, but we're not clear about your example (keep in mind we are not TypeScript programmers).

You have an interface called CountryList, but its properties are scalars, not arrays.

In your comments, you say you have to do some iteration, but your example doesn't iterate. 

Could you please clarify? Are you looking for the results to be either:

- A custom list type - CountryList
- An array of custom types - [Country, Country, Country, ...]

**Comment by danilohgds** [comment]
@dmcghan 

I took this example from my graphql github project.  The idea would be to have some fetch option where you pass an interface, and the object returned is based on it.

The interface only defines the properties that you have in a object, for better readability purposes.
You can see that I am doing index acess on my row object to compose the Array of Countries.

My idea would be a simple clean way, where you provide the interface as a fetch parameter, and you get the object back without the hassle of having to iterate. The results would be an Array of custom types [ Country, Country, Country ]

Nonetheless, after some thought I think that this would make more sense to be developed as an additional lib, instead of being a feature from node-oracledb itself.

```typescript
  getAllCountriesPooled(){
        return this.oraclePool.getConnection().then((connection:any) => {
            connection.clientIdentifier = 'getAllCountriesPooled';
            return connection.execute(allCountriesQuery).then((result: any) =>{
                    let cList:CountryList[] = Array<Countries>();                    
                    result.rows.forEach((dbRow:any) => {
                        cList.push({
                            countryId : dbRow[0],countryName : dbRow[1],regionId:dbRow[2]                            
                        })
                    });
                    doRelease(connection);
                    return cList;
                }
            );
        });
    }```

**Comment by cjbj** [comment]
@danilohgds I'll close this announcement post now, since it was created > 1 month ago.  If you want to propose feature ideas, open new issues - or new PRs, now that you have the OCA sorted!

**Comment by cjbj** [comment]
To add to the GraphQL breadcrumb trail, keep an eye on any Primsma GraphQL Oracle Connector work at https://github.com/prismagraphql/prisma/issues/1644/

**Comment by cjbj** [comment]
Via @dmcghan, for a bigger & presumably better GraphQL demo, also check out https://github.com/unofficialoraclecloudhub/oracledb-graphql-demo
