### ISSUE TITLE
undefined symbol: OCIDefineByPos2

### ISSUE THREAD

**Issue by ChinaDXTE** [oracle/node-oracledb#89]
my nodejs version is 0.10.26, my system is opensuse, i have installed node-oralcedb and use the example code in /examples/select1.js .
it can connect to oracle server successfully, but at the line "connection.execute", there is exception thrown.
below is the exception, i searched the web but this isn't any solutions.

node: symbol lookup error: /usr/ftp/Workplace/ismart/testOracle/node_modules/oracledb/build/Release/oracledb.node: undefined symbol: OCIDefineByPos2

**Comment by cjbj** [comment]
You probably built node-oracledb with  Oracle12c client libraries or headers but at runtime you are using Oracle 10 or 11g client libraries.  Make sure LD_LIBRARAY_PATH or ld.so.conf are set to the same version you built with.  The function OCIDefineByPos2 was introduced in Oracle 12c client libraries.
I'd also recommend upgrading Node.js.
