### ISSUE TITLE
Help Needed with MAKEPKG bat

### ISSUE THREAD

**Issue by danilohgds** [oracle/node-oracledb#890]
1. What is your Node.js version?  Is it 64-bit or 32-bit?   **6.9.5** 
2. What is your node-oracledb version? **2.2**
3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed? **12.2 instant client 64 bit, C:\oracle\instantclient_12_2**
4. What is your Oracle Database version? **12C**
5. What is your OS and version? **Windows 10 Pro**
6. What is your compiler version?  **$ python --version Python 2.7.14**
7. What Oracle environment variables did you set?  How *exactly* did you set them? 
![image](https://user-images.githubusercontent.com/12349622/38759020-30ced9e0-3f4a-11e8-837d-defb5b015c44.png)
8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
![image](https://user-images.githubusercontent.com/12349622/38758929-af86292e-3f49-11e8-89f6-3545b34ea689.png)
9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?  I was using /MAKEPKG.BAT to create staging batch files.
10. What error(s) you are seeing?
Logs: https://gist.github.com/danilohgds/54f0728703cbec6056363d3de19958c6

Can you guys please help me out ? I am trying to generating staging binaries pointing to my dependency repo.

**Comment by cjbj** [comment]
How did you get the source?  See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#3112-installing-github-clones-and-zip-files

**Comment by danilohgds** [comment]
Hi Chris, I cloned the source from github, master branch:  git clone https://github.com/oracle/node-oracledb.git

**Comment by kwent** [comment]
Use `git clone --recursive`

**Comment by danilohgds** [comment]
--recursive worked.

**Comment by cjbj** [comment]
@danilohgds the BAT file creates binaries (they are the same for staging and production) but not the generic package(s).  A PR is welcome.  Or just use the Makefile on macOS or Linux.

**Comment by danilohgds** [comment]
got that! Thanks Chris, I need to host the binaries with the  NODE_ORACLEDB_PACKAGE_URL_PATH and NODE_ORACLEDB_PACKAGE_HOSTNAME pointing to my private repo, so I might fix try to fix the bat.

Regards.

**Comment by cjbj** [comment]
@danilohgds this is the bit to replicate: https://github.com/oracle/node-oracledb/blob/master/package/Makefile#L56-L60

**Comment by danilohgds** [comment]
it changed on it own it seems, after the npm pack.

from this: 

if (!proxy.startsWith('http://') && !proxy.startsWith('https://')) {
      proxy = 'https://' + proxy;
    }

to this : 

if (//') && //')) {
proxy = 'https://' + proxy;
}

any ideas.

**Comment by danilohgds** [comment]
@cjbj  I got it to work, will do a PR soon, just have to sign off the OCA.
