### ISSUE TITLE
Async Hook, Node 10 Support

### ISSUE THREAD

**Issue by jpollard-cs** [oracle/node-oracledb#895]
Given node 10 is going to be released next Tuesday (4/24) I'm curious if there are any immediate plans or discussion around supporting node 10 and/or async hooks. I am using a small wrapper library around node-oracledb which abstracts away the connection. If you want to execute a bunch of sql over the same connection you just request a transaction, but then you have to pass it through to every request. If node-oracledb were to support async hooks, I could upgrade the wrapper library to automatically associate the transaction with each request in the execution path. Since node-oracledb is using the thread pool my understanding is it will need to provide additional metadata in order for node-oracledb to be compatible with async hooks (as @AndreasMadsen noted here: https://github.com/nodejs/help/issues/1021)

**Comment by dmcghan** [comment]
> I'm curious if there are any immediate plans or discussion around supporting node 10 and/or async hooks.

No immediate plans, but we are looking into it.


> If you want to execute a bunch of sql over the same connection you just request a transaction, but then you have to pass it through to every request. 

I'd like to know more about this API. Can you mock it up?


> If node-oracledb were to support async hooks, I could upgrade the wrapper library to automatically associate the transaction with each request in the execution path.

Do you have any suggestions or ideas on what the support/APIs might look like?

**Comment by jpollard-cs** [comment]
> I'd like to know more about this API. Can you mock it up?

not sure if you meant the current API, but this is how it looks now

```javascript
const transaction = await sage.transaction(options);
try {
    await sage.execute(sql1, bindParams, { transaction });
    await sage.execute(sql2, bindParams, { transaction });
    await transaction.commit();
} catch(err) {
    await transaction.rollback();
}
```
Of course this simplifies things a bit as in reality these transactions need to be weaved into more complex function calls.

ideally this would look like:

```javascript
const transaction = await sage.transaction(options);
try {
    await sage.execute(sql1, bindParams);
    await sage.execute(sql2, bindParams);
    await transaction.commit();
} catch(err) {
    await transaction.rollback();
}
```

> Do you have any suggestions or ideas on what the support/APIs might look like?

still trying to get a better grip on this - will get back to you

**Comment by jpollard-cs** [comment]
accidentally closed - reopening

**Comment by dmcghan** [comment]
> not sure if you meant the current API, but this is how it looks now

I did. The current (and proposed) API seems to complicate things a bit. 

Why not just wrap the connection itself? Then you could do whatever you're doing behind the scene without the additional transaction semantics.

```js
const conn = await sage.getConnection(options);
try {
    await conn.execute(sql1, bindParams);
    await conn.execute(sql2, bindParams);
    await conn.commit();
} catch(err) {
    await conn.rollback();
}
```

Sorry to go off on this tangent... :)

**Comment by jpollard-cs** [comment]
Well I didn't write the library, I just inherited it, although it does feel a bit unnatural (for me at least) calling commit/rollback on the connection rather than the transaction.

**Comment by dmcghan** [comment]
> Well I didn't write the library

Always fun! :)

> open to further convincing though

Okay, I'll bite... ;)

I'm just trying to imagine what happens with a call to `sage.beginTransaction`. I suppose you take a connection out of the pool and store it somewhere, then try to associate it with the transaction object so you know which connection to use when the execute call is made. Now you want to involve async hooks to simplify it all. Sounds like a lot of work for something that could be really simple.

Also, `beginTransaction` sounds odd with Oracle, as transactions don't really begin until the first change is made.

Are you convinced?

**Comment by jpollard-cs** [comment]
@dmcghan the idea is that you would be able to do something similar to thread-local storage and async hooks should make this possible - I see your point that this may seem like a lot of work, but it gives you the convenience of simply importing the library and using it directly without needing to be concerned with the context or passing connections all over the place. 

Good point on `beginTransaction` - it could be something like `useTransaction` or just stay as it is now: `transaction`

**Comment by jpollard-cs** [comment]
yes I'm aware auto-commit is more performant and maybe I'm misunderstanding how auto-commit works, but my understanding is if you were to do something like the following (using the same connection):

```
    // assuming use of node-oracledb here and not sage
    // not sure the syntax is entirely correct..
    await conn.execute(sql1, bindParams, { autoCommit: true });
    await conn.execute(sql2, bindParams, { autoCommit: true });
```

then each statement would be committed individually such that the first could succeed and still be committed even though the second could fail - or is this not the case?

**Comment by cjbj** [comment]
@jpollard-cs that's true in that scenario.

If you create some kind of transaction object, a commit on a connection will commit everything, even if you only wanted one 'transaction object' to be committed and not any others.

**Comment by jpollard-cs** [comment]
@cjbj what did you mean by 

> that's true in that scenario

is there a different way to use auto-commit such that it would commit all or nothing for all operations done on a single connection?

Our transactions are generally associated with a command which can result in several DB inserts/updates - it's important that either all of these inserts/updates succeed or they all fail.

**Comment by jpollard-cs** [comment]
@dmcghan I think adding support for this would involve replacing `node::MakeCallback` with [Nan::AsyncResource](https://github.com/nodejs/nan/blob/master/doc/node_misc.md#api_nan_asyncresource), but there may be more to it - it's been a very long time since I've done any C++.

**Comment by dmcghan** [comment]
@jpollard-cs 

> is there a different way to use auto-commit such that it would commit all or nothing for all operations done on a single connection?

That's what it does.

I think @cjbj is just saying that, while you can invoke `commit` to finish your transaction, setting `autoCommit` to `true` in the last `execute` call saves a round trip (piggybacks on another call) and is thus more performant and scalable. 

You gave this example:
```javascript
    await conn.execute(sql1, bindParams, { autoCommit: true });
    await conn.execute(sql2, bindParams, { autoCommit: true });
```

But it would look like this:
```javascript
    await conn.execute(sql1, bindParams);
    await conn.execute(sql2, bindParams, { autoCommit: true });
```

Of course, the same applies to the individual `execute` calls. If no work is being done in the middle tier to process intermediate results, then the entire transaction should be shipped over as a single PL/SQL call or a call to a stored procedure:

```javascript
    await conn.execute(plsql, bindParams, { autoCommit: true });
```

> I think adding support for this would involve replacing node::MakeCallback with Nan::AsyncResource, but there may be more to it - it's been a very long time since I've done any C++.

I can't claim to have ever done any work with C++! :) @anthony-tuininga mentioned that some things are being done in the C layer that will help support Async Hooks (more a consequence of older APIs being deprecated than anything else).

**Comment by jpollard-cs** [comment]
ah okay - thanks for clarifying @dmcghan! one thing that does not seem to be explicitly stated in the documentation is if, when using `autoCommit`, the transaction will be automatically rolled back if an error is encountered?

**Comment by anthony-tuininga** [comment]
>> I think adding support for this would involve replacing node::MakeCallback with Nan::AsyncResource, but there may be more to it - it's been a very long time since I've done any C++.

> I can't claim to have ever done any work with C++! :) @anthony-tuininga mentioned that some things are being done in the C layer that will help support Async Hooks (more a consequence of older APIs being deprecated than anything else).

That has already been changed in what will become node-oracledb 2.3.

**Comment by dmcghan** [comment]
> one thing that does not seem to be explicitly stated in the documentation is if, when using autoCommit, the transaction will be automatically rolled back if an error is encountered?

No, an automatic rollback will not be performed if an error is encountered.

**Comment by jpollard-cs** [comment]
thanks @anthony-tuininga - I look forward to that release!!
