### ISSUE TITLE
Question - Header Check Error using staging-packages

### ISSUE THREAD

**Issue by danilohgds** [oracle/node-oracledb#896]
When I run npm install with the module from the MAKE npmpackage, or run oracledbinstall.js manually

I get this header check failure: 

$ node oracledbinstall.js
oracledb TRACE In initDynamicProps
oracledb TRACE dynamicProps = { PACKAGE_JSON_VERSION: '2.2.9',
  GITHUB_TAG: 'v2.2.9',
  BINARY_BUILD_NAME: 'oracledb-v2.2.9-node-v48-win32-x64-oracledb.node',
  PACKAGE_FILE_NAME: 'oracledb-v2.2.9-node-v48-win32-x64.gz' }
oracledb TRACE In install
oracledb Beginning installation
oracledb TRACE In verifyBinary
oracledb TRACE Checking for binary at C:\Projects\teste\node_modules\oracledb\build\Release\oracledb.node
oracledb Verifying installation
oracledb TRACE In getSha C:\Projects\teste\node_modules\oracledb\build\Release\oracledb.node
oracledb TRACE sha = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
oracledb TRACE In getRemoteFileReadStream nexus.produbanbr.corp /repository/raw-downloadsv2.2.9/SHASUMS256.txt
oracledb TRACE In getProxyConfig nexus.produbanbr.corp
oracledb TRACE In getFileReadStreamBase nexus.produbanbr.corp /repository/raw-downloadsv2.2.9/SHASUMS256.txt
oracledb TRACE HTTP statusCode = 200
oracledb Build not found in SHASUMS256.txt
oracledb Continuing installation
oracledb TRACE In installBinary
oracledb TRACE In getRemoteFileReadStream nexus.produbanbr.corp /repository/raw-downloadsv2.2.9/oracledb-v2.2.9-node-v48-win32-x64.gz
oracledb TRACE In getProxyConfig nexus.produbanbr.corp
oracledb TRACE In getFileReadStreamBase nexus.produbanbr.corp /repository/raw-downloadsv2.2.9/oracledb-v2.2.9-node-v48-win32-x64.gz
oracledb TRACE HTTP statusCode = 200
oracledb TRACE In extract { licenseDest: 'C:\\Projects\\teste\\node_modules\\oracledb\\LICENSE.md',
  writeLicense: true,
  binaryDest: 'C:\\Projects\\teste\\node_modules\\oracledb\\build\\Release\\oracledb.node',
  compressedReadstream: [Object] }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)

Do you guys have any idea what is wrong ? I have been trying to fix this for hours.

**Comment by cjbj** [comment]
Did you try the ['manual install'](https://oracle.github.io/node-oracledb/INSTALL.html#manualextraction) method on your binaries `node extractpackage.js path=oracledb-v2.2.0-node-v57-darwin-x64.gz` ?  Tried another platform or version of Node.js?

**Comment by cjbj** [comment]
The binary package format is (from the [README](https://github.com/oracle/node-oracledb/blob/master/package/README.md)): 'The package uses a custom format with three components: length bytes (giving the length of the license file), the license file, and then the node-oracledb binary'.    If 'createpackage.js' builds it, the expectation is that 'extractpackage.js' (and the normal install) will be able to extract it.  I'd check a different platform.

When I bump versions, I bump them in package.json, package/package.json, src/njsOracle.h (+ various doc locations)

**Comment by danilohgds** [comment]
@cjbj, I dealt with the problem by doing --force and then node-gyp compiles it to get a binary.

I guess I should not have tinkered with the version value.

You can close this, thanks :)
