### ISSUE TITLE
Error: NJS-045: cannot load the oracle-db add-on binary

### ISSUE THREAD

**Issue by TikiLobel** [oracle/node-oracledb#898]
- Node.js version: 8.11.1
- 64-bit computer
- node-oracledb version: 2.0.15
- Instant Client version: 1.0.1 ( I think 12_2 but I cannot check...)
I used **npm install instantclient** to install, and i did it within the folder that my project resides (I opened a terminal from the folder in Visual Studio)
- I set the path variable through the Control Panel:  C:\users\tlobel\source\repos\Attempt1\Attempt1\node_modules\instantclient;C:\Users\tlobel\Downloads\VC_redist.x64;C:\Python27\;C:\Python27\Scripts;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\tlobel\AppData\Roaming\npm;

(In the path, I am unsure about whether to include 'node_modules' to instant client, since I see there is also once outside of the folder, which includes most of the contents - inside node_modules the instant client folder only has instantclient.js and a few other things)

When I try and run my code, which consists of:

const oracledb = require('oracledb')

I get the error:

_**Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.1 (win32, x64)
Cannot load C:\Users\tlobel\source\repos\Attempt1\Attempt1\node_modules\oracledb\build\Release\oracledb.node
DPI-1050: Oracle Client library must be at version 11.2 or higher
Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object.<anonymous> (C:\Users\tlobel\source\repos\Attempt1\Attempt1\node_modules\oracledb\lib\oracledb.js:68:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\tlobel\source\repos\Attempt1\Attempt1\node_modules\oracledb\index.js:1:80)
    at Module._compile (module.js:652:30)**_

My project set up looks like this:

![project](https://user-images.githubusercontent.com/38420352/39189687-816e470c-47db-11e8-8456-6c4f91cca9c3.PNG)

**Comment by cjbj** [comment]
@bchr02, this is your npm Instant Client package.  Can you take a look?

@TikiLobel Don't forget to install the VC Redistibutables. And restart any terminal window after changing PATH.  Personally I'd follow the instructions here https://oracle.github.io/node-oracledb/INSTALL.html#instwin and use the Instant Client ZIP files.

**Comment by TikiLobel** [comment]
I checked and I have instantclient 12.1.0.2.0, so i downloaded the 2010 redistributable and it still does not work

**Comment by TikiLobel** [comment]
With all methods I get the same error:

_**Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.1 (win32, x64)
Cannot load C:\Users\tlobel\source\repos\Attempt1\Attempt1\node_modules\oracledb\build\Release\oracledb.node
DPI-1050: Oracle Client library must be at version 11.2 or higher
Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

at Object.<anonymous> (C:\Users\tlobel\sourc


My paths are set correctly and installation of oracledb is successful but when I run the code this error happens...Any other solutions?

**Comment by cjbj** [comment]
> My paths are set correctly

From the errors, the PATH is not set OK.  

I haven't looked at @bchr02's package; maybe there's something I don't know.

**Comment by TikiLobel** [comment]
I'll try and organize what I have currently:

I have a User-variable in environment variables:

`PATH=C:\provisioning\instantclient;C:\Users\tlobel\Downloads\VC_redist.x64.exe;`

and a System Variable:

`PATH=%SystemRoot%\system32\WindowsPowerShell\v1.0;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\tlobel\Downloads\VC_redist.x64.exe;C:\provisioning\instantclient;`

and my NODE_PATH is unset for the time being.
I have a 64-bit computer
**Node** version 8.11.1
**npm** version 6.0.0
**node-oracledb** version 2.2

My folder structure looks like this:

![folders](https://user-images.githubusercontent.com/38420352/39462290-008beac0-4d19-11e8-9625-e151f64b5151.PNG)

The location of the oracledb.node that it is not managing to load is:

![node-folder](https://user-images.githubusercontent.com/38420352/39462319-4a0e465c-4d19-11e8-9414-9219b4671ae2.PNG)

I have downloaded the 2010 Redistributable for VS since I have the instant client version 12.1, and that is the file 'VC_redist.x64.exe' in my paths. (Not located in same folder as project, rather in Downloads folder)

The code fails and gives the error above at the line:

`const oracledb = require("oracldb");`

Any other information I can provide?
Thank you for your responses, I really appreciate your time...

**Comment by TikiLobel** [comment]
Sorted things out! Not sure what fixed what, but I did the following commands in an empty folder:

npm install oracledb
npm install instantclient
<download the VS redistributable, in my
all instantclient
<download the VS redistributable, in my case 2010 version>
Add the redistributable to my path variable after running it

Added the following  lines to my code:
`var path = require('path');
process.env['PATH'] = path.join(__dirname, '/instantclient') + ';' + process.env['PATH'];
var oracledb = require('oracledb');`

Vwalla...Could be it was a problem that I was doing npm install when there was already a package.json in the folder but really not sure...

**Comment by cjbj** [comment]
@TikiLobel I'm circling back on this after being away, what's the status?

**Comment by TikiLobel** [comment]
@cjbj It seems to have been a problem with the operating system itself, since I tried your instructions on another computer and it worked without a problem - Thanks for your help!

**Comment by cjbj** [comment]
@TikiLobel I'll close this then.  Thanks for the update.

**Comment by samizzy** [comment]
Hi i am having a similar issue,

> C:\Users\Samrat\Desktop\node_projects\aws_sts_webservice\node_modules\oracledb\lib\oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.4.1 (win32, x64)
Cannot load C:\Users\Samrat\Desktop\node_projects\aws_sts_webservice\node_modules\oracledb\build\Release\oracledb.node
Error while trying to retrieve text for error ORA-01804
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.


On my windows 10 machine, I have a local installation of oracle XE, i have installed vc++ redistributable 2005 and 2015.  Nodejs version is 10.4.1.
Also my path variable is,

> D:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Users\Samrat\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\Samrat\AppData\Roaming\npm

so it is pointing correctly to the bin folder.

**Comment by sudheer160540** [comment]
@TikiLobel did you resolve the oraceldb connecting issue.

 throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.2 (win32, x64)Node.js require() error was:
  DPI-1047: 64-bit Oracle Client library cannot be loaded: "C:\oracle\instantclient_12_2\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help
Node.js require() mapped to D:\oracle\node_modules\oracledb\build\Release\oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object.<anonymous> (D:\oracle\node_modules\oracledb\lib\oracledb.js:65:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\oracle\node_modules\oracledb\index.js:1:80)
    at Module._compile (module.js:652:30)

**Comment by cjbj** [comment]
@sudheer160540 (i) read the error message carefully (ii) open a new issue if you still have problems.
