### ISSUE TITLE
fail to install oracledb and have some error

### ISSUE THREAD

**Issue by xiecong135** [oracle/node-oracledb#899]
Node.js v 9.11.1  64-bit
windows10 17134.1

I found some errors like this during the installation:
1.oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
2.oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v59-win32-x64.gz
3.oracledb ERR! connect ETIMEDOUT 54.231.11.152:443
4.oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting
5.npm ERR! code ELIFECYCLE
6.npm ERR! errno 87
7.npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
8.npm ERR! Exit status 87
I didn't find this error(NJS-054) in INSTALL.html#troubleshooting and I think my network does not have a proxy.
How can I solve this problem? #

**Comment by xiecong135** [comment]
Thank you for simulating my environment. I noticed that you can't simulate the network environment. Then I change my network to use my proxy server and  I had successfully install it.
Thank you!

**Comment by xiecong135** [comment]
Thanks, I will learn it.

**Comment by xudatui** [comment]
666

**Comment by cjbj** [comment]
[I deleted an accidental or spam comment]
