### ISSUE TITLE
storing images

### ISSUE THREAD

**Issue by nousacademy** [oracle/node-oracledb#90]
I'm just wondering, is it recommended to store images using this ? Allowing user uploads of images.

**Comment by dmcghan** [comment]
@nousacademy I have a blog post on this topic here: https://jsao.io/2015/03/throttled-file-loading-with-node-js-oracle-database/

To put it simply, while it's possible to do this with the driver now, it's a bit tedious. When proper support for LOBs is added the code should become much simpler and more performant.

**Comment by nousacademy** [comment]
@dmcghan would you recommend any other that is better suited to do this?

**Comment by dmcghan** [comment]
@nousacademy When you say "any other", are you referring to any other Oracle Database driver? If so, then no, I wouldn't recommend any other. This is the official Oracle Database driver for Node.js and eventually we should see proper support for LOBs. Then all will be right in the world. :)

**Comment by nousacademy** [comment]
@dmcghan I meant any other besides Oracle in the meantime :D

**Comment by dmcghan** [comment]
@nousacademy I think it really comes down to the decision between the OS file system and a database. That really depends on your use case. Generally I'm a fan of using the database to store data, including images, but there are some cases where the file system would make more sense. 

If you're trying to decide between databases, then again, it really depends on your use case. I should probably say that I'm an Oracle employee and that I'm most familiar with Oracle Database as far as databases go. In my opinion, Oracle Database is a great database with a LOT of features to leverage: http://www.oracle.com/technetwork/database/database-technologies/index.html So no, I wouldn't recommend any other. ;)

**Comment by nousacademy** [comment]
In my case I just want to save one image at a time but about 3000 imgs, there not huge in size, about average size. I only have experience using NOSQL databases, using Node. :(

**Comment by dmcghan** [comment]
I see... Well, Oracle Database is a very robust database. It can be a little intimidating when just starting out. But stick with it, it's worth it! Have you seen this project: https://github.com/OraOpenSource/oraclexe-apex? It will help you get up and running with the XE (express edition) of Oracle Database.

**Comment by cjbj** [comment]
@nousacademy if you speak to people like Marcelle from http://www.piction.com/site/ she will convince you that you should be storing images in the database.  (Note, last time I checked, Piction were using a mix of technologies and scripting languages but not using Node.js)

**Comment by nousacademy** [comment]
@dmcghan @cjbj thanks guys for pointing me in the right direction, I'll be testing it out this week.
