### ISSUE TITLE
issue running .js file that requires oracledb from crontab

### ISSUE THREAD

**Issue by mrai1234** [oracle/node-oracledb#904]
Node's Version: v8.11.1
OS:  Oracle Linux 7.5

I am getting the following error when I try to run a .js file from user's crontab:
/home/mrai/node/node_modules/oracledb/lib/oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.1 (linux, x64)
Cannot load /home/mrai/node/node_modules/oracledb/build/Release/oracledb.node
Error while trying to retrieve text for error ORA-01804

Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from 
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

    at Object.<anonymous> (/home/mrai/node/node_modules/oracledb/lib/oracledb.js:68:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mrai/node/node_modules/oracledb/index.js:1:80)
    at Module._compile (module.js:652:30)

crontab -l has:
0 * * * * /usr/bin/sh /home/mrai/rss.sh

rss.sh has:
#!/bin/bash
cd /home/mrai/node
node rss.js &> /home/mrai/rss.log

On terminal, following works OK without any issues:
cd /home/mrai/node
node rss.js &> /home/mrai/rss.log

**Comment by cjbj** [comment]
Not having any environment set is a 'feature' of cron.  This is also why the [ldconfig](https://oracle.github.io/node-oracledb/INSTALL.html#instzip) method of adding the Oracle client libraries to the operating system library loading path is recommended.  If you don't want to use ldconfig, then make sure to set LD_LIBRARY_PATH (and other environment variables) in rss.sh.

**Comment by mrai1234** [comment]
I have already configured ldconfig (and also tried adding LD_LIBRARY_PATH in crontab).
But, still getting this error.

$ ldconfig -v
....
/u01/app/oracle/product/11.2.0/xe/lib:
	libxdb.so -> libxdb.so
	libuini11.so -> libuini11.so
	libsqora.so.11.1 -> libsqora.so.11.1
	libsqlplus.so -> libsqlplus.so
	libskgxp11.so -> libskgxp11.so
	libskgxns.so -> libskgxns.so
	libskgxn2.so -> libskgxn2.so
	libqsmashr.so -> libqsmashr.so
	libons.so -> libons.so
	libodmd11.so -> libodmd11.so
	libodm11.so -> libodm11.so
	libocrutl11.so -> libocrutl11.so
	libocrb11.so -> libocrb11.so
	libocr11.so -> libocr11.so
	libocijdbc11.so -> libocijdbc11.so
	libocci.so.11.1 -> libocci.so.11.1
	libntcpaio11.so -> libntcpaio11.so
	libnque11.so -> libnque11.so
	libnnz11.so -> libnnz11.so
	libnjni11.so -> libnjni11.so
	libldapjclnt11.so -> libldapjclnt11.so
	libhgotrace11.so -> libhgotrace11.so
	libheteroxa11.so -> libheteroxa11.so
	libhasgen11.so -> libhasgen11.so
	libemmas11.so -> libemmas11.so
	libdbcfg11.so -> libdbcfg11.so
	libcorejava.so -> libcorejava.so
	libclsra11.so -> libclsra11.so
	libclntsh.so.11.1 -> libclntsh.so.11.1
	libcell11.so -> libcell11.so
	libagtsh.so -> libagtsh.so.1.0
......

**Comment by dmcghan** [comment]
@mrai1234 

> and also tried adding LD_LIBRARY_PATH in crontab

Show us what you tried. Was the error exactly the same?

**Comment by cjbj** [comment]
With a full DB install such as Oracle XE, don't use ldconfig.  Make sure you set LD_LIBRARY_PATH and ORACLE_HOME and any NLS and timezone variables: you can run a command like 'env' in your shell to show what is set in your 'working' shell.  Make sure each directory in the path to Oracle software is readable/executeable to the crontab proces.

**Comment by mrai1234** [comment]
I just tried the following:
rss.sh has:
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin
export LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib
export NODE_PATH=/home/mrai/node/node_modules

cd /home/mrai/node
node rss.js &> /home/mrai/rss.log
echo $PATH &>> /home/mrai/rss.log
echo $LD_LIBRARY_PATH &>> /home/mrai/rss.log
echo $NODE_PATH &>> /home/mrai/rss.log

The error received in rss.log was:
/home/mrai/node/node_modules/oracledb/lib/oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.1 (linux, x64)
Cannot load /home/mrai/node/node_modules/oracledb/build/Release/oracledb.node
Error while trying to retrieve text for error ORA-01804

Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from 
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

    at Object.<anonymous> (/home/mrai/node/node_modules/oracledb/lib/oracledb.js:68:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mrai/node/node_modules/oracledb/index.js:1:80)
    at Module._compile (module.js:652:30)
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin
/u01/app/oracle/product/11.2.0/xe/lib
/home/mrai/node/node_modules

**Comment by dmcghan** [comment]
@mrai1234 I don't think you need to set NODE_PATH, it should be relative to the app you're running. What happens if you don't set that? 

Can you show us the code in your app where you require in the oracledb module?

**Comment by mrai1234** [comment]
Thanks. The issue is resolved.

1) rss.sh was changed to:
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin
export LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib
export NODE_PATH=/home/mrai/node/node_modules
export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe

cd /home/mrai/node
node rss.js &> /home/mrai/rss.log

2) I also removed the oracle libraries from ldconfig.

3) I will remove NODE_PATH and let you know, if anything breaks.

**Comment by mrai1234** [comment]
This is the final version of rss.sh that works:
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/lib64/qt-3.3/bin
export LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib
export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe

cd /home/mrai/node
node rss.js &> /home/mrai/rss.log

**Comment by cjbj** [comment]
Simple :)

**Comment by mcelotti** [comment]
I was able to skip the env setup just by adding "#!/bin/bash -l" to my script

**Comment by cjbj** [comment]
@mcelotti that's fine for many uses but if your script is run by someone else they may not have the library search path etc set up so it will fail.
