### ISSUE TITLE
Pool value connectionsInUse, connectionsOpen

### ISSUE THREAD

**Issue by mikollaay** [oracle/node-oracledb#91]
Pool value connectionsInUse, connectionsOpen reaches poolMax and does not decrease after connection.release. This is normal?

**Comment by cjbj** [comment]
@mikollaay Make sure you are releasing in all code paths, including the error handler.  Also check where you are monitoring the values. The `connectionsInUse` should drop with every release.  The `connectionsOpen` is subject to the `poolTimeout` value so it won't drop immediately (and if you aren't releasing, it won't ever drop).
