### ISSUE TITLE
Dropping Node 4 & 9 support in node-oracledb

### ISSUE THREAD

**Issue by cjbj** [oracle/node-oracledb#910]
Heads-up: As you know, Node.js 4 itself has [reached its end-of-life](https://github.com/nodejs/Release).  We are not planning on releasing future node-oracledb binaries for Node.js 4.

Now that Node.js 10 is available, we'd also like to drop Node.js 9 support, since Node.js itself will reach end-of-life soon in June.

The current plan is for the future node-oracledb 2.3 release to support Node 6, 8 and 10.

Comments welcome.

**Comment by cjbj** [comment]
Node-oracledb 2.3 is out with binaries for Node.js 6, 8 and 10.

**Comment by bbhad** [comment]
Hi cjbj,
looking for some help ,

on performance test getting below error when transactions are running around 4-6 tps.
 
2018-06-27T22:20:35.144Z pid:9185 worker:0 ERROR supervisor worker id 3 (pid 18193) accidental exit with SIGSEGV


RHEL7
oracledb@1.13.1
Node v4.6.2
NPM v2.15.11
strongloop v6.0.3
ora-client-12.1.0.2.0
what would be the correct version of oracledb to use with NodeJs4,unfortunately we are not able to update to node8 now

any help much appreciated,
thanks
bbhad

**Comment by cjbj** [comment]
@bbhad this smells like a duplicate of https://github.com/oracle/node-oracledb/issues/428#issuecomment-401404865 Check the answer there.  Good luck.

Next time, please open a new issue when you have a new problem.  And avoid [duplicate posts](https://github.com/oracle/node-oracledb/issues/933#issuecomment-401544951), since that wastes everyone's time.

**Comment by bbhad** [comment]
ok.. will do,thanks
