### ISSUE TITLE
Install fails behind authenticated proxy with environment variables set

### ISSUE THREAD

**Issue by Dhruv222** [oracle/node-oracledb#911]
Hi,

I am trying to install the oracledb library and i cant run the `npm install oracledb` even with the proxy variables set in both .zshrc and npm config.

I have a username and password proxy so let me know if that is the problem.

Here is the log
```
  npm install oracledb                                                                     [14:33:51]

> oracledb@2.2.0 install /Users/dhrushar/Documents/workspace/DBaS-backend/node_modules/oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v57-darwin-x64.gz
oracledb ERR! self signed certificate in certificate chain
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN DBaS@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

From the self signed certificate issue, i think it might related to the ssl but i have set the strict ssl to false in the npm config.

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js

_The script doesnt run because of the lack of oracledb package_
```
node -v                                                                                  
v8.11.1

npm -v                                                                                 
5.6.0
```

2. What is your node-oracledb version?
**it seems to install the 2.2.0 version**

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
**I am on a mac so i installed the way it was written in the docs and it works with sqldeveloper and was working before** 

4. What is your Oracle Database version?
**the driver is used to connect to a different databases and different versions which fall under the accepted categories**

5. What is your OS and version?
**mac OS Sierra 10.12.6**

6. What is your compiler version?  For example, with GCC, run `gcc --version`
```
gcc --version                                                                            [14:45:03]
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

7. What Oracle environment variables did you set?  How *exactly* did you set them?
**They are set in the .zshrc**
```
export OCI_LIB_DIR=/opt/oracle/instantclient
export OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
```

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
**(on mac) libclntsh.dylib**

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`npm install oracledb`

**Comment by cjbj** [comment]
- Can you show us that the proxy is set in the terminal before you run 'npm install'?  I.e. has it taken effect after you added it to the config files?  Also review https://github.com/oracle/node-oracledb/issues/909#issuecomment-388280097

- Can you review the [install manual](https://oracle.github.io/node-oracledb/INSTALL.html) - some of the steps you list are no longer relevant?

- Also review https://github.com/oracle/node-oracledb/blob/master/package/README.md about the error

If you can't fix your network or network settings, consider one of the alternative install methods mentioned in the instructions. e.g https://oracle.github.io/node-oracledb/INSTALL.html#manualextraction

**Comment by Dhruv222** [comment]
I checked the proxies by running the `curl https://google.com`. It gave me the following response.

```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

So I believe the proxies are set. Also running `echo $http_proxy` and `echo $https_proxy` return the proxy addresses with the user name and password appended. 
_Sorry cant show you the output as they are the company proxies and contain the username and password. If there is another way to confirm, please let me know._

I read somewhere that we need to set the terminal proxies because the request module uses it to download some stuff off of the github repo. I am thinking that the request module probably cant access the proxy data?(just spitballing here) Because I can install other packages which dont have this extra download from a node app.

**Comment by cjbj** [comment]
There is currently no support for installing via proxies that require authentication. 
If you want to replicate https://github.com/oracle/node-oracledb/pull/810, test your solution,  and get the OCA signed so we can merge a patch, I know users would appreciate it.

**Comment by Dhruv222** [comment]
Okay, I will create a pr for this by the end of week.

Thanks for the quick reply.
________________________________

**Comment by Dhruv222** [comment]
So do I just copy the file from the pr into a fork of mine? How do I proceed with this?

**Comment by cjbj** [comment]
@Dhruv222 Can you sign the [OCA](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md) and get it accepted before writing code?  Then you have to make sure your PR satisfies http://www.oracle.com/technetwork/oca-405177.pdf

Pro tip: Make sure you fill in the OCA form carefully so it doesn't have to be re-submitted.

**Comment by Dhruv222** [comment]
I have submitted the oca. Can you check and let me know?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Dhruv222** [comment]
I have also created a pr. https://github.com/oracle/node-oracledb/pull/912

**Comment by cjbj** [comment]
@Dhruv222 the proxies available to me don't need authentication.  Keep digging and you might find a solution!

**Comment by cjbj** [comment]
@Dhruv222 the OCA team say they'll look at your OCA in a few days when they process the next batch of submissions.

**Comment by cjbj** [comment]
[Code was merged to master](https://github.com/oracle/node-oracledb/pull/919) for this.

I'll close this issue and leave the [duplicate original](https://github.com/oracle/node-oracledb/issues/906) open until a release is made.
