### ISSUE TITLE
"NJS-054: Binary build/Release/oracledb.node was not installed"; installing oracledb globally with Node

### ISSUE THREAD

**Issue by MelonBall** [oracle/node-oracledb#914]
Hi,
I'm trying to install oracledb using Node v8. When I do `npm install` only, it works, but when I try `npm install -g oracledb` there is an error message.

I have Visual Studio Code 2015 with Visual C++.
I have Python 2.7.
I'm admin of my computer.

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from 
8.11.1

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  
instantclient basic windows x64 12.2
instantclient sdk windows x64 12.2

4. What is your Oracle Database version?
none

5. What is your OS and version?
windows 10

6. What is your compiler version?  For example, with GCC, run `gcc --version`
visual studio code 15

7. What Oracle environment variables did you set?  How *exactly* did you set them?
none

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
PATH : c:/oracle/instantclient
OCIINC_DIR : c:/oracle/instantclient/sdk/include
OCILIB_DIr : c:/oracle/instantclient/sdk/lib/msvc

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
npm install -g oracledb

10. What error(s) you are seeing?
![erreur](https://user-images.githubusercontent.com/35982323/40136933-36ba18ec-5917-11e8-8704-b53a7554fa48.png)

Thank you!

**Comment by cjbj** [comment]
Google and some legwork will be your friends to solve this.  If the non-global install works (when you are authenticated as the same user), then I don't see why 'npm install -g oracledb' would give a 'self signed certificate' error.

I expect the workaround for the 'self-signed certificate' error noted for testing in https://github.com/oracle/node-oracledb/blob/master/package/README.md will 'solve' the problem, but the certificate checks are there for a reason so I can't generally recommend disabling them.

I don't have a problem installing globally on macOS, even through our corporate proxy:

```
$ npm install -g oracledb

> oracledb@2.2.0 install /Users/cjones/.nvm/versions/node/v8.11.1/lib/node_modules/oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb Oracledb downloaded
oracledb Verifying installation
oracledb Binary SHA matches SHA in SHASUMS256.txt
oracledb 
oracledb ********************************************************************************
oracledb ** Node-oracledb 2.2.0 installation complete for Node.js 8.11.1 (darwin, x64)
oracledb **
oracledb ** To use the installed node-oracledb:
oracledb ** - You need to have the Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
oracledb **   Download from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
oracledb **
oracledb ** Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
oracledb ********************************************************************************

+ oracledb@2.2.0
added 1 package in 15.309s
```

**Comment by MelonBall** [comment]
I tried using NODE_TLS_REJECT_UNAUTHORIZED=0 and npm config set strict-ssl false separately, but never together... that did the trick! 

Thank you!
