### ISSUE TITLE
oracledb + ubuntu 16

### ISSUE THREAD

**Issue by mrgudzik** [oracle/node-oracledb#915]
hi!
I try to establish oracledb on ubuntu 16.04 AMD64 which works for vmware 8.

but I receive error:

gudzik@ubuntu:~/www/test/oradb$ npm i oracledb

> oracledb@2.2.0 install /home/gudzik/www/test/oradb/node_modules/oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="64")
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v64-linux-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v64-linux-x64.gz failed with code 404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN enoent ENOENT: no such file or directory, open '/home/gudzik/www/test/oradb/package.json'
npm WARN oradb No description
npm WARN oradb No repository field.
npm WARN oradb No README data
npm WARN oradb No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gudzik/.npm/_logs/2018-05-17T19_53_18_226Z-debug.log
gudzik@ubuntu:~/www/test/oradb$ 

on a new ubuntu I take the following steps:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential libssl-dev

sudo apt install curl
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

source ~/.profile

npm i -g npm

nvm install 10

npm install oracledb

what needs to be made for the oracledb installation???

help please!  
Thank you!

**Comment by cjbj** [comment]
> oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="64")

That's the problem.  

From the first point at https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting : "Did you get an HTTPS 404 failure? A pre-built node-oracledb binary package is probably not available on https://github.com/oracle/node-oracledb/releases for your Node.js version or operatiing system. Change your Node.js version or compile node-oracledb from source code."

Also see https://github.com/oracle/node-oracledb/issues/901

[If you have any suggestion how to make the install message more understandable, I'd be glad to hear them]
