### ISSUE TITLE
what is the combination for remote connectString

### ISSUE THREAD

**Issue by jhonyourangel** [oracle/node-oracledb#92]
Hi all,
I have a remote oracle database and i want to connect to it.

what is the connection string ?
is this correct : "host:port:SID" ? 

if not, what is the correct combination ?

**Comment by jhonyourangel** [comment]
found it
oracledb.getConnection( { user : "hr", password : "welcome", connectString : "hostname:port/service_name" }, . . .

**Comment by cjbj** [comment]
For the record, connections strings are described at https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionstrings

**Comment by jhonyourangel** [comment]
Hi All,
So i still have problems with the connectionString

Here how I've got the info:
Host_name = SELECT * FROM v$instance;
the port i already have it
Service_name = select value from v$parameter where name like '%service_name%';  
  
    var host_name = "//rs10xxx";
    var port = "2101";
    var service_name = "name.na.domain.com";

    var connectStr = host_name + ":" + port + "/" + service_name;



and i get this error : ora-12154: TNS: could not resolve the connect identifier


but if i use the following combination to connect:

    var host_name = "//rs10xxx.na.domain.com";
    var port = "2101";
    var service_name = "name";

    var connectStr = host_name + ":" + port + "/" + service_name;

i get the error:

ora - 12514 : TNS: listener does not currently know of service requested in connect descriptor

Can you help me up to assemble the string in the proper way please ?


Thank you

**Comment by cjbj** [comment]
`var host_name = "//rs10xxx";` is not getting to the DB server computer.

In the second case when do you have the full host & domain name, `var service_name = "name";` isn't recognized by the Oracle network listener.  Try running 'lsnrctl status' on the DB server machine and see what services are available.
