### ISSUE TITLE
installation by npm fails

### ISSUE THREAD

**Issue by mrdimaan** [oracle/node-oracledb#920]
### installation issue:

Hi I Reviewed the install instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
but I can not install module.
here is the log 

```
> oracledb@2.2.0 install /home/moein/Documents/tetst/node_modules/oracledb
> node package/oracledbinstall.js

oracledb TRACE In initDynamicProps
oracledb TRACE dynamicProps = { PACKAGE_JSON_VERSION: '2.2.0',
  GITHUB_TAG: 'v2.2.0',
  BINARY_BUILD_NAME: 'oracledb-v2.2.0-node-v57-linux-x64-oracledb.node',
  PACKAGE_FILE_NAME: 'oracledb-v2.2.0-node-v57-linux-x64.gz' }
oracledb TRACE In install
oracledb Beginning installation
oracledb TRACE In verifyBinary
oracledb TRACE Checking for binary at /home/moein/Documents/tetst/node_modules/oracledb/build/Release/oracledb.node
oracledb Verifying installation
oracledb Continuing installation
oracledb TRACE In installBinary
oracledb TRACE In getRemoteFileReadStream github.com /oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v57-linux-x64.gz
oracledb TRACE In getProxyConfig github.com
oracledb TRACE noProxy [ 'localhost',
  '127.0.0.0/8',
  '::1',
  '192.168.0.0/16',
  '192.168.8.1',
  '10.0.0.0/8',
  '172.16.0.0/12',
  '0.0.0.0/8',
  '10.0.0.0/8',
  '100.64.0.0/10',
  '127.0.0.0/8',
  '169.254.0.0/16',
  '172.16.0.0/12',
  '192.0.0.0/24',
  '192.0.2.0/24',
  '192.168.0.0/16',
  '192.88.99.0/24',
  '198.18.0.0/15',
  '198.51.100.0/24',
  '203.0.113.0/24',
  '224.0.0.0/3' ]
oracledb TRACE In getFileReadStreamByProxy github.com /oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v57-linux-x64.gz socks null
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v57-linux-x64.gz
oracledb ERR! getaddrinfo ENOTFOUND socks socks:80
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN enoent ENOENT: no such file or directory, open '/home/moein/Documents/tetst/package.json'
npm WARN tetst No description
npm WARN tetst No repository field.
npm WARN tetst No README data
npm WARN tetst No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR! 
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moein/.npm/_logs/2018-05-31T06_23_32_563Z-debug.log
```
## questions:

nodejs version: v8.11.2 x64

2. node-oracledb version: using just npm so it should be last version i think

3. Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
v12_2
installed by moving downloaded files in /opt/oracle

4. What is your OS and version? 
ubuntu 18.04

5. What is your compiler version?
7.3.0

7. What *exact* command caused the problem ?
npm i oracledb

**Comment by cjbj** [comment]
Thanks for the useful detail.  The root error seems to be `getaddrinfo ENOTFOUND socks socks:80`.  
What kind of proxy do you have - how do you normally access files over the network in Node.js? 

Proxy support in the binary downloader is pretty simple. In particular it doesn't handle authentication (see https://github.com/oracle/node-oracledb/pull/919) and the` no_proxy` support could be enhanced (as noted at the bottom of https://github.com/oracle/node-oracledb/blame/master/package/README.md).  PR's welcome.

To get you going immediately with node-oracledb, you may want to use https://oracle.github.io/node-oracledb/INSTALL.html#manualextraction or even https://oracle.github.io/node-oracledb/INSTALL.html#github

**Comment by mrdimaan** [comment]
I'm using tor but I haven't set proxy for npm and the terminal does not use my system proxy.
I started installation process from the beginning and the problem solved but finally I didn't find out why the error happened!
Thanks for the answer.

**Comment by cjbj** [comment]
@mrdimaan I'm glad you got it going.
