### ISSUE TITLE
Binary for node10

### ISSUE THREAD

**Issue by DayBr3ak** [oracle/node-oracledb#922]
Hello, I have run into an issue with binaries.
Any chance to have binaries for node 10.x

It seems it's already ready according to the readme, but I can't find them.

**Comment by cjbj** [comment]
Thanks for your interest!

The production doc is at https://oracle.github.io/node-oracledb/  Other doc on https://github.com/oracle/node-oracledb is for development (with some obvious exceptions like the CHANGELOG, LICENSE etc) - I should have added '-dev' when I updated the README.md. In the end, keep an eye on https://github.com/oracle/node-oracledb/issues/901 which will be updated when binaries are out.

Attendees of today's [Office Hours webcast](https://devgym.oracle.com/pls/apex/dg/office_hours/727) have a good idea of the timing :)
