### ISSUE TITLE
oracledb wont install on 32 bit OS.

### ISSUE THREAD

**Issue by mikemasD** [oracle/node-oracledb#923]
I have 32 bit Operating System. Have downloaded Node Js for 32 bit OS.
when i try to install oracledb(npm install oracledb) following logs are displayed:

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for architecture="ia32"
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v57-win32-ia32.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.
404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 I also tried installing the prerequisites: 

npm --add-python-to-path='true' --debug install --global windows-build-tools

> windows-build-tools@3.0.0 postinstall C:\Users\mikie\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225725
npm ERR! windows-build-tools@3.0.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 3221225725
npm ERR!
npm ERR! Failed at the windows-build-tools@3.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

How can we solve this issue.

Thanks

**Comment by cjbj** [comment]
The 'official' build instructions don't mention windows-build-tools, so it's not clear what instructions you are following or what commands you ran.  I do know some people have found that module useful. 
Unless someone quickly comments on the error when installing windows-build-tools, you should ask on that module's issues page.

It is worth reviewing https://oracle.github.io/node-oracledb/INSTALL.html#github

**Comment by mickeypearce** [comment]
Little off topic.. is there any specific reason that pre-built binary packages are not available for ia32 architecture?

**Comment by cjbj** [comment]
@mickeypearce we started with the popular platforms that we use day to day.  32-bit does seem old, I agree.

**Comment by sign0** [comment]
Same error on windows 7 x64 (node v5.9.1 & npm v.3.7.3)

```
> oracledb@2.2.0 install C:\Users\xxx\Desktop\xxx\node_modules\oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="47")
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v47-win32-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v47-win32-x64.gz failed with code 404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN xxx@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script 'node package/oracledbinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node package/oracledbinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
```

**Comment by anthony-tuininga** [comment]
Binaries for node-oracledb 2.2 are only provided for 4, 6, 8 and 9. Binaries for node-oracledb 2.3 will only be provided for 6, 8 and 10. Node v5 reached EOL almost two years ago! Perhaps upgrade to v6 at least?

**Comment by sign0** [comment]
I confused v59 with v5.9.x ...
It works properly with v8.11.2
Thanks !

**Comment by cjbj** [comment]
@mickeypearce I'll count your vote for it.

**Comment by hlblade** [comment]
Vote for 32bit windows prebuilt version

**Comment by cjbj** [comment]
@hlblade noted.  But plan to upgrade to 64-bit.

**Comment by thefill** [comment]
2020 here! Azure apps still come by default in 32bit host... don't you think its worth having this binary prebuilt?

**Comment by cjbj** [comment]
Noted.
