### ISSUE TITLE
I can't Node.js server hosting with oracledb

### ISSUE THREAD

**Issue by traeumen927** [oracle/node-oracledb#924]
Node.js version
9.8.0

node-oracledb version
2.3.0

Oracle client version
12.2.0.1.0

OS and version
macOS High Sierra 10.13.5

10. What error(s) you are seeing?

I want to create a node.js server to access the oracle database from the iPhone app.

The localhost has successfully accessed the Oracle database via the node.js server.

However, I was faced with an error in hosting it. (Hosting used firebase hosting.)

> Error: Error occurred while parsing your function triggers. Error: NJS-045: cannot load the oracledb add-on binary for Node.js 9.8.0 (darwin, x64) Node.js require() error was: DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help Node.js require() mapped to /Users/jeongyeon/Atom/BestianServer/functions/node_modules/oracledb/build/Release/oracledb.node Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html

To use oracledb in node.js, oracle instantclient must have a symbolic linked(ln-s)
**On Windows, environment variables must be set.

I think that when hosted I get an error because I do not recognize the symbolic link or environment variable setting.

Has anyone succeeded in hosting oracledb on nodejs? I would appreciate a little help.

Thank you.

**Comment by cjbj** [comment]
As I mentioned on https://stackoverflow.com/questions/50731865/node-js-server-hosting-with-oracledb/50731891#50731891 do you really need to use macOS for hosting?

**Comment by traeumen927** [comment]
no. I can host it in Windows environment.
However, it should be implemented through hosting rather than localhost.
I have also hosted it on Windows, but the hosting has not been done on the same issue.
Locally, it recognizes window's environment variables and symbolic links in mac.
I can successfully access the oracle database locally.
However, when I proceed with hosting, I get a cognitive error because I do not recognize it.

**Comment by dmcghan** [comment]
Perhaps Oracle's Application Container Cloud Service (ACCS) would be an option. In this blog post, I show how to connect ACCS to an entry-level database service from Oracle.
https://jsao.io/2017/07/connecting-a-node-js-app-in-accs-to-exadata-express/

However, that service doesn't support custom domains just yet (though it is on the road map).

Another option would be to host a VM or container. These are lower level, so they require more effort, but they do support custom domains.
