### ISSUE TITLE
VARCHAR2 outbound parameters not working properly

### ISSUE THREAD

**Issue by GadiTellez** [oracle/node-oracledb#925]
Node.js version 6.10.2
Node-oracledb version 2.3.0
Client Shared Library 64-bit - 12.2.0.1.0
Oracle 12.1.0.2.0
Linux Ubuntu on the client. CentOS 6 on the server.

Whenever I try to run a stored procedure with VARCHAR2 as output binding, I receive an error: 

ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at line 1

Various testing cases seem to indicate that the maxSize of the output variable is not correctly set for strings longer than a single character (i.e. when the returned value is a single character, the error is not produced, but two or more characters we run into the problem).

The most basic case that results in the error is with the following stored procedure:
```
create or replace PROCEDURE testproc (p_out OUT VARCHAR2)
AS
BEGIN
  p_out := 'GO';
END;
```
The client code is based on the example code provided in the test suite

```
var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');

oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function (err, connection) {
    if (err) { console.error(err.message); return; }

    var bindvars = {
      p_out:  { type: oracledb.STRING, dir: oracledb.BIND_OUT, maxSize: 200 }
    };
    connection.execute(
      "BEGIN testproc(:p_out); END;",
      bindvars,
      function (err, result) {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
        console.log(result.outBinds);
        doRelease(connection);
      });
  });

function doRelease(connection) {
  connection.close(
    function(err) {
      if (err) {
        console.error(err.message);
      }
    });
}
```
The problem goes away by changing the stored procedure to return a single character. For example:
```
create or replace PROCEDURE testproc (p_out OUT VARCHAR2)
AS
BEGIN
  p_out := 'G';
END;
```

**Comment by anthony-tuininga** [comment]
Hmm, I just tried your code exactly as given (except using a 12.2 database) and I didn't receive any errors. Perhaps adjust your code to display the client and database versions and the node-oracledb version to verify you're getting what you expect there. You might also want to try running the test suite since this sort of thing is tested there.

**Comment by cjbj** [comment]
I didn't see a problem even with 11.2 client and 11.2 database on Linux.  The DB had charset AL32UTF8.

**Comment by GadiTellez** [comment]
Hi both, thanks for the quick response. The fact that there is some test/examples with very similar code it's what makes this problem so frustrating. I will modify the code to display the client and database version and double check the DB charset to try to find any differences.

**Comment by cjbj** [comment]
@GadiTellez thanks for persevering.  If there's something we can improve, let us know.
