### ISSUE TITLE
 I want to web host node.js with oracledb.

### ISSUE THREAD

**Issue by traeumen927** [oracle/node-oracledb#927]
Hello. 
 

I have previously posed a question on the git hub oracledb (node_module) page.

>> https://github.com/oracle/node-oracledb/issues/924 

I want to make it accessible to oracle db on iOS and Android
I was able to access oracledb from localhost via node js

But, to use this, I do not want run the node.js server by always opening the terminal(or cmd) on my pc.
I want to host node.js because Turning on the server on the local host is very inefficient really inefficient.

Unfortunately, when hosting, the oracledb module does not seem to find the oracle instant client.
How do I proceed with this hosting?
If you have a way, please let me know in detail
Thank you

OS: macOS High Sierra 10.13.5
node -v : 6.11.3
oracledb -v : 2.3.0
oracle instant client : Client Shared Library 64-bit - 12.2.0.1.0

**Comment by cjbj** [comment]
I think this is a continuation of #924 and one of these should be closed.

Details such as how Instant Client is installed might be useful.  You might want to share more about the hosting environment since I'm not familiar with it.

**Comment by traeumen927** [comment]
I closed https://github.com/oracle/node-oracledb/issues/924
I watched and followed the quick start([https://oracle.github.io/node-oracledb/INSTALL.html#quickstart](url)), fully understood it and successfully executed it.
But I could not get any information about how to host it or use it more efficiently.
Is there no other way than an inefficient way? Do I really need to turn on the PC and turn on the node server in terminal or cmd to use it?
If you can not host it, do you have an effective plan that you know?
I really need help.
Usually this is the correct way to turn on my pc for 24 hours and turn on the nodejs server in the terminal(or cmd)?

**Comment by cjbj** [comment]
What do you mean 'host it'?  Where do you want to host it?  How do you want to host it?  Is this a question about starting Node.js or about using node-oracledb?

**Comment by cjbj** [comment]
Yay!  Your updated comment has the error.  It shows node-oracledb is being run on Linux 64-bit, not on macOS.  

- You need to upload the node-oracledb binary for 64-bit Linux.  I suspect you are uploading a macOS binary, hence the error 'invalid ELF header'

- You need to make sure the Instant Client for 64-bit Linux is uploaded.  The URL to get it from is given in the error message you posted: http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

- You need to follow the other instruction in the error about setting LD_LIBRARY_PATH or using ldconfig.  If you use LD_LIBRARY_PATH, you may find it easy to set this in a shell script that then calls Node.js.

If you have suggestions about improving the error message, let us know.

**Comment by traeumen927** [comment]
It means that I want to host oraclebedb through my web address by hosting the node.js code I created. 

For example, to access node.js through a web address other than 'localhost: 3000' or 'IP adrress: 3000'. 

Because I do not want my pc always on to use the node.js code I created. 
 

I am not good at English, so I ask for your understanding in advance.
If you do not understand me, ask me. 
 
 
-----Original Message-----

**Comment by dmcghan** [comment]
@traeumen927 There are many options for hosting Node.js applications in the cloud. The "right" solution for you will depend on your needs, budget, etc.

Considering that node-oracledb requires the OCI libraries, you'll need to choose a hosting provider that provides some flexibility when it comes to dependencies. For example, folks have used Heroku build packs to get things working in that environment: https://stackoverflow.com/questions/47561486/how-can-i-install-the-oracledb-npm-package-on-a-heroku-nodejs-server/47780428#47780428

What does your hosting provider allow?

As employees of Oracle, we know Oracle Cloud best. You have many options there, from simple to to more robust options. Here are a few options:

- Application Container Cloud Service (ACCS) - this option allows you to upload the application files via API calls or a GUI and then it creates a container and deploys it for you automatically. This option doesn't yet support custom domains, but it's on the roadmap. This is the closest option we have to something like Heroku and node-oracledb is automatically avaialble to applications. [I wrote about](https://jsao.io/2017/07/connecting-a-node-js-app-in-accs-to-exadata-express/) connecting this service to one of our entry level database services here.
- Container Cloud Service - this option is lower level. You create the container (with Node.js and the driver) and choose how to deploy them. Containers support DNS.
- Compute - this is the lowest-level option. You install everything and decide how to best deploy and maintain applications.
