### ISSUE TITLE
dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by jhonyourangel** [oracle/node-oracledb#93]
Hi all,
i get this error when i want to use the function "getConnection()"
```
dyld: lazy symbol binding failed: Symbol not found: __ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5ValueEEE
  Referenced from: /Users/AiU/IdeaProjects/Bucky/node_modules/oracledb/build/Release/oracledb.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5ValueEEE
  Referenced from: /Users/AiU/IdeaProjects/Bucky/node_modules/oracledb/build/Release/oracledb.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

how can it be fix ?

info:
to install it i've used those command lines:
```
cd Users/AiU/opt/oracle
unzip instantclient-basic-macos.x64-11.2.0.4.0.zip
unzip instantclient-sdk-macos.x64-11.2.0.4.0.zip
mv instantclient_11_2 instantclient
cd instantclient
ln -s libclntsh.dylib.11.1 libclntsh.dylib
ln -s libocci.dylib.11.1 libclntsh.dylib

export DYLD_LIBRARY_PATH=/Users/AiU/opt/oracle/instantclient:$DYLD_LIBRARY_PATH

export OCI_LIB_DIR=/Users/AiU/opt/oracle/instantclient
export OCI_INC_DIR=/Users/AiU/opt/oracle/instantclient/sdk/include
```

and when i run:
```node
process.env
```
i get

```
> process.env
{ TERM_PROGRAM: 'Apple_Terminal',
  SHELL: '/bin/bash',
  TERM: 'xterm-256color',
  TMPDIR: '/var/folders/v0/tbnyrr1n3m70gh9q81dq7l4h0000gn/T/',
  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.uE9Km6XYCd/Render',
  TERM_PROGRAM_VERSION: '343.6.2',
  TERM_SESSION_ID: '4DA7A589-F34B-4AF2-87FB-2CE0A10DC659',
  USER: 'AiU',
  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.hVKm6bPRfq/Listeners',
  __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
  PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin',
  PWD: '/Users/AiU',
  XPC_FLAGS: '0x0',
  XPC_SERVICE_NAME: '0',
  SHLVL: '1',
  HOME: '/Users/AiU',
  LOGNAME: 'AiU',
  LC_CTYPE: 'UTF-8',
  DISPLAY: '/private/tmp/com.apple.launchd.rwxxhWxvMB/org.macosforge.xquartz:0',
  _: '/usr/local/bin/node' }
> 
```
Searching on the internet i've found a few things about mySQL very similar error.
The fix for mySQL was setting the  DYLD_LIBRARY_PATH , but i've did that a few times and nothing changed.

What could it be the problem?

thank you for the support and patience

**Comment by cjbj** [comment]
Is Node.js running in the same process that you are setting DYLD_LIBRARY_PATH in?  Are you using 'sudo' anywhere? If your script has some relatively complex process management, have you checked that a simple example works?

**Comment by jhonyourangel** [comment]
hi thanks for answering.
1. i don't fully understand your question but i guess the answer should be: 
``` echo $DYLD_LIBRARY_PATH
/Users/AiU/node_projects/opt/oracle/instantclient:
```
( interesting, at the first call of 
``` echo $DYLD_LIBRARY_PATH ```
 in the terminal the returning value was nothing/empty, hmmm ....

2.i'm not using sudo anywhere.

3.my script is simple, is just a db connection. here is the script from app.js:
``` 
var oracledb = require('oracledb');


oracledb.getConnection(
    {
        user          : "user",
        password      : "pass",
        connectString : "[host]:1529/[sid]"
    },
    function(err, connection)
    {
        if (err) {
            console.error(err.message);
            return;
        }
        connection.execute(
            "SELECT * "
            + "FROM items_table ",
            [180],
            function(err, result)
            {
                if (err) {
                    console.error(err.message);
                    return;
                }
                console.log(result.rows);
            });
    });
```

**Comment by cjbj** [comment]
What OS X version, Xcode version and Node version are you using?

**Comment by cjbj** [comment]
@jhonyourangel did you resolve this?  Was it `$DYLD_LIBRARY_PATH` not being set?

**Comment by jhonyourangel** [comment]
Hi,
so i've solved the problem.
This comment will be answered in 3 sections: 
1. Answer to last question
2. My Possible Fix
3. My Last Install sequence
( my terminal has white background so i've delimited the screenshots with ( -------- screenshot --------- ) 
1. Answer to last question:
OS X Yosemite: 10.10.3 (14D98g)
XCode : 6.2 (6C131e)
i believe that i was missing the xcode command line tools

2. My Possible Fix
i've installed the:
*.xcode command line tools
*.node version v0.10.35
*.node-oracledb from npm v5.0
*.using a IDE ( intelij IDEA ) that is setting the $DYLD_LIBRARY_PATH at run time 

-------- screenshot ---------
![pic1](https://cloud.githubusercontent.com/assets/2562455/7703877/1a549842-fe3b-11e4-914b-1abda80e6ae3.png)

-------- screenshot ---------
 (info): it looks like my DYD_LIBRARY_PATH is empty all the time
-------- screenshot ---------
![terminal](https://cloud.githubusercontent.com/assets/2562455/7703913/43f572de-fe3b-11e4-8064-507e6529b575.png)
-------- screenshot ---------

3. My Last Install sequence:
    1. Download the 'basic' and 'SDK'  oracle files from [oracle site] (http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html)  and put them into the directory :
/Users/yourUserName
    2. Create a folder into /Users/yourUserName called opt
    3. Inside opt newly create folder create another one called 'oracle'
    4. Move the 2 files downloaded from oracle to that directory ( /Users/yourUserName/opt/oracle )
    5. Download Node.js version 10 or 10.35 and install it 
    6. Open terminal and type:

```
export PATH=/usr/local/bin:$PATH

cd /Users/yourUserName/opt/oracle
unzip instantclient-basic-macos.x64-11.2.0.4.0.zip
unzip instantclient-sdk-macos.x64-11.2.0.4.0.zip
mv instantclient_11_2 instantclient
cd instantclient
ln -s libclntsh.dylib.11.1 libclntsh.dylib
ln -s libocci.dylib.11.1 libocci.dylib

export DYLD_LIBRARY_PATH=/Users/yourUserName/opt/oracle/instantclient:$DYLD_LIBRARY_PATH

export OCI_LIB_DIR=/Users/yourUserName/opt/oracle/instantclient
export OCI_INC_DIR=/Users/yourUserName/opt/oracle/instantclient/sdk/include

npm install oracledb
```

Now if i try on running the example code from the terminal i get the error : 
-------- screenshot ---------
![Uploading not working from terminal.png…]()
-------- screenshot ---------


but if i call first 
```
export DYLD_LIBRARY_PATH=/Users/yourUserName/opt/oracle/instantclient:$DYLD_LIBRARY_PATH
```
 in the terminal and then the example is working like a charm, or all most ( except the TNS error, since i have problems on configuring the connectString )
see screenshot:
-------- screenshot ---------
![working](https://cloud.githubusercontent.com/assets/2562455/7704407/64944062-fe3e-11e4-86a2-c9d50b809963.png)
-------- screenshot ---------

So for now everything is ok.
Thank You very much for your support.

**Comment by cjbj** [comment]
@jhonyourangel the install doc https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx mentions twice that DYLD_LIBRARY_PATH is needed at runtime.  Please let me know if the wording is confusing.
