### ISSUE TITLE
This isn't Issue... just Question

### ISSUE THREAD

**Issue by newsam202** [oracle/node-oracledb#931]
hello.

i using node-red

i cann't found any document about oracledb node attribute.

What's different between 
(1)	send single query result message 
(2)	send multiple query result messages

I really want to know that

**Comment by dmcghan** [comment]
@newsam202 I'm not sure I understand your question. Could you please clarify?

**Comment by newsam202** [comment]
@dmcghan 
I want to know the difference between the two options in node-red.
==================================================
(node-red => Edit oracledb Node => Query results => Action (list)
- Action list
  ignore query result
  send single query result message
  send multiple query result messages
===================================================
Both return results, but I wonder what the difference is in using them.

**Comment by dmcghan** [comment]
@newsam202 A link to the content you're displaying would be helpful.

**Comment by newsam202** [comment]
@dmcghan i'm attach action list capture image

[https://t1.daumcdn.net/cfile/tistory/99DBC5435B3032542D](url)

**Comment by danilohgds** [comment]
Hi Sam, allow me to jump in the conversation @dmcghan 

Node-red is a library for IoT development, originally developed by IBM. @newsam202 I believe you would probably get a better understanding from folks from node-red as their development is unrelated to the node-oracledb development.

github: https://github.com/abreits/node-red-contrib-oracledb
flow documentation: https://flows.nodered.org/node/node-red-contrib-oracledb

I've used node-red so the differences are as follows:

ignore query result
- This does not send payload responses over to listening clients.
send single query result message
- Send the query result as a single payload for your clients
send multiple query result messages
- Sends the query over in multiple messages, usually through splitting or index-based of the array.

```typescript
var msg1 = { payload:"first out of output 1" };
var msg2 = { payload:"second out of output 1" };
var msg3 = { payload:"third out of output 1" };
var msg4 = { payload:"only message from output 2" };
return [ [ msg1, msg2, msg3 ], msg4 ];
```
Hope this helps you out.
