### ISSUE TITLE
Installing from Git installs the wrong version of the package

### ISSUE THREAD

**Issue by jbhue** [oracle/node-oracledb#934]
I want to install version 2.3.0 of the oracledb package and compile it from source. When I run the following command `npm install oracle/node-oracledb.git#v2.3.0` I get version `oracledb@3.0.0-dev` of the package installed.

1. Show that oracledb isn't installed

```
$ npm list | grep oracle # on output
```

2. Install oracledb using [provided command](https://oracle.github.io/node-oracledb/INSTALL.html#-2-quick-start-node-oracledb-installation) 

```
$ npm install oracle/node-oracledb.git#v2.3.0
+ oracledb@3.0.0-dev
added 2 packages in 22.693s
```

3. Confirm that version 2.3.0 wasn't what was installed

```
$ npm list | grep oracle
-- oracledb@3.0.0-dev (github:oracle/node-oracledb#d8453812def46c9d04c0fb3cd75a7c8fbdf40aee)
```

Am I doing something wrong?

Software versions:

Git 2.18.0
node: v8.9.4
npm: 5.6.0
OS: Oracle Linux Server release 6.9

**Comment by anthony-tuininga** [comment]
I just tried the command you specified and got 2.3.0 as expected. This was on Linux with node 8.11.3. What platform and Node.js version are you using?

**Comment by jbhue** [comment]
@anthony-tuininga 

Git 1.7.1
node: v8.9.4
npm: 5.6.0
OS: Oracle Linux Server release 6.9

**Comment by anthony-tuininga** [comment]
Oops. Now I see you included that information at the end of the first message. Sorry!

I tried node 8.9.4 but didn't see any differences. I am using git 2.17.1. You may wish to try a newer version of git just to see if that is an issue. I know that the git version on Oracle Linux 6 is well behind the times and you can run into some difficulties as protocols have changed -- and GitHub assumes that everyone is running something a bit newer. :-)

**Comment by jbhue** [comment]
@anthony-tuininga I actually modified the original post when I needed to respond from you. I will take that advice and report back. Thank you very much.

**Comment by jbhue** [comment]
@anthony-tuininga I was able to get Git upgraded to 2.18.0 and the exact same sequence happened to me described in the original post. Any advice?

**Comment by anthony-tuininga** [comment]
Can you provide the output of 'npm install --verbose oracle/node-oracledb.git#v2.3.0'?

**Comment by jbhue** [comment]
@anthony-tuininga 
[output of npm install verbose](https://github.com/oracle/node-oracledb/files/2146447/git.install.verbose.txt)

**Comment by anthony-tuininga** [comment]
It seems like you already have it installed somewhere or the directory where you are running the npm command has some leftovers from a previous run. You can look into that further and attempt to clean up....or you could simply use git to create a clone as follows:

```
git clone https://github.com/oracle/node-oracledb.git
git submodule init
git submodule update
git checkout v2.3.0
git submodule update
npm install
```

Its a bit more wordy than the npm install command....but it will work. :-)

**Comment by jbhue** [comment]
Thank you @anthony-tuininga and @cjbj I have already tried removing lock and node_modules wit no luck. I will try to clear the npm cache and see what that does.

In the meantime I found this [in the docs](https://oracle.github.io/node-oracledb/INSTALL.html#393-install-the-add-on)

`npm install https://github.com/oracle/node-oracledb/releases/download/v2.3.0/oracledb-src-2.3.0.tgz`

and it works for me

**Comment by cjbj** [comment]
@jbhue thanks for the update.  Let us know if you want to keep this open - though I don't think we have any other pearls of wisdom to impart.

The 3.0-dev code on master branch is pretty solid.  If you get a chance to test it too, let us know.

**Comment by jbhue** [comment]
Thank you @cjbj  and @anthony-tuininga for helping me with this and it can be closed.

**Comment by anthony-tuininga** [comment]
You're welcome. Thanks for following up.
