### ISSUE TITLE
Strange behavior with float in v2.2.0

### ISSUE THREAD

**Issue by SkyKilla** [oracle/node-oracledb#935]
`select round(112195.76000000001, 2) from dual`
and result is
112195.7600000000**1**

with other client on the same machine result is 
112195.76

**Comment by anthony-tuininga** [comment]
Which other client? You can take a look at issue #638 and the issues related to it for some additional information on this.

**Comment by SkyKilla** [comment]
Thanks!

**Comment by cjbj** [comment]
@SkyKilla also see the doc https://oracle.github.io/node-oracledb/doc/api.html#numberhandling
