### ISSUE TITLE
NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.3 (linux, x64)

### ISSUE THREAD

**Issue by Ventis** [oracle/node-oracledb#939]
Hi,

I'm creating a project where the Oracle DB is not under our management (we have the credentials and the URL) but we're creating a Nodejs REST API for frontend's to interact with it.

For this we're using a Docker container based on the `collinestes/docker-node-oracle` image but we've also tried creating our own image based on this [tutorial](https://blogs.oracle.com/opal/a-node-oracledb-web-service-in-docker). I always get the same error:
[https://gist.github.com/Ventis/7a43a2dc4ba7d803048e99054301cddb](https://gist.github.com/Ventis/7a43a2dc4ba7d803048e99054301cddb)

I checked the troubleshooting guide, I checked the installation guide several times, to no avail.

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
64-bit

2. What is your node-oracledb version?
2.3.0

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
64-bit, it's contained within the docker image. The Dockerfile of the image used:
[https://github.com/CollinEstes/docker-node-oracle/blob/8/Dockerfile](https://github.com/CollinEstes/docker-node-oracle/blob/8/Dockerfile)

4. What is your Oracle Database version?
Not applicable yet, the Oracle Database is out of our management

5. What is your OS and version?
MacOS High Sierra 10.13.5 but in the Docker image:
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
```

6. What is your compiler version?  For example, with GCC, run `gcc --version`
The image is using a precompiled binary

7. What Oracle environment variables did you set?  How *exactly* did you set them?
None, all should be set in the Docker image. As I understand it (looking at the Dockerfile of the image) the env vars set are:
```
ENV LD_LIBRARY_PATH="/opt/oracle/instantclient"
ENV OCI_HOME="/opt/oracle/instantclient"
ENV OCI_LIB_DIR="/opt/oracle/instantclient"
ENV OCI_INCLUDE_DIR="/opt/oracle/instantclient/sdk/include"
ENV OCI_VERSION=12
``` 

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
In the Docker image: `/opt/oracle/instantclient`

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`node src/index.js`

10. What error(s) you are seeing?
[https://gist.github.com/Ventis/7a43a2dc4ba7d803048e99054301cddb](https://gist.github.com/Ventis/7a43a2dc4ba7d803048e99054301cddb)

I've tried so many things already and I'm kinda running out of ideas. I hope some experts here know what is causing these problems.

**Comment by cjbj** [comment]
- The https://github.com/CollinEstes/docker-node-oracle/blob/8/Dockerfile doesn't run ldconfig after setting /etc/ld.so.conf.d/oracle-instantclient.conf which is surprising.  Note our Dockerfile does call it: https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile#L34  Yes, the LD_LIBRARY_PATH _probably_ works anyway.

- There may be reasons, but do you really need to use Ubuntu for the container?  Why not use the Oracle Linux image which runs a tested Linux distribution.

- The OCI_* env variables you list in 7 are for the unrelated (obsolete) 'oracle' module, not for this 'oracledb' module.  If the prebuilt oracledb binary works for you (which it probably does), you don't need to set any of them.

- Fundamentally the problem is 'invalid ELF header'.  I don't know which library is giving this.  The node-oracledb module was built on Oracle Linux 6, which means a particular glibc is needed.  What's your Dockerfile - where is the 'npm install' being run?

**Comment by Ventis** [comment]
@cjbj Thx for your reply.

My Dockerfile containers the following:
```
FROM collinestes/docker-node-oracle:8

WORKDIR app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY package.json .
RUN npm install

COPY . .
RUN ./build.sh

CMD [ "./up.sh" ]
```

The `build.sh` and `up.sh` script don't really do anything in dev mode besides starting the node server.

**Comment by dmcghan** [comment]
@Ventis The docker image your referencing seems to be using some older installation techniques. I created a new docker file based on that one and yours:

```Dockerfile
# INSTALL UBUNTU
FROM node:8

#INSTALL LIBAIO1 & UNZIP (NEEDED FOR NODE-ORACLEDB)
RUN apt-get update \
 && apt-get install -y libaio1 \
 && apt-get install -y build-essential \
 && apt-get install -y unzip \
 && apt-get install -y curl

#ADD ORACLE INSTANT CLIENT
RUN mkdir -p opt/oracle
ADD ./oracle/linux/ .

# 12.2
RUN unzip instantclient-basic-linux.x64-12.2.0.1.0 -d /opt/oracle

ENV LD_LIBRARY_PATH="/opt/oracle/instantclient_12_2"

WORKDIR app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY package.json .
RUN npm install

COPY ./test.js .
RUN node ./test.js
```

This could be simplified further, but I'll stop here. 

Here's the contents of test.js:

```js
const oracledb = require('oracledb');

console.log(oracledb);
```

**Comment by cjbj** [comment]
Some other tips:

In general I'd recommend using ldconfig over LD_LIBRARY_PATH.  There are too many places where environment variables are a pain, e.g. when trying to pass them to a PHP extension invoked via Apache, or in other contexts where the environment is scrubbed for security.

For a lightweight, "production" application you could just install the minimal set of files from the Instant Client Basic Light package.  With 12.2 Basic Light the necessary files are:
```
libclntsh.so.12.1
libclntshcore.so.12.1
libipc1.so
libmql1.so
libnnz12.so
libociicus.so
libons.so
```

You may not need build-essential unless you are compiling node-oracledb - a quick test will verify this.

**Comment by Ventis** [comment]
@cjbj Thx for the Dockerfile. I tested it and after some expansion of functionalities, I'm able to do queries from the `test.js`. However, in my project I still get the same error. I did notice the following line in the error message:

`at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)`

Is it possible that `node-oracledb` doesn't play nice with Babel? I changed `import oracledb from 'oracledb'` to a `require` statement but it doesn't seem to make any difference.

**Comment by hmrasi** [comment]
Hi,

I'm getting the following error when im trying to getConnection with the oracledb module. 
Imported the module as --> import {oracledb} from "oracledb";

WARNING in ./node_modules/oracledb/lib/oracledb.js
48:21-45 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\web
pack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\we
bpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\webpack\lib\Compilation.js:56
1:9)
    at applyPluginsParallel.err (C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\webpack\lib\Compiler.js
:502:17)
    at C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\webpack\lib\Compilation.js:507:1
1)
    at processModuleDependencies.err (C:\Users\hamadasi\WebstormProjects\Data_Injesion\IngestionFramework\src\bin\Ingestion_Framework Angular\node_modules\webpack\lib\Compil
ation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/oracledb/lib/oracledb.js
 @ ./node_modules/oracledb/index.js
 @ ./src/app/hero-form/hero-form.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.


Thanks in Advance.

**Comment by Ventis** [comment]
Doesn't look like Babel is the problem since I refactored my code to work without Babel and it still throws the same error.

**Comment by dmcghan** [comment]
@Ventis Are you saying you're using the new Dockerfile that worked with **test.js**, but you get the same errors with your project? Or is your project still using the old Dockerfile?

When do you get the error, when you run Babel or when you run the app?

**Comment by Ventis** [comment]
@dmcghan I created a new project and I used the new Dockerfile that worked with *test.js*. That worked.

But when I use that Dockerfile in my own project I get the same error that I got with my old Dockerfile. I removed the containers and images and rebuild to rule out cached containers/images.

I get the error when I run the app. In fact, I even copied the test.js file into my project, ran that and it still gives same error.

**Comment by Ventis** [comment]
I got it working! Though it's not entirely clear why it works now. After consulting with a colleague, he checked out my project and build it and it worked. Consequently, I did a complete wipe of all my cached docker images, containers,..., no sigar. Then I did the same thing again and restarted my laptop before rebuilding it and it worked! So it must have been a Docker caching issue but no idea which image was giving me problems (node:8 perhaps?).

**Comment by cjbj** [comment]
Phew!

**Comment by ashokkumarsand** [comment]
getting error /app/node_modules/oracledb/lib/oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.9.4 (linux, x64)
Cannot load /app/node_modules/oracledb/build/Release/oracledb.node
/app/node_modules/oracledb/build/Release/oracledb.node: invalid ELF header
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from 
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

    at Object.<anonymous> (/app/node_modules/oracledb/lib/oracledb.js:68:13)

**Comment by cjbj** [comment]
@ashokkumarsand read the installation manual and open a new issue if symptoms persist.  Thanks.

**Comment by eliskaachee** [comment]
@ashokkumarsand, did you open a new issue, or were you able to fix it? I'm getting the same error.

**Comment by guilhermeBBarros** [comment]
Me too, same issue here. Any onde can help?

**Comment by cjbj** [comment]
Installation issues are best addressed by closely following the [installation manual](https://oracle.github.io/node-oracledb/INSTALL.html).  There are lots of different starting points and possible combinations of factors (such as operating system variances and network access) so there are several methods.  One person's install problem may be unrelated to another person's.  If symptoms persist, open a new issue so you can answer the issue template questions.
