### ISSUE TITLE
gyp: Undefined variable oci_lib_dir in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by GaryFurash** [oracle/node-oracledb#94]
I'm installing on Windows. After setting python, vcvars64.bat (for vc11), etc., and I enter

npm install -g oracledb

it gives the error

gyp: Undefined variable oci_lib_dir in binding.gyp while trying to load binding.gyp

even though oci_lib_dir points to the (valid) directory

here are my environment variables:

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\furashg\AppData\Roaming
CLINK_DIR=C:\Program Files (x86)\clink\0.4.4
CommandPromptType=Cross
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=UITS-GARFUR
ComSpec=C:\Windows\system32\cmd.exe
CYGWIN_HOME=C:\Apps\Cygwin64
DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\
FP_NO_HOST_CHECK=NO
Framework35Version=v3.5
FrameworkDir=C:\Windows\Microsoft.NET\Framework\
FrameworkDIR32=C:\Windows\Microsoft.NET\Framework\
FrameworkDIR64=C:\Windows\Microsoft.NET\Framework64
FrameworkVersion=v4.0.30319
FrameworkVersion32=v4.0.30319
FrameworkVersion64=v4.0.30319
HOMEDRIVE=C:
HOMEPATH=\Users\furashg
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\8.0\include\shared;C:\Program Files (x86)\Windows Kits\8.0\include\um;C:\Program Files (x86)\Windows Kits\8.0\include\winrt;
JAVA_HOME=C:\Progra~1\Java\jdk1.6.0_34
LD_LIBRARY_PATH=C:\Apps\instantclient_12_1
LIB=C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\LIB\amd64;C:\Program Files (x86)\Windows Kits\8.0\lib\win8\um\x64;
LIBPATH=C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\LIB\amd64;C:\Program Files (x86)\Windows Kits\8.0\References\CommonConfiguration\Neutral;\Microsoft.VCLibs\11.0\References\CommonConfiguration\neutral;
LOCALAPPDATA=C:\Users\furashg\AppData\Local
LOGONSERVER=\\PANTHER
NLS_LANG=.UTF8
NODE_HOME=C:\Apps\nodejs
NODE_PATH=C:\Apps\nodejs;C:\Users\furashg\AppData\Roaming\npm\node_modules
NUMBER_OF_PROCESSORS=4
OCI_HOME=C:\Apps\instantclient_12_1
OCI_INC_DIR=c:\Apps\instantclient_12_1\sdk\include
OCI_LIB_DIR=c:\Apps\instantclient_12_1\sdk\lib\msvc\
OC_VERSION=12
ORACLE_HOME=C:\Apps\instantclient_12_1
OS=Windows_NT
Path=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\x86_amd64;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 11.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.0\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools;;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\Lib;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\DLLs;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\Lib\lib-tk;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Progra~1\Java\jdk1.6.0_34\bin;C:\Program Files (x86)\Skype\Phone\;C:\Apps\nodejs\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Apps\Git\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Apps\WinMerge;C:\Apps\nodejs;C:\Users\furashg\AppData\Roaming\npm\node_modules;C:\Apps\instantclient_12_1;C:\Users\furashg\AppData\Roaming\npm;C:\Users\furashg\bin;C:\Apps\instantclient_12_1\vc11
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
Platform=x64
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=CLINK $P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
PYTHONHOME=C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64
PYTHONPATH=C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\Lib;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\DLLs;C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\Lib\lib-tk
PYTHON_2_HOME=C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64
PYTHON_3_HOME=C:\Apps\WinPython-64bit-3.3\python-3.3.5.amd64
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TCL_LIBRARY=C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\tcl\tcl8.5
TEMP=C:\Users\furashg\AppData\Local\Temp
TK_LIBRARY=C:\Apps\WinPython-64bit-2.7\python-2.7.9.amd64\tcl\tcl8.5
TMP=C:\Users\furashg\AppData\Local\Temp
TNS_ADMIN=C:\Users\Public\instantclient_12_1\network\admin
TRIREME_CLASSPATH=C:\Apps\instantclient_12_1\ojdbc7.jar
USERDNSDOMAIN=CATNET.ARIZONA.EDU
USERDOMAIN=CATNET
USERNAME=furashg
USERPROFILE=C:\Users\furashg
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\
VIM_HOME=C:\Apps\vim\vim74
VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 11.0\
windir=C:\Windows
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\8.0\
WindowsSdkDir_old=C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

**Comment by cjbj** [comment]
Check some of the previous issues where people have pointed out how & where to set the variables.
Check that the variables are set in the window that you run 'npm install' in.

I noted you have LD_LIBRARY_PATH set, which is a UNIX variable.  OC_VERSION looks like a typo from Joe Ferner's node driver OCI_VERSION. This isn't needed for node_oracledb.

**Comment by mikollaay** [comment]
What version node.js? I had the same problem with Node v.0.12
Specified in package.json: "node" : ">=0.10.28 <0.11"

**Comment by antcoder** [comment]
same problem node 0.12

**Comment by cjbj** [comment]
I sure wish that package.json version check was honored on Windows.

**Comment by StigmaKim** [comment]
I had the same problem  several times.

I resolved it as downgrading node js version from .12.xx to 0.10.38 with nvm-windows( I use win7 64it)

and It works everytime. I installed 3 times.

**Comment by mikollaay** [comment]
I also

**Comment by cjbj** [comment]
@GaryFurash I'll close this as resolvable by downgrading to the supported 0.10 branch.
There is a pull request that gives 0.12 support at https://github.com/oracle/node-oracledb/pull/43
