### ISSUE TITLE
Error: NJS-009: invalid number of parameters

### ISSUE THREAD

**Issue by Shubhangi-yadav** [oracle/node-oracledb#940]
*Delete unnecessary parts of this template.*

### For general questions:
I have used oracledb and node js.
I have made a user table having id as autoincremented value .I want to fetch the last inserted row id and send it to the next function dodisplay and use it . I am having unable to figure out how to bind in and out binding parameters in same code. Please figure out the error and suggest the correct solution.
Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Use a gist for screen output and logs: see https://gist.github.com/ **Do not paste long output into this issue**.

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

- Review the install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

- Review the troubleshooting tips https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#troubleshooting

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js 64 bit

2. What is your node-oracledb version? 2.3.0

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed? 64 bit .added to the path

4. What is your Oracle Database version? 11g

5. What is your OS and version? windows 10

6. What is your compiler version?  For example, with GCC, run `gcc --version`  --

7. What Oracle environment variables did you set?  How *exactly* did you set them?
added oracle to the path

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as? no installation issues

10. What error(s) you are seeing?

:\Users\User\Desktop\web-app\project\node_modules\oracledb\lib\util.js:80
    throw new Error(getErrorMessage(errorCode, messageArg1));
    ^

Error: NJS-009: invalid number of parameters
    at Object.assert (c:\Users\User\Desktop\web-app\project\node_modules\oracledb\lib\util.js:80:11)
    at Connection.execute (c:\Users\User\Desktop\web-app\project\node_modules\oracledb\lib\connection.js:128:12)
    at Connection.execute (c:\Users\User\Desktop\web-app\project\node_modules\oracledb\lib\util.js:99:19)
    at doinsert (c:\Users\User\Desktop\web-app\project\backend\test.js:56:10)
[test.zip](https://github.com/oracle/node-oracledb/files/2162585/test.zip)

**Comment by cjbj** [comment]
Take a look at the [samples](https://github.com/oracle/node-oracledb/tree/master/examples) and try some one before continuing with your code.

> [,cope.name]

What's that comma doing?

And you have:

>  [,cope.name],
>       {id : {type: oracledb.NUMBER, dir: oracledb.BIND_OUT } }, // Bind values

This looks like a mix of bind-by-position and bind-by-name.  And it is two arguments. You can only pass one argument containing bind variables to `execute()`.

There are some other issues, but it's better that you do some experimentation with the examples.

**Comment by Shubhangi-yadav** [comment]
The' ,' is used for autoincrementation for user_id. Cant I use both in and out parameters at the same time?

**Comment by cjbj** [comment]
> The' ,' is used for autoincrementation for user_id

?

Regarding binding in & out, check the doc & examples :)

**Comment by Shubhangi-yadav** [comment]
I have created an auto incremented user_id on the oracle database and adding the values as in code . I wish to return the id of last inserted row .Please suggest a suitable example for doing so as i am new to both nodejs and oracle database. Individually both are working i.e. not using once the outbinding or using hardcoded data for values . But i am unable to figure out how to bind both together .
Please help.

**Comment by cjbj** [comment]
There's always a bit of a learning curve when doing something new.  You can quickly search the examples for those that have RETURNING / INTO and see what they do.  Then see how to convert them to do what you need.

**Comment by Shubhangi-yadav** [comment]
hello , I am having an error while using conn.executeMany command .Please suggest how to resolve it.
[test.zip](https://github.com/oracle/node-oracledb/files/2183521/test.zip)

**Comment by cjbj** [comment]
You uploaded the same testcase to https://github.com/oracle/node-oracledb/issues/943 so I'll assume you don't need an answer here - and I will assume I can close this.
