### ISSUE TITLE
npm install oracledb 2.3.0 fails due to in correct versioning

### ISSUE THREAD

**Issue by ramonskie** [oracle/node-oracledb#945]
the latest oracledb npm package is failing to download because of the following
the `2.3.0` version is trying to download releases with version exetensions that are used in version `2.2.0`

for example
version 2.3.0 has the following
`oracledb-v2.3.0-node-v64-linux-x64.gz`

version 2.2.0 has the following
`oracledb-v2.2.0-node-v59-linux-x64.gz`

and npm tries to donwload
`oracledb-v2.3.0-node-v59-linux-x64.gz`

notice the `node-v58`

error log:
```
oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="59")
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v59-linux-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.3.0/oracledb-v2.3.0-node-v59-linux-x64.gz failed with code 404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting
```

**Comment by cjbj** [comment]
The error shows you have Node 9 (i.e. [ABI 59](https://nodejs.org/en/download/releases/)). 

Prebuilt binaries for node-oracledb 2.3 are only available for Node 6, 8 and 10.  See https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md#node-oracledb-v230-7-jun-2018

You can upgrade Node from 9 to 10, or compile the add-on to suit your Node version.

**Comment by ramonskie** [comment]
okay but i just use the following command `npm install oracledb` you should think/expect  that the installer would check which version it should pick.

**Comment by cjbj** [comment]
It does pick.  But we don't have a presupplied binary for your version.
