### ISSUE TITLE
Binding table name

### ISSUE THREAD

**Issue by Dror-Bar** [oracle/node-oracledb#946]
Hello everyone,
I know how to bind a variable in a manner like this:

"SELECT * FROM TABLE_NAME WHERE IDENTIFIER = :first_name", ["John"]

But what I want to bind is the TABLE_NAME. Is it possible to do it? This didn't work for me:

"SELECT * FROM :table_name WHERE IDENTIFIER = 'John'", ["Employees"]

**Comment by Dror-Bar** [comment]
I see, thanks for the answer.
So this would be safe then?

let tableName = 'Employees';

if (condition) {
  tableName = 'Students';
}

"SELECT * FROM " + tableName + "WHERE NAME = 'John'",

**Comment by dmcghan** [comment]
@Dror-Bar Using a known/safe set of values is arguably even better.

Here's a variation on that theme:
```js
const oracledb = require('oracledb');
const validTables = ['emp', 'dept'];

const tableName = getTableNameFromEndUser();

if (!validTables.includes(tableName)) {
  throw new Error('Invalid table name');
}

query = 'select * from ' + tableName;
```

**Comment by Dror-Bar** [comment]
Alright, thanks for the help.
