### ISSUE TITLE
string_to_table deprecated

### ISSUE THREAD

**Issue by jpollard-cs** [oracle/node-oracledb#948]
Per https://github.com/oracle/node-oracledb/issues/137 the suggested approach is to use the provided string_to_table function which relies on the apex utilities. It appears the underlying apex util function `string_to_table` is now deprecated - is there an alternative approach?

**Comment by dmcghan** [comment]
@jpollard-cs If you're on a version of APEX where string_to_table is marked as deprecated, the recommendation is to switch to [split](https://docs.oracle.com/database/apex-18.1/AEAPI/SPLIT-Function-Signature-1.htm#GUID-3BE7FF37-E54F-4503-91B8-94F374E243E6) and [split_numbers](https://docs.oracle.com/database/apex-18.1/AEAPI/SPLIT_NUMBERS-Function.htm#AEAPI-GUID-729E046F-4E95-45DF-8B9F-5FBEA0C08DE5).

**Comment by jpollard-cs** [comment]
thanks @dmcghan that's what I figured, but wanted to double check - does it make sense to even split this out and add a separate `string_to_numeric_table` function?

**Comment by dmcghan** [comment]
Isn't that what `split_numbers` is for? Or did you want something else?

**Comment by jpollard-cs** [comment]
well I'd probably abstract the apex utils away like was done with the `string_to_table` function referenced in https://github.com/oracle/node-oracledb/issues/137 ... this function works for numbers already, but I assume that's because some automatic casting is happening and it's probably taking a performance hit

**Comment by dmcghan** [comment]
> this function works for numbers already, but I assume that's because some automatic casting is happening and it's probably taking a performance hit.

Ah, I see where you going with this. It's worth testing a `string_to_numeric_table` function to see if the optimizer can use it better. It will come down to your data, indexes, count of numbers in the string passed in, etc. If performance is an issue, check out what the optimizer is doing and see if it can be improved. If performance isn't an issue, maybe don't bother :)

**Comment by cjbj** [comment]
Closing.  @jpollard-cs ping us if there's anything to follow up.

**Comment by jpollard-cs** [comment]
Thanks @cjbj I will likely just go with a backwards compatible implementation for now, but will be sure to update if I do any further research on this
