### ISSUE TITLE
wrong error message with returning clause in 0.5

### ISSUE THREAD

**Issue by volkmarbuehringer** [oracle/node-oracledb#95]
for any error in a dml-statement with the returning clause the error message
"NJS-016 buffer is too small"
 is produced

**Comment by cjbj** [comment]
@volkmarbuehringer what's your testcase?

**Comment by cjbj** [comment]
@volkmarbuehringer never mind.  I found one.

**Comment by cjbj** [comment]
@volkmarbuehringer try node-oracledb 0.7.
