### ISSUE TITLE
Error installing v2.3.0 via NPM in Windows 10

### ISSUE THREAD

**Issue by destemidosistemas** [oracle/node-oracledb#952]
1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
A.: Node.js version: v9.8.0 (win32 x64)

2. What is your node-oracledb version?
A.: Node-oracledb version: 2.2.0 (actually)

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
A.: Oracle Client library version: 12.2.0.1.0 64-bit

4. What is your Oracle Database version?
A.: Oracle 11

5. What is your OS and version?
A.: Windows 10 Home 64-bit

6. What is your compiler version?  For example, with GCC, run `gcc --version`
A.: N/D

7. What Oracle environment variables did you set?  How *exactly* did you set them?
Only "Path" = D:\Programas\Oracle\Oracle inst client 12 64 bits\instantclient_12_2

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
Only "Path" = D:\Programas\Oracle\Oracle inst client 12 64 bits\instantclient_12_2

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
npm i oracledb --save

10. What error(s) you are seeing?
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="59")
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v59-win32-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.3.0/oracledb-v2.3.0-node-v59-win32-x64.gz failed with code 404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN ecommercePainel@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.3.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deste\AppData\Roaming\npm-cache\_logs\2018-07-26T23_56_04_216Z-debug.log

[2018-07-26T23_56_04_216Z-debug.log](https://github.com/oracle/node-oracledb/files/2233938/2018-07-26T23_56_04_216Z-debug.log)

**Comment by destemidosistemas** [comment]
I think this occured because the file https://github.com/oracle/node-oracledb/releases/download/v2.3.0/oracledb-v2.3.0-node-v59-win32-x64.gz doesn't exists. The correct file is https://github.com/oracle/node-oracledb/releases/download/v2.3.0/oracledb-v2.3.0-node-v64-win32-x64.gz.

**Comment by cjbj** [comment]
There is no pre-built binary for the obsolete Node 9.  See https://github.com/oracle/node-oracledb/issues/945#issuecomment-405855660

Let us know how you go.
