### ISSUE TITLE
Use custom proxy to download binary

### ISSUE THREAD

**Issue by jdelobel** [oracle/node-oracledb#953]
### For general questions:

At work the firewall dont authorize access to github.com.

So when i want to install oracledb:

`npm install oracledb`

I got the fallowing error:

> oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
> oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v64-win32-x64.gz
> oracledb ERR! getaddrinfo ENOTFOUND github.com github.com:443
> oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting
> 

Is ti possible to set a proxy to get this binary dependancy ?

Node version: v10.7.0 64 bits

2. What is your node-oracledb version?

2.3.0

**Comment by cjbj** [comment]
The [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html#instwin) show how to configure an http proxy.  This will improve a bit in v3, but for the moment with 2.3 you need to use proxy environment variables.  v3 will also support some authenticated proxies.

If access to GitHub is blocked totally, see [Node-oracledb Installation Without Internet Access](https://oracle.github.io/node-oracledb/INSTALL.html#offline) particularly [Installing node-oracledb without GitHub Access](https://oracle.github.io/node-oracledb/INSTALL.html#nogithubaccess).
