### ISSUE TITLE
binding parameter not work 

### ISSUE THREAD

**Issue by xeleniumz** [oracle/node-oracledb#955]
Hello node-oracle community. I found problem with binding parameter. When I was use binding parameter the result always return with 0 but when I test with raw query result is correct.

I was already recheck my variable  before query
```
{ YEAR_SEMESTER: '256020',
  SUBJECT_ID: '0',
  CLASS_ID: '12'
}
```
this is binding sql query
```
let isAnalyze = await conn.execute(
              `select count(*) AS TOTALfrom dee7402
                where start_use = :YEAR_SEMESTER
                and subject_id = :SUBJECT_ID
                and class_id = :CLASS_ID` ,{
        YEAR_SEMESTER: req.body.YEAR_SEMESTER,
        SUBJECT_ID: req.body.SUBJECT_ID, 
        CLASS_ID:  req.body.CLASS_ID,
    });
```

the result is
>   rows: [ { TOTAL: 0 } ] }

when I replace with raw query
```
let isAnalyze = await conn.execute(
              `select count(*) AS TOTALfrom dee7402
                where start_use = '256020'
                and subject_id = '0'
                and class_id = '12' `);
```
the result is
>   rows: [ { TOTAL: 524 } ] }

node version 8.9.4
oracle version instantclient-basic-linux.x64-12.2.0.1.0
OS debian 8.2
How to resolve this problem ?
Thank you

**Comment by cjbj** [comment]
Can you give us:
1. a create table statement?
2. a complete script that is runnable?

**Comment by xeleniumz** [comment]
this is table statement
```
start_use  char(6), 
subject_id char(1), 
class_id char(2)
```

this is complete script that I was test in sql developer tool and the result is correct

```
select count(*) AS TOTAL
from dee7402
where start_use = '256020'
and subject_id = '0'
and class_id = '12'
```

**Comment by cjbj** [comment]
@xeleniumz can you share a runnable javascript script?  

And don't test in SQL Developer.  Try hardcoding your query values in the same JS file so you know it is connecting to the same DB etc.

**Comment by xeleniumz** [comment]
thanks you @cjbj . I found the problem because I was send data with post and in my variable is get. This is my fault. now it's work
