### ISSUE TITLE
DPI-1010:  not connected

### ISSUE THREAD

**Issue by roshanSong** [oracle/node-oracledb#956]
```javascript
var oracledb = require("oracledb");
var dbconfig = require("./dbconfig.js");

oracledb.getConnection(
	{
		user : dbconfig.user,
		password : dbconfig.password,
		connectString : dbconfig.connectString
	}, 
	function(err, connection){
		if(err)
		{
			console.error("db has connected failed: " + err.message);
			return ;
		}

		console.log("db has connected ");

		//read one
		readOne(connection);

		doRelease(connection);
});

//read one
function readOne(connection)
{
	var sql = "select * from tp_role where role_code = :role_code";
	var params = ["0000"];
	connection.execute(sql, params, function(err, result){
		if(err)
		{
			console.error("query failed: " + err.message);
                        console.error(err);
			return ;
		}

		console.log(result);
		console.log(result.rows);
	});
}

function doRelease(connection)
{
	connection.close(function(err){
		if(err)
		{
			console.error("close db connection failed:" + err.message);
		}

		return;
	});
}
```

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
     v10.5.0 (win32 x64)
2. What is your node-oracledb version?
     2.3.0
3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
 12.2.0.1.0    64-bit   uzip instantclient-basic-windows.x64-12.2.0.1.0.zip and instantclient-sdk-windows.x64-12.2.0.1.0.zip at F:\instantclient_12_2
4. What is your Oracle Database version?
   11.2.0.3.0
5. What is your OS and version?
  Windows 7 Ultimate
6. What is your compiler version?  For example, with GCC, run `gcc --version`

7. What Oracle environment variables did you set?  How *exactly* did you set them?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
  %JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;F:\instantclient_12_2\vc14;F:\instantclient_12_2;F:\perl\site\bin;F:\perl\bin;C:\ProgramData\Oracle\Java\javapath;F:\app\roshan\product\12.1.0\dbhome_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;F:\app\roshan\product\11.2.0\client_1\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\TortoiseSVN\bin;%M2_HOME%\bin;%RED5_HOME%\boot.jar;%RED5_HOME%\lib;F:\QuickTime\QTSystem\;C:\Program Files\Darwin Streaming Server;F:\nodejs\

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
when first execute 'node myProject.js', it print 'db has connected', and finished. But execute other times, it occured error, print 'db has connected/n  query failed: DPI-1010:  not connected'.
10. What error(s) you are seeing?
  db has connected
query failed: DPI-1010: not connected
{ [Error: DPI-1010: not connected] errorNum: 0, offset: 0 }

**Comment by dmcghan** [comment]
@roshanSong You're code is not written to handle the async nature of Node.js correctly. In the callback passed to `oracledb.getConnection` you invoke `readOne` and then immediately follow that with a call to `doRelease`. This will not work. 

There are many ways to solve this problem, including correct use of callbacks, promises, async/await, etc. The easiest way to fix your code is to move the call to `doRelease` to the callback passed to `connection.execute`. This will ensure that the connection is not released prematurely.

Please see [this blog series](https://jsao.io/2017/06/how-to-get-use-and-close-a-db-connection-using-various-async-patterns/) and or [this YouTube video](https://www.youtube.com/watch?v=iAdeljxq_hs) for more details.

**Comment by roshanSong** [comment]
@anthony-tuininga  thks very much. For just learn nodejs, so don't understand async completely.But I have found it earlier,anyway thks.
