### ISSUE TITLE
createPool doesn't allow you to set poolMin and poolMax to the same

### ISSUE THREAD

**Issue by Ventis** [oracle/node-oracledb#959]
Hi,

When reading the docs, it says that Oracle recommends keeping the poolMin and poolMax of a connection pool the same. However, when I do this I get an error on creation of the pool.

```
await oracledb.createPool({
      connectionString: `${process.env.DB_HOST}:${process.env.DB_PORT}`,
      password: process.env.DB_PASSWORD,
      user: process.env.DB_USER,
      _enableStats: true,
      poolAlias: 'fooPool',
      poolMax: 24,
      poolMin: 24,
      poolIncrement: 1,
      poolTimeout: 60,
    });

```

It initializes fine when I decrease the poolMin:

```
await oracledb.createPool({
      connectionString: `${process.env.DB_HOST}:${process.env.DB_PORT}`,
      password: process.env.DB_PASSWORD,
      user: process.env.DB_USER,
      _enableStats: true,
      poolAlias: 'fooPool',
      poolMax: 24,
      poolMin: 4,
      poolIncrement: 1,
      poolTimeout: 60,
    });
```

What is your Node.js version? Is it 64-bit or 32-bit? Run version.js from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
64-bit

What is your node-oracledb version?
2.3.0

What is your Oracle client (e.g. Instant Client) version? Is it 64-bit or 32-bit? How was it installed? Where is it installed?
64-bit, it's contained within the docker image. The Dockerfile of the image used:
https://github.com/CollinEstes/docker-node-oracle/blob/8/Dockerfile

What is your Oracle Database version?
Not applicable yet, the Oracle Database is out of our management

What is your OS and version?
MacOS High Sierra 10.13.5 but in the Docker image:

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian

What is your compiler version? For example, with GCC, run gcc --version
The image is using a precompiled binary

What Oracle environment variables did you set? How exactly did you set them?
None, all should be set in the Docker image. As I understand it (looking at the Dockerfile of the image) the env vars set are:

ENV LD_LIBRARY_PATH="/opt/oracle/instantclient"
ENV OCI_HOME="/opt/oracle/instantclient"
ENV OCI_LIB_DIR="/opt/oracle/instantclient"
ENV OCI_INCLUDE_DIR="/opt/oracle/instantclient/sdk/include"
ENV OCI_VERSION=12
What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On macOS, what is in ~/lib?
In the Docker image: /opt/oracle/instantclient

What error(s) you are seeing?
```
(node:27) UnhandledPromiseRejectionWarning: Error: Error initializing db connection:
       at DBConnector.init (/app/src/server/db/oracle/DBConnector.js:34:13)
       at <anonymous>
 (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by danilohgds** [comment]
@Ventis poolIncrement must be 0 when min and max are the same value.

**Comment by danilohgds** [comment]
@cjbj  can you please add this scenario as a remark in the pool increment attribute session, I looked it over and couldn't find this documented.
This behavior can be inferred from the examples folder, however, it would help to have it explicitly mentioned in the docs.

**Comment by cjbj** [comment]
@danilohgds I'll make a note.  Good idea.  It's a common gotcha.

In fact, to reduce user frustration, the OCI session pool validation was changed to be more 'do what I mean' in 18c, so you can have `poolIncrement` > 0 when `poolMin` == `poolMax` if node-oracledb is using 18c client libraries.

**Comment by cjbj** [comment]
For future searchability of this issue, the error seen when using Oracle client 12.2 (or earlier) libraries is `ORA-24413: Invalid number of sessions specified`
