### ISSUE TITLE
CANNOT GET DATA AFTER INSER/UPDATE

### ISSUE THREAD

**Issue by LucaKIN** [oracle/node-oracledb#961]
Hey there im trying to get the updated/inserted data after UPDATE query, because i have to do another query with this response data, but im actually getting:
```
{ outBinds: undefined,
  rowsAffected: 1,
  rows: undefined,
  metaData: undefined }
```

Im using **2.3.0** node-oracledb version with **v10.8.0** NODE version and my code is : 

QUERY : 
`INSERT INTO gio.projects (code, direccion, idStatus, nombre, rules, latitude, longitude, description) VALUES (123123, null, 1, 'TEST',1, null, null, null)`

EXECUTE QUERY:
```
connection.execute(
                            queryb, [],
                            {
                                maxRows: 1000
                                , outFormat: oracledb.OBJECT
                            },
                            function (err, result) {
                            console.log("RESULT", result)
                                if (err) {
                                    doRelease(connection);
                                    return;
                                }
                            });
```

**Comment by danilohgds** [comment]
Take a look at section "14.3 DML RETURNING Bind Parameters".
That should do what u want

**Comment by LucaKIN** [comment]
Solved, ill close! thx
