### ISSUE TITLE
ORA-21700: object does not exist when using a associative array 

### ISSUE THREAD

**Issue by pickapackfr** [oracle/node-oracledb#963]
Hello everyone,

I've got an issue regarding the sample provided in this repository with associative arrays with some modifications (added a null inside the procedure body).

STEPS TO REPRODUCE : 
1- Create the following package as provided in demo.sql (simplified)
```sql
CREATE OR REPLACE PACKAGE beachpkg IS
  TYPE beachType IS TABLE OF VARCHAR2(30) INDEX BY BINARY_INTEGER;
  TYPE depthType IS TABLE OF NUMBER  INDEX BY BINARY_INTEGER;
  PROCEDURE array_in(beaches IN beachType, depths IN depthType);
END;
/
SHOW ERRORS

CREATE OR REPLACE PACKAGE BODY beachpkg IS
  -- Insert array values into a table
  PROCEDURE array_in(beaches IN beachType, depths IN depthType) IS
  BEGIN
    NULL;
  END;
END;
/
SHOW ERRORS
```

2 - Create the following fonction that request the previous stored procedure 
```javascript
var doin = function (conn, cb) {
  conn.execute(
    "BEGIN beachpkg.array_in(:beach_in, :depth_in); END;",
    {
      beach_in:
      { type : oracledb.STRING,
        dir: oracledb.BIND_IN,
        val: ["Malibu Beach", "Bondi Beach", "Waikiki Beach"] },
      depth_in:
      { type : oracledb.NUMBER,
        dir: oracledb.BIND_IN,
        val: [45, 30, 67] }
    },
    function(err) {
      if (err) {
        return cb(err, conn);
      } else {
        return cb(null, conn);
      }
    });
};
```

3 - Execute and see that it returns an empty object.
`{}`

4- Modify the stored procedure body with the following code 
```sql
FOR line IN (SELECT column_value FROM TABLE(beaches))
LOOP
       dbms_output.put_line(line.column_value);
END LOOP;
```
5 - Rexecute the javascript function et get the ORA-21700 error

NOTE THAT : 
- Associative array cannot be declared as a global type
- Nested arrays and varray cannot be bound using node-oracledb

As the target objectives is to make a select request with multiple clauses WHERE val IN (SELECT column_value FROM beaches), i didn't success to make it work with node-oracledb.

Is is there anyone that gets the same error ? and have you find the reason of that ?

Thanks.

Versions :
Node.js 9.2.0 x64
node-oracledb 2.2.0
Oracle Instant Client 12.2 latest x64
Oracle 12.2.0.1.0 x64
Windows Server 2016 x64

**Comment by dmcghan** [comment]
@pickapackfr Please see this on properly [showing code in GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/). For multi-line blocks, use three backticks instead of one (I updated your issue already).

As to your issue, this seems to be some kind of data type mismatch issue (perhaps @cjbj or @anthony-tuininga could clarify). However, the workaround is easy enough: declare some variables with the desired types and initialize them with the binds in.

```javascript
const oracledb = require('oracledb');
const config = require('./dbConfig.js');

async function runTest() {
  let conn;

  try {
    conn = await oracledb.getConnection(config);

    let result = await conn.execute(
     `declare
        l_beaches beachpkg.beachType := :beach_in;
        l_depths  beachpkg.depthType := :depth_in;
      begin 
        beachpkg.array_in(l_beaches, l_depths); 
      end;`,
      {
        beach_in: {
          type : oracledb.STRING,
          dir: oracledb.BIND_IN,
          val: ["Malibu Beach", "Bondi Beach", "Waikiki Beach"]
        },
        depth_in: {
          type : oracledb.NUMBER,
          dir: oracledb.BIND_IN,
          val: [45, 30, 67]
        }
      }
    );

    console.log(result);
  } catch (err) {
    console.error(err);
  } finally {
    if (conn) {
      try {
        await conn.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

runTest();
```

**Comment by anthony-tuininga** [comment]
@dmcghan, I tried this code with cx_Oracle as well and it appears to be a limitation in how PL/SQL handles index-by tables inside a TABLE() call. Your workaround works. And so does this. Replace this code:

```
FOR line IN (SELECT column_value FROM TABLE(beaches))
LOOP
       dbms_output.put_line(line.column_value);
END LOOP;
```

with this code:

```
FOR i in 1..beaches.count LOOP
     dbms_output.put_line(beaches(i));
END LOOP;
```

**Comment by cjbj** [comment]
A side comment: if the goal it really to insert data into database tables, then consider using [`executeMany()`](https://oracle.github.io/node-oracledb/doc/api.html#batchexecution) instead of binding arrays.

**Comment by pickapackfr** [comment]
@dmcghan Thank you for correcting my multi-line blocks. 
Your solution is working great, so thanks for that 👍 

@cjbj & @anthony-tuininga : The goal is to make a stored procedure that do this :
```
SELECT * 
FROM table 
WHERE field IN (
                  SELECT COLUMN_VALUE 
                  FROM TABLE(my_associative_array)
               )
``` 
Now imagine this with multiple associative arrays as input parameters and a cursor as output parameter.

Since your workaround works, I suggest that a sample should be added with a simple select query into the plsqlarray.js file.

Thanks again to all three of you !
