### ISSUE TITLE
NJS-054: Binary build/Release/oracledb.node was not installed.

### ISSUE THREAD

**Issue by adilharris** [oracle/node-oracledb#964]
1.What is your Node.js version? Is it 64-bit or 32-bit?

node-v8.10.0   64-bit

2.What is your node-oracledb version?

oracledb@2.3.0

3.What is your Oracle client (e.g. Instant Client) version? Is it 64-bit or 32-bit? How was it installed? Where is it installed?

instantclient-basic-linux.x64-12.1.0.1.0.zip
instantclient-sdk-linux.x64-12.1.0.1.0.zip
unzip installed     source /etc/profile
centOs6.5

4.What is your Oracle Database version?

Oracle Database 11g 11.2.0.1.0

5.What is your OS and version?

centOs6.5

6.What is your compiler version? For example, with GCC, run gcc --version

is not installed

7.What Oracle environment variables did you set? How exactly did you set them?

export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
export OCI_LIB_DIR=/opt/oracle/instantclient
export OCI_INC_DIR=/opt/oracle/instantclient/sdk/include

write in the /etc/profile and source it

8.What error(s) you are seeing?

[root@temp ExamSupervise]# npm install oracledb

> oracledb@2.3.0 install /opt/apps/ExamSupervise/node_modules/oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v57-linux-x64.gz
oracledb ERR! EACCES: permission denied, mkdir 'build'
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.3.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR! 
npm ERR! Failed at the oracledb@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-21T09_19_13_787Z-debug.log

**Comment by cjbj** [comment]
Please fill in the[ issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) - it is there for a reason.

I was able, and then unable to reproduce something like this.  Some privilege thing is preventing a [mkdir](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md).  If you can track it down, let us know.  I've added some more debugging code to the trace for 3.0.

The workaround is not to install as root.

**Comment by danilohgds** [comment]
Hello @adilharris, when opening issues please fill in the template information found here:  https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md

Your log states "permission denied mkdir build". Please make sure that you have proper writing access in other to install and compile.

**Comment by adilharris** [comment]
Thank you! The problem has been solved. replace the "oracledb.node", than be ok!
