### ISSUE TITLE
Can not bind array into parameters

### ISSUE THREAD

**Issue by purejs** [oracle/node-oracledb#969]
My issue is the same as  [https://github.com/oracle/node-oracledb/issues/137](https://github.com/oracle/node-oracledb/issues/137).

But it is closed abnormally without any useful conclusion. 

Given the mysql which is also belong to Oracle supports this, I strongly hope this feature could be implemented, which is a very common usage.

Thanks very much!

**Comment by dmcghan** [comment]
@purejs You skipped answering a bunch of questions in the new issue template. It would at least be helpful to know your database version.

Did you see [this section of the doc](https://oracle.github.io/node-oracledb/doc/api.html#sqlwherein)? 

You can bind in arrays, just not in the SQL context. I needs to be in the PL/SQL context.

Since 12c we've been able to reference locally defined types with the table operator. I've not been able to get this to work without at least compiling a package spec, but if you can do that, then this should work...

Give the following objects:
```sql
create table t (
  c number
);

-- Insert 10 rows with values 1-10
insert into t
select rownum
from dual
connect by rownum <= 10;

commit;

create or replace package my_package
as
  type number_aat is table of number
    index by pls_integer;
end;
/
```

The following should work...

```javascript
const oracledb = require('oracledb');
const config = require('./dbConfig.js');

async function runTest() {
  let conn;

  try {
    conn = await oracledb.getConnection(config);

    let result = await conn.execute(
     `declare

        l_cursor  sys_refcursor;
        l_numbers my_package.number_aat;

      begin

        l_numbers := :numbers_in;

        open :cursor 
        for
          select *
          from t
          where c in (
            select column_value
            from table(l_numbers)
          );
          
      end;`,
      {
        numbers_in: {
          type : oracledb.NUMBER,
          dir: oracledb.BIND_IN,
          val: [4, 5, 6]
        },
        cursor: {
          type: oracledb.CURSOR,
          dir: oracledb.BIND_OUT
        }
      }
    );

    while (row = await result.outBinds.cursor.getRow()) {
      console.log(row);
    }
  } catch (err) {
    console.error(err);
  } finally {
    if (conn) {
      try {
        await conn.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

runTest();
```

Granted, the wrapper code isn't ideal, but it works...

**Comment by purejs** [comment]
@dmcghan Thank you for the [doc](https://oracle.github.io/node-oracledb/doc/api.html#-147-binding-multiple-values-to-a-sql-where-in-clause), but seems only one "IN condition" can be put in the WHERE clause. If have multi conditions in the SQL how should i set the corresponding parameters? 
For example, my sql would be like this:
```sql
SELECT ... WHERE col IN ( :1, :2, :3 ) AND f1 = :4 ...
```
Another question:
If the SQL is generated by a template and how many elements would be pass in dynamically is unknown when the sql is generated, how should i make the parameter placeholder in the sql for these dynamical elements?

**Comment by dmcghan** [comment]
> seems only one "IN condition" can be put in the WHERE clause

What makes you think that? Please show us the code what you want to run and is not working for you. Better yet, create an example what we can run (as I did for you).


> If the SQL is generated by a template and how many elements would be pass in dynamically is unknown when the sql is generated, how should i make the parameter placeholder in the sql for these dynamical elements?

There are several ways to solve this problem. The best approach depends on your situation. How many values do you expect to get (min, max, average)?

Do you have to generate the SQL ahead of time, can you not generate dynamic SQL based on the inputs? 

Are you able to compile objects as part of your solution?

**Comment by purejs** [comment]
Got, for the first question,  i got a wrong thinking without trying it.
For the second question:
Yes, I have to generate the SQL ahead of time and all elements would be treated as an aggregated input like this:
```sql
SELECT ... FROM table WHERE id IN (:ids)
```
Now i've tried your method via creating a string_to_table procedure to handle the length-uncertain elements to workaround this question, it is work for me.

But if an array can be passed in the SQL with just one parameter, that would be very appreciated.

Thank you!

**Comment by danilohgds** [comment]
@anthony-tuininga @cjbj any idea what would be the changes needed to enable this in non-PL-SQL context?

**Comment by anthony-tuininga** [comment]
@dmcghan, the index-by table must be defined somewhere else (like your package) for it to be usable, unfortunately. Putting it directly in the anonymous PL/SQL block yields the error "ORA-22905: cannot access rows from a non-nested table item".

@danilohgds, in order for this to be usable in node-oracledb, we would need to establish support for objects as noted in issue #348. This code in cx_Oracle (Python interface) works fine.

```sql
create table issue_969 (
  c number
);

-- Insert 10 rows with values 1-10
insert into issue_969
select rownum
from dual
connect by rownum <= 10;

commit;

create type udt_issue_969 as table of number(9);
/
```

```python
import cx_Oracle

conn = cx_Oracle.connect("cx_Oracle/welcome@localhost/T183")

# get type named UDT_ISSUE_969 created above
objType = conn.gettype("UDT_ISSUE_969")

# create a new object and populate it with the values 3, 4 and 5
obj = objType.newobject()
obj.extend([3, 4, 5])

# perform query; this produces the three rows with ids 3, 4 and 5
cursor = conn.cursor()
for row in cursor.execute("""
        select * from issue_969
        where c in (select * from table(:tab))""", tab=obj):
    print(row)
```

The object enhancement request is on the list of much desired enhancements, but it may be a while yet, unfortunately!

**Comment by cjbj** [comment]
@purejs The node-oracledb documentation for working with multiple `IN` values is at https://oracle.github.io/node-oracledb/doc/api.html#sqlwherein  Updates are welcome.

I don't think Oracle DB will ever support binding one parameter and allowing it be handled as multiple `IN` values.

I'll close this issue; I think you have a solution.

**Comment by igor-equals** [comment]
With the ECMA6 you can do it in this way `IN ( ${naturezas.map((natureza, index) => `:param_${index}`).join(' ,')} )`. then pass the parameters like this:
`con.execute(getSql(naturezas), [...naturezas]);`

**Comment by rr-os** [comment]
An alternative way, that seems to remain performant and without creating temporary tables or objects, is to dynamically build the IN clause + bindings (as seen in similar issue/workarounds here) but use "multi-value comparison IN list" syntax which apparently has a MUCH higher theoretical limit on the  number of list items.

I have not found the official Oracle SQL reference to that, but happened upon it here: ['How to put more than 1000 values into an Oracle IN clause'](https://stackoverflow.com/a/17019130) (stackoverflow)

Simplified code :
```
let sql = "SELECT * FROM my_table WHERE (0,my_table.col) IN ( ${mx} )"; // replace ${mx} later
const inVals = ["a","b","c"]; // some LARGE array of values
const binds = {};
const inList = inVals.map((val, index) => {
	let key = `mx_${index}`;
	binds[key] = val;
	return `(0,:${key})`;
});
sql = sql.replace("${mx}", inList.join(","));
const result = await execute({ sql, binds });
```
_mind the back-ticks!_

The resulting `statement` string:
```
SELECT * FROM my_table WHERE (0,my_table.col) IN ( (0,:mx_0),(0,:mx_1),(0,:mx_2) )
```

and the resulting `binds` object:
```
{ mx_0: 'a', mx_1: 'b', mx_2: 'c'}
```

In our project use-case we do not anticipate to exceed 1000 values for the IN clause and have not seen a material performance impact. We had an equivalent query achieved with deeply nested select-from(select-from..) but was complicated and less performant.

Fragile voodoo-magic?

**Comment by cjbj** [comment]
What's the optimization plan like?  Our recent [Binding Multiple Values to a SQL WHERE IN Clause](https://oracle.github.io/node-oracledb/doc/api.html#sqlwherein) does show a way to use more than 1000 values - and it only needs one bind variable.  (And if you decide it's OK to re-use SYS.ODCIVARCHAR2LIST or SYS.ODCINUMBERLIST, you don't even need to create your own type).
