### ISSUE TITLE
Unable to bind all variables

### ISSUE THREAD

**Issue by leeadh** [oracle/node-oracledb#973]
hi, 

Am trying to use node JS for an insert. 

// simple post Employee API --> sample inserting data --> use postman to execute
router.post('/addEmployee', function (request, res) {
    var empid = request.body.empid;
    var fname = request.body.fname;
    var lname = request.body.lname;
    var email = request.body.email;
    var phonenumber = request.body.phonenumber;
    var hire_date = request.body.hire_date
    var job_id = request.body.job_id;
    var salary = request.body.salary;
    var comm_pt = request.body.comm_pt;
    var manager = request.body.manager;
    var department_id = request.body.department_id;

    addDB("INSERT INTO employees VALUES (:empid, :fname,:lname, :email, :phonenumer,TO_DATE(:hire_date,'dd-MM-yyyy'),:job_id, :salary, :comm_pt, :manager, :deparment_id)",
    [empid,"'" + fname + "'" ,  "'" + lname + "'" , "'" + email + "'"  ,  "'" + phonenumber + "'" , "'" + hire_date + "'" ,"'" + job_id + "'"  , salary , comm_pt , manager ,  department_id], 

I dunno why but its giving me a not all variablORA-01008: not all variables bound. What is happening?

**Comment by anthony-tuininga** [comment]
From what you've shown us I don't see anything obviously wrong. It would be helpful if you used DPI_DEBUG_LEVEL=16 so we can see the exact SQL that is being executed. It would also be useful if you showed us the actual node-oracledb code that is being executed. The addDB() method is not part of node-oracledb, so we can't know what it is doing to your query, if anything!

I'm not sure why you're including quotes in your bind values but that isn't necessary for binding unless you actually want quotes in the data that you are saving to the database!

**Comment by leeadh** [comment]
Hi Anthony, 

I need to include my quotes because if you look at the default sql statement for node JS:


This is my code here:

```
module.exports = function(callback) {//pass callback function and return with this
    var oracledb = require('oracledb');
    var dbConfig = require('./dbconfig.js');
    oracledb.autoCommit = true;
  
    this.addDB = function(query,callback) {
      oracledb.getConnection({
          user: dbConfig.dbuser,
          password: dbConfig.dbpassword,
          connectString: dbConfig.connectString
  
      }, function(err, connection) {
        if (err) {
          console.error(err.message);
          return callback(err);
        }
        connection.execute(query, function(err, result) {
          if (err) {
            console.error(err.message);
            doRelease(connection);
            return;
          }
          return callback(null, result)
        });
      });
  
      function doRelease(connection) {
        connection.release(function(err) {
          if (err) {
            console.error(err.message);
            return callback(err);
          }
        });
      }
    };
  };
```

**Comment by leeadh** [comment]
I managed to solve it. I used escape charaters instead. 

Thanks!

**Comment by anthony-tuininga** [comment]
So you aren't using bind variables? That leaves you open to SQL injection and is definitely not recommended!

**Comment by leeadh** [comment]
Hi Antony, I actually piped all my variable into the insert for example 

"Insert into tables values (" + varA + ")"

How is this different from the bind variables method?

**Comment by anthony-tuininga** [comment]
Hi @leeadh, you need to do something like this instead:

```javascript
connection.execute("insert into tables values (:first_bv)", [varA])
```

That passes the data directly through to the database. There is no need for quoting and no possibility of someone adding something nasty into the statement! Hope that explains things.
