### ISSUE TITLE
Question: How to handle "ORA-03135: connection lost contact" with connection pools

### ISSUE THREAD

**Issue by kevinhaeni** [oracle/node-oracledb#974]
We use a connection pool with 10 connections to connect to our database:
```
oracledb.createPool({
      poolAlias: 'default', connectString:  cs, user: user, password: pw, poolMin:  10, poolMax: 10 }).then(conpool => {
         console.log('Connection Pool created!');
      },
      err => {
         console.log('Error creating pool! Error:');
         throw err;
 });
```
This is how we execute queries from our node.js express backend:

```
public async executeQuery (sql: string, data: object, options: object): Promise<any[]> {
        try {
            const con = await oracledb.getConnection();
            try {
                console.log(sql);
                const result = await con.execute(sql, data, { outFormat: oracledb.OBJECT, ...options });

                return result.rows;
            } finally {
                con.release();
            }
        } catch (ex) {
            console.log(`database.execute exception: ${ex.message}`);
            throw ex;
        }
    }
```
In production, it happens regularly that in our execute function, the following exception occurs:

**ORA-03135: connection lost contact**

which might be due to network dropouts or something like that. I am not sure about how this is caused and how I should handle it.

From my understanding, with the new pinging mechanism, the pool should be kept healthy and `getConnection()` should always return a valid connection. Or can it be that the connection is becoming invalid in between `getConnection()` and `execute()`?

How do you suggest handling such errors? 

Our plan: Catch these ORA-03135 exceptions inside our executeQuery method and re-call it until it succeeded, or maximum POOl_MAX-times, so 10 times, since this should def. give us one new connection eventually. Is this sufficiant to solve the issue?

For my understanding: Since we always .release() the connection, regardless of whether it was a healthy or invalid one...will the pool be able to decide whether it should be re-added to the pool, or discarded and a new connection should be created and to the pool, or do we have to do that?

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Node.js 10 (x64)

2. What is your node-oracledb version? 2.3.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as? connection.execute() on a connection returned from a connectionpool

4. What error(s) you are seeing? ORA-03135: connection lost contact

5. What OS (and version) is Node.js executing on? It's some virtual linux machine in the cloud environment of our customer, I'm not sure which one

6. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed? Oracle instant client 12.2

7. What is your Oracle Database version? Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

10. Do you have a small, single Node.js script that immediately runs to show us the problem? It's not simple to reproduce since we depend on network dropouts

**Comment by anthony-tuininga** [comment]
> From my understanding, with the new pinging mechanism, the pool should be kept healthy and getConnection() should always return a valid connection. Or can it be that the connection is becoming invalid in between getConnection() and execute()?

That's a possibility. But it could also be happening in the (default) 60 seconds between pinging. See the [documentation](https://oracle.github.io/node-oracledb/doc/api.html#propdbpoolpinginterval) for more information. You could set the pool ping interval value to 0 which would perform a ping each time the connection is acquired from the pool. That incurs overhead and still doesn't guarantee anything since the dropout could occur (as you noted) between getConnection() and execute().

> Our plan: Catch these ORA-03135 exceptions inside our executeQuery method and re-call it until it succeeded, or maximum POOl_MAX-times, so 10 times, since this should def. give us one new connection eventually. Is this sufficiant to solve the issue?

That would do it. You could also set the pool ping interval to 0 to force a ping (and reset it afterwards to avoid the overhead) and therefore force the acquisition of a good connection.

Also, to be clear, ORA-3135 is one of the errors that is handled internally and which will force the connection to be dropped from the pool once it is detected.

**Comment by kevinhaeni** [comment]
Thanks @anthony. Since we are using oracleclient 12.2 and as it replaces node-oracledb's pinging mechanism, I suppose your suggestion to set ping interval to 0 isn't an option for solving our problem right?

**Comment by anthony-tuininga** [comment]
Yes, although you could try node-oracledb 3.0 (not yet released) and see if it resolves the issue for you using that technique. Version 3.0 is intended to be released relatively soon. Keep an eye on issue #933 to get a better idea of exactly when.

**Comment by cjbj** [comment]
Closing - I think this has run its course.
