### ISSUE TITLE
v. 18.3.000 and passwords uppercase problems

### ISSUE THREAD

**Issue by giagiac** [oracle/node-oracledb#978]
Unable to use oracle instant client 18.3.0.0.0 -> as i did for 12.2.0.1.0 (that's works very well) i try to download the last client but nodejs return the same error as if i don't link LD_LIBRARY_PATH right (/usr/lib/oracle/18.3/client64/lib/) 
My purpose is to use the new client and upgrande my project to the last version. Is that possible?

An other frustrating problem is : connect to oracle instance 12 and solve upper case passwords problems that now with 12.2.0.1.0 doesn't work (if i use upper case password in oracle db v.12 the client doesn't able to connect to... i suppose it make password lower at every connection... solution was change db pass flag limitation but i can't becouse i'm not the owner)

Thanks in advange Giacomo

**Comment by giagiac** [comment]
Sorry about the first question i tried hundreds times after write here -> it's my fault i was point to the wrong directory. Now i will try to use lower case and upper case password and will tell you.

**Comment by cjbj** [comment]
node-oracledb 3 (via the ODPI-C layer) will have a [fix for 18c Instant Client RPMs](https://github.com/oracle/odpi/commit/3910e19111995c5ded67521a64d740f7045acd84).  If you want it now, you can build node-oracledb from the master branch.

Haven't passwords been case sensitive since around the 11g timeframe?

**Comment by giagiac** [comment]
Haven't passwords been case sensitive since around the 11g timeframe?

I noticed, if i'm using oracle db server v.12 with oci-client 11
(downloaded from oracle) i can't use upper psw. I changed flag in the db
v12 to accept case insensitive password even if i speciped upper case
password in nodejs driver configuration. I supposed in the driver code
every password became lowercase. But i don't understand why.

Thanks bye

Il giorno mer 12 set 2018 alle ore 23:51 Christopher Jones <
notifications@github.com> ha scritto:

**Comment by cjbj** [comment]
node-oracledb doesn't change the case of passwords.  It sends whatever you enter to the DB.

**Comment by giagiac** [comment]
Thanks for your clarification, i will investigate better why i had to
change the flag in v.12DB to permit the connection...i did all the
combination (four) to connect with the node-oracledb. I will tell you!

Goodbye

Il giorno mer 19 set 2018 alle ore 12:47 Christopher Jones <
notifications@github.com> ha scritto:

**Comment by cjbj** [comment]
I'll close this.  If you have an update, let us know.
