### ISSUE TITLE
NJS-045: cannot load the oracledb add-on binary for Node.js 10.10.0

### ISSUE THREAD

**Issue by veronicacuello** [oracle/node-oracledb#979]
Got an error when trying to use the library. 
`~/src/myproject/node_modules/oracledb/lib/oracledb.js:65
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.10.0 (darwin, x64)
Node.js require() error was:
  DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help`

 I follow the instructions at https://oracle.github.io/odpi/doc/installation.html#macos and got the basic client files in `~/lib/ `and `usr/local/lib` for both the 'libclntsh' files and using the whole unzip folder. I also exported the new paths in the $PATH

Please help.

**Comment by cjbj** [comment]
Can you show an `ls` of your `~/lib` directory?  What Oracle client did you install? Do you really have the Oracle client in both `~/lib` and `/usr/local/lib`?  Try removing it from one.  Are there any directory permission issues?

**Comment by cjbj** [comment]
@orkhi Read https://oracle.github.io/odpi/doc/installation.html#windows and open a new issue if you have problems.  

This issue is about macOS.  I'm closing it due to lack of activity on that topic.
