### ISSUE TITLE
ErrorNum: 1  what does it mean?

### ISSUE THREAD

**Issue by schmitz-mauricio** [oracle/node-oracledb#982]
I'm having this feedback errorNum: 1 while performing an insert, someone knows the meaning of this return.

**Comment by schmitz-mauricio** [comment]
> What's in the rest of the Error structure? Are you seeing an ORA-0001?

All I get is this.
```{"errorNum":1,"offset":0}```

**Comment by dmcghan** [comment]
How are you logging the error? Can you show us any code?

**Comment by schmitz-mauricio** [comment]
> How are you logging the error? Can you show us any code?

My first method.
```
async function salvaQtSemestre(binds, dbConn) {
  try {
    const sql = 'INSERT INTO mytable( ' +
    '        field_1 ' +
    '      , field_2 ' +
    '      , field_3 ' +
    '      , field_4 ' +
    '  ) ' +
    '  VALUES( ' +
    '      :p_param_1 ' +
    '    , :p_param_2 ' +
    '    , 1 ' +
    '    , SYSDATE ' +
    '  ) ';
    const results = await db.executeMany(sql, binds, {}, dbConn, false);
    return results;
  } catch (e) {
    return false;
  }
}
```
with this binds: ```[{"p_param_1":"2018/2","p_param_2":192581},{"p_param_1":"2018/2","p_param_2":192585}]```

and executeMany  is this method on my error captured on connection.executeMany
```
async function executeMany(sql, bindParams, options, connection, autoCommit) {
  const sqlOriginal = sql;
  options.autoCommit = (autoCommit === undefined) ? true : autoCommit;
  options.outFormat = oracledb.OBJECT;

  return new Promise(async (resolve, reject) => {
    connection.executeMany(sql, bindParams, options, async (err, results) => {
      if (err) {
        const log = {
          err: JSON.stringify(err),
          sql,
          bindParams: JSON.stringify(bindParams),
        }
        logger.log('ORACLE EXECUTE ERROR -> executeMany', JSON.stringify(log));
        const aliveSessionErr = await checkConnection(connection);
        if (aliveSessionErr !== true) {
          const tryAgainExecute = await executeMany(
            sqlOriginal, bindParams, options, aliveSessionErr, autoCommit);
          return resolve(tryAgainExecute);
        }
        return reject(err);
      }
      if (results.rows !== undefined && results.rows.length > 0) {
        results.rows = lowerCaseRows(results.rows);
      }
      return resolve(results);
    });
  });
}
```

**Comment by dmcghan** [comment]
In your `executeMany` function, you have an error handler that JSON.stringifys `err`. What happens if you add a simple `console.log(err)` just before that? What error message do you see then?

**Comment by schmitz-mauricio** [comment]
I discovered the problem, in high amounts of requests the insert had already been performed by another request.
And this caused pk error,
Here comes the question why the library does not return native oracle errors?

**Comment by cjbj** [comment]
> Here comes the question why the library does not return native oracle errors?

It does.  Check https://oracle.github.io/node-oracledb/doc/api.html#errorobj and let us know what we can improve.

With `executeMany()` there is a [`batchErrors`](https://oracle.github.io/node-oracledb/doc/api.html#executemanyoptbatcherrors) option which may help your situation.  Also see the example https://github.com/oracle/node-oracledb/blob/master/examples/em_batcherrors_aa.js

**Comment by cjbj** [comment]
I'll close this, but feel free to continue the discussion.
