### ISSUE TITLE
[POLL] Most Wanted Enhancement - Votes needed

### ISSUE THREAD

**Issue by danilohgds** [oracle/node-oracledb#985]
Hi everyone,

Please vote which enhancement you would want the most in node-oracledb out of the ones we have in the repo.

Here is the survey link: https://www.surveymonkey.com/r/8LT889R

**Comment by cjbj** [comment]
@danilohgds do you want to share the most request feature and close this issues?

**Comment by danilohgds** [comment]
@cjbj 


Enhancement | Percentage | Count of Votes
-- | -- | --
Package OCI to simplify oracledb installation # 572 | 38,10% | 8
Support for PL/SQL record and UDT SQL types like   Oracle Spatial SDO # 147 | 23,81% | 5
Enhance bind direction and type support # 983 | 14,29% | 3
Enhance logging capabilities # 839 | 14,29% | 3
ALTER SESSION once for new session # 258 | 14,29% | 3


ps: sorry for the delay!

**Comment by cjbj** [comment]
Thanks @danilohgds.  No worries about the delay.

Now, who wants to submit some PRs?!
