### ISSUE TITLE
error while installing node-oracledb on windows 7 32-bit

### ISSUE THREAD

**Issue by AdvayThakur** [oracle/node-oracledb#986]
I am trying to install node-oraclebd using npm package. I am using windows 7 32-bit OS.
I am getting error while installing the package. I have pasted the logs below.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\702048348\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'oracledb' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose config Skipping project config: C:\Users\702048348/.npmrc. (matches userconfig)
5 verbose npm-session 180b02913cb4d780
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/oracledb 1660ms (from cache)
9 silly pacote tag manifest for oracledb@latest fetched in 1890ms
10 timing stage:loadCurrentTree Completed in 2510ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 10ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 120ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule oracledb@2.3.0 checking installable status
18 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 100ms
19 timing stage:loadIdealTree Completed in 270ms
20 silly currentTree 702048348
20 silly currentTree +-- ansi-regex@2.1.1
20 silly currentTree +-- ansi-styles@2.2.1
20 silly currentTree +-- balanced-match@1.0.0
20 silly currentTree +-- block-stream@0.0.9
20 silly currentTree +-- brace-expansion@1.1.11
20 silly currentTree +-- buffer-from@0.1.2
20 silly currentTree +-- builtins@1.0.3
20 silly currentTree +-- chalk@1.1.3
20 silly currentTree +-- commander@2.18.0
20 silly currentTree +-- concat-map@0.0.1
20 silly currentTree +-- core-util-is@1.0.2
20 silly currentTree +-- create-react-app@1.5.2
20 silly currentTree +-- cross-spawn@4.0.2
20 silly currentTree +-- debug@2.6.9
20 silly currentTree +-- duplexer2@0.0.2
20 silly currentTree +-- envinfo@3.4.2
20 silly currentTree +-- escape-string-regexp@1.0.5
20 silly currentTree +-- fs-extra@1.0.0
20 silly currentTree +-- fs.realpath@1.0.0
20 silly currentTree +-- fstream-ignore@1.0.5
20 silly currentTree +-- fstream@1.0.11
20 silly currentTree +-- glob@7.1.3
20 silly currentTree +-- graceful-fs@4.1.11
20 silly currentTree +-- has-ansi@2.0.0
20 silly currentTree +-- hyperquest@2.1.3
20 silly currentTree +-- inflight@1.0.6
20 silly currentTree +-- inherits@2.0.3
20 silly currentTree +-- isarray@0.0.1
20 silly currentTree +-- isexe@2.0.0
20 silly currentTree +-- jsonfile@2.4.0
20 silly currentTree +-- klaw@1.3.1
20 silly currentTree +-- lru-cache@4.1.3
20 silly currentTree +-- macos-release@1.1.0
20 silly currentTree +-- minimatch@3.0.4
20 silly currentTree +-- minimist@1.2.0
20 silly currentTree +-- mkdirp@0.5.1
20 silly currentTree | `-- minimist@0.0.8
20 silly currentTree +-- ms@2.0.0
20 silly currentTree +-- once@1.4.0
20 silly currentTree +-- os-name@2.0.1
20 silly currentTree +-- os-tmpdir@1.0.2
20 silly currentTree +-- path-is-absolute@1.0.1
20 silly currentTree +-- process-nextick-args@2.0.0
20 silly currentTree +-- pseudomap@1.0.2
20 silly currentTree +-- readable-stream@1.1.14
20 silly currentTree +-- rimraf@2.6.2
20 silly currentTree +-- safe-buffer@5.1.2
20 silly currentTree +-- semver@5.5.1
20 silly currentTree +-- string_decoder@0.10.31
20 silly currentTree +-- strip-ansi@3.0.1
20 silly currentTree +-- supports-color@2.0.0
20 silly currentTree +-- tar-pack@3.4.1
20 silly currentTree | +-- isarray@1.0.0
20 silly currentTree | +-- readable-stream@2.3.6
20 silly currentTree | `-- string_decoder@1.1.1
20 silly currentTree +-- tar@2.2.1
20 silly currentTree +-- through2@0.6.5
20 silly currentTree | `-- readable-stream@1.0.34
20 silly currentTree +-- tmp@0.0.31
20 silly currentTree +-- uid-number@0.0.6
20 silly currentTree +-- util-deprecate@1.0.2
20 silly currentTree +-- validate-npm-package-name@3.0.0
20 silly currentTree +-- which@1.3.1
20 silly currentTree +-- win-release@1.1.1
20 silly currentTree +-- wrappy@1.0.2
20 silly currentTree +-- xtend@4.0.1
20 silly currentTree `-- yallist@2.1.2
21 silly idealTree 702048348
21 silly idealTree +-- ansi-regex@2.1.1
21 silly idealTree +-- ansi-styles@2.2.1
21 silly idealTree +-- balanced-match@1.0.0
21 silly idealTree +-- block-stream@0.0.9
21 silly idealTree +-- brace-expansion@1.1.11
21 silly idealTree +-- buffer-from@0.1.2
21 silly idealTree +-- builtins@1.0.3
21 silly idealTree +-- chalk@1.1.3
21 silly idealTree +-- commander@2.18.0
21 silly idealTree +-- concat-map@0.0.1
21 silly idealTree +-- core-util-is@1.0.2
21 silly idealTree +-- create-react-app@1.5.2
21 silly idealTree +-- cross-spawn@4.0.2
21 silly idealTree +-- debug@2.6.9
21 silly idealTree +-- duplexer2@0.0.2
21 silly idealTree +-- envinfo@3.4.2
21 silly idealTree +-- escape-string-regexp@1.0.5
21 silly idealTree +-- fs-extra@1.0.0
21 silly idealTree +-- fs.realpath@1.0.0
21 silly idealTree +-- fstream-ignore@1.0.5
21 silly idealTree +-- fstream@1.0.11
21 silly idealTree +-- glob@7.1.3
21 silly idealTree +-- graceful-fs@4.1.11
21 silly idealTree +-- has-ansi@2.0.0
21 silly idealTree +-- hyperquest@2.1.3
21 silly idealTree +-- inflight@1.0.6
21 silly idealTree +-- inherits@2.0.3
21 silly idealTree +-- isarray@0.0.1
21 silly idealTree +-- isexe@2.0.0
21 silly idealTree +-- jsonfile@2.4.0
21 silly idealTree +-- klaw@1.3.1
21 silly idealTree +-- lru-cache@4.1.3
21 silly idealTree +-- macos-release@1.1.0
21 silly idealTree +-- minimatch@3.0.4
21 silly idealTree +-- minimist@1.2.0
21 silly idealTree +-- mkdirp@0.5.1
21 silly idealTree | `-- minimist@0.0.8
21 silly idealTree +-- ms@2.0.0
21 silly idealTree +-- once@1.4.0
21 silly idealTree +-- oracledb@2.3.0
21 silly idealTree +-- os-name@2.0.1
21 silly idealTree +-- os-tmpdir@1.0.2
21 silly idealTree +-- path-is-absolute@1.0.1
21 silly idealTree +-- process-nextick-args@2.0.0
21 silly idealTree +-- pseudomap@1.0.2
21 silly idealTree +-- readable-stream@1.1.14
21 silly idealTree +-- rimraf@2.6.2
21 silly idealTree +-- safe-buffer@5.1.2
21 silly idealTree +-- semver@5.5.1
21 silly idealTree +-- string_decoder@0.10.31
21 silly idealTree +-- strip-ansi@3.0.1
21 silly idealTree +-- supports-color@2.0.0
21 silly idealTree +-- tar-pack@3.4.1
21 silly idealTree | +-- isarray@1.0.0
21 silly idealTree | +-- readable-stream@2.3.6
21 silly idealTree | `-- string_decoder@1.1.1
21 silly idealTree +-- tar@2.2.1
21 silly idealTree +-- through2@0.6.5
21 silly idealTree | `-- readable-stream@1.0.34
21 silly idealTree +-- tmp@0.0.31
21 silly idealTree +-- uid-number@0.0.6
21 silly idealTree +-- util-deprecate@1.0.2
21 silly idealTree +-- validate-npm-package-name@3.0.0
21 silly idealTree +-- which@1.3.1
21 silly idealTree +-- win-release@1.1.1
21 silly idealTree +-- wrappy@1.0.2
21 silly idealTree +-- xtend@4.0.1
21 silly idealTree `-- yallist@2.1.2
22 silly install generateActionsToTake
23 timing stage:generateActionsToTake Completed in 10ms
24 silly diffTrees action count 1
25 silly diffTrees add oracledb@2.3.0
26 silly decomposeActions action count 8
27 silly decomposeActions fetch oracledb@2.3.0
28 silly decomposeActions extract oracledb@2.3.0
29 silly decomposeActions preinstall oracledb@2.3.0
30 silly decomposeActions build oracledb@2.3.0
31 silly decomposeActions install oracledb@2.3.0
32 silly decomposeActions postinstall oracledb@2.3.0
33 silly decomposeActions finalize oracledb@2.3.0
34 silly decomposeActions refresh-package-json oracledb@2.3.0
35 silly install executeActions
36 silly doSerial global-install 8
37 verbose correctMkdir C:\Users\702048348\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
38 timing audit compress Completed in 10ms
39 info audit Submitting payload of 4317bytes
40 verbose lock using C:\Users\702048348\AppData\Roaming\npm-cache\_locks\staging-57326a08689e2e1f.lock for C:\Users\702048348\node_modules\.staging
41 silly doParallel extract 1
42 silly extract oracledb@2.3.0
43 silly tarball trying oracledb@latest by hash: sha512-zTG1elqQ3kdGiu93OcWYje3YCFO2kfLBTC1KjEyxIck8gnH9H2vAqrE5AgPdPmColIf961g3KwwxcwlEnX0CpA==
44 silly extract oracledb@latest extracted to C:\Users\702048348\node_modules\.staging\oracledb-8be1a296 (800ms)
45 timing action:extract Completed in 810ms
46 silly doReverseSerial unbuild 8
47 silly doSerial remove 8
48 silly doSerial move 8
49 silly doSerial finalize 8
50 silly finalize C:\Users\702048348\node_modules\oracledb
51 timing action:finalize Completed in 10ms
52 silly doParallel refresh-package-json 1
53 silly refresh-package-json C:\Users\702048348\node_modules\oracledb
54 timing action:refresh-package-json Completed in 180ms
55 silly doParallel preinstall 1
56 silly preinstall oracledb@2.3.0
57 info lifecycle oracledb@2.3.0~preinstall: oracledb@2.3.0
58 timing action:preinstall Completed in 10ms
59 silly doSerial build 8
60 silly build oracledb@2.3.0
61 info linkStuff oracledb@2.3.0
62 silly linkStuff oracledb@2.3.0 has C:\Users\702048348\node_modules as its parent node_modules
63 timing action:build Completed in 0ms
64 silly doSerial global-link 8
65 silly doParallel update-linked 0
66 silly doSerial install 8
67 silly install oracledb@2.3.0
68 info lifecycle oracledb@2.3.0~install: oracledb@2.3.0
69 verbose lifecycle oracledb@2.3.0~install: unsafe-perm in lifecycle true
70 verbose lifecycle oracledb@2.3.0~install: PATH: C:\Users\702048348\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\702048348\node_modules\oracledb\node_modules\.bin;C:\Users\702048348\node_modules\.bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\bin;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\Library\bin;C:\ProgramData\Anaconda2\Scripts;C:\Informatica\9.6.1\clients\tools\datadirect;C:\Informatica\9.6.1\clients\tools\odbcdrv;C:\Informatica\9.6.1\clients\tools\jdbcdrv;C:\Program Files\Oracle\OraClient10g_home1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\ActivIdentity\ActivClient\;C:\Program Files\Windows Imaging\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Application Virtualization Client;C:\Program Files\nodejs\;C:\Users\702048348\AppData\Roaming\npm
71 verbose lifecycle oracledb@2.3.0~install: CWD: C:\Users\702048348\node_modules\oracledb
72 silly lifecycle oracledb@2.3.0~install: Args: [ '/d /s /c', 'node package/oracledbinstall.js' ]
73 timing audit submit Completed in 2550ms
74 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 2620ms
75 timing audit body Completed in 70ms
76 silly lifecycle oracledb@2.3.0~install: Returned: code: 87  signal: null
77 info lifecycle oracledb@2.3.0~install: Failed to exec install script
78 timing action:install Completed in 2340ms
79 verbose unlock done using C:\Users\702048348\AppData\Roaming\npm-cache\_locks\staging-57326a08689e2e1f.lock for C:\Users\702048348\node_modules\.staging
80 timing stage:rollbackFailedOptional Completed in 60ms
81 timing stage:runTopLevelLifecycles Completed in 7300ms
82 silly saveTree 702048348
82 silly saveTree +-- ansi-regex@2.1.1
82 silly saveTree +-- ansi-styles@2.2.1
82 silly saveTree +-- balanced-match@1.0.0
82 silly saveTree +-- block-stream@0.0.9
82 silly saveTree | `-- inherits@2.0.3
82 silly saveTree +-- brace-expansion@1.1.11
82 silly saveTree | `-- concat-map@0.0.1
82 silly saveTree +-- buffer-from@0.1.2
82 silly saveTree +-- builtins@1.0.3
82 silly saveTree +-- chalk@1.1.3
82 silly saveTree | +-- escape-string-regexp@1.0.5
82 silly saveTree | +-- has-ansi@2.0.0
82 silly saveTree | +-- strip-ansi@3.0.1
82 silly saveTree | `-- supports-color@2.0.0
82 silly saveTree +-- commander@2.18.0
82 silly saveTree +-- concat-map@0.0.1
82 silly saveTree +-- core-util-is@1.0.2
82 silly saveTree +-- create-react-app@1.5.2
82 silly saveTree | +-- cross-spawn@4.0.2
82 silly saveTree | | +-- lru-cache@4.1.3
82 silly saveTree | | | +-- pseudomap@1.0.2
82 silly saveTree | | | `-- yallist@2.1.2
82 silly saveTree | | `-- which@1.3.1
82 silly saveTree | |   `-- isexe@2.0.0
82 silly saveTree | +-- envinfo@3.4.2
82 silly saveTree | | +-- minimist@1.2.0
82 silly saveTree | | `-- os-name@2.0.1
82 silly saveTree | |   +-- macos-release@1.1.0
82 silly saveTree | |   `-- win-release@1.1.1
82 silly saveTree | |     `-- semver@5.5.1
82 silly saveTree | +-- fs-extra@1.0.0
82 silly saveTree | | +-- graceful-fs@4.1.11
82 silly saveTree | | +-- jsonfile@2.4.0
82 silly saveTree | | `-- klaw@1.3.1
82 silly saveTree | +-- hyperquest@2.1.3
82 silly saveTree | | +-- duplexer2@0.0.2
82 silly saveTree | | | `-- readable-stream@1.1.14
82 silly saveTree | | |   +-- isarray@0.0.1
82 silly saveTree | | |   `-- string_decoder@0.10.31
82 silly saveTree | | `-- through2@0.6.5
82 silly saveTree | |   +-- readable-stream@1.0.34
82 silly saveTree | |   `-- xtend@4.0.1
82 silly saveTree | +-- semver@5.5.1
82 silly saveTree | +-- tar-pack@3.4.1
82 silly saveTree | | +-- debug@2.6.9
82 silly saveTree | | | `-- ms@2.0.0
82 silly saveTree | | +-- fstream-ignore@1.0.5
82 silly saveTree | | | +-- fstream@1.0.11
82 silly saveTree | | | | +-- mkdirp@0.5.1
82 silly saveTree | | | | | `-- minimist@0.0.8
82 silly saveTree | | | | `-- rimraf@2.6.2
82 silly saveTree | | | |   `-- glob@7.1.3
82 silly saveTree | | | |     +-- fs.realpath@1.0.0
82 silly saveTree | | | |     +-- inflight@1.0.6
82 silly saveTree | | | |     | +-- once@1.4.0
82 silly saveTree | | | |     | | `-- wrappy@1.0.2
82 silly saveTree | | | |     | `-- wrappy@1.0.2
82 silly saveTree | | | |     +-- minimatch@3.0.4
82 silly saveTree | | | |     +-- once@1.4.0
82 silly saveTree | | | |     `-- path-is-absolute@1.0.1
82 silly saveTree | | | `-- minimatch@3.0.4
82 silly saveTree | | +-- fstream@1.0.11
82 silly saveTree | | +-- once@1.4.0
82 silly saveTree | | +-- readable-stream@2.3.6
82 silly saveTree | | | +-- isarray@1.0.0
82 silly saveTree | | | +-- process-nextick-args@2.0.0
82 silly saveTree | | | +-- safe-buffer@5.1.2
82 silly saveTree | | | +-- string_decoder@1.1.1
82 silly saveTree | | | `-- util-deprecate@1.0.2
82 silly saveTree | | +-- rimraf@2.6.2
82 silly saveTree | | +-- tar@2.2.1
82 silly saveTree | | `-- uid-number@0.0.6
82 silly saveTree | +-- tmp@0.0.31
82 silly saveTree | | `-- os-tmpdir@1.0.2
82 silly saveTree | `-- validate-npm-package-name@3.0.0
82 silly saveTree +-- cross-spawn@4.0.2
82 silly saveTree +-- debug@2.6.9
82 silly saveTree +-- duplexer2@0.0.2
82 silly saveTree +-- envinfo@3.4.2
82 silly saveTree +-- escape-string-regexp@1.0.5
82 silly saveTree +-- fs-extra@1.0.0
82 silly saveTree +-- fs.realpath@1.0.0
82 silly saveTree +-- fstream-ignore@1.0.5
82 silly saveTree +-- fstream@1.0.11
82 silly saveTree +-- glob@7.1.3
82 silly saveTree +-- graceful-fs@4.1.11
82 silly saveTree +-- has-ansi@2.0.0
82 silly saveTree +-- hyperquest@2.1.3
82 silly saveTree +-- inflight@1.0.6
82 silly saveTree +-- inherits@2.0.3
82 silly saveTree +-- isarray@0.0.1
82 silly saveTree +-- isexe@2.0.0
82 silly saveTree +-- jsonfile@2.4.0
82 silly saveTree +-- klaw@1.3.1
82 silly saveTree +-- lru-cache@4.1.3
82 silly saveTree +-- macos-release@1.1.0
82 silly saveTree +-- minimatch@3.0.4
82 silly saveTree +-- minimist@1.2.0
82 silly saveTree +-- mkdirp@0.5.1
82 silly saveTree +-- ms@2.0.0
82 silly saveTree +-- once@1.4.0
82 silly saveTree +-- oracledb@2.3.0
82 silly saveTree +-- os-name@2.0.1
82 silly saveTree +-- os-tmpdir@1.0.2
82 silly saveTree +-- path-is-absolute@1.0.1
82 silly saveTree +-- process-nextick-args@2.0.0
82 silly saveTree +-- pseudomap@1.0.2
82 silly saveTree +-- readable-stream@1.1.14
82 silly saveTree +-- rimraf@2.6.2
82 silly saveTree +-- safe-buffer@5.1.2
82 silly saveTree +-- semver@5.5.1
82 silly saveTree +-- string_decoder@0.10.31
82 silly saveTree +-- strip-ansi@3.0.1
82 silly saveTree +-- supports-color@2.0.0
82 silly saveTree +-- tar-pack@3.4.1
82 silly saveTree +-- tar@2.2.1
82 silly saveTree +-- through2@0.6.5
82 silly saveTree +-- tmp@0.0.31
82 silly saveTree +-- uid-number@0.0.6
82 silly saveTree +-- util-deprecate@1.0.2
82 silly saveTree +-- validate-npm-package-name@3.0.0
82 silly saveTree +-- which@1.3.1
82 silly saveTree +-- win-release@1.1.1
82 silly saveTree +-- wrappy@1.0.2
82 silly saveTree +-- xtend@4.0.1
82 silly saveTree `-- yallist@2.1.2
83 warn enoent ENOENT: no such file or directory, open 'C:\Users\702048348\package.json'
84 verbose enoent This is related to npm not being able to find a file.
85 warn 702048348 No description
86 warn 702048348 No repository field.
87 warn 702048348 No README data
88 warn 702048348 No license field.
89 verbose stack Error: oracledb@2.3.0 install: `node package/oracledbinstall.js`
89 verbose stack Exit status 87
89 verbose stack     at EventEmitter.<anonymous> (C:\Users\702048348\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
89 verbose stack     at emitTwo (events.js:126:13)
89 verbose stack     at EventEmitter.emit (events.js:214:7)
89 verbose stack     at ChildProcess.<anonymous> (C:\Users\702048348\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
89 verbose stack     at emitTwo (events.js:126:13)
89 verbose stack     at ChildProcess.emit (events.js:214:7)
89 verbose stack     at maybeClose (internal/child_process.js:915:16)
89 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
90 verbose pkgid oracledb@2.3.0
91 verbose cwd C:\Users\702048348
92 verbose Windows_NT 6.1.7601
93 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\702048348\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
94 verbose node v8.12.0
95 verbose npm  v6.4.1
96 error code ELIFECYCLE
97 error errno 87
98 error oracledb@2.3.0 install: `node package/oracledbinstall.js`
98 error Exit status 87
99 error Failed at the oracledb@2.3.0 install script.
99 error This is probably not a problem with npm. There is likely additional logging output above.
100 verbose exit [ 87, true ]

**Comment by cjbj** [comment]
Take a step back.  Read the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html) and make sure you have all the pre-requisites including an 11.2 or later Oracle client (you appear to only have 10g in PATH).  If you want to use our pre-built binaries you need a 64-bit version of Node.js.  Then try an 'npm install oracledb'.

**Comment by AdvayThakur** [comment]
thanks very much. It worked. I did fresh installation with only oracle instant client and then node-oracledb.
