### ISSUE TITLE
Question why getting Error: NJS-046: poolAlias "xxxPool" already exists in the connection pool cache

### ISSUE THREAD

**Issue by rstor1** [oracle/node-oracledb#987]
#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js

Node.js version: 6.9.1, 64-bit

2. What is your node-oracledb version?

Node-oracledb version: 2.3.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

npm run start

4. What error(s) you are seeing?
![screen shot 2018-10-01 at 3 14 13 pm](https://user-images.githubusercontent.com/43070937/46310338-10ef9f00-c58d-11e8-8434-9dc3c66b1f0a.png)

5. What OS (and version) is Node.js executing on?

MacOS version: 10.13.6

6. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

![screen shot 2018-10-01 at 3 04 34 pm](https://user-images.githubusercontent.com/43070937/46309760-5743fe80-c58b-11e8-9a3c-1f4d1c41cf15.png)

7. What is your Oracle Database version?

I am not sure, I just tried to use this guide: https://oracle.github.io/node-oracledb/INSTALL.html#instosx and although the app runs and I can debug, I get the error above.

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

<img width="214" alt="screen shot 2018-10-01 at 3 00 18 pm" src="https://user-images.githubusercontent.com/43070937/46309580-b8b79d80-c58a-11e8-9191-27a8c4623127.png">

9. What Oracle environment variables did you set?  How *exactly* did you set them?

I am not sure exactly 

10. Do you have a small, single Node.js script that immediately runs to show us the problem?
Unfortunately no but here is some code:

Top of my oracle.js file with create pool function (code formatting not working here for me so using screenshot):
![screen shot 2018-10-01 at 3 39 21 pm](https://user-images.githubusercontent.com/43070937/46311440-329e5580-c590-11e8-8dfd-26edc410bce7.png)

Connect:
`  connect() {

    var connAttrs = (this.creds.poolAlias) ? this.creds.poolAlias : this.creds;

    return oracledb.getConnection(connAttrs)
      .catch((err) => {

        debug('connect failed');
        if (_.isUndefined(this.creds.poolAlias)) {
          throw new Error(err);
        }
        else {
          return this._catchPoolErr(err, this.creds.poolAlias)
            .then(() => {
              this.connect();
            });
        }
      });

  },`

Try to createPool if does not exist:
`  _catchPoolErr(err, poolAlias) {

    // connection pool not found. create and reconnect  
    if (err.toString().match('NJS-047')) {
      debug(`connection pool ${poolAlias} not found. Will request creation`);
      return this.createPool(poolAlias);
    }
    else {
      throw new Error(err);
    }
  }`

**Comment by dmcghan** [comment]
@rstor1 The way you've written the code, you don't create the pool until a connection request is made. But what happens if two connection requests are made at the same time? That's probably what's leading to the error.

I tend to avoid this alltogether by creating the pool first, just get that out of the way, and then open up the other parts of the app that would service requests. I show how to do this with REST APIs here:
https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/

It's off topic, but I'm curious, why do you throw a new error
```js
throw new Error(err);
```

instead of just throwing the existing error?
```js
throw err;
```

**Comment by rstor1** [comment]
@dmcghan thanks for the feeback, will look into this! To answer your question about the error throwing, I did not write this code, I am helping maintaining and debug an existing service so I am not sure why the decision on throwing the `new` error. That could be another possible improvement though thanks!

**Comment by rstor1** [comment]
@cjbj thanks for pointing me to the right examples!
