### ISSUE TITLE
PLS-00306: wrong number or types of arguments in call to 'TESTPROC'

### ISSUE THREAD

**Issue by Deepanjali-Patole** [oracle/node-oracledb#990]
We created a test Procedure like below:
CREATE OR REPLACE PROCEDURE DART_CTL_110.testProc(inputno in number, IN_pl_array IN array_pl,OUT_pl_array OUT array_pl)
IS
no number(4);

BEGIN
--OUT_pl_array := NEW array_pl ();
--IN_pl_array :=NEW array_pl ();

no:= 1;
DBMS_OUTPUT.PUT_LINE(inputno);
OUT_pl_array :=IN_pl_array;
   
END;
/

Now we are using node-oracledb to call this procedure like below:
  connection.execute(
           
            "BEGIN testproc(:no,:inPL,:outPL); END;",
            {
              no:
              { 
                type: oracledb.NUMBER,
                dir: oracledb.BIND_IN,
                val:1
            },

              inPL:{ 
                type: oracledb.STRING,
                dir: oracledb.BIND_IN,
                val: ['SI','AB']
            },
            outPL:{ 
              dir: oracledb.BIND_OUT, 
              type: oracledb.STRING,
              maxArraySize: 1000
            }              
            },
            //running code sample end

            function (err, result) {
              if (err) { console.error(err); return; }
              console.log(result.rows);
            });

We are getting the below issue....

**Error: ORA-06550: line 1, column 7:

PLS-00306: wrong number or types of arguments in call to 'TESTPROC'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored errorNum: 6550, offset: 6 }
Error: ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'TESTPROC'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored**

Please help...Thanks in advance

**Comment by cjbj** [comment]
Please show all the SQL & PL/SQL needed to understand your problem.  We can't guess what you are doing!

**Comment by anthony-tuininga** [comment]
You need to show how array_pl is defined. If it is a PL/SQL index-by table it should work, but if it is a type created by "create or replace type" then it won't work (not supported yet). Please also show the complete node-oracledb script as requested by Chris.
