### ISSUE TITLE
Q: Will any open transaction always be rolled back when connection is closed?

### ISSUE THREAD

**Issue by cemremengu** [oracle/node-oracledb#993]
From the `insert2.js` example:

> DESCRIPTION
    Show the auto commit behavior.
    By default, node-oracledb does not commit on execute.
    The driver also has commit() and rollback() methods to explicitly control transactions.
    Note: when a connection is closed, any open transaction will be rolled back.

Does the `Note` section here apply to all cases or only when auto commit is specified? I mean on any error, will it be enough to just close the connection for rolling back?

**Comment by cemremengu** [comment]
Answer is YES 😄 
From the docs: `When a connection is released, any ongoing transaction on the connection is rolled back.`

Sorry for spamming.

**Comment by cjbj** [comment]
I'll tweak that example comment.

The code that does the rollback is https://github.com/oracle/odpi/blob/v3.0.0/src/dpiConn.c#L92-L104
