### ISSUE TITLE
node oracledb error. Fed up with this module.

### ISSUE THREAD

**Issue by siddharthzend** [oracle/node-oracledb#994]
Anyone have any regarding the attachment?

![error](https://user-images.githubusercontent.com/5739229/46807369-62670d80-cd87-11e8-9962-4752555ce74e.png)

**Comment by dmcghan** [comment]
Likely a proxy issue. Have you tried setting the `http_proxy` and `https_proxy` environment variables? 

```bash
set http_proxy=http://my-proxy.example.com:80/
set https_proxy=http://my-proxy.example.com:80/
```

The latest version should also pick up on the npm config for those too.

**Comment by danilohgds** [comment]
Have you tried the following? 

npm config set strict-ssl false

**Comment by cjbj** [comment]
I assume the solutions have resolved the problem.
