### ISSUE TITLE
ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by rstor1** [oracle/node-oracledb#996]
#### Answer the following questions:

**Note:** I did search in the issues prior to creating a question, but did not find what I was looking for.

1. What is your Node.js version?  Is it 64-bit or 32-bit? 

**6.9.1**

2. What is your node-oracledb version?

**1.11.0**

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

**npm run start**

4. What error(s) you are seeing?

**ORA-12154: TNS:could not resolve the connect identifier specified**

5. What OS (and version) is Node.js executing on?

**MacOS 10.13.6**

6. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

**Instantclient 12.2 64 bit installed by zip, located /opt/oracle/instantclient_12_2**

7. What is your Oracle Database version?

**Not installed**

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`? 

**In lib folder:** 
![in lib](https://user-images.githubusercontent.com/43070937/47175373-f03f7d00-d2e0-11e8-8013-f5d2781d1e77.png)

9. What Oracle environment variables did you set?  How *exactly* did you set them?

**This might be where I am stuck at because I followed the installation instructions starting from section 3.5 Node-oracledb Installation on macOS and I believe I did it correctly but I keep seeing ORACLE_HOME environment variable in other issues but the install instructions do not mention ORACLE_HOME so I was assuming it was implying the full path /opt/oracle/instantclient_12_2**

**And I think I have my tnsnames.ora file in the right place. The tnsnames.ora is well formatted as well.**

<img width="505" alt="tns location" src="https://user-images.githubusercontent.com/43070937/47175848-2c271200-d2e2-11e8-989d-90efc383a599.png">

**Instantclient_12_2 contents and location**

![instantclient contents](https://user-images.githubusercontent.com/43070937/47236184-57c0ff80-d3a9-11e8-9bf5-57fb3cf33654.png)

**What is in the getConnection():**

![screen shot 2018-10-18 at 3 56 43 pm](https://user-images.githubusercontent.com/43070937/47180451-9e055880-d2ee-11e8-8c0d-3ef94d1eafcf.png)

10. Do you have a small, single Node.js script that immediately runs to show us the problem?

**No**

**Comment by dmcghan** [comment]
@rstor1 Try pointing the TNS_ADMIN environment variable to the directory that contains your tnsnames.ora file. 

`export TNS_ADMIN=/opt/oracle/instantclient_12_2/network/admin`

**Comment by cjbj** [comment]
TNS_ADMIN isn't needed if you put the files in the network/admin subdir of the Instant Client directory since that is a default location, and also why that directory is now precreated in 18.3 Instant Client.

**Comment by dmcghan** [comment]
@cjbj Ah, makes sense.

@rstor1 According to what @cjbj said, that line wouldn't help you anyway (but it is a terminal command, meant to be run prior to executing your Node.js application).

Looking at the code you added to your question (please add new stuff to new comments), I'm not sure what's going on. Here are some questions:

1. What does `this.creds` look like?
2. When is `this.creds.poolAlias` set?
3. Why throw an error if `this.creds.poolAlias` doesn't have a value (pointing back to question 2)? Just because `this.creds.poolAlias` is `undefined` doesn't mean that `err` has a value (other than null).

I suggest you simplify things a bit. Start with this till you get things working:

```javascript
const oracledb = require('oracledb');
const config = {
  user: 'hr',
  password: 'oracle',
  connectString: 'localhost/xe'
};

async function runTest() {
  let conn;

  try {
    conn = await oracledb.getConnection(config);

    let result = await conn.execute(
      'select 'hello world' from dual'
    );

    console.log(result);
  } catch (err) {
    console.error(err);
  } finally {
    if (conn) {
      try {
        await conn.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

runTest();
```

Once that works, switch it to a tnsnames.ora. Once that's working move back to your code.

**Comment by rstor1** [comment]
@cjbj @dmcghan Turns out the culprit was the extra instantclient folder I had that was conflicting. During setup, I forgot it was there and discovered it creating this issue/question. Sorry for taking up precious time and thanks for being my rubber ducky!

**Comment by rstor1** [comment]
@dmcghan @cjbj  sorry, this actually is not working finally. i found some commented code that i uncommented and now back to the same error. I have re-installed instant client to try again. I should state that I do not have an oracle DB installed locally. Do I need this to be connecting to a remote oracle DB? If so, I have to wait until oracle gives me access to its cloud oracle linux package. I also need this locally to try the simplified test @dmcghan was suggesting. If I do not need it, the question remains as to why the error. I have updated some screenshots to show the contents of instantclient and the lib folder.

**Comment by dmcghan** [comment]
@rstor1 While waiting to run that test case, you could run another. Download SQL Developer and use [the answer here](https://stackoverflow.com/questions/2019230/use-tnsnames-ora-in-oracle-sql-developer) to test the tnsnames.ora file with that.

**Comment by cjbj** [comment]
Generally it's better to test SQL*Plus which uses Oracle Call Interface (OCI) APIs just like node-oracledb does whereas SQL Dev uses JDBC.  It's also easier to install SQL*Plus using the Instant Client packages :)

I don't get whether a tnsnames.ora file is really needed.  You could try other forms, e.g. https://oracle.github.io/node-oracledb/doc/api.html#embedtns

**Comment by rstor1** [comment]
@cjbj @dmcghan ok gonna close this, you guys have helped out tremendously and think I have plenty to go off of to troubleshoot this. Thanks again!

**Comment by rstor1** [comment]
@dmcghan @cjbj thanks again! I think I have enough to go on to troubleshoot on.

**Comment by rstor1** [comment]
@dmcghan ok so the connection works using SQL Developer and my tnsnames.ora file. If it works with this, shouldn't it be working in the app then?

**Comment by rstor1** [comment]
@cjbj awesome, it works when I embed the connection string and login info as you suggested. There is obviously something up with the timing of when the creds are being initialized and the `getConnection()` is being called. The weird thing is, what I still have to figure out on my end, is why this happens only locally on my machine but not on the server where the app is running.
